import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_53 = [
  ["akashi", "Akashi", "Whisky"], ["blue-moon", "Blue Moon", "Beer"],
  ["budweiser", "Budweiser", "Beer"], ["captain-morgan", "Captain Morgan", "Rum"],
  ["carlsberg", "Carlsberg", "Beer"], ["clase-azul", "Clase Azul", "Tequila"],
  ["glengrant", "The Glen Grant", "Single Malt"], ["hardys", "Hardys", "Wine"],
  ["jura", "Jura", "Single Malt"], ["louis-jadot", "Louis Jadot", "Wine"],
  ["nikka", "Nikka", "Whisky"], ["gekkeikan", "Gekkeikan", "Sake"],
  ["gato-negro", "Gato Negro", "Wine"], ["geist", "Geist", "Beer"],
  ["pasqua", "Pasqua", "Wine"], ["b-and-g", "Barton & Guestier", "Wine"],
  ["19-crimes", "19 Crimes", "Wine"], ["baileys", "Baileys", "Liqueur"],
  ["black-and-white", "Black & White", "Whisky"], ["blenders-pride", "Blenders Pride", "Whisky"],
  ["cotswolds", "Cotswolds", "Spirits"], ["don-julio", "Don Julio", "Tequila"],
  ["flor-de-cana", "Flor de Caña", "Rum"], ["grants", "Grant's", "Whisky"],
  ["jameson", "Jameson", "Whiskey"], ["jose-cuervo", "Jose Cuervo", "Tequila"],
  ["kendall-jackson", "Kendall-Jackson", "Wine"], ["krsma", "KRSMA", "Wine"],
  ["m-chapoutier", "M. Chapoutier", "Wine"], ["moet-and-chandon", "Moët & Chandon", "Champagne"],
] as const;

// Research references remain internal and are never rendered in customer copy.
export const BRAND_SOURCES_BATCH_53: Record<string, string[]> = {
  akashi: ["https://www.ei-sake.jp/en/whisky.html", "https://shop.ei-sake.jp/view/item/000000000112", "https://shop.ei-sake.jp/view/item/000000000034"],
  "blue-moon": ["https://www.bluemoonbrewingcompany.com/en-US/training/history"],
  budweiser: ["https://www.anheuser-busch.com/newsroom/fifth-generation-brewmaster-and-five-other-budweiser-brewing-experts-spotlighted-in-new-track-your-bud-tv-campaign"],
  "captain-morgan": ["https://www.captainmorgan.com/en-us/products/captain-morgan-original-spiced-rum"],
  carlsberg: ["https://www.carlsberg.com/en-gb/curiosity/"],
  "clase-azul": ["https://jobs.claseazul.com/content/OUR-ESSENCE/?locale=en_US", "https://www.grandcruwijnen.nl/en/amfile/file/download/file/W185Wj3mrEnC3gJgmpFBmeRswkNwtWIS/product/10844/"],
  glengrant: ["https://www.theglengrant.com/our-story/"],
  hardys: ["https://hardyswines.com/pages/us-canada"],
  jura: ["https://www.jurawhisky.com/en-us/distillery/"],
  "louis-jadot": ["https://lovejadot.com/about-louis-jadot/"],
  nikka: ["https://www.nikka.com/en/distilleries/yoichi/", "https://www.nikka.com/en/distilleries/miyagikyo/"],
  gekkeikan: ["https://www.gekkeikan.com/company/tsunekichi/chapter1/"],
  "gato-negro": ["https://vsptwinegroup.com/en/marcas/everyday-wines/gato-negro/"],
  geist: ["https://www.geist.in/about"],
  pasqua: ["https://pasqua.it/wines/", "https://pasqua.it/journal/pasqua-wines-named-innovator-of-the-year-by-wine-enthusiast-magazine/"],
  "b-and-g": ["https://www.barton-guestier.com/fr/Histoire.php"],
  "19-crimes": ["https://aus.19crimes.com/pages/the-19-crimes", "https://global.19crimes.com/products/the-uprising-red-blend"],
  baileys: ["https://www.baileys.com/en/stories/baileys-history"],
  "black-and-white": ["https://media.diageo.com/diageo-corporate-media/media/pwzbn2lv/press-release_black-white-scotch-collaborates.pdf"],
  "blenders-pride": ["https://www.pernod-ricard.com/en/brands/blenders-pride"],
  cotswolds: ["https://www.cotswoldsdistillery.com/pages/our-story"],
  "don-julio": ["https://www.donjulio.com/en/our-story", "https://www.donjulio.com/frequently-asked-questions"],
  "flor-de-cana": ["https://www.flordecana.com/mx/family-legacy"],
  grants: ["https://www.williamgrant.com/We"],
  jameson: ["https://www.jamesonwhiskey.com/en/our-story/our-history", "https://www.jamesonwhiskey.com/en/faq"],
  "jose-cuervo": ["https://global.cuervo.com/about-jose-cuervo/"],
  "kendall-jackson": ["https://www.kj.com/about.html"],
  krsma: ["https://www.krsmaestates.com/about-us/", "https://www.krsmaestates.com/crafting-wine/"],
  "m-chapoutier": ["https://www.chapoutier.com/en/the-maison/history/"],
  "moet-and-chandon": ["https://www.moet.com/en-gb/the-house/success-glamour"],
};

// Only visually checked brand marks may fill an empty stored logo field.
export const BRAND_LOGOS_BATCH_53: Record<string, string> = {
  gekkeikan: "https://www.gekkeikan.com/lib/img/common/header/img_logo.svg",
  "b-and-g": "https://www.barton-guestier.com/pics/communs/BG_logo.png",
  "19-crimes": "https://19crimes.com/cdn/shop/files/19-crimes-logo_black_x400.jpg?v=1637703033",
  "kendall-jackson": "https://www.kj.com/on/demandware.static/-/Sites-KJ-Library/default/dw1d270911/images/logo/kj-logo-from-figma-2024-group3629-hq-compressed.png",
  krsma: "https://www.krsmaestates.com/wp-content/uploads/2020/03/image-logo-krsma-630x535.webp",
  "moet-and-chandon": "https://www.moet.com/themes/custom/moet/images/logo-red-header.png",
};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_53: Record<string, BrandPublicContent> = {
  akashi: guide("Akashi", "Whisky", {
    description: "Akashi is whisky from Eigashima Shuzo in Akashi, Hyogo, on Japan's Seto Inland Sea. The White Oak distillery makes both single malts and blends under the name.",
    story: "Eigashima is also a sake producer, a connection that makes this coastal distillery unusual in Japan. Its whisky range uses different casks, so the seaside setting is a more useful thread than a single fixed flavour profile.",
    notes: ["Single malt", "The current malt release brings cassis, apple, chocolate and oak, followed by a dry close.", "Blended whisky", "The White Oak blend is malt-aromatic, smooth and slightly dry."],
    serve: "Try a small pour neat before adding a splash of water; a tall glass and soda suits the lighter blends.",
    food: "Pour beside yakitori, sesame mushrooms or chicken karaage.",
    pairings: ["yakitori", "sesame mushrooms", "chicken karaage"],
    whyChoose: "A Japanese coastal distillery with both sake-making heritage and a varied whisky range.",
    faq: ["Where is Akashi whisky made?", "Eigashima Shuzo makes Akashi whisky in Akashi, Hyogo, Japan.", "Does Akashi make single malt?", "Yes. The producer lists single malts as well as blended whiskies."],
    finalVerdict: "Akashi is worth exploring for its contrast between approachable blends and cask-led single malts.",
    metaDescription: "Explore Akashi whisky from Hyogo, its coastal distillery, tasting styles and food pairings. Compare city prices on BevOry.",
  }),
  "blue-moon": guide("Blue Moon", "Beer", {
    description: "Blue Moon is an American Belgian-style wheat beer brand born at the Sandlot Brewery in Denver's Coors Field. Its Belgian White uses wheat, oats, Valencia orange peel and coriander.",
    story: "The ballpark brewers took the Belgian witbier idea and gave it a brighter citrus accent. The familiar orange garnish reinforces the fruit already used in the brew.",
    notes: ["Citrus", "Valencia orange peel gives Belgian White its clear orange-zest aroma.", "Wheat and spice", "Wheat and oats make the body softly creamy; coriander brings a floral, gently spicy edge."],
    serve: "Pour chilled into a wheat-beer glass and add an orange slice only if you enjoy extra citrus.",
    food: "Try it with tandoori prawns, chilli paneer or grilled corn with lime.",
    pairings: ["tandoori prawns", "chilli paneer", "grilled corn with lime"],
    whyChoose: "A citrus-led wheat beer with enough spice to stand up to Indian snacks.",
    faq: ["Is Blue Moon Belgian White brewed in Belgium?", "No. It began at the Sandlot Brewery in Denver, Colorado, as an American take on Belgian witbier.", "Why is Blue Moon served with orange?", "Belgian White is brewed with Valencia orange peel; the garnish highlights that citrus character."],
    finalVerdict: "Blue Moon Belgian White is a refreshing change from crisp lager when you want citrus and a softer texture.",
    metaDescription: "Discover Blue Moon Belgian White, its orange-and-coriander recipe and Indian food pairings. Compare city prices on BevOry.",
  }),
  budweiser: guide("Budweiser", "Beer", {
    description: "Budweiser is an American lager introduced by Anheuser-Busch in 1876. Barley malt, rice and hops shape its clean, lightly malty style.",
    story: "The brewery kept its original yeast culture and a beechwood-aging step as production expanded far beyond St. Louis. The latter is part of the beer's maturation process, not a claim that the beer tastes like oak.",
    notes: ["Malt", "A restrained cereal sweetness sits beneath the beer's bright carbonation.", "Finish", "Light hop bitterness keeps the finish crisp rather than heavy."],
    serve: "Serve cold in a clean lager glass, with enough space for a modest head.",
    food: "Its brisk finish works with masala peanuts, chicken tikka or a cheeseburger.",
    pairings: ["masala peanuts", "chicken tikka", "cheeseburger"],
    whyChoose: "A long-running American lager built for a clean, easy-drinking pour.",
    faq: ["When was Budweiser introduced?", "Anheuser-Busch began brewing Budweiser in 1876.", "Does Budweiser use rice?", "Yes. Rice is used alongside barley malt in the lager."],
    finalVerdict: "Budweiser is most convincing cold, beside salty or grilled food.",
    metaDescription: "Read about Budweiser's 1876 lager, its brewing ingredients and food pairings. Compare city prices on BevOry.",
  }),
  "captain-morgan": guide("Captain Morgan", "Rum", {
    description: "Captain Morgan is a Caribbean rum-based spirits range best known for Original Spiced. That expression combines rum with vanilla and warm spices for a mixer-friendly pour.",
    story: "The brand takes its name from Henry Morgan, the seventeenth-century privateer. Today's range extends beyond Original Spiced to white and dark styles, each intended for a different kind of drink.",
    notes: ["Original Spiced", "Vanilla, brown sugar and warming cinnamon are the familiar notes in the spiced expression.", "Dark rum", "The darker style moves toward richer sugar and oak tones."],
    serve: "Build a short highball with cola and lime, or try the spiced expression with pineapple juice.",
    food: "Set it beside jerk chicken, chilli paneer or grilled pineapple.",
    pairings: ["jerk chicken", "chilli paneer", "grilled pineapple"],
    whyChoose: "A spiced rum range with a distinct vanilla-led character in simple mixed drinks.",
    faq: ["What is Captain Morgan Original Spiced?", "It is a Caribbean rum-based spirit flavoured with vanilla and spices.", "Can Captain Morgan be mixed with cola?", "Yes. Cola with a squeeze of lime is a classic serve for Original Spiced."],
    finalVerdict: "Captain Morgan works best when its spice is given room in a straightforward long drink.",
    metaDescription: "Explore Captain Morgan rum and Original Spiced, with mixing ideas and Indian food pairings. Compare city prices on BevOry.",
  }),
  carlsberg: guide("Carlsberg", "Beer", {
    description: "Carlsberg is a Danish brewing company founded in 1847. Its namesake pilsner draws on barley malt, hops and the brewery's long work with purified yeast.",
    story: "J.C. Jacobsen built the brewery in Copenhagen and later established the Carlsberg Laboratory. Research there helped make controlled yeast cultivation central to modern lager brewing.",
    notes: ["Pilsner aroma", "Grainy malt and a light herbal hop note lead the classic lager.", "Dry close", "Firm carbonation and measured bitterness clear the palate."],
    serve: "Pour well chilled into a tall pilsner glass, leaving room for the foam.",
    food: "Pair with fish fingers, paneer pakora or peppery fries.",
    pairings: ["fish fingers", "paneer pakora", "peppery fries"],
    whyChoose: "A Danish pilsner with a documented place in brewing science.",
    faq: ["Where did Carlsberg begin?", "J.C. Jacobsen founded Carlsberg in Copenhagen in 1847.", "What style is Carlsberg's classic beer?", "Its namesake beer is a pilsner-style lager."],
    finalVerdict: "Carlsberg is an easy choice when a dry lager and fried snacks are on the table.",
    metaDescription: "Discover Carlsberg's Danish pilsner, brewing history and snack pairings. Compare city prices on BevOry.",
  }),
  "clase-azul": guide("Clase Azul", "Tequila", {
    description: "Clase Azul México is a tequila and mezcal house founded by Arturo Lomelí. Mexican craft is central to its identity, particularly the decorated ceramic decanters associated with its tequila range.",
    story: "Lomelí built the company around both spirits and the work of Mexican artisans. The decanter became as recognisable as the drink, making the vessel part of the brand's cultural story.",
    notes: ["Agave", "Cooked agave is the centre of the tequila style.", "Oak-aged expressions", "Reposado and longer-aged bottlings add softer vanilla and spice tones to that agave base."],
    serve: "Pour a small measure into a stemmed tequila glass; give the aged expressions a moment to open.",
    food: "Try alongside duck carnitas, paneer tikka or dark chocolate with sea salt.",
    pairings: ["duck carnitas", "paneer tikka", "dark chocolate with sea salt"],
    whyChoose: "A Mexican spirits house where artisanal ceramic work shares the stage with agave.",
    faq: ["Who founded Clase Azul?", "Arturo Lomelí founded Clase Azul México.", "Is Clase Azul only tequila?", "No. The house also makes mezcal."],
    finalVerdict: "Clase Azul is a considered sipping choice for drinkers drawn to agave and Mexican craftsmanship.",
    metaDescription: "Explore Clase Azul tequila, its Mexican craft identity, serving ideas and pairings. Compare city prices on BevOry.",
  }),
  glengrant: guide("The Glen Grant", "Single Malt", {
    description: "The Glen Grant is a Speyside single-malt Scotch distillery in Rothes, founded by brothers John and James Grant in 1840. Tall, slender stills and purifiers help shape its light, fruit-led spirit.",
    story: "James 'The Major' Grant enlarged the distillery and introduced the still design that remains central to its style. His garden beside the distillery is still part of the place's identity.",
    notes: ["Orchard fruit", "Apple and pear tones are a useful starting point for the house style.", "Oak", "Core releases bring honey, vanilla and gentle spice as the fruit settles."],
    serve: "Use a tulip glass neat first; add a few drops of water if you want the fruit to open further.",
    food: "Match with almond biscotti, malai tikka or baked brie.",
    pairings: ["almond biscotti", "malai tikka", "baked brie"],
    whyChoose: "A Speyside malt whose still design makes its fruit character particularly clear.",
    faq: ["Where is The Glen Grant made?", "The distillery is in Rothes, in Scotland's Speyside region.", "Who founded The Glen Grant?", "Brothers John and James Grant established it in 1840."],
    finalVerdict: "The Glen Grant makes a persuasive first Speyside malt for drinkers who prefer fruit to peat.",
    metaDescription: "Meet The Glen Grant from Rothes, its tall stills, fruit-led malts and food pairings. Compare city prices on BevOry.",
  }),
  hardys: guide("Hardys", "Wine", {
    description: "Hardys is an Australian wine house founded by Thomas Hardy in South Australia in 1853. Its range spans everyday regional blends and more focused reds and whites.",
    story: "Hardy first worked with winemaker John Reynell after arriving from England. He then bought land by the River Torrens, naming his first property Bankside and building a business that later became linked with McLaren Vale.",
    notes: ["Shiraz", "Ripe plum and pepper are characteristic of the house's fuller Australian reds.", "Chardonnay", "The whites can lean toward citrus and stone fruit, with texture changing across the range."],
    serve: "Serve Chardonnay cool; give richer Shiraz a larger glass and a little air.",
    food: "Try Shiraz with pepper chicken or lamb kebabs, and Chardonnay with tandoori fish.",
    pairings: ["pepper chicken", "lamb kebabs", "tandoori fish"],
    whyChoose: "A historic South Australian name with a range broad enough to compare styles side by side.",
    faq: ["When was Hardys founded?", "Thomas Hardy began the wine business in South Australia in 1853.", "Does Hardys only make red wine?", "No. Its range includes both red and white wines."],
    finalVerdict: "Hardys is a practical starting point for exploring Australian Shiraz and Chardonnay.",
    metaDescription: "Explore Hardys wine from South Australia, its 1853 origins and food pairings. Compare city prices on BevOry.",
  }),
  jura: guide("Jura", "Single Malt", {
    description: "Jura is a single-malt Scotch whisky made on the Isle of Jura. Its exceptionally tall copper pot stills give the house a lighter, fruitier spirit than many drinkers expect from an island distillery.",
    story: "The original distillery dates to 1810, but the site was rebuilt and reopened in 1963 to support the island community. The rebuilt stills became one of the clearest influences on Jura's modern style.",
    notes: ["Citrus and fruit", "Bright citrus and soft orchard fruit lead the core style.", "Cask character", "Bourbon, rum and other finishes add vanilla, caramel or tropical accents across different releases."],
    serve: "Taste neat in a tulip glass, then add a little water; a lighter release also works in a whisky highball.",
    food: "Serve with smoked paneer, roast chicken or salted cashews.",
    pairings: ["smoked paneer", "roast chicken", "salted cashews"],
    whyChoose: "An island malt with an approachable fruit character and a distinctive 1963 distillery story.",
    faq: ["Where is Jura whisky made?", "It is distilled on Scotland's Isle of Jura.", "When did the Jura distillery reopen?", "The rebuilt distillery reopened in 1963."],
    finalVerdict: "Jura suits drinkers who want island provenance without assuming every island malt is heavily smoky.",
    metaDescription: "Explore Jura single malt, its island distillery, tall stills and serving ideas. Compare city prices on BevOry.",
  }),
  "louis-jadot": guide("Louis Jadot", "Wine", {
    description: "Louis Jadot is a Burgundy wine house founded in Beaune in 1859. Chardonnay and Pinot Noir anchor its wide range of village, premier cru and grand cru wines.",
    story: "Louis Henry Denis Jadot gave the house his name after the family had already acquired Burgundy vineyard holdings. The business later expanded its estate land while continuing to work with growers whose grapes it vinifies itself.",
    notes: ["White Burgundy", "Chardonnay moves from brisk citrus in cooler sites to fuller orchard fruit in richer appellations.", "Red Burgundy", "Pinot Noir brings red berries and floral detail, with tannin and oak varying by vineyard."],
    serve: "Chill white Burgundy lightly; pour Pinot Noir into a broad glass at cool room temperature.",
    food: "Try Chardonnay with tandoori fish and Pinot Noir with mushroom pulao or roast duck.",
    pairings: ["tandoori fish", "mushroom pulao", "roast duck"],
    whyChoose: "A Beaune house with a broad Burgundy map rather than one signature village.",
    faq: ["Where is Louis Jadot based?", "The house is based in Beaune, Burgundy, France.", "Which grapes define Louis Jadot wines?", "Chardonnay and Pinot Noir are central to its white and red Burgundy range."],
    finalVerdict: "Louis Jadot makes Burgundy's shifts in place and grape easy to explore across several price levels.",
    metaDescription: "Read about Louis Jadot's Burgundy wines, Chardonnay, Pinot Noir and food pairings. Compare city prices on BevOry.",
  }),
  nikka: guide("Nikka", "Whisky", {
    description: "Nikka is a Japanese whisky company founded by Masataka Taketsuru. Yoichi in Hokkaido and Miyagikyo near Sendai give its blenders two deliberately different malt styles.",
    story: "Taketsuru established Yoichi in 1934 after studying whisky-making in Scotland. He opened Miyagikyo in 1969 to add a softer counterpart to Yoichi's bold, coal-fired spirit.",
    notes: ["Yoichi", "The coastal, coal-fired malt tends toward weight, smoke and a savoury edge.", "Miyagikyo", "Steam-heated distillation creates a gentler, fruitier spirit with floral lift."],
    serve: "Compare small neat pours side by side; both can open with a few drops of water.",
    food: "Try Yoichi with yakitori or smoked mushrooms, and Miyagikyo with miso-glazed aubergine.",
    pairings: ["yakitori", "smoked mushrooms", "miso-glazed aubergine"],
    whyChoose: "Two contrasting Japanese distilleries give Nikka unusual blending range.",
    faq: ["Who founded Nikka?", "Masataka Taketsuru founded Nikka and established Yoichi Distillery in 1934.", "Are Yoichi and Miyagikyo the same style?", "No. Yoichi is generally bolder; Miyagikyo was designed to produce a gentler contrast."],
    finalVerdict: "Nikka is most rewarding when you taste how Yoichi and Miyagikyo pull in different directions.",
    metaDescription: "Explore Nikka whisky, Yoichi and Miyagikyo, with tasting styles and food pairings. Compare city prices on BevOry.",
  }),
  gekkeikan: guide("Gekkeikan", "Sake", {
    description: "Gekkeikan is a Japanese sake maker from Fushimi, Kyoto, founded in 1637. Its range runs from everyday sake to ginjo and other more aromatic styles.",
    story: "Founder Jiemon Okura opened a sake shop called Kasagiya beside Fushimi's waterways. Later generations established a brewing research institute, adding scientific study to the area's long sake-making tradition.",
    notes: ["Rice and texture", "Gekkeikan's gentler styles favour soft rice flavour and a smooth finish.", "Aromatic sake", "Ginjo-style bottlings bring more lifted fruit and floral notes."],
    serve: "Serve a lighter ginjo chilled in a small glass; fuller sake can be tried gently warmed.",
    food: "Pair with chicken gyoza, tandoori fish or steamed edamame.",
    pairings: ["chicken gyoza", "tandoori fish", "steamed edamame"],
    whyChoose: "A Fushimi sake house with centuries of brewing history and a wide choice of styles.",
    faq: ["Where is Gekkeikan from?", "It began in Fushimi, Kyoto, Japan.", "When was Gekkeikan founded?", "Jiemon Okura opened the original Kasagiya sake business in 1637."],
    finalVerdict: "Gekkeikan offers a useful route from easy, rice-led sake to more aromatic pours.",
    metaDescription: "Discover Gekkeikan sake from Fushimi, Kyoto, with serving ideas and food pairings. Compare city prices on BevOry.",
  }),
  "gato-negro": guide("Gato Negro", "Wine", {
    description: "Gato Negro is a Chilean wine label from Viña San Pedro, part of VSPT Wine Group. Its range includes Cabernet Sauvignon, Carmenère, Merlot, Chardonnay and Sauvignon Blanc.",
    story: "Viña San Pedro created Gato Negro in the early 1960s as bottled wine gained ground in Chile. The black-cat name stayed while the portfolio grew well beyond its original domestic market.",
    notes: ["Cabernet Sauvignon", "Dark berry fruit and a gentle herbal edge make the red an easy match for savoury food.", "Sauvignon Blanc", "Citrus and green-fruit freshness keep the white brisk."],
    serve: "Pour the red at cool room temperature; chill the Sauvignon Blanc before opening.",
    food: "Try Cabernet with mutton seekh and Sauvignon Blanc with grilled prawns or limey chaat.",
    pairings: ["mutton seekh", "grilled prawns", "limey chaat"],
    whyChoose: "A Chilean label with familiar varietals and a clear route into Carmenère.",
    faq: ["Who makes Gato Negro wine?", "Viña San Pedro, part of VSPT Wine Group, makes Gato Negro.", "Is Gato Negro only red wine?", "No. Its range also includes Chardonnay, Sauvignon Blanc and rosé."],
    finalVerdict: "Gato Negro is most useful when you want a straightforward Chilean varietal for the table.",
    metaDescription: "Explore Gato Negro's Chilean reds and whites, including Carmenère, with food pairings. Compare city prices on BevOry.",
  }),
  geist: guide("Geist", "Beer", {
    description: "Geist is a Bengaluru craft-beer producer that brews and distributes fresh beer from its own facility off Old Madras Road. Its range reaches drinkers through taps, kegs and 500 ml crowlers.",
    story: "Geist first explored packaged wheat beer through a Belgian brewing partnership, then developed local brewery operations in Bengaluru. Its distribution brewery made fresh craft beer available beyond a single brewpub.",
    notes: ["Wheat styles", "Expect soft grain and a fuller mouthfeel from the wheat beers.", "Hoppier pours", "The brewery's broader range brings a brighter bitterness and more aromatic hops."],
    serve: "Keep fresh beer cold and pour into a clean glass soon after opening a crowler.",
    food: "Choose paneer tikka for wheat beer, or peri-peri fries and chilli chicken for hoppier pours.",
    pairings: ["paneer tikka", "peri-peri fries", "chilli chicken"],
    whyChoose: "A Bengaluru brewery focused on making fresh craft beer travel beyond its taproom.",
    faq: ["Where is Geist beer brewed?", "Geist runs a distribution craft brewery in Bengaluru, Karnataka.", "What is a Geist crowler?", "It is a sealed 500 ml container used to take fresh beer from the brewery's retail network."],
    finalVerdict: "Geist is a local choice for drinkers who care as much about freshness as beer style.",
    metaDescription: "Explore Geist's Bengaluru craft beer, crowlers, serving tips and Indian food pairings. Compare city prices on BevOry.",
  }),
  pasqua: guide("Pasqua", "Wine", {
    description: "Pasqua is a family wine house based near Verona in Veneto, Italy. Its wines include Valpolicella reds, Amarone and other expressions from the region.",
    story: "The Pasqua family's wine business dates to 1925. Later generations expanded beyond its original Verona base while retaining Valpolicella grapes such as Corvina and Rondinella at the centre of key reds.",
    notes: ["Valpolicella", "Red cherry and herbal freshness mark the lighter local reds.", "Amarone", "Dried fruit, cocoa and a fuller texture distinguish wines made from dried grapes."],
    serve: "Serve Valpolicella lightly cool; allow Amarone to open in a broad red-wine glass.",
    food: "Pair Valpolicella with tomato pasta or paneer tikka, and Amarone with slow-cooked lamb.",
    pairings: ["tomato pasta", "paneer tikka", "slow-cooked lamb"],
    whyChoose: "A Verona family house that shows the range between lively Valpolicella and powerful Amarone.",
    faq: ["Where is Pasqua based?", "Pasqua is based in the Verona area of Veneto, Italy.", "What grapes appear in Pasqua's Valpolicella wines?", "Corvina and Rondinella are among the region's important grapes in the house's range."],
    finalVerdict: "Pasqua gives Veneto red-wine drinkers a clear choice between freshness and concentration.",
    metaDescription: "Explore Pasqua wines from Verona, Valpolicella and Amarone styles, and food pairings. Compare city prices on BevOry.",
  }),
  "b-and-g": guide("Barton & Guestier", "Wine", {
    description: "Barton & Guestier is a Bordeaux wine house founded after Irish merchant Thomas Barton settled there in 1725. Its French range now reaches beyond Bordeaux into other regions and grapes.",
    story: "Barton's grandson joined Daniel Guestier, formalising their partnership in 1802. Barrels once left Bordeaux's Chartrons district by river; the house's trade network eventually became international.",
    notes: ["Bordeaux red", "Merlot and Cabernet Sauvignon bring dark and red fruit with gentle spice in the house's Bordeaux blends.", "French whites", "Other regional wines introduce brighter citrus and orchard-fruit styles."],
    serve: "Give a Bordeaux red a broad glass and a little air; chill a white before serving.",
    food: "Try Bordeaux red with mushroom pulao or lamb kebabs, and white wine with grilled fish.",
    pairings: ["mushroom pulao", "lamb kebabs", "grilled fish"],
    whyChoose: "A historic Bordeaux merchant house that lets drinkers compare French regions under one name.",
    faq: ["Who founded Barton & Guestier?", "Thomas Barton established the Bordeaux wine business in 1725; Daniel Guestier later joined the family enterprise.", "Does Barton & Guestier only make Bordeaux wine?", "No. Its portfolio includes wines from other French regions."],
    finalVerdict: "Barton & Guestier is a practical introduction to French wine through a house with deep Bordeaux roots.",
    metaDescription: "Discover Barton & Guestier's Bordeaux heritage, French wine range and food pairings. Compare city prices on BevOry.",
  }),
  "19-crimes": guide("19 Crimes", "Wine", {
    description: "19 Crimes is an Australian wine brand whose labels portray people transported from Britain to Australia under the colonial penal system. Shiraz, Cabernet Sauvignon and red blends form much of its range.",
    story: "The name refers to the list of offences for which transportation could replace execution. The bottle portraits carry that story, turning the label into an unusually direct piece of brand history.",
    notes: ["Shiraz-led reds", "Ripe plum, dark berry and soft spice make the fuller reds easy to recognise.", "Cabernet Sauvignon", "The varietal bottling brings currant fruit, vanilla and a firmer line of tannin."],
    serve: "Pour the reds slightly cool in a medium red-wine glass; give fuller blends a few minutes after opening.",
    food: "Match with barbecue chicken, seekh kebabs or smoked aubergine.",
    pairings: ["barbecue chicken", "seekh kebabs", "smoked aubergine"],
    whyChoose: "A bold Australian red-wine range with an identifiable story on every label.",
    faq: ["Why is the brand called 19 Crimes?", "The name refers to offences once punishable by transportation to Australia.", "What wine styles does 19 Crimes make?", "Its range includes Shiraz, Cabernet Sauvignon and several red blends."],
    finalVerdict: "19 Crimes is most at home with smoky food and drinkers who like generous Australian reds.",
    metaDescription: "Explore 19 Crimes Australian wines, convict-label history and red-wine pairings. Compare city prices on BevOry.",
  }),
  baileys: guide("Baileys", "Liqueur", {
    description: "Baileys is an Irish cream liqueur that combines Irish dairy cream, Irish whiskey and other spirits with chocolate and vanilla flavours. The Original recipe was completed in 1974.",
    story: "The creators spent two years working out how to bring cream and whiskey together in a stable drink. Baileys became a distinct after-dinner category rather than another way of serving straight whiskey.",
    notes: ["Cream", "A thick, soft texture carries the dairy flavour.", "Chocolate and vanilla", "Cocoa, vanilla and whiskey warmth follow the first sweet sip."],
    serve: "Pour a small measure over ice, or add it to iced coffee; keep the bottle's storage directions in mind.",
    food: "Serve with tiramisu, chocolate mousse or a slice of plum cake.",
    pairings: ["tiramisu", "chocolate mousse", "plum cake"],
    whyChoose: "A creamy Irish liqueur whose dessert-like texture is the main attraction.",
    faq: ["What is Baileys made from?", "Baileys Original combines Irish dairy cream, Irish whiskey and other spirits with chocolate and vanilla flavours.", "When was Baileys created?", "The Original recipe was completed in 1974."],
    finalVerdict: "Baileys is an after-dinner pour best kept simple: ice, coffee or a chocolate dessert.",
    metaDescription: "Explore Baileys Irish cream, its 1974 origins, serving ideas and dessert pairings. Compare city prices on BevOry.",
  }),
  "black-and-white": guide("Black & White", "Whisky", {
    description: "Black & White is a blended Scotch whisky created by James Buchanan in 1904. The brand is now in Diageo's portfolio and is known for its black-and-white terrier label.",
    story: "Buchanan wanted a Scotch that could be shared readily rather than reserved for formal occasions. The pair of terriers turned a simple colour-coded name into one of the category's most recognisable labels.",
    notes: ["Malt and grain", "A soft cereal base supports a lighter malt sweetness.", "Finish", "Gentle fruit and a modest oak note keep the blend easy to mix."],
    serve: "Try a measured pour with ice and soda, or use it in a short whisky highball.",
    food: "Pair with salted almonds, chicken tikka or paneer kebabs.",
    pairings: ["salted almonds", "chicken tikka", "paneer kebabs"],
    whyChoose: "A lighter Buchanan-era Scotch blend with a distinctive, enduring identity.",
    faq: ["Who created Black & White whisky?", "James Buchanan created the blended Scotch in 1904.", "What do the dogs on the label represent?", "They are black and white terriers, echoing the brand name."],
    finalVerdict: "Black & White is a relaxed blended Scotch for a simple highball or a short pour with snacks.",
    metaDescription: "Meet Black & White blended Scotch, its Buchanan history, terrier label and pairings. Compare city prices on BevOry.",
  }),
  "blenders-pride": guide("Blenders Pride", "Whisky", {
    description: "Blenders Pride is an Indian blended whisky from Pernod Ricard. It combines Indian grain spirit with imported Scotch malt from Chivas Brothers.",
    story: "Launched in 1995, the brand became part of Pernod Ricard in 2001. Its Reserve Collection later gave the original grain-and-malt idea a separate, more fruit-led expression.",
    notes: ["Rare Premium", "Wood, fruit and a light peaty note sit over the grain-led body.", "Reserve Collection", "The later blend shifts toward a fuller fruit impression."],
    serve: "Taste a small measure neat first; add water or ice according to the blend's weight.",
    food: "Pour with mutton seekh, tandoori mushrooms or roasted cashews.",
    pairings: ["mutton seekh", "tandoori mushrooms", "roasted cashews"],
    whyChoose: "An established Indian premium blend with a clear Scotch-malt component.",
    faq: ["Is Blenders Pride an Indian whisky?", "Yes. Pernod Ricard blends Indian grain spirit with imported Scotch malts for the brand.", "When did Blenders Pride launch?", "It launched in 1995."],
    finalVerdict: "Blenders Pride offers a familiar Indian blended-whisky style with more malt character than a neutral grain pour.",
    metaDescription: "Read about Blenders Pride's Indian grain and Scotch malt blend, styles and pairings. Compare city prices on BevOry.",
  }),
  cotswolds: guide("Cotswolds", "Spirits", {
    description: "Cotswolds Distillery makes English single-malt whisky and gin in the Cotswolds. Daniel Szor founded it in 2014 with a focus on small-batch spirits and local ingredients.",
    story: "The distillery released its first Signature Single Malt in 2017, three years after work began. Gin gave the new operation a spirit to share while its whisky matured.",
    notes: ["Single malt", "The signature whisky brings orchard fruit and malt sweetness with a fuller cask finish.", "Dry gin", "Juniper and fresh citrus lead the gin, with botanicals adding a gently herbal close."],
    serve: "Taste the malt neat in a tulip glass; serve the gin long with tonic and a simple citrus garnish.",
    food: "Try whisky with roast chicken or aged cheddar, and gin with tandoori prawns.",
    pairings: ["roast chicken", "aged cheddar", "tandoori prawns"],
    whyChoose: "An English distillery whose gin and whisky show two very different uses of local craft.",
    faq: ["Who founded Cotswolds Distillery?", "Daniel Szor founded the distillery in 2014.", "Does Cotswolds make both gin and whisky?", "Yes. The range includes dry gin and English single-malt whisky."],
    finalVerdict: "Cotswolds is worth comparing across categories: a bright gin beside a richer English malt.",
    metaDescription: "Explore Cotswolds gin and single malt, the distillery's 2014 story and food pairings. Compare city prices on BevOry.",
  }),
  "don-julio": guide("Don Julio", "Tequila", {
    description: "Don Julio is a tequila house founded by Julio González in the Highlands of Jalisco, Mexico. Its tequilas begin with 100% Blue Weber agave grown in the region.",
    story: "González opened La Primavera distillery in 1942 in Atotonilco El Alto. The brand still points to his practice of tending agave plants individually and harvesting them at maturity.",
    notes: ["Blanco", "Fresh cooked agave and citrus lead the unaged style.", "Aged tequila", "Reposado and añejo expressions bring warmer vanilla and oak character."],
    serve: "Taste Blanco in a small stemmed glass or use it in a Paloma; sip aged releases slowly.",
    food: "Pair with al pastor tacos, paneer tikka or grilled prawns with lime.",
    pairings: ["al pastor tacos", "paneer tikka", "grilled prawns with lime"],
    whyChoose: "A Highland Jalisco house with a founder-led agave story dating to 1942.",
    faq: ["Where is Don Julio made?", "Don Julio tequila is made in the Highlands of Jalisco, Mexico.", "What agave does Don Julio use?", "The producer uses 100% Blue Weber agave."],
    finalVerdict: "Don Julio makes sense when you want to taste the contrast between fresh agave and barrel-aged warmth.",
    metaDescription: "Explore Don Julio tequila from Jalisco, its Blue Weber agave and serving ideas. Compare city prices on BevOry.",
  }),
  "flor-de-cana": guide("Flor de Caña", "Rum", {
    description: "Flor de Caña is a Nicaraguan rum made near the San Cristóbal volcano. The Pellas family's spirits story at the site dates to 1890.",
    story: "Alfredo Francisco Pellas chose the volcanic landscape around Chichigalpa for sugarcane and rum production. Successive generations kept the family business in Nicaragua through major political and natural upheavals.",
    notes: ["Younger rums", "Lighter cane sweetness and a clean finish suit highballs.", "Aged styles", "Longer-matured releases move toward caramel, dried fruit and wood spice."],
    serve: "Use a lighter style with soda and lime; sip an aged expression neat in a small glass.",
    food: "Match with grilled pineapple, pepper pork or cocoa-dusted almonds.",
    pairings: ["grilled pineapple", "pepper pork", "cocoa-dusted almonds"],
    whyChoose: "A Nicaraguan family rum with a long link to the San Cristóbal landscape.",
    faq: ["Where is Flor de Caña from?", "Flor de Caña is made in Nicaragua, near the San Cristóbal volcano.", "How old is the Flor de Caña family business?", "Its rum-making story at the site began in 1890."],
    finalVerdict: "Flor de Caña offers a useful path from brisk rum highballs to slower aged pours.",
    metaDescription: "Explore Flor de Caña rum from Nicaragua, its family history and serving ideas. Compare city prices on BevOry.",
  }),
  grants: guide("Grant's", "Whisky", {
    description: "Grant's is a blended Scotch whisky from William Grant & Sons. The house blends malt and grain whiskies, with grain whisky from Girvan playing an important part in its range.",
    story: "William Grant built the family distilling business in Scotland before Grant's became its blended-whisky name. Later generations built Girvan distillery and gave the blend its distinctive triangular bottle.",
    notes: ["Grain-led softness", "A light cereal sweetness keeps the blend approachable.", "Malt depth", "Fruit, vanilla and gentle oak come from the malts and cask choices across the range."],
    serve: "Try with ice and soda in a highball; taste a small neat pour to compare the malt notes.",
    food: "Serve with fish pakora, chicken tikka or salted peanuts.",
    pairings: ["fish pakora", "chicken tikka", "salted peanuts"],
    whyChoose: "A family-owned Scotch blend built around its own malt and grain whisky resources.",
    faq: ["Who makes Grant's whisky?", "William Grant & Sons makes Grant's blended Scotch whisky.", "Is Grant's a single malt?", "No. Grant's is a blend of malt and grain whiskies."],
    finalVerdict: "Grant's is a dependable blended Scotch for a long drink or an uncomplicated pour with food.",
    metaDescription: "Discover Grant's blended Scotch, Girvan grain whisky, serving ideas and pairings. Compare city prices on BevOry.",
  }),
  jameson: guide("Jameson", "Whiskey", {
    description: "Jameson is an Irish whiskey name established by John Jameson in Dublin in 1780. The signature blend uses malted and unmalted barley and is triple-distilled.",
    story: "Jameson's original home was the Bow Street distillery. The founder's emphasis on ingredients, repeated distillation and seasoned oak became the basis of the house style.",
    notes: ["Barley", "A soft grain sweetness sits alongside orchard-fruit notes.", "Oak finish", "Seasoned wood adds vanilla and a gentle spice to the smooth texture."],
    serve: "Try it neat first, then with ice or in a whiskey-and-ginger highball.",
    food: "Pair with chicken kebabs, buttered popcorn or an apple tart.",
    pairings: ["chicken kebabs", "buttered popcorn", "apple tart"],
    whyChoose: "A Dublin-rooted Irish blend whose triple-distilled style remains easy to recognise.",
    faq: ["Is Jameson Scotch whisky?", "No. Jameson is Irish whiskey with roots in Dublin.", "Is Jameson triple-distilled?", "Yes. Triple distillation is part of the producer's established method."],
    finalVerdict: "Jameson is at its easiest in a ginger highball, though the barley notes reward a neat taste first.",
    metaDescription: "Explore Jameson Irish whiskey, its Dublin history, triple distillation and pairings. Compare city prices on BevOry.",
  }),
  "jose-cuervo": guide("Jose Cuervo", "Tequila", {
    description: "Jose Cuervo is a tequila house based in Tequila, Jalisco, Mexico. Its commercial tequila licence dates to 1795, and production remains associated with La Rojeña distillery.",
    story: "José Antonio de Cuervo obtained land for agave cultivation in 1758. His descendant José María Guadalupe de Cuervo received the 1795 licence that made the family's spirit a commercial tequila business.",
    notes: ["Unaged styles", "Fresh agave and citrus make the lighter tequilas useful in mixed drinks.", "Oak-aged styles", "Barrel time brings warmer spice and vanilla to the more mature range."],
    serve: "Use a Blanco in a Margarita with fresh lime; give aged tequila a small neat pour.",
    food: "Serve with fish tacos, achari paneer or grilled corn with chilli.",
    pairings: ["fish tacos", "achari paneer", "grilled corn with chilli"],
    whyChoose: "A Jalisco tequila house with a documented family and distillery history reaching back centuries.",
    faq: ["Where is Jose Cuervo made?", "The house is based in Tequila, Jalisco, with production associated with La Rojeña distillery.", "When did Jose Cuervo receive its commercial licence?", "The family received a licence to produce and distribute tequila in 1795."],
    finalVerdict: "Jose Cuervo is a starting point for comparing fresh cocktail tequilas with slower aged styles.",
    metaDescription: "Explore Jose Cuervo tequila from Jalisco, its 1795 history and serving ideas. Compare city prices on BevOry.",
  }),
  "kendall-jackson": guide("Kendall-Jackson", "Wine", {
    description: "Kendall-Jackson is a California wine house founded by Jess Jackson and his family in 1982. Its Vintner's Reserve Chardonnay helped make the name familiar far beyond the state.",
    story: "Jess Jackson wanted a premium California wine at an attainable price. The first Vintner's Reserve Chardonnay became the house's calling card, and later collections drew fruit from cooler coastal appellations.",
    notes: ["Chardonnay", "Orchard fruit and citrus sit beneath a creamy texture in the house's best-known white.", "California reds", "Cabernet and other reds bring darker fruit and fuller tannin."],
    serve: "Serve Chardonnay cool rather than ice-cold; pour a fuller red into a broad glass.",
    food: "Try Chardonnay with tandoori prawns or roast chicken, and Cabernet with pepper lamb.",
    pairings: ["tandoori prawns", "roast chicken", "pepper lamb"],
    whyChoose: "A California wine name built on Chardonnay but broad enough for red-wine drinkers too.",
    faq: ["Who founded Kendall-Jackson?", "Jess Jackson and his family established the winery in 1982.", "What is Kendall-Jackson best known for?", "Its Vintner's Reserve Chardonnay is the house's most recognisable wine."],
    finalVerdict: "Kendall-Jackson is a useful benchmark for the richer side of California Chardonnay.",
    metaDescription: "Discover Kendall-Jackson California wines, Chardonnay heritage and food pairings. Compare city prices on BevOry.",
  }),
  krsma: guide("KRSMA", "Wine", {
    description: "KRSMA is an Indian wine estate founded by Krishna and Uma Chigurupati in the Hampi Hills of Karnataka. Its vineyard lies near Tavaregere, away from Maharashtra's better-known wine belt.",
    story: "The Chigurupatis found the hilly site during a 2008 visit near Hampi. They built the estate around close attention to fruit at harvest, with Uma tasting grapes from individual plots as they ripen.",
    notes: ["Sauvignon Blanc", "The estate's white can show lime, pear and a clean line of acidity.", "Sangiovese", "Red fruit and earthy notes give the Italian grape a different expression in Karnataka."],
    serve: "Chill Sauvignon Blanc; pour Sangiovese lightly cool into a red-wine glass.",
    food: "Pair the white with tandoori fish and the red with mushroom pulao or lamb chops.",
    pairings: ["tandoori fish", "mushroom pulao", "lamb chops"],
    whyChoose: "An estate-grown Indian wine story rooted in the rocky hills near Hampi.",
    faq: ["Where is KRSMA wine made?", "KRSMA is made in Karnataka's Hampi Hills near Tavaregere.", "Who founded KRSMA?", "Krishna and Uma Chigurupati founded the estate."],
    finalVerdict: "KRSMA shows how distinctive Indian wine can be outside the Nashik region.",
    metaDescription: "Explore KRSMA wines from Hampi Hills, their founders, grape styles and pairings. Compare city prices on BevOry.",
  }),
  "m-chapoutier": guide("M. Chapoutier", "Wine", {
    description: "M. Chapoutier is a Rhône Valley wine house based in Tain-l'Hermitage, France. It is strongly associated with Hermitage and with Michel Chapoutier's move toward biodynamic viticulture.",
    story: "The house traces its site to an 1808 wine business; Marius Chapoutier joined in 1897 and later gave the firm his family name. Michel Chapoutier took charge in 1990 and began applying biodynamic methods to the vines.",
    notes: ["Northern Rhône Syrah", "Dark berries, pepper and a savoury edge define many of the house's red wines.", "Rhône whites", "Marsanne and other white-grape wines can bring stone fruit and a broad, textured palate."],
    serve: "Give a structured Hermitage red air in a large glass; serve Rhône whites lightly chilled.",
    food: "Try Syrah with galouti kebabs or roast lamb, and white wine with tandoori fish.",
    pairings: ["galouti kebabs", "roast lamb", "tandoori fish"],
    whyChoose: "A Rhône house with a clear Hermitage identity and a long vineyard-focused history.",
    faq: ["Where is M. Chapoutier based?", "The house is based in Tain-l'Hermitage in France's Rhône Valley.", "Which red grape is central to Hermitage?", "Syrah is the red grape associated with Hermitage wines."],
    finalVerdict: "M. Chapoutier is a strong route into the Rhône's contrast between savoury Syrah and textured whites.",
    metaDescription: "Explore M. Chapoutier's Rhône wines, Hermitage heritage and Indian food pairings. Compare city prices on BevOry.",
  }),
  "moet-and-chandon": guide("Moët & Chandon", "Champagne", {
    description: "Moët & Chandon is a Champagne house founded by Claude Moët in 1743 and based in Épernay, France. Its range includes Brut Impérial, rosé and vintage cuvées.",
    story: "Claude Moët brought Champagne to a wider European audience; his grandson Jean-Rémy carried the house into international markets. The Impérial name recalls the family's association with Napoleon Bonaparte.",
    notes: ["Brut Impérial", "Apple, citrus and brioche give the house's best-known non-vintage Champagne its familiar lift.", "Rosé", "Red berries add a fruitier direction while the wine keeps its fine bubbles."],
    serve: "Chill well and pour into a tulip-shaped Champagne glass rather than a wide coupe.",
    food: "Pair with tandoori prawns, potato blinis or lightly spiced paneer skewers.",
    pairings: ["tandoori prawns", "potato blinis", "lightly spiced paneer skewers"],
    whyChoose: "A historic Épernay house with several clear routes into Champagne style.",
    faq: ["Where is Moët & Chandon based?", "The house is based in Épernay in France's Champagne region.", "When was Moët & Chandon founded?", "Claude Moët founded the house in 1743."],
    finalVerdict: "Moët & Chandon is strongest at the table when its acidity has seafood or lightly spiced snacks to work against.",
    metaDescription: "Explore Moët & Chandon Champagne, its Épernay history, Brut and rosé styles, and pairings. Compare city prices on BevOry.",
  }),
};
