import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_LOGOS_BATCH_16: Record<string, string> = {
  "1664": "https://static.livcheers.com/static/content/images/brand/1664.webp",
  "1800-tequila": "https://www.1800tequila.com/cdn/shop/files/1800-share-image.png?v=1780327979",
  "818-tequila": "https://static.livcheers.com/static/content/images/brand/818-tequila.webp",
  aberfeldy: "https://static.livcheers.com/static/content/images/brand/aberfeldy.webp",
  aberlour: "https://static.livcheers.com/static/content/images/brand/aberlour.webp",
  "aix-provence": "https://static.livcheers.com/static/content/images/brand/aix-provence.webp",
  "allan-scott": "https://static.livcheers.com/static/content/images/brand/allan-scott.webp",
  "allegrini-amarone": "https://static.livcheers.com/static/content/images/brand/allegrini-amarone.webp",
  "alta-vista": "https://static.livcheers.com/static/content/images/brand/alta-vista.webp",
  amarula: "https://dam.distell.co.za/asset/dc4330a0-ac13-4e08-8bc1-4b284ce632cb/Amarula-Logo-With-Shadow-2026.svg",
  amstel: "https://static.livcheers.com/static/content/images/brand/amstel.webp",
  angostura: "https://static.livcheers.com/static/content/images/brand/angostura.webp",
  "antiquity-blue": "https://static.livcheers.com/static/content/images/brand/antiquity-blue.webp",
  aperol: "https://static.livcheers.com/static/content/images/brand/aperol.webp",
  "appleton-estate": "https://www.appletonestate.com/app/uploads/sites/3/2025/09/logo-appleton-estate.webp",
  ardbeg: "https://static.livcheers.com/static/content/images/brand/ardbeg.webp",
  auchentoshan: "https://static.livcheers.com/static/content/images/brand/auchentoshan.webp",
  barefoot: "https://static.livcheers.com/static/content/images/brand/barefoot.webp",
  beefeater: "https://static.livcheers.com/static/content/images/brand/beefeater.webp",
  belvedere: "https://static.livcheers.com/static/content/images/brand/belvedere.webp",
};

export const BRAND_CONTENT_BATCH_16: Record<string, BrandPublicContent> = {
  "1664": {
    description: "1664 is a French beer label from the Kronenbourg brewing tradition, now owned by Carlsberg Group. Its range includes the crisp premium lager and 1664 Blanc, a hazy wheat beer made with orange peel, coriander and French hop character.",
    story: "Brewer Jerome Hatt established his brewery in Strasbourg in 1664, while Kronenbourg 1664 was introduced as a named beer in 1952. The Blanc recipe later gave the house a citrus-led wheat beer recognised by its blue bottle and pale golden haze.",
    tastingNotes: [
      { title: "1664 Blanc", description: "Orange peel, white peach and apricot meet coriander, soft wheat and a creamy, lightly bitter finish." },
      { title: "1664 Lager", description: "Pale malt, fresh bread and floral hops lead into a clean body with a dry, gently bitter close." },
    ],
    howToEnjoy: [
      { subheading: "Pour with room for foam", description: "Serve well chilled in a tall wheat-beer or lager glass, leaving space for a compact white head." },
      { subheading: "Use citrus and gentle spice", description: "Pair Blanc with fish tikka, chicken malai tikka, citrus salad or fried calamari." },
    ],
    pairingIdeas: [{ title: "French beer pairings", items: ["fish tikka", "chicken malai tikka", "citrus salad", "fried calamari", "soft goat cheese"] }],
    whyChoose: "1664 combines French lager heritage with a distinctive wheat beer built around citrus, coriander and soft texture.",
    faqs: [
      { question: "Why is the beer called 1664?", answer: "The date recalls the year Jerome Hatt founded the brewery that became associated with Kronenbourg in Strasbourg." },
      { question: "What gives 1664 Blanc its flavour?", answer: "Wheat, orange peel and coriander support its hazy body, citrus aroma and restrained bitterness." },
    ],
    finalVerdict: "1664 Blanc is the range's clearest signature, delivering bright citrus and wheat softness in an easy food-friendly pour.",
    metaTitle: "1664 French Beer Guide | BevOry",
    metaDescription: "Explore 1664 Blanc and lager, French brewing history, citrus flavours, serving tips, pairings and city prices on BevOry.",
  },
  "1800-tequila": {
    description: "1800 Tequila is a Jalisco tequila house owned by the Beckmann family and made from 100% Blue Weber agave. Mature agave from the Tequila Valley is brick-oven cooked, roller milled and double distilled in copper pot stills.",
    story: "The name marks 1800, the year the Beckmann family traces its early barrel ageing of tequila. Juan Beckmann Vidal introduced 1800 Anejo in the 1970s as Mexico's tequila denomination gained formal protection, placing aged agave spirit at the centre of the brand.",
    tastingNotes: [
      { title: "1800 Blanco", description: "Cooked agave, lime and white pepper open into green herbs and a clean mineral finish." },
      { title: "1800 Reposado", description: "Buttery caramel, vanilla and roasted agave meet cinnamon, orange peel and lightly toasted oak." },
    ],
    howToEnjoy: [
      { subheading: "Taste agave before mixing", description: "Sip Blanco or Reposado from a narrow agave glass, then use Blanco with fresh lime in a Margarita." },
      { subheading: "Connect roast with char", description: "Serve with tandoori prawns, lamb barbacoa, achari paneer, grilled corn or mole chicken." },
    ],
    pairingIdeas: [{ title: "Jalisco pairings", items: ["tandoori prawns", "lamb barbacoa", "achari paneer", "grilled corn", "mole chicken"] }],
    whyChoose: "1800 places slow-cooked Blue Weber agave and clearly differentiated oak ageing inside one coherent tequila range.",
    faqs: [
      { question: "Where is 1800 Tequila made?", answer: "It is produced in Jalisco, Mexico, from Blue Weber agave grown across the protected tequila region." },
      { question: "How long is 1800 Reposado aged?", answer: "The Reposado rests for roughly two to four months in new American and French oak barrels." },
    ],
    finalVerdict: "1800 is a precise agave-led range that moves cleanly from peppery Blanco to richer French-and-American-oak expressions.",
    metaTitle: "1800 Tequila Jalisco Guide | BevOry",
    metaDescription: "Discover 1800 Tequila, Blue Weber agave, brick-oven production, Blanco and Reposado notes and city prices on BevOry.",
  },
  "818-tequila": {
    description: "818 is a tequila brand founded by Kendall Jenner and produced at Grupo Solave in Amatitan, Jalisco. Blue Weber agave from Los Valles is slow cooked, tahona crushed, naturally fermented and double distilled in copper alembic pot stills.",
    story: "The brand takes its name from the 818 telephone area code in California's San Fernando Valley. Production moved to Grupo Solave in 2021, pairing traditional brick ovens and stone tahonas with detailed batch tracking and oak maturation for Reposado and Anejo.",
    tastingNotes: [
      { title: "818 Blanco", description: "Roasted agave, citrus and sweet herbs meet white pepper and a clean, lightly fruity finish." },
      { title: "818 Reposado", description: "Vanilla, caramel and cooked agave gain warm spice and a rounded texture from American and French oak." },
    ],
    howToEnjoy: [
      { subheading: "Keep the first pour neat", description: "Use a small agave glass for Blanco or Reposado, then shake Blanco with fresh lime for a restrained Margarita." },
      { subheading: "Bring acid and fire", description: "Pair with ceviche, chilli paneer, tandoori chicken, fish tacos or grilled pineapple." },
    ],
    pairingIdeas: [{ title: "Agave-friendly dishes", items: ["ceviche", "chilli paneer", "tandoori chicken", "fish tacos", "grilled pineapple"] }],
    whyChoose: "818 combines Los Valles agave with brick ovens, tahona extraction and copper pot distillation in a modern Jalisco range.",
    faqs: [
      { question: "Who founded 818 Tequila?", answer: "Kendall Jenner founded 818, naming it after the San Fernando Valley telephone area code." },
      { question: "Where is 818 Tequila produced?", answer: "It is produced at Grupo Solave in Amatitan, Jalisco, using agave from the Los Valles region." },
    ],
    finalVerdict: "818 offers a polished tequila style with visible traditional production steps and an agave-forward core.",
    metaTitle: "818 Tequila Jalisco Guide | BevOry",
    metaDescription: "Explore 818 Tequila, Los Valles agave, tahona production, Blanco and Reposado flavours, pairings and city prices on BevOry.",
  },
  aberfeldy: {
    description: "Aberfeldy is a Highland single malt made beside the Pitilie Burn in Perthshire and owned by Bacardi through John Dewar and Sons. Its waxy, honeyed spirit remains an important malt component of Dewar's blends while also supporting an age-stated single malt range.",
    story: "John Alexander and Tommy Dewar built Aberfeldy Distillery to designs by Charles Doig, and production began in 1898. The site expanded in 1972, joined Bacardi in 1998 and opened its visitor centre in 2000 alongside the release of Aberfeldy 12 Year Old.",
    tastingNotes: [
      { title: "Aberfeldy 12 Year", description: "Heather honey, orange and ripe pear meet vanilla, cereal and a soft touch of oak spice." },
      { title: "Aberfeldy 16 Year", description: "Richer honey, dried fruit and dark chocolate sit beside cinnamon, toasted oak and a longer finish." },
    ],
    howToEnjoy: [
      { subheading: "Give honeyed malt a narrow glass", description: "Serve neat in a tulip glass and add a few drops of water after the first sip to open the fruit and wax." },
      { subheading: "Pair sweetness with roast", description: "Try roast chicken, tandoori salmon, almond kheer, glazed pork or mature cheddar." },
    ],
    pairingIdeas: [{ title: "Highland malt pairings", items: ["roast chicken", "tandoori salmon", "almond kheer", "glazed pork", "mature cheddar"] }],
    whyChoose: "Aberfeldy is defined by a rounded Highland combination of honey, orchard fruit and supple waxy texture.",
    faqs: [
      { question: "Where is Aberfeldy whisky made?", answer: "It is distilled near Aberfeldy in Perthshire, using water drawn from the Pitilie Burn." },
      { question: "Who built Aberfeldy Distillery?", answer: "John Dewar's sons, John Alexander and Tommy Dewar, built the distillery, which began production in 1898." },
    ],
    finalVerdict: "Aberfeldy is a gentle but characterful Highland malt for drinkers drawn to honey, orange and polished oak rather than peat smoke.",
    metaTitle: "Aberfeldy Highland Whisky Guide | BevOry",
    metaDescription: "Explore Aberfeldy single malt, Dewar family history, honeyed Highland flavours, serving tips and city prices on BevOry.",
  },
  aberlour: {
    description: "Aberlour is a Speyside single malt founded by James Fleming beside the River Spey and the Lour Burn. American oak and Oloroso sherry casks shape much of the range, while A'bunadh presents a richer small-batch, sherry-led style.",
    story: "James Fleming established the present Aberlour Distillery in 1879 with the motto 'Let the deed show'. The distillery's double-cask approach developed into a house profile balancing orchard fruit and vanilla with raisins, spice and dark chocolate.",
    tastingNotes: [
      { title: "Aberlour 12 Year", description: "Red apple, honey and vanilla meet raisins, cinnamon and a rounded layer of sherry-seasoned oak." },
      { title: "A'bunadh", description: "Dried fruit, orange peel and dark chocolate build around baking spice, toasted nuts and substantial sherry richness." },
    ],
    howToEnjoy: [
      { subheading: "Add water in stages", description: "Use a tulip glass, taste neat and add water gradually, especially with the more powerful A'bunadh batches." },
      { subheading: "Bring dried fruit and spice", description: "Pair with mutton seekh, fruit cake, dark chocolate, roast duck or aged cheddar." },
    ],
    pairingIdeas: [{ title: "Sherry-cask pairings", items: ["mutton seekh", "fruit cake", "dark chocolate", "roast duck", "aged cheddar"] }],
    whyChoose: "Aberlour makes Speyside fruit more substantial through carefully managed American oak and Oloroso sherry casks.",
    faqs: [
      { question: "Who founded Aberlour Distillery?", answer: "James Fleming founded the present Speyside distillery in 1879." },
      { question: "What is Aberlour A'bunadh?", answer: "A'bunadh is a small-batch, sherry-cask-led single malt released without a standard age statement." },
    ],
    finalVerdict: "Aberlour is a rewarding Speyside malt for drinkers who prefer ripe fruit, sherry depth and warming spice.",
    metaTitle: "Aberlour Speyside Whisky Guide | BevOry",
    metaDescription: "Discover Aberlour single malt, James Fleming history, double-cask and A'bunadh flavours, pairings and city prices on BevOry.",
  },
  "aix-provence": {
    description: "AIX is the signature rose of Maison Saint Aix, a 75-hectare estate in the Coteaux d'Aix-en-Provence appellation. Grenache, Syrah and Cinsault grow in limestone-rich soils at elevation, tempered by cool nights and the Mistral wind.",
    story: "Maison Saint Aix occupies one of the higher vineyard sites north of Aix-en-Provence, near Sainte-Victoire mountain. The estate built AIX around its own fruit and a pale, dry Provence style that places freshness and mineral length ahead of sweetness.",
    tastingNotes: [
      { title: "AIX Rose", description: "Wild strawberry, raspberry and citrus meet white flowers, a silky mid-palate and a long mineral finish." },
      { title: "AIX White", description: "Pear, lime and white peach carry floral lift and saline freshness from Rolle, Sauvignon Blanc and Grenache Blanc." },
    ],
    howToEnjoy: [
      { subheading: "Chill without numbing it", description: "Serve at 8 to 10 degrees Celsius in a medium white-wine glass rather than a narrow flute." },
      { subheading: "Put Mediterranean food nearby", description: "Tandoori prawns, grilled fish, watermelon-feta salad, mezze and herb-roasted chicken suit its dry profile." },
    ],
    pairingIdeas: [{ title: "Provence pairings", items: ["tandoori prawns", "grilled fish", "watermelon-feta salad", "mezze", "herb-roasted chicken"] }],
    whyChoose: "AIX delivers the pale colour, red-fruit freshness and mineral finish expected from serious estate-grown Provence rose.",
    faqs: [
      { question: "Which grapes are used in AIX Rose?", answer: "The estate blends Grenache, Syrah and Cinsault for its signature Provence rose." },
      { question: "Where is Maison Saint Aix?", answer: "The estate lies in the Coteaux d'Aix-en-Provence appellation in southern France." },
    ],
    finalVerdict: "AIX is a dry, polished Provence rose whose freshness and quiet structure work from aperitif through a full meal.",
    metaTitle: "AIX Provence Rose Wine Guide | BevOry",
    metaDescription: "Explore AIX Provence rose, estate terroir, Grenache-led flavours, serving advice, food pairings and city prices on BevOry.",
  },
  "allan-scott": {
    description: "Allan Scott is a family winery on Jacksons Road in Marlborough, New Zealand, founded by Allan and Cathy Scott. Sauvignon Blanc leads a range that also includes Pinot Noir, Chardonnay, Riesling and traditional-method sparkling wine.",
    story: "Allan Scott helped plant some of Marlborough's early vines in 1973, bought his own vineyard block in 1975 and established the winery with Cathy in 1990. Their children Josh Scott and Sara Stocker bought the company in 2021 and now lead its production and vineyards.",
    tastingNotes: [
      { title: "Marlborough Sauvignon Blanc", description: "Passion fruit, gooseberry and lime meet fresh herbs and brisk, mouth-watering acidity." },
      { title: "Marlborough Pinot Noir", description: "Red cherry and raspberry sit beside dried herbs, fine tannin and a light savoury earthiness." },
    ],
    howToEnjoy: [
      { subheading: "Keep Sauvignon bright", description: "Serve Sauvignon Blanc at 8 to 10 degrees Celsius and Pinot Noir slightly cool in a broad glass." },
      { subheading: "Use green herbs and seafood", description: "Pair the white with tandoori fish, goat-cheese salad or green kebab, and Pinot Noir with roast duck or mushroom galouti." },
    ],
    pairingIdeas: [{ title: "Marlborough pairings", items: ["tandoori fish", "goat-cheese salad", "hara bhara kebab", "roast duck", "mushroom galouti"] }],
    whyChoose: "Allan Scott carries direct family experience from Marlborough's earliest vineyard plantings into a crisp, region-led wine range.",
    faqs: [
      { question: "Who founded Allan Scott wines?", answer: "Allan and Cathy Scott established the family winery in Marlborough in 1990." },
      { question: "Who runs Allan Scott today?", answer: "Second-generation siblings Josh Scott and Sara Stocker lead the family business." },
    ],
    finalVerdict: "Allan Scott is a dependable Marlborough name for vivid Sauvignon Blanc and carefully made cool-climate wines.",
    metaTitle: "Allan Scott Marlborough Wine Guide | BevOry",
    metaDescription: "Discover Allan Scott wines, Marlborough family history, Sauvignon Blanc and Pinot Noir notes and city prices on BevOry.",
  },
  "allegrini-amarone": {
    description: "Allegrini is a family wine producer in Fumane, within Valpolicella Classica in Italy's Veneto region. Corvina Veronese anchors Amarone, La Poja and the wider range, joined by Corvinone, Rondinella and Oseleta.",
    story: "The Allegrini family has cultivated vines around Fumane since the sixteenth century, while Giovanni Allegrini modernised the estate from the 1960s. Later generations refined appassimento drying, introduced barriques beside Slavonian oak and created the single-vineyard, pure-Corvina La Poja.",
    tastingNotes: [
      { title: "Amarone Classico", description: "Black cherry, dried plum and raisin meet cocoa, sweet spice and firm but polished tannin." },
      { title: "La Poja", description: "Pure Corvina brings ripe cherry, herbs and pepper over mineral freshness, fine oak and a long savoury finish." },
    ],
    howToEnjoy: [
      { subheading: "Decant the Amarone", description: "Give fuller bottles thirty to sixty minutes of air and serve at 16 to 18 degrees Celsius in a broad red-wine glass." },
      { subheading: "Choose slow-cooked depth", description: "Mutton rogan josh, braised lamb, wild-mushroom pasta, aged Parmigiano and dark chocolate match its concentration." },
    ],
    pairingIdeas: [{ title: "Valpolicella pairings", items: ["mutton rogan josh", "braised lamb", "wild-mushroom pasta", "aged Parmigiano", "dark chocolate"] }],
    whyChoose: "Allegrini combines Valpolicella's appassimento tradition with precise vineyard work and a clear focus on Corvina.",
    faqs: [
      { question: "Which grapes are in Allegrini Amarone?", answer: "Corvina Veronese, Corvinone, Rondinella and Oseleta form the Amarone blend." },
      { question: "What is appassimento?", answer: "It is the controlled drying of harvested grapes, concentrating sugar, flavour and structure before fermentation." },
    ],
    finalVerdict: "Allegrini Amarone delivers concentrated Valpolicella fruit with enough acidity and tannin to keep its power disciplined.",
    metaTitle: "Allegrini Amarone Wine Guide | BevOry",
    metaDescription: "Explore Allegrini Amarone, Valpolicella grapes, appassimento, La Poja, serving advice, pairings and city prices on BevOry.",
  },
  "alta-vista": {
    description: "Alta Vista is an Argentine winery founded by Count Patrick d'Aulan, with vineyard sites across Mendoza's leading Andean districts. Malbec is its defining grape, supported by Cabernet Sauvignon, Torrontes and traditional-method sparkling wine.",
    story: "Patrick d'Aulan arrived in Argentina in the 1990s after generations of family winemaking in France and established Alta Vista around the expression of individual sites. The winery restored an old Chacras de Coria cellar and helped advance the idea of single-vineyard Malbec in Mendoza.",
    tastingNotes: [
      { title: "Estate Malbec", description: "Blackberry, violet and ripe plum meet cocoa, pepper and smooth, dark-fruited tannin." },
      { title: "Single Vineyard Malbec", description: "Deeper black fruit, mineral tension and savoury spice show more structure and a longer oak-shaped finish." },
    ],
    howToEnjoy: [
      { subheading: "Give Malbec some air", description: "Serve at 16 to 18 degrees Celsius and decant the single-vineyard wines for twenty to thirty minutes." },
      { subheading: "Put flame beside fruit", description: "Pair with mutton seekh, grilled lamb chops, smoky paneer, beef empanadas or mushroom pepper fry." },
    ],
    pairingIdeas: [{ title: "Mendoza pairings", items: ["mutton seekh", "grilled lamb chops", "smoky paneer", "beef empanadas", "mushroom pepper fry"] }],
    whyChoose: "Alta Vista treats Malbec as a site-sensitive grape, separating Mendoza vineyards instead of blending away their differences.",
    faqs: [
      { question: "Who founded Alta Vista?", answer: "Count Patrick d'Aulan founded the winery after arriving in Argentina in the 1990s." },
      { question: "Which grape is Alta Vista known for?", answer: "Malbec is central to the estate, including several bottlings drawn from individual Mendoza vineyards." },
    ],
    finalVerdict: "Alta Vista is a useful window into Mendoza Malbec, moving from plush estate fruit to more structured single-site wines.",
    metaTitle: "Alta Vista Mendoza Wine Guide | BevOry",
    metaDescription: "Explore Alta Vista wines, Mendoza terroir, estate and single-vineyard Malbec notes, pairings and city prices on BevOry.",
  },
  amarula: {
    description: "Amarula is a South African cream liqueur made with spirit distilled from fermented marula fruit and blended with dairy cream. The range also includes coffee, chocolate-and-baobab and vanilla-spice expressions, plus an African gin.",
    story: "Marula fruit ripens during the South African summer and is gathered by local communities before fermentation and distillation. Amarula Cream was introduced in September 1989, building an international liqueur around a fruit long connected with food and drink traditions across southern Africa.",
    tastingNotes: [
      { title: "Amarula Cream", description: "Caramel, vanilla and ripe tropical fruit meet soft dairy richness and a gentle nutty finish." },
      { title: "Ethiopian Coffee", description: "Roasted coffee and cocoa deepen the marula fruit while cream rounds the bitter edge." },
    ],
    howToEnjoy: [
      { subheading: "Serve it cold", description: "Pour chilled or over one large cube in a short glass, or add a measured amount to iced coffee." },
      { subheading: "Treat it as dessert", description: "Pair with coffee kulfi, chocolate brownie, malva pudding, roasted hazelnuts or coconut cake." },
    ],
    pairingIdeas: [{ title: "Cream-liqueur pairings", items: ["coffee kulfi", "chocolate brownie", "malva pudding", "roasted hazelnuts", "coconut cake"] }],
    whyChoose: "Amarula turns distinctly South African marula fruit into a creamy liqueur with clear caramel and tropical-fruit character.",
    faqs: [
      { question: "Does Amarula contain real marula fruit?", answer: "Yes. The liqueur uses spirit distilled from fermented marula fruit." },
      { question: "Should opened Amarula be refrigerated?", answer: "The producer recommends refrigerating an opened bottle and consuming it within six months." },
    ],
    finalVerdict: "Amarula is a fruit-led cream liqueur that works best chilled, over ice or alongside coffee and chocolate desserts.",
    metaTitle: "Amarula South African Liqueur Guide | BevOry",
    metaDescription: "Discover Amarula cream liqueur, marula-fruit origins, tasting notes, dessert pairings, serving tips and city prices on BevOry.",
  },
  amstel: {
    description: "Amstel is a Dutch lager brand founded in Amsterdam and now owned by Heineken. The core beer is a clear golden lager with mild malt sweetness, gentle hop bitterness and a dry, uncomplicated finish.",
    story: "Friends and brothers-in-law Charles de Pesters and Johannes van Marwijk Kooy founded the Amstel brewery in 1870 after deciding to make a Bavaria-style lager they could both enjoy. The beer took its name from the Amstel River and grew from Amsterdam into an international lager family.",
    tastingNotes: [
      { title: "Classic lager", description: "Pale malt, fresh bread and light floral hops lead into clean carbonation and a mildly bitter close." },
      { title: "Amstel Light", description: "Gentle cereal and herbal notes keep the body lighter while retaining a crisp lager finish." },
    ],
    howToEnjoy: [
      { subheading: "Use a cold clean glass", description: "Serve well chilled in a tall lager glass with enough headspace for a neat cap of foam." },
      { subheading: "Bring crisp and salty food", description: "Masala fries, chicken wings, fish fry, grilled corn and chilli paneer fit the lager's light bitterness." },
    ],
    pairingIdeas: [{ title: "Lager pairings", items: ["masala fries", "chicken wings", "fish fry", "grilled corn", "chilli paneer"] }],
    whyChoose: "Amstel keeps Dutch lager simple: clean malt, moderate bitterness and enough carbonation for fried or grilled food.",
    faqs: [
      { question: "Where was Amstel founded?", answer: "Amstel was founded in Amsterdam in 1870 and named after the city's Amstel River." },
      { question: "Who founded Amstel beer?", answer: "Charles de Pesters and Johannes van Marwijk Kooy, friends and brothers-in-law, founded the brewery." },
    ],
    finalVerdict: "Amstel is a familiar golden lager whose crisp body and mild bitterness make it dependable with casual food.",
    metaTitle: "Amstel Dutch Lager Beer Guide | BevOry",
    metaDescription: "Explore Amstel lager, its 1870 Amsterdam history, crisp flavour, serving advice, food pairings and city prices on BevOry.",
  },
  angostura: {
    description: "Angostura is a Trinidad and Tobago drinks house known for aromatic bitters and a broad range of column-distilled rums. Its rums begin with molasses, proprietary yeast fermentation and continuous distillation before ageing in charred oak bourbon casks.",
    story: "German physician Johann Benjamin Siegert created his aromatic bitters in the Venezuelan town of Angostura in 1824. His family moved the business to Trinidad in the 1870s, while commercial rum production expanded at the Laventille distillery during the twentieth century.",
    tastingNotes: [
      { title: "Angostura 1919", description: "Vanilla, cocoa and caramel meet banana, toasted coconut and warm baking spice." },
      { title: "Aromatic Bitters", description: "Clove, cinnamon, bitter herbs and dried citrus deliver concentrated spice in a few measured dashes." },
    ],
    howToEnjoy: [
      { subheading: "Use rum and bitters together", description: "Sip aged rum over one cube or stir it into an Old Fashioned with aromatic and orange bitters." },
      { subheading: "Choose caramelised flavours", description: "Pair with jerk chicken, mutton roast, grilled pineapple, pecan tart or dark chocolate." },
    ],
    pairingIdeas: [{ title: "Trinidad rum pairings", items: ["jerk chicken", "mutton roast", "grilled pineapple", "pecan tart", "dark chocolate"] }],
    whyChoose: "Angostura unites one of the world's defining cocktail bitters with a complete Trinidadian rum-making operation.",
    faqs: [
      { question: "Where was Angostura bitters created?", answer: "Johann Benjamin Siegert developed it in 1824 in Angostura, the Venezuelan city now called Ciudad Bolivar." },
      { question: "Where is Angostura made today?", answer: "The company's bitters and rums are produced in Trinidad and Tobago." },
    ],
    finalVerdict: "Angostura belongs in both the cocktail cabinet and the rum glass, with concentrated bitters beside polished Trinidadian aged rum.",
    metaTitle: "Angostura Rum and Bitters Guide | BevOry",
    metaDescription: "Discover Angostura rum and bitters, Trinidad history, 1919 tasting notes, cocktail serves and city prices on BevOry.",
  },
  "antiquity-blue": {
    description: "Antiquity Blue is a premium Indian whisky from Diageo India, introduced in 1992. Select Indian malts are blended with Scotch malt and grain whisky connected with Cameronbridge, creating a malt-forward profile with wood, heather and restrained peat.",
    story: "The label draws on the grain-distilling legacy of Robert Stein, who worked at Cameronbridge in the early nineteenth century. Its cobalt-blue bottle became an Indian bar-cabinet landmark and was redesigned in 2023 around the heron emblem while retaining the established whisky blend.",
    tastingNotes: [
      { title: "Malt and oak", description: "Toasted malt, caramel and dried fruit sit beside polished wood, vanilla and a nutty undertone." },
      { title: "Heathered finish", description: "Pepper, heather and a light peat note bring warmth and dryness to the close." },
    ],
    howToEnjoy: [
      { subheading: "Begin with a neat measure", description: "Use a tulip or short whisky glass, then add a few drops of water or build a restrained soda highball." },
      { subheading: "Use char and spice", description: "Galouti kebab, pepper chicken, smoky paneer, roasted cashews and dark chocolate match its malt and wood." },
    ],
    pairingIdeas: [{ title: "Indian whisky pairings", items: ["galouti kebab", "pepper chicken", "smoky paneer", "roasted cashews", "dark chocolate"] }],
    whyChoose: "Antiquity Blue offers a distinctly malt-forward Indian blend with wood depth, heather and a measured peat accent.",
    faqs: [
      { question: "Who makes Antiquity Blue?", answer: "Antiquity Blue is made and marketed by Diageo India, also known as United Spirits Limited." },
      { question: "When was Antiquity Blue launched?", answer: "The whisky was established in 1992 and later received a major packaging redesign in 2023." },
    ],
    finalVerdict: "Antiquity Blue remains a characterful Indian blend for drinkers who prefer visible malt and oak over simple grain sweetness.",
    metaTitle: "Antiquity Blue Indian Whisky Guide | BevOry",
    metaDescription: "Explore Antiquity Blue whisky, Indian and Scotch components, malt and heather notes, pairings and city prices on BevOry.",
  },
  aperol: {
    description: "Aperol is an Italian bitter aperitivo created in Padua by brothers Luigi and Silvio Barbieri. Citrus peel, aromatic herbs, roots and woods produce its bright orange colour and lightly bitter profile, now owned by Campari Group.",
    story: "The Barbieri brothers spent seven years developing Aperol before presenting it at the Padua International Fair in 1919. Venetian bars helped establish the Aperol Spritz during the 1950s, and Campari Group acquired the label in 2003.",
    tastingNotes: [
      { title: "Citrus opening", description: "Sweet orange and citrus oil arrive first, joined by vanilla and a soft floral-herbal lift." },
      { title: "Bittersweet close", description: "Cinchona, gentian and woody herbs bring a measured bitterness that lingers without becoming severe." },
    ],
    howToEnjoy: [
      { subheading: "Build the classic Spritz", description: "Pour three parts Prosecco, two parts Aperol and one part soda over ice, then add an orange slice." },
      { subheading: "Set out aperitivo snacks", description: "Green olives, salted almonds, paneer crostini, bruschetta and fried calamari balance its sweetness." },
    ],
    pairingIdeas: [{ title: "Aperitivo pairings", items: ["green olives", "salted almonds", "paneer crostini", "bruschetta", "fried calamari"] }],
    whyChoose: "Aperol supplies the Spritz with vivid orange citrus, gentle herbal bitterness and a lighter aperitivo profile.",
    faqs: [
      { question: "Who invented Aperol?", answer: "Luigi and Silvio Barbieri created Aperol in Padua and launched it in 1919." },
      { question: "What is the Aperol Spritz ratio?", answer: "The standard recipe uses three parts Prosecco, two parts Aperol and one part soda." },
    ],
    finalVerdict: "Aperol is an approachable Italian aperitivo whose orange sweetness and gentle bitterness come alive with bubbles and salty snacks.",
    metaTitle: "Aperol Italian Aperitivo Guide | BevOry",
    metaDescription: "Explore Aperol, its 1919 Padua history, bittersweet orange flavour, Spritz recipe, pairings and city prices on BevOry.",
  },
  "appleton-estate": {
    description: "Appleton Estate is a Jamaican rum producer in Nassau Valley, making rum from sugarcane molasses through both copper pot and column distillation. Tropical ageing and the estate's proprietary yeast contribute ripe fruit, orange peel and molasses-rich depth.",
    story: "Rum production at Appleton Estate is documented from 1749, and the Lindo family brought the estate and J. Wray and Nephew together in 1916. Joy Spence joined as chief chemist in 1981 and became the spirits industry's first female master blender in 1997.",
    tastingNotes: [
      { title: "Signature Blend", description: "Orange peel, dried apricot and molasses meet vanilla, toasted nuts and a softly spiced finish." },
      { title: "8 Year Reserve", description: "Ripe fruit, cocoa and oak deepen into baking spice, honey and a longer, drier close." },
    ],
    howToEnjoy: [
      { subheading: "Let aged rum breathe", description: "Sip the 8 Year in a tulip glass or over one large cube, and use Signature in a Daiquiri or Mai Tai." },
      { subheading: "Match Jamaican intensity", description: "Jerk chicken, pork ribs, mutton roast, grilled pineapple and rum cake suit its fruit and molasses." },
    ],
    pairingIdeas: [{ title: "Jamaican rum pairings", items: ["jerk chicken", "pork ribs", "mutton roast", "grilled pineapple", "rum cake"] }],
    whyChoose: "Appleton Estate combines Jamaican pot-still character, tropical maturation and one of rum's most influential blending teams.",
    faqs: [
      { question: "Where is Appleton Estate rum made?", answer: "It is made at Appleton Estate in Jamaica's Nassau Valley." },
      { question: "Who is Joy Spence?", answer: "She became Appleton Estate's master blender in 1997 after joining the company as chief chemist in 1981." },
    ],
    finalVerdict: "Appleton Estate is a benchmark Jamaican rum range with ripe fruit, orange peel and pot-still weight held in careful balance.",
    metaTitle: "Appleton Estate Jamaican Rum Guide | BevOry",
    metaDescription: "Discover Appleton Estate rum, Nassau Valley production, Joy Spence, tasting notes, pairings and city prices on BevOry.",
  },
  ardbeg: {
    description: "Ardbeg is a heavily peated Islay single malt made on the island's southern coast and owned by the Glenmorangie Company within LVMH. Malt peated to at least 55 parts per million, Loch Uigeadail water and a spirit-still purifier produce powerful smoke with citrus and sweetness underneath.",
    story: "John Macdougall licensed Ardbeg Distillery in 1815, and Margaret and Flora Macdougall later helped run it during the nineteenth century. After closures in 1981 and 1991, Glenmorangie bought and revived the distillery in 1997 before launching Ardbeg Ten in 2000.",
    tastingNotes: [
      { title: "Ardbeg Ten", description: "Lemon, tar and bonfire smoke meet sea salt, black pepper and vanilla over a surprisingly sweet malt core." },
      { title: "Uigeadail", description: "Raisin, espresso and dark chocolate fold into dense peat smoke, spice and sherry-cask richness." },
    ],
    howToEnjoy: [
      { subheading: "Approach the peat slowly", description: "Use a tulip glass, nose at a little distance and add water a few drops at a time after tasting neat." },
      { subheading: "Bring smoke to the plate", description: "Tandoori lamb, smoked salmon, charred aubergine, blue cheese and dark chocolate can meet its intensity." },
    ],
    pairingIdeas: [{ title: "Islay smoke pairings", items: ["tandoori lamb", "smoked salmon", "charred aubergine", "blue cheese", "dark chocolate"] }],
    whyChoose: "Ardbeg delivers one of Islay's most forceful peat profiles while preserving citrus, salt and an unexpected current of sweetness.",
    faqs: [
      { question: "Is Ardbeg heavily peated?", answer: "Yes. Its malt is peated to at least 55 parts per million before distillation." },
      { question: "When was Ardbeg Distillery founded?", answer: "John Macdougall established the licensed distillery on Islay in 1815." },
    ],
    finalVerdict: "Ardbeg is uncompromising Islay whisky, yet its best bottles balance medicinal peat with citrus, sweetness and maritime salt.",
    metaTitle: "Ardbeg Islay Single Malt Guide | BevOry",
    metaDescription: "Explore Ardbeg Islay whisky, heavy peat, Ten and Uigeadail tasting notes, serving advice and city prices on BevOry.",
  },
  auchentoshan: {
    description: "Auchentoshan is a Lowland single malt made near Glasgow and distinguished by triple distillation of every drop. Unpeated malt and a third copper-pot distillation create a light spirit that takes clearly to bourbon, sherry and wine casks.",
    story: "The distillery dates to 1823 and sits at the foot of the Kilpatrick Hills on Glasgow's edge. Its commitment to three stills raises the new spirit to roughly 81 percent alcohol before maturation, leaving a clean base for fruit and oak.",
    tastingNotes: [
      { title: "American Oak", description: "Lemon, coconut and vanilla meet white peach, soft cereal and a clean oak finish." },
      { title: "Three Wood", description: "Blackcurrant, plum and raisin deepen into hazelnut, cinnamon, butterscotch and sweet oak." },
    ],
    howToEnjoy: [
      { subheading: "Try three drops of water", description: "Taste in a tulip glass, then add a small amount of water or serve American Oak in a citrus-led highball." },
      { subheading: "Pair fruit with gentle spice", description: "Chicken malai tikka, roast duck, mushroom tart, lemon cake and hazelnut praline suit the whisky's light spirit." },
    ],
    pairingIdeas: [{ title: "Lowland pairings", items: ["chicken malai tikka", "roast duck", "mushroom tart", "lemon cake", "hazelnut praline"] }],
    whyChoose: "Auchentoshan's triple distillation gives Lowland fruit and citrus a lighter frame for expressive cask finishes.",
    faqs: [
      { question: "Why is Auchentoshan triple distilled?", answer: "The third distillation creates a lighter, cleaner spirit that reaches about 81 percent before cask filling." },
      { question: "Is Auchentoshan peated?", answer: "Its core spirit is made from gently kilned, unpeated malted barley." },
    ],
    finalVerdict: "Auchentoshan is a bright Lowland malt whose triple-distilled spirit makes bourbon and sherry cask differences easy to recognise.",
    metaTitle: "Auchentoshan Lowland Whisky Guide | BevOry",
    metaDescription: "Discover Auchentoshan whisky, triple distillation, American Oak and Three Wood flavours, pairings and city prices on BevOry.",
  },
  barefoot: {
    description: "Barefoot is a California wine brand owned by E and J Gallo, covering still, sparkling and fruit-flavoured wines. Moscato, Pinot Grigio, Chardonnay, Cabernet Sauvignon and Merlot form the familiar core of its soft, fruit-forward range.",
    story: "The Barefoot name first appeared on California wine in the 1960s and was reshaped by Michael Houlihan and Bonnie Harvey from 1986. E and J Gallo acquired the label in 2005 and expanded it into a broad international wine portfolio.",
    tastingNotes: [
      { title: "Barefoot Moscato", description: "Peach, apricot and orange blossom lead a sweet, juicy palate with gentle citrus freshness." },
      { title: "Barefoot Cabernet Sauvignon", description: "Blackberry and blackcurrant meet vanilla, soft tannin and a touch of toasted oak." },
    ],
    howToEnjoy: [
      { subheading: "Set sweetness against spice", description: "Serve Moscato well chilled and pour red wines slightly cool in a medium glass." },
      { subheading: "Split sweet and savoury", description: "Moscato works with chilli paneer or fruit tart, while Cabernet suits barbecue chicken, burgers or mushroom kebab." },
    ],
    pairingIdeas: [{ title: "Easy-going wine pairings", items: ["chilli paneer", "fruit tart", "barbecue chicken", "beef burger", "mushroom kebab"] }],
    whyChoose: "Barefoot offers immediately recognisable grape styles with generous fruit and little need for formal wine knowledge.",
    faqs: [
      { question: "Who owns Barefoot wine?", answer: "Barefoot belongs to the California wine company E and J Gallo." },
      { question: "Is Barefoot Moscato sweet?", answer: "Yes. It is a sweet, fruit-led wine with peach, apricot and floral notes." },
    ],
    finalVerdict: "Barefoot is an accessible California range for drinkers who favour clear fruit, soft texture and straightforward serving.",
    metaTitle: "Barefoot California Wine Guide | BevOry",
    metaDescription: "Explore Barefoot wine, Moscato and Cabernet flavours, California history, serving advice, pairings and city prices on BevOry.",
  },
  beefeater: {
    description: "Beefeater is a London Dry gin created by pharmacist James Burrough and still distilled in Kennington, London. Juniper leads a nine-botanical recipe that includes Sicilian lemon peel, Seville orange peel, coriander, angelica and liquorice.",
    story: "James Burrough acquired a Chelsea distillery in 1863 and developed the gin that became Beefeater, named after the Yeoman Warders at the Tower of London. Production moved to the present Kennington site in the 1950s, where vintage pot stills remain in use.",
    tastingNotes: [
      { title: "London Dry", description: "Firm juniper and lemon peel meet coriander spice, earthy angelica and a dry citrus finish." },
      { title: "Beefeater 24", description: "Grapefruit and tea add aromatic lift to the juniper core, with cleaner spice and a longer close." },
    ],
    howToEnjoy: [
      { subheading: "Keep the tonic crisp", description: "Pour over hard ice with dry tonic and lemon, or stir into a cold Martini with fresh vermouth." },
      { subheading: "Use citrus and herbs", description: "Tandoori prawns, coriander chicken, goat-cheese salad, lemon-pepper paneer and smoked salmon fit its dry profile." },
    ],
    pairingIdeas: [{ title: "London gin pairings", items: ["tandoori prawns", "coriander chicken", "goat-cheese salad", "lemon-pepper paneer", "smoked salmon"] }],
    whyChoose: "Beefeater is a juniper-forward London Dry with enough citrus and root spice for both tonic and classic cocktails.",
    faqs: [
      { question: "Where is Beefeater gin made?", answer: "It is distilled in Kennington, London, using copper pot stills and a nine-botanical recipe." },
      { question: "Who created Beefeater gin?", answer: "James Burrough developed the recipe after entering the London spirits trade in the nineteenth century." },
    ],
    finalVerdict: "Beefeater remains a reference London Dry gin: firm juniper, bright citrus and a genuinely useful cocktail structure.",
    metaTitle: "Beefeater London Dry Gin Guide | BevOry",
    metaDescription: "Explore Beefeater gin, James Burrough history, nine botanicals, Martini and tonic serves, pairings and city prices on BevOry.",
  },
  belvedere: {
    description: "Belvedere is a Polish vodka made at the Polmos Zyrardow distillery from Polish rye and purified water drawn from the distillery's own wells. Its character leans toward soft cream, white pepper and almond rather than complete neutrality.",
    story: "The Zyrardow distillery was established in 1910, while Belvedere was created in 1993 and named for Warsaw's Belweder Palace. The bottle's palace illustration connects the modern luxury label with its Polish origin and centuries of rye-vodka tradition.",
    tastingNotes: [
      { title: "Pure rye profile", description: "Soft cream and vanilla meet white pepper, almond and a clean mineral finish." },
      { title: "Organic Infusions", description: "Fruit, herbs and spice add natural aromatic layers while rye remains visible underneath." },
    ],
    howToEnjoy: [
      { subheading: "Serve cool, not frozen solid", description: "Use a small stemmed glass for a chilled neat pour or stir with dry vermouth in a Vodka Martini." },
      { subheading: "Pick clean salty food", description: "Smoked salmon, potato blini, salted cucumber, tandoori prawns and mushroom pierogi suit its rye texture." },
    ],
    pairingIdeas: [{ title: "Polish vodka pairings", items: ["smoked salmon", "potato blini", "salted cucumber", "tandoori prawns", "mushroom pierogi"] }],
    whyChoose: "Belvedere preserves a clear rye signature, giving premium vodka more texture and spice than a purely neutral spirit.",
    faqs: [
      { question: "What is Belvedere vodka made from?", answer: "It is made in Poland from Polish rye and water sourced from the distillery's own wells." },
      { question: "Where is Belvedere produced?", answer: "Belvedere is produced at the Polmos Zyrardow distillery west of Warsaw, Poland." },
    ],
    finalVerdict: "Belvedere is polished Polish rye vodka with enough cream, pepper and almond character to reward a simple chilled pour.",
    metaTitle: "Belvedere Polish Vodka Guide | BevOry",
    metaDescription: "Discover Belvedere vodka, Polish rye, Zyrardow history, tasting notes, Martini serves, pairings and city prices on BevOry.",
  },
};
