import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_51 = [
  ["old-admiral", "Old Admiral", "Brandy"], ["regal-talon", "Regal Talon", "Whisky"],
  ["whytehall", "Whytehall", "Brandy"], ["pluton-bay", "Pluton Bay", "Rum"],
  ["ankahi", "Ankahi", "Liqueur"], ["morpheus-blue", "Morpheus Blue", "Brandy"],
  ["zinzi", "Zinzi", "Wine"], ["vinsura", "Vinsura", "Wine"],
  ["magic-moments", "Magic Moments", "Vodka"], ["johnnie-walker", "Johnnie Walker", "Whisky"],
  ["virgin-hills", "Virgin Hills", "Wine"], ["sensi", "Sensi", "Wine"],
  ["old-monk", "Old Monk", "Rum"], ["macallan", "The Macallan", "Whisky"],
  ["mcdowells", "McDowell's", "Whisky"], ["piccini", "Piccini", "Wine"],
  ["kingfisher", "Kingfisher", "Beer"], ["gancia", "Gancia", "Wine"],
  ["jacobs-creek", "Jacob's Creek", "Wine"], ["maharani", "Maharani Mahansar", "Liqueur"],
  ["folonari", "Folonari", "Wine"], ["tuborg", "Tuborg", "Beer"],
  ["paul-john", "Paul John", "Whisky"], ["patron", "Patrón", "Tequila"],
  ["yellow-tail", "Yellow Tail", "Wine"], ["fishing-cat", "Fishing Cat", "Wine"],
  ["paladin", "Paladin", "Wine"], ["luxardo", "Luxardo", "Liqueur"],
  ["woodbridge", "Woodbridge", "Wine"], ["camas", "Camas", "Wine"],
] as const;

// Research links are internal; none are rendered in public copy.
export const BRAND_SOURCES_BATCH_51: Record<string, string[]> = {
  "old-admiral": ["https://radicokhaitan.com/products/old-admiral-brandy/", "https://radicokhaitan.com/about-us/what-we-do/"],
  "regal-talon": ["https://www.radicokhaitan.com/wp-content/uploads/2022/09/Annual-Report-RKL-2022.pdf"],
  whytehall: ["https://www.radicokhaitan.com/wp-content/uploads/2022/09/Annual-Report-RKL-2022.pdf"],
  "pluton-bay": ["https://www.radicokhaitan.com/wp-content/uploads/2019/03/Annual-Report-FY2017.pdf"],
  ankahi: ["https://radicokhaitan.com/wp-content/uploads/2025/03/Press-Release-March-17-2025.pdf"],
  "morpheus-blue": ["https://radicokhaitan.com/products/morpheus-blue-xo-premium-brandy/"],
  zinzi: ["https://www.diageoindia.com/en/news-and-media/press-releases/2019/usl-enters-into-a-share-purchase-agreement-for-the-sale-of-equity-shares-in-four-seasons", "https://www.business-standard.com/article/press-releases/zinzi-is-back-in-karnataka-at-a-new-and-attractive-price-110122300150_1.html"],
  vinsura: ["https://vinsurawines.com/"],
  "magic-moments": ["https://radicokhaitan.com/products/magic-moments/"],
  "johnnie-walker": ["https://www.johnniewalker.com/en-us", "https://www.johnniewalker.com/en-us/our-story"],
  "virgin-hills": ["https://www.virginhillswines.com/our-mission"],
  sensi: ["https://www.sensivini.it/en/company-en/"],
  "old-monk": ["https://mohanmeakin.com/rums/", "https://mohanmeakin.com/history/"],
  macallan: ["https://www.themacallan.com/en/about"],
  mcdowells: ["https://www.diageoindia.com/en/news-and-media/stories/2024/risen-from-the-mist-mcdowells-co-reinvents-its-legacy"],
  piccini: ["https://www.piccini1882.it/en/family-history/"],
  kingfisher: ["https://www.unitedbreweries.com/pdf/InvestorReport/UB-Annual-Financial-Report-2021-2022.pdf"],
  gancia: ["https://gancia.com/en/casa-gancia/la-nostra-storia/origini/"],
  "jacobs-creek": ["https://jacobscreek.com/"],
  maharani: ["https://maharanimahansar.in/"],
  folonari: ["https://folonariwines.com/"],
  tuborg: ["https://www.tuborg.com/en"],
  "paul-john": ["https://pauljohnwhisky.com/our-story.php"],
  patron: ["https://www.patrontequila.com/our-story/tequila-guide.html"],
  "yellow-tail": ["https://www.yellowtailwine.com/"],
  "fishing-cat": ["https://fishingcat.it/"],
  paladin: ["https://www.paladin.it/en/winery/history/"],
  luxardo: ["https://www.luxardo.it/history/"],
  woodbridge: ["https://www.woodbridgewines.com/"],
  camas: ["https://www.annedejoyeuse.fr/en/a-generous-range-of-wines-for-every-occasions/camas/"],
};

// These brand marks were visually checked; the old slug URLs return 403.
export const BRAND_LOGOS_BATCH_51: Record<string, string> = {
  "morpheus-blue": "https://static.livcheers.com/static/content/images/brand/morpheus.webp",
  piccini: "https://www.winesellersltd.com/wp-content/uploads/2023/06/Piccini_logo.png",
};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_51: Record<string, BrandPublicContent> = {
  "old-admiral": guide("Old Admiral", "Brandy", {
    description: "Old Admiral is an Indian brandy from Radico Khaitan, the company behind Rampur Distillery in Uttar Pradesh. It sits in the producer's longstanding domestic spirits range.",
    story: "Radico introduced Old Admiral in 2002, after beginning its own branded spirits business with 8PM Whisky. The name and naval imagery gave a mass-market brandy a distinct identity in a crowded category.",
    notes: ["Aromatic warmth", "The house describes a rich aroma and a rounded, warming character.", "Brandy finish", "A smooth, lingering impression makes it suited to a short pour after food."],
    serve: "Pour a small measure into a tulip glass; a little water can soften the warmth.",
    food: "Try it with roasted cashews, plum cake or pepper chicken.",
    pairings: ["roasted cashews", "plum cake", "pepper chicken"],
    whyChoose: "A familiar Indian brandy with a clear place in Radico's own-brand history.",
    faq: ["Who makes Old Admiral?", "Radico Khaitan makes Old Admiral Brandy in India.", "When did Old Admiral launch?", "Radico lists 2002 as its launch year."],
    finalVerdict: "Old Admiral is at its best as an uncomplicated after-dinner brandy with something savoury or sweet alongside.",
    metaDescription: "Explore Old Admiral brandy, its Radico history, serving ideas and Indian pairings. Compare city prices on BevOry.",
  }),
  "regal-talon": guide("Regal Talon", "Whisky", {
    description: "Regal Talon is a premium grain whisky from India's Radico Khaitan. Radico describes a blend of Indian grain spirit and imported Scotch malt.",
    story: "The label arrived as Radico moved beyond its original 8PM whisky into more premium domestic expressions. Its eagle motif and grain-led blend give it a different brief from the company's Rampur single malts.",
    notes: ["Fruit and wood", "Radico notes fruity and woody aromas in the grain-and-malt blend.", "Light peat", "A restrained peaty, slightly salty accent appears in the producer's tasting description."],
    serve: "Taste a small pour neat, then add a little water or pour over ice.",
    food: "Pair with mutton seekh, tandoori mushrooms or salted peanuts.",
    pairings: ["mutton seekh", "tandoori mushrooms", "salted peanuts"],
    whyChoose: "A grain-forward Indian blend with a gentle peaty edge.",
    faq: ["Is Regal Talon a single malt?", "No. Radico describes it as a blend of Indian grain spirit and imported Scotch malt.", "Who makes Regal Talon?", "It belongs to Radico Khaitan's Indian whisky portfolio."],
    finalVerdict: "Regal Talon suits drinkers who want a light touch of smoke in an Indian blended whisky.",
    metaDescription: "Meet Regal Talon whisky: Indian grain, Scotch malt, serving ideas and food pairings. Compare city prices on BevOry.",
  }),
  whytehall: guide("Whytehall", "Brandy", {
    description: "Whytehall is a premium Indian brandy in Radico Khaitan's portfolio. It is positioned as a rounded, fruit-led after-dinner pour.",
    story: "Radico's range spans everyday spirits and higher-priced labels; Whytehall occupies the brandy side of that family. The company's annual report describes its opening as round and fruity, followed by a longer finish.",
    notes: ["Fruit first", "The producer describes a rounded fruit impression at the start.", "Longer close", "The finish is presented as elegant and persistent rather than sharply spiced."],
    serve: "Give a modest pour a few minutes in a small brandy glass.",
    food: "Serve after masala roast chicken, or alongside fruit cake and toasted almonds.",
    pairings: ["masala roast chicken", "fruit cake", "toasted almonds"],
    whyChoose: "A fruit-led brandy in Radico's domestic premium range.",
    faq: ["Is Whytehall a brandy or whisky?", "The current Radico portfolio lists Whytehall as brandy; older company material also refers to a Whytehall whisky.", "Who owns Whytehall?", "Whytehall is part of Radico Khaitan's Indian spirits portfolio."],
    finalVerdict: "Whytehall is a quiet after-dinner option for drinkers who favour fruit over heavy oak.",
    metaDescription: "Read about Whytehall brandy, its fruit-led style and food pairings. Compare city prices on BevOry.",
  }),
  "pluton-bay": guide("Pluton Bay", "Rum", {
    description: "Pluton Bay is a dark Indian rum from Radico Khaitan. The producer describes a blend of aged cane juice and neutral spirits.",
    story: "Pluton Bay joined Radico's range during its push into premium spirits beyond whisky and vodka. Its nautical name points to a rum tradition, while the brand remains a separate Radico label rather than a Contessa expression.",
    notes: ["Spiced aroma", "Radico describes the rum as spicy and dark brown.", "Smoother texture", "The aged cane-juice component gives the blend a rounded impression in a mixed drink."],
    serve: "Use a measured pour with ice and ginger ale or cola; finish with lime.",
    food: "Put it beside chilli chicken, grilled pineapple or spicy peanuts.",
    pairings: ["chilli chicken", "grilled pineapple", "spicy peanuts"],
    whyChoose: "A separate Radico rum label for a straightforward mixed serve.",
    faq: ["Who makes Pluton Bay?", "Pluton Bay is a Radico Khaitan rum brand.", "Is Pluton Bay the same as Contessa?", "No. They are separate rum labels within Radico's portfolio."],
    finalVerdict: "Pluton Bay works best when you want a simple rum highball with salty food.",
    metaDescription: "Explore Pluton Bay rum from Radico Khaitan, with serving ideas and Indian snack pairings. Compare city prices on BevOry.",
  }),
  ankahi: guide("Ankahi", "Liqueur", {
    description: "Ankahi is Radico Khaitan's saffron-led spiced liqueur. Its Zaffran expression combines Kashmiri saffron with Indian herbs and spices.",
    story: "Radico introduced Ankahi Zaffran in 2025 as an Indian botanical liqueur for international markets. Its name means 'untold', while the recipe draws on saffron's longstanding place in Kashmiri food and culture.",
    notes: ["Saffron", "A floral saffron aroma leads the Zaffran expression.", "Warm spice", "Cardamom, cinnamon and clove sit beneath its gentle sweetness."],
    serve: "Pour a small measure over ice or lengthen it with cold soda.",
    food: "Try with saffron phirni, pistachio kulfi or salted almonds.",
    pairings: ["saffron phirni", "pistachio kulfi", "salted almonds"],
    whyChoose: "A saffron-centred liqueur with a distinctly Indian spice palette.",
    faq: ["What is Ankahi Zaffran?", "It is a saffron and herb spiced liqueur from Radico Khaitan.", "Which spices appear in Ankahi?", "Radico names saffron, cardamom, cinnamon, clove and other botanicals in the Zaffran recipe."],
    finalVerdict: "Ankahi Zaffran offers a small, aromatic pour that sits naturally beside Indian desserts.",
    metaDescription: "Discover Ankahi Zaffran's saffron and spice character, serving ideas and dessert pairings. Compare city prices on BevOry.",
  }),
  "morpheus-blue": guide("Morpheus Blue", "Brandy", {
    description: "Morpheus Blue XO is a premium Indian brandy from Radico Khaitan. The Blue expression extends the producer's Morpheus brandy family.",
    story: "Radico added Morpheus Blue after the original Morpheus premium brandy. Its name borrows from Morpheus, the Greek figure associated with dreams, while the producer gives this expression a richer fruit-and-oak brief.",
    notes: ["Dried fruit", "Raisin, prune and nuts feature in Radico's description of the aroma.", "Honey and oak", "The palate is presented as full-bodied, with honey, vanilla and caramel."],
    serve: "Pour into a small snifter and let it settle for a minute before tasting.",
    food: "Pair with walnut cake, dark chocolate or smoky mutton kebabs.",
    pairings: ["walnut cake", "dark chocolate", "mutton kebabs"],
    whyChoose: "A fuller Morpheus brandy with the producer's own dried-fruit and oak notes.",
    faq: ["Is Morpheus Blue whisky?", "No. Morpheus Blue XO is a brandy; Radico also sells a separate Morpheus whisky.", "What does Morpheus Blue taste like?", "Radico describes dried fruit, honey, vanilla and caramel in the Blue XO expression."],
    finalVerdict: "Morpheus Blue XO makes sense as a slower after-dinner brandy with a rich dessert.",
    metaDescription: "Explore Morpheus Blue XO brandy, from dried-fruit notes to serving and food pairings. Compare city prices on BevOry.",
  }),
  zinzi: guide("Zinzi", "Wine", {
    description: "Zinzi is an Indian wine label associated with Four Seasons Wines in Maharashtra. It has appeared in red and white styles within the company's portfolio.",
    story: "Four Seasons Wines developed Zinzi alongside its namesake label before the business changed hands in 2019. The wine sits in the story of Maharashtra's growing domestic wine market, rather than in a separate European appellation.",
    notes: ["Red wine", "The red side of Zinzi offers a fruit-led table wine style.", "White wine", "A chilled white gives a lighter counterpart for spiced food."],
    serve: "Chill a white well; pour a red slightly cool in an ordinary wine glass.",
    food: "Match the white with paneer tikka and the red with tomato pasta or pepper chicken.",
    pairings: ["paneer tikka", "tomato pasta", "pepper chicken"],
    whyChoose: "A Maharashtra wine label linked to the Four Seasons story.",
    faq: ["Is Zinzi an Indian wine?", "Yes. Zinzi was a label of India's Four Seasons Wines.", "Does Zinzi make both red and white wine?", "The label has been sold in both red and white styles."],
    finalVerdict: "Zinzi is a simple route into Indian table wine for a meal with spice.",
    metaDescription: "Explore Zinzi Indian wine, its Four Seasons connection and food pairings. Compare city prices on BevOry.",
  }),
  vinsura: guide("Vinsura", "Wine", {
    description: "Vinsura makes Indian wine at Vinchur Wine Park in Nashik, Maharashtra. Its vineyards grow Cabernet Sauvignon, Syrah and Chenin Blanc, among other grapes.",
    story: "The name joins Vinchur with 'sura', a Sanskrit word for wine. Vinsura was started by farmers, and its winery in the Vinchur area keeps that vineyard-led identity close to home.",
    notes: ["Cabernet Syrah", "The red blend brings dark fruit and a firmer frame to the range.", "Chenin Blanc", "The white side is lighter and more refreshing at the table."],
    serve: "Serve Chenin chilled; let a Cabernet-Syrah red warm a little in the glass.",
    food: "Try Chenin with tandoori prawns and the red blend with mutton seekh or mushroom masala.",
    pairings: ["tandoori prawns", "mutton seekh", "mushroom masala"],
    whyChoose: "A Nashik winery whose name and vineyards are rooted in Vinchur.",
    faq: ["Where is Vinsura wine made?", "Vinsura's winery is at Vinchur Wine Park in the Nashik district.", "Which grapes does Vinsura grow?", "Its listed varieties include Cabernet Sauvignon, Syrah, Chenin Blanc and Sauvignon Blanc."],
    finalVerdict: "Vinsura rewards a look beyond Nashik's best-known names, especially with food on the table.",
    metaDescription: "Meet Vinsura wines from Vinchur, Nashik. Explore grapes, serving ideas and pairings; compare city prices on BevOry.",
  }),
  "magic-moments": guide("Magic Moments", "Vodka", {
    description: "Magic Moments is a grain-based Indian vodka from Radico Khaitan. The range includes the original vodka and flavoured expressions.",
    story: "Radico launched Magic Moments in 2006 as it expanded beyond whisky and brandy. The producer describes a triple-distillation process, giving the brand a clear production identity in India's vodka market.",
    notes: ["Original", "The unflavoured vodka is designed to stay clean and neutral in a mixed drink.", "Flavoured range", "Fruit-led expressions give different cocktail directions without changing the brand's grain-vodka base."],
    serve: "Chill the bottle and pour with soda and lime, or use it in a measured citrus cocktail.",
    food: "Set it beside chilli paneer, tandoori fish or salted peanuts.",
    pairings: ["chilli paneer", "tandoori fish", "salted peanuts"],
    whyChoose: "A widely recognised Indian vodka built on grain spirit and triple distillation.",
    faq: ["Who makes Magic Moments?", "Radico Khaitan makes Magic Moments Vodka.", "Is Magic Moments made from grain?", "Yes. Radico describes its vodka as grain-based and triple-distilled."],
    finalVerdict: "Magic Moments earns its place in a cold, simple drink that leaves room for the food.",
    metaDescription: "Explore Magic Moments vodka, its grain base, flavoured range and serving ideas. Compare city prices on BevOry.",
  }),
  "johnnie-walker": guide("Johnnie Walker", "Whisky", {
    description: "Johnnie Walker is a Scotch blended-whisky house owned by Diageo. Its colour-named range runs from Red Label through Black Label and Blue Label, with different blends for different serves.",
    story: "The business traces back to John Walker's grocery shop in Kilmarnock, Scotland. His family's blending trade turned a local merchant name into the striding-man whisky label known worldwide.",
    notes: ["Red Label", "The blend is lively and built to hold its shape with a mixer.", "Black Label", "A rounder style brings fruit, vanilla and a measured smoky note."],
    serve: "Try Red Label with ginger ale; pour Black Label neat or with a small splash of water.",
    food: "Bring Black Label to galouti kebabs and Red Label highballs to masala peanuts.",
    pairings: ["galouti kebabs", "masala peanuts", "aged cheddar"],
    whyChoose: "A Scotch blending house with recognisably different bottles for a highball or a slow pour.",
    faq: ["Is Johnnie Walker single malt?", "No. The main Johnnie Walker range consists of blended Scotch whiskies.", "Are Red and Black Label the same blend?", "No. They are different expressions with different flavour profiles."],
    finalVerdict: "Johnnie Walker is easiest to enjoy when the serve follows the label, not just the colour of the box.",
    metaDescription: "Compare Johnnie Walker Red, Black and Blue Label styles, serving ideas and pairings. Check city prices on BevOry.",
  }),
  "virgin-hills": guide("Virgin Hills", "Wine", {
    description: "Virgin Hills is an Indian wine project led by winemaker Kunal Chug and founder Manohar Chug. Its wines include still and sparkling styles made for the Indian market.",
    story: "The founders describe their aim as wines 'from and for India'. Kunal Chug's role as founder and winemaker gives the range a personal identity rather than a borrowed European estate story.",
    notes: ["Still wines", "The range moves between red, white and rose styles, from fuller fruit to fresher acidity.", "Sparkling wines", "Bubbles offer a lighter pour alongside salty starters."],
    serve: "Chill the sparkling and white wines; give a red a little air in a wine glass.",
    food: "Try a white with tandoori fish, a rose with paneer tikka and a red with pepper chicken.",
    pairings: ["tandoori fish", "paneer tikka", "pepper chicken"],
    whyChoose: "An Indian range shaped by named founders and a broad choice of wine styles.",
    faq: ["Who makes Virgin Hills wine?", "The project names Kunal Chug as founder and winemaker and Manohar Chug as founder and managing director.", "Does Virgin Hills include sparkling wine?", "Yes. Sparkling wines appear alongside its still-wine range."],
    finalVerdict: "Virgin Hills gives the table a useful choice between still wine and bubbles.",
    metaDescription: "Meet Virgin Hills wine, its founders, still and sparkling styles and Indian food pairings. Compare city prices on BevOry.",
  }),
  sensi: guide("Sensi", "Wine", {
    description: "Sensi is a family wine producer from Tuscany, Italy. Its range draws on Tuscan grapes and appellations, including Chianti wines based on Sangiovese.",
    story: "Pietro Sensi began making wine for local buyers in 1890 on the hills between Vinci and Florence. Later generations expanded the vineyards and took the family's wines beyond Tuscany.",
    notes: ["Chianti reds", "Sangiovese brings red-fruit acidity and a savoury finish to the Tuscan side of the range.", "Fresh whites", "Sensi also makes lighter white wines with fruit and floral notes."],
    serve: "Pour a Chianti slightly cool; chill a white before food.",
    food: "Serve Chianti with tomato pasta or tandoori mushrooms and a white with grilled prawns.",
    pairings: ["tomato pasta", "tandoori mushrooms", "grilled prawns"],
    whyChoose: "A Tuscan family name with roots near Vinci and more than a century of wine history.",
    faq: ["Where is Sensi from?", "Sensi began in Tuscany, on the hills between Vinci and Florence.", "When did the Sensi family start making wine?", "Pietro Sensi started producing wine in 1890."],
    finalVerdict: "Sensi is a good way to meet Tuscan wine through a family producer rather than a single famous label.",
    metaDescription: "Explore Sensi's Tuscan family history, Chianti styles and food pairings. Compare city prices on BevOry.",
  }),
  "old-monk": guide("Old Monk", "Rum", {
    description: "Old Monk is an Indian rum family made by Mohan Meakin. The range runs beyond the familiar XXX rum to white, flavoured and reserve-labelled bottles.",
    story: "Mohan Meakin's roots lie in India's early brewery and distillery trade, and Old Monk became its most recognisable rum name. The company's current list includes The Legend, Gold Reserve and several fruit-flavoured versions.",
    notes: ["XXX rum", "The dark-rum style leans into caramel-like sweetness and warming spice.", "Other expressions", "White and fruit-flavoured Old Monk bottles take the range toward lighter mixed drinks."],
    serve: "Pour the dark rum over ice or with cola; use a white expression in a lime highball.",
    food: "Try the dark rum with jaggery cake, chilli chicken or roasted cashews.",
    pairings: ["jaggery cake", "chilli chicken", "roasted cashews"],
    whyChoose: "One of India's most recognisable rum labels, now spanning far more than one bottle.",
    faq: ["Who makes Old Monk?", "Mohan Meakin produces the Old Monk rum range.", "Is every Old Monk bottle dark rum?", "No. The company also lists white and fruit-flavoured expressions."],
    finalVerdict: "Old Monk remains a practical dark-rum choice for a simple drink and a plate of bold snacks.",
    metaDescription: "Explore Old Monk rum, from XXX to white and flavoured bottles, with serving ideas. Compare city prices on BevOry.",
  }),
  macallan: guide("The Macallan", "Whisky", {
    description: "The Macallan makes single malt Scotch whisky at its Speyside estate in Scotland. Its core collections include Sherry Oak and Double Cask, each shaped by different oak-cask choices.",
    story: "Barley farmer and teacher Alexander Reid obtained a distilling licence on the Speyside estate in 1824. Oak selection later became central to the house, particularly sherry-seasoned casks from European and American wood.",
    notes: ["Sherry Oak", "Dried fruit and warming spice are hallmarks of the sherry-cask-led line.", "Double Cask", "American and European oak bring a softer balance of vanilla, fruit and spice."],
    serve: "Taste a small measure neat in a tulip glass; add a few drops of water if you prefer.",
    food: "Pair with dark chocolate, walnut cake or roasted almonds.",
    pairings: ["dark chocolate", "walnut cake", "roasted almonds"],
    whyChoose: "A Speyside single malt house whose cask programmes are easy to explore side by side.",
    faq: ["Is The Macallan a single malt?", "Yes. The Macallan is a Speyside single malt Scotch whisky.", "Is The Macallan smoky?", "The core Sherry Oak and Double Cask styles are better known for fruit, vanilla and spice than peat smoke."],
    finalVerdict: "The Macallan is most rewarding when you compare the cask character of two expressions slowly.",
    metaDescription: "Explore The Macallan's Speyside single malts, oak styles and food pairings. Compare city prices on BevOry.",
  }),
  mcdowells: guide("McDowell's", "Whisky", {
    description: "McDowell's No.1 is an Indian spirits family under Diageo India. Its whisky labels sit alongside the company's McDowell's brandy and rum products.",
    story: "McDowell's established a distillery in Cherthala, Kerala, in 1959 and introduced No.1 Whisky in 1968. Brandy and rum labels also became part of the No.1 family.",
    notes: ["Blended whisky", "The whisky side of No.1 is made for a rounded, mixer-friendly pour.", "Separate spirits", "The brandy and rum labels have their own flavour directions beyond the whisky range."],
    serve: "For the whisky, try a measured pour with ice and soda.",
    food: "Serve with tandoori chicken, masala peanuts or paneer tikka.",
    pairings: ["tandoori chicken", "masala peanuts", "paneer tikka"],
    whyChoose: "A familiar Indian name with distinct whisky, rum and brandy labels.",
    faq: ["Who owns McDowell's No.1?", "McDowell's is part of Diageo India's portfolio.", "Is every McDowell's No.1 product whisky?", "No. The name also appears on brandy and rum products."],
    finalVerdict: "McDowell's No.1 is best approached by spirit and label, with the whisky suited to a plain soda serve.",
    metaDescription: "Explore McDowell's No.1 whisky and its wider spirits family, with serving ideas. Compare city prices on BevOry.",
  }),
  piccini: guide("Piccini", "Wine", {
    description: "Piccini is a family-owned Italian wine producer with roots in Tuscany. Its wines include Chianti and bottles from estates in other Italian regions.",
    story: "Angiolo Piccini started the business in Poggibonsi in 1882. Five generations later, the family's work stretches from Chianti Classico to Maremma and beyond Tuscany.",
    notes: ["Chianti", "Sangiovese-led reds bring lively cherry fruit and a savoury edge.", "Wider Italy", "The estates make other regional styles, from fuller southern reds to fresher whites."],
    serve: "Pour Chianti slightly cool in a medium wine glass.",
    food: "Match a Tuscan red with mushroom pizza, tomato pasta or lamb seekh.",
    pairings: ["mushroom pizza", "tomato pasta", "lamb seekh"],
    whyChoose: "A five-generation Tuscan family whose range reaches beyond a single appellation.",
    faq: ["Where did Piccini begin?", "Angiolo Piccini founded the winery in Poggibonsi, Tuscany, in 1882.", "Does Piccini make only Chianti?", "No. The family's estates and wines also extend to other Italian regions."],
    finalVerdict: "Piccini is a useful Italian red-wine starting point when a tomato-rich meal is on the table.",
    metaDescription: "Explore Piccini's Tuscan roots, Chianti wines and food pairings. Compare city prices on BevOry.",
  }),
  kingfisher: guide("Kingfisher", "Beer", {
    description: "Kingfisher is an Indian beer brand from United Breweries. Its range includes Premium lager and stronger beers made for different drinking preferences.",
    story: "Kingfisher Premium was introduced in 1978 and grew into one of the most familiar names in Indian beer. United Breweries later developed other Kingfisher variants, keeping the original mild lager distinct from stronger labels.",
    notes: ["Premium lager", "A crisp malt-and-hop profile keeps the classic lager refreshing.", "Strong beers", "The stronger variants bring more body and a heavier finish."],
    serve: "Chill thoroughly and pour into a clean beer glass rather than serving warm.",
    food: "Bring it to masala peanuts, tandoori fish or chilli paneer.",
    pairings: ["masala peanuts", "tandoori fish", "chilli paneer"],
    whyChoose: "A longstanding Indian lager name with separate mild and strong styles.",
    faq: ["Who makes Kingfisher beer?", "United Breweries makes Kingfisher.", "Is Kingfisher Premium a strong beer?", "No. Premium is the classic mild lager; stronger Kingfisher variants are separate products."],
    finalVerdict: "Kingfisher Premium is a reliable cold lager beside spicy Indian starters.",
    metaDescription: "Explore Kingfisher Premium and strong beer styles, serving tips and food pairings. Compare city prices on BevOry.",
  }),
  gancia: guide("Gancia", "Wine", {
    description: "Gancia is an Italian sparkling-wine and aperitif house from Piedmont. Its portfolio runs from Moscato-based bubbles to vermouth.",
    story: "Carlo and Edoardo Gancia founded the business in 1850. After learning Champagne-making techniques in Reims, Carlo applied them to local Moscato grapes and presented an Italian sparkling wine in 1865.",
    notes: ["Moscato bubbles", "Aromatic grape fruit and floral sweetness define the Moscato side of the house.", "Vermouth", "Wine, herbs and spices make a very different, bittersweet aperitif."],
    serve: "Chill a sparkling wine well; serve vermouth over ice with a little soda.",
    food: "Pair Moscato with rasmalai and vermouth with olives or masala cashews.",
    pairings: ["rasmalai", "olives", "masala cashews"],
    whyChoose: "An Italian house that connects Piedmontese sparkling-wine history with the aperitif shelf.",
    faq: ["Is Gancia only a sparkling-wine producer?", "No. Its portfolio also includes vermouth and aperitifs.", "Who founded Gancia?", "Brothers Carlo and Edoardo Gancia founded the business in 1850."],
    finalVerdict: "Gancia is worth exploring for the contrast between a chilled Moscato and a herbal aperitif.",
    metaDescription: "Meet Gancia's Piedmont sparkling wines and vermouth, with serving and food ideas. Compare city prices on BevOry.",
  }),
  "jacobs-creek": guide("Jacob's Creek", "Wine", {
    description: "Jacob's Creek is an Australian wine brand rooted in South Australia's Barossa Valley. Its range includes red, white, rose and sparkling wines.",
    story: "Johann Gramp planted vines beside Jacob's Creek in 1847, beginning the winemaking history behind the name. The creek itself runs through the Barossa, grounding a widely distributed wine brand in a specific place.",
    notes: ["Barossa reds", "Shiraz-led wines bring ripe dark fruit and a fuller feel.", "Whites and bubbles", "The white and sparkling bottles give a fresher, more chilled direction."],
    serve: "Pour a red slightly cool; keep a white or sparkling bottle chilled until serving.",
    food: "Bring a red to lamb kebabs and a white to grilled prawns or paneer tikka.",
    pairings: ["lamb kebabs", "grilled prawns", "paneer tikka"],
    whyChoose: "A broad Australian range with a documented Barossa origin.",
    faq: ["Where is Jacob's Creek from?", "The brand traces its roots to the Barossa Valley in South Australia.", "Who first planted vines beside Jacob's Creek?", "Johann Gramp planted his first vineyard there in 1847."],
    finalVerdict: "Jacob's Creek makes it easy to match an Australian wine style to the food, from Shiraz to bubbles.",
    metaDescription: "Explore Jacob's Creek Barossa wines, from Shiraz to sparkling, with food pairings. Compare city prices on BevOry.",
  }),
  maharani: guide("Maharani Mahansar", "Liqueur", {
    description: "Maharani Mahansar is a Rajasthan-made heritage liqueur range from Shekhawati Heritage Herbal. Its recipes use botanicals such as rose, fennel, cardamom and orange.",
    story: "The distillery is in Sardarshahar, Churu district, and the family links its liqueur tradition to Mahansar's older recipes. Thakur Rajendra Singh Ji Mahansar leads the company today.",
    notes: ["Rose and citrus", "Floral and orange-led expressions make the range notably aromatic.", "Herbal spice", "Fennel and cardamom give other bottles a warm, distinctly Indian accent."],
    serve: "Chill a small measure, or add soda to a botanical expression over ice.",
    food: "Try with pista kulfi, orange cake or salted pistachios.",
    pairings: ["pista kulfi", "orange cake", "salted pistachios"],
    whyChoose: "A Rajasthan liqueur house built around local botanical flavours.",
    faq: ["Where is Maharani Mahansar made?", "Its distillery is in Sardarshahar in Rajasthan's Churu district.", "What flavours appear in the range?", "The producer names rose, fennel, cardamom and orange among its botanical ingredients."],
    finalVerdict: "Maharani Mahansar is a small aromatic pour that belongs beside Indian sweets.",
    metaDescription: "Explore Maharani Mahansar's Rajasthan liqueurs, botanicals and dessert pairings. Compare city prices on BevOry.",
  }),
  folonari: guide("Folonari", "Wine", {
    description: "Folonari is an Italian wine label founded in Veneto. Its range includes Pinot Grigio and Chianti as well as other easy-going table wines.",
    story: "Francesco Folonari founded the business in 1825 in northeastern Italy. The lion on its labels refers to the Lion of St Mark, keeping a visible link to the Veneto origin.",
    notes: ["Pinot Grigio", "The producer describes floral aromas, green apple and a dry, crisp finish.", "Chianti", "Its Sangiovese-based red moves through cherry, berry and an almond note."],
    serve: "Chill Pinot Grigio; pour Chianti a little cooler than room temperature.",
    food: "Match the white with tandoori prawns and the red with tomato pasta or chicken parmesan.",
    pairings: ["tandoori prawns", "tomato pasta", "chicken parmesan"],
    whyChoose: "An old Veneto name with clear, contrasting Italian white and red styles.",
    faq: ["Where did Folonari begin?", "Francesco Folonari founded the business in Veneto in 1825.", "Which grape is in Folonari Chianti?", "The producer lists Sangiovese for its Chianti DOCG."],
    finalVerdict: "Folonari is strongest at the table, where a crisp Pinot Grigio or Chianti has an obvious job.",
    metaDescription: "Meet Folonari wine, from Pinot Grigio to Chianti, with serving ideas and pairings. Compare city prices on BevOry.",
  }),
  tuborg: guide("Tuborg", "Beer", {
    description: "Tuborg is a Danish beer brand under Carlsberg. Tuborg Green is a bottom-fermented lager, while the broader range includes other beer styles.",
    story: "The brand began by Copenhagen's Hellerup harbour and became closely associated with Danish lager culture. Its international reach has taken the Tuborg name well beyond Denmark.",
    notes: ["Green lager", "A light malt base and clean finish make Green an easy cold pour.", "Lager freshness", "The bottom-fermented style keeps the body relatively crisp."],
    serve: "Serve well chilled in a clean lager glass.",
    food: "Pour beside peri-peri fries, chicken tikka or chilli paneer.",
    pairings: ["peri-peri fries", "chicken tikka", "chilli paneer"],
    whyChoose: "A Danish lager name with a crisp Green expression.",
    faq: ["Who owns Tuborg?", "Tuborg belongs to the Carlsberg group.", "What kind of beer is Tuborg Green?", "The producer describes it as a bottom-fermented lager."],
    finalVerdict: "Tuborg Green earns its spot beside hot, salty snacks when served properly cold.",
    metaDescription: "Explore Tuborg's Danish lager story, Tuborg Green and snack pairings. Compare city prices on BevOry.",
  }),
  "paul-john": guide("Paul John", "Whisky", {
    description: "Paul John is an Indian single malt whisky made by John Distilleries in Goa. It uses Indian six-row barley and copper pot stills.",
    story: "Founder Paul P John chose Goa for the distillery, where the warm coastal climate shapes maturation. The barley comes from Indian growing regions including Rajasthan and Haryana, giving the whisky a distinctly local grain story.",
    notes: ["Unpeated malts", "Fruit, malt and spice lead expressions that do not rely on peat smoke.", "Peated malts", "Other Paul John bottles bring smoke into the same rich malt frame."],
    serve: "Taste a small pour neat in a tulip glass, then try a few drops of water.",
    food: "Pair unpeated styles with roasted cashews and peated styles with tandoori mushrooms.",
    pairings: ["roasted cashews", "tandoori mushrooms", "dark chocolate"],
    whyChoose: "A Goa single malt made with Indian barley and a clear choice of peated or unpeated styles.",
    faq: ["Where is Paul John whisky made?", "John Distilleries makes Paul John single malt in Goa.", "Is all Paul John whisky smoky?", "No. The range includes both peated and unpeated expressions."],
    finalVerdict: "Paul John lets Indian barley speak clearly, whether you choose smoke or leave it out.",
    metaDescription: "Explore Paul John single malt from Goa, its six-row barley and serving ideas. Compare city prices on BevOry.",
  }),
  patron: guide("Patrón", "Tequila", {
    description: "Patrón is a tequila producer in Jalisco, Mexico, using Blue Weber agave. Its range spans unaged and oak-matured expressions.",
    story: "At Hacienda Patrón, agave hearts are cooked in brick ovens and crushed using both a roller mill and a volcanic-stone tahona. The two streams are fermented separately before distillation and blending.",
    notes: ["Blanco", "Fresh agave and citrus lead the unaged style.", "Reposado", "A period in oak adds vanilla and softer spice to the agave base."],
    serve: "Sip Blanco neat in a small glass or use it in a lime-forward margarita.",
    food: "Bring it to tandoori prawns, fish tacos or chilli paneer.",
    pairings: ["tandoori prawns", "fish tacos", "chilli paneer"],
    whyChoose: "A Jalisco tequila whose tahona and roller-mill methods are part of the flavour story.",
    faq: ["What plant is Patrón tequila made from?", "Patrón uses Blue Weber agave grown in Jalisco.", "Does Patrón use a tahona?", "Yes. The producer uses both a volcanic-stone tahona and a roller mill."],
    finalVerdict: "Patrón Blanco is a good place to taste cooked agave before moving to the oak-aged range.",
    metaDescription: "Explore Patrón tequila's Jalisco agave, tahona process and food pairings. Compare city prices on BevOry.",
  }),
  "yellow-tail": guide("Yellow Tail", "Wine", {
    description: "Yellow Tail is an Australian wine brand made by the Casella family in Yenda, New South Wales. Its range includes Shiraz, Cabernet Sauvignon, Chardonnay and sparkling wines.",
    story: "Filippo and Maria Casella moved from Sicily to Australia in 1957. The family's winery in Yenda later built Yellow Tail around accessible, fruit-forward wines rather than a single estate bottling.",
    notes: ["Reds", "Shiraz and Cabernet bring ripe fruit and a fuller dinner-wine feel.", "Whites and bubbles", "Chardonnay and sparkling styles offer a fresher route through the range."],
    serve: "Chill a white or sparkling wine; pour a red slightly cool.",
    food: "Match Shiraz with lamb kebabs and a white with tandoori fish or paneer tikka.",
    pairings: ["lamb kebabs", "tandoori fish", "paneer tikka"],
    whyChoose: "A Yenda family winery with an easy-to-navigate range of Australian grape styles.",
    faq: ["Who makes Yellow Tail wine?", "Casella Family Brands makes Yellow Tail in Yenda, Australia.", "Is Yellow Tail only red wine?", "No. The range includes white, rose and sparkling styles as well as reds."],
    finalVerdict: "Yellow Tail works when you want a clear grape choice without a complicated wine list.",
    metaDescription: "Explore Yellow Tail wines from Yenda, Australia, with grape styles and food pairings. Compare city prices on BevOry.",
  }),
  "fishing-cat": guide("Fishing Cat", "Wine", {
    description: "Fishing Cat is an Italian wine label associated with Abruzzo. Its selection includes Montepulciano d'Abruzzo, Pecorino, Pinot Grigio and sparkling wine.",
    story: "The label uses the fishing cat as a symbol of curiosity and discovery. Its range brings together familiar international grapes with wines tied more closely to Abruzzo's own denominations.",
    notes: ["Montepulciano", "A fuller Abruzzo red offers dark fruit and a savoury finish.", "Pecorino", "The white brings citrus and floral notes with a fresh edge."],
    serve: "Chill Pecorino; serve Montepulciano slightly cool in a red-wine glass.",
    food: "Pair the white with grilled prawns and the red with lamb seekh or tomato pasta.",
    pairings: ["grilled prawns", "lamb seekh", "tomato pasta"],
    whyChoose: "An Italian label with Abruzzo grapes alongside familiar international styles.",
    faq: ["Is Fishing Cat wine from Italy?", "Yes. Its wine selection is associated with Italian regions including Abruzzo.", "Which Abruzzo grapes appear in the range?", "The producer lists Montepulciano and Pecorino among its wines."],
    finalVerdict: "Fishing Cat's Abruzzo bottles are the most interesting place to start.",
    metaDescription: "Explore Fishing Cat's Italian wines, from Montepulciano to Pecorino, with food pairings. Compare city prices on BevOry.",
  }),
  paladin: guide("Paladin", "Wine", {
    description: "Paladin is a family wine producer based between Veneto and Friuli in northeastern Italy. Its vineyards near Annone Veneto grow grapes for a range of regional wines.",
    story: "Valentino Paladin began the winery in 1962. The family bought vineyards in Annone Veneto in 1977 and later developed Bosco del Merlo alongside the original Paladin name.",
    notes: ["Veneto whites", "Fresh fruit and a lighter body suit a chilled, food-led pour.", "Regional reds", "The red-wine side brings darker fruit and more structure for a meal."],
    serve: "Chill a white; pour a red slightly cool and give it a few minutes in the glass.",
    food: "Try a white with tandoori fish and a red with mushroom risotto or lamb chops.",
    pairings: ["tandoori fish", "mushroom risotto", "lamb chops"],
    whyChoose: "A Veneto family producer with a documented link to Annone Veneto's vineyards.",
    faq: ["Where is Paladin wine made?", "Paladin is based around Annone Veneto near the Veneto-Friuli border.", "Who started Paladin?", "Valentino Paladin founded the winery in 1962."],
    finalVerdict: "Paladin is a sound pick for a regional Italian wine served with dinner.",
    metaDescription: "Meet Paladin wines from Veneto, the family history and food pairings. Compare city prices on BevOry.",
  }),
  luxardo: guide("Luxardo", "Liqueur", {
    description: "Luxardo is an Italian family distiller best known for Maraschino liqueur. It also makes other cherry liqueurs, Limoncello and cocktail ingredients.",
    story: "Girolamo Luxardo founded the distillery in 1821 in Zara after Maria Canevari Luxardo developed a local maraschino recipe. The family re-established production in Torreglia, near Padua, after the Second World War.",
    notes: ["Maraschino", "The clear liqueur carries a distinct cherry-stone and floral character rather than simple cherry syrup sweetness.", "Other liqueurs", "Sangue Morlacco turns toward a richer cherry profile, while Limoncello is citrus-led."],
    serve: "Use a small measure of Maraschino in a classic cocktail or serve it lightly chilled.",
    food: "Pair with dark chocolate, almond biscotti or gulab jamun.",
    pairings: ["dark chocolate", "almond biscotti", "gulab jamun"],
    whyChoose: "A family-run distiller whose Maraschino has a specific place in cocktail history.",
    faq: ["Where did Luxardo start?", "The family distillery began in Zara in 1821 and later moved to Torreglia in Italy.", "Is Luxardo Maraschino the same as cherry syrup?", "No. Maraschino is a distilled cherry liqueur used in cocktails."],
    finalVerdict: "Luxardo Maraschino is the bottle to reach for when a cocktail needs cherry complexity without syrupy weight.",
    metaDescription: "Explore Luxardo's Maraschino history, cocktail uses and dessert pairings. Compare city prices on BevOry.",
  }),
  woodbridge: guide("Woodbridge", "Wine", {
    description: "Woodbridge by Robert Mondavi is a California wine range with roots in Lodi. It covers familiar red, white and rose grape styles.",
    story: "Robert Mondavi established Woodbridge Winery near his childhood home in 1979. The aim was to make varietal California wine suited to an ordinary dinner table, drawing on the Lodi grape-growing region.",
    notes: ["California reds", "Fruit-forward reds make a rounded match for roast and grilled food.", "Fresh whites", "White wines give a lighter, chilled contrast with seafood or vegetables."],
    serve: "Pour a red slightly cool; chill a white before serving.",
    food: "Try a red with chicken tikka and a white with grilled prawns or paneer skewers.",
    pairings: ["chicken tikka", "grilled prawns", "paneer skewers"],
    whyChoose: "Robert Mondavi's Lodi-rooted answer to everyday California wine.",
    faq: ["Who founded Woodbridge wine?", "Robert Mondavi established Woodbridge Winery in 1979.", "Where is Woodbridge from?", "Its winery was founded near Lodi in California."],
    finalVerdict: "Woodbridge makes most sense as an unfussy California wine for dinner.",
    metaDescription: "Explore Woodbridge by Robert Mondavi, its Lodi history and dinner pairings. Compare city prices on BevOry.",
  }),
  camas: guide("Camas", "Wine", {
    description: "Camas is a varietal wine range from the Anne de Joyeuse growers' cellar around Limoux in southern France. It includes Chardonnay, Chenin, Viognier, Syrah and Pinot Noir.",
    story: "Anne de Joyeuse works with vineyards across Limoux's Atlantic, Mediterranean and upper Aude influences. The Camas range presents individual grapes rather than a single house blend.",
    notes: ["Chardonnay", "The producer describes white flowers, white fruit and a fresh citrus finish.", "Red grapes", "Syrah, Merlot and Pinot Noir give separate red-wine paths through the range."],
    serve: "Chill Camas Chardonnay; pour a red slightly cool.",
    food: "Match the Chardonnay with tandoori fish and a red with mushroom pasta or lamb chops.",
    pairings: ["tandoori fish", "mushroom pasta", "lamb chops"],
    whyChoose: "A Limoux-area range that lets you explore one grape at a time.",
    faq: ["Who makes Camas wine?", "The Anne de Joyeuse growers' cellar makes the Camas range near Limoux.", "Is Camas one grape variety?", "No. The range includes separate Chardonnay, Chenin, Syrah, Pinot Noir and other wines."],
    finalVerdict: "Camas is clearest when chosen by grape, with the Chardonnay an easy first glass.",
    metaDescription: "Explore Camas wines from Limoux, from Chardonnay to Syrah, with food pairings. Compare city prices on BevOry.",
  }),
};
