import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_43 = [
  ["romanov", "Romanov", "India", "Vodka", "331c89933631da3cff298a36"],
  ["golden-mist", "Golden Mist", "India", "Brandy", "0cdf033ad53bca4ab9736eed"],
  ["x-and-o", "X&O Barrel", "India", "Whisky", "79d90a014add04b1558e8183"],
  ["srishti", "Srishti", "India", "Whisky", "9a9d246306930ba8884ad8f1"],
  ["yello", "Yello", "India", "Whisky", "0e6807fb3a06ab2a6ee35df3"],
  ["signature-rare", "Signature Rare", "India", "Whisky", "fbc13eb2ae1d4a700ce47580"],
  ["tripel-moine", "Tripel Moine", "Belgium", "Beer", "586cf5a0cb7d103e7bf793a9"],
  ["lucifer-beer", "Lucifer", "Belgium", "Beer", "d59e97d2ff0df72bb249ef54"],
  ["nomad-oscuro", "Nomad Oscuro", "India", "Rum", "49a8402c956f14441202a90b"],
  ["glenfiddich-the", "Glenfiddich", "Scotland", "Whisky", "5178d9f1ed2a2ce182af130a"],
  ["glenlivet-the", "The Glenlivet", "Scotland", "Whisky", "40a8238d2de0e3cdc6f34324"],
  ["macallan-the", "The Macallan", "Scotland", "Whisky", "913081cd4df128033046cc99"],
  ["yamazaki-the", "Yamazaki", "Japan", "Whisky", "2bc5240b644319371a3d9688"],
  ["glenwalk-the", "The Glenwalk", "Scotland", "Whisky", "38e328855fae4ead06e04739"],
  ["old-durbar", "Old Durbar", "Nepal", "Whisky", "63bfdd0edebb24919a364a9f"],
  ["oaken-glow", "Oaken Glow", "India", "Whisky", "d2f922f00e8a32de136041cb"],
  ["susegado", "Susegado", "India", "Beer", "2bf00c06b214feb9d636d9dd"],
  ["primo-malvasia", "Primo Malvasia", "Italy", "Wine", "31a85523cb218313d841348e"],
  ["tombacco-biferno", "Tombacco Biferno", "Italy", "Wine", "a99e68ca7562317dc4f854be"],
  ["luna-argenta", "Luna Argenta", "Italy", "Sparkling Wine", "ae8227f66afeb431951b2a8e"],
  ["tocornal", "Tocornal", "Chile", "Wine", "7616b29a8c39a206523ba4b8"],
  ["durvillea", "Durvillea", "New Zealand", "Wine", "6f57ae37822dc03e9c2d3c52"],
  ["seven-islands", "Seven Islands", "India", "Whisky", "d944b7f8ff2ce86bc13570cc"],
  ["woodsmen", "Woodsmen", "India", "Whisky", "eaae419411e96f7507110977"],
  ["maka-di", "Maka Di", "India", "Beer", "f04cd2b4d99c5edd9bfbc54b"],
  ["arthaus-collective-blended-malt", "Arthaus Collective", "Scotland", "Whisky", "b73739d8b35603e6c27c806a"],
  ["rahasya", "Rahasya", "India", "Vodka", "692355bfd2f4f72433d5b59e"],
  ["eight-finger-eddie", "Eight Finger Eddie", "India", "Beer", "972255e070709538c608d385"],
  ["barbar", "Barbar", "Belgium", "Beer", "08a2d3c63bf9fc88276d97a9"],
  ["cabana", "Cabana", "India", "Liqueur", "f9a74fed77738d1b2602a369"],
] as const;

// Research URLs are kept outside the public guide fields.
export const BRAND_SOURCES_BATCH_43: Record<string, string[]> = {
  romanov: ["https://inbrew.com/our-brands"],
  "golden-mist": ["https://www.abdindia.com/news-and-media/2025/golden-mist-by-abd-brings-french-cask-sophistication-to-indian-brandy-lovers/"],
  "x-and-o": ["https://www.abdindia.com/wp-content/uploads/2025/05/b18c-final-annual-report-fy22-23.pdf"],
  srishti: ["https://www.abdindia.com/spirits/whisky-brands/srishti/"],
  yello: ["https://www.abdindia.com/news-and-media/2025/abd-maestro-unveils-yello-designer-whisky-a-bold-new-fusion-of-scotch-and-indian-malts/"],
  "signature-rare": ["https://www.diageoindia.com/en/brands/brand-explorer/signature"],
  "tripel-moine": ["https://bocq.be/en/"],
  "lucifer-beer": ["https://www.hetanker.be/en/about-us", "https://www.belgenbier.be/docs/catalogus201206.pdf"],
  "nomad-oscuro": ["https://www.nomadoscuro.com/"],
  "glenfiddich-the": ["https://www.glenfiddich.com/en-us/our-whisky/12-year-old/"],
  "glenlivet-the": ["https://www.theglenlivet.com/en/our-story/"],
  "macallan-the": ["https://www.themacallan.com/en/our-story"],
  "yamazaki-the": ["https://house.suntory.com/yamazaki-whisky/yamazaki-distillery"],
  "glenwalk-the": ["https://www.theglenwalk.com/glenwalk-variants"],
  "old-durbar": ["https://olddurbar.com/whisky-collection/"],
  "oaken-glow": ["https://www.linkedin.com/posts/pernodricardindia_oakenglow-asmokytastecraftedbyfire-drinkresponsibly-activity-6760523258052804608-mHqB"],
  susegado: ["https://www.brewer-world.com/susegado-beer-now-available-in-bottled-format/", "https://www.spotlightgoa.com/3-local-beers-to-try-in-goa/"],
  "primo-malvasia": ["https://static.fantiniwines.com/media/2022/12/SCHEDA_TECNICA_PRIMO-MALVASIA-ENG.pdf"],
  "tombacco-biferno": ["https://rinomatatombacco.it/en/wines/biferno-doc-rosso-riserva/"],
  "luna-argenta": ["https://www.lunaargenta.it/en/"],
  tocornal: ["https://cyrnos.com/wp-content/uploads/2016/03/Tocornal-Merlot.pdf"],
  durvillea: ["https://astrolabewines.co.nz/wine/durvillea-pinot-noir", "https://astrolabewines.co.nz/wine/durvillea-chardonnay"],
  "seven-islands": ["https://nsearchives.nseindia.com/corporate/gthakur_20112025122124_TI_Pressrelease_SevenIslands.pdf"],
  woodsmen: ["https://woodsmenwhiskey.com/"],
  "maka-di": ["https://makabeer.space/", "https://makabeer.space/brewery-tour/"],
  "arthaus-collective-blended-malt": ["https://abdmaestro.com/brands/arthaus-whisky/"],
  rahasya: ["https://www.houseofblisswater.com/rahasya/", "https://maharajadrinks.com/products/rahasya-vodka"],
  "eight-finger-eddie": ["https://goabrewing.co/", "https://www.brewer-world.com/hitting-the-sweet-spot/"],
  barbar: ["https://www.brasserielefebvre.be/en/biere/barbar-blonde/", "https://www.brasserielefebvre.be/en/biere/barbar-rouge/"],
  cabana: ["https://www.redkraftbev.com/about-us"],
};

export const BRAND_LOGOS_BATCH_43: Record<string, string> = {
  "glenfiddich-the": "https://static.livcheers.com/static/content/images/brand/glenfiddich.webp",
  "old-durbar": "https://olddurbar.com/wp-content/themes/starter/imagio_s/img/logo/old_durbar_logo-1.svg",
  "maka-di": "https://makabeer.space/wp-content/uploads/2020/10/header-logo.png",
};

export const BRAND_CONTENT_BATCH_43: Record<string, BrandPublicContent> = {
  romanov: {
    description: "Romanov is an Indian grain vodka made by Inbrew Beverages. The range includes a plain vodka and fruit-flavoured expressions.",
    story: "Launched in 1974, Romanov borrowed its name from Russia's imperial dynasty. Inbrew now makes the spirit with triple distillation and multiple filtration steps.",
    tastingNotes: [{ title: "Classic", description: "The plain vodka is clean and crisp, with grain kept in the background." }, { title: "Fruit bottles", description: "Orange and apple versions shift the emphasis from a neutral pour to bright fruit flavour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the plain vodka for a short pour or mix it with soda and a squeeze of lime." }, { subheading: "Food", description: "The chilled plain pour suits fish tikka; orange works with chilli paneer." }],
    pairingIdeas: [{ title: "Alongside Romanov", items: ["fish tikka", "chilli paneer", "salted cashews", "cucumber chaat"] }],
    whyChoose: "A longstanding Indian vodka with a straightforward plain pour and separate fruit flavours.",
    faqs: [{ question: "Where is Romanov vodka made?", answer: "Romanov is an Indian vodka in Inbrew Beverages' portfolio." }, { question: "Is Romanov only sold plain?", answer: "No. The range also includes fruit-flavoured vodka, including orange and apple." }],
    finalVerdict: "Pick classic Romanov for a crisp mixer or a fruit expression when the cocktail needs a sweeter edge.",
    metaTitle: "Romanov Vodka Guide | BevOry", metaDescription: "Explore Romanov vodka, its plain and fruit styles, serving ideas and city prices on BevOry.",
  },
  "golden-mist": {
    description: "Golden Mist is an Indian brandy name in Allied Blenders and Distillers' portfolio. The recent French Brandy expression sits in its prestige range; the catalogue also contains a Special Brandy label.",
    story: "ABD introduced Golden Mist French Brandy in Karnataka in 2025. That launch brought a French-oak-aged expression into the company's brandy range.",
    tastingNotes: [{ title: "French Brandy", description: "The newer French Brandy has grape, honey and liquorice notes with a gentle spice finish." }, { title: "Texture", description: "That expression is rounded and smooth, with an amber colour from its French-oak maturation." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve the French Brandy in a small tulip glass, neat or over one cube." }, { subheading: "Plate", description: "Try it with mutton seekh kebabs or a piece of dark chocolate after dinner." }],
    pairingIdeas: [{ title: "For the French Brandy", items: ["mutton seekh kebabs", "dark chocolate", "roasted almonds", "caramel custard"] }],
    whyChoose: "Golden Mist's French Brandy brings an oak-led style to ABD's Indian brandy range.",
    faqs: [{ question: "Who makes Golden Mist brandy?", answer: "Golden Mist is an Allied Blenders and Distillers brand." }, { question: "Is Golden Mist French Brandy oak aged?", answer: "Yes. ABD says its French Brandy expression is aged in French oak casks." }],
    finalVerdict: "The French Brandy is the bottle to reach for when you want grape, honey and oak in a compact after-dinner pour.",
    metaTitle: "Golden Mist Brandy Guide | BevOry", metaDescription: "Meet Golden Mist brandy, French-oak tasting notes, food matches and city prices on BevOry.",
  },
  "x-and-o": {
    description: "X&O Barrel is an Indian whisky from Allied Blenders and Distillers. It combines Scotch malt matured in American bourbon barrels with Indian grain spirit.",
    story: "ABD introduced X&O Barrel in Assam and Haryana during 2022-23. The X and O on the label refer to kisses and hugs, a deliberate contrast with traditional whisky naming.",
    tastingNotes: [{ title: "Malt", description: "The Scotch component gives the blend a soft malt character." }, { title: "Oak", description: "Bourbon-barrel maturation adds a rounded, gently sweet finish to the malt element." }],
    howToEnjoy: [{ subheading: "First sip", description: "Pour a small measure neat, then try a little water before adding a mixer." }, { subheading: "Dinner", description: "Chicken malai tikka and roasted peanuts make easy companions." }],
    pairingIdeas: [{ title: "At the table", items: ["chicken malai tikka", "roasted peanuts", "grilled corn", "pepper paneer"] }],
    whyChoose: "A Scotch-malt and Indian-grain blend with a distinctive bourbon-cask element.",
    faqs: [{ question: "What is X&O Barrel made from?", answer: "It combines Scotch malt aged in American bourbon barrels with Indian grain spirits." }, { question: "Who owns X&O Barrel?", answer: "The whisky is part of Allied Blenders and Distillers' portfolio." }],
    finalVerdict: "X&O Barrel gives a familiar Indian blend a clear malt-and-bourbon-cask direction.",
    metaTitle: "X&O Barrel Whisky Guide | BevOry", metaDescription: "Explore X&O Barrel's Scotch malt and Indian grain blend, serving ideas and city prices on BevOry.",
  },
  srishti: {
    description: "Srishti is an Indian blended whisky by Allied Blenders and Distillers. Scotch malts and Indian grain spirits form the blend, which is finished with curcumin.",
    story: "Launched in 2022, Srishti uses a turmeric-derived ingredient in an otherwise familiar Scotch-and-Indian-grain format. ABD says the curcumin does not change the whisky's taste, aroma or colour.",
    tastingNotes: [{ title: "Blend", description: "The Scotch malt component brings whisky character to a softer Indian-grain base." }, { title: "Finish", description: "Curcumin is part of the recipe but is not presented as a turmeric flavour." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try it with a cube of ice before moving to a highball." }, { subheading: "Snack", description: "Serve beside masala peanuts or paneer tikka." }],
    pairingIdeas: [{ title: "With Srishti", items: ["masala peanuts", "paneer tikka", "chicken seekh", "roasted makhana"] }],
    whyChoose: "An Indian blend whose unusual curcumin addition is part of the recipe, not a claim of turmeric taste.",
    faqs: [{ question: "Does Srishti whisky taste of turmeric?", answer: "ABD says the curcumin addition does not change its taste, aroma or colour." }, { question: "Who makes Srishti?", answer: "Allied Blenders and Distillers makes Srishti in India." }],
    finalVerdict: "Srishti is worth considering for its Scotch-and-grain blend and unusual ingredient story.",
    metaTitle: "Srishti Whisky Guide | BevOry", metaDescription: "Discover Srishti whisky's Scotch-and-grain blend, serving ideas, food pairings and city prices on BevOry.",
  },
  yello: {
    description: "Yello is a designer whisky from ABD Maestro in India. Its blend joins Scotch malts from Speyside and the Highlands with Indian malt whisky.",
    story: "ABD Maestro unveiled Yello in 2025 as a Scotch-and-Indian-malt release. The Scotch portion uses ex-bourbon casks, a choice that helps shape the blend's sweeter edge.",
    tastingNotes: [{ title: "Sweetness", description: "Vanilla and caramel sit near the front of the profile." }, { title: "Malt", description: "Soft malt character follows, with the Indian and Scottish whiskies working in one blend." }],
    howToEnjoy: [{ subheading: "Serve", description: "Taste neat first, then add a few drops of water or build a tall soda highball." }, { subheading: "Food", description: "Galouti kebabs or lightly charred paneer work with its sweeter malt notes." }],
    pairingIdeas: [{ title: "With Yello", items: ["galouti kebabs", "charred paneer", "salted almonds", "grilled pineapple"] }],
    whyChoose: "Yello puts Indian malt in direct conversation with Speyside and Highland Scotch.",
    faqs: [{ question: "Is Yello an Indian whisky?", answer: "Yes. ABD Maestro blends Indian malt whisky with Scotch malts for Yello." }, { question: "Does Yello contain Scotch whisky?", answer: "Yes. Its recipe includes Speyside and Highland Scotch malts." }],
    finalVerdict: "A malt-focused cross-border blend with a vanilla-and-caramel lean.",
    metaTitle: "Yello Whisky Guide | BevOry", metaDescription: "Read about Yello's Indian and Scotch malts, tasting notes, food pairings and city prices on BevOry.",
  },
  "signature-rare": {
    description: "Signature Rare is an Indian whisky label within Diageo India's Signature family. It belongs to the brand's blended-whisky tradition rather than its single-malt category.",
    story: "Signature was established in 1994 and became a prominent Indian whisky name through United Spirits, now part of Diageo India. Rare remains in the range beside Premier.",
    tastingNotes: [{ title: "Malt", description: "Imported Scotch and Indian malt whiskies bring the grain-and-oak side of the blend." }, { title: "Grain", description: "Indian grain spirit softens the malt weight in the current Signature family." }],
    howToEnjoy: [{ subheading: "Serve", description: "Make a short whisky-and-soda over ice, keeping the mixer light enough to taste the whisky." }, { subheading: "Food", description: "Tandoori chicken and masala cashews suit a simple blended-whisky pour." }],
    pairingIdeas: [{ title: "With Signature Rare", items: ["tandoori chicken", "masala cashews", "paneer tikka", "pepper mushroom"] }],
    whyChoose: "A familiar Indian blended-whisky label from the long-running Signature family.",
    faqs: [{ question: "Is Signature Rare a single malt?", answer: "No. Signature Rare is an Indian blended whisky label." }, { question: "Who owns Signature whisky?", answer: "Signature is in Diageo India's brand portfolio." }],
    finalVerdict: "Signature Rare suits a straightforward whisky-and-soda more than a heavily dressed cocktail.",
    metaTitle: "Signature Rare Whisky Guide | BevOry", metaDescription: "Explore Signature Rare blended whisky, simple serves, Indian snacks and city prices on BevOry.",
  },
  "tripel-moine": {
    description: "Tripel Moine is a Belgian tripel beer associated with Brasserie du Bocq in Purnode. It is a strong, pale abbey-style beer rather than a light lager.",
    story: "Brasserie du Bocq has brewed in Purnode since 1858. Tripel Moine sits in the Belgian tradition of bottle-conditioned, yeast-driven strong ales.",
    tastingNotes: [{ title: "Aroma", description: "Fruit and yeast spice make the first impression." }, { title: "Palate", description: "A fuller malt body carries a dry, gently bitter finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour into a chalice or tulip glass; leave the final yeast sediment in the bottle if you prefer a clearer beer." }, { subheading: "Food", description: "Its strength and spice stand up to chicken tikka and washed-rind cheese." }],
    pairingIdeas: [{ title: "Beside the beer", items: ["chicken tikka", "pepper prawns", "washed-rind cheese", "roast chicken"] }],
    whyChoose: "A Belgian tripel for drinkers who want yeast character and body rather than lager crispness.",
    faqs: [{ question: "What style is Tripel Moine?", answer: "It is a Belgian tripel, a strong pale ale style." }, { question: "Where is Tripel Moine brewed?", answer: "It is associated with Brasserie du Bocq in Purnode, Belgium." }],
    finalVerdict: "Give Tripel Moine a proper glass and food with enough seasoning to meet it.",
    metaTitle: "Tripel Moine Beer Guide | BevOry", metaDescription: "Meet Tripel Moine Belgian tripel, its yeast-led style, food matches and city prices on BevOry.",
  },
  "lucifer-beer": {
    description: "Lucifer is a strong blonde Belgian beer now brewed by Het Anker in Mechelen. Its fruity yeast character and firm finish place it far from an everyday pilsner.",
    story: "The beer began with Brewery Riva in the 1980s. Het Anker took over the Lucifer rights in 2009, continuing the label within its Mechelen brewery portfolio.",
    tastingNotes: [{ title: "Nose", description: "Fruit-led aromas rise above the pale malt." }, { title: "Finish", description: "A modest hop bitterness cuts through the fuller body." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve cool, not icy, in a tulip glass to keep the aroma visible." }, { subheading: "Plate", description: "Try tandoori fish or a sharp cheddar beside it." }],
    pairingIdeas: [{ title: "With Lucifer", items: ["tandoori fish", "aged cheddar", "pepper chicken", "fried calamari"] }],
    whyChoose: "A Mechelen-brewed strong blonde with a history that predates its current brewery.",
    faqs: [{ question: "Who brews Lucifer beer?", answer: "Het Anker in Mechelen, Belgium, brews Lucifer today." }, { question: "Is Lucifer a lager?", answer: "No. It is a strong blonde Belgian ale." }],
    finalVerdict: "Lucifer offers Belgian yeast fruit and enough bitterness to stay lively with food.",
    metaTitle: "Lucifer Belgian Beer Guide | BevOry", metaDescription: "Discover Lucifer strong blonde beer, serving tips, spicy food pairings and city prices on BevOry.",
  },
  "nomad-oscuro": {
    description: "Nomad Oscuro is a dark rum crafted by East Side Distillery in Goa. Indian sugarcane rum meets Japanese hinoki wood and a finish in Jamaican oak barrels.",
    story: "The distilling team uses a German Holstein copper still in Goa. Its three-part ingredient route runs from Indian cane through Japanese cypress to Caribbean oak.",
    tastingNotes: [{ title: "Oak", description: "Toast, vanilla and coconut come from the Jamaican oak finish." }, { title: "Wood", description: "Hinoki lends a distinctive aromatic wood note beneath the darker rum character." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip a small measure over one large cube or lengthen it with soda." }, { subheading: "Food", description: "Try with Goan pork vindaloo or dark chocolate." }],
    pairingIdeas: [{ title: "With Nomad Oscuro", items: ["Goan pork vindaloo", "dark chocolate", "grilled pineapple", "pepper prawns"] }],
    whyChoose: "A Goa rum whose hinoki and Jamaican-oak elements give it a genuinely unusual route to the glass.",
    faqs: [{ question: "Where is Nomad Oscuro made?", answer: "East Side Distillery crafts Nomad Oscuro in Goa." }, { question: "What wood is used in Nomad Oscuro?", answer: "The recipe uses Japanese hinoki, then finishes the rum in Jamaican oak barrels." }],
    finalVerdict: "Nomad Oscuro rewards a slow pour where its cane, cypress and oak can each register.",
    metaTitle: "Nomad Oscuro Rum Guide | BevOry", metaDescription: "Explore Nomad Oscuro's Goa rum, hinoki, Jamaican oak, food matches and city prices on BevOry.",
  },
  "glenfiddich-the": {
    description: "Glenfiddich is a Speyside single malt made in Dufftown by William Grant & Sons. The 12-year-old is its best-known entry point, built around pear-like fruit and gentle oak.",
    story: "William Grant opened Glenfiddich in 1887 after building the distillery with his family. The name means Valley of the Deer in Gaelic, reflected in the stag on its mark.",
    tastingNotes: [{ title: "Orchard fruit", description: "The 12-year-old opens with fresh pear and soft malt." }, { title: "Oak", description: "Subtle oak and a creamy finish keep the fruit in balance." }],
    howToEnjoy: [{ subheading: "First glass", description: "Try the 12-year-old neat in a tulip glass, then add a drop of water." }, { subheading: "Food", description: "Tandoori salmon or almond biscuits match its lighter fruit profile." }],
    pairingIdeas: [{ title: "With Glenfiddich 12", items: ["tandoori salmon", "almond biscuits", "roast chicken", "mild cheddar"] }],
    whyChoose: "A clear introduction to Speyside single malt through fruit, malt and restrained oak.",
    faqs: [{ question: "Where is Glenfiddich made?", answer: "At Glenfiddich Distillery in Dufftown, Speyside, Scotland." }, { question: "Is Glenfiddich 12 a single malt?", answer: "Yes. It is a 12-year-old Speyside single malt Scotch whisky." }],
    finalVerdict: "Glenfiddich 12 is an easy place to begin when exploring Speyside malt.",
    metaTitle: "Glenfiddich Whisky Guide | BevOry", metaDescription: "Meet Glenfiddich 12's Speyside pear-and-oak profile, serving ideas and city prices on BevOry.",
  },
  "glenlivet-the": {
    description: "The Glenlivet is a Speyside single malt distilled near Ballindalloch, Scotland. Its range moves from bright, orchard-fruited 12-year-old whisky to richer older releases.",
    story: "George Smith secured one of the first legal distilling licences in the region in 1824. The Glenlivet name later became a marker of the style many Speyside producers wanted to evoke.",
    tastingNotes: [{ title: "12-year-old", description: "Pineapple and orchard fruit lead its lighter house style." }, { title: "Older releases", description: "Extended oak maturation builds more spice and dried-fruit depth in the older bottles." }],
    howToEnjoy: [{ subheading: "Glass", description: "Start neat in a tulip glass; add a little water to the older malts after the first sip." }, { subheading: "Food", description: "Chicken malai tikka or roasted almonds suit the softer fruit-led bottles." }],
    pairingIdeas: [{ title: "With The Glenlivet", items: ["chicken malai tikka", "roasted almonds", "grilled prawns", "apple tart"] }],
    whyChoose: "A historic Speyside distillery whose lighter malt style leaves room to explore its age range.",
    faqs: [{ question: "Who founded The Glenlivet?", answer: "George Smith founded the licensed Glenlivet distillery in 1824." }, { question: "Is The Glenlivet a blended Scotch?", answer: "No. The Glenlivet is a single malt Scotch whisky." }],
    finalVerdict: "The Glenlivet is a good fit when fruit and gentle malt appeal more than heavy peat.",
    metaTitle: "The Glenlivet Whisky Guide | BevOry", metaDescription: "Explore The Glenlivet's Speyside malt, age range, food matches and city prices on BevOry.",
  },
  "macallan-the": {
    description: "The Macallan is a Speyside single malt made at its estate near Craigellachie, Scotland. Sherry-seasoned oak is central to many of its well-known expressions.",
    story: "Alexander Reid established the distillery in 1824. Oak sourcing and cask seasoning have since become defining parts of the house's identity, especially in its Sherry Oak range.",
    tastingNotes: [{ title: "Sherry Oak", description: "Dried fruit and baking spice are characteristic of the sherry-seasoned cask range." }, { title: "Double Cask", description: "American and European oak give the Double Cask range a softer citrus-and-vanilla side." }],
    howToEnjoy: [{ subheading: "Pour", description: "Use a tulip glass and taste neat before deciding on water." }, { subheading: "Food", description: "Try spiced mutton or dark chocolate with a richer sherry-cask bottle." }],
    pairingIdeas: [{ title: "With The Macallan", items: ["spiced mutton", "dark chocolate", "date cake", "aged gouda"] }],
    whyChoose: "A Speyside malt house whose cask programme offers a direct comparison of oak styles.",
    faqs: [{ question: "Is The Macallan peated?", answer: "The Macallan's familiar Sherry Oak and Double Cask bottlings are known for oak and fruit, not a peated house style." }, { question: "Where is The Macallan made?", answer: "At The Macallan Estate near Craigellachie in Speyside, Scotland." }],
    finalVerdict: "Choose a Macallan expression by its cask style to find the fruit-and-oak balance you like.",
    metaTitle: "The Macallan Whisky Guide | BevOry", metaDescription: "Compare The Macallan's sherry and double-cask styles, pairings and city prices on BevOry.",
  },
  "yamazaki-the": {
    description: "Yamazaki is a Japanese single malt from Suntory's Yamazaki Distillery near Kyoto. Its range includes an unaged-statement Distiller's Reserve and age-stated releases.",
    story: "Shinjiro Torii founded the distillery in 1923 at the meeting of three rivers. Yamazaki became the starting point for Japanese malt whisky under the Suntory name.",
    tastingNotes: [{ title: "Distiller's Reserve", description: "Red fruit and gentle sweetness mark this accessible expression." }, { title: "Mature malts", description: "Older Yamazaki releases can develop richer dried fruit and wood spice." }],
    howToEnjoy: [{ subheading: "Glass", description: "Taste a small pour neat, then compare a highball with plenty of chilled soda." }, { subheading: "Food", description: "Yakitori and mushroom skewers make useful savoury matches." }],
    pairingIdeas: [{ title: "With Yamazaki", items: ["yakitori", "mushroom skewers", "tandoori salmon", "salted almonds"] }],
    whyChoose: "A foundational Japanese single malt from the country's first commercial whisky distillery.",
    faqs: [{ question: "Where is Yamazaki whisky made?", answer: "At Suntory's Yamazaki Distillery near Kyoto, Japan." }, { question: "Is Yamazaki a blended whisky?", answer: "No. Yamazaki is a Japanese single malt whisky." }],
    finalVerdict: "Yamazaki offers a Japanese malt route from bright red fruit to more mature wood spice.",
    metaTitle: "Yamazaki Whisky Guide | BevOry", metaDescription: "Explore Yamazaki Japanese single malt, serving ideas, food pairings and city prices on BevOry.",
  },
  "glenwalk-the": {
    description: "The Glenwalk is a blended Scotch whisky marketed in India by Cartel Bros. Its range includes peated and smoked blends alongside the core blended Scotch.",
    story: "Cartel Bros built Glenwalk around several distinct smoke profiles rather than one fixed house flavour. Its 5-year and 7-year variants give drinkers a choice between lighter and oakier blends.",
    tastingNotes: [{ title: "Peated 5-year", description: "Fresh floral notes sit over lingering peat in this younger variant." }, { title: "Smoked 7-year", description: "Oak becomes more prominent, with a restrained smoky edge." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try the peated expression neat first, then build a highball if you prefer a lighter serve." }, { subheading: "Food", description: "Tandoori chicken or charred mushrooms echo the smoke." }],
    pairingIdeas: [{ title: "With The Glenwalk", items: ["tandoori chicken", "charred mushrooms", "smoked almonds", "pepper paneer"] }],
    whyChoose: "Several clearly separated peat and smoke variants within one blended-Scotch range.",
    faqs: [{ question: "Is The Glenwalk made in India?", answer: "The Glenwalk is a blended Scotch whisky marketed in India by Cartel Bros." }, { question: "Does Glenwalk have peated whisky?", answer: "Yes. The producer lists peated 5-year and 7-year blends." }],
    finalVerdict: "The Glenwalk is most interesting when you compare its peated and smoked expressions side by side.",
    metaTitle: "The Glenwalk Whisky Guide | BevOry", metaDescription: "Compare The Glenwalk's peated and smoked Scotch variants, pairings and city prices on BevOry.",
  },
  "old-durbar": {
    description: "Old Durbar is a Nepalese whisky name from Yeti Distillery. Its collection spans blended reserve whisky and several Scotch blends.",
    story: "The brand links its whisky to Nepal's old palace imagery. Yeti Distillery separates Black Chimney, Two Continents and its age-stated Scotch bottles within the collection.",
    tastingNotes: [{ title: "Black Chimney", description: "A smokier direction distinguishes this bottle within the range." }, { title: "Age-stated Scotch", description: "The older blends lean toward richer malt and oak character." }],
    howToEnjoy: [{ subheading: "Glass", description: "Taste a small neat pour before adding ice or water." }, { subheading: "Food", description: "Seekh kebabs and roasted walnuts fit the richer blends." }],
    pairingIdeas: [{ title: "With Old Durbar", items: ["mutton seekh kebabs", "roasted walnuts", "grilled paneer", "dark chocolate"] }],
    whyChoose: "A Nepalese whisky house with a collection that moves between reserve blends and Scotch.",
    faqs: [{ question: "Who makes Old Durbar?", answer: "Old Durbar is licensed to Yeti Distillery in Nepal." }, { question: "Does Old Durbar make only one whisky?", answer: "No. Its collection includes Black Chimney, Two Continents and age-stated Scotch blends." }],
    finalVerdict: "Old Durbar rewards choosing by expression, especially if smoke or Scotch-malt depth matters to you.",
    metaTitle: "Old Durbar Whisky Guide | BevOry", metaDescription: "Explore Old Durbar's Nepalese whisky collection, serving ideas and city prices on BevOry.",
  },
  "oaken-glow": {
    description: "Oaken Glow is an Indian whisky from the Seagram's portfolio of Pernod Ricard India. The name points to an oak-led blended-whisky style.",
    story: "Seagram's Indian whisky portfolio grew around blends designed for the local market. Oaken Glow joined that wider stable as a label with a distinct wood-focused identity.",
    tastingNotes: [{ title: "Smoke", description: "Pernod Ricard presents Oaken Glow as a smoky whisky." }, { title: "Wood", description: "An oak-led impression sits behind the smoke." }],
    howToEnjoy: [{ subheading: "Serve", description: "Use a short glass with ice or make a light soda highball." }, { subheading: "Snack", description: "Try it with roasted peanuts or pepper paneer." }],
    pairingIdeas: [{ title: "With Oaken Glow", items: ["pepper paneer", "roasted peanuts", "chicken tikka", "grilled mushrooms"] }],
    whyChoose: "A wood-led Indian blend from the Seagram's stable.",
    faqs: [{ question: "Who owns Oaken Glow whisky?", answer: "Oaken Glow is associated with Pernod Ricard India's Seagram's portfolio." }, { question: "Is Oaken Glow a single malt?", answer: "No. It is an Indian blended-whisky label." }],
    finalVerdict: "Oaken Glow is a simple choice for an oak-leaning whisky-and-soda.",
    metaTitle: "Oaken Glow Whisky Guide | BevOry", metaDescription: "Read about Oaken Glow Indian whisky, serving ideas, food matches and city prices on BevOry.",
  },
  susegado: {
    description: "Susegado is a Goa craft-beer name associated with locally brewed ales and lagers. Its range includes a kokum gose, Dortmund-style lager and English-style ale.",
    story: "The name uses a Goan expression for taking life at an easier pace. Susegado's beer selection draws on both European styles and local ingredients such as kokum.",
    tastingNotes: [{ title: "Kokum Gose", description: "Tart kokum gives this beer a sharper, fruit-led direction." }, { title: "Dortmund Lager", description: "The lager takes a cleaner malt-and-hop route than the fruit-led gose." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the lager cold; let the gose warm slightly in the glass to show the fruit." }, { subheading: "Food", description: "Goan fish fry works with the lager and prawn balchao with the tart gose." }],
    pairingIdeas: [{ title: "Goan table", items: ["Goan fish fry", "prawn balchao", "chilli cheese toast", "fried calamari"] }],
    whyChoose: "A Goa beer range that brings kokum into a classic tart-beer style.",
    faqs: [{ question: "What is Susegado Kokum Gose?", answer: "It is a tart beer made with kokum in the gose style." }, { question: "Does Susegado make lager?", answer: "Yes. The range includes a Dortmund-style lager." }],
    finalVerdict: "The kokum gose is Susegado's most distinctive food-table choice.",
    metaTitle: "Susegado Beer Guide | BevOry", metaDescription: "Explore Susegado's Goa beer styles, kokum gose, food matches and city prices on BevOry.",
  },
  "primo-malvasia": {
    description: "Primo Malvasia is an Italian white-wine label from the Fantini group. Its Malvasia-Chardonnay blend draws fruit from the Ortona area of Abruzzo.",
    story: "Fantini built the Primo range around accessible southern and central Italian wines. The Malvasia bottling uses the aromatic grape as its lead, with Chardonnay adding body.",
    tastingNotes: [{ title: "Fruit", description: "Banana and fig appear in the producer's profile for the white blend." }, { title: "Texture", description: "A rounder Chardonnay-backed palate follows the aromatic Malvasia nose." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the white and pour it into a medium-sized wine glass." }, { subheading: "Food", description: "Paneer tikka or grilled prawns suit its fruit-forward side." }],
    pairingIdeas: [{ title: "With the white", items: ["paneer tikka", "grilled prawns", "lemon chicken", "soft goat cheese"] }],
    whyChoose: "An Abruzzo white that puts Malvasia's aroma ahead of a heavier oak style.",
    faqs: [{ question: "Which grapes are in Primo Malvasia?", answer: "The white blend is led by Malvasia with Chardonnay." }, { question: "Where does Primo Malvasia come from?", answer: "The wine comes from the Ortona area in Abruzzo, Italy." }],
    finalVerdict: "Primo Malvasia works best when its ripe fruit gets a lightly spiced plate.",
    metaTitle: "Primo Malvasia Wine Guide | BevOry", metaDescription: "Discover Primo Malvasia's Abruzzo blend, tasting notes, pairings and city prices on BevOry.",
  },
  "tombacco-biferno": {
    description: "Tombacco Biferno Rosso Riserva is an Italian red from Molise made by the Tombacco family. Montepulciano forms most of the blend, with Aglianico alongside it.",
    story: "The Biferno DOC takes its name from a river in Molise. Tombacco uses the region's two red grapes to build a reserve wine with both ripe fruit and structure.",
    tastingNotes: [{ title: "Fruit", description: "Cherry and plum carry the nose and palate." }, { title: "Spice", description: "Vanilla, cinnamon and a firmer red-wine finish follow the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a broad red-wine glass." }, { subheading: "Table", description: "Mutton rogan josh or grilled lamb can meet its tannin and spice." }],
    pairingIdeas: [{ title: "With Biferno", items: ["mutton rogan josh", "grilled lamb", "mushroom ragù", "aged pecorino"] }],
    whyChoose: "A Molise reserve red with a clear Montepulciano-Aglianico identity.",
    faqs: [{ question: "Where is Tombacco Biferno made?", answer: "It is a Biferno DOC wine from Molise, Italy." }, { question: "Which grapes are in the Rosso Riserva?", answer: "Tombacco lists Montepulciano and Aglianico in the blend." }],
    finalVerdict: "A generous Italian red for a meal with slow-cooked spice or grilled meat.",
    metaTitle: "Tombacco Biferno Wine Guide | BevOry", metaDescription: "Explore Tombacco Biferno's Molise grapes, cherry-spice profile, pairings and city prices on BevOry.",
  },
  "luna-argenta": {
    description: "Luna Argenta is an Italian sparkling-wine label in the Mondo del Vino group. The range includes Prosecco DOC Brut and a pink Prosecco Rosé.",
    story: "The two bottles offer different routes into Prosecco: Glera for the white Brut, and Glera with Pinot Nero for the rosé. Both sit within northern Italy's Prosecco appellation.",
    tastingNotes: [{ title: "Brut", description: "Fresh floral notes and pear lead the white Prosecco." }, { title: "Rosé", description: "Raspberry joins pear in the pink wine's brighter fruit profile." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill well and use a tulip sparkling-wine glass rather than a wide coupe." }, { subheading: "Food", description: "The Brut suits tandoori prawns; try the rosé with strawberry tart." }],
    pairingIdeas: [{ title: "With bubbles", items: ["tandoori prawns", "vegetable tempura", "strawberry tart", "soft goat cheese"] }],
    whyChoose: "A simple comparison between white and rosé Prosecco under one Italian label.",
    faqs: [{ question: "What grape is used in Luna Argenta Prosecco?", answer: "The white Prosecco uses Glera; the rosé also includes Pinot Nero." }, { question: "Is Luna Argenta Champagne?", answer: "No. It is Italian Prosecco, not wine from Champagne in France." }],
    finalVerdict: "Choose the Brut for a clean aperitif or the rosé when a red-fruit note fits the food.",
    metaTitle: "Luna Argenta Prosecco Guide | BevOry", metaDescription: "Compare Luna Argenta Brut and Rosé Prosecco, pairings and city prices on BevOry.",
  },
  tocornal: {
    description: "Tocornal is a Chilean wine label linked to Cono Sur. Its Merlot is a fruit-forward red sourced from Chile's Central Valley.",
    story: "Cono Sur developed Tocornal as an accessible route to Chilean varietal wine. The Merlot places the grape name clearly on the bottle, making it an easy starting point for that style.",
    tastingNotes: [{ title: "Fruit", description: "Cherry, plum and dark forest fruit mark the Merlot's profile." }, { title: "Body", description: "A soft red-wine texture keeps the fruit in front." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try chicken tikka or mushroom pulao with the Merlot." }],
    pairingIdeas: [{ title: "With Tocornal Merlot", items: ["chicken tikka", "mushroom pulao", "lamb cutlets", "mild cheddar"] }],
    whyChoose: "A direct, fruit-led Chilean Merlot without a complicated entry point.",
    faqs: [{ question: "Where is Tocornal Merlot from?", answer: "It is a Chilean Merlot from the Central Valley." }, { question: "Is Tocornal a red wine?", answer: "The Tocornal Merlot listed here is a red wine." }],
    finalVerdict: "Tocornal Merlot is an uncomplicated red for a weeknight meal with savoury spice.",
    metaTitle: "Tocornal Merlot Guide | BevOry", metaDescription: "Read Tocornal Merlot's Chilean fruit profile, dinner pairings and city prices on BevOry.",
  },
  durvillea: {
    description: "Durvillea is a Marlborough wine range from New Zealand producer Astrolabe. Pinot Noir and Chardonnay show its red and white sides.",
    story: "The name recalls the seaweed Durvillea and explorer Dumont d'Urville, linked to the Astrolabe story. The wines come from the Marlborough region at the top of New Zealand's South Island.",
    tastingNotes: [{ title: "Pinot Noir", description: "Cherry, forest fruit and spice sit in a supple red with a dry finish." }, { title: "Chardonnay", description: "Peach and citrus meet gentle oak and a lightly creamy finish." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill the Chardonnay; pour the Pinot Noir lightly cool, not warm." }, { subheading: "Food", description: "Pair the Pinot with duck or paneer tikka, and the Chardonnay with tandoori fish." }],
    pairingIdeas: [{ title: "Across the range", items: ["duck roast", "paneer tikka", "tandoori fish", "roasted vegetables"] }],
    whyChoose: "Marlborough Pinot and Chardonnay with distinct fruit profiles under one Astrolabe range.",
    faqs: [{ question: "Who makes Durvillea wine?", answer: "Durvillea is made by Astrolabe in Marlborough, New Zealand." }, { question: "Does Durvillea make red and white wine?", answer: "Yes. Its range includes Pinot Noir and Chardonnay." }],
    finalVerdict: "Durvillea lets you pick between cherry-led Pinot and gently oaked Chardonnay.",
    metaTitle: "Durvillea Wine Guide | BevOry", metaDescription: "Explore Durvillea's Marlborough Pinot Noir and Chardonnay, pairings and city prices on BevOry.",
  },
  "seven-islands": {
    description: "Seven Islands is an Indian pure-malt whisky from Tilaknagar Industries. Its blend brings together two Indian malts and two Scottish malts.",
    story: "Tilaknagar introduced Seven Islands as a four-malt release, using the meeting of Indian and Scottish whiskies as its main idea. The name refers to the islands that formed Mumbai.",
    tastingNotes: [{ title: "Malt", description: "A layered malt character comes from the four-whisky blend." }, { title: "Oak", description: "Oak and soft spice support the malt rather than a neutral-grain base." }],
    howToEnjoy: [{ subheading: "Glass", description: "Take the first sip neat in a tulip glass, then add water sparingly." }, { subheading: "Food", description: "Mutton seekh and roasted almonds suit its fuller malt weight." }],
    pairingIdeas: [{ title: "With Seven Islands", items: ["mutton seekh", "roasted almonds", "grilled paneer", "dark chocolate"] }],
    whyChoose: "A pure-malt meeting of two Indian and two Scottish whiskies.",
    faqs: [{ question: "Who makes Seven Islands whisky?", answer: "Seven Islands is a Tilaknagar Industries whisky." }, { question: "How many malts are in Seven Islands?", answer: "The producer describes four malts: two from India and two from Scotland." }],
    finalVerdict: "Seven Islands is a malt-focused Indian blend with a clear cross-border recipe.",
    metaTitle: "Seven Islands Whisky Guide | BevOry", metaDescription: "Discover Seven Islands' four-malt blend, serving tips, pairings and city prices on BevOry.",
  },
  woodsmen: {
    description: "Woodsmen is an Indian whisky name built around Himalayan water and mountain malts. The range includes Mountain Whiskey and other blends with different flavour directions.",
    story: "The brand was created by a first-generation Indian whisky entrepreneur with a focus on Himalayan ingredients. Its mountain identity is more than packaging: the water and malt origins are central to the producer's account.",
    tastingNotes: [{ title: "Mountain", description: "The flagship mountain expression leans toward fruit, floral malt and oak." }, { title: "Smokier bottles", description: "Other Woodsmen expressions use peat for a more smoke-led profile." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try Mountain Whiskey over one cube or in a chilled soda highball." }, { subheading: "Food", description: "Mushroom tikka or chicken seekh works with the malt; choose smoky snacks for the peated bottle." }],
    pairingIdeas: [{ title: "With Woodsmen", items: ["mushroom tikka", "chicken seekh", "smoked almonds", "grilled corn"] }],
    whyChoose: "A mountain-framed Indian whisky range with separate fruit-led and peated choices.",
    faqs: [{ question: "Is Woodsmen an Indian whisky?", answer: "Yes. Woodsmen presents itself as an Indian Himalayan whisky brand." }, { question: "Are all Woodsmen whiskies smoky?", answer: "No. The range has both fruit-led Mountain Whiskey and smokier expressions." }],
    finalVerdict: "Choose the Woodsmen expression by whether you want bright malt or peat smoke.",
    metaTitle: "Woodsmen Whisky Guide | BevOry", metaDescription: "Compare Woodsmen's Himalayan whisky styles, serving ideas and city prices on BevOry.",
  },
  "maka-di": {
    description: "Maka Di is a craft beer brewed in Latambarcem, Goa. The range draws on Belgian and German styles, alongside beers made with local ingredients.",
    story: "Latambarcem Brewers built its Goa brewery near the Western Ghats. Early releases included Belgian Blanche, Bavarian Keller, Honey Ale and Belgian Tripel.",
    tastingNotes: [{ title: "Belgian Blanche", description: "Wheat-beer freshness and citrus make this the lighter aromatic choice." }, { title: "Honey Ale", description: "Honey adds a rounder malt sweetness to the ale." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the Blanche cool into a tall beer glass; give the Tripel a wider glass and more time." }, { subheading: "Food", description: "Goan fish fry and pepper prawns work with the fresher beers." }],
    pairingIdeas: [{ title: "With Maka Di", items: ["Goan fish fry", "pepper prawns", "chicken cafreal", "salted peanuts"] }],
    whyChoose: "Goa-brewed beer that gives Belgian and Bavarian styles a local setting.",
    faqs: [{ question: "Where is Maka Di beer brewed?", answer: "At the Maka Di brewery in Latambarcem, Goa." }, { question: "What styles does Maka Di make?", answer: "Its range includes Belgian Blanche, Bavarian Keller, Honey Ale and Belgian Tripel." }],
    finalVerdict: "Maka Di is worth exploring one style at a time, especially beside Goan seafood.",
    metaTitle: "Maka Di Beer Guide | BevOry", metaDescription: "Explore Maka Di's Goa-brewed Belgian and Bavarian beers, food matches and city prices on BevOry.",
  },
  "arthaus-collective-blended-malt": {
    description: "Arthaus Collective is a blended malt Scotch whisky in ABD Maestro's Indian portfolio. It combines Highland and Speyside malts rather than adding grain whisky.",
    story: "ABD Maestro developed Arthaus around the Bauhaus school's meeting of art and design. The label's visual identity follows that idea while the whisky remains a Scotch blended malt.",
    tastingNotes: [{ title: "Malt", description: "Highland weight and Speyside fruit provide two sides of the blend." }, { title: "Finish", description: "Oak and gentle spice follow the malt sweetness." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip neat from a tulip glass before trying a drop of water." }, { subheading: "Food", description: "Galouti kebabs or roasted hazelnuts suit the fuller malt style." }],
    pairingIdeas: [{ title: "With Arthaus", items: ["galouti kebabs", "roasted hazelnuts", "tandoori mushrooms", "aged cheddar"] }],
    whyChoose: "A Scotch blend built entirely from malts across two well-known Scottish regions.",
    faqs: [{ question: "Is Arthaus Collective a single malt?", answer: "No. It is a blended malt Scotch whisky, made from more than one malt whisky." }, { question: "Which regions contribute to Arthaus?", answer: "The producer identifies Highland and Speyside malts." }],
    finalVerdict: "Arthaus suits a drinker who wants Scotch malt complexity without a single-distillery profile.",
    metaTitle: "Arthaus Collective Whisky Guide | BevOry", metaDescription: "Meet Arthaus Collective's Highland-Speyside blended malt, pairings and city prices on BevOry.",
  },
  rahasya: {
    description: "Rahasya is an Indian craft vodka from House of Blisswater. The label centres Indian ingredients and a deliberately guarded recipe.",
    story: "Rahasya means mystery in Sanskrit. Blisswater launched the vodka in 2020 after a long development period focused on Indian culinary heritage.",
    tastingNotes: [{ title: "Aroma", description: "A retailer describes a sweet, saunf-like aroma in the infused vodka." }, { title: "Palate", description: "The same tasting account finds a mukhwas-like sweetness rather than a strictly neutral vodka taste." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try a chilled short pour or mix with soda and a slice of lime." }, { subheading: "Food", description: "Tandoori prawns and spiced makhana make practical companions." }],
    pairingIdeas: [{ title: "With Rahasya", items: ["tandoori prawns", "spiced makhana", "chilli paneer", "cucumber salad"] }],
    whyChoose: "An Indian vodka that makes its local flavour identity part of the drink itself.",
    faqs: [{ question: "What does Rahasya mean?", answer: "Rahasya is the Hindi word for secret." }, { question: "Who makes Rahasya vodka?", answer: "Rahasya is made by House of Blisswater." }],
    finalVerdict: "Rahasya is a good choice when a chilled vodka should bring a little more character than neutrality.",
    metaTitle: "Rahasya Vodka Guide | BevOry", metaDescription: "Explore Rahasya Indian craft vodka, easy serves, Indian food pairings and city prices on BevOry.",
  },
  "eight-finger-eddie": {
    description: "Eight Finger Eddie is a beer from Goa Brewing Co. It is an oat-cream IPA made for a softer body than a lean, sharply bitter IPA.",
    story: "Goa Brewing Co named the beer after Eight Finger Eddie, a figure associated with Goa's counterculture. The recipe uses oats and dry hopping to put texture and hop aroma together.",
    tastingNotes: [{ title: "Hops", description: "Tropical fruit aroma leads the dry-hopped side." }, { title: "Body", description: "Oats lend a creamy, soft mouthfeel beneath the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour cool into a clean IPA glass or tumbler to release the hop aroma." }, { subheading: "Food", description: "Try with chilli garlic prawns or a crisp chicken burger." }],
    pairingIdeas: [{ title: "With the IPA", items: ["chilli garlic prawns", "chicken burger", "peri-peri fries", "paneer chilli"] }],
    whyChoose: "Tropical dry hopping and an oat-softened body in one Goa IPA.",
    faqs: [{ question: "Who brews Eight Finger Eddie?", answer: "Goa Brewing Co brews Eight Finger Eddie." }, { question: "What kind of beer is Eight Finger Eddie?", answer: "It is an oat-cream IPA with dry-hopped fruit character." }],
    finalVerdict: "Eight Finger Eddie brings hop fruit without leaving the palate lean and scratchy.",
    metaTitle: "Eight Finger Eddie Beer Guide | BevOry", metaDescription: "Discover Eight Finger Eddie oat-cream IPA, Goa beer pairings and city prices on BevOry.",
  },
  barbar: {
    description: "Barbar is a Belgian honey-beer range brewed by Brasserie Lefebvre in Rebecq. The blonde combines malted barley, wheat, honey, bitter orange peel and coriander.",
    story: "The family brewery in Rebecq has operated since the nineteenth century. Barbar's blonde beer came first; Rouge later added cherry to the honey-beer idea.",
    tastingNotes: [{ title: "Blonde", description: "Honey, citrus and floral spice sit over a round, low-bitterness palate." }, { title: "Rouge", description: "Cherry takes the lead, with honey and spice underneath." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve cool in a tulip glass so the honey and fruit aromas stay visible." }, { subheading: "Food", description: "The blonde suits tandoori chicken; the cherry Rouge works with chocolate cake." }],
    pairingIdeas: [{ title: "Across Barbar", items: ["tandoori chicken", "grilled prawns", "goat cheese", "chocolate cake"] }],
    whyChoose: "A Belgian beer range with real honey at the centre of both blonde and cherry styles.",
    faqs: [{ question: "Where is Barbar beer brewed?", answer: "Brasserie Lefebvre brews Barbar in Rebecq, Belgium." }, { question: "Does Barbar beer contain honey?", answer: "Yes. Honey is part of the Barbar blonde recipe and the Rouge range." }],
    finalVerdict: "Barbar Blonde makes honey feel at home in beer; Rouge gives the idea a cherry turn.",
    metaTitle: "Barbar Beer Guide | BevOry", metaDescription: "Explore Barbar Belgian honey beer, Blonde and Rouge notes, pairings and city prices on BevOry.",
  },
  cabana: {
    description: "Cabana is a tender-coconut liqueur from Goa-based RedKraft Beverages. It combines a coconut-led flavour with the format of a mixed-drink spirit.",
    story: "RedKraft developed Cabana as part of a Goa portfolio that also includes agave spirit and herbal liqueur. The tender-coconut angle gives the bottle a local identity distinct from cream-based coconut liqueurs.",
    tastingNotes: [{ title: "Coconut", description: "Tender coconut is the central flavour, with a fresher edge than toasted coconut." }, { title: "Texture", description: "A liqueur-like sweetness rounds the coconut profile." }],
    howToEnjoy: [{ subheading: "Mix", description: "Serve chilled with soda or blend into a measured tropical cocktail." }, { subheading: "Food", description: "Goan prawn curry or pineapple slices echo its coastal coconut note." }],
    pairingIdeas: [{ title: "With Cabana", items: ["Goan prawn curry", "grilled pineapple", "chilli cashews", "coconut tart"] }],
    whyChoose: "A Goa tender-coconut liqueur with a flavour rooted in the region's drinking culture.",
    faqs: [{ question: "What is Cabana liqueur?", answer: "Cabana is a tender-coconut liqueur from RedKraft Beverages." }, { question: "Where is Cabana from?", answer: "RedKraft is a Goa-based beverage company." }],
    finalVerdict: "Cabana works when a cocktail calls for fresh coconut rather than heavy cream.",
    metaTitle: "Cabana Coconut Liqueur Guide | BevOry", metaDescription: "Meet Cabana Goa tender-coconut liqueur, cocktail ideas, pairings and city prices on BevOry.",
  },
};
