import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_27 = [
  ["alejandro", "Alejandro", "India", "Dark Rum", "a9010fd21a93c687b3c4c506"],
  ["aodh", "AODH", "Ireland", "Irish Whiskey", "7d5c14fc8703d0f36bc33a2b"],
  ["ashanti", "Ashanti", "Guatemala", "Spiced Rum", "2bd7854a77bba6894ac42c43"],
  ["beor", "Beor", "India", "Beer", "58d979261d15194f48e13617"],
  ["boho", "Boho", "India", "Whisky", "b7878aa1e95ec4a1aa1214fa"],
  ["born-west", "Born West", "United States", "Wine", "0327793b21ef9aaed7e40490"],
  ["buho", "Buho", "Belgium", "Beer", "8bc4573b81b7b42f275ec7cf"],
  ["camino", "Camino Real", "Mexico", "Tequila", "27560a33075a3c2abeaba93e"],
  ["cobalto", "Cobalto", "Portugal", "Gin", "e249a57581517e567f368d67"],
  ["communiti", "Communiti", "India", "Beer", "8042a23a3c8fcaed5b30a11f"],
  ["coopers-best", "Coopers Best", "Australia", "Stout", "f76ab7f54371e4da3a3483e0"],
  ["coopers-original", "Coopers Original", "Australia", "Pale Ale", "c88346a328765032ccd12b85"],
  ["el-goonda", "El Goonda", "India", "Agave Spirit", "4a8fc33cd4f1c7aa9e21ad3a"],
  ["fandango", "Fandango", "Mexico", "Mezcal", "bf97c7347cde85721c2e4f23"],
  ["frizzano", "Frizzano", "India", "Sparkling Wine", "6cb19687c66519af1f45dc7d"],
  ["glen-talloch", "Glen Talloch", "Scotland", "Blended Scotch Whisky", "a912f305dc3582a7c8a1e0b8"],
  ["grizly", "Grizly", "India", "Hard Seltzer Ale", "526133f0f8a6e9099d0a6c0b"],
  ["great-indian", "Great Indian", "India", "Gin", "3dd4f3cc0e1df835c3107426"],
  ["happiness", "Happiness", "India", "Gin", "42f38c12577ba328f23ac4b4"],
  ["hill-station", "Hill Station", "India", "Hard Cider Ale", "aeecb4b0ab363d5abd846bca"],
  ["hopper", "Hopper", "Belgium", "Beer", "392a5bcbd71a7db2cfb9796c"],
  ["jamun", "Jamun", "India", "Gin", "da152a3cb144cf9a0cab669b"],
  ["kashmyr", "Kashmyr", "India", "Vodka", "790a886512a3919aff266113"],
  ["lemount", "Lemount", "India", "Beer", "977323164c276b6c63d0e324"],
  ["macroys", "MacRoys", "Scotland", "Blended Scotch Whisky", "377e8a5710b44d1028e0d2d5"],
  ["madhvan", "Madhvan", "India", "Whisky", "984363179e60327831dd9cdb"],
  ["oakton", "Oakton", "India", "Whisky", "eecc97642048661d0d0d130f"],
  ["roulette", "Roulette", "India", "Whisky and Brandy", "eecc957965147f769a83a257"],
  ["thunderbolt", "Thunderbolt", "India", "Beer", "c672b342b8aea5e4f2eb31b4"],
  ["tilt", "Tilt", "India", "Wine", "2b63bd1a162bbc8d18cef589"],
] as const;

// Editorial research references are not rendered in public brand fields.
export const BRAND_SOURCES_BATCH_27: Record<string, string[]> = {
  alejandro: ["https://www.tallidrinks.com/product-page/alejandro-crafted-dark-rum"],
  aodh: ["https://aodhwhiskey.com/", "https://nsearchives.nseindia.com/corporate/ABDINDIA_29012026194611_SE_-_Investor_Presentation_sd.pdf"],
  ashanti: ["https://ashanti-rum.com/the-product/"],
  beor: ["https://www.brewsnspirits.in/brewking-debuts-beor-360-wheat-and-lager"],
  boho: ["https://adsspirits.com/boho-whisky/"],
  "born-west": ["https://bornwest.co.in/"],
  buho: ["https://brewsnspirits.in/buho-beer-with-a-twist"],
  camino: ["https://www.bacardijapan.jp/products/brands/camino-real/", "https://bg.coca-colahellenic.com/en/our-24-7-portfolio/brands-a-z/camino-real-tequila"],
  cobalto: ["https://cobaltodouro.pt/wp-content/uploads/2022/09/CD-CO17-TechnicalSheet.pdf"],
  communiti: ["https://www.communitiindia.com/our-craft-beers.php"],
  "coopers-best": ["https://coopers.com.au/products/best-extra-stout"],
  "coopers-original": ["https://coopers.com.au/products/original-pale-ale"],
  "el-goonda": ["https://goondalife.com/agave-spirit/", "https://goondalife.com/faq/"],
  fandango: ["https://www.mezcaldistrict.com/fandango"],
  frizzano: ["https://gooddropwine.com/wines/", "https://gooddropwine.com/product/frizzano-extra-dry-sparkling-wine/"],
  "glen-talloch": ["https://www.verthemis.com/sales/scotch-whiskies"],
  grizly: ["https://conference.nrai.org/files/uploads/2024/04/NRAI-JAN-MAR-2024_compressed-1.pdf"],
  "great-indian": ["https://www.cntraveller.in/story/this-new-indian-gin-wants-to-convert-vodka-lovers/", "https://brewsnspirits.in/world-of-brands-pours-out-3-gigs"],
  happiness: ["https://happinessinabottle.in/home/", "https://www.linkedin.com/posts/officialradicokhaitan_happinessinabottle-colorsofhappiness-joyofsharing-activity-7081662100544077824-nbl4"],
  "hill-station": ["https://conference.nrai.org/files/uploads/2024/04/NRAI-JAN-MAR-2024_compressed-1.pdf"],
  hopper: ["https://guns2gewurztraminer.com/hopper/", "https://www.thebeercafe.com/wp-content/uploads/2025/08/Beverage-Menu-Aug25.pdf"],
  jamun: ["https://mohanmeakin.com/gin/", "https://iwsc.net/results/detail/152635/jamun-the-himalayan-juniper-dry-gin"],
  kashmyr: ["https://nsearchives.nseindia.com/corporate/RADICO_28072025093158_pressrelease28072025.pdf"],
  lemount: ["https://mounteverestbreweries.com/products/lemount/"],
  macroys: ["https://macroys.in/discover-our-whiskey.html"],
  madhvan: ["https://madhvan.co.in/", "https://www.linkedin.com/posts/uppal-brewers-distillers_uppalbrewersanddistillers-madhvan-premiumwhisky-activity-7375857237887504384-qXEe"],
  oakton: ["https://stockdiscovery.s3.amazonaws.com/india/company/4898/3592/AR-25.pdf"],
  roulette: ["https://www.jdl.in/roulette.php", "https://www.jdl.in/john-distilleries-launches-premium-blended-whisky.php"],
  thunderbolt: ["https://inbrew.com/our-brands"],
  tilt: ["https://fratelliwines.in/blogs/our-story/tilt"],
};

// The saved catalogue has a logo URL for each identity. Do not replace one blindly.
export const BRAND_LOGOS_BATCH_27: Record<string, string> = {};

export const BRAND_CONTENT_BATCH_27: Record<string, BrandPublicContent> = {
  alejandro: {
    description: "Alejandro is a dark rum made in Goa by Adinco Distilleries. Its recipe brings Goan red rice together with cinnamon, nutmeg and vanilla.",
    story: "Alejandro draws on Goa's rum-making culture while giving red rice a place in the blend. Adinco uses oak wood chips in its finishing process, adding a gentle woody edge to the spice.",
    tastingNotes: [{ title: "Spice", description: "Cinnamon and nutmeg sit above the rum's darker sweetness." }, { title: "Finish", description: "Vanilla and a soft oak note linger after the spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try a short pour over one cube, or lengthen it with chilled cola and lime." }, { subheading: "Food", description: "Its baking-spice character works with Goan pork vindaloo, roasted cashews or caramel pudding." }],
    pairingIdeas: [{ title: "Goan table", items: ["pork vindaloo", "roasted cashews", "caramel pudding", "grilled pineapple"] }],
    whyChoose: "A Goan dark rum with red rice and an unmistakable baking-spice direction.",
    faqs: [{ question: "Where is Alejandro rum made?", answer: "Adinco Distilleries makes Alejandro in Goa, India." }, { question: "What gives Alejandro its spiced character?", answer: "The maker lists cinnamon, nutmeg and vanilla among its flavour ingredients." }],
    finalVerdict: "Alejandro is a good match for drinkers who like rum's sweetness edged with warm spice.",
    metaTitle: "Alejandro Dark Rum Guide | BevOry", metaDescription: "Discover Alejandro dark rum from Goa, its red-rice and spice profile, serving ideas and pairings. Check city prices on BevOry.",
  },
  ashanti: {
    description: "Ashanti is a Guatemalan spiced rum made with hibiscus and ginger. The rum at its heart is aged for three years before those two ingredients give it a floral, warming turn.",
    story: "Ashanti brings together Guatemalan sugarcane spirit, hibiscus associated with West Africa and ginger sourced from India. The rum originates near Quetzaltenango, where the producer describes high-altitude ageing.",
    tastingNotes: [{ title: "Aroma", description: "Roasted honey and vanilla meet the freshness of hibiscus." }, { title: "Finish", description: "Ginger brings a warm, lightly citrus-edged finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour over ice with a squeeze of lime, or keep it neat in a small tumbler." }, { subheading: "Food", description: "Try it with ginger chicken, chilli paneer or a square of dark chocolate." }],
    pairingIdeas: [{ title: "Floral spice", items: ["ginger chicken", "chilli paneer", "dark chocolate", "grilled pineapple"] }],
    whyChoose: "Hibiscus gives this Guatemalan spiced rum a fresher edge than the usual vanilla-led style.",
    faqs: [{ question: "Where does Ashanti rum come from?", answer: "Its aged rum comes from Guatemala, near Quetzaltenango." }, { question: "What spices are used in Ashanti?", answer: "Ashanti is flavoured with hibiscus flower and ginger." }],
    finalVerdict: "Ashanti balances rum sweetness with a floral lift and a real ginger finish.",
    metaTitle: "Ashanti Spiced Rum Guide | BevOry", metaDescription: "Explore Ashanti spiced rum from Guatemala, its hibiscus and ginger notes, serving ideas and pairings. Check city prices on BevOry.",
  },
  "born-west": {
    description: "Born West is a California wine range sold in India. Its Cabernet Sauvignon and Chardonnay put two familiar grapes at the centre of the line.",
    story: "The Born West range looks to California's vineyards for its wines rather than borrowing an Indian origin story. Cabernet Sauvignon and Chardonnay give drinkers a clear choice between a structured red and a fruit-led white.",
    tastingNotes: [{ title: "Cabernet Sauvignon", description: "Redcurrant and raspberry meet a touch of vanilla and pepper." }, { title: "Chardonnay", description: "Apricot and peach lead, with pineapple, citrus and honey behind them." }],
    howToEnjoy: [{ subheading: "Serve", description: "Give the Cabernet a broad red-wine glass; serve the Chardonnay chilled in a white-wine glass." }, { subheading: "Food", description: "Put the red beside galouti kebabs and the white beside tandoori fish or paneer tikka." }],
    pairingIdeas: [{ title: "Two California styles", items: ["galouti kebabs", "tandoori fish", "paneer tikka", "roast chicken"] }],
    whyChoose: "A straightforward California pair for anyone choosing between Cabernet and Chardonnay.",
    faqs: [{ question: "Where is Born West wine from?", answer: "Born West presents its wines as Californian wines." }, { question: "Does Born West make red and white wine?", answer: "Yes. The range includes Cabernet Sauvignon red and Chardonnay white." }],
    finalVerdict: "Born West makes the red-or-white decision easy without dressing up either grape.",
    metaTitle: "Born West Wine Guide | BevOry", metaDescription: "Compare Born West Cabernet Sauvignon and Chardonnay from California, with tasting notes and pairings. Check city prices on BevOry.",
  },
  camino: {
    description: "Camino Real is a tequila from Jalisco, Mexico, offered in Blanco and Gold styles. The Blanco is bottled without ageing; Gold takes a milder, lightly rested direction.",
    story: "Bacardi traces Camino Real's tequila history back more than 70 years. Its gourd-shaped bottle has remained a recognisable part of the brand, while the two styles offer different ways to taste Jalisco tequila.",
    tastingNotes: [{ title: "Blanco", description: "Fresh agave leads a direct, lively pour." }, { title: "Gold", description: "A softer, rounder impression distinguishes it from the unaged Blanco." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use Blanco with fresh lime in a Margarita; try Gold over ice with grapefruit soda." }, { subheading: "Food", description: "Pair with tandoori prawns, chilli-lime corn or chicken tacos." }],
    pairingIdeas: [{ title: "Agave snacks", items: ["tandoori prawns", "chilli-lime corn", "chicken tacos", "salted peanuts"] }],
    whyChoose: "A Jalisco tequila line with a clear unaged-versus-Gold choice.",
    faqs: [{ question: "Where is Camino Real tequila made?", answer: "Camino Real is a tequila from Jalisco, Mexico." }, { question: "What is the difference between Camino Real Blanco and Gold?", answer: "Blanco is unaged, while Gold is presented as a softer, lightly rested style." }],
    finalVerdict: "Camino Real Blanco is the sharper cocktail pick; Gold makes a rounder mixed drink.",
    metaTitle: "Camino Real Tequila Guide | BevOry", metaDescription: "Discover Camino Real Blanco and Gold tequila from Jalisco, with serving ideas and Indian pairings. Check city prices on BevOry.",
  },
  cobalto: {
    description: "Cobalto-17 is a gin made in Portugal's Douro region. It uses juniper, peppermint, verbena, cardamom, pear and the local Tinta Amarela grape as its six botanicals.",
    story: "The producer makes separate botanical infusions before distillation in Lamego. The finished gin is filtered three times, rested in bottle for 17 days and hand bottled.",
    tastingNotes: [{ title: "Herbal edge", description: "Peppermint and verbena give the juniper a cool, green lift." }, { title: "Fruit and spice", description: "Pear and Tinta Amarela add a fruit note beside cardamom." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use plain tonic and a thin pear slice; a highly flavoured mixer would bury the herbs." }, { subheading: "Food", description: "Serve with tandoori prawns, lemon fish or coriander paneer tikka." }],
    pairingIdeas: [{ title: "Herb and citrus", items: ["tandoori prawns", "lemon fish", "coriander paneer tikka", "salted almonds"] }],
    whyChoose: "A Douro gin whose pear and wine grape make a real change from citrus-heavy recipes.",
    faqs: [{ question: "Where is Cobalto gin made?", answer: "Cobalto-17 is made in Lamego in Portugal's Douro region." }, { question: "Which botanicals are in Cobalto-17?", answer: "Its six botanicals are juniper, peppermint, verbena, cardamom, pear and Tinta Amarela grape." }],
    finalVerdict: "Cobalto-17 rewards a simple tonic that leaves its Douro fruit and green herbs in view.",
    metaTitle: "Cobalto Gin Guide | BevOry", metaDescription: "Explore Cobalto-17 gin from the Douro, with pear, herbs and Tinta Amarela grape. Find pairings and check city prices on BevOry.",
  },
  fandango: {
    description: "Fandango is a mezcal made in Mexico from Espadin agave. Its agave is roasted for an extended period and the spirit is double distilled, giving the range a smoke-led character.",
    story: "Fandango follows the mezcal route of cooking agave before distillation, rather than using a flavoured neutral spirit. Espadin is the named agave in the producer's expression.",
    tastingNotes: [{ title: "Aroma", description: "Roasted agave brings a clear smoky opening." }, { title: "Palate", description: "The smoke stays close to the cooked agave rather than turning sweet." }],
    howToEnjoy: [{ subheading: "Sip", description: "Serve a small neat pour in a copita, with orange on the side." }, { subheading: "Food", description: "Try it beside mushroom tacos, grilled corn or tandoori paneer." }],
    pairingIdeas: [{ title: "Smoke and char", items: ["mushroom tacos", "grilled corn", "tandoori paneer", "chilli-lime peanuts"] }],
    whyChoose: "An Espadin mezcal with roast and smoke at the front of the glass.",
    faqs: [{ question: "What agave is used for Fandango mezcal?", answer: "The producer identifies Espadin agave." }, { question: "Is Fandango smoky?", answer: "Yes. Its long-roasted agave gives it a smoky character." }],
    finalVerdict: "Fandango keeps the focus on cooked agave and the savoury side of smoke.",
    metaTitle: "Fandango Mezcal Guide | BevOry", metaDescription: "Discover Fandango Espadin mezcal, roasted-agave smoke, serving ideas and food pairings. Check city prices on BevOry.",
  },
  "great-indian": {
    description: "Great Indian is an Indian gin range from World of Brands. Native Dry sits alongside Nagpur Orange and Shimla Green Apple expressions, each taking a different fruit direction.",
    story: "World of Brands developed Great Indian around a nine-botanical gin recipe with juniper, coriander, lemon peel, cassia, cardamom, fennel, angelica, liquorice and pepper. The spirit is triple distilled before the range splits into its named styles.",
    tastingNotes: [{ title: "Native Dry", description: "Juniper and lemon peel lead, with cardamom and pepper adding spice." }, { title: "Nagpur Orange", description: "Orange gives the gin a bright citrus accent over the botanical base." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Keep Native Dry with plain tonic; give Nagpur Orange a fresh orange peel garnish." }, { subheading: "Food", description: "Choose tandoori fish, pepper paneer or roasted makhana." }],
    pairingIdeas: [{ title: "Indian gin table", items: ["tandoori fish", "pepper paneer", "roasted makhana", "chilli-lime peanuts"] }],
    whyChoose: "An Indian botanical gin with clearly named orange and apple alternatives to its dry expression.",
    faqs: [{ question: "Who makes Great Indian gin?", answer: "Great Indian is a gin range from World of Brands in India." }, { question: "What Great Indian gin variants are there?", answer: "The range includes Native Dry, Nagpur Orange and Shimla Green Apple." }],
    finalVerdict: "Start with Native Dry for the botanical core, then choose a fruit expression for a lighter tonic.",
    metaTitle: "Great Indian Gin Guide | BevOry", metaDescription: "Explore Great Indian Native Dry, Nagpur Orange and Shimla Green Apple gin with food pairings. Check city prices on BevOry.",
  },
  hopper: {
    description: "Hopper is a Belgian-brewed beer range brought to India through Brindco. Witbier and Blonde give it a spiced wheat-beer side and a clearer, malt-led side.",
    story: "Brindco developed Hopper with Brouwerij De Brabandere in Bavikhove, Belgium. The partnership puts Belgian brewing behind a beer line intended for Indian bars and shops.",
    tastingNotes: [{ title: "Witbier", description: "Wheat softness, coriander and Curacao orange peel give this beer a citrus-spiced nose." }, { title: "Blonde", description: "A light spicy edge sits over the Blonde's malt character." }],
    howToEnjoy: [{ subheading: "Pour", description: "Use a tall glass for Witbier and a clean pint glass for Blonde; chill both before serving." }, { subheading: "Food", description: "Try Witbier with tandoori prawns and Blonde with chilli paneer or fish fry." }],
    pairingIdeas: [{ title: "Belgian beer snacks", items: ["tandoori prawns", "chilli paneer", "fish fry", "salted fries"] }],
    whyChoose: "Belgian-made wheat and blonde beers with noticeably different spice and malt profiles.",
    faqs: [{ question: "Where is Hopper beer brewed?", answer: "Hopper is brewed in Belgium with Brouwerij De Brabandere." }, { question: "What is in Hopper Witbier?", answer: "Its wheat-beer recipe features coriander and Curacao orange peel." }],
    finalVerdict: "Hopper Witbier is the aromatic pick; Blonde suits anyone looking for a more direct beer pour.",
    metaTitle: "Hopper Belgian Beer Guide | BevOry", metaDescription: "Compare Hopper Witbier and Blonde, brewed in Belgium, with tasting notes and Indian pairings. Check city prices on BevOry.",
  },
  jamun: {
    description: "Jamun is a Himalayan juniper dry gin from India's Mohan Meakin. The producer places juniper at the centre of a peppery, citrus-tinged gin rather than a fruit-flavoured purple spirit.",
    story: "Mohan Meakin, a long-established Indian spirits house, added Jamun to its gin portfolio. Its Himalayan juniper identity sets it apart from the company's older London dry gin labels.",
    tastingNotes: [{ title: "Nose", description: "Juniper, lemon and pepper give a bright, sharp opening." }, { title: "Palate", description: "Floral hints and mild spice carry into a soft finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Add plain tonic over ice and finish with a strip of lemon peel." }, { subheading: "Food", description: "Serve with lemon fish fry, paneer tikka or peppery roasted peanuts." }],
    pairingIdeas: [{ title: "Citrus and pepper", items: ["lemon fish fry", "paneer tikka", "peppery roasted peanuts", "cucumber chaat"] }],
    whyChoose: "A Mohan Meakin dry gin with juniper, lemon and pepper at the front.",
    faqs: [{ question: "Who makes Jamun gin?", answer: "Jamun is made by Mohan Meakin in India." }, { question: "Is Jamun gin sweet like the fruit?", answer: "Jamun is presented as a dry gin with juniper, lemon and pepper notes." }],
    finalVerdict: "Jamun makes a crisp gin and tonic for drinkers who prefer lemon and pepper to sweetness.",
    metaTitle: "Jamun Dry Gin Guide | BevOry", metaDescription: "Discover Mohan Meakin's Jamun dry gin, with juniper, lemon and pepper notes and Indian pairings. Check city prices on BevOry.",
  },
  kashmyr: {
    description: "Kashmyr is an Indian vodka range from Radico Khaitan. Indian Natural and Indian Saffron are its two launch expressions, made with Himalayan grains and water.",
    story: "Radico Khaitan introduced Kashmyr in 2025, drawing its identity from the Kashmir region. The Saffron expression uses saffron from Pampore, giving one bottle a specific local ingredient alongside the unflavoured Natural.",
    tastingNotes: [{ title: "Indian Natural", description: "A clean grain-led vodka style leaves space for a simple mixer." }, { title: "Indian Saffron", description: "Pampore saffron brings a distinct aromatic spice note." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Natural for a martini; try Saffron with soda and a little lemon." }, { subheading: "Food", description: "Pair with tandoori fish, saffron paneer tikka or salted almonds." }],
    pairingIdeas: [{ title: "Clean and spiced", items: ["tandoori fish", "saffron paneer tikka", "salted almonds", "grilled prawns"] }],
    whyChoose: "An Indian vodka line that gives Pampore saffron a named place beside its natural style.",
    faqs: [{ question: "Who makes Kashmyr vodka?", answer: "Kashmyr is made by Radico Khaitan in India." }, { question: "What is in Kashmyr Indian Saffron?", answer: "The Saffron expression features saffron sourced from Pampore in Kashmir." }],
    finalVerdict: "Kashmyr's Natural suits classic vodka mixes; Saffron adds a distinct Indian aroma.",
    metaTitle: "Kashmyr Vodka Guide | BevOry", metaDescription: "Explore Kashmyr Indian Natural and Indian Saffron vodka, serving ideas and food matches. Check city prices on BevOry.",
  },
  lemount: {
    description: "Lemount is a citrus-flavoured strong beer from Mount Everest Breweries in India. It puts a lemon note over a fuller beer base.",
    story: "Mount Everest Breweries launched Lemount in 2012 as a flavoured addition to its strong-beer range. The Indore-based brewer uses European hops in the recipe and keeps the lemon character prominent.",
    tastingNotes: [{ title: "Citrus", description: "Lemon gives the opening an immediate bright edge." }, { title: "Beer base", description: "The fuller strong-beer body holds up beneath the citrus flavour." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a pint glass, without extra lemon until after the first sip." }, { subheading: "Food", description: "Try it with masala fries, fish pakora or chilli paneer." }],
    pairingIdeas: [{ title: "Lemon and heat", items: ["masala fries", "fish pakora", "chilli paneer", "roasted peanuts"] }],
    whyChoose: "A lemon-forward Indian strong beer rather than a standard unflavoured lager.",
    faqs: [{ question: "Who makes Lemount beer?", answer: "Lemount is made by Mount Everest Breweries in India." }, { question: "Is Lemount lemon flavoured?", answer: "Yes. The producer describes it as a citrus or lemon-flavoured strong beer." }],
    finalVerdict: "Lemount is the strong-beer option for someone who wants citrus built into the pour.",
    metaTitle: "Lemount Beer Guide | BevOry", metaDescription: "Discover Lemount's lemon-flavoured strong beer, serving ideas and Indian snack pairings. Check city prices on BevOry.",
  },
  madhvan: {
    description: "Madhvan is an Indian whisky from Uppal Brewers & Distillers. Its profile brings orchard fruit and vanilla on the nose, followed by honey, toffee and a little oak spice.",
    story: "The name joins madhu, meaning nectar, with van, meaning forest. Its tiger emblem carries that nature-led identity onto the bottle, while the producer keeps the whisky itself in a fruit-and-malt style.",
    tastingNotes: [{ title: "Nose", description: "Pear, green apple, vanilla and soft malt meet a floral edge." }, { title: "Palate and finish", description: "Honey and toffee move into warm oak and gentle spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try it neat, then add a small splash of water or make a ginger-and-soda highball." }, { subheading: "Food", description: "Mutton seekh, roasted cashews and apple tart all work with its sweeter side." }],
    pairingIdeas: [{ title: "Fruit and malt", items: ["mutton seekh", "roasted cashews", "apple tart", "paneer tikka"] }],
    whyChoose: "An Indian whisky with a clearly fruit-led nose and a honey-toffee middle.",
    faqs: [{ question: "Who makes Madhvan whisky?", answer: "Madhvan is associated with Uppal Brewers & Distillers in India." }, { question: "What does Madhvan taste like?", answer: "The producer describes pear, apple, vanilla, honey, toffee and soft oak spice." }],
    finalVerdict: "Madhvan's orchard-fruit opening makes its warm oak finish feel measured rather than heavy.",
    metaTitle: "Madhvan Whisky Guide | BevOry", metaDescription: "Explore Madhvan whisky's pear, honey and oak notes, serving ideas and Indian pairings. Check city prices on BevOry.",
  },
  oakton: {
    description: "Oakton is a barrel-aged grain whisky from India's Globus Spirits. Its blend brings imported Scotch together with selected Indian malts and is matured in oak barrels.",
    story: "Globus Spirits positions Oakton within its premium Indian spirits portfolio beside Terai gin and Doaab single malt. The whisky's appeal rests on blending imported Scotch with Indian malt rather than presenting itself as a single malt.",
    tastingNotes: [{ title: "Texture", description: "The producer describes a rich, rounded flavour from the blend." }, { title: "Finish", description: "Oak maturation leaves a smooth, lingering close." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip neat in a whisky glass before trying a large cube." }, { subheading: "Food", description: "Try it with tandoori mushrooms, mutton seekh or salted almonds." }],
    pairingIdeas: [{ title: "Oak and roast", items: ["tandoori mushrooms", "mutton seekh", "salted almonds", "roast chicken"] }],
    whyChoose: "A Globus whisky that makes its imported-Scotch and Indian-malt blend explicit.",
    faqs: [{ question: "Who makes Oakton whisky?", answer: "Oakton is a whisky brand from Globus Spirits in India." }, { question: "Is Oakton a single malt?", answer: "No. Globus describes it as a blend of barrel-aged imported Scotch and Indian malts." }],
    finalVerdict: "Oakton is a rounded whisky for drinkers who want both Scotch and Indian malt in the same glass.",
    metaTitle: "Oakton Whisky Guide | BevOry", metaDescription: "Explore Oakton's blend of imported Scotch and Indian malts, oak character and food pairings. Check city prices on BevOry.",
  },
  thunderbolt: {
    description: "Thunderbolt is an Indian beer now in the Inbrew Beverages portfolio. It began in the Himalayan foothills in 1984 and was developed around a bold, robust taste for Indian drinkers.",
    story: "Thunderbolt's brewing story starts with Himalayan water, which the present owner links to its strong character. Inbrew later acquired the brand and brought it into a wider beer portfolio without dropping its original name.",
    tastingNotes: [{ title: "First impression", description: "The producer describes a bold, robust beer rather than a delicate lager." }, { title: "Body", description: "A full-flavoured impression carries through the glass." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill well and use a clean pint glass for a straightforward pour." }, { subheading: "Food", description: "Its bolder profile suits tandoori chicken, masala peanuts or chilli paneer." }],
    pairingIdeas: [{ title: "Bold beer snacks", items: ["tandoori chicken", "masala peanuts", "chilli paneer", "fish pakora"] }],
    whyChoose: "A long-running Indian beer with a clearly bold house style and Himalayan roots.",
    faqs: [{ question: "Who owns Thunderbolt beer?", answer: "Thunderbolt is part of the Inbrew Beverages brand portfolio." }, { question: "When did Thunderbolt beer begin?", answer: "Inbrew dates Thunderbolt's origins in the Himalayan foothills to 1984." }],
    finalVerdict: "Thunderbolt stays true to the strong, direct beer style it was built around.",
    metaTitle: "Thunderbolt Beer Guide | BevOry", metaDescription: "Discover Thunderbolt beer's Himalayan roots, bold style and Indian food pairings. Check city prices on BevOry.",
  },
  aodh: {
    description: "AODH is an Irish whiskey introduced by ABD Maestro for the Indian market. It is triple distilled and matured in ex-bourbon casks, giving the range an approachable oak-led style.",
    story: "The name draws on Irish legend rather than an old distillery claim. ABD Maestro placed AODH in its premium spirits collection to bring an Irish-made whiskey to Indian drinkers.",
    tastingNotes: [{ title: "First sip", description: "Vanilla cream and light honey give the opening a gentle sweetness." }, { title: "Finish", description: "Toffee and soft oak follow, with a little dried fruit and spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Taste it neat in a small whisky glass, then try a tall serve with chilled soda." }, { subheading: "At the table", description: "Its soft sweetness works with chicken malai tikka, roasted cashews or apple tart." }],
    pairingIdeas: [{ title: "Soft spice", items: ["chicken malai tikka", "roasted cashews", "apple tart", "smoked almonds"] }],
    whyChoose: "An Irish whiskey with a clearly stated triple-distilled, ex-bourbon-cask profile.",
    faqs: [{ question: "Is AODH an Irish whiskey?", answer: "Yes. AODH is presented by ABD Maestro as an Irish whiskey." }, { question: "What does AODH taste like?", answer: "The producer describes vanilla cream, honey, toffee and a warm oak finish." }],
    finalVerdict: "AODH keeps the first pour gentle enough for a newcomer while still showing its cask character.",
    metaTitle: "AODH Irish Whiskey Guide | BevOry", metaDescription: "Explore AODH Irish whiskey, vanilla and honey notes, serving ideas and Indian food pairings. Check city prices on BevOry.",
  },
  beor: {
    description: "Beor 360 is a beer line from Delhi-based Brewking Beverages, made in lager and wheat styles. The wheat beer uses barley malt, wheat and hops, while the lager takes a cleaner, crisper route.",
    story: "Brewking launched Beor 360 with two different beers rather than a single flagship bottle. Its early wheat and lager releases gave drinkers a direct choice between a hazy, yeast-led beer and a clear lager.",
    tastingNotes: [{ title: "Wheat beer", description: "Orange peel and chamomile sit alongside soft clove and banana notes." }, { title: "Lager", description: "Light bread and honey meet restrained floral hops on a dry finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the wheat beer into a tall glass and serve the lager cold in a clean pint glass." }, { subheading: "Food", description: "Try the wheat beer with paneer tikka or the lager with fish pakora and salted peanuts." }],
    pairingIdeas: [{ title: "Beer snacks", items: ["paneer tikka", "fish pakora", "salted peanuts", "grilled corn"] }],
    whyChoose: "A compact two-style beer range with a meaningful contrast between wheat-beer spice and lager crispness.",
    faqs: [{ question: "Who makes Beor 360?", answer: "Beor 360 was introduced by Delhi-based Brewking Beverages." }, { question: "What is the difference between Beor Wheat and Lager?", answer: "The wheat beer is hazy and spiced; the lager is clearer, drier and more malt-led." }],
    finalVerdict: "Beor 360 is easiest to explore by pouring its wheat and lager side by side.",
    metaTitle: "Beor 360 Beer Guide | BevOry", metaDescription: "Compare Beor 360 Wheat and Lager, their flavours and food matches. Check city prices on BevOry.",
  },
  boho: {
    description: "Boho is a premium blended whisky from India's ADS Spirits. Its own tasting profile puts fruit and floral notes ahead of a gentle malt, vanilla and peat finish.",
    story: "ADS Spirits added Boho to a portfolio that also includes Royal Green and Royal Black. Its Bohemian-themed packaging gives this blend a different shelf identity from the producer's more traditional whisky labels.",
    tastingNotes: [{ title: "Aroma", description: "Ripe pear, summer fruit and a light floral edge lead the nose." }, { title: "Palate", description: "Malt and creamy vanilla pick up a restrained touch of peat." }],
    howToEnjoy: [{ subheading: "Glass", description: "Try a small neat pour first, then add a splash of water if the malt feels tight." }, { subheading: "Food", description: "Pair with tandoori mushrooms, pepper chicken or salted almonds." }],
    pairingIdeas: [{ title: "Malt and spice", items: ["tandoori mushrooms", "pepper chicken", "salted almonds", "dark chocolate"] }],
    whyChoose: "A blended Indian whisky with a fruit-led opening and only a light peat accent.",
    faqs: [{ question: "Who makes Boho whisky?", answer: "Boho is a whisky from ADS Spirits in India." }, { question: "Is Boho whisky smoky?", answer: "The producer describes a subtle touch of peat, not a strongly smoky style." }],
    finalVerdict: "Boho offers pear and vanilla first, with peat kept in the background.",
    metaTitle: "Boho Whisky Guide | BevOry", metaDescription: "Explore Boho whisky from ADS Spirits, with pear, vanilla and light peat notes. Find pairings and check city prices on BevOry.",
  },
  buho: {
    description: "Buho is a Belgian-brewed beer line brought to India by Brindco. Its range includes a wheat beer, a blonde ale and a stronger blonde-style beer.",
    story: "Brindco backed production at a family-owned Belgian brewery, connecting Buho's Indian launch to established Belgian brewing. The Blonde is associated with Brouwerij Vanhonsebrouck in Izegem, while the Witbier takes a spiced wheat-beer direction.",
    tastingNotes: [{ title: "Witbier", description: "Coriander, orange peel and ginger shape a fragrant wheat-beer profile." }, { title: "Strong", description: "Lightly roasted malt and Belgian hops lead into a fuller, nutty finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Use a tall glass for Witbier and a smaller tulip glass for the stronger beer." }, { subheading: "Food", description: "Witbier fits tandoori prawns; the Strong suits chilli paneer or roast chicken." }],
    pairingIdeas: [{ title: "Belgian beer pairings", items: ["tandoori prawns", "chilli paneer", "roast chicken", "salted fries"] }],
    whyChoose: "Belgian brewing character in a range that spans spiced wheat beer and maltier blonde styles.",
    faqs: [{ question: "Where is Buho beer brewed?", answer: "Buho is brewed in Belgium for the Indian market." }, { question: "What gives Buho Witbier its spice?", answer: "The Witbier uses coriander, orange peel and ginger alongside wheat and barley malt." }],
    finalVerdict: "Buho makes most sense as a style comparison: citrus-spiced Witbier against a fuller Belgian blonde.",
    metaTitle: "Buho Belgian Beer Guide | BevOry", metaDescription: "Discover Buho Witbier, Blonde and Strong beer, with Belgian brewing details and Indian pairings. Check city prices on BevOry.",
  },
  communiti: {
    description: "Communiti is a Bengaluru microbrewery with Belgian Wheat, Irish Ale and other house-brewed beers. Its beer programme uses imported German malt and covers wheat, lager, stout and hop-led styles.",
    story: "The brewery developed its range around several distinct beer traditions rather than a single signature pint. Belgian Wheat and Irish Ale show the contrast clearly: one is cloudy and citrus-spiced, the other maltier and red-ale inspired.",
    tastingNotes: [{ title: "Belgian Wheat", description: "Coriander and citrus lift a tangy, lightly cloudy wheat beer." }, { title: "Irish Ale", description: "Caramel sweetness and a more balanced malt-hop character define the red-ale style." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the wheat beer into a tall glass; a clean pint glass suits the Irish Ale." }, { subheading: "Food", description: "Choose lemon fish fry for wheat beer or mushroom pepper fry for the maltier ale." }],
    pairingIdeas: [{ title: "Bengaluru table", items: ["lemon fish fry", "mushroom pepper fry", "paneer tikka", "roast potatoes"] }],
    whyChoose: "A brewery range that lets drinkers move from citrus-led wheat beer to caramel-tinged ale.",
    faqs: [{ question: "Where is Communiti based?", answer: "Communiti is a microbrewery in Bengaluru, Karnataka." }, { question: "Which Communiti beer is wheat based?", answer: "Belgian Wheat is its cloudy, citrus-and-coriander wheat-beer style." }],
    finalVerdict: "Communiti's range rewards choosing a beer to suit the food, not ordering by name alone.",
    metaTitle: "Communiti Beer Guide | BevOry", metaDescription: "Explore Communiti's Bengaluru-brewed Belgian Wheat and Irish Ale, tasting notes and pairings. Check city prices on BevOry.",
  },
  "coopers-best": {
    description: "Coopers Best Extra Stout is an Australian stout brewed by Coopers Brewery with pale and roasted malts. It is naturally conditioned, giving its dark-malt character a creamy, full-bodied setting.",
    story: "Coopers has kept bottle conditioning central to its ale-making in Adelaide. Best Extra Stout follows that method with heavily roasted black malt, a marked change from the brewery's familiar green-label pale ale.",
    tastingNotes: [{ title: "Roast", description: "Coffee and dark chocolate rise from the black malt." }, { title: "Mouthfeel", description: "A creamy body carries the roast into a firm, dry finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cool, not icy, in a stout glass to let the roast come through." }, { subheading: "Food", description: "Pair with pepper mutton, mushroom kebabs or a square of dark chocolate." }],
    pairingIdeas: [{ title: "Roasted flavours", items: ["pepper mutton", "mushroom kebabs", "dark chocolate", "coffee cake"] }],
    whyChoose: "A naturally conditioned stout whose roasted malt is the main event.",
    faqs: [{ question: "What is Coopers Best Extra Stout made with?", answer: "Coopers brews it with pale and specially roasted black malts and ale yeast." }, { question: "Is Coopers Best Extra Stout bottle conditioned?", answer: "Yes. Coopers says it is naturally conditioned in bottle and keg." }],
    finalVerdict: "Best Extra Stout is the Coopers bottle to reach for when coffee-and-chocolate malt sounds better than citrusy ale.",
    metaTitle: "Coopers Best Stout Guide | BevOry", metaDescription: "Explore Coopers Best Extra Stout, its roasted malt, coffee and chocolate notes, and food pairings. Check city prices on BevOry.",
  },
  "coopers-original": {
    description: "Coopers Original Pale Ale is an Australian all-malt beer from Adelaide's Coopers Brewery. Natural conditioning leaves a fine haze and gives the golden ale its familiar fruity, floral character.",
    story: "Coopers' bottle-conditioned brewing has kept Original Pale Ale distinct from filtered pale lagers. The green-label beer continues the brewery's practice of letting secondary fermentation take place in the package.",
    tastingNotes: [{ title: "Aroma", description: "Fruity yeast character and floral notes sit over pale malt." }, { title: "Finish", description: "A crisp bitterness cuts through the soft malt sweetness." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve chilled in a pint glass; a gentle roll before pouring can lift the natural yeast sediment." }, { subheading: "Food", description: "Try it with chicken tikka, fish fry or a sharp cheddar toastie." }],
    pairingIdeas: [{ title: "Pale ale table", items: ["chicken tikka", "fish fry", "cheddar toastie", "salted peanuts"] }],
    whyChoose: "The green-label pale ale makes Coopers' natural-conditioning method easy to taste.",
    faqs: [{ question: "Why is Coopers Original Pale Ale cloudy?", answer: "Natural conditioning creates fine yeast sediment and a light haze." }, { question: "What does Coopers Original Pale Ale taste like?", answer: "It has fruity and floral yeast notes with balanced, crisp bitterness." }],
    finalVerdict: "A pale ale with real fermentation character and enough bitterness to hold up beside dinner.",
    metaTitle: "Coopers Original Pale Ale Guide | BevOry", metaDescription: "Discover Coopers Original Pale Ale, its natural haze, fruity notes and food matches. Check city prices on BevOry.",
  },
  "el-goonda": {
    description: "El Goonda makes Indian agave spirits from wild-grown Agave americana on the Deccan plateau. Its range includes Silver, Reposado and flavoured expressions such as Strawberry and Picante.",
    story: "The producer uses agave naturalised in India and double distillation to build its spirit. Its Reposado spends time in bourbon barrels, giving it a different shape from the brighter Silver expression.",
    tastingNotes: [{ title: "Silver", description: "Lime, cracked pepper and a little vanilla keep the agave lively." }, { title: "Reposado", description: "Toasted oak, caramel and vanilla round out the peppery base." }],
    howToEnjoy: [{ subheading: "Cocktail", description: "Shake Silver with fresh lime for an agave sour, or sip Reposado from a small glass." }, { subheading: "Food", description: "Match the citrusy Silver with tandoori prawns and Reposado with grilled corn or smoky paneer." }],
    pairingIdeas: [{ title: "Agave and spice", items: ["tandoori prawns", "grilled corn", "smoky paneer", "chilli-lime peanuts"] }],
    whyChoose: "A Deccan-grown agave spirit with clearly different fresh and barrel-rested expressions.",
    faqs: [{ question: "Is El Goonda tequila?", answer: "No. It is an Indian agave spirit, not a spirit made under Mexico's tequila designation." }, { question: "Where does El Goonda get its agave?", answer: "The producer says it uses wild-grown Agave americana from the Deccan plateau." }],
    finalVerdict: "El Goonda brings an Indian-grown agave story into both citrusy cocktails and slower oak-led pours.",
    metaTitle: "El Goonda Agave Spirit Guide | BevOry", metaDescription: "Explore El Goonda's Indian agave, Silver and Reposado styles, serving ideas and pairings. Check city prices on BevOry.",
  },
  frizzano: {
    description: "Frizzano is a sparkling wine range from India's Good Drop Wine Cellars. Its gently sparkling white styles use Chenin Blanc, while the rosé draws on Shiraz.",
    story: "Good Drop built Frizzano around the Charmat method, with secondary fermentation in a sealed tank. The line includes semi-dry, extra-dry and rosé bottles rather than one house cuvée.",
    tastingNotes: [{ title: "Extra Dry", description: "Green apple and peach sit behind a light yeast note in this Chenin Blanc bubbly." }, { title: "Semi Dry Rosé", description: "The Shiraz rosé brings guava, grapefruit and a floral nose." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a white-wine glass, leaving room for the bubbles to open." }, { subheading: "Food", description: "Try Extra Dry with cauliflower pakora and the rosé with tandoori fish or strawberries." }],
    pairingIdeas: [{ title: "Bubbles with food", items: ["cauliflower pakora", "tandoori fish", "salted potato chips", "fresh strawberries"] }],
    whyChoose: "Indian-made Charmat sparkling wine with a clear choice between Chenin Blanc and Shiraz rosé styles.",
    faqs: [{ question: "Who makes Frizzano?", answer: "Frizzano is made by Good Drop Wine Cellars in India." }, { question: "Which grapes go into Frizzano sparkling wine?", answer: "Good Drop lists Chenin Blanc for white Frizzano styles and Shiraz for its rosé." }],
    finalVerdict: "Frizzano's gentle bubbles make it a useful Indian alternative when a full-bodied wine would be too much.",
    metaTitle: "Frizzano Sparkling Wine Guide | BevOry", metaDescription: "Discover Frizzano's Chenin Blanc and Shiraz rosé bubbles, tasting notes and pairings. Check city prices on BevOry.",
  },
  "glen-talloch": {
    description: "Glen Talloch is a blended Scotch whisky line with malt and grain whiskies drawn from Scotland. The range includes Rare & Old, 8-year and 12-year expressions with ex-bourbon-cask maturation.",
    story: "The blender's Rare & Old release brings together malt from distilleries including Balblair, Knockdhu and Speyburn. Older Glen Talloch expressions change the malt balance and maturation time, giving the range more than one drinking style.",
    tastingNotes: [{ title: "Rare & Old", description: "The producer describes a smooth, rich blended-whisky style." }, { title: "8-year expression", description: "A softer palate brings light toast, exotic-fruit notes and a faint coastal edge." }],
    howToEnjoy: [{ subheading: "Glass", description: "Taste it neat in a tulip glass, then add water sparingly to see where the malt opens." }, { subheading: "Food", description: "Put it beside mutton seekh, roast mushrooms or salted almonds." }],
    pairingIdeas: [{ title: "Malt and roast", items: ["mutton seekh", "roast mushrooms", "salted almonds", "apple tart"] }],
    whyChoose: "A Scotch blending range that lets drinkers compare standard and older malt-forward expressions.",
    faqs: [{ question: "Is Glen Talloch a single malt?", answer: "The Rare & Old and age-stated releases described by its distributor are blended Scotch whiskies." }, { question: "What casks does Glen Talloch use?", answer: "The distributor describes ex-bourbon oak maturation for its principal blends." }],
    finalVerdict: "Glen Talloch is best approached as a blended Scotch with an accessible malt-and-grain balance.",
    metaTitle: "Glen Talloch Scotch Guide | BevOry", metaDescription: "Explore Glen Talloch blended Scotch, its ex-bourbon casks and malt-led styles. Check city prices on BevOry.",
  },
  grizly: {
    description: "Grizly is a hard-seltzer-ale line in the House of Bira 91 portfolio. Its named flavours include Blueberry & Rosemary, Pineapple & Okinawa Sugar, and Peach & Black Tea.",
    story: "House of Bira 91 introduced Grizly as a flavoured alternative to its conventional beer range. The line's flavour pairings are unusually specific, putting a herb, tea or sugar note beside the fruit in each release.",
    tastingNotes: [{ title: "Blueberry & Rosemary", description: "Berry sweetness is paired with a herbal rosemary accent." }, { title: "Peach & Black Tea", description: "Peach leads, while black tea gives the finish a drier edge." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the can and pour into a tall glass over ice." }, { subheading: "Food", description: "Try Blueberry & Rosemary with grilled paneer or Peach & Black Tea with chilli potato." }],
    pairingIdeas: [{ title: "Fruit and heat", items: ["grilled paneer", "chilli potato", "salted popcorn", "fruit tart"] }],
    whyChoose: "A flavoured seltzer-ale range built around recognisable fruit-and-botanical pairings.",
    faqs: [{ question: "Who makes Grizly?", answer: "Grizly is presented in the House of Bira 91 portfolio." }, { question: "What flavours does Grizly make?", answer: "Listed expressions include Blueberry & Rosemary, Pineapple & Okinawa Sugar, and Peach & Black Tea." }],
    finalVerdict: "Grizly's pairing-style flavour names make it easy to choose a can to suit the snacks.",
    metaTitle: "Grizly Hard Seltzer Guide | BevOry", metaDescription: "Explore Grizly's blueberry, pineapple and peach hard-seltzer-ale flavours and food matches. Check city prices on BevOry.",
  },
  happiness: {
    description: "Happiness is an Indian gin line from Radico Khaitan with Joy of Juniper, Joy of Citrus and Joy of Pink expressions. The range puts different botanical and fruit accents around a gin base.",
    story: "Radico Khaitan launched the three Happiness variants together, giving each a clear flavour direction. The Juniper expression brings Indian spices and ashwagandha into the producer's take on gin.",
    tastingNotes: [{ title: "Joy of Juniper", description: "Juniper leads, with ginger, cardamom and other Indian spices behind it." }, { title: "Joy of Citrus", description: "Orange peel, lemongrass and lemon leaf move the gin in a tangier direction." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour Joy of Juniper over ice with plain tonic; save a citrus garnish for Joy of Citrus." }, { subheading: "Food", description: "Serve with lemon-pepper paneer, tandoori fish or salted almonds." }],
    pairingIdeas: [{ title: "Gin snacks", items: ["lemon-pepper paneer", "tandoori fish", "salted almonds", "cucumber chaat"] }],
    whyChoose: "Three named gin styles make the botanical choice easy to understand at a glance.",
    faqs: [{ question: "Who makes Happiness gin?", answer: "Happiness is a gin range from Radico Khaitan." }, { question: "What Happiness gin variants are there?", answer: "The launch range includes Joy of Juniper, Joy of Citrus and Joy of Pink." }],
    finalVerdict: "Start with Juniper for a classic gin direction, then move to the fruit-led bottles for lighter mixers.",
    metaTitle: "Happiness Gin Guide | BevOry", metaDescription: "Explore Happiness Joy of Juniper, Citrus and Pink gin, serving ideas and Indian pairings. Check city prices on BevOry.",
  },
  "hill-station": {
    description: "Hill Station is a hard-cider-ale line from House of Bira 91 built around Himalayan apple. Original, Berry Twist and Strong offer different takes on the apple-led drink.",
    story: "Bira 91 moved beyond beer with Hill Station's Himalayan Apple range. The launch used apple as the common thread, then split the line into a straightforward Original, a berry-flavoured bottle and a stronger version.",
    tastingNotes: [{ title: "Original", description: "Apple leads in the plain Himalayan Apple expression." }, { title: "Berry Twist", description: "Berry flavour joins the apple base for a fruitier direction." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tumbler or small cider glass; keep the pour simple." }, { subheading: "Food", description: "Apple works with pork sausages, paneer tikka or spicy potato wedges." }],
    pairingIdeas: [{ title: "Apple with spice", items: ["paneer tikka", "spicy potato wedges", "pork sausages", "roast peanuts"] }],
    whyChoose: "A Himalayan-apple cider-ale line with plain, berry and stronger routes from the same producer.",
    faqs: [{ question: "Who makes Hill Station cider ale?", answer: "Hill Station is part of the House of Bira 91 portfolio." }, { question: "Which Hill Station flavours are there?", answer: "The range lists Himalayan Apple Original, Berry Twist and Strong." }],
    finalVerdict: "Hill Station is for an apple-led pour when beer feels too malt-heavy.",
    metaTitle: "Hill Station Cider Ale Guide | BevOry", metaDescription: "Explore Hill Station Himalayan Apple Original, Berry Twist and Strong with food pairings. Check city prices on BevOry.",
  },
  macroys: {
    description: "MacRoys is a blended Scotch whisky range associated with Angus Dundee. Its releases include Extra Peat, Bourbon Barrel Matured and Sherry Cask Finish expressions.",
    story: "The line uses different cask and peat treatments to separate its blends rather than presenting them as one uniform whisky. Extra Peat is distilled, aged and blended in Scotland, while the sherry-finished expression starts with first-fill ex-bourbon maturation.",
    tastingNotes: [{ title: "Extra Peat nose", description: "Toasted nuts, honeycomb and cocoa rise through the smoke." }, { title: "Extra Peat palate", description: "Toffee and cooked fruit meet campfire smoke and lingering spice." }],
    howToEnjoy: [{ subheading: "Taste", description: "Give Extra Peat a neat pour first; a little water can ease the smoke." }, { subheading: "Food", description: "Mutton seekh, smoked paneer or dark chocolate can stand beside its peat." }],
    pairingIdeas: [{ title: "With peat", items: ["mutton seekh", "smoked paneer", "dark chocolate", "roasted walnuts"] }],
    whyChoose: "A Scotch blend family that makes peat and cask influence explicit choices.",
    faqs: [{ question: "Is MacRoys Scotch whisky?", answer: "Yes. The producer presents MacRoys as a blended Scotch whisky range." }, { question: "Which MacRoys bottle is smoky?", answer: "Extra Peat is the smoke-led expression in the range." }],
    finalVerdict: "Choose MacRoys by style: Extra Peat for smoke, or a cask-led blend for a different direction.",
    metaTitle: "MacRoys Scotch Guide | BevOry", metaDescription: "Compare MacRoys Extra Peat and cask-finished Scotch, with tasting notes and Indian pairings. Check city prices on BevOry.",
  },
  roulette: {
    description: "Roulette is an Indian spirits line from John Distilleries with whisky and grape brandy releases. Its Peated Premium Whisky combines Indian grain spirit with peated Indian single malt for a smoke-led style.",
    story: "John Distilleries developed Roulette as a premium extension beyond its better-known Original Choice and Paul John labels. The peated whisky uses ex-bourbon cask maturation, giving the grain-and-malt blend an oak foundation.",
    tastingNotes: [{ title: "Peated whisky", description: "Soft grain sweetness meets a smoky malt note, crisp apple and oak spice." }, { title: "Grape brandy", description: "Sweet vanilla and toasted oak lead into gentle spice and a mellow finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Taste the peated whisky neat before trying it with one large cube." }, { subheading: "Food", description: "Smoky kebabs and charred paneer suit the whisky; fruit cake works with the brandy." }],
    pairingIdeas: [{ title: "Two directions", items: ["smoky kebabs", "charred paneer", "fruit cake", "roasted almonds"] }],
    whyChoose: "A John Distilleries range with a peated Indian whisky that has a distinct cask story.",
    faqs: [{ question: "Who makes Roulette whisky?", answer: "Roulette is made by John Distilleries in India." }, { question: "Is Roulette Peated Premium Whisky smoky?", answer: "Yes. John Distilleries describes peated Indian malt in its blend." }],
    finalVerdict: "Roulette's peated whisky is a straightforward entry into smoke without losing its grain-whisky base.",
    metaTitle: "Roulette Whisky Guide | BevOry", metaDescription: "Discover Roulette Peated Premium Whisky, John Distilleries' cask-led style and food matches. Check city prices on BevOry.",
  },
  tilt: {
    description: "Tilt is a canned Indian wine range from Fratelli Wines. Red, White, Bubbly and rose styles put single-serve wine into a format built for casual pouring.",
    story: "Fratelli added Tilt to its Maharashtra wine business as a lighter-format alternative to its bottled estate range. The company describes a fresh, easy-drinking approach inspired by Beaujolais-style wine-making.",
    tastingNotes: [{ title: "White", description: "Fratelli describes this can as aromatic, with balanced acidity and a smooth finish." }, { title: "Bubbly", description: "Tropical fruit leads into a citrus finish, with a light sparkling texture." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the can, then pour it into a proper wine glass to catch the aroma." }, { subheading: "Food", description: "Try White with paneer tikka and Bubbly with pakoras or fruit tart." }],
    pairingIdeas: [{ title: "Casual plates", items: ["paneer tikka", "onion pakora", "fruit tart", "grilled fish"] }],
    whyChoose: "Fratelli wine in a small can, with still and sparkling styles to choose from.",
    faqs: [{ question: "Who makes Tilt wine?", answer: "Tilt is made by Fratelli Wines in India." }, { question: "Is Tilt only sparkling wine?", answer: "No. The range includes still Red and White as well as sparkling styles." }],
    finalVerdict: "Tilt is useful when a full wine bottle would be more than the table needs.",
    metaTitle: "Tilt Canned Wine Guide | BevOry", metaDescription: "Explore Tilt canned wine from Fratelli, with Red, White and Bubbly styles, serving ideas and pairings. Check city prices on BevOry.",
  },
};
