import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_22 = [
  ["el-jimador", "El Jimador", "Mexico", "Tequila", "970f348b4554cbf09aba9aae"],
  ["elijah-craig", "Elijah Craig", "United States", "Bourbon", "13aa91381587bd524a63e30d"],
  ["erdinger", "Erdinger", "Germany", "Beer", "afe17938dc4bbd037b28aa50"],
  ["eristoff", "Eristoff", "Georgia", "Vodka", "4537495606bf5721b52f957a"],
  ["espolon", "Espolon", "Mexico", "Tequila", "5c38dc972134b53a48c476bf"],
  ["evan-williams", "Evan Williams", "United States", "Bourbon", "bf95a3ba48f5803a00ad6cb4"],
  ["fosters", "Fosters", "Australia", "Beer", "797cd5c4ea8bd7cda96736a7"],
  ["four-pillars", "Four Pillars", "Australia", "Gin", "9244b8a772c9803e37d501cb"],
  ["freixenet", "Freixenet", "Spain", "Cava", "0d52824b6dc6becaf01456ed"],
  ["frescobaldi", "Frescobaldi", "Italy", "Wine", "36db731fa1e915ffb6127dba"],
  ["frontera", "Frontera", "Chile", "Wine", "5d4653474aa1441722a9a40b"],
  ["g-h-mumm", "G H Mumm", "France", "Champagne", "94602710ae10abac1d86f068"],
  ["gaja", "Gaja", "Italy", "Wine", "d07a2fa8a813b145e2e39096"],
  ["gianchand", "GianChand", "India", "Single Malt Whisky", "05929b7d852581816adc7f6a"],
  ["gin-mare", "Gin Mare", "Spain", "Gin", "87e1d6ff612931d39ae1d840"],
  ["glenallachie", "The GlenAllachie", "Scotland", "Single Malt Scotch", "ac9a211de0a0ed669ea1a491"],
  ["glengoyne", "Glengoyne", "Scotland", "Single Malt Scotch", "ca59a449487be9219691e956"],
  ["godawan", "Godawan", "India", "Single Malt Whisky", "57d6d8eef27d4af2af641fd4"],
  ["godfather", "Godfather", "India", "Beer", "a55b0153fdbfc0fb5605e4ba"],
  ["gouden-carolus", "Gouden Carolus", "Belgium", "Beer", "276dbe4ea23237d53d4057a0"],
  ["grand-macnish", "Grand Macnish", "Scotland", "Blended Scotch", "51ece6ff467d8ccfaa606929"],
  ["guado-al-tasso", "Guado al Tasso", "Italy", "Wine", "8406ff5cb6adb86c6afee69a"],
  ["haku", "Haku", "Japan", "Vodka", "4e4780ecef248dd993fb474c"],
  ["hakushika", "Hakushika", "Japan", "Sake", "df88013c1a76540c3df8d6be"],
  ["hakutsuru", "Hakutsuru", "Japan", "Sake", "d1f76c94b6d0636d89ed8e7b"],
  ["height-of-arrows", "Height of Arrows", "Scotland", "Gin", "6c7e5062887d56eb88bf5976"],
  ["hibiki", "Hibiki", "Japan", "Blended Japanese Whisky", "1eb1c4e3b01f2d0529f117c5"],
  ["inglenook", "Inglenook", "United States", "Wine", "96da6037cc4967478af596e9"],
  ["j-and-b", "J&B", "Scotland", "Blended Scotch", "1597d3faede6487cbdcea095"],
  ["jim-barry", "Jim Barry", "Australia", "Wine", "327effb73ca7bf18504083a4"],
] as const;

// Research references are internal and never rendered in public fields.
export const BRAND_SOURCES_BATCH_22: Record<string, string[]> = {
  "el-jimador": ["https://www.brown-forman.com/brand/el-jimador"],
  "elijah-craig": ["https://elijahcraig.com/our-history", "https://elijahcraig.com/small-batch"],
  erdinger: ["https://erdinger.de/en-UK/brewery", "https://erdinger.de/en-UK/beers/wheatbeer"],
  eristoff: ["https://www.eristoff.com/heritage/", "https://www.eristoff.com/product-overview/eristoff-original-vodka/"],
  espolon: ["https://www.espolontequila.com/es-mx/como-creamos-nuestro-tequila/"],
  "evan-williams": ["https://heavenhill.com/through-the-years/", "https://evanwilliams.com/"],
  fosters: ["https://www.fosters.co.uk/"],
  "four-pillars": ["https://fourpillarsgin.com/pages/about-us", "https://fourpillarsgin.com/collections/all/products/rare-dry-gin"],
  freixenet: ["https://freixenet.com/product/cordon-negro/", "https://freixenet.com/uk/explore-our-world"],
  frescobaldi: ["https://www.frescobaldi.com/en/history"],
  frontera: ["https://fronterawines.com/wp-content/uploads/2021/05/FRON_Ficha-Comercial_CS_Corcho_750_ESP14.07.2020.pdf"],
  "g-h-mumm": ["https://www.mumm.com/en-au/the-house/maison-mumm/", "https://www.mumm.com/en-us/home/"],
  gaja: ["https://gaja.com/", "https://maps.gaja.com/GAJA_Barbaresco_Barolo/", "https://www.decanter.com/wine-reviews-tastings/cult-italian-winemakers-new-chapters-new-directions/"],
  gianchand: ["https://gianchand.com/"],
  "gin-mare": ["https://www.ginmare.com/product/"],
  glenallachie: ["https://theglenallachie.com/our-story/our-history/"],
  glengoyne: ["https://www.glengoyne.com/"],
  godawan: ["https://www.diageo.com/en/news-and-media/stories/2024/the-distilled-series-2-betterment-brands-and-godawan"],
  godfather: ["https://devans.co.in/"],
  "gouden-carolus": ["https://www.hetanker.be/en/history", "https://www.hetanker.be/en/drinks/gouden-carolus-classic"],
  "grand-macnish": ["https://www.lcbo.com/en/grand-macnish-217190", "https://prod-scotch-whisky.azurewebsites.net/whiskypedia/2384/grand-macnish/"],
  "guado-al-tasso": ["https://www.antinori.it/en/vino/guado-al-tasso-en/?wineyear=master"],
  haku: ["https://house.suntory.com/craft-philosophy/haku-vodka"],
  hakushika: ["https://www.hakushika.co.jp/en/brand/history.html", "https://www.hakushika.co.jp/en/company/president.html"],
  hakutsuru: ["https://www.hakutsuru-sake.com/our-story/", "https://www.hakutsuru-sake.com/product/hakutsuru-superior-junmai-ginjo/"],
  "height-of-arrows": ["https://holyrooddistillery.co.uk/height-of-arrows/"],
  hibiki: ["https://house.suntory.com/hibiki-whisky", "https://house.suntory.com/hibiki-whisky/hibiki-japanese-harmony"],
  inglenook: ["https://inglenook.com/our-story/"],
  "j-and-b": ["https://www.diageobaracademy.com/en-us/home/our-brands/jb"],
  "jim-barry": ["https://www.jimbarry.com/our-story", "https://www.jimbarry.com/jim-barry"],
};

// Only previously blank catalogue logos; existing logo URLs are preserved by the importer.
export const BRAND_LOGOS_BATCH_22: Record<string, string> = {
  "four-pillars": "https://fourpillarsgin.com/cdn/shop/files/logo-full.svg",
  frescobaldi: "https://www.frescobaldi.com/fsb/assets/logo.cb588.svg",
  hakutsuru: "https://www.hakutsuru-sake.com/wp-content/themes/hakutsuru_seek/assets/img/common/logo_en.svg",
  inglenook: "https://inglenook.com/wp-content/uploads/2025/03/Inglenook-Logo_Type_Black-300x99.png",
};

export const BRAND_CONTENT_BATCH_22: Record<string, BrandPublicContent> = {
  "el-jimador": {
    description: "El Jimador is a 100% blue Weber agave tequila made by Casa Herradura in Amatitán, Jalisco. Its Silver and Reposado give drinkers two clear ways into the agave-led style.",
    story: "Casa Herradura named this tequila for the jimadores who harvest mature agave by hand. Natural fermentation at the distillery connects the label to its Jalisco surroundings.",
    tastingNotes: [{ title: "Silver", description: "Fresh agave and citrus make the unaged pour lively." }, { title: "Reposado", description: "Oak softens the agave with a warmer, lightly spiced finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try Silver in a lime-forward Margarita or Reposado over one large cube." }, { subheading: "Food", description: "Fish tacos, tandoori prawns and corn chaat suit the citrus and agave." }],
    pairingIdeas: [{ title: "With agave", items: ["fish tacos", "tandoori prawns", "corn chaat", "guacamole"] }],
    whyChoose: "A straightforward Jalisco tequila that keeps blue agave in front.",
    faqs: [{ question: "Where is El Jimador made?", answer: "At Casa Herradura in Amatitán, Jalisco, Mexico." }, { question: "Is El Jimador made from blue agave?", answer: "Yes, it is made from 100% blue Weber agave." }],
    finalVerdict: "Silver brings lift to cocktails; Reposado makes a gentler sipping pour.",
    metaTitle: "El Jimador Tequila Guide | BevOry", metaDescription: "Meet El Jimador's Jalisco tequila, from bright Silver to oak-rested Reposado. Check city prices on BevOry.",
  },
  "elijah-craig": {
    description: "Elijah Craig is a Kentucky bourbon made by Heaven Hill. Its Small Batch is aged in level-three charred oak barrels, giving the range a firm bourbon-spice centre.",
    story: "The name honours an eighteenth-century Kentucky distiller linked to early bourbon history. Heaven Hill also acknowledges the contributions of enslaved people to that history, which a one-person origin story would erase.",
    tastingNotes: [{ title: "Small Batch", description: "Vanilla, caramel and warm spice lead into a charred-oak finish." }, { title: "Barrel influence", description: "A trace of smoke comes from the char, not from peated grain." }],
    howToEnjoy: [{ subheading: "Slow pour", description: "Start neat in a small whisky glass; add a few drops of water after the first sip." }, { subheading: "Dinner", description: "Mutton seekh, smoked paneer and pecan pie meet the bourbon's oak and sweetness." }],
    pairingIdeas: [{ title: "Oak and spice", items: ["mutton seekh", "smoked paneer", "pecan pie", "salted pecans"] }],
    whyChoose: "The charred-barrel spice is clear without obscuring the bourbon's sweetness.",
    faqs: [{ question: "Who makes Elijah Craig?", answer: "Heaven Hill makes Elijah Craig bourbon in Kentucky." }, { question: "Why does Small Batch taste smoky?", answer: "Its level-three charred oak barrels contribute a subtle smoky note." }],
    finalVerdict: "A bourbon for drinkers who want toasted oak alongside the usual caramel and vanilla.",
    metaTitle: "Elijah Craig Bourbon Guide | BevOry", metaDescription: "Explore Elijah Craig's Kentucky bourbon, charred-oak spice and food pairings. Check city prices on BevOry.",
  },
  erdinger: {
    description: "Erdinger is a family-owned wheat-beer brewery in Erding, Bavaria. Its Weissbier is brewed from wheat and barley malt with top-fermenting yeast.",
    story: "Brewing at the Erding site was recorded in 1886. Franz Brombach bought the brewery in 1935; his son Werner later took its wheat beer beyond Bavaria.",
    tastingNotes: [{ title: "Yeast", description: "The top-fermented wheat beer has a soft, fruity aroma." }, { title: "Malt", description: "A gentle grain sweetness gives the cloudy pour its body." }],
    howToEnjoy: [{ subheading: "Tall glass", description: "Chill the bottle and pour slowly into a wheat-beer glass, finishing with the yeast." }, { subheading: "Snack table", description: "Try it with pretzels, aloo tikki or grilled sausages." }],
    pairingIdeas: [{ title: "Wheat beer food", items: ["soft pretzels", "aloo tikki", "grilled sausages", "fried mushrooms"] }],
    whyChoose: "Erdinger brings a distinctly Bavarian wheat-beer texture to a casual meal.",
    faqs: [{ question: "Where is Erdinger brewed?", answer: "In Erding, Bavaria, Germany." }, { question: "Is Erdinger Weissbier a lager?", answer: "No. Weissbier is a top-fermented wheat beer." }],
    finalVerdict: "The fruity yeast and soft grain body work especially well with salty snacks.",
    metaTitle: "Erdinger Wheat Beer Guide | BevOry", metaDescription: "Discover Erdinger's Bavarian wheat beer, fruity yeast character and snack pairings. Check city prices on BevOry.",
  },
  eristoff: {
    description: "Eristoff is a grain vodka whose family recipe traces to Georgia. The original expression is triple-distilled and charcoal-filtered for a clean, crisp profile.",
    story: "The Eristoff family dates its vodka recipe to 1806. Its wolf emblem draws on the Georgian setting associated with the family's story.",
    tastingNotes: [{ title: "Original", description: "A clean grain spirit with a restrained sweetness and crisp close." }, { title: "Texture", description: "Charcoal filtration leaves the original vodka smooth without a strong flavouring note." }],
    howToEnjoy: [{ subheading: "Cold serve", description: "Chill the vodka and pour a small measure neat or over ice." }, { subheading: "With food", description: "Pickled cucumber, chilli paneer and smoked fish provide contrast." }],
    pairingIdeas: [{ title: "Sharp bites", items: ["pickled cucumber", "chilli paneer", "smoked fish", "salted peanuts"] }],
    whyChoose: "Its spare grain profile leaves room for both a cold neat pour and a sharp mixer.",
    faqs: [{ question: "What is Eristoff Original made from?", answer: "It is made from grain and then triple-distilled and charcoal-filtered." }, { question: "Why is there a wolf on the label?", answer: "The wolf refers to the Georgian folklore tied to the Eristoff family's heritage." }],
    finalVerdict: "Choose Original when a crisp vodka, not a flavoured one, is the point.",
    metaTitle: "Eristoff Vodka Guide | BevOry", metaDescription: "Read Eristoff's Georgian story, grain-vodka style and serving ideas. Check city prices on BevOry.",
  },
  espolon: {
    description: "Espolón is a tequila made at the San Nicolás distillery in Mexico. Its production pairs pot and column distillation, while its labels take cues from José Guadalupe Posada's printmaking.",
    story: "Master distiller Cirilo Oropeza shaped the house style. The distillery presses cooked agave, ferments the juice and bottles the tequila on site.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus give the clear tequila its direct, bright character." }, { title: "Reposado", description: "American oak adds a gentler, warmer edge to the agave." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use Blanco with fresh lime in a Paloma; pour Reposado over ice." }, { subheading: "Alongside", description: "Tacos al pastor, paneer tikka and chilli-lime corn keep the food lively." }],
    pairingIdeas: [{ title: "Tequila table", items: ["tacos al pastor", "paneer tikka", "chilli-lime corn", "guacamole"] }],
    whyChoose: "Espolón ties a practical cocktail tequila to a vivid Mexican printmaking tradition.",
    faqs: [{ question: "Where is Espolón tequila made?", answer: "At the San Nicolás distillery in Mexico." }, { question: "What do its illustrated labels reference?", answer: "They draw inspiration from the work of Mexican printmaker José Guadalupe Posada." }],
    finalVerdict: "Blanco is the sharper cocktail choice; Reposado has a softer oak-led sip.",
    metaTitle: "Espolón Tequila Guide | BevOry", metaDescription: "Meet Espolón tequila, its Posada-inspired labels and agave-led serves. Check city prices on BevOry.",
  },
  "evan-williams": {
    description: "Evan Williams is a Kentucky straight bourbon label from Heaven Hill. Black Label is its familiar oak-aged bourbon, while Bottled-in-Bond and 1783 give the range different weight.",
    story: "The brand takes its name from a Welsh-born early Kentucky distiller. Heaven Hill later made Evan Williams one of its signature bourbon labels and opened a Louisville visitor experience in its name.",
    tastingNotes: [{ title: "Black Label", description: "Vanilla and caramel sit over familiar toasted-oak spice." }, { title: "Bottled-in-Bond", description: "The stronger bottling gives the grain and oak a firmer presence." }],
    howToEnjoy: [{ subheading: "Old Fashioned", description: "Mix Black Label with bitters and a little sugar, or sip it with a cube." }, { subheading: "At the table", description: "Barbecue chicken, galouti kebabs and peanut brittle suit its sweet oak." }],
    pairingIdeas: [{ title: "Bourbon food", items: ["barbecue chicken", "galouti kebabs", "peanut brittle", "charred corn"] }],
    whyChoose: "The range lets you move from an easy mixer to a more assertive bourbon without changing labels.",
    faqs: [{ question: "Who owns Evan Williams?", answer: "Heaven Hill Brands owns the Evan Williams bourbon label." }, { question: "Is Evan Williams a bourbon?", answer: "Yes. Its core range is Kentucky straight bourbon whiskey." }],
    finalVerdict: "Black Label belongs in the bar's everyday bourbon slot, especially for stirred drinks.",
    metaTitle: "Evan Williams Bourbon Guide | BevOry", metaDescription: "Explore Evan Williams bourbon, Kentucky roots and cocktail pairings. Check city prices on BevOry.",
  },
  fosters: {
    description: "Foster's is a lager label that began in Melbourne, Australia. The pale, light-bodied beer was built around a cold, refreshing pour.",
    story: "Brothers William and Ralph Foster established their brewery in Collingwood in 1888. Their first beer reached Melbourne hotels in February 1889, with refrigeration central to its early appeal.",
    tastingNotes: [{ title: "Malt", description: "A modest grain sweetness sits beneath the pale lager." }, { title: "Finish", description: "Light hop bitterness leaves a clean, brisk end." }],
    howToEnjoy: [{ subheading: "Cold glass", description: "Serve well chilled in a tall lager glass." }, { subheading: "Bar snacks", description: "Pair with masala fries, chicken wings or salted peanuts." }],
    pairingIdeas: [{ title: "Cold-beer snacks", items: ["masala fries", "chicken wings", "salted peanuts", "fried fish"] }],
    whyChoose: "Foster's keeps the lager light enough for a noisy, snack-heavy table.",
    faqs: [{ question: "Where did Foster's begin?", answer: "In Collingwood, Melbourne, Australia." }, { question: "Who founded Foster's?", answer: "Brothers William and Ralph Foster established the original brewery." }],
    finalVerdict: "This is a cold-pour lager for fried food and conversation, not a contemplative beer.",
    metaTitle: "Foster's Lager Guide | BevOry", metaDescription: "Discover Foster's Melbourne origins, light lager profile and snack pairings. Check city prices on BevOry.",
  },
  "four-pillars": {
    description: "Four Pillars is an Australian gin producer based in Healesville in the Yarra Valley. Rare Dry Gin combines native lemon myrtle and Tasmanian pepperberry with fresh orange and other botanicals.",
    story: "The distillery began in 2013 and made Healesville its home in 2015. Its copper stills have names, starting with Wilma, a detail that has stayed as the operation grew.",
    tastingNotes: [{ title: "Rare Dry Gin", description: "Orange peel and lemon myrtle bring a bright citrus nose." }, { title: "Spice", description: "Cardamom and pepperberry give the citrus a dry, aromatic frame." }],
    howToEnjoy: [{ subheading: "G&T", description: "Build a cold gin and tonic with fresh orange rather than a sweet syrup." }, { subheading: "Dinner", description: "Tandoori prawns, orange-glazed carrots and pepper chicken suit the botanicals." }],
    pairingIdeas: [{ title: "Citrus and spice", items: ["tandoori prawns", "orange-glazed carrots", "pepper chicken", "roasted cashews"] }],
    whyChoose: "Rare Dry Gin makes Australian citrus and pepperberry useful at the cocktail table.",
    faqs: [{ question: "Where is Four Pillars gin made?", answer: "In Healesville, in Victoria's Yarra Valley." }, { question: "Which Australian botanicals appear in Rare Dry Gin?", answer: "They include lemon myrtle and Tasmanian pepperberry." }],
    finalVerdict: "Its citrus-heavy gin and tonic feels especially right beside seafood or peppery food.",
    metaTitle: "Four Pillars Gin Guide | BevOry", metaDescription: "Meet Four Pillars gin from Healesville, with orange, lemon myrtle and serving ideas. Check city prices on BevOry.",
  },
  freixenet: {
    description: "Freixenet is a Spanish sparkling-wine house closely associated with cava from Penedès. Cordón Negro uses Parellada, Macabeo and Xarel·lo grapes and gains its bubbles through a second fermentation in the bottle.",
    story: "Dolors Sala helped build Freixenet's international reputation from Catalonia. Its black-bottle Cordón Negro became one of the house's most recognizable cavas.",
    tastingNotes: [{ title: "Cordón Negro", description: "Green apple, pear and citrus sit above its brisk bubbles." }, { title: "Carta Nevada", description: "The white-bottle cava is fruitier and softer in impression." }],
    howToEnjoy: [{ subheading: "Chilled", description: "Pour cava cold into a tulip glass so its fruit and bubbles remain clear." }, { subheading: "With crunch", description: "Papdi chaat, fried chicken and tempura vegetables meet the acidity well." }],
    pairingIdeas: [{ title: "Crisp matches", items: ["papdi chaat", "fried chicken", "tempura vegetables", "salted almonds"] }],
    whyChoose: "Its Penedès grapes and bottle fermentation offer a useful alternative to Champagne.",
    faqs: [{ question: "Is Freixenet cava Champagne?", answer: "No. Its cava is Spanish sparkling wine made in the traditional bottle-fermented method." }, { question: "Which grapes are in Cordón Negro?", answer: "Parellada, Macabeo and Xarel·lo." }],
    finalVerdict: "Cordón Negro is the sharp, food-friendly bottle to bring to a fried-snack spread.",
    metaTitle: "Freixenet Cava Guide | BevOry", metaDescription: "Explore Freixenet's Penedès cava, traditional grapes and Indian snack pairings. Check city prices on BevOry.",
  },
  frescobaldi: {
    description: "Frescobaldi is a family-owned Tuscan wine producer with estates across the region. Its wines include Sangiovese-led reds as well as Chardonnay and other grapes suited to individual vineyard sites.",
    story: "The Frescobaldi family has made wine in Tuscany since the early fourteenth century. Its estate approach now spans markedly different Tuscan landscapes rather than treating the region as one uniform vineyard.",
    tastingNotes: [{ title: "Sangiovese reds", description: "Red cherry and savoury acidity shape the Chianti side of the range." }, { title: "Pomino whites", description: "Chardonnay from the cooler Pomino estate is fuller and more orchard-fruited." }],
    howToEnjoy: [{ subheading: "By style", description: "Serve Pomino whites chilled and Sangiovese reds slightly below room temperature." }, { subheading: "At dinner", description: "Try reds with mushroom pasta or mutton ragù; whites suit tandoori fish." }],
    pairingIdeas: [{ title: "Tuscan table", items: ["mushroom pasta", "mutton ragù", "tandoori fish", "aged pecorino"] }],
    whyChoose: "Frescobaldi shows how differently Tuscan sites can speak through one family of wines.",
    faqs: [{ question: "Where is Frescobaldi based?", answer: "Its wine estates are in Tuscany, Italy." }, { question: "Does Frescobaldi only make red wine?", answer: "No. Its estates also produce white wines, including Chardonnay at Pomino." }],
    finalVerdict: "Choose by estate and grape; there is no single Frescobaldi flavour profile.",
    metaTitle: "Frescobaldi Tuscan Wine Guide | BevOry", metaDescription: "Explore Frescobaldi's Tuscan estates, Sangiovese and Pomino whites. Check city prices on BevOry.",
  },
  frontera: {
    description: "Frontera is a Chilean wine label from Concha y Toro. Its range includes Central Valley Cabernet Sauvignon and other approachable varietal wines.",
    story: "Concha y Toro built Frontera around Chile's accessible, fruit-led wines. The Central Valley's warm growing conditions are especially useful for the label's red grapes.",
    tastingNotes: [{ title: "Cabernet Sauvignon", description: "Dark berries and a mild herbal edge give the red its familiar shape." }, { title: "Young style", description: "The fruit stays direct rather than taking on heavy cellar-aged notes." }],
    howToEnjoy: [{ subheading: "Red glass", description: "Serve Cabernet slightly cool in a medium wine glass." }, { subheading: "With supper", description: "Pepper chicken, mutton keema and grilled aubergine suit the red." }],
    pairingIdeas: [{ title: "Red-wine plates", items: ["pepper chicken", "mutton keema", "grilled aubergine", "beef empanadas"] }],
    whyChoose: "Frontera offers a direct introduction to Chilean varietal wine.",
    faqs: [{ question: "Who makes Frontera wine?", answer: "The Chilean producer Concha y Toro." }, { question: "Where does Frontera Cabernet Sauvignon come from?", answer: "Its Cabernet Sauvignon is associated with Chile's Central Valley." }],
    finalVerdict: "The Cabernet is a sensible, fruit-led red for an everyday spicy dinner.",
    metaTitle: "Frontera Chilean Wine Guide | BevOry", metaDescription: "Meet Frontera's Chilean Cabernet Sauvignon and food-friendly red style. Check city prices on BevOry.",
  },
  "g-h-mumm": {
    description: "G.H. Mumm is a Champagne house based in Reims, France. Pinot Noir has a leading role in its structured, fresh house style, especially in Grand Cordon.",
    story: "The Mumm family's wine business began in Cologne before its sons established the Reims Champagne house in 1827. Georges Hermann Mumm later expanded its vineyards, and the red sash became the signature of Cordon Rouge.",
    tastingNotes: [{ title: "Pinot Noir", description: "Red-fruit richness gives the house's brut Champagne some weight." }, { title: "Mousse", description: "Fine bubbles and lively acidity keep the finish fresh." }],
    howToEnjoy: [{ subheading: "Tulip glass", description: "Serve chilled in a tulip-shaped glass rather than an overly narrow flute." }, { subheading: "First course", description: "Tandoori prawns, fried calamari and mushroom tart welcome the acidity." }],
    pairingIdeas: [{ title: "With bubbles", items: ["tandoori prawns", "fried calamari", "mushroom tart", "salted cashews"] }],
    whyChoose: "Mumm's Pinot Noir backbone gives its Champagne more table presence than a purely delicate aperitif.",
    faqs: [{ question: "Where is G.H. Mumm based?", answer: "In Reims, in France's Champagne region." }, { question: "What does the red sash on Mumm Champagne signify?", answer: "It is the Cordon Rouge, the house's historic visual signature." }],
    finalVerdict: "A chilled Grand Cordon belongs at the start of dinner and can stay through the first plate.",
    metaTitle: "G.H. Mumm Champagne Guide | BevOry", metaDescription: "Discover Mumm's Reims history, Pinot Noir style and dinner pairings. Check city prices on BevOry.",
  },
  gaja: {
    description: "Gaja is a family wine producer based in Barbaresco in Italy's Piedmont region. Nebbiolo is central to its Barbaresco wines, while the family also works vineyards elsewhere in Italy.",
    story: "The house was established in Barbaresco in 1859. Angelo Gaja helped take the family's wines to a wider audience while keeping the village's Nebbiolo identity in view.",
    tastingNotes: [{ title: "Barbaresco", description: "Nebbiolo brings rose, red cherry and firm, drying tannins." }, { title: "Bottle age", description: "Mature examples can move toward dried flowers, tea and savoury earth." }],
    howToEnjoy: [{ subheading: "Give it air", description: "Pour Barbaresco into a broad red-wine glass and allow time for the aroma to open." }, { subheading: "With food", description: "Mushroom risotto, mutton rogan josh and truffle pasta meet its tannin." }],
    pairingIdeas: [{ title: "Nebbiolo dinner", items: ["mushroom risotto", "mutton rogan josh", "truffle pasta", "aged parmesan"] }],
    whyChoose: "Gaja's Barbaresco brings Nebbiolo's floral aroma and firm structure into one glass.",
    faqs: [{ question: "Where is Gaja based?", answer: "In Barbaresco, Piedmont, Italy." }, { question: "Which grape defines Gaja Barbaresco?", answer: "Nebbiolo." }],
    finalVerdict: "Open a Barbaresco with a substantial meal; its structure is the reward.",
    metaTitle: "Gaja Barbaresco Wine Guide | BevOry", metaDescription: "Explore Gaja's Piedmont roots, Nebbiolo character and dinner pairings. Check city prices on BevOry.",
  },
  gianchand: {
    description: "GianChand is an Indian single malt whisky from DeVANS, made in Jammu. The range draws on malted barley and local distilling conditions rather than borrowing a Scottish origin story.",
    story: "DeVANS named the whisky for its founder, Dewan Gian Chand. The Jammu distillery extends a company better known for Indian beer into single malt.",
    tastingNotes: [{ title: "Malt", description: "Honeyed grain and orchard fruit shape the softer side of the whisky." }, { title: "Oak", description: "Wood ageing adds gentle vanilla and spice to the finish." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Sip a small measure neat before adding water or ice." }, { subheading: "Savoury food", description: "Try with tandoori mushroom, mutton seekh or roasted walnuts." }],
    pairingIdeas: [{ title: "Jammu malt table", items: ["tandoori mushroom", "mutton seekh", "roasted walnuts", "paneer tikka"] }],
    whyChoose: "GianChand gives a Jammu-made single malt a place among India's regional whiskies.",
    faqs: [{ question: "Who makes GianChand whisky?", answer: "DeVANS produces the single malt in Jammu, India." }, { question: "Why is it called GianChand?", answer: "It is named in honour of DeVANS founder Dewan Gian Chand." }],
    finalVerdict: "A locally rooted malt to taste slowly, especially beside smoky North Indian food.",
    metaTitle: "GianChand Indian Single Malt Guide | BevOry", metaDescription: "Meet GianChand single malt from Jammu, with malt, oak and food notes. Check city prices on BevOry.",
  },
  "gin-mare": {
    description: "Gin Mare is a Spanish Mediterranean gin made near Barcelona. Arbequina olives, rosemary, thyme and basil set its savoury botanical direction.",
    story: "The gin began in a fishing village where an eighteenth-century chapel houses its original custom still. Its makers distil botanicals separately before blending them into the finished spirit.",
    tastingNotes: [{ title: "Olive", description: "Arbequina gives a subtle green, savoury edge." }, { title: "Garden herbs", description: "Rosemary, thyme and basil make the nose unmistakably Mediterranean." }],
    howToEnjoy: [{ subheading: "Dry tonic", description: "Build a gin and tonic with dry tonic, ice and a rosemary sprig." }, { subheading: "At dinner", description: "Grilled prawns, olive tapenade and tandoori fish pick up the herbal notes." }],
    pairingIdeas: [{ title: "Herbal plates", items: ["grilled prawns", "olive tapenade", "tandoori fish", "tomato bruschetta"] }],
    whyChoose: "Olive and kitchen herbs put this gin closer to dinner than dessert.",
    faqs: [{ question: "What makes Gin Mare different?", answer: "Its Mediterranean botanicals include Arbequina olive, rosemary, thyme and basil." }, { question: "Where is Gin Mare made?", answer: "Near Barcelona in Spain." }],
    finalVerdict: "A rosemary-garnished G&T makes the most of its savoury side.",
    metaTitle: "Gin Mare Mediterranean Gin Guide | BevOry", metaDescription: "Discover Gin Mare's olive, basil and rosemary botanicals with food pairings. Check city prices on BevOry.",
  },
  glenallachie: {
    description: "The GlenAllachie is a Speyside single malt made at the distillery of the same name in Scotland. Its core range gives oak casks a prominent part in the flavour, particularly sherry-seasoned wood.",
    story: "The distillery began production in 1968 after a 1967 build. Billy Walker, Trisha Savage and Graham Stevenson acquired it in 2017 and released its first core single-malt range the following year.",
    tastingNotes: [{ title: "Sherry casks", description: "Dried fruit and cocoa enrich the malt's grain sweetness." }, { title: "Spice", description: "Oak brings cinnamon-like warmth to the finish." }],
    howToEnjoy: [{ subheading: "Small pour", description: "Try neat first, then add water to open the cask aromas." }, { subheading: "After dinner", description: "Dark chocolate, mutton seekh and toasted almonds suit the deeper releases." }],
    pairingIdeas: [{ title: "Rich matches", items: ["dark chocolate", "mutton seekh", "toasted almonds", "date cake"] }],
    whyChoose: "GlenAllachie's cask-led Speyside style puts dried fruit beside malt rather than hiding it.",
    faqs: [{ question: "Where is GlenAllachie made?", answer: "At The GlenAllachie distillery in Speyside, Scotland." }, { question: "Who bought the distillery in 2017?", answer: "Billy Walker, Trisha Savage and Graham Stevenson." }],
    finalVerdict: "The sherry-cask side is an inviting place to start with this malt.",
    metaTitle: "GlenAllachie Single Malt Guide | BevOry", metaDescription: "Explore GlenAllachie's Speyside history, sherry-cask notes and pairings. Check city prices on BevOry.",
  },
  glengoyne: {
    description: "Glengoyne is a Highland single malt distilled near Dumgoyne, Scotland. It uses unpeated malt and is known for slow distillation and cask-led fruit rather than smoke.",
    story: "The distillery dates to 1833. Its stills sit in the Highlands while its maturation warehouses lie across the road in the Lowlands, an unusual bit of geography behind the label.",
    tastingNotes: [{ title: "Fruit", description: "Apple and dried-fruit notes lead the unpeated style." }, { title: "Oak", description: "Sherry-seasoned casks can add nuts and warm spice." }],
    howToEnjoy: [{ subheading: "No rush", description: "Pour neat and add a few drops of water after the first sip." }, { subheading: "With bites", description: "Roast mushrooms, paneer tikka and salted almonds make measured partners." }],
    pairingIdeas: [{ title: "Quiet pairings", items: ["roast mushrooms", "paneer tikka", "salted almonds", "apple tart"] }],
    whyChoose: "The malt's fruit and oak come through without peat smoke crowding the glass.",
    faqs: [{ question: "Is Glengoyne smoky?", answer: "Its core malt is made with unpeated barley, so peat smoke is not its defining note." }, { question: "Where is the distillery?", answer: "At Dumgoyne, near the Highland-Lowland boundary in Scotland." }],
    finalVerdict: "A slow, fruit-led Highland malt for an evening without smoke.",
    metaTitle: "Glengoyne Single Malt Guide | BevOry", metaDescription: "Meet Glengoyne's unpeated Highland malt, fruit and sherry-cask style. Check city prices on BevOry.",
  },
  godawan: {
    description: "Godawan is an Indian single malt whisky made by Diageo India at Alwar in Rajasthan. Its identity draws on desert maturation and the region's conservation work for the Great Indian Bustard.",
    story: "Diageo chose Alwar for a distinctly Rajasthan-made malt rather than a neutral production site. The whisky takes its name from the local name for the Great Indian Bustard.",
    tastingNotes: [{ title: "Malt", description: "Honeyed cereal and ripe fruit bring softness to the pour." }, { title: "Wood", description: "Oak adds vanilla and warming spice as the whisky closes." }],
    howToEnjoy: [{ subheading: "First glass", description: "Try neat in a tasting glass, then add a little water." }, { subheading: "Rajasthani plate", description: "Laal maas, ker sangri and roasted almonds stand up to the malt." }],
    pairingIdeas: [{ title: "Desert table", items: ["laal maas", "ker sangri", "roasted almonds", "smoked paneer"] }],
    whyChoose: "Godawan grounds Indian single malt in Alwar's dry landscape and a local conservation story.",
    faqs: [{ question: "Where is Godawan whisky made?", answer: "At Diageo India's Alwar distillery in Rajasthan." }, { question: "What does Godawan mean?", answer: "It is a local name for the Great Indian Bustard." }],
    finalVerdict: "Taste it beside a bold Rajasthani dish to see where the whisky's regional story lands.",
    metaTitle: "Godawan Indian Single Malt Guide | BevOry", metaDescription: "Discover Godawan single malt from Alwar, Rajasthan, with serving and food ideas. Check city prices on BevOry.",
  },
  godfather: {
    description: "Godfather is an Indian beer label from DeVANS Modern Breweries. Its range includes stronger beers as well as a lighter Luxury Lager.",
    story: "DeVANS has treated Godfather as its flagship beer since 1984. The label's line-up has widened from a strong-beer identity into several lager styles.",
    tastingNotes: [{ title: "Strong styles", description: "Fuller malt and a more forceful finish mark the stronger beers." }, { title: "Luxury Lager", description: "A lighter body and measured hop bitterness keep the lager brisk." }],
    howToEnjoy: [{ subheading: "Cold", description: "Serve the beer chilled in a clean lager glass." }, { subheading: "With snacks", description: "Try chicken tikka, spicy fries or masala peanuts." }],
    pairingIdeas: [{ title: "Beer snacks", items: ["chicken tikka", "spicy fries", "masala peanuts", "tandoori mushrooms"] }],
    whyChoose: "Godfather offers both a punchier strong beer and a gentler lager under one Indian label.",
    faqs: [{ question: "Who makes Godfather beer?", answer: "DeVANS Modern Breweries in India." }, { question: "Is every Godfather beer strong?", answer: "No. The range also includes Luxury Lager." }],
    finalVerdict: "Match the bottle to the meal: stronger beer for heat, lighter lager for a longer session.",
    metaTitle: "Godfather Beer Guide | BevOry", metaDescription: "Explore Godfather's Indian strong beers and Luxury Lager with snack pairings. Check city prices on BevOry.",
  },
  "gouden-carolus": {
    description: "Gouden Carolus is a Belgian speciality-beer range brewed by Het Anker in Mechelen. Its Classic is a dark, high-fermentation beer built on roasted malt, caramel and chocolate notes.",
    story: "Beer has been made at the Mechelen site for centuries, and the Van Breedam family took over in 1872. In the twentieth century the brewery left lager behind and made Gouden Carolus its flagship.",
    tastingNotes: [{ title: "Classic", description: "Caramel and bitter chocolate meet a dark, fruit-tinged malt body." }, { title: "Roast", description: "A restrained roasted note keeps the sweetness from feeling flat." }],
    howToEnjoy: [{ subheading: "Belgian glass", description: "Pour Classic into a stemmed glass rather than drinking it icy cold." }, { subheading: "Slow meal", description: "Beef stew, mutton rogan josh and dark chocolate suit its depth." }],
    pairingIdeas: [{ title: "Dark-beer dinner", items: ["beef stew", "mutton rogan josh", "dark chocolate", "mushroom pie"] }],
    whyChoose: "The dark malt gives Classic enough breadth to stay with a hearty dinner.",
    faqs: [{ question: "Who brews Gouden Carolus?", answer: "Het Anker brewery in Mechelen, Belgium." }, { question: "What style is Gouden Carolus Classic?", answer: "A dark Belgian speciality beer made by high fermentation." }],
    finalVerdict: "Classic earns a stemmed glass and food more substantial than bar snacks.",
    metaTitle: "Gouden Carolus Beer Guide | BevOry", metaDescription: "Discover Gouden Carolus from Mechelen, its dark-malt style and rich pairings. Check city prices on BevOry.",
  },
  "grand-macnish": {
    description: "Grand Macnish is a blended Scotch whisky with roots in Glasgow. The original blend was intended as a lighter alternative to the heavier Scotch of its day.",
    story: "Glasgow merchant Robert McNish created the label in 1863. The name has stayed with the blending tradition even as later expressions have joined the Original.",
    tastingNotes: [{ title: "Original", description: "Gentle grain sweetness and light orchard fruit keep the blend easy to approach." }, { title: "Finish", description: "Soft oak spice closes without heavy peat." }],
    howToEnjoy: [{ subheading: "Simple highball", description: "Pour over ice and lengthen with soda, or try a small neat measure." }, { subheading: "With bites", description: "Salted cashews, chicken tikka and cheddar toast suit the lighter blend." }],
    pairingIdeas: [{ title: "Light blend food", items: ["salted cashews", "chicken tikka", "cheddar toast", "roasted peanuts"] }],
    whyChoose: "Original keeps blended Scotch soft enough for an uncomplicated highball.",
    faqs: [{ question: "Where did Grand Macnish begin?", answer: "In Glasgow, Scotland, in 1863." }, { question: "Who created Grand Macnish?", answer: "Glasgow merchant Robert McNish." }],
    finalVerdict: "A lightly styled Scotch that makes its strongest case with soda and salty food.",
    metaTitle: "Grand Macnish Scotch Guide | BevOry", metaDescription: "Meet Grand Macnish's Glasgow blend, gentle style and highball pairings. Check city prices on BevOry.",
  },
  "guado-al-tasso": {
    description: "Guado al Tasso is a Bolgheri wine estate of the Antinori family on Tuscany's upper Maremma coast. Its flagship red uses Bordeaux grapes grown in a sea-facing amphitheatre of vineyards.",
    story: "The property came into the Antinori family through Carlotta della Gherardesca Antinori. The flagship Guado al Tasso wine first appeared in 1990 as Bolgheri developed its modern red-wine identity.",
    tastingNotes: [{ title: "Dark fruit", description: "The red's Cabernet-family grapes bring blackcurrant and dark cherry." }, { title: "Structure", description: "Firm tannins and oak spice give the wine the weight for a long meal." }],
    howToEnjoy: [{ subheading: "Red glass", description: "Serve slightly cool in a broad glass and give a young bottle air." }, { subheading: "Rich plates", description: "Try lamb chops, mutton rogan josh or mushroom ragù." }],
    pairingIdeas: [{ title: "Bolgheri table", items: ["lamb chops", "mutton rogan josh", "mushroom ragù", "aged pecorino"] }],
    whyChoose: "This Antinori estate puts coastal Bolgheri's structured reds in clear focus.",
    faqs: [{ question: "Where is Guado al Tasso?", answer: "In the Bolgheri DOC area on Tuscany's upper Maremma coast." }, { question: "Who owns the estate?", answer: "The Antinori family." }],
    finalVerdict: "Save the flagship red for a meal able to meet its tannin and depth.",
    metaTitle: "Guado al Tasso Wine Guide | BevOry", metaDescription: "Explore Antinori's Bolgheri estate, coastal reds and dinner pairings. Check city prices on BevOry.",
  },
  haku: {
    description: "Haku is a Japanese vodka from Suntory made from Japanese white rice. Bamboo-charcoal filtration gives the spirit a clean, soft texture.",
    story: "The name Haku can mean white or brilliance, a reference to the polished rice behind the vodka. Suntory makes it within its broader tradition of Japanese spirits and rice fermentation.",
    tastingNotes: [{ title: "Rice", description: "A quiet sweetness sits beneath the neutral spirit." }, { title: "Texture", description: "The bamboo-charcoal filtered finish feels notably silky." }],
    howToEnjoy: [{ subheading: "Cold and short", description: "Try chilled neat or in a dry Martini with a lemon twist." }, { subheading: "With food", description: "Sushi, tandoori fish and salted edamame suit its soft profile." }],
    pairingIdeas: [{ title: "Clean flavours", items: ["sushi", "tandoori fish", "salted edamame", "cucumber salad"] }],
    whyChoose: "Rice and bamboo charcoal give Haku a recognisable Japanese production story.",
    faqs: [{ question: "What is Haku vodka made from?", answer: "Japanese white rice." }, { question: "How is Haku filtered?", answer: "Through bamboo charcoal." }],
    finalVerdict: "A chilled Haku Martini keeps the rice softness in view.",
    metaTitle: "Haku Japanese Vodka Guide | BevOry", metaDescription: "Discover Haku's white-rice base, bamboo-charcoal filtration and food pairings. Check city prices on BevOry.",
  },
  hakushika: {
    description: "Hakushika is a sake label from the Tatsuuma brewery in Nishinomiya, Hyogo. The brewery uses the region's miyamizu water and rice in a range of Japanese sake styles.",
    story: "Kichizaemon Tatsuuma founded the brewery in 1662. Its Nishinomiya home lies in the Nada brewing area, where water and cool winds have long shaped sake making.",
    tastingNotes: [{ title: "Junmai", description: "Rice-driven savouriness gives the sake a rounded centre." }, { title: "Ginjo styles", description: "More aromatic releases bring a lighter fruit and floral lift." }],
    howToEnjoy: [{ subheading: "By bottle", description: "Use a small sake glass; chill aromatic ginjo or gently warm a suitable junmai." }, { subheading: "Food", description: "Prawn tempura, grilled mushrooms and paneer in light ginger sauce work well." }],
    pairingIdeas: [{ title: "Sake plates", items: ["prawn tempura", "grilled mushrooms", "ginger paneer", "rice crackers"] }],
    whyChoose: "Hakushika carries Nishinomiya's old sake-brewing identity into a broad modern range.",
    faqs: [{ question: "Where is Hakushika sake brewed?", answer: "In Nishinomiya, Hyogo Prefecture, Japan." }, { question: "When did its brewery begin?", answer: "Kichizaemon Tatsuuma founded it in 1662." }],
    finalVerdict: "Start with a chilled aromatic bottle and a plate of lightly seasoned food.",
    metaTitle: "Hakushika Sake Guide | BevOry", metaDescription: "Explore Hakushika's Nishinomiya heritage, sake styles and food pairings. Check city prices on BevOry.",
  },
  hakutsuru: {
    description: "Hakutsuru brews Japanese sake in Nada, Kobe, using rice and local water. Its range spans junmai, fragrant junmai ginjo and cloudy nigori styles.",
    story: "The brewery traces its roots to 1743 in the Nada district. Generations of brewers have used the area's water and rice to make sake with several very different textures.",
    tastingNotes: [{ title: "Superior Junmai Ginjo", description: "Strawberry, pear and a quiet nutty-rice note sit over mild acidity." }, { title: "Sayuri Nigori", description: "The cloudy sake is softer, lightly sweet and floral." }],
    howToEnjoy: [{ subheading: "Chilled glass", description: "Serve Superior Junmai Ginjo cool in a small glass." }, { subheading: "At dinner", description: "Grilled prawns, vegetable tempura and rice crackers complement the delicate sake." }],
    pairingIdeas: [{ title: "Nada sake food", items: ["grilled prawns", "vegetable tempura", "rice crackers", "lightly spiced tofu"] }],
    whyChoose: "The junmai ginjo and nigori show how much texture can change within one sake house.",
    faqs: [{ question: "Where is Hakutsuru sake made?", answer: "In the Nada district of Kobe, Japan." }, { question: "What is Hakutsuru Sayuri?", answer: "A cloudy nigori sake with a gently sweet profile." }],
    finalVerdict: "The chilled junmai ginjo is an easy first glass alongside seafood.",
    metaTitle: "Hakutsuru Sake Guide | BevOry", metaDescription: "Meet Hakutsuru sake from Kobe, from junmai ginjo to cloudy nigori. Check city prices on BevOry.",
  },
  "height-of-arrows": {
    description: "Height of Arrows is an Edinburgh gin from Holyrood Distillery. Juniper is its sole botanical; sea salt and beeswax modify flavour and texture without turning it into a herb garden.",
    story: "The name refers to Arthur's Seat, the hill behind the distillery, through the Gaelic Àrd-Na-Said. Holyrood's whisky makers deliberately approached gin with a short ingredient list.",
    tastingNotes: [{ title: "Juniper", description: "Pine and resin give the nose its direct gin character." }, { title: "Texture", description: "Beeswax lends a rounder mouthfeel, while salt sharpens the finish." }],
    howToEnjoy: [{ subheading: "Dry tonic", description: "Pour with dry tonic and a restrained lemon peel." }, { subheading: "With bites", description: "Salted olives, lemon chicken and tandoori prawns fit the savoury edge." }],
    pairingIdeas: [{ title: "Juniper partners", items: ["salted olives", "lemon chicken", "tandoori prawns", "rosemary potatoes"] }],
    whyChoose: "One botanical, juniper, makes the gin's structure unusually easy to taste.",
    faqs: [{ question: "Who makes Height of Arrows?", answer: "Holyrood Distillery in Edinburgh, Scotland." }, { question: "How many botanicals does it use?", answer: "Juniper is its only botanical; sea salt and beeswax act as modifiers." }],
    finalVerdict: "This is a gin for people who actually want to taste juniper.",
    metaTitle: "Height of Arrows Gin Guide | BevOry", metaDescription: "Discover Edinburgh's juniper-led Height of Arrows gin and serving ideas. Check city prices on BevOry.",
  },
  hibiki: {
    description: "Hibiki is a blended Japanese whisky from Suntory. Japanese Harmony brings together malt and grain whiskies into a floral, honeyed style.",
    story: "Suntory introduced Hibiki in 1989 to mark its ninetieth anniversary. The name means resonance, fitting a whisky built by blending different distillery components.",
    tastingNotes: [{ title: "Japanese Harmony nose", description: "Rose, lychee and a light rosemary note rise first." }, { title: "Palate", description: "Honey, candied orange and white chocolate follow." }],
    howToEnjoy: [{ subheading: "Neat or tall", description: "Taste neat first; then try a highball with cold soda and clear ice." }, { subheading: "Alongside", description: "Yakitori, tandoori mushrooms and roasted almonds suit its measured sweetness." }],
    pairingIdeas: [{ title: "Harmony food", items: ["yakitori", "tandoori mushrooms", "roasted almonds", "white-chocolate tart"] }],
    whyChoose: "The blend shows Suntory's floral side without demanding a heavy oak or smoke palate.",
    faqs: [{ question: "Who makes Hibiki whisky?", answer: "The House of Suntory in Japan." }, { question: "Is Hibiki a single malt?", answer: "No. Hibiki is a blend of Japanese malt and grain whiskies." }],
    finalVerdict: "A small neat pour gives Japanese Harmony's floral details room to appear.",
    metaTitle: "Hibiki Japanese Whisky Guide | BevOry", metaDescription: "Explore Hibiki Japanese Harmony's floral blend, honey notes and pairings. Check city prices on BevOry.",
  },
  inglenook: {
    description: "Inglenook is a wine estate on the Rutherford Bench in Napa Valley, California. Cabernet Sauvignon and other Bordeaux varieties define its best-known reds.",
    story: "Gustave Niebaum bought the original property in 1879 and built the estate around contiguous vineyards. Francis and Eleanor Coppola later began the long work of reuniting the estate and its historic name.",
    tastingNotes: [{ title: "Cabernet", description: "Blackcurrant, dark cherry and structured tannin lead the red wines." }, { title: "Rutherford character", description: "The finish can turn toward cocoa and savoury earth with age." }],
    howToEnjoy: [{ subheading: "A little air", description: "Serve a young Cabernet in a broad glass and give it time after opening." }, { subheading: "Dinner", description: "Grilled lamb, mutton rogan josh and mushroom steak suit its weight." }],
    pairingIdeas: [{ title: "Rutherford reds", items: ["grilled lamb", "mutton rogan josh", "mushroom steak", "aged cheddar"] }],
    whyChoose: "Inglenook's Cabernet carries the Rutherford estate's long history in a structured red.",
    faqs: [{ question: "Where is Inglenook located?", answer: "On the Rutherford Bench in Napa Valley, California." }, { question: "Who founded Inglenook?", answer: "Gustave Niebaum established the estate in 1879." }],
    finalVerdict: "Bring its Cabernet to a substantial dinner and give the wine time in the glass.",
    metaTitle: "Inglenook Napa Wine Guide | BevOry", metaDescription: "Read Inglenook's Rutherford history, Cabernet style and dinner pairings. Check city prices on BevOry.",
  },
  "j-and-b": {
    description: "J&B is a blended Scotch whisky from Justerini & Brooks, now part of Diageo. J&B Rare combines malt and grain whiskies into a lighter, fruit-led style made for mixing.",
    story: "The merchant house became Justerini & Brooks after Alfred Brooks bought into the business. Later, Eddie Tatham and blender Charlie Julian developed J&B Rare from a blend of 42 malt and grain whiskies.",
    tastingNotes: [{ title: "Rare", description: "Light fruit and malt sweetness keep the blend approachable." }, { title: "Finish", description: "Gentle spice closes without a large smoky note." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice and add cold soda or lemonade." }, { subheading: "With snacks", description: "Chicken tikka, salted peanuts and cheese toast belong beside it." }],
    pairingIdeas: [{ title: "Easy highball food", items: ["chicken tikka", "salted peanuts", "cheese toast", "masala fries"] }],
    whyChoose: "J&B Rare puts a light Scotch blend to work in simple long drinks.",
    faqs: [{ question: "What does J&B stand for?", answer: "Justerini & Brooks." }, { question: "Is J&B Rare a single malt?", answer: "No. It is a blend of malt and grain Scotch whiskies." }],
    finalVerdict: "J&B Rare is most comfortable lengthened over ice at the snack table.",
    metaTitle: "J&B Blended Scotch Guide | BevOry", metaDescription: "Explore J&B Rare's blended Scotch history, light style and highball pairings. Check city prices on BevOry.",
  },
  "jim-barry": {
    description: "Jim Barry Wines is a family-owned producer in South Australia's Clare Valley. Riesling and Shiraz are central to its vineyards and regional reputation.",
    story: "Jim Barry became the Clare Valley's first qualified winemaker after graduating from Roseworthy in 1947. He and Nancy bought their first property in 1959, and the family still works vineyards across Clare.",
    tastingNotes: [{ title: "Clare Riesling", description: "Lime and firm acidity keep the white wines taut." }, { title: "Shiraz", description: "Dark berries, pepper and ripe tannins fill out the reds." }],
    howToEnjoy: [{ subheading: "Two glasses", description: "Serve Riesling chilled and Shiraz slightly cool in a larger red-wine glass." }, { subheading: "At dinner", description: "Tandoori fish suits Riesling; mutton seekh and roast aubergine suit Shiraz." }],
    pairingIdeas: [{ title: "Clare table", items: ["tandoori fish", "mutton seekh", "roast aubergine", "lime-dressed prawns"] }],
    whyChoose: "The family offers a useful Clare Valley contrast between sharp Riesling and generous Shiraz.",
    faqs: [{ question: "Where is Jim Barry Wines based?", answer: "In South Australia's Clare Valley." }, { question: "Who founded the winery?", answer: "Jim and Nancy Barry began building their family wine business in 1959." }],
    finalVerdict: "Choose Riesling for fish and spice, Shiraz for a darker, richer plate.",
    metaTitle: "Jim Barry Clare Valley Wine Guide | BevOry", metaDescription: "Explore Jim Barry's Clare Riesling, Shiraz and family history. Check city prices on BevOry.",
  },
};
