import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_50 = [
  ["four-seasons", "Four Seasons", "Wine"], ["vallonne", "Vallonne", "Wine"],
  ["charosa", "Charosa", "Wine"], ["suntory-toki", "Suntory Toki", "Whisky"],
  ["hakushu", "Hakushu", "Whisky"], ["ao", "Suntory Ao", "Whisky"],
  ["kakubin", "Suntory Kakubin", "Whisky"], ["knob-creek", "Knob Creek", "Whiskey"],
  ["basil-haydens", "Basil Hayden", "Whiskey"], ["gentleman-jack", "Gentleman Jack", "Whiskey"],
  ["courvoisier", "Courvoisier", "Cognac"], ["hornitos", "Hornitos", "Tequila"],
  ["sauza", "Sauza", "Tequila"], ["tres-generaciones", "Tres Generaciones", "Tequila"],
  ["dusse", "D'USSÉ", "Cognac"], ["cazadores", "Cazadores", "Tequila"],
  ["st-germain", "St-Germain", "Liqueur"], ["noilly-prat", "Noilly Prat", "Vermouth"],
  ["santa-teresa", "Santa Teresa", "Rum"], ["perrier-jouet", "Perrier-Jouët", "Champagne"],
  ["grand-marnier", "Grand Marnier", "Liqueur"], ["frangelico", "Frangelico", "Liqueur"],
  ["casamigos", "Casamigos", "Tequila"], ["bumbu", "Bumbu", "Rum"],
  ["chairmans-reserve", "Chairman's Reserve", "Rum"], ["dead-mans-fingers", "Dead Man's Fingers", "Rum"],
  ["pussers", "Pusser's", "Rum"], ["sailor-jerry", "Sailor Jerry", "Rum"],
  ["michelob-ultra", "Michelob Ultra", "Beer"], ["goose-island", "Goose Island", "Beer"],
] as const;

// Research links are internal. Public fields below contain only consumer copy.
export const BRAND_SOURCES_BATCH_50: Record<string, string[]> = {
  "four-seasons": ["https://www.diageoindia.com/en/news-and-media/press-releases/2019/usl-enters-into-a-share-purchase-agreement-for-the-sale-of-equity-shares-in-four-seasons"],
  vallonne: ["https://www.vallonnevineyards.com/aboutvallonnevineyards/"],
  charosa: ["https://charosavineyards.com/", "https://www.indianwineacademy.com/item_2_587.aspx", "https://www.thewinesofindia.com/charosa-vineyards"],
  "suntory-toki": ["https://house.suntory.com/toki-whisky"],
  hakushu: ["https://house.suntory.com/hakushu-whisky"],
  ao: ["https://house.suntory.com/ao-whisky"],
  kakubin: ["https://house.suntory.com/kakubin-whisky/kakubin"],
  "knob-creek": ["https://www.knobcreek.com/about-us"],
  "basil-haydens": ["https://www.basilhaydenbourbon.com/whiskies/basil-hayden-kentucky-straight-bourbon"],
  "gentleman-jack": ["https://pressroom.jackdaniels.com/products/"],
  courvoisier: ["https://www.courvoisier.com/maison-courvoisier/"],
  hornitos: ["https://www.hornitostequila.com/about-us"],
  sauza: ["https://www.sauzatequila.com/heritage"],
  "tres-generaciones": ["https://www.tresgeneraciones.com/"],
  dusse: ["https://www.dusse.com/product/dusse-vsop-personalized/"],
  cazadores: ["https://www.cazadores.com/us/en/culture/our-story/"],
  "st-germain": ["https://www.stgermainliqueur.com/about/"],
  "noilly-prat": ["https://www.noillyprat.com/", "https://www.noillyprat.com/heritage/"],
  "santa-teresa": ["https://www.santateresarum.com/heritage/"],
  "perrier-jouet": ["https://www.perrier-jouet.com/en-ww/the-house/history"],
  "grand-marnier": ["https://www.grandmarnier.com/our-collection/cordon-rouge/"],
  frangelico: ["https://frangelico.com/en-us/about/"],
  casamigos: ["https://www.casamigos.com/en-us/our-story"],
  bumbu: ["https://bumbu.sovereignbrands.com/", "https://www.pernod-ricard.com/en/brand/bumbu"],
  "chairmans-reserve": ["https://www.chairmansreserverum.com/learn-about-our-rums/"],
  "dead-mans-fingers": ["https://deadmansfingers.com/home/our-story/"],
  pussers: ["https://pussersrum.com/pages/history"],
  "sailor-jerry": ["https://www.sailorjerry.com/en-gb/rum-cocktail-recipes/our-story"],
  "michelob-ultra": ["https://www.michelobultra.com/"],
  "goose-island": ["https://www.gooseisland.com/beers/honkers", "https://www.gooseisland.com/grit-grain"],
};

// All 30 snapshot rows already have a logo URL. No replacement is proposed.
export const BRAND_LOGOS_BATCH_50: Record<string, string> = {};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_50: Record<string, BrandPublicContent> = {
  "four-seasons": guide("Four Seasons", "Wine", {
    description: "Four Seasons is an Indian wine label whose vineyards and winery are in Maharashtra. Its portfolio covers red, white and sparkling wines, with styles suited to both a meal and a chilled aperitif.",
    story: "The label was built under Four Seasons Wines, a United Spirits venture, before the business was sold to Grover Zampa and Quintela in 2019. The move joined an established Indian wine portfolio with another Maharashtra wine producer.",
    notes: ["Red wines", "Look for dark fruit and a fuller texture in the red-wine range.", "White wines", "The whites offer a lighter, fruit-led contrast to the reds."],
    serve: "Chill the whites before pouring; give a red a few minutes in the glass with dinner.",
    food: "Try a white with tandoori fish and a red with mushroom pepper fry or lamb kebabs.",
    pairings: ["tandoori fish", "mushroom pepper fry", "lamb kebabs"],
    whyChoose: "An Indian wine range with both lighter whites and dinner-ready reds.",
    faq: ["Is Four Seasons an Indian wine brand?", "Yes. Four Seasons Wines was an Indian wine business with a Maharashtra portfolio.", "Who bought Four Seasons Wines?", "Grover Zampa and Quintela agreed to acquire Four Seasons Wines from United Spirits in 2019."],
    finalVerdict: "Four Seasons offers a familiar entry to Indian wines across more than one style.",
    metaDescription: "Explore Four Seasons Indian wines, serving ideas and food pairings. Compare city prices on BevOry.",
  }),
  vallonne: guide("Vallonne", "Wine", {
    description: "Vallonne is a boutique winery near Igatpuri in Maharashtra's Nashik wine country. Founder Shailendra Pai works with estate fruit and grapes sourced from other Nashik vineyards.",
    story: "Pai established Vallonne in 2009 near the Mukhne Dam. Its small-scale approach and location west of Nashik city distinguish it from the region's larger producers.",
    notes: ["Estate reds", "The red-wine side of the range favours ripe fruit and a food-friendly texture.", "Chilled whites", "Fresh fruit and acidity make the whites a contrast to the richer reds."],
    serve: "Pour the whites chilled and serve reds slightly cool in a medium-sized wine glass.",
    food: "Match a white with tandoori prawns; bring a red to pepper chicken or mushroom galouti.",
    pairings: ["tandoori prawns", "pepper chicken", "mushroom galouti"],
    whyChoose: "A small Nashik-area winery with a recognisable Igatpuri home.",
    faq: ["Where is Vallonne Vineyards?", "The winery is near Igatpuri and Mukhne Dam in Maharashtra's Nashik region.", "Who founded Vallonne?", "Shailendra Pai founded the winery in 2009."],
    finalVerdict: "Vallonne brings a distinctly small-winery perspective to Nashik wine.",
    metaDescription: "Meet Vallonne near Igatpuri: its wines, serving ideas and Indian pairings. Compare city prices on BevOry.",
  }),
  charosa: guide("Charosa", "Wine", {
    description: "Charosa Vineyards makes wine in the Dindori area of Nashik, Maharashtra. Its range includes Tempranillo, Cabernet Sauvignon and Viognier across several tiers.",
    story: "Charosa takes its name from the village where its vineyards stand. Its Reserve Tempranillo helped make a Spanish red grape part of the conversation about Indian wine, alongside more familiar international varieties.",
    notes: ["Reserve Tempranillo", "Ripe red fruit and oak spice give this red its structured, savoury appeal.", "Viognier", "Aromatic stone fruit and a floral lift mark the white-wine side of the range."],
    serve: "Chill Viognier before serving; give the Tempranillo a little air in a wide wine glass.",
    food: "Try Viognier with paneer tikka and Tempranillo with mutton rogan josh or grilled aubergine.",
    pairings: ["paneer tikka", "mutton rogan josh", "grilled aubergine"],
    whyChoose: "One of Nashik's more interesting stops for a Tempranillo-led red.",
    faq: ["Where is Charosa wine made?", "Charosa is a Nashik wine estate in Maharashtra's Dindori area.", "Which grape is Charosa known for?", "Its Reserve Tempranillo is a notable red in the range."],
    finalVerdict: "Charosa is worth exploring for the contrast between aromatic whites and oak-influenced reds.",
    metaDescription: "Explore Charosa wines from Nashik, from Tempranillo to Viognier, with food pairings and city prices on BevOry.",
  }),
  "suntory-toki": guide("Suntory Toki", "Whisky", {
    description: "Suntory Toki is a Japanese blended whisky that combines spirit from Hakushu, Yamazaki and Chita. It is shaped for the tall, sparkling Japanese highball rather than a heavy after-dinner pour.",
    story: "Suntory built Toki around the contrast of malt and grain whisky from its three Japanese distilleries. Its name means 'time', a nod to the house's blending traditions and a more contemporary serving style.",
    notes: ["Citrus and green fruit", "The light opening has a fresh, crisp character suited to soda.", "Grain softness", "Chita grain whisky helps keep the blend gentle through the finish."],
    serve: "Fill a chilled highball glass with ice, add Toki and top with cold soda.",
    food: "Pour beside chicken yakitori, chilli paneer or salted edamame.",
    pairings: ["chicken yakitori", "chilli paneer", "salted edamame"],
    whyChoose: "A whisky whose best-known serve is refreshing rather than solemn.",
    faq: ["Is Suntory Toki a single malt?", "No. It is a blend of malt and grain whiskies from three Suntory distilleries.", "How is Toki usually served?", "A cold soda highball is its signature serve."],
    finalVerdict: "Toki makes a lively introduction to the Japanese whisky highball.",
    metaDescription: "Explore Suntory Toki's three-distillery blend, highball serve and food pairings. Compare city prices on BevOry.",
  }),
  hakushu: guide("Hakushu", "Whisky", {
    description: "Hakushu is a Japanese single malt made by Suntory at its distillery in Yamanashi, near the Southern Alps. Its herbal freshness and measured smoke set it apart from the richer Yamazaki style.",
    story: "Keizo Saji opened the Hakushu distillery in 1973, building Suntory's second malt-whisky home in a forested mountain setting. Water and cool air are central to how the distillery presents its identity.",
    notes: ["Herbal lift", "Minty, green aromas give Hakushu its strikingly fresh first impression.", "Gentle smoke", "A restrained smoky edge carries into the finish without covering the herbs."],
    serve: "Try a small neat pour first, then add a few drops of water or make a cold highball.",
    food: "It suits grilled trout, chicken yakitori and lightly spiced paneer tikka.",
    pairings: ["grilled trout", "chicken yakitori", "paneer tikka"],
    whyChoose: "Mountain-grown character, green aromatics and smoke in balance.",
    faq: ["Where is Hakushu made?", "Suntory makes it at Hakushu distillery in Yamanashi, Japan.", "Is Hakushu smoky?", "A subtle smoky note is part of its herbal single-malt profile."],
    finalVerdict: "Hakushu is a single malt for drinkers drawn to herbal notes rather than deep sweetness.",
    metaDescription: "Explore Hakushu single malt from Yamanashi, its herbal style and food pairings. Compare city prices on BevOry.",
  }),
  ao: guide("Suntory Ao", "Whisky", {
    description: "Suntory Ao is a world whisky blended from distillates made in Japan, Scotland, Ireland, Canada and the United States. The five-sided bottle reflects those five whisky-making regions.",
    story: "Suntory's blenders brought together malt and grain whiskies from five countries under one label. Ao shifts the focus from a single national style to the interplay of several traditions.",
    notes: ["Fruit and vanilla", "Pineapple and vanilla sit in the opening of Ao's official tasting profile.", "Spice and smoke", "Cinnamon, wood and a little smoke add a drier counterpoint."],
    serve: "Sample it neat in a tulip glass, then add ice or soda to find the balance you prefer.",
    food: "Try it with tandoori mushrooms, pepper chicken or smoked cheese.",
    pairings: ["tandoori mushrooms", "pepper chicken", "smoked cheese"],
    whyChoose: "One glass that deliberately crosses five whisky regions.",
    faq: ["Is Suntory Ao made only in Japan?", "No. The blend uses whiskies from five countries, including Japan.", "Why does the Ao bottle have five sides?", "Each side represents one of its five whisky-making regions."],
    finalVerdict: "Ao rewards anyone curious about what a five-country whisky blend can taste like.",
    metaDescription: "Discover Suntory Ao's five-country whisky blend, tasting notes and pairings. Compare city prices on BevOry.",
  }),
  kakubin: guide("Suntory Kakubin", "Whisky", {
    description: "Suntory Kakubin is a Japanese blended whisky first released in 1937. Malt from Yamazaki and Hakushu meets Chita grain whisky in a blend closely associated with Japan's highball culture.",
    story: "The nickname Kakubin refers to the angular bottle that made the whisky easy to recognise. Decades later, its crisp profile remains a natural fit for a tall glass of ice and soda.",
    notes: ["Bright nose", "Lemon, green apple and butter-cookie notes lead the official tasting profile.", "Soft palate", "Apple, popcorn and nutty tones give way to a dry finish."],
    serve: "Build a highball with plenty of ice and chilled soda, stirring gently to keep the fizz.",
    food: "Try karaage chicken, masala peanuts or grilled corn with lime.",
    pairings: ["karaage chicken", "masala peanuts", "grilled corn with lime"],
    whyChoose: "A historic Japanese blend with a clear purpose at the highball table.",
    faq: ["When was Kakubin introduced?", "Suntory introduced Kakubin in 1937.", "What is in Kakubin?", "Suntory blends malt from Yamazaki and Hakushu with grain whisky from Chita."],
    finalVerdict: "Kakubin is at its most convincing cold, long and sparkling.",
    metaDescription: "Explore Kakubin's 1937 Japanese blend, highball serve and tasting notes. Compare city prices on BevOry.",
  }),
  "knob-creek": guide("Knob Creek", "Whiskey", {
    description: "Knob Creek is a Kentucky bourbon in the Jim Beam family, known for a robust, oak-forward style. Its full-flavoured approach contrasts with lighter American whiskey blends.",
    story: "Master distiller Booker Noe introduced Knob Creek in 1992 as part of a return to richly flavoured bourbon. The brand remains tied to Beam's Kentucky distilling heritage.",
    notes: ["Toasted oak", "Charred-barrel notes frame the bourbon's vanilla sweetness.", "Sweet spice", "A warming spice note gives the finish its weight."],
    serve: "Pour a small measure over one large ice cube or use it in a bourbon Old Fashioned.",
    food: "Try it with mutton seekh, barbecue corn or pecan pie.",
    pairings: ["mutton seekh", "barbecue corn", "pecan pie"],
    whyChoose: "A bourbon built around barrel flavour and a substantial finish.",
    faq: ["Who created Knob Creek?", "Booker Noe introduced Knob Creek for the Jim Beam family in 1992.", "What kind of whiskey is Knob Creek?", "It is a Kentucky straight bourbon brand."],
    finalVerdict: "Knob Creek is a confident pick when lighter bourbons feel too delicate.",
    metaDescription: "Explore Knob Creek bourbon, its Kentucky roots, oak-led taste and food pairings. Compare city prices on BevOry.",
  }),
  "basil-haydens": guide("Basil Hayden", "Whiskey", {
    description: "Basil Hayden is a Kentucky straight bourbon made in the Jim Beam family. It leans on a higher-rye mash bill for a light, spicy take on bourbon.",
    story: "Booker Noe launched Basil Hayden in 1992 and named it for an early Kentucky distiller associated with rye-forward bourbon. Its place in the Beam range is more delicate than Knob Creek's barrel-led style.",
    notes: ["Spiced aroma", "Rye-led spice meets a gentler bourbon sweetness.", "Light finish", "The finish stays relatively soft rather than heavily oaked."],
    serve: "Use a rocks glass with a single cube or mix a whiskey highball with cold soda.",
    food: "Pair with pepper paneer, roasted almonds or chicken sliders.",
    pairings: ["pepper paneer", "roasted almonds", "chicken sliders"],
    whyChoose: "A rye-tinged bourbon for drinkers who favour a lighter texture.",
    faq: ["Is Basil Hayden a rye whiskey?", "No. It is a Kentucky straight bourbon with rye in its mash bill.", "Who introduced Basil Hayden?", "Booker Noe introduced the brand in 1992."],
    finalVerdict: "Basil Hayden keeps bourbon's spice without demanding a heavy pour.",
    metaDescription: "Discover Basil Hayden bourbon, its rye spice and lighter Kentucky style. Compare city prices on BevOry.",
  }),
  "gentleman-jack": guide("Gentleman Jack", "Whiskey", {
    description: "Gentleman Jack is a Tennessee whiskey made at the Jack Daniel Distillery in Lynchburg. It passes through sugar-maple charcoal twice, once before maturation and again afterwards.",
    story: "Introduced in 1988, Gentleman Jack turned an idea attributed to Jack Daniel into a distinct expression. The second charcoal-mellowing step is what separates it from Old No. 7.",
    notes: ["Vanilla and caramel", "The whiskey's soft sweetness brings vanilla and caramel forward.", "Fruit and almond", "Apple-like fruit and a gentle nutty finish follow the sweetness."],
    serve: "Try it neat in a small glass or over a large cube; a simple ginger highball also works.",
    food: "Set it beside tandoori chicken, roasted almonds or apple tart.",
    pairings: ["tandoori chicken", "roasted almonds", "apple tart"],
    whyChoose: "The twice-mellowed alternative to Jack Daniel's familiar black label.",
    faq: ["How is Gentleman Jack different from Old No. 7?", "Gentleman Jack is charcoal-mellowed both before and after barrel ageing.", "Where is Gentleman Jack made?", "It is made at the Jack Daniel Distillery in Lynchburg, Tennessee."],
    finalVerdict: "Gentleman Jack is a softer route into Tennessee whiskey's charcoal-mellowed character.",
    metaDescription: "Explore Gentleman Jack's double charcoal mellowing, tasting notes and pairings. Compare city prices on BevOry.",
  }),
  courvoisier: guide("Courvoisier", "Cognac", {
    description: "Courvoisier is a French Cognac house based in Jarnac. Its blends of grape-derived eaux-de-vie range from VS mixing cognac to older, more layered expressions.",
    story: "Félix Courvoisier established the house in Jarnac in 1828. Its connection with Napoleon III later made the imperial association part of the label's history, but the spirit remains rooted in the Cognac region.",
    notes: ["VS", "Fresh fruit and a lively oak note make the younger style cocktail-friendly.", "VSOP", "A longer-matured blend brings rounder fruit and spice."],
    serve: "Use VS in a Sidecar or sip VSOP from a tulip-shaped glass.",
    food: "Try it with chicken pâté, saffron kheer or aged cheddar.",
    pairings: ["chicken pâté", "saffron kheer", "aged cheddar"],
    whyChoose: "A Jarnac Cognac house with a wide bridge between cocktails and sipping.",
    faq: ["Where is Courvoisier from?", "Courvoisier is a Cognac house based in Jarnac, France.", "Is Courvoisier brandy?", "Yes. Cognac is grape brandy made under the Cognac appellation in France."],
    finalVerdict: "Courvoisier moves easily from a citrus cocktail to an after-dinner glass.",
    metaDescription: "Explore Courvoisier Cognac from Jarnac, its VS and VSOP styles and food pairings. Compare city prices on BevOry.",
  }),
  hornitos: guide("Hornitos", "Tequila", {
    description: "Hornitos is a tequila label founded by Don Francisco Javier Sauza in Jalisco, Mexico. Its range uses blue Weber agave and includes unaged and oak-rested expressions.",
    story: "Sauza launched Hornitos in 1950, marking Mexican Independence Day. The name points to the small ovens associated with cooking agave before fermentation and distillation.",
    notes: ["Plata", "Clear agave character and citrus keep the unaged tequila lively.", "Reposado", "Time in oak softens the agave edge with a gentler vanilla note."],
    serve: "Use Plata with lime in a Margarita; pour Reposado over ice for a slower drink.",
    food: "Try with tandoori prawns, fish tacos or grilled pineapple chaat.",
    pairings: ["tandoori prawns", "fish tacos", "grilled pineapple chaat"],
    whyChoose: "A long-running Jalisco tequila label with distinct blanco and rested styles.",
    faq: ["Who founded Hornitos?", "Don Francisco Javier Sauza introduced Hornitos in 1950.", "What is Hornitos made from?", "Hornitos tequila is made with blue Weber agave in Jalisco."],
    finalVerdict: "Hornitos gives agave drinkers a clear choice between bright Plata and mellow Reposado.",
    metaDescription: "Explore Hornitos tequila, its Sauza history, Plata and Reposado styles. Compare city prices on BevOry.",
  }),
  sauza: guide("Sauza", "Tequila", {
    description: "Sauza is a tequila house with roots in the town of Tequila, Jalisco. Its range includes clear and oak-rested spirits made from agave.",
    story: "Don Cenobio Sauza founded La Perseverancia distillery in 1873. The family name became one of the most recognisable on tequila bottles beyond Mexico.",
    notes: ["Blanco", "Agave and citrus lead the unaged style.", "Gold", "The gold expression is softer and sweeter in mixed drinks."],
    serve: "Use Blanco with fresh lime in a Margarita or Gold in a tall citrus mixer.",
    food: "Bring it to fish tacos, chilli paneer or corn chaat.",
    pairings: ["fish tacos", "chilli paneer", "corn chaat"],
    whyChoose: "A tequila name tied directly to Jalisco's nineteenth-century distilling history.",
    faq: ["Where did Sauza begin?", "Don Cenobio Sauza founded La Perseverancia in Tequila, Jalisco, in 1873.", "Is Sauza suitable for Margaritas?", "Sauza Blanco works well with lime and orange liqueur in a Margarita."],
    finalVerdict: "Sauza's bright agave style is most at home in direct, citrus-led serves.",
    metaDescription: "Discover Sauza tequila's Jalisco roots, agave style and Margarita ideas. Compare city prices on BevOry.",
  }),
  "tres-generaciones": guide("Tres Generaciones", "Tequila", {
    description: "Tres Generaciones is a tequila label named for three generations of the Sauza family. Its Jalisco range is made from blue Weber agave and includes Blanco, Reposado and Añejo.",
    story: "The label pays tribute to Don Cenobio, Don Eladio and Don Francisco Javier Sauza. Triple distillation is part of the house's approach to a polished agave spirit.",
    notes: ["Blanco", "Fresh agave and citrus keep the clear expression brisk.", "Reposado", "Oak brings a softer vanilla edge to the agave core."],
    serve: "Pour Blanco in a stemmed tequila glass or use Reposado with grapefruit and soda.",
    food: "Try it with shrimp aguachile, paneer tikka or charred corn.",
    pairings: ["shrimp aguachile", "paneer tikka", "charred corn"],
    whyChoose: "A Sauza-family tequila range with a distinctive triple-distilled identity.",
    faq: ["What does Tres Generaciones mean?", "The name honours three generations of the Sauza tequila family.", "What is it made from?", "The tequila range uses blue Weber agave from Jalisco."],
    finalVerdict: "Tres Generaciones offers a more polished, expression-led view of Sauza tequila.",
    metaDescription: "Explore Tres Generaciones tequila, Sauza family history and agave styles. Compare city prices on BevOry.",
  }),
  dusse: guide("D'USSÉ", "Cognac", {
    description: "D'USSÉ is a Cognac brand associated with the Château de Cognac in France. Its VSOP brings together grape eaux-de-vie matured in oak and distilled by the Charentaise double-distillation method.",
    story: "The brand draws its identity from the château's cellars and their particular ageing conditions. The wine is distilled slowly in copper stills, with lees contributing depth to the spirit.",
    notes: ["VSOP aroma", "Oak and warm spice frame the richer fruit notes.", "On the palate", "The fuller-bodied VSOP settles into a smoother finish after its initial intensity."],
    serve: "Sip VSOP neat in a tulip glass or make a Sidecar with lemon and orange liqueur.",
    food: "Try with galouti kebabs, dried apricots or dark chocolate.",
    pairings: ["galouti kebabs", "dried apricots", "dark chocolate"],
    whyChoose: "A Cognac whose château setting is linked to the way its eaux-de-vie mature.",
    faq: ["Where is D'USSÉ made?", "D'USSÉ is made in France's Cognac region, with ties to the Château de Cognac.", "How is D'USSÉ VSOP distilled?", "Its eaux-de-vie are double-distilled in copper stills using the Charentaise method."],
    finalVerdict: "D'USSÉ VSOP is a richer Cognac for a short pour or a sharp citrus cocktail.",
    metaDescription: "Discover D'USSÉ Cognac, Château de Cognac maturation and VSOP serving ideas. Compare city prices on BevOry.",
  }),
  cazadores: guide("Cazadores", "Tequila", {
    description: "Cazadores is a tequila from Arandas in the highlands of Jalisco, Mexico. It is made from blue Weber agave and includes Blanco, Reposado and aged expressions.",
    story: "Don José María Bañuelos began developing the tequila in 1922 in the agave-growing hills around Arandas. The deer on its label became the visual signature of a highland tequila with a local family story.",
    notes: ["Blanco", "Fresh agave and citrus keep the clear tequila direct.", "Reposado", "A short spell in oak adds gentle sweetness and spice."],
    serve: "Use Blanco in a Paloma with grapefruit; sip Reposado over ice.",
    food: "Try with tandoori fish, grilled corn or chorizo tacos.",
    pairings: ["tandoori fish", "grilled corn", "chorizo tacos"],
    whyChoose: "A Jalisco highland tequila with roots in Arandas rather than the town of Tequila.",
    faq: ["Where is Cazadores from?", "Its roots are in Arandas, in Jalisco's highland tequila region.", "What agave does Cazadores use?", "The tequila uses blue Weber agave."],
    finalVerdict: "Cazadores gives agave-and-citrus cocktails a distinctly highland base.",
    metaDescription: "Explore Cazadores tequila from Arandas, its agave styles and food pairings. Compare city prices on BevOry.",
  }),
  "st-germain": guide("St-Germain", "Liqueur", {
    description: "St-Germain is a French elderflower liqueur made from flowers gathered during a short spring harvest. Its floral sweetness is used in spritzes and other light cocktails.",
    story: "Third-generation distiller Robert J. Cooper launched St-Germain in 2007, taking the name from a Paris neighbourhood. The harvest window for fresh elderflower is only a few weeks long, giving the ingredient a clear seasonal story.",
    notes: ["Elderflower", "A fragrant floral opening defines the liqueur.", "Fruit", "Light pear and citrus impressions sit behind the blossom sweetness."],
    serve: "Add a small measure to dry sparkling wine and soda, then garnish with lemon.",
    food: "Serve beside tandoori prawns, strawberry tart or soft goat cheese.",
    pairings: ["tandoori prawns", "strawberry tart", "soft goat cheese"],
    whyChoose: "A floral liqueur that gives a simple spritz its own character.",
    faq: ["What is St-Germain made from?", "It is made with fresh elderflowers handpicked in spring.", "Who created St-Germain?", "Robert J. Cooper launched the liqueur in 2007."],
    finalVerdict: "St-Germain is most persuasive as a modest floral accent, not the whole drink.",
    metaDescription: "Explore St-Germain elderflower liqueur, its spring harvest and spritz pairings. Compare city prices on BevOry.",
  }),
  "noilly-prat": guide("Noilly Prat", "Vermouth", {
    description: "Noilly Prat is a French vermouth house based in Marseillan on the Mediterranean coast. Its range begins with dry white wine that is flavoured with herbs and spices.",
    story: "The Noilly family developed a vermouth business in the nineteenth century, later joined by Claude Prat. Marseillan became the house's home, where outdoor ageing and hand stirring remain part of the process for its dry styles.",
    notes: ["Original Dry", "Herbs and saline freshness give the dry vermouth its aperitif appeal.", "Ambré", "The amber expression brings a warmer, spiced profile."],
    serve: "Chill Original Dry with ice and a lemon peel or use it in a classic dry Martini.",
    food: "Pair with oysters, tandoori prawns or olive tapenade.",
    pairings: ["oysters", "tandoori prawns", "olive tapenade"],
    whyChoose: "A coastal French vermouth with a long connection to the dry Martini.",
    faq: ["Where is Noilly Prat made?", "The house is based in Marseillan in southern France.", "What is Noilly Prat?", "It is vermouth: wine aromatised with herbs and spices."],
    finalVerdict: "Noilly Prat is a crisp, herbal choice for an aperitif or a restrained Martini.",
    metaDescription: "Discover Noilly Prat vermouth from Marseillan, its dry style and aperitif pairings. Compare city prices on BevOry.",
  }),
  "santa-teresa": guide("Santa Teresa", "Rum", {
    description: "Santa Teresa is a Venezuelan rum house based at Hacienda Santa Teresa in the Aragua valleys. Its best-known 1796 expression uses a solera process for a dry, rounded aged rum.",
    story: "The hacienda dates to 1796 and remains linked to the Vollmer family. Its 1796 rum takes that founding year as its name, connecting the bottle to the estate rather than promising an age statement.",
    notes: ["Aged fruit", "Dried fruit and oak bring depth to the 1796 style.", "Dry finish", "The solera-aged rum finishes less sugary than many dessert-leaning rums."],
    serve: "Pour a small measure neat or over one clear cube; a rum Old Fashioned also suits it.",
    food: "Try with mutton seekh, caramelised plantain or dark chocolate.",
    pairings: ["mutton seekh", "caramelised plantain", "dark chocolate"],
    whyChoose: "A Venezuelan estate rum with a clearly documented solera tradition.",
    faq: ["Does 1796 mean the rum is 1796 years old?", "No. The number marks the founding year of Hacienda Santa Teresa.", "Where is Santa Teresa rum from?", "Its home is Hacienda Santa Teresa in Venezuela's Aragua valleys."],
    finalVerdict: "Santa Teresa 1796 brings a drier, oak-led alternative to sweetened rum serves.",
    metaDescription: "Explore Santa Teresa rum from Venezuela, its 1796 solera style and pairings. Compare city prices on BevOry.",
  }),
  "perrier-jouet": guide("Perrier-Jouët", "Champagne", {
    description: "Perrier-Jouët is a Champagne house in Épernay, France, with Chardonnay at the centre of its style. Its cuvées range from Grand Brut to the flower-bottle Belle Epoque.",
    story: "Pierre-Nicolas Perrier and Rose-Adélaïde Jouët founded the house in 1811. The family recognised the Côte des Blancs as a strong site for Chardonnay and acquired vineyards in Cramant, Avize and Chouilly.",
    notes: ["Grand Brut", "Orchard fruit and a floral edge sit over fine bubbles.", "Blanc de Blancs", "Chardonnay brings citrus, white fruit and a tauter finish."],
    serve: "Chill the Champagne and use a tulip glass so the fruit and bubbles have room to open.",
    food: "Serve with tandoori prawns, fresh oysters or a mild goat-cheese tart.",
    pairings: ["tandoori prawns", "fresh oysters", "goat-cheese tart"],
    whyChoose: "An Épernay house whose long Chardonnay focus shapes its lighter, floral style.",
    faq: ["Where is Perrier-Jouët based?", "The Champagne house was founded in Épernay, France.", "Which grape is central to its style?", "Chardonnay has long been a signature grape for the house."],
    finalVerdict: "Perrier-Jouët is a good place to look for Champagne with freshness and floral detail.",
    metaDescription: "Explore Perrier-Jouët Champagne, its Chardonnay focus and food pairings. Compare city prices on BevOry.",
  }),
  "grand-marnier": guide("Grand Marnier", "Liqueur", {
    description: "Grand Marnier is a French orange liqueur built on Cognac and bitter-orange essence. Cordon Rouge is its defining expression, equally useful in cocktails and desserts.",
    story: "Louis-Alexandre Marnier Lapostolle created Cordon Rouge in 1880 by bringing Cognac and orange liqueur together. The red ribbon around the bottle still refers to that original house style.",
    notes: ["Bitter orange", "Orange peel gives the liqueur a bright, aromatic edge.", "Cognac depth", "Toffee and nut-like tones from the brandy base balance the citrus."],
    serve: "Use a small measure in a Margarita or Sidecar, or pour it over ice after dinner.",
    food: "Try with orange cake, dark chocolate or baked malpua.",
    pairings: ["orange cake", "dark chocolate", "baked malpua"],
    whyChoose: "Cognac weight makes this orange liqueur more than a simple citrus sweetener.",
    faq: ["Is Grand Marnier a Cognac?", "No. It is a liqueur that combines Cognac with bitter-orange essence.", "When was Cordon Rouge created?", "Louis-Alexandre Marnier Lapostolle created it in 1880."],
    finalVerdict: "Grand Marnier adds orange lift and brandy depth in one small pour.",
    metaDescription: "Discover Grand Marnier's Cognac-and-orange style, cocktails and dessert pairings. Compare city prices on BevOry.",
  }),
  frangelico: guide("Frangelico", "Liqueur", {
    description: "Frangelico is an Italian hazelnut liqueur with roots in Piedmont. Hazelnut leads the flavour, supported by vanilla and chocolate notes.",
    story: "The brand takes its name from a story about a friar in Piedmont, and its bottle is shaped like a monk's habit. Its flavour is tied to the region's long association with hazelnuts.",
    notes: ["Hazelnut", "Roasted nut aroma is the first thing you notice.", "Dessert notes", "Vanilla and dark chocolate round out the sweetness."],
    serve: "Pour a small measure over ice or add it to an espresso for an after-dinner drink.",
    food: "Pair with tiramisu, dark chocolate or cardamom kulfi.",
    pairings: ["tiramisu", "dark chocolate", "cardamom kulfi"],
    whyChoose: "A hazelnut-led liqueur that earns its place beside coffee and dessert.",
    faq: ["What does Frangelico taste like?", "Hazelnut dominates, with vanilla and chocolate in the background.", "Where is Frangelico from?", "It is an Italian liqueur associated with Piedmont."],
    finalVerdict: "Frangelico is best treated as a dessert accent, especially with coffee.",
    metaDescription: "Explore Frangelico hazelnut liqueur from Italy, its dessert pairings and serves. Compare city prices on BevOry.",
  }),
  casamigos: guide("Casamigos", "Tequila", {
    description: "Casamigos is a Jalisco tequila label made from blue Weber agave. Its range includes Blanco, Reposado and Añejo, each offering a different balance of agave and oak.",
    story: "The brand began as a project between friends who wanted a tequila they could sip without salt or lime. Its agave is roasted in a process that includes traditional brick ovens; the rested expressions spend time in American white oak.",
    notes: ["Blanco", "The unaged style keeps agave and citrus at the front.", "Reposado", "Oak ageing adds a softer vanilla note to the agave base."],
    serve: "Use Blanco with lime in a Margarita; pour Reposado in a rocks glass over ice.",
    food: "Try with fish tacos, paneer tikka or smoky grilled corn.",
    pairings: ["fish tacos", "paneer tikka", "smoky grilled corn"],
    whyChoose: "A Jalisco tequila range that shows how oak changes a familiar agave base.",
    faq: ["What agave does Casamigos use?", "Its tequilas are made from blue Weber agave grown in Jalisco.", "Is Casamigos Reposado aged?", "Yes. It spends at least six months in American white oak barrels."],
    finalVerdict: "Casamigos makes the Blanco-to-Reposado comparison easy to taste.",
    metaDescription: "Explore Casamigos tequila from Jalisco, Blanco and Reposado styles and pairings. Compare city prices on BevOry.",
  }),
  bumbu: guide("Bumbu", "Rum", {
    description: "Bumbu is a Caribbean rum range with its Original made in Barbados and XO made in Panama. The Original is a flavoured rum spirit, while XO is an oak-aged rum finished in sherry casks.",
    story: "Bumbu's Barbados connection runs through the historic West Indies Rum Company distillery. The range deliberately moves between a sweeter, spiced Original and the darker, drier XO from Panama.",
    notes: ["Original", "Sweet fruit and spice shape the flavoured Barbados expression.", "XO", "Oak, dried fruit and sherry-cask notes give the Panamanian rum a more mature profile."],
    serve: "Mix Original with ginger beer; give XO a small neat pour or one large cube.",
    food: "Try with jerk chicken, grilled pineapple or dark chocolate.",
    pairings: ["jerk chicken", "grilled pineapple", "dark chocolate"],
    whyChoose: "Two clearly different Caribbean expressions under one rum label.",
    faq: ["Is Bumbu Original the same as Bumbu XO?", "No. Original is a flavoured Barbados rum spirit; XO is a Panamanian aged rum.", "Where is Bumbu XO made?", "Bumbu XO is distilled in Panama."],
    finalVerdict: "Bumbu works best when you choose Original for mixing and XO for a slower sip.",
    metaDescription: "Compare Bumbu Original from Barbados with Panama-made XO, plus serving ideas and city prices on BevOry.",
  }),
  "chairmans-reserve": guide("Chairman's Reserve", "Rum", {
    description: "Chairman's Reserve is a Saint Lucian rum made by St. Lucia Distillers. Its blends draw on both pot-still and Coffey-still spirit, giving the brand a wider range of textures than a single-still rum.",
    story: "Chairman Laurie Barnard pushed the distillery towards pot stills, varied casks and a broader palette for blending in the 1990s. The name honours his role in changing the direction of Saint Lucian rum.",
    notes: ["Original", "Raisin, honey and vanilla open the house blend.", "After the first sip", "Grilled tropical fruit and soft spice carry the finish."],
    serve: "Sip the Original over one cube or stir it into a rum Old Fashioned.",
    food: "Try with mutton seekh, grilled pineapple or walnut cake.",
    pairings: ["mutton seekh", "grilled pineapple", "walnut cake"],
    whyChoose: "The contrast of pot and column stills is central to its Saint Lucian character.",
    faq: ["Where is Chairman's Reserve made?", "St. Lucia Distillers makes it in Saint Lucia.", "What stills are used?", "The house blends pot-still and Coffey-still rum."],
    finalVerdict: "Chairman's Reserve offers the depth of a blended island rum without losing its fruit.",
    metaDescription: "Explore Chairman's Reserve rum from Saint Lucia, its stills, oak and pairings. Compare city prices on BevOry.",
  }),
  "dead-mans-fingers": guide("Dead Man's Fingers", "Rum", {
    description: "Dead Man's Fingers is a spiced-rum label that began at the Rum and Crab Shack in St Ives, Cornwall. The range now extends beyond the original spiced bottle into other flavoured rums.",
    story: "The name comes from the finger-like gills inside a crab, not a tale of pirates. Its original flavour idea borrowed from the shack's dessert menu, including Cornish saffron cake and Pedro Ximénez ice cream.",
    notes: ["Original spice", "Nutmeg and vanilla lead the original rum's warm profile.", "Orange edge", "A faint orange note keeps the spiced finish from feeling flat."],
    serve: "Build a spiced rum and ginger beer over ice with a squeeze of lime.",
    food: "Serve with chilli prawns, grilled pineapple or saffron cake.",
    pairings: ["chilli prawns", "grilled pineapple", "saffron cake"],
    whyChoose: "A Cornwall-born spiced rum with a name drawn from the crab shack itself.",
    faq: ["Where did Dead Man's Fingers start?", "It began at the Rum and Crab Shack in St Ives, Cornwall.", "Why is it called Dead Man's Fingers?", "The name refers to the gills found inside a crab."],
    finalVerdict: "The original rum is a lively mixer for ginger, citrus and spice-heavy food.",
    metaDescription: "Discover Dead Man's Fingers rum, its St Ives origin and spiced serves. Compare city prices on BevOry.",
  }),
  pussers: guide("Pusser's", "Rum", {
    description: "Pusser's is a navy-style rum whose name comes from the ship's purser. The brand draws on the Royal Navy's historical rum blend and is closely associated with the Painkiller cocktail.",
    story: "Charles Tobias brought the naval blend into commercial bottling after the Royal Navy ended its daily rum ration. The brand established a home in the British Virgin Islands while keeping the fleet's dark-rum story at its centre.",
    notes: ["Navy rum", "Deep molasses and dried-fruit notes suit a robust dark-rum serve.", "In cocktails", "The rum keeps its weight against pineapple, orange and coconut."],
    serve: "Make a Painkiller with pineapple, orange and coconut, finishing with grated nutmeg.",
    food: "Try with jerk chicken, pepper prawns or banana fritters.",
    pairings: ["jerk chicken", "pepper prawns", "banana fritters"],
    whyChoose: "A dark-rum label with a direct link to the Royal Navy ration tradition.",
    faq: ["What does Pusser mean?", "It is a sailor's term for the ship's purser, who handled stores including rum.", "Which cocktail uses Pusser's?", "The Painkiller combines the rum with pineapple, orange, coconut and nutmeg."],
    finalVerdict: "Pusser's has the depth to stand up to a fruit-and-coconut cocktail.",
    metaDescription: "Explore Pusser's navy rum, Royal Navy history and Painkiller pairings. Compare city prices on BevOry.",
  }),
  "sailor-jerry": guide("Sailor Jerry", "Rum", {
    description: "Sailor Jerry is a spiced spirit made with a blend of Caribbean rums and natural spices. It takes its name from Norman 'Sailor Jerry' Collins, the American tattoo artist.",
    story: "Collins became known for his old-school tattoo work in Honolulu, especially among sailors. The rum label uses that visual language to honour his work rather than claiming the artist made the drink himself.",
    notes: ["Vanilla and almond", "The spiced blend opens with sweet nut and vanilla notes.", "Cassia and cinnamon", "Warm spice gives the finish its recognisable kick."],
    serve: "Mix with cola and lime or build a spiced rum Old Fashioned over ice.",
    food: "Try with barbecue wings, tandoori mushrooms or pecan pie.",
    pairings: ["barbecue wings", "tandoori mushrooms", "pecan pie"],
    whyChoose: "A cocktail-ready spiced rum with a real tattoo-history namesake.",
    faq: ["Who was Sailor Jerry?", "Norman Collins was an American tattoo artist known for his work in Honolulu.", "What flavours are in the rum?", "The brand describes vanilla, almond, cassia and cinnamon in its spiced profile."],
    finalVerdict: "Sailor Jerry brings enough cinnamon-and-vanilla character for a straightforward long drink.",
    metaDescription: "Explore Sailor Jerry spiced rum, tattoo heritage and cocktail ideas. Compare city prices on BevOry.",
  }),
  "michelob-ultra": guide("Michelob Ultra", "Beer", {
    description: "Michelob Ultra is a light American lager from Anheuser-Busch. Its clean, low-weight profile is built for a cold, easy-drinking beer serve.",
    story: "The Michelob name belongs to the Anheuser-Busch family of American beers. Ultra emerged as the lighter branch of that range and built its identity around a crisp lager style.",
    notes: ["Light malt", "A mild grain note keeps the beer gentle rather than rich.", "Clean finish", "The short, crisp finish makes the lager refreshing when cold."],
    serve: "Serve well chilled in a clean lager glass; avoid freezing the bottle.",
    food: "Try with lime chicken skewers, chilli paneer or salted popcorn.",
    pairings: ["lime chicken skewers", "chilli paneer", "salted popcorn"],
    whyChoose: "A lighter lager when heavy malt and bitter hops are not the point.",
    faq: ["What type of beer is Michelob Ultra?", "It is a light American lager.", "Who makes Michelob Ultra?", "Michelob Ultra is part of Anheuser-Busch's beer portfolio."],
    finalVerdict: "Michelob Ultra is most convincing cold, simple and alongside salty food.",
    metaDescription: "Explore Michelob Ultra light lager, its crisp style and food pairings. Compare city prices on BevOry.",
  }),
  "goose-island": guide("Goose Island", "Beer", {
    description: "Goose Island is a Chicago brewery known for ales and barrel-aged beer. Its range runs from the early Honker's Ale to Bourbon County Stout.",
    story: "John Hall opened the Clybourn brewpub in 1988, where Honker's Ale was the first beer brewed. His son Greg later used bourbon barrels for the brewery's thousandth batch, leading to Bourbon County Stout.",
    notes: ["Honker's Ale", "Floral hops and balanced malt give the English-style ale an easy finish.", "Bourbon County", "The stout's barrel programme brings richer roasted malt and oak-driven depth."],
    serve: "Pour Honker's cool into a pint glass; let a Bourbon County stout warm slightly in a smaller glass.",
    food: "Try the ale with chicken sliders and the stout with chocolate brownie or smoked brisket.",
    pairings: ["chicken sliders", "chocolate brownie", "smoked brisket"],
    whyChoose: "A Chicago brewery whose history spans pub ale and bourbon-barrel experimentation.",
    faq: ["Where did Goose Island start?", "It began at John Hall's Clybourn brewpub in Chicago in 1988.", "What is Bourbon County Stout?", "It is Goose Island's bourbon-barrel-aged stout line."],
    finalVerdict: "Goose Island gives beer drinkers a broad step from easy ale to barrel-aged stout.",
    metaDescription: "Explore Goose Island beer from Chicago, Honker's Ale and Bourbon County Stout. Compare city prices on BevOry.",
  }),
};
