import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_23 = [
  ["ketel-one", "Ketel One", "Netherlands", "Vodka", "bb7d19f68c16f3b27c4aa002"],
  ["kirin", "Kirin", "Japan", "Beer", "91c16b8f0432317cbc43ec09"],
  ["kraken", "Kraken", "Trinidad and Tobago", "Spiced Rum", "686d22d695e2c21166a89498"],
  ["kronenbourg-1664", "Kronenbourg 1664", "France", "Beer", "c900ecb9db9e1f4fb397fe44"],
  ["kumeu-river", "Kumeu River", "New Zealand", "Wine", "adc142751071c8c865cf23db"],
  ["kwv", "KWV", "South Africa", "Wine and Brandy", "08a54396c47a27b8acb7b827"],
  ["la-trappe", "La Trappe", "Netherlands", "Trappist Beer", "0e6267c391c2cf3fcaf39536"],
  ["la-vieille-ferme", "La Vieille Ferme", "France", "Wine", "b646396991d699463ac23ef2"],
  ["laurent-perrier", "Laurent-Perrier", "France", "Champagne", "8f551bfbc3c0fa9f4c60593b"],
  ["leffe", "Leffe", "Belgium", "Abbey Beer", "24552b92e17bbc7e7f19e5ba"],
  ["licor-43", "Licor 43", "Spain", "Liqueur", "a0254910e554c73fb09dd613"],
  ["london-no-1", "The London No. 1", "United Kingdom", "Gin", "b2c1cc8891044e4627a0a7e7"],
  ["longitude-77", "Longitude 77", "India", "Single Malt Whisky", "729aa671ec35afae09102871"],
  ["louis-roederer", "Louis Roederer", "France", "Champagne", "b37dcb8003ff8c3fb12458eb"],
  ["lustau", "Lustau", "Spain", "Sherry", "5775970ad44635635d9d82c9"],
  ["maestro-dobel", "Maestro Dobel", "Mexico", "Tequila", "12823cd28f1521c367582d3e"],
  ["makers-mark", "Maker's Mark", "United States", "Bourbon", "126a04d5248f480ca9408d32"],
  ["malfy", "Malfy", "Italy", "Gin", "a1f706839e10d4201fca741b"],
  ["masi", "Masi", "Italy", "Wine", "e65e6aa56c0ba68dce7c1bdc"],
  ["masseto", "Masseto", "Italy", "Wine", "fd8da0f82914c56f4391c90f"],
  ["mateus", "Mateus", "Portugal", "Rosé Wine", "1957b9981fc9cfa67abff7eb"],
  ["mcguigan", "McGuigan", "Australia", "Wine", "5ec51d77db301c973a023074"],
  ["mermaid", "Mermaid", "United Kingdom", "Gin", "0fbccedd61528383fcf15a83"],
  ["metaxa", "Metaxa", "Greece", "Spirit", "67ff2317b2b4305e59bfc94f"],
  ["meukow", "Meukow", "France", "Cognac", "5d873e62e690c5483552abfc"],
  ["midori", "Midori", "Japan", "Melon Liqueur", "1ce10b381ee4798b8c630429"],
  ["monkey-47", "Monkey 47", "Germany", "Gin", "4c4c7c949b12bb2a928c83d8"],
  ["montenegro", "Amaro Montenegro", "Italy", "Amaro", "f830720f3e3bed7436b244a9"],
  ["kati-patang", "Kati Patang", "India", "Beer", "8f7212d5f0482b8de5f4e7e4"],
  ["kamet", "Kamet", "India", "Single Malt Whisky", "c038bd25f2e75023010f736c"],
] as const;

// Editorial research only: never printed in the public brand fields.
export const BRAND_SOURCES_BATCH_23: Record<string, string[]> = {
  "ketel-one": ["https://www.ketelone.com/our-story"],
  kirin: ["https://www.kirinholdings.com/en/company/history/1990_1999/", "https://museum.kirinholdings.com/history/theme/b14_03e.html"],
  kraken: ["https://www.krakenrum.com/products/original/", "https://www.abc.virginia.gov/products/rum/kraken-black-spiced-rum?productSize=1"],
  "kronenbourg-1664": ["https://www.1664blanc.com/en/1664-heritage/"],
  "kumeu-river": ["https://kumeuriver.co.nz/pages/people-place-story", "https://kumeuriver.co.nz/products/kumeu-river-mates-vineyard-chardonnay"],
  kwv: ["https://kwv.co.za/our-company/our-history/", "https://kwv.co.za/our-company/our-brands/kwv-brandy/"],
  "la-trappe": ["https://www.koningshoeven.nl/de-abdij/brouwerij"],
  "la-vieille-ferme": ["https://m.familleperrin.com/12DC5HXR3N?l=fr"],
  "laurent-perrier": ["https://www.laurent-perrier.com/fr/la-maison/notre-histoire/"],
  leffe: ["https://www.leffe.com/history", "https://www.leffe.com/"],
  "licor-43": ["https://licor43.com/faqs/", "https://licor43.com/cocktails/asiatico-43/"],
  "london-no-1": ["https://www.gonzalezbyass.com/en/wineries-brands/london-no1"],
  "longitude-77": ["https://www.pernod-ricard.com/en/brand/longitude-77"],
  "louis-roederer": ["https://app.louis-roederer.com/the-wines/collection", "https://www.louis-roederer.com/sites/all/themes/roederer/files/LR_DP%20Collection%20246_EN.pdf"],
  lustau: ["https://lustau.es/sobre-bodegas-lustau/"],
  "maestro-dobel": ["https://www.maestrodobel.com/pages/tequila-process", "https://maestrodobel.com.mx/"],
  "makers-mark": ["https://www.makersmark.com/story"],
  malfy: ["https://www.malfygin.com/en/about-us/", "https://www.malfygin.com/en-us/our-gins/originale/"],
  masi: ["https://www.masi.it/", "https://www.masi.it/en/masi-wine-experience/visit-our-sites/masi-winery-valpolicella-wine-tour/"],
  masseto: ["https://www.masseto.com/en/the-place/", "https://www.masseto.com/en/wine/"],
  mateus: ["https://www.mateusrose.us/our-story/", "https://sogrape.com/pt/article/80-anos-sogrape"],
  mcguigan: ["https://www.mcguiganwines.com.au/winemaking.html"],
  mermaid: ["https://isleofwightdistillery.com/pages/mermaid-gin"],
  metaxa: ["https://www.metaxa.com/en-au", "https://www.metaxa.com/en-au/products/metaxa-private-reserve"],
  meukow: ["https://meukowcognac.com/history/"],
  midori: ["https://www.midori-world.com/product", "https://www.suntory.co.jp/wnb/essay/162.html"],
  "monkey-47": ["https://monkey47.com/the-schwarzwald-dna"],
  montenegro: ["https://www.amaromontenegro.eu/la-storia", "https://montenegro.elementalinc.com/our-story/"],
  "kati-patang": ["https://katipatang.com/about-us", "https://katipatang.com/blog/how-kati-patang-brews-indian-craft-beer-ingredients-brewing-process-and-craftsmanship"],
  kamet: ["https://www.highroadspirits.com/kamet-single-malt", "https://www.piccadily.com/sites/default/files/2025-06/PAIL_ANNUAL_REPORT_2023-24.pdf"],
};

// The other 11 rows already have a stored logo; these only fill verified blank slots.
export const BRAND_LOGOS_BATCH_23: Record<string, string> = {
  kraken: "https://i0.wp.com/www.krakenrum.com/wp-content/uploads/2021/09/Kraken-Spiced-Rum-Logo-1.png?fit=960%2C680&ssl=1",
  kwv: "https://09ec060a.delivery.rocketcdn.me/wp-content/uploads/elementor/thumbs/AN00197-KWV-CORPORATE-website-2021-FA_logo-white-pjh3rr7knofctmq1rn4azrwg4h391cqp2mvnyeiku8.png",
  "la-trappe": "https://uk.latrappetrappist.com/etc.clientlibs/latrappe/clientlibs/latrappe.app/resources/img/logo-la-trappe-trappist--beige.svg",
  "la-vieille-ferme": "https://www.lavieilleferme.com/wp-content/themes/tete-chercheuse/assets/images/logo.png",
  "louis-roederer": "https://www.louis-roederer.com/sites/all/themes/roederer/img/ROEDERER_logotype.svg",
  lustau: "https://lustau.es/wp-content/uploads/2020/09/logo-lustau-gris.svg",
  "maestro-dobel": "https://www.maestrodobel.com/cdn/shop/files/dobel-logo-white.svg?v=1746629111&width=600",
  masseto: "https://www.masseto.com/static/media/masseto_name_logo.svg",
  mateus: "https://www.datocms-assets.com/33016/1779794982-logo_white.svg",
  mcguigan: "https://www.mcguiganwines.com.au/on/demandware.static/-/Sites/default/dw69e984d0/McGuigan-storefront-configs/McGuigan%20Master%20Logo_horizontal_700px-02.svg",
  midori: "https://www.midori-world.com/modules/custom/bsi_header/img/logo.png",
  montenegro: "https://www.amaromontenegro.com/static/images/logo-large.png",
};

export const BRAND_CONTENT_BATCH_23: Record<string, BrandPublicContent> = {
  "ketel-one": {
    description: "Ketel One is a Dutch vodka made by the Nolet family in Schiedam. Copper pot distillation is part of a process that also uses modern distilling methods.",
    story: "The Nolets created Ketel One in 1983 after generations of distilling in Schiedam. The label depicts Distilleerketel No. 1, the copper still that gave the vodka its name.",
    tastingNotes: [{ title: "Grain", description: "A clean grain note gives way to faint citrus." }, { title: "Texture", description: "The finish is smooth and dry rather than sweet or flavoured." }],
    howToEnjoy: [{ subheading: "Martini", description: "Stir with dry vermouth and serve in a chilled glass." }, { subheading: "With food", description: "Smoked salmon, cucumber chaat and salted almonds keep the palate brisk." }],
    pairingIdeas: [{ title: "Cold plates", items: ["smoked salmon", "cucumber chaat", "salted almonds", "pickled herring"] }],
    whyChoose: "Its Schiedam pot-still heritage gives a clear point of difference in a quiet vodka.",
    faqs: [{ question: "Where is Ketel One made?", answer: "In Schiedam, the Netherlands." }, { question: "Who makes Ketel One?", answer: "The Nolet family distilling business." }],
    finalVerdict: "Ketel One earns its place in a dry Martini or a small chilled pour.",
    metaTitle: "Ketel One Vodka Guide | BevOry", metaDescription: "Explore Ketel One's Schiedam pot-still story, vodka style and pairings. Check city prices on BevOry.",
  },
  kirin: {
    description: "Kirin is a Japanese brewer whose Ichiban beer uses the first wort drawn from the mash. That first-press method gives the lager its malt-led identity.",
    story: "Kirin launched Ichiban in Japan in 1990. The name means first press, making the brewing step unusually visible to the drinker.",
    tastingNotes: [{ title: "First wort", description: "Clean malt sweetness shapes the middle of the sip." }, { title: "Finish", description: "A light hop bite keeps the lager crisp." }],
    howToEnjoy: [{ subheading: "Cold pour", description: "Serve Ichiban chilled in a narrow beer glass." }, { subheading: "Supper", description: "Yakitori, prawn tempura and chilli paneer sit well beside its mild malt." }],
    pairingIdeas: [{ title: "Japanese lager food", items: ["yakitori", "prawn tempura", "chilli paneer", "salted edamame"] }],
    whyChoose: "Ichiban turns a specific brewing decision into an easy-drinking lager.",
    faqs: [{ question: "What does Kirin Ichiban mean?", answer: "Ichiban refers to the first wort used in the beer's brewing process." }, { question: "When did Kirin Ichiban launch?", answer: "Kirin introduced it in Japan in 1990." }],
    finalVerdict: "The beer is at its best cold, with a salty or fried plate nearby.",
    metaTitle: "Kirin Ichiban Beer Guide | BevOry", metaDescription: "Meet Kirin Ichiban's first-press brewing style and food-friendly lager. Check city prices on BevOry.",
  },
  kraken: {
    description: "Kraken Original is a black spiced rum made from Caribbean rum associated with Trinidad and Tobago. Its dark colour and cinnamon-vanilla spice make it a cocktail-forward bottle.",
    story: "The label borrows its name and double-handled bottle from sea-monster folklore. The mythology is packaging; in the glass, the rum's spice and caramel are the useful facts.",
    tastingNotes: [{ title: "Nose", description: "Caramel and toffee rise ahead of the spice." }, { title: "Palate", description: "Cinnamon, vanilla and nutmeg leave a long warming finish." }],
    howToEnjoy: [{ subheading: "Dark and cold", description: "Build over ice with ginger beer and lime." }, { subheading: "Something sweet", description: "Try it with dark chocolate, banana fritters or spiced nuts." }],
    pairingIdeas: [{ title: "Spice-led bites", items: ["dark chocolate", "banana fritters", "spiced nuts", "grilled pineapple"] }],
    whyChoose: "Kraken's cinnamon-heavy profile gives a simple ginger highball real presence.",
    faqs: [{ question: "What kind of rum is Kraken Original?", answer: "A Caribbean black spiced rum." }, { question: "What flavours stand out?", answer: "Caramel, cinnamon, vanilla and nutmeg." }],
    finalVerdict: "Ginger beer and lime keep the sweetness and spice in balance.",
    metaTitle: "Kraken Spiced Rum Guide | BevOry", metaDescription: "Discover Kraken's black spiced rum, cinnamon notes and cocktail ideas. Check city prices on BevOry.",
  },
  "kronenbourg-1664": {
    description: "Kronenbourg 1664 is a French lager tied to Strasbourg brewing history. Its pale lager uses Alsatian Strisselspalt hops, while 1664 Blanc is a separate wheat-beer expression.",
    story: "Jerome Hatt established a brewery in Strasbourg in 1664. The 1664 name later became the label's link back to that Alsatian origin.",
    tastingNotes: [{ title: "Lager", description: "Pale malt and a soft herbal hop note keep the beer balanced." }, { title: "Blanc", description: "The wheat-beer expression is fruitier and softer than the lager." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the lager cold into a clean pilsner glass." }, { subheading: "With snacks", description: "Onion pakora, grilled chicken and salted pretzels fit the dry finish." }],
    pairingIdeas: [{ title: "Strasbourg and snacks", items: ["onion pakora", "grilled chicken", "salted pretzels", "fried fish"] }],
    whyChoose: "The lager's mild Alsatian hop note keeps it crisp beside fried food.",
    faqs: [{ question: "Why is it called 1664?", answer: "The date refers to Jerome Hatt's Strasbourg brewing origins." }, { question: "Is 1664 Blanc the same as the lager?", answer: "No. Blanc is the brand's wheat-beer expression." }],
    finalVerdict: "Take the lager for a clean, gently herbal pour; Blanc goes a softer route.",
    metaTitle: "Kronenbourg 1664 Beer Guide | BevOry", metaDescription: "Explore 1664's Strasbourg roots, pale lager and Blanc wheat beer. Check city prices on BevOry.",
  },
  "kumeu-river": {
    description: "Kumeu River is a family winery near Auckland, New Zealand, centred on Chardonnay. The Brajkovich family makes both estate and single-vineyard wines in a restrained, Burgundy-influenced style.",
    story: "Mick, Katé and Maté Brajkovich bought the Kumeu vineyard in 1944 after moving from Croatia. Michael Brajkovich later became New Zealand's first Master of Wine and helped shape its Chardonnay direction.",
    tastingNotes: [{ title: "Estate Chardonnay", description: "Stone fruit and citrus sit over a measured oak texture." }, { title: "Single vineyards", description: "Individual sites can bring more mineral tension or a fuller orchard-fruit palate." }],
    howToEnjoy: [{ subheading: "White-wine glass", description: "Serve lightly chilled, not ice-cold, to let the texture show." }, { subheading: "Dinner", description: "Tandoori fish, roast chicken and mushroom risotto suit the Chardonnay." }],
    pairingIdeas: [{ title: "Chardonnay table", items: ["tandoori fish", "roast chicken", "mushroom risotto", "grilled prawns"] }],
    whyChoose: "Few New Zealand Chardonnay stories are as closely tied to one family and its vineyards.",
    faqs: [{ question: "Where is Kumeu River?", answer: "Near Auckland on New Zealand's North Island." }, { question: "Which grape is it known for?", answer: "Chardonnay." }],
    finalVerdict: "A modestly chilled glass rewards attention to the wine's texture, not just its fruit.",
    metaTitle: "Kumeu River Chardonnay Guide | BevOry", metaDescription: "Explore the Brajkovich family's New Zealand Chardonnay and food pairings. Check city prices on BevOry.",
  },
  kwv: {
    description: "KWV is a South African wine and brandy producer based in Paarl. Its range runs from Roodeberg wines to oak-aged brandies made within the country's long distilling tradition.",
    story: "Wine farmers founded KWV as a cooperative in 1918. Roodeberg arrived in 1949, while KWV's brandy cellars remained part of its Paarl identity.",
    tastingNotes: [{ title: "Roodeberg reds", description: "Dark fruit and a measured oak note give the blends a dinner-ready shape." }, { title: "KWV brandy", description: "Dried fruit, honey and wood spice mark the house's aged brandies." }],
    howToEnjoy: [{ subheading: "Two serves", description: "Pour red wine slightly cool; sip aged brandy in a small tulip glass." }, { subheading: "At the table", description: "Mutton rogan josh suits the reds; dark chocolate works with brandy." }],
    pairingIdeas: [{ title: "Paarl pairings", items: ["mutton rogan josh", "grilled lamb", "dark chocolate", "roasted almonds"] }],
    whyChoose: "KWV is a useful doorway into both South African wine and brandy.",
    faqs: [{ question: "What does KWV make?", answer: "Wine and brandy, including Roodeberg wine and KWV brandy." }, { question: "Where is KWV based?", answer: "In Paarl, South Africa." }],
    finalVerdict: "Choose the wine for dinner and the brandy for the slower glass afterward.",
    metaTitle: "KWV Wine and Brandy Guide | BevOry", metaDescription: "Discover KWV's Paarl wines, aged brandies and pairing ideas. Check city prices on BevOry.",
  },
  "la-trappe": {
    description: "La Trappe is Trappist beer brewed at Koningshoeven Abbey near Tilburg in the Netherlands. The range moves from blond ales to darker Dubbel and Quadrupel styles.",
    story: "The abbey has brewed its own beer since 1884. Its monks' brewery makes La Trappe on the monastic grounds rather than borrowing an abbey name as decoration.",
    tastingNotes: [{ title: "Dubbel", description: "Dark malt brings caramel and dried-fruit warmth." }, { title: "Quadrupel", description: "A fuller body carries deeper fruit and spice." }],
    howToEnjoy: [{ subheading: "Stemmed glass", description: "Pour slowly into a chalice-shaped glass and leave room for the head." }, { subheading: "Hearty food", description: "Mutton stew, mushroom pie and aged Gouda suit the darker beers." }],
    pairingIdeas: [{ title: "Trappist table", items: ["mutton stew", "mushroom pie", "aged Gouda", "date cake"] }],
    whyChoose: "The beers connect a real working abbey to distinct, food-friendly Belgian-style ales.",
    faqs: [{ question: "Where is La Trappe brewed?", answer: "At Koningshoeven Abbey near Tilburg in the Netherlands." }, { question: "Is La Trappe a Trappist beer?", answer: "Yes, it is brewed at a Trappist abbey." }],
    finalVerdict: "Start with Dubbel at dinner; save Quadrupel for a slower glass.",
    metaTitle: "La Trappe Trappist Beer Guide | BevOry", metaDescription: "Meet La Trappe's Koningshoeven abbey beers, from Dubbel to Quadrupel. Check city prices on BevOry.",
  },
  "la-vieille-ferme": {
    description: "La Vieille Ferme is a southern Rhône wine range made by Famille Perrin. Ventoux supplies structured reds, while Luberon vineyards give its whites and rosés a fresher line.",
    story: "The Perrin family, also behind Château de Beaucastel, built this range around everyday southern French wine. Separate Ventoux and Luberon origins matter more than a single house flavour.",
    tastingNotes: [{ title: "Ventoux red", description: "Ripe red fruit and a little spice suit the warm Rhône setting." }, { title: "Luberon white", description: "Citrus and orchard fruit keep the white brighter and lighter." }],
    howToEnjoy: [{ subheading: "By colour", description: "Chill white and rosé; serve the red a touch below room temperature." }, { subheading: "Weeknight food", description: "Ratatouille, paneer tikka and roast chicken all have a place across the range." }],
    pairingIdeas: [{ title: "Southern table", items: ["ratatouille", "paneer tikka", "roast chicken", "grilled courgette"] }],
    whyChoose: "It puts two southern Rhône growing areas on an approachable dinner table.",
    faqs: [{ question: "Who makes La Vieille Ferme?", answer: "Famille Perrin in southern France." }, { question: "Are its reds and whites from the same area?", answer: "The range draws notably on Ventoux for reds and Luberon for whites and rosés." }],
    finalVerdict: "The red is for a warm supper; the white is a better match for lighter food.",
    metaTitle: "La Vieille Ferme Wine Guide | BevOry", metaDescription: "Explore Famille Perrin's Ventoux reds and Luberon whites with food ideas. Check city prices on BevOry.",
  },
  "laurent-perrier": {
    description: "Laurent-Perrier is a Champagne house based in Tours-sur-Marne, France. Its range includes La Cuvée brut and rosé Champagne made with a strong emphasis on freshness.",
    story: "André-Michel Pierlot established the business in 1812. Bernard de Nonancourt's family later developed the house into an independent Champagne name still based in the same village.",
    tastingNotes: [{ title: "La Cuvée", description: "Citrus and white flowers sit over fine, bright bubbles." }, { title: "Rosé", description: "Red-berry fruit takes a larger role without losing freshness." }],
    howToEnjoy: [{ subheading: "Tulip glass", description: "Serve chilled in a glass wide enough to catch the aroma." }, { subheading: "First course", description: "Prawn toast, tandoori fish and soft goat cheese suit the acidity." }],
    pairingIdeas: [{ title: "With Champagne", items: ["prawn toast", "tandoori fish", "soft goat cheese", "salted almonds"] }],
    whyChoose: "Laurent-Perrier's brisk style makes it useful beyond the initial toast.",
    faqs: [{ question: "Where is Laurent-Perrier based?", answer: "In Tours-sur-Marne, in France's Champagne region." }, { question: "When did the house begin?", answer: "Its origins date to 1812." }],
    finalVerdict: "Keep a chilled glass beside the first course rather than putting it away after a toast.",
    metaTitle: "Laurent-Perrier Champagne Guide | BevOry", metaDescription: "Explore Laurent-Perrier's Tours-sur-Marne history and fresh Champagne. Check city prices on BevOry.",
  },
  leffe: {
    description: "Leffe is a Belgian abbey-beer range linked to Notre-Dame de Leffe near Dinant. Blonde and Brune offer different expressions of the malt-and-yeast style.",
    story: "The Premonstratensian abbey was founded in 1152, and brewing there is recorded from 1240. That monastic association remains the name's historical anchor.",
    tastingNotes: [{ title: "Blonde", description: "Soft malt and a fruity yeast note make the golden beer rounded." }, { title: "Brune", description: "Darker malt moves toward caramel and a touch of roast." }],
    howToEnjoy: [{ subheading: "Chalice", description: "Serve in a stemmed beer glass, cool but not ice-cold." }, { subheading: "With a plate", description: "Chilli paneer, roast chicken and mushroom tart suit the range." }],
    pairingIdeas: [{ title: "Abbey-beer food", items: ["chilli paneer", "roast chicken", "mushroom tart", "aged cheddar"] }],
    whyChoose: "Blonde and Brune make the range useful at quite different meals.",
    faqs: [{ question: "Where does the Leffe name come from?", answer: "Notre-Dame de Leffe abbey near Dinant, Belgium." }, { question: "When did brewing begin at Leffe?", answer: "Abbey brewing is recorded from 1240." }],
    finalVerdict: "Blonde is the lighter dinner choice; Brune belongs with richer food.",
    metaTitle: "Leffe Abbey Beer Guide | BevOry", metaDescription: "Meet Leffe's Belgian abbey history, Blonde and Brune styles and pairings. Check city prices on BevOry.",
  },
  "licor-43": {
    description: "Licor 43 is a golden Spanish liqueur made in Cartagena by the Zamora family. Its recipe combines 43 ingredients, including Mediterranean citrus and selected botanicals.",
    story: "The family has kept the recipe private while making the liqueur a Cartagena signature. In the city's layered Asiático coffee, Licor 43 meets espresso, condensed milk and brandy.",
    tastingNotes: [{ title: "Citrus", description: "Orange and lemon-like brightness keeps the sweet liqueur lively." }, { title: "Vanilla", description: "A warm vanilla impression rounds its dessert-friendly finish." }],
    howToEnjoy: [{ subheading: "Coffee", description: "Shake with espresso and ice for a carajillo-style serve." }, { subheading: "Dessert", description: "Orange cake, kulfi and almond biscuits make natural companions." }],
    pairingIdeas: [{ title: "After-dinner sweets", items: ["orange cake", "pistachio kulfi", "almond biscuits", "dark chocolate"] }],
    whyChoose: "Citrus and vanilla let the liqueur move easily between coffee and dessert.",
    faqs: [{ question: "Where is Licor 43 made?", answer: "In Cartagena, Spain." }, { question: "Why is it called 43?", answer: "Its secret family recipe contains 43 ingredients." }],
    finalVerdict: "A measured splash in strong coffee makes better sense than a large sweet pour.",
    metaTitle: "Licor 43 Liqueur Guide | BevOry", metaDescription: "Discover Licor 43 from Cartagena, its citrus-vanilla profile and coffee serves. Check city prices on BevOry.",
  },
  "london-no-1": {
    description: "The London No. 1 is a London-distilled gin in the González Byass portfolio. Twelve botanicals, including juniper, bergamot, iris and citrus peel, build its dry aromatic style.",
    story: "The gin draws on London's dry-gin tradition while using botanicals gathered from several countries. Its blue colour makes the bottle immediately recognisable behind a bar.",
    tastingNotes: [{ title: "Juniper", description: "Pine and coriander lead the classic dry-gin side." }, { title: "Citrus", description: "Bergamot and peel add a brighter, floral edge." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour over ice with a dry tonic and a thin lemon peel." }, { subheading: "With food", description: "Tandoori prawns, lemon paneer and green olives match its lift." }],
    pairingIdeas: [{ title: "Citrus plates", items: ["tandoori prawns", "lemon paneer", "green olives", "grilled calamari"] }],
    whyChoose: "The bergamot note gives an otherwise traditional dry gin a more fragrant line.",
    faqs: [{ question: "Who owns The London No. 1?", answer: "It is part of the González Byass drinks portfolio." }, { question: "How many botanicals does it use?", answer: "The gin is made with twelve botanicals." }],
    finalVerdict: "A restrained lemon garnish leaves room for the bergamot to speak.",
    metaTitle: "The London No. 1 Gin Guide | BevOry", metaDescription: "Explore The London No. 1's twelve botanicals and dry-gin serves. Check city prices on BevOry.",
  },
  "longitude-77": {
    description: "Longitude 77 is an Indian single malt from Pernod Ricard, matured in Dindori near Nashik. Bourbon and wine casks both figure in its double-cask ageing.",
    story: "The name points to the 77th meridian east, a line running through India. Pernod Ricard chose Dindori's cool, dry conditions for the whisky's later maturation.",
    tastingNotes: [{ title: "Malt", description: "Orchard fruit and a honeyed grain note open the whisky." }, { title: "Two casks", description: "Oak spice meets a rounder fruit note from the wine-cask side." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Taste in a small whisky glass before adding a few drops of water." }, { subheading: "At dinner", description: "Mutton seekh, paneer tikka and roasted walnuts make sturdy partners." }],
    pairingIdeas: [{ title: "Nashik malt food", items: ["mutton seekh", "paneer tikka", "roasted walnuts", "grilled mushrooms"] }],
    whyChoose: "Its bourbon-and-wine cask route gives this Nashik malt a clear production identity.",
    faqs: [{ question: "Where is Longitude 77 matured?", answer: "At Dindori in the Nashik region of Maharashtra." }, { question: "Why the number 77?", answer: "It refers to the 77th meridian east running through India." }],
    finalVerdict: "Give the whisky a small neat pour before deciding whether it needs water.",
    metaTitle: "Longitude 77 Single Malt Guide | BevOry", metaDescription: "Meet Longitude 77 from Dindori, with bourbon-and-wine cask character. Check city prices on BevOry.",
  },
  "louis-roederer": {
    description: "Louis Roederer is an independent Champagne house based in Reims. Its multi-vintage Collection blends Chardonnay, Pinot Noir and Meunier from selected Champagne sites.",
    story: "The house dates to 1776, and Louis Roederer later invested in its own vineyards rather than relying solely on bought grapes. The Rouzaud family continues to lead the house today.",
    tastingNotes: [{ title: "Collection", description: "Orchard fruit, citrus and light pastry notes sit over fine bubbles." }, { title: "Cristal", description: "The prestige cuvée has a firmer, more layered Champagne structure." }],
    howToEnjoy: [{ subheading: "Chilled tulip", description: "Use a tulip glass and serve cool enough to keep the mousse lively." }, { subheading: "Across courses", description: "Tandoori fish, prawn tempura and mushroom tart suit Collection." }],
    pairingIdeas: [{ title: "Champagne dinner", items: ["tandoori fish", "prawn tempura", "mushroom tart", "salted cashews"] }],
    whyChoose: "Its vineyard ownership gives Collection a rooted, multi-vintage Champagne identity.",
    faqs: [{ question: "Where is Louis Roederer based?", answer: "In Reims, France." }, { question: "What is Collection?", answer: "Its multi-vintage Champagne cuvée built from selected vineyard plots." }],
    finalVerdict: "Collection is the house's versatile bottle for a meal, not just a toast.",
    metaTitle: "Louis Roederer Champagne Guide | BevOry", metaDescription: "Explore Louis Roederer's Reims history, Collection cuvée and pairings. Check city prices on BevOry.",
  },
  lustau: {
    description: "Lustau is a sherry house from Jerez de la Frontera, Spain. Its range moves from dry Fino and Amontillado to richer Oloroso and Pedro Ximénez wines.",
    story: "José Ruiz-Berdejo began the business in 1896 as an almacenista, ageing wine for larger sherry houses. Emilio Lustau later moved the bodega into Jerez's Santiago quarter and built its own labels.",
    tastingNotes: [{ title: "Fino", description: "Dry, saline and almond-led after ageing under flor yeast." }, { title: "Pedro Ximénez", description: "Raisins, dates and dark syrup mark the sweet end of the range." }],
    howToEnjoy: [{ subheading: "By style", description: "Chill Fino well; pour sweet Pedro Ximénez in a smaller dessert glass." }, { subheading: "Food", description: "Fino suits fried fish and masala almonds; PX belongs with vanilla kulfi." }],
    pairingIdeas: [{ title: "Sherry contrasts", items: ["fried fish", "masala almonds", "vanilla kulfi", "blue cheese"] }],
    whyChoose: "One bodega gives a practical tour from bone-dry flor-aged wine to dark sweetness.",
    faqs: [{ question: "Where is Lustau based?", answer: "In Jerez de la Frontera in southern Spain." }, { question: "Is all Lustau sherry sweet?", answer: "No. Fino is dry, while Pedro Ximénez is richly sweet." }],
    finalVerdict: "Choose the sherry style for the course; Fino and PX are different conversations.",
    metaTitle: "Lustau Sherry Guide | BevOry", metaDescription: "Discover Lustau's Jerez Fino, Amontillado and Pedro Ximénez styles. Check city prices on BevOry.",
  },
  "maestro-dobel": {
    description: "Maestro Dobel is a tequila range made in Jalisco, Mexico. Its Diamante Cristalino blends aged tequila styles and filters them to a clear appearance.",
    story: "The Beckmann family's tequila heritage sits behind the brand. Dobel's producers use both traditional distilling knowledge and filtration to make the clear, oak-touched Diamante.",
    tastingNotes: [{ title: "Diamante", description: "Cooked agave meets a soft vanilla note despite the clear colour." }, { title: "Oak", description: "The aged components leave a gentle spice on the finish." }],
    howToEnjoy: [{ subheading: "Short pour", description: "Sip Diamante chilled or over one cube to catch the agave beneath the oak." }, { subheading: "Food", description: "Fish tacos, paneer tikka and roasted corn suit the savoury side." }],
    pairingIdeas: [{ title: "Agave plates", items: ["fish tacos", "paneer tikka", "roasted corn", "guacamole"] }],
    whyChoose: "Diamante offers an oak-influenced tequila without the visual cue of a dark spirit.",
    faqs: [{ question: "What is Maestro Dobel Diamante?", answer: "A clear cristalino tequila made from aged tequila components." }, { question: "Where is it made?", answer: "In Jalisco, Mexico." }],
    finalVerdict: "A small pour makes the contrast between clear colour and aged flavour easy to notice.",
    metaTitle: "Maestro Dobel Tequila Guide | BevOry", metaDescription: "Meet Maestro Dobel's Jalisco tequila and clear, oak-touched Diamante. Check city prices on BevOry.",
  },
  "makers-mark": {
    description: "Maker's Mark is a Kentucky bourbon made at its distillery in Loretto. Red winter wheat takes the place of rye in its mash, giving the whiskey a softer spice profile.",
    story: "Bill Samuels Sr. discarded an older family recipe to make the new bourbon. Margie Samuels shaped its name, bottle and hand-dipped red wax seal.",
    tastingNotes: [{ title: "Wheat", description: "Warm baking notes replace the sharper bite associated with rye-heavy bourbon." }, { title: "Oak", description: "Vanilla and caramel come through the barrel-aged sweetness." }],
    howToEnjoy: [{ subheading: "Old Fashioned", description: "Stir with bitters and a little sugar, or sip over one large cube." }, { subheading: "Dinner", description: "Barbecue chicken, galouti kebabs and pecan pie work with the soft oak." }],
    pairingIdeas: [{ title: "Wheated bourbon food", items: ["barbecue chicken", "galouti kebabs", "pecan pie", "roasted pecans"] }],
    whyChoose: "Wheat and red wax make this bourbon's recipe and identity unusually easy to recognise.",
    faqs: [{ question: "What grain replaces rye in Maker's Mark?", answer: "Red winter wheat." }, { question: "Who designed its red-wax bottle?", answer: "Margie Samuels." }],
    finalVerdict: "The softer grain profile makes it a generous first pour for bourbon-curious drinkers.",
    metaTitle: "Maker's Mark Bourbon Guide | BevOry", metaDescription: "Explore Maker's Mark's wheated Kentucky bourbon, red wax and pairings. Check city prices on BevOry.",
  },
  malfy: {
    description: "Malfy is an Italian gin distilled at Torino Distillati in Moncalieri, Piedmont. Its citrus-led range includes Originale alongside lemon, grapefruit and orange expressions.",
    story: "The distillery sits outside Turin, a city with a long drinks-making culture. Malfy gives Italian citrus a leading role across its flavoured gins without making every bottle taste alike.",
    tastingNotes: [{ title: "Originale", description: "Juniper and liquorice give the dry gin a faintly salty finish." }, { title: "Citrus bottles", description: "The lemon and grapefruit releases put sharper fruit above the juniper." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use a dry tonic and a matching citrus slice, keeping the garnish modest." }, { subheading: "With food", description: "Grilled prawns, lemon paneer and olives suit its bright edge." }],
    pairingIdeas: [{ title: "Italian-citrus table", items: ["grilled prawns", "lemon paneer", "green olives", "fried calamari"] }],
    whyChoose: "Its citrus range lets you choose a sharper gin without leaving the juniper behind.",
    faqs: [{ question: "Where is Malfy gin distilled?", answer: "At Torino Distillati in Moncalieri, Italy." }, { question: "Is every Malfy gin lemon-flavoured?", answer: "No. Originale is a dry gin and the range includes several citrus expressions." }],
    finalVerdict: "Match the tonic garnish to the bottle and let the citrus do the work.",
    metaTitle: "Malfy Italian Gin Guide | BevOry", metaDescription: "Discover Malfy gin from Moncalieri, from dry Originale to citrus styles. Check city prices on BevOry.",
  },
  masi: {
    description: "Masi is a Valpolicella wine producer from Veneto, Italy, closely associated with Amarone. The Boscaini family uses appassimento, drying selected grapes before fermentation, in its richer reds.",
    story: "The family's first recorded harvest at Vaio dei Masi dates to 1772. Drying rooms called fruttai still form part of the area's winemaking culture.",
    tastingNotes: [{ title: "Amarone", description: "Dried cherry and raisin notes sit within a full-bodied red." }, { title: "Valpolicella", description: "The lighter reds lean toward fresher cherry and savoury acidity." }],
    howToEnjoy: [{ subheading: "Red glass", description: "Give a young Amarone air and serve it slightly below room temperature." }, { subheading: "Rich food", description: "Mutton rogan josh, mushroom ragù and aged parmesan suit its weight." }],
    pairingIdeas: [{ title: "Veneto dinner", items: ["mutton rogan josh", "mushroom ragù", "aged parmesan", "braised lamb"] }],
    whyChoose: "Masi makes the effect of dried grapes tangible in an Amarone glass.",
    faqs: [{ question: "What is appassimento?", answer: "The drying of selected grapes before winemaking, concentrating their character." }, { question: "Where is Masi based?", answer: "In the Valpolicella area of Veneto, Italy." }],
    finalVerdict: "A rich Amarone belongs with a slow meal, not a quick aperitif.",
    metaTitle: "Masi Valpolicella Wine Guide | BevOry", metaDescription: "Explore Masi's Veneto reds, Amarone and appassimento method. Check city prices on BevOry.",
  },
  masseto: {
    description: "Masseto is a Tuscan wine estate near Bolgheri whose flagship red centres on Merlot. Its sea-facing hillside contains a band of blue clay that shapes the estate's most closely watched parcels.",
    story: "The first Merlot vines went into the Masseto hillside in the early 1980s. Massetino, the estate's second wine, arrived with the 2017 vintage and may include Cabernet Franc alongside Merlot.",
    tastingNotes: [{ title: "Masseto", description: "Dark fruit, savoury depth and firm texture mark the flagship red." }, { title: "Massetino", description: "The second wine brings ripe fruit and freshness to a more immediately open glass." }],
    howToEnjoy: [{ subheading: "Decant", description: "Pour a young bottle into a decanter and use a large red-wine glass." }, { subheading: "At dinner", description: "Serve with slow-braised lamb, mutton rogan josh or porcini risotto." }],
    pairingIdeas: [{ title: "Long dinner", items: ["mutton rogan josh", "slow-braised lamb", "porcini risotto", "aged pecorino"] }],
    whyChoose: "Few Tuscan Merlot sites have an identity as particular as Masseto's blue-clay slope.",
    faqs: [{ question: "Where is Masseto made?", answer: "On the Tuscan coast near Bolgheri, Italy." }, { question: "Is Massetino the same wine as Masseto?", answer: "No. It is the estate's second wine, first made from the 2017 vintage." }],
    finalVerdict: "Give this coastal Tuscan red time in the glass and a substantial meal beside it.",
    metaTitle: "Masseto Tuscan Wine Guide | BevOry", metaDescription: "Discover Masseto's Bolgheri Merlot, blue-clay hillside and Massetino. Check city prices on BevOry.",
  },
  mateus: {
    description: "Mateus is a Portuguese rosé created by Sogrape and known for its broad, flask-shaped bottle. The original style is light, gently sparkling and fruit-led.",
    story: "Fernando van Zeller Guedes created Mateus in 1942. Its squat bottle became recognisable far beyond Portugal and helped take Portuguese rosé abroad.",
    tastingNotes: [{ title: "Fruit", description: "Strawberry and red-berry notes keep the rosé easy to approach." }, { title: "Texture", description: "A light spritz lifts the fruit on the finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a white-wine glass." }, { subheading: "Snacks", description: "Try tandoori fish, watermelon chaat or prawn skewers." }],
    pairingIdeas: [{ title: "Light plates", items: ["tandoori fish", "watermelon chaat", "prawn skewers", "strawberry tart"] }],
    whyChoose: "Its gentle fizz and familiar bottle make Portuguese rosé approachable at a casual table.",
    faqs: [{ question: "Where does Mateus rosé come from?", answer: "Portugal." }, { question: "Who created Mateus?", answer: "Fernando van Zeller Guedes of Sogrape created it in 1942." }],
    finalVerdict: "Cold Mateus rosé makes most sense with a light, salty lunch.",
    metaTitle: "Mateus Rosé Wine Guide | BevOry", metaDescription: "Meet Mateus, the Portuguese rosé in the flask-shaped bottle. Find pairings and check city prices on BevOry.",
  },
  mcguigan: {
    description: "McGuigan is an Australian wine producer with roots in the Hunter Valley of New South Wales. Its range spans whites and reds, including Semillon, Chardonnay and Shiraz.",
    story: "The McGuigan family's winemaking history reaches back to the 1880s in the Hunter Valley. Later generations built a label that travels well beyond its home region.",
    tastingNotes: [{ title: "Hunter Semillon", description: "Young examples show citrus and a lean, brisk line." }, { title: "Shiraz", description: "Dark berry fruit and spice give the red a fuller profile." }],
    howToEnjoy: [{ subheading: "Match the glass", description: "Chill Semillon; serve Shiraz slightly cool in a red-wine glass." }, { subheading: "Table", description: "Lemon fish suits Semillon; mutton seekh or peppered mushrooms suit Shiraz." }],
    pairingIdeas: [{ title: "Two styles", items: ["lemon fish", "mutton seekh", "peppered mushrooms", "grilled prawns"] }],
    whyChoose: "The range offers an accessible route into both Hunter Valley whites and Australian reds.",
    faqs: [{ question: "Where did McGuigan wines begin?", answer: "In Australia's Hunter Valley, New South Wales." }, { question: "Does McGuigan make only red wine?", answer: "No. Its range includes white grapes such as Semillon and Chardonnay." }],
    finalVerdict: "Pick by grape and dinner: a crisp Semillon and a rich Shiraz do different jobs.",
    metaTitle: "McGuigan Australian Wine Guide | BevOry", metaDescription: "Explore McGuigan's Hunter Valley roots, Semillon and Shiraz pairings. Check city prices on BevOry.",
  },
  mermaid: {
    description: "Mermaid Gin is made by the Isle of Wight Distillery in England. Its botanical recipe includes locally foraged elderflower and rock samphire alongside lemon zest and grains of paradise.",
    story: "The distillery began making gin on the island in 2014. Its Mermaid range takes its name from the coastal setting rather than a claim that the spirit tastes of seawater.",
    tastingNotes: [{ title: "Coastal herbs", description: "Rock samphire gives a green, herbal edge." }, { title: "Bright spice", description: "Lemon zest and grains of paradise add citrus and a peppery finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour over ice with a dry tonic and a strip of lemon peel." }, { subheading: "Seafood", description: "Grilled prawns, tandoori fish and cucumber salad keep the herbal notes clear." }],
    pairingIdeas: [{ title: "Coastal plates", items: ["grilled prawns", "tandoori fish", "cucumber salad", "oysters"] }],
    whyChoose: "Rock samphire gives this island gin a botanical detail you can actually taste.",
    faqs: [{ question: "Where is Mermaid Gin made?", answer: "At the Isle of Wight Distillery in England." }, { question: "What gives Mermaid Gin its coastal character?", answer: "Rock samphire is one of its botanicals." }],
    finalVerdict: "A dry tonic leaves its green coastal note room to speak.",
    metaTitle: "Mermaid Isle of Wight Gin Guide | BevOry", metaDescription: "Discover Mermaid Gin's Isle of Wight botanicals and seafood pairings. Check city prices on BevOry.",
  },
  metaxa: {
    description: "Metaxa is a Greek amber spirit combining sweet Muscat wine from the Aegean islands, aged wine distillates and Mediterranean botanicals. Spyros Metaxa created it in 1888.",
    story: "The house began in Piraeus before moving its production base to Kifissia. Muscat from islands including Samos remains central to the spirit's fruit-led character.",
    tastingNotes: [{ title: "Muscat", description: "Grape sweetness and floral fruit come from the Aegean wine component." }, { title: "Oak and spice", description: "Aged wine distillates add vanilla and warm spice beneath the fruit." }],
    howToEnjoy: [{ subheading: "After dinner", description: "Sip a small pour neat or over one cube." }, { subheading: "Dessert", description: "Orange cake, pistachio kulfi and dark chocolate work with its sweet-spiced side." }],
    pairingIdeas: [{ title: "After-dinner bites", items: ["orange cake", "pistachio kulfi", "dark chocolate", "roasted almonds"] }],
    whyChoose: "Muscat wine gives Metaxa a character distinct from a straight grape brandy.",
    faqs: [{ question: "What is Metaxa made from?", answer: "A blend of Aegean Muscat wine, aged wine distillates and Mediterranean botanicals." }, { question: "Where did Metaxa begin?", answer: "Spyros Metaxa created it in Greece in 1888." }],
    finalVerdict: "Think of it as a Greek after-dinner pour with fruit, flowers and oak in one glass.",
    metaTitle: "Metaxa Greek Spirit Guide | BevOry", metaDescription: "Learn how Metaxa combines Aegean Muscat, aged distillates and botanicals. Check city prices on BevOry.",
  },
  meukow: {
    description: "Meukow is a Cognac house established in the French town of Cognac by two brothers from Silesia. Its bottles carry a black panther emblem.",
    story: "Auguste-Christophe and Gustav Meukow opened their Cognac trading office on 1 August 1862. The panther appeared on the bottle in 1993, giving the house a lasting visual signature.",
    tastingNotes: [{ title: "Fruit", description: "Ripe orchard fruit gives the house style its rounded start." }, { title: "Cask", description: "Vanilla and spice give the warmer side of the Cognac." }],
    howToEnjoy: [{ subheading: "Small pour", description: "Try the Cognac neat in a tulip glass at room temperature." }, { subheading: "After dinner", description: "Pair with dark chocolate, almond barfi or grilled peaches." }],
    pairingIdeas: [{ title: "Sweet finish", items: ["dark chocolate", "almond barfi", "grilled peaches", "walnut cake"] }],
    whyChoose: "The house has a documented 1862 origin and a Cognac style built for a slow sip.",
    faqs: [{ question: "When was Meukow founded?", answer: "The Meukow brothers established their Cognac office in 1862." }, { question: "What is the animal on a Meukow bottle?", answer: "A black panther, introduced on the bottle in 1993." }],
    finalVerdict: "A tulip glass lets its fruit and cask warmth unfold without a mixer.",
    metaTitle: "Meukow Cognac Guide | BevOry", metaDescription: "Read Meukow's 1862 Cognac story, panther-bottle history and pairings. Check city prices on BevOry.",
  },
  midori: {
    description: "Midori is a bright green melon liqueur from Japan made by Suntory. Japanese muskmelon gives the sweet liqueur its distinctive fruit character.",
    story: "The name means green in Japanese. Midori reached the United States in 1978 and became a familiar cocktail ingredient in the following decades.",
    tastingNotes: [{ title: "Melon", description: "Sweet, fragrant muskmelon leads the sip." }, { title: "Finish", description: "The fruit remains bright and candy-like rather than bitter." }],
    howToEnjoy: [{ subheading: "Sour", description: "Shake with lemon juice to put acidity against the melon sweetness." }, { subheading: "Snacks", description: "Salted edamame, chilli-lime peanuts and fruit chaat provide contrast." }],
    pairingIdeas: [{ title: "Sweet-salty contrast", items: ["salted edamame", "chilli-lime peanuts", "fruit chaat", "spicy prawn skewers"] }],
    whyChoose: "A little Midori gives a sour cocktail a clear melon flavour and vivid colour.",
    faqs: [{ question: "What flavour is Midori?", answer: "Sweet Japanese muskmelon." }, { question: "Who makes Midori?", answer: "Suntory, the Japanese drinks company." }],
    finalVerdict: "Use citrus generously and let the melon stay the leading note.",
    metaTitle: "Midori Melon Liqueur Guide | BevOry", metaDescription: "Explore Midori's Japanese melon flavour and simple sour serves. Check city prices on BevOry.",
  },
  "monkey-47": {
    description: "Monkey 47 is a gin from Germany's Black Forest made with 47 botanicals. Its recipe draws on local ingredients including lingonberries and spruce shoots.",
    story: "The brand's story links a postwar British officer in the Black Forest with a later revival of his gin recipe. Its German woodland setting remains more than a label design: local botanicals are part of the blend.",
    tastingNotes: [{ title: "Forest", description: "Herbal, pine-like notes sit beside the juniper." }, { title: "Fruit and spice", description: "Lingonberry brightness cuts through the layered spice." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Use a restrained amount of dry tonic and no elaborate garnish." }, { subheading: "Savory food", description: "Tandoori mushrooms, smoked trout and herb-roasted chicken suit its botanical weight." }],
    pairingIdeas: [{ title: "Herbal plates", items: ["tandoori mushrooms", "smoked trout", "herb-roasted chicken", "roasted walnuts"] }],
    whyChoose: "Its layered botanicals reward a simpler tonic serve than many gins need.",
    faqs: [{ question: "Where is Monkey 47 made?", answer: "In Germany's Black Forest." }, { question: "What does 47 refer to?", answer: "The number of botanicals in the gin recipe." }],
    finalVerdict: "A measured tonic lets the forest herbs and fruit stay in focus.",
    metaTitle: "Monkey 47 Black Forest Gin Guide | BevOry", metaDescription: "Meet Monkey 47's Black Forest botanicals and food pairings. Check city prices on BevOry.",
  },
  montenegro: {
    description: "Amaro Montenegro is an Italian herbal liqueur from Bologna. Its recipe uses 40 botanicals for a bittersweet profile with a marked orange note.",
    story: "Stanislao Cobianchi founded the house in 1885, first selling the drink as Elisir Lungavita. The name Montenegro came later and has stayed with the bottle since.",
    tastingNotes: [{ title: "Citrus", description: "Orange peel gives the opening its lift." }, { title: "Herbs", description: "Gentle bitterness and warm spice round off the sweeter middle." }],
    howToEnjoy: [{ subheading: "Aperitivo", description: "Serve over ice with a splash of soda and an orange slice." }, { subheading: "Before dinner", description: "Try it with olives, paneer tikka or fried artichokes." }],
    pairingIdeas: [{ title: "Aperitivo snacks", items: ["green olives", "paneer tikka", "fried artichokes", "salted almonds"] }],
    whyChoose: "Montenegro offers a gentler route into amaro without losing its herbal bite.",
    faqs: [{ question: "Where is Amaro Montenegro from?", answer: "Bologna, Italy." }, { question: "How can I serve it?", answer: "Over ice, neat or lengthened with soda." }],
    finalVerdict: "Orange, herbs and soda make a brisk start to a meal.",
    metaTitle: "Amaro Montenegro Guide | BevOry", metaDescription: "Discover Amaro Montenegro's Bologna history, orange-herbal taste and serves. Check city prices on BevOry.",
  },
  "kati-patang": {
    description: "Kati Patang is an Indian craft-beer label founded in 2018. Its beers use local ingredients in styles that range from wheat beer to amber ale and lager.",
    story: "Shantanu and Lata left consulting and advertising careers to build the beer label. Their range turns ingredients such as Kashmiri saffron, turmeric and ginger into distinct recipes.",
    tastingNotes: [{ title: "Snappy Wheat", description: "Citrus, ginger and coriander sit above a light wheat-beer base." }, { title: "Zesty Amber", description: "Roasted malt gives caramel and chocolate notes to the fuller amber ale." }],
    howToEnjoy: [{ subheading: "Cold glass", description: "Serve chilled; use a wheat-beer glass for Snappy Wheat and a pint glass for Zesty Amber." }, { subheading: "Indian snacks", description: "Chilli paneer suits Snappy Wheat; tandoori mushrooms work with Zesty Amber." }],
    pairingIdeas: [{ title: "Beer and snacks", items: ["chilli paneer", "tandoori mushrooms", "masala peanuts", "chicken tikka"] }],
    whyChoose: "The spice belongs in the beer recipe, not just in the food beside it.",
    faqs: [{ question: "When did Kati Patang begin?", answer: "Its founders started brewing craft beer in 2018." }, { question: "What is Snappy Wheat?", answer: "A wheat beer brewed with turmeric, peppercorn, coriander, ginger and citrus." }],
    finalVerdict: "Pick the wheat for spice and lift, or the amber for a richer malt glass.",
    metaTitle: "Kati Patang Craft Beer Guide | BevOry", metaDescription: "Explore Kati Patang's Indian craft beers, from Snappy Wheat to Zesty Amber. Check city prices on BevOry.",
  },
  kamet: {
    description: "Kamet is an Indian single malt whisky made from six-row barley grown near the Himalayan foothills. It matures in ex-bourbon American oak, French wine casks and sherry casks.",
    story: "The whisky takes its name from Mount Kamet in the Himalayas. Its blender Surrinder Kumar previously worked on the Amrut single-malt programme before bringing that experience to Kamet.",
    tastingNotes: [{ title: "Fruit", description: "Ripe and dried fruit give the whisky a vinous start." }, { title: "Oak", description: "Vanilla, spice and dark chocolate carry through the finish." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Try a small neat pour, then a few drops of water." }, { subheading: "At the table", description: "Mutton seekh, roasted cashews and dark chocolate suit the fruit-and-oak balance." }],
    pairingIdeas: [{ title: "Whisky plates", items: ["mutton seekh", "roasted cashews", "dark chocolate", "smoked paneer"] }],
    whyChoose: "Three cask families give this Indian malt both wine-led fruit and oak spice.",
    faqs: [{ question: "What grain is used for Kamet?", answer: "Six-row barley grown near the Himalayan foothills." }, { question: "Which casks mature Kamet?", answer: "Ex-bourbon American oak, French wine and Pedro Ximénez and Oloroso sherry casks." }],
    finalVerdict: "A little water shows how the fruit and oak share the glass.",
    metaTitle: "Kamet Indian Single Malt Guide | BevOry", metaDescription: "Learn about Kamet's Himalayan barley, three-cask maturation and pairings. Check city prices on BevOry.",
  },
};
