import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_36 = [
  ["twin-fin", "Twin Fin", "United Kingdom", "Rum", "5826c2a76d20396437903b3c"],
  ["two-ocean", "Two Oceans", "South Africa", "Wine", "0d53fe7df709024f307551ea"],
  ["ulithorne", "Ulithorne", "Australia", "Wine", "fef6144a487dc1c4132b5526"],
  ["valiano", "Valiano", "Italy", "Wine", "594d4aeb1009074e6c519538"],
  ["varchas", "Varchas", "United States", "Whisky", "6744591170e47f436b497fac"],
  ["vecchia-romagna", "Vecchia Romagna", "Italy", "Brandy", "ada4eefed497561203e37014"],
  ["vecchio-amaro-del-capo", "Vecchio Amaro del Capo", "Italy", "Liqueur", "d41c5208d21bd292e6cd6a2b"],
  ["vietti", "Vietti", "Italy", "Wine", "5e480dccc9e20b8b406daf55"],
  ["villa-antinori", "Villa Antinori", "Italy", "Wine", "944d797a1c665ef8405cc5d6"],
  ["villa-maria", "Villa Maria", "New Zealand", "Wine", "416f7e4b7fd29ee7ac184a04"],
  ["villa-sandi", "Villa Sandi", "Italy", "Sparkling Wine", "595fc4e5d3c8f420936a54e8"],
  ["vina-albali", "Vina Albali", "Spain", "Wine", "0bb8083727d9bb118bf77d5f"],
  ["vina-esmeralda", "Vina Esmeralda", "Spain", "Wine", "186912c53219980dcd81257e"],
  ["vina-pomal", "Vina Pomal", "Spain", "Wine", "438c5b4fe88f45c34389bed6"],
  ["vivir", "VIVIR", "Mexico", "Tequila", "50e335c488a212b6269c3f96"],
  ["volare", "Volare", "Italy", "Liqueur", "685ba9d4476fe5af809dfd7f"],
  ["volcan-de-mi-tierra", "Volcan de mi Tierra", "Mexico", "Tequila", "d0340c9e71e4935add5d5000"],
  ["vollereaux", "Vollereaux", "France", "Champagne", "22da687db035c34564f23f93"],
  ["warwick", "Warwick", "South Africa", "Wine", "dacb204492f677440f0404de"],
  ["wente", "Wente", "United States", "Wine", "76484cdcb99b62bea22b53f7"],
  ["west-cork", "West Cork", "Ireland", "Whisky", "2b50888f42469bb45492d4ef"],
  ["west-malle", "Westmalle", "Belgium", "Beer", "d5c1e35d8f85dfbfdc86ccf4"],
  ["william-hardy", "William Hardy", "Australia", "Wine", "cd5fcdbbceb16df566250a0e"],
  ["william-peel", "William Peel", "Scotland", "Whisky", "4fcd0ffa3f86d5ca7423be2c"],
  ["wirra-wirra", "Wirra Wirra", "Australia", "Wine", "f3f0b987a2c0fef8290f6bf0"],
  ["wolfberger", "Wolfberger", "France", "Wine", "669fc05ac19f9e585ca6ead3"],
  ["wolfblass", "Wolf Blass", "Australia", "Wine", "528abddda4c2742c3e13bee3"],
  ["wolfburn", "Wolfburn", "Scotland", "Whisky", "329db4f5b78d99b48fe9b438"],
  ["wolftrap", "The Wolftrap", "South Africa", "Wine", "9e77b954d974117e65e4d908"],
  ["writers-tears", "Writers' Tears", "Ireland", "Whisky", "b7225fc6c910bef3dd023ed0"],
] as const;

// Research and asset provenance are internal and never rendered as consumer copy.
export const BRAND_SOURCES_BATCH_36: Record<string, string[]> = {
  "twin-fin": ["https://www.twinfinrum.com/pages/our-story", "https://www.twinfinrum.com/products/twin-fin-pineapple-and-pink-grapefruit-rum"],
  "two-ocean": ["https://catalogue.heinekenbeverages.co.za/", "https://www.saq.com/en/10967303"],
  ulithorne: ["https://www.ulithornewines.com/about-us", "https://www.ulithornewines.com/wines"],
  valiano: ["https://www.piccini1882.it/en/product-category/valiano-farm/?layout=list", "https://shop.piccini1882.it/it/eur/it/prodotti/chianti-classico-docg-2020-bio-valiano"],
  varchas: ["https://www.shankardistillers.com/india/story-of-varchas/"],
  "vecchia-romagna": ["https://vecchiaromagna.it/en/history/", "https://vecchiaromagna.it/en/"],
  "vecchio-amaro-del-capo": ["https://caffo.info/it/prodotto/1537", "https://www.caffo.com/"],
  vietti: ["https://www.vietti.com/it/storia"],
  "villa-antinori": ["https://www.antinori.it/en/vino/villa-antinori-rosso-en/historical-data/"],
  "villa-maria": ["https://villamariawines.com/our-history/"],
  "villa-sandi": ["https://www.villasandi.it/it/history"],
  "vina-albali": ["https://felixsolisavantis.com/compania/"],
  "vina-esmeralda": ["https://www.torres.es/en/wines/torres-essentials/vina-esmeralda"],
  "vina-pomal": ["https://www.15bodegas.com/bodegas-bilbainas-winery", "https://www.barrioestacion.com/en/bodega/bodegas-bilbainas/"],
  vivir: ["https://www.vivirtequila.com/pages/faqs", "https://www.vivirtequila.com/"],
  volare: ["https://www.rossidasiago.com/en/prodotti/volare-cocktails-en/", "https://www.rossidasiago.com/en/prodotto/volare-liquore-blu-curacao/"],
  "volcan-de-mi-tierra": ["https://www.lvmh.com/en/our-maisons/wines-spirits/volcan-de-mi-tierra"],
  vollereaux: ["https://www.champagne-vollereaux.fr/la-maison/", "https://www.champagne-vollereaux.fr/nos-creations/marguerite-millesime-2013/"],
  warwick: ["https://www.warwickwine.com/", "https://www.warwickwine.com/post/trilogy-a-new-era"],
  wente: ["https://wentevineyards.com/our-story/"],
  "west-cork": ["https://www.westcorkdistillers.com/our-story"],
  "west-malle": ["https://www.trappistwestmalle.be/en/trappist-beer/"],
  "william-hardy": ["https://hardyswines.com/pages/us-canada", "https://accoladewines.com/wp-content/uploads/2022/02/Accolade_WineReport_2018_Mars_v7_NEW_All-pages_lw.pdf"],
  "william-peel": ["https://www.williampeel.com/produits/", "https://mbws.com/"],
  "wirra-wirra": ["https://wirrawirra.com/"],
  wolfberger: ["https://www.wolfberger.com/en/our-history/"],
  wolfblass: ["https://www.wolfblass.com/en-gb/about/our-history.html"],
  wolfburn: ["https://wolfburn.com/pages/story"],
  wolftrap: ["https://www.boekenhoutskloof.co.za/thewolftrap", "https://www.boekenhoutskloof.co.za/wp-content/uploads/2022/02/The-Wolftrap-Red-2021.pdf"],
  "writers-tears": ["https://www.walshwhiskey.com/our-whiskeys/our-whiskeys-writers-tears/"],
};

// Each URL is an exact brand mark visible in that producer's own site header.
export const BRAND_LOGOS_BATCH_36: Record<string, string> = {
  ulithorne: "https://images.squarespace-cdn.com/content/v1/645d8a27724a3e4d475ed5ad/94330ac3-290a-4f3d-a173-60b91136ecc3/Ulithorne+Logo+v2_Ulithorne+Logo.png?format=1500w",
  "villa-sandi": "https://www.villasandi.it/static/version1754580946/frontend/Hevelop/Villasandi/en_US/images/logo.svg",
  vivir: "https://www.vivirtequila.com/cdn/shop/files/VIVIR-icon-black.png?v=1702050325&width=90",
  vollereaux: "https://www.champagne-vollereaux.fr/app/uploads/2026/08/logo-champagne-vollereaux.svg",
  warwick: "https://www.warwickwine.com/media/kotagbf2/warwick-logo-dark.png?width=332&format=webp&quality=85",
  wente: "https://wentevineyards.com/wp-content/uploads/2025/03/Went-Family-Vineyard-Logo-Black-1.png",
  "wirra-wirra": "https://wirrawirra.com/cdn/shop/files/Wirra_Wirra_Logo_500x@2x.png?v=1765767254",
  wolfblass: "https://www.wolfblass.com/on/demandware.static/-/Library-Sites-WolfBlassSharedLibrary/default/dwb6f0d71d/images/age-gate-one/wolfblass-logo.png",
  wolfburn: "https://wolfburn.com/cdn/shop/files/Wolfburn_Single_Malt_Scotch_Whisky_Logo.svg?v=1775671573&width=440",
};

export const BRAND_CONTENT_BATCH_36: Record<string, BrandPublicContent> = {
  "twin-fin": {
    description: "Twin Fin is a Cornish rum label from Southwestern Distillery, built around Caribbean rum and bright fruit flavours. Pineapple & Pink Grapefruit and Spiced Golden Rum sit alongside darker and barrel-aged bottles.",
    story: "The team in Cornwall spent two years developing a rum range that would connect Caribbean spirit with the English coast. The name and surf-coloured bottles carry that coast-to-coast idea without disguising the rum inside.",
    tastingNotes: [{ title: "Pineapple & Pink Grapefruit", description: "Charred pineapple and sharp grapefruit make the fruit-led rum lively rather than jammy." }, { title: "Spiced Golden", description: "Warm spice rounds out the golden rum's sweeter side." }],
    howToEnjoy: [{ subheading: "Long drink", description: "Pour the fruit rum over ice with lemonade and a wedge of grapefruit." }, { subheading: "Food", description: "Its citrus edge cuts through chilli prawns or peri-peri chicken." }],
    pairingIdeas: [{ title: "Coastal plates", items: ["chilli prawns", "peri-peri chicken", "pineapple chaat", "grilled corn"] }],
    whyChoose: "A fruit-forward rum that keeps the cocktail simple: ice, a mixer and citrus.",
    faqs: [{ question: "Who makes Twin Fin rum?", answer: "Twin Fin comes from Southwestern Distillery in Cornwall, England." }, { question: "Is Twin Fin only a spiced rum?", answer: "No. The range includes spiced, fruit-flavoured and barrel-aged rum styles." }],
    finalVerdict: "Twin Fin suits a sunny long drink with something hot from the grill.",
    metaTitle: "Twin Fin Rum Guide | BevOry", metaDescription: "Explore Twin Fin rum from Cornwall, fruit flavours and easy serves. Check city prices on BevOry.",
  },
  "two-ocean": {
    description: "Two Oceans is a South African wine range from the Western Cape, with Sauvignon Blanc and Shiraz among its bottles. Its name points to the Atlantic and Indian Oceans around the Cape.",
    story: "Cape vineyards feel the effect of maritime air, especially the cool Atlantic current. Two Oceans uses that coastal identity to connect accessible white and red wines with their Western Cape origin.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Lime and yellow apple keep the white brisk." }, { title: "Shiraz", description: "Dark berries and pepper give the red a more rounded finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Sauvignon Blanc well and pour Shiraz slightly cool." }, { subheading: "Food", description: "The white works with fish tikka; the red takes pepper chicken." }],
    pairingIdeas: [{ title: "Cape pairings", items: ["fish tikka", "pepper chicken", "grilled aubergine", "roast lamb"] }],
    whyChoose: "A straightforward way to taste the Western Cape in both a crisp white and a soft red.",
    faqs: [{ question: "Where is Two Oceans wine from?", answer: "The range is from South Africa's Western Cape." }, { question: "Does Two Oceans make red and white wine?", answer: "Yes. Sauvignon Blanc and Shiraz are among its white and red wines." }],
    finalVerdict: "Two Oceans Sauvignon Blanc is a handy pick for seafood; Shiraz belongs beside a smoky main course.",
    metaTitle: "Two Oceans Wine Guide | BevOry", metaDescription: "Discover Two Oceans Sauvignon Blanc and Shiraz from the Western Cape. Check city prices on BevOry.",
  },
  ulithorne: {
    description: "Ulithorne is a McLaren Vale winery in South Australia, working with Shiraz, Grenache and other red varieties. Its Epoch rose brings a lighter side to the range.",
    story: "Bob Whiting planted the original Ulithorne vineyard in 1950 on terraced ground above the Onkaparinga River. Rose Kentish and Sam Harrison took it on in 1997; the estate is now under CW Wines.",
    tastingNotes: [{ title: "Epoch Rose", description: "Fresh red berries and a dry finish make it a food-friendly rose." }, { title: "Shiraz", description: "Dark plum and warm spice mark the fuller McLaren Vale reds." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve the rose well chilled in a white-wine glass." }, { subheading: "Food", description: "Try it with tandoori prawns; save Shiraz for mutton seekh." }],
    pairingIdeas: [{ title: "McLaren Vale table", items: ["tandoori prawns", "mutton seekh", "roast beetroot", "grilled lamb"] }],
    whyChoose: "One McLaren Vale vineyard offers both a fresh rose and more muscular reds.",
    faqs: [{ question: "Where is Ulithorne grown?", answer: "Ulithorne is based in South Australia's McLaren Vale." }, { question: "Does Ulithorne make rose?", answer: "Yes. Epoch is its rose wine." }],
    finalVerdict: "Epoch rose is the Ulithorne bottle for a warm afternoon and a plate of seafood.",
    metaTitle: "Ulithorne Wine Guide | BevOry", metaDescription: "Explore Ulithorne's McLaren Vale rose and Shiraz with food pairings. Check city prices on BevOry.",
  },
  valiano: {
    description: "Valiano is a Chianti Classico estate in Castelnuovo Berardenga, Tuscany, within the Piccini family's wineries. Its reds centre on Sangiovese, including organic Chianti Classico bottlings.",
    story: "The Piccini family founded its wine business in 1882 and later built a group of estates across Italy. Valiano is its Chianti Classico address, where individual vineyard sites appear on several labels.",
    tastingNotes: [{ title: "Sangiovese", description: "Cherry and violet give the red a distinctly Tuscan opening." }, { title: "Chianti Classico", description: "Fresh acidity and firm tannin keep the berry fruit in shape." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour the red a little cool and give it time in a broad glass." }, { subheading: "Food", description: "Try it with lamb rogan josh or mushroom ragout." }],
    pairingIdeas: [{ title: "Tuscan table", items: ["lamb rogan josh", "mushroom ragout", "tomato pasta", "aged pecorino"] }],
    whyChoose: "A Piccini estate that makes Chianti Classico feel tied to its own vineyards.",
    faqs: [{ question: "Where is Valiano wine made?", answer: "Valiano is in Castelnuovo Berardenga, within Tuscany's Chianti Classico area." }, { question: "Who owns Valiano?", answer: "It is one of the Piccini family's Italian wine estates." }],
    finalVerdict: "Valiano Chianti Classico is at home with tomato, herbs and slow-cooked lamb.",
    metaTitle: "Valiano Wine Guide | BevOry", metaDescription: "Meet Valiano Chianti Classico from Tuscany, Sangiovese notes and pairings. Check city prices on BevOry.",
  },
  varchas: {
    description: "Varchas is an American whiskey label from Shankar Distillers in Michigan. Its bourbon and rye use American whiskey styles while the name and eagle emblem draw on the founder's Mysore heritage.",
    story: "Founder Varchasvi Shankar built his first businesses in technology before pursuing whiskey in the United States. The double-headed Mysore eagle and American eagle stopper bring the two parts of his story onto the bottle.",
    tastingNotes: [{ title: "Bourbon", description: "Sweet corn character and oak make the bourbon the rounder pour." }, { title: "Rye", description: "Grain spice gives the rye a firmer edge in a whiskey cocktail." }],
    howToEnjoy: [{ subheading: "Old Fashioned", description: "Stir the bourbon with bitters and a little sugar over ice." }, { subheading: "Food", description: "Try rye with mutton seekh or smoked almonds." }],
    pairingIdeas: [{ title: "Whiskey snacks", items: ["mutton seekh", "smoked almonds", "barbecue ribs", "dark chocolate"] }],
    whyChoose: "An American whiskey with a personal link to Mysore rather than a borrowed Indian origin claim.",
    faqs: [{ question: "Is Varchas whiskey made in India?", answer: "Varchas is an American whiskey label from Michigan-based Shankar Distillers." }, { question: "Who founded Varchas?", answer: "Varchasvi Shankar founded the brand." }],
    finalVerdict: "Varchas bourbon makes a rounded Old Fashioned, while the rye brings more spice.",
    metaTitle: "Varchas Whiskey Guide | BevOry", metaDescription: "Explore Varchas bourbon and rye from Michigan, their serves and pairings. Check city prices on BevOry.",
  },
  "vecchia-romagna": {
    description: "Vecchia Romagna is an Italian brandy from Bologna, made from distilled wine and aged before blending. Its triangular bottle carries a Bacchus emblem.",
    story: "Jean Buton established an experimental distillery in Bologna in 1820. The Vecchia Romagna name and triangular bottle arrived in 1939; Gruppo Montenegro acquired the company in 1999.",
    tastingNotes: [{ title: "Wine spirit", description: "Dried fruit and a soft grape warmth sit under the oak." }, { title: "Matured styles", description: "Longer-aged bottlings add vanilla, spice and deeper wood notes." }],
    howToEnjoy: [{ subheading: "After dinner", description: "Pour a small measure in a tulip glass at room temperature." }, { subheading: "Food", description: "Try it with dark chocolate or almond biscotti." }],
    pairingIdeas: [{ title: "After dinner", items: ["dark chocolate", "almond biscotti", "spiced pecans", "aged gouda"] }],
    whyChoose: "Bologna's long-running wine brandy in a bottle few drinkers mistake for another.",
    faqs: [{ question: "Where is Vecchia Romagna from?", answer: "It originated in Bologna, Italy." }, { question: "Is Vecchia Romagna cognac?", answer: "No. It is Italian brandy made from wine spirit." }],
    finalVerdict: "Vecchia Romagna is a measured finish to a meal, especially with something chocolatey.",
    metaTitle: "Vecchia Romagna Brandy Guide | BevOry", metaDescription: "Discover Vecchia Romagna brandy from Bologna, oak notes and pairings. Check city prices on BevOry.",
  },
  "vecchio-amaro-del-capo": {
    description: "Vecchio Amaro del Capo is a herbal liqueur made by the Caffo family in Calabria, southern Italy. Its bitter-sweet profile comes from an infusion of Calabrian herbs, fruit and roots.",
    story: "Generations of Caffo distillers developed the family's amaro recipe around ingredients linked to Calabria. The label became the distillery's best-known after-dinner drink.",
    tastingNotes: [{ title: "Citrus peel", description: "Orange and mandarin brighten the first sip." }, { title: "Herbal finish", description: "Liquorice and bitter herbs give the sweetness a firm counterweight." }],
    howToEnjoy: [{ subheading: "Cold", description: "Serve in a small chilled glass after dinner." }, { subheading: "Food", description: "Try it with candied orange or dark chocolate." }],
    pairingIdeas: [{ title: "Bitter and sweet", items: ["dark chocolate", "candied orange", "almond biscotti", "spiced walnuts"] }],
    whyChoose: "Calabrian citrus and herbs make this amaro taste rooted in a place.",
    faqs: [{ question: "Who makes Vecchio Amaro del Capo?", answer: "It is made by the Caffo family distillery in Calabria." }, { question: "How is it usually served?", answer: "A small, very cold after-dinner pour is a familiar way to drink it." }],
    finalVerdict: "Give Vecchio Amaro del Capo a cold glass and let its orange and herbal bitterness linger.",
    metaTitle: "Vecchio Amaro del Capo Guide | BevOry", metaDescription: "Explore Calabria's Vecchio Amaro del Capo, herbal notes and dessert matches. Check city prices on BevOry.",
  },
  vietti: {
    description: "Vietti is a winery in Castiglione Falletto in Italy's Langhe hills. Its Piedmont wines include Barolo from Nebbiolo and Barbera from local vineyard sites.",
    story: "Carlo Vietti began the cellar in the late nineteenth century. Alfredo Currado later helped advance single-vineyard Barolo and bottled Roero Arneis as a varietal wine, while artist-designed labels became another house signature.",
    tastingNotes: [{ title: "Barolo", description: "Rose, red cherry and firm tannin give Nebbiolo its lift and grip." }, { title: "Barbera", description: "Dark cherry and lively acidity make a more immediate red." }],
    howToEnjoy: [{ subheading: "Air", description: "Give Barolo time in a large glass; pour Barbera a little cool." }, { subheading: "Food", description: "Barbera suits mushroom risotto, while Barolo takes lamb." }],
    pairingIdeas: [{ title: "Piedmont table", items: ["mushroom risotto", "lamb kebabs", "truffle pasta", "aged parmesan"] }],
    whyChoose: "A Langhe cellar associated with both vineyard-specific Barolo and the return of Roero Arneis.",
    faqs: [{ question: "Where is Vietti winery?", answer: "It is in Castiglione Falletto in Piedmont's Langhe region." }, { question: "Which grape makes Vietti Barolo?", answer: "Barolo is made from Nebbiolo." }],
    finalVerdict: "Vietti gives patient red-wine drinkers a strong reason to explore the Langhe.",
    metaTitle: "Vietti Wine Guide | BevOry", metaDescription: "Discover Vietti Barolo and Barbera from the Langhe with food pairings. Check city prices on BevOry.",
  },
  "villa-antinori": {
    description: "Villa Antinori is a Tuscan wine range from the Antinori family, with both red and white bottlings. The red takes Sangiovese as its backbone.",
    story: "Niccolo Antinori first used the Villa Antinori name in 1928 for a red inspired by Chianti Classico. The family added a white in 1931, making the villa name a lasting part of its everyday wine history.",
    tastingNotes: [{ title: "Rosso", description: "Black cherry and soft spice meet the fresh edge of Sangiovese." }, { title: "Bianco", description: "The white runs toward orchard fruit and a clean citrus finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour Rosso slightly cool; chill Bianco before opening." }, { subheading: "Food", description: "The red suits tomato-braised lamb and the white grilled fish." }],
    pairingIdeas: [{ title: "Tuscan dinner", items: ["tomato-braised lamb", "grilled fish", "mushroom pasta", "pecorino"] }],
    whyChoose: "An Antinori range with nearly a century of family history on the label.",
    faqs: [{ question: "Who makes Villa Antinori?", answer: "Marchesi Antinori makes the Villa Antinori wines in Tuscany." }, { question: "Is Villa Antinori only a red wine?", answer: "No. The range includes both Rosso and Bianco." }],
    finalVerdict: "Villa Antinori Rosso is the bottle to bring to a long, savoury dinner.",
    metaTitle: "Villa Antinori Wine Guide | BevOry", metaDescription: "Explore Antinori's Tuscan Villa Rosso and Bianco with serving ideas. Check city prices on BevOry.",
  },
  "villa-maria": {
    description: "Villa Maria is a New Zealand winery founded by George Fistonich, now part of Indevin. Its wines span Marlborough Sauvignon Blanc and reds from other New Zealand regions.",
    story: "Fistonich leased five acres from his father in 1961 and made the first vintage the following year. The winery later became an early major adopter of screw-cap closures before Indevin acquired it in 2021.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Passion fruit, citrus and green herbs make the Marlborough white brisk." }, { title: "Red wines", description: "The red range moves toward cherry, darker fruit and softer spice." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Sauvignon Blanc cold in a clean white-wine glass." }, { subheading: "Food", description: "Try it with tandoori fish or coriander prawns." }],
    pairingIdeas: [{ title: "New Zealand table", items: ["tandoori fish", "coriander prawns", "goat cheese", "lemon chicken"] }],
    whyChoose: "A New Zealand wine name that helped put Marlborough Sauvignon Blanc on global tables.",
    faqs: [{ question: "Who founded Villa Maria?", answer: "George Fistonich founded it in 1961." }, { question: "Who owns Villa Maria now?", answer: "New Zealand wine company Indevin acquired Villa Maria in 2021." }],
    finalVerdict: "Villa Maria Sauvignon Blanc brings a sharp, herbal lift to seafood.",
    metaTitle: "Villa Maria Wine Guide | BevOry", metaDescription: "Discover Villa Maria Sauvignon Blanc, New Zealand roots and pairings. Check city prices on BevOry.",
  },
  "villa-sandi": {
    description: "Villa Sandi is a wine house in Italy's Veneto, closely associated with Prosecco. The Moretti Polegato family also makes still wines and traditional-method sparkling wine.",
    story: "Mario Polegato bought vineyards in the 1920s, beginning the family's wine business. His descendants acquired the seventeenth-century Villa Sandi in the late 1970s and used its restored cellars for sparkling wines.",
    tastingNotes: [{ title: "Prosecco", description: "Pear and green apple meet a fine, lively mousse." }, { title: "Cartizze", description: "Riper orchard fruit makes this hillside Prosecco a fuller pour." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve sparkling bottles cold in a tulip-shaped glass." }, { subheading: "Food", description: "Prosecco suits tandoori prawns or salty potato croquettes." }],
    pairingIdeas: [{ title: "With bubbles", items: ["tandoori prawns", "potato croquettes", "fried calamari", "salted almonds"] }],
    whyChoose: "A family Prosecco house with vineyards and an old Veneto villa behind the name.",
    faqs: [{ question: "Where is Villa Sandi based?", answer: "The winery is based in Italy's Veneto region." }, { question: "Does Villa Sandi only make Prosecco?", answer: "No. Its range also includes still wines and traditional-method sparkling wine." }],
    finalVerdict: "Villa Sandi Prosecco is a crisp partner for fried or lightly spiced starters.",
    metaTitle: "Villa Sandi Prosecco Guide | BevOry", metaDescription: "Explore Villa Sandi Prosecco, its Veneto roots and food pairings. Check city prices on BevOry.",
  },
  "vina-albali": {
    description: "Vina Albali is a Spanish wine range from Felix Solis Avantis in Valdepenas. Its bottles include Tempranillo-led reds as well as other familiar grape varieties.",
    story: "The Solis family built its Valdepenas winery into a large Spanish wine producer. Vina Albali became one of the family's labels for bringing that region's reds to a wider audience.",
    tastingNotes: [{ title: "Tempranillo", description: "Red cherry and gentle spice keep the red approachable." }, { title: "Cabernet Sauvignon", description: "Dark fruit and firmer tannin give a different shape to the range." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the red slightly cool in an everyday wine glass." }, { subheading: "Food", description: "Try it with tomato pasta or chicken tikka." }],
    pairingIdeas: [{ title: "Spanish red table", items: ["tomato pasta", "chicken tikka", "grilled mushrooms", "manchego"] }],
    whyChoose: "An accessible introduction to reds from Spain's Valdepenas region.",
    faqs: [{ question: "Who makes Vina Albali?", answer: "Felix Solis Avantis makes the wine in Spain." }, { question: "Where does Vina Albali come from?", answer: "The label is rooted in Valdepenas, in central Spain." }],
    finalVerdict: "Vina Albali is an easy Spanish red to open with a weekday dinner.",
    metaTitle: "Vina Albali Wine Guide | BevOry", metaDescription: "Discover Vina Albali from Valdepenas, Tempranillo notes and pairings. Check city prices on BevOry.",
  },
  "vina-esmeralda": {
    description: "Vina Esmeralda is a fragrant Spanish white wine from Familia Torres in Catalonia. Muscat of Alexandria is central to the wine's Mediterranean character.",
    story: "Torres named the wine for the emerald colour of the nearby sea. Its vineyards and floral grape choice give the label a lighter, more aromatic place in the family's range.",
    tastingNotes: [{ title: "Flowers", description: "Rose and orange blossom make the nose immediately expressive." }, { title: "Citrus", description: "Fresh citrus keeps the Muscat fruit from feeling heavy." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a medium white-wine glass." }, { subheading: "Food", description: "Its perfume suits Thai-style prawns or lightly spiced paneer." }],
    pairingIdeas: [{ title: "Aromatic white", items: ["Thai-style prawns", "paneer tikka", "citrus salad", "mild goat cheese"] }],
    whyChoose: "A floral Torres white that offers a different route into Spanish wine.",
    faqs: [{ question: "Who makes Vina Esmeralda?", answer: "Familia Torres makes it in Catalonia, Spain." }, { question: "What grape is in Vina Esmeralda?", answer: "Muscat of Alexandria is a key grape in the wine." }],
    finalVerdict: "Vina Esmeralda is especially good when dinner has herbs, citrus and gentle heat.",
    metaTitle: "Vina Esmeralda Wine Guide | BevOry", metaDescription: "Explore Torres Vina Esmeralda, floral Muscat notes and food matches. Check city prices on BevOry.",
  },
  "vina-pomal": {
    description: "Vina Pomal is a Rioja wine label from Bodegas Bilbainas in Haro, Spain. Tempranillo is the core red grape, with Crianza and Reserva among its well-known styles.",
    story: "Bodegas Bilbainas took shape in Haro at the start of the twentieth century. Vina Pomal grew into its flagship Rioja name, drawing on vineyards around the town and the cellar's long ageing tradition.",
    tastingNotes: [{ title: "Crianza", description: "Cherry and vanilla bring fruit and oak into easy balance." }, { title: "Reserva", description: "Darker fruit, tobacco and firmer tannin make a slower red." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour Rioja a little cool and let Reserva open in the glass." }, { subheading: "Food", description: "Crianza suits mutton seekh; Reserva works with lamb shoulder." }],
    pairingIdeas: [{ title: "Rioja table", items: ["mutton seekh", "roast lamb shoulder", "mushroom rice", "aged manchego"] }],
    whyChoose: "A Haro Rioja label with a useful step up from Crianza to Reserva.",
    faqs: [{ question: "Where is Vina Pomal made?", answer: "Bodegas Bilbainas makes it in Haro, Rioja." }, { question: "Which grape leads Vina Pomal red wines?", answer: "Tempranillo is the central red grape." }],
    finalVerdict: "Vina Pomal Crianza belongs beside grilled food; Reserva asks for a longer dinner.",
    metaTitle: "Vina Pomal Rioja Guide | BevOry", metaDescription: "Explore Vina Pomal Crianza and Reserva from Haro with pairings. Check city prices on BevOry.",
  },
  vivir: {
    description: "VIVIR is a British-founded tequila label made from Blue Weber agave in Jalisco, Mexico. Its range includes Blanco, Reposado and Anejo, plus a separate coffee liqueur.",
    story: "The brand works with Casa Maestri in Jalisco and agave grown in the state's highlands. Its tequila is made in Mexico even though the company behind the label began in Britain.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus make a clean start." }, { title: "Reposado", description: "Oak softens the agave with vanilla and warm spice." }],
    howToEnjoy: [{ subheading: "Sip or mix", description: "Try Blanco neat, then in a Margarita with fresh lime." }, { subheading: "Food", description: "Serve beside fish tacos or tandoori prawns." }],
    pairingIdeas: [{ title: "Agave table", items: ["fish tacos", "tandoori prawns", "grilled corn", "salted cashews"] }],
    whyChoose: "Highland Jalisco agave gives VIVIR a clear Mexican identity behind a British-founded label.",
    faqs: [{ question: "Where is VIVIR tequila made?", answer: "It is produced at Casa Maestri in Jalisco, Mexico." }, { question: "Is VIVIR Cafe a tequila?", answer: "It is a separate coffee liqueur in the VIVIR range." }],
    finalVerdict: "Start with VIVIR Blanco when you want the agave to do the talking.",
    metaTitle: "VIVIR Tequila Guide | BevOry", metaDescription: "Meet VIVIR tequila from Jalisco, Blanco and Reposado serves and pairings. Check city prices on BevOry.",
  },
  volare: {
    description: "Volare is an Italian cocktail-liqueur range from Rossi d'Asiago. Blue Curacao, Triple Sec and fruit flavours are made for measured use in mixed drinks.",
    story: "The distillery revisited recipes from the 1950s for a modern bar range. Its bottle has a built-in pourer, a practical detail aimed at bartenders making repeated cocktails.",
    tastingNotes: [{ title: "Blue Curacao", description: "Bitter-orange peel gives a bright citrus core beneath the blue colour." }, { title: "Triple Sec", description: "Orange oils make a drier citrus accent for a mixed drink." }],
    howToEnjoy: [{ subheading: "Mix", description: "Measure Blue Curacao with white rum and citrus for a vivid long drink." }, { subheading: "Food", description: "A citrus-led cocktail works with chilli prawns or fried calamari." }],
    pairingIdeas: [{ title: "Cocktail snacks", items: ["chilli prawns", "fried calamari", "salted peanuts", "crispy paneer"] }],
    whyChoose: "An Italian bar range that puts specific fruit and citrus flavours within easy reach.",
    faqs: [{ question: "Who makes Volare liqueurs?", answer: "Rossi d'Asiago makes the range in Italy." }, { question: "Is Volare Blue Curacao a plain spirit?", answer: "No. It is an orange-flavoured cocktail liqueur." }],
    finalVerdict: "Volare works best as a measured flavour in a cocktail, not as a large neat pour.",
    metaTitle: "Volare Liqueur Guide | BevOry", metaDescription: "Explore Volare Blue Curacao and Triple Sec, cocktails and snack pairings. Check city prices on BevOry.",
  },
  "volcan-de-mi-tierra": {
    description: "Volcan de mi Tierra is a tequila label from Jalisco, Mexico, named for the Tequila volcano. It belongs to LVMH's wines and spirits portfolio.",
    story: "The eruption of the Tequila volcano shaped the land around the region long before blue agave was planted there. Volcan de mi Tierra builds its identity on that landscape and makes tequila from Jalisco agave.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus lead a clean, bright sip." }, { title: "Reposado", description: "Oak brings a softer vanilla edge to the agave." }],
    howToEnjoy: [{ subheading: "Neat", description: "Try Blanco in a small glass before mixing it with lime." }, { subheading: "Food", description: "Pair with fish tacos or grilled paneer." }],
    pairingIdeas: [{ title: "Jalisco plates", items: ["fish tacos", "grilled paneer", "tandoori prawns", "roasted corn"] }],
    whyChoose: "A tequila whose name points directly to the volcanic ground around its home region.",
    faqs: [{ question: "Where is Volcan de mi Tierra from?", answer: "It is a tequila from Jalisco, Mexico." }, { question: "What does the name refer to?", answer: "It refers to the Tequila volcano in Jalisco." }],
    finalVerdict: "Volcan de mi Tierra Blanco makes a crisp agave-led first pour.",
    metaTitle: "Volcan de mi Tierra Tequila Guide | BevOry", metaDescription: "Discover Volcan de mi Tierra tequila from Jalisco, serving ideas and pairings. Check city prices on BevOry.",
  },
  vollereaux: {
    description: "Vollereaux is a family Champagne house in Pierry, south of Epernay, France. Its range includes Brut styles and the Chardonnay-led Cuvee Marguerite.",
    story: "The family's Champagne roots in Pierry reach back to 1805. Successive generations kept the house independent while developing wines that draw on vineyards around the Coteaux Sud d'Epernay.",
    tastingNotes: [{ title: "Cuvee Marguerite", description: "Fine bubbles carry citrus, floral notes and a touch of toasted hazelnut." }, { title: "Brut", description: "Orchard fruit and fresh acidity make the house's dry style lively." }],
    howToEnjoy: [{ subheading: "Tulip glass", description: "Serve chilled in a tulip glass rather than an overfilled flute." }, { subheading: "Food", description: "Try it with tandoori fish or crisp potato croquettes." }],
    pairingIdeas: [{ title: "Champagne table", items: ["tandoori fish", "potato croquettes", "grilled prawns", "soft brie"] }],
    whyChoose: "An independent Pierry house with a Champagne history reaching back more than two centuries.",
    faqs: [{ question: "Where is Vollereaux based?", answer: "The house is in Pierry, near Epernay in Champagne." }, { question: "What is Cuvee Marguerite?", answer: "It is a Vollereaux prestige cuvee led by Chardonnay." }],
    finalVerdict: "Vollereaux makes a compelling Champagne for a seafood-led dinner.",
    metaTitle: "Vollereaux Champagne Guide | BevOry", metaDescription: "Explore Vollereaux Champagne from Pierry, Cuvee Marguerite and pairings. Check city prices on BevOry.",
  },
  warwick: {
    description: "Warwick is a wine estate in Stellenbosch, South Africa. Its range includes Cabernet Sauvignon-led reds and the Trilogy blend associated with winemaker Norma Ratcliffe.",
    story: "The Ratcliffe family took on the property in the 1960s. Norma Ratcliffe became a central figure in its winemaking, helping turn a fruit farm into a recognised Stellenbosch wine estate.",
    tastingNotes: [{ title: "Cabernet", description: "Blackcurrant and cedar give the red its firm shape." }, { title: "Trilogy", description: "Dark fruit and spice make the blend a fuller dinner wine." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour the red a little cool and allow Trilogy time to open." }, { subheading: "Food", description: "Try Cabernet with mutton seekh or grilled lamb." }],
    pairingIdeas: [{ title: "Stellenbosch table", items: ["mutton seekh", "grilled lamb", "roast mushrooms", "aged cheddar"] }],
    whyChoose: "A Stellenbosch estate whose Cabernet history is tied to Norma Ratcliffe.",
    faqs: [{ question: "Where is Warwick wine made?", answer: "Warwick is based in Stellenbosch, South Africa." }, { question: "Who created Warwick Trilogy?", answer: "Norma Ratcliffe is closely associated with the creation of Trilogy." }],
    finalVerdict: "Warwick Cabernet deserves a savoury meal and a little time in the glass.",
    metaTitle: "Warwick Wine Guide | BevOry", metaDescription: "Explore Warwick Cabernet and Trilogy from Stellenbosch with pairings. Check city prices on BevOry.",
  },
  wente: {
    description: "Wente is a California wine producer based in the Livermore Valley, closely associated with Chardonnay. The family also makes red wines from its California vineyards.",
    story: "C.H. Wente established the winery in 1883. His son Ernest brought Chardonnay cuttings from France in 1912, beginning the lineage of vines now widely known as the Wente Clone.",
    tastingNotes: [{ title: "Chardonnay", description: "Apple and citrus lead, with a broader texture in oak-aged bottlings." }, { title: "Cabernet Sauvignon", description: "Dark berries and firmer tannin take the range into red-wine territory." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Chardonnay without making it icy; pour Cabernet lightly cool." }, { subheading: "Food", description: "Chardonnay suits roast chicken or malai tikka." }],
    pairingIdeas: [{ title: "California table", items: ["malai tikka", "roast chicken", "grilled corn", "mutton kebabs"] }],
    whyChoose: "A Livermore family winery with an unusually direct link to California Chardonnay history.",
    faqs: [{ question: "Where is Wente Vineyards?", answer: "The family winery began in California's Livermore Valley." }, { question: "Why is Wente important to Chardonnay?", answer: "Ernest Wente brought French Chardonnay cuttings to Livermore in 1912, influencing later California plantings." }],
    finalVerdict: "Wente Chardonnay makes a useful bridge between a fresh white and a richer dinner wine.",
    metaTitle: "Wente Wine Guide | BevOry", metaDescription: "Discover Wente Chardonnay, Livermore Valley history and pairings. Check city prices on BevOry.",
  },
  "west-cork": {
    description: "West Cork is an Irish whiskey label made by West Cork Distillers in Skibbereen. Its bottles include blended, single malt and cask-finished whiskeys.",
    story: "Childhood friends John O'Connell, Ger McCarthy and Denis McCarthy founded the distillery in 2003. They began with two small stills in a room behind Denis's house before moving to Skibbereen in 2014.",
    tastingNotes: [{ title: "Bourbon cask", description: "Vanilla and orchard fruit show the lighter side of the whiskey." }, { title: "Cask finishes", description: "Different finishing barrels can add dried fruit or deeper spice." }],
    howToEnjoy: [{ subheading: "Neat", description: "Begin with a small neat pour, adding a drop of water if needed." }, { subheading: "Food", description: "Try with smoked almonds or grilled chicken tikka." }],
    pairingIdeas: [{ title: "Irish whiskey snacks", items: ["smoked almonds", "chicken tikka", "apple tart", "aged cheddar"] }],
    whyChoose: "A Skibbereen distillery whose founders built an Irish whiskey business from two small stills.",
    faqs: [{ question: "Where is West Cork whiskey made?", answer: "West Cork Distillers makes it in Skibbereen, Ireland." }, { question: "Who founded West Cork Distillers?", answer: "John O'Connell, Ger McCarthy and Denis McCarthy founded the distillery in 2003." }],
    finalVerdict: "West Cork's lighter cask styles are an inviting first look at Irish whiskey.",
    metaTitle: "West Cork Whiskey Guide | BevOry", metaDescription: "Explore West Cork Irish whiskey, its Skibbereen story and serves. Check city prices on BevOry.",
  },
  "west-malle": {
    description: "Westmalle is a Belgian Trappist beer brewed within the Abbey of Our Lady of the Sacred Heart. Its beers include the dark Dubbel and golden Tripel.",
    story: "Brewing began at the abbey in 1836. The monks developed the stronger Dubbel in 1926 and introduced the Tripel when a new brewing hall opened in 1934.",
    tastingNotes: [{ title: "Dubbel", description: "Dark fruit, malt and a soft caramel edge make the beer rounded." }, { title: "Tripel", description: "Fruit-led yeast notes and a dry, lightly bitter finish give the golden beer lift." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour into a clean chalice, leaving room for the head." }, { subheading: "Food", description: "Dubbel suits pepper chicken; Tripel handles fried seafood." }],
    pairingIdeas: [{ title: "Abbey beer table", items: ["pepper chicken", "fried seafood", "mushroom croquettes", "aged gouda"] }],
    whyChoose: "Abbey-brewed beers that define two enduring Belgian styles.",
    faqs: [{ question: "Is Westmalle a Trappist beer?", answer: "Yes. It is brewed within the Westmalle abbey under Trappist supervision." }, { question: "What is the difference between Dubbel and Tripel?", answer: "Dubbel is dark and malt-led; Tripel is golden, fruitier and drier." }],
    finalVerdict: "Try Westmalle Dubbel with a savoury meal and Tripel with something crisp and salty.",
    metaTitle: "Westmalle Beer Guide | BevOry", metaDescription: "Discover Westmalle Dubbel and Tripel, Trappist brewing and pairings. Check city prices on BevOry.",
  },
  "william-hardy": {
    description: "William Hardy is an Australian wine label within the Hardys family range. The name appears on Chardonnay and other wines associated with South Australian fruit.",
    story: "Hardys began with Thomas Hardy's nineteenth-century winery near Adelaide. The William Hardy label carries the family name into a modern range, distinct from its older regional and heritage bottlings.",
    tastingNotes: [{ title: "Chardonnay", description: "Pear and golden apple give the white its ripe-fruit centre." }, { title: "Citrus finish", description: "A fresh edge keeps the fuller fruit from feeling heavy." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Chardonnay cool in a medium white-wine glass." }, { subheading: "Food", description: "Try it with malai tikka or lemon-roast chicken." }],
    pairingIdeas: [{ title: "With Chardonnay", items: ["malai tikka", "lemon-roast chicken", "grilled fish", "butter mushrooms"] }],
    whyChoose: "An Australian Chardonnay carrying one of the country's longest-running wine family names.",
    faqs: [{ question: "Is William Hardy part of Hardys Wines?", answer: "Yes. William Hardy is a label within the Hardys wine range." }, { question: "What style is William Hardy Chardonnay?", answer: "It is a fruit-led Australian white with pear and apple notes." }],
    finalVerdict: "William Hardy Chardonnay works well when a white needs enough body for dinner.",
    metaTitle: "William Hardy Wine Guide | BevOry", metaDescription: "Explore William Hardy Chardonnay, Australian origins and food pairings. Check city prices on BevOry.",
  },
  "william-peel": {
    description: "William Peel is a blended Scotch whisky brand in the Marie Brizard Wine & Spirits portfolio. Its range is built for straightforward whisky pours and mixed drinks.",
    story: "The French spirits group developed William Peel into a widely recognised Scotch label in its home market. Although the owner is French, the whisky itself is Scotch, made under Scotland's whisky rules.",
    tastingNotes: [{ title: "Malt and grain", description: "A soft cereal sweetness leads the blend." }, { title: "Oak", description: "Gentle vanilla and spice round out the finish." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over plenty of ice and lengthen with soda." }, { subheading: "Food", description: "Serve with mutton seekh or roasted masala peanuts." }],
    pairingIdeas: [{ title: "Scotch snacks", items: ["mutton seekh", "masala peanuts", "smoked cheese", "grilled mushrooms"] }],
    whyChoose: "A Scotch blend with an easygoing character and a strong following in France.",
    faqs: [{ question: "Is William Peel Scotch?", answer: "Yes. William Peel is a blended Scotch whisky." }, { question: "Who owns William Peel?", answer: "It is part of Marie Brizard Wine & Spirits." }],
    finalVerdict: "William Peel is best approached as a simple highball or a relaxed neat pour.",
    metaTitle: "William Peel Whisky Guide | BevOry", metaDescription: "Explore William Peel blended Scotch, easy serves and food matches. Check city prices on BevOry.",
  },
  "wirra-wirra": {
    description: "Wirra Wirra is a winery in McLaren Vale, South Australia, making Shiraz and other regional wines. Its name comes from an Aboriginal expression often translated as 'among the gum trees'.",
    story: "Robert Strangways Wigley established the original winery in 1894. The property later fell quiet before being revived in the twentieth century, keeping McLaren Vale at the heart of its wines.",
    tastingNotes: [{ title: "Shiraz", description: "Dark plum and pepper make the red generous but savoury." }, { title: "Grenache", description: "Red berries and softer tannins give a lighter route through the range." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour Shiraz a little cool in a broad glass." }, { subheading: "Food", description: "It works with lamb kebabs or smoky aubergine." }],
    pairingIdeas: [{ title: "McLaren Vale table", items: ["lamb kebabs", "smoky aubergine", "roast beef", "aged cheddar"] }],
    whyChoose: "A McLaren Vale name with nineteenth-century roots and a firm grip on regional reds.",
    faqs: [{ question: "Where is Wirra Wirra winery?", answer: "It is in McLaren Vale, South Australia." }, { question: "When was Wirra Wirra established?", answer: "Robert Strangways Wigley founded the original winery in 1894." }],
    finalVerdict: "Wirra Wirra Shiraz belongs beside food with char and spice.",
    metaTitle: "Wirra Wirra Wine Guide | BevOry", metaDescription: "Discover Wirra Wirra Shiraz from McLaren Vale with serving ideas. Check city prices on BevOry.",
  },
  wolfberger: {
    description: "Wolfberger is an Alsace wine cooperative based in Eguisheim, France. Its members make varietal wines, Cremant d'Alsace and regional spirits.",
    story: "Winegrowers in Eguisheim joined forces in 1902, forming one of Alsace's early cooperatives. The Wolfberger name later grew from that shared cellar into a broad range of Alsatian wines and sparkling bottles.",
    tastingNotes: [{ title: "Riesling", description: "Citrus and stony acidity make a focused white." }, { title: "Cremant d'Alsace", description: "Apple and fine bubbles give the sparkling wine a fresh finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Riesling and Cremant in separate clean glasses." }, { subheading: "Food", description: "Riesling cuts through tandoori fish; Cremant suits fried starters." }],
    pairingIdeas: [{ title: "Alsace table", items: ["tandoori fish", "fried prawns", "onion tart", "soft goat cheese"] }],
    whyChoose: "A growers' cooperative that brings Alsace still wines and bubbles under one name.",
    faqs: [{ question: "Where is Wolfberger based?", answer: "Its cooperative cellar is in Eguisheim, Alsace." }, { question: "Does Wolfberger make sparkling wine?", answer: "Yes. Cremant d'Alsace is part of its range." }],
    finalVerdict: "Wolfberger Riesling is a crisp choice when dinner brings spice and citrus.",
    metaTitle: "Wolfberger Wine Guide | BevOry", metaDescription: "Explore Wolfberger Riesling and Cremant from Alsace with pairings. Check city prices on BevOry.",
  },
  wolfblass: {
    description: "Wolf Blass is an Australian wine label founded in the Barossa Valley by German-born winemaker Wolfgang Blass. Its colour-coded labels cover a range of reds and whites.",
    story: "Blass arrived in the Barossa in 1961 and established his own wine business in 1966. Yellow Label followed that first vintage; Grey Label Cabernet Sauvignon Shiraz appeared soon after.",
    tastingNotes: [{ title: "Yellow Label red", description: "Ripe berry fruit and soft spice make it an approachable dinner red." }, { title: "Chardonnay", description: "Peach and citrus give the white a rounded start." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour reds slightly cool and chill Chardonnay." }, { subheading: "Food", description: "The red suits pepper chicken; Chardonnay suits malai tikka." }],
    pairingIdeas: [{ title: "Australian table", items: ["pepper chicken", "malai tikka", "grilled lamb", "roast cauliflower"] }],
    whyChoose: "A Barossa-founded label whose colour system makes a broad Australian range easy to navigate.",
    faqs: [{ question: "Who founded Wolf Blass?", answer: "Wolfgang Blass established the wine business in 1966." }, { question: "What does Yellow Label mean?", answer: "Yellow Label is one of Wolf Blass's established wine ranges." }],
    finalVerdict: "Wolf Blass gives an uncomplicated entry into Australian reds without losing the founder's history.",
    metaTitle: "Wolf Blass Wine Guide | BevOry", metaDescription: "Explore Wolf Blass Yellow Label, Barossa roots and food pairings. Check city prices on BevOry.",
  },
  wolfburn: {
    description: "Wolfburn is a single malt Scotch whisky distillery in Thurso, Caithness. Northland and Morven show different sides of its Highland spirit.",
    story: "William Smith founded the original Wolfburn distillery beside a stream in 1821. The modern distillery was built nearby, taking its name and inspiration from the earlier Thurso site.",
    tastingNotes: [{ title: "Northland", description: "Fruit, honey and a trace of peat smoke appear over American oak." }, { title: "Morven", description: "Gentle smoke sits with fruit and fresh sea air." }],
    howToEnjoy: [{ subheading: "Neat", description: "Give a small pour a few minutes in a tasting glass." }, { subheading: "Food", description: "Try with smoked fish or spiced almonds." }],
    pairingIdeas: [{ title: "Highland whisky snacks", items: ["smoked fish", "spiced almonds", "grilled mushrooms", "dark chocolate"] }],
    whyChoose: "A Thurso single malt that wears its old Highland distillery name honestly.",
    faqs: [{ question: "Where is Wolfburn made?", answer: "Wolfburn is distilled in Thurso, Caithness, Scotland." }, { question: "Is Wolfburn smoky?", answer: "Some expressions have gentle peat smoke; Northland has only a trace." }],
    finalVerdict: "Wolfburn Northland is a measured Highland dram, with smoke in the background rather than the lead.",
    metaTitle: "Wolfburn Whisky Guide | BevOry", metaDescription: "Discover Wolfburn single malt from Thurso, Northland notes and pairings. Check city prices on BevOry.",
  },
  wolftrap: {
    description: "The Wolftrap is a South African wine range from Boekenhoutskloof in Franschhoek. Red, white and rose bottles take inspiration from Mediterranean grape blends.",
    story: "A physical wolf trap found on the old farm gave the label its name, though the estate has no evidence of wolves in the valley. Boekenhoutskloof turned that small mystery into an approachable wine range.",
    tastingNotes: [{ title: "Red blend", description: "Syrah-led dark fruit and pepper meet a savoury edge from Mourvedre." }, { title: "Rose", description: "Red berries and a dry, fresh finish make the lighter wine suitable for food." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the red lightly cool and chill the rose." }, { subheading: "Food", description: "The red suits mutton seekh; rose goes with tandoori prawns." }],
    pairingIdeas: [{ title: "Franschhoek table", items: ["mutton seekh", "tandoori prawns", "grilled aubergine", "roast chicken"] }],
    whyChoose: "A Boekenhoutskloof range with a genuine farm story behind its unusual name.",
    faqs: [{ question: "Who makes The Wolftrap?", answer: "Boekenhoutskloof makes the range in South Africa." }, { question: "Was a wolf found at the estate?", answer: "A wolf trap was found, but the winery says no evidence of wolves has been found there." }],
    finalVerdict: "The Wolftrap red is a generous partner for charcoal and spice.",
    metaTitle: "The Wolftrap Wine Guide | BevOry", metaDescription: "Explore The Wolftrap red and rose from South Africa with pairings. Check city prices on BevOry.",
  },
  "writers-tears": {
    description: "Writers' Tears is an Irish whiskey range from Walsh Whiskey, built around pot-still character. Copper Pot, Double Oak and Single Pot Still are distinct expressions in the line.",
    story: "Bernard Walsh linked the label to Ireland's literary and whiskey traditions. The idea reaches back to an era when local pubs were familiar gathering places for writers as well as drinkers.",
    tastingNotes: [{ title: "Copper Pot", description: "Honey and orchard fruit give the whiskey a soft opening." }, { title: "Single Pot Still", description: "Grain spice and dried fruit bring more weight to the sip." }],
    howToEnjoy: [{ subheading: "Neat", description: "Pour a small measure and let it rest before tasting." }, { subheading: "Food", description: "Try with apple tart or salted almonds." }],
    pairingIdeas: [{ title: "Irish whiskey table", items: ["apple tart", "salted almonds", "mutton seekh", "aged cheddar"] }],
    whyChoose: "Pot-still-led Irish whiskey with a clear literary connection, not just a decorative name.",
    faqs: [{ question: "Who makes Writers' Tears?", answer: "Walsh Whiskey makes Writers' Tears in Ireland." }, { question: "Is every Writers' Tears bottle the same whiskey?", answer: "No. Copper Pot, Double Oak and Single Pot Still are different expressions." }],
    finalVerdict: "Copper Pot is the friendly first chapter; the Single Pot Still asks for a slower read.",
    metaTitle: "Writers' Tears Whiskey Guide | BevOry", metaDescription: "Explore Writers' Tears Irish whiskey, pot-still styles and pairings. Check city prices on BevOry.",
  },
};
