import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_38 = [
  ["el-pasador-de-oro", "El Pasador de Oro", "Guatemala", "Rum", "00edee576777993e12f9b2a1"],
  ["fattori-runcaris", "Fattori Runcaris", "Italy", "Wine", "4167aeeb55ca66a982800da1"],
  ["guidalberto", "Guidalberto", "Italy", "Wine", "701f1a44d265beae6b6b3b6e"],
  ["hapsburg", "Hapsburg", "Italy", "Absinthe", "8773956c7227db5bf99b0d51"],
  ["henkell-trocken", "Henkell Trocken", "Germany", "Sparkling Wine", "6189337af9aeccedee0d2ae1"],
  ["il-bruciato", "Il Bruciato", "Italy", "Wine", "83b67b80a1ce8ee34c98c7f8"],
  ["inedit", "Inedit", "Spain", "Beer", "88db9c5723d27e5eea675f48"],
  ["iwai", "Iwai", "Japan", "Whisky", "d2f5ec4d947f9fff62ec5324"],
  ["jacquart", "Jacquart", "France", "Champagne", "7b0a2b528bcd6063f723eb67"],
  ["jinro-chamisul", "Jinro Chamisul", "South Korea", "Soju", "cb2e16fae48dadceba4529b7"],
  ["john-barr", "John Barr", "Scotland", "Whisky", "9645de87a1051ca13eb089cf"],
  ["junimperium", "Junimperium", "Estonia", "Gin", "a1ff0518e158ed4c023428db"],
  ["kadamba", "Kadamba", "India", "Whisky", "e952217f8d5b39eb01f00982"],
  ["komagatake", "Komagatake", "Japan", "Whisky", "4e43ba03d39bc75170584470"],
  ["kyron", "Kyron", "India", "Brandy", "290a888e5aac095a823d03b4"],
  ["la-braccesca", "La Braccesca", "Italy", "Wine", "ed20d459bf6138dab3ad7302"],
  ["la-capra", "La Capra", "South Africa", "Wine", "eaa0df04d6e3490cb238646a"],
  ["la-fiole", "La Fiole", "France", "Wine", "5cd973b71de05ace40598146"],
  ["le-serre-nuove", "Le Serre Nuove", "Italy", "Wine", "f82ccdfc1ba07adcd1ca6e43"],
  ["le-volte", "Le Volte", "Italy", "Wine", "7cff54b41425335e5e18ad84"],
  ["leonardo-da-vinci", "Leonardo Da Vinci", "Italy", "Wine", "5438c152ed301237387393ef"],
  ["lazzaroni", "Lazzaroni", "Italy", "Liqueur", "963cccc629f85254d65647e0"],
  ["la-pecheresse", "La Pecheresse", "Belgium", "Beer", "27f493f7131fc40826ced54d"],
  ["kressmann", "Kressmann", "France", "Wine", "76aac015895a8fce8d50aaa2"],
  ["lauders", "Lauder's", "Scotland", "Whisky", "42f82e1f3d1e877f64fe713b"],
  ["gunpowder", "Drumshanbo Gunpowder", "Ireland", "Gin", "5ff3d7d88faf162928a16d80"],
  ["khor", "Khor", "Ukraine", "Vodka", "6b91f6fcf043eeab93ed8460"],
  ["kronenbourg-1664-biere-blanche", "1664 Blanc", "France", "Beer", "001dbbec6e06010d3c1473b4"],
  ["fincas-valdema", "Fincas Valdemacuco", "Spain", "Wine", "508d08b33fc97055dee1f222"],
  ["godet-cognac", "Godet Cognac", "France", "Cognac", "e60ddb7530cf4d2ea74010ff"],
] as const;

// Provenance is internal and is not displayed in brand pages.
export const BRAND_SOURCES_BATCH_38: Record<string, string[]> = {
  "el-pasador-de-oro": ["https://www.iss-awards.com/app/en/database/product-sheet/328/el-pasador-de-oro-el-pasador-de-oro-xo"],
  "fattori-runcaris": ["https://www.fattoriwines.com/allegati/i-nostri-vini/7/04_soave_runcaris_en.pdf"],
  guidalberto: ["https://www.tenutasanguido.com/en/guidalberto-en"],
  hapsburg: ["https://www.hapsburgabsinthe.com/brand/", "https://www.hapsburgabsinthe.com/products/"],
  "henkell-trocken": ["https://www.henkell.com/en/history-of-henkell", "https://www.henkell.com/en/henkell-brand"],
  "il-bruciato": ["https://www.antinori.it/en/vino/il-bruciato-en/?wineyear=2023"],
  inedit: ["https://www.damm.com/es/cervezas/inedit"],
  iwai: ["https://www.hombo.co.jp/en/item/whisky/iwai/", "https://www.hombo.co.jp/en/product/iwai-tradition/"],
  jacquart: ["https://www.champagne-jacquart.com/en/the-house/"],
  "jinro-chamisul": ["https://hitejinroamerica.com/chamisuloriginal"],
  "john-barr": ["https://www.whyteandmackayltd.com/our-brands/john-barr/"],
  junimperium: ["https://junimperium.ee/en/product/blended-dry-gin/"],
  kadamba: ["https://londonspiritscompetition.com/en/winner-brands/spirits/2026/imperial-distillers-and-vintners-pvt-ltd-6422/kadamba-indian-single-malt-whisky-champagne-barrel-12872.htm"],
  komagatake: ["https://www.hombo.co.jp/en/product/mars-singlemalt-komagatake/", "https://www.hombo.co.jp/en/2023/visiting/20231225-visiting-mars-komagatake-distillery/"],
  kyron: ["https://www.abdindia.com/wp-content/uploads/2025/05/abd-annual-report-fy-2023-24-1.pdf", "https://www.livcheers.com/hyderabad/liquor/kyron-premium-brandy-french-blend-375ml"],
  "la-braccesca": ["https://www.antinori.it/it/vino/la-braccesca-nobile-di-montepulciano/?wineyear=2020"],
  "la-capra": ["https://www.fairview.co.za/la-capra/", "https://fairviewmarketplace.co.za/shop?category=31"],
  "la-fiole": ["https://lafiole.com/en/home/", "https://collection.brotte.com/AGH6JE"],
  "le-serre-nuove": ["https://www.ornellaia.com/filemanager/view/ornellaia/d046e8a6-80cf-4480-a84e-db74244809c2"],
  "le-volte": ["https://www.ornellaia.com/it/vini/le-volte-dellornellaia-2021/"],
  "leonardo-da-vinci": ["https://leonardodavinci.it/en/collections/leonardo-da-vinci/"],
  lazzaroni: ["https://www.lazzaroni.it/it/liquori-classici/maraschino-12.html"],
  "la-pecheresse": ["https://lindemans.be/fr/pages/lindemans-pecheresse"],
  kressmann: ["https://www.lcbo.com/en/kressmann-selection-chardonnay-243345", "https://www.hachette-vins.com/guide-vins/producteurs/15728/kressmann/"],
  lauders: ["https://www.lauderswhisky.com/"],
  gunpowder: ["https://www.thesheddistillery.com/our-creations/drumshanbo-gunpowder-irish-gin/", "https://www.thesheddistillery.com/the-story/"],
  khor: ["https://khor.com/"],
  "kronenbourg-1664-biere-blanche": ["https://www.blanc.1664.co.uk/product-range/1664-blanc/", "https://www.carlsbergdanmark.dk/produkter/kronenbourg/1664-blanc/?Ckey=12497"],
  "fincas-valdema": ["https://valdemarfamily.com/en/ribera-de-duero-wines/", "https://valdemarfamily.com/wp-content/uploads/2023/04/FV-Roble-2021_ING.pdf"],
  "godet-cognac": ["https://cognacgodet.com/en/in-la-rochelle-since-1588/", "https://cognacgodet.com/en/collections/grand-classics/"],
};

// Only producer marks checked against the exact brand identity are included.
export const BRAND_LOGOS_BATCH_38: Record<string, string> = {
  hapsburg: "https://www.hapsburgabsinthe.com/wp-content/themes/hapsburg-theme/HapsburgTemplate/images/hapsburg_logo.png",
  "henkell-trocken": "https://www.henkell.com/_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F278849%2F3839x2984%2F90a5b36ac4%2Fhenkell_primary_logo_asset.png&w=256&q=75",
  jacquart: "https://www.champagne-jacquart.com/wp-content/themes/jacquart/src/img/jacquart-logo.svg",
  junimperium: "https://junimperium.ee/wp-content/themes/junimperium/build/img/logo__junimperium--alt.png",
  "leonardo-da-vinci": "https://leonardodavinci.it/wp-content/uploads/2021/11/Logo-LDV.svg",
  lazzaroni: "https://www.lazzaroni.it/themes/Blulab201508/img/_brand/brand-lazzaroni-header-mobile-small.png",
  lauders: "https://images.squarespace-cdn.com/content/v1/696e1afbca07cb58307de0db/84df63af-6b45-4d6c-8f69-dd5fc5bc83f4/Asset+2.png?format=1500w",
};

export const BRAND_CONTENT_BATCH_38: Record<string, BrandPublicContent> = {
  "el-pasador-de-oro": {
    description: "El Pasador de Oro is a Guatemalan rum selected by French spirits company Les Bienheureux. XO brings a soft, sweet-edged style to the range.",
    story: "The rum's journey connects Guatemala's sugarcane spirits with a French bottler. Les Bienheureux built the label around the rounded character of its Guatemalan blends.",
    tastingNotes: [{ title: "Sweet oak", description: "Vanilla and caramel sit over a mellow woody note." }, { title: "Fruit and nuts", description: "Orange peel and hazelnut give the finish a little lift." }],
    howToEnjoy: [{ subheading: "Pour", description: "Sip a small measure neat in a short glass, then try it over one cube." }, { subheading: "Food", description: "Salted cashews and dark chocolate suit its caramel side." }],
    pairingIdeas: [{ title: "After-dinner bites", items: ["salted cashews", "dark chocolate", "caramel kulfi", "roasted pineapple"] }],
    whyChoose: "A mellow Guatemalan rum for drinkers who favour caramel and soft oak.",
    faqs: [{ question: "Where does El Pasador de Oro rum come from?", answer: "Its rum distillate comes from Guatemala and the label is handled by French spirits company Les Bienheureux." }, { question: "How should El Pasador de Oro XO be served?", answer: "Neat or over a single large ice cube both suit its soft, sweet profile." }],
    finalVerdict: "XO is a slow after-dinner rum, particularly good beside dark chocolate.",
    metaTitle: "El Pasador de Oro Rum Guide | BevOry", metaDescription: "Meet El Pasador de Oro's Guatemalan rum, tasting notes, food matches and city prices on BevOry.",
  },
  "fattori-runcaris": {
    description: "Runcaris is a Soave Classico white wine from Fattori in Italy's Veneto. It is made from Garganega grown near Ronca and fermented in stainless steel.",
    story: "Fattori's Runcaris comes from pergola-trained vines on the hills of Soave Classico. The cellar keeps the wine in steel, leaving Garganega's herb and citrus notes in front.",
    tastingNotes: [{ title: "Nose", description: "Yellow citrus and stone fruit meet fresh sage and nettle." }, { title: "Palate", description: "A lightly mineral texture carries citrus and a brisk finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cool in a white-wine glass, without ice." }, { subheading: "Food", description: "Try it with tandoori fish or lemon-pepper prawns." }],
    pairingIdeas: [{ title: "Seafood and herbs", items: ["tandoori fish", "lemon-pepper prawns", "herb paneer tikka", "grilled courgette"] }],
    whyChoose: "A steel-fermented Garganega that lets Soave's citrus and savoury herbs speak clearly.",
    faqs: [{ question: "Which grape is in Fattori Runcaris?", answer: "Runcaris Soave Classico is made from Garganega." }, { question: "Is Runcaris oaked?", answer: "Fattori's technical sheet lists fermentation and maturation in stainless steel." }],
    finalVerdict: "Runcaris is at its best beside fish and a squeeze of lemon.",
    metaTitle: "Fattori Runcaris Wine Guide | BevOry", metaDescription: "Explore Runcaris Soave Classico, Garganega flavours, fish pairings and city prices on BevOry.",
  },
  guidalberto: {
    description: "Guidalberto is a Tuscan red from Tenuta San Guido near Bolgheri. Cabernet Sauvignon and Merlot give it a darker, softer profile than a Sangiovese-led Tuscan wine.",
    story: "The first Guidalberto vintage came from the 2000 harvest. Its name honours Guidalberto della Gherardesca, an ancestor of the family behind Tenuta San Guido.",
    tastingNotes: [{ title: "Dark fruit", description: "Blackcurrant and plum lead the glass." }, { title: "Structure", description: "Fine tannin and a savoury edge carry the finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a wide red-wine glass." }, { subheading: "Food", description: "Mutton seekh kebabs or mushroom galouti give the wine enough depth to work with." }],
    pairingIdeas: [{ title: "Bolgheri reds at dinner", items: ["mutton seekh kebabs", "mushroom galouti", "roast lamb", "aged pecorino"] }],
    whyChoose: "Tenuta San Guido's Cabernet-Merlot red brings Bolgheri character to the dinner table.",
    faqs: [{ question: "Who makes Guidalberto?", answer: "Tenuta San Guido, the Bolgheri estate behind Sassicaia, makes Guidalberto." }, { question: "What grapes are in Guidalberto?", answer: "Cabernet Sauvignon and Merlot form the blend." }],
    finalVerdict: "Guidalberto makes most sense with a substantial meal and time in the glass.",
    metaTitle: "Guidalberto Wine Guide | BevOry", metaDescription: "Discover Guidalberto from Tenuta San Guido, Cabernet-Merlot style, food matches and city prices on BevOry.",
  },
  hapsburg: {
    description: "Hapsburg is an Italian-made absinthe label established in 1999. Its Classic expression is infused with grand wormwood, while the wider range includes flavoured styles.",
    story: "The label appeared during absinthe's late-1990s return to international bars. Rather than borrowing a nineteenth-century origin story, Hapsburg built a contemporary absinthe range.",
    tastingNotes: [{ title: "Classic", description: "Wormwood gives a firm herbal bitterness." }, { title: "Aromatic lift", description: "Anise-like sweetness softens the green-herb edge." }],
    howToEnjoy: [{ subheading: "Dilute", description: "Add cold water slowly to a small measure of Classic absinthe." }, { subheading: "Food", description: "Salted almonds or fennel crackers work with its herbal profile." }],
    pairingIdeas: [{ title: "Salty aperitif bites", items: ["salted almonds", "fennel crackers", "olive tapenade", "fried paneer"] }],
    whyChoose: "A modern absinthe with a clear wormwood centre rather than a borrowed antique story.",
    faqs: [{ question: "When was Hapsburg Absinthe established?", answer: "Hapsburg dates to 1999." }, { question: "Does Hapsburg contain wormwood?", answer: "The Hapsburg Classic expression is infused with grand wormwood." }],
    finalVerdict: "Classic is for a slow, water-softened herbal pour.",
    metaTitle: "Hapsburg Absinthe Guide | BevOry", metaDescription: "Explore Hapsburg's wormwood-led absinthe, serving ideas, pairings and city prices on BevOry.",
  },
  "henkell-trocken": {
    description: "Henkell Trocken is a German sparkling wine from Henkell's Wiesbaden house. The dry style and familiar black label have made it one of the country's best-known Sekt names.",
    story: "Adam Henkell began making sparkling wine in the nineteenth century. Henkell Trocken later became a registered brand and carried the house well beyond Germany.",
    tastingNotes: [{ title: "Fresh fruit", description: "Apple and citrus give the first sip a clean lift." }, { title: "Dry finish", description: "The bubbles finish crisp rather than dessert-sweet." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tulip-shaped sparkling-wine glass." }, { subheading: "Food", description: "Its dry edge suits fish pakoras and chilli paneer." }],
    pairingIdeas: [{ title: "Crisp starters", items: ["fish pakoras", "chilli paneer", "salted almonds", "fried zucchini"] }],
    whyChoose: "A German Sekt with a dry profile that stands up to fried starters.",
    faqs: [{ question: "What is Henkell Trocken?", answer: "It is a dry German sparkling wine, or Sekt, from Henkell." }, { question: "How do you serve Henkell Trocken?", answer: "Serve well chilled in a sparkling-wine glass." }],
    finalVerdict: "Put Henkell Trocken on the table before the first hot snacks arrive.",
    metaTitle: "Henkell Trocken Sparkling Wine Guide | BevOry", metaDescription: "Meet Henkell Trocken German Sekt, dry flavours, snack pairings and city prices on BevOry.",
  },
  "il-bruciato": {
    description: "Il Bruciato is a Bolgheri red from Antinori's Guado al Tasso estate on the Tuscan coast. Cabernet Sauvignon, Merlot and Syrah form its modern, fruit-led blend.",
    story: "Guado al Tasso introduced Il Bruciato in 2002 after a difficult growing season. The wine became a way to show Bolgheri's coastal vineyards in a more immediate style.",
    tastingNotes: [{ title: "Fruit", description: "Ripe dark berries and plum lead the aroma." }, { title: "Finish", description: "A little spice and supple tannin follow the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour slightly cool and give it a few minutes in a red-wine glass." }, { subheading: "Food", description: "Try it with lamb seekh or mushroom pulao." }],
    pairingIdeas: [{ title: "Coastal Tuscan red", items: ["lamb seekh", "mushroom pulao", "grilled aubergine", "roast beef"] }],
    whyChoose: "A Cabernet-Merlot-Syrah route into Antinori's coastal Bolgheri estate.",
    faqs: [{ question: "Who makes Il Bruciato?", answer: "The Guado al Tasso estate of Marchesi Antinori makes Il Bruciato." }, { question: "Which grapes go into Il Bruciato?", answer: "Cabernet Sauvignon, Merlot and Syrah are used in the blend." }],
    finalVerdict: "Il Bruciato is a generous red for a spice-led main course.",
    metaTitle: "Il Bruciato Wine Guide | BevOry", metaDescription: "Explore Antinori's Il Bruciato from Bolgheri, grape blend, dinner pairings and city prices on BevOry.",
  },
  inedit: {
    description: "Inedit is a wheat-and-barley beer from Barcelona brewer Damm. It was created with chef Ferran Adria and the elBulli team as a beer to accompany food.",
    story: "Damm launched Inedit in 2008 with Ferran Adria and elBulli's sommeliers. The collaboration treated beer as a table drink with the same attention usually given to wine.",
    tastingNotes: [{ title: "Citrus", description: "Orange-peel freshness sits over a soft wheat-beer base." }, { title: "Spice", description: "Coriander-like aromatics keep the finish lively." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve chilled in a stemmed beer glass." }, { subheading: "Food", description: "Try it with tandoori fish or a peppery prawn starter." }],
    pairingIdeas: [{ title: "At the table", items: ["tandoori fish", "pepper prawns", "herb paneer", "grilled squid"] }],
    whyChoose: "A Barcelona beer built with the dinner table in mind.",
    faqs: [{ question: "Who created Inedit beer?", answer: "Damm created Inedit with Ferran Adria and the elBulli team." }, { question: "Is Inedit a wheat beer?", answer: "It combines wheat and barley malt." }],
    finalVerdict: "Inedit belongs beside food, especially dishes with citrus and herbs.",
    metaTitle: "Inedit Beer Guide | BevOry", metaDescription: "Discover Damm Inedit's wheat-and-barley style, food pairings and city prices on BevOry.",
  },
  iwai: {
    description: "Iwai is a Japanese whisky range from Hombo Shuzo's Mars Whisky. It includes approachable blends such as Iwai Tradition.",
    story: "The name honours Kiichiro Iwai, who helped plan Hombo Shuzo's whisky operation. The company's Mars distilling history connects the label to Japanese whisky-making beyond one bottling.",
    tastingNotes: [{ title: "Iwai Tradition", description: "Gentle malt sweetness sits alongside soft oak." }, { title: "Fruit", description: "A light orchard-fruit note keeps the blend fresh." }],
    howToEnjoy: [{ subheading: "Highball", description: "Try it over ice with cold soda in a tall glass." }, { subheading: "Food", description: "The highball works with chicken yakitori or pepper paneer." }],
    pairingIdeas: [{ title: "Highball snacks", items: ["chicken yakitori", "pepper paneer", "salted edamame", "mushroom skewers"] }],
    whyChoose: "A Mars Whisky blend that pays tribute to an important figure in the company's history.",
    faqs: [{ question: "Who makes Iwai whisky?", answer: "Hombo Shuzo makes Iwai under its Mars Whisky label." }, { question: "Who was Kiichiro Iwai?", answer: "He advised Hombo Shuzo and helped plan its whisky division." }],
    finalVerdict: "Iwai is an easy whisky to put in a cold highball with dinner.",
    metaTitle: "Iwai Japanese Whisky Guide | BevOry", metaDescription: "Explore Mars Iwai whisky, its Japanese history, highball ideas and city prices on BevOry.",
  },
  jacquart: {
    description: "Jacquart is a Champagne house founded in Reims in 1964. Chardonnay plays a prominent part in its fresh, finely textured blends.",
    story: "The house began in 1964 and later moved to the Hotel de Brimont in Reims. It selects fruit from numerous Champagne villages, bringing their different soils and exposures into the blends.",
    tastingNotes: [{ title: "Citrus", description: "Lemon and orchard fruit give the wine a crisp opening." }, { title: "Texture", description: "Fine bubbles and a chalky edge keep the finish light." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill and serve in a tulip glass rather than a wide coupe." }, { subheading: "Food", description: "Fish tikka and crisp potato pakoras suit its acidity." }],
    pairingIdeas: [{ title: "Champagne and starters", items: ["fish tikka", "potato pakoras", "oysters", "goat cheese"] }],
    whyChoose: "A Chardonnay-minded Reims house with a bright aperitif style.",
    faqs: [{ question: "Where is Jacquart Champagne based?", answer: "Jacquart is based in Reims, France." }, { question: "When was Champagne Jacquart founded?", answer: "The house was founded in 1964." }],
    finalVerdict: "Jacquart's fresh style deserves the first glass, not the last.",
    metaTitle: "Jacquart Champagne Guide | BevOry", metaDescription: "Explore Jacquart Champagne from Reims, Chardonnay style, food pairings and city prices on BevOry.",
  },
  "jinro-chamisul": {
    description: "Jinro Chamisul is a Korean soju from HiteJinro, not a sake. The clear spirit is commonly served cold in small glasses with food.",
    story: "Chamisul is one of HiteJinro's best-known soju labels. Its name means 'real dew', matching the brand's clear-bottle identity in Korean drinking culture.",
    tastingNotes: [{ title: "Clean opening", description: "A light grain-spirit note makes room for the food beside it." }, { title: "Finish", description: "The sip stays crisp rather than oaky." }],
    howToEnjoy: [{ subheading: "Chill", description: "Keep the bottle cold and pour into small soju glasses." }, { subheading: "Food", description: "Serve with Korean fried chicken or spicy paneer skewers." }],
    pairingIdeas: [{ title: "Sharing plates", items: ["Korean fried chicken", "spicy paneer skewers", "kimchi pancakes", "grilled pork belly"] }],
    whyChoose: "A recognisable Korean soju for cold pours around a table of spicy snacks.",
    faqs: [{ question: "Is Chamisul soju or sake?", answer: "Chamisul is Korean soju, not Japanese sake." }, { question: "Who makes Chamisul?", answer: "HiteJinro makes the Chamisul soju range." }],
    finalVerdict: "Chamisul is most at home chilled beside salty, spicy shared plates.",
    metaTitle: "Jinro Chamisul Soju Guide | BevOry", metaDescription: "Meet Jinro Chamisul Korean soju, chilled serves, food matches and city prices on BevOry.",
  },
  "john-barr": {
    description: "John Barr is a blended Scotch whisky made by Whyte & Mackay. Its Reserve expression combines malt and grain whiskies in a smooth, approachable style.",
    story: "The label honours John Barr Cumming, a nineteenth-century whisky entrepreneur. Whyte & Mackay keeps his name on a blend intended for easy drinking rather than a single-distillery identity.",
    tastingNotes: [{ title: "Malt sweetness", description: "Soft cereal and honey lead the blend." }, { title: "Oak", description: "A little vanilla and spice close the sip." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try it neat, with a splash of water, or as a simple soda highball." }, { subheading: "Food", description: "Tandoori chicken and salted cashews match its gentle sweetness." }],
    pairingIdeas: [{ title: "Scotch and supper", items: ["tandoori chicken", "salted cashews", "mushroom kebabs", "roast pork"] }],
    whyChoose: "A straightforward blended Scotch with the Whyte & Mackay name behind it.",
    faqs: [{ question: "Who makes John Barr whisky?", answer: "Whyte & Mackay makes John Barr blended Scotch whisky." }, { question: "Is John Barr a single malt?", answer: "No. It is a blend of Scotch malt and grain whiskies." }],
    finalVerdict: "John Barr Reserve is suited to a highball as readily as a short neat pour.",
    metaTitle: "John Barr Whisky Guide | BevOry", metaDescription: "Explore John Barr blended Scotch, simple serves, food pairings and city prices on BevOry.",
  },
  junimperium: {
    description: "Junimperium is a craft gin distillery in Tallinn, Estonia. Its Blended Dry Gin combines several junipers with local berries and angelica root.",
    story: "The distillery works from Tallinn's Telliskivi district. Juniper is the point of the name and of the gin: the Blended Dry recipe brings together different sources rather than hiding the berry behind citrus.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper carries the first aroma." }, { title: "Berry and root", description: "Local berries soften the centre while angelica leaves a dry finish." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Pour over ice with a neutral tonic so the juniper remains clear." }, { subheading: "Food", description: "Try it with smoked fish or peppery paneer tikka." }],
    pairingIdeas: [{ title: "Juniper-friendly plates", items: ["smoked fish", "pepper paneer tikka", "roasted mushrooms", "salted olives"] }],
    whyChoose: "A Tallinn gin that makes juniper, not a garnish, the main event.",
    faqs: [{ question: "Where is Junimperium gin made?", answer: "Junimperium is based in Tallinn, Estonia." }, { question: "What shapes Junimperium Blended Dry Gin?", answer: "Its recipe uses several junipers, local berries and angelica root." }],
    finalVerdict: "Junimperium is a good pick when you want a dry, juniper-led gin and tonic.",
    metaTitle: "Junimperium Gin Guide | BevOry", metaDescription: "Discover Junimperium gin from Tallinn, juniper flavours, food pairings and city prices on BevOry.",
  },
  kadamba: {
    description: "Kadamba is an Indian single malt whisky label from Imperial Distillers and Vintners. The range includes cask-finished bottlings such as its Champagne Barrel expression.",
    story: "Imperial Distillers and Vintners operates from Ponda in Goa. Kadamba's cask-finished releases take different routes after the malt has matured, including a Champagne Barrel expression.",
    tastingNotes: [{ title: "Champagne Barrel aroma", description: "The assessed release shows waxy peat and an earthy mushroom note." }, { title: "Champagne Barrel palate", description: "Peated butterscotch and sharp caramel carry a medium-bodied finish." }],
    howToEnjoy: [{ subheading: "Taste", description: "Try a small neat pour before adding a little water." }, { subheading: "Food", description: "Cashew nuts and pepper chicken make a good Goa-inspired table." }],
    pairingIdeas: [{ title: "Goan table", items: ["roasted cashews", "pepper chicken", "mushroom xacuti", "dark chocolate"] }],
    whyChoose: "An Indian malt range that uses finishing casks to change the character of each release.",
    faqs: [{ question: "Is Kadamba a single malt whisky?", answer: "Kadamba's named releases include Indian single malt whiskies." }, { question: "Who makes Kadamba whisky?", answer: "Imperial Distillers and Vintners is the producer named for Kadamba's Champagne Barrel single malt." }],
    finalVerdict: "Kadamba rewards a neat first sip before its cask finish meets food.",
    metaTitle: "Kadamba Whisky Guide | BevOry", metaDescription: "Explore Kadamba Indian single malt, cask-finished styles, Goan pairings and city prices on BevOry.",
  },
  komagatake: {
    description: "Komagatake is a Japanese single malt from Hombo Shuzo's Mars Komagatake Distillery in Nagano. The whisky takes its name from the Central Alps mountain nearby.",
    story: "The distillery was previously known as Mars Shinshu. Hombo Shuzo renamed it Mars Komagatake to connect the production site more clearly with its single malt.",
    tastingNotes: [{ title: "Orchard fruit", description: "Apple and pear notes keep the malt fresh." }, { title: "Cask", description: "Oak adds gentle vanilla and grain spice." }],
    howToEnjoy: [{ subheading: "Glass", description: "Taste neat in a small tulip glass, then add a few drops of water." }, { subheading: "Food", description: "Chicken yakitori or roasted mushrooms work beside the malt." }],
    pairingIdeas: [{ title: "Malt and umami", items: ["chicken yakitori", "roasted mushrooms", "salted edamame", "tandoori chicken"] }],
    whyChoose: "A Nagano single malt tied directly to Hombo Shuzo's mountain distillery.",
    faqs: [{ question: "Where is Komagatake whisky made?", answer: "It is made at Mars Komagatake Distillery in Nagano, Japan." }, { question: "Who owns Mars Komagatake?", answer: "Hombo Shuzo produces the Mars Komagatake single malt." }],
    finalVerdict: "Komagatake deserves a quiet glass before dinner takes over.",
    metaTitle: "Komagatake Whisky Guide | BevOry", metaDescription: "Explore Mars Komagatake single malt from Nagano, tasting notes, pairings and city prices on BevOry.",
  },
  kyron: {
    description: "Kyron is an Indian brandy label from Allied Blenders and Distillers. Its Premium French Blend uses grape spirit sourced from France's Cognac region.",
    story: "Allied Blenders and Distillers introduced Kyron into its Indian brandy portfolio. The label brought a French-styled name and presentation to a category with a long following in southern India.",
    tastingNotes: [{ title: "Nose", description: "Floral notes meet dried fruit and oak." }, { title: "Palate", description: "Caramelised sugar and nutmeg lead into a rounded finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve a small measure in a short glass, neat or over ice." }, { subheading: "Food", description: "Dark chocolate and roasted almonds suit its sweeter side." }],
    pairingIdeas: [{ title: "After dinner", items: ["dark chocolate", "roasted almonds", "plum cake", "cashew brittle"] }],
    whyChoose: "An Indian brandy for a simple after-dinner pour.",
    faqs: [{ question: "Who owns Kyron brandy?", answer: "Kyron is a brand of Allied Blenders and Distillers." }, { question: "Is Kyron a whisky?", answer: "No. Kyron is sold as brandy." }],
    finalVerdict: "Kyron fits a small glass after a rich meal.",
    metaTitle: "Kyron Brandy Guide | BevOry", metaDescription: "Meet Kyron Indian brandy, serving ideas, after-dinner pairings and city prices on BevOry.",
  },
  "la-braccesca": {
    description: "La Braccesca is an Antinori wine estate near Montepulciano in Tuscany. Its Vino Nobile di Montepulciano draws on the local Sangiovese grape, known here as Prugnolo Gentile.",
    story: "Antinori acquired La Braccesca in 1990, the year of its first Vino Nobile vintage. The estate connects the family's Tuscan winemaking with the hills around Montepulciano.",
    tastingNotes: [{ title: "Red fruit", description: "Cherry and plum lead the Sangiovese character." }, { title: "Savoury finish", description: "Herb and tannin make room for food." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Mutton rogan josh or tomato-rich mushroom pasta suit its savoury edge." }],
    pairingIdeas: [{ title: "Tuscan red with dinner", items: ["mutton rogan josh", "mushroom pasta", "grilled lamb chops", "aged pecorino"] }],
    whyChoose: "An Antinori route into the Sangiovese wines of Montepulciano.",
    faqs: [{ question: "Who owns La Braccesca?", answer: "Marchesi Antinori owns the La Braccesca estate." }, { question: "What is Vino Nobile di Montepulciano made from?", answer: "Sangiovese, locally called Prugnolo Gentile, is the principal grape." }],
    finalVerdict: "La Braccesca is a red to open when a proper dinner is already underway.",
    metaTitle: "La Braccesca Wine Guide | BevOry", metaDescription: "Explore La Braccesca Vino Nobile, Sangiovese flavours, dinner pairings and city prices on BevOry.",
  },
  "la-capra": {
    description: "La Capra is a South African wine range from Fairview in Paarl. Its Chenin Blanc is one of several varietal wines sold under the goat-marked label.",
    story: "Fairview's farm combines vineyards, a winery and its well-known goat tower. La Capra takes the farm's goat identity into a straightforward range of grape-led wines.",
    tastingNotes: [{ title: "Chenin Blanc", description: "Orchard fruit and a citrus edge keep the white lively." }, { title: "Finish", description: "A fresh acidity leaves the palate ready for another bite." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Chenin Blanc cool in a white-wine glass." }, { subheading: "Food", description: "Paneer tikka and grilled prawns both suit its fruit and acidity." }],
    pairingIdeas: [{ title: "Paarl Chenin at lunch", items: ["paneer tikka", "grilled prawns", "roast chicken", "goat cheese"] }],
    whyChoose: "A Fairview wine that makes South African Chenin Blanc easy to bring to lunch.",
    faqs: [{ question: "Who makes La Capra wine?", answer: "Fairview in Paarl, South Africa, makes the La Capra range." }, { question: "Does La Capra make Chenin Blanc?", answer: "Yes. Chenin Blanc is part of the La Capra range." }],
    finalVerdict: "La Capra Chenin Blanc is happiest beside a bright, spiced lunch.",
    metaTitle: "La Capra Wine Guide | BevOry", metaDescription: "Meet Fairview's La Capra Chenin Blanc from Paarl, food pairings and city prices on BevOry.",
  },
  "la-fiole": {
    description: "La Fiole is a Rhone wine range from the Brotte family in France. The Cotes du Rhone red sits alongside the better-known La Fiole du Pape bottle.",
    story: "Charles Brotte created La Fiole's distinctive curved bottle in 1952. He drew its shape from a vine bent by the Mistral wind, making the bottle part of the wine's identity.",
    tastingNotes: [{ title: "Red fruit", description: "Cherry and darker berries give the red its opening." }, { title: "Rhone spice", description: "A peppery edge follows the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve the red slightly cool in a medium wine glass." }, { subheading: "Food", description: "Try it with lamb seekh or aubergine bharta." }],
    pairingIdeas: [{ title: "Rhone reds at dinner", items: ["lamb seekh", "aubergine bharta", "roast chicken", "grilled peppers"] }],
    whyChoose: "A Rhone red with a bottle shape rooted in the region's own windswept vines.",
    faqs: [{ question: "Who makes La Fiole wine?", answer: "The Brotte family makes La Fiole wines in the Rhone Valley." }, { question: "Why is the La Fiole bottle curved?", answer: "Charles Brotte designed it to recall a vine shaped by the Mistral wind." }],
    finalVerdict: "La Fiole brings a peppery Rhone red to the table in an unmistakable bottle.",
    metaTitle: "La Fiole Wine Guide | BevOry", metaDescription: "Explore Brotte's La Fiole Rhone wines, their curved bottle, dinner pairings and city prices on BevOry.",
  },
  "le-serre-nuove": {
    description: "Le Serre Nuove dell'Ornellaia is the second red wine of the Ornellaia estate in Bolgheri. Cabernet and Merlot-family grapes give it a coastal Tuscan character.",
    story: "Ornellaia introduced Le Serre Nuove to express its vineyards through a wine that could be opened earlier than the flagship. The same Bolgheri climate and cellar team shape both reds.",
    tastingNotes: [{ title: "Dark berries", description: "Black fruit and plum lead the aroma." }, { title: "Tannin", description: "A firm but polished frame carries the long finish." }],
    howToEnjoy: [{ subheading: "Open", description: "Pour into a broad red-wine glass and give it time to breathe." }, { subheading: "Food", description: "Mutton seekh or slow-cooked mushroom dishes meet its depth." }],
    pairingIdeas: [{ title: "Bolgheri red table", items: ["mutton seekh", "mushroom ragout", "roast lamb", "aged cheddar"] }],
    whyChoose: "An Ornellaia red with the estate's Bolgheri identity in a more immediately open style.",
    faqs: [{ question: "Who makes Le Serre Nuove?", answer: "The Ornellaia estate in Bolgheri makes Le Serre Nuove." }, { question: "Is Le Serre Nuove a red wine?", answer: "Yes. It is Ornellaia's second red wine." }],
    finalVerdict: "Give Le Serre Nuove a broad glass and a substantial dinner.",
    metaTitle: "Le Serre Nuove Wine Guide | BevOry", metaDescription: "Discover Ornellaia's Le Serre Nuove Bolgheri red, food matches and city prices on BevOry.",
  },
  "le-volte": {
    description: "Le Volte dell'Ornellaia is a Tuscan red from the Ornellaia estate. It blends Italian Sangiovese with international red varieties for a lively, fruit-forward wine.",
    story: "Ornellaia created Le Volte as a distinct Toscana IGT wine, separate from its Bolgheri DOC reds. Sangiovese brings a recognisably Tuscan note to the estate's broader blending approach.",
    tastingNotes: [{ title: "Red berries", description: "Cherry and raspberry give the wine its bright opening." }, { title: "Gentle spice", description: "A light pepper note follows the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve a little cool in a regular red-wine glass." }, { subheading: "Food", description: "Tomato-rich paneer or chicken cacciatore suit the red-fruit edge." }],
    pairingIdeas: [{ title: "Weeknight Tuscan red", items: ["tomato paneer", "chicken cacciatore", "mushroom pizza", "grilled aubergine"] }],
    whyChoose: "A Sangiovese-touched entry into Ornellaia's red-wine range.",
    faqs: [{ question: "Who produces Le Volte?", answer: "Le Volte is made by the Ornellaia estate in Tuscany." }, { question: "Is Le Volte the same as Le Serre Nuove?", answer: "No. Le Volte is a Toscana IGT blend; Le Serre Nuove is Ornellaia's second Bolgheri red." }],
    finalVerdict: "Le Volte is the Ornellaia red to put beside a casual tomato-led supper.",
    metaTitle: "Le Volte Wine Guide | BevOry", metaDescription: "Explore Le Volte dell'Ornellaia, its Tuscan blend, food pairings and city prices on BevOry.",
  },
  "leonardo-da-vinci": {
    description: "Leonardo Da Vinci is an Italian wine label spanning Chianti reds and Pinot Grigio whites. The producer brings together wineries from different Italian wine regions.",
    story: "The name honours Leonardo's home town of Vinci in Tuscany. The label uses his legacy to connect familiar Italian grapes and appellations rather than a single-vineyard estate.",
    tastingNotes: [{ title: "Chianti", description: "Sangiovese brings cherry fruit and a savoury bite." }, { title: "Pinot Grigio", description: "Pear and citrus make the white lighter on its feet." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Pinot Grigio and serve Chianti slightly cool." }, { subheading: "Food", description: "Pair Chianti with lamb seekh and Pinot Grigio with tandoori fish." }],
    pairingIdeas: [{ title: "Italian grapes at the table", items: ["lamb seekh", "tandoori fish", "tomato pasta", "grilled prawns"] }],
    whyChoose: "One label offers a clear choice between Sangiovese-led Chianti and crisp Pinot Grigio.",
    faqs: [{ question: "Does Leonardo Da Vinci make Chianti?", answer: "Yes. Chianti is part of the Leonardo Da Vinci wine range." }, { question: "Does it also make white wine?", answer: "Yes. The range includes Pinot Grigio." }],
    finalVerdict: "Choose the red for tomato and roast flavours, the white for fish and herbs.",
    metaTitle: "Leonardo Da Vinci Wine Guide | BevOry", metaDescription: "Compare Leonardo Da Vinci Chianti and Pinot Grigio, food matches and city prices on BevOry.",
  },
  lazzaroni: {
    description: "Lazzaroni is an Italian liqueur house with a range that includes Maraschino and Triple Sec. Its clear Maraschino is made from Marasca cherries and their crushed stones.",
    story: "Paolo Lazzaroni & Figli is tied to Saronno's long tradition of sweet spirits. The Maraschino's faint almond note comes from the cherry stones, not a separate almond syrup.",
    tastingNotes: [{ title: "Cherry", description: "Marasca fruit gives the liqueur a delicate cherry note." }, { title: "Stone fruit", description: "Crushed stones lend a faint bitter-almond finish." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use Maraschino sparingly in a sour or serve a small chilled measure." }, { subheading: "Food", description: "Try it with almond biscotti or dark-chocolate truffles." }],
    pairingIdeas: [{ title: "Dessert table", items: ["almond biscotti", "dark-chocolate truffles", "cherry tart", "pistachio kulfi"] }],
    whyChoose: "A cherry liqueur with the dry almond edge that makes Maraschino useful in cocktails.",
    faqs: [{ question: "What is Lazzaroni Maraschino made from?", answer: "It uses Marasca cherries and their crushed stones." }, { question: "Is Maraschino the only Lazzaroni liqueur?", answer: "No. The house also makes other liqueurs, including Triple Sec." }],
    finalVerdict: "Lazzaroni Maraschino earns its place by adding cherry without turning a drink into syrup.",
    metaTitle: "Lazzaroni Liqueur Guide | BevOry", metaDescription: "Discover Lazzaroni Maraschino, cherry-and-almond notes, dessert pairings and city prices on BevOry.",
  },
  "la-pecheresse": {
    description: "Pecheresse is a Belgian peach lambic from Lindemans. It combines lambic beer's tart base with ripe peach sweetness.",
    story: "Lindemans brews in Vlezenbeek, outside Brussels, where lambic beer has deep local roots. Pecheresse uses that sour-beer tradition to carry fruit rather than brewing a conventional sweet lager.",
    tastingNotes: [{ title: "Peach", description: "Ripe peach is immediately clear on the nose." }, { title: "Lambic", description: "A gentle tartness cuts through the fruit sweetness." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a small stemmed beer glass." }, { subheading: "Food", description: "Spicy chilli paneer or a light fruit dessert both suit its sweet-sour balance." }],
    pairingIdeas: [{ title: "Peach and spice", items: ["chilli paneer", "grilled prawns", "peach tart", "soft goat cheese"] }],
    whyChoose: "A fruit lambic where peach sweetness still leaves room for the beer's tart edge.",
    faqs: [{ question: "Who makes Pecheresse?", answer: "Lindemans Brewery in Belgium makes Pecheresse." }, { question: "Is Pecheresse a peach beer?", answer: "Yes. It is a peach-flavoured lambic beer." }],
    finalVerdict: "Pecheresse works best cold, with a spicy starter or a modest dessert.",
    metaTitle: "Pecheresse Beer Guide | BevOry", metaDescription: "Explore Lindemans Pecheresse peach lambic, sweet-tart flavours, pairings and city prices on BevOry.",
  },
  kressmann: {
    description: "Kressmann is a French wine merchant label with roots in Bordeaux. Its range reaches beyond Bordeaux, including a Chardonnay from Languedoc.",
    story: "The Kressmann name grew through Bordeaux's merchant trade, where selecting and blending wines mattered as much as tending one vineyard. A southern French Chardonnay shows the label's reach beyond its home region.",
    tastingNotes: [{ title: "Chardonnay", description: "Pear and lemon make the white fresh and fruit-led." }, { title: "Finish", description: "A soft texture keeps the acidity from feeling sharp." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Chardonnay lightly chilled in a white-wine glass." }, { subheading: "Food", description: "Pair with malai tikka or grilled pomfret." }],
    pairingIdeas: [{ title: "White wine at dinner", items: ["malai tikka", "grilled pomfret", "roast chicken", "mushroom risotto"] }],
    whyChoose: "A merchant-led French wine name with an easy southern Chardonnay.",
    faqs: [{ question: "Is Kressmann only a Bordeaux label?", answer: "Its heritage is in Bordeaux, but its range includes wine from other French regions." }, { question: "Where is Kressmann Selection Chardonnay from?", answer: "The Selection Chardonnay comes from Languedoc in southern France." }],
    finalVerdict: "Kressmann Chardonnay is a useful white for creamy or gently spiced plates.",
    metaTitle: "Kressmann Wine Guide | BevOry", metaDescription: "Explore Kressmann Chardonnay, French wine heritage, dinner pairings and city prices on BevOry.",
  },
  lauders: {
    description: "Lauder's is a blended Scotch whisky with roots in Glasgow. The range combines malt and grain whiskies for a soft, approachable pour.",
    story: "Archibald Lauder built his whisky business in Glasgow in the nineteenth century. The city's trading history still sits at the heart of the label's presentation.",
    tastingNotes: [{ title: "Sweet grain", description: "Malt biscuit and light honey lead the sip." }, { title: "Oak", description: "Vanilla and gentle spice close the blend." }],
    howToEnjoy: [{ subheading: "Highball", description: "Serve over ice with cold soda, or take a short neat pour." }, { subheading: "Food", description: "Try with tandoori chicken or salted peanuts." }],
    pairingIdeas: [{ title: "Glasgow blend at dinner", items: ["tandoori chicken", "salted peanuts", "roast pork", "mushroom kebabs"] }],
    whyChoose: "A Glasgow-rooted blended Scotch that asks little of the glass or mixer.",
    faqs: [{ question: "Where does Lauder's whisky come from?", answer: "Lauder's is a blended Scotch whisky with historical roots in Glasgow." }, { question: "Is Lauder's a single malt?", answer: "No. It is a blend of Scotch malt and grain whiskies." }],
    finalVerdict: "Lauder's is an easy whisky to bring to a long dinner with friends.",
    metaTitle: "Lauder's Whisky Guide | BevOry", metaDescription: "Meet Lauder's Glasgow blended Scotch, serving ideas, food pairings and city prices on BevOry.",
  },
  gunpowder: {
    description: "Drumshanbo Gunpowder is an Irish gin from The Shed Distillery in County Leitrim. Chinese gunpowder tea, citrus and other botanicals give it a fresh herbal style.",
    story: "PJ Rigney founded The Shed Distillery in Drumshanbo to bring Irish and Asian botanicals into the same copper-pot gin. Gunpowder tea supplies the name; it has nothing to do with explosives.",
    tastingNotes: [{ title: "Citrus", description: "Fresh peel brightens the first aroma." }, { title: "Tea and herbs", description: "Gunpowder tea and botanicals leave a green, lightly spicy finish." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Pour over ice with dry tonic and a thin grapefruit slice." }, { subheading: "Food", description: "Tandoori prawns and coriander chicken work with its citrus-herb edge." }],
    pairingIdeas: [{ title: "Citrus and char", items: ["tandoori prawns", "coriander chicken", "grilled asparagus", "salted cashews"] }],
    whyChoose: "An Irish gin whose tea botanical gives the classic gin-and-tonic a different finish.",
    faqs: [{ question: "Where is Drumshanbo Gunpowder Gin made?", answer: "It is made at The Shed Distillery in Drumshanbo, County Leitrim, Ireland." }, { question: "Does the gin contain gunpowder?", answer: "No. The name refers to a style of rolled green tea used as a botanical." }],
    finalVerdict: "A cold tonic lets the tea and citrus do their work.",
    metaTitle: "Drumshanbo Gunpowder Gin Guide | BevOry", metaDescription: "Discover Drumshanbo Gunpowder Gin's tea and citrus, serving ideas and city prices on BevOry.",
  },
  khor: {
    description: "Khor is a Ukrainian vodka label launched in 1998. Its range includes Classic, Platinum and Silver expressions built around a clean mixing style.",
    story: "Khor grew from Ukraine into export markets under its short, recognisable name. The range keeps the spirit's identity in a clear, neutral profile rather than flavouring every bottle.",
    tastingNotes: [{ title: "Clean nose", description: "A light grain note stays in the background." }, { title: "Finish", description: "The spirit closes crisp, without oak or fruit flavouring." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a small glass or build a vodka soda over ice." }, { subheading: "Food", description: "Pickled vegetables and tandoori mushrooms give it something savoury to meet." }],
    pairingIdeas: [{ title: "Cold vodka table", items: ["pickled cucumber", "tandoori mushrooms", "smoked fish", "salted potatoes"] }],
    whyChoose: "A Ukrainian vodka for a cold, uncomplicated pour.",
    faqs: [{ question: "Where is Khor vodka from?", answer: "Khor is a Ukrainian vodka brand." }, { question: "When was Khor launched?", answer: "The brand dates to 1998." }],
    finalVerdict: "Khor makes sense cold, with savoury food or a simple soda mixer.",
    metaTitle: "Khor Vodka Guide | BevOry", metaDescription: "Explore Khor Ukrainian vodka, cold serves, savoury pairings and city prices on BevOry.",
  },
  "kronenbourg-1664-biere-blanche": {
    description: "1664 Blanc is a French wheat beer from the Kronenbourg family. Its hazy body and citrus profile distinguish it from 1664's clear lager.",
    story: "The blue bottle made Blanc easy to spot beside the main 1664 range. It brought a wheat-beer texture and citrus-led taste into a French brand better known for lager.",
    tastingNotes: [{ title: "Citrus", description: "Orange and lemon notes make the opening bright." }, { title: "Wheat", description: "A soft, cloudy wheat-beer body rounds the finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tall beer glass, leaving room for the foam." }, { subheading: "Food", description: "Its citrus side suits fish pakoras or chilli-lime corn." }],
    pairingIdeas: [{ title: "Wheat beer snacks", items: ["fish pakoras", "chilli-lime corn", "grilled prawns", "soft pretzels"] }],
    whyChoose: "A citrusy wheat beer for drinkers who want something softer than a crisp lager.",
    faqs: [{ question: "Is 1664 Blanc a lager?", answer: "No. Blanc is the wheat-beer style in the 1664 range." }, { question: "Why is 1664 Blanc cloudy?", answer: "Its wheat-beer style has a naturally hazier look than the clear 1664 lager." }],
    finalVerdict: "Blanc pairs the brand's familiar blue bottle with a gentler, citrus-led beer.",
    metaTitle: "1664 Blanc Beer Guide | BevOry", metaDescription: "Explore 1664 Blanc wheat beer, citrus flavour, snack pairings and city prices on BevOry.",
  },
  "fincas-valdema": {
    description: "Fincas Valdemacuco is the Ribera del Duero wine project of Spain's Valdemar family. Its Roble and Crianza reds come from Tempranillo grown outside the family's Rioja home.",
    story: "After generations in Rioja, Valdemar extended its work to Ribera del Duero. The Fincas Valdemacuco name marks that separate regional venture rather than a new Rioja label.",
    tastingNotes: [{ title: "Tempranillo fruit", description: "Dark cherry and plum give the red its core." }, { title: "Oak", description: "The Roble and Crianza styles add different degrees of spice and toast." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour a little cool in a medium red-wine glass." }, { subheading: "Food", description: "Try it with lamb seekh or mushroom kebabs." }],
    pairingIdeas: [{ title: "Ribera dinner", items: ["lamb seekh", "mushroom kebabs", "roast pork", "aged Manchego"] }],
    whyChoose: "A Valdemar red that shows the family's move from Rioja to Ribera del Duero.",
    faqs: [{ question: "Is Fincas Valdemacuco a Rioja wine?", answer: "No. It is Valdemar Family's Ribera del Duero wine project." }, { question: "What red wines does Fincas Valdemacuco make?", answer: "The range includes Roble and Crianza reds." }],
    finalVerdict: "Fincas Valdemacuco brings a darker Ribera del Duero side to the Valdemar name.",
    metaTitle: "Fincas Valdemacuco Wine Guide | BevOry", metaDescription: "Meet Valdemar's Ribera del Duero reds, Tempranillo style, pairings and city prices on BevOry.",
  },
  "godet-cognac": {
    description: "Godet is a family Cognac house based in La Rochelle, France. It blends grape eaux-de-vie from the Cognac region across several age styles.",
    story: "Bonaventure Godet brought wine to La Rochelle in the sixteenth century, and the family's spirits trade grew from the Atlantic port. Godet still ages and blends Cognac there.",
    tastingNotes: [{ title: "Fruit", description: "Orchard and dried-fruit notes lead a mature pour." }, { title: "Oak", description: "Vanilla and baking spice develop with time in wood." }],
    howToEnjoy: [{ subheading: "Sip", description: "Serve in a tulip glass at cool room temperature." }, { subheading: "Food", description: "Roasted almonds or dark chocolate suit a richer expression." }],
    pairingIdeas: [{ title: "Cognac after dinner", items: ["roasted almonds", "dark chocolate", "figs", "pecan tart"] }],
    whyChoose: "A family Cognac name with an unusual Atlantic-port home.",
    faqs: [{ question: "Where is Godet Cognac based?", answer: "Godet is based in La Rochelle on France's Atlantic coast." }, { question: "What is Godet Cognac made from?", answer: "Like other Cognacs, it is distilled from wine made with grapes grown in the Cognac region." }],
    finalVerdict: "Godet is best allowed to open slowly in a small after-dinner glass.",
    metaTitle: "Godet Cognac Guide | BevOry", metaDescription: "Explore Godet Cognac from La Rochelle, serving ideas, food pairings and city prices on BevOry.",
  },
};
