import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_37 = [
  ["x-rated", "X Rated", "France", "Liqueur", "29bc978c87043faf56cb3c75"],
  ["xanadu", "Xanadu", "Australia", "Wine", "99546aa80b4aff4c96a297de"],
  ["xenta", "Xenta", "Italy", "Absinthe", "9b136ea544ac724750f19ac9"],
  ["yamazakura", "Yamazakura", "Japan", "Whisky", "f69c9f3a8fb72f3a45f72d42"],
  ["yealands", "Yealands", "New Zealand", "Wine", "838e7984977becbd36b6c760"],
  ["yvon-mau", "Yvon Mau", "France", "Wine", "00a0b82bec02da050a63ba0d"],
  ["zampa", "Zampa", "India", "Sparkling Wine", "e868f3b49410733e98d388a9"],
  ["zardetto", "Zardetto", "Italy", "Sparkling Wine", "ac5cf9e3bc7204f1cfd45264"],
  ["zenato", "Zenato", "Italy", "Wine", "19a6f330692905b3919e13e7"],
  ["zignum", "Zignum", "Mexico", "Mezcal", "e59f4e98112d794c3c15316b"],
  ["alpaca", "Alpaca", "Chile", "Wine", "4de6702c739d8c9ed907f4c0"],
  ["bacur", "Bacur", "Italy", "Gin", "44c364a05f0607bbdecc7119"],
  ["baron-otard", "Baron Otard", "France", "Cognac", "08100f2b82f2cd6f8f2b94c2"],
  ["bhrum", "BHRUM", "India", "Rum", "ad9a359350603f7f8e465363"],
  ["casillero", "Casillero del Diablo", "Chile", "Wine", "ea2fea618fd3038936fcff95"],
  ["chivas", "Chivas", "Scotland", "Whisky", "4fb5ba9b3115cdabcc305e40"],
  ["connemara", "Connemara", "Ireland", "Whiskey", "8a32546af25d4ab8551bce13"],
  ["castelnau", "Castelnau", "France", "Champagne", "6f65a5a799cbb7d8c0ecea1e"],
  ["chartogne", "Chartogne-Taillet", "France", "Champagne", "bc4a7c80c1d197f744e0bbed"],
  ["cheval-quancard", "Cheval Quancard", "France", "Wine", "ec094664ee5680387f632274"],
  ["concha", "Concha y Toro", "Chile", "Wine", "44339bf10c86e9a13ff5c7a8"],
  ["altozano", "Altozano", "Spain", "Wine", "e55cda3ceb1131ccb93e4e00"],
  ["casa-bottega", "Casa Bottega", "Italy", "Sparkling Wine", "e839ea29e9c7baeab1c7aea4"],
  ["bosio", "Bosio", "Italy", "Wine", "5855749aa0023288d55b1546"],
  ["branca", "Branca", "Italy", "Liqueur", "135f3057000be5814264cea6"],
  ["belenkaya", "Belenkaya", "Russia", "Vodka", "8b8314333eb7aadcdde46d7a"],
  ["blue-eyes", "Blue Eyes", "India", "Vodka", "9a1e05c0fe0d0b721c7973b2"],
  ["brancaia", "Brancaia", "Italy", "Wine", "3aec77caf8ab40840cb60d4f"],
  ["botanist-the", "The Botanist", "Scotland", "Gin", "b79eec1212f376f9eea47e03"],
  ["baron-phillipe", "Baron Philippe de Rothschild", "France", "Wine", "2b33570cb0938d90b3cd10ec"],
] as const;

// Research and asset provenance stay internal; none of these URLs render as copy.
export const BRAND_SOURCES_BATCH_37: Record<string, string[]> = {
  "x-rated": ["https://www.liquor.com/brands/x-rated/", "https://www.abc.virginia.gov/products/cordials/x-rated-fusion"],
  xanadu: ["https://xanaduwines.com/about/", "https://xanaduwines.com/viticulture-and-winemaking/"],
  xenta: ["https://xenta.com/en/"],
  yamazakura: ["https://www.sasanokawa.co.jp/asaka-distillery-en/contents/productsDetail/currentProducts.html", "https://www.sasanokawa.co.jp/asaka-distillery-en/contents/story.html"],
  yealands: ["https://www.yealands.co.nz/our-story/", "https://www.yealands.co.nz/shop/single-vineyard/"],
  "yvon-mau": ["https://www.yvon-mau.com/"],
  zampa: ["https://www.groverzampa.in/about-us/art-of-winemaking", "https://www.groverzampa.in/zampa-soire%C3%A9"],
  zardetto: ["https://usa.zardettoprosecco.com/about-us/", "https://it.zardettoprosecco.com/en/wines/prosecco-brut-doc/"],
  zenato: ["https://www.zenato.it/en/the-zenato-world/"],
  zignum: ["https://www.zignummezcal.com/es/nuestros-productos/"],
  alpaca: ["https://alpacawines.com/en/about-alpaca/", "https://alpacawines.com/en/wines/premium/"],
  bacur: ["https://www.bottegaspa.com/en/collections/bacur-gin/"],
  "baron-otard": ["https://www.chateaudecognac.com/", "https://www.maisons-cognac.fr/maison/chateau-de-cognac/"],
  bhrum: ["https://alcobrew.com/wp-content/uploads/2025/09/Draft-Red-Herring-Prospectus.pdf"],
  casillero: ["https://www.casillerodeldiablo.com/wine/reserva-merlot/", "https://conchaytoro.com/en/our-history/"],
  chivas: ["https://www.chivas.com/en-us/about-us/", "https://www.chivas.com/en-us/collection/chivas-12/"],
  connemara: ["https://www.connemarawhiskey.com/"],
  castelnau: ["https://www.champagne-castelnau.fr/pages/histoire"],
  chartogne: ["https://chartogne-taillet.com/en/vin/sainte-anne/details", "https://chartogne-taillet.com/en/contact"],
  "cheval-quancard": ["https://www.chevalquancard.com/cheval-quancard/"],
  concha: ["https://conchaytoro.com/en/our-history/"],
  altozano: ["https://fincaconstancia.es/wp-content/uploads/2016/09/altozano-tempranillo_cabernet-ES-NE.pdf", "https://fincaconstancia.es/wp-content/uploads/2016/08/altozano-verdejo-semi_ENG-2015.pdf"],
  "casa-bottega": ["https://www.bottegaspa.com/en/collections/prosecco-spumante-doc-brut-casa-bottega/"],
  bosio: ["https://www.bosiovini.it/it/", "https://www.bosiovini.it/it/vino-56-gavi-docg"],
  branca: ["https://www.brancadistillerie.com/en/product/brancamenta-en/", "https://www.brancamenta.it/history"],
  belenkaya: ["https://novabev.com/en/brands/vodka/belenkaya/"],
  "blue-eyes": ["https://results.spiritsselection.com/en/results/2018/125991-blue-eyes-pure-grain-vodka"],
  brancaia: ["https://brancaia.com/en/about-us/history/"],
  "botanist-the": ["https://www.thebotanist.com/products/the-botanist-islay-dry-gin-750-ml", "https://www.thebotanist.com/products/the-botanist-cask-aged-gin"],
  "baron-phillipe": ["https://www.bpdr.com/en/branded-wines/pays-doc-2", "https://www.bpdr.com/en/the-history/key-dates"],
};

// Only exact brand marks inspected on the named producer's site are listed.
export const BRAND_LOGOS_BATCH_37: Record<string, string> = {
  xanadu: "https://xanaduwines.com/wp-content/uploads/XANADU-LOGO-DIGITAL-WHITE-RGB-1-1.png",
  xenta: "https://xenta.com/wp-content/uploads/2024/08/cropped-logo-1-1.png",
  zignum: "https://www.zignummezcal.com/logos/zignum.svg",
  castelnau: "https://www.champagne-castelnau.fr/cdn/shop/files/logo_b39221f1-eb86-4538-818b-a222df2088e0.svg?v=1682358452&width=250",
  connemara: "https://www.connemarawhiskey.com/themes/custom/bsi_theme/bsi_subtheme/logo.svg",
  "botanist-the": "https://www.thebotanist.com/cdn/shop/t/81/assets/logo-black.svg?v=103286762910329297331743598196",
};

export const BRAND_CONTENT_BATCH_37: Record<string, BrandPublicContent> = {
  "x-rated": {
    description: "X Rated Fusion is a French vodka-based fruit liqueur combining blood orange, mango and passion fruit. Its bright pink colour and citrus-fruit profile suit chilled mixed drinks.",
    story: "Introduced in 2005, X Rated Fusion brought French vodka and tropical fruit into one liqueur. It became known for its tall frosted bottle as much as its punchy fruit blend.",
    tastingNotes: [{ title: "Citrus", description: "Blood orange gives the first sip a tart, juicy edge." }, { title: "Tropical fruit", description: "Mango and passion fruit follow with a sweeter finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve over ice with soda or sparkling wine and a slice of orange." }, { subheading: "Food", description: "Try it beside chilli paneer or a plate of fresh mango and lime." }],
    pairingIdeas: [{ title: "Fruit and spice", items: ["chilli paneer", "mango chaat", "grilled prawns", "orange sorbet"] }],
    whyChoose: "A blood-orange liqueur for drinkers who want tropical fruit without building a complicated cocktail.",
    faqs: [{ question: "What is X Rated Fusion?", answer: "It is a French vodka-based liqueur flavoured with blood orange, mango and passion fruit." }, { question: "How do you serve X Rated Fusion?", answer: "Serve it chilled over ice, or lengthen it with soda or sparkling wine." }],
    finalVerdict: "Its tart orange opening makes the sweet fruit easier to enjoy over ice.",
    metaTitle: "X Rated Liqueur Guide | BevOry", metaDescription: "Explore X Rated Fusion's blood orange and tropical fruit profile, serving ideas and city prices on BevOry.",
  },
  xanadu: {
    description: "Xanadu makes wine in Western Australia's Margaret River region, including Chardonnay and Cabernet Sauvignon. Its vineyards and cellar door sit on Boodjidup Road near the town of Margaret River.",
    story: "Founded in 1977, Xanadu grew alongside Margaret River's young wine industry. Its present winemaking approach puts regional fruit ahead of heavy cellar treatment.",
    tastingNotes: [{ title: "Chardonnay", description: "Citrus and stone-fruit notes give the white a fresh opening." }, { title: "Cabernet Sauvignon", description: "Blackcurrant fruit and firm tannin make the red a more substantial pour." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill Chardonnay lightly; give Cabernet Sauvignon a broad red-wine glass." }, { subheading: "Food", description: "Pour the white with tandoori fish and the red with lamb seekh kebabs." }],
    pairingIdeas: [{ title: "Margaret River table", items: ["tandoori fish", "lamb seekh kebabs", "roast chicken", "mushroom pulao"] }],
    whyChoose: "A Margaret River producer with a clear focus on the region's Chardonnay and Cabernet Sauvignon.",
    faqs: [{ question: "Where is Xanadu wine made?", answer: "Xanadu is based in Margaret River, Western Australia." }, { question: "Which grapes is Xanadu known for?", answer: "Chardonnay and Cabernet Sauvignon are prominent in its range." }],
    finalVerdict: "Xanadu is worth considering when the wine's Margaret River origin matters as much as the grape.",
    metaTitle: "Xanadu Wine Guide | BevOry", metaDescription: "Meet Xanadu's Margaret River Chardonnay and Cabernet Sauvignon, food pairings and city prices on BevOry.",
  },
  xenta: {
    description: "Xenta is an Italian absinthe built around Artemisia absinthium and a blend of herbs and spices. Allied Brands presents it as a green, herbal spirit for traditional diluted serves and cocktails.",
    story: "Xenta's wormwood is sourced from the northern Italian Alps; the floral tops are cut before flowering. Its recipe combines ten herbs and spices, mostly of Alpine origin.",
    tastingNotes: [{ title: "Herbal nose", description: "Wormwood leads the aroma with a dry, green bitterness." }, { title: "Spiced finish", description: "The broader herb blend gives the finish a lingering savoury warmth." }],
    howToEnjoy: [{ subheading: "Dilute", description: "Add cold water gradually over ice to soften the herb intensity." }, { subheading: "At the table", description: "A small diluted pour works alongside salted almonds or fennel crackers." }],
    pairingIdeas: [{ title: "Salty bites", items: ["salted almonds", "fennel crackers", "olive tapenade", "fried paneer"] }],
    whyChoose: "The Alpine wormwood gives Xenta a recognisable bitter-herbal centre.",
    faqs: [{ question: "What is Xenta?", answer: "Xenta is an Italian absinthe flavoured with wormwood and other herbs and spices." }, { question: "Can Xenta be used in cocktails?", answer: "Yes. It can be diluted with water or used sparingly in spirit-led cocktails." }],
    finalVerdict: "Choose Xenta for a measured, herbal pour rather than a sweet liqueur.",
    metaTitle: "Xenta Absinthe Guide | BevOry", metaDescription: "Discover Xenta's Alpine wormwood, herbal flavour, serves and city prices on BevOry.",
  },
  yamazakura: {
    description: "Yamazakura is a whisky label from Sasanokawa Shuzo in Fukushima, Japan. The range includes blended whiskies and releases connected to its Asaka Distillery.",
    story: "Sasanokawa Shuzo's roots are in sake making in Fukushima. Whisky production at Asaka adds a local distilling chapter to the older family business, while Yamazakura carries the company's whisky name.",
    tastingNotes: [{ title: "Blended Whisky Black Label", description: "Malt sweetness and gentle oak make this the softer entry to the range." }, { title: "Asaka malt", description: "The distillery-led releases bring more grain and cask character into view." }],
    howToEnjoy: [{ subheading: "Taste", description: "Try a small neat pour before adding water; a highball suits the lighter blends." }, { subheading: "Food", description: "Pair a highball with chicken yakitori or peppery mushroom skewers." }],
    pairingIdeas: [{ title: "Japanese table", items: ["chicken yakitori", "mushroom skewers", "salted edamame", "tandoori chicken"] }],
    whyChoose: "A Fukushima whisky name with both approachable blends and Asaka distillery releases.",
    faqs: [{ question: "Who makes Yamazakura whisky?", answer: "Sasanokawa Shuzo in Fukushima, Japan, makes Yamazakura whisky." }, { question: "Is every Yamazakura whisky a single malt?", answer: "No. The range includes blended whisky as well as distillery-led malt releases." }],
    finalVerdict: "The lighter blends fit a highball; Asaka releases invite a slower glass.",
    metaTitle: "Yamazakura Whisky Guide | BevOry", metaDescription: "Explore Yamazakura whisky from Fukushima, Asaka releases, food pairings and city prices on BevOry.",
  },
  yealands: {
    description: "Yealands makes New Zealand wine from Marlborough's coastal Awatere Valley. Sauvignon Blanc from its Seaview Vineyard is central to the range.",
    story: "Seaview was once windswept pasture near the Cook Strait. The vineyard's coastal exposure and cool nights now shape Yealands' aromatic white wines.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Citrus, green herbs and a brisk finish suit the Awatere Valley's cool edge." }, { title: "Seaview Vineyard", description: "Its single-vineyard Sauvignon Blanc has a more pronounced mineral line." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve in a white-wine glass, cool enough to keep its acidity lively." }, { subheading: "Food", description: "Try it with tandoori prawns or coriander-lime fish." }],
    pairingIdeas: [{ title: "Coastal pairings", items: ["tandoori prawns", "coriander-lime fish", "goat cheese", "green pea tikki"] }],
    whyChoose: "A coastal Marlborough Sauvignon Blanc with a lively herbal-citrus profile.",
    faqs: [{ question: "Where are Yealands wines made?", answer: "Yealands is based in Marlborough's Awatere Valley, New Zealand." }, { question: "What is Yealands Seaview Vineyard?", answer: "It is the company's coastal vineyard in the Awatere Valley." }],
    finalVerdict: "Yealands Sauvignon Blanc belongs next to seafood, herbs and a squeeze of lime.",
    metaTitle: "Yealands Wine Guide | BevOry", metaDescription: "Meet Yealands' Awatere Valley Sauvignon Blanc, coastal style, pairings and city prices on BevOry.",
  },
  "yvon-mau": {
    description: "Yvon Mau is a Bordeaux wine house that selects and markets French wines, including red and white bottlings. It works across more than one Bordeaux appellation rather than a single vineyard.",
    story: "The Mau family name has long been tied to Bordeaux's wine trade. Its merchant role is to select wines from growers and estates, giving the label a broader regional reach than one chateau could offer.",
    tastingNotes: [{ title: "Bordeaux red", description: "Dark fruit and supple tannin suit the region's Merlot-led style." }, { title: "Bordeaux white", description: "Citrus and a clean finish make the white a lighter counterpoint." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the white chilled and the red slightly below room temperature." }, { subheading: "Food", description: "Try red with mutton seekh and white with grilled pomfret." }],
    pairingIdeas: [{ title: "Bordeaux at dinner", items: ["mutton seekh", "grilled pomfret", "mushroom galouti", "roast chicken"] }],
    whyChoose: "A Bordeaux merchant name that offers both red and white wines for different meals.",
    faqs: [{ question: "Is Yvon Mau a Bordeaux producer?", answer: "Yvon Mau is a Bordeaux wine house that selects and markets wines from the region." }, { question: "Does Yvon Mau make white wine?", answer: "Yes. Its range includes white as well as red wine." }],
    finalVerdict: "Yvon Mau is a practical route into Bordeaux without tying the choice to a single estate.",
    metaTitle: "Yvon Mau Wine Guide | BevOry", metaDescription: "Explore Yvon Mau's Bordeaux reds and whites, dinner pairings and city prices on BevOry.",
  },
  zampa: {
    description: "Zampa is the sparkling-wine label of Grover Zampa Vineyards in India. Its Soiree bottles include Brut and Brut Rose, made for crisp, food-friendly pours.",
    story: "Grover Zampa draws fruit from vineyards around Nashik and Nandi Hills. The Zampa Soiree range gives the winery a distinctly Indian sparkling-wine line rather than another still red or white.",
    tastingNotes: [{ title: "Soiree Brut", description: "A fresh, dry profile gives the bubbles an aperitif edge." }, { title: "Soiree Brut Rose", description: "Brief skin contact brings pale colour and red-fruit aromas." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill well and pour into a tulip-shaped sparkling-wine glass." }, { subheading: "Food", description: "Brut works with pakoras; the rose takes paneer tikka." }],
    pairingIdeas: [{ title: "Indian aperitif", items: ["onion pakoras", "paneer tikka", "tandoori prawns", "strawberries"] }],
    whyChoose: "Indian-made sparkling wine that sits easily beside fried and spiced starters.",
    faqs: [{ question: "Who makes Zampa sparkling wine?", answer: "Grover Zampa Vineyards makes the Zampa Soiree sparkling-wine range." }, { question: "Does Zampa make rose sparkling wine?", answer: "Yes. Zampa Soiree Brut Rose is part of the range." }],
    finalVerdict: "Chilled Zampa Brut earns its place at the start of an Indian dinner.",
    metaTitle: "Zampa Sparkling Wine Guide | BevOry", metaDescription: "Discover Zampa Soiree Brut and Rose, serving ideas, Indian pairings and city prices on BevOry.",
  },
  zardetto: {
    description: "Zardetto makes Prosecco and other sparkling wines around Conegliano in Italy's Veneto. Its range includes Prosecco DOC Brut and Conegliano Valdobbiadene DOCG wines.",
    story: "Bepi Zardetto began cultivating vines in the early twentieth century; the family later built a sparkling-wine business under Pino and Fabio Zardetto. Conegliano remains the name behind the label's Prosecco identity.",
    tastingNotes: [{ title: "Prosecco Brut", description: "Fine bubbles, orchard fruit and a citrus lift keep the Brut fresh." }, { title: "Extra Dry", description: "Glera's pear and floral notes feel softer in the Extra Dry style." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tulip glass to keep the bubbles lively." }, { subheading: "Food", description: "Try Brut with fish pakoras or Extra Dry with chilli paneer." }],
    pairingIdeas: [{ title: "Bubbles and bites", items: ["fish pakoras", "chilli paneer", "prosciutto", "fried zucchini"] }],
    whyChoose: "A family Prosecco house with both dry aperitif bottles and softer sparkling styles.",
    faqs: [{ question: "Where is Zardetto Prosecco from?", answer: "Zardetto is based in the Conegliano area of Italy's Veneto region." }, { question: "What grape is used for Zardetto Prosecco?", answer: "Glera is the principal grape in its Prosecco wines." }],
    finalVerdict: "Zardetto Brut makes a lively first glass with salty, crisp starters.",
    metaTitle: "Zardetto Prosecco Guide | BevOry", metaDescription: "Explore Zardetto Prosecco from Conegliano, Glera flavour, food pairings and city prices on BevOry.",
  },
  zenato: {
    description: "Zenato is an Italian family winery working in Lugana and Valpolicella. Its wines span Trebbiano di Lugana whites and richer Valpolicella reds.",
    story: "Sergio Zenato and Carla Prospero started the business in San Benedetto di Lugana in 1960. Their children Nadia and Alberto continue the work from Lake Garda's southern shore to the hills of Valpolicella.",
    tastingNotes: [{ title: "Lugana", description: "Trebbiano di Lugana brings citrus and stone fruit with a clean mineral finish." }, { title: "Amarone", description: "Dried dark fruit and spice give the Valpolicella red a much fuller frame." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill Lugana; give Amarone a roomy red-wine glass." }, { subheading: "Food", description: "Lugana works with fish tikka, Amarone with slow-cooked mutton." }],
    pairingIdeas: [{ title: "Lake and hills", items: ["fish tikka", "slow-cooked mutton", "mushroom risotto", "aged parmesan"] }],
    whyChoose: "One family estate offers the contrast of bright Lugana and deep Valpolicella reds.",
    faqs: [{ question: "Where is Zenato based?", answer: "Zenato began in San Benedetto di Lugana near Lake Garda, with vineyards also in Valpolicella." }, { question: "Which grapes are linked to Zenato?", answer: "Trebbiano di Lugana is central to its whites; Corvina features in its Valpolicella reds." }],
    finalVerdict: "Zenato gives a clear choice between a brisk white and a slow-sipping red.",
    metaTitle: "Zenato Wine Guide | BevOry", metaDescription: "Compare Zenato Lugana and Valpolicella styles, serving ideas, pairings and city prices on BevOry.",
  },
  zignum: {
    description: "Zignum makes mezcal from Espadin agave in Oaxaca, Mexico. Its range includes Joven and oak-matured Reposado, Anejo and Cristalino bottlings.",
    story: "Zignum uses mature Agave angustifolia from Oaxaca and distils it into a notably clean-tasting mezcal. The name means spearhead, while its Metodo Verde programme centres on the distillery's environmental practices.",
    tastingNotes: [{ title: "Joven", description: "Floral and citrus notes leave the agave easy to pick out." }, { title: "Reposado", description: "American oak brings honey, vanilla and caramel beside the agave." }],
    howToEnjoy: [{ subheading: "Sip", description: "Pour Joven into a small copita and taste slowly; Reposado also works over one large cube." }, { subheading: "Food", description: "Pair with tandoori prawns or grilled corn and lime." }],
    pairingIdeas: [{ title: "Agave and heat", items: ["tandoori prawns", "grilled corn", "chilli-lime peanuts", "quesadillas"] }],
    whyChoose: "An Espadin mezcal that lets the drinker compare fresh agave with oak-aged versions.",
    faqs: [{ question: "What agave is used in Zignum?", answer: "Zignum uses Espadin, the Agave angustifolia variety." }, { question: "Is Zignum Reposado aged?", answer: "Yes. Its Reposado rests in American oak barrels." }],
    finalVerdict: "Start with Joven for agave; move to Reposado when you want sweeter oak notes.",
    metaTitle: "Zignum Mezcal Guide | BevOry", metaDescription: "Explore Zignum Espadin mezcal from Oaxaca, Joven and Reposado flavours, pairings and city prices on BevOry.",
  },
  alpaca: {
    description: "Alpaca is a Chilean wine range named after an animal closely associated with the Andes. Its bottles include varietal whites and reds from Chilean vineyards.",
    story: "The alpaca on the label places the wine in an Andean landscape, not a European chateau. The range was built to make familiar grape varieties approachable at the dinner table.",
    tastingNotes: [{ title: "Premium Chardonnay", description: "Pineapple, peach and a light citrus edge give the white a broad, fresh profile." }, { title: "Premium Cabernet Sauvignon", description: "Berry, cherry and cassis lead into subtle vanilla and chocolate." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill Chardonnay; serve Cabernet Sauvignon a little cool in a red-wine glass." }, { subheading: "Food", description: "Put the white beside paneer tikka and the red beside pepper chicken." }],
    pairingIdeas: [{ title: "Weeknight plates", items: ["paneer tikka", "pepper chicken", "roasted peppers", "grilled lamb"] }],
    whyChoose: "A Chilean varietal range that makes matching wine to a meal straightforward.",
    faqs: [{ question: "Where is Alpaca wine from?", answer: "Alpaca is a Chilean wine range." }, { question: "Does Alpaca make red and white wine?", answer: "Yes. Its range includes white and red varietal wines." }],
    finalVerdict: "Choose the grape first: a cooler white for starters or a darker red for the main course.",
    metaTitle: "Alpaca Wine Guide | BevOry", metaDescription: "Explore Alpaca wines from Chile, grape styles, Indian food pairings and city prices on BevOry.",
  },
  bacur: {
    description: "Bacur is a distilled dry gin made by Bottega in Italy's Veneto region. Juniper, sage and lemon zest form its botanical core.",
    story: "Bottega macerates Tuscan juniper, Veneto sage and Sicilian lemon zest before double-distilling Bacur. The short botanical list gives the gin its Mediterranean character without burying the juniper.",
    tastingNotes: [{ title: "Juniper and lemon", description: "Juniper leads, followed by a clear note of lemon zest." }, { title: "Sage finish", description: "A savoury sage hint keeps the finish dry and aromatic." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Serve over ice with dry tonic and a thin lemon slice." }, { subheading: "Food", description: "Try it with tandoori prawns or herb-roasted paneer." }],
    pairingIdeas: [{ title: "Herb and citrus", items: ["tandoori prawns", "herb-roasted paneer", "grilled courgette", "salted olives"] }],
    whyChoose: "An Italian gin with a short, distinctive juniper-lemon-sage botanical line.",
    faqs: [{ question: "Who makes Bacur gin?", answer: "Bottega makes Bacur in the Veneto region of Italy." }, { question: "Which botanicals stand out in Bacur?", answer: "Juniper, sage and lemon zest shape its aroma." }],
    finalVerdict: "Bacur makes a crisp gin and tonic when lemon and savoury herbs are the point.",
    metaTitle: "Bacur Gin Guide | BevOry", metaDescription: "Discover Bacur gin's juniper, sage and lemon notes, food pairings and city prices on BevOry.",
  },
  "baron-otard": {
    description: "Baron Otard is a Cognac house based at the Chateau de Cognac in western France. Its range includes VSOP and XO expressions of grape-based French brandy.",
    story: "The house took shape at the end of the eighteenth century and still identifies with the riverside chateau in Cognac. The castle is also known as the birthplace of Francis I, giving the label an unusually tangible home.",
    tastingNotes: [{ title: "VSOP", description: "Orchard fruit and vanilla lead into a rounded oak finish." }, { title: "XO", description: "Older eaux-de-vie bring dried fruit and deeper spice." }],
    howToEnjoy: [{ subheading: "Sip", description: "Serve a small pour in a tulip-shaped glass and let it warm in the hand." }, { subheading: "Food", description: "Try VSOP with roasted almonds or XO with dark chocolate." }],
    pairingIdeas: [{ title: "After dinner", items: ["roasted almonds", "dark chocolate", "figs", "pecan tart"] }],
    whyChoose: "A Cognac house whose chateau setting is part of its living production story.",
    faqs: [{ question: "Where is Baron Otard made?", answer: "Baron Otard is a Cognac house based at the Chateau de Cognac in France." }, { question: "What is the difference between VSOP and XO?", answer: "XO is the older Cognac category; the two Baron Otard bottlings differ in maturation and flavour." }],
    finalVerdict: "Baron Otard earns a slow glass after dinner, especially with nuts or chocolate.",
    metaTitle: "Baron Otard Cognac Guide | BevOry", metaDescription: "Discover Baron Otard Cognac, VSOP and XO styles, food pairings and city prices on BevOry.",
  },
  bhrum: {
    description: "BHRUM is a lemon-flavoured white rum from Alcobrew Distilleries India. Citrus, rather than oak or spice, defines this rum's intended style.",
    story: "Alcobrew added BHRUM to a portfolio that already included Indian whisky and vodka labels. The lemon-led rum was developed as a bright mixing spirit for long drinks.",
    tastingNotes: [{ title: "Lemon", description: "A zesty citrus note comes through first." }, { title: "White rum base", description: "The clear spirit keeps the drink lighter than an oak-aged rum." }],
    howToEnjoy: [{ subheading: "Long drink", description: "Pour over ice with soda and a squeeze of fresh lime." }, { subheading: "Food", description: "Its lemon note suits fried fish or chilli-lime corn." }],
    pairingIdeas: [{ title: "Citrus snacks", items: ["fried fish", "chilli-lime corn", "peri-peri paneer", "salted cashews"] }],
    whyChoose: "A lemon-first Indian rum for a quick, cold highball.",
    faqs: [{ question: "Who makes BHRUM?", answer: "BHRUM is made by Alcobrew Distilleries India." }, { question: "What flavour is BHRUM?", answer: "It is a lemon-flavoured white rum." }],
    finalVerdict: "BHRUM's sharp citrus is the point: keep the mixer simple and the glass cold.",
    metaTitle: "BHRUM Rum Guide | BevOry", metaDescription: "Explore BHRUM lemon-flavoured white rum, citrus serves, snack pairings and city prices on BevOry.",
  },
  casillero: {
    description: "Casillero del Diablo is a Chilean wine range from Concha y Toro. Its Reserva Merlot comes from the Central Valley and has a soft, medium-bodied red-wine style.",
    story: "The name comes from Melchor Concha y Toro's tale of a devil guarding his wine cellar. That cellar story became the identity of a range now spanning several Chilean grape varieties.",
    tastingNotes: [{ title: "Merlot fruit", description: "Cherry and red berries make the Reserva Merlot immediately approachable." }, { title: "Oak detail", description: "Liquorice, vanilla and toffee add a warmer edge to the finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour the Merlot slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try it with keema pav, tomato pasta or mushroom risotto." }],
    pairingIdeas: [{ title: "Merlot dinner", items: ["keema pav", "tomato pasta", "mushroom risotto", "paneer tikka"] }],
    whyChoose: "A Central Valley Merlot with soft tannin and enough fruit for a spice-led dinner.",
    faqs: [{ question: "Who makes Casillero del Diablo?", answer: "Chilean winery Concha y Toro makes Casillero del Diablo." }, { question: "Where is its Reserva Merlot from?", answer: "The Reserva Merlot comes from Chile's Central Valley." }],
    finalVerdict: "Casillero del Diablo Merlot is at home beside tomato, mushrooms and mildly spiced food.",
    metaTitle: "Casillero del Diablo Wine | BevOry", metaDescription: "Explore Casillero del Diablo Merlot, its Chilean cellar story, food pairings and city prices on BevOry.",
  },
  chivas: {
    description: "Chivas Regal is a blended Scotch whisky made from malt and grain whiskies, with Strathisla malt at its centre. The range includes Chivas 12 and older blends.",
    story: "James and John Chivas built their business in Aberdeen; the Chivas Regal name reached the US in the early twentieth century. The 12-year-old blend arrived in 1938 after Prohibition.",
    tastingNotes: [{ title: "Chivas 12", description: "Honey, orchard fruit and a soft grain sweetness define the blend's approachable side." }, { title: "Strathisla malt", description: "Speyside malt gives the blends a rounded, fruit-led core." }],
    howToEnjoy: [{ subheading: "Highball", description: "Try Chivas 12 with ice and soda; a neat pour shows more of the malt." }, { subheading: "Food", description: "Pair with galouti kebabs or roasted almonds." }],
    pairingIdeas: [{ title: "Whisky table", items: ["galouti kebabs", "roasted almonds", "butter chicken", "aged cheddar"] }],
    whyChoose: "A Speyside-centred blend with a softer profile than heavily peated Scotch.",
    faqs: [{ question: "Is Chivas Regal a single malt?", answer: "No. It is a blended Scotch whisky made from malt and grain whiskies." }, { question: "Which malt is central to Chivas?", answer: "Strathisla single malt is central to the Chivas Regal blends." }],
    finalVerdict: "Chivas 12 is a comfortable first Scotch highball with a savoury plate.",
    metaTitle: "Chivas Whisky Guide | BevOry", metaDescription: "Explore Chivas Regal blended Scotch, Strathisla malt, pairings and city prices on BevOry.",
  },
  connemara: {
    description: "Connemara is an Irish peated single malt whiskey from the Kilbeggan Distilling Company. Smoke sets it apart from many unpeated Irish whiskeys.",
    story: "The whiskey takes its name from the boggy Connemara landscape in western Ireland. Its peated malt revives a flavour once more familiar in Irish whiskey making, though the brand is associated with the Kilbeggan distilling group.",
    tastingNotes: [{ title: "Peat smoke", description: "Earthy smoke is present without covering the malt." }, { title: "Malt and fruit", description: "A softer grain sweetness keeps the smoke from turning harsh." }],
    howToEnjoy: [{ subheading: "Neat", description: "Taste neat first, then add a few drops of water to open the smoky notes." }, { subheading: "Food", description: "Try it with smoked paneer or grilled mutton seekh." }],
    pairingIdeas: [{ title: "Smoke and salt", items: ["smoked paneer", "mutton seekh", "grilled mushrooms", "dark chocolate"] }],
    whyChoose: "An Irish single malt for drinkers curious about peat smoke without a heavy Islay-style profile.",
    faqs: [{ question: "Is Connemara whiskey peated?", answer: "Yes. Peated malt is central to Connemara's flavour." }, { question: "Is Connemara Scotch?", answer: "No. Connemara is an Irish single malt whiskey." }],
    finalVerdict: "Connemara bridges Irish malt sweetness and a clear line of peat smoke.",
    metaTitle: "Connemara Whiskey Guide | BevOry", metaDescription: "Discover Connemara peated Irish single malt, smoky food pairings and city prices on BevOry.",
  },
  castelnau: {
    description: "Champagne Castelnau is a French Champagne house founded in 1916. Its cuvees are known for extended ageing on lees and fine bubbles.",
    story: "Castelnau began as an association of Champagne enthusiasts and later reached drinkers outside France. The thistle has returned to its emblem, linking the current bottles to the house's early identity.",
    tastingNotes: [{ title: "Fine mousse", description: "Slow lees ageing gives the bubbles a softer, finer texture." }, { title: "Brut style", description: "Citrus and baked-bread notes make the wine both brisk and rounded." }],
    howToEnjoy: [{ subheading: "Chill", description: "Pour into a tulip glass so the bubbles and aroma stay in focus." }, { subheading: "Food", description: "Serve with tandoori prawns or crisp potato pakoras." }],
    pairingIdeas: [{ title: "Champagne starters", items: ["tandoori prawns", "potato pakoras", "oysters", "parmesan biscuits"] }],
    whyChoose: "A Champagne house that gives lees ageing time to shape the texture.",
    faqs: [{ question: "When was Champagne Castelnau founded?", answer: "Champagne Castelnau was founded in 1916." }, { question: "What gives Castelnau its texture?", answer: "The house uses extended ageing on lees to develop its fine mousse." }],
    finalVerdict: "Castelnau Brut is a good table Champagne when the starter is salty or fried.",
    metaTitle: "Castelnau Champagne Guide | BevOry", metaDescription: "Explore Castelnau Champagne, lees-aged texture, Indian pairings and city prices on BevOry.",
  },
  chartogne: {
    description: "Chartogne-Taillet makes grower Champagne in Merfy, north of Reims. Its Sainte Anne cuvee brings together wines from different plots around the village.",
    story: "The Chartogne-Taillet family has deep roots in Merfy; Alexandre Chartogne now gives individual sites close attention. Sainte Anne is the house's way of showing the village as a whole rather than one parcel.",
    tastingNotes: [{ title: "Sainte Anne", description: "The opening feels full before the finish tightens." }, { title: "Merfy soils", description: "A saline edge and gentle bitterness bring the village's different plots into focus." }],
    howToEnjoy: [{ subheading: "Glass", description: "Use a tulip-shaped glass rather than a narrow flute." }, { subheading: "Food", description: "Its acidity works with prawn tempura or fish pakoras." }],
    pairingIdeas: [{ title: "Merfy pairings", items: ["prawn tempura", "fish pakoras", "comte cheese", "roasted cauliflower"] }],
    whyChoose: "A grower Champagne rooted in the vineyards of one village.",
    faqs: [{ question: "Where is Chartogne-Taillet based?", answer: "The Champagne house is based in Merfy, north of Reims." }, { question: "What is Sainte Anne?", answer: "Sainte Anne is a Chartogne-Taillet cuvee blending wines from different Merfy plots." }],
    finalVerdict: "Sainte Anne brings village-level Champagne character to a seafood starter.",
    metaTitle: "Chartogne-Taillet Champagne | BevOry", metaDescription: "Explore Chartogne-Taillet Champagne from Merfy, Sainte Anne, food pairings and city prices on BevOry.",
  },
  "cheval-quancard": {
    description: "Cheval Quancard is a Bordeaux wine house with reds and whites from several French appellations. Its range stretches beyond one estate, from everyday varietal bottles to named chateaux.",
    story: "The Quancard family's Bordeaux trade took the Cheval Quancard name in 1985. That merchant background lets the house work with different vineyards and appellations rather than one patch of land.",
    tastingNotes: [{ title: "Bordeaux red", description: "Dark fruit and soft tannin make its red wines suited to food." }, { title: "Bordeaux white", description: "Citrus and fresh acidity bring a lighter option to the table." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the white; pour the red slightly cool in a medium-sized glass." }, { subheading: "Food", description: "Try white with fish tikka and red with mutton kebabs." }],
    pairingIdeas: [{ title: "Bordeaux dinners", items: ["fish tikka", "mutton kebabs", "roast aubergine", "grilled chicken"] }],
    whyChoose: "A Bordeaux house with more than one appellation and a choice of red or white.",
    faqs: [{ question: "Is Cheval Quancard a single chateau?", answer: "No. It is a Bordeaux wine house working across several appellations and estates." }, { question: "Does Cheval Quancard make white wine?", answer: "Yes. Its portfolio includes white and red Bordeaux wines." }],
    finalVerdict: "The house is useful when you want Bordeaux on the table but not one fixed style.",
    metaTitle: "Cheval Quancard Wine Guide | BevOry", metaDescription: "Explore Cheval Quancard Bordeaux reds and whites, Indian pairings and city prices on BevOry.",
  },
  concha: {
    description: "Concha y Toro is a Chilean winery founded in Pirque near Santiago. Its family of wines includes Casillero del Diablo and Marques de Casa Concha.",
    story: "Melchor Concha y Toro established the winery in 1883 after bringing French vines from Bordeaux to Chile. The firm's first export left for the Netherlands in 1933, opening the way for a much wider international presence.",
    tastingNotes: [{ title: "Cabernet Sauvignon", description: "Blackcurrant and structured tannin suit the winery's Chilean reds." }, { title: "Sauvignon Blanc", description: "Citrus and herbal notes make a crisp contrast to the reds." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give Cabernet a red-wine glass and serve Sauvignon Blanc chilled." }, { subheading: "Food", description: "The red suits lamb seekh; the white works with tandoori prawns." }],
    pairingIdeas: [{ title: "Chilean wine table", items: ["lamb seekh", "tandoori prawns", "grilled peppers", "roast chicken"] }],
    whyChoose: "One historic Chilean winery offers a broad route through familiar wine grapes.",
    faqs: [{ question: "Who founded Concha y Toro?", answer: "Melchor Concha y Toro founded the Chilean winery in 1883." }, { question: "Is Casillero del Diablo part of Concha y Toro?", answer: "Yes. Casillero del Diablo is one of the winery's wine ranges." }],
    finalVerdict: "Concha y Toro gives Chilean Cabernet and Sauvignon Blanc room at different parts of dinner.",
    metaTitle: "Concha y Toro Wine Guide | BevOry", metaDescription: "Discover Concha y Toro's Chilean wine history, red and white styles, pairings and city prices on BevOry.",
  },
  altozano: {
    description: "Altozano is a Spanish wine range from Finca Constancia near Toledo. Its bottles include Tempranillo-led reds and Verdejo-Sauvignon Blanc whites.",
    story: "Finca Constancia uses separate vineyard parcels to build Altozano's approachable varietal wines. Tempranillo and Cabernet Sauvignon meet in one red, while Verdejo gives the white a distinctly Spanish footing.",
    tastingNotes: [{ title: "Tempranillo blend", description: "Red fruit, floral notes and a touch of liquorice shape the red." }, { title: "Verdejo blend", description: "Fresh fruit and a rounded texture come from the white's time on lees." }],
    howToEnjoy: [{ subheading: "Pour", description: "Chill the white well; serve the red just below room temperature." }, { subheading: "Food", description: "Try white with fish pakoras and red with lamb chops." }],
    pairingIdeas: [{ title: "Spanish-style dinner", items: ["fish pakoras", "grilled lamb chops", "patatas bravas", "paneer tikka"] }],
    whyChoose: "A Toledo wine range that lets Tempranillo and Verdejo lead different meals.",
    faqs: [{ question: "Who makes Altozano wine?", answer: "Finca Constancia in Spain makes Altozano." }, { question: "Does Altozano make white wine?", answer: "Yes. Altozano includes Verdejo and Sauvignon Blanc white wines." }],
    finalVerdict: "Altozano makes the choice simple: Verdejo for a crisp starter, Tempranillo for the main.",
    metaTitle: "Altozano Wine Guide | BevOry", metaDescription: "Explore Altozano wines from Toledo, Tempranillo and Verdejo styles, pairings and city prices on BevOry.",
  },
  "casa-bottega": {
    description: "Casa Bottega is an Italian sparkling-wine line from Bottega in the Veneto. The range includes Prosecco Brut and Prosecco Rose bottlings.",
    story: "Bottega's home is Bibano in the province of Treviso, close to the Prosecco hills. Casa Bottega carries that sparkling-wine tradition in a more understated bottle than the producer's metallic Gold label.",
    tastingNotes: [{ title: "Prosecco Brut", description: "Apple and light citrus come through fine, lively bubbles." }, { title: "Prosecco Rose", description: "Red berry notes add a softer fruit edge to the bubbles." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tulip glass, without a mixer." }, { subheading: "Food", description: "Brut suits fried calamari; rose works with chilli paneer." }],
    pairingIdeas: [{ title: "Sparkling starters", items: ["fried calamari", "chilli paneer", "vegetable tempura", "strawberries"] }],
    whyChoose: "A Veneto sparkling-wine line with both crisp white and fruitier rose options.",
    faqs: [{ question: "Who makes Casa Bottega?", answer: "Bottega S.p.A. makes Casa Bottega sparkling wines in Italy's Veneto region." }, { question: "Is Casa Bottega a Prosecco?", answer: "The Casa Bottega range includes Prosecco Brut and Prosecco Rose." }],
    finalVerdict: "Casa Bottega Brut is a clean aperitif; the rose brings a touch more fruit to the table.",
    metaTitle: "Casa Bottega Prosecco Guide | BevOry", metaDescription: "Discover Casa Bottega Prosecco Brut and Rose, food pairings and city prices on BevOry.",
  },
  bosio: {
    description: "Bosio Family Estates makes wine in Italy's Piedmont, including Gavi and Barolo. Cortese shapes its Gavi whites, while Nebbiolo is the grape behind Barolo.",
    story: "Egidio and Angela Bosio began their winery in 1967. The family is based in Santo Stefano Belbo and now works across several Piedmont appellations rather than a single grape or village.",
    tastingNotes: [{ title: "Gavi", description: "Cortese gives the white delicate fruit and floral notes." }, { title: "Barolo", description: "Nebbiolo brings firmer tannin and a longer, savoury finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Gavi; pour Barolo into a broad glass and give it time to open." }, { subheading: "Food", description: "Gavi suits tandoori fish; Barolo takes mushroom galouti." }],
    pairingIdeas: [{ title: "Piedmont pairings", items: ["tandoori fish", "mushroom galouti", "truffle pasta", "slow-cooked lamb"] }],
    whyChoose: "A Piedmont family winery that shows the region's white and red grapes side by side.",
    faqs: [{ question: "Where is Bosio wine made?", answer: "Bosio Family Estates is based in Santo Stefano Belbo, Piedmont." }, { question: "Which grape is used in Bosio Gavi?", answer: "Bosio Gavi is made from Cortese." }],
    finalVerdict: "Bosio Gavi and Barolo make a useful two-bottle introduction to Piedmont.",
    metaTitle: "Bosio Wine Guide | BevOry", metaDescription: "Explore Bosio Gavi and Barolo from Piedmont, serving ideas, pairings and city prices on BevOry.",
  },
  branca: {
    description: "Branca is the Milanese distilling family behind Brancamenta, a mint-led herbal liqueur. Peppermint gives the dark amaro its cold, brisk finish.",
    story: "Fratelli Branca built its name in Milan with bitter herbal spirits. Brancamenta followed as a mintier variation, using peppermint essential oil from Piedmont alongside herbs and spices.",
    tastingNotes: [{ title: "Peppermint", description: "A cool mint rush leads the first sip." }, { title: "Herbal base", description: "Bitter herbs and spice hold the sweetness in check." }],
    howToEnjoy: [{ subheading: "Ice", description: "Pour a small measure very cold or over ice." }, { subheading: "Food", description: "Try it after dark chocolate or espresso-soaked tiramisu." }],
    pairingIdeas: [{ title: "After dinner", items: ["dark chocolate", "tiramisu", "roasted hazelnuts", "chocolate sandesh"] }],
    whyChoose: "A mint-and-herb Italian amaro with a notably cool finish.",
    faqs: [{ question: "What is Brancamenta?", answer: "It is a mint-flavoured herbal liqueur made by Fratelli Branca Distillerie." }, { question: "How is Brancamenta served?", answer: "Serve it very cold or over ice in a small glass." }],
    finalVerdict: "Brancamenta makes the most sense as a cold, bitter-mint finish to dinner.",
    metaTitle: "Branca Liqueur Guide | BevOry", metaDescription: "Explore Brancamenta's mint and herb flavour, chilled serves, dessert pairings and city prices on BevOry.",
  },
  belenkaya: {
    description: "Belenkaya is a Russian vodka brand in the Novabev portfolio. Its Gold bottling is one of the range's grain-spirit expressions.",
    story: "Novabev positions Belenkaya around a soft texture, clean water and a small addition of natural honey. The name translates roughly as a familiar form of 'white' in Russian.",
    tastingNotes: [{ title: "Clean grain", description: "The vodka opens with a restrained cereal note." }, { title: "Soft finish", description: "A slight honeyed roundness tempers the finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve very cold in a small glass or use in a vodka soda." }, { subheading: "Food", description: "Pair with salted cucumber, smoked fish or paneer tikka." }],
    pairingIdeas: [{ title: "Salty plates", items: ["salted cucumber", "smoked fish", "paneer tikka", "pickled mushrooms"] }],
    whyChoose: "A Russian vodka with a deliberately soft, restrained profile.",
    faqs: [{ question: "Where is Belenkaya from?", answer: "Belenkaya is a Russian vodka brand in the Novabev portfolio." }, { question: "Does Belenkaya contain honey?", answer: "Novabev describes a small addition of natural honey in the Belenkaya recipe." }],
    finalVerdict: "Belenkaya suits a chilled, simple serve with sharply flavoured snacks.",
    metaTitle: "Belenkaya Vodka Guide | BevOry", metaDescription: "Read about Belenkaya Russian vodka, cold serves, food pairings and city prices on BevOry.",
  },
  "blue-eyes": {
    description: "Blue Eyes is an Indian vodka range that includes Pure Grain and Green Apple bottlings. The Pure Grain vodka has been entered in international spirits judging by Rock and Storm Distilleries.",
    story: "Blue Eyes reached the Indian market with a plain grain vodka and a flavoured Green Apple option. The bottles were designed for chilled pours and mixed drinks rather than long cask maturation.",
    tastingNotes: [{ title: "Pure Grain", description: "A clean grain-spirit profile stays relatively neutral in a mixer." }, { title: "Green Apple", description: "Apple flavour gives the second expression a sharper fruit edge." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use Pure Grain in a vodka soda or Green Apple with soda and lime." }, { subheading: "Food", description: "Try it with chilli paneer or potato wedges." }],
    pairingIdeas: [{ title: "Cold drink snacks", items: ["chilli paneer", "potato wedges", "tandoori mushrooms", "salted peanuts"] }],
    whyChoose: "An Indian vodka range with a choice between plain grain and apple-flavoured styles.",
    faqs: [{ question: "What are the Blue Eyes vodka styles?", answer: "The range includes Pure Grain and Green Apple bottlings." }, { question: "Is Blue Eyes an Indian vodka?", answer: "Yes. Blue Eyes Pure Grain Vodka is listed as an Indian spirit." }],
    finalVerdict: "Pure Grain is the flexible mixer; Green Apple is the more fruit-led pour.",
    metaTitle: "Blue Eyes Vodka Guide | BevOry", metaDescription: "Compare Blue Eyes Pure Grain and Green Apple vodka, mixer ideas, pairings and city prices on BevOry.",
  },
  brancaia: {
    description: "Brancaia is a Tuscan winery with vineyards in Castellina and Radda in Chianti. Its red wines include Chianti Classico and the Sangiovese-led Tre.",
    story: "The Widmer family acquired Brancaia in 1981 and added a Radda property in 1989. Winemaker Barbara Widmer has since shaped the family's wines across its Chianti vineyards.",
    tastingNotes: [{ title: "Chianti Classico", description: "Cherry fruit and lively acidity reflect its Sangiovese base." }, { title: "Tre", description: "Dark berry and softer tannin give the blend a rounder feel." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour slightly cool into a medium red-wine glass." }, { subheading: "Food", description: "Try Chianti Classico with mushroom pizza and Tre with lamb kebabs." }],
    pairingIdeas: [{ title: "Tuscan dinner", items: ["mushroom pizza", "lamb kebabs", "tomato pasta", "aged pecorino"] }],
    whyChoose: "A family winery for comparing Chianti's Sangiovese edge with a softer Tuscan blend.",
    faqs: [{ question: "Where is Brancaia based?", answer: "Brancaia has vineyards in Castellina and Radda in Chianti, Tuscany." }, { question: "Who owns Brancaia?", answer: "The Widmer family owns the winery." }],
    finalVerdict: "Brancaia's reds welcome tomato, mushrooms and a substantial main course.",
    metaTitle: "Brancaia Wine Guide | BevOry", metaDescription: "Explore Brancaia Tuscan reds, Chianti vineyards, food pairings and city prices on BevOry.",
  },
  "botanist-the": {
    description: "The Botanist is an Islay dry gin made at Bruichladdich Distillery in Scotland. Twenty-two hand-foraged island botanicals join the gin's familiar juniper base.",
    story: "Bruichladdich's distillers use Islay plants to give the gin a specific island identity. The range later added a cask-aged bottling that draws on the distillery's whisky-making experience.",
    tastingNotes: [{ title: "Islay Dry", description: "Juniper, citrus and wild herbs give the gin a layered but fresh nose." }, { title: "Cask Aged", description: "Oak brings spice and darker fruit to the botanical base." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Use a large ice cube, dry tonic and a light citrus garnish." }, { subheading: "Food", description: "Try it beside herb-marinated prawns or lemony paneer tikka." }],
    pairingIdeas: [{ title: "Herb and citrus", items: ["herb-marinated prawns", "lemony paneer tikka", "grilled asparagus", "olives"] }],
    whyChoose: "An Islay gin whose local botanicals are more than a label detail.",
    faqs: [{ question: "Where is The Botanist gin made?", answer: "It is made at Bruichladdich Distillery on Islay, Scotland." }, { question: "How many Islay botanicals are used?", answer: "The Botanist uses 22 hand-foraged Islay botanicals." }],
    finalVerdict: "The Botanist rewards a restrained tonic that leaves its herbs room to speak.",
    metaTitle: "The Botanist Gin Guide | BevOry", metaDescription: "Discover The Botanist's Islay botanicals, gin serves, Indian food pairings and city prices on BevOry.",
  },
  "baron-phillipe": {
    description: "Baron Philippe de Rothschild is a French wine company whose range extends beyond its Bordeaux estates. Its Pays d'Oc varietal wines include Merlot and other familiar red and white grapes.",
    story: "Baron Philippe de Rothschild worked to make French wine available beyond a small circle of collectors. The company later expanded from Bordeaux to varietal wines in southern France, with separate labels for different regions.",
    tastingNotes: [{ title: "Pays d'Oc Merlot", description: "Red berries and supple tannin give the red an easy dinner fit." }, { title: "Pays d'Oc white", description: "The white-wine grapes bring brighter citrus and fruit notes." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Pour Merlot slightly cool; chill the white before serving." }, { subheading: "Food", description: "Merlot suits keema pav; a white works with tandoori fish." }],
    pairingIdeas: [{ title: "French varietals", items: ["keema pav", "tandoori fish", "roast vegetables", "grilled lamb"] }],
    whyChoose: "A French wine name that links Bordeaux history with accessible southern varietals.",
    faqs: [{ question: "Does Baron Philippe de Rothschild make wine outside Bordeaux?", answer: "Yes. The company makes Pays d'Oc varietal wines in southern France." }, { question: "Is Merlot part of its Pays d'Oc range?", answer: "Yes. Merlot is one of the company's Pays d'Oc varietal wines." }],
    finalVerdict: "Its Pays d'Oc Merlot is a sensible red for a savoury, spice-led meal.",
    metaTitle: "Baron Philippe de Rothschild Wine | BevOry", metaDescription: "Explore Baron Philippe de Rothschild Pays d'Oc wines, Merlot pairings and city prices on BevOry.",
  },
};
