import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_41 = [
  ["bornem-dubbel", "Bornem Dubbel", "Belgium", "Beer", "53f84caac982d6fbb08de88e"],
  ["burnetts", "Burnett's", "United Kingdom", "Gin", "353966c82ab321a028291420"],
  ["contessa", "Contessa", "India", "Rum", "a8c66e30c0c3aec28634b755"],
  ["cutty-stark", "Cutty Sark", "Scotland", "Whisky", "eb4d9bc16f494c272c727dca"],
  ["doaab", "DOAAB", "India", "Whisky", "01ef4e65bd76885e3146c2ce"],
  ["jcb", "JCB by Jean-Charles Boisset", "France", "Wine", "35296af6701a647b8a591ed9"],
  ["katoukichibee-born", "Born by Katoukichibee", "Japan", "Sake", "7b648751cd0ba0885f0737c9"],
  ["kronenbourg-1664-biere-blanche-blanc", "1664 Blanc", "France", "Beer", "1703ee44cd2ae5f47f316a37"],
  ["lab-vinho", "LAB Vinho", "Portugal", "Wine", "a7f6b46de3da9600d273ff21"],
  ["little-james", "Little James", "France", "Wine", "af8de08631ff7c366d6f30ed"],
  ["maboroshi", "Maboroshi", "Japan", "Sake", "3af1d900278d3a37f62f1ae1"],
  ["macon-lugny", "Macon-Lugny Les Genievres", "France", "Wine", "ef6267c074de7c88d68a5cc0"],
  ["marchese-antinori", "Marchese Antinori", "Italy", "Wine", "94a80eece37854de4f8c04d9"],
  ["meijo", "Meijo Shuzo", "Japan", "Sake", "51d40f89251193a8ce95e077"],
  ["mitchers", "Michter's", "United States", "Whisky", "df826b5cab3d0e5954fd7d0a"],
  ["original-oettinger", "Original Oettinger", "Germany", "Beer", "565484016cb49d98297c49b4"],
  ["ornellaila", "Ornellaia", "Italy", "Wine", "01e0ebeccc8a118ef5aa4423"],
  ["perry-road-peru-by-stranger-and-sons", "Perry Road Peru", "India", "Cocktail", "523c9ad8d3c0c1ace8569468"],
  ["sloeber", "Sloeber", "Belgium", "Beer", "da668f5f43256d7454db0793"],
  ["tequila-rose-strawberry", "Tequila Rose Strawberry", "United States", "Liqueur", "e0ac580dc6db53a65e2d80d7"],
  ["tonino-lamborghini", "Tonino Lamborghini", "Italy", "Spirits", "695d16f4c23446b3746014fc"],
  ["torre-mora", "Torre Mora", "Italy", "Wine", "8aa124f267d1c3f8f067e10d"],
  ["torresell", "Torresella", "Italy", "Wine", "5358e44caa43a9584e52f8b3"],
  ["skinos", "Skinos", "Greece", "Liqueur", "d5734888dab4c558035fb008"],
  ["baron-de-lastac", "Baron de Lestac", "France", "Wine", "44eea8380671b3b9518e37d1"],
  ["fidalgo", "Fidalgo", "India", "Feni", "cbc1c9ff70b84f57c0cdd011"],
  ["dalmore-the", "The Dalmore Port Wood Reserve", "Scotland", "Whisky", "6a0f677b079b92f57f16ff01"],
  ["romitoro", "RomiToro", "Italy", "Wine", "630c8d4ffca7cacac4349c0e"],
  ["silly-saison", "Silly Saison", "Belgium", "Beer", "b9923899808636b201bd984f"],
  ["tiamo", "Tiamo", "Italy", "Wine", "efd4b82c22e97d1902af1ed6"],
] as const;

// Research provenance stays internal; none of these links are injected into public copy.
export const BRAND_SOURCES_BATCH_41: Record<string, string[]> = {
  "bornem-dubbel": ["https://www.vansteenberge.com/onze-bieren/bornem/"],
  burnetts: ["https://www.heavenhill.com/history.php"],
  contessa: ["https://radicokhaitan.com/products/contessa-xxx-rum/"],
  "cutty-stark": ["https://cutty-sark.com/iconic-brand-1923", "https://cutty-sark.com/how-our-whisky-made"],
  doaab: ["https://announcement.acesphere.com/Annoucement/20250520/d836fa5b-ed46-4d59-861b-efdb04b28222.pdf"],
  jcb: ["https://www.boissetcollection.com/brands/jcb-by-jean-charles-boisset/portfolio/n21"],
  "katoukichibee-born": ["https://www.sakenomy.jp/en/sake/TST0000043210/"],
  "kronenbourg-1664-biere-blanche-blanc": ["https://www.1664blanc.com/en-ca/product-range/1664-blanc/"],
  "lab-vinho": ["https://www.casasantoslima.com/en/casa-santos-lima/about-us/"],
  "little-james": ["https://saintcosme.com/upload/vin/fiche/en/little_james_saint_cosme_little_james_basket_press_2021_white.pdf"],
  maboroshi: ["https://www.maboroshi.co.jp/en/story/"],
  "macon-lugny": ["https://m.louislatour.com/fr/vins/63/macon-lugny-les-genievres/2024"],
  "marchese-antinori": ["https://www.antinori.it/it/vino/marchese-antinori/?gen_pdf=1&wineyear=2022"],
  meijo: ["https://www.gi-harima.jp/en/area/en-yumesaki/"],
  mitchers: ["https://michters.com/kentucky-straight-bourbon/"],
  "original-oettinger": ["https://oettinger1731.de/bier/export/"],
  ornellaila: ["https://www.ornellaia.com/en/wines/", "https://www.ornellaia.com/en/philosophy-and-terroir/"],
  "perry-road-peru-by-stranger-and-sons": ["https://brewsnspirits.in/indian-premium-gins-surging-ahead"],
  sloeber: ["https://www.roman.be/pages/brands/sloeber"],
  "tequila-rose-strawberry": ["https://tequilarose.com/", "https://tequilarose.com/faqs/"],
  "tonino-lamborghini": ["https://lamborghini.it/it/pages/details-luxury-beverage_spirits"],
  "torre-mora": ["https://www.piccini1882.it/categoria-prodotto/catalogo/torre-mora/?layout=list"],
  torresell: ["https://www.torresella.com/en/wines/"],
  skinos: ["https://www.myskinos.com/the-collection/"],
  "baron-de-lastac": ["https://www.barondelestac.com/en"],
  fidalgo: ["https://rheadistilleries.in/home/products/"],
  "dalmore-the": ["https://www.thedalmore.com/en/our-collections/the-principal-collection/port-wood-reserve/"],
  romitoro: ["https://www.castelloromitorio.com/wines/romitorio-toscana-igt-en"],
  "silly-saison": ["https://silly-beer.com/en/silly-saison-2/"],
  tiamo: ["https://www.winesellersltd.com/brand/tiamo/"],
};

export const BRAND_LOGOS_BATCH_41: Record<string, string> = {};

export const BRAND_CONTENT_BATCH_41: Record<string, BrandPublicContent> = {
  "bornem-dubbel": {
    description: "Bornem Dubbel is a dark Belgian abbey beer brewed by Van Steenberge in Evergem. It has a malt-led profile and develops further through a second fermentation in the bottle or keg.",
    story: "Bornem takes its name and abbey connection from Sint-Bernardus Abbey in the town of Bornem. Van Steenberge has brewed the beer since 1971; the range received the Recognised Belgian Abbey Beer label in 1999.",
    tastingNotes: [{ title: "Dark malt", description: "Caramel, chocolate and a soft sweetness sit at the centre." }, { title: "Aftertaste", description: "Dried fruit, nuts and liquorice give way to a lightly hoppy finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour slowly into a stemmed beer glass, leaving the last splash of yeast in the bottle if you prefer a clearer pour." }, { subheading: "Table", description: "Try it with peppery mutton seekh or mushroom galouti kebabs." }],
    pairingIdeas: [{ title: "With Bornem Dubbel", items: ["mutton seekh", "mushroom galouti kebabs", "grilled sausages", "dark chocolate"] }],
    whyChoose: "A dark abbey beer with fruit and chocolate depth, without losing its brisk finish.",
    faqs: [{ question: "Who brews Bornem Dubbel?", answer: "Brouwerij Van Steenberge brews it in Evergem, Belgium." }, { question: "Is Bornem Dubbel bottle-conditioned?", answer: "Yes. Van Steenberge says Bornem continues a second fermentation in the bottle or keg." }],
    finalVerdict: "Pick Bornem Dubbel when you want dark malt and dried fruit with dinner.",
    metaTitle: "Bornem Dubbel Beer Guide | BevOry", metaDescription: "Explore Bornem Dubbel's dark malt and fruit notes, food pairings and city prices on BevOry.",
  },
  burnetts: {
    description: "Burnett's is a gin and vodka name owned by Kentucky distiller Heaven Hill. Burnett's London Dry Gin is the expression here, a juniper-led spirit made for classic mixed drinks.",
    story: "Heaven Hill acquired the Burnett's gin name in 1989 and introduced Burnett's vodka two years later. The gin retains the London Dry designation while the wider name now covers other spirits.",
    tastingNotes: [{ title: "Juniper", description: "A dry, pine-like juniper note leads the gin." }, { title: "In a mixer", description: "Citrus garnish brings out the gin's brisk herbal side." }],
    howToEnjoy: [{ subheading: "Highball", description: "Add chilled tonic and a lemon wedge to a tall glass of ice." }, { subheading: "Food", description: "The dry serve works with tandoori prawns or crisp masala peanuts." }],
    pairingIdeas: [{ title: "With a gin and tonic", items: ["tandoori prawns", "masala peanuts", "fish fingers", "lemon olives"] }],
    whyChoose: "An unfussy London Dry option for the familiar gin-and-tonic serve.",
    faqs: [{ question: "Is Burnett's gin the same as Burnett's vodka?", answer: "No. Heaven Hill sells both under the Burnett's name; this guide concerns its London Dry Gin." }, { question: "How can I serve Burnett's gin?", answer: "Tonic, ice and lemon make a straightforward long drink." }],
    finalVerdict: "Burnett's gin belongs in a chilled tonic rather than a complicated cocktail.",
    metaTitle: "Burnett's Gin Guide | BevOry", metaDescription: "Discover Burnett's London Dry Gin, simple serves, food pairings and city prices on BevOry.",
  },
  contessa: {
    description: "Contessa XXX is an Indian rum from Radico Khaitan, the company behind Rampur Distillery. The brand has a long association with India's defence retail segment.",
    story: "Radico Khaitan began operating as Rampur Distillery in 1943. Its Contessa rum became one of the company's major domestic names, particularly through defence channels.",
    tastingNotes: [{ title: "In the glass", description: "Contessa XXX pours as a dark rum." }, { title: "With cola", description: "A squeeze of lime keeps a simple long drink fresh." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve over ice with cola and lime, or take a small neat measure." }, { subheading: "Food", description: "Bring it to the table with tandoori chicken or chilli paneer." }],
    pairingIdeas: [{ title: "Snack plate", items: ["tandoori chicken", "chilli paneer", "roasted peanuts", "spiced potato wedges"] }],
    whyChoose: "A familiar Indian rum with a strong defence-canteen history.",
    faqs: [{ question: "Who makes Contessa XXX Rum?", answer: "Radico Khaitan makes Contessa XXX Rum." }, { question: "Is Contessa a whisky?", answer: "No. Contessa XXX is a rum in Radico Khaitan's portfolio." }],
    finalVerdict: "Contessa XXX is a straightforward dark-rum pour for ice or a lime-topped mixer.",
    metaTitle: "Contessa Rum Guide | BevOry", metaDescription: "Explore Contessa XXX Rum, its Indian heritage, serving ideas and city prices on BevOry.",
  },
  "cutty-stark": {
    description: "Cutty Sark is a blended Scotch whisky launched in 1923 by Berry Bros. & Rudd. The pale, light-bodied style was built to work both neat and in long drinks.",
    story: "The name comes from the nineteenth-century tea clipper Cutty Sark. James McBey drew the ship for the label, while its yellow background became one of the bottle's most recognisable features.",
    tastingNotes: [{ title: "Opening", description: "Soft orchard fruit and vanilla sit over cereal sweetness." }, { title: "Finish", description: "The blend stays light, with a little spice at the end." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice, top with soda and add a strip of lemon peel." }, { subheading: "Food", description: "Try a highball with chicken malai tikka or salted almonds." }],
    pairingIdeas: [{ title: "Alongside a highball", items: ["chicken malai tikka", "salted almonds", "fish cutlets", "roast chicken"] }],
    whyChoose: "A light blended Scotch whose ship-label history is as distinctive as its yellow bottle.",
    faqs: [{ question: "Why is Cutty Sark named after a ship?", answer: "It takes its name from the Cutty Sark tea clipper; a drawing of the ship appears on the label." }, { question: "Is Cutty Sark a single malt?", answer: "No. Cutty Sark is a blended Scotch whisky." }],
    finalVerdict: "Cutty Sark is at its best as a clean, easy Scotch highball.",
    metaTitle: "Cutty Sark Whisky Guide | BevOry", metaDescription: "Explore Cutty Sark blended Scotch, highball serves, pairings and city prices on BevOry.",
  },
  doaab: {
    description: "DOAAB is an Indian single malt whisky from Globus Spirits. It uses six-row Indian barley and matures entirely in ex-bourbon barrels.",
    story: "Globus Spirits brought DOAAB into its premium portfolio as an Indian craft whisky. The company also makes Terai gin, but DOAAB uses malted barley rather than gin botanicals.",
    tastingNotes: [{ title: "Nose", description: "Tropical fruit, dates, honey and vanilla sit alongside charred oak." }, { title: "Palate", description: "Nutty barley, cinnamon and toasted almond meet spiced caramel." }],
    howToEnjoy: [{ subheading: "First pour", description: "Taste a small measure in a tulip glass before adding water." }, { subheading: "With food", description: "Set it beside grilled paneer or peppery mutton seekh." }],
    pairingIdeas: [{ title: "At dinner", items: ["grilled paneer", "mutton seekh", "roast mushrooms", "salted cashews"] }],
    whyChoose: "A six-row-barley Indian single malt with a clear ex-bourbon cask identity.",
    faqs: [{ question: "Is DOAAB an Indian single malt?", answer: "Yes. Globus Spirits presents DOAAB as an Indian single malt whisky." }, { question: "What grain is used for DOAAB?", answer: "Globus Spirits identifies six-row Indian barley in its production." }],
    finalVerdict: "DOAAB offers a direct look at Indian barley whisky matured in ex-bourbon wood.",
    metaTitle: "DOAAB Indian Whisky Guide | BevOry", metaDescription: "Explore DOAAB Indian single malt, ex-bourbon maturation, serving ideas and city prices on BevOry.",
  },
  jcb: {
    description: "JCB is Jean-Charles Boisset's wine range, with numbered cuvees that include French sparkling wine. JCB N°21 is a Cremant de Bourgogne made by the traditional method.",
    story: "Jean-Charles Boisset draws on his Burgundy family background for the JCB range. Numbered releases let him work across styles and regions; the number on each bottle matters more than a single house-wide flavour description.",
    tastingNotes: [{ title: "N°21 aroma", description: "White flowers and almond appear in the N°21 sparkling wine." }, { title: "N°21 palate", description: "The finish is crisp, with fine bubbles." }],
    howToEnjoy: [{ subheading: "Sparkling pour", description: "Serve N°21 chilled in a tulip-shaped sparkling-wine glass." }, { subheading: "Food", description: "Its bright finish suits tandoori fish or a plate of pakoras." }],
    pairingIdeas: [{ title: "With N°21", items: ["tandoori fish", "vegetable pakoras", "goat cheese", "salted almonds"] }],
    whyChoose: "A Burgundy-rooted sparkling wine with a crisp, almond-edged profile.",
    faqs: [{ question: "Who is behind JCB wine?", answer: "Jean-Charles Boisset created the numbered JCB wine range." }, { question: "What is JCB N°21?", answer: "It is a Cremant de Bourgogne sparkling wine made by the traditional method." }],
    finalVerdict: "JCB N°21 makes a sharp, food-friendly start to a meal.",
    metaTitle: "JCB Wine Guide | BevOry", metaDescription: "Explore JCB N°21 Cremant de Bourgogne, serving ideas, food pairings and city prices on BevOry.",
  },
  "katoukichibee-born": {
    description: "Born is a Japanese sake label from Katoukichibee Shouten in Fukui Prefecture. Its Gold expression is a junmai daiginjo brewed from Yamada Nishiki rice.",
    story: "The Katoukichibee family brewery works in Sabae, Fukui, under the Born name. Its premium sake puts polished rice and careful fermentation ahead of added flavouring.",
    tastingNotes: [{ title: "Aroma", description: "Born Gold has a gentle, fruit-led sake aroma." }, { title: "Texture", description: "The polished-rice style gives a smooth, clean palate." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Serve lightly chilled in a small wine glass to catch the aroma." }, { subheading: "Food", description: "Pair with tandoori fish or sesame-coated prawns." }],
    pairingIdeas: [{ title: "With sake", items: ["tandoori fish", "sesame prawns", "sushi", "steamed mushroom dumplings"] }],
    whyChoose: "A Fukui junmai daiginjo that puts Yamada Nishiki rice in focus.",
    faqs: [{ question: "Where is Born sake made?", answer: "Katoukichibee Shouten brews Born in Fukui Prefecture, Japan." }, { question: "What kind of sake is Born Gold?", answer: "Born Gold is a junmai daiginjo made with Yamada Nishiki rice." }],
    finalVerdict: "Born Gold is a measured, aromatic sake for lighter dishes.",
    metaTitle: "Born Sake Guide | BevOry", metaDescription: "Discover Born sake from Fukui, its rice-led style, food pairings and city prices on BevOry.",
  },
  "kronenbourg-1664-biere-blanche-blanc": {
    description: "1664 Blanc is a French-style wheat beer in the 1664 range. Citrus peel and coriander give it a different profile from the brand's lager.",
    story: "The 1664 name refers to the founding year of the Hatt brewery in Strasbourg. Blanc later joined the range as a wheat beer with a distinctly citrus-led recipe.",
    tastingNotes: [{ title: "Citrus", description: "Orange and lemon notes lead the aroma." }, { title: "Spice", description: "Coriander and soft wheat round out the finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve chilled in a tall wheat-beer glass." }, { subheading: "Food", description: "Try it with lemony fish fry or chilli paneer." }],
    pairingIdeas: [{ title: "With 1664 Blanc", items: ["fish fry", "chilli paneer", "prawn tempura", "citrus salad"] }],
    whyChoose: "A citrus-and-coriander wheat beer for a lighter beer table.",
    faqs: [{ question: "Is 1664 Blanc a lager?", answer: "No. Blanc is the wheat beer in the 1664 range." }, { question: "What gives 1664 Blanc its citrus character?", answer: "The beer's recipe includes citrus peel alongside coriander." }],
    finalVerdict: "1664 Blanc works best cold, with sharp snacks and a tall glass.",
    metaTitle: "1664 Blanc Beer Guide | BevOry", metaDescription: "Explore 1664 Blanc wheat beer, citrus notes, pairings and city prices on BevOry.",
  },
  "lab-vinho": {
    description: "LAB Vinho is a Portuguese wine range from Casa Santos Lima, a family wine producer based near Lisbon. The range includes red, white and rose bottles.",
    story: "Casa Santos Lima works with vineyards across several Portuguese regions and built LAB as an accessible line in that wider portfolio. The range's colour and grape mix change the drinking experience from bottle to bottle.",
    tastingNotes: [{ title: "Red LAB", description: "The red is fruit-forward, with dark berry notes." }, { title: "White LAB", description: "The white keeps a fresher citrus and orchard-fruit character." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill the white; pour the red slightly cool in a medium wine glass." }, { subheading: "Food", description: "Try the red with lamb seekh and the white with tandoori fish." }],
    pairingIdeas: [{ title: "Across the range", items: ["lamb seekh", "tandoori fish", "mushroom pulao", "grilled sardines"] }],
    whyChoose: "A useful entry into Casa Santos Lima's Portuguese wines across more than one colour.",
    faqs: [{ question: "Who makes LAB wine?", answer: "Portuguese producer Casa Santos Lima makes LAB." }, { question: "Does LAB only make red wine?", answer: "No. The LAB range includes red, white and rose wine." }],
    finalVerdict: "Choose LAB by the dish: red for the grill, white for fish.",
    metaTitle: "LAB Vinho Wine Guide | BevOry", metaDescription: "Explore LAB Vinho's Portuguese reds and whites, serving ideas and city prices on BevOry.",
  },
  "little-james": {
    description: "Little James is a wine range from Chateau de Saint Cosme in France's Rhone Valley. The Basket Press line includes both red and white wines.",
    story: "Saint Cosme is closely tied to Gigondas, where the Barruol family has made wine over several generations. Little James sits alongside the estate's more site-specific wines as a separate, everyday range.",
    tastingNotes: [{ title: "White", description: "The white aims for fresh fruit and an easy, lively finish." }, { title: "Red", description: "The red is the fuller, darker-fruited side of the range." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the white; give the red a slight cool-down before pouring." }, { subheading: "Pair", description: "The white suits paneer tikka; put the red with grilled lamb." }],
    pairingIdeas: [{ title: "At the table", items: ["paneer tikka", "grilled lamb", "olive tapenade", "roast aubergine"] }],
    whyChoose: "An approachable Rhone range from a family estate better known for Gigondas.",
    faqs: [{ question: "Who makes Little James wine?", answer: "Chateau de Saint Cosme makes the Little James range." }, { question: "Is Little James only a red wine?", answer: "No. Basket Press is made in red and white expressions." }],
    finalVerdict: "Little James brings Saint Cosme's Rhone background to an everyday dinner pour.",
    metaTitle: "Little James Wine Guide | BevOry", metaDescription: "Explore Little James wines from Saint Cosme, food pairings and city prices on BevOry.",
  },
  maboroshi: {
    description: "Maboroshi is a sake label from Nakao Sake Brewery in Takehara, Hiroshima. The brewery is known for using a proprietary apple-derived yeast in some of its sake.",
    story: "Nakao began brewing in 1871. Its work on apple yeast dates to the twentieth century and became a distinctive part of the brewery's aromatic sake style.",
    tastingNotes: [{ title: "Fruit", description: "The apple-yeast expressions have a pronounced fruit-led aroma." }, { title: "Palate", description: "A clean finish keeps the sake from feeling heavy." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve chilled in a small white-wine glass." }, { subheading: "With food", description: "Try it with tandoori prawns or a cucumber-and-sesame salad." }],
    pairingIdeas: [{ title: "With Maboroshi", items: ["tandoori prawns", "sesame cucumber", "sashimi", "steamed fish"] }],
    whyChoose: "A Hiroshima sake name with a documented apple-yeast brewing story.",
    faqs: [{ question: "Where is Maboroshi brewed?", answer: "Nakao Sake Brewery makes Maboroshi in Takehara, Hiroshima." }, { question: "What is Nakao Brewery known for?", answer: "It developed an apple-derived yeast used in some of its aromatic sake." }],
    finalVerdict: "Maboroshi is worth trying for its fruit-led Hiroshima sake character.",
    metaTitle: "Maboroshi Sake Guide | BevOry", metaDescription: "Explore Maboroshi sake from Hiroshima, serving ideas, pairings and city prices on BevOry.",
  },
  "macon-lugny": {
    description: "Macon-Lugny Les Genievres is a Chardonnay from Maison Louis Latour in southern Burgundy. The named Les Genievres site is in Lugny, within the Maconnais.",
    story: "Maison Louis Latour brings its Burgundy winemaking experience to the Maconnais for this village white. The Les Genievres name points to a particular vineyard source, not to a separate wine company.",
    tastingNotes: [{ title: "Fruit", description: "Apple and citrus give this Chardonnay its fresh opening." }, { title: "Finish", description: "A gentle mineral note and rounded texture close the palate." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill lightly and pour in a white-wine glass rather than straight from the fridge." }, { subheading: "Food", description: "Try it with tandoori fish or a mild paneer malai tikka." }],
    pairingIdeas: [{ title: "With white Burgundy", items: ["tandoori fish", "paneer malai tikka", "roast chicken", "grilled mushrooms"] }],
    whyChoose: "A named-site Maconnais Chardonnay from a longstanding Burgundy house.",
    faqs: [{ question: "Who makes Macon-Lugny Les Genievres?", answer: "Maison Louis Latour makes this wine." }, { question: "Which grape is used?", answer: "Les Genievres is made from Chardonnay." }],
    finalVerdict: "Les Genievres brings a clear Maconnais Chardonnay style to the table.",
    metaTitle: "Macon-Lugny Wine Guide | BevOry", metaDescription: "Explore Louis Latour Macon-Lugny Chardonnay, pairings and city prices on BevOry.",
  },
  "marchese-antinori": {
    description: "Marchese Antinori Chianti Classico Riserva is a Tuscan red from the Antinori family. Sangiovese is the core grape in this Chianti Classico wine.",
    story: "The Antinori family's wine history in Florence reaches back to 1385. Marchese Antinori Riserva carries that family name into the Chianti Classico denomination rather than representing a separate producer.",
    tastingNotes: [{ title: "Red fruit", description: "Cherry and red berry aromas lead the wine." }, { title: "Structure", description: "Tannins and oak spice give the Riserva a firmer finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a large red-wine glass and give it a short time to open." }, { subheading: "Food", description: "Put it beside mutton rogan josh or a tomato-rich pasta." }],
    pairingIdeas: [{ title: "With Chianti Classico", items: ["mutton rogan josh", "tomato pasta", "grilled lamb chops", "mushroom lasagne"] }],
    whyChoose: "An Antinori Sangiovese with Chianti Classico's bright fruit and firm structure.",
    faqs: [{ question: "Is Marchese Antinori a Chianti Classico?", answer: "The Marchese Antinori Riserva is a Chianti Classico red wine." }, { question: "What grape defines the wine?", answer: "Sangiovese forms the core of the blend." }],
    finalVerdict: "Marchese Antinori Riserva has the acidity and grip for a rich dinner.",
    metaTitle: "Marchese Antinori Wine Guide | BevOry", metaDescription: "Explore Marchese Antinori Chianti Classico Riserva, pairings and city prices on BevOry.",
  },
  meijo: {
    description: "Meijo Shuzo is a sake brewery in Himeji, Hyogo Prefecture. Its location puts it within Harima, a region known for Yamada Nishiki sake rice.",
    story: "Meijo Shuzo grew from a group of local breweries around the historic Imai Shuzo, founded in the nineteenth century. The brewery's Himeji identity is distinct from similarly named sake makers elsewhere in Japan.",
    tastingNotes: [{ title: "Rice", description: "A gentle rice sweetness forms the centre of the sake." }, { title: "Finish", description: "The palate ends clean, suited to food rather than a sweet dessert serve." }],
    howToEnjoy: [{ subheading: "Serve", description: "Start lightly chilled in a small glass and let it warm a little as you drink." }, { subheading: "Food", description: "Try it with salt-grilled fish or paneer tikka." }],
    pairingIdeas: [{ title: "With Meijo sake", items: ["salt-grilled fish", "paneer tikka", "chicken yakitori", "steamed dumplings"] }],
    whyChoose: "A Harima-region sake with a clear Himeji brewery identity.",
    faqs: [{ question: "Where is Meijo Shuzo based?", answer: "Meijo Shuzo is based in Himeji, Hyogo Prefecture." }, { question: "Is Meijo Shuzo the same as Yamanashi Meijo?", answer: "No. They are different sake breweries in different prefectures." }],
    finalVerdict: "Meijo makes sense beside grilled or lightly spiced food.",
    metaTitle: "Meijo Sake Guide | BevOry", metaDescription: "Explore Meijo sake from Himeji, serving ideas, pairings and city prices on BevOry.",
  },
  mitchers: {
    description: "Michter's is an American whiskey maker based in Louisville, Kentucky. Its US*1 range includes Kentucky Straight Bourbon, rye, sour mash and American whiskey.",
    story: "Michter's uses the US*1 name as a reference to its Pennsylvania whiskey heritage. Today's bourbon is distilled and bottled in Kentucky, with small batches held to a maximum of twenty full barrels.",
    tastingNotes: [{ title: "Bourbon nose", description: "Caramel and vanilla sit over stone-fruit notes in US*1 Bourbon." }, { title: "Finish", description: "A little smoke and new-oak character carry the finish." }],
    howToEnjoy: [{ subheading: "Taste", description: "Try US*1 Bourbon neat first, then add a few drops of water." }, { subheading: "Food", description: "Bring it to the table with smoky lamb seekh or pecan pie." }],
    pairingIdeas: [{ title: "With US*1 Bourbon", items: ["lamb seekh", "pecan pie", "smoked paneer", "dark chocolate"] }],
    whyChoose: "A Kentucky small-batch bourbon with a documented twenty-barrel ceiling.",
    faqs: [{ question: "Where is Michter's US*1 Bourbon made?", answer: "It is distilled and bottled in Kentucky." }, { question: "Does Michter's only make bourbon?", answer: "No. The US*1 range also includes rye, sour mash and American whiskey." }],
    finalVerdict: "US*1 Bourbon balances caramel and oak without demanding a mixer.",
    metaTitle: "Michter's Whisky Guide | BevOry", metaDescription: "Explore Michter's US*1 Bourbon, tasting notes, pairings and city prices on BevOry.",
  },
  "original-oettinger": {
    description: "Original Oettinger is a German beer range from Oettinger Brauerei. Its Export is a pale, malt-led beer brewed in the German lager tradition.",
    story: "The Oettinger brewery takes its name from Oettingen in Bavaria. Its contemporary range extends beyond Export to other German beer styles.",
    tastingNotes: [{ title: "Malt", description: "Export has a full, lightly sweet malt opening." }, { title: "Finish", description: "A restrained hop bitterness closes the beer." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour chilled into a clean lager glass." }, { subheading: "Snack", description: "Try it with chicken schnitzel or chilli potato." }],
    pairingIdeas: [{ title: "With Export", items: ["chicken schnitzel", "chilli potato", "grilled sausages", "salted pretzels"] }],
    whyChoose: "A malt-forward German Export beer with a gentle hop finish.",
    faqs: [{ question: "Where is Original Oettinger from?", answer: "Oettinger Brauerei is a German brewer named for Oettingen in Bavaria." }, { question: "What style is Oettinger Export?", answer: "Export is a pale, malt-led German lager style." }],
    finalVerdict: "Original Oettinger Export is a straightforward partner for salty, fried food.",
    metaTitle: "Original Oettinger Beer Guide | BevOry", metaDescription: "Explore Original Oettinger Export beer, food pairings and city prices on BevOry.",
  },
  ornellaila: {
    description: "Ornellaia is a Bolgheri wine estate on Tuscany's coast. Its flagship Bolgheri Superiore red draws on Cabernet Sauvignon, Merlot, Cabernet Franc and Petit Verdot.",
    story: "The estate was founded in 1981 as Bolgheri emerged as a centre for Bordeaux-variety wines. Coastal light, maritime air and varied vineyard soils shape Ornellaia's blends.",
    tastingNotes: [{ title: "Fruit", description: "Dark berries and plum sit at the centre of the flagship red." }, { title: "Structure", description: "Fine tannins and measured oak frame its long finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve in a large red-wine glass, slightly cool, after some time in a decanter." }, { subheading: "Food", description: "A rich red like this stands up to mutton rogan josh or grilled lamb chops." }],
    pairingIdeas: [{ title: "With the flagship red", items: ["mutton rogan josh", "grilled lamb chops", "mushroom galouti", "aged pecorino"] }],
    whyChoose: "A coastal Tuscan Bordeaux-variety blend with Bolgheri's distinctive identity.",
    faqs: [{ question: "Where is Ornellaia made?", answer: "Ornellaia is made at the estate in Bolgheri, Tuscany." }, { question: "Which grapes are in Ornellaia's flagship red?", answer: "The blend uses Cabernet Sauvignon, Merlot, Cabernet Franc and Petit Verdot." }],
    finalVerdict: "Ornellaia is a structured dinner wine built for patient drinking.",
    metaTitle: "Ornellaia Wine Guide | BevOry", metaDescription: "Explore Ornellaia from Bolgheri, its grapes, dinner pairings and city prices on BevOry.",
  },
  "perry-road-peru-by-stranger-and-sons": {
    description: "Perry Road Peru is a gin-based bottled cocktail associated with Stranger & Sons and The Bombay Canteen. Guava and chilli place it firmly in a Mumbai-inspired drinks tradition.",
    story: "The drink takes its name from a road in Mumbai's Bandra neighbourhood. Stranger & Sons worked with The Bombay Canteen on a ready-to-pour take on a guava-and-chilli cocktail rather than a plain gin expression.",
    tastingNotes: [{ title: "Guava", description: "Ripe guava gives the drink its fruit-led centre." }, { title: "Chilli", description: "A gentle chilli kick follows the fruit." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve well chilled over ice in a short glass." }, { subheading: "Snack", description: "Try it with corn chaat or chilli cheese toast." }],
    pairingIdeas: [{ title: "With guava and chilli", items: ["corn chaat", "chilli cheese toast", "masala peanuts", "tandoori prawns"] }],
    whyChoose: "A Mumbai cocktail idea in a bottle, with guava and chilli doing the work.",
    faqs: [{ question: "Is Perry Road Peru a straight gin?", answer: "No. It is a gin-based cocktail with guava and chilli." }, { question: "Why is it called Perry Road Peru?", answer: "The name refers to Perry Road in Bandra, Mumbai; peru is a local word for guava." }],
    finalVerdict: "Perry Road Peru is for anyone who likes fruit with a little heat.",
    metaTitle: "Perry Road Peru Cocktail Guide | BevOry", metaDescription: "Explore Perry Road Peru's guava-chilli profile, snack pairings and city prices on BevOry.",
  },
  sloeber: {
    description: "Sloeber is a strong blond Belgian ale from Brouwerij Roman in Oudenaarde. Its fruit-led aroma and mild bitterness distinguish it from a crisp pilsner.",
    story: "Brouwerij Roman introduced Sloeber in 1983. The Oudenaarde family brewery developed the ale as a distinct blond beer within a range better known in Belgium for several regional styles.",
    tastingNotes: [{ title: "Aroma", description: "Soft fruit and yeast notes lead the nose." }, { title: "Finish", description: "A touch of sweetness gives way to a gentle bitter edge." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cool in a stemmed Belgian ale glass." }, { subheading: "Food", description: "The fruit and bitterness work with chicken tikka or fried calamari." }],
    pairingIdeas: [{ title: "With Sloeber", items: ["chicken tikka", "fried calamari", "spiced potato wedges", "aged cheddar"] }],
    whyChoose: "A fruit-led Belgian blond from a longstanding Oudenaarde brewery.",
    faqs: [{ question: "Who makes Sloeber beer?", answer: "Brouwerij Roman in Oudenaarde makes Sloeber." }, { question: "Is Sloeber a pilsner?", answer: "No. It is a Belgian blond ale." }],
    finalVerdict: "Sloeber brings Belgian yeast character to the snack table.",
    metaTitle: "Sloeber Beer Guide | BevOry", metaDescription: "Explore Sloeber Belgian blond ale, serving ideas, food pairings and city prices on BevOry.",
  },
  "tequila-rose-strawberry": {
    description: "Tequila Rose Strawberry is a strawberry cream liqueur made with tequila. Despite its name, it is not a rose wine.",
    story: "Tequila Rose built its identity around strawberry-flavoured cream and a tequila base. The bright pink bottle made it a recognisable dessert and party pour, distinct from unflavoured tequila.",
    tastingNotes: [{ title: "Strawberry", description: "Sweet strawberry leads the aroma and flavour." }, { title: "Cream", description: "A thick, smooth cream texture follows the fruit." }],
    howToEnjoy: [{ subheading: "Cold", description: "Chill thoroughly and pour a small measure into a shot glass or over ice." }, { subheading: "Dessert", description: "Serve with chocolate brownie or vanilla kulfi." }],
    pairingIdeas: [{ title: "Dessert plate", items: ["chocolate brownie", "vanilla kulfi", "strawberry cheesecake", "dark chocolate"] }],
    whyChoose: "A strawberry-and-cream liqueur when dessert is the point of the pour.",
    faqs: [{ question: "Is Tequila Rose a wine?", answer: "No. Tequila Rose Strawberry is a cream liqueur made with tequila." }, { question: "Should Tequila Rose be served cold?", answer: "It is commonly served chilled or over ice." }],
    finalVerdict: "Tequila Rose is a small, cold dessert drink rather than a sipping tequila.",
    metaTitle: "Tequila Rose Liqueur Guide | BevOry", metaDescription: "Explore Tequila Rose Strawberry, dessert pairings, serving ideas and city prices on BevOry.",
  },
  "tonino-lamborghini": {
    description: "Tonino Lamborghini is an Italian lifestyle name with a spirits range that includes gin, vodka and whisky. The bottles carry the Tonino Lamborghini name, separate from the car maker's drink portfolio.",
    story: "Tonino Lamborghini expanded his family name into design, hospitality and beverages. The spirits line uses different production bases for its gin, vodka and whisky rather than a single shared recipe.",
    tastingNotes: [{ title: "Gin", description: "Juniper and citrus shape the gin's aromatic profile." }, { title: "Vodka", description: "The vodka is intended as a clean, neutral base for chilled serves." }],
    howToEnjoy: [{ subheading: "Choose a style", description: "Use the gin with tonic and citrus; serve the vodka cold in a martini or simple highball." }, { subheading: "Food", description: "The gin suits tandoori prawns; try the vodka with smoked salmon." }],
    pairingIdeas: [{ title: "Across the range", items: ["tandoori prawns", "smoked salmon", "salted almonds", "grilled paneer"] }],
    whyChoose: "An Italian design name whose spirits range spans several distinct styles.",
    faqs: [{ question: "Does Tonino Lamborghini make gin?", answer: "Yes. The beverage range includes gin, vodka and whisky." }, { question: "Are all Tonino Lamborghini spirits made the same way?", answer: "No. Gin, vodka and whisky use different ingredients and production methods." }],
    finalVerdict: "Choose the Tonino Lamborghini spirit for the drink you actually plan to make.",
    metaTitle: "Tonino Lamborghini Spirits Guide | BevOry", metaDescription: "Explore Tonino Lamborghini gin, vodka and whisky, food pairings and city prices on BevOry.",
  },
  "torre-mora": {
    description: "Torre Mora is a wine estate on Sicily's Mount Etna in the Piccini 1882 group. Its vineyards include Nerello Mascalese, a red grape closely associated with Etna.",
    story: "The estate farms volcanic slopes on the eastern side of Etna. Piccini's Torre Mora project focuses on this mountain's local grapes and the differences between its lava-soil sites.",
    tastingNotes: [{ title: "Nerello fruit", description: "Red cherry gives Etna reds a bright opening." }, { title: "Mountain edge", description: "A savoury, lightly mineral finish sits behind the fruit." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour a red slightly cool in a medium Burgundy-shaped glass." }, { subheading: "Food", description: "Try it with grilled lamb or mushroom galouti kebabs." }],
    pairingIdeas: [{ title: "With Etna red", items: ["grilled lamb", "mushroom galouti kebabs", "aubergine parmigiana", "roast chicken"] }],
    whyChoose: "Etna's volcanic site and Nerello Mascalese grape give Torre Mora a clear sense of place.",
    faqs: [{ question: "Where is Torre Mora?", answer: "Torre Mora is a wine estate on Mount Etna in Sicily." }, { question: "Which red grape is associated with Torre Mora?", answer: "Nerello Mascalese is a key grape in its Etna reds." }],
    finalVerdict: "Torre Mora is a good place to meet Etna's bright, savoury red-wine style.",
    metaTitle: "Torre Mora Wine Guide | BevOry", metaDescription: "Explore Torre Mora Etna wines, Nerello Mascalese, pairings and city prices on BevOry.",
  },
  torresell: {
    description: "Torresella is an Italian wine range from the Veneto. Its bottles include Pinot Grigio and Prosecco alongside red wines.",
    story: "The Torresella name belongs to northeast Italy's wine landscape. Its range covers still and sparkling wines, so the glass can change considerably between a Pinot Grigio and a Prosecco.",
    tastingNotes: [{ title: "Pinot Grigio", description: "Light orchard fruit and citrus give the white a crisp profile." }, { title: "Prosecco", description: "Apple-led fruit and lively bubbles make the sparkling wine a lighter pour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the white or Prosecco; use a white-wine glass for either." }, { subheading: "Food", description: "Pinot Grigio works with tandoori fish; Prosecco suits vegetable pakoras." }],
    pairingIdeas: [{ title: "Across the range", items: ["tandoori fish", "vegetable pakoras", "prawn salad", "fresh mozzarella"] }],
    whyChoose: "A Veneto range with both easy-drinking still white and sparkling wine.",
    faqs: [{ question: "Where is Torresella from?", answer: "Torresella is a wine range from Italy's Veneto region." }, { question: "Does Torresella make Prosecco?", answer: "Yes. Prosecco is among its sparkling wines." }],
    finalVerdict: "Torresella's white and sparkling bottles suit a lighter meal.",
    metaTitle: "Torresella Wine Guide | BevOry", metaDescription: "Explore Torresella Pinot Grigio and Prosecco, pairings and city prices on BevOry.",
  },
  skinos: {
    description: "Skinos is a Greek mastiha liqueur made with resin from mastic trees on the island of Chios. It brings an herbal profile quite unlike anise-led ouzo.",
    story: "Chios mastiha has a long history in Greek food and drink. Skinos put that resin at the centre of a modern bottled spirit and cocktail range.",
    tastingNotes: [{ title: "Resin", description: "Pine-like, herbal notes give Skinos its unmistakable aroma." }, { title: "Palate", description: "A gentle sweetness follows the fresh, mint-like edge." }],
    howToEnjoy: [{ subheading: "Cold serve", description: "Pour over ice with a squeeze of lemon, or use it in a sour." }, { subheading: "Food", description: "Try it with grilled prawns or salty feta." }],
    pairingIdeas: [{ title: "With mastiha", items: ["grilled prawns", "feta and olives", "paneer tikka", "pistachio dessert"] }],
    whyChoose: "A distinct Chios mastiha flavour that holds up in simple cocktails.",
    faqs: [{ question: "What is Skinos made from?", answer: "Skinos uses mastiha resin from mastic trees grown on Chios." }, { question: "Is Skinos the same as ouzo?", answer: "No. Skinos is based on mastiha; ouzo is primarily anise-flavoured." }],
    finalVerdict: "Skinos turns the aroma of Chios mastiha into a memorable cold serve.",
    metaTitle: "Skinos Mastiha Guide | BevOry", metaDescription: "Explore Skinos mastiha from Chios, cocktail serves, pairings and city prices on BevOry.",
  },
  "baron-de-lastac": {
    description: "Baron de Lestac is a Bordeaux wine range with red and white bottles. Its red wine draws on the region's familiar Merlot- and Cabernet-based blending tradition.",
    story: "Baron de Lestac began in Bordeaux in 1986. Its red keeps oak-barrel ageing as part of the house style, while the range has grown to include whites and rose.",
    tastingNotes: [{ title: "Red fruit", description: "Red berries give the Bordeaux red its opening." }, { title: "Oak", description: "Spice and a touch of toast follow the fruit." }],
    howToEnjoy: [{ subheading: "Red", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try the red with mutton seekh or a mushroom pie." }],
    pairingIdeas: [{ title: "With the Bordeaux red", items: ["mutton seekh", "mushroom pie", "grilled lamb", "aged cheddar"] }],
    whyChoose: "A Bordeaux red with accessible fruit and a recognisable oak note.",
    faqs: [{ question: "Is Baron de Lestac from Bordeaux?", answer: "Yes. The range includes Bordeaux red and white wines." }, { question: "Is Baron de Lestac only a red wine?", answer: "No. The range also includes white wine." }],
    finalVerdict: "Baron de Lestac red makes sense with a hearty dinner.",
    metaTitle: "Baron de Lestac Wine Guide | BevOry", metaDescription: "Explore Baron de Lestac Bordeaux wines, dinner pairings and city prices on BevOry.",
  },
  fidalgo: {
    description: "Fidalgo is a Goan cashew feni from Rhea Distilleries. Its base is fermented cashew apple juice, making it distinct from grain whisky or grape brandy.",
    story: "Cashew feni is a traditional spirit of Goa, where ripe cashew apples are crushed, fermented and distilled. Fidalgo presents that local practice in a contemporary bottled spirit.",
    tastingNotes: [{ title: "Fruit", description: "A pronounced cashew-apple aroma leads the glass." }, { title: "Finish", description: "The spirit's fruit character stays present after a small sip." }],
    howToEnjoy: [{ subheading: "Goan highball", description: "Try a modest pour with ice, soda and a squeeze of lime." }, { subheading: "Food", description: "Pair with Goan prawn balchao or recheado fish." }],
    pairingIdeas: [{ title: "Goan table", items: ["prawn balchao", "recheado fish", "chorizo pao", "salted cashews"] }],
    whyChoose: "A cashew-apple spirit rooted in Goa's own distilling tradition.",
    faqs: [{ question: "What is Fidalgo made from?", answer: "Fidalgo is a cashew feni made from fermented cashew apples." }, { question: "Where is Fidalgo from?", answer: "Fidalgo comes from Goa, India." }],
    finalVerdict: "Fidalgo tastes most at home beside sharp, spicy Goan food.",
    metaTitle: "Fidalgo Feni Guide | BevOry", metaDescription: "Explore Fidalgo Goan cashew feni, food pairings, serving ideas and city prices on BevOry.",
  },
  "dalmore-the": {
    description: "The Dalmore Port Wood Reserve is a Highland single malt Scotch whisky. Its cask programme combines American white oak ex-bourbon barrels with port pipes from Portugal.",
    story: "The Dalmore distillery stands by the Cromarty Firth in Alness. Port Wood Reserve takes the house's cask-led style toward Portuguese port wood rather than relying on a simple age statement.",
    tastingNotes: [{ title: "Fruit", description: "Plum and berry notes lead the whisky's richer side." }, { title: "Cask", description: "Vanilla and gentle spice follow from the oak." }],
    howToEnjoy: [{ subheading: "Glass", description: "Start neat in a tulip glass, then add a few drops of water." }, { subheading: "Food", description: "Try it with dark chocolate or mutton galouti kebabs." }],
    pairingIdeas: [{ title: "With Port Wood Reserve", items: ["dark chocolate", "mutton galouti kebabs", "roasted figs", "aged cheddar"] }],
    whyChoose: "A Highland malt that places port-cask fruit alongside Dalmore's oak-led style.",
    faqs: [{ question: "Where is Port Wood Reserve made?", answer: "The Dalmore makes it at its Highland distillery in Alness, Scotland." }, { question: "What casks shape Port Wood Reserve?", answer: "The Dalmore uses ex-bourbon American oak and Portuguese port pipes." }],
    finalVerdict: "Port Wood Reserve is a rich after-dinner Dalmore with a clear cask story.",
    metaTitle: "Dalmore Port Wood Whisky Guide | BevOry", metaDescription: "Explore Dalmore Port Wood Reserve, cask notes, pairings and city prices on BevOry.",
  },
  romitoro: {
    description: "RomiToro is a Tuscan red from Castello Romitorio near Montalcino. The blend brings together Syrah and Petit Verdot rather than the Sangiovese of the estate's Brunello.",
    story: "Castello Romitorio is linked to artist Sandro Chia and his family. RomiToro gives the estate a different Tuscan voice through international grape varieties.",
    tastingNotes: [{ title: "Fruit", description: "Dark cherry and plum lead the aroma." }, { title: "Spice", description: "Peppery notes and firm tannins carry the finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour slightly cool into a red-wine glass and give it time to open." }, { subheading: "Food", description: "Its grip works with mutton rogan josh or grilled aubergine." }],
    pairingIdeas: [{ title: "With RomiToro", items: ["mutton rogan josh", "grilled aubergine", "lamb chops", "mushroom ragout"] }],
    whyChoose: "A Montalcino estate's Syrah-Petit Verdot blend with a firmer, darker profile.",
    faqs: [{ question: "Who makes RomiToro?", answer: "Castello Romitorio makes RomiToro in Tuscany." }, { question: "Is RomiToro a Brunello di Montalcino?", answer: "No. RomiToro is a Tuscan red made with Syrah and Petit Verdot." }],
    finalVerdict: "RomiToro is a robust Tuscan red for a spice-heavy meal.",
    metaTitle: "RomiToro Wine Guide | BevOry", metaDescription: "Explore RomiToro Tuscan red, its Syrah-Petit Verdot blend and city prices on BevOry.",
  },
  "silly-saison": {
    description: "Silly Saison is a Belgian farmhouse-style beer from Brasserie de Silly in Hainaut. The brewery's saison keeps a lightly tart edge beside its malt and hops.",
    story: "Brasserie de Silly traces its brewing to 1850, when Marcellin Meynsbrughen began making beer for farm workers. Saison grew from that working-season tradition in Belgium's French-speaking countryside.",
    tastingNotes: [{ title: "Opening", description: "Light malt and a little orchard fruit start the beer." }, { title: "Finish", description: "A mild sour note and hop bitterness keep it brisk." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cool in a stemmed beer glass." }, { subheading: "Food", description: "The brisk finish suits pakoras or grilled chicken." }],
    pairingIdeas: [{ title: "With saison", items: ["vegetable pakoras", "grilled chicken", "goat cheese", "fried prawns"] }],
    whyChoose: "A farmhouse beer with an actual farming-brewery story behind it.",
    faqs: [{ question: "Where is Silly Saison made?", answer: "Brasserie de Silly brews it in Hainaut, Belgium." }, { question: "What is a saison?", answer: "Saison is a Belgian farmhouse ale style historically tied to seasonal agricultural work." }],
    finalVerdict: "Silly Saison's slight tang makes it a lively partner for fried snacks.",
    metaTitle: "Silly Saison Beer Guide | BevOry", metaDescription: "Explore Silly Saison farmhouse beer, pairings and city prices on BevOry.",
  },
  tiamo: {
    description: "Tiamo is a range of organic Italian wines distributed by Winesellers Ltd. Its bottles include several grape varieties and styles rather than one fixed blend.",
    story: "Tiamo's Prosecco comes from vineyards around Valdobbiadene, while its Pinot Grigio comes from near Treviso. Its Chianti is sourced from Montespertoli in Tuscany; each bottle therefore has its own regional starting point.",
    tastingNotes: [{ title: "White wines", description: "The whites lean toward fresh citrus and orchard fruit." }, { title: "Red wines", description: "The reds bring riper berry fruit and a rounder texture." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill the white or sparkling wine; serve the red slightly cool." }, { subheading: "Food", description: "Match the white with tandoori fish and the red with tomato-based pasta." }],
    pairingIdeas: [{ title: "Across the range", items: ["tandoori fish", "tomato pasta", "paneer tikka", "grilled vegetables"] }],
    whyChoose: "An organic Italian range with room to choose between fresh whites and fuller reds.",
    faqs: [{ question: "Are Tiamo wines organic?", answer: "Tiamo is presented as an organic Italian wine range." }, { question: "Is Tiamo one grape variety?", answer: "No. The range includes wines made from different grapes and regions." }],
    finalVerdict: "Tiamo is an uncomplicated route to an organic Italian dinner wine.",
    metaTitle: "Tiamo Wine Guide | BevOry", metaDescription: "Explore Tiamo organic Italian wines, serving ideas, pairings and city prices on BevOry.",
  },
};
