import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_42 = [
  ["ardmore-the", "The Ardmore", "Scotland", "Whisky", "19ca15040727363eebc6762c"],
  ["avalon", "Avalon", "United States", "Wine", "657cd4d68c6a6e51740f3289"],
  ["bobbys", "Bobby's", "Netherlands", "Gin", "7f9dd81220e07423d3d3c0fd"],
  ["carta-vieja", "Carta Vieja", "Chile", "Wine", "e591004fb3f1d7f272317d6f"],
  ["crazy-cock", "Crazy Cock", "India", "Whisky", "7a30dbe6b39163bb177152b8"],
  ["deugniet", "Deugniet", "Belgium", "Beer", "c221dcb30f0e9c265ffca60e"],
  ["directors-special", "Director's Special", "India", "Whisky", "680491046545df3fa64d2431"],
  ["heradura", "Herradura", "Mexico", "Tequila", "0e045974d781d319d040575f"],
  ["hercules", "Hercules", "India", "Rum", "d50ced435359c1f2baadf3c9"],
  ["honey-bee", "Honey Bee", "India", "Brandy", "30cce014727386344ef954b4"],
  ["iconiq-white-whisky", "ICONiQ White", "India", "Whisky", "188ba88384bf844f441c256c"],
  ["kadamba-the", "Kadamba", "India", "Whisky", "724f7773bee58e4f9b20b024"],
  ["medusa", "Medusa", "India", "Beer", "823e291431cff346861d254b"],
  ["mountain-oak", "Mountain Oak", "India", "Whisky", "8bf7d328ec19828e1567b188"],
  ["old-port", "Old Port", "India", "Rum", "21097a25eee7ec24c3e18fe6"],
  ["onegin", "Onegin", "Russia", "Vodka", "e60ed0d10eb00958dd32925d"],
  ["mis-amigos", "Mis Amigos", "United Kingdom", "Tequila Liqueur", "b441e70619ea64ebfca1b672"],
  ["old-st-andrew", "Old St Andrews", "Scotland", "Whisky", "68dcdd17ad8e09a9cca3b968"],
  ["snoski", "Snoski", "India", "Vodka", "97f631ccfae4d3ef03a17bec"],
  ["solan-no-1", "Solan No. 1", "India", "Whisky", "14e0493ccb2c172923baef9b"],
  ["something-special", "Something Special", "Scotland", "Whisky", "0ea2d4dbf96ed1dd1ef2f5f8"],
  ["viru-valge", "Viru Valge", "Estonia", "Vodka", "0e02314b328bbeda43a68317"],
  ["white-mischief", "White Mischief", "India", "Vodka", "63558ecd53f7eece31aefacc"],
  ["yaksha-small-batch", "Yaksha", "India", "Whisky", "256bee56ffc840473440aba2"],
  ["uniteds-epitome", "United's Epitome Reserve", "India", "Whisky", "ae330215bf4dcb93485c3f04"],
  ["blue-riband", "Blue Riband", "India", "Gin", "6bc261540a44a202206780e5"],
  ["no-label-mead", "No Label", "India", "Mead", "12cb8ade8fd192142af16046"],
  ["sir-edwards", "Sir Edward's", "Scotland", "Whisky", "d04ea36a33c586a9a48133c9"],
  ["gauloise", "Gauloise", "Belgium", "Beer", "0d23c819124e13fbbc5bf75f"],
  ["white-lace", "White Lace", "India", "Vodka", "0f94b9b7c47d95c8b44a98b4"],
] as const;

// Source links are retained for editorial review, never rendered as consumer copy.
export const BRAND_SOURCES_BATCH_42: Record<string, string[]> = {
  "ardmore-the": ["https://www.ardmorewhisky.com/"],
  avalon: ["https://www.avalonwinery.com/our-wines/"],
  bobbys: ["https://bobbysdrygin.com/", "https://www.abrandnewday.nl/en/brand/bobbys-dry-gin/"],
  "carta-vieja": ["https://delpedregalwines.com/EN/nuestros_vinos"],
  "crazy-cock": ["https://www.crazycocksinglemalt.com/", "https://southseasdistilleries.com/our-spirits"],
  deugniet: ["https://www.bocq.be/en/"],
  "directors-special": ["https://www.diageoindia.com/en/news-and-media/press-releases/2022/usl-signs-sale-and-franchise-agreements-for-select-popular-brands-with-inbrew"],
  heradura: ["https://www.herradura.com/en-us/the-story/", "https://www.brown-forman.com/brand/tequila-herradura"],
  hercules: ["https://thehouseofkhodays.com/hercules/"],
  "honey-bee": ["https://inbrew.com/our-brands"],
  "iconiq-white-whisky": ["https://www.abdindia.com/wp-content/uploads/2025/05/b18c-final-annual-report-fy22-23.pdf"],
  "kadamba-the": ["https://www.midrafzc.com/product/kadamba/"],
  medusa: ["https://medusabeverages.com/"],
  "mountain-oak": ["https://www.globusspirits.com/"],
  "old-port": ["https://amrutdistilleries.com/old-port-rum/"],
  onegin: ["https://oneginvodka.com/static/files/presenter_english.pdf"],
  "mis-amigos": ["https://www.bevnet.com/spirits/brands/mis-amigos"],
  "old-st-andrew": ["https://hisumer.com/wp-content/uploads/fichas_eng/OSA_clubhouse_ENG.pdf"],
  snoski: ["https://www.globusspirits.com/documents/Globus-Spirit-AR-24-25-8mb.pdf"],
  "solan-no-1": ["https://mohanmeakin.com/whiskies/"],
  "something-special": ["https://www.pernod-ricard.com/en/brands/something-special"],
  "viru-valge": ["https://liviko.ee/static/Viru-Valge-A4-2018-ENG.pdf"],
  "white-mischief": ["https://inbrew.com/our-brands"],
  "yaksha-small-batch": ["https://weareyaksha.com/", "https://www.ikemitsu.co.jp/product/yaksha/"],
  "uniteds-epitome": ["https://media.diageo.com/diageo-corporate-media/media/xzsjbaut/annual-report-2021-22.pdf"],
  "blue-riband": ["https://inbrew.com/our-brands"],
  "no-label-mead": ["https://boredbev.com/our-portfolio/", "https://www.brewer-world.com/anant-gupta-and-vinayak-malhotra-co-founders-at-no-label/"],
  "sir-edwards": ["https://www.siredwards.com/our-whiskies/finest/"],
  gauloise: ["https://www.bocq.be/en/"],
  "white-lace": ["https://www.globusspirits.com/documents/Covering_Letter_With_Investor_PPT.pdf"],
};

export const BRAND_LOGOS_BATCH_42: Record<string, string> = {
  "honey-bee": "https://inbrew.com/uploads/brand/1770886803_f94a938274a701b0f193.png",
  "blue-riband": "https://inbrew.com/uploads/brand/1770886961_cf39a1423935377ecbe7.png",
  "white-mischief": "https://inbrew.com/uploads/brand/1770887024_19eea64f0f823a822a13.png",
};

export const BRAND_CONTENT_BATCH_42: Record<string, BrandPublicContent> = {
  "ardmore-the": {
    description: "The Ardmore is a peated Highland single malt from the Ardmore Distillery in Kennethmont, Aberdeenshire. Its smoke comes from peat-dried malt, a less common choice among Highland distilleries.",
    story: "The distillery was built in 1898 to supply malt whisky for Teacher's blended Scotch. Ardmore's own bottlings put that distinctly smoky house character at the centre of the glass.",
    tastingNotes: [{ title: "Smoke", description: "Peat smoke sits beside honeyed malt rather than covering it." }, { title: "Underneath", description: "Soft vanilla and a dry, earthy finish follow the first smoky impression." }],
    howToEnjoy: [{ subheading: "Glass", description: "Try a small neat measure in a tulip glass; a little water can open the malt sweetness." }, { subheading: "At dinner", description: "Smoky whisky works with tandoori chicken or charred mushroom tikka." }],
    pairingIdeas: [{ title: "Beside Ardmore", items: ["tandoori chicken", "mushroom tikka", "smoked almonds", "aged cheddar"] }],
    whyChoose: "A Highland malt for drinkers who want peat without losing the barley beneath it.",
    faqs: [{ question: "Is The Ardmore a peated whisky?", answer: "Yes. Ardmore uses peat-dried malt for its Highland single malt." }, { question: "Where is Ardmore made?", answer: "At Ardmore Distillery in Kennethmont, Aberdeenshire, Scotland." }],
    finalVerdict: "Ardmore brings measured smoke to a classic Highland malt profile.",
    metaTitle: "The Ardmore Whisky Guide | BevOry", metaDescription: "Discover Ardmore's peated Highland style, serving ideas, food pairings and city prices on BevOry.",
  },
  avalon: {
    description: "Avalon is a California wine label with Cabernet Sauvignon, Pinot Noir and Chardonnay in its range. The bottles are approachable, fruit-led expressions of familiar Californian grapes.",
    story: "Avalon began in 1991 with a focus on California wines. Its name references the mythical island of Avalon, but the practical distinction between bottles is the grape printed on the label.",
    tastingNotes: [{ title: "Pinot Noir", description: "Red berry fruit and a lighter body mark the Pinot Noir style." }, { title: "Chardonnay", description: "Ripe orchard fruit gives the white a rounder feel than a sharply mineral wine." }],
    howToEnjoy: [{ subheading: "Pour", description: "Chill Chardonnay; give the reds a slightly cool serving temperature rather than a warm room." }, { subheading: "Table", description: "Put Pinot Noir beside chicken tikka and Cabernet beside peppery lamb chops." }],
    pairingIdeas: [{ title: "With Avalon wine", items: ["chicken tikka", "peppery lamb chops", "paneer skewers", "roast chicken"] }],
    whyChoose: "A clear route into California's best-known red and white grapes.",
    faqs: [{ question: "Is Avalon a California wine?", answer: "Yes. Avalon is a California wine label with several grape varieties." }, { question: "Does Avalon make only red wine?", answer: "No. Chardonnay sits alongside Cabernet Sauvignon and Pinot Noir in the range." }],
    finalVerdict: "Choose Avalon by grape and dinner, not by a single house-wide tasting note.",
    metaTitle: "Avalon Wine Guide | BevOry", metaDescription: "Explore Avalon Cabernet, Pinot Noir and Chardonnay, food matches and city prices on BevOry.",
  },
  bobbys: {
    description: "Bobby's is a Dutch gin and jenever name from Schiedam. Its dry gin combines traditional gin botanicals with Indonesian ingredients such as lemongrass, clove and cinnamon.",
    story: "The gin honours Jacobus 'Bobby' Alfons, whose Indonesian roots inspired his grandson Sebastiaan to revisit the family recipe. Production in Schiedam links that story to a city with a long jenever trade.",
    tastingNotes: [{ title: "Citrus and spice", description: "Lemongrass cuts through the warm clove and cinnamon." }, { title: "Gin core", description: "Juniper keeps the aromatic mix recognisably dry and herbal." }],
    howToEnjoy: [{ subheading: "Long drink", description: "Build a gin and tonic over ice with an orange slice and a few cloves." }, { subheading: "Food", description: "Pair the spice with tandoori prawns or ginger-laced chicken satay." }],
    pairingIdeas: [{ title: "With Bobby's gin", items: ["tandoori prawns", "chicken satay", "spiced cashews", "grilled fish"] }],
    whyChoose: "Dutch gin heritage with a distinctly Indonesian botanical accent.",
    faqs: [{ question: "Where is Bobby's gin made?", answer: "Bobby's Dry Gin comes from Schiedam in the Netherlands." }, { question: "What makes Bobby's gin different?", answer: "Its botanical recipe brings Indonesian lemongrass, clove and cinnamon into a juniper-led gin." }],
    finalVerdict: "Bobby's makes a gin and tonic that tastes as much of spice as of citrus.",
    metaTitle: "Bobby's Gin Guide | BevOry", metaDescription: "Meet Bobby's Schiedam gin, its Indonesian botanicals, food pairings and city prices on BevOry.",
  },
  "carta-vieja": {
    description: "Carta Vieja is a Chilean wine label from Viña del Pedregal in the Maule Valley. Its range includes varietal reds such as Merlot, with individual bottlings determining the exact style.",
    story: "The del Pedregal family's wine business has roots in Chile's central valley. Alberto del Pedregal Aldunate established the Carta Vieja name in 1978, building on that family's vineyard work.",
    tastingNotes: [{ title: "Merlot fruit", description: "The Merlot style centres on ripe plum and red fruit." }, { title: "At the table", description: "Soft tannins make the red easier to match with food than a heavily extracted wine." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Merlot slightly cool in an ordinary red-wine glass." }, { subheading: "Dinner", description: "Try it with lamb keema or mushroom and pea pulao." }],
    pairingIdeas: [{ title: "With Carta Vieja Merlot", items: ["lamb keema", "mushroom pulao", "grilled sausages", "roast aubergine"] }],
    whyChoose: "A Maule Valley red with an easy, fruit-forward place at dinner.",
    faqs: [{ question: "Where is Carta Vieja wine from?", answer: "Viña del Pedregal produces Carta Vieja in Chile's Maule Valley." }, { question: "Does Carta Vieja make Merlot?", answer: "Yes. Merlot is among the varietal wines sold under Carta Vieja." }],
    finalVerdict: "Carta Vieja Merlot is a useful red for a savoury weeknight meal.",
    metaTitle: "Carta Vieja Wine Guide | BevOry", metaDescription: "Explore Carta Vieja's Maule Valley wines, Merlot style, pairings and city prices on BevOry.",
  },
  "crazy-cock": {
    description: "Crazy Cock is an Indian single malt made by South Seas Distilleries. Dhua is its peated expression; Double Oak takes a separate route through bourbon and sherry wood.",
    story: "South Seas Distilleries built the Crazy Cock range around Indian malt and cask-driven releases. The Hindi word dhua means smoke, an unusually direct name for the peat-led bottling.",
    tastingNotes: [{ title: "Dhua", description: "Light peat runs through raisin, vanilla and warm spice." }, { title: "Double Oak", description: "Bourbon and sherry casks bring fruit, oak sweetness and spice into the same pour." }],
    howToEnjoy: [{ subheading: "First sip", description: "Pour neat, then add a little water to a second taste." }, { subheading: "Food", description: "Try Dhua with smoky paneer tikka and Double Oak with peppery mutton seekh." }],
    pairingIdeas: [{ title: "Across the range", items: ["smoky paneer tikka", "mutton seekh", "roasted cashews", "dark chocolate"] }],
    whyChoose: "Two clearly different routes into Indian single malt: peat smoke or layered oak.",
    faqs: [{ question: "Who makes Crazy Cock whisky?", answer: "South Seas Distilleries makes Crazy Cock Indian single malt." }, { question: "Is every Crazy Cock whisky peated?", answer: "No. Dhua is peated, while Double Oak is defined by its bourbon and sherry cask treatment." }],
    finalVerdict: "Crazy Cock is most interesting when Dhua and Double Oak are tasted side by side.",
    metaTitle: "Crazy Cock Whisky Guide | BevOry", metaDescription: "Compare Crazy Cock Dhua and Double Oak, tasting notes, food matches and city prices on BevOry.",
  },
  deugniet: {
    description: "Deugniet is a Belgian beer brewed by Brasserie du Bocq in Purnode. It is a strong, bottle-fermented blonde beer rather than a light lager.",
    story: "Martin Belot founded Brasserie du Bocq in Purnode in 1858. The family brewery developed a range of Belgian ales, including Deugniet, using its established bottle-conditioning tradition.",
    tastingNotes: [{ title: "Aroma", description: "Green-apple fruit meets a fine hop note above the foam." }, { title: "Finish", description: "A light bitterness keeps the stronger beer brisk." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cool in a stemmed beer glass, leaving a little sediment in the bottle if preferred." }, { subheading: "Food", description: "Its carbonation works with fried fish or peppery paneer pakora." }],
    pairingIdeas: [{ title: "With Deugniet", items: ["paneer pakora", "fried fish", "chicken cutlets", "salted almonds"] }],
    whyChoose: "A lively Belgian blonde for drinkers who want yeast character as well as strength.",
    faqs: [{ question: "Who brews Deugniet?", answer: "Brasserie du Bocq brews Deugniet in Purnode, Belgium." }, { question: "Is Deugniet a lager?", answer: "No. It is a Belgian blonde ale with bottle fermentation." }],
    finalVerdict: "Give Deugniet a proper glass and a salty snack; it rewards both.",
    metaTitle: "Deugniet Beer Guide | BevOry", metaDescription: "Explore Deugniet Belgian blonde beer, serving tips, snack pairings and city prices on BevOry.",
  },
  "directors-special": {
    description: "Director's Special is an Indian whisky brand in the United Spirits portfolio. The range includes Director's Special Black and Gold, names that refer to different bottlings rather than one fixed flavour profile.",
    story: "Director's Special became a long-standing name in India's mass-market whisky trade. United Spirits kept the brand when it transferred several other popular labels to Inbrew in 2022.",
    tastingNotes: [{ title: "Black", description: "A whisky-led, oak-tinged style intended for a simple pour or mixer." }, { title: "Gold", description: "The Gold bottling offers a separate blend with a fuller, sweeter presentation." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try over ice with a little soda before adding a stronger mixer." }, { subheading: "Snack", description: "Serve alongside masala peanuts or tandoori chicken." }],
    pairingIdeas: [{ title: "For the table", items: ["masala peanuts", "tandoori chicken", "spiced potato wedges", "mutton seekh"] }],
    whyChoose: "An established Indian whisky with distinct Black and Gold choices.",
    faqs: [{ question: "Who owns Director's Special whisky?", answer: "Director's Special remains in the United Spirits portfolio." }, { question: "Are Director's Special Black and Gold the same whisky?", answer: "No. They are separate bottlings under the same brand." }],
    finalVerdict: "Director's Special is best chosen by the exact Black or Gold bottle on the shelf.",
    metaTitle: "Director's Special Whisky Guide | BevOry", metaDescription: "Explore Director's Special Black and Gold, serving ideas, food pairings and city prices on BevOry.",
  },
  heradura: {
    description: "Herradura is a 100% blue-agave tequila made in Amatitán, Jalisco. Its Plata, Reposado and Añejo expressions give drinkers a clear choice between fresh agave and oak-aged styles.",
    story: "The estate's tequila history goes back to 1870. Herradura introduced a commercially released reposado in 1974; Brown-Forman now owns the brand.",
    tastingNotes: [{ title: "Plata", description: "Cooked agave and fresh herbal notes lead the unaged style." }, { title: "Reposado", description: "Time in oak brings vanilla and a softer, rounder finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip Plata chilled or pour Reposado neat into a small stemmed glass." }, { subheading: "Food", description: "Try grilled fish tacos or tandoori prawns with lime." }],
    pairingIdeas: [{ title: "With Herradura", items: ["grilled fish tacos", "tandoori prawns", "chilli corn", "roasted pineapple"] }],
    whyChoose: "An Amatitán tequila house with a notable place in reposado history.",
    faqs: [{ question: "Where is Herradura tequila made?", answer: "Herradura is made in Amatitán, Jalisco, Mexico." }, { question: "What does reposado mean on Herradura?", answer: "Reposado is the oak-rested expression, distinct from the unaged Plata." }],
    finalVerdict: "Herradura lets agave stay visible even when oak enters the picture.",
    metaTitle: "Herradura Tequila Guide | BevOry", metaDescription: "Discover Herradura Plata and Reposado, agave flavour, food pairings and city prices on BevOry.",
  },
  hercules: {
    description: "Hercules is a rum name from Bengaluru-based Khoday India. Its Old Matured Deluxe XXX is a dark rum, while Hercules Bianco is a separate light rum.",
    story: "The Khoday family built its spirits business in Karnataka and made Hercules one of its rum labels. The XXX and Bianco bottles are best understood as different styles within that same name.",
    tastingNotes: [{ title: "XXX rum", description: "Caramel warmth and woody notes define the dark pour." }, { title: "Bianco", description: "The lighter bottling is intended for a cleaner mixed drink." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour XXX over ice with cola and lime; use Bianco in a lime-forward long drink." }, { subheading: "Food", description: "Dark rum meets pepper chicken or sticky chilli paneer." }],
    pairingIdeas: [{ title: "With Hercules rum", items: ["pepper chicken", "chilli paneer", "spiced peanuts", "grilled pineapple"] }],
    whyChoose: "A Karnataka rum label with both dark and light options.",
    faqs: [{ question: "Who makes Hercules rum?", answer: "Khoday India makes Hercules rum." }, { question: "Is Hercules Bianco the same as Hercules XXX?", answer: "No. Bianco is a light rum; Old Matured Deluxe XXX is dark." }],
    finalVerdict: "Hercules XXX suits a darker mixed drink; Bianco keeps the pour lighter.",
    metaTitle: "Hercules Rum Guide | BevOry", metaDescription: "Compare Hercules XXX and Bianco rum, serving ideas, food matches and city prices on BevOry.",
  },
  "honey-bee": {
    description: "Honey Bee is an Indian brandy now in the Inbrew portfolio. It is made in a sweet, fruit-forward style intended for uncomplicated drinking.",
    story: "Honey Bee was among the popular brands transferred from United Spirits to Inbrew in 2022. Its familiar name has lasted through that ownership change without turning the drink into a honey liqueur.",
    tastingNotes: [{ title: "Fruit", description: "Grape-fruit sweetness sits at the front of the brandy." }, { title: "Finish", description: "Honeyed warmth and mild spice follow the fruit." }],
    howToEnjoy: [{ subheading: "Pour", description: "Take a small neat measure or add ice and a splash of water." }, { subheading: "Food", description: "Try with roasted almonds or gulab jamun after dinner." }],
    pairingIdeas: [{ title: "With Honey Bee", items: ["roasted almonds", "gulab jamun", "apple tart", "salted cashews"] }],
    whyChoose: "A familiar Indian brandy whose fruit and sweetness suit a short after-dinner pour.",
    faqs: [{ question: "Who owns Honey Bee brandy?", answer: "Honey Bee is part of Inbrew's spirits portfolio." }, { question: "Is Honey Bee a honey-flavoured liqueur?", answer: "No. Honey Bee is sold as brandy." }],
    finalVerdict: "Honey Bee keeps brandy easy to approach without asking for a complicated serve.",
    metaTitle: "Honey Bee Brandy Guide | BevOry", metaDescription: "Discover Honey Bee brandy, its fruit-led style, pairings and city prices on BevOry.",
  },
  "iconiq-white-whisky": {
    description: "ICONiQ White is an Indian whisky from Allied Blenders & Distillers. The blend combines Scotch malts matured in bourbon oak with Indian grain spirits.",
    story: "Allied Blenders & Distillers introduced ICONiQ White as a contemporary addition to its whisky portfolio. The company is also behind Officer's Choice, but ICONiQ White is a separate label with its own identity.",
    tastingNotes: [{ title: "Malt", description: "A soft cereal note reflects the whisky's malt-and-grain base." }, { title: "Oak", description: "The bourbon-cask malt brings a gently sweet wood influence." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice and top with soda and a squeeze of lemon." }, { subheading: "Snack", description: "Pair with chicken malai tikka or salted cashews." }],
    pairingIdeas: [{ title: "With ICONiQ White", items: ["chicken malai tikka", "salted cashews", "paneer skewers", "potato wedges"] }],
    whyChoose: "A lighter-looking Indian whisky built for an easy highball.",
    faqs: [{ question: "Who makes ICONiQ White whisky?", answer: "Allied Blenders & Distillers makes ICONiQ White." }, { question: "Is ICONiQ White a vodka?", answer: "No. It is sold as a whisky despite its pale colour." }],
    finalVerdict: "ICONiQ White makes most sense over ice with a bright mixer.",
    metaTitle: "ICONiQ White Whisky Guide | BevOry", metaDescription: "Explore ICONiQ White whisky, highball serves, food matches and city prices on BevOry.",
  },
  "kadamba-the": {
    description: "Kadamba is an Indian single malt whisky with Sherry Cask and Agave Barrel Finished expressions. The cask named on the bottle matters: these are not interchangeable pours.",
    story: "The Kadamba name draws on a historic dynasty associated with Goa. Its whisky range uses contrasting cask finishes to give the Indian malt distinct directions.",
    tastingNotes: [{ title: "Sherry Cask", description: "Dried fruit, toffee, vanilla and dark chocolate mark the sherry-led bottling." }, { title: "Agave finish", description: "The agave-barrel expression takes a different, brighter route through the cask." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip neat in a small whisky glass, then add a few drops of water." }, { subheading: "Dinner", description: "Sherry Cask works with mutton seekh or dark chocolate." }],
    pairingIdeas: [{ title: "With Kadamba", items: ["mutton seekh", "dark chocolate", "roasted almonds", "paneer tikka"] }],
    whyChoose: "An Indian single malt range whose cask differences are worth tasting directly.",
    faqs: [{ question: "Is Kadamba an Indian single malt?", answer: "Yes. Kadamba sells Indian single malt whisky." }, { question: "Are Kadamba Sherry Cask and Agave Barrel the same?", answer: "No. They are separate cask-led expressions." }],
    finalVerdict: "Choose Kadamba by cask: sherry richness or an agave-barrel twist.",
    metaTitle: "Kadamba Whisky Guide | BevOry", metaDescription: "Compare Kadamba Indian single malts, cask styles, pairings and city prices on BevOry.",
  },
  medusa: {
    description: "Medusa is an Indian beer brand from Medusa Beverages, founded in Delhi. Its range includes Premium Strong and Air Mild, two different choices for drinkers of packaged beer.",
    story: "Medusa Beverages began in 2017 and expanded the Medusa name through India's state-by-state beer market. The Air Mild release broadened a range first associated with stronger beer.",
    tastingNotes: [{ title: "Air Mild", description: "A lighter malt impression and crisp finish suit a cold pour." }, { title: "Premium Strong", description: "More weight and malt sweetness distinguish the stronger beer." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve well chilled in a clean lager glass." }, { subheading: "Snack", description: "Try with chilli paneer or chicken 65." }],
    pairingIdeas: [{ title: "With Medusa beer", items: ["chilli paneer", "chicken 65", "masala fries", "fried fish"] }],
    whyChoose: "A Delhi-born beer name with both mild and strong releases.",
    faqs: [{ question: "Is Medusa an Indian beer?", answer: "Yes. Medusa Beverages began in Delhi, India." }, { question: "Does Medusa make only strong beer?", answer: "No. Air Mild sits alongside Premium Strong in its range." }],
    finalVerdict: "Medusa is a cold-beer choice where the Mild versus Strong decision comes first.",
    metaTitle: "Medusa Beer Guide | BevOry", metaDescription: "Explore Medusa Air Mild and Premium Strong, snack matches and city prices on BevOry.",
  },
  "mountain-oak": {
    description: "Mountain Oak is an Indian whisky from Globus Spirits. Its blend combines Scotch malt with Indian grain spirit; it is not an Indian single malt.",
    story: "Globus Spirits developed Mountain Oak within the same wider portfolio as DOAAB and Terai. Here the focus is a blended whisky rather than DOAAB's all-malt identity.",
    tastingNotes: [{ title: "Malt", description: "Malt sweetness gives the blend an accessible opening." }, { title: "Oak", description: "Wood notes and gentle spice round out the finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try with ice and a splash of soda." }, { subheading: "Food", description: "Serve with chicken tikka or roasted peanuts." }],
    pairingIdeas: [{ title: "With Mountain Oak", items: ["chicken tikka", "roasted peanuts", "paneer skewers", "grilled mushrooms"] }],
    whyChoose: "A Globus blend that puts Scotch malt into an Indian whisky context.",
    faqs: [{ question: "Is Mountain Oak a single malt?", answer: "No. Globus Spirits describes it as a blend of Scotch malt and Indian grain spirit." }, { question: "Who makes Mountain Oak?", answer: "Mountain Oak is a Globus Spirits brand." }],
    finalVerdict: "Mountain Oak is a simple blended-whisky pour for ice and soda.",
    metaTitle: "Mountain Oak Whisky Guide | BevOry", metaDescription: "Discover Mountain Oak blended whisky, serving ideas, food pairings and city prices on BevOry.",
  },
  "old-port": {
    description: "Old Port is an Indian rum from Amrut Distilleries. It is made from cane molasses and matured in a combination of ex-whisky and new oak casks.",
    story: "Amrut is based in Bengaluru and is widely known for whisky, but Old Port shows its long-running rum side. The brand's dark rum is a separate proposition from Amrut's single malts.",
    tastingNotes: [{ title: "Nose", description: "Vanilla, sweet spice and pistachio-brittle notes rise from the glass." }, { title: "Palate", description: "Ginger and nutmeg carry the oak-influenced finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try neat before adding ice or a squeeze of lime." }, { subheading: "Food", description: "Match its spice with pepper chicken or jaggery-coated peanuts." }],
    pairingIdeas: [{ title: "With Old Port", items: ["pepper chicken", "jaggery peanuts", "grilled pineapple", "dark chocolate"] }],
    whyChoose: "A molasses rum whose cask and spice character stand up to a neat pour.",
    faqs: [{ question: "Who makes Old Port rum?", answer: "Amrut Distilleries makes Old Port in India." }, { question: "What is Old Port rum made from?", answer: "Amrut identifies cane molasses as its base ingredient." }],
    finalVerdict: "Old Port is worth tasting neat before it goes into a mixer.",
    metaTitle: "Old Port Rum Guide | BevOry", metaDescription: "Discover Amrut Old Port rum, oak and spice notes, pairings and city prices on BevOry.",
  },
  onegin: {
    description: "Onegin is a Russian vodka made from wheat. The name references Alexander Pushkin's Eugene Onegin, giving this otherwise spare grain spirit a literary identity.",
    story: "Onegin's makers place the brand in St Petersburg's cultural tradition. The vodka itself is built around wheat rather than a flavoured-fruit recipe.",
    tastingNotes: [{ title: "Opening", description: "A mild cereal sweetness and a hint of almond keep the first sip rounded." }, { title: "Finish", description: "The close is drier, with a slight bitter edge." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the bottle and pour a small measure into a cold shot glass." }, { subheading: "Food", description: "Try alongside smoked fish or dill-topped potato cutlets." }],
    pairingIdeas: [{ title: "With Onegin", items: ["smoked fish", "dill potato cutlets", "salted cucumber", "blini with sour cream"] }],
    whyChoose: "A wheat vodka with a restrained, dry finish and a St Petersburg connection.",
    faqs: [{ question: "What grain is Onegin vodka made from?", answer: "Onegin identifies wheat as its base grain." }, { question: "Is Onegin a flavoured vodka?", answer: "The core Onegin vodka is a wheat spirit rather than a fruit-flavoured release." }],
    finalVerdict: "Onegin suits a chilled, unadorned pour beside savoury food.",
    metaTitle: "Onegin Vodka Guide | BevOry", metaDescription: "Explore Onegin wheat vodka, a simple chilled serve, food pairings and city prices on BevOry.",
  },
  "mis-amigos": {
    description: "Mis Amigos is a UK-owned range of tequila cream liqueurs. Strawberry Cream, Chocolate Cream and Coffee Cream are dessert-style drinks, not plain blanco tequila.",
    story: "The Mis Amigos name grew around flavoured tequila-based pours from the G&I Spirits Group. Its cream bottles make the flavour printed on the label the main decision for a drinker.",
    tastingNotes: [{ title: "Strawberry Cream", description: "Sweet berry and cream lead the lighter dessert serve." }, { title: "Coffee Cream", description: "Coffee and creamy sweetness give this bottling a deeper after-dinner character." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill thoroughly and pour a small measure over ice." }, { subheading: "Dessert", description: "Strawberry Cream suits vanilla ice cream; Coffee Cream works with chocolate brownies." }],
    pairingIdeas: [{ title: "After dinner", items: ["vanilla ice cream", "chocolate brownies", "strawberry tart", "coffee kulfi"] }],
    whyChoose: "An easy dessert drink when the occasion calls for cream rather than a straight tequila shot.",
    faqs: [{ question: "Is Mis Amigos a plain tequila?", answer: "The cream releases are tequila-based liqueurs, not unflavoured blanco tequila." }, { question: "What Mis Amigos flavours are there?", answer: "The range includes Strawberry Cream, Chocolate Cream and Coffee Cream." }],
    finalVerdict: "Pick the Mis Amigos cream flavour to match dessert and keep the pour small.",
    metaTitle: "Mis Amigos Tequila Liqueur Guide | BevOry", metaDescription: "Compare Mis Amigos cream liqueurs, dessert pairings, serving ideas and city prices on BevOry.",
  },
  "old-st-andrew": {
    description: "Old St Andrews is a Scotch whisky brand best recognised for its golf-ball-shaped Clubhouse bottle. Clubhouse is a blended Scotch rather than a single malt.",
    story: "The brand took Scotland's golfing heritage as its packaging cue, making the bottle itself part of the gift appeal. Underneath that shape is a blended Scotch intended for an everyday whisky serve.",
    tastingNotes: [{ title: "First sip", description: "Sweet malt and soft cereal notes open the blend." }, { title: "Finish", description: "Light oak and gentle spice keep the closing sip measured." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour over one large piece of ice or make a soda highball." }, { subheading: "Snack", description: "Pair with chicken malai tikka or salted almonds." }],
    pairingIdeas: [{ title: "With Clubhouse", items: ["chicken malai tikka", "salted almonds", "fish fingers", "cheddar toast"] }],
    whyChoose: "A recognisable golf-themed bottle containing an accessible blended Scotch.",
    faqs: [{ question: "Why is Old St Andrews shaped like a golf ball?", answer: "The Clubhouse bottle references St Andrews and Scotland's golfing tradition." }, { question: "Is Old St Andrews Clubhouse a single malt?", answer: "No. Clubhouse is a blended Scotch whisky." }],
    finalVerdict: "Old St Andrews Clubhouse is as much a gift bottle as a straightforward highball whisky.",
    metaTitle: "Old St Andrews Whisky Guide | BevOry", metaDescription: "Meet Old St Andrews Clubhouse Scotch, golf-ball bottle, pairings and city prices on BevOry.",
  },
  snoski: {
    description: "Snoski is a vodka label from India's Globus Spirits. The range includes plain and flavoured grain-vodka releases.",
    story: "Globus Spirits added Snoski to a portfolio that also spans whisky and gin. The vodka's variants give buyers a choice between a neutral mixer base and fruit-led pours.",
    tastingNotes: [{ title: "Plain vodka", description: "A clean grain profile leaves room for citrus or soda." }, { title: "Flavoured releases", description: "The named fruit variant leads the aroma rather than the vodka's base grain." }],
    howToEnjoy: [{ subheading: "Highball", description: "Build over ice with soda and a squeeze of lime." }, { subheading: "Food", description: "Try with tandoori fish or chilli garlic mushrooms." }],
    pairingIdeas: [{ title: "With Snoski", items: ["tandoori fish", "chilli garlic mushrooms", "salted peanuts", "potato croquettes"] }],
    whyChoose: "A Globus vodka range for straightforward citrus highballs or a fruit-flavoured pour.",
    faqs: [{ question: "Who makes Snoski vodka?", answer: "Globus Spirits includes Snoski in its Indian drinks portfolio." }, { question: "Is every Snoski vodka flavoured?", answer: "No. The range includes plain vodka as well as flavoured variants." }],
    finalVerdict: "Snoski is most useful as a chilled vodka base for a short, bright mixer.",
    metaTitle: "Snoski Vodka Guide | BevOry", metaDescription: "Explore Snoski vodka styles, highball serves, snack pairings and city prices on BevOry.",
  },
  "solan-no-1": {
    description: "Solan No. 1 is an Indian whisky from Mohan Meakin. The Black bottling carries a name closely tied to the company's Himachal Pradesh history.",
    story: "Mohan Meakin's brewing and distilling roots run through Kasauli and Solan. Solan No. 1 remains a whisky label within that longer company story, distinct from the firm's Old Monk rum.",
    tastingNotes: [{ title: "Malt", description: "Cereal sweetness gives the whisky a direct opening." }, { title: "Finish", description: "A little wood and spice keep the aftertaste dry." }],
    howToEnjoy: [{ subheading: "Pour", description: "Start with ice and a splash of water; add soda for a longer drink." }, { subheading: "Food", description: "Pair with mutton seekh or roasted masala peanuts." }],
    pairingIdeas: [{ title: "With Solan No. 1", items: ["mutton seekh", "masala peanuts", "paneer tikka", "spiced potato wedges"] }],
    whyChoose: "A Mohan Meakin whisky with a direct link to Solan's distilling history.",
    faqs: [{ question: "Who makes Solan No. 1 whisky?", answer: "Mohan Meakin makes Solan No. 1." }, { question: "Is Solan No. 1 the same as Old Monk?", answer: "No. Solan No. 1 is a whisky; Old Monk is Mohan Meakin's rum brand." }],
    finalVerdict: "This Solan whisky carries an old Himachal name into an uncomplicated serve.",
    metaTitle: "Solan No. 1 Whisky Guide | BevOry", metaDescription: "Discover Solan No. 1 whisky, Mohan Meakin heritage, food pairings and city prices on BevOry.",
  },
  "something-special": {
    description: "Something Special is a blended Scotch whisky in the Pernod Ricard portfolio. Its recipe brings malt and grain whisky together for a gently smoky, sweet style.",
    story: "The blend dates to 1912 and has maintained the Something Special name through more than a century of Scotch whisky trade. Its identity rests on blending rather than a single distillery's malt.",
    tastingNotes: [{ title: "Opening", description: "Malt sweetness and vanilla come through first." }, { title: "Aftertaste", description: "A soft thread of smoke and spice gives the finish shape." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try neat, then over ice or in a soda highball." }, { subheading: "Dinner", description: "Smoky-sweet Scotch suits chicken tikka or smoked paneer." }],
    pairingIdeas: [{ title: "With Something Special", items: ["chicken tikka", "smoked paneer", "roasted almonds", "grilled sausages"] }],
    whyChoose: "A century-old Scotch blend whose light smoke does not crowd out its sweetness.",
    faqs: [{ question: "Is Something Special a blended Scotch?", answer: "Yes. It combines malt and grain Scotch whiskies." }, { question: "Who owns Something Special whisky?", answer: "Something Special is part of Pernod Ricard's spirits portfolio." }],
    finalVerdict: "Something Special works best when its gentle smoke is left room to show.",
    metaTitle: "Something Special Whisky Guide | BevOry", metaDescription: "Explore Something Special blended Scotch, tasting style, pairings and city prices on BevOry.",
  },
  "viru-valge": {
    description: "Viru Valge is an Estonian vodka from Liviko. It is made from grain spirit and filtered for a clean, restrained drinking style.",
    story: "Liviko has produced drinks in Estonia since the nineteenth century. Viru Valge became one of the company's defining vodka names and now spans several variants.",
    tastingNotes: [{ title: "Plain vodka", description: "A mild cereal note sits behind a crisp first sip." }, { title: "Finish", description: "The close is clean, with a light warmth rather than a fruit flavour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour chilled into a small glass or mix with cold soda and lemon." }, { subheading: "Food", description: "Pair with smoked fish or dill potato salad." }],
    pairingIdeas: [{ title: "With Viru Valge", items: ["smoked fish", "dill potato salad", "salted cucumber", "fried fish"] }],
    whyChoose: "A long-running Estonian vodka name with a plain grain-spirit core.",
    faqs: [{ question: "Where is Viru Valge vodka from?", answer: "Viru Valge is an Estonian vodka made by Liviko." }, { question: "Is Viru Valge only sold plain?", answer: "No. Liviko has released variants alongside the plain vodka." }],
    finalVerdict: "Viru Valge belongs in the freezer before a simple savoury spread.",
    metaTitle: "Viru Valge Vodka Guide | BevOry", metaDescription: "Discover Viru Valge Estonian vodka, chilled serves, food matches and city prices on BevOry.",
  },
  "white-mischief": {
    description: "White Mischief is an Indian vodka label now in Inbrew's portfolio. Its range includes plain and flavoured releases made for mixed drinks.",
    story: "The brand launched in the 1990s and moved from United Spirits to Inbrew in the 2022 sale of several popular labels. That change of ownership did not make the different flavours identical drinks.",
    tastingNotes: [{ title: "Plain", description: "A light, neutral grain profile keeps the mixer in focus." }, { title: "Orange variant", description: "Sweet orange aroma takes the lead in the citrus bottling." }],
    howToEnjoy: [{ subheading: "Highball", description: "Use plenty of ice, soda and a slice of lime for the plain vodka." }, { subheading: "Food", description: "Try with chilli paneer or chicken 65." }],
    pairingIdeas: [{ title: "With White Mischief", items: ["chilli paneer", "chicken 65", "masala fries", "spiced peanuts"] }],
    whyChoose: "A familiar Indian mixing vodka with a choice of plain or fruit-led styles.",
    faqs: [{ question: "Who owns White Mischief vodka?", answer: "White Mischief is part of Inbrew's portfolio." }, { question: "Does White Mischief come in flavours?", answer: "Yes. The range includes flavoured vodka alongside the plain release." }],
    finalVerdict: "White Mischief is a mixer-first vodka; choose the plain or flavoured bottle for the drink you have in mind.",
    metaTitle: "White Mischief Vodka Guide | BevOry", metaDescription: "Compare White Mischief vodka styles, easy mixers, snack pairings and city prices on BevOry.",
  },
  "yaksha-small-batch": {
    description: "Yaksha is an Indian whisky that brings Scotch malt and Indian grain spirit together. Its recipe also takes inspiration from Indian botanicals, including date and basil.",
    story: "The Yaksha name draws on a figure from Indian mythology, while the drink combines whisky-making traditions from Scotland and India. It is a blend, not an Indian single malt.",
    tastingNotes: [{ title: "Opening", description: "Oak sweetness and cereal sit behind a soft fruit note." }, { title: "Botanical edge", description: "Date-like sweetness and herbal lift distinguish it from a plain whisky blend." }],
    howToEnjoy: [{ subheading: "Glass", description: "Take a neat first sip, then try ice or a little cold water." }, { subheading: "Food", description: "Pair with galouti kebabs or charred paneer." }],
    pairingIdeas: [{ title: "With Yaksha", items: ["galouti kebabs", "charred paneer", "salted dates", "roasted cashews"] }],
    whyChoose: "A whisky blend that puts an Indian botanical accent on a Scotch-and-grain base.",
    faqs: [{ question: "Is Yaksha an Indian single malt?", answer: "No. Its recipe combines Scotch malt whisky and Indian grain spirit." }, { question: "What makes Yaksha's style unusual?", answer: "Its flavour concept draws on Indian ingredients including date and basil." }],
    finalVerdict: "Yaksha is a blend to try neat before its herbal side gets diluted in a mixer.",
    metaTitle: "Yaksha Whisky Guide | BevOry", metaDescription: "Explore Yaksha's Scotch-and-Indian whisky blend, pairings and city prices on BevOry.",
  },
  "uniteds-epitome": {
    description: "United's Epitome Reserve is a limited Indian whisky project from Diageo India. The second Epitome Reserve release is a peated Indian single malt, distinct from the rice-based first release.",
    story: "United Spirits used Epitome Reserve to showcase small-run Indian whisky-making. Its first release explored rice; the later peated single malt moved the series in a different direction.",
    tastingNotes: [{ title: "Smoke", description: "Peat brings a distinct smoky opening to the second release." }, { title: "Malt", description: "Barley sweetness remains under the smoke, separating it from a one-note peated pour." }],
    howToEnjoy: [{ subheading: "Glass", description: "Taste neat in a tulip glass before adding a few drops of water." }, { subheading: "Food", description: "Try with charcoal-grilled paneer or peppery mutton seekh." }],
    pairingIdeas: [{ title: "With peated Epitome", items: ["charcoal-grilled paneer", "mutton seekh", "smoked almonds", "dark chocolate"] }],
    whyChoose: "A rare Diageo India release that puts peat at the centre of an Indian single malt.",
    faqs: [{ question: "Is the second United's Epitome Reserve made from rice?", answer: "No. The second release is a peated Indian single malt; rice was associated with the first release." }, { question: "Who made Epitome Reserve?", answer: "United Spirits, part of Diageo India, made the Epitome Reserve releases." }],
    finalVerdict: "The peated Epitome is the one to seek for smoke, not the rice-whisky story of its predecessor.",
    metaTitle: "United's Epitome Whisky Guide | BevOry", metaDescription: "Explore United's Epitome Reserve peated single malt, pairings and city prices on BevOry.",
  },
  "blue-riband": {
    description: "Blue Riband is an Indian gin brand in the Inbrew portfolio. The long-running name includes the core gin and flavoured variants.",
    story: "Blue Riband dates to 1959 and became a familiar name in India's domestic gin market. It moved from United Spirits to Inbrew as part of a wider brand sale in 2022.",
    tastingNotes: [{ title: "Core gin", description: "Herbal gin notes meet a dry, mixer-friendly finish." }, { title: "Fruit variants", description: "The flavoured releases lead with their named fruit, changing the balance of a tonic serve." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour the core gin over ice with tonic and lemon." }, { subheading: "Snack", description: "Try with tandoori fish or masala peanuts." }],
    pairingIdeas: [{ title: "With Blue Riband", items: ["tandoori fish", "masala peanuts", "cucumber chaat", "grilled prawns"] }],
    whyChoose: "An established Indian gin name for a no-fuss tonic.",
    faqs: [{ question: "Who owns Blue Riband gin?", answer: "Blue Riband is now part of Inbrew's portfolio." }, { question: "Does Blue Riband have flavoured gin?", answer: "Yes. Flavoured variants have been sold alongside the core gin." }],
    finalVerdict: "Blue Riband keeps a gin and tonic simple, with fruit variants for a different mood.",
    metaTitle: "Blue Riband Gin Guide | BevOry", metaDescription: "Discover Blue Riband Indian gin, tonic serves, food matches and city prices on BevOry.",
  },
  "no-label-mead": {
    description: "No Label is an Indian mead from Bored Beverages. Mead is made by fermenting honey, giving this drink a different base from beer or grape wine.",
    story: "Bored Beverages developed No Label around India's small but growing interest in honey-fermented drinks. Its portfolio page now describes the project as paused, making No Label more of a catalogue discovery than a current release announcement.",
    tastingNotes: [{ title: "Original mead", description: "The original release is light and crisp, with a citrus-forward edge." }, { title: "Fruit and flowers", description: "Floral and fruity notes sit ahead of a heavy honey flavour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill well and pour into a small wine glass." }, { subheading: "Food", description: "Try with peppery paneer tikka or apple tart." }],
    pairingIdeas: [{ title: "With No Label mead", items: ["paneer tikka", "apple tart", "roasted almonds", "aged cheddar"] }],
    whyChoose: "An Indian honey-fermented drink for someone curious about mead rather than another beer.",
    faqs: [{ question: "What is No Label mead made from?", answer: "Mead is a fermented-honey drink; No Label is Bored Beverages' mead project." }, { question: "Who created No Label mead?", answer: "Bored Beverages developed the No Label mead range in India." }],
    finalVerdict: "No Label is an interesting reference point for India's mead story, even while the project is paused.",
    metaTitle: "No Label Mead Guide | BevOry", metaDescription: "Learn about No Label Indian mead, honey fermentation, pairings and city prices on BevOry.",
  },
  "sir-edwards": {
    description: "Sir Edward's is a blended Scotch whisky made from malt and grain Scotch. The Finest bottling is positioned as a light, approachable blend.",
    story: "Sir Edward's draws on Scotland's long blending tradition rather than a single distillery story. Its Finest label is the core expression in a range that also includes older releases.",
    tastingNotes: [{ title: "Opening", description: "Cereal and light fruit lead the whisky." }, { title: "Finish", description: "Soft oak and a touch of sweetness keep the blend easy-going." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice, top with soda and add a lemon twist." }, { subheading: "Food", description: "Try with chicken malai tikka or salted almonds." }],
    pairingIdeas: [{ title: "With Sir Edward's", items: ["chicken malai tikka", "salted almonds", "fish cutlets", "cheddar toast"] }],
    whyChoose: "A light blended Scotch that makes a clean, uncomplicated highball.",
    faqs: [{ question: "Is Sir Edward's a blended Scotch?", answer: "Yes. Sir Edward's combines malt and grain Scotch whisky." }, { question: "Which Sir Edward's bottle is the core release?", answer: "Sir Edward's Finest is the brand's core blended Scotch." }],
    finalVerdict: "Sir Edward's Finest is a reliable choice for an ice-cold Scotch and soda.",
    metaTitle: "Sir Edward's Whisky Guide | BevOry", metaDescription: "Explore Sir Edward's Finest blended Scotch, simple serves, pairings and city prices on BevOry.",
  },
  gauloise: {
    description: "Gauloise is a Belgian beer range brewed by Brasserie du Bocq in Purnode. Blonde, Amber and darker releases make it a family of ales rather than one fixed-tasting beer.",
    story: "Brasserie du Bocq has brewed in Purnode since Martin Belot founded the family business in 1858. Gauloise carries that Belgian brewing tradition across several colours and strengths.",
    tastingNotes: [{ title: "Blonde", description: "Pale malt, lively bubbles and yeast spice define the lighter pour." }, { title: "Amber", description: "Deeper malt brings caramel and a rounder body." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve cool in a stemmed beer glass, leaving room for foam." }, { subheading: "Food", description: "Blonde suits fish pakora; Amber can take on chicken tikka." }],
    pairingIdeas: [{ title: "Across Gauloise", items: ["fish pakora", "chicken tikka", "roast mushrooms", "salted nuts"] }],
    whyChoose: "A Belgian ale range that moves from crisp blonde to maltier amber styles.",
    faqs: [{ question: "Who brews Gauloise beer?", answer: "Brasserie du Bocq brews Gauloise in Purnode, Belgium." }, { question: "Is Gauloise only a blonde beer?", answer: "No. The range includes other Belgian ale styles, including Amber." }],
    finalVerdict: "The Gauloise label is a starting point; the colour of the bottle tells you which beer to expect.",
    metaTitle: "Gauloise Beer Guide | BevOry", metaDescription: "Compare Gauloise Belgian ales, serving ideas, snack pairings and city prices on BevOry.",
  },
  "white-lace": {
    description: "White Lace is a vodka label in the Globus Spirits portfolio. It includes flavoured bottlings such as Orange, made for an easy cold mixer.",
    story: "Globus Spirits has developed White Lace alongside its other Indian drinks brands. The Orange release gives the vodka a direct fruit-led role rather than presenting it as a plain spirit.",
    tastingNotes: [{ title: "Orange", description: "Sweet citrus aroma leads the Orange bottling." }, { title: "Mixed", description: "Soda adds a crisp edge to the fruit-led vodka." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over plenty of ice and top with soda." }, { subheading: "Snack", description: "Pair with chilli paneer or salted popcorn." }],
    pairingIdeas: [{ title: "With White Lace Orange", items: ["chilli paneer", "salted popcorn", "chicken 65", "masala fries"] }],
    whyChoose: "A simple orange-vodka option for a cold, citrus-forward highball.",
    faqs: [{ question: "Who makes White Lace vodka?", answer: "White Lace is a Globus Spirits vodka brand." }, { question: "Does White Lace have an Orange version?", answer: "Yes. Orange is among the brand's flavoured vodka releases." }],
    finalVerdict: "White Lace Orange is best kept cold and mixed simply.",
    metaTitle: "White Lace Vodka Guide | BevOry", metaDescription: "Explore White Lace Orange vodka, citrus serves, snack pairings and city prices on BevOry.",
  },
};
