import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_18 = [
  ["bowmore", "Bowmore", "Scotland", "Single Malts", "90ae0146801951084eb6325a"],
  ["bruichladdich", "Bruichladdich", "Scotland", "Single Malts", "1b5c31088ff89c2860a37cac"],
  ["buffalo-trace", "Buffalo Trace", "United States", "World Whisky", "b0b68e8258af41cf30242068"],
  ["bulleit", "Bulleit", "United States", "World Whisky", "f8508c31c372363c18b29dc6"],
  ["campari", "Campari", "Italy", "Aperitif", "6163405c7a834f68df51634b"],
  ["cointreau", "Cointreau", "France", "Liqueur", "526e4b017af2bf7caf048b4c"],
  ["ciroc", "Ciroc", "France", "Vodka", "5f54557c7537945f26556265"],
  ["kahlua", "Kahlua", "Mexico", "Liqueur", "afa06d194fbcc82f37c70bca"],
  ["dalwhinnie", "Dalwhinnie", "Scotland", "Single Malts", "ad3286b7bf7c6d8bf8291595"],
  ["glenkinchie", "Glenkinchie", "Scotland", "Single Malts", "2fd33cd69ddc14256394ab87"],
  ["lagavulin", "Lagavulin", "Scotland", "Single Malts", "6dc636088b183b85ac96d052"],
  ["oban", "Oban", "Scotland", "Single Malts", "b7daeeb163804768f8ab7dfc"],
  ["highland-park", "Highland Park", "Scotland", "Single Malts", "461f31ce308cfca632a21131"],
  ["kilchoman", "Kilchoman", "Scotland", "Single Malts", "c9b630f8291b0624c3cdda0f"],
  ["teremana", "Teremana", "Mexico", "Tequila", "34f1dcfd6e380fd25476d38c"],
  ["teachers", "Teacher's", "Scotland", "Blended Scotch", "f434d56d24bbc7bf16294f56"],
  ["royal-green", "Royal Green", "India", "Indian Whisky", "573e41e4fc665d90f3d1a193"],
  ["royal-stag", "Royal Stag", "India", "Indian Whisky", "a698246eb239f2762480f7ba"],
  ["bee-young", "BeeYoung", "India", "Beer", "611147b2bf4cd418d45fb7a6"],
  ["bad-monkey", "Bad Monkey", "India", "Beer", "a21db4e060fd8a028f16d05a"],
] as const;

// Evidence stays outside BrandPublicContent and is not rendered on brand pages.
export const BRAND_SOURCES_BATCH_18: Record<string, string[]> = {
  bowmore: ["https://www.bowmore.com/en-gb/whiskies/12-year-old", "https://www.bowmore.com/stories/a-journey-through-flavour-stories"],
  bruichladdich: ["https://us.bruichladdich.com/pages/faqs", "https://www.bruichladdich.com/blogs/philosophy/whats-in-your-whisky"],
  "buffalo-trace": ["https://www.buffalotracedistillery.com/our-brands/bourbon/buffalo-trace-bourbon/", "https://www.buffalotrace.com/mobile/our-bourbon.html"],
  bulleit: ["https://www.bulleit.com/whiskeys/bulleit-bourbon", "https://www.bulleit.com/fr-fr/l-histoire-de-bulleit", "https://media.diageo.com/diageo-corporate-media/media/b0ndfru5/288_bulleit-frontier-whiskey-vc-release-final.pdf"],
  campari: ["https://www.campari.com/en-gb/our-history/", "https://www.campari.com/en-jm/campari/"],
  cointreau: ["https://www.cointreau.com/us/en/discover-cointreau/history", "https://www.cointreau.com/au/en/art-cointreau/terroir"],
  ciroc: ["https://www.ciroc.com/en/ciroc-flavours/ciroc-vodka", "https://www.ciroc.com/en/our-roots"],
  kahlua: ["https://www.kahlua.com/en-us/products/original-coffee-liqueur/", "https://www.kahlua.com/en-us/about/"],
  dalwhinnie: ["https://www.malts.com/en/products/dalwhinnie-15-year-old-single-malt-scotch-whisky-70cl", "https://www.malts.com/en/dalwhinnie"],
  glenkinchie: ["https://www.malts.com/en/glenkinchie", "https://www.malts.com/en/products/glenkinchie-12-year-old-single-malt-scotch-whisky-70cl"],
  lagavulin: ["https://www.malts.com/en/lagavulin", "https://www.malts.com/en/products/lagavulin-16-year-old-single-malt-scotch-whisky-70cl"],
  oban: ["https://www.malts.com/en/articles/oban-the-town-that-whisky-built", "https://www.malts.com/en-au/products/oban-14-year-old-single-malt-scotch-whisky-700ml", "https://www.malts.com/en-be/oban"],
  "highland-park": ["https://www.highlandparkwhisky.com/en/orkney-stories", "https://www.highlandparkwhisky.com/en-us/products/12-year-old-single-malt-whisky"],
  kilchoman: ["https://www.kilchomandistillery.com/our-whisky/machir-bay/", "https://www.kilchomandistillery.com/distillery_categories/slider/page/8/", "https://www.kilchomandistillery.com/distillery-news/sherry-to-sauternes-an-overview-of-kilchoman-casks/"],
  teremana: ["https://teremana.com/", "https://teremana.com/pages/tequila", "https://teremana.com/pages/our-story", "https://teremana.com/pages/programoffers"],
  teachers: ["https://www.teacherswhisky.com/our-story", "https://www.teacherswhisky.com/our-whiskies"],
  "royal-green": ["https://adsspirits.com/royal-green/", "https://adsdistilleries.com/view.php?name=Royal-Green"],
  "royal-stag": ["https://www.pernod-ricard.com/en/brands/royal-stag"],
  "bee-young": ["https://www.kimayahimalayan.com/", "https://www.kimayahimalayan.com/brands"],
  "bad-monkey": ["https://www.badmonkey.in/about/", "https://www.livcheers.com/delhi/liquor/bad-monkey-tamed-lager-beer-650ml"],
};

export const BRAND_LOGOS_BATCH_18: Record<string, string> = {
  bowmore: "https://static.livcheers.com/static/content/images/brand/bowmore.webp",
  bruichladdich: "https://www.bruichladdich.com/cdn/shop/t/96/assets/BDC-Roundel_150x.png?v=117978068751994032641709823457",
  "buffalo-trace": "https://static.livcheers.com/static/content/images/brand/buffalo-trace.webp",
  bulleit: "https://static.livcheers.com/static/content/images/brand/bulleit.webp",
  campari: "https://static.livcheers.com/static/content/images/brand/campari.webp",
  cointreau: "https://static.livcheers.com/static/content/images/brand/cointreau.webp",
  ciroc: "https://static.livcheers.com/static/content/images/brand/ciroc.webp",
  kahlua: "https://static.livcheers.com/static/content/images/brand/kahlua.webp",
  dalwhinnie: "https://static.livcheers.com/static/content/images/brand/dalwhinnie.webp",
  glenkinchie: "https://static.livcheers.com/static/content/images/brand/glenkinchie.webp",
  lagavulin: "https://static.livcheers.com/static/content/images/brand/lagavulin.webp",
  oban: "https://static.livcheers.com/static/content/images/brand/oban.webp",
  kilchoman: "https://www.kilchomandistillery.com/wp-content/uploads/2018/04/logo.svg",
  teremana: "https://static.livcheers.com/static/content/images/brand/teremana.webp",
  teachers: "https://static.livcheers.com/static/content/images/brand/teachers.webp",
  "royal-green": "https://static.livcheers.com/static/content/images/brand/royal-green.webp",
  "royal-stag": "https://static.livcheers.com/static/content/images/brand/royal-stag.webp",
  "bad-monkey": "https://www.badmonkey.in/wp-content/uploads/2024/01/cropped-BM-green-logo-Phone.png",
  "bee-young": "https://static.wixstatic.com/media/212f39_3181f693f440415c8e90914e1032e1d4~mv2.png/v1/fit/w_600,h_300,q_90/BEEYOUNG.png",
};

export const BRAND_CONTENT_BATCH_18: Record<string, BrandPublicContent> = {
  bowmore: {
    description: "Bowmore makes peated single malt Scotch beside Loch Indaal on Islay. Its core 12-year-old combines American ex-bourbon and European Oloroso sherry casks, setting lemon and honey against earthy smoke.",
    story: "Whisky production at Bowmore dates to 1779. The distillery's place on the shore of Loch Indaal has made the town and its single malt closely linked parts of Islay's whisky culture.",
    tastingNotes: [{ title: "12 Year Old: lemon and honey", description: "Fresh lemon and heather honey lead the aroma, with a soft earthy smokiness underneath." }, { title: "Fruit, chocolate and smoke", description: "The core 12-year-old brings warm fruit and dark chocolate before a lingering, sweetly smoky finish." }],
    howToEnjoy: [{ subheading: "A little water", description: "Use a tulip glass and add a few drops of water after the first taste to explore the citrus beneath the smoke." }, { subheading: "Food with some char", description: "Try tandoori prawns or mushroom seekh with the 12-year-old; a square of dark chocolate works after dinner." }],
    pairingIdeas: [{ title: "Smoky and savoury", items: ["tandoori prawns", "mushroom seekh", "smoked aubergine", "dark chocolate"] }],
    whyChoose: "Bowmore balances Islay peat with citrus and honey, giving smoke a supporting role alongside fruit.",
    faqs: [{ question: "Where is Bowmore whisky made?", answer: "Bowmore is made on Islay, at the distillery beside Loch Indaal in the town of Bowmore." }, { question: "Is Bowmore 12 smoky?", answer: "Yes, the core 12-year-old has earthy peat smoke, balanced by lemon, honey, fruit and dark chocolate." }],
    finalVerdict: "Bowmore suits a drinker who wants recognisable Islay smoke without losing the fruit and honey around it.",
    metaTitle: "Bowmore Single Malt Scotch Guide | BevOry",
    metaDescription: "Explore Bowmore's Islay origins, 12-year-old tasting notes, water serves and tandoori pairings. Check city prices on BevOry.",
  },
  bruichladdich: {
    description: "Bruichladdich is an Islay single malt range made without peat-smoked barley. Distilled, matured and bottled on the island, it puts barley character, flowers and fruit ahead of the smoke often associated with Islay.",
    story: "The distillery was built in 1881 and still uses traditional wooden washbacks. Its modern Barley Exploration releases examine the influence of grain provenance, including Islay-grown, organic and Bere barley.",
    tastingNotes: [{ title: "Floral malt", description: "The Classic Laddie expresses the range's floral, barley-led house style without a peat-smoke centre." }, { title: "Bourbon-cask sweetness", description: "Ex-bourbon maturation can bring vanilla, butterscotch and tropical fruit to Bruichladdich's unpeated spirit." }],
    howToEnjoy: [{ subheading: "Let the malt open", description: "Pour into a small tulip glass and try a few drops of water to soften the texture and open the aroma." }, { subheading: "Gentle seasoning", description: "Chicken malai tikka, mushroom tart and buttered scallops leave room for the floral malt rather than overwhelming it." }],
    pairingIdeas: [{ title: "For a floral malt", items: ["chicken malai tikka", "mushroom tart", "buttered scallops", "salted almonds"] }],
    whyChoose: "Bruichladdich shows an unpeated side of Islay through grain provenance and a floral, fruit-led spirit.",
    faqs: [{ question: "Is Bruichladdich peated?", answer: "Bruichladdich-branded single malts are unpeated; the same distillery's Port Charlotte and Octomore ranges are peated." }, { question: "What is Bruichladdich's Barley Exploration range?", answer: "It explores barley provenance through releases such as Islay Barley, Organic Barley and Bere Barley." }],
    finalVerdict: "Choose Bruichladdich for Islay whisky that gives barley, flowers and cask sweetness the space usually occupied by peat.",
    metaTitle: "Bruichladdich Single Malt Scotch Guide | BevOry",
    metaDescription: "Discover unpeated Bruichladdich, Islay barley, floral malt notes and malai tikka pairings. Check city prices on BevOry.",
  },
  "buffalo-trace": {
    description: "Buffalo Trace is a Kentucky straight bourbon made in Frankfort from corn, rye and malted barley. Maturation in new charred oak barrels gives the flagship whiskey its vanilla, toffee and dark-fruit character.",
    story: "The name recalls the buffalo paths that crossed Kentucky and helped guide early westward travel. One of those routes passed through the site now occupied by Buffalo Trace Distillery.",
    tastingNotes: [{ title: "Vanilla and mint", description: "Vanilla, mint and molasses form the aroma, with a sweet but herbal lift." }, { title: "Brown sugar and spice", description: "Brown sugar gives way to oak, toffee, dark fruit and anise, followed by a long finish." }],
    howToEnjoy: [{ subheading: "Neat or Old Fashioned", description: "Try a small neat pour in a rocks glass, or stir with bitters and a little sugar for an Old Fashioned." }, { subheading: "Roast and caramel", description: "Barbecue chicken, peppered paneer and pecan tart work with the bourbon's charred-oak sweetness." }],
    pairingIdeas: [{ title: "From grill to dessert", items: ["barbecue chicken", "peppered paneer", "pecan tart", "roasted walnuts"] }],
    whyChoose: "Buffalo Trace combines familiar bourbon sweetness with mint and anise that keep the flavour from becoming one-note.",
    faqs: [{ question: "Where is Buffalo Trace bourbon made?", answer: "It is made at Buffalo Trace Distillery in Frankfort, Kentucky." }, { question: "What grains are in Buffalo Trace bourbon?", answer: "The flagship bourbon uses corn, rye and malted barley." }],
    finalVerdict: "A rounded Kentucky bourbon with enough spice for an Old Fashioned and enough detail for a neat pour.",
    metaTitle: "Buffalo Trace Bourbon Guide | BevOry",
    metaDescription: "Meet Buffalo Trace bourbon from Kentucky, vanilla and mint notes, Old Fashioned serves and food pairings. Check city prices on BevOry.",
  },
  bulleit: {
    description: "Bulleit is an American whiskey brand whose Kentucky straight bourbon uses corn, rye and malted barley. A relatively high rye content gives the bourbon a spicy edge alongside maple, oak and toffee.",
    story: "Tom Bulleit established the Bulleit Distilling Company in 1987. The brand later opened its visitor experience in Shelbyville, Kentucky, in 2019, bringing its distilling story onto the Kentucky Bourbon Trail.",
    tastingNotes: [{ title: "Sweet oak aroma", description: "Bulleit Bourbon opens with sweet oak and gentle spice rather than a heavy, syrupy aroma." }, { title: "Maple and nutmeg", description: "Maple and nutmeg sit across a smooth middle, followed by a drier finish with light toffee." }],
    howToEnjoy: [{ subheading: "Stir, don't over-sweeten", description: "Use the bourbon in an Old Fashioned with restrained sugar, or serve over one large ice cube." }, { subheading: "Pepper and toasted spice", description: "Pepper chicken, mushroom pepper fry and aged cheddar make useful savoury matches for the rye spice." }],
    pairingIdeas: [{ title: "Spice-led matches", items: ["pepper chicken", "mushroom pepper fry", "aged cheddar", "pecan pie"] }],
    whyChoose: "Bulleit's rye-led spice gives its bourbon a firmer, drier outline than its sweet oak aroma first suggests.",
    faqs: [{ question: "Is Bulleit Bourbon the same as Bulleit Rye?", answer: "No, they are separate whiskeys; Bulleit Bourbon uses a corn-led grain recipe with a substantial rye component." }, { question: "What does Bulleit Bourbon taste like?", answer: "Expect sweet oak, maple and nutmeg, with a long, relatively dry toffee finish." }],
    finalVerdict: "Bulleit Bourbon is a good fit for drinkers who want maple sweetness held in check by rye spice and dry oak.",
    metaTitle: "Bulleit Bourbon Whiskey Guide | BevOry",
    metaDescription: "Explore Bulleit bourbon, Kentucky history, maple and nutmeg notes, cocktail serves and Indian pairings. Check city prices on BevOry.",
  },
  campari: {
    description: "Campari is the red Italian bitter aperitif created by Gaspare Campari. Orange and aromatic herbs give it a forceful bittersweet flavour that anchors drinks such as the Negroni and Americano.",
    story: "Gaspare developed Campari in 1860 and opened Caffe Campari in Milan's Galleria Vittorio Emanuele II in 1867. The business later moved production to Sesto San Giovanni in 1904 as demand grew.",
    tastingNotes: [{ title: "Orange and herbs", description: "Orange peel and aromatic herbs dominate the nose, with a lighter floral layer." }, { title: "Bitter, with a soft finish", description: "Firm bitterness carries orange and woody notes across a rounded texture, leaving a persistent herbal aftertaste." }],
    howToEnjoy: [{ subheading: "Soda or a stirred cocktail", description: "Lengthen with cold soda over ice and add orange, or stir with gin and sweet vermouth for a Negroni." }, { subheading: "Salt before dinner", description: "Serve alongside masala olives, potato croquettes, paneer tikka or tomato bruschetta." }],
    pairingIdeas: [{ title: "Aperitivo plates", items: ["masala olives", "potato croquettes", "paneer tikka", "tomato bruschetta"] }],
    whyChoose: "Campari supplies the bitter orange-and-herb backbone that keeps a sweet vermouth cocktail balanced.",
    faqs: [{ question: "Is Campari sweet or bitter?", answer: "It is bittersweet, with pronounced bitterness, orange, herbs and a rounded finish." }, { question: "Can Campari be served without gin?", answer: "Yes, Campari and soda is a simple long drink, while an Americano combines it with sweet vermouth and soda." }],
    finalVerdict: "Campari is for drinkers who enjoy a clear bitter edge, especially with soda or in a carefully balanced aperitif cocktail.",
    metaTitle: "Campari Italian Aperitif Guide | BevOry",
    metaDescription: "Explore Campari's Milan history, bitter orange tasting notes, Negroni serves and savoury pairings. Check city prices on BevOry.",
  },
  cointreau: {
    description: "Cointreau is a clear French orange liqueur from the house founded in Angers. Distilled sweet and bitter orange peels give it concentrated citrus aromas that work in a Margarita, Sidecar or simple soda serve.",
    story: "Adolphe Cointreau began the family liqueur business in 1849, with his brother Edouard-Jean joining later. The next generation, Edouard and Louisa, narrowed the house's focus to orange liqueur and built the identity around its square bottle.",
    tastingNotes: [{ title: "Sweet orange blossom", description: "Sweet orange peel brings juicy citrus and a floral impression of orange blossom." }, { title: "Zest and warm spice", description: "Bitter orange adds zesty freshness, bergamot and peppery spice, giving the sweetness a sharper outline." }],
    howToEnjoy: [{ subheading: "Fresh citrus cocktails", description: "Shake with tequila and fresh lime for a Margarita, or try a smaller measure with soda over ice." }, { subheading: "Orange-friendly dishes", description: "Pair an orange-led serve with tandoori prawns, roast duck or almond cake; dark chocolate works with a small neat pour." }],
    pairingIdeas: [{ title: "Citrus companions", items: ["tandoori prawns", "roast duck", "almond cake", "dark chocolate"] }],
    whyChoose: "Cointreau brings both sweet orange perfume and bitter-peel definition to citrus cocktails.",
    faqs: [{ question: "What is Cointreau made with?", answer: "Its flavour comes from a combination of sweet and bitter orange peels, including fresh and dried peels." }, { question: "Why is Cointreau clear rather than orange?", answer: "The orange peels are distilled to capture their aromas in a clear liqueur." }],
    finalVerdict: "Cointreau earns its place in a cocktail cupboard through concentrated orange flavour with enough peel bitterness to stay precise.",
    metaTitle: "Cointreau Orange Liqueur Guide | BevOry",
    metaDescription: "Discover Cointreau's Angers roots, sweet and bitter orange notes, Margarita serves and food pairings. Check city prices on BevOry.",
  },
  ciroc: {
    description: "Ciroc is a French vodka made from grapes rather than a grain base. Its fifth distillation takes place in a copper pot still, producing a soft texture and fresh citrus character.",
    story: "Master distiller Jean-Sebastien Robicquet developed Ciroc in the south of France, with the brand established in 2003. His background in winemaking and distillation shaped its grape-based approach at Maison Villevert.",
    tastingNotes: [{ title: "Fresh citrus", description: "The original vodka has a clean citrus impression, with freshness rather than heavy spice at the centre." }, { title: "Soft texture", description: "A smooth mouthfeel carries the restrained fruit character into a light, fresh finish." }],
    howToEnjoy: [{ subheading: "A cold, simple serve", description: "Serve chilled in a small glass, or combine with soda, lime and a few mint leaves over ice." }, { subheading: "Keep the food light", description: "Try lemon fish tikka, cucumber sushi rolls, smoked salmon or lightly salted almonds." }],
    pairingIdeas: [{ title: "Fresh and lightly seasoned", items: ["lemon fish tikka", "cucumber sushi rolls", "smoked salmon", "salted almonds"] }],
    whyChoose: "Ciroc offers a grape-based alternative to grain vodka with a soft texture and a citrus-led finish.",
    faqs: [{ question: "Is Ciroc made from grapes?", answer: "Yes, the original Ciroc vodka is distilled from French grapes." }, { question: "Who created Ciroc?", answer: "French master distiller Jean-Sebastien Robicquet developed Ciroc, which was established in 2003." }],
    finalVerdict: "Ciroc suits a chilled pour or light citrus highball where a soft vodka texture matters more than spice.",
    metaTitle: "Ciroc French Vodka Guide | BevOry",
    metaDescription: "Meet grape-based Ciroc vodka, French distilling roots, fresh citrus notes and light food pairings. Check city prices on BevOry.",
  },
  kahlua: {
    description: "Kahlua is a Mexican coffee liqueur made with Arabica coffee beans and rum. Its Original expression combines roasted coffee, vanilla and chocolate in a sweet, full-flavoured base for coffee cocktails.",
    story: "Kahlua began in Mexico in 1936 and is closely associated with Veracruz's coffee-growing culture. Its rum-and-coffee combination later became a defining ingredient in the Black Russian, White Russian and Espresso Martini.",
    tastingNotes: [{ title: "Roasted coffee", description: "Black-coffee flavour forms the centre of Kahlua Original, with a rich, rounded body." }, { title: "Vanilla and chocolate", description: "Vanilla, chocolate and a buttery sweetness soften the roasted notes, with a little spice underneath." }],
    howToEnjoy: [{ subheading: "Shake with fresh coffee", description: "Use freshly brewed, cooled espresso with vodka and Kahlua for an Espresso Martini, served in a chilled coupe." }, { subheading: "Small desserts", description: "Dark chocolate brownies, walnut cake and a modest portion of coffee kulfi complement the liqueur's roasted sweetness." }],
    pairingIdeas: [{ title: "After-dinner bites", items: ["dark chocolate brownie", "walnut cake", "coffee kulfi", "salted almonds"] }],
    whyChoose: "Kahlua brings real Arabica coffee and rum together in a liqueur with enough roasted depth for coffee cocktails.",
    faqs: [{ question: "Is Kahlua a coffee liqueur or a vodka?", answer: "Kahlua is a rum-and-coffee liqueur, not vodka; vodka is added separately in an Espresso Martini or White Russian." }, { question: "Does Kahlua contain real coffee?", answer: "Yes, Kahlua Original is made with Arabica coffee beans." }],
    finalVerdict: "Kahlua is a practical choice for coffee cocktails when you want roasted flavour as well as sweetness.",
    metaTitle: "Kahlua Coffee Liqueur Guide | BevOry",
    metaDescription: "Explore Kahlua's Veracruz roots, Arabica coffee tasting notes, Espresso Martini serves and dessert pairings. Check city prices on BevOry.",
  },
  dalwhinnie: {
    description: "Dalwhinnie is a Highland single malt Scotch from the Cairngorms. Its 15-year-old expression is known for heather honey, vanilla and citrus, followed by a quieter smoky warmth.",
    story: "The distillery was founded at the end of the nineteenth century in a cold, upland setting. Its name comes from a Gaelic term meaning meeting place, reflecting Dalwhinnie's position among Highland routes.",
    tastingNotes: [{ title: "Heather honey", description: "Dalwhinnie 15 has a crisp heather aroma and a soft, honeyed palate, with vanilla and a light-to-medium body." }, { title: "Citrus and malt", description: "Citrus and malted-bread notes follow the sweetness, while the long finish turns gently smoky and malty." }],
    howToEnjoy: [{ subheading: "Neat, then a little water", description: "Use a tulip glass and taste neat before adding a small splash of still water." }, { subheading: "Soft spice and nuts", description: "Chicken malai tikka, roasted almonds and a lightly sweet almond cake suit the honeyed profile." }],
    pairingIdeas: [{ title: "Gentle accompaniments", items: ["chicken malai tikka", "roasted almonds", "almond cake", "aged gouda"] }],
    whyChoose: "Dalwhinnie 15 pairs a honeyed Highland profile with just enough smoke to add depth without dominating.",
    faqs: [{ question: "Is Dalwhinnie a Highland whisky?", answer: "Yes, Dalwhinnie is a Highland single malt made in the Cairngorms in Scotland." }, { question: "Is Dalwhinnie 15 heavily peated?", answer: "Its character is led by heather honey, vanilla and citrus, with a gentler smoky finish rather than dominant peat." }],
    finalVerdict: "Dalwhinnie offers a soft, honey-led malt for drinkers who prefer their smoke in the background.",
    metaTitle: "Dalwhinnie Single Malt Scotch Guide | BevOry",
    metaDescription: "Discover Dalwhinnie Highland whisky, heather-honey tasting notes, simple serves and malai tikka pairings. Check city prices on BevOry.",
  },
  glenkinchie: {
    description: "Glenkinchie is a Lowland single malt made near Edinburgh in East Lothian. Large stills and traditional worm-tub cooling contribute to a whisky whose 12-year-old expression is floral, light and creamy.",
    story: "Known as the Edinburgh Malt, Glenkinchie takes its name from the nearby Kinchie Burn. Its Victorian redbrick buildings and former workers' houses preserve a visible link to the distillery's agricultural surroundings.",
    tastingNotes: [{ title: "Blossom and vanilla", description: "The 12-year-old opens with blossom, vanilla and a lightly toasted note, developing a lemon-cheesecake aroma." }, { title: "Creamy citrus", description: "Soft custard and lemon flavours sit in a light body before a herbal, drying finish." }],
    howToEnjoy: [{ subheading: "A small pre-dinner pour", description: "Serve the 12-year-old in a tulip glass, adding a few drops of water to explore its creamier notes." }, { subheading: "Seafood and soft spice", description: "Try prawn tempura, lemon fish tikka or scallops; a plain madeleine is a gentle sweet pairing." }],
    pairingIdeas: [{ title: "Light plates", items: ["prawn tempura", "lemon fish tikka", "buttered scallops", "plain madeleines"] }],
    whyChoose: "Glenkinchie offers floral Lowland malt with a creamy lemon character instead of a heavily smoky profile.",
    faqs: [{ question: "Why is Glenkinchie called the Edinburgh Malt?", answer: "Its distillery is in East Lothian, around fifteen miles from Edinburgh." }, { question: "What does Glenkinchie 12 taste like?", answer: "It combines blossom, vanilla and creamy lemon notes with a light body and a dry, herbal finish." }],
    finalVerdict: "Glenkinchie is an appealing choice for a light, floral single malt beside seafood or before dinner.",
    metaTitle: "Glenkinchie Single Malt Scotch Guide | BevOry",
    metaDescription: "Meet Glenkinchie from East Lothian, floral and creamy lemon notes, serving ideas and seafood pairings. Check city prices on BevOry.",
  },
  lagavulin: {
    description: "Lagavulin is a heavily peated single malt Scotch from southern Islay. Its established 16-year-old expression combines dry smoke, maritime aromas and a deeper sweetness shaped by oak maturation.",
    story: "Peter Mackie's involvement from 1887 helped shape Lagavulin's place in Scotch whisky. The distillery became closely associated with Islay's full-bodied, smoky style, with the 16-year-old serving as a familiar introduction to that character.",
    tastingNotes: [{ title: "Smoke and seaweed", description: "Lagavulin 16 has a powerful peat-smoke aroma, with iodine, seaweed and a deep sweet note." }, { title: "Dry peat and salt", description: "Dry smoke spreads across the palate before salt and wood emerge; the finish stays long, smoky and maritime." }],
    howToEnjoy: [{ subheading: "Give the smoke room", description: "Serve a small measure in a tulip glass and let it rest briefly; a few drops of water can soften the intensity." }, { subheading: "Match the intensity", description: "Smoked mutton seekh, charred aubergine and blue cheese can stand up to the peat, while dark chocolate offers contrast." }],
    pairingIdeas: [{ title: "Bold flavours", items: ["smoked mutton seekh", "charred aubergine", "blue cheese", "dark chocolate"] }],
    whyChoose: "Lagavulin 16 gives peat lovers sustained smoke and maritime depth without abandoning a sweet centre.",
    faqs: [{ question: "Is Lagavulin a smoky whisky?", answer: "Yes, peat smoke is central to Lagavulin, especially its 16-year-old single malt." }, { question: "Where does Lagavulin come from?", answer: "It is made on the south coast of Islay in Scotland." }],
    finalVerdict: "Lagavulin is a deliberate choice for a drinker who enjoys pronounced peat, salt and a long, dry finish.",
    metaTitle: "Lagavulin Single Malt Scotch Guide | BevOry",
    metaDescription: "Explore Lagavulin from Islay, 16-year-old smoke and seaweed notes, water serves and bold food pairings. Check city prices on BevOry.",
  },
  oban: {
    description: "Oban is a West Highland single malt made in the Scottish coastal town of the same name. Malted barley and lamp-glass-shaped stills produce a substantial spirit with fruit, spice and a maritime edge.",
    story: "Hugh and John Stevenson began distilling at Oban in 1794, before the surrounding town developed. The distillery remains within the town that grew around it, close to the harbour on the Firth of Lorn.",
    tastingNotes: [{ title: "14 Year Old: fruit and orange", description: "Orchard fruit, nutty cake and orange sit above malt, with traces of brine and smoke." }, { title: "Clove and green apple", description: "The 14-year-old has a coating texture, with fruit bread, orange zest and clove turning towards green apple and drying spice." }],
    howToEnjoy: [{ subheading: "Room for the texture", description: "Taste neat in a small glass, then add a little cool water to open the fruit and ease the dense mouthfeel." }, { subheading: "Coastal dishes", description: "Grilled prawns, fish tikka and smoked salmon work with the coastal notes; aged cheddar suits the maltier side." }],
    pairingIdeas: [{ title: "Harbour-side flavours", items: ["grilled prawns", "fish tikka", "smoked salmon", "aged cheddar"] }],
    whyChoose: "Oban combines Highland fruit and spice with restrained coastal smoke in a notably full-textured malt.",
    faqs: [{ question: "Is Oban an Islay whisky?", answer: "No, Oban is a West Highland single malt from the mainland town of Oban." }, { question: "Did the Oban distillery come before the town?", answer: "Yes, the Stevenson brothers began distilling in 1794 and the town developed around the distillery and harbour." }],
    finalVerdict: "Oban suits a drinker seeking fruit and body with a coastal edge, rather than an overwhelmingly peaty whisky.",
    metaTitle: "Oban Single Malt Scotch Guide | BevOry",
    metaDescription: "Explore Oban's coastal Highland history, 14-year-old fruit and spice notes, serving ideas and pairings. Check city prices on BevOry.",
  },
  "highland-park": {
    description: "Highland Park is an Orkney single malt Scotch shaped by local heathered peat and sherry-seasoned oak casks. Its 12-year-old expression balances orange, honey and fruitcake with a restrained smoky finish.",
    story: "The distillery traces its history to 1798 on Orkney. Peat from Hobbister Moor contains the heather that grows across the island's exposed landscape, giving Highland Park its particular aromatic smoke.",
    tastingNotes: [{ title: "Orange and heather honey", description: "Highland Park 12 combines Seville orange zest with heather-honey sweetness." }, { title: "Fruitcake and gentle smoke", description: "Spiced fruitcake brings warmth to the middle before subtle heathered peat smoke lingers on the finish." }],
    howToEnjoy: [{ subheading: "Neat or gently diluted", description: "Try the 12-year-old in a tulip glass, then add a few drops of water to explore the orange and spice." }, { subheading: "Warm spice at dinner", description: "Mutton seekh, roasted mushrooms and aged cheddar match the smoke; fruitcake echoes the cask-led flavours." }],
    pairingIdeas: [{ title: "Savoury and spiced", items: ["mutton seekh", "roasted mushrooms", "aged cheddar", "spiced fruitcake"] }],
    whyChoose: "Highland Park's heathered peat lends aromatic smoke to a malt that also makes room for orange and honey.",
    faqs: [{ question: "Where is Highland Park whisky made?", answer: "It is made on Orkney, the island group off Scotland's north coast." }, { question: "Is Highland Park 12 peated?", answer: "Yes, it has a subtle heathered peat-smoke character alongside orange, honey and fruitcake." }],
    finalVerdict: "Highland Park 12 offers a measured balance of honey, spice and smoke for drinkers who enjoy all three.",
    metaTitle: "Highland Park Single Malt Scotch Guide | BevOry",
    metaDescription: "Discover Highland Park's Orkney peat, orange and honey tasting notes, simple serves and food pairings. Check city prices on BevOry.",
  },
  kilchoman: {
    description: "Kilchoman is a peated Islay single malt distillery founded by Anthony and Kathy Wills. Its Machir Bay expression combines bourbon- and sherry-cask whisky, bringing fresh citrus and tropical fruit through maritime smoke.",
    story: "Anthony and Kathy established Kilchoman in 2005, with its first cask filled that December. Machir Bay takes its name from the nearby Islay beach, connecting a core whisky to the island's western coast.",
    tastingNotes: [{ title: "Machir Bay: lemon and vanilla", description: "Lemon zest and vanilla open into peach, pear and floral notes with a coastal edge." }, { title: "Tropical fruit and peat", description: "Tropical fruit, sultanas and butterscotch meet warming smoke, followed by black pepper, sea salt and lingering citrus." }],
    howToEnjoy: [{ subheading: "Explore the fruit beneath peat", description: "Pour Machir Bay into a tulip glass and add a few drops of water after tasting it neat." }, { subheading: "Smoke with fresh acidity", description: "Tandoori prawns with lime, smoked aubergine and grilled pineapple balance the whisky's smoky sweetness." }],
    pairingIdeas: [{ title: "Char, salt and citrus", items: ["tandoori prawns with lime", "smoked aubergine", "grilled pineapple", "aged cheddar"] }],
    whyChoose: "Kilchoman keeps bright fruit visible beneath substantial Islay peat, especially in bourbon-led Machir Bay.",
    faqs: [{ question: "Who founded Kilchoman?", answer: "Anthony and Kathy Wills founded Kilchoman on Islay in 2005." }, { question: "What casks are used for Kilchoman Machir Bay?", answer: "Machir Bay combines bourbon- and sherry-cask maturation, with bourbon barrels making up the larger share." }],
    finalVerdict: "Kilchoman is for peat drinkers who also want lemon, tropical fruit and a lively coastal finish.",
    metaTitle: "Kilchoman Single Malt Scotch Guide | BevOry",
    metaDescription: "Meet Kilchoman from Islay, Machir Bay citrus and peat notes, distillery history and tandoori pairings. Check city prices on BevOry.",
  },
  teremana: {
    description: "Teremana is a tequila made at Destileria Teremana de Agave in Mexico's Jalisco Highlands. Blue Weber agave is roasted in brick ovens, fermented in open tanks and distilled in handmade copper pot stills.",
    story: "Founded by Dwayne Johnson, Teremana takes its name from the idea of the spirit of the earth. The distillery uses locally made copper stills and composts leftover agave fibres for use in the fields.",
    tastingNotes: [{ title: "Blanco: bright citrus", description: "Teremana Blanco centres on bright citrus with a fresh, smooth finish." }, { title: "Reposado: oak and vanilla", description: "American whiskey-barrel maturation gives Reposado a richer oak-and-vanilla profile." }],
    howToEnjoy: [{ subheading: "Choose the serve by style", description: "Use Blanco with fresh lime in a Margarita; try Reposado neat in a small glass or over one ice cube." }, { subheading: "Agave at the table", description: "Fish tacos, tandoori prawns, roasted corn and achari paneer suit the citrus and cooked-agave setting." }],
    pairingIdeas: [{ title: "For Blanco or Reposado", items: ["fish tacos", "tandoori prawns", "roasted corn", "achari paneer"] }],
    whyChoose: "Teremana offers a clear contrast between citrus-led Blanco and oak-rounded Reposado, with brick-oven agave at their core.",
    faqs: [{ question: "Where is Teremana made?", answer: "Teremana is made at Destileria Teremana de Agave in the Jalisco Highlands of Mexico." }, { question: "How do Teremana Blanco and Reposado differ?", answer: "Blanco emphasises fresh citrus, while Reposado adds oak and vanilla through maturation in American whiskey barrels." }],
    finalVerdict: "Teremana makes sense for fresh-lime cocktails or a softer oak-led pour, depending on the expression you choose.",
    metaTitle: "Teremana Tequila Guide | BevOry",
    metaDescription: "Discover Teremana's Jalisco agave, Blanco and Reposado tasting notes, Margarita serves and food pairings. Check city prices on BevOry.",
  },
  teachers: {
    description: "Teacher's is a blended Scotch whisky whose Highland Cream uses peated Ardmore single malt as a defining component. Malt, orchard fruit and honey sit around a warm smoky centre.",
    story: "William Teacher began selling whisky from a Glasgow grocer's shop in 1830. He went on to establish dram shops, and Highland Cream emerged in the 1860s as his own blend of malt and grain whiskies.",
    tastingNotes: [{ title: "Malt and Highland smoke", description: "Highland Cream begins with robust malt and a gentle peat-smoke aroma." }, { title: "Apple, pear and honey", description: "Apple, pear and honey become more apparent as the smoky opening settles into a rounded, warming texture." }],
    howToEnjoy: [{ subheading: "A measured highball", description: "Serve with cold soda and plenty of ice in a tall glass, or taste neat with a small splash of water." }, { subheading: "Tandoor flavours", description: "Mutton seekh, tandoori mushrooms and pepper chicken give the malt and smoke a savoury companion." }],
    pairingIdeas: [{ title: "For the smoky malt", items: ["mutton seekh", "tandoori mushrooms", "pepper chicken", "aged cheddar"] }],
    whyChoose: "Teacher's Highland Cream places recognisable peated malt at the centre of a rounded Scotch blend.",
    faqs: [{ question: "Does Teacher's Highland Cream contain cream?", answer: "It is a blended Scotch whisky, not a dairy cream liqueur." }, { question: "Which distillery gives Teacher's its smoky character?", answer: "Peated single malt from Ardmore is a defining component of Highland Cream." }],
    finalVerdict: "Teacher's suits a smoky Scotch highball or a simple rocks pour with malt and orchard fruit still in focus.",
    metaTitle: "Teacher's Blended Scotch Whisky Guide | BevOry",
    metaDescription: "Explore Teacher's Glasgow origins, Ardmore malt, smoky tasting notes, highball serves and food pairings. Check city prices on BevOry.",
  },
  "royal-green": {
    description: "Royal Green is an Indian blended whisky from ADS Spirits, combining Indian grain spirit with imported Scotch malts. Grass, vanilla and cinnamon on the nose lead into a medium-bodied, fruit-and-oak palate.",
    story: "Royal Green built its identity around a distinctive green bottle and early launches in Haryana and Delhi. A redesigned bottle followed in 2022 as the brand expanded beyond its initial markets.",
    tastingNotes: [{ title: "Grass, malt and spice", description: "Freshly cut grass, malt, vanilla and cinnamon shape the opening aroma." }, { title: "Fruit and gentle oak", description: "The medium-bodied palate combines fruit and vanilla with a little oak, finishing with spice and a touch of peat." }],
    howToEnjoy: [{ subheading: "Water or cold soda", description: "Try a small pour with water, or build a simple highball with cold soda and ice." }, { subheading: "A savoury spread", description: "Paneer tikka, mutton seekh and mushroom pepper fry complement the whisky's malt and spice." }],
    pairingIdeas: [{ title: "Indian dinner plates", items: ["paneer tikka", "mutton seekh", "mushroom pepper fry", "roasted almonds"] }],
    whyChoose: "Royal Green offers a medium-bodied Indian blend with distinct vanilla, fruit and warming spice rather than heavy sweetness.",
    faqs: [{ question: "Who makes Royal Green whisky?", answer: "Royal Green is made by ADS Spirits in India." }, { question: "Is Royal Green a Scotch whisky?", answer: "It is an Indian blended whisky that combines Indian grain spirit with imported Scotch malts." }],
    finalVerdict: "Royal Green works as a straightforward soda or water serve for drinkers who enjoy malt, vanilla and light spice.",
    metaTitle: "Royal Green Indian Whisky Guide | BevOry",
    metaDescription: "Meet Royal Green by ADS Spirits, vanilla and cinnamon tasting notes, simple serves and Indian pairings. Check city prices on BevOry.",
  },
  "royal-stag": {
    description: "Royal Stag is an Indian whisky blending Indian grain spirits with imported Scotch malts. The Deluxe expression has a woody, fruity character with a light smoky touch, while Barrel Select adds an oak-matured option.",
    story: "Royal Stag launched in 1995 and became part of Pernod Ricard in 2001. Its grain-spirit and Scotch-malt blend helped establish the brand's place in India's whisky market.",
    tastingNotes: [{ title: "Deluxe: wood and fruit", description: "Royal Stag Deluxe combines woody notes with fruit in a rounded profile." }, { title: "A light smoky touch", description: "A restrained smoke note sits behind Deluxe's fruit and wood rather than dominating the flavour." }],
    howToEnjoy: [{ subheading: "Keep the mixer simple", description: "Serve Deluxe with water or cold soda over ice so the fruit and light smoke remain noticeable." }, { subheading: "Tikka and kebabs", description: "Try paneer tikka, chicken seekh or tandoori mushrooms; roasted peanuts make a simpler accompaniment." }],
    pairingIdeas: [{ title: "Familiar savoury plates", items: ["paneer tikka", "chicken seekh", "tandoori mushrooms", "roasted peanuts"] }],
    whyChoose: "Royal Stag Deluxe offers an Indian grain-and-malt blend with an uncomplicated balance of fruit, wood and light smoke.",
    faqs: [{ question: "Is Royal Stag an Indian whisky?", answer: "Yes, Royal Stag blends Indian grain spirits with imported Scotch malts." }, { question: "How are Royal Stag Deluxe and Barrel Select different?", answer: "Deluxe has a woody, fruity profile with light smoke; Barrel Select is a separate blend matured in selected oak barrels." }],
    finalVerdict: "Royal Stag Deluxe suits a simple highball when you want a rounded whisky with fruit and a little smoke.",
    metaTitle: "Royal Stag Indian Whisky Guide | BevOry",
    metaDescription: "Explore Royal Stag's Indian origins, Deluxe tasting notes, Barrel Select, soda serves and tikka pairings. Check city prices on BevOry.",
  },
  "bee-young": {
    description: "BeeYoung is an Indian strong lager from Kimaya Himalayan Beverages. Its crisp opening develops into malt and ripe fruit, giving it more flavour weight than a neutral light lager.",
    story: "Kimaya developed BeeYoung as the strong-lager side of a portfolio that also includes Yavira basmati pilsner. The two beers reflect the company's focus on giving familiar Indian beer styles more individual identities.",
    tastingNotes: [{ title: "Crisp malt", description: "BeeYoung opens crisply, with malt becoming the main flavour through the first sip." }, { title: "Ripe fruit", description: "A ripe-fruit character develops across the middle, adding roundness to the lager profile." }],
    howToEnjoy: [{ subheading: "Chilled, in a clean glass", description: "Pour chilled into a clean lager glass, leaving room for a modest head rather than serving it partly frozen." }, { subheading: "Crisp fried food", description: "Onion pakoras, chilli paneer and fish fry suit the combination of crispness and malt." }],
    pairingIdeas: [{ title: "With a savoury snack", items: ["onion pakoras", "chilli paneer", "fish fry", "masala peanuts"] }],
    whyChoose: "BeeYoung combines the body of a strong lager with a crisp opening and a noticeable ripe-fruit middle.",
    faqs: [{ question: "Who makes BeeYoung beer?", answer: "BeeYoung is made by Kimaya Himalayan Beverages in India." }, { question: "Is BeeYoung a wheat beer?", answer: "BeeYoung's core beer is a strong lager, with a crisp, malty and ripe-fruit profile." }],
    finalVerdict: "BeeYoung is a flavour-led strong lager to pair with pakoras, chilli paneer or a freshly cooked fish fry.",
    metaTitle: "BeeYoung Indian Beer Guide | BevOry",
    metaDescription: "Meet BeeYoung strong lager from Kimaya, crisp malt and ripe-fruit notes, chilled serves and Indian pairings. Check city prices on BevOry.",
  },
  "bad-monkey": {
    description: "Bad Monkey is an Indian beer brand from Sinq Beverage, founded by Rohan Khare. Its range includes strong beer and Tamed Lager, with barley and hops forming the brewing base.",
    story: "Khare brought experience in beverage product development to the creation of Bad Monkey. The brewery combines barley and hops sourced from Europe and North America with Himalayan-sourced water, building the brand around Indian beer drinkers.",
    tastingNotes: [{ title: "Tamed Lager: toasted malt", description: "Tamed Lager has a light toasted-malt character and a restrained sweetness." }, { title: "Citrus and a clean finish", description: "A subtle citrus note runs through Tamed Lager's lighter body, ending cleanly rather than with heavy caramel." }],
    howToEnjoy: [{ subheading: "A chilled lager pour", description: "Serve Tamed Lager chilled in a clean beer glass, pouring steadily to keep a small head." }, { subheading: "Crisp snacks", description: "Fish fingers, onion bhajis, paneer tikka and salted potato wedges fit its lighter malt character." }],
    pairingIdeas: [{ title: "For Tamed Lager", items: ["fish fingers", "onion bhajis", "paneer tikka", "salted potato wedges"] }],
    whyChoose: "Bad Monkey Tamed Lager offers toasted malt and a clean finish for drinkers seeking a lighter-bodied beer within the range.",
    faqs: [{ question: "Who owns Bad Monkey beer?", answer: "Bad Monkey is a brand of Sinq Beverage, founded by Rohan Khare." }, { question: "Is every Bad Monkey beer a strong beer?", answer: "The range includes strong beer as well as Tamed Lager, a separate lighter-bodied lager expression." }],
    finalVerdict: "Tamed Lager is the Bad Monkey expression to consider for a lighter malt profile alongside fried or tandoori snacks.",
    metaTitle: "Bad Monkey Indian Beer Guide | BevOry",
    metaDescription: "Discover Bad Monkey beer, Sinq origins, Tamed Lager tasting notes, chilled serves and Indian snack pairings. Check city prices on BevOry.",
  },
};
