import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_20 = [
  ["bols", "Bols", "Netherlands", "Liqueur", "d5a6bb426783849bf1cbaa14"],
  ["corona", "Corona", "Mexico", "Beer", "8ec3e99ade3055c2b616ee75"],
  ["drambuie", "Drambuie", "Scotland", "Liqueur", "09c190e7c79bb36b6cc90f19"],
  ["fernet-branca", "Fernet-Branca", "Italy", "Liqueur", "8d2d2e8547dba45930d152a8"],
  ["finlandia", "Finlandia", "Finland", "Vodka", "c4b8bef691d04a753e9d227d"],
  ["fireball", "Fireball", "Canada", "Flavoured Whisky", "d81bc59a7f48ef98c648c68e"],
  ["glenfarclas", "Glenfarclas", "Scotland", "Single Malt Scotch", "1ebebcbfd6ed1410536c50f5"],
  ["gordons", "Gordon's", "United Kingdom", "Gin", "a6a0afe5a1d9dfbef463c54c"],
  ["guinness", "Guinness", "Ireland", "Stout", "8879addeb18c6b29e8b89960"],
  ["hapusa", "Hapusa", "India", "Gin", "314c24886b8cbb3473becdfc"],
  ["heineken", "Heineken", "Netherlands", "Beer", "8dbb1fe7268af062c8355080"],
  ["malibu", "Malibu", "Barbados", "Coconut Rum Liqueur", "5f16c3e2f49a617db5d9b49a"],
  ["martell", "Martell", "France", "Cognac", "e8cb8cf1908d87ab83958f14"],
  ["miller", "Miller", "United States", "Beer", "d2641888ed6426afd3d36490"],
  ["old-forester", "Old Forester", "United States", "Bourbon", "9de9e6ba8853713577bb201a"],
  ["old-pulteney", "Old Pulteney", "Scotland", "Single Malt Scotch", "202a354752293f91af8850fc"],
  ["old-smuggler", "Old Smuggler", "Scotland", "Blended Scotch", "209dae17947ea4140ff761d7"],
  ["peroni", "Peroni", "Italy", "Beer", "87b72f1ab81e8e2f327a299d"],
  ["pimms", "Pimm's", "United Kingdom", "Fruit Cup", "f542f2e14f998d7556d2b3fd"],
  ["rampur", "Rampur", "India", "Single Malt Whisky", "58e9b2a552a040bff7c0af29"],
  ["ricard", "Ricard", "France", "Pastis", "2e813ac225b6ccc90cb9118e"],
  ["skyy", "SKYY", "United States", "Vodka", "afd60bfdab49bae2c0ffd65c"],
  ["stolichnaya", "Stolichnaya", "Latvia", "Vodka", "b6501fb5f44fa87bd3d76567"],
  ["teeling", "Teeling", "Ireland", "Irish Whiskey", "69d2db887c8bf4b2446ea37f"],
  ["titos", "Tito's", "United States", "Vodka", "63fcc12dcc69cb9393f28507"],
  ["wild-turkey", "Wild Turkey", "United States", "Bourbon", "03bc96c0abe66f58e5455a54"],
  ["william-fevre", "William Fèvre", "France", "Wine", "2dee9daa5ae7512f333a6697"],
  ["woodford", "Woodford Reserve", "United States", "Bourbon", "48ef4cc1cb686d9b8c3f4e18"],
  ["yamazaki", "Yamazaki", "Japan", "Japanese Whisky", "56877aab9e1365c49bc8bd85"],
  ["zubrowka", "Żubrówka", "Poland", "Vodka", "7ac8634f8a22580be3b7e6f6"],
] as const;

// Review-only evidence; these URLs are never rendered in public editorial fields.
export const BRAND_SOURCES_BATCH_20: Record<string, string[]> = {
  bols: ["https://bols.com/pages/bols-heritage"],
  corona: ["https://www.corona.com/es/node/776", "https://www.grupomodelo.com/quienes-somos"],
  drambuie: ["https://drambuie.com/en-gb/about-us/"],
  "fernet-branca": ["https://www.fernetbranca.com/en/fernet-branca-world/an-amaro-that-will-make-history"],
  finlandia: ["https://www.finlandia.com/en/about"],
  fireball: ["https://www.fireballwhisky.com/faqs.html"],
  glenfarclas: ["https://glenfarclas.com/family/", "https://glenfarclas.com/production/"],
  gordons: ["https://www.thebar.com/en-gb/products/gordons-london-dry-gin-70cl"],
  guinness: ["https://www.guinness.com/en-gb/our-craft/guinness-story"],
  hapusa: ["https://naospirits.com/"],
  heineken: ["https://www.heineken.com/nl/nl/historie"],
  malibu: ["https://www.pernod-ricard.com/en", "https://www.pernod-ricard.com/sites/default/files/news/downloads/2024-12/Malibu%20DDAD%20-%20UK%20Trade%20Press%20Release%20-%20Final%20%28002%29.pdf"],
  martell: ["https://www.martell.com/en-us/faq/", "https://digitalpressroom.martell.com/the-house/"],
  miller: ["https://www.millerhighlife.com/"],
  "old-forester": ["https://www.oldforester.com/our-legacy/"],
  "old-pulteney": ["https://oldpulteney.com/pages/our-craft"],
  "old-smuggler": ["https://www.camparigroup.com/sites/default/files/attachments/acquisitions/Microsoft%20PowerPoint%20-%20Present%20Glen%20Grant%20Dec2005%20Final.pdf", "https://www.shawross.com/portfolio-of-products/spirits/old-smuggler-scotch-whisky/"],
  peroni: ["https://www.peroninastroazzurro.it/chi-siamo", "https://archiviostorico.birraperoni.it/percorsi/momenti-istituzionali"],
  pimms: ["https://www.thebar.com/en-gb/brands/pimms"],
  rampur: ["https://radicokhaitan.com/products/rampur-indian-single-malt-whisky/"],
  ricard: ["https://www.ricard.com/pastisologie"],
  skyy: ["https://www.skyyvodka.com/our-history/"],
  stolichnaya: ["https://stoli-group.com/portfolio/stoli-vodka/", "https://stoli.com/en-gl/about"],
  teeling: ["https://www.teelingwhiskey.com/our-story/", "https://www.teelingwhiskey.com/teeling-whiskeys/small-batch-whiskey/"],
  titos: ["https://www.titosvodka.com/about/timeline", "https://www.titosvodka.com/contact-faqs"],
  "wild-turkey": ["https://www.wildturkeybourbon.com/our-heritage/"],
  "william-fevre": ["https://www.williamfevre.fr/en/since-1959/a-prestigious-domain/", "https://www.williamfevre.fr/en/since-1959/irresistible-chablis/"],
  woodford: ["https://www.woodfordreserve.com/our-story/", "https://www.woodfordreserve.com/lifestyle/conducting-a-tasting/"],
  yamazaki: ["https://house.suntory.com/yamazaki-whisky/yamazaki-distillery", "https://house.suntory.com/yamazaki-whisky/yamazaki-distillers-reserve"],
  zubrowka: ["https://zubrowka.com/en/about-us/"],
};

// Only exact, accessible image identities belonging to rows with a blank live logo are listed here.
export const BRAND_LOGOS_BATCH_20: Record<string, string> = {
  bols: "https://bols.com/cdn/shop/files/Bols_est.1575_logo_2026_Blue.png?width=400",
  drambuie: "https://www.williamgrant.com/assets/OurBrands/DRAMBUIE_LOGO_FULL_COLOUR_CMYK-v2-50.png",
  "fernet-branca": "https://www.fernetbranca.com/wp-content/uploads/2017/06/logo_black-1.png",
  finlandia: "https://hu.coca-colahellenic.com/content/dam/cch/hu/images/products/Finlandia%20logo.png",
  martell: "https://www.pernod-ricard.com/sites/default/files/2021-06/martell_logo_600.jpeg",
  "old-forester": "https://www.oldforester.com/wp-content/uploads/2019/06/old-forester-logo-card.png",
  ricard: "https://www.pernod-ricard.com/sites/default/files/2021-04/brand-ricard-logo-600px.png",
  titos: "https://titos-next.transforms.svdcdn.com/production/images/brand-assets/logo-pack.png?auto=format&dm=1743794658&fit=min&h=480&q=90&s=e04e71551b10da5d5b8b7d79c7424878&w=855",
  "william-fevre": "https://www.lafite.com/wp-content/uploads/2025/10/Logo-WF-circulaire.svg",
  zubrowka: "https://zubrowka.com/wp-content/themes/zubrowka/dist/assets/images/logo.svg",
};

export const BRAND_CONTENT_BATCH_20: Record<string, BrandPublicContent> = {
  bols: {
    description: "Bols began as an Amsterdam distillery and now makes Dutch genever, liqueurs and cocktail spirits. Its range runs from malt-led genever to fruit and citrus liqueurs, rather than one uniform flavour.",
    story: "The Bols family established 't Lootsje in 1575. Lucas Bols later expanded the family's recipes, and the name travelled with genever into early American cocktail bars.",
    tastingNotes: [{ title: "Bols Genever", description: "Malt wine brings a rounded grain note beneath the juniper." }, { title: "Bols Blue Curaçao", description: "Sweet orange peel gives this liqueur its citrus-led character." }],
    howToEnjoy: [{ subheading: "In the glass", description: "Use genever in a small tulip glass or a classic Collins; reserve Blue Curaçao for mixed drinks where its orange flavour belongs." }, { subheading: "Alongside", description: "Orange-led cocktails suit chilli paneer, while genever sits well with smoked fish or salted almonds." }],
    pairingIdeas: [{ title: "At the table", items: ["chilli paneer", "smoked fish", "salted almonds", "orange-dark chocolate"] }],
    whyChoose: "Few cocktail labels connect old Amsterdam genever and modern fruit liqueurs so directly.",
    faqs: [{ question: "Where did Bols begin?", answer: "The Bols family founded its distillery in Amsterdam in 1575." }, { question: "Is Bols only a liqueur brand?", answer: "No. It also makes genever, the Dutch juniper spirit closely tied to early cocktail history." }],
    finalVerdict: "Pick the Bols expression for the drink: malt-led genever and bright orange liqueur play very different roles.",
    metaTitle: "Bols Genever & Liqueur Guide | BevOry",
    metaDescription: "Explore Bols genever and liqueurs from Amsterdam, with serving ideas and food pairings. Check city prices on BevOry.",
  },
  corona: {
    description: "Corona is a Mexican beer brand best known for Corona Extra, a light, pale lager. Its crisp finish and familiar clear bottle make it a common choice for citrus-led, warm-weather serves.",
    story: "Grupo Modelo began brewing in Mexico in 1925, the year Corona traces its origins to. Its clear bottle and beach imagery later carried the lager far beyond its home market.",
    tastingNotes: [{ title: "Pale malt", description: "A light cereal sweetness forms the first impression." }, { title: "Crisp finish", description: "Gentle hop bitterness keeps the lager refreshing." }],
    howToEnjoy: [{ subheading: "Cold and simple", description: "Serve well chilled from the bottle or in a narrow beer glass; add a lime wedge only if you like a sharper finish." }, { subheading: "With spice", description: "Fish tacos, tandoori prawns and green-chilli corn all work with its restrained bitterness." }],
    pairingIdeas: [{ title: "Bright plates", items: ["tandoori prawns", "fish tacos", "green-chilli corn", "salted nachos"] }],
    whyChoose: "Corona Extra gives a spicy meal a light, easy-drinking Mexican lager rather than a heavy malt profile.",
    faqs: [{ question: "What kind of beer is Corona Extra?", answer: "It is a pale Mexican lager." }, { question: "Does Corona need lime?", answer: "No. Lime is an optional serving choice, not part of the beer." }],
    finalVerdict: "A chilled Corona Extra is most useful when the food is salty, spicy or rich in lime.",
    metaTitle: "Corona Mexican Beer Guide | BevOry",
    metaDescription: "Meet Corona Extra's light lager style, lime serve and spicy-food pairings. Check city prices on BevOry.",
  },
  drambuie: {
    description: "Drambuie is a Scottish liqueur made with aged Scotch whisky, heather honey, herbs and spices. Whisky gives it structure; the honey supplies a soft, lingering sweetness.",
    story: "The brand traces its recipe to the eighteenth-century story of Bonnie Prince Charlie and the Isle of Skye. Its Gaelic name is commonly rendered as 'the drink that satisfies'.",
    tastingNotes: [{ title: "Heather honey", description: "Honey sweetness arrives first, with an aromatic herbal edge." }, { title: "Whisky and spice", description: "The aged Scotch base adds warmth under the liqueur's spiced finish." }],
    howToEnjoy: [{ subheading: "Over ice", description: "Pour a small measure over one large cube, or pair it with Scotch in a Rusty Nail." }, { subheading: "After dinner", description: "Dark chocolate, roasted figs or saffron phirni give the honeyed spirit something substantial to meet." }],
    pairingIdeas: [{ title: "Sweet and savoury", items: ["saffron phirni", "dark chocolate", "roasted figs", "aged cheddar"] }],
    whyChoose: "Drambuie keeps its Scotch whisky backbone even when the honey and herbs take the lead.",
    faqs: [{ question: "What is Drambuie made with?", answer: "Its maker describes aged Scotch whisky, heather honey, herbs and spices." }, { question: "What is a Rusty Nail?", answer: "A short cocktail made by combining Drambuie with Scotch whisky." }],
    finalVerdict: "Choose Drambuie when you want a whisky-based after-dinner drink with honey rather than cream.",
    metaTitle: "Drambuie Scotch Liqueur Guide | BevOry",
    metaDescription: "Discover Drambuie's Scotch, heather honey and herbs, plus Rusty Nail serves and dessert pairings. Check city prices on BevOry.",
  },
  "fernet-branca": {
    description: "Fernet-Branca is a bitter Italian herbal liqueur made by Fratelli Branca Distillerie. Its intense herbal profile is built from ingredients drawn from several parts of the world.",
    story: "Bernardino Branca created the original preparation in Milan in 1845. The business grew from his laboratory into a distillery, while the recipe remained closely held by the family company.",
    tastingNotes: [{ title: "Aromatic herbs", description: "Dark, mint-like herbal notes are more prominent than sweetness." }, { title: "Long bitterness", description: "Warm spice and a persistent bitter finish define the pour." }],
    howToEnjoy: [{ subheading: "A small measure", description: "Serve lightly chilled in a small glass, or lengthen with cola and plenty of ice." }, { subheading: "Bitter and rich", description: "Try it after mutton seekh, a mushroom pizza or a square of dark chocolate." }],
    pairingIdeas: [{ title: "Strong flavours", items: ["mutton seekh", "mushroom pizza", "dark chocolate", "salted walnuts"] }],
    whyChoose: "Fernet-Branca is for drinkers who enjoy assertive bitterness rather than a sweet herbal cordial.",
    faqs: [{ question: "Where was Fernet-Branca created?", answer: "Bernardino Branca created it in Milan in 1845." }, { question: "Is Fernet-Branca sweet?", answer: "It has some sweetness, but its bitter herbs and long finish are the defining notes." }],
    finalVerdict: "This Milanese amaro rewards a slow sip and food bold enough to stand beside it.",
    metaTitle: "Fernet-Branca Amaro Guide | BevOry",
    metaDescription: "Read Fernet-Branca's Milan story, bitter-herb notes and food pairings. Check city prices on BevOry.",
  },
  finlandia: {
    description: "Finlandia is a Finnish vodka made from locally grown barley and glacial spring water from Rajamäki. The grain spirit is distilled through a long, multi-stage process before the water is added.",
    story: "The brand grew from Finland's grain-distilling tradition into a vodka identified with its northern landscape. Its production ties the barley-growing areas to the Rajamäki water source.",
    tastingNotes: [{ title: "Clean grain", description: "A light barley note sits behind the neutral, clear aroma." }, { title: "Dry close", description: "The finish stays clean instead of becoming sweet or heavily spiced." }],
    howToEnjoy: [{ subheading: "A cold pour", description: "Chill the bottle and serve a small measure straight, or use soda and lemon for a longer drink." }, { subheading: "With something salty", description: "Smoked salmon, tandoori fish or salted cashews suit its spare profile." }],
    pairingIdeas: [{ title: "Cold and savoury", items: ["smoked salmon", "tandoori fish", "salted cashews", "cucumber chaat"] }],
    whyChoose: "Finlandia offers a barley-based vodka with a clear connection to Finland's spring water.",
    faqs: [{ question: "What grain is Finlandia vodka made from?", answer: "The producer uses Finnish barley." }, { question: "Where does Finlandia's water come from?", answer: "It comes from the Rajamäki glacial spring in Finland." }],
    finalVerdict: "A clean, barley-based vodka that suits chilled pours and lightly seasoned seafood.",
    metaTitle: "Finlandia Vodka Guide | BevOry",
    metaDescription: "Explore Finlandia's Finnish barley, Rajamäki spring water and serving ideas. Check city prices on BevOry.",
  },
  fireball: {
    description: "Fireball Cinnamon Whisky is a cinnamon-flavoured whisky drink from the Sazerac portfolio. Its sharp cinnamon heat and marked sweetness make it a very different pour from straight whisky.",
    story: "The brand made cinnamon the centre of a small, chilled party serve. Fireball also uses its name on separate cinnamon beverages, while the whisky-labelled bottle remains whisky-based.",
    tastingNotes: [{ title: "Cinnamon first", description: "Natural cinnamon dominates the aroma and the first sip." }, { title: "Sweet heat", description: "Sugar softens the spice before a warming cinnamon finish." }],
    howToEnjoy: [{ subheading: "Chilled", description: "Serve a small measure cold, or add a splash to apple juice over ice." }, { subheading: "Snack match", description: "Cinnamon rolls, salted popcorn and dark chocolate hold their own beside the heat." }],
    pairingIdeas: [{ title: "Sweet and salty", items: ["salted popcorn", "cinnamon rolls", "dark chocolate", "apple pie"] }],
    whyChoose: "Fireball delivers unmistakable cinnamon rather than the oak-led flavour of conventional whisky.",
    faqs: [{ question: "Is Fireball Cinnamon Whisky whisky-based?", answer: "Yes. The bottle labelled Cinnamon Whisky is whisky-based." }, { question: "Is every Fireball Cinnamon drink whisky?", answer: "No. The brand also makes separate malt-based and wine-based Cinnamon products." }],
    finalVerdict: "Keep the pour small: this is a sweet, hot cinnamon drink, not a substitute for neat bourbon.",
    metaTitle: "Fireball Cinnamon Whisky Guide | BevOry",
    metaDescription: "Learn Fireball's cinnamon style, cold serves and snack pairings. Check city prices on BevOry.",
  },
  glenfarclas: {
    description: "Glenfarclas is a family-owned Speyside single malt Scotch whisky made by the Grant family. Malted barley, spring water and Oloroso sherry casks shape its richer, fruit-and-spice side.",
    story: "John Grant bought the distillery in 1865, and the Grant family still runs it. That continuity lets the house release both age-stated whiskies and Family Casks from individual vintages.",
    tastingNotes: [{ title: "Sherry fruit", description: "Raisin and fruitcake notes speak to the Oloroso-cask style." }, { title: "Malt and spice", description: "Malted barley and gentle baking spice give the sweetness a firm base." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Use a small tulip glass and add a few drops of water after the first sip." }, { subheading: "At dinner", description: "Spiced mutton, dried figs and toasted walnuts work with its sherry-led side." }],
    pairingIdeas: [{ title: "Rich plates", items: ["spiced mutton", "dried figs", "toasted walnuts", "Christmas cake"] }],
    whyChoose: "Glenfarclas keeps family ownership and sherry-cask maturation at the centre of its Speyside identity.",
    faqs: [{ question: "Is Glenfarclas family owned?", answer: "Yes. The Grant family has owned it since John Grant's 1865 purchase." }, { question: "Which casks are closely associated with Glenfarclas?", answer: "The distillery selects European oak casks previously used for Oloroso sherry." }],
    finalVerdict: "A good malt for drinkers who favour dried fruit and malt over heavy smoke.",
    metaTitle: "Glenfarclas Single Malt Guide | BevOry",
    metaDescription: "Discover Glenfarclas, the Grant family's Speyside malt, sherry casks and food pairings. Check city prices on BevOry.",
  },
  gordons: {
    description: "Gordon's is a London Dry gin created by Alexander Gordon in Britain. Its classic recipe pushes juniper forward, with coriander, angelica and liquorice among the botanicals.",
    story: "Alexander Gordon introduced the gin in 1769. Triple distillation and a distinctly juniper-led character helped establish the label as a familiar gin-and-tonic base.",
    tastingNotes: [{ title: "Juniper", description: "Pine-like juniper is the strongest aroma in the London Dry." }, { title: "Dry botanicals", description: "Coriander and angelica give a crisp, herbal finish." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Pour over ice with tonic and a wedge of lemon in a tall glass." }, { subheading: "At the table", description: "Pair the bitter-citrus serve with tandoori prawns or a plate of masala peanuts." }],
    pairingIdeas: [{ title: "Bright snacks", items: ["tandoori prawns", "masala peanuts", "lemon chicken", "cucumber sandwiches"] }],
    whyChoose: "Gordon's puts unmistakable juniper ahead of fashionable sweet botanicals.",
    faqs: [{ question: "Who created Gordon's gin?", answer: "Alexander Gordon created the brand in 1769." }, { question: "What gives Gordon's London Dry its main flavour?", answer: "Juniper is central, supported by coriander, angelica and liquorice." }],
    finalVerdict: "A straightforward London Dry for a crisp gin and tonic with savoury food.",
    metaTitle: "Gordon's London Dry Gin Guide | BevOry",
    metaDescription: "Explore Gordon's juniper-led gin, classic tonic serve and Indian snack pairings. Check city prices on BevOry.",
  },
  guinness: {
    description: "Guinness is an Irish stout brand rooted at St. James's Gate in Dublin. Its dark malt character appears in several beers, including the familiar Draught and the more robust Foreign Extra Stout.",
    story: "Arthur Guinness signed a long lease on the Dublin brewery in 1759. The harp later became the mark tying the stout to its Irish home.",
    tastingNotes: [{ title: "Roasted malt", description: "Coffee-like roast and a dry cocoa note distinguish the stout." }, { title: "Draught texture", description: "The Draught's creamy head softens its dry, roasted finish." }],
    howToEnjoy: [{ subheading: "Pour gently", description: "Serve cool in a clean pint glass, leaving room for the foam to settle." }, { subheading: "With a meal", description: "Pepper beef, mushroom pie and spiced roast potatoes work with the roasted malt." }],
    pairingIdeas: [{ title: "Roast and spice", items: ["pepper beef", "mushroom pie", "spiced roast potatoes", "dark chocolate"] }],
    whyChoose: "Guinness offers the roasted side of beer without tasting like a sweet porter.",
    faqs: [{ question: "Where did Guinness begin?", answer: "Arthur Guinness took over the St. James's Gate brewery in Dublin in 1759." }, { question: "Is every Guinness beer the same?", answer: "No. Draught and Foreign Extra Stout are distinct beers with different strength and flavour." }],
    finalVerdict: "Choose Guinness when you want roasted malt and a dry finish alongside hearty food.",
    metaTitle: "Guinness Irish Stout Guide | BevOry",
    metaDescription: "Read Guinness's Dublin story, roasted-malt notes and hearty food pairings. Check city prices on BevOry.",
  },
  hapusa: {
    description: "Hapusa is a Himalayan dry gin made by India's Nao Spirits in Goa. Himalayan juniper gives the spirit a pine-and-earth character that stands apart from citrus-first gins.",
    story: "Nao Spirits followed its Greater Than gin with Hapusa, turning toward Indian botanicals and a bolder juniper expression. The brand's name refers to juniper in Sanskrit.",
    tastingNotes: [{ title: "Forest aroma", description: "Pine and wildflower notes rise from the juniper." }, { title: "Earth and spice", description: "An earthy middle leads into a long, gently spiced finish." }],
    howToEnjoy: [{ subheading: "Very cold", description: "Try a small pour straight from the freezer before adding tonic or ice." }, { subheading: "Indian grill", description: "Tandoori mushrooms, lemon fish tikka and roasted peanuts suit its pine and spice." }],
    pairingIdeas: [{ title: "Juniper-friendly plates", items: ["tandoori mushrooms", "lemon fish tikka", "roasted peanuts", "pepper paneer"] }],
    whyChoose: "Hapusa gives Himalayan juniper a central role in a gin distilled in India.",
    faqs: [{ question: "Where is Hapusa gin made?", answer: "Nao Spirits makes it in Goa, India." }, { question: "What sets Hapusa apart from a citrus-led gin?", answer: "Its Himalayan juniper brings pine, earth and a longer spice finish." }],
    finalVerdict: "For someone who likes juniper to be unmistakable, Hapusa is worth a cold, unhurried pour.",
    metaTitle: "Hapusa Himalayan Gin Guide | BevOry",
    metaDescription: "Explore Hapusa's Himalayan juniper, Goa distilling and tandoori pairings. Check city prices on BevOry.",
  },
  heineken: {
    description: "Heineken is a Dutch lager brand that began in Amsterdam. The familiar green-bottle beer is a pale, dry lager brewed with barley malt, hops, water and the brewery's A-yeast.",
    story: "Gerard Adriaan Heineken bought De Hooiberg brewery in 1864 and put his name on the family brewery in 1873. Amsterdam remained central to its identity as the beer travelled far beyond the Netherlands.",
    tastingNotes: [{ title: "Light malt", description: "A mild cereal sweetness anchors the lager." }, { title: "Hop finish", description: "A clean bitterness follows the first crisp sip." }],
    howToEnjoy: [{ subheading: "Well chilled", description: "Pour into a clean pilsner glass and leave space for a modest head." }, { subheading: "Simple snacks", description: "Chicken tikka, salted fries and grilled corn match the beer's dry finish." }],
    pairingIdeas: [{ title: "With lager", items: ["chicken tikka", "salted fries", "grilled corn", "fried calamari"] }],
    whyChoose: "Heineken gives familiar pale-lager crispness with enough hop bite to cut through fried food.",
    faqs: [{ question: "Where did Heineken begin?", answer: "The brewery began in Amsterdam under Gerard Adriaan Heineken." }, { question: "When did the Heineken brewery take his name?", answer: "Gerard Heineken established the named brewery in 1873." }],
    finalVerdict: "Keep it cold and pair it with something salty or grilled.",
    metaTitle: "Heineken Dutch Beer Guide | BevOry",
    metaDescription: "Explore Heineken's Amsterdam roots, crisp lager style and grilled-food pairings. Check city prices on BevOry.",
  },
  malibu: {
    description: "Malibu Original is a Caribbean coconut-flavoured rum liqueur in Pernod Ricard's portfolio. Sweet coconut is its defining flavour, particularly in pineapple-led mixed drinks.",
    story: "Created in the late 1970s, Malibu became closely associated with beach cocktails rather than traditional sipping rum. Pernod Ricard added the brand to its portfolio in 2005.",
    tastingNotes: [{ title: "Coconut", description: "Sweet coconut takes the foreground, with a soft rum base behind it." }, { title: "Tropical finish", description: "The finish stays light and sweet rather than oaky." }],
    howToEnjoy: [{ subheading: "With pineapple", description: "Use a tall glass, plenty of ice and pineapple juice, or add it to a Piña Colada." }, { subheading: "Alongside", description: "Grilled pineapple, coconut barfi and chilli-lime prawns play off the sweetness." }],
    pairingIdeas: [{ title: "Sweet and spicy", items: ["chilli-lime prawns", "grilled pineapple", "coconut barfi", "plantain chips"] }],
    whyChoose: "Malibu is an easy route to coconut in a mixed drink without making the rum itself the loudest ingredient.",
    faqs: [{ question: "What does Malibu Original taste like?", answer: "Coconut is the main flavour, with a light Caribbean rum base." }, { question: "Is Malibu best served neat?", answer: "It is most often mixed with pineapple juice or used in tropical cocktails." }],
    finalVerdict: "A useful bottle for coconut-and-pineapple drinks; don't mistake it for an oak-aged rum.",
    metaTitle: "Malibu Coconut Rum Guide | BevOry",
    metaDescription: "Discover Malibu Original's coconut style, pineapple serves and spicy-food pairings. Check city prices on BevOry.",
  },
  martell: {
    description: "Martell is a Cognac house founded by Jean Martell in France. Its eaux-de-vie are associated with the Borderies cru and distillation of clear wines, producing a fruit-and-floral house style.",
    story: "Jean Martell arrived from Jersey and established the house in Cognac in 1715. Borderies fruit, careful blending and fine-grained oak remain recurring elements of its long-running identity.",
    tastingNotes: [{ title: "Flowers and fruit", description: "The Borderies influence is associated with floral aroma and candied fruit." }, { title: "Oak warmth", description: "Fine-grained oak adds spice beneath the fruit in aged expressions." }],
    howToEnjoy: [{ subheading: "A slow pour", description: "Use a small tulip glass and let the cognac settle before drinking; younger expressions also suit a simple highball." }, { subheading: "After food", description: "Dark chocolate, dried apricots and galouti kebabs bring out different sides of the fruit and oak." }],
    pairingIdeas: [{ title: "Fruit and spice", items: ["galouti kebabs", "dried apricots", "dark chocolate", "roasted hazelnuts"] }],
    whyChoose: "Martell's long Cognac history is closely tied to the floral Borderies cru.",
    faqs: [{ question: "Who founded Martell?", answer: "Jean Martell founded the Cognac house in 1715." }, { question: "What is Borderies in relation to Martell?", answer: "Borderies is a Cognac growing cru whose floral eaux-de-vie are important to the house style." }],
    finalVerdict: "Look to Martell for a Cognac that brings fruit and flowers into the oak-aged conversation.",
    metaTitle: "Martell Cognac Guide | BevOry",
    metaDescription: "Explore Martell's 1715 Cognac heritage, Borderies style and food pairings. Check city prices on BevOry.",
  },
  miller: {
    description: "Miller is an American brewing name; Miller High Life is its long-running pale lager. Malted barley, Pacific Northwest hops and Miller yeast give High Life a light, crisp profile.",
    story: "Miller High Life was launched in 1903 as the company's flagship bottled beer. Its clear glass and fine bubbles soon earned it a champagne-themed nickname.",
    tastingNotes: [{ title: "Fresh malt", description: "Light grain sweetness keeps the lager easy to drink." }, { title: "Bright finish", description: "A touch of hops and lively carbonation close each sip." }],
    howToEnjoy: [{ subheading: "Straight from the fridge", description: "Serve cold in a narrow glass that shows the beer's lively bubbles." }, { subheading: "Bar food", description: "Chicken wings, masala fries and crispy fish suit its light body." }],
    pairingIdeas: [{ title: "Crisp bites", items: ["chicken wings", "masala fries", "crispy fish", "salted pretzels"] }],
    whyChoose: "Miller High Life is an old-school American bottled lager with a distinctly light touch.",
    faqs: [{ question: "When was Miller High Life introduced?", answer: "Miller Brewing launched it in 1903." }, { question: "What style is Miller High Life?", answer: "It is an American pale lager." }],
    finalVerdict: "An unfussy beer for fried snacks and a cold glass.",
    metaTitle: "Miller High Life Beer Guide | BevOry",
    metaDescription: "Explore Miller High Life's 1903 origins, light lager style and snack pairings. Check city prices on BevOry.",
  },
  "old-forester": {
    description: "Old Forester is a Kentucky bourbon founded by George Garvin Brown and now part of Brown-Forman. Its range includes bourbon and rye expressions made for neat pours and classic American whiskey cocktails.",
    story: "Brown introduced Old Forester in 1870 at a time when whiskey quality varied widely. Selling it in sealed bottles gave buyers a more dependable identity than open-barrel pours.",
    tastingNotes: [{ title: "Brown sugar and oak", description: "The bourbon side brings caramelised sweetness and charred wood." }, { title: "Warm spice", description: "A rye-tinged spice keeps the finish lively." }],
    howToEnjoy: [{ subheading: "Neat or Old Fashioned", description: "Try a small neat pour, then use a measure with bitters and sugar in an Old Fashioned." }, { subheading: "Savory heat", description: "Tandoori lamb, barbecue ribs and roasted pecans stand up to its oak." }],
    pairingIdeas: [{ title: "Oak-friendly food", items: ["tandoori lamb", "barbecue ribs", "roasted pecans", "dark chocolate"] }],
    whyChoose: "Old Forester connects bourbon's bottled-whiskey history to a broad modern Kentucky range.",
    faqs: [{ question: "Who started Old Forester?", answer: "George Garvin Brown introduced it in 1870." }, { question: "Is Old Forester a bourbon?", answer: "The core range includes Kentucky straight bourbon, alongside rye whiskey expressions." }],
    finalVerdict: "A solid Kentucky choice when caramel, oak and spice are what you want in the glass.",
    metaTitle: "Old Forester Bourbon Guide | BevOry",
    metaDescription: "Read Old Forester's 1870 Kentucky story, oak-and-spice notes and pairing ideas. Check city prices on BevOry.",
  },
  "old-pulteney": {
    description: "Old Pulteney is a single malt Scotch whisky made at Pulteney Distillery in Wick, on Scotland's north coast. Unusually shaped copper stills and coastal maturation help define its maritime character.",
    story: "James Henderson founded the distillery in 1826, when barley and whisky travelled in and out of Wick by sea. The harbour town's herring trade and the distillery grew side by side.",
    tastingNotes: [{ title: "Coastal edge", description: "A dry, saline note cuts through the malt." }, { title: "Honeyed malt", description: "Gentle sweetness and citrus keep the maritime side from feeling austere." }],
    howToEnjoy: [{ subheading: "A few drops", description: "Sip from a small tulip glass; a little water can lift the citrus." }, { subheading: "Seafood", description: "Grilled prawns, fish tikka and salted almonds make sense beside its coastal note." }],
    pairingIdeas: [{ title: "By the sea", items: ["grilled prawns", "fish tikka", "salted almonds", "smoked mackerel"] }],
    whyChoose: "Few Scottish malts connect their flavour to a working North Sea port as plainly as Old Pulteney.",
    faqs: [{ question: "Where is Old Pulteney made?", answer: "At Pulteney Distillery in Wick, Scotland." }, { question: "When did Pulteney Distillery begin?", answer: "James Henderson founded it in 1826." }],
    finalVerdict: "A coastal malt for someone who likes a little salt beside honey and citrus.",
    metaTitle: "Old Pulteney Single Malt Guide | BevOry",
    metaDescription: "Discover Old Pulteney's Wick distillery, coastal malt style and seafood pairings. Check city prices on BevOry.",
  },
  "old-smuggler": {
    description: "Old Smuggler is a blended Scotch whisky now in the Campari Group portfolio. It brings together Scotch malt and grain whiskies in an approachable, lighter style.",
    story: "The brand dates to 1835, when its name evoked the illicit whisky trade of earlier Scottish history. Campari acquired Old Smuggler with the Glen Grant transaction in 2006.",
    tastingNotes: [{ title: "Toffee and caramel", description: "The aroma brings English toffee and caramel, with a little charcoal." }, { title: "Creamy, then dry", description: "A soft toffee palate turns mildly spicy and oaky on the finish." }],
    howToEnjoy: [{ subheading: "Long with soda", description: "Add chilled soda and ice to a modest measure for a simple highball." }, { subheading: "Beside snacks", description: "Masala peanuts, grilled mushrooms and pepper chicken suit its restrained body." }],
    pairingIdeas: [{ title: "Everyday savoury", items: ["masala peanuts", "grilled mushrooms", "pepper chicken", "roasted cashews"] }],
    whyChoose: "Old Smuggler is a straightforward blended Scotch with a longer history than its easy-drinking style suggests.",
    faqs: [{ question: "Is Old Smuggler Scotch whisky?", answer: "Yes. It is a blended Scotch whisky." }, { question: "Who owns Old Smuggler?", answer: "Campari Group acquired the brand in 2006." }],
    finalVerdict: "A modest, malt-led Scotch that works well lengthened with soda.",
    metaTitle: "Old Smuggler Scotch Guide | BevOry",
    metaDescription: "Read Old Smuggler's 1835 Scotch story, soft malt style and snack pairings. Check city prices on BevOry.",
  },
  peroni: {
    description: "Peroni is an Italian beer name; Peroni Nastro Azzurro is its crisp premium lager. The Nastro Azzurro style is light-bodied, with a clean malt start and dry finish.",
    story: "Birra Peroni's history begins in 1846, while Nastro Azzurro was launched in Naples in 1963. Its name borrows from the Blue Riband ocean-crossing award won by the Italian liner Rex.",
    tastingNotes: [{ title: "Pale malt", description: "A restrained grain sweetness gives the beer its base." }, { title: "Dry close", description: "Fine bubbles and a touch of bitterness leave the finish crisp." }],
    howToEnjoy: [{ subheading: "Cold in a glass", description: "Serve chilled in a narrow beer glass rather than warming it in the bottle." }, { subheading: "Italian and Indian", description: "Margherita pizza, fried calamari and chilli paneer all suit a dry lager." }],
    pairingIdeas: [{ title: "With a lager", items: ["margherita pizza", "fried calamari", "chilli paneer", "salted olives"] }],
    whyChoose: "Nastro Azzurro gives the Peroni name an especially dry, food-friendly Italian lager.",
    faqs: [{ question: "When did Peroni Nastro Azzurro begin?", answer: "It was launched in 1963." }, { question: "What does Nastro Azzurro mean?", answer: "It refers to the Blue Riband associated with a fast Atlantic crossing." }],
    finalVerdict: "A pale Italian lager that belongs next to food, especially something salty or fried.",
    metaTitle: "Peroni Nastro Azzurro Beer Guide | BevOry",
    metaDescription: "Explore Peroni Nastro Azzurro's Italian story, dry lager style and food pairings. Check city prices on BevOry.",
  },
  pimms: {
    description: "Pimm's No. 1 is a British gin-based fruit cup with herbs and citrus. It is usually served long with lemonade, ice and fresh fruit rather than drunk neat.",
    story: "James Pimm served his No. 1 Cup at a London oyster bar in the 1840s. The drink spread from that table to the wider British summer tradition.",
    tastingNotes: [{ title: "Orange and fruit", description: "Caramelised orange and bright citrus give the cup a fruity opening." }, { title: "Herbal lift", description: "Gentle botanicals keep the sweet fruit from turning heavy." }],
    howToEnjoy: [{ subheading: "A tall cup", description: "Pour over plenty of ice, top with lemonade and add cucumber, orange and mint." }, { subheading: "With lunch", description: "Cucumber sandwiches, tandoori prawns and strawberries fit the fresh serve." }],
    pairingIdeas: [{ title: "Summer plates", items: ["cucumber sandwiches", "tandoori prawns", "strawberries", "lemon cake"] }],
    whyChoose: "Pimm's turns a gin-based cup into a low-fuss, fruit-and-herb long drink.",
    faqs: [{ question: "Is Pimm's No. 1 gin-based?", answer: "Yes. The original No. 1 Cup is based on gin with herbs and fruit flavours." }, { question: "How is Pimm's usually served?", answer: "With lemonade, ice, fruit and often cucumber or mint." }],
    finalVerdict: "Keep the jug cold and the garnish fresh; that is where Pimm's makes sense.",
    metaTitle: "Pimm's No. 1 Fruit Cup Guide | BevOry",
    metaDescription: "Meet Pimm's gin-based fruit cup, its London story and lemonade serve. Check city prices on BevOry.",
  },
  rampur: {
    description: "Rampur is an Indian single malt from Radico Khaitan's distillery in Uttar Pradesh. Copper pot distillation and maturation in the Himalayan foothills give its different expressions a distinct Indian setting.",
    story: "The distillery began operations in 1943, long before Rampur became its internationally visible single-malt label. Large seasonal temperature changes influence how the whisky interacts with its casks.",
    tastingNotes: [{ title: "Fruit and malt", description: "The core style has a rounded malt character with orchard-fruit notes." }, { title: "Oak spice", description: "Cask maturation adds warmth and spice without making peat the focus." }],
    howToEnjoy: [{ subheading: "Neat, then water", description: "Sip from a small glass and add a few drops of water if you want the fruit to open." }, { subheading: "With Indian food", description: "Seekh kebabs, roasted paneer and salted almonds suit its malt-and-oak profile." }],
    pairingIdeas: [{ title: "Malt and spice", items: ["mutton seekh", "roasted paneer", "salted almonds", "grilled lamb chops"] }],
    whyChoose: "Rampur connects Indian single malt to a distillery that has worked in Uttar Pradesh since 1943.",
    faqs: [{ question: "Who makes Rampur single malt?", answer: "Radico Khaitan makes it at its Rampur distillery in Uttar Pradesh." }, { question: "Is Rampur a blended whisky?", answer: "No. The Rampur range is Indian single malt whisky." }],
    finalVerdict: "A useful Indian malt to explore for fruit, oak and the influence of a warmer maturation climate.",
    metaTitle: "Rampur Indian Single Malt Guide | BevOry",
    metaDescription: "Explore Rampur's Uttar Pradesh distillery, copper-pot malt and kebab pairings. Check city prices on BevOry.",
  },
  ricard: {
    description: "Ricard is a pastis from Marseille created by Paul Ricard. Anise and liquorice are its unmistakable flavours, traditionally opened up with cold water.",
    story: "Paul Ricard introduced his pastis in 1932. The label has stayed close to Marseille's aperitif culture, where a small measure becomes a longer drink at the table.",
    tastingNotes: [{ title: "Anise", description: "Fresh, aromatic anise takes the lead as soon as water meets the spirit." }, { title: "Liquorice", description: "A deeper liquorice note gives the finish its characteristic length." }],
    howToEnjoy: [{ subheading: "Add water", description: "Pour a little Ricard into a tall glass, add cold water gradually, then ice if you want it colder." }, { subheading: "Before a meal", description: "Salted olives, fried squid and masala peanuts make good small plates." }],
    pairingIdeas: [{ title: "Aperitif bites", items: ["salted olives", "fried squid", "masala peanuts", "grilled fennel"] }],
    whyChoose: "Ricard brings the anise-and-liquorice tradition of Marseille to a slow, water-lengthened aperitif.",
    faqs: [{ question: "Is Ricard a whisky?", answer: "No. Ricard is a French anise-flavoured pastis." }, { question: "How should Ricard be served?", answer: "It is traditionally diluted with cold water and served with ice to taste." }],
    finalVerdict: "Best treated as an aperitif: small measure, cold water, salty food.",
    metaTitle: "Ricard Pastis Guide | BevOry",
    metaDescription: "Discover Ricard pastis from Marseille, its anise notes and classic water serve. Check city prices on BevOry.",
  },
  skyy: {
    description: "SKYY is a vodka brand born in San Francisco and now in the Campari Group portfolio. Its clear, neutral style was developed around multiple distillation and filtration steps.",
    story: "Inventor Maurice Kanbar introduced SKYY in 1992. The cobalt-blue bottle became a visual signature while the vodka became a frequent base for American bar cocktails.",
    tastingNotes: [{ title: "Clean aroma", description: "The vodka keeps its nose restrained rather than strongly grain-led." }, { title: "Dry finish", description: "A soft texture gives way to a clean, crisp close." }],
    howToEnjoy: [{ subheading: "A simple mixer", description: "Use chilled soda and a squeeze of grapefruit in a tall glass, or make a vodka Martini." }, { subheading: "With food", description: "Lemon prawns, cucumber chaat and salted potato chips keep the pairing light." }],
    pairingIdeas: [{ title: "Fresh and salty", items: ["lemon prawns", "cucumber chaat", "salted potato chips", "smoked salmon"] }],
    whyChoose: "SKYY's spare style leaves room for citrus and bitters in mixed drinks.",
    faqs: [{ question: "Where was SKYY Vodka created?", answer: "Maurice Kanbar launched it in San Francisco in 1992." }, { question: "Who owns SKYY?", answer: "SKYY is part of the Campari Group portfolio." }],
    finalVerdict: "A neutral vodka for a citrus highball or a clean, cold Martini.",
    metaTitle: "SKYY Vodka Guide | BevOry",
    metaDescription: "Explore SKYY Vodka's San Francisco origins, clean style and cocktail serves. Check city prices on BevOry.",
  },
  stolichnaya: {
    description: "Stolichnaya, now branded Stoli in many markets, is a grain vodka from Stoli Group. Current Stoli production is associated with the Latvijas Balzams facility in Riga, Latvia.",
    story: "The brand traces its history to 1938. Its modern Riga production and bottling give the long-established label a distinct Latvian manufacturing home.",
    tastingNotes: [{ title: "Grain softness", description: "Wheat-led softness sits beneath a largely neutral aroma." }, { title: "Clean citrus", description: "A light citrus impression brightens the finish." }],
    howToEnjoy: [{ subheading: "Cold or mixed", description: "Chill for a small straight pour, or mix with soda and fresh lemon in a tall glass." }, { subheading: "Savoury table", description: "Pickled cucumber, smoked fish and paneer tikka bring contrast to its clean profile." }],
    pairingIdeas: [{ title: "Salt and smoke", items: ["pickled cucumber", "smoked fish", "paneer tikka", "salted cashews"] }],
    whyChoose: "Stoli offers a long-running grain-vodka name with a restrained profile for simple drinks.",
    faqs: [{ question: "Where is current Stoli vodka produced?", answer: "Stoli Group identifies Latvijas Balzams in Riga, Latvia, as a production and bottling site." }, { question: "Are Stoli and Stolichnaya related?", answer: "Yes. Stoli is the current branding used for the long-established Stolichnaya vodka." }],
    finalVerdict: "Most at home very cold or lengthened with soda and citrus.",
    metaTitle: "Stolichnaya Stoli Vodka Guide | BevOry",
    metaDescription: "Read about Stolichnaya and Stoli, Riga production and crisp serving ideas. Check city prices on BevOry.",
  },
  teeling: {
    description: "Teeling is an Irish whiskey name revived by brothers Jack and Stephen Teeling in Dublin. Its range explores different whiskey styles and cask finishes rather than one fixed flavour profile.",
    story: "Walter Teeling distilled on Marrowbone Lane in 1782. More than two centuries later, Jack and Stephen opened a new Teeling distillery in Dublin in 2015, close to the family's old neighbourhood.",
    tastingNotes: [{ title: "Small Batch", description: "The rum-cask-finished blend leans toward vanilla, fruit and gentle spice." }, { title: "Single Malt", description: "Fruit and wood complexity come through more strongly in the malt expression." }],
    howToEnjoy: [{ subheading: "Start neat", description: "Try a small neat measure before adding a little water; Small Batch also works in an Irish Whiskey Sour." }, { subheading: "With dinner", description: "Pepper chicken, roasted mushrooms and apple tart complement its sweeter cask notes." }],
    pairingIdeas: [{ title: "Dublin to dinner", items: ["pepper chicken", "roasted mushrooms", "apple tart", "salted almonds"] }],
    whyChoose: "Teeling brings active Dublin distilling back into a family name with an eighteenth-century address.",
    faqs: [{ question: "Who founded the modern Teeling distillery?", answer: "Brothers Jack and Stephen Teeling opened it in Dublin in 2015." }, { question: "Is all Teeling whiskey made in one style?", answer: "No. The range includes blends and single malt expressions with different cask influences." }],
    finalVerdict: "A Dublin whiskey range worth approaching expression by expression, beginning with a neat sip.",
    metaTitle: "Teeling Irish Whiskey Guide | BevOry",
    metaDescription: "Discover Teeling's Dublin distillery, Small Batch style and food pairings. Check city prices on BevOry.",
  },
  titos: {
    description: "Tito's Handmade Vodka is a corn-based American vodka made in Austin, Texas. Its founder, Bert 'Tito' Beveridge, built the brand around a Texas distillery rather than a traditional grain-vodka region.",
    story: "Beveridge started the company in 1997. What began as a small Austin operation developed into one of the most recognisable American vodka labels.",
    tastingNotes: [{ title: "Soft corn", description: "The corn base gives a gentle sweetness beneath the neutral spirit." }, { title: "Clean close", description: "A crisp, restrained finish makes room for citrus in a mixed drink." }],
    howToEnjoy: [{ subheading: "Soda and lime", description: "Use plenty of ice, soda and a squeeze of lime in a highball glass." }, { subheading: "With a snack", description: "Chilli paneer, tortilla chips and grilled prawns all benefit from the cold citrus serve." }],
    pairingIdeas: [{ title: "Citrus-friendly", items: ["chilli paneer", "tortilla chips", "grilled prawns", "salted peanuts"] }],
    whyChoose: "Tito's gives vodka drinkers a clearly identified corn base and Austin origin.",
    faqs: [{ question: "What is Tito's Vodka made from?", answer: "Tito's says it distils its vodka from corn." }, { question: "Where did Tito's begin?", answer: "It began in Austin, Texas, in 1997." }],
    finalVerdict: "A corn vodka that sits neatly in a cold soda-and-lime drink.",
    metaTitle: "Tito's Handmade Vodka Guide | BevOry",
    metaDescription: "Learn Tito's Austin story, corn-vodka style and simple mixer ideas. Check city prices on BevOry.",
  },
  "wild-turkey": {
    description: "Wild Turkey is a Kentucky bourbon brand distilled in Lawrenceburg. Corn-led grain, new charred oak and the Russell family's long stewardship give the core whiskeys their bold, spicy character.",
    story: "The Ripy brothers established a distillery on Wild Turkey Hill in the nineteenth century. Jimmy Russell later became one of the brand's best-known distillers, with Eddie Russell continuing the family work.",
    tastingNotes: [{ title: "Vanilla and caramel", description: "Oak brings sweetness without losing the whiskey's grain character." }, { title: "Kentucky spice", description: "A firm spice note and warm finish distinguish the bourbon from lighter blends." }],
    howToEnjoy: [{ subheading: "Rocks or Old Fashioned", description: "Try a small pour over one cube, or use it with bitters in an Old Fashioned." }, { subheading: "Charred food", description: "Barbecue chicken, mutton seekh and roasted pecans meet the oak and spice." }],
    pairingIdeas: [{ title: "Char and oak", items: ["barbecue chicken", "mutton seekh", "roasted pecans", "dark chocolate"] }],
    whyChoose: "Wild Turkey keeps a robust Kentucky bourbon character at the centre of its range.",
    faqs: [{ question: "Where is Wild Turkey bourbon made?", answer: "It is distilled in Lawrenceburg, Kentucky." }, { question: "Who are the Russells at Wild Turkey?", answer: "Jimmy and Eddie Russell are the father-and-son distillers closely associated with the brand." }],
    finalVerdict: "Reach for Wild Turkey when a bourbon needs enough spice to stand beside a grilled meal.",
    metaTitle: "Wild Turkey Bourbon Guide | BevOry",
    metaDescription: "Explore Wild Turkey's Kentucky roots, oak-and-spice profile and barbecue pairings. Check city prices on BevOry.",
  },
  "william-fevre": {
    description: "Domaine William Fèvre is a Chablis wine estate in Burgundy, France, devoted to Chardonnay. Its vineyards include Premier Cru and Grand Cru sites on the region's limestone-rich slopes.",
    story: "William Fèvre took over the family estate in 1959, giving it his name and expanding its historic Chablis parcels. The domaine joined Domaines Barons de Rothschild Lafite in 2024.",
    tastingNotes: [{ title: "Chablis freshness", description: "Citrus and firm acidity give the Chardonnay a brisk opening." }, { title: "Stony finish", description: "A mineral impression and restrained fruit reflect Chablis's limestone terrain." }],
    howToEnjoy: [{ subheading: "Chilled, not icy", description: "Serve in a medium white-wine glass so its citrus and mineral notes remain clear." }, { subheading: "Seafood first", description: "Tandoori fish, grilled prawns and goat cheese work with the acidity." }],
    pairingIdeas: [{ title: "For Chablis", items: ["tandoori fish", "grilled prawns", "goat cheese", "lemon butter mushrooms"] }],
    whyChoose: "William Fèvre brings a long-held Chablis estate and named cru vineyards to Chardonnay drinkers.",
    faqs: [{ question: "Which grape is William Fèvre Chablis made from?", answer: "Chablis is made from Chardonnay." }, { question: "When did William Fèvre take over the estate?", answer: "He took over the family domaine in 1959." }],
    finalVerdict: "A Chablis name for someone who values acidity, limestone character and food-friendly restraint.",
    metaTitle: "William Fèvre Chablis Wine Guide | BevOry",
    metaDescription: "Discover William Fèvre's Chablis Chardonnay, limestone terroir and seafood pairings. Check city prices on BevOry.",
  },
  woodford: {
    description: "Woodford Reserve is a Kentucky bourbon from Brown-Forman, made at a distillery site with roots in nineteenth-century whiskey production. Corn, rye and malted barley shape its grain base.",
    story: "Whiskey production on the Woodford County site dates to 1812. The present distillery draws on that history while using copper pot stills and long fermentation for its core bourbon.",
    tastingNotes: [{ title: "Orange and fruit", description: "Citrus and orchard-fruit aromas come through in the bourbon." }, { title: "Chocolate and spice", description: "Oak, grain and fermentation contribute cocoa, clove and a warming spice note." }],
    howToEnjoy: [{ subheading: "Taste neat first", description: "Start with a small neat pour; a single cube or an Old Fashioned can follow." }, { subheading: "With richness", description: "Dark chocolate, galouti kebabs and roasted pecans suit the bourbon's spice." }],
    pairingIdeas: [{ title: "Sweet and savoury", items: ["dark chocolate", "galouti kebabs", "roasted pecans", "grilled pork"] }],
    whyChoose: "Woodford Reserve balances fruit and spice with a substantial bourbon texture.",
    faqs: [{ question: "Where is Woodford Reserve made?", answer: "It is made in Woodford County, Kentucky, at a historic distillery site." }, { question: "What grains are in its bourbon?", answer: "The grain recipe includes corn, rye and malted barley." }],
    finalVerdict: "A bourbon with enough citrus to lift its oak, and enough spice to hold a rich meal.",
    metaTitle: "Woodford Reserve Bourbon Guide | BevOry",
    metaDescription: "Explore Woodford Reserve's Kentucky heritage, citrus-and-spice notes and pairings. Check city prices on BevOry.",
  },
  yamazaki: {
    description: "Yamazaki is a Japanese single malt whisky made by Suntory near Kyoto. The distillery's range of stills and casks gives its expressions different fruit, oak and spice characters.",
    story: "Shinjiro Torii established Yamazaki in 1923 as Japan's first malt whisky distillery. He chose the site where three rivers converge, seeking a climate and water source suited to his own approach to whisky.",
    tastingNotes: [{ title: "Distiller's Reserve aroma", description: "Strawberry and cherry meet the scent of Japanese Mizunara oak." }, { title: "Distiller's Reserve palate", description: "Raspberry and white peach lead into a light coconut note." }],
    howToEnjoy: [{ subheading: "A quiet glass", description: "Begin neat in a small tulip glass; add a few drops of water only after tasting." }, { subheading: "Japanese and Indian", description: "Yakitori, tandoori mushrooms and roasted almonds work beside its savoury oak." }],
    pairingIdeas: [{ title: "Against oak", items: ["yakitori", "tandoori mushrooms", "roasted almonds", "grilled salmon"] }],
    whyChoose: "Yamazaki links Japanese single malt to the distillery where Suntory's whisky project began.",
    faqs: [{ question: "Who founded Yamazaki Distillery?", answer: "Suntory founder Shinjiro Torii established it in 1923." }, { question: "Is Yamazaki a single malt?", answer: "Yes. Yamazaki is Suntory's single malt whisky from its Yamazaki Distillery." }],
    finalVerdict: "Take it slowly: Yamazaki's fruit and oak shift noticeably between expressions.",
    metaTitle: "Yamazaki Japanese Whisky Guide | BevOry",
    metaDescription: "Read Yamazaki's 1923 Kyoto-area story, fruit-and-oak notes and food pairings. Check city prices on BevOry.",
  },
  zubrowka: {
    description: "Żubrówka is a Polish vodka associated with bison grass from the Białowieża Forest region. Its best-known Bison Grass expression has a distinctive hay-and-herb aroma.",
    story: "Adding aromatic bison grass to spirits has a long history in Poland. Żubrówka built a modern brand around that tradition and the forest landscape of the country's northeast.",
    tastingNotes: [{ title: "Fresh hay", description: "Bison grass gives an unmistakable dry-grass and herbal aroma." }, { title: "Soft sweetness", description: "A light honey-like note follows the green herbs." }],
    howToEnjoy: [{ subheading: "With apple", description: "Serve chilled with clear apple juice and ice, or sip a small measure cold." }, { subheading: "Food", description: "Apple tart, roast pork and paneer tikka all pick up its herb-and-fruit side." }],
    pairingIdeas: [{ title: "Herb and apple", items: ["apple tart", "roast pork", "paneer tikka", "salted almonds"] }],
    whyChoose: "Żubrówka offers a grass-scented vodka profile that neutral spirits cannot imitate.",
    faqs: [{ question: "What flavours Żubrówka Bison Grass?", answer: "Aromatic bison grass gives the expression its hay-like aroma." }, { question: "Where does its bison-grass tradition come from?", answer: "It is associated with northeastern Poland and the Białowieża Forest region." }],
    finalVerdict: "Use apple to bring out the grass and honey notes, or try a small cold pour on its own.",
    metaTitle: "Żubrówka Bison Grass Vodka Guide | BevOry",
    metaDescription: "Explore Żubrówka's Polish bison grass, hay notes and apple serve. Check city prices on BevOry.",
  },
};
