import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_46 = [
  ["alter-ego", "Alter Ego de Palmer", "France", "Wine", "212d4a3d41e79aad8bf65dc2"],
  ["arna", "Arna", "Nepal", "Beer", "795f1b827bd05913f229c8af"],
  ["attitude", "Attitude", "France", "Wine", "b67cab457e406488e88a0ebd"],
  ["aussieres", "Aussieres", "France", "Wine", "30b03785ab80328f1468eb00"],
  ["bad-boy", "Bad Boy", "France", "Wine", "7349a876ddf6f1d6fb44146e"],
  ["bodkin", "Bodkin", "United States", "Wine", "9d4f74c80071c473665afe9e"],
  ["bootz", "Bootz", "Netherlands", "Spirits", "9b473bd47c1608625879f964"],
  ["butlers", "Butlers", "South Africa", "Liqueur", "37cae3160c1fdc91ca5c537c"],
  ["condesa-de-leganza", "Condesa de Leganza", "Spain", "Wine", "3a887478582ca296651f0cf0"],
  ["dr-schmitt", "Dr Schmitt", "Germany", "Wine", "8a03a19424f9c8649fae3a7f"],
  ["glen-flagler", "Glen Flagler", "Scotland", "Whisky", "e1374814a0446e4a4dcbe74d"],
  ["grand-sud", "Grand Sud", "France", "Wine", "88391d8e9b2aea947ccf6784"],
  ["hanacka", "Hanacka", "Czech Republic", "Vodka", "82f93a03b9847e2d08ba9c5f"],
  ["hichki", "Hichki", "India", "Gin", "a52aa2902e056c041b55bea1"],
  ["invincible", "Invincible", "India", "Vodka", "efb581cc8d3b432a96484aaf"],
  ["jnoon", "J'NOON", "India", "Wine", "996d59b7d5d04035337dcbfd"],
  ["lions-de-batailley", "Lions de Batailley", "France", "Wine", "69550f03cc7033a18d6613eb"],
  ["mooz", "Moooz", "India", "Vodka", "915916a5b5cdae697aeec0f4"],
  ["nicobar", "Nicobar", "India", "Gin", "9de31aed012df6b5bb2ba8a5"],
  ["ottos", "Otto's Athens Vermouth", "Greece", "Vermouth", "67c44b058e99d9d3c886a6bc"],
  ["pursue", "Pursue", "India", "Ready-to-drink", "0f571e7c2d332077617c23a5"],
  ["rasa", "Rasa", "India", "Wine", "3e8abece7b0ba288845a7b28"],
  ["seven-hills", "Seven Hills", "Italy", "Gin", "3c10e93544b3126c9b06628d"],
  ["six-brothers", "Six Brothers", "India", "Mahua Spirit", "6aa620b8868e0adf740a9883"],
  ["tommy-bahama", "Tommy Bahama", "United States", "Spirits", "9482fb291c55550708b3f94b"],
  ["white-fox", "White Fox", "India", "Vodka", "c93bc7fb2872c6c93a51ed84"],
  ["white-birch", "White Birch", "Russia", "Vodka", "8d1c59e1b4e54ec867e76edc"],
  ["zappa", "Zappa", "South Africa", "Sambuca", "4c63f163e41a37f4c2e03470"],
  ["gracia-viva-agave", "Gracia Viva Agave", "India", "Agave Spirit", "3369f4c0e37028fac565abbc"],
  ["pieno-sud", "Pieno Sud", "Italy", "Wine", "d0e6d4b44119d664e1ff7e21"],
] as const;

// Research provenance is internal and must not appear in customer-facing fields.
export const BRAND_SOURCES_BATCH_46: Record<string, string[]> = {
  "alter-ego": ["https://www.chateau-palmer.com/en/alterego"],
  arna: ["https://www.arnabeer.com/"],
  attitude: ["https://pascaljolivet.com/produits/vins/attitude/sauvignon-blanc-attitude-igp-du-val-de-loire/"],
  aussieres: ["https://www.lafite.com/domaines/domaine-aussieres/read/"],
  "bad-boy": ["https://www.thunevin-online.com/", "https://www.thunevin.com/upload/Bad-Boy_EN-.pdf"],
  bodkin: ["https://bodkinwines.com/about/"],
  bootz: ["https://www.lucasbols.nl/files/1/9/9/5/2/Lucas_Bols_Annual_Report_2014_15_Final.pdf"],
  butlers: ["https://butlerscocktails.co.za/"],
  "condesa-de-leganza": ["https://www.condesadeleganza.com/es/condesa-de-leganza-rosado-seleccion-de-familia"],
  "dr-schmitt": ["https://www.schmitt-soehne.com/products/pi-dr-schmitt-riesling-qba-109549987/s-0-75-l"],
  "glen-flagler": ["https://whiskyauctioneer.com/learn/explore-whisky/distilleries/glen-flagler"],
  "grand-sud": ["https://www.groupegcf.com/our-brands/grand-sud.html"],
  hanacka: ["https://hanackavodka.cz/"],
  hichki: ["https://www.quickcompany.in/trademarks/3785500-hichki", "https://tasmac.reclaimchennai.city/types/GIN"],
  invincible: ["https://invincible-vodka.com/"],
  jnoon: ["https://fratelliwines.in/blogs/our-story/jnoon", "https://www.boissetcollection.com/brands/jnoon"],
  "lions-de-batailley": ["https://batailley.com/en/", "https://www.borie-manoux.com/wines/lions-de-batailley-2/"],
  mooz: ["https://www.linkedin.com/posts/adie-broswon-group_theadiebroswongroup-abgrainspirits-mooozsparkle-activity-7295677837766799360-_jX8"],
  nicobar: ["https://www.nicobargin.com/"],
  ottos: ["https://www.athensvermouth.com/"],
  pursue: ["https://pursuedrinks.com/"],
  rasa: ["https://sulavineyards.com/files/0524/Press%20Release%20-%20Sula%27s%20RASA%20Cabernet%20Sauvignon%20Garners%20India%27s%20First%20Gold%20at%20Global%20Masters.pdf"],
  "seven-hills": ["https://www.diffordsguide.com/beer-wine-spirits/7096/seven-hills-gin"],
  "six-brothers": ["https://sixbrothers.com/the-distillery", "https://sixbrothers.com/the-location"],
  "tommy-bahama": ["https://cloud-preview.tommybahama.com/about/spirits"],
  "white-fox": ["https://somindia.com/product/white-fox-vodka/"],
  "white-birch": ["https://solexbev.com/brands/whitebirch/"],
  zappa: ["https://zappa.co.za/"],
  "gracia-viva-agave": ["https://www.drinkgracia.com/"],
  "pieno-sud": ["https://www.livcheers.com/goa/liquor/pieno-sud-rosso-750ml", "https://www.livcheers.com/goa/liquor/pieno-sud-bianco-750ml"],
};

export const BRAND_LOGOS_BATCH_46: Record<string, string> = {
  invincible: "https://invincible-vodka.com/wp-content/uploads/2026/01/logo-1-e1768822048857.png",
  pursue: "https://pursuedrinks.com/cdn/shop/files/pursue-logo-black.png?height=80&v=1756221935",
};

type Draft = {
  description: string;
  story: string;
  notes: [string, string, string, string];
  serve: string;
  food: string;
  pairings: string[];
  whyChoose: string;
  faq: [string, string, string, string];
  finalVerdict: string;
  metaDescription: string;
  metaTitle?: string;
};

const guide = (name: string, category: string, draft: Draft): BrandPublicContent => ({
  description: draft.description,
  story: draft.story,
  tastingNotes: [
    { title: draft.notes[0], description: draft.notes[1] },
    { title: draft.notes[2], description: draft.notes[3] },
  ],
  howToEnjoy: [
    { subheading: "Serve", description: draft.serve },
    { subheading: "Food", description: draft.food },
  ],
  pairingIdeas: [{ title: `With ${name}`, items: draft.pairings }],
  whyChoose: draft.whyChoose,
  faqs: [
    { question: draft.faq[0], answer: draft.faq[1] },
    { question: draft.faq[2], answer: draft.faq[3] },
  ],
  finalVerdict: draft.finalVerdict,
  metaTitle: draft.metaTitle ?? `${name} ${category} Guide | BevOry`,
  metaDescription: draft.metaDescription,
});

export const BRAND_CONTENT_BATCH_46: Record<string, BrandPublicContent> = {
  "alter-ego": guide("Alter Ego de Palmer", "Wine", {
    description: "Alter Ego de Palmer is a Margaux red made by Chateau Palmer in Bordeaux. Merlot often leads its blend, with Cabernet Sauvignon bringing structure from the estate's gravelly soils.",
    story: "Palmer treats Alter Ego as a distinct expression of the estate rather than leftover fruit from its grand vin. The wine is shaped to show Margaux's supple texture earlier in its life.",
    notes: ["Red fruit", "Red and black berries sit at the centre of its Merlot-led profile.", "Texture", "Fine tannins give the wine the soft, powdery feel associated with Margaux."],
    serve: "Open an hour before dinner and pour into a large Bordeaux glass.",
    food: "Try it with galouti kebabs, lamb chops or mushroom pulao.",
    pairings: ["galouti kebabs", "lamb chops", "mushroom pulao"],
    whyChoose: "A Margaux red with Palmer's estate character and a more approachable young texture.",
    faq: ["Who makes Alter Ego de Palmer?", "Chateau Palmer makes it in Margaux, Bordeaux.", "Is Alter Ego always Merlot-only?", "No. Its blend varies by vintage, although Merlot often leads."],
    finalVerdict: "Alter Ego brings Palmer's fine-grained Margaux style to a dinner table without demanding decades of patience.",
    metaDescription: "Explore Alter Ego de Palmer from Margaux, its Merlot-led style, food pairings and city prices on BevOry.",
  }),
  arna: guide("Arna", "Beer", {
    description: "Arna is a Nepalese beer from Yeti Brewery, launched in 2015. Its range includes lighter lager and stronger beer styles.",
    story: "Yeti Brewery built Arna around a Nepalese identity and a buffalo emblem. The name has grown from one beer into a range with different strengths and serves.",
    notes: ["Lager", "The lighter beer is crisp, with grain and a restrained hop edge.", "Strong", "Arna Strong brings a fuller malt impression than the lighter lager."],
    serve: "Chill well and pour into a clean tall glass to keep the head lively.",
    food: "Its carbonation works with chicken momos, sekuwa or chilli potatoes.",
    pairings: ["chicken momos", "sekuwa", "chilli potatoes"],
    whyChoose: "A Nepal-born beer range whose light and strong bottles suit different plates.",
    faq: ["Where is Arna beer from?", "Yeti Brewery produces Arna in Nepal.", "Does Arna make more than one beer?", "Yes. The range includes light and strong styles."],
    finalVerdict: "Arna is most at home beside hot, salty food and a cold glass.",
    metaDescription: "Meet Nepal's Arna beer, its light and strong styles, snack pairings and city prices on BevOry.",
  }),
  attitude: guide("Attitude", "Wine", {
    description: "Attitude Sauvignon Blanc is a Loire Valley wine made by Pascal Jolivet. Its fruit comes from the Touraine area around Chemery, where limestone, clay and flint shape the vineyards.",
    story: "Jolivet is known for Loire Sauvignon Blanc from Sancerre and Pouilly-Fume. For Attitude, sorted grapes ferment in temperature-controlled stainless steel and spend time on fine lees.",
    notes: ["Citrus", "Lime and green apple keep the first impression brisk.", "Finish", "A mineral edge follows the fruit into a long, dry finish."],
    serve: "Serve chilled at around 10 C in a white-wine glass.",
    food: "Pair with tandoori fish, grilled prawns or goat-cheese salad.",
    pairings: ["tandoori fish", "grilled prawns", "goat-cheese salad"],
    whyChoose: "Pascal Jolivet's Loire Sauvignon Blanc offers clean citrus and a clear sense of place.",
    faq: ["Who makes Attitude Sauvignon Blanc?", "Pascal Jolivet makes it in France's Loire Valley.", "Is Attitude aged in oak?", "The Sauvignon Blanc is vinified in stainless steel and aged on fine lees."],
    finalVerdict: "Attitude is a sharp, food-friendly Loire white for fish and fresh herbs.",
    metaDescription: "Explore Pascal Jolivet Attitude Sauvignon Blanc, Loire tasting notes, pairings and city prices on BevOry.",
  }),
  aussieres: guide("Aussieres", "Wine", {
    description: "Aussieres is a Languedoc wine estate owned by Domaines Barons de Rothschild (Lafite). Its A d'Aussieres Chardonnay comes from cool parcels near the Fontfroide foothills south of Narbonne.",
    story: "Baron Eric de Rothschild bought the neglected property in 1999. The Chardonnay is harvested before daylight, fermented cool in stainless steel and partly rested on lees.",
    notes: ["Chardonnay", "The cool-picked fruit keeps the white wine fresh rather than heavily oaked.", "Lees", "A short lees rest gives the mid-palate a little roundness."],
    serve: "Chill the Chardonnay, then let it warm slightly in the glass at the table.",
    food: "Serve with malai tikka, butter-poached prawns or mushroom risotto.",
    pairings: ["malai tikka", "butter-poached prawns", "mushroom risotto"],
    whyChoose: "A Languedoc Chardonnay tied to a named estate and cool-parcel winemaking.",
    faq: ["Who owns Domaine d'Aussieres?", "It is part of Domaines Barons de Rothschild (Lafite).", "Where is A d'Aussieres Chardonnay made?", "The estate sits south of Narbonne in France's Languedoc region."],
    finalVerdict: "Aussieres Chardonnay puts freshness first, with just enough texture for a rich starter.",
    metaDescription: "Explore Aussieres Chardonnay from Languedoc, its cool-fermented style, food matches and city prices on BevOry.",
  }),
  "bad-boy": guide("Bad Boy", "Wine", {
    description: "Bad Boy is a Bordeaux red from Jean-Luc Thunevin, the winemaker behind Chateau Valandraud. The name grew from the 'bad boy' nickname attached to his unconventional Bordeaux work.",
    story: "Thunevin created the cuvee under the broader Bordeaux appellation when its blend did not fit the local conventions of his Saint-Emilion projects. That decision made the label's rebellious name part of the wine's actual history.",
    notes: ["Dark fruit", "Merlot-led Bordeaux fruit gives a ripe plum and black-cherry direction.", "Finish", "The red holds enough tannin to stand beside a substantial main course."],
    serve: "Pour into a roomy red-wine glass and give it air while dinner is prepared.",
    food: "Match with mutton seekh, roast duck or mushroom keema.",
    pairings: ["mutton seekh", "roast duck", "mushroom keema"],
    whyChoose: "A Bordeaux red with a real Jean-Luc Thunevin backstory behind the name.",
    faq: ["Who makes Bad Boy wine?", "Bordeaux winemaker Jean-Luc Thunevin created it.", "Is Bad Boy from Saint-Emilion?", "It was created as a Bordeaux-appellation wine rather than a Saint-Emilion bottling."],
    finalVerdict: "Bad Boy is a generous Bordeaux red for food with smoke, spice and depth.",
    metaDescription: "Discover Jean-Luc Thunevin's Bad Boy Bordeaux, its history, red-wine style and city prices on BevOry.",
  }),
  bodkin: guide("Bodkin", "Wine", {
    description: "Bodkin is a California wine project founded by winemaker Chris Christensen. Sauvignon Blanc is central to the range, including still and sparkling expressions.",
    story: "Christensen started Bodkin in 2011 and made a sparkling Sauvignon Blanc the following year. His wines lean toward bright acidity and a lighter touch rather than heavy extraction.",
    notes: ["Sauvignon Blanc", "Citrus and a lively acid line define the still white style.", "Sparkling", "The sparkling bottling brings bubbles to the grape's tart, green-fruit side."],
    serve: "Chill the still wine well; pour the sparkling version into a white-wine glass rather than a narrow flute.",
    food: "Its acidity suits tandoori prawns, lemon chicken or herbed paneer.",
    pairings: ["tandoori prawns", "lemon chicken", "herbed paneer"],
    whyChoose: "An independent California winery that made sparkling Sauvignon Blanc its calling card.",
    faq: ["Who founded Bodkin Wines?", "Winemaker Chris Christensen founded Bodkin in 2011.", "Does Bodkin make sparkling Sauvignon Blanc?", "Yes. Christensen first made that style in 2012."],
    finalVerdict: "Bodkin is a lively Sauvignon Blanc choice when the meal needs a clean acid lift.",
    metaDescription: "Explore Bodkin Sauvignon Blanc from California, sparkling and still styles, pairings and city prices on BevOry.",
  }),
  bootz: guide("Bootz", "Spirits", {
    description: "Bootz is a Dutch spirits name in the Lucas Bols portfolio. Its range has included dark rum and Dutch brandy, two different bottles with a shared label history.",
    story: "Bootz became known in the Netherlands for its long-running spirits business before joining the Bols group. The brand's rum later found a market in India as well as at home.",
    notes: ["Dark rum", "The darker rum style brings molasses-led sweetness to mixed drinks.", "Grape brandy", "The brandy bottle shifts the range toward grape spirit and a warmer after-dinner pour."],
    serve: "Use dark rum with cola and lime; pour the grape brandy in a small tulip glass.",
    food: "Try rum with pepper chicken or caramel pudding, and brandy with roasted almonds.",
    pairings: ["pepper chicken", "caramel pudding", "roasted almonds"],
    whyChoose: "A Dutch spirits label with both rum and brandy in its established range.",
    faq: ["Who owns Bootz spirits?", "Bootz is part of the Lucas Bols portfolio.", "Is Bootz only a rum?", "No. Its range has included rum and Dutch grape brandy."],
    finalVerdict: "Bootz is best chosen by the spirit in the bottle: rum for a mixer, brandy for a slow pour.",
    metaDescription: "Explore Bootz Dutch rum and brandy, serving ideas, food pairings and city prices on BevOry.",
  }),
  butlers: guide("Butlers", "Liqueur", {
    description: "Butlers is a South African cocktail-liqueur range with Espresso, Blue Curacao and Triple Sec among its flavours. Each bottle has a specific mixing job, from coffee depth to orange brightness.",
    story: "The brand redesigned its bottles in 2009 for bar use. Its nine-flavour range also includes Cherry Kirsch, peppermint, strawberry and ginger.",
    notes: ["Espresso", "Coffee bitterness and sweetness add body to an after-dinner cocktail.", "Triple Sec", "Orange peel brings a citrus lift to sours and tall drinks."],
    serve: "Shake Espresso with vodka and fresh coffee; use a smaller measure of Triple Sec in a Margarita.",
    food: "Serve coffee cocktails with chocolate tart, or orange-led drinks with chilli prawns.",
    pairings: ["chocolate tart", "chilli prawns", "salted almonds"],
    whyChoose: "A practical set of cocktail liqueurs with clearly different flavour roles.",
    faq: ["Where is Butlers liqueur from?", "Butlers is a South African cocktail-liqueur brand.", "Does Butlers make Blue Curacao?", "Yes. Blue Curacao is one of its nine flavours."],
    finalVerdict: "Butlers earns its place behind the bar by doing one flavour job well per bottle.",
    metaDescription: "Explore Butlers Espresso, Triple Sec and Blue Curacao, cocktail ideas and city prices on BevOry.",
  }),
  "condesa-de-leganza": guide("Condesa de Leganza", "Wine", {
    description: "Condesa de Leganza is a Spanish wine label with a rosado from Bodegas Leganza. The pink wine brings a fresh, dry option to the producer's La Mancha range.",
    story: "The winery sits in La Mancha, where hot days make picking and cellar timing important to a lively rose. Its Seleccion de Familia rosado is built for the table rather than a sweet dessert finish.",
    notes: ["Fruit", "The rose shows red-fruit freshness rather than dark-red weight.", "Finish", "A dry, lightly savoury finish keeps the wine ready for food."],
    serve: "Chill the rosado and pour into a small white-wine glass.",
    food: "Pair with paneer tikka, grilled calamari or tomato bruschetta.",
    pairings: ["paneer tikka", "grilled calamari", "tomato bruschetta"],
    whyChoose: "A Spanish rose whose dry shape makes it easy to bring to a savoury meal.",
    faq: ["Where is Condesa de Leganza made?", "Bodegas Leganza makes the wine in Spain's La Mancha region.", "Is Condesa de Leganza Rosado a red wine?", "No. Rosado is the Spanish term for rose wine."],
    finalVerdict: "Condesa de Leganza Rosado fits a warm evening with grilled food and no heavy sauce.",
    metaDescription: "Explore Condesa de Leganza Rosado from La Mancha, tasting notes, pairings and city prices on BevOry.",
  }),
  "dr-schmitt": guide("Dr Schmitt", "Wine", {
    description: "Dr Schmitt is a German wine label from Schmitt Sohne. Its Riesling QbA and Pinot Noir bottles show the producer's white and red grape work.",
    story: "Schmitt Sohne is a family wine company in Germany's Mosel region. The Dr Schmitt Riesling label draws on grapes from Mosel or Rheinhessen, depending on the bottle.",
    notes: ["Riesling", "Green-fruit acidity keeps the white lively beside spice.", "Pinot Noir", "The red is lighter in tannin than a Cabernet-led wine."],
    serve: "Serve Riesling cold; give Pinot Noir a light chill rather than room warmth.",
    food: "Riesling suits fish tikka; Pinot Noir works with mushroom kebabs or roast chicken.",
    pairings: ["fish tikka", "mushroom kebabs", "roast chicken"],
    whyChoose: "A German range that lets Riesling and Pinot Noir answer two very different dinners.",
    faq: ["Who makes Dr Schmitt wine?", "German producer Schmitt Sohne makes the label.", "Is Dr Schmitt Riesling from one region?", "The producer lists Mosel or Rheinhessen fruit for its Riesling QbA."],
    finalVerdict: "Choose Dr Schmitt by grape: Riesling for heat and Pinot Noir for a lighter red course.",
    metaDescription: "Explore Dr Schmitt Riesling and Pinot Noir from Germany, serving ideas and city prices on BevOry.",
  }),
  "glen-flagler": guide("Glen Flagler", "Whisky", {
    description: "Glen Flagler was a Lowland single malt made at the Moffat distilling complex in Airdrie, Scotland. Original bottles come from a distillery that no longer operates.",
    story: "Inver House built the malt operation in the 1960s beside the Garnheath grain distillery. Glen Flagler supplied blends as well as its own single-malt bottlings before closing in 1985.",
    notes: ["Lowland malt", "The malt's old bottlings are known for a lighter style than heavily peated island whisky.", "Mature bottle", "Long bottle age makes preservation and provenance especially important to the drinking experience."],
    serve: "Pour a small measure neat in a tulip glass; give an older bottle time to settle after opening.",
    food: "Keep the plate quiet: roasted almonds, mild cheddar or butter biscuits.",
    pairings: ["roasted almonds", "mild cheddar", "butter biscuits"],
    whyChoose: "A rare glimpse of the short-lived Moffat malt distillery in Scotland's Lowlands.",
    faq: ["Is Glen Flagler still made?", "No. The Airdrie distillery closed in 1985.", "Was Glen Flagler a Highland whisky?", "No. The distillery stood in Scotland's Lowland region."],
    finalVerdict: "Glen Flagler is a historical malt best approached slowly, with attention to the particular bottling.",
    metaDescription: "Explore Glen Flagler Lowland single malt, its Moffat history, serving ideas and city prices on BevOry.",
  }),
  "grand-sud": guide("Grand Sud", "Wine", {
    description: "Grand Sud is a French varietal wine range from Les Grands Chais de France. Syrah and Sauvignon Blanc place red and white southern-French grapes under the same label.",
    story: "The producer works with partner growers across southern France. Grand Sud became known for generous one-litre bottles intended for the shared table.",
    notes: ["Syrah", "Dark fruit and pepper make the red a good match for charred food.", "Sauvignon Blanc", "The white brings citrus and herb freshness to a cold serve."],
    serve: "Give Syrah a large red glass; chill Sauvignon Blanc before pouring.",
    food: "Match the red with tandoori mushrooms and the white with coriander fish or grilled prawns.",
    pairings: ["tandoori mushrooms", "coriander fish", "grilled prawns"],
    whyChoose: "A southern-French range built around recognisable grapes and generous table bottles.",
    faq: ["Who makes Grand Sud wine?", "Les Grands Chais de France makes Grand Sud.", "Does Grand Sud include white wine?", "Yes. Sauvignon Blanc is among its white-wine bottles."],
    finalVerdict: "Grand Sud is an easy way to pick a southern-French red or white for a large meal.",
    metaDescription: "Explore Grand Sud Syrah and Sauvignon Blanc, southern-French styles, pairings and city prices on BevOry.",
  }),
  hanacka: guide("Hanacka", "Vodka", {
    description: "Hanacka is a Czech vodka with roots in the Haná region of Moravia. Its name carries that regional connection rather than borrowing a Russian identity.",
    story: "The brand presents a long Czech distilling tradition and now also makes ready-to-mix flavoured drinks. The plain vodka remains the clean base for cold, simple serves.",
    notes: ["Plain vodka", "The unflavoured bottle keeps the palate spare and the finish clean.", "Mixed drinks", "A neutral base lets citrus and soda take the lead without fighting the spirit."],
    serve: "Serve freezer-cold in a small glass, or lengthen with soda and fresh lemon.",
    food: "A cold pour cuts through smoked fish, potato pancakes or chilli paneer.",
    pairings: ["smoked fish", "potato pancakes", "chilli paneer"],
    whyChoose: "A Czech vodka with a place-name identity rooted in Moravia.",
    faq: ["Where is Hanacka vodka from?", "It is a Czech vodka named for the Haná region of Moravia.", "Is Hanacka only sold as plain vodka?", "The brand also presents flavoured ready-to-mix drinks."],
    finalVerdict: "Hanacka works best cold, simple and alongside salty food.",
    metaDescription: "Meet Hanacka vodka from Czech Moravia, cold-serve ideas, food pairings and city prices on BevOry.",
  }),
  hichki: guide("Hichki", "Gin", {
    description: "Hichki is an Indian gin sold in Tamil Nadu. It gives a local gin option for a classic tonic or citrus-led mixed drink.",
    story: "Hichki means 'hiccup' in Hindi, a playful name for a dry spirit. The gin appears in Tamil Nadu's retail range, where it joins a growing selection of Indian-made bottles.",
    notes: ["Juniper", "A gin-and-tonic serve puts the expected dry juniper edge in focus.", "Citrus", "Lemon peel and tonic brighten the spirit without adding syrup."],
    serve: "Build a gin and tonic over plenty of ice with a strip of lemon peel.",
    food: "Use the cold, bitter highball with pepper prawns, pakoras or masala peanuts.",
    pairings: ["pepper prawns", "pakoras", "masala peanuts"],
    whyChoose: "An Indian gin with a memorable Hindi name and a straightforward tonic serve.",
    faq: ["Is Hichki a gin?", "Yes. Hichki Gin appears in Tamil Nadu retail records.", "What does Hichki mean?", "Hichki is the Hindi word for a hiccup."],
    finalVerdict: "Hichki fits the straightforward gin-and-tonic slot beside spicy snacks.",
    metaDescription: "Explore Hichki Gin from India, simple tonic serves, Indian snack pairings and city prices on BevOry.",
  }),
  invincible: guide("Invincible", "Vodka", {
    description: "Invincible is an Indian grain vodka from Octaga Green. Its Himalayan grain sourcing is central to the bottle's identity, and the plain spirit suits chilled pours and long drinks.",
    story: "The brand presents an eight-column distillation process and a clean finish rather than added fruit flavour. Its mountain imagery carries that grain-and-place story onto the bottle.",
    notes: ["Grain", "The base spirit aims for a soft grain texture rather than a flavoured-vodka finish.", "Cold serve", "Chilling keeps the pour crisp and the aftertaste restrained."],
    serve: "Chill thoroughly or pour over ice with soda and a squeezed lime wedge.",
    food: "Try it with tandoori prawns, fried paneer or salted cashews.",
    pairings: ["tandoori prawns", "fried paneer", "salted cashews"],
    whyChoose: "An Indian vodka whose grain base and Himalayan identity are central to its presentation.",
    faq: ["Where is Invincible vodka made?", "Invincible is an Indian vodka.", "Is Invincible a flavoured vodka?", "The core bottle is presented as a plain grain vodka."],
    finalVerdict: "Invincible is a clean vodka choice for a chilled, citrus-led serve.",
    metaDescription: "Explore Invincible Indian grain vodka, cold serves, food pairings and city prices on BevOry.",
  }),
  jnoon: guide("J'NOON", "Wine", {
    description: "J'NOON is an Indian wine collaboration between Fratelli Wines and Jean-Charles Boisset. Its red and white wines use grapes grown near Akluj in Maharashtra.",
    story: "Kapil Sekhri and Boisset developed the range to bring Fratelli's estate fruit to a wider fine-wine audience. The name draws on the Urdu word junoon, or passion.",
    notes: ["White", "The white leans on orchard fruit and acidity for a food-led pour.", "Red", "The red brings darker fruit and more tannic weight to the same estate story."],
    serve: "Chill the white; give the red a larger glass and a little air before dinner.",
    food: "Pair white with tandoori fish and red with lamb seekh or roasted mushrooms.",
    pairings: ["tandoori fish", "lamb seekh", "roasted mushrooms"],
    whyChoose: "A named Fratelli-Boisset collaboration made from Maharashtra-grown grapes.",
    faq: ["Who created J'NOON wine?", "Fratelli Wines and Jean-Charles Boisset created the range together.", "Where are J'NOON grapes grown?", "The collaboration uses fruit from Fratelli's vineyards near Akluj, Maharashtra."],
    finalVerdict: "J'NOON shows how an Akluj-grown red or white can take its place at a serious dinner.",
    metaDescription: "Discover J'NOON wines from Fratelli and Boisset, Akluj origins, pairings and city prices on BevOry.",
  }),
  "lions-de-batailley": guide("Lions de Batailley", "Wine", {
    description: "Lions de Batailley is the second wine of Chateau Batailley in Pauillac, Bordeaux. Its name refers to the two stone lions at the estate gate.",
    story: "The first Lions de Batailley vintage was 2014. The Casteja family's estate uses it to show Pauillac fruit with a more approachable young texture than the grand vin.",
    notes: ["Fruit", "Blackcurrant and dark cherry lead the red-fruit and black-fruit profile.", "Structure", "Cabernet-led Pauillac tannin carries the wine through a long savoury meal."],
    serve: "Decant a young bottle briefly and pour into Bordeaux glasses.",
    food: "Match with mutton rogan josh, grilled lamb chops or mushroom pie.",
    pairings: ["mutton rogan josh", "grilled lamb chops", "mushroom pie"],
    whyChoose: "Pauillac character from a named classified estate in a more accessible second wine.",
    faq: ["Who makes Lions de Batailley?", "Chateau Batailley makes it in Pauillac.", "What do the lions in the name represent?", "They refer to the lions at the entrance to the chateau."],
    finalVerdict: "Lions de Batailley brings the estate's Bordeaux structure to a table built around roast or spice.",
    metaDescription: "Explore Lions de Batailley from Pauillac, estate history, food pairings and city prices on BevOry.",
  }),
  mooz: guide("Moooz", "Vodka", {
    description: "Moooz Sparkle is an Indian vodka from the Adie Broswon group. Its name and presentation place it in the contemporary plain-vodka market.",
    story: "The group introduced Moooz Sparkle to Delhi's drinks trade as a triple-distilled vodka. The brand keeps its focus on a straightforward cold serve rather than a fruit-flavoured range.",
    notes: ["Plain vodka", "The spirit is intended to be clean and neutral enough for citrus mixers.", "Texture", "Three distillations aim for a smooth, uncluttered sip."],
    serve: "Use plenty of ice, soda and a fresh lime wedge; avoid a sweet mixer if serving with food.",
    food: "Pair with crispy lotus stem, paneer tikka or chilli chicken.",
    pairings: ["crispy lotus stem", "paneer tikka", "chilli chicken"],
    whyChoose: "A contemporary Indian vodka with a documented triple-distilled production claim.",
    faq: ["Who makes Moooz Sparkle vodka?", "It comes from the Adie Broswon group in India.", "Is Moooz Sparkle flavoured?", "The Sparkle bottle is presented as plain vodka."],
    finalVerdict: "Moooz Sparkle makes sense in a tall, cold drink with lime and a salty snack.",
    metaDescription: "Explore Moooz Sparkle Indian vodka, simple mixers, food matches and city prices on BevOry.",
  }),
  nicobar: guide("Nicobar", "Gin", {
    description: "Nicobar is an Indian dry gin built around juniper and a nine-ingredient botanical recipe. The ship on its bottle ties its spice theme to the sea routes of the Indian Ocean.",
    story: "The brand uses the Nicobar name and maritime artwork to frame its gin. Its producer puts juniper first and describes the remaining botanicals as a supporting cast.",
    notes: ["Juniper", "The classic piney gin note stays at the centre of the spirit.", "Botanicals", "A broader botanical mix rounds the dry base without turning it into a sweet liqueur."],
    serve: "Try a tonic with lemon peel, or a gin Rickey with lime and soda.",
    food: "Serve with tandoori prawns, coriander chicken or lime-dressed cucumber.",
    pairings: ["tandoori prawns", "coriander chicken", "lime-dressed cucumber"],
    whyChoose: "An Indian gin with a clear juniper core and a maritime visual identity.",
    faq: ["Is Nicobar an Indian gin?", "Yes. Nicobar is marketed as an Indian dry gin.", "Does Nicobar work in a gin and tonic?", "The producer lists a lemon-peel gin and tonic among its serves."],
    finalVerdict: "Nicobar is at its clearest with tonic, citrus and food from the grill.",
    metaDescription: "Explore Nicobar Indian dry gin, juniper notes, tonic serves and city prices on BevOry.",
  }),
  ottos: guide("Otto's Athens Vermouth", "Vermouth", {
    description: "Otto's Athens Vermouth is a Greek wine-based aperitif infused with rose petals, wormwood, citrus and local herbs. Olive leaves and oregano give it a distinctly Athenian botanical direction.",
    story: "Its makers draw on Greek wine and herbs rather than copying an Italian vermouth formula. The wine base carries the botanicals into a drink suited to both ice and cocktails.",
    notes: ["Floral", "Rose petals soften the herbal nose.", "Bitter herbs", "Wormwood and oregano give the finish its aperitif bite."],
    serve: "Pour over ice with an orange slice, or use a small measure in a Negroni variation.",
    food: "Set it beside olives, grilled halloumi or tandoori mushrooms.",
    pairings: ["olives", "grilled halloumi", "tandoori mushrooms"],
    whyChoose: "A Greek vermouth where olive leaf and oregano genuinely shape the recipe.",
    faq: ["What is Otto's Athens Vermouth made from?", "It starts with Greek wine infused with herbs, citrus, rose and wormwood.", "Is Otto's a gin?", "No. It is a wine-based vermouth."],
    finalVerdict: "Otto's turns a glass of ice into a properly herbal, floral aperitif.",
    metaDescription: "Discover Otto's Athens Vermouth, Greek botanicals, aperitif serves and city prices on BevOry.",
  }),
  pursue: guide("Pursue", "Hard Seltzer", {
    description: "Pursue is an Indian hard-seltzer range with flavours such as Peach & White Tea, Strawberry & Rose and Mango & Chilli. Its light, sparkling format takes a different route from a spirit and mixer poured at the bar.",
    story: "The Chennai-based brand built its range around fruit-and-botanical pairings. Mosambi & Mint and Elderflower & Yuzu sit alongside its better-known fruit flavours.",
    notes: ["Peach & White Tea", "Soft peach fruit meets a gentle tea note.", "Mango & Chilli", "Ripe mango leads before a peppery kick."],
    serve: "Chill the can and pour over ice only if you want a longer, softer fizz.",
    food: "Peach suits tandoori chicken, while Mango & Chilli meets crispy lotus stem or fried prawns.",
    pairings: ["tandoori chicken", "crispy lotus stem", "fried prawns"],
    whyChoose: "A local hard-seltzer range with deliberately paired fruit and botanical flavours.",
    faq: ["Is Pursue a hard seltzer?", "Yes. Pursue sells flavoured hard seltzers in India.", "Does Pursue make a peach flavour?", "Peach & White Tea is one of its listed variants."],
    finalVerdict: "Pursue is the chilled, fizzy option when a full cocktail feels too heavy.",
    metaDescription: "Explore Pursue hard seltzers, Peach & White Tea and Mango & Chilli flavours, pairings and city prices on BevOry.",
  }),
  rasa: guide("Rasa", "Wine", {
    description: "Rasa is Sula Vineyards' Indian red-wine collection from Maharashtra. Cabernet Sauvignon, Syrah and Zinfandel give the range three different grape-led directions.",
    story: "Sula developed Rasa as a more focused red-wine line within its Nashik estate portfolio. The three named grapes let a drinker move from Cabernet structure to Syrah spice or Zinfandel fruit.",
    notes: ["Cabernet Sauvignon", "Black-fruit depth and firmer tannin suit a long main course.", "Zinfandel", "Riper berry fruit gives this red a rounder, more generous direction."],
    serve: "Pour into a broad red-wine glass and give the Cabernet a little air.",
    food: "Cabernet suits mutton rogan josh; Zinfandel works with barbecue chicken or spiced paneer.",
    pairings: ["mutton rogan josh", "barbecue chicken", "spiced paneer"],
    whyChoose: "A Sula red range that makes the choice between three grapes meaningful at the table.",
    faq: ["Who makes Rasa wine?", "Sula Vineyards makes Rasa in India.", "Which grapes appear in the Rasa range?", "Its red range includes Cabernet Sauvignon, Syrah and Zinfandel."],
    finalVerdict: "Rasa is strongest when chosen by the grape that fits dinner, not just by the black label.",
    metaDescription: "Explore Sula Rasa Cabernet, Syrah and Zinfandel from Nashik, food pairings and city prices on BevOry.",
  }),
  "seven-hills": guide("Seven Hills", "Gin", {
    description: "Seven Hills is an Italian gin distilled at Torino Distillati in Piedmont. Its seven-botanical recipe includes juniper, celery, rosehip, pomegranate, chamomile, blood orange and artichoke.",
    story: "The name nods to Rome's seven hills while the spirit is made near Turin. Low-pressure distillation is used to draw flavour from its unusual herb-and-fruit mix.",
    notes: ["Citrus", "Blood orange brings a rounded citrus note to the juniper base.", "Herbs", "Celery and artichoke give the gin a savoury counterpoint."],
    serve: "Use a plain tonic and orange peel, keeping the mixer light enough for the botanicals to show.",
    food: "Pair with olives, tandoori mushrooms or grilled prawns.",
    pairings: ["olives", "tandoori mushrooms", "grilled prawns"],
    whyChoose: "An Italian gin with seven named botanicals, including artichoke and blood orange.",
    faq: ["Where is Seven Hills Gin made?", "Torino Distillati makes it in Piedmont, Italy.", "Is Seven Hills a juniper gin?", "Yes. Juniper is one of its seven botanicals."],
    finalVerdict: "Seven Hills gives a gin and tonic a savoury Italian turn without hiding the juniper.",
    metaDescription: "Explore Seven Hills Italian gin, its seven botanicals, tonic serves and city prices on BevOry.",
  }),
  "six-brothers": guide("Six Brothers", "Mahua Spirit", {
    description: "Six Brothers is an Indian spirit made from mahua flowers by South Seas Distilleries in Dahanu, Maharashtra. The range includes Small Batch and 1922 Resurrection.",
    story: "The distilling family traces its work to the early twentieth century. Six Brothers draws on that legacy to give mahua, a flower long fermented in India, a modern bottled expression.",
    notes: ["Flower", "Mahua gives the spirit a gentle floral core rather than a grain-whisky profile.", "Pot still", "The Small Batch expression is double-distilled in copper pot stills."],
    serve: "Try a small neat pour first, then add a cube if a cooler glass suits the meal.",
    food: "Match with smoked paneer, mutton seekh or jaggery-sweetened nuts.",
    pairings: ["smoked paneer", "mutton seekh", "jaggery-sweetened nuts"],
    whyChoose: "A Dahanu-made mahua spirit linked to a century-old Indian distilling family.",
    faq: ["What is Six Brothers made from?", "Its Mahura spirit is made from mahua flowers.", "Where is Six Brothers distilled?", "South Seas Distilleries is based in Dahanu, Maharashtra."],
    finalVerdict: "Six Brothers is a distinctly Indian flower spirit worth tasting on its own before mixing.",
    metaDescription: "Discover Six Brothers Mahura from Dahanu, its flower-spirit style, pairings and city prices on BevOry.",
  }),
  "tommy-bahama": guide("Tommy Bahama", "Spirits", {
    description: "Tommy Bahama Spirits extends the American lifestyle brand into vodka, bourbon, rum and rye-based drinks. The bottles have very different bases despite their shared island-inspired name.",
    story: "The spirits project was taken to market by Coral Cay Beverage Group. Tommy Bahama restaurants also use the branded bourbon, vodka and rye in their own cocktails.",
    notes: ["Cucumber vodka", "Cucumber gives the vodka a green, cooling direction for tall drinks.", "Bourbon", "The whiskey brings a warmer oak-and-grain centre to stirred cocktails."],
    serve: "Use cucumber vodka with soda and lime; stir bourbon over ice with a dash of bitters.",
    food: "Vodka suits grilled prawns, while bourbon meets barbecue chicken or pecan pie.",
    pairings: ["grilled prawns", "barbecue chicken", "pecan pie"],
    whyChoose: "A multi-spirit American range where the bottle, not the shared branding, decides the serve.",
    faq: ["Does Tommy Bahama make bourbon?", "Yes. Bourbon is part of its spirits range.", "Is Tommy Bahama only a rum brand?", "No. The range also includes vodka, gin, bourbon and rye-based drinks."],
    finalVerdict: "Tommy Bahama works best when the chosen spirit matches the drink rather than the beach imagery.",
    metaDescription: "Explore Tommy Bahama vodka, bourbon and rum, cocktail serves, food matches and city prices on BevOry.",
  }),
  "white-fox": guide("White Fox", "Vodka", {
    description: "White Fox is an Indian vodka from SOM Group. Its plain vodka is triple-distilled, while a Green Apple bottle adds a fruit-led option.",
    story: "SOM makes the range in India and puts the distillation process on the plain-vodka label. The flavoured expression is designed for colder, lighter mixes.",
    notes: ["Plain vodka", "The triple-distilled spirit aims for a clean, spare finish.", "Green Apple", "The flavoured bottle adds tart orchard fruit to the vodka base."],
    serve: "Chill the plain vodka well; serve Green Apple with soda rather than a sugary mixer.",
    food: "Try the plain bottle with chilli paneer and the apple one with crispy lotus stem.",
    pairings: ["chilli paneer", "crispy lotus stem", "salted cashews"],
    whyChoose: "A locally made vodka with both unflavoured and green-apple directions.",
    faq: ["Who makes White Fox vodka?", "SOM Group makes White Fox in India.", "Is White Fox Green Apple plain vodka?", "No. It is the brand's apple-flavoured expression."],
    finalVerdict: "White Fox covers a clean vodka pour and an apple-led highball under one label.",
    metaDescription: "Explore White Fox plain and Green Apple vodka from India, serving ideas and city prices on BevOry.",
  }),
  "white-birch": guide("White Birch", "Vodka", {
    description: "White Birch is a Siberian wheat vodka. Its name and birch-tree bottle design place its Russian origin at the centre of the brand.",
    story: "The producer describes a traditional Siberian approach to distillation. Wheat gives the plain vodka its base before it reaches the distinctive clear bottle.",
    notes: ["Wheat", "The grain base gives the spirit a soft, rounded feel.", "Cold finish", "Serving it well chilled keeps the finish clean and restrained."],
    serve: "Pour freezer-cold in a small glass or over ice with a strip of lemon zest.",
    food: "Match with smoked fish, potato cutlets or dill cucumber salad.",
    pairings: ["smoked fish", "potato cutlets", "dill cucumber salad"],
    whyChoose: "A Russian wheat vodka with an explicit Siberian production identity.",
    faq: ["Where is White Birch vodka from?", "White Birch is a Russian vodka associated with Siberia.", "What grain does White Birch use?", "The brand describes its classic vodka as wheat-based."],
    finalVerdict: "White Birch asks for a cold glass and a simple, savoury plate.",
    metaDescription: "Explore White Birch Siberian wheat vodka, cold serves, food pairings and city prices on BevOry.",
  }),
  zappa: guide("Zappa", "Sambuca", {
    description: "Zappa is a South African sambuca range sold in colours including Blue, Black, Red and Green. Its Blue bottle is an anise-led liqueur designed for small, cold serves.",
    story: "The label grew as a colourful shooter in South Africa's bar scene. The different colours make it easy to recognise on a back bar, while sambuca remains the shared style.",
    notes: ["Anise", "Liquorice-like anise leads the sweet liqueur profile.", "Blue", "The Blue expression keeps that sambuca sweetness in a vividly coloured bottle."],
    serve: "Chill before pouring a small measure; it can also be floated into a dessert cocktail.",
    food: "Use after dinner with dark chocolate, almond biscotti or coffee ice cream.",
    pairings: ["dark chocolate", "almond biscotti", "coffee ice cream"],
    whyChoose: "A South African sambuca label with a recognisable colour-coded range.",
    faq: ["What kind of drink is Zappa Blue?", "It is a blue sambuca-style liqueur.", "Where is Zappa from?", "Zappa is a South African liqueur brand."],
    finalVerdict: "Zappa Blue is a sweet anise finish to a meal, best served in a small glass.",
    metaDescription: "Explore Zappa Blue Sambuca from South Africa, anise notes, dessert pairings and city prices on BevOry.",
  }),
  "gracia-viva-agave": guide("Gracia Viva Agave", "Agave Spirit", {
    description: "Gracia Viva Agave is an agave-spirit range from Kantala Spirits in Goa. Wildly Raw and Yuzzu are two distinct expressions, one herbal and peppery, the other citrus-led.",
    story: "Suzann Homan named the project Gracia, the Spanish word for grace. The Goan range was built around flavoured agave drinks rather than a single blanco-style bottle.",
    notes: ["Wildly Raw", "Herbal notes and delicate pepper give this expression a warm edge.", "Yuzzu", "Lime and orange zest brighten the citrus-infused agave spirit."],
    serve: "Sip Wildly Raw over ice; mix Yuzzu with soda, lime and a small piece of ginger.",
    food: "Wildly Raw suits chilli paneer, while Yuzzu pairs with grilled prawns or fish tacos.",
    pairings: ["chilli paneer", "grilled prawns", "fish tacos"],
    whyChoose: "A Goan agave project whose two expressions offer clearly different herbal and citrus profiles.",
    faq: ["Where is Gracia Viva Agave from?", "Kantala Spirits developed the range in Goa.", "What does Gracia Yuzzu taste like?", "The producer describes lime and orange-zest notes."],
    finalVerdict: "Gracia makes an agave highball more interesting by letting the chosen flavour do the work.",
    metaDescription: "Discover Gracia Viva Agave from Goa, Wildly Raw and Yuzzu notes, pairings and city prices on BevOry.",
  }),
  "pieno-sud": guide("Pieno Sud", "Wine", {
    description: "Pieno Sud is an Italian wine range from Sicily with Bianco, Rosato and Rosso bottles. Its Rosso is made with Nero d'Avola under the Terre Siciliane IGT designation.",
    story: "The name means 'full south', a direct nod to the warm Sicilian origin of the wines. The range gives a white, a rose and a red a shared Mediterranean identity.",
    notes: ["Rosso", "Nero d'Avola brings ripe red fruit and a savoury edge.", "Bianco", "The white leans on pear and apple fruit with a lemon-bright finish."],
    serve: "Chill Bianco and Rosato; pour Rosso slightly cool in a medium red-wine glass.",
    food: "Try Bianco with tandoori fish and Rosso with tomato pasta or grilled lamb.",
    pairings: ["tandoori fish", "tomato pasta", "grilled lamb"],
    whyChoose: "A simple Sicilian range that covers three wine colours without hiding the Rosso's Nero d'Avola grape.",
    faq: ["Where is Pieno Sud wine from?", "The range is associated with Sicily, Italy.", "What grape is in Pieno Sud Rosso?", "The Rosso is made with Nero d'Avola."],
    finalVerdict: "Pieno Sud is a useful Sicilian choice when the table moves from seafood to tomato-rich food.",
    metaDescription: "Explore Pieno Sud Bianco, Rosato and Nero d'Avola Rosso from Sicily, pairings and city prices on BevOry.",
  }),
};
