import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_49 = [
  ["absolut", "Absolut", "Sweden", "Vodka"],
  ["amrut", "Amrut", "India", "Whisky"],
  ["bacardi", "Bacardi", "Cuba", "Rum"],
  ["ballantines", "Ballantines", "Scotland", "Whisky"],
  ["balvenie", "Balvenie", "Scotland", "Whisky"],
  ["big-banyan", "Big Banyan", "India", "Wine"],
  ["bira", "Bira", "India", "Beer"],
  ["black-dog", "Black Dog", "Scotland", "Whisky"],
  ["bombay-sapphire", "Bombay Sapphire", "United Kingdom", "Gin"],
  ["bottega", "Bottega", "Italy", "Wine"],
  ["breezer", "Breezer", "India", "Ready-to-drink"],
  ["brewdog", "Brewdog", "Scotland", "Beer"],
  ["bushmills", "Bushmills", "Northern Ireland", "Whiskey"],
  ["chivas-regal", "Chivas Regal", "Scotland", "Whisky"],
  ["corralejo", "Corralejo", "Mexico", "Tequila"],
  ["dalmore", "Dalmore", "Scotland", "Whisky"],
  ["dewars", "Dewars", "Scotland", "Whisky"],
  ["edinburgh-gin", "Edinburgh Gin", "Scotland", "Gin"],
  ["fratelli", "Fratelli", "India", "Wine"],
  ["glenfiddich", "Glenfiddich", "Scotland", "Whisky"],
  ["glenlivet", "Glenlivet", "Scotland", "Whisky"],
  ["glenmorangie", "Glenmorangie", "Scotland", "Whisky"],
  ["greater-than", "Greater Than", "India", "Gin"],
  ["grey-goose", "Grey Goose", "France", "Vodka"],
  ["grover", "Grover", "India", "Wine"],
  ["hendricks", "Hendricks", "Scotland", "Gin"],
  ["hennessy", "Hennessy", "France", "Cognac"],
  ["hoegaarden", "Hoegaarden", "Belgium", "Beer"],
  ["indri", "Indri", "India", "Whisky"],
  ["jack-daniels", "Jack Daniels", "United States", "Whiskey"],
] as const;

// Research URLs remain internal; no public field contains source or audit language.
export const BRAND_SOURCES_BATCH_49: Record<string, string[]> = {
  absolut: ["https://www.absolut.com/en-us/faq/"],
  amrut: ["https://amrutdistilleries.com/story/"],
  bacardi: ["https://www.bacardi.com/uk/en/culture/history/", "https://www.bacardi.com/culture/molasses-to-mojitos-making-bacardi-rum/"],
  ballantines: ["https://www.ballantines.com/en/whisky-guide/our-story/", "https://www.ballantines.com/en/whisky-guide/faqs/"],
  balvenie: ["https://www.williamgrant.com/gb/brands/the-balvenie/", "https://shop.us.thebalvenie.com/products/the-balvenie-doublewood-12"],
  "big-banyan": ["https://www.jdl.in/big-banyan-wines.php", "https://bigbanyanwines.com/"],
  bira: ["https://www.hptax.gov.in/public/notifications/174409640067f4cc90ca412.pdf"],
  "black-dog": ["https://www.diageoindia.com/~/media/Files/D/Diageo-V2/Diageo-India/investors/financials/results-reports-and-presentations/united-spirits-limited-annual-report-2024-25.pdf", "https://www.iwsc.net/results/detail/72910/black-dog-triple-gold-reserve-triple-matured--scotch-whisky"],
  "bombay-sapphire": ["https://www.bombaysapphire.com/our-story/"],
  bottega: ["https://www.bottegaspa.com/en/history/"],
  breezer: ["https://www.bacardilimited.com/our-brands/portfolio/"],
  brewdog: ["https://brewdog.com/pages/fresh"],
  bushmills: ["https://bushmills.com/pages/faq"],
  "chivas-regal": ["https://www.chivas.com/en-us/collection/chivas-12/", "https://www.chivas.com/en/craft/"],
  corralejo: ["https://corralejotequila.com/pages/our-craft"],
  dalmore: ["https://www.thedalmore.com/en-gb/our-world/history-of-the-dalmore/"],
  dewars: ["https://shop.dewars.com/collections/blended-scotch-whisky/products/dewars-double-agent-16-year-old-whisky"],
  "edinburgh-gin": ["https://www.edinburghgin.com/seaside-gin"],
  fratelli: ["https://fratelliwines.in/products/sette-new"],
  glenfiddich: ["https://www.glenfiddich.com/assets/Uploads/Shared/News-Releases/Goodwood-1979/Glenfiddich-Goodwood-1979-Press-ReleaseFINAL.pdf"],
  glenlivet: ["https://www.theglenlivet.com/en-us/faqs/", "https://www.theglenlivet.com/en/whisky/12-year-old-single-malt-scotch/"],
  glenmorangie: ["https://www.glenmorangie.com/pages/history"],
  "greater-than": ["https://naospirits.com/"],
  "grey-goose": ["https://www.greygoose.com/faqs/what-is-grey-goose-vodka-made-from.html"],
  grover: ["https://www.groverzampa.in/about-us"],
  hendricks: ["https://hendricksgin.com/faqs/", "https://us.hendricksgin.com/distilling/"],
  hennessy: ["https://www.hennessy.com/en-us/node/73"],
  hoegaarden: ["https://www.hoegaarden.com/beer"],
  indri: ["https://www.indri.in/faq", "https://www.indri.in/the-whisky"],
  "jack-daniels": ["https://pressroom.jackdaniels.com/wp-content/uploads/2015/01/Old-No.7-Fact-Sheet.pdf"],
};

// Every selected snapshot row already has a stored logo. There are no proposed replacements.
export const BRAND_LOGOS_BATCH_49: Record<string, string> = {};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_49: Record<string, BrandPublicContent> = {
  absolut: guide("Absolut", "Vodka", {
    description: "Absolut is a Swedish vodka made from winter wheat and local water in Åhus, Skåne. Alongside the original spirit, its range includes citrus, pepper and other flavoured vodkas.",
    story: "Lars Olsson Smith introduced continuous distillation in Sweden in 1879. A century later, the Åhus-made bottle became an export success, but its wheat and water still come from southern Sweden.",
    notes: ["Original", "A light grain character gives the unflavoured vodka a restrained finish.", "Citron", "The lemon expression brings a clear citrus note to the same vodka base."],
    serve: "Keep the original cold for a vodka soda; use Citron with tonic and fresh lemon.",
    food: "Set out smoked salmon, chilli paneer or dill potatoes.",
    pairings: ["smoked salmon", "chilli paneer", "dill potatoes"],
    whyChoose: "A wheat-based Swedish vodka with a long history in simple mixed drinks.",
    faq: ["Where is Absolut made?", "Absolut is distilled and bottled in Åhus, southern Sweden.", "What is Absolut vodka made from?", "The original uses Swedish winter wheat and local water."],
    finalVerdict: "Absolut earns its place in a cold, clean highball rather than an elaborate mixer.",
    metaDescription: "Explore Absolut vodka from Åhus, Sweden, including Citron and other flavours. Find serving ideas and city prices on BevOry.",
  }),
  amrut: guide("Amrut", "Whisky", {
    description: "Amrut is an Indian whisky house founded in Bengaluru, Karnataka, by JN Radhakrishna in 1948. Its single malts span classic, peated and cask-finished expressions.",
    story: "Amrut began as Amrut Laboratories soon after Indian independence. Its move into single malt helped bring Bengaluru's warm-climate whisky maturation to a wider audience.",
    notes: ["Classic malt", "Barley sweetness and oak sit at the centre of the unpeated house style.", "Cask finishes", "A stout or wine cask changes the flavour of its named expression rather than the whole range."],
    serve: "Start with a small neat pour, then add a few drops of water.",
    food: "Try with mutton seekh, roasted almonds or dark chocolate.",
    pairings: ["mutton seekh", "roasted almonds", "dark chocolate"],
    whyChoose: "One of the key names in Bengaluru-made Indian single malt.",
    faq: ["Where is Amrut whisky from?", "Amrut's distilling history began in Bengaluru, Karnataka.", "Is every Amrut whisky peated?", "No. The range includes unpeated and peated expressions."],
    finalVerdict: "Amrut is a good way to taste how Indian maturation shapes barley and oak.",
    metaDescription: "Discover Amrut Indian whisky from Bengaluru. Explore single-malt styles, food pairings and city prices on BevOry.",
  }),
  bacardi: guide("Bacardi", "Rum", {
    description: "Bacardi is a rum house founded in Santiago de Cuba by Don Facundo Bacardí Massó in 1862. Its portfolio ranges from light mixing rum to oak-aged Ocho and flavoured expressions.",
    story: "Facundo worked with distillation and filtration to make a lighter Cuban rum. The fruit bats in the original distillery inspired the bat emblem still attached to the family name.",
    notes: ["Light rum", "A mild cane sweetness stays in the background of a long mixed drink.", "Ocho", "The aged expression moves toward oak and dried-fruit depth."],
    serve: "Use light Bacardi with lime in a daiquiri; pour Ocho over ice.",
    food: "Match a citrus drink with fish tacos, Goan prawn fry or salted plantain chips.",
    pairings: ["fish tacos", "Goan prawn fry", "salted plantain chips"],
    whyChoose: "A Cuban-founded rum family with a bottle for both cocktails and slower pours.",
    faq: ["Where did Bacardi begin?", "Don Facundo Bacardí Massó founded it in Santiago de Cuba in 1862.", "Is Bacardi Ocho the same as Bacardi light rum?", "No. Ocho is an oak-aged expression with a fuller style."],
    finalVerdict: "Bacardi is most useful when the bottle is chosen for the drink being made.",
    metaDescription: "Explore Bacardi rum, from light cocktail pours to Ocho. Find food pairings and city prices on BevOry.",
  }),
  ballantines: guide("Ballantine's", "Whisky", {
    description: "Ballantine's is a Scottish blended whisky label rooted in George Ballantine's Edinburgh shop. Its range includes Finest and aged blends such as 17 Year Old.",
    story: "George Ballantine opened a grocery shop in Edinburgh in 1827 and later moved into wine and spirits. Blending became the family business rather than a single-distillery pursuit.",
    notes: ["Finest", "A light honey-and-apple direction makes the core blend easy to mix.", "Aged blends", "Longer maturation brings a deeper oak and spice register."],
    serve: "Pour Finest with soda and ice; give an older blend a short glass.",
    food: "Bring out chicken tikka, salted cashews or cheddar toast.",
    pairings: ["chicken tikka", "salted cashews", "cheddar toast"],
    whyChoose: "An Edinburgh blending name whose bottles cover both highballs and neat whisky.",
    faq: ["Who founded Ballantine's?", "George Ballantine opened his Edinburgh shop in 1827.", "Is Ballantine's a single malt?", "The core Ballantine's range is blended Scotch whisky."],
    finalVerdict: "Ballantine's Finest belongs in a highball; its older blends invite a slower sip.",
    metaDescription: "Explore Ballantine's blended Scotch, from Finest to aged releases. Find serving ideas and city prices on BevOry.",
  }),
  balvenie: guide("The Balvenie", "Whisky", {
    description: "The Balvenie is a Speyside single malt made in Dufftown by William Grant & Sons. The distillery retains floor maltings, its own cooperage and an on-site coppersmith.",
    story: "William Grant built Balvenie close to his Glenfiddich distillery in Dufftown. Its hands-on malt and cask work still shapes the house's approach to single malt.",
    notes: ["DoubleWood 12", "Honey and gentle sherry spice are hallmarks of this named expression.", "Pedro Ximénez cask", "A sherry-cask finish can bring a richer dried-fruit accent."],
    serve: "Use a tulip glass and give the whisky a few minutes before the first sip.",
    food: "Pair with galouti kebabs, walnut cake or aged cheddar.",
    pairings: ["galouti kebabs", "walnut cake", "aged cheddar"],
    whyChoose: "A Dufftown malt where maltings and cask care remain visible parts of production.",
    faq: ["Where is The Balvenie made?", "At its distillery in Dufftown, Speyside, Scotland.", "Does Balvenie still use floor maltings?", "Yes. Traditional floor maltings remain part of its distillery work."],
    finalVerdict: "Balvenie rewards an unhurried pour, particularly beside roasted or gently spiced food.",
    metaDescription: "Discover The Balvenie Speyside single malt. Explore its floor maltings, cask styles, pairings and city prices on BevOry.",
  }),
  "big-banyan": guide("Big Banyan", "Wine", {
    description: "Big Banyan is an Indian wine label from John Distilleries, with a winery near Bengaluru. Its range includes Shiraz, Chardonnay and other single-varietal wines.",
    story: "The label takes its name from the great banyan tree near the Bengaluru winery. Grapes come from its local vineyards and selected sites elsewhere in India.",
    notes: ["Shiraz", "Dark berries lead the red's broad, spice-friendly style.", "Chardonnay", "Tropical fruit and a creamy, nutty edge mark the white."],
    serve: "Give Shiraz a broad glass; chill Chardonnay without serving it ice-cold.",
    food: "Try the red with lamb seekh and the white with tandoori fish or paneer malai tikka.",
    pairings: ["lamb seekh", "tandoori fish", "paneer malai tikka"],
    whyChoose: "An Indian winery that gives familiar grape names a Bengaluru context.",
    faq: ["Who makes Big Banyan wine?", "Big Banyan is part of John Distilleries' wine range.", "Does Big Banyan make white wine?", "Yes. Chardonnay, Chenin Blanc and Sauvignon Blanc are in the range."],
    finalVerdict: "Big Banyan gives a mixed Indian dinner table a clear red-or-white choice.",
    metaDescription: "Explore Big Banyan Shiraz and Chardonnay from India. Find grape styles, pairings and city prices on BevOry.",
  }),
  bira: guide("Bira 91", "Beer", {
    description: "Bira 91 is an Indian beer label from B9 Beverages. Its range spans White wheat beer, Blonde lager and stronger wheat and lager releases.",
    story: "Bira 91 entered the Indian beer market with a wheat beer that stood apart from the usual strong lager. Blonde and Gold widened the range without replacing that original white-beer identity.",
    notes: ["White", "A soft wheat body and citrus edge suit a chilled glass.", "Blonde", "A crisper lager profile gives the range a different finish."],
    serve: "Pour cold into a clean glass, leaving space for the head.",
    food: "Put White with chilli prawns and Blonde with pakora or masala peanuts.",
    pairings: ["chilli prawns", "pakora", "masala peanuts"],
    whyChoose: "A familiar Indian route from wheat beer to lager.",
    faq: ["Who makes Bira 91?", "B9 Beverages is the company behind Bira 91.", "Are Bira White and Blonde the same style?", "No. White is a wheat beer and Blonde is a lager."],
    finalVerdict: "Bira 91 is easiest to enjoy when White and Blonde are treated as different beers.",
    metaDescription: "Compare Bira 91 White, Blonde and strong beers. Find style notes, Indian snack pairings and city prices on BevOry.",
  }),
  "black-dog": guide("Black Dog", "Whisky", {
    description: "Black Dog is a blended Scotch whisky label in the United Spirits portfolio. Its current Indian range includes Black Reserve and Triple Gold Reserve.",
    story: "The brand traces its name to Sir Walter Millard in the nineteenth century. United Spirits later shaped the range around Reserve blends familiar to Indian Scotch drinkers.",
    notes: ["Black Reserve", "Malt and oak give the blend its Scotch backbone.", "Triple Gold Reserve", "Vanilla and warm spice mark this separately matured blend."],
    serve: "Start with a neat measure, or add soda for a longer drink.",
    food: "Match with tandoori chicken, smoked almonds or mushroom kebabs.",
    pairings: ["tandoori chicken", "smoked almonds", "mushroom kebabs"],
    whyChoose: "A Scotch blend with a long-established place on Indian shelves.",
    faq: ["Is Black Dog Scotch whisky?", "Yes. Black Dog is a blended Scotch whisky label.", "Who owns Black Dog in India?", "It sits in the United Spirits portfolio."],
    finalVerdict: "Black Dog is built for drinkers who prefer a rounded Scotch blend to a single malt.",
    metaDescription: "Explore Black Dog blended Scotch and its Reserve range. See pairings and city prices on BevOry.",
  }),
  "bombay-sapphire": guide("Bombay Sapphire", "Gin", {
    description: "Bombay Sapphire is an English gin distilled at Laverstoke Mill in Hampshire. Its classic recipe uses ten botanicals, including juniper, cubeb and grains of paradise.",
    story: "Rather than boiling botanicals in spirit, Bombay Sapphire uses vapour infusion in Carterhead stills. The botanical baskets give the gin a bright, layered aroma without a heavy steeped character.",
    notes: ["Juniper and citrus", "Pine-like juniper meets lemon and orange peel.", "Spice", "Cubeb pepper and grains of paradise bring a dry aromatic edge."],
    serve: "Make a long tonic with ice and a citrus wedge.",
    food: "Serve with tandoori prawns, coriander paneer or salted almonds.",
    pairings: ["tandoori prawns", "coriander paneer", "salted almonds"],
    whyChoose: "An English gin defined by its vapour-infused botanical method.",
    faq: ["Where is Bombay Sapphire made?", "At Laverstoke Mill in Hampshire, England.", "How many botanicals are in classic Bombay Sapphire?", "The classic recipe uses ten botanicals."],
    finalVerdict: "Bombay Sapphire's citrus-and-spice profile needs little more than tonic and ice.",
    metaDescription: "Discover Bombay Sapphire gin from Hampshire. Explore its ten botanicals, food pairings and city prices on BevOry.",
  }),
  bottega: guide("Bottega", "Wine", {
    description: "Bottega is a family-owned Italian wine and spirits producer based in Bibano, Veneto. Its portfolio includes Prosecco, rosé sparkling wines, Brunello and grappa.",
    story: "Aldo Bottega and Rosina Zambon founded the distillery in 1977. The family added Il Vino dei Poeti Prosecco in 1992, taking the name from grappa into sparkling wine.",
    notes: ["Prosecco", "Glera brings pear and apple freshness to the sparkling wines.", "Brunello", "The Sangiovese-based red takes a firmer, darker-fruit path."],
    serve: "Chill Prosecco in a flute or white-wine glass; give Brunello air in a broad glass.",
    food: "Pair bubbles with pakora and Brunello with mushroom risotto or lamb rogan josh.",
    pairings: ["pakora", "mushroom risotto", "lamb rogan josh"],
    whyChoose: "A Veneto family house whose bottles run from aperitif bubbles to Tuscan red.",
    faq: ["Where is Bottega based?", "Bottega is based in Bibano di Godega di Sant'Urbano, Veneto.", "Does Bottega only make Prosecco?", "No. The range also includes still wines, grappa and other spirits."],
    finalVerdict: "Bottega makes sense across a meal, from the first sparkling glass to the main course.",
    metaDescription: "Explore Bottega Prosecco, rosé and Italian reds. Find serving ideas, pairings and city prices on BevOry.",
  }),
  breezer: guide("Breezer", "Ready-to-drink", {
    description: "Bacardi Breezer is a fruit-flavoured ready-to-drink label from Bacardi. Indian listings include blueberry, blackberry and Jamaican Passion variants.",
    story: "Breezer takes the Bacardi name away from a straight rum pour and into chilled, sweet fruit drinks. Each flavour supplies its own fruit character rather than a single shared tasting profile.",
    notes: ["Blueberry", "Berry sweetness leads the blue-fruit variant.", "Jamaican Passion", "A tropical-fruit direction gives this bottle a different finish."],
    serve: "Serve cold from the bottle or over ice in a tall glass.",
    food: "Bring out chilli cheese toast, peri-peri fries or spicy corn chaat.",
    pairings: ["chilli cheese toast", "peri-peri fries", "spicy corn chaat"],
    whyChoose: "A fruit-led chilled drink that requires no mixing.",
    faq: ["Who makes Breezer?", "Breezer is part of the Bacardi drinks portfolio.", "Do all Breezer flavours taste alike?", "No. Blueberry, blackberry and Jamaican Passion have different fruit profiles."],
    finalVerdict: "Breezer works best cold, with salty snacks to balance its sweetness.",
    metaDescription: "Explore Bacardi Breezer flavours in India. See fruit styles, snack pairings and city prices on BevOry.",
  }),
  brewdog: guide("BrewDog", "Beer", {
    description: "BrewDog is a Scottish beer company founded in 2007. Its range includes Punk IPA, Elvis Juice, Dead Pony Club and Lost Lager.",
    story: "BrewDog built its name on hop-forward beers at a time when British supermarket shelves were dominated by lager. The beer range has since stretched from grapefruit-leaning IPA to a cleaner lager pour.",
    notes: ["Punk IPA", "Tropical and citrus hop aromas lead the flagship IPA.", "Lost Lager", "A cleaner malt-and-hop balance sets the lager apart."],
    serve: "Chill the lager well; serve IPA cool rather than frozen.",
    food: "Match IPA with chicken 65 and lager with fish fry or salted chips.",
    pairings: ["chicken 65", "fish fry", "salted chips"],
    whyChoose: "A Scottish beer range with a clear contrast between hop-led IPA and lager.",
    faq: ["Where did BrewDog start?", "BrewDog began in Scotland in 2007.", "Is every BrewDog beer an IPA?", "No. The range also includes Lost Lager and other beer styles."],
    finalVerdict: "BrewDog is strongest when the chosen beer matches the heat and weight of the food.",
    metaDescription: "Compare BrewDog Punk IPA, Elvis Juice and Lost Lager. Find pairings and city prices on BevOry.",
  }),
  bushmills: guide("Bushmills", "Whiskey", {
    description: "Bushmills is an Irish whiskey house in County Antrim, Northern Ireland. Its range spans Original and Black Bush blends plus triple-distilled single malts.",
    story: "A royal licence to distil in the Bushmills area dates to 1608. The River Bush and the village distillery remain central to the house's identity.",
    notes: ["Original", "A lighter grain component keeps the malt-led blend approachable.", "Black Bush", "Oloroso sherry and bourbon casks give the malt-rich blend deeper fruit and oak."],
    serve: "Try Original in a highball and Black Bush neat or over one cube.",
    food: "Pair with smoked chicken, galouti kebabs or walnut cake.",
    pairings: ["smoked chicken", "galouti kebabs", "walnut cake"],
    whyChoose: "An Antrim distillery with both blended Irish whiskey and single malt.",
    faq: ["Where is Bushmills made?", "At the Old Bushmills Distillery in County Antrim, Northern Ireland.", "Is Black Bush a single malt?", "No. Black Bush is a blend with a high proportion of malt whiskey."],
    finalVerdict: "Bushmills offers a gentle first glass in Original and more sherry depth in Black Bush.",
    metaDescription: "Explore Bushmills Original, Black Bush and Irish single malts. Find food pairings and city prices on BevOry.",
  }),
  "chivas-regal": guide("Chivas Regal", "Whisky", {
    description: "Chivas Regal is a blended Scotch whisky built around malt and grain whiskies. Strathisla single malt from Speyside is a key part of its house blend.",
    story: "Brothers John and James Chivas began blending in their nineteenth-century emporium. Chivas Regal later took their name into a range running from 12 Year Old to older expressions.",
    notes: ["Orchard fruit", "The Chivas 12 blend carries apple, honey and heather notes.", "Palate", "Vanilla, hazelnut and butterscotch give that expression its rounded finish."],
    serve: "Pour Chivas 12 neat, on ice or with soda in a highball.",
    food: "Put it with paneer tikka, mutton seekh or toasted hazelnuts.",
    pairings: ["paneer tikka", "mutton seekh", "toasted hazelnuts"],
    whyChoose: "A Speyside-centred Scotch blend with a recognised orchard-fruit style.",
    faq: ["Is Chivas Regal a single malt?", "No. It is blended Scotch whisky made from malt and grain whiskies.", "Which malt is central to Chivas Regal?", "Strathisla single malt is at the heart of its blends."],
    finalVerdict: "Chivas 12 is particularly comfortable in a long, cold whisky highball.",
    metaDescription: "Explore Chivas Regal blended Scotch and its Speyside character. Find serving ideas and city prices on BevOry.",
  }),
  corralejo: guide("Corralejo", "Tequila", {
    description: "Corralejo is a 100% Blue Weber agave tequila made at Hacienda Corralejo in Guanajuato, Mexico. Its range includes Silver, Reposado and Añejo.",
    story: "Corralejo is unusual among tequila houses because it is rooted in Guanajuato rather than Jalisco. The distillery slow-roasts agave in clay ovens and uses both copper pot and column stills.",
    notes: ["Silver", "Cooked agave and a bright citrus edge lead the fresh spirit.", "Reposado", "Barrel time adds a softer vanilla-and-spice register."],
    serve: "Sip Silver with a little water or use it in a lime-led Margarita.",
    food: "Try with tandoori prawns, chicken tacos or charred corn.",
    pairings: ["tandoori prawns", "chicken tacos", "charred corn"],
    whyChoose: "A Guanajuato tequila with an estate-agave identity.",
    faq: ["Where is Corralejo tequila made?", "At Hacienda Corralejo in Guanajuato, Mexico.", "What agave does Corralejo use?", "The house uses 100% Blue Weber agave."],
    finalVerdict: "Corralejo Silver makes an agave-forward Margarita without losing its own character.",
    metaDescription: "Discover Corralejo tequila from Guanajuato. Compare Silver and aged styles, pairings and city prices on BevOry.",
  }),
  dalmore: guide("The Dalmore", "Whisky", {
    description: "The Dalmore is a Highland single malt from Alness on Scotland's Cromarty Firth. Sherry, wine and port casks feature across its maturation-led range.",
    story: "Sir Alexander Matheson founded the distillery in 1839. Its twelve-point stag emblem recalls the Mackenzie clan's story of Colin of Kintail and King Alexander III.",
    notes: ["Sherry casks", "Dried fruit and orange-peel depth suit the sherry-influenced expressions.", "Oak", "Chocolate and warm spice are recurring notes in mature releases."],
    serve: "Use a tulip glass and allow a few minutes in the glass before adding water.",
    food: "Serve beside dark chocolate, mutton rogan josh or orange cake.",
    pairings: ["dark chocolate", "mutton rogan josh", "orange cake"],
    whyChoose: "A Highland malt known for layered cask maturation and a richer style.",
    faq: ["Where is Dalmore made?", "The Dalmore distillery is in Alness, in the Scottish Highlands.", "What does the stag on Dalmore mean?", "It reflects the Mackenzie clan story associated with the distillery."],
    finalVerdict: "Dalmore suits the end of dinner, when oak, fruit and dessert can share the table.",
    metaDescription: "Explore Dalmore Highland single malt, cask styles and food pairings. Check city prices on BevOry.",
  }),
  dewars: guide("Dewar's", "Whisky", {
    description: "Dewar's is a Scottish blended whisky house founded by John Dewar in Perth in 1846. White Label and age-stated blends sit alongside cask-finished expressions.",
    story: "John Dewar started with a Perth wine and spirits shop. The house later made double ageing central to its blending process, resting blended whisky after the components have matured.",
    notes: ["White Label", "A light fruit-and-honey direction makes the blend easy to mix.", "Older blends", "More time in oak brings deeper dried-fruit and spice notes."],
    serve: "Mix White Label with soda and ice; pour an older blend neat.",
    food: "Pair with chicken tikka, roasted cashews or spiced apple tart.",
    pairings: ["chicken tikka", "roasted cashews", "spiced apple tart"],
    whyChoose: "A Perth-born Scotch blend with a distinct double-ageing method.",
    faq: ["Who founded Dewar's?", "John Dewar opened his Perth shop in 1846.", "What is Dewar's double ageing?", "The blended whisky rests together after its components have matured."],
    finalVerdict: "Dewar's gives a fruit-led blended Scotch character to both highballs and neat pours.",
    metaDescription: "Explore Dewar's blended Scotch and double ageing. Find serving ideas, pairings and city prices on BevOry.",
  }),
  "edinburgh-gin": guide("Edinburgh Gin", "Gin", {
    description: "Edinburgh Gin is a Scottish gin label with Classic, Seaside and fruit-led expressions. The Seaside gin uses coastal botanicals associated with beaches around Edinburgh.",
    story: "The label draws on the Scottish capital's gin culture while giving each expression a distinct botanical idea. Seaside steps away from ordinary citrus garnishes toward a more mineral coastal profile.",
    notes: ["Classic", "Juniper and citrus keep the core gin in a familiar dry style.", "Seaside", "A lightly floral aroma and mineral edge mark the coastal expression."],
    serve: "Use a tall tonic with ice; garnish Seaside with grapefruit or a thin strip of lemon.",
    food: "Pair with tandoori fish, oysters or lemon-pepper paneer.",
    pairings: ["tandoori fish", "oysters", "lemon-pepper paneer"],
    whyChoose: "A Scottish gin range whose Seaside bottle has a clear coastal identity.",
    faq: ["What is Edinburgh Gin Seaside?", "It is a London Dry gin made with coastal botanicals.", "Does Edinburgh Gin make fruit flavours?", "Yes. Fruit-led expressions sit alongside Classic and Seaside."],
    finalVerdict: "Edinburgh Gin Seaside is particularly good beside briny food and a cold tonic.",
    metaDescription: "Explore Edinburgh Gin Classic, Seaside and fruit styles. See pairings and city prices on BevOry.",
  }),
  fratelli: guide("Fratelli", "Wine", {
    description: "Fratelli is an Indian wine estate at Akluj, Maharashtra. Its range includes Sangiovese, Cabernet Franc-Shiraz and Sette, a Sangiovese-Cabernet Sauvignon blend.",
    story: "Italian and Indian partners planted vineyards at Akluj, with the first harvest in 2009. The estate's work with Sangiovese gives it a different red-wine identity from Nashik's better-known vineyards.",
    notes: ["Sette", "Raspberry, violet and blackcurrant meet French-oak vanilla in the named blend.", "Sangiovese", "Red-fruit brightness and acidity mark the grape's table-wine style."],
    serve: "Give Sette 20 minutes in a decanter; serve lighter reds a little cool.",
    food: "Try with lamb rogan josh, mushroom risotto or paneer tikka.",
    pairings: ["lamb rogan josh", "mushroom risotto", "paneer tikka"],
    whyChoose: "An Akluj estate that made Sangiovese part of India's wine conversation.",
    faq: ["Where is Fratelli wine made?", "Fratelli's estate vineyards are at Akluj, Maharashtra.", "Which grapes are in Fratelli Sette?", "Sette blends Sangiovese and Cabernet Sauvignon."],
    finalVerdict: "Fratelli Sette belongs with a rich main course, not just the first glass.",
    metaDescription: "Discover Fratelli wine from Akluj, including Sette and Sangiovese. Find pairings and city prices on BevOry.",
  }),
  glenfiddich: guide("Glenfiddich", "Whisky", {
    description: "Glenfiddich is a Speyside single malt made in Dufftown by William Grant & Sons. The range runs from 12 Year Old to older and cask-finished releases.",
    story: "William Grant built the distillery with his family; its stills first ran on Christmas Day 1887. The deer emblem reflects Glenfiddich's name, the valley of the deer.",
    notes: ["12 Year Old", "Pear and orchard fruit lead the familiar younger malt.", "Older releases", "Longer cask time brings deeper oak and spice to named bottles."],
    serve: "Start in a tulip glass, neat or with a few drops of water.",
    food: "Bring out smoked salmon, tandoori chicken or aged cheddar.",
    pairings: ["smoked salmon", "tandoori chicken", "aged cheddar"],
    whyChoose: "A family-owned Dufftown single malt with a clear orchard-fruit signature.",
    faq: ["Where is Glenfiddich made?", "At the Glenfiddich Distillery in Dufftown, Speyside.", "Who founded Glenfiddich?", "William Grant founded the distillery, which first produced spirit in 1887."],
    finalVerdict: "Glenfiddich 12 offers a bright first step into Speyside single malt.",
    metaDescription: "Explore Glenfiddich Speyside single malt, from 12 Year Old upward. Find pairings and city prices on BevOry.",
  }),
  glenlivet: guide("The Glenlivet", "Whisky", {
    description: "The Glenlivet is a Speyside single malt made from malted barley at its distillery in Scotland's Livet valley. Fruity and floral notes are part of its house style.",
    story: "George Smith took a legal distilling licence in 1824 after learning his craft in the remote valley. The name became so widely imitated that the family secured the distinct 'The Glenlivet' identity.",
    notes: ["Fruit", "Orchard and tropical fruit are familiar notes across the house style.", "Flowers", "A lighter floral lift keeps the malt from reading as heavily smoky."],
    serve: "Pour in a tulip glass; try a little water before reaching for ice.",
    food: "Match with malai tikka, grilled prawns or pear tart.",
    pairings: ["malai tikka", "grilled prawns", "pear tart"],
    whyChoose: "A Speyside malt with a legal-distilling story dating to 1824.",
    faq: ["Who founded The Glenlivet?", "George Smith established the licensed distillery in 1824.", "Is The Glenlivet usually smoky?", "Its familiar house style is better known for fruit and floral notes than smoke."],
    finalVerdict: "The Glenlivet makes a gentle, fruit-led first Speyside dram.",
    metaDescription: "Discover The Glenlivet single malt from Speyside. Find its history, serving ideas and city prices on BevOry.",
  }),
  glenmorangie: guide("Glenmorangie", "Whisky", {
    description: "Glenmorangie is a Highland single malt made in Tain, Scotland. Its range includes The Original, Lasanta and Quinta Ruban, each shaped by different cask choices.",
    story: "William and Anne Matheson began the distillery in 1843 in Ross-shire. The people who make its spirit are still known as the Distillers of Tain.",
    notes: ["The Original", "Citrus and vanilla give the core malt a bright opening.", "Quinta Ruban", "Port-cask finishing leads the named expression toward darker fruit and chocolate."],
    serve: "Give The Original a neat pour; try Quinta Ruban after dinner.",
    food: "Put it beside chicken tikka, orange cake or dark chocolate.",
    pairings: ["chicken tikka", "orange cake", "dark chocolate"],
    whyChoose: "A Tain malt that explores Highland spirit through distinct cask finishes.",
    faq: ["Where is Glenmorangie made?", "Glenmorangie is made in Tain, in the Scottish Highlands.", "Is Quinta Ruban the same as The Original?", "No. Quinta Ruban is a port-cask-finished expression."],
    finalVerdict: "Glenmorangie is a useful whisky for seeing what a change of cask can do.",
    metaDescription: "Explore Glenmorangie Original, Lasanta and Quinta Ruban. Find cask styles, pairings and city prices on BevOry.",
  }),
  "greater-than": guide("Greater Than", "Gin", {
    description: "Greater Than is an Indian London Dry gin from Nao Spirits, distilled in Goa. Juniper anchors the recipe, with lemon peel, fennel and ginger giving it a local turn.",
    story: "Nao Spirits began after Delhi bar owners Anand Virmani and colleagues saw room for an Indian gin with a classic dry structure. Its copper pot still, Agotha, sits at the heart of production.",
    notes: ["Aroma", "Clean juniper and fresh lemon peel open the gin.", "Finish", "Fennel sweetness yields to a sharper ginger note."],
    serve: "Build a gin and tonic with ice, lemon peel and a restrained measure of tonic.",
    food: "Set out tandoori prawns, coriander chutney paneer or masala peanuts.",
    pairings: ["tandoori prawns", "coriander chutney paneer", "masala peanuts"],
    whyChoose: "A Goa-distilled London Dry gin with a clear juniper-citrus-spice line.",
    faq: ["Who makes Greater Than gin?", "Nao Spirits makes Greater Than in Goa.", "What gives Greater Than its flavour?", "Juniper, lemon peel, fennel and ginger are prominent in its stated profile."],
    finalVerdict: "Greater Than needs little garnish; its juniper, lemon and ginger do the work.",
    metaDescription: "Explore Greater Than gin from Goa. Find botanical notes, Indian food pairings and city prices on BevOry.",
  }),
  "grey-goose": guide("Grey Goose", "Vodka", {
    description: "Grey Goose is a French vodka made with winter wheat from Picardy and spring water from Gensac-la-Pallue. The range includes the original vodka and fruit-flavoured expressions.",
    story: "The wheat grows in northern France while the water comes from the Cognac area. Those two ingredients give the original spirit its French production identity.",
    notes: ["Original", "A soft wheat note and clean finish suit a minimal serve.", "Pear expression", "Ripe pear takes the flavoured vodka in a fruit-led direction."],
    serve: "Chill the original for a Martini; use pear with soda and a slice of fresh pear.",
    food: "Match with smoked fish, chilli prawns or salted almonds.",
    pairings: ["smoked fish", "chilli prawns", "salted almonds"],
    whyChoose: "A French wheat vodka whose ingredient origins are unusually clear.",
    faq: ["What is Grey Goose vodka made from?", "It uses winter wheat from Picardy and spring water from Gensac-la-Pallue.", "Is Grey Goose made in France?", "Yes. Its original vodka is French-made."],
    finalVerdict: "Grey Goose works best when a simple serve leaves its wheat base visible.",
    metaDescription: "Discover Grey Goose vodka from French wheat and spring water. Find serving ideas and city prices on BevOry.",
  }),
  grover: guide("Grover Zampa", "Wine", {
    description: "Grover Zampa is an Indian wine producer with vineyards in the Nandi Hills of Karnataka and the Nashik Valley. Its range includes Sauvignon Blanc, rosé and La Réserve reds.",
    story: "Kanwal Grover began the business in the 1960s. The two vineyard regions give the house distinct sites rather than a single all-India wine origin.",
    notes: ["Sauvignon Blanc", "Citrus and green-fruit freshness suit the white grape.", "La Réserve red", "Darker fruit and oak give the named red a fuller dinner-wine role."],
    serve: "Chill Sauvignon Blanc; give La Réserve a broad glass and time to open.",
    food: "Pair the white with tandoori fish and the red with lamb seekh or mushroom masala.",
    pairings: ["tandoori fish", "lamb seekh", "mushroom masala"],
    whyChoose: "An Indian wine house working across both Nandi Hills and Nashik.",
    faq: ["Where are Grover Zampa's vineyards?", "They are in the Nandi Hills, Karnataka, and the Nashik Valley, Maharashtra.", "Who started Grover wines?", "Kanwal Grover founded the original business."],
    finalVerdict: "Grover offers a white and red path through two important Indian wine regions.",
    metaDescription: "Explore Grover Zampa wines from Nandi Hills and Nashik. Find grape styles, pairings and city prices on BevOry.",
  }),
  hendricks: guide("Hendrick's", "Gin", {
    description: "Hendrick's is a Scottish gin distilled in Girvan, South Ayrshire. Rose and cucumber distinguish its original gin alongside juniper and other botanicals.",
    story: "Master distiller Lesley Gracie built the recipe around two very different stills: a Bennett pot still and a Carter-Head. The original gin first appeared in 1999 and remains the reference for the brand's later releases.",
    notes: ["Rose", "A delicate floral aroma sits over the juniper.", "Cucumber", "A cool green note makes the classic gin unusually refreshing."],
    serve: "Pour with tonic over ice and add a thin cucumber slice.",
    food: "Try with cucumber chaat, tandoori prawns or goat cheese.",
    pairings: ["cucumber chaat", "tandoori prawns", "goat cheese"],
    whyChoose: "A Girvan gin whose rose-and-cucumber character is unmistakable.",
    faq: ["Where is Hendrick's gin made?", "It is distilled in Girvan, South Ayrshire, Scotland.", "Why is Hendrick's served with cucumber?", "Cucumber is part of the original gin's flavour profile."],
    finalVerdict: "Hendrick's is at its clearest in a cold tonic with cucumber.",
    metaDescription: "Explore Hendrick's Scottish gin, rose and cucumber botanicals, pairings and city prices on BevOry.",
  }),
  hennessy: guide("Hennessy", "Cognac", {
    description: "Hennessy is a Cognac house founded by Richard Hennessy in France in 1765. Its range includes VS, VSOP and XO blends of aged grape eaux-de-vie.",
    story: "Richard Hennessy, an Irishman, established his trading house beside the Charente River. The Fillioux family's blending work became part of the house's long continuity.",
    notes: ["VS", "Fresh fruit and oak spice make the younger blend useful in mixed drinks.", "XO", "Older eaux-de-vie bring deeper dried-fruit and warm-spice notes."],
    serve: "Use VS in a highball; give XO a small tulip glass after dinner.",
    food: "Pair with galouti kebabs, dark chocolate or orange peel.",
    pairings: ["galouti kebabs", "dark chocolate", "orange peel"],
    whyChoose: "A Cognac house with a documented Charente story reaching back to 1765.",
    faq: ["Who founded Hennessy?", "Richard Hennessy founded the trading house in Cognac in 1765.", "Are Hennessy VS and XO the same style?", "No. Their age categories and blend profiles differ."],
    finalVerdict: "Hennessy shifts comfortably from a VS cocktail to a slower XO pour.",
    metaDescription: "Explore Hennessy Cognac from VS to XO. Discover its history, food pairings and city prices on BevOry.",
  }),
  hoegaarden: guide("Hoegaarden", "Beer", {
    description: "Hoegaarden is a Belgian wheat beer label associated with the village of Hoegaarden. Its Original witbier uses coriander and orange peel.",
    story: "Witbier had a long history in the village before Hoegaarden became an international name. The cloudy wheat base and botanical seasoning kept it distinct from a clear lager.",
    notes: ["Orange", "Citrus peel brings a bright lift to the classic wheat beer.", "Coriander", "A lightly earthy spice note sits under the soft wheat body."],
    serve: "Chill and pour into a wide glass, leaving room for a generous head.",
    food: "Serve with tandoori prawns, lemon chicken or pakora.",
    pairings: ["tandoori prawns", "lemon chicken", "pakora"],
    whyChoose: "A Belgian witbier where wheat, coriander and orange work together.",
    faq: ["What style is Hoegaarden Original?", "It is a Belgian witbier, or wheat beer.", "What gives Hoegaarden its citrus note?", "Orange peel is part of the classic recipe."],
    finalVerdict: "Hoegaarden is a good cold beer for citrus, seafood and light spice.",
    metaDescription: "Discover Hoegaarden Belgian wheat beer, orange and coriander notes, pairings and city prices on BevOry.",
  }),
  indri: guide("Indri", "Whisky", {
    description: "Indri is an Indian single malt whisky made by Piccadily in Indri, Haryana. The flagship Trini expression uses Indian six-row barley and three cask types.",
    story: "Piccadily built its distillery in the northern plains of Haryana. Trini's name points to maturation in ex-bourbon, French wine and sherry casks before the malts are brought together.",
    notes: ["Trini aroma", "Caramelised pineapple, vanilla and citrus appear in the three-wood expression.", "Trini finish", "Raisins, black tea and a quiet nuttiness linger after the fruit."],
    serve: "Start with Trini neat in a tulip glass; add a little water if the oak feels firm.",
    food: "Try with tandoori mushrooms, mutton seekh or toasted almonds.",
    pairings: ["tandoori mushrooms", "mutton seekh", "toasted almonds"],
    whyChoose: "A Haryana single malt that lets three distinct casks shape its flagship.",
    faq: ["Where is Indri whisky made?", "Piccadily makes Indri in the town of Indri, Haryana.", "What are Indri Trini's three casks?", "The flagship combines ex-bourbon, French wine and sherry cask maturation."],
    finalVerdict: "Indri Trini brings northern Indian barley and a three-cask finish into the same glass.",
    metaDescription: "Explore Indri Indian single malt from Haryana, including Trini's three casks. Find pairings and city prices on BevOry.",
  }),
  "jack-daniels": guide("Jack Daniel's", "Whiskey", {
    description: "Jack Daniel's is a Tennessee whiskey made in Lynchburg from corn, rye, malted barley and local limestone-filtered water. Old No. 7 is charcoal mellowed before entering new charred oak barrels.",
    story: "Jack Daniel registered his Lynchburg distillery in the nineteenth century. The sugar-maple charcoal process remained in place through the Motlow family's stewardship and later ownership by Brown-Forman.",
    notes: ["Old No. 7 aroma", "Vanilla, caramel and a little fruit sit over the grain.", "Finish", "Charred oak leaves a dry wood note after the sweeter opening."],
    serve: "Pour over ice, or lengthen with cola and a wedge of lime.",
    food: "Match with barbecue chicken, mutton seekh or pecan pie.",
    pairings: ["barbecue chicken", "mutton seekh", "pecan pie"],
    whyChoose: "A Lynchburg whiskey with a distinctive sugar-maple charcoal step.",
    faq: ["Where is Jack Daniel's made?", "At the Jack Daniel Distillery in Lynchburg, Tennessee.", "What is charcoal mellowing?", "The spirit passes through sugar-maple charcoal before barrel maturation."],
    finalVerdict: "The flagship whiskey brings caramel and oak to a short glass or a simple highball.",
    metaDescription: "Explore Jack Daniel's Tennessee whiskey, charcoal mellowing, pairings and city prices on BevOry.",
  }),
};
