import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_LOGOS_BATCH_17: Record<string, string> = {
  "1965-xxx": "https://static.livcheers.com/static/content/images/brand/1965-xxx.webp",
  "3-kilos": "https://3kilos.de/wp-content/uploads/2024/04/cropped-3-KILOS-VODKA-LOGO-PRIMARY-583x1024.png",
  "44-degree": "https://static.livcheers.com/static/content/images/brand/44-degree.webp",
  "9-lives": "https://static.livcheers.com/static/content/images/brand/9-lives.webp",
  adobe: "https://www.emiliana.cl/cms/wp-content/uploads/2020/02/adobe_cortao.png",
  agavales: "https://www.agavalestequila.com/image/6795185.1610451419000/Agavales_white.png",
  altamura: "https://www.altamuradistilleries.com/wp-content/uploads/2024/01/01-24-logo.svg",
  altano: "https://en.altano.pt/images/altano-brand-main.svg",
  "antigal-uno": "https://www.antigal.com/wp-content/uploads/svg/brand_UNO.svg",
  archers: "https://archers.com/wp-content/uploads/2025/09/Archers-Logo.svg",
  ardmore: "https://static.livcheers.com/static/content/images/brand/ardmore.webp",
  argento: "https://argentowine.com/wp-content/themes/argento-2012/images/logo.png",
  "armand-de-brignac": "https://armanddebrignac.com/wp-content/uploads/2026/02/Secondary-Logo.svg",
  aultmore: "https://static.livcheers.com/static/content/images/brand/aultmore.webp",
  balblair: "https://static.livcheers.com/static/content/images/brand/balblair.webp",
};

export const BRAND_IDENTITIES_BATCH_17 = [
  ["1965-xxx", "1965 Spirit of Victory", "India", "Rum", "5e2ee4b84a3f922df4dd1717"],
  ["3-kilos", "3 Kilos", "Netherlands", "Vodka", "628310acccd74a85fde04d18"],
  ["44-degree", "44°N", "France", "Gin", "807429c3597c22b37d4100b4"],
  ["9-lives", "9 Lives", "Chile", "Wine", "bc867356de020e99127ca88b"],
  ["adobe", "Adobe", "Chile", "Wine", "ee9021c84f33366bde80b75e"],
  ["aerolite-lyndsay", "Aerolite Lyndsay", "Scotland", "Single Malts", "deb5a35d7d78b87ed2411653"],
  ["after-dark", "After Dark", "India", "Indian Whisky", "0f06d70100a5c5f60159bd5f"],
  ["agavales", "Agavales", "Mexico", "Tequila", "0642006d621a0f36d4f07290"],
  ["akori", "Akori", "Spain", "Gin", "c1517fa9e5607ed98778e290"],
  ["alambre", "Alambre", "Portugal", "Wine", "7d7256aaf50def314d64bf36"],
  ["altamura", "Altamura", "Italy", "Vodka", "66f40fff5f0447c6f136e77d"],
  ["altano", "Altano", "Portugal", "Wine", "fe4901e6a40cc69a4a47ab89"],
  ["anakena-birdman", "Anakena Birdman", "Chile", "Wine", "9f070df4f7f35dcbc87eb8a1"],
  ["antigal-uno", "Antigal UNO", "Argentina", "Wine", "5714ede1544d7939dbd19bcc"],
  ["archers", "Archers", "United Kingdom", "Liqueur", "16970d112808f59ee01adfa6"],
  ["ardmore", "Ardmore", "Scotland", "Single Malts", "2c95982e95867d1b8c926f55"],
  ["argento", "Argento", "Argentina", "Wine", "7a9432116f6fc337d0a8d508"],
  ["armand-de-brignac", "Armand de Brignac", "France", "Champagne", "275275c2708d20e77ce59be5"],
  ["aultmore", "Aultmore", "Scotland", "Single Malts", "2616b823c091201ade5aa347"],
  ["balblair", "Balblair", "Scotland", "Single Malts", "fe8703bdec4c0d30e63dc75e"],
] as const;

// Research links are internal evidence, never consumer copy.
export const BRAND_SOURCES_BATCH_17: Record<string, string[]> = {
  "1965-xxx": ["https://radicokhaitan.com/products/1965-premium-xxx-rum/"],
  "3-kilos": ["https://3kilos.de/", "https://3kilos.com/pages/contact"],
  "44-degree": ["https://www.44gin.com/", "https://www.44gin.com/pages/science"],
  "9-lives": ["https://9liveswine.com/wines/delirious/", "https://vsptwinegroup.com/wp/wp-content/uploads/2020/06/PRESS-KIT-GATONEGRO-2020-ENG.pdf"],
  adobe: ["https://www.emiliana.cl/vinos/adobe/", "https://www.emiliana.cl/cms/wp-content/uploads/2025/06/ADOBE-SB-2023-ESP-CB-1.pdf"],
  "aerolite-lyndsay": ["https://www.atombrands.com/blog-press-posts/aerolite-lyndsay", "https://thewhiskyphiles.com/2020/07/10/aerolite-lyndsay-10-years-old/"],
  "after-dark": ["https://radicokhaitan.com/products/after-dark-2/", "https://www.whiskybase.com/whiskies/whisky/71566/after-dark-fine-grain-whisky", "https://astudentofwine.blogspot.com/2013/06/?m=0"],
  agavales: ["https://www.agavalestequila.com/original-blanco-range-tequila", "https://www.magnifiquebrands.com/en/agavales-en/"],
  akori: ["https://www.systembolaget.se/produkt/sprit/akori-5550901/", "https://www.alcoholprofessor.com/blog-posts/pink-gin"],
  alambre: ["https://www.jmf.pt/index.php?id=77", "https://www.jmf.pt/index.php?id=416"],
  altamura: ["https://www.altamuradistilleries.com/en/premium-vodka/"],
  altano: ["https://en.altano.pt/wines", "https://en.altano.pt/vineyards"],
  "anakena-birdman": ["https://anakenawines.com/en-gb", "https://anakenawines.com/collections/all"],
  "antigal-uno": ["https://www.antigal.com/es/nuestra-historia/", "https://www.antigal.com/uno/"],
  archers: ["https://archers.com/products/archers/", "https://www.dekuypercompany.com/2022/09/cocktail-liqueur-expert-de-kuyper-royal-distillers-strengthens-leading-position-by-acquiring-british-peach-liqueur-legend-archers/"],
  ardmore: ["https://www.ardmorewhisky.com/", "https://media.marketwire.com/attachments/200911/444985_Ardmore_US_Media_Pack_LR.pdf"],
  argento: ["https://argentowine.com/wines/argento/", "https://www.grupoavinea.com/", "https://www.bodegaargento.com/assets/files/resto/vinos/en/fichas-tecnicas/Seleccion/Estate-Bottled-Malbec-2020.pdf"],
  "armand-de-brignac": ["https://www.armanddebrignac.com/inside-armand-de-brignac/", "https://www.armanddebrignac.com/wp-content/uploads/2016/11/Armand-de-Brignac-Brut-Gold-2023.pdf"],
  aultmore: ["https://shop.dewars.com/products/aultmore-12-year-old-whisky"],
  balblair: ["https://www.balblair.com/", "https://www.thewhiskyexchange.com/p/48761/balblair-12-year-old", "https://whiskycast.com/ratings/balblair-12/"],
};

export const BRAND_CONTENT_BATCH_17: Record<string, BrandPublicContent> = {
  "1965-xxx": {
    description: "1965 Spirit of Victory is Radico Khaitan's Indian XXX rum, with a dark, sweet profile built around honey, chocolate and dried fruit. It belongs to the company's rum portfolio alongside Contessa.",
    story: "The name honours Indian soldiers who fought in the 1965 Indo-Pak war. Radico introduced the rum through the Canteen Stores Department in 2017 before extending it to civilian markets.",
    tastingNotes: [{ title: "Honey and cocoa", description: "Honeyed sweetness meets chocolate, giving the rum a rich, rounded centre." }, { title: "Dried fruit finish", description: "Dried-fruit notes carry through a lingering, softly oaky finish." }],
    howToEnjoy: [{ subheading: "A simple rocks pour", description: "Pour a small measure over a large ice cube, or lengthen it with soda and a squeeze of lime." }, { subheading: "Char and cocoa", description: "Try mutton seekh, charred pineapple or dark chocolate alongside the rum's sweet fruit." }],
    pairingIdeas: [{ title: "With dinner or dessert", items: ["mutton seekh", "charred pineapple", "dark chocolate", "pepper chicken"] }],
    whyChoose: "1965 offers a honey-and-chocolate rum style with a distinctly Indian commemorative identity.",
    faqs: [{ question: "Who makes 1965 rum?", answer: "Radico Khaitan makes 1965 Spirit of Victory rum in India." }, { question: "Does 1965 refer to the rum's age?", answer: "No, it commemorates the 1965 Indo-Pak war rather than a distillation year or maturation period." }],
    finalVerdict: "A rounded dark rum for drinkers who enjoy chocolate, honey and dried fruit more than a dry, grassy style.",
    metaTitle: "1965 Spirit of Victory Rum Guide | BevOry",
    metaDescription: "Meet 1965 rum from Radico Khaitan: honey, chocolate and dried-fruit notes, serving ideas and food pairings. Check city prices on BevOry.",
  },
  "3-kilos": {
    description: "3 Kilos is a Dutch wheat vodka distilled in Schiedam, South Holland, and presented in a gold-bar-shaped bottle. Five-stage column distillation and purified water produce a soft spirit with a restrained citrus-and-almond character.",
    story: "Schiedam's distilling heritage provides the production setting for this modern vodka label. The bullion-shaped packaging borrows its visual language from gold reserves, making the bottle as recognisable as its name.",
    tastingNotes: [{ title: "Floral opening", description: "Light floral aromas and vanilla sit above a gentle grain character." }, { title: "Citrus and almond", description: "Grapefruit and almond lead into a silky mouthfeel and a lightly mineral finish." }],
    howToEnjoy: [{ subheading: "Keep the pour cool", description: "Serve chilled in a small stemmed glass or stir with dry vermouth for a Vodka Martini." }, { subheading: "Salt and light spice", description: "Smoked salmon, dill potatoes and tandoori prawns suit the soft wheat profile." }],
    pairingIdeas: [{ title: "Vodka accompaniments", items: ["smoked salmon", "dill potatoes", "tandoori prawns", "salted cucumber"] }],
    whyChoose: "3 Kilos combines Schiedam wheat distillation with a notably soft texture and unmistakable bullion-inspired packaging.",
    faqs: [{ question: "Where is 3 Kilos vodka made?", answer: "It is distilled in Schiedam in the Netherlands." }, { question: "What is 3 Kilos vodka made from?", answer: "Its base is European wheat, processed through five stages of column distillation." }],
    finalVerdict: "The gold-bar bottle is bold, but the vodka inside favours quiet citrus, almond and a smooth wheat texture.",
    metaTitle: "3 Kilos Dutch Vodka Guide | BevOry",
    metaDescription: "Discover 3 Kilos wheat vodka from Schiedam, floral and citrus notes, Martini serves and food pairings. Find city prices on BevOry.",
  },
  "44-degree": {
    description: "44°N is a gin made by Comte de Grasse in Grasse on the French Riviera. Its botanicals draw on the region's perfume traditions, bringing rose, jasmine, mimosa and citrus around a juniper core.",
    story: "Comte de Grasse works in the restored Bertrand & Fils perfume distillery, whose origins date to 1820. The gin's name refers to its latitude, while ultrasonic maceration and vacuum distillation connect local aromatic plants with modern extraction methods.",
    tastingNotes: [{ title: "Riviera citrus", description: "Lemon and grapefruit bring a bright opening, with juniper and a savoury samphire note underneath." }, { title: "Flowers and honey", description: "Rose and jasmine give way to orange, earthy roots and a soft honeyed finish." }],
    howToEnjoy: [{ subheading: "Leave the flowers space", description: "Use a light tonic, plenty of ice and a small strip of grapefruit peel rather than several competing garnishes." }, { subheading: "Fresh herbs at the table", description: "Pair with lemon fish tikka, goat-cheese salad, grilled prawns or rosemary focaccia." }],
    pairingIdeas: [{ title: "Coastal dishes", items: ["lemon fish tikka", "goat-cheese salad", "grilled prawns", "rosemary focaccia"] }],
    whyChoose: "44°N translates Grasse's perfume-making heritage into a floral, citrus-led gin with a savoury edge.",
    faqs: [{ question: "Is 44°N a French gin?", answer: "Yes, Comte de Grasse produces it in Grasse on the French Riviera." }, { question: "What does the name 44°N mean?", answer: "It refers to the latitude associated with the distillery's Riviera location." }],
    finalVerdict: "Choose 44°N for a fragrant gin where flowers, citrus and coastal herbs remain more prominent than heavy spice.",
    metaTitle: "44°N French Gin Guide | BevOry",
    metaDescription: "Explore 44°N gin from Grasse, Riviera botanicals, floral tasting notes, tonic serves and food pairings. Check city prices on BevOry.",
  },
  "9-lives": {
    description: "9 Lives is a Chilean wine range from Vina San Pedro, part of VSPT Wine Group. Its Delirious Cabernet Sauvignon combines ripe berry fruit with pepper, black tea and a touch of vanilla.",
    story: "The label builds on San Pedro's GatoNegro identity, using the familiar cat as the starting point for a separate wine range. Its name carries that feline association into a bolder visual style and fruit-led wines.",
    tastingNotes: [{ title: "Delirious Cabernet fruit", description: "Strawberry and cherry give the Cabernet Sauvignon a ripe, juicy opening." }, { title: "Pepper and tea", description: "Black pepper, black tea and vanilla add a savoury counterpoint to the red fruit." }],
    howToEnjoy: [{ subheading: "Cabernet slightly cool", description: "Serve the Cabernet in a medium red-wine glass, slightly cooler than a warm Indian room." }, { subheading: "Roast and mushroom", description: "Mutton seekh, stuffed mushrooms and roast lamb work with its fruit and pepper." }],
    pairingIdeas: [{ title: "For the Cabernet", items: ["mutton seekh", "stuffed mushrooms", "roast lamb", "aged cheddar"] }],
    whyChoose: "9 Lives brings a bright berry-led approach to Chilean Cabernet without losing its peppery, savoury side.",
    faqs: [{ question: "Who produces 9 Lives wine?", answer: "Vina San Pedro, part of Chile's VSPT Wine Group, produces the range." }, { question: "What does 9 Lives Delirious Cabernet taste like?", answer: "It combines strawberry and cherry with black pepper, tea and vanilla." }],
    finalVerdict: "The Delirious Cabernet is a fruit-forward option for a table of roast dishes, mushrooms and gently spiced kebabs.",
    metaTitle: "9 Lives Chilean Wine Guide | BevOry",
    metaDescription: "Discover 9 Lives wine, Delirious Cabernet tasting notes, Chilean origins and dinner pairings. Check city prices on BevOry.",
  },
  adobe: {
    description: "Adobe is Emiliana's organic wine range from Chile, spanning grapes including Sauvignon Blanc, Carmenere, Cabernet Sauvignon and Chardonnay. The range puts recognisable varietal character at the centre of its wines.",
    story: "Emiliana developed Adobe within its wider commitment to organic viticulture in Chile. Its Sauvignon Blanc draws on Casablanca Valley, where cool growing conditions support the grape's citrus and herbal character.",
    tastingNotes: [{ title: "Sauvignon Blanc citrus", description: "Grapefruit and lime give the Casablanca Sauvignon Blanc a brisk, fresh opening." }, { title: "Herbal finish", description: "Green herbs and a light white-pepper note accompany the wine's crisp acidity." }],
    howToEnjoy: [{ subheading: "Chill the Sauvignon", description: "Serve Sauvignon Blanc chilled in a tulip-shaped white-wine glass; leave a little room for its herbal aromas." }, { subheading: "Citrus with green herbs", description: "Try coriander fish tikka, goat-cheese salad, lemon rice or grilled asparagus with the Sauvignon Blanc." }],
    pairingIdeas: [{ title: "Sauvignon Blanc pairings", items: ["coriander fish tikka", "goat-cheese salad", "lemon rice", "grilled asparagus"] }],
    whyChoose: "Adobe offers a clear introduction to Emiliana's organic wines through familiar grapes and distinctive Chilean growing regions.",
    faqs: [{ question: "Who makes Adobe wine?", answer: "Emiliana produces the Adobe organic wine range in Chile." }, { question: "Where does Adobe Sauvignon Blanc come from?", answer: "The Casablanca Valley supplies the Sauvignon Blanc described here, with a fresh citrus-and-herb style." }],
    finalVerdict: "Start with Adobe Sauvignon Blanc for a crisp, herbal white suited to citrus-dressed food and lighter Indian dishes.",
    metaTitle: "Adobe Organic Wine Guide | BevOry",
    metaDescription: "Meet Emiliana's Adobe wines from Chile. Explore Sauvignon Blanc notes, organic viticulture and food pairings. Find city prices on BevOry.",
  },
  "aerolite-lyndsay": {
    description: "Aerolite Lyndsay is a ten-year-old peated Islay single malt released by Atom Brands under The Character of Islay Whisky Company. Bourbon barrels and sherry casks contribute sweetness and dark-fruit depth around the smoky spirit.",
    story: "The whisky launched in 2019 as part of a project centred on Islay's distinctive spirit. Its unusual name is an anagram of 'ten year old Islay', turning the whisky's age and origin into a small word puzzle.",
    tastingNotes: [{ title: "Smoke and cocoa", description: "Peat smoke, dark chocolate and coffee give the whisky a dense, savoury opening." }, { title: "Mint and toffee", description: "Mint, liquorice and toffee run through the finish, with a salty edge beneath the sweetness." }],
    howToEnjoy: [{ subheading: "Open with a little water", description: "Taste a small pour in a tulip glass, then add a few drops of water to soften the smoky weight." }, { subheading: "Meet smoke with char", description: "Serve alongside charred aubergine, tandoori lamb, smoked cheese or dark chocolate." }],
    pairingIdeas: [{ title: "Smoky malt pairings", items: ["charred aubergine", "tandoori lamb", "smoked cheese", "dark chocolate"] }],
    whyChoose: "Aerolite Lyndsay combines an age-stated Islay spirit with both bourbon-cask sweetness and sherry-cask depth.",
    faqs: [{ question: "Is Aerolite Lyndsay peated?", answer: "Yes, it is a smoky Islay single malt with peat at the centre of its flavour." }, { question: "What does Aerolite Lyndsay mean?", answer: "The name rearranges the letters of 'ten year old Islay'." }],
    finalVerdict: "A smoky Islay malt with enough cocoa, toffee and sherry influence to balance its savoury side.",
    metaTitle: "Aerolite Lyndsay Islay Whisky Guide | BevOry",
    metaDescription: "Discover Aerolite Lyndsay, a ten-year-old Islay malt, smoky tasting notes, cask styles and food pairings. Check city prices on BevOry.",
  },
  "after-dark": {
    description: "After Dark is a fine-grain Indian whisky from Radico Khaitan, the company behind Rampur and 8PM. The blend combines a honeyed character with a rounded, gently spicy style.",
    story: "Radico's distilling roots go back to Rampur in 1943. After Dark became part of its premium Indian whisky range as the company expanded beyond its established mass-market labels.",
    tastingNotes: [{ title: "Honey and fruit", description: "Honey and ripe stone-fruit notes give the whisky a gently sweet opening." }, { title: "Floral spice", description: "Light floral aromas and warming spice sit alongside a soft, rounded grain character." }],
    howToEnjoy: [{ subheading: "Water before a sweet mixer", description: "Try a small pour with a splash of water, or build a simple soda highball over ice." }, { subheading: "Grill gently", description: "Chicken tikka, paneer skewers and salted almonds work with the honeyed side of the blend." }],
    pairingIdeas: [{ title: "Whisky snacks", items: ["chicken tikka", "paneer skewers", "salted almonds", "mushroom kebabs"] }],
    whyChoose: "After Dark suits a straightforward whisky-and-soda serve with honeyed grain character and a little spice.",
    faqs: [{ question: "Is After Dark an Indian whisky?", answer: "Yes, it is an Indian whisky from Radico Khaitan." }, { question: "How can I serve After Dark?", answer: "Try it with water, over ice or in a tall soda highball with a small citrus peel." }],
    finalVerdict: "An uncomplicated Indian blend for a light highball and a plate of grilled snacks.",
    metaTitle: "After Dark Indian Whisky Guide | BevOry",
    metaDescription: "Explore After Dark whisky from Radico Khaitan, honeyed tasting notes, soda serves and Indian food pairings. Find city prices on BevOry.",
  },
  agavales: {
    description: "Agavales is a tequila range produced by Casa Maestri in Tequila, Jalisco. Its Blanco and Reposado styles move from fresh agave and citrus to richer baked-agave and caramel flavours.",
    story: "Casa Maestri's distillery stands in the town that gives tequila its name. Agavales expresses that Jalisco connection through a range built around agave spirit and contrasting maturation styles.",
    tastingNotes: [{ title: "Original Blanco", description: "Fresh vegetation, tangerine and agave meet earthy white pepper and a trace of vanilla." }, { title: "Original Reposado", description: "Baked agave and caramel gain lime, melon and warm spice, with an earthy finish." }],
    howToEnjoy: [{ subheading: "Fresh lime, simple glass", description: "Sip from a narrow tasting glass or shake Blanco with fresh lime and orange liqueur for a Margarita." }, { subheading: "Charred corn and lime", description: "Pair with grilled corn, tandoori prawns, fish tacos or achari paneer." }],
    pairingIdeas: [{ title: "Agave-friendly dishes", items: ["grilled corn", "tandoori prawns", "fish tacos", "achari paneer"] }],
    whyChoose: "Agavales makes the contrast between fresh Blanco agave and rounder Reposado flavours easy to explore.",
    faqs: [{ question: "Where is Agavales tequila produced?", answer: "Casa Maestri produces Agavales in Tequila, Jalisco, Mexico." }, { question: "How do Agavales Blanco and Reposado differ?", answer: "Blanco is more citrus-led and peppery, while Reposado adds baked-agave, caramel and warmer spice notes." }],
    finalVerdict: "Agavales is a useful Jalisco range for fresh-lime cocktails and a side-by-side look at Blanco and Reposado.",
    metaTitle: "Agavales Jalisco Tequila Guide | BevOry",
    metaDescription: "Explore Agavales tequila, Casa Maestri origins, Blanco and Reposado notes, Margarita serves and pairings. Find city prices on BevOry.",
  },
  akori: {
    description: "Akori is a Spanish gin from Destilerias Campeny, inspired by Japanese ingredients and aesthetics. Its Cherry Blossom expression combines a rice-based spirit with sakura, ginger and citrus flavours.",
    story: "Campeny developed Akori in the Barcelona region as a meeting of Spanish distilling and Japanese-inspired botanicals. Cherry Blossom extends that idea into a pink gin centred on the floral associations of sakura.",
    tastingNotes: [{ title: "Cherry Blossom flowers", description: "A fragrant floral opening brings sakura-like blossom and soft almond notes." }, { title: "Ginger and kumquat", description: "Ginger and kumquat add warmth and citrus brightness beneath the floral sweetness." }],
    howToEnjoy: [{ subheading: "Tonic without heavy garnish", description: "Serve Cherry Blossom over ice with a restrained tonic and a small citrus twist." }, { subheading: "Gentle heat on the plate", description: "Try prawn tempura, ginger chicken, paneer tikka or cucumber sushi rolls." }],
    pairingIdeas: [{ title: "For Cherry Blossom", items: ["prawn tempura", "ginger chicken", "paneer tikka", "cucumber sushi rolls"] }],
    whyChoose: "Akori Cherry Blossom offers a floral alternative to sharply juniper-led gin, with ginger and citrus keeping the profile lively.",
    faqs: [{ question: "Is Akori made in Japan?", answer: "No, it is produced in Spain by Destilerias Campeny, with Japanese-inspired ingredients and design." }, { question: "What is Akori Cherry Blossom like?", answer: "It is floral and gently sweet, with blossom, almond, ginger and citrus notes." }],
    finalVerdict: "A floral gin for a light tonic serve, particularly for drinkers drawn to blossom and ginger rather than strong juniper.",
    metaTitle: "Akori Spanish Gin Guide | BevOry",
    metaDescription: "Discover Akori gin, Spanish origins and Japanese inspiration, Cherry Blossom notes and food pairings. Check city prices on BevOry.",
  },
  alambre: {
    description: "Alambre is a Moscatel de Setubal fortified wine range from Jose Maria da Fonseca in Portugal. Muscat grapes give it floral and orange-peel aromas, while maturation brings dried fruit, nuts and caramel.",
    story: "Jose Maria da Fonseca has made wine in Portugal since 1834. For Alambre's aged Moscatel, grape spirit arrests fermentation and extended skin contact helps extract the grape's aroma before the wine matures in used oak.",
    tastingNotes: [{ title: "Orange and apricot", description: "Orange peel, floral notes and apricot bring freshness to the sweet Muscat profile." }, { title: "Ten-year richness", description: "The ten-year-old expression adds walnuts, honey, fennel and toasted fruit, with a long, soft finish." }],
    howToEnjoy: [{ subheading: "Small glass, cool pour", description: "Serve lightly chilled in a small white-wine glass, or try the younger style over ice as an aperitif." }, { subheading: "Nuts and citrus desserts", description: "Pair with almond cake, orange tart, walnut halwa or aged cheese." }],
    pairingIdeas: [{ title: "Sweet and savoury matches", items: ["almond cake", "orange tart", "walnut halwa", "aged gouda"] }],
    whyChoose: "Alambre brings together Setubal Muscat's orange-flower perfume and the nutty depth of fortified-wine maturation.",
    faqs: [{ question: "What kind of wine is Alambre?", answer: "It is Moscatel de Setubal, a sweet fortified Muscat wine from Portugal." }, { question: "Who produces Alambre?", answer: "Jose Maria da Fonseca, the Portuguese wine house founded in 1834, produces Alambre." }],
    finalVerdict: "Alambre rewards a small, cool pour with orange peel, dried fruit and enough nutty complexity for dessert or cheese.",
    metaTitle: "Alambre Moscatel Wine Guide | BevOry",
    metaDescription: "Explore Alambre Moscatel de Setubal, orange and walnut notes, Portuguese heritage and dessert pairings. Check city prices on BevOry.",
  },
  altamura: {
    description: "Altamura is an Italian vodka distilled from durum wheat grown around Altamura in Puglia. Triple distillation preserves a creamy cereal character with citrus, vanilla and a savoury finish.",
    story: "The project draws its identity from the durum wheat associated with Altamura's bread-making tradition. Wheat varieties including Arcangelo, Duilio and Simeto connect the vodka to the grain culture of southern Italy.",
    tastingNotes: [{ title: "Grain and vanilla", description: "Nutty cereal aromas open into vanilla and a creamy, gently savoury palate." }, { title: "Citrus and anise", description: "Lemon, grapefruit and anise add definition to the wheat-led body." }],
    howToEnjoy: [{ subheading: "A grain-led Martini", description: "Serve chilled on its own or in a dry Vodka Martini with a lemon twist." }, { subheading: "Bread, salt and seafood", description: "Try focaccia, burrata, tandoori prawns or mushroom crostini with the cereal-rich texture." }],
    pairingIdeas: [{ title: "Puglia-inspired pairings", items: ["rosemary focaccia", "burrata", "tandoori prawns", "mushroom crostini"] }],
    whyChoose: "Altamura gives vodka a recognisable durum-wheat character instead of aiming for complete neutrality.",
    faqs: [{ question: "What grain is used in Altamura vodka?", answer: "It is made from durum wheat grown in the Altamura area of Puglia, Italy." }, { question: "Does Altamura vodka taste strongly of wheat?", answer: "Its profile includes nutty cereal and a creamy texture, balanced by citrus, vanilla and anise." }],
    finalVerdict: "A characterful wheat vodka for a chilled pour or Martini where texture matters as much as clarity.",
    metaTitle: "Altamura Italian Vodka Guide | BevOry",
    metaDescription: "Meet Altamura durum-wheat vodka from Puglia, creamy tasting notes, Martini serves and food pairings. Find city prices on BevOry.",
  },
  altano: {
    description: "Altano is the Symington family's Douro wine range from Portugal, covering fresh whites and structured reds. Indigenous grapes such as Touriga Franca, Tinta Roriz, Viosinho and Gouveio shape its regional character.",
    story: "The Symington family launched Altano in 1999, extending its Douro experience beyond Port into dry table wine. Vineyards in Cima Corgo and Douro Superior, including the Vilarica Valley, contribute to the range.",
    tastingNotes: [{ title: "Douro red", description: "Red berries and plum meet warm spice and a firm but rounded tannin structure." }, { title: "Douro white", description: "Citrus, apple and wildflowers give the white wines a fresh, aromatic profile." }],
    howToEnjoy: [{ subheading: "Two temperatures", description: "Chill the whites and serve the reds slightly cool in a medium wine glass." }, { subheading: "Match the colour", description: "Try white Altano with fish tikka or lemon rice; pour the red with lamb chops or mushroom pulao." }],
    pairingIdeas: [{ title: "For white and red", items: ["fish tikka", "lemon rice", "lamb chops", "mushroom pulao"] }],
    whyChoose: "Altano gives Portugal's native Douro grapes a dry-wine setting backed by the Symington family's regional experience.",
    faqs: [{ question: "Is Altano a Port wine?", answer: "Altano is a dry table-wine range, although its producer, the Symington family, is also known for Port." }, { question: "Where are Altano wines from?", answer: "They come from Portugal's Douro region, including Cima Corgo and Douro Superior." }],
    finalVerdict: "Altano is a useful starting point for Douro table wine, from fragrant whites to plum-rich reds with dinner-friendly structure.",
    metaTitle: "Altano Douro Wine Guide | BevOry",
    metaDescription: "Discover Altano by the Symington family, Douro grapes, red and white tasting notes and food pairings. Check city prices on BevOry.",
  },
  "anakena-birdman": {
    description: "Anakena Birdman is a Chilean wine range with Cabernet Sauvignon, Merlot and Chardonnay among its grape-led styles. The wines favour direct fruit flavours, from dark berries in the reds to peach and tropical fruit in Chardonnay.",
    story: "Anakena's identity draws on Chile and the cultural heritage of Rapa Nui. The Birdman name refers to Tangata Manu, the island's birdman tradition, rather than a grape variety or winemaking method.",
    tastingNotes: [{ title: "Birdman Cabernet", description: "Berry fruit leads the Cabernet Sauvignon, supported by balanced tannins." }, { title: "Birdman Chardonnay", description: "Peach and tropical fruit sit above a fresh, crisp finish." }],
    howToEnjoy: [{ subheading: "Keep fruit fresh", description: "Chill Chardonnay and serve Cabernet slightly cool, using a medium glass for either." }, { subheading: "Separate the dinner matches", description: "Pour Chardonnay with chicken malai tikka or grilled fish; choose Cabernet for mushroom kebabs and roast lamb." }],
    pairingIdeas: [{ title: "Birdman at dinner", items: ["chicken malai tikka", "grilled fish", "mushroom kebabs", "roast lamb"] }],
    whyChoose: "Birdman offers approachable Chilean grape styles with clear fruit and straightforward food matches.",
    faqs: [{ question: "What does Anakena Birdman refer to?", answer: "The name draws on the Tangata Manu birdman tradition of Rapa Nui." }, { question: "Is Birdman only a red wine?", answer: "No, the range includes red grapes such as Cabernet Sauvignon and Merlot as well as Chardonnay." }],
    finalVerdict: "Choose Birdman for uncomplicated Chilean fruit flavours, with Chardonnay and Cabernet serving different places at the table.",
    metaTitle: "Anakena Birdman Wine Guide | BevOry",
    metaDescription: "Explore Anakena Birdman wines, Chilean origins, Cabernet and Chardonnay notes, serving tips and pairings. Find city prices on BevOry.",
  },
  "antigal-uno": {
    description: "Antigal UNO is a Mendoza wine range led by Malbec, with Cabernet Sauvignon and other varietal wines alongside it. The winery is based in Maipu, while its Malbec also draws on vineyards in the Uco Valley.",
    story: "Antigal restored a winery dating to 1897, beginning its modern project in 2000. The metal number one on UNO bottles was developed from the idea of reusing barrel hoops, giving the range its distinctive emblem.",
    tastingNotes: [{ title: "UNO Malbec", description: "Plum, blackberry and strawberry meet violet, vanilla and milk chocolate over silky tannins." }, { title: "UNO Cabernet Sauvignon", description: "Red and black fruit gain herbal notes, pepper and oak spice." }],
    howToEnjoy: [{ subheading: "Give red wine some air", description: "Serve slightly cool in a broad red-wine glass and let the aromas develop after pouring." }, { subheading: "Grill and slow cook", description: "Try Malbec with mutton rogan josh, grilled lamb chops or mushroom steaks." }],
    pairingIdeas: [{ title: "Mendoza red pairings", items: ["mutton rogan josh", "grilled lamb chops", "mushroom steaks", "aged cheddar"] }],
    whyChoose: "UNO combines generous Mendoza fruit with a softer tannin profile, particularly in its Malbec.",
    faqs: [{ question: "Where is Antigal UNO made?", answer: "Antigal makes UNO in Mendoza, Argentina, at its Maipu winery." }, { question: "Why is there a metal 1 on UNO bottles?", answer: "The emblem grew from a design based on barrel hoops and reflects the UNO name." }],
    finalVerdict: "UNO Malbec is a rounded, fruit-rich Mendoza red for grilled or slow-cooked food rather than delicate dishes.",
    metaTitle: "Antigal UNO Mendoza Wine Guide | BevOry",
    metaDescription: "Discover Antigal UNO, Mendoza Malbec and Cabernet notes, winery history and Indian food pairings. Check city prices on BevOry.",
  },
  archers: {
    description: "Archers is a peach liqueur brand launched in Britain and now owned by De Kuyper Royal Distillers. Its sweet peach flavour makes it a familiar ingredient in long drinks and fruit-led cocktails.",
    story: "Archers arrived in 1986 in its recognisable frosted bottle. De Kuyper acquired the brand from Diageo in 2022, adding it to a portfolio focused on liqueurs and cocktail ingredients.",
    tastingNotes: [{ title: "Peach aroma", description: "Ripe peach leads the nose with an immediately sweet, fruity character." }, { title: "Soft fruit finish", description: "Peach sweetness continues across a soft palate, without the bitterness of an orange aperitif." }],
    howToEnjoy: [{ subheading: "Lengthen with sharp fruit", description: "Pour over ice with lemonade or cranberry juice, or use it in a Woo Woo with vodka and cranberry." }, { subheading: "Balance the sweetness", description: "Salted almonds, chilli paneer and tangy fruit chaat provide contrast to the peach flavour." }],
    pairingIdeas: [{ title: "Sweet-sour matches", items: ["salted almonds", "chilli paneer", "fruit chaat", "grilled halloumi"] }],
    whyChoose: "Archers is a direct way to add peach flavour and sweetness to a long drink without muddling fresh fruit.",
    faqs: [{ question: "Is Archers vodka?", answer: "No, Archers is a peach liqueur, although it is often mixed with vodka in cocktails." }, { question: "Who owns Archers?", answer: "De Kuyper Royal Distillers acquired Archers from Diageo in 2022." }],
    finalVerdict: "A straightforward peach liqueur that works best with plenty of ice and a sharp or lightly bitter counterpoint.",
    metaTitle: "Archers Peach Liqueur Guide | BevOry",
    metaDescription: "Explore Archers peach liqueur, its British origins, tasting notes, Woo Woo serves and snack pairings. Find city prices on BevOry.",
  },
  ardmore: {
    description: "Ardmore is a peated Highland single malt made at Kennethmont in Aberdeenshire. Its Legacy expression brings together heather honey, gentle peat and creamy vanilla rather than the maritime intensity associated with many Islay malts.",
    story: "William Teacher & Sons established Ardmore in 1898 to provide malt whisky for its blends. The distillery's smoky Highland spirit remains central to its identity as both a blending malt and a single malt.",
    tastingNotes: [{ title: "Legacy aroma", description: "Heather honey, cinnamon and toffee sit above a mild peat-smoke note." }, { title: "Legacy palate", description: "Creamy vanilla and charcoal develop into a silky palate with a drier, spicy finish." }],
    howToEnjoy: [{ subheading: "A gentle water addition", description: "Taste neat in a tulip glass, then add a few drops of water to open the honey and smoke." }, { subheading: "Honey with char", description: "Pair with tandoori chicken, smoked paneer, grilled mushrooms or salted almonds." }],
    pairingIdeas: [{ title: "Highland smoke pairings", items: ["tandoori chicken", "smoked paneer", "grilled mushrooms", "salted almonds"] }],
    whyChoose: "Ardmore offers a Highland approach to peat, balancing smoke with heather honey and creamy vanilla.",
    faqs: [{ question: "Is Ardmore an Islay whisky?", answer: "No, Ardmore is a Highland distillery in Kennethmont, Aberdeenshire." }, { question: "Is Ardmore Legacy smoky?", answer: "Yes, it has a gentle peat character alongside honey, vanilla and spice." }],
    finalVerdict: "Ardmore Legacy is a useful step into smoky malt for drinkers who still want honey and vanilla in the foreground.",
    metaTitle: "Ardmore Highland Whisky Guide | BevOry",
    metaDescription: "Discover Ardmore Highland malt, Teacher's distilling history, Legacy tasting notes and smoky food pairings. Check city prices on BevOry.",
  },
  argento: {
    description: "Argento is an Argentine wine producer in Mendoza, with Malbec at the centre of a range that also includes other international grapes. Its wines belong to Grupo Avinea, part of Alejandro Bulgheroni Family Vineyards.",
    story: "Argento's vineyards and wines reflect several parts of Mendoza rather than a single uniform landscape. The Estate Bottled Malbec from Agrelo in Lujan de Cuyo gives a focused example of the house's fruit-led approach.",
    tastingNotes: [{ title: "Estate Malbec fruit", description: "Plum, raspberry and cherry give the Malbec a bright, generous fruit profile." }, { title: "Violet and texture", description: "Violet aromas rise above rounded tannins, giving the fruit a soft but defined frame." }],
    howToEnjoy: [{ subheading: "Cool the red slightly", description: "Serve Malbec below warm room temperature in a medium-to-large red-wine glass." }, { subheading: "Grill and roast", description: "Lamb chops, mutton seekh, roast aubergine and mushroom burgers suit its ripe fruit and tannin." }],
    pairingIdeas: [{ title: "Malbec at the table", items: ["lamb chops", "mutton seekh", "roast aubergine", "mushroom burgers"] }],
    whyChoose: "Argento makes Mendoza Malbec approachable through clear berry fruit, violet aromas and rounded tannins.",
    faqs: [{ question: "Where is Argento wine produced?", answer: "Argento produces wine in Mendoza, Argentina, including wines from Agrelo in Lujan de Cuyo." }, { question: "What does Argento Estate Malbec taste like?", answer: "It is fruit-led, with plum, raspberry, cherry and violet notes over rounded tannins." }],
    finalVerdict: "A fruit-first Mendoza Malbec choice for grilled food, with floral lift and enough structure to hold a meal.",
    metaTitle: "Argento Mendoza Wine Guide | BevOry",
    metaDescription: "Explore Argento wine from Mendoza, Estate Malbec tasting notes, Agrelo origins and food pairings. Find city prices on BevOry.",
  },
  "armand-de-brignac": {
    description: "Armand de Brignac is a Champagne made by the Cattier family in the Montagne de Reims. Its Brut Gold combines Pinot Noir, Chardonnay and Meunier in a blend of three vintages, presented in a metallic bottle.",
    story: "Jean-Jacques and Alexandre Cattier connect the cuvees with vineyards around Rilly-la-Montagne, Chigny-les-Roses and Ludes. The house uses first-press juice and finishes its distinctive bottles by hand.",
    tastingNotes: [{ title: "Brut Gold fruit", description: "Peach, lemon and orange blossom lead into candied citrus and a touch of honey." }, { title: "Pastry and texture", description: "Biscuit and vanilla accompany a creamy palate, with fine acidity keeping the finish fresh." }],
    howToEnjoy: [{ subheading: "A tulip rather than a narrow flute", description: "Serve chilled in a tulip-shaped Champagne glass to leave room for fruit and pastry aromas." }, { subheading: "Crisp textures", description: "Try tempura prawns, chicken malai tikka, mushroom vol-au-vents or salted almonds." }],
    pairingIdeas: [{ title: "Brut Gold pairings", items: ["tempura prawns", "chicken malai tikka", "mushroom vol-au-vents", "salted almonds"] }],
    whyChoose: "Brut Gold pairs a three-vintage Champagne blend with generous fruit, pastry notes and a notably creamy texture.",
    faqs: [{ question: "Who makes Armand de Brignac Champagne?", answer: "The Cattier family makes it in the Montagne de Reims region of Champagne, France." }, { question: "Which grapes are in Brut Gold?", answer: "Brut Gold combines Pinot Noir, Chardonnay and Meunier." }],
    finalVerdict: "Armand de Brignac Brut Gold is a broad, creamy Champagne with citrus freshness beneath its fruit and pastry richness.",
    metaTitle: "Armand de Brignac Champagne Guide | BevOry",
    metaDescription: "Discover Armand de Brignac Brut Gold, Cattier origins, Champagne grapes, tasting notes and pairings. Check city prices on BevOry.",
  },
  aultmore: {
    description: "Aultmore is a Speyside single malt distilled near Keith in Scotland. Its twelve-year-old expression favours green apple, flowers and herbs, with refill casks allowing the lighter spirit to remain prominent.",
    story: "The distillery dates to 1897 and became valued as a source of malt for blended Scotch. Its single-malt bottlings give that delicate Speyside character a stage of its own.",
    tastingNotes: [{ title: "Twelve-year fruit", description: "Green apple and fresh fruit meet a light floral aroma." }, { title: "Garden herbs", description: "Rosemary and thyme add an herbal edge to a silky, gently sweet palate." }],
    howToEnjoy: [{ subheading: "Avoid overpowering the malt", description: "Use a tulip glass and try it neat before adding a few drops of water; keep strongly flavoured mixers aside." }, { subheading: "Light savoury dishes", description: "Pair with chicken malai tikka, mushroom risotto, herbed paneer or a simple apple tart." }],
    pairingIdeas: [{ title: "Delicate malt pairings", items: ["chicken malai tikka", "mushroom risotto", "herbed paneer", "apple tart"] }],
    whyChoose: "Aultmore offers a lighter Speyside style where green fruit and herbs are not buried beneath heavy oak.",
    faqs: [{ question: "Where is Aultmore distilled?", answer: "Aultmore is distilled near Keith in Scotland's Speyside region." }, { question: "What is Aultmore 12 like?", answer: "It is delicate and silky, with green apple, flowers and herbal notes including rosemary and thyme." }],
    finalVerdict: "Aultmore suits drinkers looking for a quiet, herbal Speyside malt with fresh fruit and restrained cask influence.",
    metaTitle: "Aultmore Speyside Whisky Guide | BevOry",
    metaDescription: "Explore Aultmore Speyside malt, its 1897 origins, green-apple and herbal notes, serving tips and pairings. Find city prices on BevOry.",
  },
  balblair: {
    description: "Balblair is a Highland single malt from Edderton in Ross-shire, near the Dornoch Firth. The distillery's fruit-led style combines citrus and creamy vanilla with oak spice across its age-stated range.",
    story: "Established in 1790, Balblair is one of Scotland's long-running distilleries. Its setting near Struie Hill connects the whisky with the northern Highlands, while a twelve-year-old bottling provides an entry to the house style.",
    tastingNotes: [{ title: "Twelve-year citrus", description: "Dried orange, citrus peel and vanilla cream lead the twelve-year-old's aroma and palate." }, { title: "Spiced finish", description: "Clove, white pepper and gentle oak meet a little honey and dark chocolate toward the finish." }],
    howToEnjoy: [{ subheading: "Taste the citrus first", description: "Pour into a tulip glass and taste neat, then add a little water if the spice feels dominant." }, { subheading: "Roast and orchard fruit", description: "Chicken malai tikka, roast squash, apple crumble and dark chocolate suit the fruit-and-spice balance." }],
    pairingIdeas: [{ title: "Northern Highland matches", items: ["chicken malai tikka", "roast squash", "apple crumble", "dark chocolate"] }],
    whyChoose: "Balblair offers a fruit-led northern Highland character with creamy vanilla and enough spice to keep the finish lively.",
    faqs: [{ question: "Where is Balblair made?", answer: "Balblair is made in Edderton, Ross-shire, near the Dornoch Firth in the Scottish Highlands." }, { question: "When was Balblair established?", answer: "The distillery was established in 1790." }],
    finalVerdict: "Balblair's twelve-year-old is a citrus-and-vanilla Highland malt with a gently spicy finish, suited to an unhurried neat pour.",
    metaTitle: "Balblair Highland Whisky Guide | BevOry",
    metaDescription: "Discover Balblair Highland malt, Edderton history, twelve-year-old tasting notes and food pairings. Check city prices on BevOry.",
  },
};
