import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_LOGOS_BATCH_14: Record<string, string> = {
  "19-crimes": "https://19crimes.com/cdn/shop/files/19-crimes-logo_black_x400.jpg?v=1637703033",
  baileys: "https://static.livcheers.com/static/content/images/brand/baileys.webp",
  "black-and-white": "https://images.ctfassets.net/vvbow7h7clgh/5s7Fo6diKA0xOksUv1Xu7k/5c8d932ffb654025363cc7f0a0c37c76/9a6c0636f39262b71d8cf78347edd2f8832ac820__1_.png",
  "blenders-pride": "https://static.livcheers.com/static/content/images/brand/blenders-pride.webp",
  cotswolds: "https://static.livcheers.com/static/content/images/brand/cotswolds.webp",
  "don-julio": "https://static.livcheers.com/static/content/images/brand/don-julio.webp",
  "flor-de-cana": "https://cdn.prod.website-files.com/635173a41d48bd4bbbaefa01/67f56757e1c417a9a781587e_fdc_logo-p-500.png",
  grants: "https://static.livcheers.com/static/content/images/brand/grants.webp",
  jameson: "https://static.livcheers.com/static/content/images/brand/jameson.webp",
  "jose-cuervo": "https://static.livcheers.com/static/content/images/brand/jose-cuervo.webp",
  "kendall-jackson": "https://www.kj.com/on/demandware.static/-/Sites-KJ-Library/default/dw1d270911/images/logo/kj-logo-from-figma-2024-group3629-hq-compressed.png",
  krsma: "https://www.krsmaestates.com/wp-content/uploads/2020/03/image-logo-krsma-630x535.webp",
  "m-chapoutier": "https://www.mchapoutier.com.au/wp-content/uploads/2022/11/M.Chapoutier-Australia.png",
  "moet-and-chandon": "https://www.moet.com/themes/custom/moet/images/logo-red-header.png",
  "remy-martin": "https://static.livcheers.com/static/content/images/brand/remy-martin.webp",
  "ron-zacapa": "https://images.ctfassets.net/llp5a1wx5fd2/7B4WkDYde9YF3yWV694LK0/466789dd536c18d76f33a1c0d0dac0e0/header-logo.svg",
  singleton: "https://static.livcheers.com/static/content/images/brand/singleton.webp",
  talisker: "https://static.livcheers.com/static/content/images/brand/talisker.webp",
  tanqueray: "https://static.livcheers.com/static/content/images/brand/tanqueray.webp",
  "william-lawsons": "https://static.livcheers.com/static/content/images/brand/william-lawsons.webp",
};

export const BRAND_CONTENT_BATCH_14: Record<string, BrandPublicContent> = {
  "19-crimes": {
    description: "19 Crimes is an Australian wine brand from Treasury Wine Estates, introduced in 2012. Its labels portray British convicts transported to Australia, while the range covers fruit-forward reds, Chardonnay and sparkling wine.",
    story: "The name refers to the nineteen offences that could lead to transportation from Britain to Australia during the eighteenth and nineteenth centuries. Each cork carries one of those offences, and the portrait labels connect individual bottles with documented convict stories.",
    tastingNotes: [
      { title: "Red Blend", description: "Ripe blackberry and plum meet vanilla, sweet spice and a soft, rounded finish." },
      { title: "Cabernet Sauvignon", description: "Blackcurrant and dark cherry lead into firm tannin, cedar and a measured oak note." },
    ],
    howToEnjoy: [
      { subheading: "Give the reds some air", description: "Serve the red wines slightly cool in a broad glass and allow a newly opened bottle ten to fifteen minutes to settle." },
      { subheading: "Bring char to the plate", description: "Match the dark-fruited reds with mutton seekh kebab, smoky paneer tikka, barbecue ribs or a mushroom burger." },
    ],
    pairingIdeas: [{ title: "Bold red-wine pairings", items: ["mutton seekh kebab", "smoky paneer tikka", "barbecue ribs", "mushroom burger", "aged cheddar"] }],
    whyChoose: "19 Crimes combines accessible Australian fruit with one of the wine aisle's most recognisable historical label concepts.",
    faqs: [
      { question: "Why is the wine called 19 Crimes?", answer: "The name recalls nineteen offences for which British prisoners could be sentenced to transportation to Australia." },
      { question: "Who owns 19 Crimes wine?", answer: "19 Crimes belongs to Treasury Wine Estates, the Australian wine company behind the brand's global range." },
    ],
    finalVerdict: "19 Crimes is an easy entry into plush Australian wine, especially for drinkers who enjoy ripe fruit, gentle oak and memorable packaging.",
    metaTitle: "19 Crimes Australian Wine Guide | BevOry",
    metaDescription: "Explore 19 Crimes wine, convict-label history, red-wine flavours, serving advice, Indian food pairings and city prices on BevOry.",
  },
  baileys: {
    description: "Baileys is an Irish cream liqueur created in Dublin and launched in 1974. Irish dairy cream, Irish whiskey and spirits are combined with chocolate and vanilla flavours for its familiar rich texture.",
    story: "A small development team spent two years refining the original recipe before bringing Baileys to market. The cream is sourced largely from family-owned Irish farms and reaches the bottling process soon after leaving the dairy.",
    tastingNotes: [
      { title: "Chocolate and vanilla", description: "Milk chocolate, cocoa and vanilla arrive first, supported by sweet cream and a quiet whiskey warmth." },
      { title: "Velvety finish", description: "The dense, smooth texture carries caramel and roasted coffee notes into a lingering sweet close." },
    ],
    howToEnjoy: [
      { subheading: "Pour it over one large cube", description: "Serve Baileys chilled or over ice in a short glass, or add a measured pour to coffee after the heat has eased slightly." },
      { subheading: "Treat it like dessert", description: "Pair it with tiramisu, chocolate brownie, coffee kulfi or toasted hazelnuts rather than heavily spiced savoury food." },
    ],
    pairingIdeas: [{ title: "Cream-liqueur pairings", items: ["tiramisu", "chocolate brownie", "coffee kulfi", "toasted hazelnuts", "salted caramel tart"] }],
    whyChoose: "Baileys turns Irish whiskey and fresh cream into a dessert liqueur that works equally well over ice, with coffee or beside chocolate.",
    faqs: [
      { question: "What is Baileys made from?", answer: "Baileys Original combines Irish dairy cream with Irish whiskey and spirits, plus chocolate and vanilla flavours." },
      { question: "Does Baileys contain dairy?", answer: "Yes. Baileys Original contains dairy cream and milk proteins, so it is not suitable for people avoiding dairy." },
    ],
    finalVerdict: "Baileys remains the reference point for Irish cream liqueur, with a thick texture and clear chocolate, vanilla and coffee-friendly character.",
    metaTitle: "Baileys Irish Cream Liqueur Guide | BevOry",
    metaDescription: "Discover Baileys Irish Cream, its chocolate and vanilla profile, chilled serves, dessert pairings and city prices on BevOry.",
  },
  "black-and-white": {
    description: "Black & White is a blended Scotch whisky created by whisky merchant James Buchanan and now owned by Diageo. Its light, approachable style is built for simple pours and long mixed drinks.",
    story: "The whisky began as Buchanan's Blend before customers started asking for the bottle by its black-and-white presentation; the familiar name became official in 1902. A black Scottish Terrier and a white West Highland Terrier later became the label's enduring symbols.",
    tastingNotes: [
      { title: "Fresh opening", description: "Light cereal, cut grass and soft citrus appear over a restrained malt sweetness." },
      { title: "Easy close", description: "Vanilla, gentle pepper and faint smoke finish cleanly without heavy oak or dense peat." },
    ],
    howToEnjoy: [
      { subheading: "Keep the highball dry", description: "Pour over hard ice and lengthen with cold soda, or add ginger ale and a strip of lemon peel for a sweeter serve." },
      { subheading: "Pick crisp, salty food", description: "Masala peanuts, fish fingers, chicken tikka and vegetable cutlets suit the whisky's light body." },
    ],
    pairingIdeas: [{ title: "Casual whisky pairings", items: ["masala peanuts", "fish fingers", "chicken tikka", "vegetable cutlets", "mild cheddar"] }],
    whyChoose: "Black & White keeps blended Scotch light, clean and uncomplicated, with enough malt and spice to hold up in a highball.",
    faqs: [
      { question: "Who created Black & White whisky?", answer: "Scottish whisky merchant James Buchanan created the blend that later took the Black & White name." },
      { question: "What do the two dogs on Black & White represent?", answer: "They are a black Scottish Terrier and a white West Highland Terrier, a visual play on the brand name." },
    ],
    finalVerdict: "Black & White is a mild blended Scotch for easy highballs, casual food and drinkers who prefer little peat or oak weight.",
    metaTitle: "Black & White Scotch Whisky Guide | BevOry",
    metaDescription: "Read the Black & White Scotch guide for its Buchanan history, light flavour, highball serves, pairings and city prices on BevOry.",
  },
  "blenders-pride": {
    description: "Blenders Pride is a premium Indian blended whisky owned by Pernod Ricard India. Indian grain spirit is blended with imported Scotch malts from Chivas Brothers to create its soft, fruit-and-oak house style.",
    story: "Seagram introduced Blenders Pride in India in 1995, and the label later joined Pernod Ricard's Indian portfolio. Reserve Collection extends the range with a fuller presentation while retaining the brand's grain-and-malt foundation.",
    tastingNotes: [
      { title: "Rare Premium Whisky", description: "Orchard fruit, honeyed grain and vanilla sit beside gentle wood spice and a smooth finish." },
      { title: "Reserve Collection", description: "Dried fruit, caramel and toasted oak give the richer expression more depth and warmth." },
    ],
    howToEnjoy: [
      { subheading: "Taste before adding water", description: "Begin with a small neat pour in a tulip glass, then add a few drops of water or build a restrained soda highball." },
      { subheading: "Use roast and spice", description: "Serve with galouti kebabs, tandoori mushrooms, pepper chicken or roasted cashews." },
    ],
    pairingIdeas: [{ title: "Indian whisky pairings", items: ["galouti kebabs", "tandoori mushrooms", "pepper chicken", "roasted cashews", "dark chocolate"] }],
    whyChoose: "Blenders Pride places Scotch malt character inside a polished Indian blend with familiar fruit, vanilla and gentle oak.",
    faqs: [
      { question: "Who makes Blenders Pride?", answer: "Blenders Pride is owned and marketed by Pernod Ricard India." },
      { question: "What is blended into Blenders Pride?", answer: "The whisky combines Indian grain spirit with imported Scotch malts sourced from Chivas Brothers." },
    ],
    finalVerdict: "Blenders Pride is a rounded Indian whisky that balances clean grain spirit with enough Scotch malt and oak to reward a neat pour.",
    metaTitle: "Blenders Pride Indian Whisky Guide | BevOry",
    metaDescription: "Explore Blenders Pride whisky, its Indian grain and Scotch malt blend, tasting notes, food matches and city prices on BevOry.",
  },
  cotswolds: {
    description: "Cotswolds is an English distillery founded by Daniel Szor near Stourton in 2014. It produces single malt whisky from locally grown barley alongside a botanical-rich dry gin.",
    story: "Szor left a finance career in London after noticing that the barley surrounding his Cotswolds home was not being distilled locally. Signature Single Malt arrived in 2017 as the first whisky distilled in the Cotswolds, three years after the distillery opened.",
    tastingNotes: [
      { title: "Signature Single Malt", description: "Ripe red fruit, honey and malt meet vanilla, toasted spice and a full, oily texture." },
      { title: "Cotswolds Dry Gin", description: "Juniper, grapefruit and lime are lifted by lavender and other floral botanicals, turning visibly cloudy with tonic." },
    ],
    howToEnjoy: [
      { subheading: "Choose the glass by spirit", description: "Give the whisky a tulip glass and a few drops of water; serve the gin over ice with tonic and a slice of pink grapefruit." },
      { subheading: "Pair fruit with savoury depth", description: "Try the whisky with roast lamb or mushroom galouti, and the gin with tandoori prawns or goat-cheese salad." },
    ],
    pairingIdeas: [{ title: "English spirit pairings", items: ["roast lamb", "mushroom galouti", "tandoori prawns", "goat-cheese salad", "lemon tart"] }],
    whyChoose: "Cotswolds offers two clear signatures from one rural English distillery: fruit-rich single malt and intensely aromatic dry gin.",
    faqs: [
      { question: "Who founded Cotswolds Distillery?", answer: "Daniel Szor founded the distillery near Stourton, Warwickshire, and opened its doors in July 2014." },
      { question: "Why does Cotswolds Dry Gin turn cloudy?", answer: "Its high concentration of botanical oils forms a pearly cloud when the gin is mixed with tonic or water." },
    ],
    finalVerdict: "Cotswolds brings local English barley and an assertive botanical recipe together in a compact distillery with two distinct strengths.",
    metaTitle: "Cotswolds English Whisky & Gin Guide | BevOry",
    metaDescription: "Discover Cotswolds whisky and gin, local barley, botanical flavours, serving ideas, food pairings and city prices on BevOry.",
  },
  "don-julio": {
    description: "Don Julio is a tequila house founded by Don Julio Gonzalez in the Highlands of Jalisco, Mexico. Its tequilas use 100% Blue Weber agave grown in the region's red clay and volcanic soils.",
    story: "Gonzalez began making tequila in 1942 after securing a loan for La Primavera distillery in Atotonilco El Alto. He focused on mature agave, careful hand harvesting and quality-led production at a time when tequila was commonly treated as a volume spirit.",
    tastingNotes: [
      { title: "Blanco", description: "Cooked agave, fresh citrus and green herbs meet white pepper and a clean, lightly sweet finish." },
      { title: "Reposado", description: "Vanilla, caramel and dried fruit soften the peppery agave while American oak adds warm spice." },
    ],
    howToEnjoy: [
      { subheading: "Use a narrow agave glass", description: "Sip Blanco or Reposado neat at cool room temperature, or build Blanco into a Margarita with fresh lime and restrained sweetness." },
      { subheading: "Let citrus and char connect", description: "Pair Blanco with ceviche or tandoori prawns and Reposado with lamb barbacoa, mole chicken or grilled corn." },
    ],
    pairingIdeas: [{ title: "Jalisco pairings", items: ["ceviche", "tandoori prawns", "lamb barbacoa", "mole chicken", "grilled corn"] }],
    whyChoose: "Don Julio shows Highland agave through a precise progression from fresh, peppery Blanco to rounded oak-aged tequila.",
    faqs: [
      { question: "Where is Don Julio tequila made?", answer: "Don Julio is produced at La Primavera in the Highlands of Jalisco, around Atotonilco El Alto." },
      { question: "What agave does Don Julio use?", answer: "The house makes tequila from 100% Blue Weber agave grown in Jalisco." },
    ],
    finalVerdict: "Don Julio is a dependable Highland tequila range with ripe agave at its centre and oak used to build texture rather than hide it.",
    metaTitle: "Don Julio Tequila Guide | BevOry",
    metaDescription: "Explore Don Julio tequila, Highland Jalisco agave, Blanco and Reposado notes, food pairings and city prices on BevOry.",
  },
  "flor-de-cana": {
    description: "Flor de Caña is a Nicaraguan rum made by the Pellas family at the foot of the San Cristobal volcano. The house uses sugarcane molasses, column distillation and American oak maturation for a notably dry aged-rum profile.",
    story: "The family's rum history began in 1890 with a distillery linked to the San Antonio sugar estate in Chichigalpa. Five generations later, the volcanic landscape and hot tropical climate remain central to the brand's account of maturation.",
    tastingNotes: [
      { title: "12 Year", description: "Baked apple, honey and toasted nuts meet vanilla, dry oak and a long, restrained finish." },
      { title: "7 Year Gran Reserva", description: "Caramel, dark fruit and roasted coconut sit over peppery oak and a drier close than many sweet rums." },
    ],
    howToEnjoy: [
      { subheading: "Respect the dry edge", description: "Sip the 12 Year neat or over one cube, and use the 7 Year in a Rum Old Fashioned with very little added sugar." },
      { subheading: "Choose caramelised food", description: "Pork ribs, mutton roast, grilled pineapple and pecan tart echo the rum's toasted sugar and oak." },
    ],
    pairingIdeas: [{ title: "Nicaraguan rum pairings", items: ["pork ribs", "mutton roast", "grilled pineapple", "pecan tart", "dark chocolate"] }],
    whyChoose: "Flor de Caña favours firm oak, roasted nuts and a dry finish over the syrupy sweetness found in many aged rums.",
    faqs: [
      { question: "Where is Flor de Caña rum made?", answer: "Flor de Caña is made in Chichigalpa, Nicaragua, near the San Cristobal volcano." },
      { question: "Who owns Flor de Caña?", answer: "The Pellas family has remained behind Flor de Caña through five generations of rum production." },
    ],
    finalVerdict: "Flor de Caña is a dry-leaning Nicaraguan rum whose roasted fruit and oak work particularly well in slow pours and restrained cocktails.",
    metaTitle: "Flor de Caña Nicaraguan Rum Guide | BevOry",
    metaDescription: "Explore Flor de Caña rum, volcanic Nicaragua, dry aged-rum flavours, serving ideas, pairings and city prices on BevOry.",
  },
  grants: {
    description: "Grant's is a blended Scotch whisky made by the family-owned William Grant & Sons. Girvan grain whisky forms the core, supported by malt whiskies and maturation in selected oak casks.",
    story: "William Grant built Glenfiddich with his nine children and produced the family's first spirit there in 1887. Six generations later, the company remains family controlled, while the triangular Grant's bottle has become its visual signature.",
    tastingNotes: [
      { title: "Triple Wood", description: "Pear, vanilla and malt open into light cinnamon, caramel and a clean, gently smoky finish." },
      { title: "Sherry Cask Finish", description: "Dried fruit, orange peel and baking spice add depth to the familiar grain-led softness." },
    ],
    howToEnjoy: [
      { subheading: "Build from neat to long", description: "Taste a small pour first, then add water or lengthen with soda and lemon in a cold highball." },
      { subheading: "Set out a savoury plate", description: "Pair with chicken tikka, hara bhara kebab, roasted almonds or mature cheddar." },
    ],
    pairingIdeas: [{ title: "Blended Scotch pairings", items: ["chicken tikka", "hara bhara kebab", "roasted almonds", "mature cheddar", "apple tart"] }],
    whyChoose: "Grant's uses family-owned grain and malt resources to produce a clean, fruit-led Scotch that remains flexible at the table.",
    faqs: [
      { question: "Who makes Grant's whisky?", answer: "Grant's is made by William Grant & Sons, the independent Scottish family company founded by William Grant." },
      { question: "What is at the heart of Grant's blend?", answer: "Grain whisky from the family's Girvan Distillery provides the blend's light, smooth foundation." },
    ],
    finalVerdict: "Grant's is a straightforward family-made blend with pear, vanilla and gentle spice that can move from neat pours to soda highballs.",
    metaTitle: "Grant's Blended Scotch Whisky Guide | BevOry",
    metaDescription: "Discover Grant's Scotch, Girvan grain whisky, Triple Wood flavours, highball serves, Indian pairings and city prices on BevOry.",
  },
  jameson: {
    description: "Jameson is an Irish whiskey founded by John Jameson at Bow Street, Dublin, in 1780 and now distilled at Midleton in County Cork. The core blend combines pot still and grain whiskeys and is triple distilled for a light, rounded texture.",
    story: "John Jameson took charge of the Bow Street distillery and built one of Dublin's major whiskey houses. Production moved to the modern Midleton Distillery in the 1970s, while Bow Street remains the brand's historic visitor home.",
    tastingNotes: [
      { title: "Jameson Original", description: "Fresh apple, cut grass and vanilla move into toasted wood, soft spice and a clean finish." },
      { title: "Black Barrel", description: "Caramel, tropical fruit and toasted nuts gain extra vanilla and char from flame-charred bourbon barrels." },
    ],
    howToEnjoy: [
      { subheading: "Make a tall ginger serve", description: "Pour Jameson over ice, add ginger ale and finish with lime, or taste Black Barrel neat in a tulip glass." },
      { subheading: "Work with sweet spice", description: "Butter chicken, glazed pork, chilli paneer and apple crumble fit the whiskey's vanilla and orchard fruit." },
    ],
    pairingIdeas: [{ title: "Irish whiskey pairings", items: ["butter chicken", "glazed pork", "chilli paneer", "apple crumble", "aged cheddar"] }],
    whyChoose: "Jameson pairs triple-distilled softness with enough pot-still spice to remain recognisable in a highball.",
    faqs: [
      { question: "Where is Jameson made today?", answer: "Jameson is distilled at the Midleton Distillery in County Cork, Ireland." },
      { question: "Is Jameson a single malt?", answer: "No. Jameson Original is a blend of Irish pot still whiskey and grain whiskey." },
    ],
    finalVerdict: "Jameson is a versatile Irish blend whose apple, vanilla and gentle spice make both neat pours and simple mixed serves work.",
    metaTitle: "Jameson Irish Whiskey Guide | BevOry",
    metaDescription: "Explore Jameson Irish whiskey, Bow Street history, triple distillation, tasting notes, pairings and city prices on BevOry.",
  },
  "jose-cuervo": {
    description: "Jose Cuervo is a tequila house rooted in the town of Tequila, Jalisco, and owned by the Beckmann family through Becle. Its portfolio stretches from Especial mixto tequila to 100% agave Tradicional and Reserva de la Familia.",
    story: "Jose Antonio de Cuervo received land for agave cultivation in 1758, and Jose Maria Guadalupe Cuervo gained the first royal commercial tequila licence in 1795. Production continues at La Rojeña, founded in 1812 and recognised as Latin America's oldest active distillery.",
    tastingNotes: [
      { title: "Tradicional Plata", description: "Cooked agave, lime and fresh herbs lead into black pepper and a dry, clean close." },
      { title: "Tradicional Reposado", description: "Roasted agave gains vanilla, caramel and light oak spice while retaining a peppery centre." },
    ],
    howToEnjoy: [
      { subheading: "Keep lime fresh", description: "Sip Tradicional from a narrow glass or shake it with fresh lime and orange liqueur for a balanced Margarita." },
      { subheading: "Put agave beside acidity", description: "Ceviche, fish tacos, achari paneer and grilled prawns sharpen the cooked-agave and citrus notes." },
    ],
    pairingIdeas: [{ title: "Tequila-table pairings", items: ["ceviche", "fish tacos", "achari paneer", "grilled prawns", "roasted corn"] }],
    whyChoose: "Jose Cuervo connects tequila's earliest commercial history with a range that covers everyday mixing and serious 100% agave bottles.",
    faqs: [
      { question: "Where is Jose Cuervo made?", answer: "Jose Cuervo is produced at La Rojeña in Tequila, Jalisco, Mexico." },
      { question: "Is every Jose Cuervo tequila 100% agave?", answer: "No. Tradicional and Reserva de la Familia are 100% agave lines, while Especial is a mixto tequila." },
    ],
    finalVerdict: "Jose Cuervo is best understood expression by expression, from straightforward Especial mixers to agave-led Tradicional and Reserva bottles.",
    metaTitle: "Jose Cuervo Tequila Guide | BevOry",
    metaDescription: "Learn Jose Cuervo's Jalisco history, compare Tradicional tequila styles, serving ideas, food pairings and city prices on BevOry.",
  },
  "kendall-jackson": {
    description: "Kendall-Jackson is a California wine estate founded by Jess Jackson and his family in 1982. Vintner's Reserve Chardonnay anchors a portfolio drawn largely from cool coastal vineyards across California.",
    story: "The first 1982 Vintner's Reserve Chardonnay established the house's fruit-forward, oak-shaped style and reached the market the following year. Kendall-Jackson remains part of Jackson Family Wines, with family-owned vineyards supplying many of its regional and reserve bottlings.",
    tastingNotes: [
      { title: "Vintner's Reserve Chardonnay", description: "Pineapple, mango and citrus meet vanilla, toasted oak and a creamy texture balanced by fresh acidity." },
      { title: "Vintner's Reserve Cabernet", description: "Black cherry, cassis and mocha sit over fine tannin, cedar and a lingering dark-fruit finish." },
    ],
    howToEnjoy: [
      { subheading: "Chill Chardonnay gently", description: "Serve Chardonnay at 10 to 12 degrees Celsius in a white-wine glass; give Cabernet a broad glass at about 16 degrees Celsius." },
      { subheading: "Follow the wine's weight", description: "Match Chardonnay with malai tikka or grilled fish and Cabernet with lamb chops, mushroom galouti or aged cheddar." },
    ],
    pairingIdeas: [{ title: "California wine pairings", items: ["malai tikka", "grilled fish", "lamb chops", "mushroom galouti", "aged cheddar"] }],
    whyChoose: "Kendall-Jackson delivers a clear California style, led by richly textured Chardonnay and ripe coastal fruit.",
    faqs: [
      { question: "Who founded Kendall-Jackson?", answer: "Jess Jackson and his family established Kendall-Jackson in California in 1982." },
      { question: "Which Kendall-Jackson wine is best known?", answer: "Vintner's Reserve Chardonnay is the label most closely associated with Kendall-Jackson." },
    ],
    finalVerdict: "Kendall-Jackson is a reliable California producer for drinkers who enjoy ripe fruit, measured oak and a generous Chardonnay texture.",
    metaTitle: "Kendall-Jackson California Wine Guide | BevOry",
    metaDescription: "Explore Kendall-Jackson wine, Vintner's Reserve Chardonnay, coastal fruit, serving advice and city prices on BevOry.",
  },
  krsma: {
    description: "KRSMA Estates is an Indian winery founded by Krishna and Uma Chigurupati near Hampi in Karnataka. Its estate-grown range focuses on Cabernet Sauvignon, Sangiovese, Syrah, Sauvignon Blanc and Chardonnay from the Hampi Hills.",
    story: "The Chigurupatis found the rocky, previously unplanted site in 2008 and built a vineyard among granite hills close to the UNESCO-listed ruins of Hampi. The name KRSMA combines letters from Krishna and Uma, reflecting the founders' direct role in the estate.",
    tastingNotes: [
      { title: "Cabernet Sauvignon", description: "Cassis, black cherry and dried herbs meet firm tannin, cedar and savoury oak." },
      { title: "Sangiovese", description: "Red cherry, plum and violet sit beside fresh acidity, fine tannin and a gentle earthy note." },
    ],
    howToEnjoy: [
      { subheading: "Give Hampi reds time", description: "Decant Cabernet Sauvignon or Sangiovese for twenty to thirty minutes and serve slightly below warm room temperature." },
      { subheading: "Use char and tomato", description: "Pair the reds with lamb seekh, tomato-rich pasta, paneer tikka or wood-fired mushroom pizza." },
    ],
    pairingIdeas: [{ title: "Hampi Hills pairings", items: ["lamb seekh", "tomato-rich pasta", "paneer tikka", "wood-fired mushroom pizza", "aged gouda"] }],
    whyChoose: "KRSMA gives Karnataka's granite Hampi Hills a precise wine identity through estate-grown fruit and small-scale releases.",
    faqs: [
      { question: "Where is KRSMA wine made?", answer: "KRSMA Estates grows and makes its wine in the Hampi Hills of Karnataka, near the historic ruins of Hampi." },
      { question: "Who founded KRSMA Estates?", answer: "Krishna and Uma Chigurupati founded the estate after discovering the Hampi Hills vineyard site in 2008." },
    ],
    finalVerdict: "KRSMA is a distinctive Indian estate whose structured reds carry the ripe fruit, acidity and savoury character of the Hampi Hills.",
    metaTitle: "KRSMA Hampi Hills Wine Guide | BevOry",
    metaDescription: "Discover KRSMA Estates from Hampi Hills, its Cabernet and Sangiovese styles, Indian pairings and city prices on BevOry.",
  },
  "m-chapoutier": {
    description: "M. Chapoutier is a family wine house based in Tain-l'Hermitage in France's northern Rhône Valley. Syrah and Marsanne sit at the heart of its Hermitage wines, while the wider portfolio reaches across France and several international regions.",
    story: "The house traces its history to 1808, and Marius Chapoutier joined the business that took his family name in 1897. Michel Chapoutier assumed control in 1990, expanded biodynamic farming and continued the Braille labels introduced across the range.",
    tastingNotes: [
      { title: "Crozes-Hermitage Syrah", description: "Blackberry, violet and cracked pepper meet olive, firm tannin and a savoury mineral finish." },
      { title: "Rhône White", description: "Pear, white peach and honeysuckle sit over a broad texture with almond and gentle freshness." },
    ],
    howToEnjoy: [
      { subheading: "Use Rhône-shaped glasses", description: "Serve Syrah around 16 degrees Celsius with air; chill Marsanne-based whites lightly so their texture remains visible." },
      { subheading: "Match pepper and herbs", description: "Choose rogan josh, grilled lamb, mushroom galouti or herb-roasted chicken for the house's savoury Rhône profile." },
    ],
    pairingIdeas: [{ title: "Rhône Valley pairings", items: ["rogan josh", "grilled lamb", "mushroom galouti", "herb-roasted chicken", "aged Comte"] }],
    whyChoose: "Chapoutier offers a detailed view of Rhône terroir, from peppery northern Syrah to textured Marsanne and biodynamic single parcels.",
    faqs: [
      { question: "Where is M. Chapoutier based?", answer: "The family house is based in Tain-l'Hermitage in the northern Rhône Valley of France." },
      { question: "Why do M. Chapoutier labels use Braille?", answer: "The house added Braille to its labels in tribute to Maurice de la Sizeranne, a Tain-born advocate for blind people." },
    ],
    finalVerdict: "Chapoutier rewards Rhône drinkers with expressive Syrah and Marsanne shaped by site, careful farming and a long family history.",
    metaTitle: "M. Chapoutier Rhône Wine Guide | BevOry",
    metaDescription: "Explore M. Chapoutier wines, Rhône Syrah and Marsanne, biodynamic history, food pairings and city prices on BevOry.",
  },
  "moet-and-chandon": {
    description: "Moët & Chandon is a Champagne house founded by Claude Moët in Épernay, France, in 1743. Moët Impérial blends Pinot Noir, Pinot Meunier and Chardonnay into the house's bright, fruit-led non-vintage style.",
    story: "Claude Moët developed an international market for Champagne, while his grandson Jean-Rémy expanded the house during the Napoleonic era. The maison now works from the Avenue de Champagne above an extensive network of chalk cellars in Épernay.",
    tastingNotes: [
      { title: "Moët Impérial", description: "Green apple, pear and citrus meet brioche, white flowers and a lively, fine-beaded finish." },
      { title: "Rosé Impérial", description: "Wild strawberry, raspberry and cherry gain peppery lift and a fleshy, energetic palate." },
    ],
    howToEnjoy: [
      { subheading: "Use a white-wine glass", description: "Chill to 8 to 10 degrees Celsius and pour into a tulip-shaped white-wine glass rather than an extremely narrow flute." },
      { subheading: "Keep the food crisp", description: "Serve Impérial with tandoori prawns, tempura vegetables, sushi or soft-rind cheese; pair Rosé with duck or berry tart." },
    ],
    pairingIdeas: [{ title: "Champagne pairings", items: ["tandoori prawns", "tempura vegetables", "sushi", "soft-rind cheese", "berry tart"] }],
    whyChoose: "Moët & Chandon delivers the recognisable Champagne balance of orchard fruit, brioche and brisk acidity on a large-house scale.",
    faqs: [
      { question: "Where is Moët & Chandon made?", answer: "Moët & Chandon is based in Épernay and makes Champagne from vineyards across France's Champagne region." },
      { question: "Which grapes are used in Moët Impérial?", answer: "Moët Impérial is assembled from Pinot Noir, Pinot Meunier and Chardonnay." },
    ],
    finalVerdict: "Moët & Chandon Impérial is polished, energetic Champagne with enough fruit and brioche to work from aperitif through a light meal.",
    metaTitle: "Moët & Chandon Champagne Guide | BevOry",
    metaDescription: "Explore Moët & Chandon Champagne, Impérial flavours, Épernay history, serving tips, pairings and city prices on BevOry.",
  },
  "remy-martin": {
    description: "Rémy Martin is a Cognac house founded by winegrower Rémy Martin in 1724. Its Cognac Fine Champagne blends eaux-de-vie from Grande Champagne and Petite Champagne, with at least half coming from Grande Champagne.",
    story: "King Louis XV granted Rémy Martin the rare right to plant new vines in 1738, recognising the quality of his Cognac. The centaur became the house emblem in 1870 as the family expanded exports beyond Europe.",
    tastingNotes: [
      { title: "VSOP", description: "Apricot, ripe peach and vanilla meet liquorice, gentle oak and a smooth, warming close." },
      { title: "1738 Accord Royal", description: "Plum, fig and butterscotch develop into toasted bread, baking spice and a rounder, deeper finish." },
    ],
    howToEnjoy: [
      { subheading: "Use a tulip, not a hot bowl", description: "Pour at room temperature into a tulip glass, hold it by the stem and allow the Cognac to open without warming it aggressively." },
      { subheading: "Follow stone fruit and oak", description: "Pair VSOP with galouti kebab or roast duck and 1738 with fruit cake, roasted almonds or dark chocolate." },
    ],
    pairingIdeas: [{ title: "Fine Champagne pairings", items: ["galouti kebab", "roast duck", "fruit cake", "roasted almonds", "dark chocolate"] }],
    whyChoose: "Rémy Martin specialises in Fine Champagne Cognac, bringing floral fruit and long maturation together across a focused house style.",
    faqs: [
      { question: "What does Cognac Fine Champagne mean?", answer: "It denotes a blend from Grande Champagne and Petite Champagne, with Grande Champagne providing at least fifty percent." },
      { question: "When was Rémy Martin founded?", answer: "Winegrower Rémy Martin began selling Cognac under his own name in 1724." },
    ],
    finalVerdict: "Rémy Martin is a fruit-rich, polished Cognac house whose VSOP and 1738 make the Grande and Petite Champagne blend easy to appreciate.",
    metaTitle: "Rémy Martin Cognac Guide | BevOry",
    metaDescription: "Discover Rémy Martin Fine Champagne Cognac, VSOP and 1738 notes, serving advice, pairings and city prices on BevOry.",
  },
  "ron-zacapa": {
    description: "Zacapa is a Guatemalan rum created in 1976 and made from concentrated first-press sugarcane juice rather than conventional molasses. Its component rums mature in the highlands at about 2,300 metres using a solera-style sequence of casks.",
    story: "The brand was introduced to mark the centenary of Zacapa, a town in eastern Guatemala. Maturation takes place at the House Above the Clouds in Quetzaltenango, where cooler mountain conditions slow the interaction between spirit and wood.",
    tastingNotes: [
      { title: "Zacapa 23", description: "Caramel, raisin and orange peel meet vanilla, toasted nuts, cocoa and sweet oak." },
      { title: "Zacapa XO", description: "Dark cherry, prune and spice deepen into roasted coffee, chocolate and a polished Cognac-cask finish." },
    ],
    howToEnjoy: [
      { subheading: "Let one cube melt slowly", description: "Serve Zacapa 23 neat or over a single large cube; give XO a tulip glass and several quiet minutes before sipping." },
      { subheading: "Meet richness with roast", description: "Choose pork belly, mutton roast, grilled pineapple, pecan pie or high-cocoa dark chocolate." },
    ],
    pairingIdeas: [{ title: "Highland rum pairings", items: ["pork belly", "mutton roast", "grilled pineapple", "pecan pie", "dark chocolate"] }],
    whyChoose: "Zacapa combines sugarcane honey, cool highland maturation and layered cask ageing for a plush, dessert-spiced rum profile.",
    faqs: [
      { question: "Where is Zacapa rum aged?", answer: "Zacapa matures in Quetzaltenango, Guatemala, at the highland site known as the House Above the Clouds." },
      { question: "Is Zacapa made from molasses?", answer: "Zacapa uses concentrated first-press sugarcane juice, often called virgin sugarcane honey, as its fermentation base." },
    ],
    finalVerdict: "Zacapa is a rich Guatemalan sipping rum where raisin, caramel, orange and cocoa are shaped by cool mountain ageing.",
    metaTitle: "Zacapa Guatemalan Rum Guide | BevOry",
    metaDescription: "Explore Zacapa rum, sugarcane honey, highland solera ageing, tasting notes, rich food pairings and city prices on BevOry.",
  },
  singleton: {
    description: "The Singleton is Diageo's single malt Scotch whisky brand drawn from Glen Ord, Dufftown and Glendullan distilleries. Long fermentation, slow distillation and American and European oak support its smooth, fruit-led style.",
    story: "The brand brings three Scottish distilleries under one name, with the source traditionally varying by market. Glen Ord represents the Highland side of the family, while Dufftown and Glendullan are based in Speyside.",
    tastingNotes: [
      { title: "12 Year Old", description: "Baked apple, pear and honey meet vanilla, toasted nuts and soft baking spice." },
      { title: "15 Year Old", description: "Richer orchard fruit and caramel develop into cinnamon, gentle oak and a longer, silkier finish." },
    ],
    howToEnjoy: [
      { subheading: "Open it with a few drops", description: "Taste in a tulip glass at room temperature, then add a small amount of water to lift the fruit and honey." },
      { subheading: "Choose gentle savoury flavours", description: "Roast chicken, tandoori salmon, mushroom galouti and almond tart preserve the whisky's soft texture." },
    ],
    pairingIdeas: [{ title: "Smooth malt pairings", items: ["roast chicken", "tandoori salmon", "mushroom galouti", "almond tart", "mild cheddar"] }],
    whyChoose: "The Singleton makes slow distillation and cask-led fruit approachable without stripping away the identity of its Scottish distilleries.",
    faqs: [
      { question: "Which distillery makes The Singleton?", answer: "The Singleton name covers single malts from Glen Ord, Dufftown and Glendullan, with different distilleries prominent in different markets." },
      { question: "What does The Singleton taste like?", answer: "The shared house direction is smooth and fruit-led, commonly showing apple, pear, honey, vanilla and gentle spice." },
    ],
    finalVerdict: "The Singleton is an approachable single malt family whose orchard fruit, honey and soft oak make slow sipping easy.",
    metaTitle: "The Singleton Scotch Whisky Guide | BevOry",
    metaDescription: "Explore The Singleton whisky from Glen Ord, Dufftown and Glendullan, with tasting notes, pairings and city prices on BevOry.",
  },
  talisker: {
    description: "Talisker is a single malt Scotch whisky made at Carbost on the Isle of Skye. Its coastal house style combines pepper, maritime salinity, malt sweetness and measured peat smoke.",
    story: "Brothers Hugh and Kenneth MacAskill founded Talisker beside Loch Harport in 1830. It remains Skye's oldest working distillery and draws its water from springs on the Cnoc nan Speireag ridge above the site.",
    tastingNotes: [
      { title: "Talisker 10 Year Old", description: "Sea spray, black pepper and peat smoke meet barley sweetness, citrus and a long warming finish." },
      { title: "Talisker Storm", description: "Smoke and brine arrive more forcefully, followed by chilli heat, honeyed malt and charred oak." },
    ],
    howToEnjoy: [
      { subheading: "Add water after the first sip", description: "Use a tulip glass at room temperature and introduce a few drops of water to separate the smoke, citrus and pepper." },
      { subheading: "Match the coast", description: "Smoked salmon, tandoori fish, pepper lamb and charred aubergine stand up to Talisker's smoke and salinity." },
    ],
    pairingIdeas: [{ title: "Skye-inspired pairings", items: ["smoked salmon", "tandoori fish", "pepper lamb", "charred aubergine", "dark chocolate"] }],
    whyChoose: "Talisker expresses Skye through a distinctive meeting of sea salt, cracked pepper, sweet malt and controlled peat smoke.",
    faqs: [
      { question: "Where is Talisker whisky made?", answer: "Talisker is distilled at Carbost on the shore of Loch Harport on Scotland's Isle of Skye." },
      { question: "Is Talisker smoky?", answer: "Yes. Talisker uses peated malt, but its smoke is balanced by pepper, maritime notes and malt sweetness." },
    ],
    finalVerdict: "Talisker is a characterful island malt whose pepper and sea spray make its peat feel vivid rather than simply heavy.",
    metaTitle: "Talisker Isle of Skye Whisky Guide | BevOry",
    metaDescription: "Discover Talisker whisky from Skye, with smoke, sea salt and pepper notes, serving advice, pairings and city prices on BevOry.",
  },
  tanqueray: {
    description: "Tanqueray is a London Dry gin founded by Charles Tanqueray in Bloomsbury, London, in 1830 and now produced by Diageo at Cameronbridge in Fife. The classic recipe centres on juniper, coriander, angelica and liquorice.",
    story: "Charles Tanqueray tested hundreds of botanical combinations before settling on the spare four-botanical London Dry recipe. The distillery survived severe wartime damage in London before production eventually moved to Scotland.",
    tastingNotes: [
      { title: "London Dry", description: "Firm piney juniper leads coriander citrus, dry angelica and a peppery, clean finish." },
      { title: "No. Ten", description: "Fresh grapefruit, lime and orange soften the juniper with chamomile and a silkier citrus-led close." },
    ],
    howToEnjoy: [
      { subheading: "Keep tonic below the rim", description: "Build London Dry over hard ice with crisp tonic and lime; use No. Ten with grapefruit in a colder, drier Martini." },
      { subheading: "Lean into citrus and herbs", description: "Tandoori prawns, coriander chicken, goat-cheese salad and lemon-pepper paneer fit the botanical profile." },
    ],
    pairingIdeas: [{ title: "Botanical gin pairings", items: ["tandoori prawns", "coriander chicken", "goat-cheese salad", "lemon-pepper paneer", "salted almonds"] }],
    whyChoose: "Tanqueray gives juniper the lead, with a concise botanical recipe that remains clear even after tonic is added.",
    faqs: [
      { question: "Who created Tanqueray gin?", answer: "Charles Tanqueray founded the brand and began distilling in London's Bloomsbury district in 1830." },
      { question: "Which botanicals are in Tanqueray London Dry?", answer: "Its core botanical set is juniper, coriander seed, angelica root and liquorice." },
    ],
    finalVerdict: "Tanqueray is a firm, dry, juniper-first gin that keeps its identity in tonic, a Gimlet or a cold Martini.",
    metaTitle: "Tanqueray London Dry Gin Guide | BevOry",
    metaDescription: "Explore Tanqueray gin, its four botanicals, London history, tonic and Martini serves, pairings and city prices on BevOry.",
  },
  "william-lawsons": {
    description: "William Lawson's is a blended Scotch whisky owned by Bacardi and built around malt whisky from Macduff Distillery in the Highlands. The house style avoids peat smoke in favour of cereal, fruit, vanilla and warm spice.",
    story: "The name comes from William Lawson, who worked with the business that developed the blend during the nineteenth century. Macduff became the brand's malt home after William Lawson Distillers acquired the Highland distillery in 1972.",
    tastingNotes: [
      { title: "Original", description: "Malted cereal, green apple and caramel meet vanilla, baking spice and a clean, smoke-free finish." },
      { title: "Super Spiced", description: "Vanilla and cinnamon become more pronounced, joined by maple-like sweetness and toasted fruit." },
    ],
    howToEnjoy: [
      { subheading: "Make an unfussy long drink", description: "Serve Original over ice with cola, ginger ale or apple juice, keeping enough whisky in the glass to retain its malt character." },
      { subheading: "Bring crisp heat", description: "Pair with pepper chicken, seekh kebab, masala fries or smoked paneer." },
    ],
    pairingIdeas: [{ title: "Highland blend pairings", items: ["pepper chicken", "seekh kebab", "masala fries", "smoked paneer", "apple crumble"] }],
    whyChoose: "William Lawson's offers a bold, smoke-free Scotch profile designed for ice, cola and relaxed food-led drinking.",
    faqs: [
      { question: "Where is William Lawson's made?", answer: "The blend is made in Scotland, with Macduff Distillery in the Highlands supplying its central malt character." },
      { question: "Is William Lawson's smoky?", answer: "No. The brand describes its Scotch as unpeated, with fruit, cereal, vanilla and spice taking the lead." },
    ],
    finalVerdict: "William Lawson's is a robust but smoke-free blend that works best in straightforward long drinks beside spicy, savoury food.",
    metaTitle: "William Lawson's Scotch Whisky Guide | BevOry",
    metaDescription: "Explore William Lawson's Scotch, Macduff malt, smoke-free flavours, mixed serves, Indian pairings and city prices on BevOry.",
  },
};
