import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_32 = [
  ["los-vascos", "Los Vascos", "Chile", "Wine", "662169138b14e04234da706b"],
  ["love-by-leoube", "Love by Leoube", "France", "Wine", "761dd7e00dbeaaf6ec235b72"],
  ["loveblock", "Loveblock", "New Zealand", "Wine", "a0f04dddd249551cb065b7f1"],
  ["maison-alexandrins", "Maison les Alexandrins", "France", "Wine", "05c6422ae8066d39c97fcf6e"],
  ["man-family", "MAN Family Wines", "South Africa", "Wine", "1bcf2c8de3fc414aa76bafb3"],
  ["mancino", "Mancino", "Italy", "Vermouth", "4dcf857b11efbb9b8fee94b9"],
  ["mars-tsunuki", "Mars Tsunuki", "Japan", "Japanese Whisky", "dd8ea944191f1c7b9d52dcee"],
  ["martin-millers", "Martin Miller's", "United Kingdom", "Gin", "bca1fab0e584a62fa3c77941"],
  ["mas-de-daumas", "Mas de Daumas Gassac", "France", "Wine", "b36369e0e04b121bb3d3d10f"],
  ["masahiro", "Masahiro", "Japan", "Gin", "8d4669cb0d3ac20dc0f552e6"],
  ["meijo-sake", "Meijo Sake", "Japan", "Sake", "f09afdde138b94a04304c898"],
  ["michel-lynch", "Michel Lynch", "France", "Wine", "46b305198728fb65b1ef103f"],
  ["moillard-bourgogne", "Moillard", "France", "Wine", "5027c6684c1c8abbd63a9ede"],
  ["molinari", "Molinari", "Italy", "Sambuca", "a81da606ebdac8b2a8dafbf3"],
  ["moskovskaya", "Moskovskaya", "Latvia", "Vodka", "8081f9d04a393712b76ef9c9"],
  ["moulin-de-gassac", "Moulin de Gassac", "France", "Wine", "550af4759c7665eac671322d"],
  ["mount-rozier", "Mount Rozier", "South Africa", "Wine", "fe2c4ea8330d1d1601203493"],
  ["ott-domaine", "Domaines Ott", "France", "Wine", "9674b6b6d4e8bee11379babb"],
  ["london-hill", "London Hill", "United Kingdom", "Gin", "f94d9272fe78d9bd6a2944fe"],
  ["london-pilsner", "London Pilsner", "India", "Beer", "69ef6d59188ecd52264d7f9a"],
  ["lone-wolf", "LoneWolf", "United Kingdom", "Gin", "bdd65dcd9f231498fa89dad7"],
  ["luca-bosio", "Luca Bosio", "Italy", "Wine", "8d203451d9dc1488606257de"],
  ["nautilus", "Nautilus Estate", "New Zealand", "Wine", "c4a417644614ac61ed4e53c8"],
  ["neil-ellis", "Neil Ellis", "South Africa", "Wine", "f849904bc75c55d60533c98b"],
  ["nemiroff", "Nemiroff", "Ukraine", "Vodka", "47c3fca7ee496cf54d59c6b0"],
  ["niel-joubert", "Niel Joubert", "South Africa", "Wine", "e7f79f2e1ba0c8282d85b898"],
  ["normindia", "Normindia", "France", "Gin", "524e3192b6f9863f3cb742da"],
  ["omar", "Omar", "Taiwan", "Single Malt Whisky", "21297e6e966afbd06e8f08c4"],
  ["uluvka", "U'luvka", "Poland", "Vodka", "6e4d766a7ebe1e75be5408fb"],
  ["ouzo-of-plomari", "Ouzo of Plomari", "Greece", "Ouzo", "29c00cfdd7f8b143deb21597"],
] as const;

// Editorial provenance stays outside the public content contract.
export const BRAND_SOURCES_BATCH_32: Record<string, string[]> = {
  "los-vascos": ["https://www.lafite.com/domaines/los-vascos/read/"],
  "love-by-leoube": ["https://www.leoube.com/en/love-by-leoube-rose"],
  loveblock: ["https://loveblockwine.com/"],
  "maison-alexandrins": ["https://lesalexandrins.com/pages/notre-histoire"],
  "man-family": ["https://manwines.com/our-story/"],
  mancino: ["https://mancinovermouth.com/en/giancarlo-mancino"],
  "mars-tsunuki": ["https://www.hombo.co.jp/en/visiting/tsunuki/"],
  "martin-millers": ["https://martinmillersgin.com/pure/"],
  "mas-de-daumas": ["https://www.daumas-gassac.com/en/mas-de-daumas-gassac-history/"],
  masahiro: ["https://www.en.masahiro.co.jp/products/masahiro_okinawa_gin/"],
  "meijo-sake": ["https://hyogo-sake.or.jp/en/introduction/himeji.html"],
  "michel-lynch": ["https://www.michel-lynch.fr/en/michel-lynch/background"],
  "moillard-bourgogne": ["https://www.moillard.fr/blog/notre-maison/"],
  molinari: ["https://www.molinari.it/en/sambuca-history"],
  moskovskaya: ["https://moskovskaya.vodka/"],
  "moulin-de-gassac": ["https://www.daumas-gassac.com/en/sas-moulin-de-gassac-history/"],
  "mount-rozier": ["https://mountrozier.com/"],
  "ott-domaine": ["https://www.domaines-ott.com/en/the-history-of-domaines-ott"],
  "london-hill": ["https://www.ianmacleod.com/brands/london-hill-gin", "https://www.keepersquestbrands.com/london-hill"],
  "london-pilsner": ["https://www.unitedbreweries.com/sites/united-breweries/files/united-breweries/Press-Release-Launch-of-London-Pilsner-Strong-Beer.pdf"],
  "lone-wolf": ["https://www.lonewolfgin.com/"],
  "luca-bosio": ["https://www.bosiovini.it/it/storia.php"],
  nautilus: ["https://www.nautilusestate.com/"],
  "neil-ellis": ["https://neilellis.com/"],
  nemiroff: ["https://nemiroff.vodka/en-uk/about-us/"],
  "niel-joubert": ["https://nieljoubert.co.za/"],
  normindia: ["https://gin-normindia.com/"],
  omar: ["https://omarwhisky.ttl.com.tw/en/about_brew.aspx"],
  uluvka: ["https://wina-mp.pl/pl/produkt/uluvka-signature-07-l-gola", "https://www.diffordsguide.com/beer-wine-spirits/1148/uluvka"],
  "ouzo-of-plomari": ["https://ouzoplomari.gr/en/traditional-process/"],
};

export const BRAND_LOGOS_BATCH_32: Record<string, string> = {
  loveblock: "https://loveblockwine.com/wp-content/uploads/logo.svg",
  "man-family": "https://manwines.com/wp-content/uploads/2022/10/man_logo_colour-480x186.png",
  mancino: "https://mancinovermouth.com/assets/images/Logo_Mancino.webp",
  molinari: "https://www.molinari.it/themes/custom/lab/img/share/logo-000.png",
  "lone-wolf": "https://www.lonewolfgin.com/_resources/themes/simple/images/BDDC_LoneWolfGin_Logo.png",
  nemiroff: "https://nemiroff.vodka/wp-content/uploads/2024/03/logo.svg",
  "ouzo-of-plomari": "https://ouzo.plomari-media.gr/wp-content/uploads/2026/07/WHITE-TRANSlogo_final-30-11-20_OUT_ENG-21.png",
};

export const BRAND_CONTENT_BATCH_32: Record<string, BrandPublicContent> = {
  "los-vascos": {
    description: "Los Vascos is a Chilean wine estate in the Colchagua Valley run by Domaines Barons de Rothschild Lafite. Cabernet Sauvignon is central to its range, alongside Carmenere, Chardonnay and Sauvignon Blanc.",
    story: "The estate sits between the Andes and Chile's coastal mountains. The Lafite family took it over in 1988 and developed a Bordeaux-minded approach to Colchagua fruit.",
    tastingNotes: [{ title: "Cabernet Sauvignon", description: "Blackcurrant and plum lead a dry, firm red." }, { title: "Sauvignon Blanc", description: "Citrus and green-fruit notes bring a brisker side to the estate." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve the Cabernet lightly cool in a red-wine glass; chill the Sauvignon Blanc well." }, { subheading: "At the table", description: "Put the red beside lamb seekh kebabs or mushroom pepper fry." }],
    pairingIdeas: [{ title: "Colchagua pairings", items: ["lamb seekh kebabs", "mushroom pepper fry", "grilled steak", "tandoori prawns"] }],
    whyChoose: "A Colchagua estate with Cabernet at its heart and the Lafite family's winemaking hand behind it.",
    faqs: [{ question: "Where is Los Vascos made?", answer: "Its vineyards are in Chile's Colchagua Valley." }, { question: "Who owns Los Vascos?", answer: "Domaines Barons de Rothschild Lafite owns the estate." }],
    finalVerdict: "Los Vascos Cabernet is a sturdy red for a spice-led dinner with grilled food.",
    metaTitle: "Los Vascos Wine Guide | BevOry", metaDescription: "Explore Los Vascos Cabernet and Colchagua wines, tasting notes and pairings. Check city prices on BevOry.",
  },
  "love-by-leoube": {
    description: "Love by Leoube is an organic wine range from Chateau Leoube on France's Provence coast. The range includes pale rose, white, red and sparkling wines.",
    story: "Chateau Leoube's vineyards meet the Mediterranean near Bormes-les-Mimosas. Its Love rose blends Grenache, Cinsault, Syrah and Mourvedre and is fermented in temperature-controlled steel.",
    tastingNotes: [{ title: "Rose fruit", description: "Peach, strawberry and fresh citrus give the rose a lively opening." }, { title: "Finish", description: "A light, bright acidity keeps the fruit from feeling heavy." }],
    howToEnjoy: [{ subheading: "Chill", description: "Pour the rose cold, around 8 to 10 degrees Celsius, in a white-wine glass." }, { subheading: "Food", description: "Try it with tandoori prawns, grilled vegetables or a tomato salad." }],
    pairingIdeas: [{ title: "Coastal table", items: ["tandoori prawns", "grilled vegetables", "tomato salad", "chicken skewers"] }],
    whyChoose: "An organic Provence rose that keeps its Mediterranean fruit light on its feet.",
    faqs: [{ question: "Is Love by Leoube a rose only?", answer: "No. Chateau Leoube also makes Love white, red and sparkling wines." }, { question: "What grapes are in Love by Leoube rose?", answer: "The rose uses Grenache, Cinsault, Syrah and Mourvedre." }],
    finalVerdict: "The rose makes sense beside a seafood lunch when a crisp, pale wine is called for.",
    metaTitle: "Love by Leoube Wine Guide | BevOry", metaDescription: "Discover Love by Leoube rose, Provence grapes and food pairings. Check city prices on BevOry.",
  },
  loveblock: {
    description: "Loveblock is a New Zealand wine project from Erica and Kim Crawford. Its Marlborough vineyards produce Sauvignon Blanc, Pinot Gris, Pinot Noir and other small-range wines.",
    story: "After building an internationally known wine name, the Crawfords turned to the Loveblock farm in Marlborough. The project places organic growing and the character of its Awatere and Wairau sites ahead of a uniform house flavour.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Citrus and herbal notes carry the bright white-wine side of the range." }, { title: "Pinot Noir", description: "Red berry fruit meets a lighter, savoury frame." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill Sauvignon Blanc well; give Pinot Noir a lightly cool red-wine glass." }, { subheading: "Food", description: "Pair the white with fish tikka or herbed paneer; try Pinot Noir with mushroom kebabs." }],
    pairingIdeas: [{ title: "Marlborough plates", items: ["fish tikka", "herbed paneer", "mushroom kebabs", "roast chicken"] }],
    whyChoose: "Marlborough wines with a distinct farm story and a fresh, food-friendly range.",
    faqs: [{ question: "Who founded Loveblock?", answer: "Winemakers Erica and Kim Crawford founded the Loveblock project." }, { question: "Where are Loveblock wines from?", answer: "The project is based in Marlborough, New Zealand." }],
    finalVerdict: "Loveblock is a useful name to know for Marlborough whites beyond the obvious party bottle.",
    metaTitle: "Loveblock Wine Guide | BevOry", metaDescription: "Meet Loveblock's Marlborough wines, from Sauvignon Blanc to Pinot Noir. Check city prices on BevOry.",
  },
  "maison-alexandrins": {
    description: "Maison les Alexandrins makes French wines from the northern Rhone Valley. The range follows Syrah reds and local white grapes through appellations including Crozes-Hermitage and Saint-Joseph.",
    story: "Nicolas Jaboulet and Alexandre Caso brought their northern Rhone experience together under the Alexandrins name. Their Maison range draws fruit from several sites rather than presenting a single-estate bottling as the whole story.",
    tastingNotes: [{ title: "Syrah", description: "Dark berries and black pepper sit over a lean, savoury structure." }, { title: "White Rhone", description: "Stone fruit and floral notes mark the softer white-wine side." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour Syrah lightly cool in a broad glass; chill whites before serving." }, { subheading: "Pair", description: "Try the red with mutton seekh or pepper-crusted mushrooms." }],
    pairingIdeas: [{ title: "Rhone pairings", items: ["mutton seekh", "pepper-crusted mushrooms", "roast duck", "aged cheddar"] }],
    whyChoose: "A northern Rhone address where Syrah keeps its pepper and place.",
    faqs: [{ question: "Which region is Maison les Alexandrins from?", answer: "Its wines come from the northern Rhone Valley in France." }, { question: "Which red grape is central to the range?", answer: "Syrah is the principal red grape in its northern Rhone wines." }],
    finalVerdict: "Choose a Maison les Alexandrins Syrah when dinner needs a red with spice rather than sweetness.",
    metaTitle: "Maison les Alexandrins Wine Guide | BevOry", metaDescription: "Explore Maison les Alexandrins Syrah and northern Rhone styles. Check city prices on BevOry.",
  },
  "man-family": {
    description: "MAN Family Wines is a South African producer founded by Tyrrel Myburgh, Philip Myburgh and Jose Conde. Its Cape range includes Chenin Blanc, Pinotage and Cabernet Sauvignon.",
    story: "The first MAN Pinotage was made in an old tractor shed. The project grew through partnerships with Cape growers, including farmers tending old Chenin Blanc vines.",
    tastingNotes: [{ title: "Chenin Blanc", description: "Orchard fruit and citrus give the white an easy brightness." }, { title: "Pinotage", description: "Dark berry fruit and a gentle smoky edge suit the red." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill Chenin Blanc; serve Pinotage just below room temperature." }, { subheading: "Food", description: "Put Pinotage with barbecue chicken or mutton seekh and Chenin with tandoori fish." }],
    pairingIdeas: [{ title: "Cape table", items: ["tandoori fish", "barbecue chicken", "mutton seekh", "grilled corn"] }],
    whyChoose: "Cape wines with an old-vine Chenin connection and a particularly South African Pinotage story.",
    faqs: [{ question: "What does MAN Family Wines make?", answer: "The range includes Chenin Blanc, Pinotage and Cabernet Sauvignon." }, { question: "Where is MAN Family Wines based?", answer: "It works with growers in South Africa's Cape wine regions." }],
    finalVerdict: "MAN Pinotage earns its place with grilled food, while the Chenin is the cooler first glass.",
    metaTitle: "MAN Family Wines Guide | BevOry", metaDescription: "Explore MAN Family Wines, Chenin Blanc, Pinotage and food matches. Check city prices on BevOry.",
  },
  mancino: {
    description: "Mancino is an Italian vermouth label created by bartender Giancarlo Mancino. Its recipes marry Italian wine with infusions of botanicals for aperitivo and cocktail use.",
    story: "Mancino developed the range after working behind bars and studying older vermouth styles. The early recipes drew on dozens of botanicals and were presented to bartenders in 2012.",
    tastingNotes: [{ title: "Rosso", description: "Herbal bitterness, warm spice and a sweet wine base make a rounded aperitif." }, { title: "Bianco", description: "Citrus peel and floral herbs give the lighter style lift." }],
    howToEnjoy: [{ subheading: "Aperitivo", description: "Serve chilled over ice with an orange slice, or measure into a Negroni." }, { subheading: "Food", description: "Try the bitter-sweet Rosso with masala peanuts or olive tapenade." }],
    pairingIdeas: [{ title: "Aperitivo plates", items: ["masala peanuts", "olive tapenade", "aged gouda", "grilled artichokes"] }],
    whyChoose: "A bartender-built vermouth range with a clear Italian wine-and-herb backbone.",
    faqs: [{ question: "Who created Mancino vermouth?", answer: "Italian bartender Giancarlo Mancino created it." }, { question: "How can Mancino Rosso be served?", answer: "Try it over ice with orange or in a Negroni." }],
    finalVerdict: "Mancino is at home in a proper aperitivo, especially when the food has salt and spice.",
    metaTitle: "Mancino Vermouth Guide | BevOry", metaDescription: "Discover Mancino vermouth, herbal styles, Negroni serves and pairings. Check city prices on BevOry.",
  },
  "mars-tsunuki": {
    description: "Mars Tsunuki is Japanese single malt whisky from Hombo Shuzo's distillery in Minamisatsuma, Kagoshima. The site is separate from the company's Shinshu distillery in Nagano.",
    story: "Tsunuki is the birthplace of Hombo Shuzo. The company returned malt-whisky distillation to Kagoshima with a new distillery there after decades of making whisky elsewhere in Japan.",
    tastingNotes: [{ title: "Malt", description: "Orchard fruit and cereal notes show the whisky's malt base." }, { title: "Cask", description: "Oak spice and dried fruit appear in the richer cask-led releases." }],
    howToEnjoy: [{ subheading: "Taste", description: "Start with a small neat pour in a tulip glass, then add a few drops of water." }, { subheading: "Food", description: "Try it with yakitori, smoked almonds or grilled shiitake." }],
    pairingIdeas: [{ title: "With whisky", items: ["yakitori", "smoked almonds", "grilled shiitake", "dark chocolate"] }],
    whyChoose: "A Kagoshima single malt that tells a different Mars story from the Nagano distillery.",
    faqs: [{ question: "Where is Mars Tsunuki made?", answer: "It is distilled in Tsunuki, Minamisatsuma City, Kagoshima Prefecture." }, { question: "Who makes Mars Tsunuki?", answer: "Hombo Shuzo makes the whisky at its Mars Tsunuki distillery." }],
    finalVerdict: "Tsunuki is a worthwhile Japanese malt for drinkers curious about whisky made in southern Japan.",
    metaTitle: "Mars Tsunuki Whisky Guide | BevOry", metaDescription: "Explore Mars Tsunuki whisky from Kagoshima, serving ideas and food matches. Check city prices on BevOry.",
  },
  "martin-millers": {
    description: "Martin Miller's is a gin distilled in England and blended with Icelandic spring water. Its process distils citrus and earthy botanicals separately before combining them.",
    story: "Martin Miller set out to rework the London dry gin experience at the end of the 1990s. The spirit's journey from England to Iceland for blending remains its most unusual production choice.",
    tastingNotes: [{ title: "Nose", description: "Juniper and lemon peel give a clean, brisk first impression." }, { title: "Palate", description: "Soft citrus and a lightly herbal finish keep the gin balanced." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Use plenty of ice, a dry tonic and a thin citrus garnish." }, { subheading: "Food", description: "Serve beside tandoori prawns, cucumber salad or grilled halloumi." }],
    pairingIdeas: [{ title: "Bright plates", items: ["tandoori prawns", "cucumber salad", "grilled halloumi", "lemon olives"] }],
    whyChoose: "An English gin whose Icelandic water and split distillation keep its citrus unusually clear.",
    faqs: [{ question: "Where is Martin Miller's gin distilled?", answer: "It is distilled in England and blended with Icelandic spring water." }, { question: "What is a simple Martin Miller's serve?", answer: "A cold gin and tonic with a restrained citrus garnish works well." }],
    finalVerdict: "Martin Miller's makes a crisp G&T that does not need a bowl of garnish to speak.",
    metaTitle: "Martin Miller's Gin Guide | BevOry", metaDescription: "Meet Martin Miller's gin, its England-Iceland process and food pairings. Check city prices on BevOry.",
  },
  "mas-de-daumas": {
    description: "Mas de Daumas Gassac is a family wine estate in the Gassac Valley near Aniane, Languedoc. Its red wine is built around Cabernet Sauvignon, while the estate also makes white wine.",
    story: "Veronique and Aime Guibert began developing the property in the 1970s. Their decision to plant Cabernet in the cool Gassac valley challenged the region's reputation for simple bulk wine.",
    tastingNotes: [{ title: "Red", description: "Dark fruit, herbs and firm tannin give the Cabernet-led red its shape." }, { title: "White", description: "Stone fruit and citrus mark the estate's fresher white side." }],
    howToEnjoy: [{ subheading: "Decant", description: "Give a young red time in a decanter and serve it slightly cool." }, { subheading: "Food", description: "Bring out the red with lamb rogan josh or rosemary roast chicken." }],
    pairingIdeas: [{ title: "Gassac table", items: ["lamb rogan josh", "rosemary roast chicken", "grilled aubergine", "aged cheddar"] }],
    whyChoose: "A Languedoc estate that proved Cabernet could make serious wine in the Gassac Valley.",
    faqs: [{ question: "Where is Mas de Daumas Gassac?", answer: "The estate is near Aniane in France's Languedoc region." }, { question: "Which grape leads its red wine?", answer: "Cabernet Sauvignon forms the core of its red wine." }],
    finalVerdict: "The red rewards an unhurried dinner with deep savoury food.",
    metaTitle: "Mas de Daumas Gassac Wine Guide | BevOry", metaDescription: "Discover Mas de Daumas Gassac reds, Languedoc history and pairings. Check city prices on BevOry.",
  },
  masahiro: {
    description: "Masahiro is an Okinawan drinks producer whose craft gin draws on the island's awamori distilling tradition. Recipe 01 combines juniper with shekwasha citrus, goya, guava leaves, roselle and long pepper.",
    story: "Masahiro Shuzo adapted methods from its rice-spirit work to make Okinawa Craft Gin. The shift from awamori to gin gave the distillery a different way to show Okinawan ingredients.",
    tastingNotes: [{ title: "Citrus", description: "Shekwasha brings a bright Okinawan citrus aroma." }, { title: "Botanicals", description: "Juniper, guava leaf and long pepper give the palate a herbal, gently spiced turn." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice with chilled soda and a thin citrus peel." }, { subheading: "Food", description: "Try it beside prawn tempura or chilli-salt edamame." }],
    pairingIdeas: [{ title: "Okinawan cues", items: ["prawn tempura", "chilli-salt edamame", "grilled squid", "cucumber pickle"] }],
    whyChoose: "An Okinawan gin that carries a working awamori distillery's knowledge into a botanical spirit.",
    faqs: [{ question: "Where is Masahiro Craft Gin made?", answer: "It is made by Masahiro Shuzo in Okinawa, Japan." }, { question: "What distilling tradition shaped it?", answer: "Masahiro drew on its experience making awamori, Okinawa's rice spirit." }],
    finalVerdict: "Masahiro is a lively gin for a short, cold highball with seafood.",
    metaTitle: "Masahiro Gin Guide | BevOry", metaDescription: "Explore Masahiro Okinawa Craft Gin, its citrus character and food matches. Check city prices on BevOry.",
  },
  "meijo-sake": {
    description: "Meijo Sake is a Japanese sake label from Himeji in Hyogo Prefecture. The brewery's range includes dry and softer rice-based styles for the table.",
    story: "Meijo takes its name from Himeji Castle, the city's best-known landmark. Brewing in Himeji links the label to Harima's long rice-and-water sake tradition.",
    tastingNotes: [{ title: "Rice", description: "A gentle rice aroma sits at the centre of the sake." }, { title: "Dry style", description: "The drier bottles finish clean and suit salty food." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try a chilled pour in a small sake cup, then compare it lightly warmed." }, { subheading: "Food", description: "Serve with yakitori, tempura or lightly spiced tandoori fish." }],
    pairingIdeas: [{ title: "Sake table", items: ["yakitori", "tempura", "tandoori fish", "steamed dumplings"] }],
    whyChoose: "A Himeji sake with a direct connection to Hyogo's brewing country.",
    faqs: [{ question: "Where is Meijo Sake from?", answer: "Meijo Sake is from Himeji in Japan's Hyogo Prefecture." }, { question: "Can Meijo Sake be served warm?", answer: "A lightly warmed pour is one option, alongside serving it chilled." }],
    finalVerdict: "Meijo is a pleasant table sake when the food has salt, smoke or a little spice.",
    metaTitle: "Meijo Sake Guide | BevOry", metaDescription: "Discover Meijo Sake from Himeji, serving options and food pairings. Check city prices on BevOry.",
  },
  "michel-lynch": {
    description: "Michel Lynch is a Bordeaux wine range created by Jean-Michel Cazes of Chateau Lynch-Bages. It offers red, white and rose wines designed to show Bordeaux character without long cellaring.",
    story: "Cazes conceived the range in the late 1980s and named it for Michel Lynch, an earlier figure in the Lynch-Bages story. The label gave the Cazes family a way to bring Bordeaux wine to a wider everyday table.",
    tastingNotes: [{ title: "Red Bordeaux", description: "Dark berry fruit and supple tannin frame the red." }, { title: "White Bordeaux", description: "Citrus and orchard fruit give the white a cleaner line." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve red slightly cool and chill white thoroughly." }, { subheading: "Food", description: "Match the red with keema kebabs and the white with lemon fish." }],
    pairingIdeas: [{ title: "Bordeaux at dinner", items: ["keema kebabs", "lemon fish", "roast chicken", "mushroom tart"] }],
    whyChoose: "Bordeaux fruit with a Cazes family signature and an approachable place at dinner.",
    faqs: [{ question: "Who created Michel Lynch wines?", answer: "Jean-Michel Cazes of the Lynch-Bages family created the range." }, { question: "Is Michel Lynch only a red wine?", answer: "No. The range includes red, white and rose Bordeaux wines." }],
    finalVerdict: "Michel Lynch red is an easy way into Bordeaux alongside kebabs or roast chicken.",
    metaTitle: "Michel Lynch Wine Guide | BevOry", metaDescription: "Explore Michel Lynch Bordeaux reds, whites and meal pairings. Check city prices on BevOry.",
  },
  "moillard-bourgogne": {
    description: "Moillard is a Burgundy wine house based in Nuits-Saint-Georges, France. Its range covers Pinot Noir, Chardonnay and Cremant de Bourgogne across several appellations.",
    story: "The Moillard name has been tied to Burgundy wine since the nineteenth century. Its Nuits-Saint-Georges base places the house in the Cote de Nuits, close to some of the region's best-known Pinot Noir vineyards.",
    tastingNotes: [{ title: "Pinot Noir", description: "Red cherry and a fine earthy note give the red a lighter frame." }, { title: "Chardonnay", description: "Citrus and orchard fruit mark the white's fresh side." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Serve Pinot Noir a little cool; chill Chardonnay and Cremant before opening." }, { subheading: "Food", description: "Pair Pinot Noir with tandoori mushrooms or roast duck." }],
    pairingIdeas: [{ title: "Burgundy table", items: ["tandoori mushrooms", "roast duck", "grilled asparagus", "butter chicken"] }],
    whyChoose: "A Nuits-Saint-Georges house that gives Burgundy's two key grapes room to speak.",
    faqs: [{ question: "Where is Moillard based?", answer: "Moillard is based in Nuits-Saint-Georges, Burgundy." }, { question: "What wines does Moillard make?", answer: "Its range includes Pinot Noir, Chardonnay and Cremant de Bourgogne." }],
    finalVerdict: "Moillard Pinot Noir is a good red when dinner calls for finesse instead of weight.",
    metaTitle: "Moillard Burgundy Wine Guide | BevOry", metaDescription: "Meet Moillard's Burgundy Pinot Noir, Chardonnay and pairings. Check city prices on BevOry.",
  },
  molinari: {
    description: "Molinari is an Italian sambuca producer founded by Angelo Molinari in Civitavecchia. Its Sambuca Extra is an anise-led liqueur traditionally poured after a meal.",
    story: "Angelo Molinari began working on the recipe in 1945. The family brought it to Rome's restaurants, where serving sambuca with coffee beans became part of its public life.",
    tastingNotes: [{ title: "Star anise", description: "A pronounced sweet anise aroma leads the glass." }, { title: "Finish", description: "Liquorice-like warmth lingers after the sweetness." }],
    howToEnjoy: [{ subheading: "After dinner", description: "Serve a small measure neat or with coffee beans in the glass." }, { subheading: "Food", description: "Try it after tiramisu or beside anise biscuits and dark chocolate." }],
    pairingIdeas: [{ title: "After-dinner bites", items: ["tiramisu", "anise biscuits", "dark chocolate", "espresso gelato"] }],
    whyChoose: "A Civitavecchia sambuca whose star-anise character has stayed recognisable since 1945.",
    faqs: [{ question: "Who created Molinari Sambuca?", answer: "Angelo Molinari created it in Civitavecchia, Italy." }, { question: "What flavour defines Molinari?", answer: "Star anise defines the classic Sambuca Extra." }],
    finalVerdict: "Molinari belongs after dinner, when anise and espresso can have the last word.",
    metaTitle: "Molinari Sambuca Guide | BevOry", metaDescription: "Discover Molinari sambuca, star-anise flavour and dessert pairings. Check city prices on BevOry.",
  },
  moskovskaya: {
    description: "Moskovskaya is a vodka label produced in Riga, Latvia. Its green bottle and wheat-based spirit link a historical vodka name to a current Baltic production site.",
    story: "The label's roots reach into late nineteenth-century vodka production. War and political change interrupted that history, while the present brand continues the name from Riga.",
    tastingNotes: [{ title: "Grain", description: "A mild grain note remains beneath the clean vodka aroma." }, { title: "Finish", description: "The finish is dry and direct rather than sweet." }],
    howToEnjoy: [{ subheading: "Cold", description: "Chill a small pour well or use it in a simple vodka soda." }, { subheading: "Food", description: "Serve beside smoked fish, salted cucumber or potato pancakes." }],
    pairingIdeas: [{ title: "Salty plates", items: ["smoked fish", "salted cucumber", "potato pancakes", "tandoori prawns"] }],
    whyChoose: "A Riga-produced vodka with an old name and a straightforward grain-led serve.",
    faqs: [{ question: "Where is Moskovskaya vodka produced?", answer: "The current brand is produced in Riga, Latvia." }, { question: "How can Moskovskaya be served?", answer: "Try a small chilled measure or a vodka soda with lemon." }],
    finalVerdict: "Moskovskaya works best cold and uncomplicated beside salty food.",
    metaTitle: "Moskovskaya Vodka Guide | BevOry", metaDescription: "Explore Moskovskaya vodka from Riga, simple serves and food matches. Check city prices on BevOry.",
  },
  "moulin-de-gassac": {
    description: "Moulin de Gassac is a Languedoc wine range created by Aime Guibert of Mas de Daumas Gassac. It draws fruit from selected vineyard plots around Villeveyrac and Pinet.",
    story: "Guibert launched Moulin de Gassac in the early 1990s as a more accessible counterpart to the family's estate wines. The range grew through work with local growers rather than simply relabelling the Gassac estate's top cuvees.",
    tastingNotes: [{ title: "Reds", description: "Ripe berry fruit and southern herbs give the reds a warm edge." }, { title: "Whites", description: "Fresh citrus and stone fruit keep the whites lively." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the whites; serve the reds slightly below room temperature." }, { subheading: "Food", description: "Pair a red with chicken tikka or a white with grilled fish." }],
    pairingIdeas: [{ title: "Southern French table", items: ["chicken tikka", "grilled fish", "ratatouille", "lamb chops"] }],
    whyChoose: "Guibert family Languedoc wines that bring selected local plots to the everyday table.",
    faqs: [{ question: "Who created Moulin de Gassac?", answer: "Aime Guibert, founder of Mas de Daumas Gassac, created it." }, { question: "Where does Moulin de Gassac source grapes?", answer: "The selection draws from Languedoc vineyard plots, including sites near Villeveyrac and Pinet." }],
    finalVerdict: "Moulin de Gassac is the easygoing Guibert-family bottle for a generous dinner.",
    metaTitle: "Moulin de Gassac Wine Guide | BevOry", metaDescription: "Explore Moulin de Gassac's Languedoc wines and food matches. Check city prices on BevOry.",
  },
  "mount-rozier": {
    description: "Mount Rozier is a South African wine label rooted in the Stellenbosch winelands. Its range includes Chenin Blanc, rose, Shiraz and Merlot from Western Cape fruit.",
    story: "The name honours Annie Rozier, who gathered wildflowers on the local hills. The vineyards look towards False Bay between the Helderberg and Hottentots Holland mountains.",
    tastingNotes: [{ title: "Chenin Blanc", description: "Orchard fruit and citrus give the white a bright Cape profile." }, { title: "Shiraz", description: "Dark fruit and spice lend the red more weight." }],
    howToEnjoy: [{ subheading: "Pour", description: "Chill the Chenin; let Shiraz sit slightly cool in a red-wine glass." }, { subheading: "Food", description: "Put the Shiraz beside mutton seekh and the Chenin beside fish tikka." }],
    pairingIdeas: [{ title: "Cape pairings", items: ["mutton seekh", "fish tikka", "grilled aubergine", "barbecue chicken"] }],
    whyChoose: "Western Cape wines with a Stellenbosch landscape behind the name.",
    faqs: [{ question: "Where is Mount Rozier from?", answer: "The label is rooted in the Stellenbosch winelands of South Africa." }, { question: "Who was Annie Rozier?", answer: "She was a local flower gatherer whose name inspired Mount Rozier." }],
    finalVerdict: "The Chenin and Shiraz give Mount Rozier two useful routes through a spicy meal.",
    metaTitle: "Mount Rozier Wine Guide | BevOry", metaDescription: "Discover Mount Rozier wines, Stellenbosch roots and pairings. Check city prices on BevOry.",
  },
  "ott-domaine": {
    description: "Domaines Ott is a Provence wine house associated especially with rose. Its three estates are Chateau de Selle, Clos Mireille and Chateau Romassan.",
    story: "Marcel Ott bought Chateau de Selle in 1912 and added Clos Mireille and Chateau Romassan later. The properties span Cotes de Provence and Bandol, allowing each rose to speak for a different coastal or inland site.",
    tastingNotes: [{ title: "Rose", description: "Pale red fruit, citrus and a dry finish define the house's rose direction." }, { title: "White", description: "The Clos Mireille whites lean toward fresh citrus and a coastal note." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve the rose cold in a white-wine glass, away from direct sun." }, { subheading: "Food", description: "Pair it with tandoori fish, grilled prawns or herbed paneer." }],
    pairingIdeas: [{ title: "Provence table", items: ["tandoori fish", "grilled prawns", "herbed paneer", "olive focaccia"] }],
    whyChoose: "Three Provence estates offer a clear comparison between different rose terroirs.",
    faqs: [{ question: "Who founded Domaines Ott?", answer: "Marcel Ott established the family's Provence wine project." }, { question: "Which estates make Domaines Ott wines?", answer: "Chateau de Selle, Clos Mireille and Chateau Romassan are its three estates." }],
    finalVerdict: "A chilled Ott rose is at its best with seafood and a long lunch.",
    metaTitle: "Domaines Ott Wine Guide | BevOry", metaDescription: "Explore Domaines Ott Provence rose, three estates and food pairings. Check city prices on BevOry.",
  },
  "london-hill": {
    description: "London Hill is an English dry gin in the Ian Macleod Distillers portfolio. It is made at Langley Distillery using a traditional pot-still process.",
    story: "Langley's distilling roots reach back to the eighteenth century in the West Midlands. London Hill keeps to a juniper-led dry-gin profile suited to short, straightforward mixed drinks.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper makes the first impression." }, { title: "Citrus", description: "Lemon peel lifts the dry herbal finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour over ice with dry tonic and a lemon twist." }, { subheading: "Food", description: "Try it with pepper prawns or a cucumber-and-mint salad." }],
    pairingIdeas: [{ title: "Gin plates", items: ["pepper prawns", "cucumber-and-mint salad", "grilled halloumi", "salted almonds"] }],
    whyChoose: "A pot-still English gin that lets juniper stay in front.",
    faqs: [{ question: "Who owns London Hill gin?", answer: "London Hill is part of Ian Macleod Distillers' spirits portfolio." }, { question: "Where is London Hill made?", answer: "It is produced at Langley Distillery in England." }],
    finalVerdict: "London Hill is a sensible gin-and-tonic pour for juniper lovers.",
    metaTitle: "London Hill Gin Guide | BevOry", metaDescription: "Discover London Hill dry gin, its Langley roots and simple pairings. Check city prices on BevOry.",
  },
  "london-pilsner": {
    description: "London Pilsner is an Indian beer brand marketed by United Breweries. Its strong beer uses European hops and spends a week ageing at sub-zero temperatures.",
    story: "United Breweries brought London Pilsner Strong Beer to Karnataka in 2024 after Maharashtra. The rollout gave the label a second state market under the company's wider beer business.",
    tastingNotes: [{ title: "First sip", description: "The opening is crisp and refreshing." }, { title: "Finish", description: "A smooth finish follows the cold-aged beer." }],
    howToEnjoy: [{ subheading: "Cold", description: "Serve well chilled in a clean beer glass." }, { subheading: "Food", description: "Try it with chilli chicken or masala peanuts." }],
    pairingIdeas: [{ title: "Bar snacks", items: ["chilli chicken", "masala peanuts", "paneer pakora", "fish fry"] }],
    whyChoose: "An Indian strong beer from United Breweries with a straightforward malt-led profile.",
    faqs: [{ question: "Who markets London Pilsner?", answer: "United Breweries markets the beer in India." }, { question: "How should London Pilsner be served?", answer: "Serve it well chilled in a clean beer glass." }],
    finalVerdict: "London Pilsner is a cold beer for a plate of salty, spicy snacks.",
    metaTitle: "London Pilsner Beer Guide | BevOry", metaDescription: "Explore London Pilsner beer, chilled serves and Indian snack pairings. Check city prices on BevOry.",
  },
  "lone-wolf": {
    description: "LoneWolf is a Scottish gin from BrewDog Distilling Company in Aberdeenshire. The distillery makes its own base spirit and uses a triple-bubble copper pot still for the gin.",
    story: "BrewDog extended its Ellon operation from beer into spirits with LoneWolf. The brand keeps production close to its Aberdeenshire base rather than buying in finished gin.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper gives the gin its dry centre." }, { title: "Citrus", description: "Citrus peel cuts through the herbal finish." }],
    howToEnjoy: [{ subheading: "G&T", description: "Use plenty of ice, dry tonic and a slice of grapefruit." }, { subheading: "Food", description: "Try it with smoked salmon, chilli paneer or grilled prawns." }],
    pairingIdeas: [{ title: "With a G&T", items: ["smoked salmon", "chilli paneer", "grilled prawns", "salted almonds"] }],
    whyChoose: "A Scottish gin made from base spirit to bottle by its own distilling team.",
    faqs: [{ question: "Who makes LoneWolf gin?", answer: "BrewDog Distilling Company makes it in Aberdeenshire, Scotland." }, { question: "What still does LoneWolf use?", answer: "The distillery uses a triple-bubble copper pot still." }],
    finalVerdict: "LoneWolf has the juniper and citrus to carry a crisp, no-fuss G&T.",
    metaTitle: "LoneWolf Gin Guide | BevOry", metaDescription: "Explore LoneWolf Scottish gin, copper-still production and pairings. Check city prices on BevOry.",
  },
  "luca-bosio": {
    description: "Luca Bosio is a Piedmont wine label from the Bosio family's vineyards near Valdivilla. Moscato d'Asti sits alongside Barbera, Nebbiolo and other regional wines.",
    story: "The family's vines lie in the steep Moscato hills of Piedmont. Luca Bosio joined the family business after studying oenology, adding his name to its wines.",
    tastingNotes: [{ title: "Moscato d'Asti", description: "Orange blossom and ripe peach ride a light spritz." }, { title: "Barbera", description: "Red cherry and brisk acidity give the red an easy food match." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Moscato cold in a white-wine glass; keep Barbera slightly cool." }, { subheading: "Food", description: "Put Moscato with fruit tart and Barbera with tomato-based pasta." }],
    pairingIdeas: [{ title: "Piedmont table", items: ["fruit tart", "tomato-based pasta", "paneer tikka", "mushroom risotto"] }],
    whyChoose: "A family Piedmont range with Moscato from the hills where the grape feels at home.",
    faqs: [{ question: "Where are Luca Bosio wines made?", answer: "The Bosio family works in Piedmont, Italy, near Valdivilla." }, { question: "Is Luca Bosio only Moscato?", answer: "No. The range also includes Barbera, Nebbiolo and other Piedmont wines." }],
    finalVerdict: "Luca Bosio Moscato is the lighter answer to a fruit-led dessert.",
    metaTitle: "Luca Bosio Wine Guide | BevOry", metaDescription: "Discover Luca Bosio's Piedmont Moscato and red wines. Check city prices on BevOry.",
  },
  nautilus: {
    description: "Nautilus Estate makes wine in Marlborough, New Zealand. Its cool-climate range includes Sauvignon Blanc, Pinot Noir, Chardonnay and other white varieties.",
    story: "Nautilus began making wine in 1985, early in Marlborough's modern growth. Separate white-wine and Pinot Noir facilities allow the team to handle those grapes differently.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Citrus and green herbs give the white its bright edge." }, { title: "Pinot Noir", description: "Red cherry and a gentle savoury note shape the lighter red." }],
    howToEnjoy: [{ subheading: "Pour", description: "Chill Sauvignon Blanc; serve Pinot Noir just below room temperature." }, { subheading: "Food", description: "Match the white with fish tikka and Pinot Noir with mushroom kebabs." }],
    pairingIdeas: [{ title: "Marlborough food", items: ["fish tikka", "mushroom kebabs", "roast chicken", "green salad"] }],
    whyChoose: "An early Marlborough estate with a distinct Pinot Noir cellar as well as fresh whites.",
    faqs: [{ question: "When did Nautilus Estate begin?", answer: "Nautilus began making wine in Marlborough in 1985." }, { question: "Which wines does Nautilus make?", answer: "The range includes Sauvignon Blanc, Pinot Noir and Chardonnay." }],
    finalVerdict: "Nautilus is a good Marlborough name to explore beyond Sauvignon Blanc alone.",
    metaTitle: "Nautilus Estate Wine Guide | BevOry", metaDescription: "Explore Nautilus Marlborough whites and Pinot Noir with food ideas. Check city prices on BevOry.",
  },
  "neil-ellis": {
    description: "Neil Ellis is a South African wine producer associated with Stellenbosch and other Cape vineyards. The range includes Cabernet Sauvignon, Sauvignon Blanc and site-focused red wines.",
    story: "Neil Ellis built his name by sourcing grapes from vineyards chosen for place rather than owning one all-purpose estate. That site-first approach helped make South African wine labels more specific about origin.",
    tastingNotes: [{ title: "Cabernet", description: "Blackcurrant and cedar give the structured red a classic line." }, { title: "Sauvignon Blanc", description: "Citrus and green-fruit notes keep the white lively." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give Cabernet a broad glass and chill Sauvignon Blanc well." }, { subheading: "Food", description: "Try the Cabernet with mutton rogan josh or chargrilled steak." }],
    pairingIdeas: [{ title: "Cape dinner", items: ["mutton rogan josh", "chargrilled steak", "smoked paneer", "grilled fish"] }],
    whyChoose: "Cape wines shaped by vineyard selection and a long interest in site identity.",
    faqs: [{ question: "Where does Neil Ellis make wine?", answer: "The producer works with vineyards in Stellenbosch and other Cape wine regions." }, { question: "Which grapes are in the range?", answer: "Cabernet Sauvignon and Sauvignon Blanc are among its wines." }],
    finalVerdict: "Neil Ellis Cabernet deserves a table with smoke, spice and time for the glass to open.",
    metaTitle: "Neil Ellis Wine Guide | BevOry", metaDescription: "Explore Neil Ellis Cape wines, Cabernet style and Indian pairings. Check city prices on BevOry.",
  },
  nemiroff: {
    description: "Nemiroff is a Ukrainian vodka brand named for the town of Nemyriv. Its range includes straight grain vodka and honey-and-pepper expressions.",
    story: "Vodka production in Nemyriv goes back well before the modern Nemiroff label. The brand built its export identity around Ukrainian production and the distinctive Honey Pepper bottling.",
    tastingNotes: [{ title: "Original", description: "Clean grain and a dry finish suit a cold, simple pour." }, { title: "Honey Pepper", description: "Honey sweetness meets a warm pepper bite." }],
    howToEnjoy: [{ subheading: "Cold", description: "Chill Original for a small neat serve or mix with soda." }, { subheading: "Food", description: "Try Honey Pepper beside grilled chicken or spicy pickles." }],
    pairingIdeas: [{ title: "Strong flavours", items: ["grilled chicken", "spicy pickles", "smoked fish", "potato pancakes"] }],
    whyChoose: "A Ukrainian vodka range whose honey-and-pepper expression has a character of its own.",
    faqs: [{ question: "Where is Nemiroff from?", answer: "Nemiroff is from Ukraine and takes its name from Nemyriv." }, { question: "Does Nemiroff make flavoured vodka?", answer: "Yes. Honey Pepper is one of its best-known expressions." }],
    finalVerdict: "The plain vodka is for a clean cold pour; Honey Pepper asks for a spicier table.",
    metaTitle: "Nemiroff Vodka Guide | BevOry", metaDescription: "Discover Nemiroff Ukrainian vodka, Original and Honey Pepper styles. Check city prices on BevOry.",
  },
  "niel-joubert": {
    description: "Niel Joubert is a family wine label from South Africa's Western Cape. Its range spans white, rose and red wines, including familiar Cape varieties.",
    story: "The Joubert family named the label for third-generation patriarch Niel Joubert in 1994. The estate's present family management keeps that personal name on a broad Cape wine range.",
    tastingNotes: [{ title: "Whites", description: "Citrus and orchard fruit keep the lighter wines fresh." }, { title: "Reds", description: "Dark berry fruit and mild spice give the reds more weight." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill whites and rose; give red wine a slightly cool pour." }, { subheading: "Food", description: "Try the red with chicken tikka or the white with grilled fish." }],
    pairingIdeas: [{ title: "Cape food", items: ["chicken tikka", "grilled fish", "paneer skewers", "roast vegetables"] }],
    whyChoose: "A family-named Cape range with a clear connection to the Joubert estate story.",
    faqs: [{ question: "Who was Niel Joubert?", answer: "He was the third-generation patriarch after whom the family named the wines." }, { question: "Where are Niel Joubert wines from?", answer: "The label comes from South Africa's Western Cape." }],
    finalVerdict: "Niel Joubert offers an easy route from Cape whites to fuller reds at dinner.",
    metaTitle: "Niel Joubert Wine Guide | BevOry", metaDescription: "Explore Niel Joubert Western Cape wines, serving tips and pairings. Check city prices on BevOry.",
  },
  normindia: {
    description: "Normindia is a French gin made by Domaine du Coquerel in Normandy. The family distillery, better known for Calvados, uses its apple-country setting as part of the gin's identity.",
    story: "Pierre Martin Neuhaus developed Normindia after returning to the family distillery. Coquerel had been making Calvados since 1937, so gin brought a new botanical direction to an established distilling site.",
    tastingNotes: [{ title: "Nose", description: "Juniper and citrus meet a gentle floral note." }, { title: "Finish", description: "Herbal spice carries through the dry finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Serve over ice with dry tonic and a thin apple slice." }, { subheading: "Food", description: "Try it with smoked cheese, apple slaw or tandoori prawns." }],
    pairingIdeas: [{ title: "Normandy cues", items: ["smoked cheese", "apple slaw", "tandoori prawns", "roast chicken"] }],
    whyChoose: "A Normandy gin from a Calvados house that brings its own orchard-country perspective.",
    faqs: [{ question: "Who makes Normindia gin?", answer: "Domaine du Coquerel makes it in Normandy, France." }, { question: "Does Coquerel also make Calvados?", answer: "Yes. The family distillery has made Calvados since 1937." }],
    finalVerdict: "Normindia is a neat change of pace for a G&T beside salty snacks.",
    metaTitle: "Normindia Gin Guide | BevOry", metaDescription: "Meet Normindia gin from Normandy, its Coquerel roots and pairings. Check city prices on BevOry.",
  },
  omar: {
    description: "Omar is a Taiwanese single malt whisky from Nantou Distillery. The distillery makes separate bourbon-cask and sherry-cask expressions.",
    story: "Nantou sits in central Taiwan and operates under Taiwan Tobacco and Liquor Corporation. Its four pot stills produce malt spirit for Omar's cask-led range.",
    tastingNotes: [{ title: "Bourbon cask", description: "Vanilla and orchard fruit lead the lighter cask style." }, { title: "Sherry cask", description: "Dried fruit and oak spice give the darker style more depth." }],
    howToEnjoy: [{ subheading: "Taste", description: "Use a tulip glass for a small neat pour before adding a few drops of water." }, { subheading: "Food", description: "Try it with smoked duck, sesame brittle or dark chocolate." }],
    pairingIdeas: [{ title: "Taiwan malt table", items: ["smoked duck", "sesame brittle", "dark chocolate", "grilled mushrooms"] }],
    whyChoose: "A Nantou malt that offers a clear bourbon-versus-sherry cask comparison.",
    faqs: [{ question: "Where is Omar whisky made?", answer: "It is made at Nantou Distillery in central Taiwan." }, { question: "Is Omar a single malt?", answer: "Yes. Omar is Nantou Distillery's single malt whisky label." }],
    finalVerdict: "Omar is worth tasting side by side across its two core cask styles.",
    metaTitle: "Omar Single Malt Guide | BevOry", metaDescription: "Explore Omar Taiwanese single malt, cask styles and food pairings. Check city prices on BevOry.",
  },
  uluvka: {
    description: "U'luvka is a Polish vodka sold in a distinctive long-necked bottle. Its grain-based spirit belongs to Poland's long tradition of clear table vodka.",
    story: "The bottle's leaning silhouette made U'luvka recognisable well beyond Poland. The brand has been presented internationally as a premium Polish grain vodka.",
    tastingNotes: [{ title: "Grain", description: "A quiet cereal note gives the vodka some weight." }, { title: "Finish", description: "The close is clean, dry and gently peppery." }],
    howToEnjoy: [{ subheading: "Serve cold", description: "Chill a small measure or mix with soda and a lemon peel." }, { subheading: "Food", description: "Try it with smoked fish, potato pancakes or pickled cucumber." }],
    pairingIdeas: [{ title: "Polish table", items: ["smoked fish", "potato pancakes", "pickled cucumber", "grilled prawns"] }],
    whyChoose: "A Polish grain vodka whose unusual bottle is easy to spot on a back bar.",
    faqs: [{ question: "Where is U'luvka from?", answer: "U'luvka is a Polish vodka." }, { question: "How can U'luvka be served?", answer: "Serve a small measure well chilled or in a simple vodka soda." }],
    finalVerdict: "U'luvka keeps the glass clean and lets salty food do the talking.",
    metaTitle: "U'luvka Vodka Guide | BevOry", metaDescription: "Discover U'luvka Polish vodka, cold serves and savoury pairings. Check city prices on BevOry.",
  },
  "ouzo-of-plomari": {
    description: "Ouzo of Plomari is an anise spirit from Plomari on the Greek island of Lesvos. The Isidoros Arvanitis distillery makes it with Lisvori anise in traditional copper stills.",
    story: "Isidoros Arvanitis built the distillery around Plomari's long ouzo-making culture. Its anise is grown in the Lisvori area of Lesvos, close enough for the ingredient to remain part of the local story.",
    tastingNotes: [{ title: "Anise", description: "Sweet liquorice-like anise rises immediately from the glass." }, { title: "With water", description: "The aroma opens as water turns the clear spirit milky." }],
    howToEnjoy: [{ subheading: "Slow pour", description: "Add cold water to a small measure and sip it with food." }, { subheading: "Food", description: "Serve beside grilled prawns, feta, olives or fish fry." }],
    pairingIdeas: [{ title: "Meze", items: ["grilled prawns", "feta", "olives", "fish fry"] }],
    whyChoose: "A Lesvos ouzo built around local Lisvori anise and copper-still distillation.",
    faqs: [{ question: "Where is Ouzo of Plomari made?", answer: "It is made in Plomari on Lesvos, Greece." }, { question: "Why does ouzo turn cloudy with water?", answer: "Adding water makes the anise oils disperse, turning the drink milky." }],
    finalVerdict: "Ouzo of Plomari asks for cold water, seafood and time at the table.",
    metaTitle: "Ouzo of Plomari Guide | BevOry", metaDescription: "Explore Ouzo of Plomari, Lisvori anise, serves and Greek pairings. Check city prices on BevOry.",
  },
};
