import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_28 = [
  ["barahsinge", "Barahsinge", "Nepal", "Beer", "7f521ba74197e68fbd2e88cf"],
  ["bardinet", "Bardinet", "France", "Brandy", "949adaee689020623f1e7dee"],
  ["bathtub", "Bathtub", "United Kingdom", "Gin", "821577e05f6c18d9e888d714"],
  ["bellevoye", "Bellevoye", "France", "Whisky", "43ace4e779f93df01e20b898"],
  ["bellini-canella", "Bellini Canella", "Italy", "Sparkling Cocktail", "8086b2eeee31f8bb2ff4aba0"],
  ["bia-saigon", "Bia Saigon", "Vietnam", "Beer", "6cf7d79a37b406b3d0560ce9"],
  ["bisquit-and-dubouche", "Bisquit & Dubouche", "France", "Cognac", "63395332b50b0d3dad98fda1"],
  ["bitburger", "Bitburger", "Germany", "Beer", "b6fde13a47cad338bf60ec77"],
  ["black-bottle", "Black Bottle", "Scotland", "Blended Scotch Whisky", "b31760b3f11b2e359536c65a"],
  ["black-tears", "Black Tears", "Cuba", "Spiced Rum", "fd12d7fd07b9e8f1b97aa113"],
  ["black-tower", "Black Tower", "Germany", "Wine", "8d6d02d61d6cfa1ade5a719d"],
  ["black-velvet", "Black Velvet", "Canada", "Whisky", "d6c6682e058f8443b9a5deb6"],
  ["blanche-de-namur", "Blanche De Namur", "Belgium", "Witbier", "f4f0c818f1f1b0559e31b111"],
  ["bodega-norton", "Bodega Norton", "Argentina", "Wine", "94b41b904fb56a82d8136473"],
  ["boekenhoutskloof", "Boekenhoutskloof", "South Africa", "Wine", "15a15c3503b8ce5b0dbc6315"],
  ["bogle", "Bogle", "United States", "Wine", "e8cad997fdc6d3b37edf897d"],
  ["bollinger", "Bollinger", "France", "Champagne", "ab1ca2d2c2eab40c5cf9dd7e"],
  ["borsao", "Borsao", "Spain", "Wine", "70e4c3a458b5544f864201c8"],
  ["brenne", "Brenne", "France", "Single Malt Whisky", "cb6e37b8953690a1fb620d19"],
  ["brokers", "Brokers", "United Kingdom", "Gin", "3e513630faa2f3b8963ed421"],
  ["bruce-jack", "Bruce Jack", "South Africa", "Wine", "c91b31cabf0b8722c63c6ca5"],
  ["budejovicky-budvar", "Budejovicky Budvar", "Czech Republic", "Lager", "141863f69772b701f2a6132e"],
  ["cakebread", "Cakebread", "United States", "Wine", "decba2224b8dd4f2f18d500b"],
  ["calle-23", "Calle 23", "Mexico", "Tequila", "59a01a01b9ddc90462ca40c4"],
  ["carling", "Carling", "United Kingdom", "Beer", "f69ce85544ed2c28bfeec81b"],
  ["cashmir", "Cashmir", "India", "Vodka", "d39aab7e55a521ff8f2780b9"],
  ["chartreuse", "Chartreuse", "France", "Herbal Liqueur", "52c201d689ea62eaa2755511"],
  ["citadelle", "Citadelle", "France", "Gin", "1c21d87125eaf48191372096"],
  ["codorniu", "Codorniu", "Spain", "Cava", "dbeb896423ce1ff4cd0b6a4a"],
  ["compass-box", "Compass Box", "Scotland", "Scotch Whisky", "de86911c69acaa62775078f8"],
] as const;

// Research links remain internal and never render in public fields.
export const BRAND_SOURCES_BATCH_28: Record<string, string[]> = {
  barahsinge: ["https://barahsinghe.com/about/"],
  bardinet: ["https://bardinet.fr/en/brandy/bardinet", "https://bardinet.fr/en/our-company"],
  bathtub: ["https://bathtubgin.com/pages/our-method"],
  bellevoye: ["https://bellevoye.com/fr/bellevoye-bleu", "https://whiskydefrance.fr/etablissement/bellevoye/"],
  "bellini-canella": ["https://bellinicanella.com/en/"],
  "bia-saigon": ["https://www.sabeco.com.vn/en-US/about-us/history"],
  "bisquit-and-dubouche": ["https://www.bisquitdubouche.com/", "https://www.bisquitdubouche.com/en-us/know-how/heritage/"],
  bitburger: ["https://www.bitburger.com/family-brewery/the-bitburger-philosophy/"],
  "black-bottle": ["https://blackbottle.com/products/black-bottle-blended-scotch-whisky"],
  "black-tears": ["https://www.blacktears.com/about"],
  "black-tower": ["https://www.reh-kendermann.de/en/marken/black-tower/"],
  "black-velvet": ["https://blackvelvetwhisky.com/about.php", "https://www.heavenhill.com/press-detail.php?postid=what-is-black-velvet-canadian-whisky"],
  "blanche-de-namur": ["https://bocq.be/fr/"],
  "bodega-norton": ["https://www.norton.com.ar/en/our-vineyards/", "https://www.norton.com.ar/en/our-wines/estate-wines-2/norton-doc/"],
  boekenhoutskloof: ["https://www.boekenhoutskloof.co.za/", "https://www.boekenhoutskloof.co.za/thechocolate-block/"],
  bogle: ["https://boglewinery.com/"],
  bollinger: ["https://www.champagne-bollinger.com/en/champagne/", "https://www.champagne-bollinger.com/en/wine/grande-annee-2018/"],
  borsao: ["https://www.bodegasborsao.com/en/pages/history"],
  brenne: ["https://brennewhisky.com/our-story"],
  brokers: ["https://brokersgin.com/"],
  "bruce-jack": ["https://www.jackfamilywines.com/order/p/sauvignon-blanc"],
  "budejovicky-budvar": ["https://budweiserbudvar.com/brewery/"],
  cakebread: ["https://www.cakebread.com/about/our-history/"],
  "calle-23": ["https://www.tequilacalle23.com/site/"],
  carling: ["https://dev1c3ab2.carling.com/our-story", "https://www.molsoncoors.com/UKandIreland/about"],
  cashmir: ["https://piccadily.com/cashmir"],
  chartreuse: ["https://www.chartreuse.fr/en/home/", "https://www.chartreuse.fr/en/story/"],
  citadelle: ["https://citadellegin.com/en/the-french-gin/"],
  codorniu: ["https://www.codorniu.com/en/the-house-of-cava"],
  "compass-box": ["https://www.compassboxwhisky.com/products/hedonism", "https://www.compassboxwhisky.com/pages/whiskies"],
};

// Cashmir already has a matching stored asset; the other 29 need logo verification.
export const BRAND_LOGOS_BATCH_28: Record<string, string> = {};

export const BRAND_CONTENT_BATCH_28: Record<string, BrandPublicContent> = {
  barahsinge: {
    description: "Barahsinge is a Nepali beer from Yak Brewing Company. Its Pilsner Bier sits beside wheat, fruit and stronger styles rather than a single house lager.",
    story: "The brewery set out to widen the beer choices available in Nepal. Brewmaster Clemens Newman helped shape its pilsner, and the name takes inspiration from the barasingha deer.",
    tastingNotes: [{ title: "Pilsner", description: "Crisp malt gives way to a clean, dry hop finish." }, { title: "Dunkelweizen", description: "A darker wheat-beer style brings fruit and a rounder malt impression." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the pilsner cold into a tall glass; give the dark wheat beer a wider glass." }, { subheading: "Food", description: "Try momo, chilli paneer or chicken sekuwa alongside the range." }],
    pairingIdeas: [{ title: "Nepali table", items: ["chicken momo", "chilli paneer", "chicken sekuwa", "spiced potato wedges"] }],
    whyChoose: "A Nepali brewery with a properly differentiated pilsner and wheat-beer range.",
    faqs: [{ question: "Where is Barahsinge brewed?", answer: "Barahsinge is brewed in Nepal by Yak Brewing Company." }, { question: "Is Barahsinge only a strong beer?", answer: "No. Its range also includes Pilsner Bier and wheat-beer styles." }],
    finalVerdict: "The pilsner makes a sharp starting point; the darker wheat beer is a change of pace.",
    metaTitle: "Barahsinge Beer Guide | BevOry", metaDescription: "Explore Barahsinge beer from Nepal, from crisp Pilsner Bier to wheat styles and food pairings. Check city prices on BevOry.",
  },
  bardinet: {
    description: "Bardinet is a French brandy house with VSOP, XO and other expressions. It blends selected wine spirits matured in oak at the Domaine de Fleurenne estate.",
    story: "Paul Bardinet's name has been on French spirits for over a century. Today's brandy range is built through eau-de-vie selection, oak maturation and blending, rather than a single estate wine.",
    tastingNotes: [{ title: "Oak", description: "Cask ageing gives the brandies a rounded, gently woody character." }, { title: "Texture", description: "The house describes softness and aromatic intensity across its core blends." }],
    howToEnjoy: [{ subheading: "Glass", description: "A small tulip glass gives the brandy room to open without warming it too much." }, { subheading: "Food", description: "Try it after dinner with almond halwa, dark chocolate or roasted walnuts." }],
    pairingIdeas: [{ title: "After dinner", items: ["almond halwa", "dark chocolate", "roasted walnuts", "apple tart"] }],
    whyChoose: "A French brandy range that puts oak-aged blending at the centre.",
    faqs: [{ question: "Where is Bardinet brandy made?", answer: "Bardinet matures and blends its brandy in France." }, { question: "Does Bardinet make VSOP and XO?", answer: "Yes. Both VSOP and XO are part of the house's brandy collection." }],
    finalVerdict: "Bardinet is a measured after-dinner pour for anyone drawn to softly rounded oak.",
    metaTitle: "Bardinet Brandy Guide | BevOry", metaDescription: "Discover Bardinet French brandy, its oak-aged VSOP and XO styles, serving ideas and pairings. Check city prices on BevOry.",
  },
  bathtub: {
    description: "Bathtub is an English gin made by Ableforth's using cold compounding. Botanicals steep in a distilled spirit instead of being redistilled together for the final flavour.",
    story: "The brand revived an older way of building gin flavour through botanical infusion. Its paper-wrapped bottle reflects that old-fashioned method, while the range has grown beyond the original gin.",
    tastingNotes: [{ title: "Juniper", description: "Juniper stays prominent, with citrus and spice around it." }, { title: "Mouthfeel", description: "The cold steep gives the gin a fuller, lightly creamy texture." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use plain tonic and an orange peel so the infused botanicals remain clear." }, { subheading: "Food", description: "Pair with lemon fish fry, tandoori mushrooms or salted cashews." }],
    pairingIdeas: [{ title: "Botanical snacks", items: ["lemon fish fry", "tandoori mushrooms", "salted cashews", "cucumber chaat"] }],
    whyChoose: "Its cold-compounded method gives a familiar gin-and-tonic a different texture.",
    faqs: [{ question: "How is Bathtub Gin made?", answer: "Ableforth's steeps botanicals in spirit using cold compounding." }, { question: "Is Bathtub a London Dry gin?", answer: "The original Bathtub is a compound gin, not a redistilled London Dry." }],
    finalVerdict: "Bathtub is worth trying for the fuller botanical feel that a simple tonic exposes.",
    metaTitle: "Bathtub Gin Guide | BevOry", metaDescription: "Explore Ableforth's cold-compounded Bathtub Gin, its botanical character and Indian pairings. Check city prices on BevOry.",
  },
  bellevoye: {
    description: "Bellevoye is a French triple-malt whisky blended from malts made at three French distilleries. Bleu, Blanc, Rouge and Noir take the house style in different cask or peat directions.",
    story: "Bellevoye brings mature French malts together before further resting the blend in Charente. Its range makes the finish a choice: Blanc uses Sauternes casks, while Noir adds a lightly peated accent.",
    tastingNotes: [{ title: "Bleu", description: "A soft malt-led style keeps smoke out of the foreground." }, { title: "Noir", description: "A measured peat note changes the blend without making it all smoke." }],
    howToEnjoy: [{ subheading: "Compare", description: "Taste Bleu and Noir neat in separate small glasses to catch the peat contrast." }, { subheading: "Food", description: "Try Bleu with roast chicken and Noir with mutton seekh or smoked paneer." }],
    pairingIdeas: [{ title: "Malt and smoke", items: ["roast chicken", "mutton seekh", "smoked paneer", "salted almonds"] }],
    whyChoose: "A French malt blend where cask finish and light peat are genuine style choices.",
    faqs: [{ question: "Is Bellevoye Scotch whisky?", answer: "No. Bellevoye blends malt whiskies distilled in France." }, { question: "Which Bellevoye expression is peated?", answer: "Noir is the lightly peated expression." }],
    finalVerdict: "Bellevoye's colour-coded bottles make a useful tasting flight rather than one fixed whisky profile.",
    metaTitle: "Bellevoye French Whisky Guide | BevOry", metaDescription: "Compare Bellevoye's French triple-malt whiskies, finishes and food pairings. Check city prices on BevOry.",
  },
  "bellini-canella": {
    description: "Bellini Canella is a ready-to-serve Italian sparkling cocktail from the Canella family. It mixes Prosecco Brut with white-peach juice and pulp, plus a little raspberry juice for colour.",
    story: "The family planted its own white-peach grove at San Dona di Piave to control fruit quality for its Bellini. The recipe follows the Venetian drink's peach-and-sparkling-wine idea in a bottled format.",
    tastingNotes: [{ title: "Peach", description: "White-peach pulp gives the drink a soft, ripe fruit nose." }, { title: "Bubbles", description: "Prosecco keeps the sweet fruit moving with a light sparkling finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a flute or small white-wine glass; pour gently to keep the bubbles." }, { subheading: "Food", description: "Pair with fruit chaat, mild paneer tikka or a peach tart." }],
    pairingIdeas: [{ title: "With white peach", items: ["fruit chaat", "mild paneer tikka", "peach tart", "salted cashews"] }],
    whyChoose: "Real white-peach pulp gives this bottled Venetian cocktail its point of difference.",
    faqs: [{ question: "What is in Bellini Canella?", answer: "Canella uses Prosecco Brut, white-peach juice and pulp, and a little raspberry juice." }, { question: "Is Bellini Canella a wine or cocktail?", answer: "It is a ready-to-serve sparkling wine cocktail." }],
    finalVerdict: "A chilled glass gives Bellini Canella's peach more room than drinking it straight from the bottle.",
    metaTitle: "Bellini Canella Cocktail Guide | BevOry", metaDescription: "Discover Bellini Canella's Prosecco and white-peach cocktail, serving ideas and pairings. Check city prices on BevOry.",
  },
  "bia-saigon": {
    description: "Bia Saigon is a Vietnamese beer family from SABECO. Its Lager, Special, Export and Chill labels cover several takes on the country's pale-beer tradition.",
    story: "Saigon Lager joined the brewery's line in 1992, followed by Export and Special in the same decade. SABECO refreshed those labels in 2019 while retaining the Bia Saigon name.",
    tastingNotes: [{ title: "Lager", description: "A clean, brisk pale-beer profile suits a cold pour." }, { title: "Export", description: "A fuller malt impression distinguishes it from the lighter Lager." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve chilled in a straight-sided beer glass." }, { subheading: "Food", description: "Try with fish sauce wings, chilli prawns or paneer pakora." }],
    pairingIdeas: [{ title: "Beer and spice", items: ["chilli prawns", "paneer pakora", "fish sauce wings", "salted peanuts"] }],
    whyChoose: "A Vietnamese brewery name with several clearly separate lager labels.",
    faqs: [{ question: "Who brews Bia Saigon?", answer: "SABECO makes the Bia Saigon beer family in Vietnam." }, { question: "Are Saigon Lager and Saigon Special the same beer?", answer: "No. They are different releases within the Bia Saigon range." }],
    finalVerdict: "Bia Saigon is best explored by choosing the exact label, starting with Lager for the cleanest pour.",
    metaTitle: "Bia Saigon Beer Guide | BevOry", metaDescription: "Explore Bia Saigon Lager, Special and Export from Vietnam, with food ideas and serving tips. Check city prices on BevOry.",
  },
  "bisquit-and-dubouche": {
    description: "Bisquit & Dubouche is a Cognac house founded by Alexandre Bisquit in France. Its VS, VSOP and XO range is known for aromatic, richly textured grape brandy.",
    story: "Alexandre Bisquit developed a distinctive distillation approach that remains part of the house's identity. More than two centuries later, the collection still separates youthful VS from longer-aged VSOP and XO styles.",
    tastingNotes: [{ title: "Aromatics", description: "The house describes a smooth, expressive nose rather than sharp spirit heat." }, { title: "Texture", description: "A rounded, rich mouthfeel carries the fruit and oak." }],
    howToEnjoy: [{ subheading: "Sip", description: "Give VSOP a small tulip glass; keep a little room for the aromas to gather." }, { subheading: "Food", description: "Serve with almond halwa, fig cake or dark chocolate." }],
    pairingIdeas: [{ title: "With Cognac", items: ["almond halwa", "fig cake", "dark chocolate", "roasted walnuts"] }],
    whyChoose: "A Cognac house with an unusually clear distillation story behind its rich texture.",
    faqs: [{ question: "Where is Bisquit & Dubouche made?", answer: "It is made in the Cognac region of France." }, { question: "What styles does Bisquit & Dubouche make?", answer: "The core collection includes VS, VSOP and XO Cognac." }],
    finalVerdict: "The VSOP makes a considered starting point for this house's fruit-and-oak balance.",
    metaTitle: "Bisquit & Dubouche Cognac Guide | BevOry", metaDescription: "Explore Bisquit & Dubouche Cognac, its VS to XO range, serving ideas and pairings. Check city prices on BevOry.",
  },
  bitburger: {
    description: "Bitburger is a German brewery from the South Eifel, best known for Premium Pils. Its pilsner is made with sealed hops, deep-well water, malt and selected yeast.",
    story: "The family brewery dates its home in Bitburg to 1817. Its long-standing commitment to the pilsner style puts hop selection and a clean finish ahead of heavy malt sweetness.",
    tastingNotes: [{ title: "Hops", description: "A herbal hop aroma gives the pilsner its brisk opening." }, { title: "Finish", description: "Dry bitterness cuts through the light malt body." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cold in a narrow pilsner glass to keep the head and aroma." }, { subheading: "Food", description: "Pair with fish fry, chilli paneer or salty pretzels." }],
    pairingIdeas: [{ title: "Pilsner plates", items: ["fish fry", "chilli paneer", "salty pretzels", "masala peanuts"] }],
    whyChoose: "A hop-forward German pilsner made by a family brewery with deep roots in Bitburg.",
    faqs: [{ question: "Where is Bitburger brewed?", answer: "Bitburger is brewed in Bitburg in Germany's South Eifel region." }, { question: "What style is Bitburger Premium?", answer: "It is a German pilsner with a distinct hop-bitter finish." }],
    finalVerdict: "Bitburger is at its best cold, with the hops still obvious beside salty food.",
    metaTitle: "Bitburger Beer Guide | BevOry", metaDescription: "Discover Bitburger Premium Pils, its German hop character and food pairings. Check city prices on BevOry.",
  },
  "black-bottle": {
    description: "Black Bottle is a blended Scotch whisky with peated Islay malt in the mix. Unpeated malts and ex-bourbon-cask grain whisky keep the smoke in balance.",
    story: "The brand's dark bottle gives it a shelf presence that matches its name. Its modern blend deliberately combines smoky and unpeated Scotch components rather than relying on one distillery.",
    tastingNotes: [{ title: "Smoke", description: "Islay peat brings a dry, smoky opening." }, { title: "Sweetness", description: "Vanilla and grain softness sit under the malt smoke." }],
    howToEnjoy: [{ subheading: "Pour", description: "Taste neat, then try an Old Fashioned if you want the peat alongside bitters." }, { subheading: "Food", description: "Serve with mutton seekh, smoked paneer or dark chocolate." }],
    pairingIdeas: [{ title: "With peat", items: ["mutton seekh", "smoked paneer", "dark chocolate", "roasted almonds"] }],
    whyChoose: "An approachable Scotch blend that keeps Islay peat visible without making it the whole story.",
    faqs: [{ question: "Is Black Bottle a single malt?", answer: "No. It is a blended Scotch whisky." }, { question: "Why is Black Bottle smoky?", answer: "Peated malts from Islay are part of its blend." }],
    finalVerdict: "Black Bottle is a handy bridge between soft blended Scotch and peatier malts.",
    metaTitle: "Black Bottle Scotch Guide | BevOry", metaDescription: "Explore Black Bottle blended Scotch, its Islay smoke and food pairings. Check city prices on BevOry.",
  },
  "black-tears": {
    description: "Black Tears is a Cuban dry spiced rum made from molasses-based rum in Ciego de Avila. Coffee, cocoa and the local sweet chilli pepper aji dulce give it its signature flavour.",
    story: "The name refers to the Cuban song Lagrimas Negras. Its producers received permission to make a spiced Cuban rum in 2012, then built the recipe around ingredients associated with the island.",
    tastingNotes: [{ title: "Dark notes", description: "Coffee and cocoa lead without turning the rum into a dessert drink." }, { title: "Pepper", description: "Aji dulce adds a gentle savoury heat at the end." }],
    howToEnjoy: [{ subheading: "Mix", description: "Make a Cuba Libre with cola and fresh lime, or pour over one large cube." }, { subheading: "Food", description: "Try with chilli chocolate, grilled pineapple or pepper chicken." }],
    pairingIdeas: [{ title: "Cocoa and heat", items: ["chilli chocolate", "grilled pineapple", "pepper chicken", "spiced cashews"] }],
    whyChoose: "A dry Cuban spiced rum where coffee and aji dulce are more important than vanilla sweetness.",
    faqs: [{ question: "Where is Black Tears rum from?", answer: "Black Tears is made from Cuban rum associated with Ciego de Avila." }, { question: "What spices Black Tears?", answer: "Its stated flavour ingredients include coffee, cocoa and aji dulce pepper." }],
    finalVerdict: "Black Tears turns a simple rum-and-cola into something darker and gently peppery.",
    metaTitle: "Black Tears Rum Guide | BevOry", metaDescription: "Discover Black Tears Cuban rum, its coffee, cocoa and aji dulce notes and serving ideas. Check city prices on BevOry.",
  },
  "black-tower": {
    description: "Black Tower is a German wine range from Reh Kendermann in Bingen. Riesling sits within a wider collection of still wines sold under the distinctive dark-bottle label.",
    story: "The family winery developed Black Tower as an export-facing German wine name. The range later expanded beyond its original style to include Riesling-led and lighter-drinking releases.",
    tastingNotes: [{ title: "Riesling", description: "Fresh apple and citrus suit the grape's bright acidity." }, { title: "Fruit-led styles", description: "Other Black Tower wines move toward softer, riper fruit rather than one fixed flavour." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Riesling well chilled in a white-wine glass." }, { subheading: "Food", description: "Its acidity suits paneer tikka, prawn curry or spicy noodles." }],
    pairingIdeas: [{ title: "With Riesling", items: ["paneer tikka", "prawn curry", "spicy noodles", "salted cashews"] }],
    whyChoose: "An accessible German wine name with Riesling as a useful starting point.",
    faqs: [{ question: "Who makes Black Tower wine?", answer: "Black Tower belongs to Reh Kendermann, a winery based in Bingen, Germany." }, { question: "Is Black Tower only Riesling?", answer: "No. Its collection includes Riesling and other wine styles." }],
    finalVerdict: "Chilled Black Tower Riesling makes the most sense when dinner brings spice.",
    metaTitle: "Black Tower Wine Guide | BevOry", metaDescription: "Explore Black Tower German wine, its Riesling style and Indian food matches. Check city prices on BevOry.",
  },
  "black-velvet": {
    description: "Black Velvet is a Canadian blended whisky now in Heaven Hill's portfolio. Rye, barley and corn form its grain base, giving the blend a softer profile than a single-grain whisky.",
    story: "The label grew from Canadian distilling traditions connected with the former Gilbey operation. Heaven Hill acquired the brand and its Lethbridge distillery, keeping production in Alberta.",
    tastingNotes: [{ title: "Sweet side", description: "Caramel and dark fruit appear in the classic blend." }, { title: "Spice", description: "Rye, pepper and ginger lift the finish." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice with soda and a strip of orange peel." }, { subheading: "Food", description: "Try with pepper chicken, roasted peanuts or a caramel dessert." }],
    pairingIdeas: [{ title: "Canadian blend table", items: ["pepper chicken", "roasted peanuts", "caramel pudding", "grilled corn"] }],
    whyChoose: "A Canadian grain blend whose caramel softness still leaves room for rye spice.",
    faqs: [{ question: "Where is Black Velvet whisky made?", answer: "Black Velvet is made in Alberta, Canada." }, { question: "What grains are used in Black Velvet?", answer: "The producer identifies rye, barley and corn among its grains." }],
    finalVerdict: "Black Velvet takes well to a simple highball, where its sweet grain and spice stay separate.",
    metaTitle: "Black Velvet Whisky Guide | BevOry", metaDescription: "Discover Black Velvet Canadian whisky, its caramel and rye-spice notes, and food pairings. Check city prices on BevOry.",
  },
  "blanche-de-namur": {
    description: "Blanche de Namur is an unfiltered Belgian wheat beer brewed by Brasserie du Bocq. Coriander and orange peel give the cloudy beer its floral, citrus-spiced character.",
    story: "The brewery named the beer for Blanche of Namur, a historic figure associated with the region. Brasserie du Bocq has brewed in Belgium since the nineteenth century and retains haze in this wheat beer rather than filtering it clear.",
    tastingNotes: [{ title: "Aroma", description: "Orange peel and coriander rise over soft wheat." }, { title: "Texture", description: "A gentle cloudiness gives the beer a rounded feel with a fresh finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve chilled in a wide wheat-beer glass, allowing the unfiltered haze into the pour." }, { subheading: "Food", description: "Match it with tandoori prawns, lemon fish or cauliflower pakora." }],
    pairingIdeas: [{ title: "Citrus-spiced beer", items: ["tandoori prawns", "lemon fish", "cauliflower pakora", "salted fries"] }],
    whyChoose: "A Belgian witbier with a clear coriander-and-orange signature.",
    faqs: [{ question: "Who brews Blanche de Namur?", answer: "Brasserie du Bocq brews it in Belgium." }, { question: "Why is Blanche de Namur cloudy?", answer: "The brewery leaves this wheat beer unfiltered." }],
    finalVerdict: "Its soft wheat body takes the edge off spicy seafood without hiding the orange peel.",
    metaTitle: "Blanche de Namur Beer Guide | BevOry", metaDescription: "Explore Blanche de Namur Belgian wheat beer, its orange and coriander notes, and pairings. Check city prices on BevOry.",
  },
  "bodega-norton": {
    description: "Bodega Norton is an Argentine winery based in Lujan de Cuyo, Mendoza. Its five vineyards make Malbec, Cabernet Sauvignon and other wines at the foot of the Andes.",
    story: "The original Perdriel property remains home to the winery. Norton was among the first wineries to gain Lujan de Cuyo's Malbec DOC certification, tying one of its flagship wines to that specific place.",
    tastingNotes: [{ title: "Malbec DOC", description: "Ripe dark fruit and a rounded tannin shape the Lujan de Cuyo red." }, { title: "Cabernet Sauvignon", description: "Blackberry and red pepper notes bring a firmer, spicier contrast." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Malbec slightly cool in a broad red-wine glass." }, { subheading: "Food", description: "Pair with mutton seekh, mushroom kebabs or grilled lamb chops." }],
    pairingIdeas: [{ title: "Mendoza reds", items: ["mutton seekh", "mushroom kebabs", "grilled lamb chops", "aged cheddar"] }],
    whyChoose: "A Mendoza estate with a genuinely place-specific Malbec DOC story.",
    faqs: [{ question: "Where is Bodega Norton?", answer: "Its winery is in Perdriel, Lujan de Cuyo, Mendoza, Argentina." }, { question: "Does Norton make Malbec?", answer: "Yes. Norton makes Malbec, including a Lujan de Cuyo DOC bottling." }],
    finalVerdict: "Norton Malbec is a useful way into the darker fruit and softer tannins of Mendoza.",
    metaTitle: "Bodega Norton Wine Guide | BevOry", metaDescription: "Discover Bodega Norton Malbec from Mendoza, its vineyard story and Indian pairings. Check city prices on BevOry.",
  },
  boekenhoutskloof: {
    description: "Boekenhoutskloof is a South African winery in Franschhoek known for Syrah and its The Chocolate Block red blend. The estate also works with Cabernet Sauvignon, Grenache, Semillon and Viognier.",
    story: "The farm and homestead were restored after a 1993 purchase, followed by new vineyard planting. The Chocolate Block began with the 2002 vintage and made the winery's Syrah-led blending style widely known.",
    tastingNotes: [{ title: "The Chocolate Block", description: "Syrah gives the blend dark fruit and spice; Grenache and Cinsault bring lift." }, { title: "Estate Syrah", description: "A deeper, more peppery red direction highlights the grape itself." }],
    howToEnjoy: [{ subheading: "Decant", description: "Give a young Chocolate Block red a broad glass and a little air." }, { subheading: "Food", description: "Set it beside mutton rogan josh, grilled lamb or mushroom pepper fry." }],
    pairingIdeas: [{ title: "Cape reds", items: ["mutton rogan josh", "grilled lamb", "mushroom pepper fry", "aged gouda"] }],
    whyChoose: "A Franschhoek winery with a distinctive Syrah-led blend and serious single-varietal reds.",
    faqs: [{ question: "Where is Boekenhoutskloof?", answer: "The winery is in Franschhoek, South Africa." }, { question: "Who makes The Chocolate Block?", answer: "The Chocolate Block is made by Boekenhoutskloof." }],
    finalVerdict: "The Chocolate Block brings generous fruit, while the estate Syrah narrows the focus to pepper and depth.",
    metaTitle: "Boekenhoutskloof Wine Guide | BevOry", metaDescription: "Explore Boekenhoutskloof Syrah and The Chocolate Block from Franschhoek. Check city prices on BevOry.",
  },
  bogle: {
    description: "Bogle is a family-owned California winery based in Clarksburg. Its range includes Chardonnay, Pinot Noir and other wines made from estate and long-term grower fruit.",
    story: "The Bogle family has farmed in the Sacramento River Delta for generations. The winery uses hands-on cellar work, including hand-stirring Chardonnay and ageing some reds in small oak barrels.",
    tastingNotes: [{ title: "Chardonnay", description: "Stone fruit and citrus sit within a fuller, worked-wine texture." }, { title: "Pinot Noir", description: "Red cherry gives the lighter red a fruit-first nose." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Chardonnay lightly; pour Pinot Noir a touch cooler than room temperature." }, { subheading: "Food", description: "Pair Chardonnay with tandoori fish and Pinot Noir with mushroom tikka." }],
    pairingIdeas: [{ title: "California table", items: ["tandoori fish", "mushroom tikka", "roast chicken", "grilled vegetables"] }],
    whyChoose: "A Clarksburg family winery that gives Chardonnay and Pinot Noir different, accessible routes.",
    faqs: [{ question: "Where is Bogle winery?", answer: "Bogle Family Vineyards is based in Clarksburg, California." }, { question: "Does Bogle make Chardonnay?", answer: "Yes. Chardonnay is one of the winery's established varietal wines." }],
    finalVerdict: "Bogle's Chardonnay is the fuller white; Pinot Noir offers a softer red beside food.",
    metaTitle: "Bogle Wine Guide | BevOry", metaDescription: "Compare Bogle California Chardonnay and Pinot Noir, with serving tips and pairings. Check city prices on BevOry.",
  },
  bollinger: {
    description: "Bollinger is a Champagne house in Ay, France, with Pinot Noir central to its style. Chardonnay also plays a substantial role in its vintage wines, including La Grande Annee.",
    story: "The house's vineyards around Ay and other Champagne villages give Pinot Noir a prominent place in its blends. For La Grande Annee, Bollinger ferments the wine in oak before long bottle ageing.",
    tastingNotes: [{ title: "Pinot Noir", description: "The grape adds structure and red-fruit depth beneath the bubbles." }, { title: "Oak-fermented vintage wine", description: "La Grande Annee takes a fuller, toastier direction than a light aperitif fizz." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve chilled in a tulip-shaped wine glass rather than an extremely narrow flute." }, { subheading: "Food", description: "Try with tandoori prawns, chicken malai tikka or aged cheddar." }],
    pairingIdeas: [{ title: "Champagne at dinner", items: ["tandoori prawns", "chicken malai tikka", "aged cheddar", "salted almonds"] }],
    whyChoose: "A Pinot Noir-led Champagne house whose vintage wines show real oak-fermentation character.",
    faqs: [{ question: "Where is Bollinger made?", answer: "Bollinger is a Champagne house based in Ay, France." }, { question: "Which grapes are important to Bollinger?", answer: "Pinot Noir is central to the house style, with Chardonnay also used in its blends." }],
    finalVerdict: "Bollinger is the Champagne to open when the glass needs to stand up to a proper meal.",
    metaTitle: "Bollinger Champagne Guide | BevOry", metaDescription: "Explore Bollinger's Pinot Noir-led Champagne, vintage style and Indian food matches. Check city prices on BevOry.",
  },
  borsao: {
    description: "Borsao is a Spanish winery in Campo de Borja, Aragon, with Garnacha at the centre of its reds. The Tres Picos label is one of its best-known expressions of that grape.",
    story: "The winery works in a region whose dry, varied vineyards have long favoured Garnacha. Borsao developed a reputation around that grape rather than imitating Rioja's Tempranillo-led model.",
    tastingNotes: [{ title: "Garnacha fruit", description: "Ripe red berries give the wines an open, generous start." }, { title: "Spice", description: "Warm spice and a broad mouthfeel carry the red-fruit finish." }],
    howToEnjoy: [{ subheading: "Cool slightly", description: "Serve red Borsao a little below room temperature in a broad glass." }, { subheading: "Food", description: "Match with mutton seekh, smoky baingan bharta or lamb chops." }],
    pairingIdeas: [{ title: "Garnacha with spice", items: ["mutton seekh", "baingan bharta", "grilled lamb chops", "aged manchego"] }],
    whyChoose: "A Campo de Borja winery that makes Garnacha the main event.",
    faqs: [{ question: "Where does Borsao wine come from?", answer: "Borsao is based in Campo de Borja, Aragon, Spain." }, { question: "Which grape is Borsao known for?", answer: "Garnacha is the winery's defining red grape." }],
    finalVerdict: "Borsao Garnacha gives spicy food a ripe-fruited red without losing its regional identity.",
    metaTitle: "Borsao Wine Guide | BevOry", metaDescription: "Discover Borsao Garnacha from Campo de Borja, its style and Indian food pairings. Check city prices on BevOry.",
  },
  brenne: {
    description: "Brenne is a French single malt whisky made in the Cognac region. It uses locally grown heirloom barley and matures in new French Limousin oak and Cognac casks.",
    story: "Allison Parc founded Brenne to show what French grain, water and casks could do for single malt. The whisky uses water from the Charente and a maturation route uncommon in Scotch.",
    tastingNotes: [{ title: "Fruit", description: "Ripe fruit and a soft sweetness give Brenne its inviting opening." }, { title: "Cask", description: "Cognac wood brings vanilla and a rounded finish." }],
    howToEnjoy: [{ subheading: "Sip", description: "Taste neat in a small tulip glass before adding a few drops of water." }, { subheading: "Food", description: "Try with saffron kulfi, roasted almonds or apple tart." }],
    pairingIdeas: [{ title: "French malt table", items: ["saffron kulfi", "roasted almonds", "apple tart", "mild chicken tikka"] }],
    whyChoose: "A French single malt whose local barley and Cognac-cask maturation really shape its identity.",
    faqs: [{ question: "Is Brenne a Scotch whisky?", answer: "No. Brenne is a single malt made in France's Cognac region." }, { question: "What casks mature Brenne?", answer: "The maker uses new French Limousin oak and Cognac casks." }],
    finalVerdict: "Brenne is a fruitier single malt for the drinker curious about whisky made outside Scotland.",
    metaTitle: "Brenne French Whisky Guide | BevOry", metaDescription: "Explore Brenne single malt from Cognac, its French oak and fruit notes, and food pairings. Check city prices on BevOry.",
  },
  brokers: {
    description: "Broker's is an English gin made with traditional copper pot distillation. Brothers Martin and Andy Dawson built the label around a juniper-led London Dry style.",
    story: "The Dawson brothers chose a traditional recipe and an English distillery rather than a heavily flavoured modern gin. The small bowler hat on the cap recalls the London stockbroker who inspired the name.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper leads the nose and stays present through the finish." }, { title: "Citrus and spice", description: "Citrus peel and dry spice sharpen the classic gin profile." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour over plenty of ice with plain tonic and a twist of lemon." }, { subheading: "Food", description: "Try with tandoori prawns, lemon-pepper chicken or salted almonds." }],
    pairingIdeas: [{ title: "With a dry gin", items: ["tandoori prawns", "lemon-pepper chicken", "salted almonds", "cucumber chaat"] }],
    whyChoose: "A straightforward London Dry built around juniper rather than novelty flavours.",
    faqs: [{ question: "Who created Broker's Gin?", answer: "Brothers Martin and Andy Dawson created the brand." }, { question: "What style is Broker's Gin?", answer: "It is a juniper-forward London Dry gin made in England." }],
    finalVerdict: "Broker's earns its place in a gin and tonic by keeping the botanicals crisp and familiar.",
    metaTitle: "Broker's Gin Guide | BevOry", metaDescription: "Discover Broker's English London Dry gin, its juniper and citrus notes, and food pairings. Check city prices on BevOry.",
  },
  "bruce-jack": {
    description: "Bruce Jack is a South African wine label founded by winemaker Bruce Jack. Its range draws on vineyards across the Western Cape, with Sauvignon Blanc and red varietal wines among its releases.",
    story: "Bruce Jack built the label after years of working with South African growers and cellars. The wines put the Cape's different vineyard sites and grape varieties ahead of a single estate signature.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Gooseberry and green fig bring a fresh, herbal edge to the white wine." }, { title: "Finish", description: "Bright acidity keeps the fruit lively at the end of a sip." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Sauvignon Blanc chilled in a white-wine glass." }, { subheading: "Food", description: "Try it with coriander fish tikka, grilled prawns or lemony paneer." }],
    pairingIdeas: [{ title: "With Sauvignon Blanc", items: ["coriander fish tikka", "grilled prawns", "lemony paneer", "goat cheese"] }],
    whyChoose: "A Cape wine label that gives fresh Sauvignon Blanc a clear, food-friendly role.",
    faqs: [{ question: "Who founded Bruce Jack wine?", answer: "South African winemaker Bruce Jack founded the label." }, { question: "Where does Bruce Jack wine come from?", answer: "Its wines draw on vineyards in South Africa's Western Cape." }],
    finalVerdict: "Bruce Jack Sauvignon Blanc brings enough herbal freshness for a spiced seafood plate.",
    metaTitle: "Bruce Jack Wine Guide | BevOry", metaDescription: "Explore Bruce Jack wines from South Africa, Sauvignon Blanc notes and seafood pairings. Check city prices on BevOry.",
  },
  "budejovicky-budvar": {
    description: "Budejovicky Budvar is a Czech brewery in Ceske Budejovice. Its lager is brewed with Moravian barley, Saaz hops, local water and the brewery's own yeast.",
    story: "The state-owned brewery has made beer in Ceske Budejovice since 1895. Budvar still uses whole-cone Saaz hops and cold lagering, keeping the beer tied to its Czech brewing home.",
    tastingNotes: [{ title: "Malt", description: "A rounded bread-like malt note gives the lager its base." }, { title: "Hops", description: "Saaz hops add a clean, herbal bitterness that lingers after the sip." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cold in a clean lager glass with room for a proper foam head." }, { subheading: "Food", description: "Pair with chicken schnitzel, aloo tikki or pork sausages." }],
    pairingIdeas: [{ title: "Lager table", items: ["chicken schnitzel", "aloo tikki", "pork sausages", "salted peanuts"] }],
    whyChoose: "A Czech lager whose Saaz hops and long cold maturation give it a distinct shape.",
    faqs: [{ question: "Where is Budvar brewed?", answer: "It is brewed in Ceske Budejovice in the Czech Republic." }, { question: "Which hops does Budvar use?", answer: "The brewery uses whole-cone Saaz hops." }],
    finalVerdict: "Budvar has the malt weight and herbal finish to make a lager interesting with dinner.",
    metaTitle: "Budejovicky Budvar Beer Guide | BevOry", metaDescription: "Discover Czech Budvar lager, Moravian barley and Saaz hops, with food pairings. Check city prices on BevOry.",
  },
  cakebread: {
    description: "Cakebread Cellars is a Napa Valley winery founded by Jack and Dolores Cakebread. Its wines include Chardonnay and Cabernet Sauvignon from California vineyards.",
    story: "The Cakebreads bought a ranch in Rutherford in 1972 and released their first Chardonnay from the 1973 vintage. The family continued building vineyard holdings through Napa Valley as the winery grew.",
    tastingNotes: [{ title: "Chardonnay", description: "Orchard fruit and citrus sit over a rounded, polished texture." }, { title: "Cabernet Sauvignon", description: "Dark fruit and firm tannins give the red a more structured feel." }],
    howToEnjoy: [{ subheading: "Glass", description: "Chill Chardonnay lightly; give Cabernet Sauvignon a broad glass and time to open." }, { subheading: "Food", description: "Match Chardonnay with chicken malai tikka and Cabernet with lamb chops." }],
    pairingIdeas: [{ title: "Napa table", items: ["chicken malai tikka", "grilled lamb chops", "mushroom tikka", "aged cheddar"] }],
    whyChoose: "A family Napa winery with a long-standing focus on both Chardonnay and Cabernet Sauvignon.",
    faqs: [{ question: "Who founded Cakebread Cellars?", answer: "Jack and Dolores Cakebread founded the winery after buying a Rutherford ranch in 1972." }, { question: "Where is Cakebread Cellars?", answer: "The winery is in Napa Valley, California." }],
    finalVerdict: "Cakebread offers a Napa white-and-red pairing with enough contrast to plan a whole dinner.",
    metaTitle: "Cakebread Wine Guide | BevOry", metaDescription: "Explore Cakebread Cellars from Napa Valley, its Chardonnay and Cabernet styles and pairings. Check city prices on BevOry.",
  },
  "calle-23": {
    description: "Calle 23 is a tequila label made from blue agave in the highlands of Jalisco, Mexico. Founder and distiller Sophie Decobecq created Blanco, Reposado and Anejo expressions.",
    story: "Decobecq trained in the science of fermentation before building Calle 23 in Mexico. Highland agave from the area around Tepatitlan gives the range its regional starting point.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus keep the unaged tequila vivid." }, { title: "Reposado", description: "Oak rest adds vanilla warmth while agave remains in view." }],
    howToEnjoy: [{ subheading: "Sip", description: "Taste Blanco neat in a small glass or use it in a margarita with fresh lime." }, { subheading: "Food", description: "Try with chilli-lime prawns, chicken tacos or paneer tikka." }],
    pairingIdeas: [{ title: "Agave with spice", items: ["chilli-lime prawns", "chicken tacos", "paneer tikka", "grilled corn"] }],
    whyChoose: "A Jalisco highland tequila range shaped by a distiller with a fermentation background.",
    faqs: [{ question: "Who founded Calle 23 tequila?", answer: "Sophie Decobecq founded Calle 23." }, { question: "Where is Calle 23 made?", answer: "It is made from blue agave in the highlands of Jalisco, Mexico." }],
    finalVerdict: "Calle 23 Blanco puts cooked agave first, especially in a simple lime-led drink.",
    metaTitle: "Calle 23 Tequila Guide | BevOry", metaDescription: "Explore Calle 23 highland tequila, Blanco and Reposado notes, and food pairings. Check city prices on BevOry.",
  },
  carling: {
    description: "Carling is a British lager brand brewed by Molson Coors in Burton-on-Trent. The core beer is a familiar light lager made with British barley.",
    story: "The Carling name began with the Carling family in Canada before becoming closely associated with British pubs. Burton-on-Trent's brewing tradition remains central to its UK production.",
    tastingNotes: [{ title: "Malt", description: "Light cereal malt gives the lager a clean, uncomplicated opening." }, { title: "Finish", description: "A mild hop edge leaves the finish dry and easy to revisit." }],
    howToEnjoy: [{ subheading: "Cold", description: "Pour well chilled into a lager glass or clean pint glass." }, { subheading: "Food", description: "Pair with fish and chips, chicken pakora or spicy fries." }],
    pairingIdeas: [{ title: "Pub snacks", items: ["fish and chips", "chicken pakora", "spicy fries", "salted peanuts"] }],
    whyChoose: "A light Burton-brewed lager built for straightforward pub drinking.",
    faqs: [{ question: "Who brews Carling in the UK?", answer: "Molson Coors brews Carling in Burton-on-Trent." }, { question: "Is Carling a lager?", answer: "Yes. The core Carling beer is a British lager." }],
    finalVerdict: "Carling is at its best cold beside salty, crisp pub food.",
    metaTitle: "Carling Beer Guide | BevOry", metaDescription: "Discover Carling British lager, its Burton-on-Trent brewing and pub-food pairings. Check city prices on BevOry.",
  },
  cashmir: {
    description: "Cashmir is an Indian vodka from Piccadily Agro Industries made with Sona Moti heritage wheat. Its water comes from the Kashmir Valley, linking grain from Punjab with northern mountain water.",
    story: "Piccadily brought Cashmir into a portfolio that also includes Indian malt whisky. The vodka is distilled seven times and filtered through several stages, including activated carbon and mango wood charcoal.",
    tastingNotes: [{ title: "Grain", description: "A restrained wheat sweetness softens the vodka's otherwise clean profile." }, { title: "Finish", description: "The filtered spirit ends crisp rather than heavily flavoured." }],
    howToEnjoy: [{ subheading: "Cold", description: "Serve well chilled in a small glass or use with soda and a lemon twist." }, { subheading: "Food", description: "Try with tandoori prawns, cucumber chaat or salted cashews." }],
    pairingIdeas: [{ title: "With a clean vodka", items: ["tandoori prawns", "cucumber chaat", "salted cashews", "smoked salmon"] }],
    whyChoose: "Sona Moti wheat and Kashmir Valley water give this Indian vodka a specific provenance.",
    faqs: [{ question: "Who makes Cashmir vodka?", answer: "Piccadily Agro Industries makes Cashmir in India." }, { question: "What grain is used for Cashmir?", answer: "The producer uses Sona Moti heritage wheat." }],
    finalVerdict: "Cashmir is a crisp wheat vodka that keeps its origin part of the conversation.",
    metaTitle: "Cashmir Vodka Guide | BevOry", metaDescription: "Explore Cashmir Indian wheat vodka, its Kashmir Valley water and food pairings. Check city prices on BevOry.",
  },
  chartreuse: {
    description: "Chartreuse is a French herbal liqueur made by Carthusian monks. Green and Yellow Chartreuse use a closely guarded mixture of 130 plants, flowers, bark and roots.",
    story: "The monks trace the liqueur to a manuscript received in 1605. The production story moved through centuries of monastic distilling, with the green and yellow versions developing distinct profiles.",
    tastingNotes: [{ title: "Green", description: "Intense herbal and mint-like notes give the green liqueur its bold edge." }, { title: "Yellow", description: "The yellow version is softer and sweeter, with floral and spice notes." }],
    howToEnjoy: [{ subheading: "After dinner", description: "Serve a small chilled pour, or use Green Chartreuse sparingly in a Last Word cocktail." }, { subheading: "Food", description: "Try with dark chocolate, pistachio kulfi or almond biscotti." }],
    pairingIdeas: [{ title: "Herbs after dinner", items: ["dark chocolate", "pistachio kulfi", "almond biscotti", "candied orange peel"] }],
    whyChoose: "Few liqueurs have Chartreuse's combination of monastic history and unmistakable herbal flavour.",
    faqs: [{ question: "Who makes Chartreuse?", answer: "Carthusian monks make Chartreuse in France." }, { question: "Are Green and Yellow Chartreuse the same?", answer: "No. They are separate liqueurs with different herbal intensity and sweetness." }],
    finalVerdict: "Chartreuse is a small pour with enough herbal character to carry an entire cocktail.",
    metaTitle: "Chartreuse Liqueur Guide | BevOry", metaDescription: "Compare Green and Yellow Chartreuse, their herbal notes and serving ideas. Check city prices on BevOry.",
  },
  citadelle: {
    description: "Citadelle is a French gin created by Alexandre Gabriel near Cognac. It is distilled in copper pot stills with juniper and a broad selection of botanicals.",
    story: "Gabriel launched Citadelle in 1996 at the Chateau de Bonbonnet estate. The team later planted a juniper field there, bringing one of gin's defining ingredients close to the distillery.",
    tastingNotes: [{ title: "Juniper", description: "Juniper gives the gin its pine-like centre." }, { title: "Citrus and pepper", description: "Citrus peel brightens the nose, while peppery spice carries the finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Build with plain tonic, plenty of ice and a strip of orange peel." }, { subheading: "Food", description: "Try with tandoori fish, pepper mushrooms or salted almonds." }],
    pairingIdeas: [{ title: "Botanical plate", items: ["tandoori fish", "pepper mushrooms", "salted almonds", "lemon chicken"] }],
    whyChoose: "A Cognac-region gin that gives juniper, citrus and spice distinct parts to play.",
    faqs: [{ question: "Who created Citadelle Gin?", answer: "Alexandre Gabriel created Citadelle in 1996." }, { question: "Where is Citadelle made?", answer: "It is made near Cognac in France." }],
    finalVerdict: "Citadelle makes a bright gin and tonic without covering up the juniper.",
    metaTitle: "Citadelle Gin Guide | BevOry", metaDescription: "Discover Citadelle French gin from Cognac, its juniper and citrus notes, and pairings. Check city prices on BevOry.",
  },
  codorniu: {
    description: "Codorniu is a Spanish cava producer based in Sant Sadurni d'Anoia in Penedes. Its traditional-method sparkling wines use grapes including Macabeo, Xarel-lo and Parellada.",
    story: "Josep Raventos made the family's first sparkling wine in 1872, using bottle fermentation learned from Champagne. The Anna de Codorniu line later brought Chardonnay into a cava blend alongside local grapes.",
    tastingNotes: [{ title: "Classic cava", description: "Apple and citrus meet the light bread-like notes that bottle ageing can bring." }, { title: "Anna de Codorniu", description: "Chardonnay adds a rounder fruit impression beside the fresher local grapes." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a tulip glass that leaves room for the aroma." }, { subheading: "Food", description: "Pair with tandoori prawns, patatas bravas or chicken malai tikka." }],
    pairingIdeas: [{ title: "With cava", items: ["tandoori prawns", "patatas bravas", "chicken malai tikka", "salted almonds"] }],
    whyChoose: "A historic Penedes producer whose sparkling-wine story reaches back to 1872.",
    faqs: [{ question: "Where is Codorniu cava made?", answer: "Codorniu is based in Sant Sadurni d'Anoia in Spain's Penedes region." }, { question: "Which grapes go into Codorniu cava?", answer: "Its range uses local grapes such as Macabeo, Xarel-lo and Parellada; Anna de Codorniu also uses Chardonnay." }],
    finalVerdict: "Codorniu's crisp bubbles make a useful bridge between salty tapas and Indian starters.",
    metaTitle: "Codorniu Cava Guide | BevOry", metaDescription: "Explore Codorniu cava from Penedes, its grapes, sparkling style and food pairings. Check city prices on BevOry.",
  },
  "compass-box": {
    description: "Compass Box is a Scotch whisky blending house founded by John Glaser. Its releases include Hedonism blended grain whisky and malt-led expressions built from selected casks.",
    story: "Glaser started Compass Box in 2000 to make blending the central craft rather than an anonymous step. The house names its different blends and explains how their component whiskies shape the result.",
    tastingNotes: [{ title: "Hedonism", description: "Vanilla cream, toffee and coconut give the grain blend its dessert-like side." }, { title: "Texture", description: "A soft, silky mouthfeel makes Hedonism gentler than a peppery malt blend." }],
    howToEnjoy: [{ subheading: "Sip", description: "Pour Hedonism neat into a small tulip glass, then try a few drops of water." }, { subheading: "Food", description: "Try with salted caramel, almond kulfi or pecan pie." }],
    pairingIdeas: [{ title: "With Hedonism", items: ["salted caramel", "almond kulfi", "pecan pie", "roasted hazelnuts"] }],
    whyChoose: "A whisky house that makes the blend itself the main point of interest.",
    faqs: [{ question: "Who founded Compass Box?", answer: "John Glaser founded Compass Box in 2000." }, { question: "Is Hedonism a single malt?", answer: "No. Hedonism is a blended grain Scotch whisky." }],
    finalVerdict: "Compass Box Hedonism is a different route into Scotch, with grain whisky's creamy side upfront.",
    metaTitle: "Compass Box Whisky Guide | BevOry", metaDescription: "Explore Compass Box Scotch, including Hedonism's vanilla and toffee notes. Check city prices on BevOry.",
  },
};
