import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_40 = [
  ["bombay-bramble", "Bombay Bramble", "United Kingdom", "Gin", "1d557a83ac49a3f6fec78ce7"],
  ["by-ott", "BY.OTT", "France", "Wine", "6fb3c07b3974f86a5196c0e5"],
  ["cavino-romios", "Cavino Romios", "Greece", "Ouzo", "90164eb649d9115e90376770"],
  ["domaine-hamelin", "Domaine Hamelin", "France", "Wine", "32f3be9b713f1cc483a633e4"],
  ["hakutsuru-tojikan", "Hakutsuru Toji-Kan", "Japan", "Sake", "3cc09ac44b290bd280957f71"],
  ["hana-kizakura", "Hana Kizakura", "Japan", "Sake", "fde0a46c67a6a24f0d69b792"],
  ["l-angoor-by-big-banyan-wines", "L'Angoor by Big Banyan", "India", "Wine", "7794f29d027412b0a780b27d"],
  ["man-vintners", "MAN Vintners", "South Africa", "Wine", "546cd1f60f6e3001d60afdaf"],
  ["mirabeau-classic-cotes", "Mirabeau Classic", "France", "Wine", "9f59b4601ef43f3c9a8a0153"],
  ["montes-reserva", "Montes Reserva", "Chile", "Wine", "ee09f41d502abb94b36ee45e"],
  ["naked", "Naked Malt", "Scotland", "Whisky", "12a667c9be6ff8f665d2e916"],
  ["old-monk-amber", "Old Monk Amber", "India", "Rum", "339a6702ff6d7b809c72e480"],
  ["orendain", "Orendain", "Mexico", "Tequila", "4897ac311b105fdf497a610a"],
  ["petalo-amore", "Petalo Il Vino dell'Amore", "Italy", "Wine", "994ea153cef393e627465d47"],
  ["pian-delle", "Pian delle Vigne", "Italy", "Wine", "9466f48415d0cd054dbcc377"],
  ["produttori", "Produttori del Barbaresco", "Italy", "Wine", "b70860b8f916cefd1a28cb1c"],
  ["rampur-1943-virasat", "Rampur 1943 Virasat", "India", "Whisky", "89dd93cf374f36f77738b44d"],
  ["red-breast", "Redbreast", "Ireland", "Whisky", "71b26b01d831c7d29b2f957b"],
  ["reserva-de-la-familia", "Reserva de la Familia", "Mexico", "Tequila", "23e3cae9ba4652b502bcc7f1"],
  ["saint-esprit", "Saint-Esprit", "France", "Wine", "630cab752cab4b496e0a495a"],
  ["scaia", "Scaia", "Italy", "Wine", "6eac318248668b5d8f144773"],
  ["siepi", "Siepi", "Italy", "Wine", "4407b5725be62d90fa35af26"],
  ["solaia", "Solaia", "Italy", "Wine", "7e151b876780b3cb64c9c017"],
  ["somrus", "Somrus", "United States", "Liqueur", "a415b728ae7effc4160e7c91"],
  ["trois-rivieres", "Trois Rivieres", "Martinique", "Rum", "3c1a4af88b9370561ed6ec4f"],
  ["whitley", "Whitley Neill", "United Kingdom", "Gin", "edab2d0f5554bedd033e27cf"],
  ["belstar", "Belstar", "Italy", "Sparkling Wine", "95ed797a0ae6804cc1aa7fa5"],
  ["bira-original", "Bira 91 Original", "India", "Beer", "cd58e7fc8a8f77bc2d1d7053"],
  ["beaune-du-chateau", "Beaune du Chateau", "France", "Wine", "e2e00e3e152a39bd35c97ce1"],
  ["glengrant-the", "The Glen Grant", "Scotland", "Whisky", "fd3a72e1b43d9064cf762b3e"],
] as const;

// Source provenance is internal. Public fields below contain consumer copy only.
export const BRAND_SOURCES_BATCH_40: Record<string, string[]> = {
  "bombay-bramble": ["https://www.bombaysapphire.com/products/bombay-bramble/"],
  "by-ott": ["https://www.domaines-ott.com/en/by-ott-rose"],
  "cavino-romios": ["https://cavino.gr/product/ouzo-romios-700ml/"],
  "domaine-hamelin": ["https://www.dvp-vins-domaines.com/en/pdf/domaine/24/domaine-hamelin"],
  "hakutsuru-tojikan": ["https://www.hakutsuru-sake.com/product/hakutsuru-toji-kan-sake/"],
  "hana-kizakura": ["https://kizakura.co.jp/en/kizakura/item_03_1520.html"],
  "l-angoor-by-big-banyan-wines": ["https://bigbanyanwines.com/products/langoor/langoor-white"],
  "man-vintners": ["https://manwines.com/our-wines/"],
  "mirabeau-classic-cotes": ["https://www.maisonmirabeau.com/our-range/classic-provence-rose-wine/"],
  "montes-reserva": ["https://www.monteswines.com/EN/biblioteca/classic-series/merlot"],
  naked: ["https://www.nakedmalt.com/"],
  "old-monk-amber": ["https://mohanmeakin.com/rums/"],
  orendain: ["https://marketing.destileriaorendain.com/site/en/home/"],
  "petalo-amore": ["https://www.bottegaspa.com/collezioni/petalo-moscato/"],
  "pian-delle": ["https://www.antinori.it/en/vino/pian-delle-vigne-brunello-di-montalcino-en/"],
  produttori: ["https://www.produttoridelbarbaresco.com/en/"],
  "rampur-1943-virasat": ["https://radicokhaitan.com/wp-content/uploads/2025/11/Press-Release-Debut-of-Rampur-1943-Virasat-Single-Malt-November-24-2025.pdf"],
  "red-breast": ["https://www.redbreastwhiskey.com/en-us/whiskey-collections/redbreast-12-year-old/"],
  "reserva-de-la-familia": ["https://cuervo.com/tequila-categories/"],
  "saint-esprit": ["https://delas.com/vins/saint-esprit/"],
  scaia: ["https://shop.tenutasantantonio.it/en/experiences-events/scaia-tasting/"],
  siepi: ["https://mazzei.it/en/products/discover-siepi"],
  solaia: ["https://www.antinori.it/en/vino/solaia-en/"],
  somrus: ["https://somrus.com/"],
  "trois-rivieres": ["https://www.troisrivieresrhum.com/our-know-how/"],
  whitley: ["https://whitleyneill.com/gin/blood-orange-gin/"],
  belstar: ["https://bisol.it/bisol/en/"],
  "bira-original": ["https://www.bira91.com/", "https://delhiassembly.delhi.gov.in/sites/default/files/dlas/question/un-123-20180807.pdf", "https://untappd.com/b/bira-91-bira-91-strong/2135379"],
  "beaune-du-chateau": ["https://www.bouchard-pereetfils.com/en/our-wines/beaune-du-chateau-premier-cru"],
  "glengrant-the": ["https://www.theglengrant.com/en/"],
};

export const BRAND_LOGOS_BATCH_40: Record<string, string> = {
  whitley: "https://whitleyneill.com/wp-content/uploads/2023/03/WNG_LOGO_2023_MASTER_stacked_trimmed.png.webp",
};

export const BRAND_CONTENT_BATCH_40: Record<string, BrandPublicContent> = {
  "bombay-bramble": {
    description: "Bombay Bramble is Bombay Sapphire's berry-infused gin, made with blackberries and raspberries. It keeps the London dry gin base but brings tart fruit to the front.",
    story: "Bombay Sapphire developed Bramble around the blackberry-led Bramble cocktail. The fruit infusion supplies its colour without added sugar.",
    tastingNotes: [{ title: "Berry", description: "Blackberry and raspberry give the nose a fresh, tart lift." }, { title: "Gin finish", description: "Juniper stays present beneath the fruit, with a dry finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Build a gin and tonic over ice and add a lemon wedge." }, { subheading: "Food", description: "Try it with pepper paneer tikka or a plate of berry tartlets." }],
    pairingIdeas: [{ title: "At the table", items: ["pepper paneer tikka", "berry tartlets", "salted cashews", "grilled prawns"] }],
    whyChoose: "A tart-fruit gin that still tastes recognisably of gin.",
    faqs: [{ question: "What fruit is in Bombay Bramble?", answer: "Bombay Bramble is infused with blackberries and raspberries." }, { question: "Does Bombay Bramble contain added sugar?", answer: "Bombay Sapphire says no sugar is added to Bramble." }],
    finalVerdict: "Bramble brings berry sharpness to a simple gin and tonic.",
    metaTitle: "Bombay Bramble Gin Guide | BevOry", metaDescription: "Explore Bombay Bramble's blackberry and raspberry profile, serving ideas, pairings and city prices on BevOry.",
  },
  "by-ott": {
    description: "BY.OTT is a Cotes de Provence rose from Domaines Ott in southern France. Its blend draws on Grenache, Cinsault, Syrah, Mourvedre and Rolle for pale colour and fresh fruit.",
    story: "Domaines Ott traces its Provence wine estates to Marcel Ott's early twentieth-century work in the region. BY.OTT was created as an approachable expression of the house's rose style.",
    tastingNotes: [{ title: "Nose", description: "Red berries and yellow fruit lead the aroma." }, { title: "Finish", description: "Fresh acidity and a light mineral edge keep the finish crisp." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill, then pour into a medium white-wine glass." }, { subheading: "Food", description: "The dry style suits tandoori prawns or a tomato-and-olive salad." }],
    pairingIdeas: [{ title: "Provence table", items: ["tandoori prawns", "tomato-and-olive salad", "grilled sea bass", "paneer skewers"] }],
    whyChoose: "A dry Provence rose with enough acidity to stay lively beside food.",
    faqs: [{ question: "Where is BY.OTT rose made?", answer: "It is a Cotes de Provence rose from Domaines Ott in southern France." }, { question: "Is BY.OTT rose sweet?", answer: "It is made in a dry Provence rose style." }],
    finalVerdict: "BY.OTT is at its best cold, with seafood or a sunny lunch.",
    metaTitle: "BY.OTT Rose Wine Guide | BevOry", metaDescription: "Read about BY.OTT Provence rose, its fruit profile, seafood pairings and city prices on BevOry.",
  },
  "cavino-romios": {
    description: "Romios is a Greek ouzo from Cavino, made in a distinctly anise-led style. The range belongs to Greece's long tradition of aromatic aperitif spirits.",
    story: "Cavino is a Greek drinks producer with roots in the Peloponnese. Romios draws on the country's ouzo custom, where anise scent and a slow aperitif pour matter as much as strength.",
    tastingNotes: [{ title: "Aroma", description: "Anise is clear, with a herbal edge." }, { title: "Palate", description: "A soft, liquorice-like sweetness follows the aromatic opening." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve in a small glass with cold water and ice alongside." }, { subheading: "Food", description: "Pour with grilled calamari, masala peanuts or lemony prawns." }],
    pairingIdeas: [{ title: "With ouzo", items: ["grilled calamari", "masala peanuts", "lemony prawns", "olives"] }],
    whyChoose: "A Greek anise spirit made for a slow, savoury aperitif.",
    faqs: [{ question: "What type of drink is Romios?", answer: "Romios is an ouzo made by Greek producer Cavino." }, { question: "How is ouzo served?", answer: "A small pour with cold water and ice is a traditional way to enjoy it." }],
    finalVerdict: "Romios makes sense beside salty seafood and unhurried conversation.",
    metaTitle: "Cavino Romios Ouzo Guide | BevOry", metaDescription: "Discover Romios ouzo's anise profile, aperitif serving ideas, food pairings and city prices on BevOry.",
  },
  "domaine-hamelin": {
    description: "Domaine Hamelin is a family wine estate in Lignorelles, in Burgundy's Chablis area. Its Chablis wines use Chardonnay rather than the red grapes suggested by some catalogue labels.",
    story: "The Hamelin family farms vineyards around Lignorelles, north of the town of Chablis. The village's cool climate and limestone-rich soils shape its brisk white wines.",
    tastingNotes: [{ title: "Citrus", description: "Lemon and green apple bring a clean, bright opening." }, { title: "Texture", description: "The finish is lean and mineral rather than heavy." }],
    howToEnjoy: [{ subheading: "Serve", description: "Serve cool in a white-wine glass; avoid over-chilling the aromas away." }, { subheading: "Food", description: "Match with tandoori fish or oysters with lemon." }],
    pairingIdeas: [{ title: "Chablis pairings", items: ["tandoori fish", "oysters with lemon", "goat-cheese toast", "grilled prawns"] }],
    whyChoose: "Chablis Chardonnay with a fresh, limestone-shaped profile.",
    faqs: [{ question: "Where is Domaine Hamelin?", answer: "The estate is based in Lignorelles in the Chablis area of Burgundy, France." }, { question: "Which grape is used for Chablis?", answer: "Chablis is made from Chardonnay." }],
    finalVerdict: "Domaine Hamelin suits seafood when you want acidity ahead of oak.",
    metaTitle: "Domaine Hamelin Chablis Guide | BevOry", metaDescription: "Explore Domaine Hamelin Chablis, Chardonnay tasting notes, seafood pairings and city prices on BevOry.",
  },
  "hakutsuru-tojikan": {
    description: "Hakutsuru Toji-Kan is a junmai sake from Hakutsuru, the Kobe-based Japanese brewer. It is associated with toji Masao Nakazawa's approach to a balanced, food-friendly sake.",
    story: "Hakutsuru grew in Kobe's Nada brewing district, where access to water, rice and coastal trade shaped the area's sake houses. Toji-Kan puts the brewmaster's craft at the centre of the bottle.",
    tastingNotes: [{ title: "Aroma", description: "A gentle grain aroma sits beside a light fruit note." }, { title: "Palate", description: "Soft rice character and savoury depth lead to a clean finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try it chilled in a small sake cup or wine glass." }, { subheading: "Food", description: "Serve with yakitori, tandoori mushrooms or steamed fish." }],
    pairingIdeas: [{ title: "Sake and supper", items: ["yakitori", "tandoori mushrooms", "steamed fish", "salted edamame"] }],
    whyChoose: "A junmai sake whose savoury balance is built for the table.",
    faqs: [{ question: "Who makes Toji-Kan sake?", answer: "Hakutsuru makes Toji-Kan in Japan's Kobe area." }, { question: "What does junmai mean?", answer: "Junmai is a sake category made from rice, water, koji and yeast without added brewer's alcohol." }],
    finalVerdict: "Toji-Kan is a quiet companion to grilled and steamed dishes.",
    metaTitle: "Hakutsuru Toji-Kan Sake Guide | BevOry", metaDescription: "Discover Hakutsuru Toji-Kan junmai sake, serving ideas, Japanese and Indian pairings, and city prices on BevOry.",
  },
  "hana-kizakura": {
    description: "Hana Kizakura is a junmai ginjo sake made by Kizakura in Kyoto's Fushimi brewing district. The brewer uses yeast isolated from yellow cherry blossoms to give it a floral, fruit-led character.",
    story: "Fushimi's sake tradition grew around its soft local water. Kizakura's use of yellow cherry blossom yeast gives Hana Kizakura a name and aroma tied directly to the brewer's Kyoto identity.",
    tastingNotes: [{ title: "Aroma", description: "Flowers and ripe fruit lead the nose." }, { title: "Finish", description: "A soft sweetness eases into a clean sake finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill gently and pour into a small wine glass." }, { subheading: "Food", description: "Try with prawn tempura or lightly spiced paneer tikka." }],
    pairingIdeas: [{ title: "Delicate plates", items: ["prawn tempura", "paneer tikka", "sushi", "salted edamame"] }],
    whyChoose: "A Kyoto sake with a floral yeast story you can smell in the glass.",
    faqs: [{ question: "Where is Hana Kizakura made?", answer: "Kizakura makes it in the Fushimi district of Kyoto, Japan." }, { question: "Why is Hana Kizakura floral?", answer: "Kizakura uses yeast isolated from yellow cherry blossoms." }],
    finalVerdict: "Hana Kizakura rewards a cool pour and delicately seasoned food.",
    metaTitle: "Hana Kizakura Sake Guide | BevOry", metaDescription: "Explore Hana Kizakura's floral junmai ginjo style, serving tips, food pairings and city prices on BevOry.",
  },
  "l-angoor-by-big-banyan-wines": {
    description: "L'Angoor is an Indian wine label from Big Banyan Wines. Its White blends Chenin Blanc, Sauvignon Blanc and Chardonnay into a fruit-forward, unoaked style.",
    story: "Big Banyan Wines built L'Angoor as an accessible part of its Indian wine range. The white wine's stainless-steel fermentation keeps the fruit in focus rather than the flavour of wood.",
    tastingNotes: [{ title: "Fruit", description: "Passionfruit and other tropical fruit carry the aroma." }, { title: "Finish", description: "Citrus freshness makes the finish light and easy to return to." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the White and use a simple white-wine glass." }, { subheading: "Food", description: "Pour beside dhokla, dahi puri or grilled fish." }],
    pairingIdeas: [{ title: "Fresh, tangy food", items: ["dhokla", "dahi puri", "grilled fish", "herb paneer tikka"] }],
    whyChoose: "An Indian white blend with lively tropical fruit and no oak weight.",
    faqs: [{ question: "Who makes L'Angoor wine?", answer: "Big Banyan Wines makes L'Angoor." }, { question: "Which grapes are in L'Angoor White?", answer: "Its White combines Chenin Blanc, Sauvignon Blanc and Chardonnay." }],
    finalVerdict: "L'Angoor White fits best with tangy snacks and a well-chilled glass.",
    metaTitle: "L'Angoor Wine Guide | BevOry", metaDescription: "Discover L'Angoor White's Indian grape blend, tropical tasting notes, snack pairings and city prices on BevOry.",
  },
  "man-vintners": {
    description: "MAN Vintners makes South African wines from the Cape's varied growing areas. Its Padstal Chardonnay draws fruit from the Cape Coast and Agter-Paarl for a ripe, lightly rounded white.",
    story: "The label's name comes from the initials of the founders' wives. MAN works with Cape growers to make wines that put regional fruit ahead of elaborate cellar treatment.",
    tastingNotes: [{ title: "Fruit", description: "Pineapple and citrus show through the Chardonnay." }, { title: "Roundness", description: "A little oak adds a soft butterscotch edge without losing freshness." }],
    howToEnjoy: [{ subheading: "Serve", description: "Serve the Chardonnay cool in a medium white-wine glass." }, { subheading: "Food", description: "Match with butter chicken or roast cauliflower." }],
    pairingIdeas: [{ title: "For ripe Chardonnay", items: ["butter chicken", "roast cauliflower", "grilled prawns", "corn fritters"] }],
    whyChoose: "Cape Chardonnay that balances ripe fruit with a little creaminess.",
    faqs: [{ question: "Where does MAN Vintners make wine?", answer: "MAN Vintners works in South Africa's Western Cape." }, { question: "What is Padstal Chardonnay like?", answer: "It is a ripe Chardonnay with tropical fruit and a lightly rounded finish." }],
    finalVerdict: "Padstal Chardonnay handles richer dishes without feeling heavy.",
    metaTitle: "MAN Vintners Wine Guide | BevOry", metaDescription: "Read about MAN Vintners' Cape Chardonnay, tasting notes, Indian food pairings and city prices on BevOry.",
  },
  "mirabeau-classic-cotes": {
    description: "Mirabeau Classic is a Cotes de Provence rose from Maison Mirabeau. Grenache, Cinsault and Syrah form the core of this pale, dry wine.",
    story: "Stephen and Jeany Cronk moved to Provence and founded Mirabeau around the region's rose wines. Classic is the house's direct take on a chilled, food-friendly Provence pour.",
    tastingNotes: [{ title: "Nose", description: "Red currant and soft stone fruit sit above a floral note." }, { title: "Palate", description: "Fresh acidity and a light peppery edge keep the fruit sharp." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill and pour into a white-wine glass." }, { subheading: "Food", description: "Try with tandoori prawns or a tomato salad." }],
    pairingIdeas: [{ title: "Rose lunch", items: ["tandoori prawns", "tomato salad", "grilled fish", "feta and olives"] }],
    whyChoose: "A Provence rose with fresh red fruit and a dry finish.",
    faqs: [{ question: "What kind of wine is Mirabeau Classic?", answer: "It is a dry rose from Cotes de Provence, France." }, { question: "Which grapes are used in Mirabeau Classic?", answer: "Grenache, Cinsault and Syrah are central to the blend." }],
    finalVerdict: "Mirabeau Classic makes a light, refreshing match for seafood.",
    metaTitle: "Mirabeau Classic Rose Guide | BevOry", metaDescription: "Explore Mirabeau Classic Provence rose, red-fruit notes, serving tips, pairings and city prices on BevOry.",
  },
  "montes-reserva": {
    description: "Montes Reserva is a Chilean wine range from Montes. Its Merlot bottling brings the grape's soft red-fruit character to the producer's accessible Reserva tier.",
    story: "Aurelio Montes and his partners established Montes in Chile to make wines with a clear sense of vineyard origin. Reserva gives drinkers a route into that style through familiar varieties such as Merlot.",
    tastingNotes: [{ title: "Fruit", description: "Plum and red berries lead the Merlot's aroma." }, { title: "Finish", description: "Soft tannins leave a smooth, gently savoury close." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve the Merlot slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try it with seekh kebabs or mushroom pulao." }],
    pairingIdeas: [{ title: "For Merlot", items: ["seekh kebabs", "mushroom pulao", "roast chicken", "aged cheddar"] }],
    whyChoose: "A Chilean Merlot with generous fruit and approachable tannins.",
    faqs: [{ question: "Who makes Montes Reserva?", answer: "Montes, the Chilean wine producer, makes the Reserva range." }, { question: "Is Montes Reserva only Merlot?", answer: "No. Reserva includes several grape varieties; the Merlot is one expression." }],
    finalVerdict: "Montes Reserva Merlot works well when dinner calls for a softer red.",
    metaTitle: "Montes Reserva Wine Guide | BevOry", metaDescription: "Discover Montes Reserva's Chilean Merlot, tasting notes, dinner pairings and city prices on BevOry.",
  },
  naked: {
    description: "Naked Malt is a blended malt Scotch whisky built around sherry-cask influence. Its approachable dried-fruit character is aimed as much at mixing as at sipping.",
    story: "Naked Malt was previously known as Naked Grouse. The change brought the whisky's blended-malt identity and sherry-led style to the front of the label.",
    tastingNotes: [{ title: "Nose", description: "Dried fruit and soft spice lead the aroma." }, { title: "Palate", description: "Sweet malt and a rounded sherry-cask note give way to a warm finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try a short pour over ice or lengthen it with soda in a highball." }, { subheading: "Food", description: "Match with mutton seekh or dark chocolate." }],
    pairingIdeas: [{ title: "With malt whisky", items: ["mutton seekh", "dark chocolate", "salted almonds", "smoked cheese"] }],
    whyChoose: "A sherry-led Scotch malt that stays friendly in a highball.",
    faqs: [{ question: "Is Naked Malt a single malt?", answer: "No. Naked Malt is a blended malt Scotch whisky." }, { question: "What was Naked Malt called before?", answer: "The whisky was formerly sold as Naked Grouse." }],
    finalVerdict: "Naked Malt brings dried-fruit warmth without demanding a formal serve.",
    metaTitle: "Naked Malt Whisky Guide | BevOry", metaDescription: "Explore Naked Malt's sherry-led Scotch style, highball ideas, food pairings and city prices on BevOry.",
  },
  "old-monk-amber": {
    description: "Old Monk Amber is a rum in Mohan Meakin's Old Monk range from India. It sits alongside the brand's better-known dark rum labels as a distinct Amber expression.",
    story: "Mohan Meakin's brewing and distilling history reaches back to the nineteenth century in India. Old Monk became one of the country's most recognisable rum names, with Amber extending the family beyond the classic bottle.",
    tastingNotes: [{ title: "Aroma", description: "A mellow rum sweetness leads the opening." }, { title: "Finish", description: "A warm, rounded finish suits a slow pour." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve over ice or with cola and a squeeze of lime." }, { subheading: "Food", description: "Try it beside spiced peanuts or chilli paneer." }],
    pairingIdeas: [{ title: "Rum snacks", items: ["spiced peanuts", "chilli paneer", "tandoori chicken", "dark chocolate"] }],
    whyChoose: "An Old Monk label for drinkers who want a different rum from the familiar classic.",
    faqs: [{ question: "Who makes Old Monk Amber?", answer: "Mohan Meakin makes Old Monk Amber." }, { question: "Is Old Monk Amber the classic Old Monk rum?", answer: "No. Amber is a separate expression in the Old Monk range." }],
    finalVerdict: "Old Monk Amber is an easy rum to pair with salty, spiced snacks.",
    metaTitle: "Old Monk Amber Rum Guide | BevOry", metaDescription: "Discover Old Monk Amber rum, simple serving ideas, Indian snack pairings and city prices on BevOry.",
  },
  orendain: {
    description: "Orendain is a tequila producer based in Jalisco, Mexico. Its range includes clear Blanco and oak-rested Reposado expressions made from blue agave.",
    story: "The Orendain family is part of Jalisco's tequila-making history. Its distillery links the family name to a region where blue agave is both crop and cultural marker.",
    tastingNotes: [{ title: "Blanco", description: "Fresh agave character is the point of a clear, unaged pour." }, { title: "Reposado", description: "Time in wood softens the agave with gentle oak warmth." }],
    howToEnjoy: [{ subheading: "Glass", description: "Sip Blanco in a small tequila glass or use it in a lime-led Paloma." }, { subheading: "Food", description: "Serve with grilled corn or smoky paneer tacos." }],
    pairingIdeas: [{ title: "Agave at the table", items: ["grilled corn", "smoky paneer tacos", "chilli-lime prawns", "guacamole"] }],
    whyChoose: "A Jalisco tequila house with both bright and oak-rested styles.",
    faqs: [{ question: "Where is Orendain tequila from?", answer: "Orendain is based in Jalisco, Mexico." }, { question: "What is the difference between Blanco and Reposado?", answer: "Blanco is clear and unaged; Reposado spends time in oak." }],
    finalVerdict: "Orendain gives agave drinkers a choice between fresh and oak-softened pours.",
    metaTitle: "Orendain Tequila Guide | BevOry", metaDescription: "Explore Orendain's Jalisco Blanco and Reposado tequila, serving ideas, pairings and city prices on BevOry.",
  },
  "petalo-amore": {
    description: "Petalo Il Vino dell'Amore is Bottega's sweet Moscato sparkling wine from Italy. Its floral scent and soft bubbles put it firmly in the dessert-wine camp.",
    story: "Bottega developed Petalo around Moscato's naturally aromatic grape character. The wine's rose-themed presentation mirrors the flower notes that make Moscato distinctive.",
    tastingNotes: [{ title: "Aroma", description: "Rose, peach and apricot rise above the glass." }, { title: "Palate", description: "Gentle bubbles carry a sweet, fragrant finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Serve well chilled in a tulip glass." }, { subheading: "Food", description: "Pair with rasmalai, fruit tart or almond biscuits." }],
    pairingIdeas: [{ title: "For dessert", items: ["rasmalai", "fruit tart", "almond biscuits", "fresh peaches"] }],
    whyChoose: "A flower-scented Moscato when dessert calls for bubbles.",
    faqs: [{ question: "Is Petalo Il Vino dell'Amore sweet?", answer: "Yes. It is a sweet Moscato sparkling wine." }, { question: "Who makes Petalo wine?", answer: "Italian producer Bottega makes Petalo." }],
    finalVerdict: "Petalo works best cold, beside fruit or a creamy dessert.",
    metaTitle: "Petalo Moscato Wine Guide | BevOry", metaDescription: "Explore Bottega Petalo Moscato's rose and peach notes, dessert pairings and city prices on BevOry.",
  },
  "pian-delle": {
    description: "Pian delle Vigne is Marchesi Antinori's Brunello di Montalcino estate in Tuscany. Its Brunello is made from Sangiovese grown around Montalcino.",
    story: "Antinori acquired Pian delle Vigne in the 1990s and named the estate after a railway station on the property. The vineyards place the family in one of Italy's most recognised Sangiovese appellations.",
    tastingNotes: [{ title: "Fruit", description: "Cherry and darker red fruit form the centre of the wine." }, { title: "Structure", description: "Firm tannins and savoury spice give it length." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a generous red-wine glass; a young vintage benefits from air." }, { subheading: "Food", description: "Bring it to mutton rogan josh or porcini risotto." }],
    pairingIdeas: [{ title: "For Brunello", items: ["mutton rogan josh", "porcini risotto", "grilled lamb chops", "aged pecorino"] }],
    whyChoose: "Antinori's estate-grown take on Brunello's powerful Sangiovese style.",
    faqs: [{ question: "Who owns Pian delle Vigne?", answer: "Pian delle Vigne is an estate of Marchesi Antinori." }, { question: "Which grape makes Pian delle Vigne Brunello?", answer: "The Brunello is made from Sangiovese." }],
    finalVerdict: "Pian delle Vigne calls for a proper meal and time in the glass.",
    metaTitle: "Pian delle Vigne Wine Guide | BevOry", metaDescription: "Read about Antinori's Pian delle Vigne Brunello, Sangiovese notes, food pairings and city prices on BevOry.",
  },
  produttori: {
    description: "Produttori del Barbaresco is a grower cooperative in Piedmont, Italy, focused on Nebbiolo. Its wines range from Langhe Nebbiolo to Barbaresco and vineyard-designated Riserva releases.",
    story: "Nineteen growers founded the cooperative in 1958 to keep Barbaresco's Nebbiolo in local hands. The members' vineyards have since made it a defining name in the appellation.",
    tastingNotes: [{ title: "Langhe Nebbiolo", description: "Red cherry and rose meet a savoury, gently tannic edge." }, { title: "Barbaresco", description: "The fruit grows deeper and the tannins firmer, with a long herbal finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a broad red-wine glass; let Barbaresco open with air." }, { subheading: "Food", description: "Try with mushroom pulao or slow-cooked lamb." }],
    pairingIdeas: [{ title: "With Nebbiolo", items: ["mushroom pulao", "slow-cooked lamb", "truffle pasta", "aged parmesan"] }],
    whyChoose: "Grower-made Nebbiolo with a direct connection to Barbaresco's vineyards.",
    faqs: [{ question: "Is Produttori del Barbaresco a winery or a cooperative?", answer: "It is a cooperative owned by grape growers in Barbaresco." }, { question: "Which grape does Produttori del Barbaresco use?", answer: "Its red wines are made from Nebbiolo." }],
    finalVerdict: "Produttori del Barbaresco is a rewarding way into Nebbiolo's perfume and grip.",
    metaTitle: "Produttori del Barbaresco Guide | BevOry", metaDescription: "Discover Produttori del Barbaresco Nebbiolo, tasting notes, food pairings and city prices on BevOry.",
  },
  "rampur-1943-virasat": {
    description: "Rampur 1943 Virasat is an Indian single malt whisky from Radico Khaitan. Made from six-row Indian barley in Uttar Pradesh, it matures in bourbon barrels before a ruby port-pipe finish.",
    story: "Radico Khaitan began its distilling story at Rampur in 1943. Virasat, introduced in 2025, uses that date to connect a new single malt with the distillery's past.",
    tastingNotes: [{ title: "Nose", description: "Vanilla, caramel and toasted oak open the whisky." }, { title: "Finish", description: "Tropical fruit gives way to red berries, stewed fruit and soft spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Start neat in a tulip glass, then add a few drops of water if you like." }, { subheading: "Food", description: "Pair with tandoori mushrooms or salted almonds." }],
    pairingIdeas: [{ title: "Malt pairings", items: ["tandoori mushrooms", "salted almonds", "galouti kebabs", "dark chocolate"] }],
    whyChoose: "A Rampur single malt that carries the distillery's founding date on its label.",
    faqs: [{ question: "Who makes Rampur 1943 Virasat?", answer: "Radico Khaitan makes it at its Rampur distillery in Uttar Pradesh." }, { question: "Is Rampur 1943 Virasat a single malt?", answer: "Yes. It is an Indian single malt whisky." }],
    finalVerdict: "Virasat is a measured pour for drinkers curious about Indian single malt.",
    metaTitle: "Rampur 1943 Virasat Whisky Guide | BevOry", metaDescription: "Explore Rampur 1943 Virasat single malt, serving ideas, Indian pairings and city prices on BevOry.",
  },
  "red-breast": {
    description: "Redbreast is an Irish single pot still whiskey made at Midleton Distillery in County Cork. Its signature 12 Year Old combines malted and unmalted barley and matures in bourbon and sherry casks.",
    story: "Redbreast's name appeared in the early twentieth century through W&A Gilbey's whiskey bottlings. The label survived the decline of single pot still whiskey and became one of the style's best-known names.",
    tastingNotes: [{ title: "Nose", description: "Dried fruit, toasted wood and baking spice come forward." }, { title: "Palate", description: "A creamy texture carries fruit, nuts and a long spicy close." }],
    howToEnjoy: [{ subheading: "Pour", description: "Sip neat in a small tulip glass; add a drop of water to open the aroma." }, { subheading: "Food", description: "Try with galouti kebabs or pecan pie." }],
    pairingIdeas: [{ title: "With pot still whiskey", items: ["galouti kebabs", "pecan pie", "roasted almonds", "aged cheddar"] }],
    whyChoose: "An Irish pot still whiskey with sherry depth and a creamy texture.",
    faqs: [{ question: "Where is Redbreast whiskey made?", answer: "It is made at Midleton Distillery in County Cork, Ireland." }, { question: "What is in single pot still whiskey?", answer: "The style uses both malted and unmalted barley in a single distillery." }],
    finalVerdict: "Redbreast 12 is worth slowing down for after dinner.",
    metaTitle: "Redbreast Whiskey Guide | BevOry", metaDescription: "Read about Redbreast Irish pot still whiskey, sherry-cask notes, pairings and city prices on BevOry.",
  },
  "reserva-de-la-familia": {
    description: "Reserva de la Familia is Jose Cuervo's premium tequila family from Jalisco, Mexico. The line includes clear Platino and oak-aged Extra Anejo, both centred on blue Weber agave.",
    story: "Jose Cuervo introduced Reserva de la Familia as a higher-end expression of its tequila heritage. The Extra Anejo's presentation draws on the family's long association with tequila in Jalisco.",
    tastingNotes: [{ title: "Platino", description: "Fresh agave and citrus give the clear tequila its lift." }, { title: "Extra Anejo", description: "Oak ageing adds vanilla, spice and a deeper finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Sip Platino cool or pour Extra Anejo neat in a small glass." }, { subheading: "Food", description: "Pair with chilli-lime prawns or dark chocolate." }],
    pairingIdeas: [{ title: "Agave pairings", items: ["chilli-lime prawns", "mushroom tacos", "dark chocolate", "grilled corn"] }],
    whyChoose: "A Jose Cuervo range that shows agave both fresh and shaped by oak.",
    faqs: [{ question: "Who makes Reserva de la Familia?", answer: "Jose Cuervo makes the Reserva de la Familia tequila line." }, { question: "Is Reserva de la Familia aged?", answer: "The range includes both clear Platino and oak-aged Extra Anejo expressions." }],
    finalVerdict: "The contrast between Platino and Extra Anejo is the reason to explore this range.",
    metaTitle: "Reserva de la Familia Guide | BevOry", metaDescription: "Compare Reserva de la Familia Platino and Extra Anejo, serving ideas, pairings and city prices on BevOry.",
  },
  "saint-esprit": {
    description: "Saint-Esprit is a Cotes du Rhone red wine from Delas in France's Rhone Valley. Grenache and Syrah lead the blend, with Mourvedre adding structure.",
    story: "Delas has worked in the Rhone Valley since the nineteenth century. Saint-Esprit brings the broad southern Rhone blend into an everyday red built for food.",
    tastingNotes: [{ title: "Fruit", description: "Dark berries and ripe plum open the wine." }, { title: "Spice", description: "Pepper and soft tannins give the finish shape." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour slightly cool into a medium red-wine glass." }, { subheading: "Food", description: "Try it with mutton seekh or a tomato-rich aubergine dish." }],
    pairingIdeas: [{ title: "Southern Rhone table", items: ["mutton seekh", "aubergine in tomato sauce", "roast chicken", "aged cheddar"] }],
    whyChoose: "A fruit-and-spice Cotes du Rhone built around a classic southern blend.",
    faqs: [{ question: "Who makes Saint-Esprit wine?", answer: "Delas makes Saint-Esprit in France's Rhone Valley." }, { question: "What grapes are in Saint-Esprit?", answer: "Grenache, Syrah and Mourvedre make up the red blend." }],
    finalVerdict: "Saint-Esprit makes a dependable red for grilled, savoury food.",
    metaTitle: "Saint-Esprit Wine Guide | BevOry", metaDescription: "Explore Delas Saint-Esprit Cotes du Rhone, grape blend, food pairings and city prices on BevOry.",
  },
  scaia: {
    description: "Scaia is a wine range from Tenuta Sant'Antonio in Italy's Veneto region. It includes white, rose and red expressions rather than one fixed grape or flavour.",
    story: "The Castagnedi family built Tenuta Sant'Antonio near Verona. Scaia gives the family room to work with varieties such as Garganega, Chardonnay and Corvina outside its more traditional Amarone labels.",
    tastingNotes: [{ title: "White", description: "The white styles bring citrus and floral freshness." }, { title: "Red", description: "Corvina-led reds lean toward cherry fruit and a savoury finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the whites; give the reds a medium glass and a slight coolness." }, { subheading: "Food", description: "Pair white Scaia with tandoori fish and red Scaia with mushroom pizza." }],
    pairingIdeas: [{ title: "Across the range", items: ["tandoori fish", "mushroom pizza", "grilled vegetables", "tomato pasta"] }],
    whyChoose: "A Veneto range that shows the Castagnedi family's lighter, flexible side.",
    faqs: [{ question: "Who makes Scaia wine?", answer: "Tenuta Sant'Antonio, owned by the Castagnedi family, makes Scaia." }, { question: "Is Scaia only a red wine?", answer: "No. Scaia includes white, rose and red wines." }],
    finalVerdict: "Scaia is most rewarding when the colour matches the meal.",
    metaTitle: "Scaia Wine Guide | BevOry", metaDescription: "Discover Tenuta Sant'Antonio's Scaia wines, tasting styles, Italian and Indian pairings, and city prices on BevOry.",
  },
  siepi: {
    description: "Siepi is a Tuscan red from the Mazzei family, grown at their Castellina in Chianti estate. The wine combines Sangiovese with Merlot.",
    story: "Siepi is the name of a Mazzei vineyard documented in the family's estate history since the fifteenth century. Merlot plantings in the 1980s gave the site the two-grape identity of the modern wine.",
    tastingNotes: [{ title: "Fruit", description: "Black cherry and plum make a concentrated opening." }, { title: "Structure", description: "Sangiovese freshness holds the richer Merlot fruit in line." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give it air in a large red-wine glass." }, { subheading: "Food", description: "Serve with lamb chops or paneer in a smoky tomato sauce." }],
    pairingIdeas: [{ title: "For a Tuscan red", items: ["lamb chops", "smoky paneer", "wild-mushroom pasta", "aged pecorino"] }],
    whyChoose: "A single-vineyard Tuscan blend with Sangiovese tension and Merlot depth.",
    faqs: [{ question: "Who makes Siepi wine?", answer: "The Mazzei family makes Siepi at Castellina in Chianti." }, { question: "Which grapes are in Siepi?", answer: "Siepi blends Sangiovese and Merlot." }],
    finalVerdict: "Siepi deserves a full meal and a little patience in the glass.",
    metaTitle: "Siepi Tuscan Wine Guide | BevOry", metaDescription: "Explore Mazzei Siepi's Sangiovese-Merlot blend, tasting notes, rich-food pairings and city prices on BevOry.",
  },
  solaia: {
    description: "Solaia is a Tuscan red wine from Marchesi Antinori's Tignanello estate. It brings Cabernet Sauvignon, Sangiovese and Cabernet Franc together in a concentrated blend.",
    story: "Antinori first produced Solaia in 1978 from a sun-facing vineyard on the Tignanello property. The wine became one of the estate's most recognisable expressions outside conventional Chianti blends.",
    tastingNotes: [{ title: "Fruit", description: "Dark berries and black cherry lead." }, { title: "Depth", description: "Oak spice and firm tannins give the wine a long, layered finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Decant a young vintage and use a broad red-wine glass." }, { subheading: "Food", description: "Serve with slow-cooked lamb or porcini risotto." }],
    pairingIdeas: [{ title: "For Solaia", items: ["slow-cooked lamb", "porcini risotto", "mutton rogan josh", "aged parmesan"] }],
    whyChoose: "Antinori's sun-facing Tuscan blend has both Cabernet weight and Sangiovese lift.",
    faqs: [{ question: "Who makes Solaia?", answer: "Marchesi Antinori makes Solaia at its Tignanello estate in Tuscany." }, { question: "Which grapes are in Solaia?", answer: "The blend uses Cabernet Sauvignon, Sangiovese and Cabernet Franc." }],
    finalVerdict: "Solaia is a serious dinner red, not a wine to rush.",
    metaTitle: "Solaia Tuscan Wine Guide | BevOry", metaDescription: "Read about Antinori Solaia's Tuscan grape blend, tasting notes, dinner pairings and city prices on BevOry.",
  },
  somrus: {
    description: "Somrus makes cream liqueurs built around Indian-inspired flavours. Its range includes chai, mango and coffee expressions designed for sipping or mixing.",
    story: "The name combines the Hindi word for nectar with a familiar rum reference. Somrus uses dessert and tea flavours to give the cream-liqueur category a South Asian accent.",
    tastingNotes: [{ title: "Chai", description: "Tea spice gives the chai expression its warming aroma." }, { title: "Mango", description: "The mango expression leans toward ripe tropical fruit and cream." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cold over ice or add a measured pour to coffee." }, { subheading: "Food", description: "Try the chai expression with gulab jamun or the mango one with coconut cake." }],
    pairingIdeas: [{ title: "After dinner", items: ["gulab jamun", "coconut cake", "coffee ice cream", "shortbread"] }],
    whyChoose: "A cream-liqueur range that puts chai and mango beside the usual coffee notes.",
    faqs: [{ question: "What is Somrus?", answer: "Somrus is a range of cream liqueurs with flavours including chai, mango and coffee." }, { question: "How do you serve Somrus?", answer: "Serve it chilled over ice or mix a small pour into coffee." }],
    finalVerdict: "Somrus works as a cold, dessert-friendly pour after the meal.",
    metaTitle: "Somrus Cream Liqueur Guide | BevOry", metaDescription: "Explore Somrus chai, mango and coffee cream liqueurs, dessert pairings and city prices on BevOry.",
  },
  "trois-rivieres": {
    description: "Trois Rivieres makes rhum agricole from sugarcane juice in Martinique. Its range includes white and oak-aged rums under the island's AOC rules.",
    story: "The Trois Rivieres estate is part of Martinique's sugarcane landscape. Its agricole style begins with fresh cane juice rather than the molasses used for many other rums.",
    tastingNotes: [{ title: "White rum", description: "Fresh cane and a grassy edge lead the aroma." }, { title: "Aged rum", description: "Oak brings spice and a rounder finish to the cane base." }],
    howToEnjoy: [{ subheading: "Pour", description: "Use white rhum in a lime-led Ti' Punch; sip an aged expression in a small glass." }, { subheading: "Food", description: "Try with jerk chicken or chilli-lime prawns." }],
    pairingIdeas: [{ title: "Cane and spice", items: ["jerk chicken", "chilli-lime prawns", "grilled pineapple", "spiced peanuts"] }],
    whyChoose: "Martinique cane-juice rum with both lively white and rounded aged styles.",
    faqs: [{ question: "What is rhum agricole?", answer: "It is rum distilled from fresh sugarcane juice rather than molasses." }, { question: "Where is Trois Rivieres made?", answer: "Trois Rivieres makes rhum agricole in Martinique." }],
    finalVerdict: "Trois Rivieres makes the flavour of cane the point of the pour.",
    metaTitle: "Trois Rivieres Rhum Guide | BevOry", metaDescription: "Discover Trois Rivieres Martinique cane-juice rum, Ti' Punch serving ideas, pairings and city prices on BevOry.",
  },
  whitley: {
    description: "Whitley Neill is an English gin range known for fruit-led expressions alongside its London Dry. Blood Orange and Blackberry are two of its distinctive flavoured gins.",
    story: "The Whitley Neill name comes from distiller Johnny Neill's family heritage. The range uses botanical and fruit combinations to move beyond a single classic gin profile.",
    tastingNotes: [{ title: "Blood Orange", description: "Sweet citrus and orange peel sit over a juniper base." }, { title: "Blackberry", description: "Dark berry fruit brings a soft, tart edge." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use the Blood Orange gin with tonic and an orange slice; try Blackberry with soda." }, { subheading: "Food", description: "Pair the citrus gin with tandoori prawns or the berry gin with a cheese tart." }],
    pairingIdeas: [{ title: "Fruit-led gin", items: ["tandoori prawns", "cheese tart", "salted almonds", "orange-glazed chicken"] }],
    whyChoose: "A gin range with clear citrus and berry choices beyond London Dry.",
    faqs: [{ question: "Is Whitley Neill only London Dry gin?", answer: "No. The range includes Blood Orange, Blackberry and other flavoured gins." }, { question: "How should Whitley Neill Blood Orange be served?", answer: "Try it with tonic, ice and an orange slice." }],
    finalVerdict: "Whitley Neill is at its easiest in a cold, fruit-matched long drink.",
    metaTitle: "Whitley Neill Gin Guide | BevOry", metaDescription: "Explore Whitley Neill Blood Orange and Blackberry gin, tonic serves, food pairings and city prices on BevOry.",
  },
  belstar: {
    description: "Belstar is a Prosecco label associated with the Bisol family in Veneto, Italy. The sparkling wine draws on the Glera grape's fresh pear and apple character.",
    story: "Bisol's winemaking roots lie in the hills around Valdobbiadene. Belstar presents the family's sparkling-wine experience in a direct Prosecco style.",
    tastingNotes: [{ title: "Fruit", description: "Pear and green apple give the aroma its freshness." }, { title: "Bubbles", description: "Lively mousse and citrus keep the finish light." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill and pour into a tulip sparkling-wine glass." }, { subheading: "Food", description: "Try with tempura prawns or potato pakora." }],
    pairingIdeas: [{ title: "Crisp bites", items: ["tempura prawns", "potato pakora", "bruschetta", "salted cashews"] }],
    whyChoose: "An easy-drinking Prosecco for crisp snacks and aperitif pours.",
    faqs: [{ question: "What kind of wine is Belstar?", answer: "Belstar is an Italian Prosecco sparkling wine." }, { question: "Which grape is used for Prosecco?", answer: "Prosecco is made primarily from Glera." }],
    finalVerdict: "Belstar belongs at the start of a meal, cold and freshly poured.",
    metaTitle: "Belstar Prosecco Guide | BevOry", metaDescription: "Explore Belstar Prosecco's pear-and-apple style, aperitif pairings and city prices on BevOry.",
  },
  "bira-original": {
    description: "Bira 91 Original is a strong beer label from Indian brewer Bira 91. The Original Strong expression uses caramel malt for a fuller, sweeter profile than the brand's lighter beers.",
    story: "Bira 91 was launched as an Indian beer brand in 2015. Its name combines the Hindi word for brother with the country's telephone code, 91.",
    tastingNotes: [{ title: "Malt", description: "Caramel and honey notes lead the opening." }, { title: "Finish", description: "Bitterness stays low before a soft, spicy close." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill and pour into a clean beer glass." }, { subheading: "Food", description: "Set it beside chilli paneer or masala fries." }],
    pairingIdeas: [{ title: "Beer snacks", items: ["chilli paneer", "masala fries", "tandoori chicken", "salted peanuts"] }],
    whyChoose: "An Indian beer label with a straightforward, food-friendly serve.",
    faqs: [{ question: "Who makes Bira 91 Original?", answer: "Bira 91 makes it as part of its Indian beer range." }, { question: "How should Bira 91 beer be served?", answer: "Serve it chilled in a clean beer glass." }],
    finalVerdict: "Bira 91 Original is an uncomplicated match for hot snacks.",
    metaTitle: "Bira 91 Original Beer Guide | BevOry", metaDescription: "Read about Bira 91 Original beer, serving ideas, Indian snack pairings and city prices on BevOry.",
  },
  "beaune-du-chateau": {
    description: "Beaune du Chateau is a Premier Cru wine from Bouchard Pere & Fils in Burgundy. The house makes both a Pinot Noir red and a Chardonnay white under this name.",
    story: "Bouchard Pere & Fils has worked in Beaune since 1731. Beaune du Chateau gathers fruit from the town's Premier Cru vineyards into separate red and white wines.",
    tastingNotes: [{ title: "Rouge", description: "Red berries and a gentle earthy edge mark the Pinot Noir." }, { title: "Blanc", description: "The Chardonnay brings orchard fruit and a mineral finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Cool the white well; serve the red lightly chilled in a broad glass." }, { subheading: "Food", description: "Try the white with tandoori fish and the red with mushroom risotto." }],
    pairingIdeas: [{ title: "Two colours", items: ["tandoori fish", "mushroom risotto", "roast chicken", "goat cheese"] }],
    whyChoose: "A Beaune Premier Cru name with both Pinot Noir and Chardonnay expressions.",
    faqs: [{ question: "Who makes Beaune du Chateau?", answer: "Bouchard Pere & Fils makes the wine in Beaune, Burgundy." }, { question: "Is Beaune du Chateau red or white?", answer: "The house makes both Pinot Noir red and Chardonnay white versions." }],
    finalVerdict: "Choose Beaune du Chateau by colour first, then let dinner do the rest.",
    metaTitle: "Beaune du Chateau Wine Guide | BevOry", metaDescription: "Compare Beaune du Chateau red and white Burgundy, tasting notes, meal pairings and city prices on BevOry.",
  },
  "glengrant-the": {
    description: "The Glen Grant is a Speyside single malt Scotch whisky distilled in Rothes, Scotland. Its character is known for bright orchard fruit and a light, clean spirit style.",
    story: "Brothers John and James Grant founded the distillery in 1840. James 'The Major' Grant later shaped its style through tall stills and purifiers that encourage a lighter spirit.",
    tastingNotes: [{ title: "Nose", description: "Apple, pear and soft malt lead the aroma." }, { title: "Finish", description: "A clean, gently sweet close keeps the whisky brisk." }],
    howToEnjoy: [{ subheading: "Pour", description: "Sip neat in a tulip glass or add a splash of water." }, { subheading: "Food", description: "Try it with roasted almonds or mild paneer tikka." }],
    pairingIdeas: [{ title: "Light malt pairings", items: ["roasted almonds", "paneer tikka", "apple tart", "smoked cheese"] }],
    whyChoose: "A Speyside malt for drinkers who prefer fruit and clarity over heavy smoke.",
    faqs: [{ question: "Where is The Glen Grant distilled?", answer: "It is distilled in Rothes in Scotland's Speyside region." }, { question: "What shapes The Glen Grant's lighter style?", answer: "Its tall stills and purifiers contribute to a lighter spirit." }],
    finalVerdict: "The Glen Grant is an inviting Speyside pour for a quiet first glass.",
    metaTitle: "The Glen Grant Whisky Guide | BevOry", metaDescription: "Discover The Glen Grant's Speyside style, orchard-fruit notes, pairings and city prices on BevOry.",
  },
};
