import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_33 = [
  ["passport", "Passport", "Scotland", "Blended Scotch Whisky", "cbc471ca60092bbe6c631f02"],
  ["paul-jaboulet-aine", "Paul Jaboulet Aine", "France", "Wine", "db450e0dafb79f41e7c528b1"],
  ["perdeberg", "Perdeberg", "South Africa", "Wine", "e2f5d7a420baadd736b73a4c"],
  ["periquita", "Periquita", "Portugal", "Wine", "0f1ba877c3d6bd8a2c3623b3"],
  ["perlino", "Perlino", "Italy", "Vermouth and Wine", "52b9cd6a8cd98bfcb2026e95"],
  ["perrin", "Famille Perrin", "France", "Wine", "7fed5d2eb677f1763acb5676"],
  ["pink-killer", "Pink Killer", "Belgium", "Beer", "bd41516fe6499af86ad131a1"],
  ["picollo-gavi", "Picollo Gavi", "Italy", "Wine", "8321e19a1dea09686c5eccf0"],
  ["pietro-rinaldi", "Pietro Rinaldi", "Italy", "Wine", "efe60e673f9d37901d421367"],
  ["pink-47", "Pink 47", "United Kingdom", "Gin", "8e0c4f0fc46e274ddf12b5f5"],
  ["pipa-rum-de-goa", "Pipa Rum de Goa", "India", "Rum", "5355efd35e4ddc171bea0e10"],
  ["pisco-cuatro-gallos", "Pisco Cuatro Gallos", "Peru", "Pisco", "fbea8191353e78aa636dc81d"],
  ["pitars", "Pitars", "Italy", "Wine", "80aeae18562930ec5f3f7e44"],
  ["plantation", "Planteray (formerly Plantation)", "France", "Rum", "4708b6a9e852767bb871fc10"],
  ["portillo", "Portillo", "Argentina", "Wine", "63759651c147c1208de75faa"],
  ["portobello-road", "Portobello Road", "United Kingdom", "Gin", "25ec284cc6a12b9d8c06544f"],
  ["prunotto", "Prunotto", "Italy", "Wine", "3a44f879b29f396fe75f4602"],
  ["querciabella", "Querciabella", "Italy", "Wine", "97a368112dd7fd45049ce0f1"],
  ["quiet-man", "The Quiet Man", "Ireland", "Irish Whiskey", "53f9d7b935cb0c37244d1b4c"],
  ["reichsgraf-von-kesselstatt", "Reichsgraf von Kesselstatt", "Germany", "Wine", "e827dba93805c51c0c49b069"],
  ["reveilo", "Reveilo", "India", "Wine", "df4197f2d9b4f364caec3220"],
  ["ricossa", "Ricossa", "Italy", "Wine", "78116d100f06e9c64d9bb15d"],
  ["riunite", "Riunite", "Italy", "Wine", "25776ab854505379ae9037e6"],
  ["rock-rose", "Rock Rose", "Scotland", "Gin", "e4e73d47219c2d8c6b63fd9d"],
  ["roe-and-co", "Roe & Co", "Ireland", "Irish Whiskey", "576509a73bfa3c5818be6a02"],
  ["rooster-rojo", "Rooster Rojo", "Mexico", "Tequila", "7d2177ae3faffdaccaae7ca0"],
  ["ruffino", "Ruffino", "Italy", "Wine", "c125847736b37aaeca692d08"],
  ["russian-standard", "Russian Standard", "Russia", "Vodka", "680f867b93cdd2bcbfe8ad58"],
  ["rutini", "Rutini", "Argentina", "Wine", "903a0eef50d0b950e88bc7f7"],
  ["red-horse", "Red Horse", "Philippines", "Beer", "66c7d6a304075c6f5bdf96e7"],
] as const;

// Research provenance is deliberately separate from consumer-facing fields.
export const BRAND_SOURCES_BATCH_33: Record<string, string[]> = {
  passport: ["https://www.pernod-ricard.com/en/brands/passport-scotch"],
  "paul-jaboulet-aine": ["https://jaboulet.com/our-history/"],
  perdeberg: ["https://perdeberg.co.za/our-story/"],
  periquita: ["https://www.periquita.pt/en/the-family/"],
  perlino: ["https://www.perlino.com/en/history-wine-asti/"],
  perrin: ["https://www.familleperrin.com/en/the-family/philosophy/"],
  "pink-killer": ["https://belgianfamilybrewers.be/belgian-beers/pink-killer/"],
  "picollo-gavi": ["https://www.picolloernesto.it/"],
  "pietro-rinaldi": ["https://www.pietrorinaldi.com/en/vini/barolo-docg/"],
  "pink-47": ["https://osawhisky.co.uk/wp-content/uploads/2022/08/SEL14V1.0.pdf"],
  "pipa-rum-de-goa": ["https://www.diageoindia.com/en/brands/brand-explorer/pipa-rum-de-goa"],
  "pisco-cuatro-gallos": ["https://www.cuatrogallos.com.pe/", "https://www.cuatrogallos.com.pe/pisco-puro-nuevo/"],
  pitars: ["https://www.pitars.it/"],
  plantation: ["https://planterayrum.com/new-name/", "https://maisonferrand.com/about/who-we-are"],
  portillo: ["https://portillowines.com/", "https://www.bodegasalentein.com/es/bodega/lineas.html"],
  "portobello-road": ["https://portobelloroaddistillery.com/pages/portobello-road-gin"],
  prunotto: ["https://www.antinori.it/en/tenuta/estates-italy/prunotto-estate/"],
  querciabella: ["https://querciabella.com/history/"],
  "quiet-man": ["https://thequietmanirishwhiskey.com/", "https://new.mgpingredients.com/branded-spirits/niche-drinks"],
  "reichsgraf-von-kesselstatt": ["https://en.kesselstatt.de/history"],
  reveilo: ["https://reveilo.com/"],
  ricossa: ["https://www.ricossa.wine/en/our-wines/"],
  riunite: ["https://www.riunite.com/our-story/"],
  "rock-rose": ["https://dunnetbaydistillers.co.uk/news/caithness-life/the-unique-gin-botanicals-behind-rock-rose-gin-discover-our-highland-botanical-gin/"],
  "roe-and-co": ["https://www.roeandcowhiskey.com/our-story"],
  "rooster-rojo": ["https://roosterrojo.com/"],
  ruffino: ["https://www.ruffino.it/it/pages/about-us"],
  "russian-standard": ["https://www.spiritsanddistilling.com/dictionary/acref-9780199311132-e-174"],
  rutini: ["https://rutiniwines.com/en/history/"],
  "red-horse": ["https://www.sanmiguelbrewery.com.ph/storage/disclosure/SMB_17-A_Annual_Report_for_the_year_ending_December_31%2C_2022.pdf"],
};

export const BRAND_LOGOS_BATCH_33: Record<string, string> = {
  perdeberg: "https://perdeberg.co.za/wp-content/uploads/PW-Logo.png",
  pitars: "https://www.pitars.it/wp-content/uploads/2020/02/logo-pitars-nero.svg",
  "pietro-rinaldi": "https://www.pietrorinaldi.com/wp-content/uploads/2019/02/pietrorinaldi-logo-2019.png",
  querciabella: "https://querciabella.com/wp-content/themes/querciabella-theme/img/logo-full.svg",
  riunite: "https://www.riunite.com/wp-content/uploads/logo-and-tag.png",
  "roe-and-co": "https://images.ctfassets.net/h07fxpgu0eby/RKjew3nzVANq9Hd2ytKbO/6582ea930d36a41ca12730c2fbee13f5/logo.svg",
  ruffino: "https://www.ruffino.it/cdn/shop/files/Ruffino_Logo-01_1_1_6531016e-c0ab-456f-959a-1a56f85df200.png",
};

export const BRAND_CONTENT_BATCH_33: Record<string, BrandPublicContent> = {
  passport: {
    description: "Passport is a blended Scotch whisky in Pernod Ricard's portfolio. Its roots lie in Scotland's Glen Keith distillery and the more open, fruit-led blended-whisky style of the 1960s.",
    story: "The brand began in the 1960s, when Scotch blenders were making lighter styles for a new generation of drinkers. Glen Keith, in Speyside, remains part of the story told by its owner.",
    tastingNotes: [{ title: "Fruit", description: "Soft orchard-fruit sweetness is the first impression of Passport Original." }, { title: "Finish", description: "A creamy, rounded finish follows the fruit rather than a heavy smoke note." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try a small pour over ice or lengthen it with chilled soda." }, { subheading: "Food", description: "Salted almonds or chicken tikka work beside the lighter blend." }],
    pairingIdeas: [{ title: "At the table", items: ["chicken tikka", "salted almonds", "grilled corn", "mild cheddar"] }],
    whyChoose: "A fruit-led Scotch blend built for a relaxed highball rather than a smoky dram.",
    faqs: [{ question: "Is Passport a Scotch whisky?", answer: "Yes. Passport is a blended Scotch whisky." }, { question: "Who owns Passport Scotch?", answer: "It is part of Pernod Ricard's whisky portfolio." }],
    finalVerdict: "Passport works best when a Scotch highball should stay light and uncomplicated.",
    metaTitle: "Passport Scotch Whisky Guide | BevOry", metaDescription: "Explore Passport Scotch, its fruity style, simple serves and food matches. Check city prices on BevOry.",
  },
  "paul-jaboulet-aine": {
    description: "Paul Jaboulet Aine is a wine house based in Tain-l'Hermitage in France's northern Rhone Valley. Syrah from Hermitage and Crozes-Hermitage sits at the centre of its red-wine reputation.",
    story: "Antoine Jaboulet established the house in 1834. Its vineyards and cellars became closely associated with the steep hill of Hermitage above the Rhone.",
    tastingNotes: [{ title: "Northern Rhone red", description: "Black fruit and pepper frame the house's Syrah wines." }, { title: "White Rhone", description: "Its white-wine side brings a fuller, stone-fruit character." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Syrah slightly cool in a roomy red-wine glass." }, { subheading: "Food", description: "Try it with mutton seekh or aubergine cooked over charcoal." }],
    pairingIdeas: [{ title: "Rhone table", items: ["mutton seekh", "charred aubergine", "roast duck", "aged Comte"] }],
    whyChoose: "A historic northern Rhone house with direct ties to the Hermitage hillside.",
    faqs: [{ question: "Where is Paul Jaboulet Aine based?", answer: "The house is based in Tain-l'Hermitage in the northern Rhone Valley." }, { question: "Which grape shapes its red wines?", answer: "Syrah is the defining red grape in Hermitage and Crozes-Hermitage." }],
    finalVerdict: "Its Syrah is a fine place to explore the Rhone with a peppery, savoury dinner.",
    metaTitle: "Paul Jaboulet Aine Wine Guide | BevOry", metaDescription: "Meet Paul Jaboulet Aine, Hermitage Syrah and food pairings. Check city prices on BevOry.",
  },
  perdeberg: {
    description: "Perdeberg is a South African wine cellar at the foot of Paardeberg mountain near Paarl. Its Cape range includes Chenin Blanc and red blends made with fruit from local growers.",
    story: "Local farmer Jan Rossouw encouraged neighbouring growers to make their own wine, and Perdeberg Cellar began in 1941. The cooperative setting still explains the broad range of vineyards behind its bottles.",
    tastingNotes: [{ title: "Chenin Blanc", description: "Fresh orchard fruit and citrus give the white side of the range its lift." }, { title: "Cape reds", description: "Ripe berry fruit and a rounded palate suit the cellar's fuller reds." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill Chenin Blanc well; serve reds just below room temperature." }, { subheading: "Food", description: "Try Chenin with fish tikka and a red with peri-peri chicken." }],
    pairingIdeas: [{ title: "Cape table", items: ["fish tikka", "peri-peri chicken", "roasted peppers", "grilled lamb"] }],
    whyChoose: "A Paarl cellar with a genuine grower-cooperative history and several Cape styles to explore.",
    faqs: [{ question: "Where is Perdeberg wine made?", answer: "Perdeberg is based near Paarl in South Africa's Western Cape." }, { question: "When did Perdeberg Cellar begin?", answer: "The cellar dates to 1941." }],
    finalVerdict: "Perdeberg offers a useful route from brisk Cape Chenin to richer dinner reds.",
    metaTitle: "Perdeberg Wine Guide | BevOry", metaDescription: "Explore Perdeberg wines from Paarl, Chenin Blanc, red styles and pairings. Check city prices on BevOry.",
  },
  periquita: {
    description: "Periquita is a Portuguese wine label made by Jose Maria da Fonseca on the Setubal Peninsula. Its red-wine identity is closely tied to the Castelao grape.",
    story: "Jose Maria da Fonseca founded the family wine business in 1834. Periquita later became one of its best-known labels, carrying Setubal-grown Castelao to drinkers beyond Portugal.",
    tastingNotes: [{ title: "Red fruit", description: "Periquita's Castelao-based red shows cherry and plum." }, { title: "Savoury edge", description: "A light herbal note and supple tannins balance the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve the red lightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Its fruit suits chicken cafreal or grilled chorizo." }],
    pairingIdeas: [{ title: "Setubal pairings", items: ["chicken cafreal", "grilled chorizo", "mushroom rice", "roast pork"] }],
    whyChoose: "A long-running Portuguese red label that puts the Castelao grape in focus.",
    faqs: [{ question: "Who makes Periquita?", answer: "Jose Maria da Fonseca makes Periquita." }, { question: "Which grape is associated with Periquita red?", answer: "Castelao is the grape most closely associated with the label." }],
    finalVerdict: "Periquita red is an easy introduction to Setubal's Castelao tradition.",
    metaTitle: "Periquita Wine Guide | BevOry", metaDescription: "Discover Periquita, Setubal Castelao, tasting notes and dinner pairings. Check city prices on BevOry.",
  },
  perlino: {
    description: "Perlino is a Piedmontese producer of vermouth, sparkling wine and still wine near Asti. Its vermouth starts with wine and an infusion of herbs for the region's aperitivo tradition.",
    story: "Giuseppe Perlino began trading Asti wines in 1905. The family added sparkling wine and vermouth production in the 1930s, turning a wine business into an aperitivo house.",
    tastingNotes: [{ title: "Vermouth", description: "Herbal bitterness and wine sweetness give the aperitif its shape." }, { title: "Sparkling wine", description: "Perlino's bubbles bring a fresher, fruit-led side to the range." }],
    howToEnjoy: [{ subheading: "Aperitivo", description: "Pour vermouth over ice with orange peel or use it in a classic cocktail." }, { subheading: "Food", description: "Put out masala olives and fried artichokes; keep the sparkling wine chilled." }],
    pairingIdeas: [{ title: "Asti aperitivo", items: ["masala olives", "fried artichokes", "salami", "roasted almonds"] }],
    whyChoose: "Asti wine history expressed through both sparkling bottles and a proper herbal vermouth.",
    faqs: [{ question: "Where is Perlino from?", answer: "Perlino is from the Asti area of Piedmont, Italy." }, { question: "What does Perlino make besides wine?", answer: "It also makes vermouth and sparkling wine." }],
    finalVerdict: "Perlino's vermouth belongs on an aperitivo table with something salty.",
    metaTitle: "Perlino Vermouth and Wine Guide | BevOry", metaDescription: "Explore Perlino vermouth and Asti wines, serving ideas and pairings. Check city prices on BevOry.",
  },
  perrin: {
    description: "Famille Perrin is a southern Rhone wine family associated with Chateau de Beaucastel. Its wines span Chateauneuf-du-Pape, Cotes du Rhone and other Mediterranean appellations.",
    story: "The family's work at Beaucastel shaped its approach to soil and vineyard farming. It began organic cultivation in 1950 and moved the Beaucastel estate toward biodynamic practice in the 1970s.",
    tastingNotes: [{ title: "Southern Rhone red", description: "Dark fruit, herbs and spice define the fuller red side of the range." }, { title: "White Rhone", description: "Stone fruit and a round texture mark many of the whites." }],
    howToEnjoy: [{ subheading: "Pour", description: "Give a young red some air and pour it slightly cool." }, { subheading: "Food", description: "Serve with lamb rogan josh or rosemary roast chicken." }],
    pairingIdeas: [{ title: "Rhone plates", items: ["lamb rogan josh", "rosemary roast chicken", "ratatouille", "aged hard cheese"] }],
    whyChoose: "A family name connecting everyday Rhone wines with the Beaucastel vineyard tradition.",
    faqs: [{ question: "Which estate is Famille Perrin known for?", answer: "Chateau de Beaucastel in Chateauneuf-du-Pape is its best-known estate." }, { question: "Where does Famille Perrin work?", answer: "Its vineyards are concentrated in France's southern Rhone Valley." }],
    finalVerdict: "A Perrin red brings the herbal warmth of the southern Rhone to a substantial meal.",
    metaTitle: "Famille Perrin Wine Guide | BevOry", metaDescription: "Explore Famille Perrin, Beaucastel, Rhone wine styles and pairings. Check city prices on BevOry.",
  },
  "pink-killer": {
    description: "Pink Killer is a Belgian fruit beer from Brasserie de Silly. Malt, wheat and pink grapefruit give it a pale pink colour and a citrus-bitter finish.",
    story: "Brasserie de Silly is a family brewery in the village of Silly, Hainaut. Pink Killer took its established brewing tradition in a bright grapefruit direction rather than imitating a pink gin.",
    tastingNotes: [{ title: "Grapefruit", description: "Pink grapefruit is clear on the nose and through the finish." }, { title: "Malt and wheat", description: "A soft, lightly sweet body keeps the citrus bitterness in balance." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a clean beer glass with room for the head." }, { subheading: "Food", description: "Try it with chilli paneer or crispy calamari." }],
    pairingIdeas: [{ title: "Citrus and spice", items: ["chilli paneer", "crispy calamari", "fish tacos", "salted cashews"] }],
    whyChoose: "A grapefruit wheat beer with a proper Belgian brewery behind the playful colour.",
    faqs: [{ question: "Is Pink Killer a gin?", answer: "No. Pink Killer is a Belgian fruit beer." }, { question: "What gives Pink Killer its flavour?", answer: "Pink grapefruit brings the characteristic citrus note." }],
    finalVerdict: "Pink Killer is a cold, citrusy beer for spicy snacks rather than a spirit mixer.",
    metaTitle: "Pink Killer Beer Guide | BevOry", metaDescription: "Meet Pink Killer grapefruit beer, its flavour and food matches. Check city prices on BevOry.",
  },
  "picollo-gavi": {
    description: "Picollo Gavi refers to the Cortese wines of Picollo Ernesto in Rovereto di Gavi, Piedmont. The family farms 16 hectares dedicated to the white grape.",
    story: "Lorenzo Picollo founded the winery in 1945; his son Ernesto and grandson Gianlorenzo continued it. The Gavi wines are fermented and aged in stainless steel, keeping attention on Cortese fruit and acidity.",
    tastingNotes: [{ title: "Citrus", description: "Lemon and orchard-fruit notes give Gavi its clear opening." }, { title: "Finish", description: "Cortese's acidity leaves a dry, brisk finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cool in a white-wine glass, not ice cold." }, { subheading: "Food", description: "Try it beside tandoori fish or lemon risotto." }],
    pairingIdeas: [{ title: "Gavi table", items: ["tandoori fish", "lemon risotto", "grilled prawns", "herbed paneer"] }],
    whyChoose: "Family-grown Cortese from Rovereto di Gavi, made without an oak-heavy signature.",
    faqs: [{ question: "What grape is used for Picollo Gavi?", answer: "The winery's Gavi is made from Cortese." }, { question: "Where are its vineyards?", answer: "They are centred on Rovereto di Gavi in Piedmont." }],
    finalVerdict: "Picollo's Gavi makes a sharp, refreshing partner for seafood and lemon-led dishes.",
    metaTitle: "Picollo Gavi Wine Guide | BevOry", metaDescription: "Explore Picollo Ernesto Gavi, Cortese notes and seafood pairings. Check city prices on BevOry.",
  },
  "pietro-rinaldi": {
    description: "Pietro Rinaldi is a family wine estate on the hills above Alba in Piedmont's Langhe. Its range includes Nebbiolo wines from Barolo alongside other regional reds.",
    story: "The winery works from Madonna di Como above Alba. Its Barolo draws on Nebbiolo vineyards in Verduno, tying the family name to one of the Langhe's established wine villages.",
    tastingNotes: [{ title: "Nebbiolo fruit", description: "Red cherry and rose notes open the Barolo style." }, { title: "Structure", description: "Firm tannin and savoury spice make it a wine for food." }],
    howToEnjoy: [{ subheading: "Air", description: "Give a young Barolo time in a wide glass or decanter." }, { subheading: "Food", description: "Serve beside mushroom risotto or slow-cooked mutton." }],
    pairingIdeas: [{ title: "Langhe dinner", items: ["mushroom risotto", "slow-cooked mutton", "truffle pasta", "aged Parmesan"] }],
    whyChoose: "A Langhe family estate with a direct Verduno connection for its Barolo.",
    faqs: [{ question: "Where is Pietro Rinaldi based?", answer: "The estate is near Alba in Piedmont's Langhe hills." }, { question: "Which grape makes its Barolo?", answer: "Barolo is made from Nebbiolo." }],
    finalVerdict: "Its Barolo belongs at a long dinner where tannin and savoury food can meet.",
    metaTitle: "Pietro Rinaldi Wine Guide | BevOry", metaDescription: "Discover Pietro Rinaldi Barolo, Langhe history and food matches. Check city prices on BevOry.",
  },
  "pink-47": {
    description: "Pink 47 is a clear London dry gin in a diamond-shaped bottle. Its small-batch recipe uses juniper, two angelicas, two corianders, citrus, almond, nutmeg and other spices.",
    story: "The diamond bottle was designed to show the gin's clarity, despite the name suggesting a pink spirit. Four distillations and a classic botanical base put it closer to a firm London dry than a fruit-flavoured gin.",
    tastingNotes: [{ title: "Juniper", description: "Italian juniper provides the dry, piney centre." }, { title: "Citrus and spice", description: "Spanish citrus and almond meet nutmeg and warmer spice on the finish." }],
    howToEnjoy: [{ subheading: "Gin and tonic", description: "Use plenty of ice, dry tonic and a thin lemon peel." }, { subheading: "Food", description: "Try it with tandoori prawns or peppered cashews." }],
    pairingIdeas: [{ title: "With gin", items: ["tandoori prawns", "peppered cashews", "cucumber chaat", "grilled halloumi"] }],
    whyChoose: "A decidedly dry gin whose name and clear liquid tell different stories.",
    faqs: [{ question: "Is Pink 47 gin pink?", answer: "No. Pink 47 is a crystal-clear London dry gin." }, { question: "What is its main botanical?", answer: "Juniper is the foundation, joined by citrus and other spices." }],
    finalVerdict: "Pink 47 is for a crisp G&T, not a sweet pink-gin serve.",
    metaTitle: "Pink 47 Gin Guide | BevOry", metaDescription: "Explore Pink 47 London dry gin, botanicals and food pairings. Check city prices on BevOry.",
  },
  "pipa-rum-de-goa": {
    description: "Pipa Rum de Goa is a Goan spiced rum in the Diageo India portfolio. It is distilled from local jaggery, matured in Portuguese port-wine casks and finished with black pepper, cinnamon and clove.",
    story: "The rum connects Goa's jaggery distilling with the Portuguese wine-cask trade. Its choice of pepper, cinnamon and clove points to the spices that drew Portuguese traders to India's western coast.",
    tastingNotes: [{ title: "Warm spice", description: "Clove and cinnamon sit up front, with black pepper adding a dry edge." }, { title: "Cask", description: "The port-cask maturation brings a darker fruit and oak note beneath the spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try it over one large ice cube or with chilled soda." }, { subheading: "Food", description: "Goan chorizo pao and bebinca make a particularly local pairing." }],
    pairingIdeas: [{ title: "Goan table", items: ["Goan chorizo pao", "pork vindaloo", "bebinca", "roasted cashews"] }],
    whyChoose: "Jaggery, port casks and coastal spices give this Goan rum a recognisable address.",
    faqs: [{ question: "What is Pipa Rum de Goa made from?", answer: "It is distilled from local Goan jaggery." }, { question: "Which spices finish Pipa?", answer: "Black pepper, cinnamon and clove are added to the rum." }],
    finalVerdict: "Pipa makes a memorable after-dinner Goan pour alongside dessert or spiced pork.",
    metaTitle: "Pipa Rum de Goa Guide | BevOry", metaDescription: "Explore Pipa's jaggery rum, port-cask character and Goan food pairings. Check city prices on BevOry.",
  },
  "pisco-cuatro-gallos": {
    description: "Cuatro Gallos is a Peruvian pisco label from the Ica Valley. Its range includes single-grape Quebranta and the blended-grape Acholado style.",
    story: "Four brothers found an Ica vineyard planted with old Quebranta vines in the 1990s. The brand later paired its pisco-making story with a series of collaborations with Peruvian artists.",
    tastingNotes: [{ title: "Quebranta", description: "A measured grape aroma gives way to a rounded palate and a distant dried-fruit note." }, { title: "Acholado", description: "Floral and citrus aromas lead a rounder, more aromatic pour." }],
    howToEnjoy: [{ subheading: "Pisco sour", description: "Shake with fresh lime and simple syrup for a classic sour." }, { subheading: "Food", description: "Try the citrusy drink with ceviche or tandoori prawns." }],
    pairingIdeas: [{ title: "With pisco", items: ["ceviche", "tandoori prawns", "salted corn", "grilled squid"] }],
    whyChoose: "An Ica Valley pisco range that lets drinkers compare Quebranta with a blended-grape style.",
    faqs: [{ question: "Where is Cuatro Gallos from?", answer: "Its story begins with Quebranta vines in Peru's Ica Valley." }, { question: "Does it make more than one pisco style?", answer: "Yes. The range includes Quebranta and Acholado." }],
    finalVerdict: "Cuatro Gallos earns a place in a sharp pisco sour with seafood on the side.",
    metaTitle: "Cuatro Gallos Pisco Guide | BevOry", metaDescription: "Discover Cuatro Gallos pisco, Quebranta and Acholado serves and pairings. Check city prices on BevOry.",
  },
  pitars: {
    description: "Pitars is a family wine producer in the Grave del Friuli area of northeast Italy. Its vineyards near the Tagliamento river grow Friulano, Pinot Grigio, Sauvignon and Merlot.",
    story: "The Pittaro family's local vineyard history reaches back to the seventeenth century. Angelo Pittaro built the modern Cantina San Martino in 1968; it later took the family's dialect name, Pitars.",
    tastingNotes: [{ title: "Friulano", description: "Gentle blossom and almond notes give this white a recognisable Friulian finish." }, { title: "Merlot", description: "Soft plum fruit shows the family's older red-grape connection." }],
    howToEnjoy: [{ subheading: "White wine", description: "Chill Friulano lightly and use a small white-wine glass." }, { subheading: "Food", description: "Pour it with tandoori fish or asparagus risotto." }],
    pairingIdeas: [{ title: "Friuli table", items: ["tandoori fish", "asparagus risotto", "prosciutto", "grilled courgette"] }],
    whyChoose: "A Tagliamento-side family winery with native Friulian whites and a Merlot history.",
    faqs: [{ question: "Where is Pitars wine made?", answer: "The winery is in San Martino al Tagliamento in Friuli." }, { question: "What did Pitars used to be called?", answer: "The modern winery began as Cantina San Martino." }],
    finalVerdict: "Pitars Friulano is worth opening with a fish supper that needs a clean, nutty white.",
    metaTitle: "Pitars Wine Guide | BevOry", metaDescription: "Explore Pitars wines from Friuli, Friulano notes and pairings. Check city prices on BevOry.",
  },
  plantation: {
    description: "Planteray is the current name of the rum brand formerly called Plantation. Maison Ferrand blends rums from several producing regions, with many releases receiving a second maturation in France.",
    story: "Alexandre Gabriel began the rum project in 1999. Maison Ferrand later changed the name to Planteray while continuing its work with Caribbean distilleries and its double-ageing approach.",
    tastingNotes: [{ title: "Barbados style", description: "The Barbados releases tend toward soft vanilla and tropical fruit." }, { title: "Jamaican style", description: "Jamaican bottlings can bring a stronger fermented-fruit and spice character." }],
    howToEnjoy: [{ subheading: "Taste", description: "Try a neat pour before mixing; the country and cask make a difference." }, { subheading: "Food", description: "Pineapple-led releases work with jerk chicken or charred pineapple." }],
    pairingIdeas: [{ title: "Rum table", items: ["jerk chicken", "charred pineapple", "pepper prawns", "dark chocolate"] }],
    whyChoose: "A rum range where the producing region remains audible after the French finishing cask.",
    faqs: [{ question: "Is Plantation Rum now Planteray?", answer: "Yes. Maison Ferrand renamed the rum brand Planteray." }, { question: "Are all Planteray rums from one country?", answer: "No. The range brings together rums from several producing regions." }],
    finalVerdict: "Choose a Planteray bottle by origin: the styles stretch well beyond one house flavour.",
    metaTitle: "Planteray Plantation Rum Guide | BevOry", metaDescription: "Explore Planteray, formerly Plantation Rum, its origins and food matches. Check city prices on BevOry.",
  },
  portillo: {
    description: "Portillo is an Argentine wine range from Bodegas Salentein in Mendoza's Uco Valley. Malbec and Chardonnay are among its valley-grown bottles.",
    story: "The label takes its name from a historic mountain pass linking the Andes with the Uco Valley. Salentein uses the range to present the valley's fruit in approachable, single-variety wines.",
    tastingNotes: [{ title: "Malbec", description: "Plum and dark cherry sit in a supple red frame." }, { title: "Chardonnay", description: "Orchard fruit and a fresh edge make a lighter table wine." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Serve Malbec slightly cool; chill Chardonnay well." }, { subheading: "Food", description: "Put Malbec beside mutton seekh and Chardonnay beside roast chicken." }],
    pairingIdeas: [{ title: "Uco Valley dinner", items: ["mutton seekh", "roast chicken", "grilled peppers", "mushroom empanadas"] }],
    whyChoose: "Salentein's Uco Valley fruit in a straightforward Malbec-and-Chardonnay range.",
    faqs: [{ question: "Who makes Portillo wine?", answer: "Bodegas Salentein makes Portillo." }, { question: "Where are the wines from?", answer: "The range is associated with Mendoza's Uco Valley in Argentina." }],
    finalVerdict: "Portillo Malbec is a useful red for grilled, peppery food.",
    metaTitle: "Portillo Wine Guide | BevOry", metaDescription: "Explore Portillo Malbec and Chardonnay from the Uco Valley. Check city prices on BevOry.",
  },
  "portobello-road": {
    description: "Portobello Road is a London dry gin made in Notting Hill, London. Its Number 171 recipe uses nine botanicals, including juniper, citrus peels, nutmeg and cassia.",
    story: "The brand takes its name and number from 171 Portobello Road, home of its gin-making operation. Its London dry recipe keeps juniper in charge while bringing in botanicals sourced from several countries.",
    tastingNotes: [{ title: "Juniper", description: "A firm juniper opening gives the gin its classic spine." }, { title: "Citrus and spice", description: "Lemon and bitter orange lead into nutmeg and cassia." }],
    howToEnjoy: [{ subheading: "G&T", description: "Build over plenty of ice with dry tonic and a grapefruit twist." }, { subheading: "Food", description: "Pair with tandoori prawns or green-olive tapenade." }],
    pairingIdeas: [{ title: "With a G&T", items: ["tandoori prawns", "green-olive tapenade", "salted almonds", "grilled halloumi"] }],
    whyChoose: "A proper juniper-led London dry with a specific Notting Hill address.",
    faqs: [{ question: "What does 171 mean on Portobello Road gin?", answer: "It refers to the brand's address at 171 Portobello Road." }, { question: "Is it a London dry gin?", answer: "Yes. No. 171 is a London dry gin." }],
    finalVerdict: "Portobello Road Number 171 makes a crisp, spice-edged gin and tonic.",
    metaTitle: "Portobello Road Gin Guide | BevOry", metaDescription: "Discover Portobello Road No. 171 gin, botanicals and pairings. Check city prices on BevOry.",
  },
  prunotto: {
    description: "Prunotto is a Piedmont wine estate based around Alba and the Langhe. Its Barolo, Barbaresco and Barbera wines belong to the Marchesi Antinori family portfolio.",
    story: "Alfredo Prunotto took over an Alba wine cooperative in the early twentieth century. Antinori began working with the estate in 1989 and assumed production in 1994, retaining its Piedmont focus.",
    tastingNotes: [{ title: "Barolo", description: "Nebbiolo brings rose, red cherry and a firm tannic line." }, { title: "Barbera", description: "Darker cherry fruit and brisk acidity make a different Piedmont red." }],
    howToEnjoy: [{ subheading: "Air", description: "Give a young Barolo time in a broad glass." }, { subheading: "Food", description: "Choose mushroom risotto or slow-cooked lamb; Barbera suits tomato pasta." }],
    pairingIdeas: [{ title: "Piedmont plates", items: ["mushroom risotto", "slow-cooked lamb", "tomato pasta", "aged Parmesan"] }],
    whyChoose: "An Alba estate that moves confidently between Nebbiolo and Barbera.",
    faqs: [{ question: "Who owns Prunotto?", answer: "Prunotto is part of the Marchesi Antinori portfolio." }, { question: "Where is Prunotto based?", answer: "It is based in the Alba area of Piedmont, Italy." }],
    finalVerdict: "Prunotto rewards a Piedmont dinner, especially when mushrooms or slow-cooked meat are on the table.",
    metaTitle: "Prunotto Wine Guide | BevOry", metaDescription: "Explore Prunotto Barolo, Barbera and Langhe food pairings. Check city prices on BevOry.",
  },
  querciabella: {
    description: "Querciabella is a Tuscan wine estate with vineyards in Chianti Classico and Maremma. Its Chianti Classico is based on Sangiovese grown under plant-based biodynamic practices.",
    story: "Giuseppe Castiglioni founded the estate in 1974. His son Sebastiano moved it toward organic farming and, by 2000, a vegan biodynamic approach across its vineyards.",
    tastingNotes: [{ title: "Sangiovese", description: "Red cherry and dried herb notes hold a taut, savoury shape." }, { title: "Finish", description: "Fresh acidity and fine tannin keep the Chianti Classico lively with food." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try with mushroom pizza or paneer tikka in tomato gravy." }],
    pairingIdeas: [{ title: "Tuscan table", items: ["mushroom pizza", "paneer tikka in tomato gravy", "pappardelle al ragu", "roasted aubergine"] }],
    whyChoose: "Chianti Classico Sangiovese from a Tuscan estate with a long commitment to plant-based vineyard farming.",
    faqs: [{ question: "Where are Querciabella's vineyards?", answer: "They are in Chianti Classico and coastal Maremma, Tuscany." }, { question: "Which grape leads its Chianti Classico?", answer: "Sangiovese is the defining grape." }],
    finalVerdict: "Querciabella Chianti Classico is a red to put beside tomato, mushroom and herbs.",
    metaTitle: "Querciabella Wine Guide | BevOry", metaDescription: "Discover Querciabella's Tuscan Sangiovese, tasting notes and pairings. Check city prices on BevOry.",
  },
  "quiet-man": {
    description: "The Quiet Man is an Irish whiskey brand produced by Niche Drinks in Derry, Northern Ireland. Its range includes blended whiskey and single malt expressions.",
    story: "The name honours John Mulgrew, a bartender remembered by his son Ciaran for listening more than talking. That family tribute gave a Derry whiskey project its quiet identity.",
    tastingNotes: [{ title: "Blend", description: "Vanilla and orchard fruit make the blended whiskey soft on the palate." }, { title: "Malt", description: "The single malt side brings a fuller cereal and oak impression." }],
    howToEnjoy: [{ subheading: "Taste", description: "Start neat in a small tulip glass, then add a few drops of water." }, { subheading: "Food", description: "Try it with smoked almonds or apple tart." }],
    pairingIdeas: [{ title: "With Irish whiskey", items: ["smoked almonds", "apple tart", "grilled pork", "mild cheddar"] }],
    whyChoose: "A Derry whiskey with an unusually personal family story behind its name.",
    faqs: [{ question: "Where does The Quiet Man whiskey come from?", answer: "The brand is associated with Niche Drinks in Derry, Northern Ireland." }, { question: "Who inspired the name?", answer: "It honours John Mulgrew, the founder's father." }],
    finalVerdict: "A mellow Irish whiskey whose story is as understated as its name.",
    metaTitle: "The Quiet Man Whiskey Guide | BevOry", metaDescription: "Meet The Quiet Man Irish whiskey, its Derry story and food pairings. Check city prices on BevOry.",
  },
  "reichsgraf-von-kesselstatt": {
    description: "Reichsgraf von Kesselstatt is a German wine estate focused on Riesling from the Mosel, Saar and Ruwer valleys. Its vineyard sites include the celebrated Piesporter Goldtropfchen.",
    story: "The Kesselstatt name has deep roots along the Mosel. Rather than treating the three valleys as one flavour, the estate bottles Riesling from distinct slate-soil sites.",
    tastingNotes: [{ title: "Riesling fruit", description: "Citrus and green apple give the wines a precise opening." }, { title: "Mineral finish", description: "A stony line and brisk acidity carry the palate." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cool in a narrow white-wine glass." }, { subheading: "Food", description: "Try with tandoori fish or ginger-spiced prawns." }],
    pairingIdeas: [{ title: "Riesling table", items: ["tandoori fish", "ginger prawns", "pork schnitzel", "lime pickle"] }],
    whyChoose: "A Mosel estate whose Rieslings can show the difference between neighbouring river valleys.",
    faqs: [{ question: "Which grape is Reichsgraf von Kesselstatt known for?", answer: "Riesling is its signature grape." }, { question: "Where are its vineyards?", answer: "The estate works in the Mosel, Saar and Ruwer valleys." }],
    finalVerdict: "Its Riesling brings keen acidity to rich or spicy food without needing a heavy pour.",
    metaTitle: "Reichsgraf von Kesselstatt Wine Guide | BevOry", metaDescription: "Explore Kesselstatt Riesling from Mosel, Saar and Ruwer. Check city prices on BevOry.",
  },
  reveilo: {
    description: "Reveilo is an Indian wine label made by the Patil family on their Nashik estate in Maharashtra. The range covers red, white and rose wines from grapes grown in the region.",
    story: "Yatin and Kiran Patil returned to the family's Nashik farm and planted their first wine grapes in 2000. They brought in Italian winemaking know-how through a collaboration with Enofly.",
    tastingNotes: [{ title: "White wines", description: "Fresh fruit and floral notes bring a lighter side to the Nashik range." }, { title: "Red wines", description: "Ripe berry fruit and a rounder texture suit the estate's reds." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill whites and rose; let a red sit slightly cool in the glass." }, { subheading: "Food", description: "Try a white with paneer tikka and a red with mutton seekh." }],
    pairingIdeas: [{ title: "Nashik dinner", items: ["paneer tikka", "mutton seekh", "tandoori fish", "roasted peppers"] }],
    whyChoose: "A Nashik family project that made its own vineyard the starting point for the brand.",
    faqs: [{ question: "Where is Reveilo wine made?", answer: "Reveilo comes from the Patil family's Nashik estate in Maharashtra." }, { question: "When were the first vines planted?", answer: "The family planted its first wine grape varieties in 2000." }],
    finalVerdict: "Reveilo gives an Indian dinner a locally grown wine choice across several styles.",
    metaTitle: "Reveilo Wine Guide | BevOry", metaDescription: "Explore Reveilo wines from Nashik, serving ideas and Indian food matches. Check city prices on BevOry.",
  },
  ricossa: {
    description: "Ricossa is a Piedmont wine label drawing on Langhe, Roero and Monferrato vineyards. Its range includes Barbera d'Asti, Barolo and other regional wines.",
    story: "The Ricossa name began in the Asti area in the early twentieth century. A Lorenzo Ricossa line commemorates the man associated with its beginnings, while the current winery works across several Piedmont appellations.",
    tastingNotes: [{ title: "Barbera", description: "Cherry fruit and lively acidity give Barbera d'Asti its table-friendly pace." }, { title: "Barolo", description: "Nebbiolo brings rose, red fruit and firmer tannin." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Barbera slightly cool; give young Barolo more air." }, { subheading: "Food", description: "Put Barbera with tomato pasta and Barolo with mushroom risotto." }],
    pairingIdeas: [{ title: "Piedmont supper", items: ["tomato pasta", "mushroom risotto", "lamb ragout", "aged Parmesan"] }],
    whyChoose: "A Piedmont range that moves from bright Asti Barbera to structured Nebbiolo.",
    faqs: [{ question: "Where is Ricossa from?", answer: "The brand has roots in the Asti area of Piedmont, Italy." }, { question: "Does Ricossa make Barolo?", answer: "Yes. Barolo is part of its Piedmont wine range." }],
    finalVerdict: "Ricossa Barbera is the weeknight red; Barolo calls for the slower dinner.",
    metaTitle: "Ricossa Wine Guide | BevOry", metaDescription: "Explore Ricossa Barbera, Barolo and Piedmont pairings. Check city prices on BevOry.",
  },
  riunite: {
    description: "Riunite is an Italian wine cooperative from Emilia-Romagna, best known for lightly sparkling Lambrusco. Its red bubbles are fruit-led and made for chilling.",
    story: "Nine wine producers formed Cantine Riunite in 1950. The cooperative helped carry Emilia's Lambrusco beyond Italy while remaining tied to local grower families.",
    tastingNotes: [{ title: "Red fruit", description: "Cherry and berry notes lead the Lambrusco palate." }, { title: "Fizz", description: "Gentle bubbles and fresh acidity lighten the fruit." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Lambrusco cold in a wine glass with room for the bubbles." }, { subheading: "Food", description: "Pair it with spicy pizza or tandoori chicken wings." }],
    pairingIdeas: [{ title: "With Lambrusco", items: ["spicy pizza", "tandoori chicken wings", "salami", "fried mushrooms"] }],
    whyChoose: "An Emilia cooperative label that makes red sparkling wine easy to bring to the table.",
    faqs: [{ question: "What is Riunite known for?", answer: "Its lightly sparkling Lambrusco is the best-known wine." }, { question: "Where did Riunite begin?", answer: "The cooperative began in Emilia-Romagna in 1950." }],
    finalVerdict: "Chilled Riunite Lambrusco is a lively partner for salty, spicy snacks.",
    metaTitle: "Riunite Lambrusco Wine Guide | BevOry", metaDescription: "Discover Riunite Lambrusco, its red-fruit fizz and food pairings. Check city prices on BevOry.",
  },
  "rock-rose": {
    description: "Rock Rose is a Scottish gin from Dunnet Bay Distillers in Caithness. Its recipe mixes traditional gin botanicals with plants gathered around Scotland's northern coast.",
    story: "The distillery opened at Dunnet Bay near the top of mainland Scotland. Rock rose, a local name for Rhodiola rosea, supplied the gin's name and a distinctly northern botanical cue.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper gives the gin a dry core." }, { title: "Coastal botanicals", description: "Citrus, herbs and a light floral edge soften the finish." }],
    howToEnjoy: [{ subheading: "G&T", description: "Build with dry tonic over ice and keep the garnish simple." }, { subheading: "Food", description: "Try with smoked salmon or pepper prawns." }],
    pairingIdeas: [{ title: "Coastal plates", items: ["smoked salmon", "pepper prawns", "cucumber salad", "oat crackers"] }],
    whyChoose: "A Caithness gin with local botanicals and a distillery rooted in its northern landscape.",
    faqs: [{ question: "Who makes Rock Rose Gin?", answer: "Dunnet Bay Distillers makes it in Caithness, Scotland." }, { question: "What is rock rose?", answer: "It is a local name for Rhodiola rosea, a plant linked to the gin." }],
    finalVerdict: "Rock Rose is a fine G&T gin for seafood and a restrained garnish.",
    metaTitle: "Rock Rose Gin Guide | BevOry", metaDescription: "Explore Rock Rose Gin from Caithness, its botanicals and seafood pairings. Check city prices on BevOry.",
  },
  "roe-and-co": {
    description: "Roe & Co is a blended Irish whiskey brand from Diageo with a distillery in Dublin's Liberties. It honours George Roe, whose nineteenth-century distillery once stood nearby.",
    story: "George Roe's original whiskey operation closed in 1926. Diageo revived the name and built the modern Roe & Co distillery in a former Guinness power station near the old site.",
    tastingNotes: [{ title: "Fruit", description: "Soft pear and vanilla give the blend a gentle opening." }, { title: "Oak", description: "A light spice note follows the sweet grain character." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice with chilled soda and a lemon peel." }, { subheading: "Food", description: "Try beside roast chicken or smoked almonds." }],
    pairingIdeas: [{ title: "Dublin table", items: ["roast chicken", "smoked almonds", "apple tart", "mild cheddar"] }],
    whyChoose: "A modern Dublin distillery reviving one of the city's historic whiskey names.",
    faqs: [{ question: "Where is Roe & Co distillery?", answer: "It is in Dublin's Liberties, near the former George Roe site." }, { question: "Is Roe & Co a blended whiskey?", answer: "Its core whiskey is an Irish blend." }],
    finalVerdict: "Roe & Co is an easy Dublin blend for a clean whiskey highball.",
    metaTitle: "Roe & Co Irish Whiskey Guide | BevOry", metaDescription: "Meet Roe & Co's Dublin whiskey, its history and highball pairings. Check city prices on BevOry.",
  },
  "rooster-rojo": {
    description: "Rooster Rojo is a tequila brand made from blue agave in Jalisco, Mexico. Its range includes blanco and oak-rested expressions.",
    story: "The label takes the red rooster, a familiar Mexican symbol, as its identifying mark. It is part of Amber Beverage Group's spirits portfolio and keeps its production identity tied to Jalisco agave.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus make a brisk, peppery opening." }, { title: "Reposado", description: "Oak adds vanilla and a softer spice note to the agave." }],
    howToEnjoy: [{ subheading: "Taste", description: "Sip blanco cool and neat, or use it in a lime-led margarita." }, { subheading: "Food", description: "Pair with fish tacos or tandoori prawns." }],
    pairingIdeas: [{ title: "Agave table", items: ["fish tacos", "tandoori prawns", "grilled corn", "guacamole"] }],
    whyChoose: "A Jalisco blue-agave tequila with clear blanco and rested styles to compare.",
    faqs: [{ question: "Where is Rooster Rojo tequila made?", answer: "It is made in Jalisco, Mexico." }, { question: "Does it use blue agave?", answer: "Yes. Rooster Rojo is made from blue agave." }],
    finalVerdict: "Rooster Rojo blanco suits a tart margarita and a plate of grilled food.",
    metaTitle: "Rooster Rojo Tequila Guide | BevOry", metaDescription: "Explore Rooster Rojo tequila from Jalisco, agave notes and pairings. Check city prices on BevOry.",
  },
  ruffino: {
    description: "Ruffino is a Tuscan wine producer known for Chianti and other Italian wines. Its range reaches from Sangiovese-led reds to sparkling and white bottles.",
    story: "Cousins Ilario and Leopoldo Ruffino established the business in Pontassieve in 1877. Chianti became the name most closely linked to the house as it expanded beyond Tuscany.",
    tastingNotes: [{ title: "Chianti", description: "Cherry and dried herbs bring a savoury edge to the Sangiovese red." }, { title: "Prosecco", description: "Apple and pear notes show a brighter, sparkling side of the range." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve Chianti slightly cool and Prosecco well chilled." }, { subheading: "Food", description: "Put the red beside tomato pasta or paneer tikka." }],
    pairingIdeas: [{ title: "Italian table", items: ["tomato pasta", "paneer tikka", "mushroom pizza", "grilled vegetables"] }],
    whyChoose: "A Tuscan name whose long Chianti history still anchors a wider Italian range.",
    faqs: [{ question: "When was Ruffino founded?", answer: "Ilario and Leopoldo Ruffino founded it in 1877." }, { question: "Which wine is Ruffino especially known for?", answer: "Chianti is one of its signature wines." }],
    finalVerdict: "Ruffino Chianti makes most sense with a tomato-rich, herb-led dinner.",
    metaTitle: "Ruffino Wine Guide | BevOry", metaDescription: "Explore Ruffino Chianti, Tuscan history and food pairings. Check city prices on BevOry.",
  },
  "russian-standard": {
    description: "Russian Standard is a Russian vodka brand associated with St Petersburg. Its core range is built around a clean wheat-spirit style.",
    story: "The brand launched in the late 1990s and later moved production to its own St Petersburg distillery. It became a prominent modern Russian vodka name by pairing traditional imagery with large-scale production.",
    tastingNotes: [{ title: "Nose", description: "A restrained cereal note keeps the aroma quiet." }, { title: "Texture", description: "The palate is clean and rounded, with a dry finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a small glass or measure into a vodka martini." }, { subheading: "Food", description: "Try with smoked fish or salted cucumber." }],
    pairingIdeas: [{ title: "Cold-table bites", items: ["smoked fish", "salted cucumber", "potato blinis", "pickled mushrooms"] }],
    whyChoose: "A St Petersburg vodka whose appeal is its restrained wheat-spirit character.",
    faqs: [{ question: "Where is Russian Standard vodka from?", answer: "The brand is associated with St Petersburg, Russia." }, { question: "How can it be served?", answer: "Serve it chilled or use it in a dry vodka martini." }],
    finalVerdict: "Russian Standard suits a cold, simple serve with salty food.",
    metaTitle: "Russian Standard Vodka Guide | BevOry", metaDescription: "Explore Russian Standard vodka, serving ideas and food matches. Check city prices on BevOry.",
  },
  rutini: {
    description: "Rutini is an Argentine wine house with vineyards in Mendoza's Uco Valley. Its portfolio includes Malbec and other high-altitude reds and whites.",
    story: "Felipe Rutini founded Bodega La Rural in Maipu in 1885. The winery began planting in the Uco Valley in 1924 and later built its Rutini production site in Tupungato.",
    tastingNotes: [{ title: "Malbec", description: "Black plum and violet meet a firm but rounded red-wine frame." }, { title: "White wines", description: "Citrus and orchard fruit give a fresher contrast to the reds." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Malbec slightly cool in a broad red-wine glass." }, { subheading: "Food", description: "Try it with lamb kebabs or grilled mushrooms." }],
    pairingIdeas: [{ title: "Mendoza dinner", items: ["lamb kebabs", "grilled mushrooms", "beef empanadas", "roasted peppers"] }],
    whyChoose: "A Mendoza house that planted in the Uco Valley long before it became a global wine address.",
    faqs: [{ question: "Who founded Rutini Wines?", answer: "Felipe Rutini founded the original winery in 1885." }, { question: "Where does Rutini grow grapes?", answer: "Its vineyards include sites in Mendoza's Uco Valley." }],
    finalVerdict: "Rutini Malbec belongs beside grilled food with enough depth to meet its fruit.",
    metaTitle: "Rutini Wine Guide | BevOry", metaDescription: "Discover Rutini wines from Mendoza, Malbec notes and pairings. Check city prices on BevOry.",
  },
  "red-horse": {
    description: "Red Horse is a strong lager brewed by San Miguel Brewery in the Philippines. It is known for a fuller malt body than a standard pale pilsner.",
    story: "San Miguel Brewery has built several beer labels around Philippine drinking occasions. Red Horse became its extra-strong lager name, sitting apart from San Miguel Pale Pilsen in the company's range.",
    tastingNotes: [{ title: "Malt", description: "Grain and light caramel give the beer its weight." }, { title: "Finish", description: "A modest hop bitterness stops the fuller body from turning sweet." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a sturdy beer glass." }, { subheading: "Food", description: "Try with pork sisig or spicy chicken inasal." }],
    pairingIdeas: [{ title: "Philippine plates", items: ["pork sisig", "chicken inasal", "chilli garlic peanuts", "grilled pork skewers"] }],
    whyChoose: "A fuller-strength Philippine lager from the brewery behind San Miguel Pale Pilsen.",
    faqs: [{ question: "Who brews Red Horse?", answer: "San Miguel Brewery brews Red Horse." }, { question: "Where did Red Horse originate?", answer: "It is a Philippine beer brand." }],
    finalVerdict: "Red Horse is a cold lager for bold, salty food rather than delicate snacks.",
    metaTitle: "Red Horse Beer Guide | BevOry", metaDescription: "Explore Red Horse strong lager, flavour and Philippine food pairings. Check city prices on BevOry.",
  },
};
