import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_39 = [
  ["ename-blond", "Ename Blond", "Belgium", "Beer", "40d789a8b94390cbbb906bd5"],
  ["ernest", "Ernest Rapeneau", "France", "Champagne", "61a3c22a310f6b6328941b54"],
  ["fournier", "Fournier Pere et Fils", "France", "Wine", "8ac2aa7a084027a42f92db0a"],
  ["gentse", "Gentse Strop", "Belgium", "Beer", "7f517291a4a1ea280ae50c96"],
  ["georges", "Georges Duboeuf", "France", "Wine", "eda1138590096cd8de1a4254"],
  ["good-day", "Good Day", "South Korea", "Soju", "094af38f344a731a73972137"],
  ["goose-312", "Goose Island 312", "United States", "Beer", "673b4076243df5a8d2aef8eb"],
  ["haart-to-heart", "Haart to Heart", "Germany", "Wine", "19fcb79a2af5747e9fe1ca01"],
  ["hakushika-junmai", "Hakushika Yoshino Taru", "Japan", "Sake", "1faa61f5478d55361b134955"],
  ["hakutsuru-junmai", "Hakutsuru Junmai Draft", "Japan", "Sake", "e456d65721c7bb79c2035285"],
  ["iconiq-white", "ICONiQ White", "India", "Whisky", "3fe98ddb8f6e30778c64a06c"],
  ["kauffman", "Kauffman", "Russia", "Vodka", "104c88e40408ddea91b956fd"],
  ["langleys", "Langley's", "United Kingdom", "Gin", "9ee1ea3de205eca1d2442f16"],
  ["le-calvados", "Christian Drouin Calvados", "France", "Brandy", "11628779cf218bac34946168"],
  ["le-gin-de", "Le Gin de Christian Drouin", "France", "Gin", "fbf1d001d09502297df38a66"],
  ["les-pagodes", "Les Pagodes de Cos", "France", "Wine", "653cf81c77e584bbe601f391"],
  ["le-corti", "Le Corti", "Italy", "Wine", "9da9d5ba82d53bec9d775a35"],
  ["le-grand", "Le Grand Noir", "France", "Wine", "c29689bb610b9bbe89541267"],
  ["la-pierrelee", "La Pierrelee", "France", "Wine", "8ae76e7ed50c22825cf29c19"],
  ["la-cacciatora", "La Cacciatora", "Italy", "Wine", "84a064938bad7f6d349455f7"],
  ["masi-bonacosta", "Masi Bonacosta", "Italy", "Wine", "da44ccbf59e219a7cdc7a10d"],
  ["miraval-cotes", "Miraval Cotes de Provence", "France", "Wine", "fce98a0d1f9232324b4abf73"],
  ["moletto", "Moletto", "Italy", "Sparkling Wine", "cce9184ea211bac4a3471696"],
  ["montes-limited", "Montes Limited Selection", "Chile", "Wine", "785d34ac346ed4ec2a07c865"],
  ["montgras-day-one", "MontGras Day One", "Chile", "Wine", "d1cefc6554f7ede13b1a4d46"],
  ["moonshine", "Moonshine Meadery", "India", "Mead", "d82087a6287be66026e4b4bb"],
  ["morosha", "Morosha", "Ukraine", "Vodka", "ceecafdef41b723883e9ac6c"],
  ["patron-tequila", "Patron El Alto", "Mexico", "Tequila", "adc0799a5fddff1a143e049c"],
  ["peppoli", "Peppoli", "Italy", "Wine", "906bfd52c54518b6e83c3155"],
  ["petrus-gouden", "Petrus Gouden Tripel", "Belgium", "Beer", "ffee33f97fc0ea20d522f724"],
] as const;

// Research provenance stays internal; public content below carries no citations.
export const BRAND_SOURCES_BATCH_39: Record<string, string[]> = {
  "ename-blond": ["https://www.roman.be/en/pages/brands/ename-abdijbier"],
  ernest: ["https://champagne-ernest-rapeneau.com/la-collection/cuvee-brut/"],
  fournier: ["https://www.fournier-pere-fils.com/en/wine/les-belles-vignes-blanc/"],
  gentse: ["https://www.roman.be/en/pages/brands/gentse-strop"],
  georges: ["https://www.duboeuf.com/en/wines/"],
  "good-day": ["https://www.muhak.co.kr/product/goodday/"],
  "goose-312": ["https://www.gooseisland.com/beers/312-beer"],
  "haart-to-heart": ["https://haart.de/weine/"],
  "hakushika-junmai": ["https://www.hakushika.co.jp/en/products/p14.html"],
  "hakutsuru-junmai": ["https://www.hakutsuru-sake.com/product/hakutsuru-tanrei-junmai/"],
  "iconiq-white": ["https://www.abdindia.com/"],
  kauffman: ["https://roust.com/en/brands/owned/russian-vodka/kauffman/"],
  langleys: ["https://www.langleysgin.com/"],
  "le-calvados": ["https://www.calvados-drouin.com/en/house-of-drouin"],
  "le-gin-de": ["https://www.calvados-drouin.com/en/product/50/le-gin"],
  "les-pagodes": ["https://www.estournel.com/fr/cos/vins-pagodes-de-cos/"],
  "le-corti": ["https://principecorsini.com/i-vini/"],
  "le-grand": ["https://www.legrandnoir.com/classic-range/"],
  "la-pierrelee": ["https://chablisienne.com/media/wysiwyg/FT-EN-CHABLIS-LA-PIERRELEE_2023.pdf"],
  "la-cacciatora": ["https://www.lacacciatorawine.it/en/homepage/"],
  "masi-bonacosta": ["https://www.masi.it/files/qw_masi_bonacosta_e.pdf"],
  "miraval-cotes": ["https://www.miraval.com/en/a-work-of-art/miraval-rose/"],
  moletto: ["https://www.moletto.com/en/wines/prosecco-doc-rose-treviso-millesimato-extra-dry-2/"],
  "montes-limited": ["https://www.monteswines.com/EN/biblioteca/limited-selection/cabernet-sauvignon-carmen%C3%A8re"],
  "montgras-day-one": ["https://montgras.cl/wp-content/uploads/2022/03/2020-MontGras-DAY-ONE-Chardonnay-ENG.pdf"],
  moonshine: ["https://www.moonshinemeadery.com/"],
  morosha: ["https://morosha.com/en/products/spring"],
  "patron-tequila": ["https://www.patrontequila.com/products/el-alto.html"],
  peppoli: ["https://www.antinori.it/en/tenuta/estates-antinori/peppoli-estate/"],
  "petrus-gouden": ["https://www.brouwerijdebrabandere.be/en/brands/petrus-tripel", "https://belgianfamilybrewers.be/wp-content/uploads/2015/pdf/53308_BFB_Brewery_GUIDE_A4_2015_v3_De%20Brabantere.pdf"],
};

export const BRAND_LOGOS_BATCH_39: Record<string, string> = {
  "miraval-cotes": "https://www.miraval.com/wp-content/themes/tete-chercheuse/assets/images/logo.jpg",
  peppoli: "https://www.antinori.it/wp-content/themes/antinori/static/images/tenute/peppoli.svg?mtime=1528289843",
};

export const BRAND_CONTENT_BATCH_39: Record<string, BrandPublicContent> = {
  "ename-blond": {
    description: "Ename Blond is a Belgian abbey beer brewed by Brouwerij Roman in Oudenaarde. This bottle-conditioned blonde ale brings a soft malt base and a lively, dry finish.",
    story: "Ename takes its name from the historic abbey site near Oudenaarde. The Roman family brewery makes the beer in East Flanders and lets it finish in the bottle.",
    tastingNotes: [{ title: "Nose", description: "Light grain, orchard fruit and a faint floral hop note." }, { title: "Finish", description: "A rounded malt opening gives way to gentle bitterness and a crisp close." }],
    howToEnjoy: [{ subheading: "Pour", description: "Pour cool into a stemmed Belgian beer glass, leaving the yeast sediment behind if you prefer clarity." }, { subheading: "Food", description: "Try it with chicken tikka or crisp potato croquettes." }],
    pairingIdeas: [{ title: "With a blonde ale", items: ["chicken tikka", "potato croquettes", "fried calamari", "salted almonds"] }],
    whyChoose: "A bottle-conditioned abbey blonde with the easy lift of fruit and gentle hops.",
    faqs: [{ question: "Who brews Ename Blond?", answer: "Brouwerij Roman brews it in Oudenaarde, Belgium." }, { question: "Is Ename Blond bottle conditioned?", answer: "Yes, the beer continues its maturation in the bottle." }],
    finalVerdict: "Ename Blond suits a slow pour and salty, crisp snacks.",
    metaTitle: "Ename Blond Beer Guide | BevOry", metaDescription: "Explore Ename Blond's abbey-beer style, tasting notes, food pairings and city prices on BevOry.",
  },
  ernest: {
    description: "Ernest Rapeneau is a Champagne house associated with Hautvillers in France. Its Brut cuvee blends Champagne's classic grape varieties for a fresh, orchard-fruit led sparkling wine.",
    story: "The Rapeneau family's Champagne work reaches back to the early twentieth century. Hautvillers, the village closely tied to the region's winemaking history, remains central to the house's identity.",
    tastingNotes: [{ title: "Fruit", description: "Apple and pear sit alongside a citrus edge." }, { title: "Texture", description: "Fine bubbles lift a lightly toasty, dry finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill well and pour into a tulip glass rather than a wide coupe." }, { subheading: "Food", description: "Its acidity works with tandoori prawns or a plate of soft cheese." }],
    pairingIdeas: [{ title: "For the table", items: ["tandoori prawns", "fish fingers", "brie", "salted cashews"] }],
    whyChoose: "A French Champagne for drinkers who want bright fruit and a crisp finish.",
    faqs: [{ question: "Where is Ernest Rapeneau Champagne from?", answer: "The house is associated with Hautvillers in France's Champagne region." }, { question: "How should its Brut be served?", answer: "Serve it chilled in a tulip-shaped sparkling-wine glass." }],
    finalVerdict: "Ernest Rapeneau Brut is a lively match for seafood and savoury starters.",
    metaTitle: "Ernest Rapeneau Champagne Guide | BevOry", metaDescription: "Read about Ernest Rapeneau Champagne, its bright Brut style, pairings and city prices on BevOry.",
  },
  fournier: {
    description: "Fournier Pere et Fils makes Loire Valley wine around Verdigny in Sancerre. Its Les Belles Vignes Blanc is a Sauvignon Blanc built around citrus, herbs and the region's mineral edge.",
    story: "The Fournier family has worked vineyards in Sancerre for generations. Les Belles Vignes draws on the area's hillside Sauvignon Blanc rather than oak-led richness.",
    tastingNotes: [{ title: "Aroma", description: "Lemon zest and white flowers meet a green herbal note." }, { title: "Palate", description: "Brisk acidity carries citrus and a clean, stony finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve chilled in a medium white-wine glass." }, { subheading: "Food", description: "Pour beside tandoori fish or goat-cheese toast." }],
    pairingIdeas: [{ title: "Citrus-friendly plates", items: ["tandoori fish", "goat-cheese toast", "lemon prawns", "herb paneer tikka"] }],
    whyChoose: "A direct, herb-edged Sancerre Sauvignon Blanc with refreshing acidity.",
    faqs: [{ question: "Which grape makes Fournier Les Belles Vignes Blanc?", answer: "It is made from Sauvignon Blanc in Sancerre." }, { question: "Where is Fournier Pere et Fils based?", answer: "The producer works around Verdigny in France's Loire Valley." }],
    finalVerdict: "Les Belles Vignes brings Sancerre's citrus snap to seafood and herby dishes.",
    metaTitle: "Fournier Pere et Fils Wine Guide | BevOry", metaDescription: "Discover Fournier's Sancerre Sauvignon Blanc, tasting notes, Indian food matches and city prices on BevOry.",
  },
  gentse: {
    description: "Gentse Strop is a Belgian blonde beer brewed by Brouwerij Roman. It takes its name from Ghent's 'noose-bearer' nickname and balances pale malt with a lively hop finish.",
    story: "The beer's name recalls a chapter of Ghent's civic history that locals turned into a badge of pride. Roman brews it in East Flanders, connecting a city story with a regional brewing tradition.",
    tastingNotes: [{ title: "Opening", description: "Soft cereal and light fruit come through first." }, { title: "Aftertaste", description: "A little spice and hop bitterness tighten the finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cool in a Belgian goblet with room for foam." }, { subheading: "Food", description: "Its dry edge suits chicken pakora and Belgian-style fries." }],
    pairingIdeas: [{ title: "Golden-beer snacks", items: ["chicken pakora", "Belgian-style fries", "cheese croquettes", "masala peanuts"] }],
    whyChoose: "A Ghent-inspired blonde with enough bite to stand up to fried snacks.",
    faqs: [{ question: "Who makes Gentse Strop?", answer: "Brouwerij Roman brews it in East Flanders, Belgium." }, { question: "What does Gentse Strop refer to?", answer: "It refers to Ghent's historic 'noose-bearer' nickname." }],
    finalVerdict: "Gentse Strop is best with a proper foam cap and something salty on the table.",
    metaTitle: "Gentse Strop Beer Guide | BevOry", metaDescription: "Meet Ghent-inspired Gentse Strop beer, its blonde-ale profile, pairings and city prices on BevOry.",
  },
  georges: {
    description: "Georges Duboeuf is a French wine name closely tied to Beaujolais and the Maconnais. The range includes Gamay-based Beaujolais reds and Chardonnay from southern Burgundy.",
    story: "Georges Duboeuf helped bring Beaujolais to an international audience. His family's wines trace two neighbouring French wine areas, from the Gamay vineyards of Beaujolais to Chardonnay country farther north.",
    tastingNotes: [{ title: "Beaujolais", description: "Red cherry and raspberry lead a supple Gamay red." }, { title: "Macon-Villages", description: "Apple, citrus and a soft floral note shape the Chardonnay white." }],
    howToEnjoy: [{ subheading: "Serve", description: "Give the red a light chill; serve the white cool in a white-wine glass." }, { subheading: "Food", description: "Try Beaujolais with chicken tikka and Macon-Villages with grilled fish." }],
    pairingIdeas: [{ title: "Two sides of the range", items: ["chicken tikka", "grilled fish", "mushroom toast", "goat cheese"] }],
    whyChoose: "An accessible route into Beaujolais Gamay and Maconnais Chardonnay.",
    faqs: [{ question: "What grapes appear in Georges Duboeuf wines?", answer: "Beaujolais reds are made from Gamay; the Macon-Villages white is Chardonnay." }, { question: "Where is Georges Duboeuf wine from?", answer: "The range is rooted in Beaujolais and the Maconnais in eastern France." }],
    finalVerdict: "Duboeuf offers an easy French wine choice, from juicy red to bright white.",
    metaTitle: "Georges Duboeuf Wine Guide | BevOry", metaDescription: "Explore Georges Duboeuf Beaujolais and Macon-Villages, tasting notes, pairings and city prices on BevOry.",
  },
  "good-day": {
    description: "Good Day is a South Korean soju brand from Muhak. Its fruit-flavoured bottles bring a softer, sweeter take on the chilled soju serve.",
    story: "Muhak launched Good Day in South Korea and later extended it beyond the original clear spirit. The flavoured range uses familiar fruit cues to suit shared meals and easy mixed drinks.",
    tastingNotes: [{ title: "Fruit range", description: "The selected flavour leads the nose, with a sweet fruit impression." }, { title: "Finish", description: "A light body keeps the finish short and cool." }],
    howToEnjoy: [{ subheading: "Chill", description: "Refrigerate and serve in small glasses." }, { subheading: "Food", description: "Pair fruity bottles with Korean fried chicken or chilli paneer." }],
    pairingIdeas: [{ title: "At the table", items: ["Korean fried chicken", "chilli paneer", "kimchi pancakes", "spicy grilled corn"] }],
    whyChoose: "A fruit-forward soju range that works well for a shared, chilled pour.",
    faqs: [{ question: "Who makes Good Day soju?", answer: "Good Day is made by South Korean producer Muhak." }, { question: "How is flavoured Good Day usually served?", answer: "It is commonly served well chilled in small glasses." }],
    finalVerdict: "Good Day is an easy pick when fruit flavour matters more than a hard spirit edge.",
    metaTitle: "Good Day Soju Guide | BevOry", metaDescription: "Explore Good Day fruit soju from Muhak, serving ideas, food matches and city prices on BevOry.",
  },
  "goose-312": {
    description: "Goose Island 312 is an American wheat beer named for Chicago's 312 area code. The Urban Wheat Ale puts soft grain, citrus and a light haze in the glass.",
    story: "Goose Island began brewing in Chicago, and 312 keeps that home-city connection in its name. The beer takes a wheat-ale route rather than the heavier malt character of an amber or stout.",
    tastingNotes: [{ title: "Wheat", description: "Fresh bread and pale grain form a soft base." }, { title: "Lift", description: "A citrus note and light hop bite freshen the finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve cold in a tall glass; a little haze is part of the beer." }, { subheading: "Food", description: "The wheat body fits fish tacos or peppery chicken wings." }],
    pairingIdeas: [{ title: "Casual plates", items: ["fish tacos", "pepper chicken wings", "paneer skewers", "salted popcorn"] }],
    whyChoose: "A Chicago wheat ale with a soft texture and citrus lift.",
    faqs: [{ question: "What does 312 mean on the beer?", answer: "312 is an area code for Chicago, Goose Island's home city." }, { question: "What style is Goose Island 312?", answer: "It is an Urban Wheat Ale." }],
    finalVerdict: "312 is at its best cold, with crisp food and an unhurried pour.",
    metaTitle: "Goose Island 312 Beer Guide | BevOry", metaDescription: "Discover Goose Island 312 Urban Wheat Ale, Chicago roots, food pairings and city prices on BevOry.",
  },
  "haart-to-heart": {
    description: "Haart to Heart is a Riesling from Weingut Haart in Piesport on Germany's Mosel. The estate presents it as feinherb, a lightly off-dry style shaped by the grape's acidity.",
    story: "The Haart family works steep Mosel vineyards around Piesport. This bottling makes that Riesling character approachable through fresh fruit and a measured touch of sweetness.",
    tastingNotes: [{ title: "Nose", description: "Green apple, citrus and white peach." }, { title: "Balance", description: "A gentle sweetness meets bright acidity on the finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill and pour in a white-wine glass." }, { subheading: "Food", description: "Try it with chilli paneer or ginger prawns, where acidity helps with heat." }],
    pairingIdeas: [{ title: "With spice", items: ["chilli paneer", "ginger prawns", "Thai green curry", "sesame chicken"] }],
    whyChoose: "Mosel Riesling with fruit, lift and enough sweetness for spicy food.",
    faqs: [{ question: "Where is Haart to Heart made?", answer: "Weingut Haart makes it in Piesport in Germany's Mosel region." }, { question: "Is Haart to Heart Riesling dry?", answer: "The estate lists it as feinherb, a lightly off-dry style." }],
    finalVerdict: "Haart to Heart is a useful Riesling to bring to a spice-led dinner.",
    metaTitle: "Haart to Heart Riesling Guide | BevOry", metaDescription: "Read about Haart to Heart Mosel Riesling, its off-dry balance, food matches and city prices on BevOry.",
  },
  "hakushika-junmai": {
    description: "Hakushika Yoshino Taru is a Japanese junmai sake from Tatsuuma-Honke Brewing. Brief contact with Yoshino cedar gives the rice sake a fragrant woody accent.",
    story: "Hakushika comes from Nishinomiya, an established sake-brewing area in Hyogo. The Yoshino Taru expression draws on the tradition of storing sake in cedar casks.",
    tastingNotes: [{ title: "Cedar", description: "Fresh wood spice comes through clearly on the nose." }, { title: "Rice", description: "A soft grain note sits beneath the crisp, savoury finish." }],
    howToEnjoy: [{ subheading: "Serve", description: "Try it lightly chilled in a small sake glass." }, { subheading: "Food", description: "Its cedar aroma suits grilled mushrooms or yakitori." }],
    pairingIdeas: [{ title: "Savoury pairings", items: ["yakitori", "grilled mushrooms", "soy-glazed aubergine", "tandoori fish"] }],
    whyChoose: "A rice-based junmai with a distinctive Yoshino cedar scent.",
    faqs: [{ question: "What gives Hakushika Yoshino Taru its woody aroma?", answer: "Contact with Yoshino cedar adds the fragrance." }, { question: "Who makes Hakushika sake?", answer: "It is made by Tatsuuma-Honke Brewing in Japan." }],
    finalVerdict: "Yoshino Taru is a good way to taste cedar's effect on junmai sake.",
    metaTitle: "Hakushika Yoshino Taru Sake Guide | BevOry", metaDescription: "Explore Hakushika Yoshino Taru junmai sake, cedar notes, serving ideas and city prices on BevOry.",
  },
  "hakutsuru-junmai": {
    description: "Hakutsuru Junmai Draft is a Japanese namachozo sake from Hakutsuru in Kobe. It is pasteurised once before bottling, keeping a bright, fresh rice profile.",
    story: "Hakutsuru is a long-established brewer in Kobe's Nada sake district. Junmai Draft takes its name from the fresher treatment of the sake after brewing.",
    tastingNotes: [{ title: "Aroma", description: "Pear and green melon hover over sweet rice." }, { title: "Finish", description: "A clean, soft mouthfeel closes with a fresh edge." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill and pour into a small sake cup or white-wine glass." }, { subheading: "Food", description: "Serve beside sushi, tandoori prawns or steamed dumplings." }],
    pairingIdeas: [{ title: "Light dishes", items: ["sushi", "tandoori prawns", "steamed dumplings", "cucumber salad"] }],
    whyChoose: "A fresh-tasting junmai from one of Kobe's established sake houses.",
    faqs: [{ question: "What is namachozo sake?", answer: "It is sake stored without pasteurisation and pasteurised once before bottling." }, { question: "Where is Hakutsuru based?", answer: "Hakutsuru brews in the Nada district of Kobe, Japan." }],
    finalVerdict: "Hakutsuru Junmai Draft is a cool, clean partner for seafood and light starters.",
    metaTitle: "Hakutsuru Junmai Draft Sake Guide | BevOry", metaDescription: "Discover Hakutsuru Junmai Draft sake, fresh rice notes, food pairings and city prices on BevOry.",
  },
  "iconiq-white": {
    description: "ICONiQ White is an Indian whisky label from Allied Blenders and Distillers. It sits in the company's contemporary whisky range with a light, mix-friendly style.",
    story: "Allied Blenders and Distillers developed ICONiQ White for India's growing branded whisky market. The label's pale presentation sets it apart from the company's older, darker-coloured whisky packaging.",
    tastingNotes: [{ title: "Opening", description: "Soft cereal and a light sweetness lead the sip." }, { title: "Finish", description: "A mild woody note keeps the finish short." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over plenty of ice and top with soda." }, { subheading: "Food", description: "Serve with masala peanuts or chicken tikka." }],
    pairingIdeas: [{ title: "Easy snacks", items: ["masala peanuts", "chicken tikka", "paneer pakora", "potato wedges"] }],
    whyChoose: "A straightforward Indian whisky built for simple highballs.",
    faqs: [{ question: "Who owns ICONiQ White?", answer: "It is a whisky label from Allied Blenders and Distillers." }, { question: "How can ICONiQ White be mixed?", answer: "Soda and ice make a simple highball." }],
    finalVerdict: "ICONiQ White is most at home in an uncomplicated whisky-and-soda pour.",
    metaTitle: "ICONiQ White Whisky Guide | BevOry", metaDescription: "Meet ICONiQ White Indian whisky, its serving style, snack pairings and city prices on BevOry.",
  },
  kauffman: {
    description: "Kauffman is a Russian vodka brand in the Roust portfolio. It is positioned around a clean grain spirit and a polished, chilled serve.",
    story: "Kauffman grew from a founder-led Russian vodka label into a premium name within Roust's portfolio. The range uses repeated distillation and filtration to keep the spirit clear and restrained.",
    tastingNotes: [{ title: "Nose", description: "A light grain note with little overt sweetness." }, { title: "Texture", description: "A smooth, cool palate closes cleanly." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a small stemmed glass." }, { subheading: "Food", description: "Try it alongside pickled cucumber or smoked fish." }],
    pairingIdeas: [{ title: "Salty plates", items: ["pickled cucumber", "smoked fish", "salted almonds", "potato blini"] }],
    whyChoose: "A restrained vodka for drinkers who favour a clean chilled pour.",
    faqs: [{ question: "Which company owns Kauffman vodka?", answer: "Kauffman is part of Roust's vodka portfolio." }, { question: "How is Kauffman best served?", answer: "Serve it thoroughly chilled, neat or in a Vodka Martini." }],
    finalVerdict: "Kauffman keeps the focus on a crisp, cold vodka serve.",
    metaTitle: "Kauffman Vodka Guide | BevOry", metaDescription: "Explore Kauffman vodka, chilled serving ideas, savoury pairings and city prices on BevOry.",
  },
  langleys: {
    description: "Langley's makes English gin, including London Dry and Old Tom expressions. Its range centres on juniper and citrus, with Old Tom taking a softer, sweeter turn.",
    story: "The brand takes its name from the Langley distilling site in the English Midlands. It keeps classic gin styles in view rather than treating every bottle as the same recipe.",
    tastingNotes: [{ title: "London Dry", description: "Juniper, lemon peel and a peppery herbal edge." }, { title: "Old Tom", description: "Rounder citrus with a gentle sweetness." }],
    howToEnjoy: [{ subheading: "Mix", description: "Use London Dry in a tonic; try Old Tom in a Martinez." }, { subheading: "Food", description: "Citrus gin fits tandoori prawns and cucumber chaat." }],
    pairingIdeas: [{ title: "With gin", items: ["tandoori prawns", "cucumber chaat", "fried olives", "rosemary crackers"] }],
    whyChoose: "Two classic English gin styles under one label, each with a different sweetness level.",
    faqs: [{ question: "What is Langley's Old Tom?", answer: "It is the brand's softer, gently sweeter gin style." }, { question: "How is Langley's London Dry served?", answer: "It works in a gin and tonic with a strip of citrus peel." }],
    finalVerdict: "Langley's makes the dry-versus-sweet gin choice clear at the bar.",
    metaTitle: "Langley's Gin Guide | BevOry", metaDescription: "Compare Langley's London Dry and Old Tom gin, serving ideas, food matches and city prices on BevOry.",
  },
  "le-calvados": {
    description: "Christian Drouin makes Calvados, the apple brandy of Normandy, France. The house's Pays d'Auge roots put orchard fruit and oak-aged spirit at the centre of its range.",
    story: "The Drouin family built its Calvados house around Normandy apples and traditional distillation. Different maturations show how fresh apple character changes in oak over time.",
    tastingNotes: [{ title: "Apple", description: "Baked apple and peel carry the main aroma." }, { title: "Oak", description: "Vanilla and gentle spice emerge in the mature expressions." }],
    howToEnjoy: [{ subheading: "After dinner", description: "Sip a small measure neat in a tulip glass." }, { subheading: "Food", description: "Apple brandy suits apple tart, aged cheddar or walnut cake." }],
    pairingIdeas: [{ title: "After-dinner table", items: ["apple tart", "aged cheddar", "walnut cake", "caramel kulfi"] }],
    whyChoose: "Normandy apple brandy with a clear link between orchard fruit and oak.",
    faqs: [{ question: "What is Christian Drouin Calvados made from?", answer: "Calvados is a Normandy apple brandy made from fermented cider." }, { question: "How can Calvados be served?", answer: "A small neat pour after dinner lets its apple and oak notes show." }],
    finalVerdict: "Christian Drouin makes an inviting apple-led finish to a meal.",
    metaTitle: "Christian Drouin Calvados Guide | BevOry", metaDescription: "Explore Christian Drouin Calvados, Normandy apple notes, food pairings and city prices on BevOry.",
  },
  "le-gin-de": {
    description: "Le Gin de Christian Drouin is a Normandy gin built on an apple-spirit base. Juniper and botanicals meet the fruit character of the Drouin family's cider apples.",
    story: "Christian Drouin brought its Calvados expertise into gin rather than starting with a neutral grain spirit. That choice gives the bottle a distinctly Norman point of view.",
    tastingNotes: [{ title: "Fruit", description: "Fresh apple and citrus appear beside juniper." }, { title: "Spice", description: "Herbal notes and a dry botanical finish follow." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use a restrained tonic so the apple-spirit base stays noticeable." }, { subheading: "Food", description: "Serve with apple-and-cheddar toast or grilled prawns." }],
    pairingIdeas: [{ title: "Apple and spice", items: ["apple-and-cheddar toast", "grilled prawns", "herb paneer tikka", "salted walnuts"] }],
    whyChoose: "A gin whose apple-spirit base changes the usual juniper-led equation.",
    faqs: [{ question: "What is unusual about Le Gin de Christian Drouin?", answer: "It uses an apple-spirit base linked to the house's Normandy cider tradition." }, { question: "Can Le Gin de Christian Drouin go in tonic?", answer: "Yes, a light tonic leaves room for its apple and juniper notes." }],
    finalVerdict: "Le Gin de Christian Drouin offers a fresh apple angle on a familiar gin serve.",
    metaTitle: "Le Gin de Christian Drouin Guide | BevOry", metaDescription: "Discover Le Gin de Christian Drouin, its apple-spirit base, pairings and city prices on BevOry.",
  },
  "les-pagodes": {
    description: "Les Pagodes de Cos is a Saint-Estephe red wine from Chateau Cos d'Estournel in Bordeaux. Cabernet Sauvignon and Merlot carry the property's dark-fruit, structured style.",
    story: "Cos d'Estournel's estate sits on the gravelly rise of Cos in northern Medoc. Les Pagodes gives the chateau a second red wine drawn from its Saint-Estephe terroir.",
    tastingNotes: [{ title: "Fruit", description: "Blackcurrant and dark plum lead the aroma." }, { title: "Structure", description: "Cedar spice and firm tannins support a long, savoury finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a large red-wine glass." }, { subheading: "Food", description: "The firm structure fits mutton seekh or slow-cooked lamb." }],
    pairingIdeas: [{ title: "With Bordeaux red", items: ["mutton seekh", "slow-cooked lamb", "mushroom galouti", "aged cheddar"] }],
    whyChoose: "A Saint-Estephe route into the Cos d'Estournel estate's red-wine style.",
    faqs: [{ question: "Who makes Les Pagodes de Cos?", answer: "It is made by Chateau Cos d'Estournel in Saint-Estephe, Bordeaux." }, { question: "What kind of wine is Les Pagodes de Cos?", answer: "It is a structured Bordeaux red centred on Cabernet Sauvignon and Merlot." }],
    finalVerdict: "Les Pagodes de Cos earns its place beside a substantial savoury dinner.",
    metaTitle: "Les Pagodes de Cos Wine Guide | BevOry", metaDescription: "Explore Les Pagodes de Cos Saint-Estephe red, tasting notes, pairings and city prices on BevOry.",
  },
  "le-corti": {
    description: "Le Corti is a Chianti Classico wine from Villa Le Corti, the Corsini family's Tuscan estate. Sangiovese gives the red its cherry fruit, savoury herbs and lively acidity.",
    story: "The Corsini family has long farmed around San Casciano in Val di Pesa. Le Corti carries that Chianti Classico origin in a wine designed around Sangiovese rather than heavy sweetness.",
    tastingNotes: [{ title: "Fruit", description: "Red cherry and plum meet a dried-herb note." }, { title: "Finish", description: "Fresh acidity and a light tannic grip keep it food-friendly." }],
    howToEnjoy: [{ subheading: "Serve", description: "Open slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Match it with mushroom pasta or lamb kebabs." }],
    pairingIdeas: [{ title: "Tuscan-style table", items: ["mushroom pasta", "lamb kebabs", "tomato bruschetta", "aged pecorino"] }],
    whyChoose: "A Sangiovese-led Tuscan red with the acidity to lift a rich meal.",
    faqs: [{ question: "Where is Le Corti made?", answer: "It comes from Villa Le Corti in the Chianti Classico area of Tuscany." }, { question: "Which grape leads Le Corti Chianti Classico?", answer: "Sangiovese is the leading grape." }],
    finalVerdict: "Le Corti is a natural bottle for tomato, mushrooms and grilled lamb.",
    metaTitle: "Le Corti Chianti Classico Guide | BevOry", metaDescription: "Discover Le Corti Chianti Classico, Sangiovese notes, meal pairings and city prices on BevOry.",
  },
  "le-grand": {
    description: "Le Grand Noir is a French wine range associated with Languedoc vineyards. Its red bottles include Pinot Noir, Merlot and Syrah, each with a different fruit and spice profile.",
    story: "The range was developed to make southern French varieties straightforward to choose by grape. Its sheep-marked labels give the bottles a shared identity without making the wines taste alike.",
    tastingNotes: [{ title: "Pinot Noir", description: "Red berry fruit and a light pepper note make a supple red." }, { title: "Syrah", description: "Darker berry fruit brings more spice and weight." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve the Pinot Noir lightly cool; give Syrah a broader glass." }, { subheading: "Food", description: "Pinot fits tandoori chicken; Syrah takes on mutton seekh." }],
    pairingIdeas: [{ title: "Choose by grape", items: ["tandoori chicken", "mutton seekh", "mushroom toast", "grilled aubergine"] }],
    whyChoose: "An approachable way to compare distinct French red grapes side by side.",
    faqs: [{ question: "Is Le Grand Noir one grape variety?", answer: "No. The range includes separate varietal wines such as Pinot Noir, Merlot and Syrah." }, { question: "Where does Le Grand Noir come from?", answer: "The range is associated with vineyards in southern France's Languedoc region." }],
    finalVerdict: "Le Grand Noir makes the grape, not a complicated label, the starting point.",
    metaTitle: "Le Grand Noir Wine Guide | BevOry", metaDescription: "Compare Le Grand Noir Pinot Noir, Merlot and Syrah, food matches and city prices on BevOry.",
  },
  "la-pierrelee": {
    description: "La Pierrelee is a Chablis Chardonnay made by the La Chablisienne cooperative in Burgundy. It leans on the area's cool climate for citrus, apple and a mineral finish.",
    story: "La Chablisienne brings together winegrowers from across Chablis. La Pierrelee expresses the region's Chardonnay through freshness rather than tropical ripeness.",
    tastingNotes: [{ title: "Fruit", description: "Green apple and lemon sit over a faint floral note." }, { title: "Finish", description: "A taut, stony edge follows the citrus." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cool in a white-wine glass, not ice-cold." }, { subheading: "Food", description: "Try it with grilled prawns or tandoori fish." }],
    pairingIdeas: [{ title: "Seafood first", items: ["grilled prawns", "tandoori fish", "oyster mushrooms", "goat cheese"] }],
    whyChoose: "A cooperative-made Chablis that keeps Chardonnay crisp and mineral.",
    faqs: [{ question: "Which grape is in La Pierrelee Chablis?", answer: "Chablis is made from Chardonnay." }, { question: "Who produces La Pierrelee?", answer: "It is made by the La Chablisienne winegrowers' cooperative." }],
    finalVerdict: "La Pierrelee is a bright, clean white for seafood and lighter savoury plates.",
    metaTitle: "La Pierrelee Chablis Guide | BevOry", metaDescription: "Explore La Pierrelee Chablis Chardonnay, citrus notes, seafood pairings and city prices on BevOry.",
  },
  "la-cacciatora": {
    description: "La Cacciatora is an Italian wine range spanning several grapes and regions. The selection includes Gavi, Barbera, Pinot Grigio and Garganega-led whites and reds.",
    story: "The label draws together familiar regional Italian styles under one name. That makes the grape and appellation on each bottle more useful than a single house-wide flavour claim.",
    tastingNotes: [{ title: "Gavi", description: "A bright white style with citrus and orchard-fruit notes." }, { title: "Barbera", description: "Juicy red fruit and vivid acidity shape the red expression." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Chill the Gavi; give Barbera a slight cool-down before pouring." }, { subheading: "Food", description: "Gavi fits grilled prawns, while Barbera suits tomato-rich pasta." }],
    pairingIdeas: [{ title: "Italian staples", items: ["grilled prawns", "tomato pasta", "paneer arrabbiata", "roast vegetables"] }],
    whyChoose: "A single label that opens up more than one everyday Italian wine style.",
    faqs: [{ question: "Is La Cacciatora only a red wine?", answer: "No. The range also includes Italian whites such as Gavi and Pinot Grigio." }, { question: "What should I serve with La Cacciatora Gavi?", answer: "Grilled prawns, white fish or light vegetable starters all suit a fresh Gavi." }],
    finalVerdict: "La Cacciatora rewards choosing by the grape and region that suit the meal.",
    metaTitle: "La Cacciatora Wine Guide | BevOry", metaDescription: "Discover La Cacciatora Italian wines, from Gavi to Barbera, food pairings and city prices on BevOry.",
  },
  "masi-bonacosta": {
    description: "Bonacosta is Masi's Valpolicella Classico red from the Veneto in Italy. Corvina and companion local grapes make a fresh, cherry-led wine for food.",
    story: "Masi has deep roots in the Valpolicella area near Verona. Bonacosta keeps the region's everyday red-wine character in view rather than the dried-grape richness of Amarone.",
    tastingNotes: [{ title: "Cherry", description: "Fresh red cherry leads with a hint of violet." }, { title: "Palate", description: "Light tannins and lively acidity bring a clean finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Try it with tomato pasta or chicken tikka." }],
    pairingIdeas: [{ title: "Everyday red", items: ["tomato pasta", "chicken tikka", "mushroom pizza", "grilled aubergine"] }],
    whyChoose: "A lively Valpolicella red for meals that need freshness, not weight.",
    faqs: [{ question: "Where is Masi Bonacosta made?", answer: "It is a Valpolicella Classico wine from the Veneto region of Italy." }, { question: "Is Bonacosta an Amarone?", answer: "No. Bonacosta is a fresher Valpolicella Classico red." }],
    finalVerdict: "Bonacosta is a dependable cherry-bright red for pizza, pasta and grilled food.",
    metaTitle: "Masi Bonacosta Wine Guide | BevOry", metaDescription: "Meet Masi Bonacosta Valpolicella Classico, cherry notes, food matches and city prices on BevOry.",
  },
  "miraval-cotes": {
    description: "Miraval Cotes de Provence Rose comes from the Miraval estate in Provence, France, with winemaking by Famille Perrin. Its pale, dry rose brings red fruit, citrus and a saline edge.",
    story: "The estate sits among Provence's hills and vineyards. Miraval's rose focuses on the region's fresh, food-friendly side, with Famille Perrin handling the winemaking.",
    tastingNotes: [{ title: "Nose", description: "Wild strawberry and white flowers sit beside citrus peel." }, { title: "Finish", description: "A dry, lightly saline finish keeps the fruit in check." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a white-wine glass." }, { subheading: "Food", description: "Try it with tandoori prawns or watermelon-and-feta salad." }],
    pairingIdeas: [{ title: "Fresh plates", items: ["tandoori prawns", "watermelon-and-feta salad", "grilled fish", "paneer tikka"] }],
    whyChoose: "A dry Provence rose that balances pale fruit with a clean savoury edge.",
    faqs: [{ question: "Where is Miraval rose made?", answer: "It comes from the Miraval estate in Provence, France." }, { question: "Who makes Miraval wine?", answer: "Famille Perrin manages the winemaking for Miraval." }],
    finalVerdict: "Miraval rose is a crisp choice for seafood, warm weather and lightly spiced plates.",
    metaTitle: "Miraval Cotes de Provence Rose Guide | BevOry", metaDescription: "Explore Miraval Provence rose, red-fruit notes, Indian food pairings and city prices on BevOry.",
  },
  moletto: {
    description: "Moletto is a Veneto wine producer whose sparkling range includes Prosecco and rose. Glera gives the Prosecco its fresh apple-and-pear character.",
    story: "The Moletto estate sits in eastern Veneto, within reach of Prosecco country. Its sparkling bottles offer both the region's Glera-based white style and a separate rose choice.",
    tastingNotes: [{ title: "Prosecco", description: "Pear, green apple and white flowers come through on a lively mousse." }, { title: "Rose", description: "Red-berry aromas add a fruitier turn to the bubbles." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill thoroughly and pour into a tulip glass." }, { subheading: "Food", description: "Use Prosecco with pakora or try rose beside grilled prawns." }],
    pairingIdeas: [{ title: "With bubbles", items: ["vegetable pakora", "grilled prawns", "prosciutto", "salted almonds"] }],
    whyChoose: "A Veneto sparkling range with a classic Glera-led Prosecco option.",
    faqs: [{ question: "What grape is used in Moletto Prosecco?", answer: "Glera is the principal Prosecco grape." }, { question: "How should Moletto sparkling wine be served?", answer: "Serve it chilled in a tulip-shaped glass." }],
    finalVerdict: "Moletto's bubbles fit a snack table without asking for a formal occasion.",
    metaTitle: "Moletto Sparkling Wine Guide | BevOry", metaDescription: "Discover Moletto Prosecco and rose, fresh tasting notes, snack pairings and city prices on BevOry.",
  },
  "montes-limited": {
    description: "Montes Limited Selection is a Chilean wine range from Montes. Its Carmenere brings the variety's dark fruit and green-spice character into a full-bodied red.",
    story: "Montes helped build Chile's international reputation for premium wine. The Limited Selection line draws on regional fruit, including Carmenere from Colchagua Valley vineyards.",
    tastingNotes: [{ title: "Fruit", description: "Black plum and dark berries lead the Carmenere." }, { title: "Spice", description: "Pepper and a green herbal edge sit behind the fruit." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give the red a broad glass and a little air after opening." }, { subheading: "Food", description: "Serve with mutton seekh or smoky grilled peppers." }],
    pairingIdeas: [{ title: "Smoky food", items: ["mutton seekh", "grilled peppers", "lamb chops", "mushroom galouti"] }],
    whyChoose: "A Chilean Carmenere with enough fruit and spice for grilled food.",
    faqs: [{ question: "Where is Montes Limited Selection made?", answer: "It is a Chilean wine range from Montes; the Carmenere is linked to Colchagua Valley fruit." }, { question: "What does Carmenere taste like?", answer: "The Montes expression shows dark fruit with peppery, herbal notes." }],
    finalVerdict: "Montes Limited Selection Carmenere belongs beside the grill.",
    metaTitle: "Montes Limited Selection Wine Guide | BevOry", metaDescription: "Explore Montes Limited Selection Carmenere, Chilean tasting notes, pairings and city prices on BevOry.",
  },
  "montgras-day-one": {
    description: "MontGras Day One Chardonnay is a Chilean white wine from cool coastal Leyda in the San Antonio Valley. Its Chardonnay combines citrus and floral fruit with a rounded texture.",
    story: "MontGras built Day One around the first fruit selected from its vineyards. For Chardonnay, Leyda's maritime climate brings cooler growing conditions than Chile's warmer inland valleys.",
    tastingNotes: [{ title: "Aroma", description: "Citrus blossom and pineapple sit over a fresh fruit core." }, { title: "Texture", description: "A creamy middle meets balancing acidity." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill lightly; let the glass warm a little to show its texture." }, { subheading: "Food", description: "Try it with malai tikka or butter-poached fish." }],
    pairingIdeas: [{ title: "Soft textures", items: ["malai tikka", "butter-poached fish", "creamy mushroom pasta", "paneer in white gravy"] }],
    whyChoose: "A coastal Chilean Chardonnay that brings freshness to a creamy palate.",
    faqs: [{ question: "Where is MontGras Day One Chardonnay from?", answer: "It comes from Leyda in Chile's San Antonio Valley." }, { question: "Which food fits this Chardonnay?", answer: "Creamy chicken, paneer or fish dishes work with its rounded texture and acidity." }],
    finalVerdict: "Day One Chardonnay handles creamy dishes without losing its citrus lift.",
    metaTitle: "MontGras Day One Chardonnay Guide | BevOry", metaDescription: "Read about MontGras Day One Chardonnay from Leyda, tasting notes, pairings and city prices on BevOry.",
  },
  moonshine: {
    description: "Moonshine Meadery makes honey-based alcoholic drinks in Pune, India. The range pairs fermented honey with bold flavour ideas such as Guava Chilli, Grilled Pineapple and Coffee.",
    story: "The Pune meadery helped bring mead into India's contemporary drinks conversation. Its fruit and spice combinations move the ancient honey-fermented category toward familiar Indian flavours.",
    tastingNotes: [{ title: "Guava Chilli", description: "Guava sweetness meets a warm chilli edge." }, { title: "Grilled Pineapple", description: "Tropical fruit takes on a lightly caramelised note." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a wine glass and let the selected flavour lead." }, { subheading: "Food", description: "Guava Chilli suits paneer tikka; Grilled Pineapple fits barbecue chicken." }],
    pairingIdeas: [{ title: "With flavoured mead", items: ["paneer tikka", "barbecue chicken", "spicy corn ribs", "salted peanuts"] }],
    whyChoose: "An Indian mead range that uses honey as a base for assertive fruit and spice.",
    faqs: [{ question: "What is Moonshine Meadery's drink made from?", answer: "Mead is made by fermenting honey with water; Moonshine also makes flavoured expressions." }, { question: "Where is Moonshine Meadery based?", answer: "The meadery is based in Pune, India." }],
    finalVerdict: "Moonshine Meadery is a flavour-first introduction to honey wine.",
    metaTitle: "Moonshine Meadery Guide | BevOry", metaDescription: "Explore Moonshine's Pune-made meads, from Guava Chilli to Grilled Pineapple, and check city prices on BevOry.",
  },
  morosha: {
    description: "Morosha is a Ukrainian vodka brand built around Carpathian mountain-spring water and grain spirit. Its range includes expressions identified by the altitude of their water source.",
    story: "Morosha uses the Carpathian landscape as the central idea behind its vodka. The numbered variants point to differing mountain-spring sources rather than a change of drink category.",
    tastingNotes: [{ title: "Aroma", description: "A restrained grain note keeps the nose clean." }, { title: "Palate", description: "Soft texture and a short, lightly sweet finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a small glass or use in a dry Martini." }, { subheading: "Food", description: "Pair with pickled vegetables or smoked fish." }],
    pairingIdeas: [{ title: "Cold table", items: ["pickled vegetables", "smoked fish", "potato salad", "salted mushrooms"] }],
    whyChoose: "A Carpathian-water vodka with a soft, measured profile.",
    faqs: [{ question: "Where is Morosha vodka from?", answer: "Morosha is a Ukrainian vodka brand associated with Carpathian spring water." }, { question: "What do Morosha's numbers refer to?", answer: "They refer to the altitude of a mountain-spring water source used for an expression." }],
    finalVerdict: "Morosha suits a cold pour with savoury, salty food.",
    metaTitle: "Morosha Vodka Guide | BevOry", metaDescription: "Discover Morosha vodka's Carpathian-water story, serving ideas, pairings and city prices on BevOry.",
  },
  "patron-tequila": {
    description: "Patron El Alto is an aged tequila made from Blue Weber agave grown in the highlands of Jalisco, Mexico. The blend combines Reposado, Anejo and Extra Anejo tequilas.",
    story: "El Alto takes its name from the highland area around Atotonilco el Alto. Patron uses its agave-growing and oak-aging work there to build a richer expression than its unaged Silver tequila.",
    tastingNotes: [{ title: "Aroma", description: "Cooked agave, dried fruit and toasted wood." }, { title: "Palate", description: "Apricot, vanilla and almond follow the agave sweetness." }],
    howToEnjoy: [{ subheading: "Sip", description: "Pour neat in a small tulip glass; a single large cube works too." }, { subheading: "Food", description: "Try it with dark chocolate or slow-cooked lamb." }],
    pairingIdeas: [{ title: "After dinner", items: ["dark chocolate", "slow-cooked lamb", "roasted almonds", "caramel flan"] }],
    whyChoose: "A Jalisco highland tequila built for sipping rather than quick mixing.",
    faqs: [{ question: "What is in Patron El Alto?", answer: "It blends Reposado, Anejo and Extra Anejo tequilas made from Blue Weber agave." }, { question: "Where is Patron El Alto made?", answer: "It is made in the highlands of Jalisco, Mexico." }],
    finalVerdict: "El Alto is a slow sipping tequila with fruit, agave and polished oak.",
    metaTitle: "Patron El Alto Tequila Guide | BevOry", metaDescription: "Explore Patron El Alto's aged Jalisco tequila, tasting notes, pairings and city prices on BevOry.",
  },
  peppoli: {
    description: "Peppoli is a Chianti Classico red from Marchesi Antinori's Peppoli estate in Tuscany. Sangiovese leads the blend, supported by small amounts of other varieties.",
    story: "Antinori acquired the Peppoli estate in 1985, six centuries after the family's wine business began. The estate sits near San Casciano in Val di Pesa, with Sangiovese grown on gravelly, mineral-rich soils.",
    tastingNotes: [{ title: "Fruit", description: "Cherry and raspberry give the wine its lively centre." }, { title: "Finish", description: "A floral note and fine tannins keep the close fresh." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve slightly cool in a medium red-wine glass." }, { subheading: "Food", description: "Pair it with tomato pasta or lamb kebabs." }],
    pairingIdeas: [{ title: "Tuscan table", items: ["tomato pasta", "lamb kebabs", "mushroom pizza", "aged pecorino"] }],
    whyChoose: "A Sangiovese-led Chianti Classico with a clear, fruit-first Antinori style.",
    faqs: [{ question: "Who makes Peppoli Chianti Classico?", answer: "Marchesi Antinori makes it from its Peppoli estate in Tuscany." }, { question: "Which grape leads Peppoli?", answer: "Sangiovese is the main grape in the blend." }],
    finalVerdict: "Peppoli brings bright Tuscan red fruit to tomato-rich meals.",
    metaTitle: "Peppoli Chianti Classico Guide | BevOry", metaDescription: "Read about Antinori Peppoli Chianti Classico, Sangiovese notes, pairings and city prices on BevOry.",
  },
  "petrus-gouden": {
    description: "Petrus Gouden Tripel is a Belgian tripel from Brouwerij De Brabandere. The golden ale brings pale malt, fruity yeast character and a warming finish.",
    story: "De Brabandere is a family brewery in West Flanders. Gouden Tripel belongs to its Petrus range, showing a stronger Belgian blond style rather than the sour character of some other Petrus beers.",
    tastingNotes: [{ title: "Aroma", description: "Orchard fruit and light spice rise above the malt." }, { title: "Finish", description: "A rounded body ends with gentle bitterness and warmth." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve cool in a stemmed Belgian beer glass." }, { subheading: "Food", description: "Pair with tandoori chicken or aged gouda." }],
    pairingIdeas: [{ title: "Bold snacks", items: ["tandoori chicken", "aged gouda", "roasted cashews", "spiced pork skewers"] }],
    whyChoose: "A golden Belgian tripel for drinkers who like fruit and spice with their malt.",
    faqs: [{ question: "Who brews Petrus Gouden Tripel?", answer: "It is brewed by Brouwerij De Brabandere in Belgium." }, { question: "Is Petrus Gouden Tripel a sour beer?", answer: "No. It is a golden tripel, distinct from the sour styles elsewhere in the Petrus range." }],
    finalVerdict: "Gouden Tripel brings a fuller Belgian ale to a savoury snack table.",
    metaTitle: "Petrus Gouden Tripel Beer Guide | BevOry", metaDescription: "Meet Petrus Gouden Tripel, its Belgian beer profile, food pairings and city prices on BevOry.",
  },
};
