import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_48 = [
  ["cazcar", "Cazcar", "India", "Feni", "b9c2c616cb8bcd1e9579f140"],
  ["pedrera", "Pedrera", "Spain", "Wine", "1dc3c29f04bcbe03990a0f66"],
  ["la-madre", "La Madre", "Spain", "Vermouth", "cbbedfbdf3d1b7ccbcde6138"],
  ["satiwa", "Satiwa", "India", "Gin", "bb1f17bc63abd21a42d4d10b"],
  ["talli-tales", "Talli Tales", "India", "Ready-to-drink", "af366f3712265f45c1f02e8b"],
  ["hopout", "Hopout", "India", "Wine", "79ecc9bd3ee435c518b81315"],
  ["fuze", "Fuze", "India", "Wine Cocktail", "a0ea9b24d5d5468c77127461"],
  ["ginebra", "Ginebra", "Philippines", "Gin", "215fefdeade5451fdbbf1b4a"],
  ["deluze", "Deluze", "France", "Cognac", "21cbab9e7253dd132b0c3a47"],
  ["panic-button", "Panic Button", "Spain", "Wine", "98969037dacb9fe20142a261"],
  ["mythic-mountain", "Mythic Mountain", "Argentina", "Wine", "dce3ff68b133c520ad49f16c"],
  ["jacky", "Jacky", "France", "Wine", "c9bb526fb4dde6859db10d72"],
  ["bex-nahe", "Bex Nahe", "Germany", "Wine", "b86eb6aede2ec943f6419043"],
  ["borgo-alla", "Borgo Alla", "Italy", "Wine", "7fc6f7ce5d587ab28b131359"],
  ["just-roberto", "Just Roberto", "Italy", "Wine", "823688ae375ca6aedfcd4e2c"],
  ["sunny-beaches", "Sunny Beaches", "India", "Beer", "d99af9a1c5f1b3587986b26a"],
  ["eekh", "Eekh", "India", "Rum", "f99014ee56242b86f9b05b0e"],
  ["french-roots", "French Roots", "France", "Wine", "617f6d0e9529540298a04607"],
  ["secret-island-indian", "Secret Island Indian", "India", "Whisky", "89cef3cbd8b234e9f788de30"],
  ["black-fort", "Black Fort", "India", "Beer and Rum", "b26c54cb0ed3c42035f20c2e"],
  ["power-10000", "Power 10000", "India", "Beer", "4ce96dfacbc388a808dbd737"],
  ["milestone", "Milestone", "India", "Spirits", "7f7f85b1e7d5ffd45265405b"],
  ["pentagon", "Pentagon", "India", "Rum and Whisky", "ecc7dcf5bc2d51ebc4d9a9c9"],
  ["reserve-mont-redon", "Reserve Mont Redon", "France", "Wine", "f9789346c2cf5581f5d520d4"],
  ["bonachi", "Bonachi", "Italy", "Wine", "e4f0db0bfdef9b50c88c7db6"],
  ["mosaic", "Mosaic", "India", "Wine", "19818c00e27a53819a4ce134"],
  ["vina-temprana", "Vina Temprana", "Spain", "Wine", "76641f8746f0f18f84f7975d"],
  ["samara", "Samara", "India", "Wine", "9ef100006f200f87ab417abb"],
  ["madera", "Madera", "India", "Wine", "8c41a399d8cbf4d5711cdbe5"],
  ["moja", "Moja", "India", "Rum", "b393e6133b4b00760aef84ce"],
] as const;

// Source evidence is deliberately kept out of all public fields.
export const BRAND_SOURCES_BATCH_48: Record<string, string[]> = {
  cazcar: ["https://cazcars.com/"],
  pedrera: ["https://www.carm.es/web/pagina?IDCONTENIDO=898&IDTIPO=11&RASTRO=c32%24m1185%2C34701", "https://www.bodegavila.com/pedrera/"],
  "la-madre": ["https://lamadrevermouth.com/en/pages/nosotros"],
  satiwa: ["https://satiwagin.com/", "https://satiwagin.com/gogreenwithsatiwa/"],
  "talli-tales": ["https://in.linkedin.com/company/tallitales"],
  hopout: ["https://uniwine.in/crafted-wines/"],
  fuze: ["https://uniwine.in/faq/"],
  ginebra: ["https://www.ginebrasanmiguel.com/about-ginebra/"],
  deluze: ["https://cognacdeluze.com/our-history/"],
  "panic-button": ["https://mywinesnspirits.com/"],
  "mythic-mountain": ["https://mythiccellars.com/mythic-mountain/"],
  jacky: ["https://www.domainejackymarteau.fr/en/white-touraine-sauvignon/"],
  "bex-nahe": ["https://bexwinery.com/"],
  "borgo-alla": ["https://www.piccini1882.it/wp-content/uploads/2025/12/digitale-ENG-Geografico.pdf"],
  "just-roberto": ["https://vsf2002.wordpress.com/just-roberto/"],
  "sunny-beaches": ["https://www.icra.in/Rating/ShowRationalReportFilePdf/140530"],
  eekh: ["https://in.linkedin.com/company/madhushala-beverages-pvt-ltd", "https://barbundle.in/the-story-of-eekh-rum-indias-premium-rum-crafted-from-sugarcane/"],
  "french-roots": ["https://www.wineenthusiast.com/buying-guide/ginestet-2004-french-roots-merlot-vin-pays-doc/"],
  "secret-island-indian": ["https://sipawards.com/content/results/sipawards2024results.pdf", "https://www.thecheersgroup.com/"],
  "black-fort": ["https://somindia.com/product/black-fort-premium-lager-beer/"],
  "power-10000": ["https://nobel-spirits.com/som/", "https://nuwavebeverage.com/product/power-10000/"],
  milestone: ["https://somindia.com/product/milestone-100-premium-whisky/", "https://www.icra.in/Rating/ShowRationalReportFilePdf/140530"],
  pentagon: ["https://somindia.com/product/pentagon-gold-edition-whisky/", "https://somindia.com/wp-content/uploads/2024/11/som-letter-of-offer.pdf"],
  "reserve-mont-redon": ["https://www.eschervins.ch/en_US/products/chateau-mont-redon-reserve-mont-redon-red-2024-75cl-5292"],
  bonachi: ["https://www.bonacchi.it/en/", "https://www.bonacchi.it/images/schede_tecniche/bonacchi_brunello_di_montalcino.pdf"],
  mosaic: ["https://sulavineyards.com/files/0724/Annual%20Report%2023-24.pdf"],
  "vina-temprana": ["https://tmarchettico.com/wp-content/uploads/Vina-Temprana-Tempranillo-ST.pdf"],
  samara: ["https://sulavineyards.com/files/0724/Annual%20Report%2023-24.pdf"],
  madera: ["https://sulavineyards.com/files/0724/Annual%20Report%2023-24.pdf"],
  moja: ["https://www.nvgroup.co.in/products/moja-rum"],
};

export const BRAND_LOGOS_BATCH_48: Record<string, string> = {
  deluze: "https://cognacdeluze.com/wp-content/uploads/2021/11/blason-deluze-new-400x271.png",
};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_48: Record<string, BrandPublicContent> = {
  cazcar: guide("Cazcar", "Feni", {
    description: "Cazcar makes cashew-apple feni at its family distillery in Nanora, Goa. The Bhakta family keeps the local fruit and traditional distillation at the centre of the range.",
    story: "The distillery began in 1969, and Gurudatta and Rupa Bhakta carried the family operation into its second generation. Nanora lies north of Panaji, within the Goan landscape where cashew feni is made.",
    notes: ["Cashew fruit", "A pungent, ripe-fruit aroma is part of feni's character.", "Finish", "A dry, earthy finish follows the fruit."],
    serve: "Pour a small measure over ice or add soda and a squeeze of lime.",
    food: "Bring out Goan prawn balchao, recheado fish or roasted cashews.",
    pairings: ["Goan prawn balchao", "recheado fish", "roasted cashews"],
    whyChoose: "A family-made feni rooted in Nanora's cashew harvest.",
    faq: ["Where is Cazcar made?", "At the Bhakta family's distillery in Nanora, Goa.", "What fruit is used for Cazcar feni?", "Cashew apples are the fruit behind its caju feni."],
    finalVerdict: "Cazcar belongs on a Goan table, especially with seafood and lime.",
    metaDescription: "Meet Cazcar feni from Nanora, Goa. Explore cashew-fruit character, Goan food pairings and city prices on BevOry.",
  }),
  pedrera: guide("Pedrera", "Wine", {
    description: "Pedrera is a Spanish wine label associated with Bodegas Juan Gil in Jumilla, Murcia. Its range includes Monastrell-led red wine as well as white and rosado bottlings.",
    story: "Jumilla's dry climate and stony vineyards have long suited Monastrell. Pedrera takes that local grape beyond the regional red, with lighter-coloured wines under the same label.",
    notes: ["Monastrell red", "Dark berries and a savoury, sun-warmed edge shape the red's character.", "Rosado", "Red-fruit freshness gives the rosado a lighter register."],
    serve: "Serve the red just below room temperature; chill the white and rosado.",
    food: "Try the red with mutton seekh or grilled aubergine; pour rosado with tomato chaat.",
    pairings: ["mutton seekh", "grilled aubergine", "tomato chaat"],
    whyChoose: "A compact introduction to Jumilla, from Monastrell red to rosado.",
    faq: ["Where is Pedrera wine from?", "Pedrera is linked to Bodegas Juan Gil in Jumilla, Murcia.", "Is Pedrera only a red wine?", "No. The range also includes white and rosado wines."],
    finalVerdict: "Pedrera brings the warmth of Jumilla to a table built around bold, savoury food.",
    metaDescription: "Discover Pedrera wines from Jumilla, including Monastrell red and rosado. See pairings and city prices on BevOry.",
  }),
  "la-madre": guide("La Madre", "Vermouth", {
    description: "La Madre is a Spanish vermouth range spanning red, white, rosé and reserve styles. Wine is blended with an herbal essence made by macerating botanicals in ceramic amphorae.",
    story: "La Madre grew from a wish to take Spanish vermouth beyond the familiar red aperitif. The team ages its botanical essence in barrels for several months before blending it with wine.",
    notes: ["Red vermouth", "Herbal bitterness meets rounded sweetness in the red style.", "Rosé vermouth", "A brighter, fruit-led aperitif with an aromatic herbal edge."],
    serve: "Serve over ice with an orange slice; use the drier styles in a Martini-style drink.",
    food: "Put out masala olives, patatas bravas or chilli paneer before dinner.",
    pairings: ["masala olives", "patatas bravas", "chilli paneer"],
    whyChoose: "A vermouth house willing to make room for rosé and dry styles alongside red.",
    faq: ["How is La Madre vermouth made?", "Its botanicals are macerated in ceramic amphorae, barrel-aged and blended with wine.", "Does La Madre make rosé vermouth?", "Yes. Rosé sits alongside red, white and other aperitif styles."],
    finalVerdict: "La Madre makes the vermouth hour more interesting without leaving the aperitif tradition behind.",
    metaDescription: "Explore La Madre vermouth, from red to rosé. Find serving ideas, tapas pairings and city prices on BevOry.",
  }),
  satiwa: guide("Satiwa", "Gin", {
    description: "Satiwa is a Goa-made hemp craft gin built around juniper and hemp seed botanicals. Its range includes fruit-led Passion and Berry expressions.",
    story: "The brand takes its name from Cannabis sativa and places hemp in a gin recipe rather than a novelty garnish. Citrus peel and Indian spices sit beside the seed botanical in its Goa-made profile.",
    notes: ["Original style", "Juniper, orange peel and herbal spice lead the aroma.", "Fruit expressions", "Passion and Berry move the range toward brighter fruit while retaining a gin base."],
    serve: "Use plenty of ice, tonic and a thin orange slice; keep the fruit expressions lightly mixed.",
    food: "Pair with tandoori prawns, lemon-pepper paneer or salted peanuts.",
    pairings: ["tandoori prawns", "lemon-pepper paneer", "salted peanuts"],
    whyChoose: "An Indian gin that makes hemp seed a genuine part of its botanical identity.",
    faq: ["Where is Satiwa gin made?", "Satiwa is made in Goa, India.", "What is distinctive about Satiwa?", "Hemp seed joins juniper, citrus and spice in the brand's gin profile."],
    finalVerdict: "Satiwa is most at home in a long, cold gin and tonic with spicy coastal food.",
    metaDescription: "Explore Goa-made Satiwa hemp craft gin. Find botanical notes, G&T pairings and city prices on BevOry.",
  }),
  "talli-tales": guide("Talli Tales", "Cocktail", {
    description: "Talli Tales is an Indian ready-to-drink cocktail label with Cosmopolitan and Long Island Iced Tea variants. The Jaipur-based company introduced its canned cocktail range in Goa.",
    story: "Talli Tales entered the market in 2023 with familiar bar orders in a packaged format. The idea was to bring a mixed-drink occasion out of the cocktail bar and into a chilled, ready-to-pour can.",
    notes: ["Cosmopolitan", "A tart cranberry-and-citrus direction defines this cocktail style.", "Long Island Iced Tea", "Cola and citrus shape the recognisable long-drink profile."],
    serve: "Chill thoroughly and pour over fresh ice in a highball glass.",
    food: "Serve with peri-peri fries, chicken tikka or spicy corn chaat.",
    pairings: ["peri-peri fries", "chicken tikka", "spicy corn chaat"],
    whyChoose: "Recognisable cocktail formats without measuring a set of spirits and mixers.",
    faq: ["What does Talli Tales make?", "Ready-to-drink cocktails including Cosmopolitan and Long Island Iced Tea.", "Where did Talli Tales launch its canned drinks?", "The Jaipur-based label launched its range in Goa."],
    finalVerdict: "Talli Tales suits an easy cocktail pour when the food, rather than the mixing, is the main event.",
    metaDescription: "Explore Talli Tales canned cocktails, from Cosmo to Long Island Iced Tea. See serving ideas and city prices on BevOry.",
  }),
  hopout: guide("Hopout", "Wine", {
    description: "Hopout is a crafted hopped wine from India's Uniwine portfolio. It brings a beer-associated aromatic ingredient, hops, into a wine-based drink.",
    story: "Uniwine puts Hopout among its crafted wines rather than its conventional varietal labels. The crossover is the point: wine structure meets the lifted aroma associated with hops.",
    notes: ["Hops", "A floral, herbal aroma gives the wine its unusual opening.", "Wine base", "Fruit and acidity keep the drink closer to wine than beer."],
    serve: "Chill well and use a stemmed wine glass rather than a beer mug.",
    food: "Match with masala fries, grilled corn or chilli paneer.",
    pairings: ["masala fries", "grilled corn", "chilli paneer"],
    whyChoose: "A hop-accented wine for drinkers curious about the space between wine and beer.",
    faq: ["Is Hopout a beer?", "No. Uniwine lists Hopout as a crafted hopped wine.", "How should Hopout be served?", "Serve chilled in a wine glass with salty, spicy snacks."],
    finalVerdict: "Hopout is a neat change of pace for a casual snack table.",
    metaDescription: "Meet Hopout, Uniwine's hopped wine. Explore its herbal profile, snack pairings and city prices on BevOry.",
  }),
  fuze: guide("Fuze", "Wine Cocktail", {
    description: "Fuze is a wine-based cocktail label from Uniwine in India. Its sangria-style drink takes wine toward a chilled, fruit-forward serve.",
    story: "Uniwine works across conventional wines and ready-to-drink wine formats. Fuze sits on the more playful side of that range, built for a pour over ice rather than a formal tasting flight.",
    notes: ["Fruit", "Sangria-style fruit comes forward first.", "Finish", "A wine-led finish keeps the fruit from reading like a soft drink."],
    serve: "Chill before opening and pour over ice with orange or apple slices.",
    food: "Bring out chilli cheese toast, peri-peri paneer or spiced olives.",
    pairings: ["chilli cheese toast", "peri-peri paneer", "spiced olives"],
    whyChoose: "A ready-to-pour way into the familiar fruit-and-wine character of sangria.",
    faq: ["What is Fuze Sangria?", "It is a wine-based, sangria-style drink in Uniwine's range.", "Should Fuze be chilled?", "Yes. A cold pour over ice suits its fruit-led style."],
    finalVerdict: "Fuze fits a relaxed table of salty snacks and cold glasses.",
    metaDescription: "Discover Fuze sangria-style wine cocktail. Find fruit notes, snack pairings and city prices on BevOry.",
  }),
  ginebra: guide("Ginebra", "Gin", {
    description: "Ginebra San Miguel is a Philippine gin brand made by Ginebra San Miguel Inc. The range includes Ginebra San Miguel and a Premium Gin expression.",
    story: "The brand's roots go back to nineteenth-century Manila, where gin became part of local drinking culture. Today Ginebra San Miguel remains a prominent name in Philippine spirits.",
    notes: ["Juniper", "The familiar pine-like gin aroma anchors the pour.", "Citrus", "A bright citrus edge lightens the spirit in a long drink."],
    serve: "Mix with cold tonic or citrus soda in a tall glass packed with ice.",
    food: "Pair with chicken inasal, pork sisig or chilli-garlic prawns.",
    pairings: ["chicken inasal", "pork sisig", "chilli-garlic prawns"],
    whyChoose: "A long-running Philippine gin name with an accessible mixed-drink style.",
    faq: ["Where is Ginebra San Miguel from?", "It is a Philippine gin brand associated with Manila's spirits history.", "Who makes Ginebra San Miguel?", "Ginebra San Miguel Inc. makes the brand."],
    finalVerdict: "Ginebra works well as a cold, citrus-led long drink beside assertive food.",
    metaDescription: "Explore Philippine gin brand Ginebra San Miguel. See serving ideas, food pairings and city prices on BevOry.",
  }),
  deluze: guide("Deluze", "Cognac", {
    description: "De Luze is a French Cognac house now run by the Boinaud family in Angeac-Champagne. Its range moves from VS and VSOP to XO and older expressions.",
    story: "Alfred De Luze established A. De Luze & Fils in 1822 after working in wine and spirits trade on both sides of the Atlantic. The Boinaud family acquired the house in 2006 and continues its Cognac production in Charente.",
    notes: ["Younger expressions", "Fresh grape-fruit and light oak are the useful starting points.", "Older expressions", "Longer-aged Cognac moves toward dried fruit and baking-spice depth."],
    serve: "Pour into a tulip glass; add a single cube to a younger expression if preferred.",
    food: "Try with almond halwa, dark chocolate or walnut cake.",
    pairings: ["almond halwa", "dark chocolate", "walnut cake"],
    whyChoose: "An 1822 Cognac name carried forward by a family distiller in Charente.",
    faq: ["Who owns De Luze Cognac?", "The Boinaud family has owned the house since 2006.", "Where is De Luze based?", "The Cognac house is based in Angeac-Champagne, France."],
    finalVerdict: "De Luze offers a clear route from a young Cognac pour to a slower after-dinner glass.",
    metaDescription: "Explore De Luze Cognac from Charente. Discover its 1822 history, serving ideas, dessert pairings and city prices on BevOry.",
  }),
  "panic-button": guide("Panic Button", "Wine", {
    description: "Panic Button is a Spanish wine label sold in red and white styles. One of its white blends combines Sauvignon Blanc and Viognier.",
    story: "The label's red-and-white range places a fragrant grape partnership beside a more traditional red-wine choice. Sauvignon Blanc contributes the brisk side of the white blend; Viognier brings fuller aromatics.",
    notes: ["White blend", "Citrus and orchard-fruit freshness meet a more floral note.", "Red style", "Ripe red fruit provides a fuller, food-friendly contrast."],
    serve: "Chill the white; let the red sit slightly below room temperature before pouring.",
    food: "Put the white with tandoori fish and the red with mushroom tikka or lamb chops.",
    pairings: ["tandoori fish", "mushroom tikka", "lamb chops"],
    whyChoose: "An approachable Spanish red-and-white choice with a distinctive Sauvignon-Viognier white.",
    faq: ["What grapes are in Panic Button white wine?", "A listed white blend combines Sauvignon Blanc and Viognier.", "Does Panic Button make red wine?", "Yes. The label is sold in both red and white styles."],
    finalVerdict: "Panic Button offers two straightforward table wines with different food strengths.",
    metaDescription: "Compare Panic Button Spanish red and Sauvignon-Viognier white. See pairing ideas and city prices on BevOry.",
  }),
  "mythic-mountain": guide("Mythic Mountain", "Wine", {
    description: "Mythic Mountain is an Argentine wine label associated with Mythic Cellars in Mendoza. The range includes Malbec and white-wine expressions.",
    story: "Mendoza's Andean setting gives the label its mountain reference. Mythic Cellars uses the region's signature Malbec alongside whites that show a different side of the same wine country.",
    notes: ["Malbec", "Dark plum and black cherry lead into a supple, savoury finish.", "White style", "Citrus and orchard fruit offer a brighter counterpoint."],
    serve: "Give the red a broad wine glass; serve the white properly chilled.",
    food: "Try Malbec with mutton seekh or grilled mushrooms and the white with tandoori fish.",
    pairings: ["mutton seekh", "grilled mushrooms", "tandoori fish"],
    whyChoose: "A Mendoza label that pairs the region's Malbec reputation with accessible whites.",
    faq: ["Where is Mythic Mountain wine from?", "Mythic Mountain comes from Mendoza, Argentina.", "Does Mythic Mountain make Malbec?", "Yes. Malbec is one of the wines in the range."],
    finalVerdict: "Mythic Mountain is an easy Mendoza starting point for red and white drinkers alike.",
    metaDescription: "Explore Mythic Mountain wines from Mendoza, including Malbec. Find pairings and city prices on BevOry.",
  }),
  jacky: guide("Jacky", "Wine", {
    description: "Jacky Marteau is a family wine estate in Pouillé, in France's Touraine region. Its white Touraine wine is made from Sauvignon Blanc.",
    story: "The Marteau family works in the Loire Valley's Touraine appellation, where Sauvignon Blanc is a familiar white grape. Ludivine Marteau carries the family's estate forward.",
    notes: ["Aroma", "Citrus and green fruit lead the Sauvignon Blanc nose.", "Palate", "Brisk acidity leaves a clean, fresh finish."],
    serve: "Chill the Sauvignon Blanc and pour into a small white-wine glass.",
    food: "Serve with tandoori fish, goat cheese or a coriander-lime prawn starter.",
    pairings: ["tandoori fish", "goat cheese", "coriander-lime prawns"],
    whyChoose: "A family-made Loire Sauvignon with the freshness Touraine drinkers look for.",
    faq: ["Where is Jacky Marteau wine made?", "At the family estate in Pouillé, Touraine, France.", "Which grape is used in the white Touraine?", "The white Touraine wine is Sauvignon Blanc."],
    finalVerdict: "Jacky Marteau's white is a good match for fish, herbs and the first course.",
    metaDescription: "Explore Jacky Marteau Touraine Sauvignon Blanc. See Loire Valley background, pairings and city prices on BevOry.",
  }),
  "bex-nahe": guide("Bex Nahe", "Wine", {
    description: "Bex is a German Riesling label drawing on grapes from the Nahe wine region. The wine keeps Riesling's fruit and acidity in focus.",
    story: "The Nahe runs between more famous German wine areas but has its own mix of vineyard soils and slopes. Bex uses the regional name to put that origin at the front of its Riesling identity.",
    notes: ["Aroma", "Peach, apricot and citrus make a bright first impression.", "Palate", "A mineral note and firm acidity give the fruit a clean outline."],
    serve: "Serve well chilled in a white-wine glass.",
    food: "Pour with chilli prawns, paneer tikka or Thai green curry.",
    pairings: ["chilli prawns", "paneer tikka", "Thai green curry"],
    whyChoose: "A fruit-bright Nahe Riesling that handles spice particularly well.",
    faq: ["What grape is Bex Nahe made from?", "Bex Nahe is a Riesling wine.", "Where is the Nahe wine region?", "Nahe is a wine-growing region in Germany."],
    finalVerdict: "Bex Nahe earns its place with spicy starters and seafood.",
    metaDescription: "Discover Bex Nahe Riesling from Germany. Find peach-and-citrus notes, spicy food pairings and city prices on BevOry.",
  }),
  "borgo-alla": guide("Borgo Alla", "Wine", {
    description: "Borgo Alla is an Italian wine label in the Geografico range associated with Piccini. Bottlings include Chianti and Toscana reds.",
    story: "Geografico began as a Tuscan growers' project and later became part of the Piccini wine group. Chianti's Sangiovese tradition gives the Borgo Alla red range its regional anchor.",
    notes: ["Chianti", "Red cherry and herbal notes suit the grape's lively acidity.", "Toscana red", "A rounder red-fruit impression makes for an easy table wine."],
    serve: "Pour slightly cool into an everyday red-wine glass.",
    food: "Try with tomato pasta, mushroom masala or grilled lamb.",
    pairings: ["tomato pasta", "mushroom masala", "grilled lamb"],
    whyChoose: "A route into Tuscan reds through Chianti and Toscana bottlings.",
    faq: ["Is Borgo Alla a Tuscan wine?", "The range includes Tuscan Chianti and Toscana red wines.", "Which group is behind Borgo Alla?", "The label is associated with Geografico in the Piccini group."],
    finalVerdict: "Borgo Alla is best treated as a food wine, with tomato, herbs and savoury dishes nearby.",
    metaDescription: "Explore Borgo Alla Chianti and Toscana wines. Find Tuscan red-wine pairings and city prices on BevOry.",
  }),
  "just-roberto": guide("Just Roberto", "Wine", {
    description: "Just Roberto is an Italian wine label covering Prosecco, Pinot Grigio, Chianti and Merlot. The range moves between northern sparkling and white styles and central Italian reds.",
    story: "Just Roberto brings several familiar Italian wine names under one label. Prosecco and Pinot Grigio offer a fresh opening; Chianti and Merlot fill the red-wine side of the table.",
    notes: ["Prosecco", "Light fruit and lively bubbles give the sparkling wine its aperitif feel.", "Chianti", "Red cherry and a savoury edge suit tomato-led dishes."],
    serve: "Chill Prosecco and Pinot Grigio; pour the reds just below room temperature.",
    food: "Pair Prosecco with pakora, Pinot Grigio with grilled prawns and Chianti with pasta arrabbiata.",
    pairings: ["pakora", "grilled prawns", "pasta arrabbiata"],
    whyChoose: "A quick tour of Italian wine styles under one recognisable label.",
    faq: ["Does Just Roberto make sparkling wine?", "Yes. Prosecco is part of its range.", "What red wines are in the Just Roberto range?", "Chianti and Merlot appear alongside the white and sparkling wines."],
    finalVerdict: "Just Roberto makes most sense when the bottle follows the course being served.",
    metaDescription: "Compare Just Roberto Prosecco, Pinot Grigio, Chianti and Merlot. See pairings and city prices on BevOry.",
  }),
  "sunny-beaches": guide("Sunny Beaches", "Beer", {
    description: "Sunny Beaches is a mild Indian beer label from SOM Distilleries and Breweries. It joined the company's beer portfolio in Karnataka in 2025.",
    story: "SOM introduced Sunny Beaches alongside an expansion of its beer and spirits portfolio. The beer first entered the Karnataka market, where the company also sells its Woodpecker label.",
    notes: ["Aroma", "Grain and light hop notes lead the beer profile.", "Finish", "A crisp finish keeps it suited to a cold, quick pour."],
    serve: "Chill well and pour into a clean beer glass.",
    food: "Match with masala peanuts, fish fry or chilli potato.",
    pairings: ["masala peanuts", "fish fry", "chilli potato"],
    whyChoose: "A newer SOM beer for a straightforward cold-beer occasion.",
    faq: ["Who makes Sunny Beaches beer?", "Sunny Beaches is a SOM Distilleries and Breweries label.", "How should Sunny Beaches be served?", "Serve cold in a clean beer glass with savoury snacks."],
    finalVerdict: "Sunny Beaches is built for the simple pleasure of cold beer and salty food.",
    metaDescription: "Explore Sunny Beaches beer from SOM. Find serving ideas, snack pairings and city prices on BevOry.",
  }),
  eekh: guide("Eekh", "Rum", {
    description: "Eekh is an Indian rum made from sugarcane juice by Madhushala Beverages. Its agricultural-rum approach puts cane character ahead of a heavy molasses profile.",
    story: "Founders Abhijeet Roy and Simran Singh built Eekh around the cane itself; the name recalls the Hindi word for sugarcane. The spirit adds an Indian voice to the fresh-cane rum tradition.",
    notes: ["Cane", "Fresh, grassy cane notes rise above the glass.", "Palate", "Fruit and a dry herbal edge follow the initial sweetness."],
    serve: "Try a small neat pour, then make a highball with soda and lime.",
    food: "Serve with pepper prawns, pork vindaloo or grilled pineapple.",
    pairings: ["pepper prawns", "pork vindaloo", "grilled pineapple"],
    whyChoose: "A cane-juice rum with a deliberately Indian sense of place.",
    faq: ["What is Eekh rum made from?", "Eekh is made from sugarcane juice.", "Who is behind Eekh?", "Abhijeet Roy and Simran Singh founded the brand through Madhushala Beverages."],
    finalVerdict: "Eekh rewards a lime-led serve that leaves its cane character intact.",
    metaDescription: "Discover Eekh Indian sugarcane-juice rum. Explore its grassy profile, Goan-style pairings and city prices on BevOry.",
  }),
  "french-roots": guide("French Roots", "Wine", {
    description: "French Roots is a French wine label with Merlot and Sauvignon Blanc bottlings from Pays d'Oc. The range draws on the Languedoc region's broad choice of grapes.",
    story: "Pays d'Oc gives growers in southern France room to bottle varietal wines outside a narrower appellation recipe. French Roots uses that flexibility to put grape names, rather than a village, in front.",
    notes: ["Merlot", "Plum and soft red fruit give the red an easy shape.", "Sauvignon Blanc", "Citrus and green-fruit freshness mark the white."],
    serve: "Chill the Sauvignon Blanc; serve Merlot a touch below room temperature.",
    food: "Set the white beside tandoori fish and the red beside paneer tikka or lamb kofta.",
    pairings: ["tandoori fish", "paneer tikka", "lamb kofta"],
    whyChoose: "Two familiar grapes viewed through southern France's Pays d'Oc.",
    faq: ["Where is French Roots wine from?", "Its listed wines come from Pays d'Oc in southern France.", "Which grapes appear in French Roots wines?", "The range includes Merlot and Sauvignon Blanc bottlings."],
    finalVerdict: "French Roots is a useful red-or-white choice for a mixed dinner table.",
    metaDescription: "Explore French Roots Merlot and Sauvignon Blanc from Pays d'Oc. Find pairings and city prices on BevOry.",
  }),
  "secret-island-indian": guide("Secret Island Indian", "Whisky", {
    description: "Secret Island Indian is an Indian single malt whisky associated with the Cheers Group. It is a malt-whisky label rather than a blended Scotch expression.",
    story: "The label belongs to India's expanding single-malt conversation, where domestic makers work with malt spirit in a warmer maturation climate. The Secret Island name keeps its origin Indian even as it borrows the language of discovery.",
    notes: ["Malt", "Cereal sweetness forms the base of the whisky's style.", "Oak", "Wood spice provides the contrast to the malt."],
    serve: "Start with a neat pour in a small tulip glass; add a few drops of water if desired.",
    food: "Try with tandoori mushrooms, roasted almonds or dark chocolate.",
    pairings: ["tandoori mushrooms", "roasted almonds", "dark chocolate"],
    whyChoose: "An Indian single malt for drinkers exploring beyond familiar Scotch labels.",
    faq: ["Is Secret Island an Indian whisky?", "Yes. Secret Island is listed as an Indian single malt.", "Is Secret Island a blended whisky?", "The named expression is a single malt rather than a blend."],
    finalVerdict: "Secret Island is best introduced slowly, with a small neat glass and savoury food.",
    metaDescription: "Explore Secret Island Indian single malt whisky. Find serving ideas, food pairings and city prices on BevOry.",
  }),
  "black-fort": guide("Black Fort", "Beer and Rum", {
    description: "Black Fort is an Indian drinks label in SOM Distilleries and Breweries' portfolio. Its listings include beer and rum, two distinct drinks under one name.",
    story: "SOM's Black Fort beer sits in the company's brewing range. The rum label extends the name beyond the brewery, so the beer and spirit deserve separate glasses and serving styles.",
    notes: ["Premium lager", "Grain and hop notes lead a crisp beer profile.", "Matured rum", "A darker, fuller spirit profile suits a slower pour."],
    serve: "Chill the beer; pour the rum over ice or add cola and lime.",
    food: "Try beer with chilli potato and rum with pepper chicken or roasted peanuts.",
    pairings: ["chilli potato", "pepper chicken", "roasted peanuts"],
    whyChoose: "A single Indian label spanning brewery and spirits shelves.",
    faq: ["Is Black Fort only a beer?", "No. Black Fort appears on both beer and rum listings.", "Who makes Black Fort?", "It is part of SOM Distilleries and Breweries' portfolio."],
    finalVerdict: "Black Fort changes character with the bottle: cold beer for snacks, rum for a longer sit-down.",
    metaDescription: "Explore Black Fort beer and rum from SOM. Compare serving styles, food pairings and city prices on BevOry.",
  }),
  "power-10000": guide("Power 10000", "Beer", {
    description: "Power 10000 is a strong beer label from SOM Distilleries and Breweries in India. It belongs to the company's beer portfolio rather than its whisky or rum range.",
    story: "SOM has built a broad Indian beer business, and Power 10000 is one of its strength-led labels. The name is direct; the useful distinction is that this is a strong beer, not a spirit.",
    notes: ["Malt", "Grain sweetness gives the beer its body.", "Finish", "A firmer finish than a light lager stands up to spicy snacks."],
    serve: "Serve properly chilled in a clean glass and pour steadily to control the head.",
    food: "Match with masala peanuts, chicken 65 or chilli paneer.",
    pairings: ["masala peanuts", "chicken 65", "chilli paneer"],
    whyChoose: "A strong-beer option within SOM's Indian brewing range.",
    faq: ["What kind of drink is Power 10000?", "Power 10000 is a strong beer.", "Who makes Power 10000?", "It is a SOM Distilleries and Breweries label."],
    finalVerdict: "Power 10000 suits a cold glass and the boldest snacks on the table.",
    metaDescription: "Explore Power 10000 strong beer from SOM. See snack pairings, serving tips and city prices on BevOry.",
  }),
  milestone: guide("Milestone", "Spirits", {
    description: "Milestone is an Indian drinks label in SOM Distilleries and Breweries' spirits portfolio. The wider range covers whisky, vodka and brandy.",
    story: "SOM launched Milestone 100 whisky in Bhopal in 2013, blending Indian grain spirit with Scotch malt. Milestone Blue and vodka expressions later broadened the name beyond that first whisky.",
    notes: ["Whisky range", "Malt-like cereal and oak notes fit the whisky side of the label.", "Vodka range", "A cleaner, lighter profile makes the vodka a mixer-friendly option."],
    serve: "Use a short glass for whisky; chill vodka before mixing with soda or citrus.",
    food: "Pair whisky with tandoori mushrooms and vodka drinks with salted peanuts or chilli prawns.",
    pairings: ["tandoori mushrooms", "salted peanuts", "chilli prawns"],
    whyChoose: "A SOM label with both whisky and vodka choices for different serves.",
    faq: ["Is Milestone only a whisky brand?", "No. Milestone listings also include vodka.", "Who makes Milestone spirits?", "Milestone is in SOM Distilleries and Breweries' portfolio."],
    finalVerdict: "Milestone is best chosen by spirit first, then by the food and mixer on hand.",
    metaDescription: "Compare Milestone whisky and vodka from SOM. Find serving styles, food pairings and city prices on BevOry.",
  }),
  pentagon: guide("Pentagon", "Rum", {
    description: "Pentagon is an Indian SOM Distilleries and Breweries label spanning rum and whisky. Rum listings include XO Premium; the company also names Pentagon Gold Edition Whisky in its range.",
    story: "SOM launched Pentagon whisky in northern India in 2019, extending its spirits business beyond the Milestone label. The same name appears on rum, so a Pentagon bottle may be either spirit.",
    notes: ["XO rum", "Cane juice and molasses are blended for the rum's base.", "Gold Edition whisky", "Highland Scotch malt and Sharbati wheat shape the whisky's grain-led style."],
    serve: "Try the rum over a large ice cube; give the whisky a separate neat pour or soda highball.",
    food: "Put out pepper chicken, roasted cashews or caramel pudding.",
    pairings: ["pepper chicken", "roasted cashews", "caramel pudding"],
    whyChoose: "A SOM spirits label with both rum and whisky on the shelf.",
    faq: ["Is Pentagon a rum or whisky?", "SOM uses Pentagon for both rum and whisky expressions.", "Which company is behind Pentagon?", "Pentagon appears in SOM Distilleries and Breweries' spirits portfolio."],
    finalVerdict: "Pentagon needs a bottle-specific choice: its rum and whisky are different drinks.",
    metaDescription: "Compare Pentagon rum and whisky from SOM. Find serving ideas, food pairings and city prices on BevOry.",
  }),
  "reserve-mont-redon": guide("Reserve Mont Redon", "Wine", {
    description: "Réserve Mont-Redon is a southern Rhône wine from the Château Mont-Redon family estate. The red Côtes du Rhône bottling draws on the region's Grenache-led tradition.",
    story: "Mont-Redon is closely tied to Châteauneuf-du-Pape, but the family also bottles Côtes du Rhône wines under the Réserve name. The red offers a more everyday entry into the house's Rhône identity.",
    notes: ["Fruit", "Red berries and darker plum fruit give the wine its centre.", "Spice", "A dry herbal edge follows the fruit."],
    serve: "Pour a little below room temperature into a medium red-wine glass.",
    food: "Try with lamb rogan josh, roasted aubergine or herb-roast chicken.",
    pairings: ["lamb rogan josh", "roasted aubergine", "herb-roast chicken"],
    whyChoose: "Southern Rhône character from a family known for Mont-Redon.",
    faq: ["Where is Réserve Mont-Redon from?", "The red is a Côtes du Rhône wine from southern France.", "Is Réserve Mont-Redon a Châteauneuf-du-Pape wine?", "The Réserve red is sold as Côtes du Rhône, distinct from the estate's Châteauneuf-du-Pape."],
    finalVerdict: "Réserve Mont-Redon belongs beside herb-led roasts and rich Indian gravies.",
    metaDescription: "Discover Réserve Mont-Redon Côtes du Rhône red. Explore Rhône flavours, pairings and city prices on BevOry.",
  }),
  bonachi: guide("Bonachi", "Wine", {
    description: "Bonachi is a Tuscan wine listing associated with Cantine Bonacchi and its Brunello di Montalcino bottling. Brunello is made from Sangiovese grown around Montalcino.",
    story: "The Bonacchi family works across Tuscany, including wines from the Montalcino area. Brunello gives its Sangiovese grapes a longer, more structured expression than an everyday Tuscan red.",
    notes: ["Fruit", "Red cherry and dried-fruit notes give Brunello its depth.", "Structure", "Firm tannins and savoury spice carry a long finish."],
    serve: "Open ahead of dinner and pour into a generous red-wine glass.",
    food: "Serve with lamb rogan josh, mushroom risotto or aged pecorino.",
    pairings: ["lamb rogan josh", "mushroom risotto", "aged pecorino"],
    whyChoose: "A Tuscan Sangiovese wine made for a substantial dinner.",
    faq: ["Who makes Bonachi Brunello?", "Cantine Bonacchi is the Tuscan producer associated with the Brunello listing.", "What grape makes Brunello di Montalcino?", "Brunello di Montalcino is made from Sangiovese."],
    finalVerdict: "Bonacchi's Brunello calls for time in the glass and a rich main course.",
    metaDescription: "Explore Bonachi, the Cantine Bonacchi Brunello di Montalcino listing. Find Sangiovese pairings and city prices on BevOry.",
  }),
  mosaic: guide("Mosaic", "Wine", {
    description: "Mosaic is an Indian wine label from Sula Vineyards in Nashik, Maharashtra. The range includes both red and white blends.",
    story: "Sula helped bring Nashik wines to a national audience, and Mosaic uses the region's fruit in easy-drinking blends. Its red and white bottles are intended for different courses rather than a single fixed flavour profile.",
    notes: ["Red", "Ripe red fruit gives the blend a soft, casual profile.", "White", "Citrus and orchard fruit make the white a fresh counterpoint."],
    serve: "Chill the white well; pour the red slightly cool.",
    food: "Match the white with tandoori fish and the red with paneer tikka or pasta arrabbiata.",
    pairings: ["tandoori fish", "paneer tikka", "pasta arrabbiata"],
    whyChoose: "A red-and-white Nashik wine range from Sula.",
    faq: ["Who makes Mosaic wine?", "Mosaic is a Sula Vineyards label.", "Does Mosaic come in red and white?", "Yes. Both red and white wines appear in the range."],
    finalVerdict: "Mosaic keeps a mixed dinner table easy to match with one red and one white choice.",
    metaDescription: "Explore Mosaic red and white wines from Sula, Nashik. Find food pairings and city prices on BevOry.",
  }),
  "vina-temprana": guide("Vina Temprana", "Wine", {
    description: "Viña Temprana is a Spanish wine label from Bodegas Aragonesas in Campo de Borja, Aragón. Its range includes old-vine Tempranillo, Macabeo white and rosado wines.",
    story: "Campo de Borja is often associated with Garnacha, but Viña Temprana also gives space to Tempranillo and the white grape Macabeo. The label presents the area's grapes in approachable single-bottle styles.",
    notes: ["Tempranillo", "Dark cherry and red plum sit beside gentle spice.", "Macabeo", "Citrus and apple freshness make the white lighter on its feet."],
    serve: "Serve Tempranillo slightly cool and chill Macabeo or rosado before opening.",
    food: "Try the red with mutton seekh and the white with grilled prawns or paneer tikka.",
    pairings: ["mutton seekh", "grilled prawns", "paneer tikka"],
    whyChoose: "Several sides of Aragón wine under one Campo de Borja label.",
    faq: ["Where is Viña Temprana made?", "It comes from Bodegas Aragonesas in Campo de Borja, Aragón.", "Does Viña Temprana make white wine?", "Yes. Macabeo is one of its white-wine listings."],
    finalVerdict: "Viña Temprana gives Spanish red, white and rosado drinkers a common regional starting point.",
    metaDescription: "Discover Viña Temprana wines from Campo de Borja, including Tempranillo and Macabeo. See pairings and city prices on BevOry.",
  }),
  samara: guide("Samara", "Wine", {
    description: "Samara is an Indian wine label in Sula Vineyards' Nashik portfolio. The range includes red and white bottlings.",
    story: "Sula's vineyards and winemaking put Nashik on the Indian wine map. Samara sits among its accessible labels, with a choice of red or white rather than a single grape-led flagship.",
    notes: ["Red", "Soft red-fruit notes make the wine an easy partner for savoury food.", "White", "A brighter fruit profile gives the white a lighter place at the table."],
    serve: "Chill the white and give the red a short spell in a cool room before serving.",
    food: "Pair white with malai tikka and red with mushroom masala or tomato pasta.",
    pairings: ["malai tikka", "mushroom masala", "tomato pasta"],
    whyChoose: "A simple red-or-white entry to Sula's Nashik wine range.",
    faq: ["Who makes Samara wine?", "Samara is in Sula Vineyards' wine portfolio.", "Is Samara available as white wine?", "Yes. Samara includes both white and red wines."],
    finalVerdict: "Samara is most useful when a table needs a straightforward Indian wine choice.",
    metaDescription: "Explore Samara red and white wines from Sula, Nashik. Find serving tips, Indian pairings and city prices on BevOry.",
  }),
  madera: guide("Madera", "Wine", {
    description: "Madera is an Indian wine label produced by Sula Vineyards in Nashik. It covers both red and white wines.",
    story: "Sula's Nashik base supplies the context for Madera: Indian grapes turned into approachable table wine. The label keeps a red and a white in the same family for different meals.",
    notes: ["Red", "Ripe fruit and a soft structure keep the red approachable.", "White", "Citrus-led freshness gives the white an easy aperitif feel."],
    serve: "Chill the white; give the red a light chill during hot weather.",
    food: "Serve white with tandoori prawns and red with paneer tikka or grilled chicken.",
    pairings: ["tandoori prawns", "paneer tikka", "grilled chicken"],
    whyChoose: "A practical Nashik red-and-white choice from Sula.",
    faq: ["Where is Madera wine from?", "Madera is part of Sula's Indian wine range based in Nashik.", "Does Madera include white wine?", "Yes. Both red and white bottles appear in the range."],
    finalVerdict: "Madera is at its best as an unfussy wine beside a full dinner spread.",
    metaDescription: "Discover Madera red and white wine from Sula, Nashik. Find serving ideas, food pairings and city prices on BevOry.",
  }),
  moja: guide("Moja", "Rum", {
    description: "Moja is an Indian dark rum from NV Group. The Legend of Black is the name attached to its dark-rum expression.",
    story: "NV Group places Moja among its Indian spirits labels. Dark colour, oak influence and a fuller flavour direction distinguish The Legend of Black from a white mixing rum.",
    notes: ["Aroma", "Caramel and ripe-fruit notes rise from the glass.", "Finish", "Chocolate and roasted-nut tones give the darker style its finish."],
    serve: "Pour over a large cube or stretch with cola and a squeeze of lime.",
    food: "Match with pepper chicken, roasted cashews or dark chocolate.",
    pairings: ["pepper chicken", "roasted cashews", "dark chocolate"],
    whyChoose: "A dark Indian rum with an oak-accented, dessert-friendly profile.",
    faq: ["Who makes Moja rum?", "Moja is a rum label from India's NV Group.", "What style is Moja The Legend of Black?", "It is the brand's dark-rum expression."],
    finalVerdict: "Moja is an easy move from a cola-and-lime mix to a slower after-dinner pour.",
    metaDescription: "Explore Moja The Legend of Black rum from NV Group. See tasting notes, pairings and city prices on BevOry.",
  }),
};
