import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_LOGOS_BATCH_13: Record<string, string> = {
  beluga: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-db4b593cedf2b826cdea6a75/a87a139b9866b192b993.jpg",
  "maya-pistola": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-eec52c1317f0c3f80b7278da/54b34dd9a9e5cc7574a4.jpg",
  morpheus: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-c1a1e4aa1037bae1586d8d1f/a823e8aea6e00e779626.jpg",
  "ron-diplomatico": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-d050fd1ff294e1173d1dd508/7cd1030de1fb436cbf45.jpg",
  akashi: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-e49c56641b7ba80097d0443c/e92c7e86917b76d35e1f.jpg",
  "blue-moon": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-218d373c2875fac885aed35c/67143d4500e013c3fc05.jpg",
  budweiser: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-448d6731ee98ea8d5c97cd65/040225260a647e9a25a8.jpg",
  "captain-morgan": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-2b1c9cd7e36108c9e56b5e83/37074c7e67792a9b1221.jpg",
  carlsberg: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-b3733477164d87458b778ce7/6297926b4ddc5b9dd880.jpg",
  "clase-azul": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-4894395267f859141ba86dc6/4cce8099d23123ee50ca.jpg",
  glengrant: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-852ce7fc856d61694e333742/833abdb273de82e05783.jpg",
  hardys: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-d18156fb3ecd86021560d68c/d68a9ab4bc75c34f0c5f.jpg",
  jura: "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-b53f9a608e7b653326769940/6129103ab1f69f524de5.jpg",
  "louis-jadot": "https://bevory.in/media/migrated-images/brand-spotlights/lc-brand-2c48fcf58b16608870edc19a/b5d7f575dc0f2236862b.jpg",
  nikka: "https://www.nikka.com/common/img/og.png",
  gekkeikan: "https://www.gekkeikan.com/lib/img/common/header/img_logo.svg",
  "gato-negro": "https://vsptwinegroup.com/cms/wp-content/uploads/2025/01/gatonegro002.png",
  geist: "https://cdn.prod.website-files.com/62dc3bf0c84234f523cebb22/63c69ced1a635594021124f5_black%20logo.svg",
  pasqua: "https://cdn.adoratorio.app/pasqua/pasqua_socialcard.jpg",
  "b-and-g": "https://www.barton-guestier.com/pics/communs/BG_logo.png",
};

export const BRAND_CONTENT_BATCH_13: Record<string, BrandPublicContent> = {
  beluga: {
    description: "Beluga is a super-premium vodka produced by Noblewood Group with organic grain spirit made in Latvia and finished in Montenegro. Noble, Gold Line and Transatlantic Racing express the house preference for a polished texture and restrained flavour.",
    story: "Noblewood acquired Beluga's international rights in 2022 and established its production base in Niksic, Montenegro. The metal sturgeon fixed to each bottle remains the brand's most recognisable detail.",
    tastingNotes: [
      { title: "Beluga Noble", description: "A clean, rounded profile with light cereal sweetness, white pepper and a soft, dry finish." },
      { title: "Gold Line", description: "Silky grain, vanilla and faint citrus sit over a longer, gently spiced close." },
    ],
    howToEnjoy: [
      { subheading: "Cold, not numb", description: "Chill the bottle and pour into a small stemmed glass; excessive freezing can flatten the delicate grain and citrus notes." },
      { subheading: "Build a sharp contrast", description: "Serve with caviar, smoked salmon or salted cucumber, or use a measured pour in a very cold Vodka Martini." },
    ],
    pairingIdeas: [{ title: "Cold-table pairings", items: ["smoked salmon", "salted cucumber", "tandoori prawns", "potato blini", "aged gouda"] }],
    whyChoose: "Beluga favours a composed, silky vodka profile rather than aggressive heat or conspicuous flavouring.",
    faqs: [
      { question: "Where is Beluga Vodka made?", answer: "Noblewood makes the organic grain spirit in Latvia and produces and bottles Beluga for international markets in Niksic, Montenegro." },
      { question: "What is the difference between Beluga Noble and Gold Line?", answer: "Noble is the core smooth, grain-led expression, while Gold Line is presented as a richer, more luxurious step in the range." },
    ],
    finalVerdict: "Beluga is a quiet, polished vodka whose best features appear in a small chilled pour beside salty food.",
    metaTitle: "Beluga Premium Vodka Guide | BevOry",
    metaDescription: "Explore Beluga vodka, from Noble to Gold Line, with tasting notes, chilled serves, food pairings and city prices on BevOry.",
  },
  "maya-pistola": {
    description: "Maya Pistola Agavepura is an Indian agave spirit founded by Rakshay Dhariwal and made from wild Agave americana grown on the Deccan Plateau. The cooked agave is fermented in wooden vats, double-distilled in a part-copper pot still and matured by the Goan coast.",
    story: "The name combines Mayahuel, the Aztec goddess of agave, with the Spanish word for pistol. Its oak programme uses virgin American white oak, ex-bourbon and ex-red-wine casks to give Indian agave a distinct identity outside tequila's Jalisco appellation.",
    tastingNotes: [
      { title: "Joven", description: "Roasted agave, green pepper and citrus arrive first, followed by gentle smoke, earth and white spice." },
      { title: "Reposado", description: "Cooked agave gains vanilla, caramel and warm oak while retaining pepper and an herbaceous edge." },
    ],
    howToEnjoy: [
      { subheading: "Sip before mixing", description: "Use a small agave-spirit glass at cool room temperature, then add Joven to a Margarita or Reposado to a spirit-forward Paloma." },
      { subheading: "Meet smoke with spice", description: "Try Joven with achari prawns or chilli corn; Reposado has the weight for pork sorpotel, lamb barbacoa or dark chocolate." },
    ],
    pairingIdeas: [{ title: "Deccan and coastal pairings", items: ["achari prawns", "chilli corn", "pork sorpotel", "lamb barbacoa", "dark chocolate"] }],
    whyChoose: "Maya Pistola turns mature Deccan agave and coastal maturation into a spirit that belongs to India rather than imitating tequila.",
    faqs: [
      { question: "Is Maya Pistola tequila?", answer: "No. It is an Indian agave spirit made from Agave americana grown on the Deccan Plateau; tequila is protected for authorised Mexican regions and approved agave." },
      { question: "How is Maya Pistola made?", answer: "The agave hearts are pressure-cooked, milled, fermented in wooden vats, double-distilled and matured in selected American oak, bourbon or red-wine casks." },
    ],
    finalVerdict: "Maya Pistola gives Indian agave a convincing voice through earthy spirit, careful oak and a peppery backbone.",
    metaTitle: "Maya Pistola Indian Agave Guide | BevOry",
    metaDescription: "Discover Maya Pistola's Deccan agave, Goan maturation, tasting notes, cocktail serves, food pairings and city prices on BevOry.",
  },
  morpheus: {
    description: "Morpheus XO is an Indian premium brandy made by Radico Khaitan, the company that grew from Rampur Distillery. Its profile centres on dried fruit, flowers, vanilla and mature wood.",
    story: "Named after the winged Greek god of dreams, Morpheus entered the market as Radico Khaitan's premium step above everyday Indian brandy. The bottle's tall shoulders and copper-toned presentation have become familiar across southern and eastern Indian markets.",
    tastingNotes: [
      { title: "Fruit and flowers", description: "Raisin, prune and floral top notes form an intense aroma with a sweet, full-bodied entry." },
      { title: "Wood and finish", description: "Vanilla and mature wood follow the dried fruit into a long, warming finish." },
    ],
    howToEnjoy: [
      { subheading: "Give it a narrow glass", description: "Pour a small measure into a tulip or brandy glass and let it rest briefly before tasting neat or with a few drops of water." },
      { subheading: "Choose deep flavours", description: "Raisin and oak work well with mutton seekh, pepper chicken, fruit cake or cocoa-rich dark chocolate." },
    ],
    pairingIdeas: [{ title: "Warm-spice pairings", items: ["mutton seekh", "pepper chicken", "fruit cake", "roasted almonds", "dark chocolate"] }],
    whyChoose: "Morpheus XO delivers the dried-fruit richness and lingering wood that many Indian brandy drinkers actively seek.",
    faqs: [
      { question: "Who makes Morpheus Brandy?", answer: "Morpheus XO is made by Radico Khaitan, whose distilling business began as Rampur Distillery in 1943." },
      { question: "What does Morpheus XO taste like?", answer: "Floral notes, raisin and prune meet vanilla and mature wood, followed by a long finish." },
    ],
    finalVerdict: "Morpheus XO is a full, sweet-edged Indian brandy built for slow pours, dried fruit and robust food.",
    metaTitle: "Morpheus XO Indian Brandy Guide | BevOry",
    metaDescription: "Read the Morpheus XO guide for dried-fruit and oak notes, serving advice, Indian food pairings and city prices on BevOry.",
  },
  "ron-diplomatico": {
    description: "Diplomatico is a Venezuelan rum made at Destilerias Unidas near the Andes with locally sourced sugarcane molasses. Pot stills, batch kettles and columns create light and heavy rums that are matured mainly in ex-bourbon and ex-whiskey casks.",
    story: "The distillery dates to 1959, while the Don Juancho figure on the label recalls the Mantuanos, travelled Venezuelan noblemen and collectors of the nineteenth century. Brown-Forman owns the brand, while DUSA continues to produce the rum in Venezuela.",
    tastingNotes: [
      { title: "Reserva Exclusiva", description: "Orange peel, raisin and toffee lead into vanilla, baking spice and a rounded, sweet finish." },
      { title: "Mantuano", description: "Dried plum, oak and vanilla sit beside gentle spice in a drier, cocktail-friendly frame." },
    ],
    howToEnjoy: [
      { subheading: "Match the expression", description: "Sip Reserva Exclusiva neat or over one large cube; use Mantuano in a Rum Old Fashioned or a balanced Daiquiri." },
      { subheading: "Work with caramelised flavours", description: "Pair the richer bottles with pork belly, grilled pineapple, mutton roast, pecan tart or dark chocolate." },
    ],
    pairingIdeas: [{ title: "Rum-table pairings", items: ["pork belly", "grilled pineapple", "mutton roast", "pecan tart", "dark chocolate"] }],
    whyChoose: "Diplomatico layers three distillation systems and Venezuelan oak maturation into a notably round, fruit-rich rum style.",
    faqs: [
      { question: "Where is Diplomatico Rum made?", answer: "Diplomatico is made by Destilerias Unidas in Venezuela, using locally sourced sugarcane molasses." },
      { question: "Which Diplomatico rum is best for sipping?", answer: "Reserva Exclusiva is the familiar sipping expression, while Mantuano has a firmer profile that also works well in cocktails." },
    ],
    finalVerdict: "Diplomatico is generous Venezuelan rum, with Reserva Exclusiva placing orange, raisin and toffee ahead of sharp alcohol heat.",
    metaTitle: "Diplomatico Venezuelan Rum Guide | BevOry",
    metaDescription: "Compare Diplomatico Reserva Exclusiva and Mantuano, with rum-making facts, tasting notes, pairings and city prices on BevOry.",
  },
  akashi: {
    description: "Akashi is the whisky label of Eigashima Shuzo, a sake producer based beside the Seto Inland Sea in Akashi, Hyogo. Its White Oak distillery makes Japanese malt whisky alongside blended and cask-finished releases.",
    story: "Eigashima's brewing history reaches back to the late nineteenth century, long before Akashi whisky found an international audience. The compact distillery works around the sake-brewing calendar, giving its whisky production an unusually small-scale rhythm.",
    tastingNotes: [
      { title: "Akashi Blended", description: "Honeyed malt, citrus peel and vanilla move into light spice and a clean, easy finish." },
      { title: "Single Malt", description: "Orchard fruit, malt biscuit and oak show more depth, with dried fruit appearing in sherry-cask releases." },
    ],
    howToEnjoy: [
      { subheading: "Use the Japanese highball", description: "Taste the whisky neat in a small tulip glass, then lengthen the blended bottle with cold soda and hard ice." },
      { subheading: "Keep the plate savoury", description: "Yakitori, miso-glazed mushrooms, chicken teriyaki and sesame paneer suit the malt, citrus and mild oak." },
    ],
    pairingIdeas: [{ title: "Japanese-inspired pairings", items: ["yakitori", "miso-glazed mushrooms", "chicken teriyaki", "sesame paneer", "salted almonds"] }],
    whyChoose: "Akashi offers a small Hyogo producer's view of Japanese whisky, from light highball blends to fuller cask-led malt.",
    faqs: [
      { question: "Who makes Akashi whisky?", answer: "Akashi is made by Eigashima Shuzo at its White Oak distillery in Akashi City, Hyogo Prefecture." },
      { question: "How should Akashi whisky be served?", answer: "The blend works neatly in a highball, while single malt and cask-finished bottles deserve a tulip glass and a little time." },
    ],
    finalVerdict: "Akashi is most rewarding when its lighter blend and deeper single malt are treated as two different sides of White Oak.",
    metaTitle: "Akashi Japanese Whisky Guide | BevOry",
    metaDescription: "Explore Akashi whisky from White Oak Distillery, including blend and single-malt notes, highball serves and city prices on BevOry.",
  },
  "blue-moon": {
    description: "Blue Moon Belgian White is an American Belgian-style wheat ale created by brewer Keith Villa at the Sandlot Brewery in Denver in 1995. White wheat, oats, Valencia orange peel and coriander shape its cloudy, citrus-led profile.",
    story: "Villa returned from brewing studies in Brussels and called the first beer Bellyslide Wit before a tasting-room remark supplied the Blue Moon name. His orange-wheel garnish replaced the lemon then commonly served with wheat beer and became part of the brand's identity.",
    tastingNotes: [
      { title: "Citrus and spice", description: "Valencia orange and floral coriander sit over soft wheat, with light pepper and restrained sweetness." },
      { title: "Texture and finish", description: "Wheat and oats provide a creamy middle before a crisp, citrus-spiced finish." },
    ],
    howToEnjoy: [
      { subheading: "Pour the cloudiness", description: "Serve chilled in a wheat-beer glass, leaving room for the head and adding an orange wheel only after the pour." },
      { subheading: "Use gentle heat", description: "Fish tikka, chicken malai tikka, citrus salad and fried calamari echo the beer without overwhelming its low bitterness." },
    ],
    pairingIdeas: [{ title: "Wheat-beer pairings", items: ["fish tikka", "chicken malai tikka", "fried calamari", "citrus salad", "orange cheesecake"] }],
    whyChoose: "Blue Moon combines cloudy wheat texture with obvious orange and coriander, making it an accessible alternative to lager.",
    faqs: [
      { question: "Who created Blue Moon Belgian White?", answer: "Brewer Keith Villa created it at the Sandlot Brewery inside Denver's Coors Field in 1995." },
      { question: "Why is Blue Moon served with orange?", answer: "Keith Villa introduced the orange wheel to lift the Valencia orange-peel aroma already present in the beer." },
    ],
    finalVerdict: "Blue Moon is a soft, citrus-bright wheat ale whose orange and coriander remain clear from aroma to finish.",
    metaTitle: "Blue Moon Belgian White Beer Guide | BevOry",
    metaDescription: "Know Blue Moon Belgian White, its orange and coriander recipe, cloudy pour, food matches and city prices on BevOry.",
  },
  budweiser: {
    description: "Budweiser is an American-style lager created by Adolphus Busch in St. Louis in 1876 and now owned by AB InBev. Barley malt, rice, hops and the original yeast culture produce a light-bodied, clean and gently sweet beer.",
    story: "Busch built Budweiser as a national bottled-beer brand at a time when American beer was largely local. Its long lagering stage uses beechwood strips to increase contact between yeast and beer, a production signature rather than a source of woody flavour.",
    tastingNotes: [
      { title: "Classic lager profile", description: "Pale malt and light cereal sweetness meet mild floral hops and a clean, low-bitterness finish." },
      { title: "Texture", description: "Crisp carbonation and a light body keep the beer refreshing rather than rich or heavily malty." },
    ],
    howToEnjoy: [
      { subheading: "Keep the glass cold and clean", description: "Serve well chilled in a tall lager glass, pouring down the side before straightening the glass to form a compact head." },
      { subheading: "Bring salt and char", description: "Chicken wings, seekh kebab, masala fries and grilled corn give this mild lager enough savoury contrast." },
    ],
    pairingIdeas: [{ title: "Lager pairings", items: ["chicken wings", "seekh kebab", "masala fries", "grilled corn", "pepperoni pizza"] }],
    whyChoose: "Budweiser is built around consistency, brisk carbonation and a clean lager finish rather than hop intensity.",
    faqs: [
      { question: "When was Budweiser created?", answer: "Adolphus Busch introduced Budweiser in St. Louis, Missouri, in 1876." },
      { question: "Does Budweiser taste like wood?", answer: "No. Beechwood ageing supports yeast contact during lagering; it is not intended to add an oak or timber flavour." },
    ],
    finalVerdict: "Budweiser remains a straightforward cold lager for drinkers who value fizz, clean malt and very little bitterness.",
    metaTitle: "Budweiser American Lager Guide | BevOry",
    metaDescription: "Read the Budweiser guide for its 1876 story, beechwood lagering, crisp flavour, food pairings and city prices on BevOry.",
  },
  "captain-morgan": {
    description: "Captain Morgan is Diageo's Caribbean rum brand, launched in 1982 and named for the seventeenth-century Welsh privateer Henry Morgan. Original Spiced Gold blends Caribbean rum with vanilla, natural flavours and warming spice.",
    story: "The brand turns Caribbean rum history into an accessible mixing style rather than a formal sipping ritual. Its range now includes spiced, dark and white rum expressions made for different cocktails and markets.",
    tastingNotes: [
      { title: "Original Spiced Gold", description: "Vanilla and caramel lead, followed by cinnamon-like warmth, molasses sweetness and a short oak note." },
      { title: "Dark Rum", description: "Deeper molasses, dried fruit and charred oak give the darker bottle more weight and spice." },
    ],
    howToEnjoy: [
      { subheading: "Build a simple long drink", description: "Combine Original Spiced Gold with cola, plenty of ice and fresh lime, or use white rum in a clean Daiquiri." },
      { subheading: "Choose smoke and sweetness", description: "Barbecue chicken, jerk-spiced paneer, grilled pineapple and ginger cake suit the rum's vanilla and spice." },
    ],
    pairingIdeas: [{ title: "Spiced-rum pairings", items: ["barbecue chicken", "jerk-spiced paneer", "grilled pineapple", "pork ribs", "ginger cake"] }],
    whyChoose: "Captain Morgan makes vanilla-led spiced rum easy to place in cola highballs, party serves and uncomplicated cocktails.",
    faqs: [
      { question: "What is Captain Morgan Original Spiced Gold?", answer: "It is a blend of Caribbean rum flavoured with vanilla, spice and other natural flavours." },
      { question: "What mixer goes with Captain Morgan?", answer: "Cola and lime are the familiar pairing, while ginger beer works when a drier, spicier long drink is preferred." },
    ],
    finalVerdict: "Captain Morgan Original Spiced Gold is a friendly mixing rum where vanilla, caramel and spice do most of the talking.",
    metaTitle: "Captain Morgan Spiced Rum Guide | BevOry",
    metaDescription: "Explore Captain Morgan rum, from Spiced Gold to Dark, with mixer ideas, tasting notes, pairings and city prices on BevOry.",
  },
  carlsberg: {
    description: "Carlsberg is a Danish lager brand founded by J.C. Jacobsen at Valby, Copenhagen, in 1847. The flagship beer has a pale malt core, herbal hops and a dry, lightly bitter finish.",
    story: "Jacobsen named the brewery for his son Carl and the Danish word bjerg, referring to Valby Hill. The Carlsberg Laboratory later isolated a pure lager yeast culture in 1883, helping brewers produce more consistent bottom-fermented beer.",
    tastingNotes: [
      { title: "Malt and hops", description: "Soft grain and cracker-like malt meet a mild herbal hop note with restrained sweetness." },
      { title: "Dry finish", description: "Medium carbonation clears the palate before a neat, lightly bitter lager close." },
    ],
    howToEnjoy: [
      { subheading: "Use a tall lager glass", description: "Serve well chilled and pour with a compact head so the malt and herbal hop aroma remain present." },
      { subheading: "Give bitterness a job", description: "Pair it with fish fry, chilli paneer, chicken tikka, Danish open sandwiches or salted peanuts." },
    ],
    pairingIdeas: [{ title: "Copenhagen-to-India pairings", items: ["fish fry", "chilli paneer", "chicken tikka", "smorrebrod", "salted peanuts"] }],
    whyChoose: "Carlsberg brings a little more herbal bitterness and dryness than many mass-market pale lagers.",
    faqs: [
      { question: "Who founded Carlsberg?", answer: "J.C. Jacobsen founded the brewery at Valby in Copenhagen in 1847." },
      { question: "Why is Carlsberg important to brewing history?", answer: "The Carlsberg Laboratory isolated a pure lager yeast culture in 1883 and shared the work with the brewing world." },
    ],
    finalVerdict: "Carlsberg is a crisp Danish lager with enough herbal hop bitterness to stay dry beside fried or spicy food.",
    metaTitle: "Carlsberg Danish Lager Guide | BevOry",
    metaDescription: "Discover Carlsberg's Copenhagen roots, pure lager yeast history, crisp tasting notes, pairings and city prices on BevOry.",
  },
  "clase-azul": {
    description: "Clase Azul Mexico is a luxury tequila house founded by Arturo Lomeli and built around agave from Los Altos de Jalisco. Its Reposado is recognised by a cobalt-painted ceramic decanter made and decorated by Mexican artisans.",
    story: "The first Clase Azul tequila appeared in 2000, linking Highland agave with a bottle intended to remain as a piece of Mexican craft. Ceramic work and spirit production now meet at the brand's Jalisco operation, where each decanter is finished by hand.",
    tastingNotes: [
      { title: "Reposado", description: "Cooked agave, vanilla and candied orange meet cinnamon, hazelnut and a rounded oak sweetness." },
      { title: "Plata", description: "Fresh agave, citrus and green herbs lead a cleaner profile with pepper and a lightly sweet finish." },
    ],
    howToEnjoy: [
      { subheading: "Leave the shot glass aside", description: "Pour Reposado into a narrow agave-spirit glass at room temperature; chill Plata lightly for a clean neat serve or a refined Margarita." },
      { subheading: "Pair agave with char", description: "Reposado suits lamb barbacoa and mole chicken, while Plata works with ceviche, tandoori prawns and citrus-dressed corn." },
    ],
    pairingIdeas: [{ title: "Highland-agave pairings", items: ["lamb barbacoa", "mole chicken", "ceviche", "tandoori prawns", "citrus-dressed corn"] }],
    whyChoose: "Clase Azul combines ripe Highland agave, a rounded house style and hand-painted ceramics in one unmistakable presentation.",
    faqs: [
      { question: "Where is Clase Azul tequila made?", answer: "Clase Azul is made in Jalisco, Mexico, from Blue Weber agave grown in the state's highland region." },
      { question: "Are Clase Azul bottles handmade?", answer: "The ceramic decanters are formed and hand-painted by Mexican artisans, so small visual differences are expected." },
    ],
    finalVerdict: "Clase Azul Reposado pairs a sweet, polished agave profile with one of tequila's most distinctive artisan decanters.",
    metaTitle: "Clase Azul Mexico Tequila Guide | BevOry",
    metaDescription: "Explore Clase Azul Reposado and Plata, Highland agave, artisan decanters, serving ideas and city prices on BevOry.",
  },
  glengrant: {
    description: "The Glen Grant is a Speyside single malt made in Rothes, where brothers John and James Grant founded the distillery in 1840. Tall, slender pot stills and water-cooling purifiers create an unusually light, orchard-fruited new make.",
    story: "James 'The Major' Grant expanded the distillery after taking control in 1872 and introduced the still shape and purifiers that still define its spirit. His travels also inspired the twenty-two-acre Victorian garden beside the distillery.",
    tastingNotes: [
      { title: "10 Year Old", description: "Green apple, pear and almond sit over vanilla, malt and a clean, gently nutty finish." },
      { title: "12 Year Old", description: "Ripe orchard fruit and citrus gain honey, caramel and light spice from longer oak maturation." },
    ],
    howToEnjoy: [
      { subheading: "Let the fruit open", description: "Serve in a tulip glass at room temperature and add only a few drops of water after the first sip." },
      { subheading: "Stay on the lighter side", description: "Tandoori salmon, roast chicken, almond kheer and mild aged cheddar preserve the whisky's fruit and delicacy." },
    ],
    pairingIdeas: [{ title: "Speyside pairings", items: ["tandoori salmon", "roast chicken", "almond kheer", "mild aged cheddar", "pear tart"] }],
    whyChoose: "The Glen Grant shows Speyside through apple, pear and clean malt rather than dense sherry or heavy smoke.",
    faqs: [
      { question: "Where is The Glen Grant made?", answer: "The whisky is distilled in Rothes in Scotland's Speyside region." },
      { question: "Why is The Glen Grant light and fruity?", answer: "Tall, slender stills and water-cooling purifiers increase reflux and help select a lighter, cleaner spirit." },
    ],
    finalVerdict: "The Glen Grant is graceful Speyside whisky, led by orchard fruit, clean malt and restrained oak.",
    metaTitle: "The Glen Grant Speyside Whisky Guide | BevOry",
    metaDescription: "Learn how tall stills shape The Glen Grant, with 10 and 12 Year tasting notes, food pairings and city prices on BevOry.",
  },
  hardys: {
    description: "Hardys is an Australian wine brand founded by Thomas Hardy in South Australia in 1853. Its broad range draws on varieties such as Shiraz, Cabernet Sauvignon, Chardonnay and Sauvignon Blanc across labels including Stamp, VR and Crest.",
    story: "Thomas Hardy planted the Bankside vineyard beside Adelaide's River Torrens and shipped his first wine to England in 1857. His aim to make Australian wine known abroad shaped a house that now works with fruit from several established Australian regions.",
    tastingNotes: [
      { title: "Shiraz", description: "Ripe blackberry and plum carry black pepper, sweet spice and a soft, generous body." },
      { title: "Chardonnay", description: "Peach, melon and citrus sit over a rounded palate with gentle vanilla in oak-influenced bottlings." },
    ],
    howToEnjoy: [
      { subheading: "Two serving temperatures", description: "Chill Chardonnay to 8 to 10 degrees Celsius; bring Shiraz to about 16 degrees in a medium red-wine glass." },
      { subheading: "Split the menu", description: "Chardonnay suits malai tikka and grilled prawns, while Shiraz can handle mutton seekh, barbecue chicken or mushroom pepper fry." },
    ],
    pairingIdeas: [{ title: "Australian wine pairings", items: ["malai tikka", "grilled prawns", "mutton seekh", "barbecue chicken", "mushroom pepper fry"] }],
    whyChoose: "Hardys offers recognisable Australian grape styles at several price levels without making the label difficult to decode.",
    faqs: [
      { question: "Who founded Hardys Wines?", answer: "English-born winemaker Thomas Hardy established the business in South Australia in 1853." },
      { question: "Which Hardys wine should I choose with Indian food?", answer: "Choose Chardonnay for creamy chicken or seafood dishes and Shiraz for peppery kebabs, barbecue and richer gravies." },
    ],
    finalVerdict: "Hardys is dependable Australian wine with ripe fruit, familiar grape names and a bottle for most parts of dinner.",
    metaTitle: "Hardys Australian Wine Guide | BevOry",
    metaDescription: "Compare Hardys Shiraz and Chardonnay, read Thomas Hardy's story, find Indian food pairings and city prices on BevOry.",
  },
  jura: {
    description: "Jura is an island single malt made at the only whisky distillery on the Scottish Isle of Jura. Exceptionally tall pot stills give the spirit a lighter structure that the range develops through bourbon, sherry and wine casks.",
    story: "Archibald Campbell established a distillery on Jura in 1810, but production later stopped for decades. Local landowners Robin Fletcher and Tony Riley-Smith rebuilt it with architect William Delme-Evans, and spirit flowed again in 1963.",
    tastingNotes: [
      { title: "Jura 10 Year Old", description: "Apricot, vanilla and dark chocolate meet ginger, light smoke and a coffee-toned finish." },
      { title: "Jura Seven Wood", description: "Coffee, ginger and chocolate deepen into baked fruit, caramelised peach and firmer oak spice." },
    ],
    howToEnjoy: [
      { subheading: "Open it in stages", description: "Taste neat from a tulip glass, then add a few drops of water to separate the fruit, chocolate and gentle smoke." },
      { subheading: "Use earth and char", description: "Tandoori lamb, smoked paneer, roast mushrooms and dark chocolate fit Jura's mix of fruit, oak and smoke." },
    ],
    pairingIdeas: [{ title: "Island pairings", items: ["tandoori lamb", "smoked paneer", "roast mushrooms", "dark chocolate", "grilled salmon"] }],
    whyChoose: "Jura offers island character without making peat smoke the only subject in the glass.",
    faqs: [
      { question: "Where is Jura whisky made?", answer: "It is made at Jura Distillery in Craighouse on the Isle of Jura, off Scotland's west coast." },
      { question: "Is Jura whisky heavily peated?", answer: "The core range is generally fruit-led with measured smoke, though peat influence varies between expressions." },
    ],
    finalVerdict: "Jura balances island smoke with apricot, chocolate and oak, giving the range more breadth than its remote address suggests.",
    metaTitle: "Jura Island Single Malt Guide | BevOry",
    metaDescription: "Explore Jura island whisky, its tall stills, 10 Year and Seven Wood notes, food pairings and city prices on BevOry.",
  },
  "louis-jadot": {
    description: "Maison Louis Jadot is a Burgundy producer and negociant founded in Beaune in 1859. Pinot Noir and Chardonnay run through a portfolio stretching from regional Bourgogne to village, Premier Cru and Grand Cru vineyards.",
    story: "The Jadot family's Burgundy roots predate the house: Louis Henry Denis Jadot bought Beaune Premier Cru Clos des Ursules in 1826. The walled Pinot Noir parcel remains with the family and is still one of the maison's defining wines.",
    tastingNotes: [
      { title: "Bourgogne Pinot Noir", description: "Red cherry and raspberry meet violet, light earth and fine, fresh tannins." },
      { title: "Bourgogne Chardonnay", description: "Apple, pear and citrus carry a soft mineral line, gentle cream and measured oak." },
    ],
    howToEnjoy: [
      { subheading: "Cool both colours", description: "Serve Chardonnay around 10 to 12 degrees Celsius and Pinot Noir around 14 to 16 degrees in a broad Burgundy glass." },
      { subheading: "Follow Burgundy's restraint", description: "Chardonnay suits tandoori fish and roast chicken; Pinot Noir works with mushroom galouti, duck or grilled lamb chops." },
    ],
    pairingIdeas: [{ title: "Burgundy pairings", items: ["tandoori fish", "roast chicken", "mushroom galouti", "duck breast", "grilled lamb chops"] }],
    whyChoose: "Louis Jadot provides a readable route through Burgundy, with the grape and appellation carrying more weight than branding alone.",
    faqs: [
      { question: "Where is Louis Jadot based?", answer: "Maison Louis Jadot is based in Beaune, at the heart of Burgundy's Cote d'Or." },
      { question: "Which grapes define Louis Jadot wines?", answer: "Pinot Noir defines most red Burgundy in the range, while Chardonnay defines the whites." },
    ],
    finalVerdict: "Louis Jadot is a useful Burgundy name because regional bottles and serious crus share the same clear focus on place and grape.",
    metaTitle: "Louis Jadot Burgundy Wine Guide | BevOry",
    metaDescription: "Explore Louis Jadot Pinot Noir and Chardonnay, the Clos des Ursules story, serving notes and city prices on BevOry.",
  },
  nikka: {
    description: "Nikka is a Japanese whisky company founded by Masataka Taketsuru in 1934 after his study of distilling in Scotland. Its range draws on Yoichi malt, Miyagikyo malt and Coffey-still grain whisky.",
    story: "Taketsuru chose coastal Yoichi in Hokkaido for its cool climate, clean water and resemblance to parts of Scotland. Miyagikyo followed near Sendai in 1969, giving Nikka a softer malt style to blend against Yoichi's firmer, lightly smoky spirit.",
    tastingNotes: [
      { title: "From the Barrel", description: "Dried orange, stone fruit and caramel meet clove, pepper and a concentrated, warming finish." },
      { title: "Coffey Grain", description: "Sweet corn, banana and melon move through vanilla, biscuit and a soft, creamy close." },
    ],
    howToEnjoy: [
      { subheading: "Treat each bottle differently", description: "Add a little water to From the Barrel after tasting neat; serve Coffey Grain over one cube or in a cold highball." },
      { subheading: "Work across sweet and savoury", description: "Yakitori and mutton seekh fit the spice of From the Barrel, while Coffey Grain suits caramel pudding or roasted corn." },
    ],
    pairingIdeas: [{ title: "Japanese whisky pairings", items: ["yakitori", "mutton seekh", "roasted corn", "caramel pudding", "dark chocolate"] }],
    whyChoose: "Nikka can move from muscular Yoichi malt to creamy Coffey grain without losing the precise blending style Taketsuru established.",
    faqs: [
      { question: "Who founded Nikka Whisky?", answer: "Masataka Taketsuru founded the company in 1934 after studying whisky production in Scotland and helping establish Japanese distilling." },
      { question: "Which distilleries make Nikka whisky?", answer: "Yoichi in Hokkaido and Miyagikyo near Sendai supply its principal Japanese malt whiskies, supported by Coffey-still grain spirit." },
    ],
    finalVerdict: "Nikka rewards exploration because its smoky malt, delicate malt and creamy grain whiskies each keep a distinct voice.",
    metaTitle: "Nikka Japanese Whisky Guide | BevOry",
    metaDescription: "Discover Nikka's Yoichi, Miyagikyo and Coffey styles, with tasting notes, serving ideas, pairings and city prices on BevOry.",
  },
  gekkeikan: {
    description: "Gekkeikan is a Japanese sake house founded by Jiemon Okura in Fushimi, Kyoto, in 1637. Fushimi's soft water supports a smooth, gentle style across junmai, nama, nigori and sparkling sake.",
    story: "Okura opened a sake shop called Kasagiya beside Fushimi's waterways and brewed under the name Tama no Izumi. The company adopted Gekkeikan, meaning laurel wreath, as its modern identity and later established a brewery in Folsom, California, in 1989.",
    tastingNotes: [
      { title: "Traditional Sake", description: "Steamed rice, melon and a faint herbal note lead a smooth, lightly dry palate." },
      { title: "Nigori", description: "Cloudy rice sediment brings a creamier texture with coconut, ripe fruit and gentle sweetness." },
    ],
    howToEnjoy: [
      { subheading: "Choose the temperature by style", description: "Serve lighter sake chilled in a wine glass; fuller traditional sake can be enjoyed cool or gently warmed in a tokkuri." },
      { subheading: "Match umami and spice", description: "Sushi, miso aubergine, tandoori fish and mushroom gyoza suit traditional sake, while nigori works with mango cheesecake." },
    ],
    pairingIdeas: [{ title: "Sake pairings", items: ["sushi", "miso aubergine", "tandoori fish", "mushroom gyoza", "mango cheesecake"] }],
    whyChoose: "Gekkeikan makes Fushimi's soft-water sake style accessible across clear, cloudy, sparkling and warm-serving bottles.",
    faqs: [
      { question: "Where was Gekkeikan founded?", answer: "Jiemon Okura founded the brewery in Fushimi, just south of Kyoto, in 1637." },
      { question: "Should Gekkeikan sake be served hot or cold?", answer: "Lighter and aromatic bottles suit a chilled serve, while fuller traditional sake can also be warmed gently." },
    ],
    finalVerdict: "Gekkeikan is an approachable doorway into sake, with soft water, rice-led flavour and several useful serving styles.",
    metaTitle: "Gekkeikan Japanese Sake Guide | BevOry",
    metaDescription: "Explore Gekkeikan sake from Fushimi, including traditional and nigori styles, serving temperatures and city prices on BevOry.",
  },
  "gato-negro": {
    description: "Gato Negro is a Chilean wine brand made by Vina San Pedro from Central Valley fruit. Cabernet Sauvignon, Carmenere, Merlot, Pinot Noir, Chardonnay, Sauvignon Blanc and Rose form its familiar varietal range.",
    story: "Vina San Pedro was founded in 1865 and developed Gato Negro as an easy-to-recognise everyday label for export markets. The black cat on the bottle now travels with the brand across dozens of countries and several lighter-alcohol formats.",
    tastingNotes: [
      { title: "Cabernet Sauvignon", description: "Blackcurrant, blackberry and cherry meet green pepper, liquorice and a supple medium body." },
      { title: "Carmenere", description: "Plum and blueberry carry coffee, gentle spice and soft tannins with balanced acidity." },
    ],
    howToEnjoy: [
      { subheading: "Keep reds slightly cool", description: "Serve Cabernet Sauvignon and Carmenere around 15 to 17 degrees Celsius in a medium red-wine glass." },
      { subheading: "Use everyday food", description: "Cabernet suits mutton keema and grilled lamb; Carmenere works with chilli paneer, roast vegetables and mushroom pulao." },
    ],
    pairingIdeas: [{ title: "Central Valley pairings", items: ["mutton keema", "grilled lamb", "chilli paneer", "roast vegetables", "mushroom pulao"] }],
    whyChoose: "Gato Negro offers clearly labelled Chilean grape varieties with ripe fruit and soft structure for uncomplicated meals.",
    faqs: [
      { question: "Who makes Gato Negro wine?", answer: "Gato Negro is made by Vina San Pedro, part of Chile's VSPT Wine Group." },
      { question: "Where do Gato Negro grapes come from?", answer: "The core varietal wines are associated with Chile's Central Valley, including vineyards around Molina and Pencahue." },
    ],
    finalVerdict: "Gato Negro is straightforward Chilean wine: choose the grape on the label, cool it properly and put food on the table.",
    metaTitle: "Gato Negro Chilean Wine Guide | BevOry",
    metaDescription: "Compare Gato Negro Cabernet and Carmenere, with Central Valley notes, serving advice, pairings and city prices on BevOry.",
  },
  geist: {
    description: "Geist is a Bengaluru craft beer company brewing wheat beer, lager, stout, IPA and Belgian-style ale at Nimbekaipura off Old Madras Road. The distribution brewery opened in 2017 inside a converted plywood factory.",
    story: "The team first introduced an Indian-owned wheat beer through a brewing partnership in Belgium before building South India's first distribution craft brewery. Geist later added beer gardens, taprooms, growler takeaway and 500 ml crowlers across Bengaluru and Hyderabad.",
    tastingNotes: [
      { title: "Weiss Guy", description: "Cloudy wheat, banana and clove sit over bready malt, lively carbonation and low bitterness." },
      { title: "Uncle Dunkel", description: "Caramel, chocolate and nuts deepen the wheat base while banana and clove keep the dark beer recognisably Bavarian in style." },
    ],
    howToEnjoy: [
      { subheading: "Give wheat beer a tall glass", description: "Serve Weiss Guy or Uncle Dunkel chilled in a wheat-beer glass with enough space for their vigorous foam." },
      { subheading: "Choose Bengaluru comfort food", description: "Weiss Guy suits fish tikka and chilli paneer; Uncle Dunkel works with pork ribs, mushroom pepper fry or chocolate cake." },
    ],
    pairingIdeas: [{ title: "Bengaluru beer pairings", items: ["fish tikka", "chilli paneer", "pork ribs", "mushroom pepper fry", "chocolate cake"] }],
    whyChoose: "Geist gives Bengaluru drinkers fresh, locally brewed versions of wheat, dark-wheat, lager and ale styles rather than another generic strong beer.",
    faqs: [
      { question: "Where is Geist beer brewed?", answer: "Geist brews at Nimbekaipura on Old Madras Road in the Bengaluru area." },
      { question: "Is Geist Uncle Dunkel a stout?", answer: "No. It is a Bavarian-style dark wheat beer with caramel, chocolate, banana and clove notes." },
    ],
    finalVerdict: "Geist is at its best when a fresh wheat beer and a plate of Bengaluru bar food arrive together.",
    metaTitle: "Geist Bengaluru Craft Beer Guide | BevOry",
    metaDescription: "Meet Geist beer from Bengaluru, compare Weiss Guy and Uncle Dunkel, find food pairings and city prices on BevOry.",
  },
  pasqua: {
    description: "Pasqua Wines is a family-owned Veronese winery founded in 1925 and known for Veneto wines. Amarone della Valpolicella, Valpolicella Ripasso, Soave and modern projects such as 11 Minutes show the range of its regional work.",
    story: "The Pasqua brothers began trading wine in Verona before building a production business that is now led by the family's third generation. Vineyards in Valpolicella and the Montevegro site connect the house to Corvina, Corvinone, Rondinella and the appassimento method.",
    tastingNotes: [
      { title: "Famiglia Pasqua Amarone", description: "Cherry, redcurrant and blueberry meet cocoa, tobacco and vanilla over silky tannins and a long morello-cherry finish." },
      { title: "11 Minutes Rose", description: "Fresh red fruit and citrus carry floral detail, crisp acidity and a dry, lightly savoury close." },
    ],
    howToEnjoy: [
      { subheading: "From rose to Amarone", description: "Chill 11 Minutes to 8 to 10 degrees Celsius; serve Amarone at 16 to 18 degrees after time in a decanter." },
      { subheading: "Match weight carefully", description: "Rose suits grilled prawns and paneer tikka, while Amarone belongs with rogan josh, braised lamb or aged Parmigiano." },
    ],
    pairingIdeas: [{ title: "Verona-inspired pairings", items: ["grilled prawns", "paneer tikka", "rogan josh", "braised lamb", "aged Parmigiano"] }],
    whyChoose: "Pasqua moves confidently from crisp Veneto whites and rose to concentrated appassimento reds without losing its Veronese identity.",
    faqs: [
      { question: "Where is Pasqua Wines based?", answer: "Pasqua is based in Verona in Italy's Veneto region and has been family-owned since its foundation in 1925." },
      { question: "Which grapes are used in Pasqua Amarone?", answer: "Famiglia Pasqua Amarone uses Corvina, Rondinella and Corvinone from the Valpolicella area." },
    ],
    finalVerdict: "Pasqua is a broad Veneto house, but its most distinctive work comes when Verona's native grapes meet appassimento and careful oak.",
    metaTitle: "Pasqua Veneto Wine Guide | BevOry",
    metaDescription: "Explore Pasqua Amarone, rose and Veneto roots, with tasting notes, serving temperatures, pairings and city prices on BevOry.",
  },
  "b-and-g": {
    description: "Barton & Guestier is a Bordeaux wine house whose roots begin with Irish merchant Thomas Barton in 1725. Its range covers Bordeaux blends and wines from other French regions, including Loire, Rhone, Provence and Languedoc.",
    story: "Thomas Barton built a wine-export business from Bordeaux's Chartrons district, and his grandson Hugh formalised a partnership with French merchant Daniel Guestier in 1802. Chateau Magnol in the Haut-Medoc became the company's home in 1969.",
    tastingNotes: [
      { title: "1725 Bordeaux Reserve", description: "Merlot and Cabernet Sauvignon bring red berries, spice and liquorice with a supple, meal-friendly structure." },
      { title: "Chateau Magnol", description: "Blackcurrant, plum and cedar meet tobacco, firm tannins and the savoury depth of a Haut-Medoc red." },
    ],
    howToEnjoy: [
      { subheading: "Give Bordeaux some air", description: "Serve younger reds at 16 to 18 degrees Celsius and decant firmer Haut-Medoc bottles before dinner." },
      { subheading: "Bring roasted flavours", description: "Pair 1725 Reserve with seekh kebab or mushroom galouti; Chateau Magnol suits rogan josh, roast lamb and aged cheddar." },
    ],
    pairingIdeas: [{ title: "Bordeaux pairings", items: ["seekh kebab", "mushroom galouti", "rogan josh", "roast lamb", "aged cheddar"] }],
    whyChoose: "Barton & Guestier offers a long-established Bordeaux name with bottles that reach beyond the region without obscuring their French origin.",
    faqs: [
      { question: "When was Barton & Guestier founded?", answer: "Its history begins in 1725, when Thomas Barton settled in Bordeaux; Barton & Guestier became the formal partnership in 1802." },
      { question: "What is Barton & Guestier 1725 Bordeaux Reserve?", answer: "It is a Bordeaux red based on Merlot and Cabernet Sauvignon, named for the year Thomas Barton began his Bordeaux business." },
    ],
    finalVerdict: "Barton & Guestier makes Bordeaux approachable through clear regional labels, recognisable grapes and practical dinner-table styles.",
    metaTitle: "Barton & Guestier Wine Guide | BevOry",
    metaDescription: "Read the Barton & Guestier story, compare 1725 Reserve and Chateau Magnol, find pairings and city prices on BevOry.",
  },
};
