import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_45 = [
  ["8848-himalayas", "8848 Himalayas", "Nepal", "Vodka", "ec7da2311909f59348fa397c"],
  ["alcobrew", "Alcobrew", "India", "Whisky", "3f8531c5f73447350a93b836"],
  ["golden-circle", "Golden Circle", "India", "Whisky", "c8a036324353c8e41d879213"],
  ["one-more", "One More", "India", "Vodka", "4a4ccc84bc62d90d137f29ed"],
  ["white-and-blue", "White & Blue", "India", "Whisky", "bc2f693d30c0565a2b3dd6ec"],
  ["bibi", "Bibi Graetz", "Italy", "Wine", "9a1ef8e9abb02eb32f701f8a"],
  ["big-boss", "Big Boss", "India", "Feni", "7e07fdaf0474b7ca0359bef8"],
  ["siempre", "Siempre", "Mexico", "Tequila", "8d6b69638b96ccd3d80ba935"],
  ["seven-rivers", "Seven Rivers", "India", "Rum", "942ab8642c51ddb994db6226"],
  ["wingman", "Wingman", "India", "Whisky", "5d86d506f4f54726d14d3ff3"],
  ["beach-house", "Beach House", "Mauritius", "Rum", "3303f0a287e4c179e86df272"],
  ["antares", "Antares", "Chile", "Wine", "f43c7b93298a00534c9b15dc"],
  ["antica", "Antica", "Italy", "Liqueur", "7ec3997adb00bfdd8eaa7f8d"],
  ["aristocrat", "Aristocrat", "India", "Whisky", "5fcfe1b9433151c103831afb"],
  ["agavita", "Agavita", "Mexico", "Tequila", "a06c94b9726c6a5065454333"],
  ["quaffine", "Quaffine", "India", "Liqueur", "e16e22fc818ad55e7b66d82b"],
  ["the-source", "The Source", "India", "Wine", "d10207ff4e3546fcae95062b"],
  ["lembranca-by-madame-rosa-1933", "Lembranca", "India", "Feni", "11aef849e85db5a1ed3bd68a"],
  ["kalevala", "Kalevala", "Finland", "Gin", "c0439fbe01ef27fdb015bf91"],
  ["dandelion", "Dandelion Vineyards", "Australia", "Wine", "077ff8c245bf1f45eb194a3f"],
  ["punter-soju", "Punter Soju", "South Korea", "Soju", "903bf7ed6a8d5a1a37361355"],
  ["bex", "BEX", "Germany", "Wine", "5c94f71de80851571bfd0712"],
  ["what-the-fox", "What the Fox", "France", "Wine", "f9a2c9bb1daa21ceab20ab6b"],
  ["tickle", "Tickle", "India", "Gin", "20f759a1625250532102c726"],
  ["06", "06", "France", "Vodka", "aacd834b5cdc64a329e27649"],
  ["adira", "Adira", "Spain", "Wine", "e6a526dbd871b7f2c94c9ecd"],
  ["arka", "Arka", "India", "Mead", "0cde7b186e42f60bff07d8c6"],
  ["antaraa", "Antaraa", "India", "Wine", "f8d34321aaea4137f55759bb"],
  ["nine-hill", "Nine Hills", "India", "Wine", "4ac25b3ada74e0bf9015de8b"],
  ["vijay-amtriraj", "Vijay Amritraj Reserve", "India", "Wine", "6285a439297ddba0273634dc"],
] as const;

// Research evidence is kept out of customer-facing fields.
export const BRAND_SOURCES_BATCH_45: Record<string, string[]> = {
  "8848-himalayas": ["https://8848vodka.com/product/8848-vodka/"],
  alcobrew: ["https://alcobrew.com/wp-content/uploads/2025/09/Draft-Red-Herring-Prospectus.pdf"],
  "golden-circle": ["https://alcobrew.com/wp-content/uploads/2025/09/Draft-Red-Herring-Prospectus.pdf"],
  "one-more": ["https://alcobrew.com/wp-content/uploads/2025/09/Draft-Red-Herring-Prospectus.pdf"],
  "white-and-blue": ["https://alcobrew.com/wp-content/uploads/2025/09/Draft-Red-Herring-Prospectus.pdf"],
  bibi: ["https://www.bibigraetz.com/en/wines", "https://www.bibigraetz.com/en/"],
  "big-boss": ["https://www.goaipb.goa.gov.in/wp-content/uploads/2025/02/ODOP-Feni-List-of-Brands.pdf", "https://www.heraldgoa.in/business/living-life-on-his-terms/121606/"],
  siempre: ["https://siempretequila.com/about/"],
  "seven-rivers": ["https://www.livcheers.com/mumbai/liquor/seven-rivers-premium-spiced-rum-750ml", "https://www.livemint.com/mint-lounge/ideas/kartikeya-sharma-ab-inbev-mint-business-lounge-profile-111702547243201.html"],
  wingman: ["https://www.wingmanwhisky.co.in/home"],
  "beach-house": ["https://caravanwinesandspirits.com.au/products/beach-house-gold-spiced-rum"],
  antares: ["https://antareswines.com/varietal/carmenere/", "https://antareswines.com/"],
  antica: ["https://www.anticasambuca.it/en/"],
  aristocrat: ["https://in.linkedin.com/company/jagatjit-industries-ltd", "https://www.bseindia.com/bseplus/AnnualReport/507155/5071550316.pdf"],
  agavita: ["https://www.vodkahaus.de/agavita-blanco-tequila"],
  quaffine: ["https://www.quaffine.com/"],
  "the-source": ["https://sulavineyards.com/source/cabernet-sauvignon.php", "https://sulavineyards.com/files/0225/Annual%20Report%202023-24.pdf"],
  "lembranca-by-madame-rosa-1933": ["https://www.heraldgoa.in/business/living-life-on-his-terms/121606/", "https://economictimes.indiatimes.com/industry/cons-products/liquor/raising-a-toast-heres-how-goas-local-liquors-like-feni-are-getting-a-makeover/articleshow/58553963.cms"],
  kalevala: ["https://www.kalevaladistillery.com/", "https://www.kalevaladistillery.com/faqs"],
  dandelion: ["https://dandelionvineyards.com.au/", "https://dandelionvineyards.com.au/our-wines/?availability=all"],
  "punter-soju": ["https://www.prowein.de/vis-content/event-prowein2026/exh-prowein2026.3063555/ProWein-2026-Real-Trade-Inc.-Paper-prowein2026.3063555-2W9hQpPBSG6WJ94854LEFA.pdf"],
  bex: ["https://bexwinery.com/"],
  "what-the-fox": ["https://vbev.co.in/what-the-fox/", "https://vbev.co.in/what-the-fox-cabernet/"],
  tickle: ["https://www.luxebook.in/digitalcopy/Luxebook-june-2021/files/assets/common/downloads/LuxeBook%20June-2021.pdf"],
  "06": ["https://cavadrosia.gr/brand-06-en", "https://aquaabymcs.com/vodka"],
  adira: ["https://www.linkedin.com/posts/c2c-importers-pvt-ltd_adirawines-adiramerlot-finewine-activity-7271727795909574656-Za5W", "https://www.sensibook.com/companies/1292877/U46308UP2023PTC184627/ADIRA-WINES-PRIVATE-LIMITED"],
  arka: ["https://www.architecturaldigest.in/story/6-indian-mead-brands-that-pack-a-flavourful-punch/", "https://www.mumbailive.com/en/food-drinks/premium-honey-by-mead-brand-arka-68113"],
  antaraa: ["https://www.sommelierindia.com/antaraa_a_new_blend_from_good/", "https://gooddropwine.com/wines/"],
  "nine-hill": ["https://tsbcl.nic.in/open_record.php?ID=210", "https://www.indianwineacademy.com/List_of_Winners.html"],
  "vijay-amtriraj": ["https://www.groverzampa.in/winery-tours", "https://www.indianwineacademy.com/Gz_VA_Booklet.pdf"],
};

export const BRAND_LOGOS_BATCH_45: Record<string, string> = {
  quaffine: "https://static.wixstatic.com/media/88695e_aab968c8ae0c4af9875ecfc2bacf23b2~mv2.png/v1/fill/w_604,h_126,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/logotype~blk~transparent.png",
};

type Draft = {
  description: string;
  story: string;
  notes: [string, string, string, string];
  serve: string;
  food: string;
  pairings: string[];
  whyChoose: string;
  faq: [string, string, string, string];
  finalVerdict: string;
  metaDescription: string;
  metaTitle?: string;
};

const guide = (name: string, category: string, draft: Draft): BrandPublicContent => ({
  description: draft.description,
  story: draft.story,
  tastingNotes: [
    { title: draft.notes[0], description: draft.notes[1] },
    { title: draft.notes[2], description: draft.notes[3] },
  ],
  howToEnjoy: [
    { subheading: "Serve", description: draft.serve },
    { subheading: "Food", description: draft.food },
  ],
  pairingIdeas: [{ title: `With ${name}`, items: draft.pairings }],
  whyChoose: draft.whyChoose,
  faqs: [
    { question: draft.faq[0], answer: draft.faq[1] },
    { question: draft.faq[2], answer: draft.faq[3] },
  ],
  finalVerdict: draft.finalVerdict,
  metaTitle: draft.metaTitle ?? `${name} ${category} Guide | BevOry`,
  metaDescription: draft.metaDescription,
});

export const BRAND_CONTENT_BATCH_45: Record<string, BrandPublicContent> = {
  "8848-himalayas": guide("8848 Himalayas", "Vodka", {
    description: "8848 is a Nepali vodka built around French winter wheat and Himalayan water. The name refers to Mount Everest's height in metres, giving the bottle an unmistakable home address.",
    story: "The distiller runs the wheat spirit through copper columns five times before filtering it through silver and platinum carbon. Himalayan water is added at the final blending stage.",
    notes: ["Original vodka", "The producer describes a smooth, crisp pour with a clean finish.", "Wheat base", "Winter wheat gives the spirit a soft texture without added flavouring."],
    serve: "Chill the original vodka well, or use it in a tall soda with fresh lime.",
    food: "A cold highball cuts through chicken momos, chilli paneer or fried prawns.",
    pairings: ["chicken momos", "chilli paneer", "fried prawns"],
    whyChoose: "A Nepali vodka whose wheat base and Himalayan-water blend are both clearly documented.",
    faq: ["Where is 8848 vodka from?", "8848 is a Nepali vodka named after Mount Everest's height.", "What is 8848 vodka made from?", "Its original expression uses French winter wheat and Himalayan water."],
    finalVerdict: "8848 makes most sense as a cold, spare pour that leaves its crisp character intact.",
    metaDescription: "Explore 8848 vodka from Nepal, its winter-wheat base, serving ideas and city prices on BevOry.",
  }),
  alcobrew: guide("Alcobrew", "Whisky", {
    description: "Alcobrew is an Indian spirits company whose Single Oak whisky combines Scotch whisky, Indian grain spirit and matured malt. The bottle sits in the company's whisky range alongside Golfer's Shot and White & Blue.",
    story: "Alcobrew launched Single Oak in 2022 as it expanded its own malt-spirit production and cask stocks. The green bottle puts the oak-led blend at the centre of the label.",
    notes: ["Oak-led blend", "The mature malt component lends a wood note to the grain-spirit base.", "Scotch component", "Imported Scotch brings a malt accent to Single Oak's blended profile."],
    serve: "Try a small measure over ice before adding soda; the two pours show different sides of the blend.",
    food: "Its oak-and-grain direction suits mutton seekh, smoked paneer or roasted peanuts.",
    pairings: ["mutton seekh", "smoked paneer", "roasted peanuts"],
    whyChoose: "Single Oak has a documented mix of imported Scotch, Indian grain spirit and matured malt.",
    faq: ["Who makes Alcobrew Single Oak?", "Alcobrew Distilleries India makes it.", "Is Single Oak a single malt?", "No. It is a whisky blend that includes Scotch, Indian grain spirit and matured malt."],
    finalVerdict: "Single Oak is a straightforward choice for a blended Indian whisky with a visible malt component.",
    metaDescription: "Discover Alcobrew Single Oak whisky, its blend, food matches and city prices on BevOry.",
  }),
  "golden-circle": guide("Golden Circle", "Whisky", {
    description: "Golden Circle Global Craft is an Indian whisky introduced by Alcobrew Distilleries. It is the company's newer whisky label, separate from Single Oak and White & Blue.",
    story: "Alcobrew added Golden Circle to its portfolio in 2025, after building a wider base of grain spirit, malt production and matured cask stocks. Its global-craft name marks a move beyond the company's earlier flagship whisky labels.",
    notes: ["Whisky style", "Golden Circle belongs to Alcobrew's blended-whisky portfolio.", "At the table", "A small whisky-and-soda serve keeps the flavour alongside strongly spiced snacks."],
    serve: "Pour over one large cube or lengthen with chilled soda.",
    food: "Try it with tandoori mushrooms, mutton kebabs or pepper cashews.",
    pairings: ["tandoori mushrooms", "mutton kebabs", "pepper cashews"],
    whyChoose: "A recent Alcobrew whisky with a clear place in the Indian producer's expanding portfolio.",
    faq: ["Who makes Golden Circle whisky?", "Alcobrew Distilleries India makes Golden Circle Global Craft Whisky.", "When did Golden Circle enter the Alcobrew range?", "Alcobrew lists its launch in 2025."],
    finalVerdict: "Golden Circle is an Alcobrew whisky to reach for when the food is smoky and the pour is simple.",
    metaDescription: "Explore Golden Circle whisky from Alcobrew, serving ideas, Indian pairings and city prices on BevOry.",
  }),
  "one-more": guide("One More", "Vodka", {
    description: "One More is an Indian vodka range from Alcobrew Distilleries. Its bottles include plain vodka and fruit-led flavours such as orange and green apple.",
    story: "Alcobrew launched One More in 2021 with flavoured vodka as a key part of its range. It later extended the line with One More Next craft vodka.",
    notes: ["Orange", "The citrus-labelled expression gives a long soda serve a sweeter orange direction.", "Green apple", "This bottle takes the range towards sharper orchard-fruit flavour."],
    serve: "Use the plain vodka with lime and soda; keep the flavoured bottles cold and use less sweet mixer.",
    food: "Orange suits chilli paneer, while green apple works with crispy lotus stem or salted cashews.",
    pairings: ["chilli paneer", "crispy lotus stem", "salted cashews"],
    whyChoose: "An Alcobrew vodka line with plain and distinctly fruit-led choices.",
    faq: ["Who makes One More vodka?", "Alcobrew Distilleries India makes it.", "Does One More come in flavours?", "Yes. Its range includes orange and green apple bottles."],
    finalVerdict: "One More is built for an uncomplicated cold mixer, with sweetness adjusted to the bottle in hand.",
    metaDescription: "Explore One More plain and flavoured vodka, mixer ideas, food matches and city prices on BevOry.",
  }),
  "white-and-blue": guide("White & Blue", "Whisky", {
    description: "White & Blue is an Indian whisky owned by Alcobrew Distilleries. It is an established label in the company's portfolio, separate from the later Single Oak release.",
    story: "Alcobrew dates the launch of White & Blue to 2012. The whisky helped establish the company before it expanded into newer malt-led blends and flavoured vodka.",
    notes: ["Blended style", "White & Blue is a blended Indian whisky made for a familiar grain-and-malt pour.", "Long drink", "Soda lets the whisky sit comfortably beside spicy food without a sweet mixer."],
    serve: "Serve with a large cube, or add soda and a little ice for a longer drink.",
    food: "Bring it to the table with paneer tikka, chicken kebabs or masala peanuts.",
    pairings: ["paneer tikka", "chicken kebabs", "masala peanuts"],
    whyChoose: "One of Alcobrew's earliest named whisky labels, launched in 2012.",
    faq: ["Who owns White & Blue whisky?", "White & Blue is an Alcobrew Distilleries brand.", "Is White & Blue the same whisky as Single Oak?", "No. They are separate labels in Alcobrew's range."],
    finalVerdict: "White & Blue is the older Alcobrew label for a direct, easy whisky-and-soda serve.",
    metaDescription: "Meet White & Blue whisky from Alcobrew, its history, Indian food pairings and city prices on BevOry.",
  }),
  bibi: guide("Bibi Graetz", "Wine", {
    description: "Bibi Graetz makes Tuscan wine from vineyards around Fiesole and Florence. Casamatta and Soffocone show two sides of his Sangiovese work: young-vine freshness and a named Vincigliata vineyard.",
    story: "Graetz founded the winery in 2000 after growing up in a family of artists. Soffocone takes its name from the Vincigliata vineyard where the project began; Casamatta Rosso draws from younger sites between Florence and Siena.",
    notes: ["Casamatta Rosso", "Stainless-steel vinification keeps Sangiovese red fruit bright and immediate.", "Soffocone", "The Vincigliata Sangiovese spends time in large oak casks, adding a more settled structure."],
    serve: "Give Casamatta a medium red-wine glass; open Soffocone a little before dinner.",
    food: "Sangiovese's acidity works with tomato-rich paneer, mushroom ragù or lamb chops.",
    pairings: ["tomato paneer", "mushroom ragù", "grilled lamb chops"],
    whyChoose: "A Tuscan producer whose two named reds make the difference between site and style easy to taste.",
    faq: ["Where is Bibi Graetz wine made?", "His winery is in Fiesole, above Florence in Tuscany.", "What grape is used in Casamatta Rosso?", "The producer makes Casamatta Rosso from Sangiovese."],
    finalVerdict: "Start with Casamatta for lively Tuscan red fruit, then move to Soffocone for the Vincigliata vineyard.",
    metaDescription: "Explore Bibi Graetz Casamatta and Soffocone, Tuscan Sangiovese, pairings and city prices on BevOry.",
  }),
  "big-boss": guide("Big Boss", "Feni", {
    description: "Big Boss is a Goan feni label from Madame Rosa Distillery, with cashew and coconut bottles. The same portfolio also includes a grape brandy, so the name reaches beyond one local spirit.",
    story: "The Vaz family's distillery is tied to Goa's long-running feni trade. Big Boss appears in the Goa government's cashew-feni brand list and remains one of Madame Rosa's familiar labels.",
    notes: ["Cashew feni", "The cashew-apple distillate has the assertive fruit character that makes Goan feni distinctive.", "Coconut feni", "The coconut-sap spirit offers a different, drier route through the same local tradition."],
    serve: "Try a small chilled pour, or lengthen feni with soda and fresh lime.",
    food: "Pair cashew feni with recheado prawns, pork sorpotel or fried chana.",
    pairings: ["recheado prawns", "pork sorpotel", "fried chana"],
    whyChoose: "A longstanding Madame Rosa name with both cashew and coconut feni in the Goan tradition.",
    faq: ["Who makes Big Boss feni?", "Madame Rosa Distillery in Goa makes Big Boss.", "Is Big Boss only cashew feni?", "No. The range includes coconut feni and a grape brandy."],
    finalVerdict: "Big Boss is a useful entry to Goa's two distinct feni bases: cashew apple and coconut sap.",
    metaDescription: "Explore Big Boss cashew and coconut feni from Goa, serving ideas, pairings and city prices on BevOry.",
  }),
  siempre: guide("Siempre", "Tequila", {
    description: "Siempre is a tequila label founded by Monica Sanita and Alex Lacroix. Its Plata and Reposado bottles come from Jalisco, the Mexican state at the centre of tequila production.",
    story: "Sanita links the project to her grandmother's agricultural work with agave spirits in Mexico. The founders built Siempre by working with Jalisco distilleries rather than presenting the label as a single estate.",
    notes: ["Plata", "The unaged style puts agave and citrus at the front of the glass.", "Reposado", "A period in wood adds a softer, warmer side to the agave base."],
    serve: "Taste Plata neat before mixing a Margarita; use a small glass for Reposado.",
    food: "Try Plata with fish tacos or tandoori prawns, and Reposado with grilled corn.",
    pairings: ["fish tacos", "tandoori prawns", "grilled corn"],
    whyChoose: "A Jalisco tequila whose founders tell a specific family story rather than borrowing a generic heritage claim.",
    faq: ["Who founded Siempre tequila?", "Monica Sanita and Alex Lacroix founded Siempre.", "Where is Siempre tequila made?", "Its tequilas are made with partner distilleries in Jalisco, Mexico."],
    finalVerdict: "Siempre offers a clear choice between an agave-led Plata and a gentler Reposado.",
    metaDescription: "Explore Siempre Plata and Reposado tequila, Jalisco roots, food pairings and city prices on BevOry.",
  }),
  "seven-rivers": guide("Seven Rivers", "Rum", {
    description: "Seven Rivers Premium Spiced Rum is an Indian rum made from molasses and warm spices. Seven Rivers also makes beer, giving the name a place in both brewing and distilling.",
    story: "AB InBev extended Seven Rivers beyond craft beer into spirits as part of its Indian drinks portfolio. The rum draws its flavour direction from cinnamon, vanilla, nutmeg, clove and pepper.",
    notes: ["Spice", "Cinnamon, clove and nutmeg set the aromatic direction.", "Rum base", "Molasses gives the spiced blend a sweet, rounded foundation."],
    serve: "Pour over ice with cola and a squeeze of lime, or use ginger ale for a drier long drink.",
    food: "Its baking-spice notes sit well with pepper chicken, pork vindaloo or roasted cashews.",
    pairings: ["pepper chicken", "pork vindaloo", "roasted cashews"],
    whyChoose: "A spiced rum from an Indian craft-beverage name better known to some drinkers for beer.",
    faq: ["Is Seven Rivers a beer or a rum?", "Seven Rivers makes both beer and Premium Spiced Rum.", "What flavours Seven Rivers rum?", "The blend includes cinnamon, vanilla, nutmeg, clove and pepper."],
    finalVerdict: "Seven Rivers works as a spice-forward rum and ginger ale beside bold, peppery food.",
    metaDescription: "Explore Seven Rivers spiced rum, its molasses-and-spice profile, pairings and city prices on BevOry.",
  }),
  wingman: guide("Wingman", "Whisky", {
    description: "Wingman is a blended Indian whisky from Indospirit Beverages. Its Rare blended malt bottle combines selected malt whiskies with grain spirit.",
    story: "The Delhi-based company built Wingman around a casual sharing-drink identity and a distinctive pop-and-pour closure. The closure makes it easy to open the bottle at a crowded table.",
    notes: ["Nose", "The producer names floral and fruit notes with a hint of white chocolate.", "Palate", "Melon and citrus give the blend its lighter side before a rounded finish."],
    serve: "Try it over a single large cube first; add a splash of water if you prefer a softer pour.",
    food: "The fruit-led style works with chicken malai tikka, grilled paneer or salted almonds.",
    pairings: ["chicken malai tikka", "grilled paneer", "salted almonds"],
    whyChoose: "A newer Indian whisky with a documented malt-and-grain blend and a recognisable closure.",
    faq: ["Who makes Wingman whisky?", "Wingman is from Indospirit Beverages in New Delhi.", "Is Wingman a single malt?", "No. The producer describes a blend of selected malts and grain spirits."],
    finalVerdict: "Wingman is best approached as a light, fruit-led blended whisky, not as a single malt.",
    metaDescription: "Discover Wingman whisky, its malt-and-grain blend, tasting notes, pairings and city prices on BevOry.",
  }),
  "beach-house": guide("Beach House", "Rum", {
    description: "Beach House Gold Spiced is a rum associated with Mauritius and the Arcane spirits range. Its warm-spice character gives the label a different purpose from a plain white rum.",
    story: "The Beach House name places Mauritian rum in a coastal setting. Gold Spiced takes the producer's cane-spirit base toward warm spice rather than a plain rum pour.",
    notes: ["Gold Spiced", "Sweet spice sits over the rum's rounded cane character.", "Long drinks", "Ginger and lime bring sharper edges to the spiced base."],
    serve: "Pour Gold Spiced over ice with ginger ale and a wedge of lime.",
    food: "Try the long drink with grilled pineapple, jerk chicken or paneer tikka.",
    pairings: ["grilled pineapple", "jerk chicken", "paneer tikka"],
    whyChoose: "A Mauritian spiced-rum expression with an easy ginger-and-lime serve.",
    faq: ["Where is Beach House Gold Spiced rum from?", "The Gold Spiced expression is associated with Mauritius.", "How can Beach House Gold Spiced be served?", "Ginger ale, ice and lime make a simple long drink."],
    finalVerdict: "Beach House Gold Spiced belongs beside food with smoke, sweetness or a little heat.",
    metaDescription: "Explore Beach House Gold Spiced rum, Mauritian roots, food matches and city prices on BevOry.",
  }),
  antares: guide("Antares", "Wine", {
    description: "Antares is a Chilean wine range that includes Sauvignon Blanc and Carmenere. Its name comes from the bright southern star, a fitting reference for a label built around Chile's landscape.",
    story: "The producer draws fruit from Chilean vineyards and presents each grape separately. Carmenere and Sauvignon Blanc give the range a practical red-and-white choice without pretending the two wines taste alike.",
    notes: ["Sauvignon Blanc", "The white brings a fresh, fruit-led profile suited to chilled serving.", "Carmenere", "Chile's signature red grape gives the range a darker, softer-edged dinner wine."],
    serve: "Chill Sauvignon Blanc well; give Carmenere a medium red-wine glass.",
    food: "Pour the white with tandoori fish and the red with mushroom keema or lamb chops.",
    pairings: ["tandoori fish", "mushroom keema", "lamb chops"],
    whyChoose: "A Chilean range with two clearly different grape-led routes through the table.",
    faq: ["Where is Antares wine from?", "Antares wines come from Chile.", "Does Antares make white wine?", "Yes. Sauvignon Blanc is among its white wines."],
    finalVerdict: "Choose Antares by the dish: Sauvignon Blanc for freshness, Carmenere for deeper savoury food.",
    metaDescription: "Explore Antares Sauvignon Blanc and Carmenere from Chile, serving ideas and city prices on BevOry.",
  }),
  antica: guide("Antica", "Liqueur", {
    description: "Antica is an Italian sambuca made by Rossi d'Asiago. Its Classic bottle is led by star anise rather than the fruit flavours found elsewhere in the range.",
    story: "The distillery works in the Veneto foothills between the Dolomites and Venice. Antica's classic recipe uses star anise and a wider set of botanicals, while newer bottles take the same anise base into coffee, cherry and other flavours.",
    notes: ["Classic", "Star anise gives the liqueur its unmistakable liquorice-like aroma.", "Sweet finish", "The sweetness and herbal edge make it a compact after-dinner pour."],
    serve: "Serve a small measure chilled, over ice, or in espresso after dinner.",
    food: "Its anise bite suits biscotti, dark chocolate or a small bowl of roasted almonds.",
    pairings: ["biscotti", "dark chocolate", "roasted almonds"],
    whyChoose: "A Veneto-made sambuca whose star-anise character remains clear even in a short coffee serve.",
    faq: ["Who makes Antica Sambuca?", "Rossi d'Asiago makes Antica in Italy.", "What does Antica Sambuca Classic taste of?", "Star anise is its leading flavour."],
    finalVerdict: "Antica Classic makes a better after-dinner accent than a large sweet drink.",
    metaDescription: "Explore Antica Sambuca Classic, its Italian anise recipe, dessert pairings and city prices on BevOry.",
  }),
  aristocrat: guide("Aristocrat", "Whisky", {
    description: "Aristocrat is an Indian whisky name owned by Jagatjit Industries. Premium whisky is the best-known expression in a company portfolio that also uses the Aristocrat name on other spirits.",
    story: "Jagatjit Industries was founded in 1944 and built a major spirits business around its Kapurthala roots. Aristocrat became one of its flagship brands, with production extending beyond the original Punjab base.",
    notes: ["Premium whisky", "The familiar blended style is built for a direct whisky-and-soda pour.", "At dinner", "A little dilution keeps the whisky alongside spice-heavy food without a sugary mixer."],
    serve: "Use a large cube or top a measured pour with chilled soda.",
    food: "Try it with seekh kebabs, chilli paneer or masala peanuts.",
    pairings: ["seekh kebabs", "chilli paneer", "masala peanuts"],
    whyChoose: "A longstanding Jagatjit whisky label with a clear place in India's domestic spirits history.",
    faq: ["Who owns Aristocrat whisky?", "Jagatjit Industries owns the Aristocrat brand.", "Is Aristocrat only a whisky name?", "No. Jagatjit has also used the name for other spirit categories."],
    finalVerdict: "Aristocrat is an old-school Indian blended-whisky name for a simple, food-friendly serve.",
    metaDescription: "Explore Aristocrat whisky from Jagatjit Industries, serving ideas, food pairings and city prices on BevOry.",
  }),
  agavita: guide("Agavita", "Tequila", {
    description: "Agavita Blanco is a tequila made by Cooperativa Tequilera La Magdalena in Jalisco, Mexico. The clear expression leaves the blue-agave base at the front.",
    story: "The distillery is based in Magdalena, west of the town of Tequila. Agavita Blanco is bottled without a wood-resting stage, unlike the label's Gold expression.",
    notes: ["Agave", "The Blanco keeps the fresh agave core visible.", "Citrus edge", "Retail tasting notes describe citrus, herbs and a little pepper around that base."],
    serve: "Taste a small measure neat or shake with lime for a Margarita.",
    food: "A citrus serve works with fish tacos, tandoori prawns or grilled corn.",
    pairings: ["fish tacos", "tandoori prawns", "grilled corn"],
    whyChoose: "A Jalisco Blanco from a named tequila cooperative rather than an anonymous agave label.",
    faq: ["Where is Agavita tequila made?", "It is made in Magdalena, Jalisco, Mexico.", "Is Agavita Blanco oak-aged?", "No. Blanco is the unaged expression."],
    finalVerdict: "Agavita Blanco is most useful where its direct agave character can stay visible.",
    metaDescription: "Discover Agavita Blanco tequila from Jalisco, tasting notes, food matches and city prices on BevOry.",
  }),
  quaffine: guide("Quaffine", "Liqueur", {
    description: "Quaffine is an Indian cold-brew coffee liqueur made with Arabica beans from Chikmagalur, Karnataka. Coffee, not cream or chocolate, is the point of the bottle.",
    story: "The brand uses a long cold-brew extraction and a label that traces coffee's journey to India. Its Arabica beans come from Chikmagalur's coffee-growing hills.",
    notes: ["Coffee", "Medium-dark roasted Arabica gives Quaffine a clear coffee-first aroma.", "Cold brew", "The cold extraction keeps the drink smooth without hiding the bean's darker notes."],
    serve: "Pour a small measure over ice or shake it with espresso for a short cocktail.",
    food: "Try it with dark chocolate, coffee cake or a slice of bebinca.",
    pairings: ["dark chocolate", "coffee cake", "bebinca"],
    whyChoose: "A Chikmagalur-Arabica liqueur that puts its cold-brew method front and centre.",
    faq: ["Where does Quaffine's coffee come from?", "Its Arabica beans come from Chikmagalur, Karnataka.", "Is Quaffine a cream liqueur?", "No. Its base is cold-brew coffee rather than dairy cream."],
    finalVerdict: "Quaffine is a tidy after-dinner choice for someone who wants the coffee to lead.",
    metaDescription: "Explore Quaffine cold-brew coffee liqueur, Chikmagalur Arabica, pairings and city prices on BevOry.",
  }),
  "the-source": guide("The Source", "Wine", {
    description: "The Source is Sula Vineyards' premium Indian wine range. Its Cabernet Sauvignon, Sauvignon Blanc Reserve and Grenache Rose move from structured red to oak-influenced white and dry pink wine.",
    story: "Sula introduced the range with Grenache Rose in 2018 and later widened it to several grape-led wines. The label sits above Sula's everyday bottles without losing its Nashik vineyard identity.",
    notes: ["Cabernet Sauvignon", "Cherry, blackberry and plum meet a touch of chocolate; part of the wine rests in French oak.", "Sauvignon Blanc Reserve", "Oak contact gives the tropical-fruit white more weight than a brisk unoaked Sauvignon Blanc."],
    serve: "Pour Cabernet in a roomy red-wine glass; chill the Sauvignon Blanc Reserve before serving.",
    food: "Try Cabernet with laal maas or kadai paneer, and the white with grilled prawns.",
    pairings: ["laal maas", "kadai paneer", "grilled prawns"],
    whyChoose: "A Sula range that offers distinct, named grapes and visibly different winemaking styles.",
    faq: ["Who makes The Source wine?", "Sula Vineyards makes The Source in India.", "Is The Source only red wine?", "No. The range also includes Sauvignon Blanc Reserve and Grenache Rose."],
    finalVerdict: "The Source is worth choosing by grape and dish, rather than treating its bottles as one style.",
    metaDescription: "Explore Sula's The Source wines, Cabernet and Sauvignon Blanc notes, pairings and city prices on BevOry.",
  }),
  "lembranca-by-madame-rosa-1933": guide("Lembranca", "Feni", {
    description: "Lembranca is a Goan cashew feni from Madame Rosa Distillery. Oak-aged and charcoal-filtered feni are brought together for a more mellow expression of the local spirit.",
    story: "The Vaz family developed Lembranca within a distillery long associated with Big Boss feni. Goan cartoonist Mario Miranda illustrated its label, turning the bottle into a small piece of local visual culture.",
    notes: ["Cashew fruit", "The cashew-apple origin remains apparent beneath the gentler finish.", "Oak influence", "A period in wood gives the spirit a warmer edge than a fresh feni pour."],
    serve: "Sip a small measure over one cube, or add soda and a squeeze of lime.",
    food: "Goan chorizo pulao, recheado fish and roasted cashews all suit its fruit-and-oak profile.",
    pairings: ["Goan chorizo pulao", "recheado fish", "roasted cashews"],
    whyChoose: "A Madame Rosa cashew feni with both oak influence and a Mario Miranda label.",
    faq: ["Who makes Lembranca feni?", "Madame Rosa Distillery in Goa makes it.", "What is pictured on the Lembranca label?", "Mario Miranda illustrated the Goan scene on the bottle."],
    finalVerdict: "Lembranca is a gentler way into cashew feni without losing its Goan identity.",
    metaDescription: "Discover Lembranca cashew feni, its Goa heritage, oak-led style, pairings and city prices on BevOry.",
  }),
  kalevala: guide("Kalevala", "Gin", {
    description: "Kalevala is a Finnish gin made in Kitee, eastern Finland. Its distillery uses Finnish spring water and botanicals for a distinctly Nordic dry-gin range.",
    story: "The name draws from Finland's national epic, but the production setting is contemporary Kitee. A London Dry expression sits beside more local variations, including a gin with Jerusalem artichoke.",
    notes: ["Dry gin", "Juniper anchors the herbal profile.", "Kitee expression", "Jerusalem artichoke gives one local variation an earthy note."],
    serve: "Use a chilled tonic and a simple citrus garnish; try the dry gin first without a flavoured mixer.",
    food: "It works with tandoori fish, cucumber chaat or smoked salmon.",
    pairings: ["tandoori fish", "cucumber chaat", "smoked salmon"],
    whyChoose: "A Kitee-made gin range that joins a classic juniper base to an identifiable Finnish setting.",
    faq: ["Where is Kalevala gin made?", "Kalevala Distillery makes it in Kitee, eastern Finland.", "What makes the Kitee variation different?", "The distillery uses Jerusalem artichoke in that expression."],
    finalVerdict: "Kalevala rewards a restrained tonic serve that lets its botanical character remain clear.",
    metaDescription: "Explore Kalevala gin from Finland, botanical notes, serving ideas and city prices on BevOry.",
  }),
  dandelion: guide("Dandelion Vineyards", "Wine", {
    description: "Dandelion Vineyards is an Australian wine producer based in McLaren Vale, South Australia. Its Chardonnay sits in a wider range drawn from regions including the Adelaide Hills, Eden Valley and Barossa.",
    story: "The winery brings together fruit from older vineyard sites and winemaking led by Elena Brooks. Its Wonder Room in McLaren Vale lets visitors taste across those regional differences rather than treating South Australia as one vineyard.",
    notes: ["Chardonnay", "The white-wine range includes an Adelaide Hills Chardonnay with citrus and white-flower notes.", "Oak", "Measured oak contact can add texture without obscuring the wine's fruit."],
    serve: "Chill Chardonnay lightly rather than freezing it, and pour into a medium white-wine glass.",
    food: "Try it with chicken malai tikka, grilled prawns or a creamy mushroom dish.",
    pairings: ["chicken malai tikka", "grilled prawns", "creamy mushrooms"],
    whyChoose: "A South Australian winery where the region behind each bottle matters as much as the grape.",
    faq: ["Where is Dandelion Vineyards based?", "Its home is in McLaren Vale, South Australia.", "Does Dandelion make Chardonnay?", "Yes. Chardonnay appears in its Australian wine range."],
    finalVerdict: "Dandelion Chardonnay is a food-friendly introduction to the winery's regional approach.",
    metaDescription: "Explore Dandelion Vineyards Chardonnay, South Australian roots, pairings and city prices on BevOry.",
  }),
  "punter-soju": guide("Punter Soju", "Soju", {
    description: "Punter is a Korean soju range that includes Original and Peach. Its green bottles come from Real Trade's drinks portfolio in South Korea.",
    story: "Real Trade presents Punter as part of its export-facing spirits collection. The Original and fruit editions offer two ways into the light, chilled soju serve familiar at a Korean table.",
    notes: ["Original", "The plain expression keeps the drink cool and direct beside food.", "Peach", "The fruit edition adds a sweeter peach note."],
    serve: "Chill the bottle and pour small measures; keep the Peach expression free of extra syrup.",
    food: "Korean fried chicken, gochujang paneer or grilled mushrooms all welcome a cold pour.",
    pairings: ["Korean fried chicken", "gochujang paneer", "grilled mushrooms"],
    whyChoose: "A Korean soju name with a simple Original-versus-Peach decision.",
    faq: ["Where is Punter Soju from?", "Punter is presented by South Korea's Real Trade.", "Does Punter make a peach flavour?", "Yes. Peach appears alongside Original in the range."],
    finalVerdict: "Punter suits a chilled shared-table pour, especially when the food carries heat.",
    metaDescription: "Explore Punter Original and Peach soju, serving ideas, Korean-Indian pairings and city prices on BevOry.",
  }),
  bex: guide("BEX", "Wine", {
    description: "BEX is a Riesling wine name focused on Germany's Nahe region. Its white wine uses cool fermentation and stainless steel to preserve fruit and freshness.",
    story: "The Nahe sits between Germany's better-known Rhine and Mosel wine districts. BEX uses that regional identity, rather than oak or sweetness alone, to explain its Riesling.",
    notes: ["Fruit", "Peach and apricot sit alongside citrus in the producer's Riesling description.", "Finish", "A mineral note keeps the fruit from feeling heavy."],
    serve: "Serve well chilled in a white-wine glass, without ice in the wine itself.",
    food: "Try it with spicy prawn curry, chilli paneer or Thai basil chicken.",
    pairings: ["spicy prawn curry", "chilli paneer", "Thai basil chicken"],
    whyChoose: "A Nahe Riesling whose cool-fermented, steel-aged style keeps the grape bright.",
    faq: ["Where does BEX Riesling come from?", "BEX presents its Riesling as a wine from Germany's Nahe region.", "Is BEX Riesling aged in oak?", "The producer describes fermentation and ageing in stainless steel."],
    finalVerdict: "BEX brings Nahe Riesling's peach-and-citrus side to a spicy dinner table.",
    metaDescription: "Explore BEX Riesling from Germany's Nahe, tasting notes, spicy-food matches and city prices on BevOry.",
  }),
  "what-the-fox": guide("What the Fox", "Wine", {
    description: "What the Fox is a French wine range with Cabernet Sauvignon, Merlot and sparkling Brut bottles. Its Indian distributor presents the label as a playful route through several grape and wine styles.",
    story: "The illustrated fox links the bottles visually, but the wines do different jobs at the table. Cabernet brings black-fruit weight, Merlot offers a softer red, and Brut moves to sparkling wine.",
    notes: ["Cabernet Sauvignon", "Black plum and baking spice make this the fuller red in the range.", "Brut", "The sparkling bottle brings a fresher, drier opening pour."],
    serve: "Pour Brut chilled in a flute or small wine glass; serve Cabernet in a roomy red-wine glass.",
    food: "Try Brut with pakoras and Cabernet with lamb seekh or mushroom keema.",
    pairings: ["vegetable pakoras", "lamb seekh", "mushroom keema"],
    whyChoose: "A French range with genuine red-and-sparkling variety behind its lively label.",
    faq: ["Is What the Fox only red wine?", "No. The range includes a Brut sparkling wine as well as reds.", "Which red grapes appear under What the Fox?", "Cabernet Sauvignon and Merlot both appear in the range."],
    finalVerdict: "What the Fox is best picked by the moment: Brut to open, Cabernet for a heartier plate.",
    metaDescription: "Explore What the Fox French Cabernet, Merlot and Brut, pairing ideas and city prices on BevOry.",
  }),
  tickle: guide("Tickle", "Gin", {
    description: "Tickle Dry Gin is a Goan spirit made by Adinco Distilleries. Its dry-gin base has Indian spice influences, giving it a different direction from a citrus-only gin.",
    story: "Adinco is also behind Goa's Cabo coconut liqueur, but Tickle takes the distillery into gin. Cardamom, clove and cinnamon are associated with its botanical profile.",
    notes: ["Botanicals", "Cardamom and clove bring warmth around the expected juniper base.", "Spice", "Cinnamon gives the aroma a softer, sweeter edge without turning the gin into a liqueur."],
    serve: "Use plain tonic, plenty of ice and a thin lime wheel rather than a sweet mixer.",
    food: "Try it with tandoori prawns, chilli-lime peanuts or cucumber chaat.",
    pairings: ["tandoori prawns", "chilli-lime peanuts", "cucumber chaat"],
    whyChoose: "A Goa-made dry gin that uses familiar Indian kitchen spices in a restrained serve.",
    faq: ["Who makes Tickle Dry Gin?", "Adinco Distilleries in Goa makes Tickle.", "What botanicals give Tickle its spice?", "Cardamom, clove and cinnamon are among its reported spice notes."],
    finalVerdict: "Tickle works best in a simple tonic that leaves room for its spice-led gin character.",
    metaDescription: "Explore Tickle Dry Gin from Goa, spice notes, tonic serves, food pairings and city prices on BevOry.",
  }),
  "06": guide("06", "Vodka", {
    description: "06 Rose Vodka is a French flavoured vodka that combines winter-wheat spirit with rose-wine extract. Its floral direction is distinct from an unflavoured vodka.",
    story: "The rose-wine connection points to Provence, where the extract is associated with Chateau Vert. The bottle takes the region's pink-wine identity into a clear spirit rather than presenting itself as wine.",
    notes: ["Rose", "A light floral aroma sits over the vodka base.", "Wine extract", "The rose-wine element adds a soft fruit note without turning the spirit into a grape wine."],
    serve: "Chill it and use soda with a strip of lemon peel; avoid a heavily sweetened mixer.",
    food: "Try the floral highball with grilled prawns, malai tikka or fresh strawberries.",
    pairings: ["grilled prawns", "chicken malai tikka", "fresh strawberries"],
    whyChoose: "A French vodka whose rose-wine extract gives it a specific Provençal identity.",
    faq: ["Where is 06 Rose Vodka from?", "It is a French flavoured vodka.", "Is 06 Rose Vodka a wine?", "No. It is vodka infused with rose-wine extract."],
    finalVerdict: "06 Rose is for a cold, lightly floral vodka-and-soda rather than a sugary cocktail.",
    metaDescription: "Discover 06 Rose Vodka from France, its floral profile, food matches and city prices on BevOry.",
  }),
  adira: guide("Adira", "Wine", {
    description: "Adira is a Spanish wine name sold in India with a Merlot bottle. Its appeal is the softer red-fruit side of Merlot rather than the firm grip of a young Cabernet Sauvignon.",
    story: "Indian importer C2C has promoted Adira Merlot as part of its wine selection. The label brings Spain's familiar Merlot grape to a straightforward red-wine table style.",
    notes: ["Merlot", "Ripe red fruit and a softer tannin profile make the grape approachable with dinner.", "Red-wine body", "A medium red-wine glass gives its fruit more room than a chilled tumbler."],
    serve: "Serve slightly below room temperature in a medium red-wine glass.",
    food: "Try it with mushroom galouti, tomato-based pasta or paneer tikka.",
    pairings: ["mushroom galouti", "tomato pasta", "paneer tikka"],
    whyChoose: "A Merlot-led Spanish wine name with a direct Indian-market presence.",
    faq: ["What kind of wine is Adira Merlot?", "It is a red wine made from Merlot grapes.", "Is Adira sold in India?", "Indian importer C2C has promoted Adira Merlot in its wine range."],
    finalVerdict: "Adira Merlot is a comfortable red for tomato, mushroom and lightly smoky dishes.",
    metaDescription: "Explore Adira Merlot, its red-wine style, Indian food pairings and city prices on BevOry.",
  }),
  arka: guide("Arka", "Mead", {
    description: "Arka is an Indian dessert mead range built around honey and local fruit or flowers. Jamun, rose and honey-led bottles bring three different directions to the same fermented-honey base.",
    story: "The range emerged from Maharashtra's fruit-wine and mead scene, with a production connection to the Sinnar area near Nashik. Jamun and dried rose petals give the line a more local vocabulary than imported fruit flavours.",
    notes: ["Jamun", "The Indian berry adds a dark, tart fruit edge to honey sweetness.", "Rose", "Petal aroma gives the floral bottle a different finish from the fruit-led Jamun."],
    serve: "Chill lightly and pour a small glass after dinner.",
    food: "Pair the Jamun mead with gulab jamun, dark chocolate or a small piece of aged cheddar.",
    pairings: ["gulab jamun", "dark chocolate", "aged cheddar"],
    whyChoose: "A Maharashtra mead range that uses jamun and rose rather than anonymous fruit flavouring.",
    faq: ["What is Arka mead made from?", "Arka is a fermented-honey drink with Jamun, rose and honey-led editions.", "Is Arka a wine made from grapes?", "No. Mead is based on fermented honey."],
    finalVerdict: "Arka gives Indian fruit and flowers a small, dessert-friendly place in the glass.",
    metaDescription: "Explore Arka Jamun and Rose mead from Maharashtra, dessert pairings and city prices on BevOry.",
  }),
  antaraa: guide("Antaraa", "Wine", {
    description: "Antaraa is a Cabernet Sauvignon-Shiraz red from the Good Earth wine range in Nashik. The blend brings two familiar red grapes into one Indian dinner wine.",
    story: "Good Earth introduced Antaraa as a Cabernet-Shiraz blend before the winery business passed to Good Drop Wine Cellars. Early production combined tank-kept Cabernet with a smaller oak-aged Shiraz component.",
    notes: ["Cabernet", "Cabernet Sauvignon gives the blend dark-fruit weight and structure.", "Shiraz", "The oak-aged Shiraz portion brings a warmer spice accent."],
    serve: "Pour into a medium red-wine glass and give it a few minutes after opening.",
    food: "Mutton seekh, mushroom keema or grilled lamb are natural matches.",
    pairings: ["mutton seekh", "mushroom keema", "grilled lamb"],
    whyChoose: "A Nashik red with a documented Cabernet-and-Shiraz blend rather than an unnamed house style.",
    faq: ["What grapes are in Antaraa?", "Antaraa is a Cabernet Sauvignon-Shiraz blend.", "Who introduced Antaraa?", "The Good Earth winery introduced it before Good Drop acquired the business."],
    finalVerdict: "Antaraa is a Nashik red for a fuller, spice-rich dinner.",
    metaDescription: "Discover Antaraa Cabernet-Shiraz from Nashik, tasting notes, pairings and city prices on BevOry.",
  }),
  "nine-hill": guide("Nine Hills", "Wine", {
    description: "Nine Hills is a Nashik wine label from Pernod Ricard India. Its range includes Chenin Blanc alongside red grapes such as Shiraz and Cabernet Sauvignon.",
    story: "Seagram India introduced Nine Hills in 2006, taking its name from the hills around Nashik. The wines gave Pernod Ricard an Indian grape-wine line alongside its international drinks portfolio.",
    notes: ["Chenin Blanc", "The white offers a fresh, fruit-led direction for a lighter plate.", "Red wines", "Shiraz and Cabernet Sauvignon move the range toward darker fruit and firmer dinner pairings."],
    serve: "Chill Chenin Blanc; use a medium glass for the reds.",
    food: "Try Chenin with paneer tikka and the reds with mutton seekh or baingan bharta.",
    pairings: ["paneer tikka", "mutton seekh", "baingan bharta"],
    whyChoose: "A Nashik wine name with a documented 2006 launch and several familiar grape choices.",
    faq: ["Who makes Nine Hills wine?", "Nine Hills is a Pernod Ricard India wine label.", "Where does the Nine Hills name come from?", "It refers to the hills around Nashik, Maharashtra."],
    finalVerdict: "Nine Hills is easiest to explore by grape, starting with Chenin for light food and reds for richer dishes.",
    metaDescription: "Explore Nine Hills Chenin Blanc and reds from Nashik, Indian pairings and city prices on BevOry.",
  }),
  "vijay-amtriraj": guide("Vijay Amritraj Reserve", "Wine", {
    description: "Vijay Amritraj Reserve Collection is an Indian wine range made by Grover Zampa. Named for the tennis player, it includes reserve wines with an oak-ageing step.",
    story: "Grover Zampa presents the range in its barrel room alongside La Reserve, Chene and Signet. The collection carries the name of Indian tennis player Vijay Amritraj.",
    notes: ["Reserve style", "Oak contact gives the wines more texture than a purely tank-kept table wine.", "Red direction", "The reserve reds call for a larger glass and food with some weight."],
    serve: "Serve reds just below room temperature and give them a few minutes in the glass.",
    food: "Try the red with tandoori lamb, mushroom galouti or aged cheddar.",
    pairings: ["tandoori lamb", "mushroom galouti", "aged cheddar"],
    whyChoose: "An oak-aged Grover Zampa collection tied to Vijay Amritraj by name and Indian wine production.",
    faq: ["Who makes Vijay Amritraj Reserve Collection?", "Grover Zampa makes the collection in India.", "Are the wines oak-aged?", "Grover Zampa includes the range among the wines it ages in imported oak barrels."],
    finalVerdict: "Vijay Amritraj Reserve belongs at the table with food that can meet its oak-aged structure.",
    metaDescription: "Explore Vijay Amritraj Reserve wines from Grover Zampa, pairings and city prices on BevOry.",
    metaTitle: "Vijay Amritraj Reserve Wine Guide | BevOry",
  }),
};
