import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_35 = [
  ["st-hugo", "St Hugo", "Australia", "Wine", "15f2423e2b951088618abe6a"],
  ["st-pierre", "St Pierre", "France", "Beer", "9238b39acfe6e163ea17aa0e"],
  ["star-of-bombay", "Star of Bombay", "United Kingdom", "Gin", "d310bcd9d26de45285d26af9"],
  ["stara-myslivecka", "Stara Myslivecka", "Czech Republic", "Rye Spirit", "aacd5f5f0e225b995656a56d"],
  ["stark-conde", "Stark-Conde", "South Africa", "Wine", "d7f102ecf959fbef7d0ff9df"],
  ["stella-rosa", "Stella Rosa", "Italy", "Wine", "8bfea1bb21fb9b8de880b1e3"],
  ["stepp", "Stepp", "Germany", "Wine", "362a0653bc7ecd4c4258ac97"],
  ["strange-nature", "Strange Nature", "New Zealand", "Gin", "db839d271b160a8ecdb5ff5c"],
  ["stranger-and-sons", "Stranger & Sons", "India", "Gin", "ec41fba1690783a6deb6425c"],
  ["sula", "Sula", "India", "Wine", "e9ecd4af9e5061c4cba71f79"],
  ["svedka", "Svedka", "Sweden", "Vodka", "59666ae22919f64cba491357"],
  ["tabernero", "Tabernero", "Peru", "Pisco", "8cbdb74034217ba9a2083133"],
  ["talamonti", "Talamonti", "Italy", "Wine", "0df7d5dbc089af0dc3613c48"],
  ["taylors", "Taylors", "Australia", "Wine", "f4080d61efd0af178c36ca79"],
  ["tears-of-llorona", "Tears of Llorona", "Mexico", "Tequila", "b3e7c48eb6e9416a9f6cee12"],
  ["tequila-komos", "Tequila Komos", "Mexico", "Tequila", "bd062ae11fa5099138a4b89e"],
  ["tequila-rose", "Tequila Rose", "United States", "Liqueur", "a34bba5848a8415f6b360378"],
  ["terrazas", "Terrazas de los Andes", "Argentina", "Wine", "ad5d5225c1be8bf9c4ca0604"],
  ["terroir-daronton", "Terroir Daronton", "France", "Wine", "f95b194ce740bf5eec904197"],
  ["the-lane", "The Lane", "Australia", "Wine", "ef7f4f590c115bdd10470f02"],
  ["thelema", "Thelema", "South Africa", "Wine", "9644efd2eb9ea37e71a70ee7"],
  ["three-bridges", "Three Bridges", "Australia", "Wine", "a440ceb028b51b213f7f9247"],
  ["tignanello", "Tignanello", "Italy", "Red Wine", "52ab767dd738295f8d5660e0"],
  ["toit", "Toit", "India", "Beer", "8693a23084d1bdb0806cf74b"],
  ["torbreck", "Torbreck", "Australia", "Wine", "51217d055f890ad9ff0bdf3e"],
  ["tornatore", "Tornatore", "Italy", "Wine", "ea4740c17fcf52411dbfc299"],
  ["torres", "Familia Torres", "Spain", "Wine", "eda7a59466adce3a5349eaac"],
  ["trapiche", "Trapiche", "Argentina", "Wine", "79477f8b22535b1ae696170f"],
  ["triennes", "Triennes", "France", "Wine", "d9edfc76a1d36142c9ad9863"],
  ["tromba", "Tequila Tromba", "Mexico", "Tequila", "11f25776692eac0f2734f0e5"],
] as const;

// Research and asset provenance never enter public copy.
export const BRAND_SOURCES_BATCH_35: Record<string, string[]> = {
  "st-hugo": ["https://sthugo.com/pages/heritage"],
  "st-pierre": ["https://www.lasaintpierre.com/notre-histoire/"],
  "star-of-bombay": ["https://www.bombaysapphire.com/fr/fr/products/star-of-bombay/"],
  "stara-myslivecka": ["https://staramyslivecka.cz/en/destilujeme-500-let/"],
  "stark-conde": ["https://stark-conde.co.za/our-story/", "https://karatarawines.co.za/wp-content/uploads/2021/06/kt_fact_pinotnoir_19.pdf"],
  "stella-rosa": ["https://stellarosawines.com/our-story/"],
  stepp: ["https://cfdf.german-pavilion.com/en/sites/exhibitors/135984"],
  "strange-nature": ["https://strangenaturegin.com/"],
  "stranger-and-sons": ["https://strangerandsons.com/"],
  sula: ["https://sulavineyards.com/our-history.php", "https://sulavineyards.com/our-people.php"],
  svedka: ["https://www.sazerac.com/our-brands/sazerac-brands/svedka.html", "https://svedka.com/"],
  tabernero: ["https://www.tabernero.com/en/", "https://tabernero.com/en/producto/edicion-limitada-quebranta-pisco/"],
  talamonti: ["https://www.tenutatalamonti.it/en/estate-en/"],
  taylors: ["https://www.wakefieldwines.com/pages/our-story", "https://www.taylorswines.com.au/blogs/wine-blog/st-andrews-story"],
  "tears-of-llorona": ["https://tearsofllorona.com/"],
  "tequila-komos": ["https://komos.com/tequilas/reposado-rosa", "https://shop.komos.com/shop"],
  "tequila-rose": ["https://tequilarose.com/"],
  terrazas: ["https://www.terrazasdelosandes.com/en-us/about-us"],
  "terroir-daronton": ["https://www.terroirdaronton.fr/en/history-of-a-thousand-year-old-terroir/", "https://www.terroirdaronton.fr/nos-vins/les-crus/"],
  "the-lane": ["https://www.thelane.com.au/about-us/"],
  thelema: ["https://www.thelema.co.za/our-story"],
  "three-bridges": ["https://www.calabriawines.com.au/our-wines/three-bridges", "https://www.calabriawines.com.au/three-bridges-chardonnay"],
  tignanello: ["https://www.antinori.it/en/vino/tignanello/"],
  toit: ["https://toit.in/restaurant/toit-bangalore/"],
  torbreck: ["https://torbreck.com/pages/our-story"],
  tornatore: ["https://www.tornatorevini.com/company-base-crafts-people/?lang=en"],
  torres: ["https://www.torres.es/en/news/familia-torres-celebrates-150-years-internationally-renowned-family-winery"],
  trapiche: ["https://trapiche.com.ar/comex/en/winery/"],
  triennes: ["https://www.triennes.com/notre-philosophie/"],
  tromba: ["https://tequilatromba.com/pages/about-us"],
};

// All 16 assets were opened and visually checked. Sula and Svedka already have stored logos.
export const BRAND_LOGOS_BATCH_35: Record<string, string> = {
  "st-hugo": "https://sthugo.com/cdn/shop/files/small_logo.png",
  "st-pierre": "https://www.lasaintpierre.com/wp-content/uploads/2018/05/SP_Logo-288.png",
  "stara-myslivecka": "https://staramyslivecka.cz/wp-content/uploads/2023/03/SZM_logo_old-hunters_mobil.png",
  "stark-conde": "https://stark-conde.co.za/wp-content/uploads/2025/11/sc_logo_website_2-scaled-1-1024x282.webp",
  "strange-nature": "https://strangenaturegin.com/cdn/shop/files/Strange_Nature_Full_Logo_White.png",
  "stranger-and-sons": "https://strangerandsons.com/assets/build/ss-logo.webp",
  tabernero: "https://www.tabernero.com/static_tabernero/img/logo-tabernero-1.svg",
  taylors: "https://www.taylorswines.com.au/cdn/shop/files/taylors-logo-dark.svg",
  "tears-of-llorona": "https://tearsofllorona.com/cdn/shop/files/logo-tears-of-llorona-black.svg",
  "tequila-komos": "https://cdn.prod.website-files.com/6238c4355ba5436391290ba2/650ca632f4f740cbd4d63a4b_komos-logo.svg",
  "terroir-daronton": "https://www.terroirdaronton.fr/wp-content/uploads/2025/10/logo_TerroirDaronton.png",
  "the-lane": "https://www.thelane.com.au/wp-content/uploads/2022/03/Logo-for-website-Google.png",
  torbreck: "https://torbreck.com/cdn/shop/files/torbreck-logo-white.png",
  torres: "https://www.torres.es/themes/custom/torres_theme/logo.png",
  triennes: "https://www.triennes.com/wp-content/themes/astra-child/assets/images/logo/triennes-logo-color.png",
  tromba: "https://tequilatromba.com/cdn/shop/files/Outlined_yellow_logo_a40c42e2-a2a6-480a-960b-dcd178d83680.png",
};

export const BRAND_CONTENT_BATCH_35: Record<string, BrandPublicContent> = {
  "st-hugo": {
    description: "St Hugo is an Australian wine label associated with Cabernet Sauvignon from Coonawarra and Shiraz from the Barossa Valley. It sits in Pernod Ricard's wine portfolio and focuses on substantial South Australian reds.",
    story: "The name honours Hugo Gramp, a figure in Barossa winemaking. The label brings together two regions with different strengths: Coonawarra's Cabernet vineyards and the Barossa's old Shiraz vines.",
    tastingNotes: [{ title: "Coonawarra Cabernet", description: "Blackcurrant and mint run through the firm, dark-fruited red." }, { title: "Barossa Shiraz", description: "Ripe plum and pepper give the fuller Shiraz its warmth." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour either red just below room temperature in a generous wine glass." }, { subheading: "Food", description: "Cabernet suits lamb rogan josh; Shiraz takes on smoky seekh kebabs." }],
    pairingIdeas: [{ title: "South Australian table", items: ["lamb rogan josh", "mutton seekh", "grilled steak", "aged cheddar"] }],
    whyChoose: "Two classic South Australian red-wine regions under one label.",
    faqs: [{ question: "Which regions make St Hugo's best-known reds?", answer: "Coonawarra is associated with its Cabernet Sauvignon and the Barossa Valley with its Shiraz." }, { question: "Who owns St Hugo?", answer: "St Hugo is part of Pernod Ricard's wine portfolio." }],
    finalVerdict: "St Hugo belongs at a table where the food can match a firm Australian red.",
    metaTitle: "St Hugo Wine Guide | BevOry", metaDescription: "Explore St Hugo Coonawarra Cabernet, Barossa Shiraz and food pairings. Check city prices on BevOry.",
  },
  "st-pierre": {
    description: "St Pierre is a beer range brewed in Alsace, France, by Brasserie Artisanale de Saint-Pierre. The range includes Blonde and White beers made with regional hops and barley malt.",
    story: "The brewery began in 2001 in the Alsatian village of Saint-Pierre. Local hops and water from Saint-Pierre helped give a small regional brewery its own identity.",
    tastingNotes: [{ title: "Blonde", description: "Light malt and a gentle hop bitterness keep the golden beer crisp." }, { title: "White", description: "The wheat-led white beer has a softer body and a brighter, lightly spiced finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve cold in a clean beer glass with room for the head." }, { subheading: "Food", description: "Blonde suits chicken tikka; White works with fish fry and lemon." }],
    pairingIdeas: [{ title: "With Alsatian beer", items: ["chicken tikka", "fish fry", "pretzel", "salted almonds"] }],
    whyChoose: "A small Alsatian brewery with both crisp Blonde and softer White styles.",
    faqs: [{ question: "Where is St Pierre beer brewed?", answer: "It is brewed in Saint-Pierre in Alsace, France." }, { question: "Does St Pierre make a wheat beer?", answer: "Yes. The range includes a White beer alongside its Blonde." }],
    finalVerdict: "Choose Blonde for a clean lager-like pour or White for a softer wheat-beer mood.",
    metaTitle: "St Pierre Beer Guide | BevOry", metaDescription: "Discover St Pierre beer from Alsace, Blonde and White styles, and pairings. Check city prices on BevOry.",
  },
  "star-of-bombay": {
    description: "Star of Bombay is a gin expression from Bombay Sapphire, made with twelve botanicals. Bergamot peel from Calabria and ambrette seeds from Ecuador add to the familiar juniper-led recipe.",
    story: "Bombay Sapphire developed Star of Bombay as a slower-distilled, more aromatic relative of its original blue-bottle gin. The additional botanicals give a distinct reason for this label to exist beyond the familiar packaging.",
    tastingNotes: [{ title: "Bergamot", description: "A fragrant citrus lift sits above the juniper." }, { title: "Spice", description: "Ambrette and coriander bring a rounded, lightly peppery finish." }],
    howToEnjoy: [{ subheading: "Martini", description: "Stir with dry vermouth and strain cold into a small Martini glass." }, { subheading: "Food", description: "Try it with tandoori prawns or lemony olives." }],
    pairingIdeas: [{ title: "Citrus and salt", items: ["tandoori prawns", "lemony olives", "fried calamari", "salted pistachios"] }],
    whyChoose: "A more aromatic Bombay Sapphire gin built around bergamot and ambrette.",
    faqs: [{ question: "How many botanicals are in Star of Bombay?", answer: "Bombay Sapphire uses twelve botanicals in Star of Bombay." }, { question: "What makes it different from Bombay Sapphire?", answer: "Bergamot and ambrette join the core botanicals, with a slower vapour-infusion distillation." }],
    finalVerdict: "Star of Bombay is at its best when a cold Martini leaves the botanicals uncluttered.",
    metaTitle: "Star of Bombay Gin Guide | BevOry", metaDescription: "Explore Star of Bombay's bergamot gin, Martini serve and food matches. Check city prices on BevOry.",
  },
  "stara-myslivecka": {
    description: "Stara Myslivecka is a Czech rye spirit also marketed as Old Hunter's Rye. It comes from the Palirna U Zeleneho stromu distillery in Prostejov.",
    story: "The distillery traces its roots through centuries of Czech distilling. Its rye recipe became associated with the Old Hunter name after Jakub Vojacek and Luis Eckelmann brought it to a wider market.",
    tastingNotes: [{ title: "Rye", description: "Grain spice and a gentle sweetness shape the core rye spirit." }, { title: "Oak", description: "The Reserve expression adds a deeper, wood-led finish." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try a small neat pour, then over one cube if you prefer a softer edge." }, { subheading: "Food", description: "Rye spice works with smoked sausage or masala peanuts." }],
    pairingIdeas: [{ title: "With rye", items: ["smoked sausage", "masala peanuts", "mutton seekh", "rye bread"] }],
    whyChoose: "A Czech rye label with a distillery history distinct from American rye whiskey.",
    faqs: [{ question: "Where is Stara Myslivecka made?", answer: "It comes from the Palirna U Zeleneho stromu distillery in Prostejov, Czech Republic." }, { question: "Is Old Hunter's Rye the same label?", answer: "Old Hunter's Rye is the international name used for Stara Myslivecka." }],
    finalVerdict: "The rye's warm grain character suits a small pour beside savoury snacks.",
    metaTitle: "Stara Myslivecka Rye Guide | BevOry", metaDescription: "Meet Stara Myslivecka, Czech Old Hunter's Rye, serving ideas and pairings. Check city prices on BevOry.",
  },
  "stark-conde": {
    description: "Stark-Conde is a South African wine estate in the Jonkershoek Valley near Stellenbosch. Cabernet Sauvignon and Syrah anchor the estate range, while Kara-Tara carries Pinot Noir from cooler Cape sites.",
    story: "The Stark and Conde family names meet in a farm surrounded by the mountains of Jonkershoek. Vineyards there sit close to the protected fynbos landscape, giving the winery a strong sense of place.",
    tastingNotes: [{ title: "Jonkershoek Cabernet", description: "Dark berries and a savoury herbal edge suit the structured red." }, { title: "Kara-Tara Pinot Noir", description: "Red cherry and gentle spice give the lighter wine its lift." }],
    howToEnjoy: [{ subheading: "Temperature", description: "Serve Cabernet a little cool; give Pinot Noir a lighter chill." }, { subheading: "Food", description: "Try Cabernet with mutton kebabs and Pinot with mushroom tikka." }],
    pairingIdeas: [{ title: "Cape table", items: ["mutton kebabs", "mushroom tikka", "roast duck", "aged gouda"] }],
    whyChoose: "A Jonkershoek estate with a clear contrast between structured Cabernet and bright Pinot Noir.",
    faqs: [{ question: "Where is Stark-Conde based?", answer: "Its estate is in the Jonkershoek Valley near Stellenbosch, South Africa." }, { question: "Is Kara-Tara part of Stark-Conde?", answer: "Kara-Tara is a related Pinot Noir project connected with the Stark-Conde winemaking team." }],
    finalVerdict: "Stark-Conde is especially good company for a Cape red-wine dinner.",
    metaTitle: "Stark-Conde Wine Guide | BevOry", metaDescription: "Explore Stark-Conde, Jonkershoek Cabernet and Kara-Tara Pinot Noir. Check city prices on BevOry.",
  },
  "stella-rosa": {
    description: "Stella Rosa is the Riboli family's Italian semi-sweet, lightly sparkling wine range. Moscato d'Asti from Piedmont sits at the centre of its identity.",
    story: "The Riboli family's connection to Asti runs through matriarch Maddalena Riboli. That region's aromatic grapes shaped Stella Rosa's first Moscato-led wines before the range widened into other fruit-forward styles.",
    tastingNotes: [{ title: "Moscato", description: "Peach and orange blossom meet a gentle spritz." }, { title: "Pink styles", description: "Red berry fruit and sweetness make the pink wines easy to serve cold." }],
    howToEnjoy: [{ subheading: "Cold glass", description: "Chill Moscato well and pour into a small white-wine glass." }, { subheading: "Food", description: "Its sweetness works with chilli paneer or fruit tart." }],
    pairingIdeas: [{ title: "Sweet and spicy", items: ["chilli paneer", "fruit tart", "spiced cashews", "strawberry cake"] }],
    whyChoose: "A gently sparkling Italian wine for drinkers who like noticeable fruit and sweetness.",
    faqs: [{ question: "Who makes Stella Rosa?", answer: "Stella Rosa is made by the Riboli family." }, { question: "What is Stella Rosa's flagship style?", answer: "Moscato d'Asti, a lightly sparkling sweet white wine from Piedmont, is central to the range." }],
    finalVerdict: "Stella Rosa Moscato makes more sense chilled beside spice or dessert than beside a heavy main course.",
    metaTitle: "Stella Rosa Wine Guide | BevOry", metaDescription: "Explore Stella Rosa Moscato, light bubbles, sweet fruit and food pairings. Check city prices on BevOry.",
  },
  stepp: {
    description: "Stepp is the Pfalz wine project of German winemaker Gerd Stepp. Riesling and Pinot varieties are central to wines from vineyards around Bad Durkheim.",
    story: "Stepp grew up in a local wine family, worked internationally as a winemaker and returned to the Pfalz to work with family vineyards and nearby growers. His range includes limestone-site Riesling and Pinot Noir rose.",
    tastingNotes: [{ title: "Riesling", description: "Citrus and orchard fruit sit over a dry, lively palate." }, { title: "Pinot Noir rose", description: "Red berries and brisk acidity make the pink wine a lighter table choice." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve both wines cool in a white-wine glass." }, { subheading: "Food", description: "Riesling suits fish tikka; the rose can take a plate of paneer tikka." }],
    pairingIdeas: [{ title: "Pfalz table", items: ["fish tikka", "paneer tikka", "roast chicken", "goat cheese"] }],
    whyChoose: "A Pfalz winemaker using Riesling and Pinot to show a few different sides of the region.",
    faqs: [{ question: "Who makes Stepp wine?", answer: "Gerd Stepp runs the wine project." }, { question: "Where are Stepp wines from?", answer: "They come from the Pfalz wine region of Germany." }],
    finalVerdict: "Stepp's Riesling is a straightforward place to begin with the Pfalz's dry whites.",
    metaTitle: "Stepp Wine Guide | BevOry", metaDescription: "Discover Gerd Stepp's Pfalz Riesling, Pinot Noir rose and pairings. Check city prices on BevOry.",
  },
  "strange-nature": {
    description: "Strange Nature is a New Zealand gin made with spirit from Sauvignon Blanc grapes. The grape base links its flavour to wine country rather than the usual grain-spirit route.",
    story: "The project took a grape spirit with a recognisable Sauvignon Blanc character and turned it into gin. Juniper gives it the legal and sensory centre of the style while the base adds a distinctive fruit note.",
    tastingNotes: [{ title: "Sauvignon Blanc base", description: "Fresh tropical fruit and citrus recall the wine grape behind the spirit." }, { title: "Juniper", description: "A peppery juniper edge keeps the finish recognisably gin-like." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use a dry tonic and plenty of ice; skip a sweet garnish." }, { subheading: "Food", description: "Try with tandoori prawns or a crisp cucumber salad." }],
    pairingIdeas: [{ title: "Fresh plates", items: ["tandoori prawns", "cucumber salad", "goat cheese", "salted almonds"] }],
    whyChoose: "Gin that carries a clear trace of New Zealand Sauvignon Blanc into the glass.",
    faqs: [{ question: "What is Strange Nature Gin made from?", answer: "Its base spirit comes from Sauvignon Blanc grapes." }, { question: "Is Strange Nature still a gin?", answer: "Yes. Juniper is part of the botanical profile." }],
    finalVerdict: "Strange Nature is a fresh, grape-led alternative to a conventional London Dry gin.",
    metaTitle: "Strange Nature Gin Guide | BevOry", metaDescription: "Explore Strange Nature Sauvignon Blanc gin, its grape base and pairings. Check city prices on BevOry.",
  },
  "stranger-and-sons": {
    description: "Stranger & Sons is an Indian gin made by Third Eye Distillery in Goa. It uses Indian citrus and spices alongside juniper for a fuller botanical style.",
    story: "The gin emerged from a Goa distillery interested in making Indian ingredients part of the liquid rather than just the label. Its later releases have included collaborations and local flavours beyond the core gin.",
    tastingNotes: [{ title: "Citrus", description: "Indian citrus brings a bright opening over the juniper." }, { title: "Spice", description: "Warm spice gives the gin a longer, savoury finish." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Pour with dry tonic and a simple citrus wedge over plenty of ice." }, { subheading: "Food", description: "Try it with pepper chicken or tandoori mushrooms." }],
    pairingIdeas: [{ title: "Goa snacks", items: ["pepper chicken", "tandoori mushrooms", "prawn balchao", "masala cashews"] }],
    whyChoose: "A Goa gin that lets Indian citrus and spice do real work in the glass.",
    faqs: [{ question: "Where is Stranger & Sons made?", answer: "It is made in Goa, India, by Third Eye Distillery." }, { question: "Is Stranger & Sons a London Dry gin?", answer: "The core gin is juniper-led but built with a notably Indian botanical profile." }],
    finalVerdict: "Stranger & Sons makes a gin and tonic that stands up to a spicy snack plate.",
    metaTitle: "Stranger & Sons Gin Guide | BevOry", metaDescription: "Explore Stranger & Sons gin from Goa, Indian botanicals and pairings. Check city prices on BevOry.",
  },
  sula: {
    description: "Sula is a Nashik wine producer founded by Rajeev Samant. Its Indian portfolio spans Chenin Blanc, Sauvignon Blanc, Shiraz, Zinfandel and sparkling wines.",
    story: "Samant returned to his family's land near Nashik in the 1990s and began planting wine grapes. Sula's first winery followed in 1999, helping turn the region into India's best-known wine destination.",
    tastingNotes: [{ title: "Chenin Blanc", description: "Citrus and orchard fruit keep the white fresh." }, { title: "Shiraz", description: "Ripe dark fruit and spice make the red a fuller dinner pour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the whites and bubbles; serve the reds lightly cool." }, { subheading: "Food", description: "Chenin suits paneer tikka, while Shiraz handles mutton seekh." }],
    pairingIdeas: [{ title: "Nashik table", items: ["paneer tikka", "mutton seekh", "tandoori fish", "roasted peanuts"] }],
    whyChoose: "A Nashik winery that helped give Indian wine a place on everyday tables.",
    faqs: [{ question: "Who founded Sula?", answer: "Rajeev Samant founded Sula in Nashik." }, { question: "Where are Sula wines made?", answer: "Sula's home winery is in Nashik, Maharashtra." }],
    finalVerdict: "Sula is a useful starting point for tasting how India's own wine regions handle familiar grapes.",
    metaTitle: "Sula Wine Guide | BevOry", metaDescription: "Discover Sula's Nashik wines, Chenin, Shiraz and Indian food pairings. Check city prices on BevOry.",
  },
  svedka: {
    description: "Svedka is a vodka label with Swedish roots and a range of plain and flavoured expressions. It now sits in Sazerac's spirits portfolio.",
    story: "The brand launched in the late 1990s and built a name around accessible vodka and bright flavour variants. Its ownership moved from Constellation Brands to Sazerac in 2025.",
    tastingNotes: [{ title: "Original", description: "A neutral, clean vodka profile leaves room for the mixer." }, { title: "Flavoured bottles", description: "Fruit-led variants such as Citron and Peach bring their own aroma to a long drink." }],
    howToEnjoy: [{ subheading: "Long drink", description: "Chill Original and lengthen with soda and fresh lime." }, { subheading: "Food", description: "A simple vodka soda works beside salty fries or fish tikka." }],
    pairingIdeas: [{ title: "Easy snacks", items: ["fish tikka", "salted fries", "cucumber salad", "roasted cashews"] }],
    whyChoose: "A versatile vodka range that keeps the plain spirit and fruit flavours clearly separate.",
    faqs: [{ question: "Who owns Svedka?", answer: "Svedka is part of Sazerac's vodka portfolio." }, { question: "Does Svedka make flavoured vodka?", answer: "Yes. The range includes fruit-flavoured variants as well as Original." }],
    finalVerdict: "Original is the cleaner cocktail base; a flavoured Svedka is the quicker route to a fruit-led highball.",
    metaTitle: "Svedka Vodka Guide | BevOry", metaDescription: "Explore Svedka Original and flavoured vodkas, mixers and food matches. Check city prices on BevOry.",
  },
  tabernero: {
    description: "Tabernero is a Peruvian wine and pisco producer with a long history in the Chincha Valley. Its pisco range includes Quebranta and aromatic grape styles.",
    story: "The winery dates to 1897. As Peruvian pisco grew beyond its home market, Tabernero kept grape names on its labels so drinkers could distinguish Quebranta from aromatic varieties such as Torontel.",
    tastingNotes: [{ title: "Quebranta", description: "A dry grape-spirit character with soft fruit and a clean finish." }, { title: "Torontel", description: "Floral and citrus aromas distinguish the aromatic grape expression." }],
    howToEnjoy: [{ subheading: "Sour", description: "Shake pisco with lime, syrup and egg white for a classic Pisco Sour." }, { subheading: "Food", description: "Try it with ceviche or tandoori prawns." }],
    pairingIdeas: [{ title: "With pisco", items: ["ceviche", "tandoori prawns", "roasted corn", "salted cashews"] }],
    whyChoose: "A Peruvian producer whose pisco labels make the grape difference easy to explore.",
    faqs: [{ question: "Where is Tabernero from?", answer: "Tabernero is a producer from Peru's Chincha Valley." }, { question: "What is Quebranta pisco?", answer: "It is a pisco made from the Quebranta grape, one of Peru's traditional pisco varieties." }],
    finalVerdict: "Quebranta makes a firm Pisco Sour, while Torontel is worth smelling before the first sip.",
    metaTitle: "Tabernero Pisco Guide | BevOry", metaDescription: "Discover Tabernero pisco, Quebranta and Torontel styles, and pairings. Check city prices on BevOry.",
  },
  talamonti: {
    description: "Talamonti is an Abruzzo wine estate founded by the Redmont-Di Tonno family. Montepulciano d'Abruzzo is a central red, with local white grapes also in the range.",
    story: "The family established the estate in 2001 in eastern Italy. Its work with oak vessels of different origins and sizes reflects an interest in how Montepulciano responds to ageing.",
    tastingNotes: [{ title: "Montepulciano", description: "Dark cherry and plum give the red its broad fruit character." }, { title: "Oak influence", description: "A little spice and roundness develop in the more mature bottlings." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour the red slightly cool and give a fuller bottle a little air." }, { subheading: "Food", description: "Try with mutton seekh or tomato-braised aubergine." }],
    pairingIdeas: [{ title: "Abruzzo table", items: ["mutton seekh", "tomato-braised aubergine", "roast pork", "pecorino"] }],
    whyChoose: "An Abruzzo producer that gives Montepulciano room to show both fruit and oak.",
    faqs: [{ question: "Where is Talamonti?", answer: "The estate is in Abruzzo, Italy." }, { question: "Which red grape is Talamonti known for?", answer: "Montepulciano is central to its red wines." }],
    finalVerdict: "Talamonti Montepulciano is an easy match for a savoury red-sauce dinner.",
    metaTitle: "Talamonti Wine Guide | BevOry", metaDescription: "Explore Talamonti Montepulciano from Abruzzo, tasting notes and pairings. Check city prices on BevOry.",
  },
  taylors: {
    description: "Taylors is a family wine producer from the Clare Valley in South Australia, sold as Wakefield in some markets. Its Promised Land range includes Chardonnay and Shiraz.",
    story: "The Taylor family entered the Clare Valley wine trade in the late 1950s and acquired vineyard land in 1969. The Promised Land name comes from one of the blocks on that original property.",
    tastingNotes: [{ title: "Chardonnay", description: "Stone fruit and citrus give the white wine a rounded but fresh profile." }, { title: "Shiraz", description: "Dark berries and gentle spice lead the red." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Chardonnay; pour Shiraz a touch below room temperature." }, { subheading: "Food", description: "Try Chardonnay with tandoori fish and Shiraz with peppery lamb." }],
    pairingIdeas: [{ title: "Clare Valley table", items: ["tandoori fish", "peppery lamb", "roast chicken", "aged cheddar"] }],
    whyChoose: "A Clare Valley family winery with approachable whites and reds under Promised Land.",
    faqs: [{ question: "Where is Taylors Wines based?", answer: "The family winery is based in South Australia's Clare Valley." }, { question: "Why is Taylors also called Wakefield?", answer: "Wakefield is the name used for the family's wines in some export markets." }],
    finalVerdict: "Taylors offers an uncomplicated path from a chilled Chardonnay to a fuller Shiraz.",
    metaTitle: "Taylors Wine Guide | BevOry", metaDescription: "Explore Taylors Clare Valley wines, Promised Land Chardonnay and Shiraz. Check city prices on BevOry.",
  },
  "tears-of-llorona": {
    description: "Tears of Llorona is an extra anejo tequila created by Mexican master distiller German Gonzalez. Blue agave spirit spends years in oak before bottling as a slow-sipping tequila.",
    story: "Gonzalez first imagined the tequila for family and friends rather than a broad release. His five-year ageing plan gives the agave time with wood well beyond the minimum for extra anejo.",
    tastingNotes: [{ title: "Agave", description: "Cooked agave remains present beneath the oak." }, { title: "Mature oak", description: "Dried fruit, vanilla and spice give the long-aged tequila its depth." }],
    howToEnjoy: [{ subheading: "Neat", description: "Pour a small measure at room temperature in a narrow tasting glass." }, { subheading: "Food", description: "Try it after dinner with dark chocolate or spiced pecans." }],
    pairingIdeas: [{ title: "After dinner", items: ["dark chocolate", "spiced pecans", "caramel flan", "aged gouda"] }],
    whyChoose: "A long-aged tequila built for sipping, with German Gonzalez's distilling experience behind it.",
    faqs: [{ question: "Who makes Tears of Llorona?", answer: "Master distiller German Gonzalez created the tequila." }, { question: "What type of tequila is Tears of Llorona?", answer: "It is an extra anejo tequila aged for five years." }],
    finalVerdict: "Give Tears of Llorona a small glass and enough time for agave and oak to come through.",
    metaTitle: "Tears of Llorona Tequila Guide | BevOry", metaDescription: "Discover Tears of Llorona extra anejo, oak notes and pairings. Check city prices on BevOry.",
  },
  "tequila-komos": {
    description: "Komos is a tequila label from Jalisco, Mexico, known for wine-cask finishing and ceramic bottles. Its expressions include Reposado Rosa and Anejo Cristalino.",
    story: "The label draws on both tequila making and wine maturation. Reposado Rosa spends time in French oak red-wine barrels, giving a different direction to the usual reposado profile.",
    tastingNotes: [{ title: "Reposado Rosa", description: "Cooked agave meets soft red-fruit and oak notes." }, { title: "Anejo Cristalino", description: "Aged agave character appears in a clear, smooth-textured pour." }],
    howToEnjoy: [{ subheading: "Sip", description: "Pour a small measure into a tasting glass and let it warm slightly." }, { subheading: "Food", description: "Try Reposado Rosa with achiote chicken or paneer tikka." }],
    pairingIdeas: [{ title: "At the table", items: ["achiote chicken", "paneer tikka", "grilled prawns", "dark chocolate"] }],
    whyChoose: "Wine-cask finishing gives this Jalisco tequila a distinct point of view.",
    faqs: [{ question: "Where is Komos tequila made?", answer: "Komos is made in Jalisco, Mexico." }, { question: "What is Komos Reposado Rosa?", answer: "It is a reposado tequila rested in French oak barrels previously used for red wine." }],
    finalVerdict: "Komos Reposado Rosa rewards a slow sip before dinner.",
    metaTitle: "Tequila Komos Guide | BevOry", metaDescription: "Explore Komos tequila, Reposado Rosa, serving ideas and food pairings. Check city prices on BevOry.",
  },
  "tequila-rose": {
    description: "Tequila Rose is a strawberry cream liqueur made with tequila. It is a sweet, dairy-based drink rather than a straight tequila for sipping or mixing in a Margarita.",
    story: "The label brought tequila into the cream-liqueur aisle through a recognisable strawberry flavour. Its pink bottle has become part of the drink's identity as much as the flavour itself.",
    tastingNotes: [{ title: "Strawberry", description: "Sweet berry flavour leads the first sip." }, { title: "Cream", description: "A thick, smooth texture gives the liqueur its dessert-like finish." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve well chilled in a small glass or over ice." }, { subheading: "Dessert", description: "Pour alongside chocolate cake or fresh strawberries." }],
    pairingIdeas: [{ title: "Sweet finish", items: ["chocolate cake", "fresh strawberries", "vanilla ice cream", "gulab jamun"] }],
    whyChoose: "Strawberry cream and tequila make an unmistakably sweet after-dinner pour.",
    faqs: [{ question: "Is Tequila Rose straight tequila?", answer: "No. It is a strawberry cream liqueur containing tequila." }, { question: "How should Tequila Rose be served?", answer: "Serve it cold, either neat or over ice." }],
    finalVerdict: "Choose Tequila Rose for dessert, not for a traditional tequila tasting.",
    metaTitle: "Tequila Rose Liqueur Guide | BevOry", metaDescription: "Discover Tequila Rose strawberry cream liqueur, serving ideas and desserts. Check city prices on BevOry.",
  },
  terrazas: {
    description: "Terrazas de los Andes is an Argentine winery working with high-altitude vineyards in Mendoza. Malbec is central to its range, alongside Cabernet Sauvignon and other wines.",
    story: "The winery grew around a simple Mendoza idea: match each grape with the altitude where it ripens best. Its vineyard work spans the Andean foothills rather than one uniform valley floor.",
    tastingNotes: [{ title: "Malbec", description: "Black plum and violet lead a ripe but fresh red." }, { title: "Cabernet Sauvignon", description: "Blackcurrant and savoury spice give the firmer red its shape." }],
    howToEnjoy: [{ subheading: "Glass", description: "Pour Malbec slightly cool in a generous red-wine glass." }, { subheading: "Food", description: "Try it with lamb chops or seekh kebabs." }],
    pairingIdeas: [{ title: "Mendoza table", items: ["lamb chops", "mutton seekh", "mushroom tikka", "chimichurri steak"] }],
    whyChoose: "A Mendoza producer whose wines make Andean altitude tangible in the glass.",
    faqs: [{ question: "Where is Terrazas de los Andes based?", answer: "It works with vineyards in Mendoza, Argentina." }, { question: "Which grape is Terrazas de los Andes known for?", answer: "Malbec is a central grape in its range." }],
    finalVerdict: "Terrazas Malbec fits a meal with smoke, spice and a little char.",
    metaTitle: "Terrazas de los Andes Wine Guide | BevOry", metaDescription: "Explore Mendoza Malbec from Terrazas de los Andes, tasting notes and pairings. Check city prices on BevOry.",
  },
  "terroir-daronton": {
    description: "Terroir Daronton is a French wine label rooted in the southern Rhone, especially Vacqueyras. It draws on the growers of a cooperative established in 1956.",
    story: "Winegrowers around Vacqueyras joined forces to bottle the character of their own vineyards. Their cooperative later became part of Rhonea, retaining the Daronton name for wines from its local growers.",
    tastingNotes: [{ title: "Red Rhone", description: "Dark fruit and pepper sit over the warmth of southern Rhone grapes." }, { title: "Rose", description: "Red berries and fresh acidity make the lighter wine suited to a chilled pour." }],
    howToEnjoy: [{ subheading: "Serve", description: "Pour the red a little cool and chill the rose well." }, { subheading: "Food", description: "Red suits lamb rogan josh; rose is good with tandoori prawns." }],
    pairingIdeas: [{ title: "Rhone table", items: ["lamb rogan josh", "tandoori prawns", "ratatouille", "grilled aubergine"] }],
    whyChoose: "A southern Rhone growers' label with Vacqueyras at its heart.",
    faqs: [{ question: "Where does Terroir Daronton come from?", answer: "The label is rooted in Vacqueyras in France's southern Rhone." }, { question: "Is Terroir Daronton a cooperative wine?", answer: "Yes. Its history began with local winegrowers forming a cooperative in 1956." }],
    finalVerdict: "Daronton brings the warmth of the southern Rhone to a savoury dinner.",
    metaTitle: "Terroir Daronton Wine Guide | BevOry", metaDescription: "Discover Terroir Daronton from Vacqueyras, Rhone reds and food matches. Check city prices on BevOry.",
  },
  "the-lane": {
    description: "The Lane is an Australian winery in the Adelaide Hills, South Australia. Chardonnay is a key part of its cool-climate range, alongside Pinot Noir and other varieties.",
    story: "The Edwards family planted their first vineyard in 1993. The hillside site above Hahndorf became the winery's home and gave the label its Adelaide Hills identity.",
    tastingNotes: [{ title: "Chardonnay", description: "Citrus and stone fruit keep the white lively." }, { title: "Pinot Noir", description: "Red cherry and gentle spice give the lighter red its lift." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve Chardonnay chilled and Pinot Noir lightly cool." }, { subheading: "Food", description: "Try Chardonnay with tandoori fish and Pinot with roast duck." }],
    pairingIdeas: [{ title: "Adelaide Hills table", items: ["tandoori fish", "roast duck", "mushroom tikka", "grilled prawns"] }],
    whyChoose: "The Lane makes a clear case for the freshness of Adelaide Hills wine.",
    faqs: [{ question: "Where is The Lane winery?", answer: "It is in the Adelaide Hills of South Australia, near Hahndorf." }, { question: "When did The Lane begin?", answer: "The Edwards family planted the vineyard in 1993." }],
    finalVerdict: "The Lane Chardonnay is an appealing white for a fish or vegetable dinner.",
    metaTitle: "The Lane Wine Guide | BevOry", metaDescription: "Explore The Lane's Adelaide Hills Chardonnay and Pinot Noir with pairings. Check city prices on BevOry.",
  },
  thelema: {
    description: "Thelema is a South African wine estate on the Simonsberg slopes near Stellenbosch. Cabernet Sauvignon and Sauvignon Blanc are among its best-known wines.",
    story: "Gyles Webb bought the former fruit farm in 1983 and planted it with vines. The mountain setting helped establish Thelema as a Stellenbosch estate with a strong sense of place.",
    tastingNotes: [{ title: "Cabernet Sauvignon", description: "Blackcurrant and cedar shape the structured red." }, { title: "Sauvignon Blanc", description: "Citrus and herbal notes keep the white brisk." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill Sauvignon Blanc; give Cabernet a generous glass." }, { subheading: "Food", description: "The white suits tandoori prawns, the red mutton seekh." }],
    pairingIdeas: [{ title: "Simonsberg table", items: ["tandoori prawns", "mutton seekh", "goat cheese", "grilled mushrooms"] }],
    whyChoose: "A Stellenbosch estate with recognisable Simonsberg Cabernet and Sauvignon Blanc.",
    faqs: [{ question: "Where is Thelema?", answer: "The estate lies on the Simonsberg slopes near Stellenbosch, South Africa." }, { question: "Who founded Thelema winery?", answer: "Gyles Webb developed the winery after buying the property in 1983." }],
    finalVerdict: "Thelema offers a firm red and a brisk white from one mountain estate.",
    metaTitle: "Thelema Wine Guide | BevOry", metaDescription: "Meet Thelema's Stellenbosch Cabernet and Sauvignon Blanc with pairings. Check city prices on BevOry.",
  },
  "three-bridges": {
    description: "Three Bridges is a wine range from Australia's Calabria family. It covers regional wines including Chardonnay and Shiraz, with fruit sources varying by bottle.",
    story: "The Calabria family built its winery in the Riverina and expanded into wines from other Australian regions. Three Bridges became one of the family's labels for those regional expressions.",
    tastingNotes: [{ title: "Chardonnay", description: "Stone fruit and citrus make the white a rounded dinner wine." }, { title: "Shiraz", description: "Dark berries and pepper give the red more weight." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the Chardonnay and pour the Shiraz slightly cool." }, { subheading: "Food", description: "Chardonnay suits chicken tikka; Shiraz takes grilled lamb." }],
    pairingIdeas: [{ title: "With dinner", items: ["chicken tikka", "grilled lamb", "roast cauliflower", "aged cheddar"] }],
    whyChoose: "A Calabria family range that explores Australian wine beyond one region.",
    faqs: [{ question: "Who makes Three Bridges wine?", answer: "Three Bridges is produced by the Calabria family in Australia." }, { question: "Is every Three Bridges wine from the Riverina?", answer: "No. The range uses fruit from different Australian regions." }],
    finalVerdict: "Three Bridges gives you a straightforward choice between a rounded white and a fuller red.",
    metaTitle: "Three Bridges Wine Guide | BevOry", metaDescription: "Explore Calabria's Three Bridges Chardonnay and Shiraz with pairings. Check city prices on BevOry.",
  },
  tignanello: {
    description: "Tignanello is a Tuscan red wine from the Antinori family estate in Chianti Classico. Its blend brings Sangiovese together with Cabernet Sauvignon and Cabernet Franc.",
    story: "Antinori first made the wine from the Tignanello vineyard in the 1970s. The decision to blend international grapes with Sangiovese helped define the modern Super Tuscan era.",
    tastingNotes: [{ title: "Red fruit", description: "Cherry and plum bring the Sangiovese side forward." }, { title: "Structure", description: "Dark fruit, spice and firm tannin give the wine its long finish." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give the red time in a large glass after opening." }, { subheading: "Food", description: "Try with lamb rogan josh or slow-cooked beef." }],
    pairingIdeas: [{ title: "Tuscan red table", items: ["lamb rogan josh", "slow-cooked beef", "porcini risotto", "aged pecorino"] }],
    whyChoose: "An Antinori wine that changed the conversation about Tuscan reds.",
    faqs: [{ question: "Who makes Tignanello?", answer: "The Antinori family makes it from its Tignanello estate in Tuscany." }, { question: "Which grapes are in Tignanello?", answer: "The blend uses Sangiovese, Cabernet Sauvignon and Cabernet Franc." }],
    finalVerdict: "Tignanello earns a place beside a slow, savoury dinner.",
    metaTitle: "Tignanello Red Wine Guide | BevOry", metaDescription: "Discover Antinori Tignanello, its Tuscan grapes, tasting profile and pairings. Check city prices on BevOry.",
  },
  toit: {
    description: "Toit is a Bengaluru craft brewery and brewpub serving beers made on site. Its range includes styles such as Banger Lager and Nitro Stout.",
    story: "Toit made fresh draft beer a regular part of Bengaluru's pub culture. The Indiranagar brewpub pairs an in-house brewery with a busy food kitchen rather than treating beer as an afterthought.",
    tastingNotes: [{ title: "Banger Lager", description: "Light malt and a crisp finish keep the lager refreshing." }, { title: "Nitro Stout", description: "Roasted malt and a creamy texture make the darker beer slower to drink." }],
    howToEnjoy: [{ subheading: "Fresh pour", description: "Order draft beer cold in the glass suited to its style." }, { subheading: "Food", description: "Lager fits chilli paneer; stout works with chocolate dessert." }],
    pairingIdeas: [{ title: "Brewpub plates", items: ["chilli paneer", "pepper chicken", "wood-fired pizza", "chocolate brownie"] }],
    whyChoose: "Fresh Bengaluru-brewed beer with a style for both light and dark beer drinkers.",
    faqs: [{ question: "Where is Toit based?", answer: "Toit began as a brewpub in Bengaluru, India." }, { question: "Does Toit brew its own beer?", answer: "Yes. Toit brews beer for its brewpubs." }],
    finalVerdict: "At Toit, start with a fresh lager and leave room to try the stout.",
    metaTitle: "Toit Beer Guide | BevOry", metaDescription: "Explore Toit beer from Bengaluru, Banger Lager and Nitro Stout with pairings. Check city prices on BevOry.",
  },
  torbreck: {
    description: "Torbreck is a Barossa Valley winery in South Australia focused on Shiraz and other Rhone varieties. Its reds draw on mature vineyards across the valley.",
    story: "David Powell founded Torbreck in 1994, naming it after a Scottish forest where he had worked. He set out to make Barossa wines inspired by the Rhone, with old vines central to the project.",
    tastingNotes: [{ title: "Shiraz", description: "Dark plum and black pepper give the red its Barossa depth." }, { title: "Rhone blend", description: "Grenache and Mourvedre can add red fruit and savoury spice." }],
    howToEnjoy: [{ subheading: "Glass", description: "Give the red a broad glass and serve just below room temperature." }, { subheading: "Food", description: "Pair with mutton seekh or charcoal-grilled lamb." }],
    pairingIdeas: [{ title: "Barossa table", items: ["mutton seekh", "charcoal-grilled lamb", "roast aubergine", "hard cheese"] }],
    whyChoose: "Old Barossa vines and Rhone grapes give Torbreck its bold signature.",
    faqs: [{ question: "Who founded Torbreck?", answer: "David Powell founded Torbreck in 1994." }, { question: "Where are Torbreck wines from?", answer: "Torbreck is based in South Australia's Barossa Valley." }],
    finalVerdict: "Torbreck Shiraz is built for a smoky, substantial main course.",
    metaTitle: "Torbreck Wine Guide | BevOry", metaDescription: "Explore Torbreck Barossa Shiraz, old vines and Rhone-inspired reds. Check city prices on BevOry.",
  },
  tornatore: {
    description: "Tornatore is a Sicilian winery on the northern slopes of Mount Etna. It works with local grapes including Nerello Mascalese for red wine and Carricante for white.",
    story: "The Tornatore family's agricultural roots on Etna reach back to the nineteenth century. Volcanic soils and the mountain's changing elevations shape the vineyards around Castiglione di Sicilia.",
    tastingNotes: [{ title: "Etna Rosso", description: "Red cherry and smoky mineral notes lead the Nerello Mascalese red." }, { title: "Etna Bianco", description: "Citrus and a stony edge give Carricante its taut profile." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the white and serve the red lightly cool." }, { subheading: "Food", description: "Carricante suits tandoori fish; Nerello works with roast mushrooms." }],
    pairingIdeas: [{ title: "Etna table", items: ["tandoori fish", "roast mushrooms", "tomato pasta", "grilled aubergine"] }],
    whyChoose: "A direct introduction to Etna's two distinctive local wine grapes.",
    faqs: [{ question: "Where is Tornatore winery?", answer: "It is on the northern side of Mount Etna in Sicily, Italy." }, { question: "Which grapes does Tornatore use?", answer: "Nerello Mascalese and Carricante are central to its Etna reds and whites." }],
    finalVerdict: "Tornatore makes the contrast between Etna red and white worth exploring.",
    metaTitle: "Tornatore Wine Guide | BevOry", metaDescription: "Discover Tornatore Etna wines, Nerello Mascalese and Carricante. Check city prices on BevOry.",
  },
  torres: {
    description: "Familia Torres is a Spanish wine producer founded in the Penedes region of Catalonia. Its wines now span several Spanish regions and include both familiar and recovered local grapes.",
    story: "Jaime and Miguel Torres established the family company in 1870. Later generations expanded its vineyards while working to bring nearly lost Catalan varieties back into production.",
    tastingNotes: [{ title: "Penedes whites", description: "Citrus and orchard fruit give the fresher wines their lift." }, { title: "Spanish reds", description: "Dark fruit and spice appear in the fuller, oak-influenced bottles." }],
    howToEnjoy: [{ subheading: "Serve", description: "Chill the whites and pour the reds slightly cool." }, { subheading: "Food", description: "Try a white with grilled prawns or a red with lamb kebabs." }],
    pairingIdeas: [{ title: "Spanish table", items: ["grilled prawns", "lamb kebabs", "patatas bravas", "manchego"] }],
    whyChoose: "A long-running Catalan family winery with a wide view of Spanish grapes.",
    faqs: [{ question: "Where did Familia Torres begin?", answer: "The family wine company began in Penedes, Catalonia, in 1870." }, { question: "Does Torres only make wine in Penedes?", answer: "No. Its Spanish wines also come from other regions." }],
    finalVerdict: "Torres is a useful route into the variety of Spanish wine beyond one appellation.",
    metaTitle: "Familia Torres Wine Guide | BevOry", metaDescription: "Explore Familia Torres from Penedes, Spanish grape varieties and pairings. Check city prices on BevOry.",
  },
  trapiche: {
    description: "Trapiche is an Argentine wine producer based in Mendoza. Malbec is prominent in its range, alongside other red and white varieties.",
    story: "The winery traces its beginnings to 1883. Over generations, Trapiche became one of Mendoza's best-known names while exploring fruit from different vineyard districts.",
    tastingNotes: [{ title: "Malbec", description: "Plum and dark cherry sit beside soft spice." }, { title: "Cabernet Sauvignon", description: "Blackcurrant and firmer tannin make a more structured red." }],
    howToEnjoy: [{ subheading: "Glass", description: "Serve Malbec a little cool in a red-wine glass." }, { subheading: "Food", description: "Try it with mutton seekh or a grilled mushroom skewer." }],
    pairingIdeas: [{ title: "Mendoza table", items: ["mutton seekh", "grilled mushroom skewers", "roast beef", "hard cheese"] }],
    whyChoose: "A historic Mendoza producer with Malbec at the centre of a broad range.",
    faqs: [{ question: "Where is Trapiche from?", answer: "Trapiche is based in Mendoza, Argentina." }, { question: "When was Trapiche founded?", answer: "Its history dates to 1883." }],
    finalVerdict: "Trapiche Malbec is a reliable partner for charred, savoury food.",
    metaTitle: "Trapiche Wine Guide | BevOry", metaDescription: "Explore Trapiche Malbec from Mendoza, tasting notes and food pairings. Check city prices on BevOry.",
  },
  triennes: {
    description: "Triennes is a wine estate in Provence's Var department, France. It is especially associated with pale rose, alongside red and white wines.",
    story: "Jacques Seysses of Domaine Dujac and Aubert de Villaine of Domaine de la Romanee-Conti joined the project around 1990. The estate's limestone country offered them a different French landscape from Burgundy.",
    tastingNotes: [{ title: "Rose", description: "Red berries and citrus keep the pale wine bright." }, { title: "White", description: "Fresh orchard fruit and herbal notes suit a chilled glass." }],
    howToEnjoy: [{ subheading: "Chill", description: "Serve the rose cold, but not icy, in a white-wine glass." }, { subheading: "Food", description: "Try rose with tandoori prawns or a tomato salad." }],
    pairingIdeas: [{ title: "Provence table", items: ["tandoori prawns", "tomato salad", "grilled courgette", "goat cheese"] }],
    whyChoose: "A Provence rose with a notable Burgundian connection.",
    faqs: [{ question: "Where is Triennes made?", answer: "The estate is in the Var department of Provence, France." }, { question: "Who started Triennes?", answer: "Jacques Seysses and Aubert de Villaine were among the founders of the project." }],
    finalVerdict: "Triennes rose is a bright choice for a seafood or vegetable lunch.",
    metaTitle: "Triennes Wine Guide | BevOry", metaDescription: "Discover Triennes Provence rose, its founders and food pairings. Check city prices on BevOry.",
  },
  tromba: {
    description: "Tromba is a tequila label made from blue agave in Jalisco's Los Altos highlands. Master distiller Marco Cedano is closely associated with its production.",
    story: "Cedano worked with a new team to create a tequila that kept cooked agave clear in the finished spirit. The name refers to the heavy rainstorms that can roll across Jalisco's highlands.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave and citrus give the unaged tequila a bright start." }, { title: "Reposado", description: "Resting in oak adds soft vanilla and spice." }],
    howToEnjoy: [{ subheading: "Pour", description: "Try Blanco neat before using it in a Margarita." }, { subheading: "Food", description: "Pair with fish tacos or tandoori prawns." }],
    pairingIdeas: [{ title: "Highland tequila table", items: ["fish tacos", "tandoori prawns", "grilled corn", "salted peanuts"] }],
    whyChoose: "A Los Altos tequila whose cooked-agave character stays in focus.",
    faqs: [{ question: "Where is Tromba tequila made?", answer: "It is made in the Los Altos region of Jalisco, Mexico." }, { question: "Who is Tromba's master distiller?", answer: "Marco Cedano is the master distiller associated with Tromba." }],
    finalVerdict: "Tromba Blanco makes a crisp first pour and a lively Margarita.",
    metaTitle: "Tequila Tromba Guide | BevOry", metaDescription: "Explore Tromba tequila from Los Altos, Blanco and Reposado serves. Check city prices on BevOry.",
  },
};
