import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_47 = [
  ["antarctica-godet", "Antarctica Godet", "France", "Cognac", "31df342311853acd7a11a170"],
  ["caribba", "Caribba", "India", "Rum", "5d7e6ec1ed9f6fda007b226d"],
  ["celia", "Celia", "India", "Whisky", "b709ebbce1b402e2bbd711ed"],
  ["davana", "Davana", "India", "Vermouth", "a2360819243509c9d3b02c2d"],
  ["ginsberg", "Ginsberg", "India", "Beer", "862288041b76ecadd2cca7f3"],
  ["indian-standard-time", "Indian Standard Time", "India", "Hard Seltzer", "3e161fc7e6593751e2323d6a"],
  ["ayakiku", "Ayakiku", "Japan", "Sake", "9cff12f279d7fd94a02ccefe"],
  ["herdadepaco", "Herdadepaco", "Portugal", "Wine", "374144d918e218430db95e84"],
  ["one-tree-hill", "One Tree Hill", "India", "Wine", "054314edfe8f08f5d50d6094"],
  ["strelley-farm", "Strelley Farm", "Australia", "Wine", "f97c22044d68ad0631e98e4f"],
  ["terry-sent-me", "Terry Sent Me!", "India", "Gin", "7529a2bef713fbe5ae67a205"],
  ["marionette", "Marionette", "Spain", "Wine", "bb7b8e39808fbc0ba87d0e95"],
  ["tavo", "Tavo", "Italy", "Wine", "cd14d5273f185317a580869b"],
  ["la-pevera", "La Pevera", "Italy", "Wine", "82536ad09150c001ed2af1b5"],
  ["rawsons", "Rawsons", "Australia", "Wine", "ba547dd6307ebe8d7fac7b6e"],
  ["bodega-juan", "Bodega Juan", "Spain", "Wine", "d758890bd723cf53509ea46b"],
  ["vinologist", "Vinologist", "South Africa", "Wine", "bb12b4b2aad863d4c7c186ed"],
  ["havana", "Havana", "Cuba", "Rum", "4811d0a5bec0aad60ef8ef6d"],
  ["antonov", "Antonov", "Philippines", "Vodka", "e97dc1d062239ee2134d0d95"],
  ["feni-freezer", "Feni Freezer", "India", "Feni", "858274c4fbcd0f7eb16e2f6e"],
  ["goru", "Goru", "Spain", "Wine", "cffefbbf33995609835b3380"],
  ["shotoku", "Shotoku", "Japan", "Sake", "b3afd3d63c8258898cbf3ad8"],
  ["raya", "Raya", "India", "Hard Seltzer", "4d08ae5378638d7eca766c5a"],
  ["chemin", "Chemin", "France", "Wine", "554b653c59e510dc9b9f1672"],
  ["everyday-friday", "Everyday Friday", "India", "Ready-to-drink", "4e2769559d733338ed4b43f5"],
  ["o-be", "O'Be", "India", "Ready-to-drink", "70f3f6db41ba2eefa6f98173"],
  ["mr-jerry", "Mr Jerry", "India", "Ready-to-drink", "bdb6bcf38aaf4f1ab9bfd838"],
  ["schweppes", "Schweppes", "United Kingdom", "Ready-to-drink", "2853cd698251bc68dc6954b2"],
  ["rosita", "Rosita", "India", "Ready-to-drink", "7ebae16ec321ebbc0bbe34ce"],
  ["la-piuma", "La Piuma", "Italy", "Wine", "d0b5e90ac785ea694132152f"],
] as const;

// Evidence belongs to the editorial audit, never to the public guide.
export const BRAND_SOURCES_BATCH_47: Record<string, string[]> = {
  "antarctica-godet": ["https://cognacgodet.com/fr/", "https://novabev.com/en/brands/cognac/godet/"],
  caribba: ["https://oceanking.pl/", "https://www.livcheers.com/goa/liquor/caribba-blanco-white-rum-750ml"],
  celia: ["https://oceanking.pl/"],
  davana: ["https://www.livcheers.com/goa/liquor/davana-vermouth-indica-bianco-750ml", "https://maharajadrinks.com/collections/davana-vermouth"],
  ginsberg: ["https://www.brewer-world.com/ginsberg-strong-organic-beer/"],
  "indian-standard-time": ["https://www.drinkist.in/", "https://www.outlookindia.com/travel/indian-standard-time%3A-a-new-age-drinking-experience-209008"],
  ayakiku: ["https://www.ayakiku.com/", "https://www.iidagroup.co.jp/en/business/company05.html"],
  herdadepaco: ["https://pacodoconde.com/en", "https://pacodoconde.com/en/vinhos/"],
  "one-tree-hill": ["https://www.groverzampa.in/one-tree-hill"],
  "strelley-farm": ["https://strelleyfarm.wine/", "https://www.winerepublic.com.au/products/strelley-farm-chardonnay"],
  "terry-sent-me": ["https://terrysentme.com/", "https://thedailypour.com/article/terry-sent-me-gin/"],
  marionette: ["https://egobodegas.com/vino/marionette/"],
  tavo: ["https://www.i-lauri.it/portfolio/ilauri-tavo/"],
  "la-pevera": ["https://www.piccini1882.it/en/product/la-pevera/"],
  rawsons: ["https://www.wine.com/product/penfolds-rawsons-retreat-chardonnay-2001/49104"],
  "bodega-juan": ["https://store.gilfamily.es/products/item/2/juan-gil-rosado/pdf", "https://store.gilfamily.es/products/bodega/bodegas_juan_gil"],
  vinologist: ["https://thevinologist.com/", "https://www.vineyardbrands.com/content/Marketing/0092/0092-21-01-25-17-27-21-232.pdf"],
  havana: ["https://havana-club.com/en-gb/our-story/", "https://havana-club.com/en-gb/product/havana-club-3/"],
  antonov: ["https://www.ginebrasanmiguel.com/about-ginebra/", "https://www.smfb.com.ph/files/reports/Final_Prospectus_dated_February_20%2C_2020_-_updated.pdf"],
  "feni-freezer": ["https://www.cazcars.com/PRODUCTS.html", "https://www.goaipb.goa.gov.in/wp-content/uploads/2025/02/ODOP-Feni-List-of-Brands.pdf"],
  goru: ["https://egobodegas.com/vino/goru-gold/", "https://www.bodeboca.com/es/es/bodegas/ego-bodegas"],
  shotoku: ["https://www.shoutoku.co.jp/en/sake.html"],
  raya: ["https://indulgeindia.com/hard-seltzer-new-kid-on-the-block/", "https://in.linkedin.com/company/bomdiego-beverages-pvt-ltd"],
  chemin: ["https://iucbrands.com/component/jshopping/chemin-des-papes.html"],
  "everyday-friday": ["https://everydayfriday.co/", "https://in.linkedin.com/company/coast-town-labs"],
  "o-be": ["https://www.ifttrade.com/news/O%E2%80%99Be-cocktails-launches-RTD-O%E2%80%99Besauve-gin-and-tonic-cocktail"],
  "mr-jerry": ["https://lbb.in/kolkata/mr-jerrys-ready-to-serve-cocktails/", "https://winepalacegoa.com/mr-jerrys-mai-tai/"],
  schweppes: ["https://www.livcheers.com/goa/liquor/schweppes-mojito-rtd-275ml"],
  rosita: ["https://www.livcheers.com/goa/liquor/rosita-kokum-lime-cocktail-275ml"],
  "la-piuma": ["https://sourcing.hktdc.com/en/Product-Detail/Chianti-DOCG-1X15E74B", "https://www.mitra.nl/product/la-piuma-orvieto-classico-doc-umbrie-75cl"],
};

// Only an exact first-party mark is proposed for a previously blank row.
export const BRAND_LOGOS_BATCH_47: Record<string, string> = {
  ayakiku: "https://img21.shop-pro.jp/PA01487/646/etc/logo.png",
  "strelley-farm": "https://strelleyfarm.wine/cdn/shop/files/strelley_farm_logo_BLACK_f1ee5c9f-1a3c-4ce2-9466-5f60d0072449_300x300.png?v=1641795773",
  "terry-sent-me": "https://terrysentme.com/app-contents/images/logo.svg",
};

type Draft = {
  description: string; story: string; notes: [string, string, string, string];
  serve: string; food: string; pairings: string[]; whyChoose: string;
  faq: [string, string, string, string]; finalVerdict: string; metaDescription: string;
};
const guide = (name: string, category: string, d: Draft): BrandPublicContent => ({
  description: d.description, story: d.story,
  tastingNotes: [{ title: d.notes[0], description: d.notes[1] }, { title: d.notes[2], description: d.notes[3] }],
  howToEnjoy: [{ subheading: "Serve", description: d.serve }, { subheading: "Food", description: d.food }],
  pairingIdeas: [{ title: `With ${name}`, items: d.pairings }], whyChoose: d.whyChoose,
  faqs: [{ question: d.faq[0], answer: d.faq[1] }, { question: d.faq[2], answer: d.faq[3] }],
  finalVerdict: d.finalVerdict, metaTitle: `${name} ${category} Guide | BevOry`, metaDescription: d.metaDescription,
});

export const BRAND_CONTENT_BATCH_47: Record<string, BrandPublicContent> = {
  "antarctica-godet": guide("Antarctica Godet", "Cognac", {
    description: "Antarctica is a clear grape spirit from the Godet cognac house of La Rochelle, France. It was created for a chilled serve rather than the usual amber-cognac ritual.",
    story: "The Godet family traces its trade in Cognac back to the late sixteenth century. The family's coastal home at La Rochelle still informs a range that includes both traditional aged Cognac and this unusually transparent expression.",
    notes: ["Nose", "Fresh floral and grape notes lead the aroma.", "Palate", "A light honeyed sweetness meets a clean, cool finish."],
    serve: "Chill the bottle and pour a small measure into a cold tulip glass.",
    food: "Set it beside salted almonds, tandoori prawns or a citrus tart.",
    pairings: ["salted almonds", "tandoori prawns", "citrus tart"],
    whyChoose: "A clear, chilled take on the Godet family's Cognac tradition.",
    faq: ["Who makes Antarctica?", "The Godet family house in La Rochelle makes Antarctica.", "How is Antarctica served?", "Its clear style is particularly suited to a chilled, neat pour."],
    finalVerdict: "Antarctica turns the Cognac conversation toward a crisp, cold aperitif.",
    metaDescription: "Meet Godet Antarctica, the clear French grape spirit for a chilled pour. Explore pairings and city prices on BevOry.",
  }),
  caribba: guide("Caribba", "Rum", {
    description: "Caribba is a rum label in Ocean King Distillers' Goa portfolio, with Blanco and Negro bottlings. The white rum includes coconut extract, giving the range a distinct tropical direction.",
    story: "Ocean King Distillers develops its spirits in Goa, where rum has a long place in the local bar scene. Caribba's two colour-coded expressions give bartenders a white-rum option and a darker counterpart.",
    notes: ["Blanco", "Coconut is a defining note of the white rum.", "Style", "The Blanco's lighter colour suits bright, citrus-led mixed drinks."],
    serve: "Build a tall drink with Blanco, ice, lime and soda.",
    food: "The coconut note works with Goan prawn curry, chilli paneer and grilled pineapple.",
    pairings: ["Goan prawn curry", "chilli paneer", "grilled pineapple"],
    whyChoose: "A Goa rum range with a coconut-led white expression.",
    faq: ["Where is Caribba from?", "Caribba belongs to Ocean King Distillers' Goa spirits portfolio.", "Does Caribba have a white rum?", "Yes. Its Blanco is a white rum made with coconut extract."],
    finalVerdict: "Caribba Blanco earns its place in a lime-forward rum highball.",
    metaDescription: "Explore Caribba's Goa rum range, coconut-led Blanco, mixing ideas and city prices on BevOry.",
  }),
  celia: guide("Celia", "Whisky", {
    description: "Celia is a single malt whisky in Ocean King Distillers' Goa portfolio. The range includes an original single malt and a separate peated bottling.",
    story: "Ocean King Distillers' work in Goa extends beyond rum into Indian single malt. Celia keeps its classic and peated styles distinct, making the choice between gentle malt character and smoke straightforward.",
    notes: ["Original", "Honey, vanilla and almond feature in the original malt's profile.", "Peated expression", "The peated release offers a smokier direction than the original."],
    serve: "Try the original neat in a small tulip glass; add a few drops of water if preferred.",
    food: "Pair the original with roasted cashews or paneer tikka, and the peated style with tandoori mushrooms.",
    pairings: ["roasted cashews", "paneer tikka", "tandoori mushrooms"],
    whyChoose: "A Goa single malt range offering both unpeated and peated choices.",
    faq: ["Is Celia an Indian single malt?", "Yes. Celia is part of Ocean King Distillers' Goa portfolio.", "Does every Celia whisky taste smoky?", "No. The peated bottling is separate from the original malt."],
    finalVerdict: "Celia gives Indian single malt drinkers a clear choice between honeyed malt and peat.",
    metaDescription: "Discover Celia single malt from Goa, its original and peated styles, food pairings and city prices on BevOry.",
  }),
  davana: guide("Davana", "Vermouth", {
    description: "Davana is an Indian vermouth built around Nashik Chenin Blanc and a botanical recipe that includes Indian wormwood. Its Indica Bianco is a white vermouth intended for aperitifs and cocktails.",
    story: "Created by Adarsh Gadvi, Davana places an Indian wine base inside the European vermouth tradition. Its name comes from davana, an aromatic herb used in Indian perfumery and drinks.",
    notes: ["Aromatics", "Wormwood brings the gently bitter herbal edge expected of vermouth.", "Wine base", "Chenin Blanc gives the Bianco a bright, fruit-led foundation."],
    serve: "Pour chilled over ice with a slice of orange, or use in a light vermouth spritz.",
    food: "Try it with masala peanuts, paneer tikka or olive-studded focaccia.",
    pairings: ["masala peanuts", "paneer tikka", "olive focaccia"],
    whyChoose: "A Nashik wine-based aperitif shaped by Indian botanicals.",
    faq: ["What wine is used for Davana?", "Davana Indica Bianco uses Chenin Blanc from Nashik.", "Is Davana a wine or a spirit?", "It is vermouth: aromatised, fortified wine."],
    finalVerdict: "Davana gives the classic pre-dinner vermouth pour a distinctly Indian accent.",
    metaDescription: "Explore Davana Indica Bianco, a Nashik Chenin Blanc vermouth with Indian botanicals, pairings and city prices on BevOry.",
  }),
  ginsberg: guide("Ginsberg", "Beer", {
    description: "Ginsberg is an Indian beer from Amara Breweries in Punjab. Its range includes strong beer expressions such as Ginsberg Classic and Gold.",
    story: "Amara Breweries established production near Patiala, drawing on Punjab's brewing market. Ginsberg's focus is the full-bodied strong lager style familiar to Indian beer drinkers.",
    notes: ["Malt", "The strong lager style puts grain and malt ahead of sharp fruit flavours.", "Finish", "A firm, brisk finish keeps the beer suited to spicy snacks."],
    serve: "Serve cold in a clean lager glass rather than over ice.",
    food: "Bring out chicken tikka, masala fries or fried peanuts.",
    pairings: ["chicken tikka", "masala fries", "fried peanuts"],
    whyChoose: "A Punjab-made strong beer with a malt-forward profile.",
    faq: ["Where is Ginsberg brewed?", "Amara Breweries makes Ginsberg in Punjab.", "Is Ginsberg a strong beer?", "The range includes strong beer expressions, including Classic and Gold."],
    finalVerdict: "Ginsberg is built for the cold lager and hot tandoor combination.",
    metaDescription: "Read about Punjab's Ginsberg beer, its strong lager style, tandoori pairings and city prices on BevOry.",
  }),
  "indian-standard-time": guide("Indian Standard Time", "Hard Seltzer", {
    description: "Indian Standard Time, or IST, is a Goa-born hard seltzer brand founded by Krupa and Kunal Shah. Its sparkling drinks include Spiked Lemonade and Spiked Grapefruit.",
    story: "IST emerged as a locally made alternative to imported canned seltzers. The brand builds its drinks around a sparkling-water base, grain spirit and flavours pitched at India's long, warm afternoons.",
    notes: ["Spiked Lemonade", "Lemon and lime bring a tart, lively citrus profile.", "Spiked Grapefruit", "Pink grapefruit is joined by red-berry and pomegranate notes."],
    serve: "Chill the can thoroughly and pour over ice into a tall glass.",
    food: "Try Lemonade with tandoori fish or chilli corn; Grapefruit suits grilled prawns.",
    pairings: ["tandoori fish", "chilli corn", "grilled prawns"],
    whyChoose: "A sparkling Goa-made option with recognizable citrus-led flavours.",
    faq: ["What is IST?", "Indian Standard Time is a Goa-born brand of alcoholic hard seltzers.", "Which IST flavours are listed?", "The range includes Spiked Lemonade and Spiked Grapefruit."],
    finalVerdict: "IST makes a light, fizzy companion to sharp and spicy snacks.",
    metaDescription: "Meet IST hard seltzer from Goa. Compare Lemonade and Grapefruit flavours, food pairings and city prices on BevOry.",
  }),
  ayakiku: guide("Ayakiku", "Sake", {
    description: "Ayakiku is a sake brewery in Kagawa Prefecture on Japan's Shikoku island. Its range includes Junmai Ginjo, a rice-based style prized for aromatic lift.",
    story: "The Ayakiku brewery traces its beginnings to 1790 in the old Sanuki region. Local rice and water anchor its approach to sake making in Kagawa.",
    notes: ["Junmai", "Rice gives the sake a rounded, gently savoury centre.", "Ginjo", "The ginjo style brings a more lifted, delicate aroma than rustic table sake."],
    serve: "Serve cool in a small wine glass to make room for the aroma.",
    food: "Pair with grilled prawns, steamed fish or lightly spiced paneer.",
    pairings: ["grilled prawns", "steamed fish", "lightly spiced paneer"],
    whyChoose: "A Kagawa brewery with more than two centuries of sake history.",
    faq: ["Where is Ayakiku made?", "Ayakiku is brewed in Kagawa Prefecture, Japan.", "What does Junmai Ginjo mean?", "It names a sake style made from rice, water, koji and yeast with a ginjo-grade rice-polishing standard."],
    finalVerdict: "Ayakiku's Junmai Ginjo brings Sanuki brewing to a delicate, food-friendly pour.",
    metaDescription: "Discover Ayakiku sake from Kagawa, Junmai Ginjo serving ideas, food pairings and city prices on BevOry.",
  }),
  herdadepaco: guide("Herdadepaco", "Wine", {
    description: "Herdade Paco do Conde is a Portuguese wine estate in Baixo Alentejo, near the Guadiana River. The Castelo Branco family grows local and international grapes for its red and white wines.",
    story: "The family's Alentejo estate dates to 1918, with a modern cellar built in 2002. Warm days and the river valley shape the estate's fruit, while night harvesting helps retain freshness.",
    notes: ["Reds", "Aragonez and Touriga Nacional appear alongside grapes such as Alicante Bouschet and Syrah.", "Whites", "Antao Vaz, Arinto and Verdelho contribute freshness and fruit to the white-wine range."],
    serve: "Pour whites chilled; give fuller reds some air in a wide glass.",
    food: "Try the white with tandoori fish and the red with lamb kebabs or mushroom pulao.",
    pairings: ["tandoori fish", "lamb kebabs", "mushroom pulao"],
    whyChoose: "An Alentejo estate that shows both regional grapes and the range of its river-valley vineyard.",
    faq: ["Where is Paco do Conde?", "The estate is in Baixo Alentejo, Portugal, near the Guadiana River.", "Does the estate make white wine?", "Yes. Its portfolio includes both red and white Alentejo wines."],
    finalVerdict: "Paco do Conde is a useful introduction to the breadth of Alentejo wine.",
    metaDescription: "Explore Herdade Paco do Conde wines from Portugal's Alentejo, grape varieties, pairings and city prices on BevOry.",
  }),
  "one-tree-hill": guide("One Tree Hill", "Wine", {
    description: "One Tree Hill is a Grover Zampa wine range from Maharashtra's Sahyadri Valley. Its bottles include a white blend and a spice-infused Kadha wine.",
    story: "The name points to a solitary mango tree on the Sanjegaon vineyard. Grover Zampa uses the label to move between a fresh white blend and a Shiraz-based mulled-style wine with Indian spices.",
    notes: ["White blend", "Sauvignon Blanc, Chenin Blanc and Viognier contribute citrus, guava and tropical-fruit notes.", "Kadha wine", "Shiraz meets warming spices including star anise, cumin and black pepper."],
    serve: "Chill the white; gently warm the Kadha wine without boiling it.",
    food: "Serve the white with grilled fish or paneer tikka, and Kadha with spiced mutton kebabs.",
    pairings: ["grilled fish", "paneer tikka", "mutton kebabs"],
    whyChoose: "A Sahyadri Valley range that moves from crisp white wine to a distinctively spiced Kadha pour.",
    faq: ["Who makes One Tree Hill?", "Grover Zampa makes the range in Maharashtra's Sahyadri Valley.", "Can One Tree Hill Kadha be served warm?", "Yes. It is designed as a gently warmed, spiced wine serve."],
    finalVerdict: "One Tree Hill gives familiar Indian food two very different wine companions.",
    metaDescription: "Explore Grover Zampa's One Tree Hill white and Kadha wines, serving ideas, pairings and city prices on BevOry.",
  }),
  "strelley-farm": guide("Strelley Farm", "Wine", {
    description: "Strelley Farm is a Tasmanian wine estate with Chardonnay among its bottlings. Its wines draw on fruit from several of the island's cool-climate growing regions.",
    story: "Winemaker Liam McElhinney works with vineyards across Tasmania to show the differences between its subregions. The estate's Chardonnay is made with texture as well as freshness in mind.",
    notes: ["Fruit", "Stone fruit and citrus form the core of the Chardonnay.", "Texture", "Subtle almond and spice notes sit behind the fresh fruit."],
    serve: "Pour lightly chilled in a medium white-wine glass, not straight from the freezer.",
    food: "Try it with tandoori fish, butter-garlic prawns or roast chicken.",
    pairings: ["tandoori fish", "butter-garlic prawns", "roast chicken"],
    whyChoose: "A Tasmanian Chardonnay with both cool-climate lift and a gentle nutty edge.",
    faq: ["Where is Strelley Farm?", "Strelley Farm is a Tasmanian estate that works with fruit from several island subregions.", "What grape is its listed wine?", "The listed Strelley Farm wine is Chardonnay."],
    finalVerdict: "Strelley Farm suits drinkers who like Chardonnay with freshness intact.",
    metaDescription: "Discover Strelley Farm Chardonnay from Tasmania, its cool-climate style, pairings and city prices on BevOry.",
  }),
  "terry-sent-me": guide("Terry Sent Me!", "Gin", {
    description: "Terry Sent Me! is a citrus-forward gin made in Goa. Its name borrows the password-like language of a Prohibition-era speakeasy.",
    story: "Launched in 2022 by Pilcrow Spirits, the brand takes its identity from the hidden-bar culture of the 1930s. Founder Tarang Doshi shaped it as a mixing gin for contemporary Indian cocktail bars.",
    notes: ["Citrus", "Bright citrus leads the gin's aroma and mixing character.", "Structure", "Juniper keeps the spirit recognisably gin beneath the fruit."],
    serve: "Use a generous wedge of lime in a cold gin and tonic, or shake into a crisp Martini.",
    food: "The citrus works with Goan calamari, tandoori prawns or lemony hummus.",
    pairings: ["Goan calamari", "tandoori prawns", "lemony hummus"],
    whyChoose: "A Goa gin with a clear citrus-led cocktail brief.",
    faq: ["Where is Terry Sent Me! made?", "It is a Goa-made gin.", "What kind of gin drink suits it?", "Its citrus profile works particularly well in a gin and tonic."],
    finalVerdict: "This citrus-led Goa gin feels most at home at the start of an evening, with tonic and lime.",
    metaDescription: "Meet Goa's Terry Sent Me! gin, its citrus-led style, cocktail serves, pairings and city prices on BevOry.",
  }),
  marionette: guide("Marionette", "Wine", {
    description: "Marionette is a red wine from Ego Bodegas in Jumilla, southeastern Spain. Monastrell and Syrah are blended for a ripe, approachable Mediterranean style.",
    story: "Ego Bodegas works in the dry, sunlit landscape of Murcia's Jumilla region. For Marionette, the two grape varieties ferment separately in stainless steel before they are brought together.",
    notes: ["Fruit", "Ripe red fruit sits beside floral notes.", "Mouthfeel", "Round tannins make the Monastrell-Syrah blend easy to drink with food."],
    serve: "Pour slightly cool in a medium red-wine glass.",
    food: "Try it with mutton seekh kebabs, roasted aubergine or tomato-rich pasta.",
    pairings: ["mutton seekh kebabs", "roasted aubergine", "tomato pasta"],
    whyChoose: "A direct introduction to Jumilla's Monastrell through a softer Syrah blend.",
    faq: ["Who makes Marionette wine?", "Ego Bodegas makes Marionette in Jumilla, Spain.", "Which grapes are used?", "Marionette blends Monastrell with Syrah."],
    finalVerdict: "Marionette brings sunny Jumilla fruit to an uncomplicated dinner red.",
    metaDescription: "Explore Marionette Monastrell-Syrah from Spain's Jumilla region, tasting notes, pairings and city prices on BevOry.",
  }),
  tavo: guide("Tavo", "Wine", {
    description: "Tavo is a Pinot Grigio delle Venezie made by the iLauri wine team in northeastern Italy. It is a fresh white wine with fruit and floral notes.",
    story: "The wine takes its name from the Tavo River in Abruzzo, the region associated with the producer's wider project. This Pinot Grigio comes from the delle Venezie area and spends time in stainless steel to preserve its bright style.",
    notes: ["Nose", "Orange blossom and ripe melon lift the aroma.", "Palate", "Citrus and a little mango lead into a fresh finish."],
    serve: "Chill and pour into a narrow white-wine glass.",
    food: "Its freshness suits tandoori fish, cucumber raita or grilled prawns.",
    pairings: ["tandoori fish", "cucumber raita", "grilled prawns"],
    whyChoose: "An aromatic, stainless-steel-raised Pinot Grigio for light food.",
    faq: ["What grape is Tavo?", "Tavo is made from Pinot Grigio.", "Where does Tavo Pinot Grigio come from?", "Its denomination is delle Venezie in northeastern Italy."],
    finalVerdict: "Tavo offers bright fruit without losing the briskness expected of Pinot Grigio.",
    metaDescription: "Discover Tavo Pinot Grigio delle Venezie, its citrus-floral style, food pairings and city prices on BevOry.",
  }),
  "la-pevera": guide("La Pevera", "Wine", {
    description: "La Pevera is a Toscana IGT red from the Geografico wine project within Piccini 1882. Its blend brings Sangiovese together with Cabernet Sauvignon and Syrah.",
    story: "Geografico began as a Tuscan growers' cooperative and later joined the Piccini family portfolio. The wine's name refers to the pevera, a traditional funnel used when moving wine into barrels.",
    notes: ["Dark fruit", "Blackberry and ripe fig mark its fruit profile.", "Oak", "Vanilla and chocolate notes add a soft edge to the Tuscan blend."],
    serve: "Pour at cool room temperature and let the glass open for a few minutes.",
    food: "Match it with galouti kebabs, mushroom lasagne or spiced lamb chops.",
    pairings: ["galouti kebabs", "mushroom lasagne", "spiced lamb chops"],
    whyChoose: "A Sangiovese-led Tuscan red with a darker, oak-touched side.",
    faq: ["Where is La Pevera from?", "It is a Toscana IGT red wine from Italy.", "Who produces La Pevera?", "It comes from Geografico, part of the Piccini 1882 wine portfolio."],
    finalVerdict: "La Pevera brings Tuscany's savoury red-wine character to a hearty meal.",
    metaDescription: "Explore La Pevera Toscana IGT, its Sangiovese-led blend, pairings and city prices on BevOry.",
  }),
  rawsons: guide("Rawsons", "Wine", {
    description: "Rawson's Retreat is an Australian wine label created by Penfolds. Its Chardonnay sits in an accessible, fruit-led part of the producer's portfolio.",
    story: "The Rawson's Retreat name recalls the Magill estate where Penfolds began in South Australia. It was introduced as an everyday range distinct from the house's cellar-focused wines.",
    notes: ["Chardonnay", "The grape brings a rounded fruit character to the listed white wine.", "Style", "This is a straightforward Australian white for a chilled table pour."],
    serve: "Chill lightly and pour into a white-wine glass.",
    food: "Pair with chicken malai tikka, buttered corn or grilled fish.",
    pairings: ["chicken malai tikka", "buttered corn", "grilled fish"],
    whyChoose: "A familiar Penfolds-connected label for a casual Australian Chardonnay.",
    faq: ["Who created Rawson's Retreat?", "Penfolds created the Australian wine range.", "What grape is the listed Rawson's wine?", "The listed white wine is Chardonnay."],
    finalVerdict: "Rawson's Retreat is at its best as an easy-going, food-friendly Chardonnay.",
    metaDescription: "Read about Penfolds' Rawson's Retreat Chardonnay, serving ideas, Indian pairings and city prices on BevOry.",
  }),
  "bodega-juan": guide("Bodega Juan", "Wine", {
    description: "Bodegas Juan Gil is a family wine producer in Jumilla, southeastern Spain. Its reds are closely associated with Monastrell grown in the region's dry climate.",
    story: "The Gil family's winery began in Jumilla in 1916 and remains the centre of a wider Spanish wine group. Monastrell is its best-known local grape, although the winery also makes other colours and styles.",
    notes: ["Jumilla reds", "Monastrell gives the house's red wines ripe fruit and firm structure.", "Rosado", "The producer also makes rosado, offering a lighter, chilled alternative to its reds."],
    serve: "Serve rosado chilled; pour fuller Monastrell reds slightly cool in a broad glass.",
    food: "Bring the rosado to tandoori prawns and the red to lamb seekh or grilled aubergine.",
    pairings: ["tandoori prawns", "lamb seekh", "grilled aubergine"],
    whyChoose: "A Jumilla family winery with Monastrell at the heart of its identity.",
    faq: ["Where is Bodegas Juan Gil?", "The family winery is in Jumilla, Murcia, Spain.", "Which grape is Juan Gil known for?", "Monastrell is the grape most closely linked to its Jumilla reds."],
    finalVerdict: "Juan Gil opens a useful route into the sun-grown wines of Jumilla.",
    metaDescription: "Explore Bodegas Juan Gil from Jumilla, Monastrell wines, rosado serves, pairings and city prices on BevOry.",
  }),
  vinologist: guide("Vinologist", "Wine", {
    description: "Vinologist is a South African wine project associated with Marc Kent. Its range draws on different Cape growing areas rather than a single estate vineyard.",
    story: "Kent built the label around matching grape variety to place. Bottlings include Stellenbosch Cabernet Sauvignon, Swartland Chenin Blanc and a Cape Town Sauvignon Blanc.",
    notes: ["Chenin Blanc", "The Swartland white puts Chenin's fruit and acidity in the foreground.", "Cabernet Sauvignon", "The Stellenbosch red offers darker fruit and a firmer frame."],
    serve: "Chill the whites and pour the Cabernet slightly below room temperature.",
    food: "Try Chenin with tandoori fish and Cabernet with spiced mutton chops.",
    pairings: ["tandoori fish", "spiced mutton chops", "roast mushrooms"],
    whyChoose: "A Cape range that makes the link between grape and region easy to explore.",
    faq: ["Where is Vinologist from?", "It is a South African wine project drawing from several Cape regions.", "Does Vinologist only make red wine?", "No. Its range includes Chenin Blanc and Sauvignon Blanc as well as Cabernet Sauvignon."],
    finalVerdict: "Vinologist invites a side-by-side taste of South African grapes and places.",
    metaDescription: "Discover Vinologist wines from Stellenbosch, Swartland and Cape Town, pairings and city prices on BevOry.",
  }),
  havana: guide("Havana", "Rum", {
    description: "Havana Club is a Cuban rum made from local sugarcane molasses. Its range runs from lighter cocktail rums to longer-aged sipping expressions.",
    story: "The brand's Maestros del Ron Cubano carry a tradition of distilling, blending and ageing rum on the island. Don Jose Navarro helped define its aged-rum style; the present distillery is in San Jose, Cuba.",
    notes: ["Light rum", "The lighter style brings fresh cane and citrus notes to mixed drinks.", "Aged rum", "Longer contact with oak moves the range toward vanilla and deeper fruit."],
    serve: "Use a light expression in a Mojito with mint and lime; pour an aged one over a large cube.",
    food: "Pair a citrus-led serve with Goan fish fry, pork vindaloo or salted plantain chips.",
    pairings: ["Goan fish fry", "pork vindaloo", "salted plantain chips"],
    whyChoose: "A Cuban rum house whose lighter and aged styles serve different drinks well.",
    faq: ["Where is Havana Club rum made?", "Its Cuban rum is produced in Cuba from sugarcane molasses.", "Which Havana Club works in a Mojito?", "A light Havana Club expression suits the mint-and-lime cocktail."],
    finalVerdict: "Havana Club is a reliable starting point for learning what Cuban rum can do in a glass.",
    metaDescription: "Explore Havana Club Cuban rum, light and aged styles, Mojito serves, food pairings and city prices on BevOry.",
  }),
  antonov: guide("Antonov", "Vodka", {
    description: "Antonov is a vodka label in the Ginebra San Miguel spirits portfolio of the Philippines. The range uses multiple distillation and charcoal filtration for a clean mixing style.",
    story: "Ginebra San Miguel is a long-established Philippine drinks company best known for gin. Antonov extends that portfolio into vodka, with a practical emphasis on cocktails and long drinks.",
    notes: ["Aroma", "The style is deliberately neutral rather than botanical or oak-led.", "Finish", "Filtration aims for a clean finish in mixed drinks."],
    serve: "Mix with chilled soda and a squeeze of calamansi or lime.",
    food: "Keep snacks punchy: chilli prawns, salted peanuts or fish fingers.",
    pairings: ["chilli prawns", "salted peanuts", "fish fingers"],
    whyChoose: "A clean Philippine vodka made for simple, citrus-led mixing.",
    faq: ["Who makes Antonov vodka?", "Antonov is part of the Ginebra San Miguel spirits portfolio.", "How can Antonov be served?", "It works in a cold vodka soda with citrus."],
    finalVerdict: "Antonov keeps the attention on the mixer, ice and citrus.",
    metaDescription: "Get to know Antonov vodka, its Philippine producer, cocktail serves, food pairings and city prices on BevOry.",
  }),
  "feni-freezer": guide("Feni Freezer", "Feni", {
    description: "Feni Freezer is a flavoured cashew-feni range from Cazcar Heritage Distillers in Goa. Lemon and cranberry expressions make the traditional Goan spirit approachable as a chilled drink.",
    story: "Cazcar's work centres on cashew feni, a spirit made from fermented cashew-apple juice. Feni Freezer takes that local base into a ready-to-serve format suited to Goa's warm evenings.",
    notes: ["Lemon", "Citrus gives one expression a bright, tart edge.", "Cranberry", "The cranberry version leans into red-fruit flavour against the feni base."],
    serve: "Chill well and pour over ice with a squeeze of lime.",
    food: "Match the citrus version with recheado fish, Goan chorizo or masala peanuts.",
    pairings: ["recheado fish", "Goan chorizo", "masala peanuts"],
    whyChoose: "A Goa-made way to meet cashew feni through familiar fruit flavours.",
    faq: ["What spirit is in Feni Freezer?", "Its base is Goan cashew feni.", "Which Feni Freezer flavours are listed?", "Lemon and cranberry expressions appear in the range."],
    finalVerdict: "Feni Freezer brings cashew feni into a simple, cold long-drink setting.",
    metaDescription: "Explore Goa's Feni Freezer, lemon and cranberry cashew-feni drinks, food pairings and city prices on BevOry.",
  }),
  goru: guide("Goru", "Wine", {
    description: "Goru is a wine range from Ego Bodegas in Jumilla, Spain. The listed El Blanco offers a white-wine counterpoint to the producer's red Goru labels.",
    story: "Ego Bodegas works in the dry, sunny landscape of Murcia, where Jumilla is closely linked with Monastrell. Goru uses a graphic bull identity across wines that include both red and white expressions.",
    notes: ["El Blanco", "The white expression is aromatic and fruit-led.", "Range", "Goru's reds draw on Jumilla's warmer, fuller wine style."],
    serve: "Chill El Blanco and pour into a white-wine glass.",
    food: "Try the white with grilled prawns, paneer tikka or lemon chicken.",
    pairings: ["grilled prawns", "paneer tikka", "lemon chicken"],
    whyChoose: "A Jumilla producer's white wine within a range better known for reds.",
    faq: ["Who makes Goru wine?", "Ego Bodegas makes Goru in Spain's Jumilla region.", "Is Goru only red wine?", "No. The range also includes El Blanco."],
    finalVerdict: "Goru El Blanco offers a fresh path into Ego Bodegas' Jumilla range.",
    metaDescription: "Explore Goru wines from Jumilla, including El Blanco, serving ideas, pairings and city prices on BevOry.",
  }),
  shotoku: guide("Shotoku", "Sake", {
    description: "Shotoku is a sake label from Shoutoku Shuzo in Kyoto, Japan. Its range includes a cloudy Junmai Nigorizake made from rice, koji, water and yeast.",
    story: "Shoutoku Shuzo brews in Kyoto, a city whose food culture values delicate seasoning and careful rice preparation. Nigorizake retains fine rice particles after brewing, giving the drink its cloudy appearance.",
    notes: ["Appearance", "The Nigorizake is cloudy rather than clear.", "Texture", "Suspended rice gives the sake a fuller mouthfeel than a filtered pour."],
    serve: "Turn the bottle gently before pouring cool into a small glass.",
    food: "Try it with yakitori, tempura prawns or mildly spiced paneer.",
    pairings: ["yakitori", "tempura prawns", "mildly spiced paneer"],
    whyChoose: "A Kyoto brewery's cloudy sake for drinkers curious about rice-led texture.",
    faq: ["What is Shotoku Nigorizake?", "It is a cloudy Junmai sake from Shoutoku Shuzo in Kyoto.", "Why does Nigorizake look cloudy?", "Fine rice particles remain in the drink after brewing."],
    finalVerdict: "Shotoku Nigorizake puts texture at the centre of the sake glass.",
    metaDescription: "Discover Shotoku's cloudy Kyoto Nigorizake, serving tips, Japanese and Indian pairings and city prices on BevOry.",
  }),
  raya: guide("Raya", "Hard Seltzer", {
    description: "Raya is a Goa-made hard seltzer from Bomdiego Beverages. Its Pomegranate Mint expression brings fruit and herbs to a sparkling alcoholic drink.",
    story: "The brand came out of the newer Indian hard-seltzer movement, using Goa's casual drinking culture as a starting point. Raya focuses on light, fizzy serves rather than a conventional bottled spirit.",
    notes: ["Pomegranate", "Red-fruit flavour sets the direction of the listed seltzer.", "Mint", "Mint adds a cooling herbal edge to the bubbles."],
    serve: "Pour cold over ice into a tall glass; garnish with fresh mint if available.",
    food: "The sparkling fruit works with chilli corn, tandoori mushrooms and sev puri.",
    pairings: ["chilli corn", "tandoori mushrooms", "sev puri"],
    whyChoose: "A sparkling Goa serve that combines pomegranate with mint.",
    faq: ["What is Raya?", "Raya is a hard-seltzer brand from Bomdiego Beverages in Goa.", "Which Raya flavour is listed?", "Pomegranate Mint is among its listed seltzers."],
    finalVerdict: "Raya is a crisp, fruit-and-herb option for a long, cold pour.",
    metaDescription: "Meet Goa's Raya Pomegranate Mint hard seltzer, food pairings, serving ideas and city prices on BevOry.",
  }),
  chemin: guide("Chemin", "Wine", {
    description: "Chemin des Papes is a French wine label from Les Grands Chais de France. Its Rhone range includes a Chateauneuf-du-Pape red.",
    story: "The name recalls the papal history of the southern Rhone, where Chateauneuf-du-Pape takes its name from the popes' Avignon period. The label presents wines from this warm, Grenache-friendly part of France.",
    notes: ["Red fruit", "Southern Rhone reds often put ripe berry fruit at the front of the glass.", "Spice", "The region's warm-climate reds can carry a savoury, peppery edge."],
    serve: "Give the Chateauneuf-du-Pape a little air and pour slightly cool into a broad red-wine glass.",
    food: "Serve beside mutton rogan josh, grilled lamb or aubergine parmigiana.",
    pairings: ["mutton rogan josh", "grilled lamb", "aubergine parmigiana"],
    whyChoose: "An accessible label for exploring the southern Rhone's papal wine region.",
    faq: ["Who makes Chemin des Papes?", "It is a wine label from Les Grands Chais de France.", "What is Chateauneuf-du-Pape?", "It is a protected wine appellation in the southern Rhone Valley of France."],
    finalVerdict: "Chemin des Papes brings a classic southern Rhone red to the dinner table.",
    metaDescription: "Explore Chemin des Papes from the Rhone, its Chateauneuf-du-Pape red, food pairings and city prices on BevOry.",
  }),
  "everyday-friday": guide("Everyday Friday", "Ready-to-drink", {
    description: "Everyday Friday is an Indian ready-to-drink cocktail label associated with Coast Town Labs. Its canned vodka-soda range includes Cranberry & Lime and Peach Lemonade flavours.",
    story: "The brand draws on Goa's informal bar-and-beach scene, packaging familiar mixed-drink combinations for a chilled serve. It has also worked with Samsara gin on a separate pink-gin drink.",
    notes: ["Cranberry & Lime", "Tart berry and lime make a bright, sharp combination.", "Peach Lemonade", "Peach softens the citrus edge of the lemonade-style drink."],
    serve: "Chill the can and pour into an ice-filled highball.",
    food: "Bring out peri-peri fries, chilli paneer or grilled prawns.",
    pairings: ["peri-peri fries", "chilli paneer", "grilled prawns"],
    whyChoose: "Ready-mixed fruit-and-citrus cocktails built for an easy cold pour.",
    faq: ["What does Everyday Friday make?", "It makes ready-to-drink cocktails, including vodka-soda flavours.", "Is every Everyday Friday can vodka-based?", "No. The brand has also made a separate drink with Samsara pink gin."],
    finalVerdict: "Everyday Friday is at its best with ice, a hot snack and no bar equipment.",
    metaDescription: "Explore Everyday Friday canned cocktails, Cranberry & Lime, Peach Lemonade, pairings and city prices on BevOry.",
  }),
  "o-be": guide("O'Be", "Ready-to-drink", {
    description: "O'Be is a Bengaluru-founded ready-to-drink cocktail label associated with Nitesh Prakash. The range has included gin and tonic, mojito and Long Island Iced Tea styles.",
    story: "The venture brought bar-style recipes into a packaged format during India's early wave of domestic canned cocktails. Its Sauve gin-and-tonic release placed a familiar highball beside fruitier mixed drinks.",
    notes: ["Gin and tonic", "A bitter-citrus tonic profile drives the Sauve expression.", "Mojito", "The mojito-style drink turns toward mint and lime."],
    serve: "Serve well chilled over ice in a tall glass.",
    food: "Try it with masala peanuts, chicken tikka or chilli garlic potatoes.",
    pairings: ["masala peanuts", "chicken tikka", "chilli garlic potatoes"],
    whyChoose: "A locally developed take on familiar mixed drinks in a ready-to-serve format.",
    faq: ["Where did O'Be begin?", "The cocktail venture began in Bengaluru.", "Which cocktails has O'Be made?", "Its range has included gin and tonic, mojito and Long Island Iced Tea styles."],
    finalVerdict: "O'Be speaks to the appeal of a cold cocktail without the mixing steps.",
    metaDescription: "Explore O'Be ready-to-drink cocktails, gin-and-tonic and mojito styles, pairings and city prices on BevOry.",
  }),
  "mr-jerry": guide("Mr Jerry", "Ready-to-drink", {
    description: "Mr Jerry's is a ready-to-serve cocktail range from Blue Ocean Beverages in Goa. Its bottled line has included a Mai Tai alongside other classic cocktail styles.",
    story: "Introduced in 2020, the range brought bar-style mixed drinks into a bottled Goa format. Its appeal lies in the recognisable cocktail names and a serve that needs little more than ice.",
    notes: ["Mai Tai", "The listed Mai Tai follows a fruit-forward tropical-cocktail direction.", "Format", "A premixed pour keeps the balance consistent from glass to glass."],
    serve: "Pour the Mai Tai cold over crushed ice with a lime wedge.",
    food: "Try it with Goan fish fry, chilli chicken or roasted cashews.",
    pairings: ["Goan fish fry", "chilli chicken", "roasted cashews"],
    whyChoose: "A Goa-made bottled cocktail for a quick tropical-style serve.",
    faq: ["Who makes Mr Jerry's?", "Blue Ocean Beverages in Goa is associated with the range.", "Does Mr Jerry's include a Mai Tai?", "Yes. A Mai Tai is among its listed ready-to-serve cocktails."],
    finalVerdict: "Mr Jerry's is a straightforward route to a cold cocktail and spicy coastal snacks.",
    metaDescription: "Discover Mr Jerry's Goa-made bottled cocktails, its Mai Tai, food pairings and city prices on BevOry.",
  }),
  schweppes: guide("Schweppes", "Ready-to-drink", {
    description: "Schweppes is a long-established name in sparkling mixers; the listed Goa range includes a Mojito ready-to-drink cocktail. That bottled cocktail is distinct from the brand's plain tonic water.",
    story: "Schweppes traces its carbonation heritage to Jacob Schweppe's eighteenth-century work. Its name has since appeared on tonic, soda and locally marketed mixed-drink products in different markets.",
    notes: ["Mojito", "Mint and lime set the direction of the listed premixed drink.", "Bubbles", "Carbonation gives the serve a crisp, lifted finish."],
    serve: "Serve the ready-to-drink Mojito cold over ice with fresh mint.",
    food: "Pair with tandoori prawns, chilli corn or salted potato wedges.",
    pairings: ["tandoori prawns", "chilli corn", "salted potato wedges"],
    whyChoose: "A mint-and-lime bottled cocktail under a familiar sparkling-drink name.",
    faq: ["Is Schweppes Mojito the same as tonic water?", "No. The listed Mojito is a ready-to-drink mixed beverage, not plain tonic.", "What flavours define the Mojito?", "Mint and lime are its familiar lead flavours."],
    finalVerdict: "The Mojito expression takes Schweppes' sparkling identity into a ready-poured drink.",
    metaDescription: "Explore Schweppes Mojito ready-to-drink, its mint-and-lime style, pairings and city prices on BevOry.",
  }),
  rosita: guide("Rosita", "Ready-to-drink", {
    description: "Rosita is a bottled Goa cocktail associated with Taphouse. Its listed Kokum & Lime expression pairs a local sour fruit with citrus.",
    story: "Kokum is deeply familiar in Goan kitchens and drinks, where its sharp fruit note cuts through heat and spice. Rosita carries that flavour into a ready-to-serve cocktail format.",
    notes: ["Kokum", "Tart, dark-fruit character gives the drink its Goan identity.", "Lime", "Fresh citrus sharpens the finish."],
    serve: "Pour cold over ice and add a lime wheel.",
    food: "Its acidity suits recheado prawns, fried calamari and chilli paneer.",
    pairings: ["recheado prawns", "fried calamari", "chilli paneer"],
    whyChoose: "A locally rooted kokum-and-lime cocktail with a bright, sour edge.",
    faq: ["What flavour is Rosita's listed cocktail?", "The listed expression is Kokum & Lime.", "Where does kokum fit in the drink?", "Kokum brings a tart fruit character familiar from Goan food and beverages."],
    finalVerdict: "Rosita makes kokum the centre of a simple, chilled cocktail serve.",
    metaDescription: "Meet Rosita Kokum & Lime from Goa, serving ideas, coastal-food pairings and city prices on BevOry.",
  }),
  "la-piuma": guide("La Piuma", "Wine", {
    description: "La Piuma is an Italian wine label with both a Tuscan Chianti and an Orvieto Classico from Umbria. Its range crosses the red-white divide rather than representing a single grape.",
    story: "The two denominations come from central Italy but tell different stories: Chianti is rooted in Tuscany's Sangiovese tradition, while Orvieto Classico is a historic Umbrian white-wine district. La Piuma puts both on the same label.",
    notes: ["Chianti", "Sangiovese brings red-fruit acidity and a savoury edge.", "Orvieto Classico", "The white offers a lighter, fresher profile for a chilled serve."],
    serve: "Pour Orvieto chilled; serve Chianti slightly below room temperature.",
    food: "Try the white with tandoori fish and the red with tomato pasta or lamb seekh.",
    pairings: ["tandoori fish", "tomato pasta", "lamb seekh"],
    whyChoose: "A two-region introduction to central Italian red and white wine.",
    faq: ["Is La Piuma only Chianti?", "No. The label also includes Orvieto Classico white wine.", "Where does La Piuma Orvieto come from?", "Orvieto Classico is a wine denomination in Umbria, Italy."],
    finalVerdict: "La Piuma is a useful pairing choice when dinner could call for either Italian red or white.",
    metaDescription: "Explore La Piuma Chianti and Orvieto Classico, serving styles, Indian food pairings and city prices on BevOry.",
  }),
};
