import type { BrandPublicContent } from "./brandContentBatch01.js";

export const BRAND_IDENTITIES_BATCH_21 = [
  ["barone-ricasoli", "Barone Ricasoli", "Italy", "Wine", "837ece650bf88c4a3ce190ef"],
  ["barsol", "BarSol", "Peru", "Pisco", "7156ad868b768b55f645deae"],
  ["becks", "Beck's", "Germany", "Beer", "bd685b6a84dd30be1af1eb36"],
  ["benromach", "Benromach", "Scotland", "Single Malt Scotch", "a728e5651a6741af769ec397"],
  ["beronia", "Beronia", "Spain", "Wine", "fb09c0006aa3f140dd6c4cb6"],
  ["besserat", "Besserat de Bellefon", "France", "Champagne", "ba40b76b37bc746ce566ecaa"],
  ["birra-moretti", "Birra Moretti", "Italy", "Beer", "9aa89d109e577513e3133b0c"],
  ["blue-nun", "Blue Nun", "Germany", "Wine", "4c83f9203eb8474b7aa33ed1"],
  ["boodles", "Boodles", "United Kingdom", "Gin", "6323e249a7bb7f783f9d28e4"],
  ["botanist", "The Botanist", "Scotland", "Gin", "745d32ff61e2dd2d9526776a"],
  ["brancott-estate", "Brancott Estate", "New Zealand", "Wine", "ec582b0ed5e7e0856c759a6a"],
  ["famous-grouse", "The Famous Grouse", "Scotland", "Blended Scotch", "30ca11040533ddb2f3de5307"],
  ["bull-dog", "Bulldog", "United Kingdom", "Gin", "5aa7ae42bb3078ad03a392a9"],
  ["camikara", "Camikara", "India", "Rum", "172a13ba4ea33842af756319"],
  ["canadian-club", "Canadian Club", "Canada", "Canadian Whisky", "d34458e5d811590a7ac7c92d"],
  ["caorunn", "Caorunn", "Scotland", "Gin", "677ef4f79ad4e2b81fef56b9"],
  ["cardhu", "Cardhu", "Scotland", "Single Malt Scotch", "390030415bc19ca37bf49066"],
  ["carlo-rossi", "Carlo Rossi", "United States", "Wine", "bfcba18bca7ccf10d522e496"],
  ["chambord", "Chambord", "France", "Liqueur", "95f32270ee93385de514f08f"],
  ["chimay", "Chimay", "Belgium", "Trappist Beer", "60e8388f84d0a25467f70b11"],
  ["cloudy-bay", "Cloudy Bay", "New Zealand", "Wine", "eb46ed5e6a1784db950bda63"],
  ["clynelish", "Clynelish", "Scotland", "Single Malt Scotch", "4a92a20c6282c94c9c35157f"],
  ["codigo", "Código 1530", "Mexico", "Tequila", "67524139a20cf891b53bc208"],
  ["copper-dog", "Copper Dog", "Scotland", "Blended Malt Scotch", "946b7f60e418ab416d1add77"],
  ["craigellachie", "Craigellachie", "Scotland", "Single Malt Scotch", "502712eb03cbc19add40e1b2"],
  ["crystal-head", "Crystal Head", "Canada", "Vodka", "642bdfdbf912fbacb6a903c9"],
  ["delirium", "Delirium", "Belgium", "Beer", "a945157a1f7a9f257ad17009"],
  ["dom-perignon", "Dom Pérignon", "France", "Champagne", "4ee9338e3653239e6eea528e"],
  ["donnafugata", "Donnafugata", "Italy", "Wine", "5dd350c34f87f4f1122595d4"],
  ["el-dorado", "El Dorado", "Guyana", "Rum", "7c3136173017802c225d5c72"],
] as const;

// Internal research only; never rendered as public copy.
export const BRAND_SOURCES_BATCH_21: Record<string, string[]> = {
  "barone-ricasoli": ["https://www.ricasoli.com/en/the-ricasolis-and-the-chianti-classico-wine-area/", "https://www.ricasoli.com/en/products/"],
  barsol: ["https://www.barsolpisco.com/about-us/", "https://www.barsolpisco.com/products/"],
  becks: ["https://becks.de/becks/historie?lang=en"],
  benromach: ["https://www.benromach.com/our-story"],
  beronia: ["https://www.beronia.com/en/", "https://beronia.com/en-es/node/452"],
  besserat: ["https://www.besseratdebellefon.com/maison-en.php"],
  "birra-moretti": ["https://cms.birramoretti.com/us/en/homepage", "https://acc-www2.birramoretti.com/global/en/our-history/"],
  "blue-nun": ["https://www.bluenun.wine/product/authentic-white", "https://www.bluenun.wine/download/product/BLUE-NUN_Product-Sheet_Riesling_750ml_USA.pdf"],
  boodles: ["https://boodlesgin.com/"],
  botanist: ["https://www.thebotanist.com/products/the-botanist-70cl"],
  "brancott-estate": ["https://brancottestate.com/en-us/our-wines", "https://brancottestate.com/products/reserve-sauvignon-blanc"],
  "famous-grouse": ["https://www.thefamousgrouse.com/nl-nl/the-famous-grouse"],
  "bull-dog": ["https://www.bulldoggin.com/london-dry-gin/"],
  camikara: ["https://www.piccadily.com/faq", "https://www.piccadily.com/sites/default/files/2025-06/PAIL_ANNUAL_REPORT_2023-24.pdf"],
  "canadian-club": ["https://www.canadianclub.com/en-au/our-story"],
  caorunn: ["https://www.caorunngin.com/about-us"],
  cardhu: ["https://www.thebar.com/en-gb/products/cardhu-amber-rock-single-malt-scotch-whisky-70cl"],
  "carlo-rossi": ["https://d.carlorossi.com/our-story"],
  chambord: ["https://www.chambordliqueur.com/our-magnifique-process/"],
  chimay: ["https://chimay.com/en/discover/"],
  "cloudy-bay": ["https://www.cloudybay.com/en-nz/journal/40-years-in-the-making/", "https://www.cloudybay.com/en-us/our-wines/"],
  clynelish: ["https://www.malts.com/en/clynelish/visit"],
  codigo: ["https://codigo1530.com/en-us/our-story"],
  "copper-dog": ["https://www.mhdhk.com/en/brands/copper-dog"],
  craigellachie: ["https://www.craigellachie.com/", "https://www.craigellachie.com/faq/"],
  "crystal-head": ["https://www.crystalheadvodka.com/"],
  delirium: ["https://www.delirium.be/en/history"],
  "dom-perignon": ["https://www.lvmh.com/en/our-maisons/wines-spirits/dom-perignon"],
  donnafugata: ["https://www.donnafugata.it/en/roots/"],
  "el-dorado": ["https://theeldoradorum.com/our-stills", "https://demeraradistillers.com/"],
};

// The other 27 live rows already have logos and must not be replaced.
export const BRAND_LOGOS_BATCH_21: Record<string, string> = {
  "barone-ricasoli": "https://ricasoli.com/wp-content/uploads/2018/03/IST_RICASOLI_NEW__bianco.png",
  beronia: "https://www.beronia.com/sites/default/files/styles/logo_header/public/2021-07/logotipo-beronia-blanco.png?itok=9GpuOZfr",
};

export const BRAND_CONTENT_BATCH_21: Record<string, BrandPublicContent> = {
  "barone-ricasoli": {
    description: "Barone Ricasoli makes Chianti Classico at Brolio in Tuscany, with Sangiovese at the heart of its reds. The estate's vineyards around Gaiole in Chianti sit on a patchwork of soils that the family has mapped in detail.",
    story: "The Ricasoli family has held Brolio Castle since 1141. Bettino Ricasoli's nineteenth-century blending work helped establish the Sangiovese-led identity of Chianti.",
    tastingNotes: [{ title: "Brolio reds", description: "Sangiovese brings red cherry and a lively, savoury edge." }, { title: "Estate whites", description: "The white wines move toward citrus and orchard fruit rather than the tannin of the reds." }],
    howToEnjoy: [{ subheading: "In the glass", description: "Pour Chianti Classico into a medium-sized wine glass at a cool room temperature." }, { subheading: "At dinner", description: "Try the reds with mushroom risotto, mutton ragù or paneer in tomato gravy." }],
    pairingIdeas: [{ title: "Brolio at the table", items: ["mushroom risotto", "mutton ragù", "paneer in tomato gravy", "aged pecorino"] }],
    whyChoose: "Brolio links a living Sangiovese estate to one of Chianti's most consequential families.",
    faqs: [{ question: "Where is Barone Ricasoli based?", answer: "At Brolio, near Gaiole in Chianti in Tuscany." }, { question: "Which grape leads its Chianti Classico?", answer: "Sangiovese is central to the estate's Chianti Classico wines." }],
    finalVerdict: "Choose Brolio when a savoury Tuscan red belongs alongside dinner, not just in the glass beforehand.",
    metaTitle: "Barone Ricasoli Wine Guide | BevOry",
    metaDescription: "Discover Brolio's Sangiovese-led Chianti Classico, family history and food pairings. Check city prices on BevOry.",
  },
  barsol: {
    description: "BarSol is a Peruvian pisco made at Bodega San Isidro in the Ica Valley. Its range includes Quebranta and aromatic grapes such as Italia, Torontel and Moscatel.",
    story: "Diego Loret de Mola and Carlos Ferreyros founded BarSol around the old Ica bodega. The name joins 'bar' with 'sol', the Spanish word for sun, in a nod to the valley where its grapes grow.",
    tastingNotes: [{ title: "Quebranta", description: "The non-aromatic grape gives a firmer, grapey spirit suited to a Pisco Sour." }, { title: "Italia", description: "This aromatic variety brings a more floral, fruit-led nose." }],
    howToEnjoy: [{ subheading: "Shake it", description: "Use Quebranta with lime, sugar and egg white in a Pisco Sour." }, { subheading: "With food", description: "Lime-heavy ceviche, tandoori prawns and chilli-lime peanuts suit its bright grape character." }],
    pairingIdeas: [{ title: "Fresh and sharp", items: ["fish ceviche", "tandoori prawns", "chilli-lime peanuts", "grilled corn with lime"] }],
    whyChoose: "BarSol puts Ica-grown pisco grapes, rather than neutral spirit, at the centre of the drink.",
    faqs: [{ question: "Where is BarSol pisco made?", answer: "At Bodega San Isidro in Ica, Peru." }, { question: "Is every BarSol pisco made from Quebranta?", answer: "No. The range also includes aromatic Italia, Torontel and Moscatel expressions." }],
    finalVerdict: "The Quebranta is the straightforward cocktail pick; the aromatic bottles invite a slower sip.",
    metaTitle: "BarSol Pisco Guide | BevOry",
    metaDescription: "Meet BarSol pisco from Peru's Ica Valley, from Quebranta to Italia, with serving ideas. Check city prices on BevOry.",
  },
  becks: {
    description: "Beck's is a Bremen-born German beer label built around a crisp pilsner. Its green bottle and key emblem have travelled with the beer well beyond its home city.",
    story: "Brewer Heinrich Beck joined Lüder Rutenberg and Thomas May to establish the Kaiserbrauerei in 1873. The founders made a pilsner that could withstand long export journeys from Bremen.",
    tastingNotes: [{ title: "Pale malt", description: "Light grain sweetness gives the beer its base." }, { title: "Dry close", description: "A clean hop bitterness keeps the finish brisk." }],
    howToEnjoy: [{ subheading: "Cold pour", description: "Serve the pilsner well chilled in a tall glass." }, { subheading: "With snacks", description: "It works with onion pakora, grilled sausages or salted pretzels." }],
    pairingIdeas: [{ title: "Beer snacks", items: ["onion pakora", "grilled sausages", "salted pretzels", "chilli fries"] }],
    whyChoose: "Beck's gives a spice-heavy snack table a dry, Bremen-style pilsner.",
    faqs: [{ question: "Where did Beck's beer begin?", answer: "In Bremen, Germany, where its founding brewery opened in 1873." }, { question: "What style is Beck's Original?", answer: "It is a pale pilsner beer." }],
    finalVerdict: "A cold Beck's is at its best beside salty food and a plate that needs a crisp reset.",
    metaTitle: "Beck's Pilsner Beer Guide | BevOry",
    metaDescription: "Read Beck's Bremen story, crisp pilsner notes and snack pairings. Check city prices on BevOry.",
  },
  benromach: {
    description: "Benromach is a Speyside single malt distilled in Forres by Gordon & MacPhail. Its signature range combines malt sweetness with a restrained trace of peat smoke.",
    story: "The distillery was built in 1898 and acquired by Gordon & MacPhail in 1993. After restoration it reopened in 1998, drawing on an older, lightly smoky Speyside style.",
    tastingNotes: [{ title: "Malted barley", description: "Cereal sweetness and orchard fruit sit at the centre of the house style." }, { title: "Gentle smoke", description: "Peat gives the signature malt a light smoky edge rather than an Islay-sized blast." }],
    howToEnjoy: [{ subheading: "First sip", description: "Try a small neat pour, then add a few drops of water." }, { subheading: "With dinner", description: "Smoked paneer tikka, roast mushrooms and mutton seekh suit the malt's smoky edge." }],
    pairingIdeas: [{ title: "Smoke and savour", items: ["smoked paneer tikka", "roast mushrooms", "mutton seekh", "toasted almonds"] }],
    whyChoose: "Benromach offers peat in a Speyside register: present, but never the whole conversation.",
    faqs: [{ question: "Who owns Benromach?", answer: "The family-owned Scottish company Gordon & MacPhail." }, { question: "Is Benromach a smoky whisky?", answer: "Its signature style has a delicate peat-smoke note." }],
    finalVerdict: "A useful bridge for a Speyside drinker curious about a little smoke.",
    metaTitle: "Benromach Single Malt Guide | BevOry",
    metaDescription: "Explore Benromach's Forres distillery, gentle peat smoke and food pairings. Check city prices on BevOry.",
  },
  beronia: {
    description: "Beronia makes Spanish wines in Rioja Alta and Rueda, with Tempranillo central to its Rioja reds. Its Rioja range runs from youthful fruit to oak-aged Crianza and Reserva styles.",
    story: "A group of friends founded Beronia in 1973 around wine and shared meals. González Byass joined the project in 1982, and the winery later expanded into Verdejo from Rueda.",
    tastingNotes: [{ title: "Rioja reds", description: "Tempranillo brings plum and red berry fruit; oak-aged releases add savoury spice." }, { title: "Rueda Verdejo", description: "The white side of Beronia is fresher, with citrus and herbal notes." }],
    howToEnjoy: [{ subheading: "Two temperatures", description: "Serve Verdejo chilled and pour the Rioja reds slightly below room temperature." }, { subheading: "Food first", description: "Chorizo, mushroom croquetas and paneer tikka make sensible companions for the reds." }],
    pairingIdeas: [{ title: "Across the range", items: ["chorizo", "mushroom croquetas", "paneer tikka", "grilled prawns"] }],
    whyChoose: "Beronia gives one winery's view of both Rioja Tempranillo and Rueda Verdejo.",
    faqs: [{ question: "Where is Beronia's main winery?", answer: "In Rioja Alta, Spain." }, { question: "Does Beronia make white wine?", answer: "Yes. It also makes Verdejo in Rueda." }],
    finalVerdict: "Reach for Rioja at a robust dinner; keep the Rueda white for a lighter plate.",
    metaTitle: "Beronia Rioja Wine Guide | BevOry",
    metaDescription: "Discover Beronia's Rioja reds and Rueda Verdejo, with serving and food ideas. Check city prices on BevOry.",
  },
  besserat: {
    description: "Besserat de Bellefon is a Champagne house in Épernay known for its fine, soft mousse. Its wines include the Cuvée des Moines range, built to sit comfortably with food.",
    story: "The house traces its beginnings to 1843. Its long-standing emphasis on a lighter texture made Champagne a companion to a full meal, rather than only a toast.",
    tastingNotes: [{ title: "Fine mousse", description: "The bubbles feel creamy and gentle rather than sharp." }, { title: "Fresh finish", description: "Citrus and orchard-fruit notes keep the style lively." }],
    howToEnjoy: [{ subheading: "Serve chilled", description: "Use a tulip-shaped glass so the aroma has room to open." }, { subheading: "Through the meal", description: "Try brut with tandoori fish, prawn toast or a light mushroom tart." }],
    pairingIdeas: [{ title: "Dinner pairings", items: ["tandoori fish", "prawn toast", "mushroom tart", "salted cashews"] }],
    whyChoose: "Its delicate mousse makes this a Champagne to keep on the table after the first course arrives.",
    faqs: [{ question: "Where is Besserat de Bellefon based?", answer: "In Épernay, in France's Champagne region." }, { question: "What distinguishes its style?", answer: "The house places particular emphasis on a silky, light mousse." }],
    finalVerdict: "A food-minded Champagne for people who prefer finesse to forceful fizz.",
    metaTitle: "Besserat de Bellefon Champagne Guide | BevOry",
    metaDescription: "Meet Besserat de Bellefon's fine mousse, Épernay history and dinner pairings. Check city prices on BevOry.",
  },
  "birra-moretti": {
    description: "Birra Moretti is an Italian beer brand founded in Udine, best known for its pale L'Autentica lager. Malt and hops give the beer a mild bitterness that works naturally with food.",
    story: "Luigi Moretti established a beer-and-ice business in Udine in 1859. The moustached figure on today's label, Baffo, became the brand's familiar face later in its history.",
    tastingNotes: [{ title: "Malt", description: "A light bread-like sweetness starts the sip." }, { title: "Hops", description: "Moderate bitterness leaves the finish clean." }],
    howToEnjoy: [{ subheading: "Glass first", description: "Pour L'Autentica cold into a clean lager glass." }, { subheading: "With supper", description: "Margherita pizza, chilli paneer and fried calamari are easy matches." }],
    pairingIdeas: [{ title: "Casual plates", items: ["margherita pizza", "chilli paneer", "fried calamari", "roasted peanuts"] }],
    whyChoose: "Moretti's gentle bitterness lets it stay beside dinner instead of competing with it.",
    faqs: [{ question: "Where did Birra Moretti start?", answer: "In Udine, in Italy's Friuli region." }, { question: "What is Birra Moretti L'Autentica?", answer: "The brand's classic pale lager." }],
    finalVerdict: "A straightforward Italian lager for pizza, fried snacks and relaxed meals.",
    metaTitle: "Birra Moretti Beer Guide | BevOry",
    metaDescription: "Explore Birra Moretti's Udine roots, lager style and Italian-food pairings. Check city prices on BevOry.",
  },
  "blue-nun": {
    description: "Blue Nun is a German wine label produced by Langguth Erben. Its range extends beyond its familiar white wine into Riesling, Gewürztraminer and sparkling bottlings.",
    story: "The Langguth company is based in Traben-Trarbach on the Mosel. Blue Nun travelled widely as an export wine, while its present range draws on several German growing regions.",
    tastingNotes: [{ title: "Authentic White", description: "Apple-like fruit and a light sweetness sit over refreshing acidity." }, { title: "Riesling", description: "The Rheinhessen Riesling brings a more focused aromatic lift." }],
    howToEnjoy: [{ subheading: "Cool glass", description: "Chill the white wines and use a small white-wine glass." }, { subheading: "With spice", description: "Paneer tikka, mild Thai curry and tandoori fish suit their fruit and acidity." }],
    pairingIdeas: [{ title: "Bright plates", items: ["paneer tikka", "mild Thai curry", "tandoori fish", "apple tart"] }],
    whyChoose: "Blue Nun offers approachable German whites without requiring a single fixed grape or sweetness level across the range.",
    faqs: [{ question: "Who produces Blue Nun?", answer: "The German wine company F. W. Langguth Erben." }, { question: "Is every Blue Nun bottle Riesling?", answer: "No. The range includes multiple white wines and sparkling styles." }],
    finalVerdict: "Choose by bottle style: the fruit-led whites and sparkling releases belong at different tables.",
    metaTitle: "Blue Nun German Wine Guide | BevOry",
    metaDescription: "See Blue Nun's German whites, Riesling notes and food pairings. Check city prices on BevOry.",
  },
  boodles: {
    description: "Boodles is a British London Dry gin redistilled from wheat spirit in a Carter-Head copper still. The recipe includes juniper, nutmeg, sage and rosemary, but no citrus botanicals.",
    story: "The original distillers left citrus out because they expected a slice of lemon or lime to arrive in the finished drink. That decision still gives the gin its herbal direction.",
    tastingNotes: [{ title: "Herbal core", description: "Sage and rosemary sit behind the juniper." }, { title: "Warm spice", description: "Nutmeg contributes a quiet, rounded spice note." }],
    howToEnjoy: [{ subheading: "Add the citrus", description: "Use dry tonic and a fresh lime wedge, or mix a chilled Martini." }, { subheading: "At the table", description: "Try tandoori prawns, lemon-pepper paneer or herb-roasted chicken." }],
    pairingIdeas: [{ title: "Herb and citrus", items: ["tandoori prawns", "lemon-pepper paneer", "herb-roasted chicken", "salted olives"] }],
    whyChoose: "Boodles leaves space for the garnish to supply the citrus rather than putting it in the still.",
    faqs: [{ question: "Does Boodles contain citrus botanicals?", answer: "No. Its makers intentionally omit citrus from the gin recipe." }, { question: "How is Boodles distilled?", answer: "Wheat-based spirit is redistilled in a Carter-Head copper still." }],
    finalVerdict: "A particularly good gin when fresh lime and herbal food are already in the picture.",
    metaTitle: "Boodles Gin Guide | BevOry",
    metaDescription: "Discover Boodles' citrus-free botanicals, Carter-Head still and serving ideas. Check city prices on BevOry.",
  },
  botanist: {
    description: "The Botanist is an Islay dry gin distilled at Bruichladdich in Scotland. Twenty-two hand-foraged island botanicals join nine more traditional gin ingredients in its original expression.",
    story: "Bruichladdich turned its distilling knowledge toward the plants growing on Islay. The result keeps the island in the glass through local herbs and flowers rather than peat smoke.",
    tastingNotes: [{ title: "Wild herbs", description: "A floral, herbaceous aroma opens above the juniper." }, { title: "Citrus lift", description: "Bright citrus and gentle spice keep the original dry gin lively." }],
    howToEnjoy: [{ subheading: "Simple tonic", description: "Serve with dry tonic over ice, with a modest citrus garnish." }, { subheading: "Fresh food", description: "Cucumber chaat, grilled prawns and goat-cheese toast suit the botanical profile." }],
    pairingIdeas: [{ title: "Fresh flavours", items: ["cucumber chaat", "grilled prawns", "goat-cheese toast", "lemon olives"] }],
    whyChoose: "The Botanist expresses Islay through its plants, offering an island story without whisky's smoky shorthand.",
    faqs: [{ question: "Where is The Botanist made?", answer: "At Bruichladdich Distillery on Scotland's island of Islay." }, { question: "How many Islay botanicals are used?", answer: "The original dry gin includes 22 hand-foraged local botanicals." }],
    finalVerdict: "A fragrant dry gin worth pouring simply enough to taste the island botanicals.",
    metaTitle: "The Botanist Islay Gin Guide | BevOry",
    metaDescription: "Explore The Botanist's Islay botanicals, dry-gin style and food pairings. Check city prices on BevOry.",
  },
  "brancott-estate": {
    description: "Brancott Estate is a New Zealand winery associated with Marlborough Sauvignon Blanc. Its portfolio also includes reserve and other varietal wines from the region.",
    story: "The estate helped bring Sauvignon Blanc into Marlborough's wine story. Today its winemakers draw fruit from the Wairau and Awatere valleys for different expressions of the grape.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Grapefruit, passionfruit and a green herbal edge keep the wine brisk." }, { title: "Reserve", description: "Selected Marlborough fruit gives the Reserve Sauvignon Blanc a fuller texture." }],
    howToEnjoy: [{ subheading: "Cold, not icy", description: "Serve Sauvignon Blanc chilled in a white-wine glass." }, { subheading: "With dinner", description: "Tandoori fish, goat cheese and coriander prawns make good partners for its acidity." }],
    pairingIdeas: [{ title: "Citrus-friendly food", items: ["tandoori fish", "goat-cheese salad", "coriander prawns", "lime-dressed asparagus"] }],
    whyChoose: "Brancott Estate gives Marlborough's bright Sauvignon Blanc a clear regional anchor.",
    faqs: [{ question: "Where is Brancott Estate from?", answer: "Marlborough, New Zealand." }, { question: "What wine is it especially known for?", answer: "Sauvignon Blanc, the grape most closely tied to its Marlborough reputation." }],
    finalVerdict: "Take it to the table when herbs, lime and seafood are doing the talking.",
    metaTitle: "Brancott Estate Wine Guide | BevOry",
    metaDescription: "Explore Brancott Estate's Marlborough Sauvignon Blanc and food pairings. Check city prices on BevOry.",
  },
  "famous-grouse": {
    description: "The Famous Grouse is a Scottish blended whisky made from malt and grain whiskies. Its core blend leans toward soft fruit, shortbread and a warm finish.",
    story: "The Grouse name dates to the late nineteenth century, with the house marking 1896 in its history. The bird on the label became the sign by which drinkers recognised the blend.",
    tastingNotes: [{ title: "Fruit and biscuit", description: "Candied fruit, citrus peel and buttery shortbread mark the core blend's aroma." }, { title: "Warm finish", description: "A rounded malt-and-grain texture closes gently." }],
    howToEnjoy: [{ subheading: "Easy highball", description: "Pour over ice and lengthen with ginger ale and a squeeze of lime." }, { subheading: "Before dinner", description: "Salted almonds, chicken tikka and cheddar toast work with its soft fruit." }],
    pairingIdeas: [{ title: "Snack board", items: ["salted almonds", "chicken tikka", "cheddar toast", "roast mushrooms"] }],
    whyChoose: "Its fruit-and-shortbread character makes the core blend useful both neat and with ginger.",
    faqs: [{ question: "Is The Famous Grouse a single malt?", answer: "No. The core whisky is a blend of malt and grain Scotch whiskies." }, { question: "How can I mix it simply?", answer: "Serve with ice, ginger ale and a squeeze of lime." }],
    finalVerdict: "A dependable blended Scotch for a simple highball beside savoury snacks.",
    metaTitle: "The Famous Grouse Whisky Guide | BevOry",
    metaDescription: "Read The Famous Grouse's blended Scotch story, fruit notes and serving ideas. Check city prices on BevOry.",
  },
  "bull-dog": {
    description: "Bulldog is a London Dry gin made with a twelve-botanical recipe. Its crisp juniper base is shaped by citrus and spice rather than added sweetness.",
    story: "The brand recast the familiar London Dry profile in a modern bottle with a studded collar. Its distillers built the recipe around botanicals sourced from several parts of the world.",
    tastingNotes: [{ title: "Juniper", description: "Piney juniper leads the aroma." }, { title: "Citrus and spice", description: "A bright citrus note settles into softer spice." }],
    howToEnjoy: [{ subheading: "Tonic", description: "Use a dry tonic and plenty of ice, keeping the garnish simple." }, { subheading: "With food", description: "Chilli paneer, lemon chicken and tandoori prawns hold up beside the botanicals." }],
    pairingIdeas: [{ title: "Spice and citrus", items: ["chilli paneer", "lemon chicken", "tandoori prawns", "salted olives"] }],
    whyChoose: "Bulldog keeps a recognisable London Dry backbone while widening the botanical palette.",
    faqs: [{ question: "What kind of gin is Bulldog?", answer: "It is a London Dry gin." }, { question: "How many botanicals are in its recipe?", answer: "The producer describes a twelve-botanical recipe." }],
    finalVerdict: "A juniper-led gin that takes well to tonic and a plate with a little heat.",
    metaTitle: "Bulldog London Dry Gin Guide | BevOry",
    metaDescription: "Meet Bulldog's twelve-botanical London Dry gin and spicy-food pairings. Check city prices on BevOry.",
  },
  camikara: {
    description: "Camikara is an Indian rum made by Piccadily from fresh sugarcane juice rather than molasses. The spirit is pot-distilled and matured in oak at the company's Haryana distillery.",
    story: "Piccadily developed Camikara alongside its whisky work in Indri. Its name comes from a Sanskrit expression for liquid gold, tying the rum to India's sugarcane crop.",
    tastingNotes: [{ title: "Cane character", description: "Fresh cane gives the spirit a grassy, fruity starting point." }, { title: "Oak", description: "Maturation adds vanilla and warm spice to the cane base." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Try a small pour neat before adding ice or mixing it with soda." }, { subheading: "With spice", description: "Mutton seekh, grilled pineapple and dark chocolate meet its oak and cane notes." }],
    pairingIdeas: [{ title: "Cane and char", items: ["mutton seekh", "grilled pineapple", "dark chocolate", "roast cashews"] }],
    whyChoose: "Camikara brings fresh-cane rum making into an Indian distilling setting.",
    faqs: [{ question: "What is Camikara made from?", answer: "Fresh sugarcane juice, not molasses." }, { question: "Who makes Camikara?", answer: "Piccadily Agro Industries at its Haryana distillery." }],
    finalVerdict: "A rum for drinkers interested in the taste of cane as well as cask.",
    metaTitle: "Camikara Indian Rum Guide | BevOry",
    metaDescription: "Discover Camikara's fresh-cane Indian rum, oak influence and food pairings. Check city prices on BevOry.",
  },
  "canadian-club": {
    description: "Canadian Club is a Canadian whisky that began in Walkerville, Ontario. Its approachable blended style is built for both straight pours and highballs.",
    story: "Grain merchant Hiram Walker founded the distillery in 1858. He put a name on his whisky barrels at a time when many sellers offered anonymous spirit from the cask.",
    tastingNotes: [{ title: "Grain sweetness", description: "Light cereal and vanilla notes make the entry gentle." }, { title: "Soft spice", description: "A modest spice note gives the finish shape." }],
    howToEnjoy: [{ subheading: "Highball", description: "Pour over ice with soda or ginger ale." }, { subheading: "Snack match", description: "Try roast peanuts, chicken kebabs or a sharp cheddar toastie." }],
    pairingIdeas: [{ title: "Highball food", items: ["roast peanuts", "chicken kebabs", "cheddar toastie", "spiced popcorn"] }],
    whyChoose: "Canadian Club has a long Walkerville history and a blend that stays easy to mix.",
    faqs: [{ question: "Who founded Canadian Club?", answer: "Hiram Walker, in Walkerville in 1858." }, { question: "Is Canadian Club a single malt?", answer: "No. It is a Canadian blended whisky." }],
    finalVerdict: "Reach for it when the plan is a tall, uncomplicated whisky drink.",
    metaTitle: "Canadian Club Whisky Guide | BevOry",
    metaDescription: "Read Canadian Club's Walkerville history, gentle whisky notes and highball ideas. Check city prices on BevOry.",
  },
  caorunn: {
    description: "Caorunn is a Scottish gin made at Balmenach Distillery in Speyside. Five locally foraged Celtic botanicals, including rowan berry, meet six classic gin botanicals.",
    story: "The gin launched in 2009 and takes its name from the Gaelic word for rowan berry. A working Copper Berry Chamber handles the botanical infusion at the whisky distillery.",
    tastingNotes: [{ title: "Rowan and herbs", description: "The locally gathered botanicals bring a green, aromatic edge." }, { title: "Classic gin", description: "Juniper and citrus keep the unusual recipe recognisably gin." }],
    howToEnjoy: [{ subheading: "Apple tonic", description: "Serve with tonic over ice and thin slices of red apple." }, { subheading: "Alongside", description: "Coriander chicken, cucumber chaat and smoked trout suit its fresh profile." }],
    pairingIdeas: [{ title: "Green and crisp", items: ["coriander chicken", "cucumber chaat", "smoked trout", "goat-cheese toast"] }],
    whyChoose: "Caorunn's rowan berry and Copper Berry Chamber give it a Speyside story of its own.",
    faqs: [{ question: "Where is Caorunn distilled?", answer: "At Balmenach Distillery in Scotland's Speyside region." }, { question: "What does Caorunn mean?", answer: "It is the Gaelic word for rowan berry." }],
    finalVerdict: "A refreshing gin for an apple-garnished tonic and herb-led food.",
    metaTitle: "Caorunn Scottish Gin Guide | BevOry",
    metaDescription: "Explore Caorunn's Speyside botanicals, rowan berry and apple-tonic serve. Check city prices on BevOry.",
  },
  cardhu: {
    description: "Cardhu is a Speyside single malt Scotch made near the River Spey. Its house reputation rests on a softer, sweet-fruited style.",
    story: "Helen Cumming began distilling with her husband in the early nineteenth century; her daughter-in-law Elizabeth later developed the trade. John Walker & Sons bought the distillery in 1893.",
    tastingNotes: [{ title: "Orchard fruit", description: "Apple-like fruit and honeyed sweetness lead the gentler side of Cardhu." }, { title: "Soft spice", description: "A light oak-spice note closes the sip." }],
    howToEnjoy: [{ subheading: "Small glass", description: "Try neat first, then add a little water." }, { subheading: "After food", description: "Roasted almonds, saffron phirni and mild cheddar suit its softer profile." }],
    pairingIdeas: [{ title: "Gentle pairings", items: ["roasted almonds", "saffron phirni", "mild cheddar", "apple tart"] }],
    whyChoose: "Cardhu offers a Speyside malt with a notable history shaped by Helen and Elizabeth Cumming.",
    faqs: [{ question: "Who were Helen and Elizabeth Cumming?", answer: "Two women of the founding family who helped build Cardhu's distilling and commercial history." }, { question: "Which whisky region is Cardhu in?", answer: "Speyside, Scotland." }],
    finalVerdict: "A measured introduction to Speyside malt when sweetness matters more than smoke.",
    metaTitle: "Cardhu Speyside Whisky Guide | BevOry",
    metaDescription: "Meet Cardhu's Speyside history, gentle fruit notes and serving ideas. Check city prices on BevOry.",
  },
  "carlo-rossi": {
    description: "Carlo Rossi is an American wine label in the Gallo family portfolio. Its broad range spans reds, whites and fruit-led styles rather than a single grape or region.",
    story: "Carlo Rossi joined the Gallo winery in 1953 and became the face of its named jug wines. His relaxed, direct approach to talking about wine shaped the label's public voice.",
    tastingNotes: [{ title: "Red wines", description: "The reds tend toward ripe, easy fruit." }, { title: "Whites", description: "The lighter wines put freshness and straightforward fruit first." }],
    howToEnjoy: [{ subheading: "Choose the glass", description: "Chill whites and pour reds slightly cool, using simple everyday wine glasses." }, { subheading: "With food", description: "Tomato pasta, paneer pizza and barbecue chicken cover much of the range." }],
    pairingIdeas: [{ title: "Everyday plates", items: ["tomato pasta", "paneer pizza", "barbecue chicken", "grilled vegetables"] }],
    whyChoose: "Carlo Rossi makes uncomplicated table wine the point, not a technical tasting exercise.",
    faqs: [{ question: "Who was Carlo Rossi?", answer: "The wine personality who joined Gallo in 1953 and lent his name to the label." }, { question: "Does Carlo Rossi make only red wine?", answer: "No. The range also includes whites and other styles." }],
    finalVerdict: "Pick the style for the meal and let it be an easy table wine.",
    metaTitle: "Carlo Rossi Wine Guide | BevOry",
    metaDescription: "Explore Carlo Rossi's American wine range, story and everyday food pairings. Check city prices on BevOry.",
  },
  chambord: {
    description: "Chambord is a French raspberry liqueur associated with the Loire Valley. Black raspberries and other raspberry varieties meet vanilla, citrus peel and honey in its recipe.",
    story: "The brand draws its identity from the Loire and the royal château at Chambord. Its round bottle has become a recognisable part of cocktail shelves.",
    tastingNotes: [{ title: "Dark berry", description: "Black raspberry gives the liqueur its concentrated fruit note." }, { title: "Sweet finish", description: "Vanilla, honey and citrus peel round out the berries." }],
    howToEnjoy: [{ subheading: "A small splash", description: "Add a little to sparkling wine, or use it to deepen a berry cocktail." }, { subheading: "Dessert", description: "Dark chocolate, raspberry tart and baked cheesecake suit its fruit." }],
    pairingIdeas: [{ title: "Berry desserts", items: ["dark chocolate", "raspberry tart", "baked cheesecake", "vanilla kulfi"] }],
    whyChoose: "Chambord brings a layered raspberry flavour where a plain fruit syrup would fall short.",
    faqs: [{ question: "What fruit defines Chambord?", answer: "Black raspberries alongside other raspberry varieties." }, { question: "Where is Chambord associated with?", answer: "France's Loire Valley." }],
    finalVerdict: "Best used sparingly: a little berry depth goes a long way.",
    metaTitle: "Chambord Raspberry Liqueur Guide | BevOry",
    metaDescription: "Discover Chambord's raspberry, vanilla and citrus notes, with cocktail and dessert ideas. Check city prices on BevOry.",
  },
  chimay: {
    description: "Chimay is a Belgian Trappist beer brewed at the Abbey of Scourmont. Its bottle-conditioned ales include the familiar Red, Blue and White labels, each with a different balance of malt, yeast and fruit.",
    story: "Monks from Westvleteren arrived at Scourmont in 1850 and began brewing in 1862. The community later developed its own yeast culture and continues to make beer under Trappist principles.",
    tastingNotes: [{ title: "Chimay Red", description: "Malt and dark fruit meet a gentle yeast spice." }, { title: "Chimay Blue", description: "The darker ale brings deeper dried-fruit and caramel tones." }],
    howToEnjoy: [{ subheading: "Slow pour", description: "Serve cool, not icy, in a wide goblet; leave the sediment in the bottle if preferred." }, { subheading: "At dinner", description: "Mushroom stew, mutton rogan josh and aged cheese work with the richer ales." }],
    pairingIdeas: [{ title: "Rich plates", items: ["mushroom stew", "mutton rogan josh", "aged cheese", "walnut bread"] }],
    whyChoose: "Chimay gives Belgian ale its monastic context without losing its place at dinner.",
    faqs: [{ question: "Where is Chimay brewed?", answer: "At the Abbey of Scourmont in Belgium." }, { question: "What does bottle-conditioned mean?", answer: "A further fermentation in the bottle helps develop the beer's carbonation and flavour." }],
    finalVerdict: "Make room for the goblet and a meal; Chimay is not a hurried lager.",
    metaTitle: "Chimay Trappist Beer Guide | BevOry",
    metaDescription: "Discover Chimay's Belgian abbey ales, bottle conditioning and food pairings. Check city prices on BevOry.",
  },
  "cloudy-bay": {
    description: "Cloudy Bay is a New Zealand winery whose Marlborough Sauvignon Blanc helped put the region on the world wine map. It also makes Chardonnay, Pinot Noir and other wines from selected New Zealand sites.",
    story: "David Hohnen founded Cloudy Bay in 1985 and brought winemaker Kevin Judd into the first vintage. The estate later broadened beyond Sauvignon Blanc while keeping Marlborough central to its identity.",
    tastingNotes: [{ title: "Sauvignon Blanc", description: "Citrus and tropical fruit carry a sharp, green freshness." }, { title: "Te Koko", description: "Wild-yeast fermentation and oak bring a fuller, more textured Sauvignon Blanc style." }],
    howToEnjoy: [{ subheading: "Keep it cool", description: "Serve Sauvignon Blanc chilled in a white-wine glass, allowing the aroma to open." }, { subheading: "Fresh plates", description: "Tandoori prawns, coriander fish and goat cheese suit its brisk acidity." }],
    pairingIdeas: [{ title: "Bright pairings", items: ["tandoori prawns", "coriander fish", "goat cheese", "citrus salad"] }],
    whyChoose: "Cloudy Bay captures the vivid side of Marlborough without making every bottle taste alike.",
    faqs: [{ question: "Who founded Cloudy Bay?", answer: "David Hohnen founded it in 1985, with Kevin Judd as founding winemaker." }, { question: "Is Cloudy Bay only Sauvignon Blanc?", answer: "No. Its range also includes Chardonnay, Pinot Noir and other wines." }],
    finalVerdict: "A clear choice when a seafood meal calls for New Zealand's citrus-and-herb wine style.",
    metaTitle: "Cloudy Bay Wine Guide | BevOry",
    metaDescription: "Explore Cloudy Bay's Marlborough Sauvignon Blanc, founding story and food matches. Check city prices on BevOry.",
  },
  clynelish: {
    description: "Clynelish is a Highland single malt made near Brora on Scotland's northeast coast. Its distillate is known for a waxy texture, honeyed fruit and a modest coastal edge.",
    story: "The original Clynelish site dates to 1819; the modern distillery opened across the road in 1968. Its whisky became an important component in the Johnnie Walker blending family.",
    tastingNotes: [{ title: "Waxy texture", description: "A distinctive, coating mouthfeel gives the malt its signature shape." }, { title: "Fruit and coast", description: "Honeyed fruit meets a light mineral or maritime note." }],
    howToEnjoy: [{ subheading: "Slow sip", description: "Pour neat in a small whisky glass, then add a few drops of water." }, { subheading: "Food match", description: "Smoked fish, tandoori chicken and salted cashews suit its savoury edge." }],
    pairingIdeas: [{ title: "Coastal savour", items: ["smoked fish", "tandoori chicken", "salted cashews", "roast potatoes"] }],
    whyChoose: "Clynelish is a Highland malt remembered as much for texture as for aroma.",
    faqs: [{ question: "Where is Clynelish distilled?", answer: "Near Brora in the Scottish Highlands." }, { question: "Why do tasters call Clynelish waxy?", answer: "The distillate has a characteristic coating texture often described that way." }],
    finalVerdict: "Try it when texture and a hint of the coast matter more than overt smoke.",
    metaTitle: "Clynelish Highland Whisky Guide | BevOry",
    metaDescription: "Read Clynelish's Brora history, waxy texture and seafood pairings. Check city prices on BevOry.",
  },
  codigo: {
    description: "Código 1530 is a tequila made in Amatitán, Jalisco, from mature agave. The producer cooks the agave in stainless-steel ovens and uses French oak red-wine barrels for its aged expressions.",
    story: "The name points to the old codes and customs of Amatitán and the Los Bajos region. Its cross emblem comes from the Jalisco coat of arms, which the company traces to 1530.",
    tastingNotes: [{ title: "Blanco", description: "Cooked agave gives a clean, peppery starting point." }, { title: "Rested expressions", description: "Red-wine barrels add gentle fruit and oak around the agave." }],
    howToEnjoy: [{ subheading: "Small pour", description: "Taste Blanco neat before trying it with grapefruit soda and lime." }, { subheading: "Spice and char", description: "Tandoori prawns, grilled corn and salsa verde work with agave's savoury side." }],
    pairingIdeas: [{ title: "Agave plates", items: ["tandoori prawns", "grilled corn", "salsa verde", "chilli-lime peanuts"] }],
    whyChoose: "Código 1530 puts Amatitán agave next to an unusual red-wine-cask approach for aged tequila.",
    faqs: [{ question: "Where is Código 1530 made?", answer: "In Amatitán, Jalisco, Mexico." }, { question: "What barrels are used for its rested tequilas?", answer: "The producer uses French oak barrels previously used for red wine from Napa Valley." }],
    finalVerdict: "A useful comparison between direct agave flavour and wine-cask influence.",
    metaTitle: "Código 1530 Tequila Guide | BevOry",
    metaDescription: "Explore Código 1530's Amatitán agave, Blanco and wine-cask styles. Check city prices on BevOry.",
  },
  "copper-dog": {
    description: "Copper Dog is a Speyside blended malt Scotch made from eight single malts. Its name comes from the Copper Dog pub at the Craigellachie Hotel beside the River Spey.",
    story: "The brand ties itself to the metal 'copper dog' used to discreetly carry whisky from a cask. That bit of distilling folklore became a modern blended-malt label associated with the Craigellachie Hotel.",
    tastingNotes: [{ title: "Orchard fruit", description: "Apple-like fruit keeps the malt fresh." }, { title: "Sweet malt", description: "Vanilla and soft cereal notes round out the blend." }],
    howToEnjoy: [{ subheading: "Long drink", description: "Try it over ice with soda or ginger ale." }, { subheading: "Bar snacks", description: "Chicken tikka, salted peanuts and a cheddar toastie suit the fruit-led malt." }],
    pairingIdeas: [{ title: "Pub table", items: ["chicken tikka", "salted peanuts", "cheddar toastie", "roast mushrooms"] }],
    whyChoose: "Eight Speyside malts make this a blended malt with an easy, fruit-led highball style.",
    faqs: [{ question: "Is Copper Dog a blended Scotch?", answer: "Yes. More specifically, it is a blend of single malt whiskies, without grain whisky." }, { question: "What does its name refer to?", answer: "The Craigellachie Hotel pub and a small copper vessel once used to carry whisky." }],
    finalVerdict: "A friendly Speyside malt blend for ice, soda and bar food.",
    metaTitle: "Copper Dog Blended Malt Guide | BevOry",
    metaDescription: "Meet Copper Dog's eight Speyside malts, pub history and highball ideas. Check city prices on BevOry.",
  },
  craigellachie: {
    description: "Craigellachie is a Speyside single malt made where the Rivers Fiddich and Spey meet. Worm-tub condensers help give its spirit a weightier texture than many neighbours' malts.",
    story: "The distillery dates to 1891 and takes its name from the rock above the village. It has kept the older worm-tub method even as much of Scotch production moved toward other condensers.",
    tastingNotes: [{ title: "Fruit", description: "Pineapple-like fruit gives the spirit a bright lift." }, { title: "Weight", description: "The worm-tub character brings a muscular, savoury depth." }],
    howToEnjoy: [{ subheading: "Neat first", description: "Use a small tulip glass and give the whisky a few minutes before the first sip." }, { subheading: "Strong food", description: "Mutton seekh, mushroom pie and aged cheddar can meet its full texture." }],
    pairingIdeas: [{ title: "Fuller plates", items: ["mutton seekh", "mushroom pie", "aged cheddar", "roast walnuts"] }],
    whyChoose: "Craigellachie keeps a substantial, old-fashioned Speyside spirit in production.",
    faqs: [{ question: "What are worm tubs?", answer: "Coiled pipes in cooling water that condense whisky vapour after distillation." }, { question: "Where is Craigellachie?", answer: "In Speyside, above the meeting of the Fiddich and Spey rivers." }],
    finalVerdict: "Try it for a denser Speyside malt with fruit as well as weight.",
    metaTitle: "Craigellachie Whisky Guide | BevOry",
    metaDescription: "Discover Craigellachie's Speyside worm tubs, fruit-led malt and food pairings. Check city prices on BevOry.",
  },
  "crystal-head": {
    description: "Crystal Head is a Canadian vodka brand created by Dan Aykroyd and artist John Alexander. Its skull bottle holds several distinct spirits, including corn-based Original, wheat-based Aurora and agave-based Onyx.",
    story: "Aykroyd and Alexander designed the skull as a symbol of life rather than a conventional vodka bottle. The brand built its identity around an additive-free spirit and an unusually sculptural package.",
    tastingNotes: [{ title: "Original", description: "Corn gives a soft, clean spirit with a mild sweetness." }, { title: "Aurora", description: "English wheat gives this expression a different grain texture." }],
    howToEnjoy: [{ subheading: "Cold pour", description: "Serve a small measure chilled or use it in a dry Martini." }, { subheading: "Simple food", description: "Smoked salmon, cucumber chaat and salted cashews leave room for the vodka." }],
    pairingIdeas: [{ title: "Cool and salty", items: ["smoked salmon", "cucumber chaat", "salted cashews", "potato blini"] }],
    whyChoose: "The skull gets attention, but the choice between corn, wheat and agave is the more useful detail.",
    faqs: [{ question: "Who created Crystal Head?", answer: "Dan Aykroyd and artist John Alexander." }, { question: "Is every Crystal Head vodka made from corn?", answer: "No. Original uses Canadian corn, while Aurora uses English wheat and Onyx uses Blue Weber agave." }],
    finalVerdict: "Pick by base ingredient, not only by bottle shape.",
    metaTitle: "Crystal Head Vodka Guide | BevOry",
    metaDescription: "Compare Crystal Head's corn, wheat and agave vodkas, with serving ideas. Check city prices on BevOry.",
  },
  delirium: {
    description: "Delirium is a Belgian beer range from Brouwerij Huyghe, identified by its pink elephant label. The best-known beer, Delirium Tremens, is a strong golden ale rather than a lager.",
    story: "Delirium Tremens was introduced on 26 December 1988. The Huyghe brewery in Melle later expanded the range with darker and fruit-led beers while keeping the elephant as its sign.",
    tastingNotes: [{ title: "Delirium Tremens", description: "Golden malt, fruit and lively Belgian yeast spice make a complex first impression." }, { title: "Delirium Nocturnum", description: "The dark beer shifts toward deeper malt and dried fruit." }],
    howToEnjoy: [{ subheading: "Belgian glass", description: "Pour cool into a tulip glass and leave space for the foam." }, { subheading: "Food", description: "Mutton seekh, mushroom toast and sharp cheese stand up to the golden ale." }],
    pairingIdeas: [{ title: "Beer with bite", items: ["mutton seekh", "mushroom toast", "sharp cheese", "spiced fries"] }],
    whyChoose: "Delirium gives Belgian yeast character room to speak over its malt.",
    faqs: [{ question: "Who brews Delirium?", answer: "Brouwerij Huyghe in Melle, Belgium." }, { question: "When did Delirium Tremens appear?", answer: "The brewery dates its launch to 26 December 1988." }],
    finalVerdict: "Give it a proper glass and time; the pink elephant fronts a serious Belgian ale.",
    metaTitle: "Delirium Belgian Beer Guide | BevOry",
    metaDescription: "Explore Delirium Tremens, Huyghe's Belgian ale and hearty food matches. Check city prices on BevOry.",
  },
  "dom-perignon": {
    description: "Dom Pérignon is a vintage-only Champagne from the house of Moët & Chandon. Each release expresses a single harvest, with Chardonnay and Pinot Noir central to the blend.",
    story: "The name honours Dom Pierre Pérignon, a monk linked to the Abbey of Hautvillers. The modern house chooses to release only vintage Champagne, leaving each growing year with its own character.",
    tastingNotes: [{ title: "Vintage white", description: "Citrus, orchard fruit and fine autolytic notes develop with time on lees." }, { title: "Rosé", description: "The rosé expression brings more red-fruit depth alongside Champagne freshness." }],
    howToEnjoy: [{ subheading: "A wider glass", description: "Serve chilled in a tulip-shaped wine glass rather than a narrow flute." }, { subheading: "With food", description: "Oysters, tandoori prawns and mushroom tart each meet a different side of its texture." }],
    pairingIdeas: [{ title: "At the table", items: ["oysters", "tandoori prawns", "mushroom tart", "aged Comté"] }],
    whyChoose: "A single-vintage approach makes the harvest year part of the decision, not decoration on the label.",
    faqs: [{ question: "Is Dom Pérignon made every year?", answer: "No. The house makes vintage Champagne only." }, { question: "Which grapes are central to Dom Pérignon?", answer: "Chardonnay and Pinot Noir." }],
    finalVerdict: "Let the vintage guide the occasion, then give the wine a real glass and a meal.",
    metaTitle: "Dom Pérignon Champagne Guide | BevOry",
    metaDescription: "Read Dom Pérignon's vintage-only Champagne story, tasting style and pairings. Check city prices on BevOry.",
  },
  donnafugata: {
    description: "Donnafugata is a Sicilian wine estate founded by Giacomo Rallo and Gabriella Anca. Its vineyards reach from Contessa Entellina to Pantelleria, Etna and Vittoria, making wines from grapes including Zibibbo and Nero d'Avola.",
    story: "The Rallo family established Donnafugata in 1983, building on wine cellars in Marsala. Gabriella drew the name and windblown-woman label from the Sicilian setting of The Leopard; the family began working on Pantelleria in 1989.",
    tastingNotes: [{ title: "Pantelleria Zibibbo", description: "The island's aromatic grape can bring orange blossom and apricot to sweet wine." }, { title: "Sicilian reds", description: "Nero d'Avola gives the red side darker fruit and savoury weight." }],
    howToEnjoy: [{ subheading: "Match the style", description: "Chill aromatic whites; pour fuller Sicilian reds a little below room temperature." }, { subheading: "Two tables", description: "Grilled aubergine and lamb ragù suit reds, while almond halwa suits a small glass of sweet Zibibbo." }],
    pairingIdeas: [{ title: "Sicily and spice", items: ["grilled aubergine", "lamb ragù", "almond halwa", "roasted pistachios"] }],
    whyChoose: "Donnafugata makes Sicily's mainland and island landscapes visible across one family portfolio.",
    faqs: [{ question: "Who founded Donnafugata?", answer: "Giacomo Rallo and Gabriella Anca in 1983." }, { question: "Where is its famous sweet wine from?", answer: "Ben Ryé comes from Zibibbo grapes grown on Pantelleria." }],
    finalVerdict: "Follow the island on the label: a Pantelleria sweet wine and an Etna red ask for different food.",
    metaTitle: "Donnafugata Sicilian Wine Guide | BevOry",
    metaDescription: "Discover Donnafugata's Sicilian estates, Zibibbo and Nero d'Avola food matches. Check city prices on BevOry.",
  },
  "el-dorado": {
    description: "El Dorado is a Demerara rum brand made by Demerara Distillers at the Diamond Distillery in Guyana. Its blends draw on several still types, including historic wooden stills.",
    story: "Guyana's rum trade grew along the Demerara River through centuries of sugar production. Demerara Distillers gathered that distilling inheritance at Diamond, preserving old wooden equipment alongside modern stills.",
    tastingNotes: [{ title: "Demerara depth", description: "Molasses-based richness can bring brown sugar and dried-fruit impressions." }, { title: "Wooden-still weight", description: "The historic pot-still spirit lends body to selected blends." }],
    howToEnjoy: [{ subheading: "Neat or over ice", description: "Try a measured pour neat before adding one cube." }, { subheading: "With food", description: "Jerk chicken, mutton seekh and dark chocolate suit its richer side." }],
    pairingIdeas: [{ title: "Deep flavours", items: ["jerk chicken", "mutton seekh", "dark chocolate", "grilled pineapple"] }],
    whyChoose: "Few rum houses can still blend spirit from Guyana's surviving wooden stills.",
    faqs: [{ question: "Where is El Dorado rum made?", answer: "At Demerara Distillers' Diamond Distillery in Guyana." }, { question: "Does every El Dorado bottle use one still?", answer: "No. The range includes blends as well as single-still expressions." }],
    finalVerdict: "A Guyanese rum to explore by still and blend, not only by age statement.",
    metaTitle: "El Dorado Demerara Rum Guide | BevOry",
    metaDescription: "Explore El Dorado's Guyanese wooden stills, rum style and food pairings. Check city prices on BevOry.",
  },
};
