// Editorial source review: docs/editorial/product-batch-34-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

type Entry = Omit<ProductPublicDetail, "tastingNotes" | "servingGuide" | "metaTitle" | "metaDescription"> & {
  nose: string; palate: string; finish: string; glassware: string; temperature: string; serve: string; description: string;
};
const detail = (item: Entry): ProductPublicDetail => ({
  productName: item.productName, category: item.category,
  shortOverview: item.shortOverview, craftStory: item.craftStory,
  tastingNotes: { nose: item.nose, palate: item.palate, finish: item.finish },
  servingGuide: { glassware: item.glassware, idealTemperature: item.temperature, recommendation: item.serve },
  foodPairings: item.foodPairings, whyBuyThis: item.whyBuyThis, faqs: item.faqs,
  metaTitle: `${item.productName} Price, Taste & Review | BevOry`.length <= 60
    ? `${item.productName} Price, Taste & Review | BevOry`
    : `${item.productName} Price | BevOry`.length <= 60
      ? `${item.productName} Price | BevOry`
      : item.productName.length <= 60 ? item.productName : `${item.productName.slice(0, 59)}…`,
  metaDescription: item.description,
});

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "macallan-the-macallan-rare-cask-black-9780123": detail({
    productName: "The Macallan Rare Cask Black", category: "Peated Speyside Single Malt Scotch", shortOverview: "Rare Cask Black is an unusual, smoky Macallan rather than an example of the distillery's usual unpeated house style. Dates, figs and raisins meet restrained wood smoke.", craftStory: "The Macallan selects rare stocks of peated distillation at its Speyside estate. The spirit matures in American and European sherry-seasoned oak, and the maker describes this release as an exception to its usual unpeated character.", nose: "Dried fruit, nutmeg and seasoned oak.", palate: "Full and velvety, with dates, figs, raisins and measured smoke.", finish: "Long and fruity, trailing elegant wood smoke.", glassware: "Glencairn glass", temperature: "Room temperature (18–20°C)", serve: "Sip 25 ml neat; add a few drops of spring water only after tasting the first pour.", foodPairings: ["galouti kebab", "mutton seekh", "lamb rogan josh", "70% dark chocolate"], whyBuyThis: "It is a genuinely peated Macallan drawn from unusually rare distillate.", faqs: [{ question: "Is every Macallan smoky?", answer: "No. Rare Cask Black draws on exceptional peated stocks and is not typical of the range." }, { question: "What wood matures it?", answer: "The maker identifies American and European sherry-seasoned oak casks." }], description: "Rare Cask Black pairs dried fruit with rare Macallan smoke. Try with galouti kebab; check city prices on BevOry."
  }),
  "macallan-the-macallan-a-night-on-earth-scotch-720fe5d": detail({
    productName: "The Macallan A Night on Earth in Scotland", category: "Speyside Single Malt Scotch", shortOverview: "A Night on Earth in Scotland evokes Hogmanay through shortbread-like malt sweetness, dried orange and spice. It is a seasonal, unpeated single malt best tried neat.", craftStory: "The Macallan marries American and European sherry-seasoned oak casks with American ex-bourbon barrels for this Speyside release. Illustrator Erica Dorn designed packaging inspired by Scotland's New Year fire and first-footing traditions.", nose: "Shortbread, dried orange and warm oak.", palate: "Rounded and sweet, with buttery biscuit, citrus peel and baking spice.", finish: "Medium-long, with orange and soft oak.", glassware: "Glencairn glass", temperature: "Room temperature (18–20°C)", serve: "Pour 25–30 ml neat; serve a plain shortbread biscuit alongside if desired.", foodPairings: ["roasted cashews", "almond nankhatai", "70% dark chocolate", "galouti kebab"], whyBuyThis: "Its cask mix creates a precise festive-biscuit profile without added flavouring.", faqs: [{ question: "Is A Night on Earth peated?", answer: "The producer describes sherry-seasoned and ex-bourbon casks, not a peated release." }, { question: "What is Hogmanay?", answer: "It is Scotland's New Year celebration, the theme of this limited edition." }], description: "Macallan A Night on Earth has shortbread, orange and spice. Pair with nankhatai; check city prices on BevOry."
  }),
  "fratelli-kyra-red-d15e19a": detail({
    productName: "Fratelli Kyra Red", category: "Indian Red Wine", shortOverview: "Kyra Red sits in Fratelli's approachable Indian wine range. Its ripe red-fruit direction is best served slightly cool with spiced food.", craftStory: "Fratelli grew from an Italian-Indian partnership at Akluj, Maharashtra, guided by Tuscan winemaker Piero Masi. Kyra Red belongs to its approachable Indian wine range.", nose: "Ripe plum and red berries.", palate: "Medium-bodied, fruit-led and softly tannic.", finish: "Medium, with berry fruit and mild spice.", glassware: "Bordeaux glass", temperature: "Slightly cool (16–18°C)", serve: "Pour into a medium red-wine glass and give it ten minutes of air.", foodPairings: ["tandoori chicken", "mutton ghee roast", "paneer tikka", "lamb chops"], whyBuyThis: "An Akluj-grown Indian red with an easy, food-led style.", faqs: [{ question: "Where is Fratelli based?", answer: "Its vineyards and winery are centred on Akluj, Maharashtra." }, { question: "How should Kyra Red be served?", answer: "Aim for 16–18°C rather than room-warm service." }], description: "Fratelli Kyra Red offers ripe berries and soft tannins. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "fratelli-sidus-premium-red-wine-71ab638": detail({
    productName: "Fratelli Sidus Premium Red", category: "Indian Sweet Red Wine", shortOverview: "Sidus is Fratelli's sweeter, entry-level red-wine style. Its dark fruit and soft sweetness make it easier with spice or a small dessert than with delicate seafood.", craftStory: "The Fratelli partnership farms around Akluj in Maharashtra. The company's value-wine portfolio includes Sidus, which has also been presented as an Indian port-style wine rather than a dry single-varietal red.", nose: "Dark berries, raisin and a light sweet-spice note.", palate: "Soft and sweet-leaning, with plum and grape preserve.", finish: "Medium, fruity and gently warming.", glassware: "Small red-wine glass", temperature: "Slightly cool (14–16°C)", serve: "Pour a smaller measure and chill lightly to balance sweetness.", foodPairings: ["gajar halwa", "spiced roasted nuts", "70% dark chocolate", "mutton seekh"], whyBuyThis: "Its sweet-fruit profile makes a simple dessert-adjacent Indian wine.", faqs: [{ question: "Is Sidus a dry Cabernet Sauvignon?", answer: "No. Fratelli positions Sidus in its value and port-style range." }, { question: "Should sweet red wine be served warm?", answer: "A slight chill around 14–16°C keeps it fresher." }], description: "Fratelli Sidus has soft dark fruit and sweetness. Pair with gajar halwa; check city prices on BevOry."
  }),
  "fratelli-mosso-peach-wine-88aeab5": detail({
    productName: "Fratelli Mosso Peach Wine", category: "Peach-Flavoured Indian Wine", shortOverview: "Mosso is the peach-focused wine in Fratelli's value range. Serve it well chilled to keep the stone-fruit sweetness fresh.", craftStory: "Fratelli's Akluj-based Indian-Italian winemaking venture identifies Mosso as a peach wine created for particular regional markets. The peach profile distinguishes it from the estate's dry varietal wines.", nose: "Ripe peach and soft floral fruit.", palate: "Light, sweet and peach-led, with a gentle wine acidity.", finish: "Short, fruity and refreshing.", glassware: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve chilled in a small white-wine glass; avoid adding syrup.", foodPairings: ["malai paneer tikka", "fruit chaat", "tandoori prawns", "grilled peaches"], whyBuyThis: "A clear peach profile gives a different entry point to Indian wine.", faqs: [{ question: "Is Mosso a dry white wine?", answer: "No. Fratelli describes it as peach wine." }, { question: "How cold should it be?", answer: "Around 8–10°C keeps the fruit note lively." }], description: "Fratelli Mosso is peach-led and lightly sweet. Pair with fruit chaat; check city prices on BevOry."
  }),
  "fratelli-ziva-white-wine-d53e976": detail({
    productName: "Fratelli Ziva White", category: "Indian White Wine", shortOverview: "Ziva White is a fruit-forward member of Fratelli's accessible wine range. Its lighter body suits chilled service and fresh Indian seafood.", craftStory: "Fratelli farms around Akluj, Maharashtra, with an Indian-Italian founding team and Tuscan winemaking influence. Its company portfolio names Ziva White within a red, white and rosé value line.", nose: "Citrus, orchard fruit and light flowers.", palate: "Light to medium-bodied, with fruit sweetness and fresh acidity.", finish: "Short, clean and citrusy.", glassware: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Pour at 8–10°C and let the glass warm slightly while drinking.", foodPairings: ["rava-fried fish", "tandoori prawns", "malai paneer tikka", "cucumber chaat"], whyBuyThis: "An approachable Indian white that works with coastal spice.", faqs: [{ question: "Is Ziva White made in India?", answer: "Yes. It is part of Fratelli's Indian wine range based around Akluj." }, { question: "Which glass suits it?", answer: "A standard white-wine glass keeps it cool and aromatic." }], description: "Fratelli Ziva White offers citrus and orchard fruit. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "fratelli-ziva-red-wine-7b4e62d": detail({
    productName: "Fratelli Ziva Red", category: "Indian Red Wine", shortOverview: "Ziva Red is the red counterpart to Fratelli's approachable Ziva White. Ripe fruit and soft tannin suit a broad range of Indian grilled dishes.", craftStory: "Fratelli's wine project unites Indian and Italian families at Akluj in Maharashtra. Ziva Red sits alongside white and rosé wines in the company's accessible Ziva range.", nose: "Plum, red cherry and a little spice.", palate: "Medium-bodied and fruit-forward, with gentle tannin.", finish: "Medium, berry-led and softly dry.", glassware: "Bordeaux glass", temperature: "Slightly cool (16–18°C)", serve: "Serve slightly cool and allow ten minutes in the glass.", foodPairings: ["tandoori chicken", "mutton ghee roast", "paneer tikka", "lamb chops"], whyBuyThis: "A soft Indian red for everyday spiced meals.", faqs: [{ question: "Is Ziva Red a dessert wine?", answer: "It is Fratelli's red Ziva table-wine expression." }, { question: "What temperature suits it?", answer: "Around 16–18°C is better than a hot room-temperature pour." }], description: "Fratelli Ziva Red has plum and soft tannins. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "fratelli-sidus-port-wine-7419995": detail({
    productName: "Fratelli Sidus Port-Style Wine", category: "Indian Sweet Port-Style Wine", shortOverview: "Sidus is Fratelli's dark, sweet, port-style wine. A small cool pour sits well beside nuts or Indian sweets.", craftStory: "Fratelli's Akluj-based portfolio identifies Sidus as its value-range port-style wine. The term describes a style here; it is not a claim that this Indian wine comes from Portugal's protected Douro region.", nose: "Raisin, dark plum and fruit preserve.", palate: "Rounded and sweet, with dried-fruit weight and mild warmth.", finish: "Medium, sweet-fruited and gently spiced.", glassware: "Small dessert-wine glass", temperature: "Slightly cool (14–16°C)", serve: "Pour a modest measure at 14–16°C alongside dessert.", foodPairings: ["gajar halwa", "roasted walnuts", "70% dark chocolate", "mutton seekh"], whyBuyThis: "Its concentrated sweetness fits a small after-dinner serve.", faqs: [{ question: "Is Sidus from Portugal?", answer: "No. It is an Indian port-style wine from Fratelli." }, { question: "How should it be served?", answer: "A small pour, lightly chilled, suits its sweetness." }], description: "Fratelli Sidus Port-Style has raisin and plum sweetness. Pair with gajar halwa; check city prices on BevOry."
  }),
  "fratelli-ziva-rose-3837a9e": detail({
    productName: "Fratelli Ziva Rosé", category: "Indian Rosé Wine", shortOverview: "Ziva Rosé offers Fratelli's lighter red-fruit style between Ziva White and Red. Chill it well for tandoori food or a warm-weather meal.", craftStory: "Fratelli's Akluj, Maharashtra portfolio includes Ziva in red, white and rosé. The partnership joins Indian growers and Italian winemaking experience.", nose: "Strawberry, red cherry and light citrus.", palate: "Light and fresh, with red-berry fruit and crisp acidity.", finish: "Short, dry-leaning and fruity.", glassware: "Rosé or white-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve at 8–10°C in a smaller stemmed glass.", foodPairings: ["tandoori prawns", "malai paneer tikka", "cucumber chaat", "rava-fried fish"], whyBuyThis: "A flexible rosé that bridges seafood and gentle spice.", faqs: [{ question: "Is Ziva Rosé a red wine?", answer: "No. It is the rosé member of Fratelli's Ziva line." }, { question: "Does rosé need chilling?", answer: "Yes. Around 8–10°C keeps its fruit and acidity balanced." }], description: "Fratelli Ziva Rosé has strawberry and citrus. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "fratelli-vero-rosso-a864b5f": detail({
    productName: "Fratelli Vero Rosso", category: "Indian Cabernet Sauvignon Red Wine", shortOverview: "Vero Rosso is a straightforward, fruit-led Indian red. Cabernet Sauvignon's dark-fruit and tannic shape makes it a partner for savoury grilled dishes.", craftStory: "Fratelli's Akluj vineyards sit in Maharashtra and reflect an Indian-Italian wine partnership. Vero Rosso is a Cabernet Sauvignon-led red made for uncomplicated meals.", nose: "Blackcurrant, plum and mild herb.", palate: "Medium-bodied, dark-fruited and moderately tannic.", finish: "Medium, dry and lightly savoury.", glassware: "Bordeaux glass", temperature: "Slightly cool (16–18°C)", serve: "Serve at 16–18°C and let it open briefly in the glass.", foodPairings: ["mutton ghee roast", "tandoori chicken", "lamb chops", "aged cheddar"], whyBuyThis: "A direct Indian Cabernet-style red for robust food.", faqs: [{ question: "What style is Vero Rosso?", answer: "It is a straightforward Indian red associated with Cabernet Sauvignon." }, { question: "Should it be chilled?", answer: "A slight chill to 16–18°C keeps the fruit fresh." }], description: "Fratelli Vero Rosso has blackcurrant and firm fruit. Pair with mutton roast; check city prices on BevOry."
  }),
  "fratelli-kyra-white-578c860": detail({
    productName: "Fratelli Kyra White", category: "Indian White Wine", shortOverview: "Kyra White is a light, accessible Fratelli wine for chilled service. Fresh orchard-fruit notes make it a sensible partner for paneer and coastal fish.", craftStory: "Fratelli's Indian-Italian founding families established vineyards at Akluj, Maharashtra, with winemaking guidance from Piero Masi. Kyra White is part of its approachable wine range.", nose: "Green apple, citrus and light flowers.", palate: "Light to medium-bodied, fresh and fruit-led.", finish: "Short, crisp and orchard-fruited.", glassware: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Pour at 8–10°C and avoid over-chilling below the fruit's aroma range.", foodPairings: ["rava-fried fish", "malai paneer tikka", "tandoori prawns", "cucumber chaat"], whyBuyThis: "A simple Indian white for fresh, lightly spiced food.", faqs: [{ question: "Is Kyra White made in India?", answer: "It belongs to Fratelli's Akluj-based Indian wine portfolio." }, { question: "How cold should it be served?", answer: "Around 8–10°C in a white-wine glass." }], description: "Fratelli Kyra White has orchard fruit and citrus. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "bacardi-plus-cranberry-7eb388e": detail({
    productName: "Bacardi Plus Cranberry", category: "Cranberry Rum Ready-to-Drink", shortOverview: "Plus Cranberry is a premixed Bacardi rum drink with tart berry flavour. Its chilled bottle is for a quick serve, not for measuring like a full-strength rum.", craftStory: "Bacardi's rum heritage began with Don Facundo Bacardí Massó in Santiago de Cuba in 1862. The India-market Plus line includes Cranberry as a separate ready-to-drink variant, with the local bottle label governing its strength.", nose: "Cranberry and a soft citrus edge.", palate: "Light, sweet-tart and berry-led, with gentle rum warmth.", finish: "Short, refreshing and tangy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a squeeze of lime; no extra syrup is needed.", foodPairings: ["paneer tikka", "chilli-lime corn", "tandoori chicken", "spiced roasted peanuts"], whyBuyThis: "Cranberry gives the premix a tart counterpoint to sweetness.", faqs: [{ question: "Is Plus Cranberry full-strength rum?", answer: "No. It is a premixed ready-to-drink beverage; read the pack for its ABV." }, { question: "Does it need a mixer?", answer: "No. It can be served chilled as bottled." }], description: "Bacardi Plus Cranberry is tart and berry-led. Pair with paneer tikka; check city prices on BevOry."
  }),
  "bacardi-plus-orange-4cb078d": detail({
    productName: "Bacardi Plus Orange", category: "Orange Rum Ready-to-Drink", shortOverview: "Plus Orange delivers sweet orange over a light premixed rum drink. Chill it thoroughly to keep the citrus from feeling heavy.", craftStory: "Bacardi's classic rum starts from fermented sugarcane molasses before distillation and blending. Plus Orange is an India-market ready-to-drink extension rather than an oak-aged sipping rum.", nose: "Orange peel and sweet citrus.", palate: "Light-bodied and fruity, with orange sweetness and soft rum notes.", finish: "Short, citrusy and lightly sweet.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice with a thin orange wheel; skip extra juice.", foodPairings: ["tandoori chicken", "chilli-lime corn", "paneer tikka", "roasted peanuts"], whyBuyThis: "A ready orange serve needs no separate fruit mixer.", faqs: [{ question: "Is Plus Orange a bottle of plain rum?", answer: "No. It is a flavoured ready-to-drink premix." }, { question: "What strength is it?", answer: "Check the local bottle label, as ready-to-drink strengths can vary by market." }], description: "Bacardi Plus Orange is bright and citrus-led. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "bacardi-plus-lemonade-f232329": detail({
    productName: "Bacardi Plus Lemonade", category: "Lemon Rum Ready-to-Drink", shortOverview: "Plus Lemonade is a tart-sweet premix designed to be opened cold. Fresh mint makes a better garnish than more lemonade.", craftStory: "Bacardi's rum-making process ferments and distils sugarcane molasses before blending. India-market Plus Lemonade combines the rum identity with a ready citrus-drink format, separate from the brand's full-strength Limón rum.", nose: "Lemon zest and light sugarcane.", palate: "Light and lively, with lemonade sweetness and citrus tang.", finish: "Short, crisp and lemony.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a fresh mint sprig.", foodPairings: ["tandoori prawns", "chilli-lime corn", "paneer tikka", "spiced roasted makhana"], whyBuyThis: "A premixed lemon-and-rum style is convenient without extra cocktail ingredients.", faqs: [{ question: "Is Plus Lemonade the same as Bacardi Limón?", answer: "No. Plus is ready to drink; Limón is a flavoured rum for mixing." }, { question: "Should it be diluted?", answer: "It is already mixed; serve chilled or over ice." }], description: "Bacardi Plus Lemonade is tart, sweet and citrusy. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "bacardi-apple-9b56bcc": detail({
    productName: "Bacardi Apple", category: "Apple-Flavoured Rum", shortOverview: "Bacardi Apple brings crisp orchard fruit to a white-rum style. A dry ginger ale or soda keeps it from tasting like apple syrup.", craftStory: "The Bacardi house began in 1862 in Santiago de Cuba and makes its core rum from fermented molasses. Apple flavour gives this mixing expression its distinction; it is not an age-stated rum.", nose: "Green apple and soft cane sweetness.", palate: "Light-bodied and fruit-led, with crisp apple and gentle rum warmth.", finish: "Short, fresh and lightly sweet.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Use 45 ml with chilled soda or dry ginger ale and a squeeze of lime.", foodPairings: ["tandoori chicken", "paneer tikka", "chilli-lime corn", "roasted peanuts"], whyBuyThis: "Apple's tart edge makes an easy lighter rum highball.", faqs: [{ question: "Is Bacardi Apple an aged rum?", answer: "It is an apple-flavoured rum, not an age-stated sipping expression." }, { question: "What balances the apple sweetness?", answer: "Fresh lime and plain soda keep the serve bright." }], description: "Bacardi Apple brings crisp orchard fruit to rum. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "bacardi-orange-dlx-original-rum-a433eae": detail({
    productName: "Bacardi Orange Deluxe Rum", category: "Orange-Flavoured Rum", shortOverview: "Orange Deluxe is a full-strength flavoured rum rather than a premixed Bacardi Plus drink. Its citrus peel character works best with soda and fresh lime.", craftStory: "Bacardi's rum base begins with fermented sugarcane molasses and its house yeast. Orange flavour gives this India-market mixing rum a separate role from the brand's ready-to-drink orange bottle.", nose: "Sweet orange peel and light cane.", palate: "Medium-light, with ripe orange and a touch of bitter peel.", finish: "Short, citrusy and warming.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled soda and 10 ml fresh lime juice.", foodPairings: ["tandoori chicken", "paneer tikka", "spiced roasted peanuts", "grilled pineapple"], whyBuyThis: "Orange peel stands up to soda without demanding a sweet mixer.", faqs: [{ question: "Is Orange Deluxe ready to drink?", answer: "No. It is sold as a flavoured rum for mixing." }, { question: "Is it the same as Plus Orange?", answer: "Plus Orange is a premixed drink; Orange Deluxe is a rum bottle." }], description: "Bacardi Orange Deluxe has citrus peel and cane warmth. Pair with paneer tikka; check city prices on BevOry."
  }),
  "bacardi-green-lime-super-deluxe-original-lime-rum-9f4213c": detail({
    productName: "Bacardi Green Lime Rum", category: "Lime-Flavoured Rum", shortOverview: "Green Lime is a sharp citrus entry in Bacardi's India-market flavoured rum range. Plain soda preserves its lime profile better than a sweet lemon-lime soft drink.", craftStory: "Bacardi makes its rum from fermented molasses and its signature yeast before distillation, filtering and blending. Lime flavour supplies this expression's bright edge rather than wood ageing.", nose: "Lime zest and clean cane.", palate: "Light, citrus-forward and mildly sweet, with a dry lime-pith turn.", finish: "Short and zesty.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Pour 45 ml with chilled soda and a fresh lime wedge.", foodPairings: ["tandoori prawns", "cucumber chaat", "rava-fried fish", "malai paneer tikka"], whyBuyThis: "A clear lime note makes a simple rum-and-soda more aromatic.", faqs: [{ question: "Is Green Lime the same as unflavoured Bacardi Superior?", answer: "No. It is a lime-flavoured rum expression." }, { question: "What is a good mixer?", answer: "Chilled plain soda keeps the citrus distinct." }], description: "Bacardi Green Lime is zesty and light. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "bacardi-breezer-lemonade-3860194": detail({
    productName: "Bacardi Breezer Lemonade", category: "Lemon Ready-to-Drink", shortOverview: "Breezer Lemonade is a low-strength, lemon-led premix. It should be served cold as bottled rather than measured out as a full-strength rum.", craftStory: "Bacardi Breezer is the company's fruit-forward ready-to-drink family. Lemonade brings a tart citrus profile to this India-market variant, distinct from the higher-strength Bacardi Plus line.", nose: "Lemon zest and light sweetness.", palate: "Light and fizzy, with lemonade tang and soft fruit sweetness.", finish: "Short, refreshing and citrusy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve straight from a chilled bottle or over ice with mint.", foodPairings: ["tandoori prawns", "paneer tikka", "chilli-lime corn", "spiced roasted peanuts"], whyBuyThis: "A tart lemon profile is easy to enjoy without extra mixing.", faqs: [{ question: "Is Breezer Lemonade plain rum?", answer: "No. It is a ready-to-drink flavoured beverage." }, { question: "Is it the same as Bacardi Plus Lemonade?", answer: "They are separate India-market premix lines; check each pack's ABV." }], description: "Bacardi Breezer Lemonade is tart and refreshing. Pair with chilli-lime corn; check city prices on BevOry."
  }),
  "bacardi-ginger-original-ginger-rum-9966cc2": detail({
    productName: "Bacardi Ginger Rum", category: "Ginger-Flavoured Rum", shortOverview: "Bacardi Ginger adds warm root spice to the house's easy-mixing rum base. Fresh lime keeps a ginger-ale highball from becoming too sweet.", craftStory: "Bacardi's heritage begins with Don Facundo Bacardí Massó's 1862 Santiago de Cuba distillery. Rum made from fermented molasses provides the base, while ginger supplies this India-market bottle's defining spice.", nose: "Fresh ginger, cane sugar and lime-like lift.", palate: "Medium-light, with ginger warmth and soft rum sweetness.", finish: "Medium, spicy and lightly warming.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled dry ginger ale and a squeeze of lime.", foodPairings: ["tandoori chicken", "mutton seekh", "spiced roasted peanuts", "paneer tikka"], whyBuyThis: "A ginger-led rum needs little more than soda for a useful highball.", faqs: [{ question: "Is Bacardi Ginger a ginger beer?", answer: "No. It is a ginger-flavoured rum meant to be measured and mixed." }, { question: "What goes well with it?", answer: "Dry ginger ale and fresh lime bring out its spice." }], description: "Bacardi Ginger has root spice and rum warmth. Pair with mutton seekh; check city prices on BevOry."
  }),
  "bacardi-bacardi-orange-ec5d4ba": detail({
    productName: "Bacardi Plus Orange", category: "Orange Rum Ready-to-Drink", shortOverview: "Bacardi Plus Orange is a chilled orange premix, not a bottle of orange-flavoured rum concentrate. The citrus is sweetest up front, with a short refreshing finish.", craftStory: "Bacardi's rum tradition uses molasses fermentation, distillation and blending. India-market Plus Orange packages the orange-and-rum combination as a ready-to-drink serve.", nose: "Sweet orange and mild citrus peel.", palate: "Light, fruity and sweet, with soft rum warmth.", finish: "Short and orange-led.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a squeeze of lime.", foodPairings: ["tandoori chicken", "paneer tikka", "chilli-lime corn", "spiced peanuts"], whyBuyThis: "Its premixed format provides a citrus drink without a separate mixer.", faqs: [{ question: "Is Bacardi Plus Orange ready to drink?", answer: "Yes. It is a premixed orange variant in the Plus range." }, { question: "Is it the same as Orange Deluxe rum?", answer: "No. Orange Deluxe is a flavoured rum for mixing." }], description: "Bacardi Plus Orange is citrusy and chilled. Pair with paneer tikka; check city prices on BevOry."
  }),
  "bacardi-orange-super-deluxe-original-orange-rum-dfd0ca3": detail({
    productName: "Bacardi Orange Super Deluxe Rum", category: "Orange-Flavoured Rum", shortOverview: "Orange Super Deluxe gives the Bacardi mixing-rum style a ripe citrus note. Its orange peel edge balances best against chilled plain soda.", craftStory: "Bacardi's core rum process ferments molasses with its house yeast before distillation. Orange flavour distinguishes this India-market rum from the company's lighter Orange Plus premix.", nose: "Ripe orange, orange peel and clean cane.", palate: "Medium-light, fruit-led and gently warming, with sweet citrus.", finish: "Short, zesty and mildly dry.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Combine 45 ml rum with chilled soda and a lime wedge.", foodPairings: ["tandoori chicken", "malai paneer tikka", "spiced roasted peanuts", "grilled pineapple"], whyBuyThis: "The stronger rum base lets orange remain clear in a long drink.", faqs: [{ question: "Is Orange Super Deluxe a premix?", answer: "No. It is an orange-flavoured rum intended for mixing." }, { question: "What mixer is least sweet?", answer: "Plain chilled soda and fresh lime." }], description: "Bacardi Orange Super Deluxe has ripe citrus and cane. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "bacardi-bacardi-lemonade-d7dc76f": detail({
    productName: "Bacardi Plus Lemonade", category: "Lemon Rum Ready-to-Drink", shortOverview: "Plus Lemonade brings lemon tang to a premixed rum drink. It is light enough for a chilled bottle serve with a small mint garnish.", craftStory: "Bacardi was founded in 1862 in Santiago de Cuba, and its rum is built from sugarcane molasses. The India-market Plus line presents Lemonade as a ready-to-drink variant rather than a full-strength citrus rum.", nose: "Lemon peel and faint cane sweetness.", palate: "Light, tart-sweet and citrus-led.", finish: "Short and refreshing.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice with fresh mint; do not add a second sweet mixer.", foodPairings: ["tandoori prawns", "chilli-lime corn", "paneer tikka", "roasted peanuts"], whyBuyThis: "Its citrus-and-rum profile is already mixed for a quick cold serve.", faqs: [{ question: "Is Plus Lemonade a flavoured rum bottle?", answer: "No. It is a ready-to-drink premix." }, { question: "Does it need dilution?", answer: "It can be served chilled without further mixing." }], description: "Bacardi Plus Lemonade is zesty and light. Pair with chilli-lime corn; check city prices on BevOry."
  }),
  "bacardi-premium-lemonade-d719cc1": detail({
    productName: "Bacardi Premium Plus Lemonade", category: "Lemon Rum Ready-to-Drink", shortOverview: "Premium Plus Lemonade is a lemon-led Bacardi premix for a simple cold serve. It keeps citrus and light rum character together in one pack.", craftStory: "Bacardi's rum base starts with fermented sugarcane molasses. India-market Plus Lemonade appears in official beverage registrations as a ready-to-drink format, separate from full-strength Limón rum.", nose: "Lemon zest and light cane.", palate: "Light-bodied and sweet-tart, with lemonade fruit and soft warmth.", finish: "Short and cleanly citrusy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a squeezed lemon wedge.", foodPairings: ["tandoori prawns", "cucumber chaat", "paneer tikka", "spiced roasted makhana"], whyBuyThis: "A premixed lemon rum drink needs no separate cordial or syrup.", faqs: [{ question: "Is Premium Plus Lemonade a sipping rum?", answer: "No. It is a lower-strength, ready-to-drink lemon premix." }, { question: "How should it be served?", answer: "Serve chilled, with ice if preferred." }], description: "Bacardi Premium Plus Lemonade is tart and citrusy. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "bacardi-bacardi-cranberry-2af6829": detail({
    productName: "Bacardi Plus Cranberry", category: "Cranberry Rum Ready-to-Drink", shortOverview: "Plus Cranberry is a fruit-tart Bacardi premix with a gentle rum base. A lime wedge adds brightness without another sweet mixer.", craftStory: "Bacardi rum begins with sugarcane molasses fermentation and distillation. The India-market Plus range bottles Cranberry as a ready-to-drink flavour, not a separately aged rum expression.", nose: "Cranberry and a hint of citrus.", palate: "Light, sweet-tart and berry-led.", finish: "Short, tangy and refreshing.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice and squeeze in fresh lime.", foodPairings: ["paneer tikka", "tandoori chicken", "chilli-lime corn", "spiced roasted peanuts"], whyBuyThis: "Cranberry tartness makes a convenient premix feel less sugary.", faqs: [{ question: "Is Plus Cranberry plain rum?", answer: "No. It is a cranberry-flavoured ready-to-drink mix." }, { question: "Can it be served without ice?", answer: "Yes. Chill the bottle well first." }], description: "Bacardi Plus Cranberry is tart and fruity. Pair with paneer tikka; check city prices on BevOry."
  }),
  "bacardi-guava-rum-6de850e": detail({
    productName: "Bacardi Guava Rum", category: "Guava-Flavoured Rum", shortOverview: "Bacardi Guava brings a recognisable tropical fruit note to a white-rum style. Fresh lime and soda keep the guava from becoming jammy.", craftStory: "Bacardi was established in Santiago de Cuba in 1862 and makes its rum base from fermented molasses. Guava flavour distinguishes this India-market mixing expression from the house's unflavoured white rum.", nose: "Ripe guava, tropical fruit and light cane.", palate: "Medium-light and fruit-led, with guava sweetness and gentle warmth.", finish: "Short, tropical and lightly tart.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled soda and 10 ml fresh lime juice.", foodPairings: ["tandoori prawns", "chilli-lime corn", "malai paneer tikka", "grilled pineapple"], whyBuyThis: "Guava offers an India-familiar fruit note without needing guava juice in the glass.", faqs: [{ question: "Is Bacardi Guava ready to drink?", answer: "No. It is a flavoured rum to measure and mix." }, { question: "Which mixer keeps it balanced?", answer: "Plain soda and fresh lime keep the fruit crisp." }], description: "Bacardi Guava has ripe tropical fruit and cane. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "breezer-jamaican-passion-d55d589": detail({
    productName: "Breezer Jamaican Passion", category: "Tropical Fruit Ready-to-Drink", shortOverview: "Jamaican Passion is a tropical-fruit Breezer made for a cold, uncomplicated serve. Its passion-fruit character has a bright tart edge against a sweeter fruit centre.", craftStory: "Breezer is Bacardi's fruit-forward ready-to-drink range. Jamaican Passion is part of its India-market flavour selection; the name describes the drink's tropical profile rather than a Jamaican distillation origin.", nose: "Passion fruit and ripe tropical fruit.", palate: "Light and sweet-tart, with passion-fruit tang and a soft fruity middle.", finish: "Short, juicy and lightly tangy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve straight from a chilled bottle or pour over ice with lime.", foodPairings: ["tandoori prawns", "chilli-lime corn", "paneer tikka", "spiced roasted peanuts"], whyBuyThis: "Tropical tang makes this a ready-made alternative to mixing a fruit cocktail.", faqs: [{ question: "Is Jamaican Passion a full-strength rum?", answer: "No. It is a ready-to-drink flavoured beverage; check the bottle for its ABV." }, { question: "Does the name mean it is distilled in Jamaica?", answer: "No. Jamaican Passion is the flavour name, not a stated production origin." }], description: "Breezer Jamaican Passion has tropical fruit and a tart edge. Pair with chilli-lime corn; check city prices on BevOry."
  }),
  "breezer-blackberry-5f13af6": detail({
    productName: "Breezer Blackberry Crush", category: "Blackberry Ready-to-Drink", shortOverview: "Blackberry Crush is a berry-led Breezer with a darker fruit character than the citrus flavours. Serve it thoroughly chilled so its sweet-and-tart balance stays lively.", craftStory: "Bacardi's Breezer range packages fruit-forward, ready-to-drink serves. Blackberry Crush is one of the range's listed flavour expressions, presented as a premix rather than a bottle of standalone rum.", nose: "Blackberry and a light berry-candy note.", palate: "Light-bodied, sweet and mildly tart, with dark-berry flavour.", finish: "Short, fruity and refreshing.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice and add a small squeeze of lemon to sharpen the berry note.", foodPairings: ["tandoori chicken", "paneer tikka", "spiced roasted makhana", "grilled pineapple"], whyBuyThis: "Its distinct dark-berry note works without extra juice or syrup.", faqs: [{ question: "Is Blackberry Crush plain rum?", answer: "No. It is a flavoured ready-to-drink beverage." }, { question: "Can it be served from the bottle?", answer: "Yes. Chill it well first; ice is optional." }], description: "Breezer Blackberry Crush is sweet-tart and berry-led. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "breezer-cranberry-80ef6dd": detail({
    productName: "Breezer Tangy Cranberry", category: "Cranberry Ready-to-Drink", shortOverview: "Tangy Cranberry is a Breezer built around cranberry's familiar sweet-sour character. A cold serve and fresh lime bring out its sharper side.", craftStory: "Breezer is Bacardi's fruit-led premix family. Tangy Cranberry is a named variant in that range, intended for drinking chilled rather than being used as a concentrated cocktail spirit.", nose: "Cranberry and faint citrus.", palate: "Light, sweet-tart and cranberry-forward.", finish: "Short and pleasantly tangy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a lime wedge; avoid adding sweet juice.", foodPairings: ["paneer tikka", "tandoori chicken", "chilli-lime corn", "roasted peanuts"], whyBuyThis: "Cranberry acidity gives the premix a crisp fruit finish.", faqs: [{ question: "Is Breezer Cranberry a wine?", answer: "No. It is a fruit-flavoured ready-to-drink beverage." }, { question: "How should it be served?", answer: "Chill the bottle thoroughly and pour over ice if preferred." }], description: "Breezer Tangy Cranberry is crisp and sweet-tart. Pair with paneer tikka; check city prices on BevOry."
  }),
  "breezer-blueberry-7e9459c": detail({
    productName: "Breezer Tasty Blueberry", category: "Blueberry Ready-to-Drink", shortOverview: "Tasty Blueberry is a sweet berry expression in Breezer's ready-to-drink line. Its soft fruit profile suits a cold serve rather than a complex mixer.", craftStory: "Bacardi's Breezer range offers pre-mixed fruit flavours. Tasty Blueberry is a separately named variant in the producer's range, with blueberry as its defining taste cue.", nose: "Blueberry and sweet mixed berries.", palate: "Light and smooth, with blueberry sweetness and mild fruit tang.", finish: "Short, berry-sweet and clean.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Chill well and pour over ice with a lemon wedge for contrast.", foodPairings: ["malai paneer tikka", "spiced roasted makhana", "grilled pineapple", "chilli-lime corn"], whyBuyThis: "A straightforward blueberry premix takes no preparation beyond chilling.", faqs: [{ question: "Is Tasty Blueberry a full-strength spirit?", answer: "No. It is a ready-to-drink flavoured beverage; check the pack for ABV." }, { question: "What balances its sweetness?", answer: "A squeeze of fresh lemon adds tartness without another mixer." }], description: "Breezer Tasty Blueberry is softly sweet and berry-led. Pair with malai paneer tikka; check city prices on BevOry."
  }),
  "breezer-bacardi-breezer-watermelon-mint-287d1f2": detail({
    productName: "Bacardi Breezer Watermelon Mint", category: "Watermelon Mint Ready-to-Drink", shortOverview: "Watermelon Mint combines juicy melon sweetness with a cooling herbal note. It is a light, fruit-forward Breezer to drink cold.", craftStory: "Breezer is Bacardi's bottled ready-to-drink range. Watermelon Mint is a named flavour in the collection; the drink pairs a watermelon taste cue with a mint finish rather than calling for separate cocktail ingredients.", nose: "Fresh watermelon and mint.", palate: "Light and sweet, with juicy melon followed by a cooling mint note.", finish: "Short, fresh and gently herbal.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice with a few fresh mint leaves; do not add syrup.", foodPairings: ["cucumber chaat", "malai paneer tikka", "tandoori prawns", "chilli-lime corn"], whyBuyThis: "Melon and mint make a refreshing premix without a separate garnish kit.", faqs: [{ question: "Is Watermelon Mint a cocktail spirit?", answer: "No. It is a ready-to-drink flavoured beverage." }, { question: "Does it need a mixer?", answer: "No. Serve it chilled, with ice if desired." }], description: "Bacardi Breezer Watermelon Mint is juicy and cooling. Pair with cucumber chaat; check city prices on BevOry."
  }),
};
