// Producer evidence: docs/editorial/product-batch-45-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

type Draft = {
  n: string; c: string; o: string; craft: string; nose: string; palate: string; finish: string;
  glass: string; temp: string; serve: string; pairs: [string, string, string, string];
  why: string; question: string; answer: string;
};
const detail = (d: Draft): ProductPublicDetail => {
  const title = `${d.n} Price, Taste & Review | BevOry`;
  const shortTitle = `${d.n} Price | BevOry`;
  const description = `${d.n}: ${d.nose} Try it with ${d.pairs[0]}; check indicative city prices on BevOry.`;
  return {
    productName: d.n, category: d.c, shortOverview: d.o, craftStory: d.craft,
    tastingNotes: { nose: d.nose, palate: d.palate, finish: d.finish },
    servingGuide: { glassware: d.glass, idealTemperature: d.temp, recommendation: d.serve },
    foodPairings: d.pairs, whyBuyThis: d.why,
    faqs: [{ question: d.question, answer: d.answer }, { question: `How should I serve ${d.n}?`, answer: d.serve }],
    metaTitle: title.length <= 60 ? title : shortTitle.length <= 60 ? shortTitle : `${d.n.slice(0, 36)} Price | BevOry`,
    metaDescription: description.length <= 155 ? description : `${d.n}: tasting notes, Indian food pairings and indicative city prices on BevOry.`,
  };
};

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "allan-scott-sauvignon-blanc-81add44": detail({
    n: "Allan Scott Sauvignon Blanc", c: "Marlborough Sauvignon Blanc Wine", o: "This Marlborough white is vivid with tropical fruit and green herbs. Its sharp acidity cuts through rich or fried starters without making the wine feel thin.", craft: "Allan Scott planted vines in Marlborough, New Zealand, in the 1970s and built a family wine estate there. Cool nights and careful picking preserve Sauvignon Blanc's passion-fruit, capsicum and herb character; the precise balance shifts with each harvest.", nose: "Passion fruit, guava, red capsicum and fresh dill.", palate: "Dry and brisk, moving from tropical fruit to lime and green herbs.", finish: "Medium-long, zesty and clean.", glass: "White-wine glass", temp: "Chilled (8–10°C)", serve: "Serve cool, not ice-cold, with fish or coriander (dhania)-led chutney.", pairs: ["rava-fried fish", "tandoori prawns", "cucumber chaat", "malai paneer tikka"], why: "It captures Marlborough's exuberant aromatics while retaining food-friendly acidity.", question: "Is Allan Scott Sauvignon Blanc sweet?", answer: "No. Its tropical aroma is expressive, but the palate is dry and crisp."
  }),
  "alta-vista-malbec-2020-2bebd1a": detail({
    n: "Alta Vista Malbec 2020", c: "Argentine Malbec Red Wine", o: "Alta Vista's 2020 Malbec offers ripe plum and cherry with a savoury spice edge. Medium-to-full body makes it a useful red for grilled and tandoori food.", craft: "Count Patrick d'Aulan founded Alta Vista in Argentina, bringing French winemaking experience to Mendoza's high-altitude vineyards. The 2020 Malbec draws its fruit from the region's sunny days and cool nights; exact oak use depends on the named Alta Vista range on the bottle.", nose: "Black plum, violet and dark cherry.", palate: "Rounded and fruit-led, with blackberry, modest tannin and pepper spice.", finish: "Medium, with dark fruit and a dry cocoa note.", glass: "Bordeaux red-wine glass", temp: "Slightly cool (16–18°C)", serve: "Open 20 minutes before dinner and pour slightly below room temperature.", pairs: ["mutton ghee roast", "tandoori chicken", "lamb chops", "aged cheddar"], why: "The 2020 vintage gives a practical entry into Mendoza Malbec's ripe but structured style.", question: "Does Alta Vista Malbec 2020 need chilling?", answer: "A slight chill to around 16–18°C keeps its fruit fresh and tannins balanced."
  }),
  "bollinger-special-brut-cuvee-d79ab9f": detail({
    n: "Bollinger Special Cuvée Brut", c: "Non-Vintage Brut Champagne", o: "Bollinger Special Cuvée has unusually broad shoulders for a non-vintage Champagne. Roasted apple and brioche sit behind fine bubbles and a dry, persistent finish.", craft: "The Aÿ house blends 60% Pinot Noir with Chardonnay and Meunier, drawing heavily on reserve wines, some held in magnum. Extended cellar ageing builds its pastry-and-nut complexity without losing Champagne's acidity.", nose: "Roasted apple, peach, brioche and a touch of spice.", palate: "Creamy and structured, with pear, toasted bread and fine mousse.", finish: "Long, fresh and lightly walnut-like.", glass: "Tulip Champagne glass", temp: "Chilled (8–10°C)", serve: "Pour in a tulip glass at 8–10°C; let the first glass open for a minute.", pairs: ["tandoori prawns", "rava-fried fish", "malai paneer tikka", "mushroom risotto"], why: "Reserve-wine depth makes it a Champagne to drink throughout a meal.", question: "Is Special Cuvée a vintage Champagne?", answer: "No. Bollinger blends multiple harvests and reserve wines for a consistent house style."
  }),
  "laurent-perrier-rose-5def8d2": detail({
    n: "Laurent-Perrier Cuvée Rosé", c: "Brut Rosé Champagne", o: "Cuvée Rosé is distinctly red-fruited and dry rather than sugary pink fizz. Its Pinot Noir structure makes it more versatile with food than its delicate colour suggests.", craft: "Laurent-Perrier, founded in Tours-sur-Marne in 1812, introduced this cuvée in 1968. It macerates Pinot Noir from Champagne crus to draw colour and berry flavour before the wine's second fermentation and lees maturation.", nose: "Raspberry, wild strawberry and redcurrant.", palate: "Fine bubbles carry ripe berries over firm, fresh acidity.", finish: "Long, dry and red-fruit scented.", glass: "Tulip Champagne glass", temp: "Chilled (8–10°C)", serve: "Serve cool with a savoury course; avoid an over-frozen glass.", pairs: ["tandoori prawns", "chicken tikka", "paneer tikka", "grilled salmon"], why: "Pinot maceration gives this rosé unusually clear berry identity.", question: "Is Laurent-Perrier Cuvée Rosé sweet?", answer: "No. It is a dry rosé Champagne despite its ripe berry aromas."
  }),
  "laurent-perrier-brut-b68f410": detail({
    n: "Laurent-Perrier La Cuvée Brut", c: "Non-Vintage Brut Champagne", o: "La Cuvée is a Chardonnay-led Champagne with citrus freshness and a fine, restrained mousse. It is a lighter counterpoint to Pinot-heavy, toast-driven houses.", craft: "Laurent-Perrier in Tours-sur-Marne uses the first, purest grape pressings and a blend led by Chardonnay with Pinot Noir and Meunier. Reserve wines and extended cellar ageing bring balance while keeping the house's bright style.", nose: "Lemon, white flowers and fresh peach.", palate: "Fine and crisp, with citrus, white fruit and a soft pastry undertone.", finish: "Medium-long, clean and gently mineral.", glass: "Tulip Champagne glass", temp: "Chilled (8–10°C)", serve: "Pour at 8–10°C into a tulip flute or white-wine glass.", pairs: ["rava-fried fish", "tandoori prawns", "malai paneer tikka", "cucumber chaat"], why: "Its Chardonnay focus keeps a celebration bottle useful with delicate food.", question: "What grape leads Laurent-Perrier La Cuvée?", answer: "Chardonnay is the leading variety, supported by Pinot Noir and Meunier."
  }),
  "montes-reserva-montes-res-sauvignon-blank-dcee3ee": detail({
    n: "Montes Reserva Sauvignon Blanc", c: "Chilean Sauvignon Blanc Wine", o: "Montes Reserva is a dry white built around citrus and fresh green notes. The fruit has enough weight for seafood without hiding its brisk acidity.", craft: "Montes works with Chilean Sauvignon Blanc from the cool Aconcagua Coast, where ocean influence slows ripening. A producer technical sheet describes cold fermentation and no oak contact for the Classic Series Reserva, preserving grapefruit and white-peach character.", nose: "Grapefruit, white peach and orange blossom.", palate: "Light-bodied and lively, with citrus, pineapple and fresh acidity.", finish: "Medium-long, clean and lightly herbal.", glass: "White-wine glass", temp: "Chilled (9–11°C)", serve: "Serve cool with prawns or fish; no decanting is needed.", pairs: ["rava-fried fish", "tandoori prawns", "cucumber chaat", "lemon rice"], why: "Cool-coast fruit gives its Sauvignon Blanc a bright, precise shape.", question: "Is Montes Reserva Sauvignon Blanc oaked?", answer: "The producer's Classic Series Reserva technical sheet describes an unoaked wine."
  }),
  "montes-reserva-merlot-b9f5294": detail({
    n: "Montes Reserva Merlot", c: "Chilean Merlot Red Wine", o: "Montes Reserva Merlot has dark plum fruit and softer tannins than a forceful Cabernet. It still has enough structure for grilled meat and rich paneer dishes.", craft: "Montes sources its Classic Series Reserva Merlot from Chile's Central Valley, including Colchagua-area vineyards. The producer's 2022 sheet includes Carmenère in the blend; proportions and oak handling can change by vintage.", nose: "Black plum, cherry and a hint of dried herb.", palate: "Medium-bodied and supple, with ripe dark fruit and gentle spice.", finish: "Medium, smooth and lightly savoury.", glass: "Bordeaux red-wine glass", temp: "Slightly cool (16–18°C)", serve: "Open 15 minutes early and serve around 17°C.", pairs: ["tandoori chicken", "mutton ghee roast", "lamb chops", "paneer tikka"], why: "It supplies Merlot's soft texture without losing a useful savoury edge.", question: "Is Montes Reserva Merlot always 100% Merlot?", answer: "Not necessarily; the producer has blended a small share of Carmenère in some vintages."
  }),
  "godawan-01-rich-and-rounded-af394c3": detail({
    n: "Godawan 01 Rich and Rounded", c: "Rajasthani Indian Single Malt Whisky", o: "Godawan 01 leans towards dried fruit and caramel rather than peat smoke. Its generous texture reflects a single malt shaped by Rajasthan's hot, dry climate.", craft: "Diageo India makes Godawan from locally sourced six-row barley and matures it in Rajasthan. The producer describes a flexible cask programme and a profile of dried fruit, caramel and buttery sweetness for the 01 expression.", nose: "Raisin, caramel and a warm cereal note.", palate: "Rounded and oily, with dried fruit, toffee and gentle oak spice.", finish: "Medium-long, sweet-spiced and warming.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Taste 30 ml neat before adding a few drops of water.", pairs: ["galouti kebab", "mutton seekh kebab", "dark chocolate 70%", "badam halwa"], why: "It shows how Rajasthan's climate can give Indian single malt an opulent profile.", question: "Is Godawan 01 smoky?", answer: "Its stated identity is rich and rounded, centred on dried fruit and caramel rather than peat."
  }),
  "godawan-02-fruit-and-spicy-89e1f2d": detail({
    n: "Godawan 02 Fruit and Spice", c: "Rajasthani Indian Single Malt Whisky", o: "Godawan 02 turns towards fruit, flowers and roast-coffee spice. Compared with 01, its profile is more aromatic and brisk.", craft: "The Godawan distillery in Rajasthan uses locally sourced six-row barley and maturation suited to the desert climate. Diageo India describes 02 with rich fruit, floral notes and a touch of roasted coffee; individual bottlings may show additional cask nuances.", nose: "Orchard fruit, flowers and a trace of roasted coffee.", palate: "Medium-bodied, with ripe fruit followed by spice and dry cocoa.", finish: "Medium-long, floral and gently coffee-bitter.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Pour 30 ml neat; add a few drops of water to draw out the fruit.", pairs: ["mutton seekh kebab", "pepper paneer tikka", "roasted cashews", "dark chocolate 70%"], why: "It offers a fruitier route into Rajasthan-made single malt than the richer 01.", question: "How does Godawan 02 differ from 01?", answer: "Diageo describes 02 as fruit-and-spice led, while 01 is richer and rounder."
  }),
  "heradura-anejo-fc9b55c": detail({
    n: "Herradura Añejo", c: "Añejo Tequila", o: "Herradura Añejo balances roasted agave with wood, nuts and spice. Its long oak rest makes it a sipping tequila rather than just a Margarita base.", craft: "Casa Herradura in Jalisco makes tequila from 100% Blue Weber agave, fermented with natural yeast and double distilled. The Añejo spends 25 months in oak, well beyond the category's one-year minimum.", nose: "Roasted agave, toasted oak, almond and cinnamon.", palate: "Full and warming, with cooked agave, candied nuts and oak spice.", finish: "Long, dry and cinnamon-oaked.", glass: "Small tulip glass", temp: "Room temperature (18–20°C)", serve: "Sip 30 ml neat; a large cube is optional, but avoid sweet mixers.", pairs: ["mutton seekh kebab", "tandoori chicken", "dark chocolate 70%", "lamb chops"], why: "The extended maturation brings serious wood depth without erasing agave.", question: "How long is Herradura Añejo aged?", answer: "The producer states 25 months in oak."
  }),
  "heradura-reposado-177f3a1": detail({
    n: "Herradura Reposado", c: "Reposado Tequila", o: "Herradura Reposado sits between fresh agave and mature oak. Buttery agave, vanilla and gentle dried fruit make it comfortable neat or in a spirit-led drink.", craft: "Casa Herradura makes its 100% Blue Weber agave tequila in Jalisco through natural fermentation and double distillation. Reposado rests for 11 months in oak, giving more colour and spice than the house's Silver.", nose: "Cooked agave, vanilla and warm wood.", palate: "Rounded, with buttery agave, dried fruit and a little anise.", finish: "Medium-long, butterscotch-like and softly spiced.", glass: "Rocks glass", temp: "Room temperature or over one cube", serve: "Sip 30 ml neat or mix 45 ml into a Tommy's Margarita.", pairs: ["tandoori prawns", "mutton seekh kebab", "paneer tikka", "mushroom pepper fry"], why: "Its 11-month rest offers unusual depth for a Reposado while keeping agave visible.", question: "Is Herradura Reposado aged?", answer: "Yes. Herradura states 11 months in oak barrels."
  }),
  "heradura-plata-1cf825e": detail({
    n: "Herradura Silver", c: "Oak-Rested Silver Tequila", o: "Herradura Silver is agave-forward but less sharp than an unaged blanco. A short oak rest adds a faint vanilla note without turning it into a dark sipping tequila.", craft: "The Jalisco producer uses 100% Blue Weber agave, natural fermentation and double distillation. Its Silver rests in oak for 45 days before bottling, an important distinction from the house's unaged Blanco.", nose: "Fresh agave, green herbs and light vanilla.", palate: "Crisp and mildly sweet, with cooked agave and a touch of oak.", finish: "Short-medium, clean and peppery.", glass: "Rocks glass", temp: "Cool room temperature or over ice", serve: "Mix 45 ml with lime and grapefruit soda for a Paloma, or sip neat.", pairs: ["tandoori prawns", "cucumber chaat", "rava-fried fish", "malai paneer tikka"], why: "The brief barrel rest softens an agave-first tequila without masking its freshness.", question: "Is Herradura Silver completely unaged?", answer: "No. The producer rests it in oak for 45 days."
  }),
  "ironstone-petite-sirah-3ed3466": detail({
    n: "Ironstone Petite Sirah", c: "California Petite Sirah Red Wine", o: "Ironstone Petite Sirah is a dark, full-flavoured red with berry fruit and firm but manageable tannin. It is built for char, smoke and robust spice at the table.", craft: "The Kautz family farms vines in California's Lodi region and opened Ironstone Winery in 1990. Petite Sirah grown in warm, well-drained vineyard sites produces dense colour; oak handling and any blending component vary by vintage.", nose: "Blueberry pie, blackberry, vanilla and black pepper.", palate: "Full-bodied, with dark berry, cocoa and cedar over moderate tannins.", finish: "Long, dark-fruited and faintly peppery.", glass: "Bordeaux red-wine glass", temp: "Slightly cool (16–18°C)", serve: "Open 30 minutes before a hearty meal; use a wide red-wine glass.", pairs: ["mutton ghee roast", "lamb rogan josh", "tandoori chicken", "aged cheddar"], why: "Its depth stands up to dishes that would flatten a lighter red.", question: "Is Petite Sirah the same grape as Syrah?", answer: "No. Petite Sirah is a separate grape known for darker colour and firmer structure."
  }),
  "ironstone-pinot-noir-a374b64": detail({
    n: "Ironstone Pinot Noir", c: "California Pinot Noir Red Wine", o: "Ironstone Pinot Noir is a softer, red-fruited contrast to the winery's Petite Sirah. Cherry and gentle clove suit lighter tandoori plates.", craft: "The Kautz family's Ironstone winery works with California Pinot Noir for a lighter, more aromatic red. Careful extraction keeps this thin-skinned variety supple; vineyard source and oak proportion should be read from the vintage label.", nose: "Black cherry, raspberry and a hint of clove.", palate: "Light-medium in weight, with juicy red fruit and soft tannin.", finish: "Medium, fresh and lightly spiced.", glass: "Burgundy red-wine glass", temp: "Slightly cool (14–16°C)", serve: "Give the bottle 15 minutes in the fridge, then serve with lighter savoury dishes.", pairs: ["tandoori chicken", "mushroom pepper fry", "paneer tikka", "roast duck"], why: "It supplies red-wine flavour without the weight of a heavy Cabernet.", question: "Should Ironstone Pinot Noir be served warm?", answer: "A slight chill around 14–16°C protects its fresh cherry notes."
  }),
  "ironstone-chardonnay-21124c4": detail({
    n: "Ironstone Chardonnay", c: "California Chardonnay White Wine", o: "Ironstone Chardonnay combines orchard and tropical fruit with a modest vanilla-oak impression. It has enough roundness for creamy food while keeping a fresh line.", craft: "The Kautz family works with California Chardonnay at Ironstone Winery, established in 1990. Producer notes describe green apple, citrus and tropical fruit with oak and vanilla accents; the exact oak regime can change by vintage.", nose: "Green apple, pineapple, citrus and vanilla.", palate: "Medium-bodied and rounded, with tropical fruit, gentle oak and balanced acidity.", finish: "Medium, fresh and lightly creamy.", glass: "White-wine glass", temp: "Cool (10–12°C)", serve: "Serve cool rather than icy beside a creamy or grilled dish.", pairs: ["malai paneer tikka", "tandoori prawns", "grilled pomfret", "butter chicken"], why: "Its fruit-and-oak balance works with both seafood and creamy Indian dishes.", question: "Is Ironstone Chardonnay completely unoaked?", answer: "No. Producer notes describe vanilla and oak accents, though treatment varies by vintage."
  }),
  "kah-kah-blanco-3a57c5e": detail({
    n: "KAH Blanco Tequila", c: "Unaged Blue Weber Agave Tequila", o: "KAH Blanco keeps cooked agave and pepper at the centre of the glass. The striking skull bottle is packaging; the liquid is an unaged, 100% blue-agave tequila.", craft: "Fábrica de Tequilas Finos in the town of Tequila, Jalisco, cooks Blue Weber agave, ferments its juice and distils it twice. Blanco is bottled without oak ageing, preserving the plant's bright, spicy character.", nose: "Cooked agave, citrus peel and white pepper.", palate: "Silky at first, then distinctly peppery with sweet agave.", finish: "Medium, dry and spice-led.", glass: "Rocks glass", temp: "Cool room temperature or over ice", serve: "Sip 30 ml neat or mix 45 ml with lime in a Tommy's Margarita.", pairs: ["tandoori prawns", "cucumber chaat", "rava-fried fish", "malai paneer tikka"], why: "It delivers a clean agave-first tequila inside an unmistakable bottle.", question: "Is KAH Blanco aged in wood?", answer: "No. The producer lists its Blanco as unaged."
  }),
  "kah-kah-reposado-8319139": detail({
    n: "KAH Reposado Tequila", c: "Oak-Rested Blue Weber Agave Tequila", o: "KAH Reposado balances agave with vanilla and caramel from oak. It is richer than the Blanco without losing the plant's natural brightness.", craft: "KAH's 100% Blue Weber agave tequila is made in the town of Tequila, Jalisco. After double distillation, the Reposado rests in oak; producer information places the expression in the reposado ageing range rather than the longer Añejo period.", nose: "Cooked agave, vanilla and light caramel.", palate: "Round and softly sweet, followed by pepper, oak and agave.", finish: "Medium, warming and caramel-spiced.", glass: "Rocks glass", temp: "Room temperature or over one cube", serve: "Try 30 ml neat before using it in an oak-accented Margarita.", pairs: ["mutton seekh kebab", "paneer tikka", "tandoori prawns", "mushroom pepper fry"], why: "It adds a mellow oak layer to KAH's vivid agave base.", question: "How does KAH Reposado differ from Blanco?", answer: "Reposado spends time in oak, gaining vanilla and caramel that the unaged Blanco does not have."
  }),
  "kah-anjeo-9630257": detail({
    n: "KAH Añejo Tequila", c: "Añejo Blue Weber Agave Tequila", o: "KAH Añejo turns the brand's agave base towards chocolate, coffee and tobacco-like oak notes. This is the expression to sip slowly after dinner.", craft: "Fábrica de Tequilas Finos makes KAH from 100% Blue Weber agave in Jalisco and double distils the fermented juice. Añejo maturation in oak lasts at least one year under tequila rules, developing darker, rounder flavours than Blanco or Reposado.", nose: "Roasted agave, cocoa, coffee and toasted wood.", palate: "Full and smooth, with dark chocolate, cooked agave and oak spice.", finish: "Long, warm and cocoa-oaked.", glass: "Small tulip glass", temp: "Room temperature (18–20°C)", serve: "Sip 25–30 ml neat in a small tulip glass.", pairs: ["mutton seekh kebab", "lamb chops", "dark chocolate 70%", "almond halwa"], why: "It shows the richer, oak-developed side of the same agave spirit.", question: "Is KAH Añejo made from 100% agave?", answer: "Yes. KAH identifies its tequila range as 100% Blue Weber agave."
  }),
  "kilchoman-sanaig-2df23f4": detail({
    n: "Kilchoman Sanaig", c: "Peated Islay Single Malt Scotch Whisky", o: "Sanaig ties Islay peat smoke to dried fruit from Oloroso sherry casks. It is fuller and darker than a bourbon-led citrus-and-smoke malt.", craft: "Kilchoman distils peated malt on Islay and vats whisky matured in Oloroso sherry and bourbon casks. A high sherry-cask share builds raisin and spice without covering the distillery's citrus and peat signature.", nose: "Heather, raisins, orange peel and peat smoke.", palate: "Mouth-coating plum and cherry lead into toffee, dark chocolate and smoky oak.", finish: "Long, with caramel, clove and lingering peat.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Taste 30 ml neat; add a few drops of spring water only if needed.", pairs: ["galouti kebab", "mutton seekh kebab", "lamb rogan josh", "dark chocolate 70%"], why: "Oloroso richness and Islay peat meet without either side disappearing.", question: "Which casks shape Kilchoman Sanaig?", answer: "The producer blends Oloroso sherry and bourbon cask whisky, with strong sherry influence."
  }),
  "lillet-blanc-d442eea": detail({
    n: "Lillet Blanc", c: "French Wine-Based Aperitif", o: "Lillet Blanc is a citrus-scented wine aperitif, not a dry white wine or a spirit. Orange blossom and honey give it a soft sweetness for pre-dinner drinks.", craft: "Lillet is made in Podensac near Bordeaux from selected wines and fruit macerates. Sémillon and Sauvignon Blanc are its leading grapes; Lillet Blanc is matured in oak for a short period before blending.", nose: "Orange blossom, mint, vanilla and ripe citrus.", palate: "Soft and wine-like, with candied orange, honey and gentle bitterness.", finish: "Medium, floral and lightly pine-resinous.", glass: "Stemmed wine glass", temp: "Chilled (8–10°C)", serve: "Pour 60 ml over ice with grapefruit soda and a citrus slice.", pairs: ["cucumber chaat", "malai paneer tikka", "tandoori prawns", "fresh oysters"], why: "It provides a lower-strength, citrus-led base for an elegant aperitif.", question: "Is Lillet Blanc the same as white wine?", answer: "No. It blends wine with fruit macerates to make a flavoured aperitif."
  }),
  "lillet-rose-48f6644": detail({
    n: "Lillet Rosé", c: "French Rosé Wine-Based Aperitif", o: "Lillet Rosé is lighter and more citrus-forward than Lillet's red-fruited Rouge. A chilled spritz brings out its grapefruit and berry freshness.", craft: "Lillet created Rosé in 2011 in Podensac, using French wines and fruit macerates. Unlike Blanc, the Rosé is not given the same oak-maturation step, helping preserve its bright fruit profile.", nose: "Grapefruit, orange blossom and red berries.", palate: "Light, fruity and gently sweet with a citrus-bitter edge.", finish: "Short-medium, fresh and pink-grapefruit-like.", glass: "Stemmed wine glass", temp: "Chilled (8–10°C)", serve: "Build 60 ml over ice with grapefruit soda and a grapefruit wedge.", pairs: ["tandoori prawns", "cucumber chaat", "paneer tikka", "fruit chaat"], why: "It makes a bright aperitif without the weight of a spirit-led cocktail.", question: "Should Lillet Rosé be refrigerated after opening?", answer: "Yes. As a wine-based aperitif, it should be kept chilled after opening."
  }),
  "jim-barry-lodge-hill-riesling-wine-9ed8f11": detail({
    n: "Jim Barry Lodge Hill Riesling", c: "Clare Valley Dry Riesling Wine", o: "Lodge Hill Riesling is taut, citrus-led and dry. Its clear acidity makes it particularly good with fried fish and fresh chutneys.", craft: "Jim Barry bought Lodge Hill Vineyard in 1977 on Clare Valley's eastern ranges in South Australia. At about 480 metres, cool nights help Riesling retain acidity; gentle pressing and prompt fermentation preserve its citrus character.", nose: "Lime blossom, lemon zest and green apple.", palate: "Dry and focused, with lime, crisp apple and mineral tension.", finish: "Long, citrus-clean and lightly saline.", glass: "White-wine glass", temp: "Chilled (8–10°C)", serve: "Serve cool in a medium white-wine glass; no oak-style warming is needed.", pairs: ["rava-fried fish", "tandoori prawns", "cucumber chaat", "lemon rice"], why: "Its high-site Clare Valley fruit brings piercing freshness without sweetness.", question: "Is Lodge Hill Riesling sweet?", answer: "The house styles Lodge Hill as a crisp, dry Riesling."
  }),
  "jim-barry-assyrtiko-833e934": detail({
    n: "Jim Barry Assyrtiko", c: "Clare Valley Assyrtiko White Wine", o: "Jim Barry's Assyrtiko translates a Greek grape into a Clare Valley white with citrus and saline bite. It is leaner and more mineral than a buttery Chardonnay.", craft: "The Barry family brought Assyrtiko vine material from Santorini and planted it at Lodge Hill in South Australia in 2012. The first release followed in 2016; Clare's soils and climate give their own expression to the grape's dry, acid-driven character.", nose: "Lemon peel, white peach and sea-spray mineral notes.", palate: "Dry and linear, with citrus, stone fruit and taut acidity.", finish: "Long, saline and refreshing.", glass: "White-wine glass", temp: "Chilled (8–10°C)", serve: "Pour cool alongside coastal seafood or a lemon-forward dish.", pairs: ["rava-fried fish", "tandoori prawns", "lemon rice", "malai paneer tikka"], why: "It offers Assyrtiko's distinctive salt-and-citrus feel from an Australian vineyard.", question: "Is Jim Barry Assyrtiko made in Greece?", answer: "No. It is grown and made in South Australia's Clare Valley from Greek-origin vines."
  }),
  "gin-mare-mediterranean-gin-a0c18d3": detail({
    n: "Gin Mare Mediterranean Gin", c: "Spanish Mediterranean Gin", o: "Gin Mare is savoury rather than conventionally lemon-led. Olive, rosemary, thyme and basil make it especially comfortable beside food.", craft: "Created near Barcelona, Gin Mare treats botanicals through maceration and individual distillation before blending. Arbequina olive, rosemary, basil and thyme join juniper, citrus and coriander in its Mediterranean recipe.", nose: "Juniper, rosemary, olive and fresh basil.", palate: "Dry and rounded, with herbal warmth, citrus and a green olive edge.", finish: "Medium-long, savoury and lightly saline.", glass: "Balloon gin glass", temp: "Over ice (4–8°C)", serve: "Mix 50 ml with dry tonic, orange peel and one rosemary sprig.", pairs: ["tandoori prawns", "cucumber chaat", "rava-fried fish", "herb paneer tikka"], why: "Its olive-and-herb profile gives a gin-and-tonic the feel of a food aperitif.", question: "Does Gin Mare contain olives?", answer: "Yes. Arbequina olive is one of its signature botanicals."
  }),
  "kirin-ichiban-454b3d1": detail({
    n: "Kirin Ichiban", c: "Japanese Lager Beer", o: "Kirin Ichiban is a smooth Japanese lager built around a clean malt taste. It has a softer, creamier impression than a sharply bitter pilsner.", craft: "Kirin Brewery uses its Ichiban Shibori first-press method to take the first wort from the mash. That choice highlights barley-malt richness before fermentation and lagering produce a crisp, pale beer.", nose: "Fresh grain, light bread and gentle hops.", palate: "Smooth and lightly creamy, with malt sweetness and restrained bitterness.", finish: "Short-medium, clean and dry.", glass: "Chilled lager glass", temp: "Cold (4–6°C)", serve: "Pour into a clean glass at 4–6°C; leave room for a modest foam head.", pairs: ["chicken tikka", "vegetable pakora", "tandoori prawns", "masala peanuts"], why: "The first-press method gives it a distinct malt softness without heaviness.", question: "What does Ichiban mean in this beer?", answer: "It refers to Kirin's first-press brewing method, which uses the first wort."
  }),
  "jinro-chamisul-soju-c611c86": detail({
    n: "Jinro Chamisul Fresh Soju", c: "Korean Soju", o: "Chamisul Fresh is a light, clean soju designed for small chilled pours with food. Its neutral profile is gentler than a full-strength vodka.", craft: "Jinro makes Chamisul in South Korea as a clear, filtered soju. The producer markets Fresh around a pure flavour and gentle aroma; its packaged strength can differ across markets and should be read from the bottle.", nose: "Very light grain and a faint sweet note.", palate: "Clean, soft and subtly sweet, without a heavy botanical or oak character.", finish: "Short, crisp and gently warming.", glass: "Small soju shot glass", temp: "Chilled (5–8°C)", serve: "Chill the bottle and pour small measures alongside shared food.", pairs: ["tandoori chicken", "paneer tikka", "spicy fried chicken", "mushroom pepper fry"], why: "Its restrained flavour lets spicy dishes remain the focus.", question: "Is Chamisul Fresh a flavoured soju?", answer: "No. Fresh is Jinro's clean original-style expression, not a fruit variant."
  }),
  "harveys-bristol-cream-9ea56f4": detail({
    n: "Harveys Bristol Cream", c: "Sweet Cream Sherry", o: "Bristol Cream is a sweet, nutty sherry with more depth than a simple dessert wine. Dried fruit and a velvety finish work with Indian sweets or blue cheese.", craft: "Harveys created Bristol Cream in 1882 by blending Jerez wines, including Fino, Amontillado, Oloroso and Pedro Ximénez. Its components age in American-oak solera systems before blending to a rich but balanced style.", nose: "Walnut, raisin, caramel and dried orange.", palate: "Full and silky, with dried figs, toffee and a balancing acidity.", finish: "Long, mellow and nutty.", glass: "Small white-wine glass", temp: "Chilled (10–12°C)", serve: "Serve chilled in a wine glass, or pour 60 ml over ice with orange peel.", pairs: ["gajar ka halwa", "dark chocolate 70%", "blue cheese", "almond cake"], why: "A multi-style solera blend makes a classic sweet sherry with more than just sugar.", question: "Is Harveys Bristol Cream a dairy cream drink?", answer: "No. Cream sherry describes a sweet wine style; it contains no dairy cream."
  }),
  "lustau-deluxe-cream-capataz-andres-sherry-1ffb404": detail({
    n: "Lustau Deluxe Cream Capataz Andrés", c: "Sweet Cream Sherry", o: "Capataz Andrés joins nutty Oloroso with raisiny Pedro Ximénez for a concentrated but fresh sweet sherry. It is at home with dessert, blue cheese or a simple orange garnish.", craft: "Bodegas Lustau in Jerez de la Frontera ages its Oloroso and Pedro Ximénez components in separate soleras before blending. The wine honours cellar master Andrés Pérez and carries an average age of about eight years.", nose: "Dates, dried figs, raisins and smoky wood.", palate: "Silky and sweet, with dark fruit, walnut and balancing acidity.", finish: "Long, nutty and gently smoky.", glass: "Small white-wine glass", temp: "Slightly chilled (10–12°C)", serve: "Pour at 10–12°C, or over one cube with an orange slice.", pairs: ["gajar ka halwa", "dark chocolate 70%", "blue cheese", "almond cake"], why: "Its separate Oloroso and PX soleras build sweetness with real savoury depth.", question: "Which grapes are in Capataz Andrés?", answer: "Lustau identifies Palomino and Pedro Ximénez in the wine."
  }),
  "g-h-mumm-brut-e07b847": detail({
    n: "G.H. Mumm Brut", c: "Non-Vintage Brut Champagne", o: "Mumm's Brut house style is broad, fruit-led and dry. Fine bubbles and pastry notes make it useful beyond a ceremonial toast.", craft: "The Reims house blends Champagne crus with a Pinot Noir emphasis, and reserve wines add depth. Mumm's Grand Cordon expression includes fruit from more than 100 crus; the broad Brut name should be matched to the specific front label for precise blend details.", nose: "Yellow peach, honey, vanilla and a trace of pastry.", palate: "Lively and rounded, with stone fruit, citrus and fine mousse.", finish: "Long, dry and gently toasted.", glass: "Tulip Champagne glass", temp: "Chilled (8–10°C)", serve: "Serve at 8–10°C in a tulip glass beside savoury starters.", pairs: ["tandoori prawns", "rava-fried fish", "malai paneer tikka", "vegetable pakora"], why: "Its fruit-and-pastry balance is approachable without being flat.", question: "Is G.H. Mumm Brut sweet?", answer: "No. Brut denotes a dry Champagne style."
  }),
  "gunpowder-irish-gin-a4765c4": detail({
    n: "Drumshanbo Gunpowder Irish Gin", c: "Irish Botanical Gin", o: "Drumshanbo's gin combines juniper and citrus with the leafy aroma of gunpowder green tea. The tea lends freshness, not smoke or actual gunpowder.", craft: "The Shed Distillery in Drumshanbo, County Leitrim, slow-distils a botanical recipe that includes gunpowder tea and citrus. Its Irish origin and tea accent distinguish it from a straight London Dry.", nose: "Juniper, lemon peel, green tea and light spice.", palate: "Dry and aromatic, with citrus, herb and a softly tannic tea edge.", finish: "Medium-long, crisp and gently peppery.", glass: "Balloon gin glass", temp: "Over ice (4–8°C)", serve: "Mix 45 ml with dry tonic and a grapefruit slice.", pairs: ["tandoori prawns", "cucumber chaat", "rava-fried fish", "malai paneer tikka"], why: "The tea note adds an unusually refreshing layer to a juniper-led gin.", question: "Does Gunpowder Gin contain gunpowder?", answer: "No. Gunpowder is the name of a rolled green-tea style used as a botanical."
  }),
};
