// Editorial verification notes: docs/editorial/product-batch-35-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

type Entry = Omit<ProductPublicDetail, "tastingNotes" | "servingGuide" | "metaTitle" | "metaDescription"> & {
  nose: string; palate: string; finish: string; glassware: string; temperature: string; serve: string; description: string;
};
const detail = (item: Entry): ProductPublicDetail => ({
  productName: item.productName, category: item.category,
  shortOverview: item.shortOverview, craftStory: item.craftStory,
  tastingNotes: { nose: item.nose, palate: item.palate, finish: item.finish },
  servingGuide: { glassware: item.glassware, idealTemperature: item.temperature, recommendation: item.serve },
  foodPairings: item.foodPairings, whyBuyThis: item.whyBuyThis, faqs: item.faqs,
  metaTitle: `${item.productName} Price, Taste & Review | BevOry`.length <= 60
    ? `${item.productName} Price, Taste & Review | BevOry`
    : `${item.productName} Price | BevOry`.length <= 60
      ? `${item.productName} Price | BevOry`
      : item.productName.length <= 60 ? item.productName : `${item.productName.slice(0, 59)}…`,
  metaDescription: item.description,
});

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "magic-moments-magic-moment-vodka-d97c587": detail({
    productName: "Magic Moments Premium Grain Vodka", category: "Indian Grain Vodka", shortOverview: "Magic Moments is Radico Khaitan's grain-based Indian vodka, built for a clean, neutral pour. Its restrained profile leaves room for citrus, spice and Indian food rather than competing with them.", craftStory: "Launched in 2006, Magic Moments is produced by Radico Khaitan, whose Rampur distillery roots reach back to 1943. The maker identifies a triple-distillation process for its grain spirit; it is not a barrel-aged whisky or rum.", nose: "Clean cereal and a faint citrus-peel lift.", palate: "Light, smooth and largely neutral, with a little grain sweetness.", finish: "Short, crisp and gently warming.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled soda and 10 ml nimbu juice; add cucumber if desired.", foodPairings: ["tandoori prawns", "malai paneer tikka", "cucumber chaat", "rava-fried fish"], whyBuyThis: "A neutral Indian vodka that works with fresh mixers and spice-led snacks.", faqs: [{ question: "Is Magic Moments made from grain?", answer: "Radico Khaitan describes its vodka as grain-based and triple distilled." }, { question: "Does it need a sweet mixer?", answer: "No. Soda and fresh nimbu make a lighter highball." }], description: "Magic Moments grain vodka is clean and crisp. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "magic-moments-verve-orange-8da17ff": detail({
    productName: "Magic Moments Verve Orange", category: "Orange-Flavoured Indian Vodka", shortOverview: "Verve Orange gives Radico Khaitan's filtered vodka an orange-led citrus profile. Its ripe-fruit sweetness is best balanced with plain soda rather than another sweet mixer.", craftStory: "Magic Moments Verve joined the Radico Khaitan range in 2012. The producer describes a slow five-stage filtration with silver and platinum filters and identifies ripe orange as this expression's flavour cue.", nose: "Fresh orange peel and sweet orange flesh.", palate: "Light-bodied and smooth, with ripe citrus sweetness and a tart edge.", finish: "Short, zesty and softly sweet.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Pour 45 ml over ice, top with soda and squeeze in a little nimbu.", foodPairings: ["tandoori chicken", "paneer tikka", "chilli-lime corn", "spiced roasted peanuts"], whyBuyThis: "Orange character stays clear in a simple, unsweetened highball.", faqs: [{ question: "How is Verve different from regular Magic Moments?", answer: "Verve is the producer's more filtered premium range; this bottle adds orange flavour." }, { question: "What mixer suits it?", answer: "Plain soda and fresh nimbu keep its citrus balanced." }], description: "Verve Orange has ripe citrus and a clean finish. Pair with paneer tikka; check city prices on BevOry."
  }),
  "magic-moments-magic-moment-verv-vodka-beb7cd1": detail({
    productName: "Magic Moments Verve Vodka", category: "Premium Indian Grain Vodka", shortOverview: "Verve is the unflavoured premium expression of Magic Moments, designed for a cleaner vodka-led drink. Its light grain texture works particularly well with soda and citrus.", craftStory: "Radico Khaitan launched Verve in 2012 after establishing Magic Moments as a grain-vodka brand. The maker specifies five-stage slow filtration using silver and platinum filters for the Verve range.", nose: "Subtle grain, mineral freshness and faint citrus.", palate: "Smooth and lean, with restrained grain sweetness and a light peppery lift.", finish: "Short, dry and clean.", glassware: "Rocks glass", temperature: "Well chilled (4–7°C)", serve: "Serve 30 ml well chilled, or lengthen 45 ml with soda and nimbu.", foodPairings: ["rava-fried fish", "malai paneer tikka", "tandoori prawns", "cucumber chaat"], whyBuyThis: "Its filtered, neutral style makes fresh Indian garnishes useful rather than necessary.", faqs: [{ question: "Is Verve a flavoured vodka?", answer: "This Verve listing is the plain vodka; the brand also sells fruit-flavoured versions." }, { question: "Is it oak matured?", answer: "No oak maturation is claimed for this vodka." }], description: "Magic Moments Verve is clean and lightly grain-led. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "magic-moments-remix-lemon-grass-and-ginger-premium-flavoured-vodka-f025339": detail({
    productName: "Magic Moments Remix Lemongrass & Ginger", category: "Lemongrass Ginger Vodka", shortOverview: "Remix Lemongrass & Ginger combines citrusy herb aroma with root-spice warmth. It is a flavoured vodka for a long, lightly sweetened highball.", craftStory: "Radico Khaitan makes Magic Moments from grain with triple distillation and lists Lemongrass & Ginger among the Remix flavours. The pairing gives this bottle a distinct aromatic direction without requiring cask maturation.", nose: "Lemongrass, fresh ginger and light citrus.", palate: "Light and clean, opening herbal before ginger warmth builds.", finish: "Medium-short, citrusy and gently spicy.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with soda, a squeeze of nimbu and one bruised lemongrass stalk.", foodPairings: ["tandoori prawns", "malai paneer tikka", "coastal rava-fried fish", "chilli-lime corn"], whyBuyThis: "Ginger and lemongrass make an aromatic highball without heavy syrup.", faqs: [{ question: "Is this a premixed cocktail?", answer: "No. Remix Lemongrass & Ginger is flavoured vodka to measure into a drink." }, { question: "Does it need ginger ale?", answer: "Not necessarily; soda preserves the fresh herb note." }], description: "Remix Lemongrass & Ginger is herbal and spicy. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-verve-lemon-lush-60deab6": detail({
    productName: "Magic Moments Verve Lemon Lush", category: "Lemon-Flavoured Indian Vodka", shortOverview: "Lemon Lush is Verve's bright lemon expression, more aromatic than plain vodka. Its tart citrus profile fits chilled soda and a salty snack.", craftStory: "Radico Khaitan's Verve range uses slow five-stage filtration with silver and platinum filters. Lemon Lush belongs to its flavoured releases and has been cited by the maker in its annual product reporting.", nose: "Lemon peel and a touch of sweet citrus.", palate: "Light and brisk, with lemon tang over smooth vodka.", finish: "Short, fresh and peel-led.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Use 45 ml with chilled soda, ice and a thin nimbu wheel.", foodPairings: ["tandoori prawns", "cucumber chaat", "malai paneer tikka", "spiced roasted makhana"], whyBuyThis: "A direct lemon note gives a clean long drink without cordial.", faqs: [{ question: "Is Lemon Lush ready to drink?", answer: "No. It is a flavoured vodka, unlike the brand's premixed cocktail cans." }, { question: "What is Verve's filtration method?", answer: "Radico Khaitan describes five-stage slow filtration using silver and platinum filters." }], description: "Verve Lemon Lush is bright and tart. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "magic-moments-remix-chocolate-flavoured-vodka-35dc8c1": detail({
    productName: "Magic Moments Remix Chocolate", category: "Chocolate-Flavoured Indian Vodka", shortOverview: "Remix Chocolate brings cocoa-like sweetness to an otherwise clean vodka base. A small chilled serve is more balanced than an oversized sugary mix.", craftStory: "Radico Khaitan lists Chocolate among its Magic Moments Remix flavours. The parent grain vodka is triple distilled; chocolate character is a flavour addition, not evidence of a chocolate-based distillate.", nose: "Cocoa, milk chocolate and a little vanilla-like sweetness.", palate: "Soft and sweet-leaning, with chocolate over light vodka warmth.", finish: "Medium-short, cocoa-led and mildly warming.", glassware: "Rocks glass", temperature: "Well chilled (4–7°C)", serve: "Serve 30 ml over ice, or stir 30 ml into unsweetened chilled coffee.", foodPairings: ["70% dark chocolate", "roasted almonds", "gajar halwa", "coffee kulfi"], whyBuyThis: "Its cocoa profile makes a compact after-dinner pour possible without dessert syrup.", faqs: [{ question: "Is it chocolate liqueur?", answer: "No. The producer categorises Remix Chocolate as flavoured vodka." }, { question: "What dessert suits it?", answer: "Dark chocolate or coffee kulfi provides contrast to its sweetness." }], description: "Remix Chocolate has cocoa sweetness and vodka warmth. Pair with coffee kulfi; check city prices on BevOry."
  }),
  "magic-moments-remix-grapefruit-and-watermelon-flavoured-superior-vodka-967fc1c": detail({
    productName: "Magic Moments Remix Grapefruit & Watermelon", category: "Grapefruit Watermelon Vodka", shortOverview: "Grapefruit & Watermelon balances juicy melon against sharper citrus peel. It makes a refreshing long drink when topped with unsweetened soda.", craftStory: "Radico Khaitan lists this two-fruit flavour in its Remix vodka line. The underlying Magic Moments grain spirit undergoes triple distillation before the finished fruit profile is built.", nose: "Watermelon flesh and grapefruit peel.", palate: "Light, juicy and sweet-tart, with melon first and citrus bitterness later.", finish: "Short, cooling and faintly bitter.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with soda and a squeeze of grapefruit or nimbu.", foodPairings: ["chilli-lime corn", "tandoori prawns", "cucumber chaat", "malai paneer tikka"], whyBuyThis: "The melon-citrus contrast is more lively than a single-fruit vodka.", faqs: [{ question: "Is it a ready-to-drink can?", answer: "No. This Remix expression is flavoured vodka for mixing." }, { question: "Which mixer avoids extra sweetness?", answer: "Plain chilled soda works well." }], description: "Remix Grapefruit & Watermelon is juicy and tart. Pair with chilli-lime corn; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-dazzle-special-edition-vanilla-flavoured-vodka-4c08d01": detail({
    productName: "Magic Moments Dazzle Vanilla", category: "Madagascar Vanilla-Flavoured Vodka", shortOverview: "Dazzle Vanilla is Magic Moments' creamy, vanilla-led premium vodka. It is better treated as a small dessert-style pour than buried under sweet cola.", craftStory: "Radico Khaitan introduced Dazzle in 2021, using a seven-stage filtration sequence that includes carbon, silver, platinum and gold. The producer identifies Madagascar vanilla as the flavour source for this expression.", nose: "Vanilla pod, cream and soft grain.", palate: "Smooth and sweet-leaning, with creamy vanilla over light spirit warmth.", finish: "Medium, vanilla-led and gently warming.", glassware: "Rocks glass", temperature: "Well chilled (4–7°C)", serve: "Pour 30 ml over a large ice cube, or add a splash of unsweetened cold brew.", foodPairings: ["coffee kulfi", "70% dark chocolate", "roasted almonds", "gajar halwa"], whyBuyThis: "Producer-specified Madagascar vanilla gives a recognisable dessert note.", faqs: [{ question: "Is Dazzle Vanilla a liqueur?", answer: "It is a vanilla-flavoured vodka in the Dazzle line." }, { question: "How is Dazzle filtered?", answer: "Radico Khaitan describes a seven-stage filtration process." }], description: "Dazzle Vanilla has creamy Madagascar vanilla. Pair with coffee kulfi; check city prices on BevOry."
  }),
  "magic-moments-magic-moment-verve-green-apple-efb3cf9": detail({
    productName: "Magic Moments Verve Green Apple", category: "Green Apple-Flavoured Vodka", shortOverview: "Verve Green Apple leans toward crisp apple rather than cooked-apple sweetness. Its fresh edge suits soda and a small nimbu squeeze.", craftStory: "Radico Khaitan describes Verve as a five-stage, silver-and-platinum-filtered vodka range. Green Apple is an established flavour in that line, with the maker emphasising a freshly picked apple character.", nose: "Green apple skin and fresh-cut fruit.", palate: "Light, crisp and mildly sweet, with green-apple acidity.", finish: "Short, fresh and apple-led.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled soda and a thin apple slice.", foodPairings: ["malai paneer tikka", "tandoori prawns", "cucumber chaat", "spiced roasted makhana"], whyBuyThis: "Its sharper apple note keeps a highball from tasting syrupy.", faqs: [{ question: "Is Verve Green Apple a cider?", answer: "No. It is a green-apple-flavoured vodka." }, { question: "What mixer suits it?", answer: "Plain soda highlights the apple without more sugar." }], description: "Verve Green Apple is crisp and lightly sweet. Pair with paneer tikka; check city prices on BevOry."
  }),
  "magic-moments-magic-moment-verve-cranberry-1b31cc9": detail({
    productName: "Magic Moments Verve Cranberry", category: "Cranberry-Flavoured Vodka", shortOverview: "Verve Cranberry pairs berry tartness with a filtered vodka base. The sharper fruit note lends itself to a simple lime-and-soda serve.", craftStory: "Radico Khaitan lists Cranberry among the fruit variants of Verve. The line uses slow five-stage filtration with silver and platinum filters, distinct from the brand's lower-strength cocktail cans.", nose: "Cranberry skin and red-berry sweetness.", palate: "Light, sweet-tart and fruit-led, with clean vodka warmth.", finish: "Short, berry-tangy and dry-leaning.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with soda and 10 ml nimbu juice; avoid sweet cranberry cordial.", foodPairings: ["paneer tikka", "tandoori chicken", "chilli-lime corn", "roasted peanuts"], whyBuyThis: "Cranberry brings enough tartness for a brisk two-ingredient highball.", faqs: [{ question: "Is this a premixed drink?", answer: "No. Verve Cranberry is a flavoured vodka for measured serves." }, { question: "How does it differ from plain Verve?", answer: "It adds a cranberry fruit profile to the filtered vodka base." }], description: "Verve Cranberry is tart and berry-led. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-cocktail-mojito-79f9591": detail({
    productName: "Magic Moments Vodka Cocktail Mojito", category: "Vodka-Based Mojito Ready-to-Drink", shortOverview: "This Mojito is a vodka-based canned cocktail with lime-and-mint cues. It is a lower-strength premix, not a full-strength bottle of Magic Moments vodka.", craftStory: "Radico Khaitan introduced Magic Moments Vodka Cocktails in 2022 as a ready-to-drink range. Its launch included Mojito, Cola and Cosmopolitan; the producer stated a vodka base and 4.8% ABV for the launch cans.", nose: "Mint leaf and lime peel.", palate: "Light and sweet-tart, with lime freshness and cooling mint.", finish: "Short, cool and citrusy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold as packaged or over ice with fresh pudina and nimbu.", foodPairings: ["cucumber chaat", "malai paneer tikka", "tandoori prawns", "chilli-lime corn"], whyBuyThis: "A mint-lime cocktail profile comes ready to pour without separate ingredients.", faqs: [{ question: "Is this a rum Mojito?", answer: "No. Radico Khaitan describes its canned Mojito as vodka-based." }, { question: "Is it the same strength as bottled vodka?", answer: "No. The launch cans were specified at 4.8% ABV; read the current pack label." }], description: "Magic Moments Mojito has mint and lime in a chilled can. Pair with cucumber chaat; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-cocktail-cosmopolitan-595c434": detail({
    productName: "Magic Moments Vodka Cocktail Cosmopolitan", category: "Vodka-Based Cosmopolitan Ready-to-Drink", shortOverview: "The Cosmopolitan can gives cranberry-and-citrus character in a vodka-based premix. It is for chilled service, not for measuring as a cocktail spirit.", craftStory: "Radico Khaitan launched the Magic Moments Vodka Cocktails range in 2022 with Cosmopolitan, Cola and Mojito. The original press release specifies vodka as the alcohol base and 4.8% ABV for these cans.", nose: "Cranberry and orange-like citrus.", palate: "Light, sweet-tart and berry-led, with citrus lift.", finish: "Short, tangy and clean.", glassware: "Coupe or small tumbler", temperature: "Well chilled (4–7°C)", serve: "Chill thoroughly and pour into a small coupe, with an orange twist if available.", foodPairings: ["paneer tikka", "tandoori chicken", "spiced roasted peanuts", "chilli-lime corn"], whyBuyThis: "It offers a recognisable Cosmopolitan-style fruit balance without a shaker.", faqs: [{ question: "Is this bottled vodka?", answer: "No. It is a lower-strength ready-to-drink vodka cocktail." }, { question: "Should it be diluted?", answer: "It can be served chilled as packaged." }], description: "Magic Moments Cosmopolitan is cranberry-citrus and ready to pour. Pair with paneer tikka; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-cocktail-cola-dc38fe8": detail({
    productName: "Magic Moments Vodka Cocktail Cola", category: "Vodka Cola Ready-to-Drink", shortOverview: "The Cola can combines vodka character with familiar cola spice in a low-strength premix. A cold serve keeps the sweetness in check.", craftStory: "Radico Khaitan introduced its Magic Moments Vodka Cocktails in 2022 as canned ready-to-drink beverages. Cola was one of the three launch flavours, alongside Mojito and Cosmopolitan, with a stated 4.8% ABV at launch.", nose: "Cola spice, caramel and citrus-like lift.", palate: "Light, sweet and cola-led, with gentle spirit warmth.", finish: "Short, sweet-spiced and refreshing.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour over ice with a nimbu wedge; do not add more cola.", foodPairings: ["tandoori chicken", "mutton seekh", "spiced roasted peanuts", "paneer tikka"], whyBuyThis: "Its premixed format makes a vodka-cola serve straightforward.", faqs: [{ question: "Is the Cola can full-strength vodka?", answer: "No. It is a lower-strength ready-to-drink cocktail." }, { question: "Does it need another mixer?", answer: "No. Chill and serve it as packaged." }], description: "Magic Moments Vodka Cocktail Cola is sweet-spiced and chilled. Pair with mutton seekh; check city prices on BevOry."
  }),
  "magic-moments-jamun-spicy-mint-ac6a58d": detail({
    productName: "Magic Moments Jamun SpicyMint", category: "Jamun Mint-Flavoured Indian Vodka", shortOverview: "Jamun SpicyMint layers tart Indian jamun with cooling mint and a small spice kick. The fruit-herb profile fits soda better than a sweet juice mixer.", craftStory: "Radico Khaitan announced Jamun SpicyMint in 2025 for its Flavours of India range. The company's launch description specifically identifies jamun, mint and spice, building on the Magic Moments grain-vodka line.", nose: "Ripe jamun, crushed mint and gentle spice.", palate: "Medium-light, tart-fruited and cooling before a warm spice turn.", finish: "Medium-short, minty and tangy.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Use 45 ml with chilled soda, 10 ml nimbu juice and one mint sprig.", foodPairings: ["aloo chaat", "paneer tikka", "chilli-lime corn", "tandoori chicken"], whyBuyThis: "Jamun gives this vodka a distinctly Indian tart-fruit direction.", faqs: [{ question: "What is jamun?", answer: "Jamun is the Indian black plum; it provides the fruit cue in this vodka." }, { question: "Is it a ready-to-drink can?", answer: "No. It is a flavoured vodka intended for measured serves." }], description: "Magic Moments Jamun SpicyMint is tangy, minty and gently spiced. Pair with aloo chaat; check city prices on BevOry."
  }),
  "magic-moments-magic-moment-green-apple-39ea7dc": detail({
    productName: "Magic Moments Green Apple Vodka", category: "Green Apple-Flavoured Indian Vodka", shortOverview: "Remix Green Apple puts a crisp fruit note into Magic Moments' original flavoured range. It is a vodka to mix, not a bottled apple cider.", craftStory: "Radico Khaitan's grain-based Magic Moments vodka is triple distilled. The producer lists Green Apple among its flavoured vodka expressions, alongside the more heavily filtered Verve line.", nose: "Green apple peel and fresh orchard fruit.", palate: "Light and clean, with sweet apple followed by tart skin.", finish: "Short, fruity and mildly sharp.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with soda and a thin nimbu wheel.", foodPairings: ["malai paneer tikka", "cucumber chaat", "tandoori prawns", "spiced roasted makhana"], whyBuyThis: "Its lively apple note works with a simple dry mixer.", faqs: [{ question: "Is this the Verve bottle?", answer: "This listing is a Magic Moments Green Apple vodka; Verve Green Apple is a separately named range." }, { question: "Does it need apple juice?", answer: "No. Chilled soda leaves the existing apple flavour clear." }], description: "Magic Moments Green Apple is crisp, fruity and lightly tart. Pair with paneer tikka; check city prices on BevOry."
  }),
  "old-monk-supreme-b2ca47c": detail({
    productName: "Old Monk Supreme XXX Rum", category: "Aged Indian Dark Rum", shortOverview: "Supreme is a darker, fuller Old Monk expression suited to a slow pour. Vanilla, cocoa and warming spice distinguish it from the lighter white rum.", craftStory: "Mohan Meakin lists Supreme XXX in its Indian rum range. The producer's wider portfolio includes this darker Supreme expression alongside Gold Reserve and The Legend.", nose: "Vanilla, cocoa, black tea and cinnamon over dark caramel.", palate: "Full and rounded, with coconut, vanilla and baking spice.", finish: "Long, warm and oak-spiced.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Sip 30 ml neat first, then try a single large ice cube.", foodPairings: ["galouti kebab", "mutton seekh", "lamb rogan josh", "70% dark chocolate"], whyBuyThis: "Its deeper cocoa-spice profile rewards slower sipping than a cola serve.", faqs: [{ question: "Is Supreme the same as Old Monk White?", answer: "No. Supreme XXX is a dark, aged-style rum; White is a clear mixing rum." }, { question: "Should it be mixed with cola?", answer: "It can be, but a neat first taste shows more of its spice and cocoa." }], description: "Old Monk Supreme has cocoa, vanilla and warm spice. Pair with galouti kebab; check city prices on BevOry."
  }),
  "old-monk-amber-mellow-and-matured-rum-120b941": detail({
    productName: "Old Monk Amber Mellow & Matured Rum", category: "Matured Indian Amber Rum", shortOverview: "Old Monk Amber sits between the brand's pale mixer and its dense dark rums. Expect mellow caramel and wood-spice character in a measured rocks pour.", craftStory: "Mohan Meakin identifies Amber as a separate Old Monk rum expression. The company's Solan roots and Mohan Nagar production history remain part of the brand's identity.", nose: "Caramel, vanilla and gentle toasted wood.", palate: "Medium-bodied, rounded and softly sweet, with spice emerging late.", finish: "Medium, warming and lightly woody.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Try 30 ml neat before adding one cube of ice.", foodPairings: ["mutton seekh", "tandoori chicken", "roasted cashews", "70% dark chocolate"], whyBuyThis: "A mellow amber profile offers a bridge from highball rum to sipping rum.", faqs: [{ question: "Is Amber the same as White Rum?", answer: "No. Amber is a separate, darker expression." }, { question: "Does every Amber bottle have a 20-year statement?", answer: "Pack names differ by market; read the exact local label for any age claim." }], description: "Old Monk Amber has mellow caramel and wood spice. Pair with mutton seekh; check city prices on BevOry."
  }),
  "old-monk-white-rum-4abf892": detail({
    productName: "Old Monk White Rum", category: "Indian White Rum", shortOverview: "Old Monk White is the clear, cocktail-oriented member of the range. Its lighter body lets lime, mint and tropical fruit remain prominent.", craftStory: "Mohan Meakin lists White Rum separately from its dark Old Monk expressions. The authorised export distributor describes a clear spirit with coconut and vanilla notes, although local bottlings may differ in pack details.", nose: "Light coconut, vanilla and soft cane.", palate: "Light to medium-bodied, clean and slightly sweet, with coconut-spice hints.", finish: "Short to medium, gentle and lightly warming.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Make a simple Daiquiri with 45 ml rum, 20 ml nimbu juice and 10 ml sugar syrup.", foodPairings: ["tandoori prawns", "rava-fried fish", "malai paneer tikka", "cucumber chaat"], whyBuyThis: "Its clear, light profile is more useful in citrus cocktails than the brand's dark rums.", faqs: [{ question: "Is Old Monk White a dark rum?", answer: "No. It is the brand's clear white-rum expression." }, { question: "What classic cocktail suits it?", answer: "A lime-led Daiquiri is a good starting point." }], description: "Old Monk White has light coconut and vanilla. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "old-monk-lemon-rum-e5e70bf": detail({
    productName: "Old Monk Lemon Rum", category: "Lemon-Flavoured Indian Rum", shortOverview: "Old Monk Lemon adds a clear citrus cue to the company's rum range. Plain soda and fresh nimbu make a sharper serve than sweet lemonade.", craftStory: "Mohan Meakin's published rum range includes Old Monk Lemon alongside its white, dark and other fruit-flavoured rums. The lemon profile is a flavour expression, not a separate citrus distillate or cask finish.", nose: "Lemon peel, light cane and mild sweet spice.", palate: "Medium-light, citrus-led and sweet-tart over rum warmth.", finish: "Short, zesty and gently warming.", glassware: "Highball glass", temperature: "Cold over ice", serve: "Mix 45 ml with chilled soda and a fresh nimbu wedge.", foodPairings: ["tandoori prawns", "paneer tikka", "chilli-lime corn", "rava-fried fish"], whyBuyThis: "It brings citrus directly into a rum highball without cordial.", faqs: [{ question: "Is Old Monk Lemon a premixed drink?", answer: "No. Mohan Meakin lists it as a lemon-flavoured rum." }, { question: "What mixer avoids excess sweetness?", answer: "Plain soda and a fresh nimbu wedge." }], description: "Old Monk Lemon is citrus-led and lightly spiced. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "old-monk-very-old-vatted-old-monk-rum-e5f515a": detail({
    productName: "Old Monk Very Old Vatted Rum", category: "Indian Dark Vatted Rum", shortOverview: "Very Old Vatted represents Old Monk's classic dark-rum style, with caramel depth and warm spice. It is a useful reference point for comparing the brand's premium expressions.", craftStory: "Mohan Meakin's annual reports identify Very Old Vatted Old Monk among its rum products. The vatted style brings matured rum components together for a consistent dark-rum profile.", nose: "Dark caramel, vanilla and a little molasses.", palate: "Rounded and sweet-spiced, with cocoa and toasted-sugar depth.", finish: "Medium, warming and caramel-led.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Try 30 ml neat, then add a few drops of water or one large ice cube.", foodPairings: ["mutton seekh", "galouti kebab", "roasted peanuts", "70% dark chocolate"], whyBuyThis: "It shows the familiar dark Old Monk profile without a flavoured-rum overlay.", faqs: [{ question: "What does vatted mean?", answer: "It refers to combining rum components into a consistent finished blend." }, { question: "Does Very Old mean a fixed age?", answer: "No fixed age is stated by the name alone; check the exact pack." }], description: "Old Monk Very Old Vatted has caramel and warm spice. Pair with mutton seekh; check city prices on BevOry."
  }),
  "old-monk-the-legend-409bb08": detail({
    productName: "Old Monk The Legend Rum", category: "Premium Indian Dark Rum", shortOverview: "The Legend is a deeper, slower-sipping Old Monk than the standard mixing bottle. Burnt caramel, tobacco-like aroma and dark chocolate make it food-friendly after dinner.", craftStory: "Mohan Meakin lists The Legend as a distinct rum in its portfolio. Its deeper dark-rum style sits apart from the company's standard XXX and White expressions.", nose: "Burnt caramel, tobacco leaf and dark wood.", palate: "Full and smooth, with vanilla, dark chocolate and caramel.", finish: "Long, warming and softly oaky.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Sip 25–30 ml neat; add a few drops of water if the spirit feels closed.", foodPairings: ["galouti kebab", "lamb rogan josh", "mutton seekh", "70% dark chocolate"], whyBuyThis: "Its caramel-and-chocolate depth merits a neat comparison with other Old Monk rums.", faqs: [{ question: "Is The Legend a white rum?", answer: "No. It is a dark, premium Old Monk expression." }, { question: "Is every Indian bottle 21 years old?", answer: "The export distributor cites 21 years for its market; check the local label before applying that age elsewhere." }], description: "Old Monk The Legend has burnt caramel and dark chocolate. Pair with galouti kebab; check city prices on BevOry."
  }),
  "old-monk-gold-reserve-dark-rum-7a9bc25": detail({
    productName: "Old Monk Gold Reserve Dark Rum", category: "Indian Dark Reserve Rum", shortOverview: "Gold Reserve is a darker, rounded Old Monk expression with toffee and spice. It sits closer to the brand's sipping rums than its fruit-flavoured releases.", craftStory: "Mohan Meakin names Gold Reserve in its official Old Monk rum portfolio and annual reports. It is bottled as a separate reserve expression alongside the company's XXX and Supreme rums.", nose: "Toffee, vanilla and dark sugar with a little oak spice.", palate: "Medium-full and mellow, with caramel, dried fruit and warm spice.", finish: "Medium-long, sweet-spiced and gently woody.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Pour 30 ml neat or over one large cube; let it rest briefly in the glass.", foodPairings: ["mutton ghee roast", "galouti kebab", "roasted cashews", "70% dark chocolate"], whyBuyThis: "A reserve-style Old Monk for drinkers seeking more depth than a basic rum-cola.", faqs: [{ question: "Is Gold Reserve flavoured with lemon?", answer: "No. It is a separate dark-rum expression." }, { question: "Must it be mixed?", answer: "No. A small neat or rocks pour is a sensible first taste." }], description: "Old Monk Gold Reserve has toffee and warm spice. Pair with mutton ghee roast; check city prices on BevOry."
  }),
  "old-monk-xxx-7595b9e": detail({
    productName: "Old Monk XXX Rum", category: "Indian Dark XXX Rum", shortOverview: "Old Monk XXX is the dark-rum reference point for the label: sweet caramel, vanilla and spice. It can be tried neat before the familiar cola highball.", craftStory: "Mohan Meakin lists XXX Rum among its core expressions and has produced Old Monk under its long-established Indian spirits business. Dark rum in this style gains its profile from blended rum and maturation rather than a fruit flavour addition.", nose: "Caramel, vanilla and molasses with soft spice.", palate: "Rounded, sweet and medium-bodied, with cocoa and toasted sugar.", finish: "Medium, warming and caramel-led.", glassware: "Rocks glass", temperature: "Room temperature (18–20°C)", serve: "Try 30 ml neat, or mix 45 ml with cola and a squeeze of nimbu.", foodPairings: ["mutton seekh", "tandoori chicken", "spiced roasted peanuts", "70% dark chocolate"], whyBuyThis: "The classic dark-rum profile works both as a small sipping pour and in a highball.", faqs: [{ question: "Is XXX the same as White Rum?", answer: "No. XXX is a dark expression; White is a clear mixing rum." }, { question: "What is a simple mixer?", answer: "Cola with nimbu is common, while soda keeps it less sweet." }], description: "Old Monk XXX has caramel, vanilla and spice. Pair with mutton seekh; check city prices on BevOry."
  }),
  "old-monk-coffee-extra-ordinary-xo-coffee-flavoured-premium-rum-4a88a93": detail({
    productName: "Old Monk XO Coffee Rum", category: "Coffee-Flavoured Indian Rum", shortOverview: "XO Coffee adds roasted-bean character to Old Monk's rum warmth. Its coffee-and-chocolate direction is suited to a small after-dinner pour.", craftStory: "Mohan Meakin lists Coffee Rum in its Old Monk portfolio. Coffee, vanilla and chocolate define this flavoured expression within the wider rum range.", nose: "Roasted coffee beans, vanilla and dark chocolate.", palate: "Rounded and gently sweet, with coffee, cocoa and rum warmth.", finish: "Long, coffee-led with a faint citrus turn.", glassware: "Rocks glass", temperature: "Slightly cool (14–18°C)", serve: "Sip 25–30 ml neat or over one large ice cube; avoid sweet coffee syrup.", foodPairings: ["coffee kulfi", "70% dark chocolate", "roasted almonds", "gajar halwa"], whyBuyThis: "Coffee character gives an Old Monk pour a clear after-dinner role.", faqs: [{ question: "Is XO Coffee a coffee liqueur?", answer: "Mohan Meakin markets it as a coffee-flavoured rum." }, { question: "Does XO confirm an age?", answer: "No specific age follows from the name alone; use the bottle label for that." }], description: "Old Monk XO Coffee has roasted beans, vanilla and cocoa. Pair with coffee kulfi; check city prices on BevOry."
  }),
  "tuborg-strong-beer-e85ff90": detail({
    productName: "Tuborg Strong Beer", category: "Indian Strong Lager", shortOverview: "Tuborg Strong is the brand's bolder India-market lager, fuller than its lighter Green beer. Grain sweetness and firm carbonation make it best served properly cold.", craftStory: "Tuborg was founded by Philip W. Heyman at Hellerup near Copenhagen and became part of Carlsberg's beer group. Carlsberg India dates Tuborg Strong's local launch to 2010 and identifies it as a lager brewed for the Indian market.", nose: "Malted grain, light bread and a grassy hop edge.", palate: "Medium-bodied and lively, with grain sweetness, mild hop bitterness and firm bubbles.", finish: "Medium-short, malty and gently bitter.", glassware: "Chilled lager glass", temperature: "Cold (4–7°C)", serve: "Pour down the side of a clean glass, then straighten for a small foam head; do not freeze the bottle.", foodPairings: ["tandoori chicken", "chilli-lime corn", "mutton seekh", "spiced roasted peanuts"], whyBuyThis: "A fuller lager with enough body for grilled, spicy food.", faqs: [{ question: "Is Tuborg Strong a lager?", answer: "Yes. Carlsberg India identifies it as a lager." }, { question: "Is its ABV the same worldwide?", answer: "No. Strength can differ by market; use the local pack label." }], description: "Tuborg Strong has malt, lively bubbles and a bitter edge. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "breezer-lemon-iced-tea-flv-2d22967": detail({
    productName: "Breezer Lemon Iced Tea", category: "Lemon Tea Ready-to-Drink", shortOverview: "Lemon Iced Tea brings tea-like softness and lemon tang to a cold Breezer premix. Its mellow citrus profile is distinct from the sharper Lemonade expression.", craftStory: "Breezer is Bacardi's fruit-forward ready-to-drink family. The official global range includes Lemony Iced Tea as a separate flavour, designed for chilled service rather than spirit-strength mixing.", nose: "Lemon peel and light black-tea aroma.", palate: "Light and sweet-tart, with iced-tea softness behind the lemon.", finish: "Short, cool and lightly tea-like.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a nimbu wheel; avoid adding sugar syrup.", foodPairings: ["malai paneer tikka", "chilli-lime corn", "rava-fried fish", "spiced roasted makhana"], whyBuyThis: "Tea softness gives this lemon premix a different finish from plain citrus Breezer.", faqs: [{ question: "Is it an unflavoured tea drink?", answer: "No. It is a lemon-iced-tea-flavoured alcoholic premix." }, { question: "Does it need a mixer?", answer: "No. Chill and serve it as bottled." }], description: "Breezer Lemon Iced Tea is mellow and citrusy. Pair with paneer tikka; check city prices on BevOry."
  }),
  "breezer-mango-peach-a47ae45": detail({
    productName: "Breezer Mango Peach", category: "Mango Peach Ready-to-Drink", shortOverview: "Mango Peach combines the lush fruit character of aam with softer stone-fruit sweetness. Serve it cold enough to retain a fresh finish.", craftStory: "Breezer is Bacardi's ready-to-drink fruit range, which includes mango and peach flavours internationally. The local Mango Peach listing names both fruits; its bottle label remains the authority for formulation and strength.", nose: "Ripe mango and peach skin.", palate: "Light, juicy and sweet, with mango up front and peach softness behind.", finish: "Short, tropical and gently tangy.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Pour cold over ice and add a squeeze of nimbu to cut sweetness.", foodPairings: ["tandoori prawns", "chilli-lime corn", "malai paneer tikka", "spiced roasted peanuts"], whyBuyThis: "Two familiar fruit notes make a ready-made warm-weather serve.", faqs: [{ question: "Is Mango Peach a bottle of rum?", answer: "No. It is a fruit-flavoured ready-to-drink beverage." }, { question: "How can it taste less sweet?", answer: "Serve it very cold with fresh nimbu; avoid extra juice." }], description: "Breezer Mango Peach is juicy and tropical. Pair with chilli-lime corn; check city prices on BevOry."
  }),
  "breezer-juniper-and-lime-20dee82": detail({
    productName: "Breezer Juniper & Lime", category: "Juniper Lime Ready-to-Drink", shortOverview: "Juniper & Lime is a drier-tasting Breezer direction, with pine-like herb and sharp citrus cues. It is a bottled premix, not gin that needs tonic.", craftStory: "The official Breezer product range identifies Juniper Lime among its flavours. Bacardi positions the line as ready-to-drink fruit beverages, so the juniper note should not be confused with a declared gin distillation.", nose: "Lime zest and a light pine-like juniper note.", palate: "Light, citrus-led and mildly herbal, with restrained sweetness.", finish: "Short, zesty and lightly aromatic.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a thin lime or nimbu wheel.", foodPairings: ["tandoori prawns", "cucumber chaat", "malai paneer tikka", "rava-fried fish"], whyBuyThis: "Its juniper-citrus contrast appeals to drinkers who find sweeter fruit premixes heavy.", faqs: [{ question: "Is this gin and tonic?", answer: "No. It is a Juniper & Lime flavoured ready-to-drink Breezer." }, { question: "Should tonic be added?", answer: "It is already a premix; serve it chilled first." }], description: "Breezer Juniper & Lime is herbal and zesty. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "breezer-watermelon-flavour-2d05ec1": detail({
    productName: "Breezer Watermelon", category: "Watermelon Ready-to-Drink", shortOverview: "Watermelon is Breezer's straight melon-flavoured premix, without the mint accent of Watermelon Mint. Its easy fruit sweetness works best with a cold serve and a touch of lime.", craftStory: "Bacardi's official Breezer range includes Watermelon as its own flavour. It is part of the bottled ready-to-drink family; the watermelon cue does not indicate a fruit-distilled spirit.", nose: "Fresh watermelon and a faint candy-fruit lift.", palate: "Light and juicy, with soft melon sweetness and mild acidity.", finish: "Short, cooling and fruit-led.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a squeeze of nimbu; do not add sweet syrup.", foodPairings: ["cucumber chaat", "chilli-lime corn", "malai paneer tikka", "tandoori prawns"], whyBuyThis: "A simple watermelon profile is easy to pair with salty, spicy snacks.", faqs: [{ question: "Is it the Watermelon Mint variant?", answer: "No. This listing is the straight Watermelon flavour." }, { question: "Does it need dilution?", answer: "No. It is ready to drink when chilled." }], description: "Breezer Watermelon is juicy and cooling. Pair with cucumber chaat; check city prices on BevOry."
  }),
  "breezer-orange-413dfa7": detail({
    productName: "Breezer Orange", category: "Orange Ready-to-Drink", shortOverview: "Orange is a bright, sweet-citrus member of Breezer's premix range. A well-chilled bottle preserves its refreshing side better than a warm pour.", craftStory: "Bacardi's global Breezer range lists Orange as a distinct flavour. It is a ready-to-drink fruit beverage, separate from orange-flavoured full-strength rum.", nose: "Ripe orange and light peel.", palate: "Light, sweet and citrus-led, with a mild tang.", finish: "Short, clean and orange-fruited.", glassware: "Highball glass", temperature: "Well chilled (4–7°C)", serve: "Serve cold over ice with a nimbu wedge if a sharper finish is preferred.", foodPairings: ["paneer tikka", "tandoori chicken", "chilli-lime corn", "spiced roasted peanuts"], whyBuyThis: "Its familiar orange note needs no separate juice or mixer.", faqs: [{ question: "Is Breezer Orange a full-strength rum?", answer: "No. It is a flavoured ready-to-drink beverage." }, { question: "How should it be served?", answer: "Chill it well; pour over ice if desired." }], description: "Breezer Orange has ripe citrus and a light finish. Pair with paneer tikka; check city prices on BevOry."
  }),
};
