// Producer references and catalogue-identity cautions: docs/editorial/product-batch-43-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

type Draft = {
  name: string; category: string; overview: string; craft: string;
  nose: string; palate: string; finish: string; glass: string; temperature: string;
  serve: string; pairings: [string, string, string, string]; why: string;
  questions: [{ question: string; answer: string }, { question: string; answer: string }];
  shortTitle?: string;
};
const detail = (d: Draft): ProductPublicDetail => {
  const fullTitle = `${d.name} Price, Taste & Review | BevOry`;
  const priceTitle = `${d.name} Price | BevOry`;
  const description = `${d.name}: ${d.nose} Pair with ${d.pairings[0]}; compare city prices on BevOry.`;
  return {
    productName: d.name, category: d.category, shortOverview: d.overview, craftStory: d.craft,
    tastingNotes: { nose: d.nose, palate: d.palate, finish: d.finish },
    servingGuide: { glassware: d.glass, idealTemperature: d.temperature, recommendation: d.serve },
    foodPairings: d.pairings, whyBuyThis: d.why, faqs: d.questions,
    metaTitle: fullTitle.length <= 60 ? fullTitle : priceTitle.length <= 60 ? priceTitle : d.shortTitle ?? `${d.name.slice(0, 36)} Price | BevOry`,
    metaDescription: description.length <= 155 ? description : `${d.name}: tasting notes, food pairings and city prices on BevOry.`,
  };
};

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "anakena-birdman-merlot-4c083a5": detail({
    name: "Anakena Birdman Merlot", category: "Chilean Merlot Red Wine", overview: "Birdman Merlot is a medium-bodied Chilean red that puts blackberry fruit ahead of firm tannin. It is a comfortable pour for a table mixing grilled vegetables and meat.", craft: "Anakena traces its roots to Alto Cachapoal at the foot of the Chilean Andes. Birdman takes its name from the Tangata Manu figure of Rapa Nui; the producer describes this Merlot as fruit-led rather than a heavily extracted reserve wine.", nose: "Blackberry, plum and a faint herbal lift.", palate: "Rounded and medium-bodied, with chewy dark berries and soft, measured tannin.", finish: "Medium, smooth and gently fruit-sweet.", glass: "Medium red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Pour after a brief chill in warm weather; do not serve ice-cold.", pairings: ["tandoori chicken", "mushroom pepper fry", "mutton seekh kebab", "aged cheddar"], why: "Its soft tannin makes a useful introduction to Chilean Merlot at a spicy dinner.", questions: [{ question: "Is Birdman Merlot a heavy red?", answer: "No. Anakena presents it as medium-bodied and fruit-forward rather than dense or highly tannic." }, { question: "Should I decant it?", answer: "A short pour into the glass is enough for a young bottle; decant only if the specific vintage tastes closed." }]
  }),
  "anakena-birdman-cabernet-sauvignon-f030d76": detail({
    name: "Anakena Birdman Cabernet Sauvignon", category: "Chilean Cabernet Sauvignon Red Wine", overview: "A firmer Birdman red with ripe berry fruit and a more structured finish than the Merlot. It suits a barbecue plate with both char and fat.", craft: "The Anakena winery draws its identity from Chile's Andean foothills and the Birdman motif of Rapa Nui. Its Cabernet Sauvignon is described by the producer through ripe tannin, acidity and dark berry fruit; no fixed oak regime is claimed for an unspecified vintage.", nose: "Cassis, blackberry and a touch of dried herb.", palate: "Medium-full, with dark berries, fresh acidity and ripe, grippy tannin.", finish: "Medium-long, with cassis skin and a dry herbal edge.", glass: "Bordeaux red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Give the wine ten minutes in the glass alongside grilled food.", pairings: ["lamb chops", "mutton ghee roast", "tandoori chicken", "pepper paneer tikka"], why: "It offers the recognisable blackcurrant-and-tannin profile of Cabernet in an approachable Chilean style.", questions: [{ question: "How is it different from Birdman Merlot?", answer: "Cabernet Sauvignon normally brings firmer tannin and a stronger cassis note; Birdman Merlot is rounder." }, { question: "Does this need food?", answer: "It can be enjoyed alone, but grilled protein or paneer softens the impression of tannin." }]
  }),
  "beronia-rioja-red-1915d89": detail({
    name: "Beronia Rioja Red", category: "Rioja Tempranillo Red Wine", overview: "Beronia's Rioja red sits in the Spanish Tempranillo tradition: cherry fruit, savoury spice and food-friendly freshness. It makes a flexible match for roasted mushrooms or char-grilled kebabs.", craft: "Beronia works in Rioja around Ollauri, where Tempranillo is the region's central red grape. Its approachable red style shows Tempranillo's cherry fruit and Rioja's savoury freshness.", nose: "Red cherry, plum skin and a light savoury spice.", palate: "Medium-bodied, with juicy red fruit, balanced acidity and a dry tannin line.", finish: "Medium, leaving cherry and a little earth.", glass: "Standard red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Serve slightly cool with a meal to sharpen its red-fruit profile.", pairings: ["chicken tikka", "lamb seekh kebab", "roasted mushrooms", "aged Manchego"], why: "It brings Rioja's savoury red-fruit character to a broad range of Indian grills.", questions: [{ question: "Is this Beronia Reserva?", answer: "Reserva is Beronia's separately named, longer-matured wine; this Rioja red is a lighter everyday style." }, { question: "What grape is typical of Beronia Rioja reds?", answer: "Tempranillo is central to the house's Rioja reds, though the exact blend depends on the bottling." }]
  }),
  "beronia-reserve-rioja-fb1d3c7": detail({
    name: "Beronia Reserva Rioja", category: "Rioja Reserva Red Wine", overview: "Reserva is Beronia's more developed Rioja red, where dark fruit meets cocoa and sweet spice. Its softer, layered texture rewards a slower meal rather than a quick chilled pour.", craft: "At Beronia in Rioja, selected older-vine grapes are fermented before extended maturation. The producer describes 18 months in mixed French and American oak followed by further bottle ageing for its Reserva; grape percentages change by vintage.", nose: "Black fruit, cinnamon and a trace of roasted hazelnut.", palate: "Rounded and medium-full, with blackberry, cacao and supple tannins.", finish: "Long, with pepper, fruit and quiet oak spice.", glass: "Bordeaux red-wine glass", temperature: "Cellar cool (16–18°C)", serve: "Open 20 minutes before dinner and pour into a broad red-wine glass.", pairings: ["galouti kebab", "lamb rogan josh", "mushroom galouti", "aged Manchego"], why: "The mature oak and dark fruit give this Rioja enough depth for richly spiced food.", questions: [{ question: "How long is Beronia Reserva aged?", answer: "The producer describes 18 months in oak and additional time in bottle; consult the vintage label for precise release details." }, { question: "Does it need decanting?", answer: "A young Reserva benefits from some air; an older bottle should be handled gently and tasted first." }]
  }),
  "altozano-tempranilo-syrah-red-5e2eb4a": detail({
    name: "Altozano Tempranillo Syrah Red", category: "Spanish Tempranillo–Syrah Red Wine", overview: "This red brings Tempranillo's cherry fruit together with Syrah's darker, peppery side. It is a lively choice for grilled tandoori food.", craft: "Finca Constancia makes the Altozano range in Castilla-La Mancha, Spain. The two varieties bring red-fruit lift and darker pepper spice to the Altozano blend.", nose: "Ripe cherry, blackberry and black pepper.", palate: "Medium-bodied and juicy, with red fruit first and a darker spicy turn.", finish: "Medium, with pepper and dry berry skin.", glass: "Standard red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Pour slightly cool beside smoky, grilled dishes.", pairings: ["tandoori chicken", "mutton seekh kebab", "smoky baingan bharta", "lamb chops"], why: "The two-grape blend balances accessible fruit with enough spice for the grill.", questions: [{ question: "Are Tempranillo and Syrah both in this bottle?", answer: "Yes, both varieties are named in this Altozano expression." }, { question: "Is it best served warm?", answer: "No. Around 16–18°C keeps the fruit clear in a warm Indian dining room." }]
  }),
  "altozano-tempranillo-cab-sau-0a02f6e": detail({
    name: "Altozano Tempranillo Cabernet Sauvignon", category: "Spanish Tempranillo–Cabernet Red Wine", overview: "Tempranillo lends red-fruit generosity while Cabernet Sauvignon adds a firmer outline. This Altozano red is more structured than the house's rosé.", craft: "Finca Constancia's estate in Castilla-La Mancha supplies both varieties for the Altozano blend. The producer's 2016 technical sheet describes selective harvest and post-fermentation oak maturation.", nose: "Black cherry, cassis and mild baking spice.", palate: "Medium-full, with dark fruit, fresh acidity and firmer Cabernet tannin.", finish: "Medium-long, with plum skin and gentle oak spice.", glass: "Bordeaux red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Let a young bottle breathe for 15 minutes before serving with dinner.", pairings: ["mutton ghee roast", "lamb chops", "paneer tikka masala", "aged cheddar"], why: "It gives a clear contrast between Spanish Tempranillo fruit and Cabernet's grip.", questions: [{ question: "Is this a single-variety Cabernet?", answer: "No. The label names both Tempranillo and Cabernet Sauvignon." }, { question: "Does every vintage use identical oak ageing?", answer: "No. Oak influence can change with vintage, while the Tempranillo–Cabernet grape pairing remains the wine's defining feature." }]
  }),
  "altozano-tempranillo-syrah-rose-e158436": detail({
    name: "Altozano Tempranillo Syrah Rosé", category: "Spanish Dry Rosé Wine", overview: "A pink Altozano wine that shifts the Tempranillo–Syrah pairing toward fresher red fruit. It belongs at a chilled lunch, not beside a heavy, long-aged red.", craft: "Finca Constancia produces Altozano in Castilla-La Mancha from estate-grown varieties. The producer's rosado technical material describes gentle colour extraction and cool fermentation; blend proportions vary by vintage.", nose: "Strawberry, red currant and a faint floral note.", palate: "Light and brisk, with red berry fruit and refreshing acidity.", finish: "Short-medium, clean and berry-led.", glass: "Rosé or white-wine glass", temperature: "Chilled (8–10°C)", serve: "Chill well, then pour with savoury snacks rather than adding ice.", pairings: ["malai paneer tikka", "tandoori prawns", "cucumber chaat", "grilled chicken kebab"], why: "It has enough red-fruit presence for snacks without the tannin of its red counterpart.", questions: [{ question: "Is this the same wine as Altozano's red blend?", answer: "No. Rosé is made for a lighter, chilled red-fruit profile." }, { question: "What temperature works best?", answer: "About 8–10°C retains freshness without muting the fruit completely." }]
  }),
  "altozano-sauvignon-blanc-a8180e1": detail({
    name: "Altozano Sauvignon Blanc", category: "Spanish Sauvignon Blanc White Wine", overview: "A crisp Altozano white centred on Sauvignon Blanc's citrus and green-herb character. It brings relief to a chilli-forward starter.", craft: "Finca Constancia grows white varieties at its Castilla-La Mancha estate. Sauvignon Blanc's citrus and herbal character shapes this fresh, food-friendly style.", nose: "Lime, green apple and freshly cut herb.", palate: "Light and zesty, with citrus acidity and a soft orchard-fruit centre.", finish: "Medium, brisk and lightly herbal.", glass: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve cool beside lime-dressed seafood or paneer.", pairings: ["rava-fried fish", "malai paneer tikka", "tandoori prawns", "cucumber chaat"], why: "Its sharp, green freshness cuts through creamy or fried starters.", questions: [{ question: "Is Altozano Sauvignon Blanc always 100% Sauvignon?", answer: "Not always; Altozano has also produced blends of Sauvignon Blanc and Verdejo." }, { question: "Should I decant this white?", answer: "No. Chill it and pour it fresh; prolonged air is not needed." }]
  }),
  "baron-philippe-cadet-doc-sauvignon-blanc-fcea57b": detail({
    name: "Baron Philippe Cadet Sauvignon Blanc", category: "French Sauvignon Blanc White Wine", overview: "A brisk French white with Sauvignon Blanc's citrus-herb signature. Its dry, clean finish is particularly useful before a richer red wine.", craft: "The Baron Philippe de Rothschild wine portfolio includes Sauvignon Blanc-led whites from Bordeaux and other French appellations. The wider range draws on French vineyard partners and prioritises freshness in its white wines.", nose: "Grapefruit, lemon leaf and green apple.", palate: "Light, dry and citrus-driven, with a cool herbal edge.", finish: "Medium and mouth-watering, leaving lime peel.", glass: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve with seafood or fresh herbs; avoid freezing the glass.", pairings: ["tandoori prawns", "coriander (dhania) chutney fish", "cucumber chaat", "malai paneer tikka"], why: "Its bright acidity makes a direct pairing with fresh, herb-led Indian food.", questions: [{ question: "Is this Mouton Cadet Blanc?", answer: "Mouton Cadet Blanc is a Bordeaux blend that can include Sauvignon Blanc and Sémillon; this entry is the Sauvignon Blanc-labelled wine." }, { question: "Does it need oak?", answer: "Oak is not what defines this wine's appeal; its citrus and herb freshness does." }]
  }),
  "baron-philippe-cadet-doc-chardonnay-014c788": detail({
    name: "Baron Philippe Cadet Chardonnay", category: "French Chardonnay White Wine", overview: "A Chardonnay-labelled French white offering more rounded orchard fruit than the Sauvignon Blanc entry. It suits gentle spice and creamy textures.", craft: "Baron Philippe de Rothschild markets varietal wines alongside its Bordeaux blends. This Chardonnay shows the rounded orchard-fruit side of the house's French varietal wines.", nose: "Yellow apple, pear and lemon zest.", palate: "Medium-bodied, softly textured, with orchard fruit and a citrus lift.", finish: "Medium, clean and gently rounded.", glass: "White-wine glass", temperature: "Cool (9–11°C)", serve: "Pour cool with mildly spiced dishes; allow a minute in the glass.", pairings: ["malai paneer tikka", "butter-garlic prawns", "lemon rice", "grilled pomfret"], why: "Its rounded Chardonnay texture meets cream and butter more comfortably than a sharp white.", questions: [{ question: "Is this definitely oaked Chardonnay?", answer: "Not necessarily. Chardonnay can be crisp and fruit-led as well as creamy; this wine is best judged by its orchard-fruit profile." }, { question: "What temperature is practical?", answer: "Around 9–11°C balances its fruit and texture." }]
  }),
  "baron-philippe-cadet-rouge-aoc-bordeaux-2018-2f00ad4": detail({
    name: "Baron Philippe Cadet Rouge Bordeaux 2018", category: "Bordeaux AOC Red Wine", overview: "A 2018 Bordeaux red from the Mouton Cadet family, built for food rather than sweetness. Dark fruit and dry tannin make it a sound match for roast or kebab.", craft: "Mouton Cadet was created by Baron Philippe de Rothschild in Bordeaux in 1930. Its red draws on Bordeaux varieties including Merlot and Cabernet Sauvignon, giving the 2018 wine fruit and dry structure.", nose: "Black cherry, plum and a faint cedar note.", palate: "Medium-bodied and dry, with dark fruit, fresh acidity and measured tannin.", finish: "Medium, with berry skin and savoury spice.", glass: "Bordeaux red-wine glass", temperature: "Cellar cool (16–18°C)", serve: "Open before dinner and taste before deciding whether to decant.", pairings: ["lamb rogan josh", "tandoori chicken", "mushroom galouti", "aged cheddar"], why: "The Bordeaux structure is useful with roasted and richly seasoned mains.", questions: [{ question: "Is the 2018 bottle identical to today's Mouton Cadet Rouge?", answer: "No. Bordeaux blends evolve with each harvest, so the 2018 release has its own character." }, { question: "Should a 2018 Bordeaux be chilled?", answer: "Serve around 16–18°C, slightly cooler than a warm room." }], shortTitle: "Cadet Rouge Bordeaux 2018 Price | BevOry"
  }),
  "baron-philippe-cadet-doc-pinot-noir-7a0b549": detail({
    name: "Baron Philippe Cadet Pinot Noir", category: "French Pinot Noir Red Wine", overview: "This Pinot Noir entry points to a lighter red-fruit style than the Bordeaux blend. It works particularly well when dinner is poultry or mushroom-led.", craft: "Baron Philippe de Rothschild's varietal portfolio extends beyond Bordeaux blending. Pinot Noir brings a lighter texture and more delicate tannin than the house's Bordeaux red blends.", nose: "Red cherry, raspberry and a light earthy note.", palate: "Light-medium, silky and dry, with red berries and fine tannin.", finish: "Medium, with cherry skin and gentle spice.", glass: "Burgundy red-wine glass", temperature: "Slightly cool (14–16°C)", serve: "A short chill helps the red fruit stay precise.", pairings: ["tandoori chicken", "mushroom pepper fry", "paneer tikka", "roast duck"], why: "Its lower tannin lets it bridge vegetarian and poultry plates.", questions: [{ question: "Is this a Burgundy Pinot Noir?", answer: "No. Baron Philippe de Rothschild's French varietal Pinot Noir is distinct from a Burgundy appellation wine." }, { question: "Can Pinot Noir be lightly chilled?", answer: "Yes. About 14–16°C usually brings out its red fruit." }]
  }),
  "baron-philippe-cadet-doc-merlot-4b991a5": detail({
    name: "Baron Philippe Cadet Merlot", category: "French Merlot Red Wine", overview: "A Merlot-labelled French red with soft plum fruit and modest tannin. It is the gentler red option beside the Cabernet-led styles in this range.", craft: "Merlot is a cornerstone of Baron Philippe de Rothschild's Bordeaux work, including Mouton Cadet blends. The grape's soft fruit character makes it a natural contrast to Cabernet-led Bordeaux reds.", nose: "Plum, black cherry and a trace of cocoa.", palate: "Medium-bodied, round and fruit-led, with supple tannin.", finish: "Medium, with plum skin and light spice.", glass: "Standard red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Serve alongside roast chicken or softer spiced mains.", pairings: ["chicken tikka", "mushroom masala", "mutton seekh kebab", "aged Gouda"], why: "Its gentle structure suits a mixed table without demanding a heavy red-meat dish.", questions: [{ question: "Is this the same as Mouton Cadet Rouge?", answer: "No. Merlot is the named grape here; Mouton Cadet Rouge is a Bordeaux blend." }, { question: "Is Merlot necessarily sweet?", answer: "No. Ripe plum flavour can appear in a dry red wine." }]
  }),
  "borsao-garnacha-5a502d3": detail({
    name: "Borsao Garnacha", category: "Campo de Borja Garnacha Red Wine", overview: "Borsao puts Aragón's Garnacha grape at the centre of an expressive, red-fruited style. Its juicy character gives it range from tapas to Indian barbecue.", craft: "Bodegas Borsao is a growers' cooperative in Campo de Borja, Aragón, a region closely identified with Garnacha. The cooperative's Garnacha wines draw their ripe red fruit from vineyards across the Campo de Borja appellation.", nose: "Raspberry, red cherry and a little dried herb.", palate: "Medium-bodied and generous, with sweet-seeming red fruit and light spice.", finish: "Medium, warm and red-fruited.", glass: "Standard red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Pour just below room temperature with smoky starters.", pairings: ["lamb seekh kebab", "tandoori chicken", "smoky baingan bharta", "Manchego"], why: "Garnacha's fruit and warmth hold up well against cumin and smoke.", questions: [{ question: "Is every Borsao Garnacha aged in oak?", answer: "No. Borsao makes youthful and matured Garnacha expressions, each with a different texture." }, { question: "Where is Borsao from?", answer: "The winery is based in Campo de Borja in Aragón, Spain." }]
  }),
  "borsao-white-90cd5c8": detail({
    name: "Borsao White", category: "Campo de Borja Spanish White Wine", overview: "A fresh white counterpart to Borsao's Garnacha-led reds. Orchard and citrus fruit make it easy to place with fried fish or paneer.", craft: "Bodegas Borsao makes white wines from Campo de Borja vineyards in Aragón. The producer's white range expresses the region's orchard fruit and bright acidity.", nose: "Green apple, white peach and lemon peel.", palate: "Light-medium, fruit-led and crisp, with citrus acidity.", finish: "Medium and clean, with orchard fruit.", glass: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Pour cold but not icy beside a lightly spiced starter.", pairings: ["rava-fried fish", "malai paneer tikka", "tandoori prawns", "lemon rice"], why: "It offers a refreshing entry into a winery better known for red Garnacha.", questions: [{ question: "Is this definitely Borsao Bolé Blanco?", answer: "Bolé Blanco is one named wine in Borsao's broader white range; this white is best explored on its own terms." }, { question: "What food suits it?", answer: "Citrus-led seafood and mild paneer dishes are practical matches." }]
  }),
  "bosio-gavi-docg-b373966": detail({
    name: "Bosio Gavi DOCG", category: "Piedmont Gavi Cortese White Wine", overview: "Gavi is Piedmont's crisp Cortese white, and Bosio's version is built around citrus and gentle flowers. It is a particularly useful alternative to a sharp Sauvignon Blanc.", craft: "Bosio Family Estates is based at Santo Stefano Belbo in Piedmont. A Bosio technical sheet identifies this Gavi as Cortese from Gavi and Tassarolo, fermented cool in steel and rested on its lees; production details can vary by vintage.", nose: "White flowers, green pear and lemon zest.", palate: "Light-medium and dry, with soft orchard fruit and lively acidity.", finish: "Medium, clean and faintly almond-like.", glass: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve at about 8°C with seafood; let the glass warm slightly at the table.", pairings: ["rava-fried fish", "tandoori prawns", "malai paneer tikka", "lemon rice"], why: "Its Cortese freshness handles coastal seafood without overpowering it.", questions: [{ question: "Which grape makes Gavi?", answer: "Gavi DOCG is made from Cortese, the grape identified in Bosio's technical sheet." }, { question: "Is Bosio Gavi oaked?", answer: "The producer sheet describes cool steel fermentation and lees contact rather than an oak-led style." }]
  }),
  "bosio-gavi-del-comune-di-gavi-0c07ce7": detail({
    name: "Bosio Gavi del Comune di Gavi", category: "Gavi del Comune di Gavi DOCG White Wine", overview: "The Comune di Gavi designation narrows the origin to the Gavi municipality. Expect a finer, stony feel beside the orchard-fruit profile of Cortese.", craft: "Bosio's Piedmont range includes Gavi wines made from Cortese. 'Del Comune di Gavi' is a geographical designation within the Gavi DOCG; no single parcel, lees duration or cask programme is assigned without a matching vintage technical sheet.", nose: "Citrus blossom, pear and wet-stone nuance.", palate: "Dry and poised, with crisp lemon, pear and a lightly saline impression.", finish: "Medium-long, clean and mineral-leaning.", glass: "Narrow white-wine glass", temperature: "Cool (9–11°C)", serve: "Serve just cool enough to retain the delicate floral aroma.", pairings: ["coastal rava-fried fish", "tandoori prawns", "cucumber chaat", "goat cheese"], why: "Its focused Cortese style offers a more place-specific route into Gavi.", questions: [{ question: "How does this differ from standard Gavi DOCG?", answer: "The Comune designation points specifically to grapes from the Gavi municipality." }, { question: "Is this a sweet white?", answer: "Gavi is generally made as a dry white; check the specific label for any exceptional style." }], shortTitle: "Bosio Comune di Gavi Price | BevOry"
  }),
  "bosio-barolo-docg-cd3671f": detail({
    name: "Bosio Barolo DOCG", category: "Piedmont Barolo Nebbiolo Red Wine", overview: "Barolo gives Bosio's range a firmly structured Nebbiolo red, quite different from its delicate Gavi. Rose, red fruit and tannin make this a wine for a substantial dinner.", craft: "Bosio Family Estates works in Piedmont and lists Barolo among its regional wines. Barolo DOCG is made from Nebbiolo and requires extended maturation, building the grape's complex aroma and tannic structure.", nose: "Dried rose, red cherry and a note of liquorice.", palate: "Dry and full, with cherry, firm tannin and savoury spice.", finish: "Long, leaving tea-like tannin and red fruit.", glass: "Large Burgundy red-wine glass", temperature: "Cellar cool (16–18°C)", serve: "Open ahead of a rich meal; assess the vintage before long decanting.", pairings: ["lamb rogan josh", "mutton seekh kebab", "mushroom galouti", "aged Parmigiano"], why: "Nebbiolo's perfume and structure reward slow, food-focused drinking.", questions: [{ question: "Which grape is in Barolo?", answer: "Barolo DOCG is made from Nebbiolo." }, { question: "Can I drink it straight after opening?", answer: "Yes, but a young bottle may benefit from air; taste before deciding how long to decant." }]
  }),
  "black-tears-dry-spiced-rum-f343563": detail({
    name: "Black Tears Dry Spiced Rum", category: "Cuban Dry Spiced Rum", overview: "Black Tears is a Cuban spiced rum with coffee and cocoa bitterness instead of a vanilla-heavy sweet profile. A little ají dulce pepper brings gentle warmth to its finish.", craft: "Made from molasses in Ciego de Ávila, Cuba, the rum uses copper-column-distilled aguardiente aged in white oak. The producer blends the matured bases before adding coffee, cocoa and Cuban ají dulce pepper.", nose: "Fresh coffee, cocoa and toasted oak.", palate: "Medium-bodied and bittersweet, with chocolate, cream and mild sweet-pepper spice.", finish: "Medium-long, with coffee and a dry pepper trace.", glass: "Rocks glass", temperature: "Room temperature or over ice (18–20°C neat)", serve: "Try 45 ml over one cube or in a Cuba Libre with 120 ml cola and fresh lime.", pairings: ["mutton seekh kebab", "dark chocolate 70%", "coffee kulfi", "masala-spiced nuts"], why: "Coffee, cocoa and ají dulce make it recognisably Cuban rather than a generic sweet spiced rum.", questions: [{ question: "Is Black Tears very sweet?", answer: "The producer presents it as a dry-spiced rum with coffee and cocoa bitterness; it still contains some sugar." }, { question: "What is ají dulce?", answer: "It is a mild, sweet chilli pepper used in Cuban cooking and in this rum's spice blend." }]
  }),
  "bruce-jack-chenin-blanc-143ecb4": detail({
    name: "Bruce Jack Chenin Blanc", category: "South African Chenin Blanc White Wine", overview: "A South African Chenin Blanc with the grape's useful mix of orchard fruit and brisk acidity. It is an easy white to bring to a table of varied starters.", craft: "Bruce Jack produces several South African Chenin Blanc labels, including a Lifestyle Collection wine. The house's Chenin wines draw on the grape's orchard-fruit aroma and adaptable acidity.", nose: "Pear, yellow apple and a touch of quince.", palate: "Medium-light, with juicy orchard fruit and fresh acidity.", finish: "Medium, with apple skin and citrus.", glass: "White-wine glass", temperature: "Chilled (8–10°C)", serve: "Serve cool with grilled or mildly creamy food.", pairings: ["malai paneer tikka", "grilled pomfret", "tandoori prawns", "lemon rice"], why: "Chenin's fruit-and-acidity balance works across seafood and paneer.", questions: [{ question: "Is this an oaked Chenin Blanc?", answer: "Chenin Blanc can be made with or without oak; this entry focuses on its orchard-fruit profile." }, { question: "Can Chenin Blanc be dry?", answer: "Yes. Chenin spans dry to sweet styles, and the precise sweetness should be read from this bottle." }]
  }),
  "amarula-cream-c09e42a": detail({
    name: "Amarula Cream", category: "South African Marula Cream Liqueur", overview: "Amarula combines marula-fruit spirit with cream for a plush, dessert-like liqueur. It belongs with pudding or coffee rather than a dry aperitif course.", craft: "Amarula was launched in 1989 and uses fruit from sub-Equatorial African marula trees. The producer says its marula spirit is distilled and aged in French oak for two years before being blended into the original cream liqueur.", nose: "Cream, caramel and soft tropical fruit.", palate: "Rich and velvety, with sweet cream and mellow marula fruit.", finish: "Medium, creamy and gently caramel-like.", glass: "Small rocks glass", temperature: "Chilled (6–10°C)", serve: "Pour 45 ml over ice or alongside coffee; refrigerate after opening as the label directs.", pairings: ["shahi tukda", "dark chocolate truffle", "coffee kulfi", "caramel custard"], why: "The marula-fruit base gives this cream liqueur a flavour beyond ordinary vanilla cream.", questions: [{ question: "Does Amarula contain dairy?", answer: "The original Amarula Cream is a dairy-cream liqueur; check the label for allergens." }, { question: "Can it be used in a cocktail?", answer: "Yes. It works in a dessert-style coffee drink or poured over ice." }]
  }),
  "angostura-aromatic-bitters-eef412e": detail({
    name: "Angostura Aromatic Bitters", category: "Aromatic Cocktail Bitters", overview: "A few dashes of Angostura add concentrated spice and bitter depth to cocktails. This is a seasoning ingredient, not a spirit intended for a full neat pour.", craft: "Dr Johann Siegert developed the original aromatic bitters in 1824 in the town then called Angostura, Venezuela. The secret botanical formula remains proprietary; the modern brand is produced by the House of Angostura in Trinidad and Tobago.", nose: "Warm spice, clove and dried herb.", palate: "Highly concentrated, bitter and aromatic, with cinnamon-like warmth.", finish: "Long and spice-laden despite a tiny serving.", glass: "Cocktail mixing glass", temperature: "Served in a chilled mixed drink", serve: "Use two or three dashes in an Old Fashioned or a lemon-and-soda highball; do not serve it by the shot.", pairings: ["masala-spiced nuts", "dark chocolate 70%", "ginger biscuits", "caramel custard"], why: "It changes the balance of a drink with only a few drops.", questions: [{ question: "Can I drink Angostura bitters neat?", answer: "It is designed as a concentrated cocktail ingredient; use measured dashes rather than a full pour." }, { question: "Are the botanicals disclosed?", answer: "No. The House of Angostura keeps its aromatic bitters formula secret." }]
  }),
  "armand-de-brignac-brut-gold-7a23b03": detail({
    name: "Armand de Brignac Brut Gold", category: "Prestige Brut Champagne", overview: "Brut Gold is Armand de Brignac's multi-vintage prestige Champagne, combining fruit richness with fine acidity. It is a bottle to serve slowly in a tulip glass, not as a mixer.", craft: "The house blends Pinot Noir, Chardonnay and Pinot Meunier from three Champagne vintages. Its current published assemblage is 50% Pinot Noir, 40% Chardonnay and 10% Meunier, though exact reserve years change by release.", nose: "Warm brioche, ripe peach and citrus blossom.", palate: "Generous and creamy, with apricot, lemon zest and a fine, persistent mousse.", finish: "Long, fresh and gently honeyed.", glass: "Tulip-shaped Champagne glass", temperature: "Chilled (8–10°C)", serve: "Chill gradually, open carefully and pour small servings to preserve the bubbles.", pairings: ["tandoori prawns", "malai paneer tikka", "butter-poached lobster", "fried chicken"], why: "Its multi-vintage blend brings the breadth and texture expected of a prestige cuvée.", questions: [{ question: "Is Brut Gold a single-vintage Champagne?", answer: "No. The house blends wines from three harvest years." }, { question: "Should it be served in a flute?", answer: "A tulip glass gives its brioche and fruit aromas more room than a narrow flute." }]
  }),
  "crystal-head-vodka-130a1b6": detail({
    name: "Crystal Head Vodka", category: "Canadian Corn Vodka", overview: "Crystal Head Original is a clean Canadian vodka in the distinctive clear skull bottle. Citrus and vanilla are subtle accents rather than added flavours.", craft: "Launched in 2008, Original is distilled four times from Canadian corn and blended with Newfoundland water. The producer says it is filtered seven times, including three passes through layers of Herkimer crystals.", nose: "Clean grain with a light citrus trace.", palate: "Silky and neutral, with restrained sweetness and a touch of vanilla.", finish: "Medium, soft and creamy.", glass: "Chilled vodka glass or Martini glass", temperature: "Chilled (4–8°C)", serve: "Serve 45 ml chilled or stir into a dry Martini; do not hide it under heavy syrup.", pairings: ["tandoori prawns", "cucumber chaat", "smoked salmon", "malai paneer tikka"], why: "Its unusually gentle texture works in a restrained Martini as well as a neat chilled pour.", questions: [{ question: "Is Crystal Head Original flavoured?", answer: "No. The citrus and vanilla notes are tasting impressions, not a flavoured-vodka label." }, { question: "What is it made from?", answer: "The producer specifies Canadian corn and Newfoundland water for Original." }]
  }),
  "crystal-head-vodka-onyx-55322e5": detail({
    name: "Crystal Head Vodka Onyx", category: "Blue Weber Agave Vodka", overview: "Onyx is Crystal Head's agave-based vodka, with more green pepper and earthy character than Original. It is vodka rather than tequila despite the Blue Weber agave base.", craft: "Introduced in 2020, Onyx uses Blue Weber agave from a single Mexican farm and water from Newfoundland. The producer says no sugar, oils or other additives are added; the glossy black skull bottle identifies this expression.", nose: "Green grass, white pepper and a little citrus.", palate: "Soft, lightly sweet and peppery, moving into earthy agave.", finish: "Medium, with green herbs and pepper.", glass: "Chilled rocks glass", temperature: "Cool (6–10°C)", serve: "Try 45 ml over one large cube or in an agave-and-lime Gimlet.", pairings: ["tandoori prawns", "cucumber chaat", "lime chicken tikka", "rava-fried fish"], why: "The agave base supplies a savoury edge uncommon in neutral vodka.", questions: [{ question: "Is Onyx tequila?", answer: "No. Crystal Head markets Onyx as a vodka made with Blue Weber agave." }, { question: "How does it differ from Original?", answer: "Original is corn-based and more neutral; Onyx brings grassy, peppery agave notes." }]
  }),
  "bottega-cabernet-sauvignon-2ea7b4d": detail({
    name: "Bottega Cabernet Sauvignon", category: "Trevenezie IGT Cabernet Sauvignon Red Wine", overview: "Bottega's Cabernet Sauvignon is a northern Italian red with dark berry fruit and a dry finish. It is a firmer dinner wine than the producer's Prosecco range.", craft: "Bottega lists its Cabernet Sauvignon under the Trevenezie IGT, an area spanning Veneto, Friuli Venezia Giulia and Trento. Cabernet Sauvignon's dark fruit and dry structure make it well suited to grilled food.", nose: "Blackcurrant, cherry and dried herb.", palate: "Medium-bodied and dry, with dark fruit and moderate tannin.", finish: "Medium, with black fruit skin and savoury spice.", glass: "Bordeaux red-wine glass", temperature: "Slightly cool (16–18°C)", serve: "Pair with grilled mains and let the glass warm gradually.", pairings: ["mutton seekh kebab", "lamb chops", "tandoori chicken", "aged Grana Padano"], why: "It offers the Cabernet profile through a northern Italian lens.", questions: [{ question: "Is this a Bordeaux wine?", answer: "No. Bottega places this Cabernet Sauvignon in the Trevenezie IGT of northern Italy." }, { question: "What food suits its tannin?", answer: "Grilled meat, firm cheese or richly seasoned paneer can balance the dry tannin." }]
  }),
  "cune-rioja-rose-1ca4e9b": detail({
    name: "Cune Rioja Rosé", category: "Rioja Tempranillo Rosé Wine", overview: "Cune Rosado is a red-fruit Rioja rosé that stays fresh rather than sugary. Strawberry and raspberry make it an easy partner for a spicy lunch.", craft: "CVNE was founded in Haro, Rioja Alta, in 1879. Its current Cune Rosado is made from Tempranillo, harvested early and fermented under temperature control in stainless steel; vintage details can change.", nose: "Strawberry, raspberry and red liquorice.", palate: "Light and smooth, with bright berry fruit and refreshing acidity.", finish: "Medium, clean and strawberry-led.", glass: "Rosé wine glass", temperature: "Chilled (8–10°C)", serve: "Serve chilled with savoury starters; avoid diluting it with ice.", pairings: ["tandoori prawns", "chicken tikka", "paneer tikka", "watermelon chaat"], why: "The Tempranillo rosé style brings fruit without losing a crisp finish.", questions: [{ question: "Is Cune Rosé made with Tempranillo?", answer: "CVNE lists Tempranillo for the current Rosado; check older vintage labels individually." }, { question: "Is it a sweet pink wine?", answer: "It is made in a fresh, food-friendly rosé style rather than as a dessert wine." }]
  }),
  "castello-di-ama-chianti-classico-0e96b54": detail({
    name: "Castello di Ama Chianti Classico", category: "Chianti Classico DOCG Red Wine", overview: "Castello di Ama's Chianti Classico is a Tuscan red where cherry fruit meets savoury acidity and firm but polished tannin. Its balance is better suited to dinner than a sweet aperitif.", craft: "Four families revived the Ama estate in 1976 in the heart of Chianti Classico; Marco Pallanti joined in 1982. The producer farms high-lying vineyards with clay and chalk soils that help give its Chianti Classico freshness and poise.", nose: "Sour cherry, violet and dried Mediterranean herb.", palate: "Medium-full and dry, with red cherry, lively acidity and fine tannin.", finish: "Long, savoury and gently earthy.", glass: "Large red-wine glass", temperature: "Cellar cool (16–18°C)", serve: "Pour with a tomato- or meat-based meal; young bottles may welcome brief air.", pairings: ["lamb chops", "mutton ghee roast", "mushroom ragù", "aged pecorino"], why: "Its Sangiovese-driven acidity gives rich food a clean counterpoint.", questions: [{ question: "Is this the Bellavista Gran Selezione?", answer: "Bellavista is a separate named Gran Selezione from the same estate, with a more concentrated profile." }, { question: "Which grape defines Chianti Classico?", answer: "Sangiovese is the principal grape of Chianti Classico; supporting grapes depend on the cuvée." }]
  }),
  "cannonball-chardonnay-82dc462": detail({
    name: "Cannonball Chardonnay", category: "California Chardonnay White Wine", overview: "Cannonball's California Chardonnay aims for balance between ripe orchard fruit and freshness. Pear and lemon curd make it richer than a lean mineral white, without losing its food focus.", craft: "Cannonball Wine is based in Healdsburg, California, and lists Chardonnay among its core wines. The producer describes poached pear, yellow plum and toasted almond; oak handling changes between releases and is not fixed here.", nose: "Poached pear, yellow plum and a hint of toasted almond.", palate: "Medium-bodied and softly textured, with lemon curd and ripe orchard fruit.", finish: "Medium, rounded and citrus-bright.", glass: "White-wine glass", temperature: "Cool (9–11°C)", serve: "Pour cool, then allow a little warmth to reveal its pear and almond notes.", pairings: ["malai paneer tikka", "butter-garlic prawns", "grilled pomfret", "roast chicken"], why: "It keeps Chardonnay's creamy appeal in balance with acidity.", questions: [{ question: "Is Cannonball Chardonnay very buttery?", answer: "The producer emphasises fruit and balance; the impression of butter varies with vintage and serving temperature." }, { question: "Should it be served ice-cold?", answer: "No. Around 9–11°C allows the fruit and texture to show." }]
  }),
  "barolo-bersano-80ee953": detail({
    name: "Bersano Barolo", category: "Barolo DOCG Nebbiolo Red Wine", overview: "Bersano's Barolo is a traditional, structured Nebbiolo red made for slow meals. Mature fruit, dried violet and long tannin ask for substantial food.", craft: "Bersano's Barolo comes from the Barolo communes of Piedmont and uses Nebbiolo grapes. Its Barolo tradition includes skin fermentation and extended maturation in large oak casks and bottle.", nose: "Dried violet, ripe plum and liquorice.", palate: "Full and dry, with red fruit, leather-like savouriness and firm, softening tannin.", finish: "Long, with pepper, plum and persistent tannin.", glass: "Large Burgundy red-wine glass", temperature: "Cellar cool (16–18°C)", serve: "Open well before a rich meal; decant a young vintage only after tasting it.", pairings: ["lamb rogan josh", "mutton seekh kebab", "mushroom galouti", "aged Parmigiano"], why: "Its traditional Nebbiolo structure rewards a slow meal and careful serving.", questions: [{ question: "Which grape makes Bersano Barolo?", answer: "Barolo DOCG is made from Nebbiolo." }, { question: "How does Bersano Napoleonica compare?", answer: "Napoleonica is a named Bersano Barolo cuvée with extended oak and bottle maturation." }]
  }),
};
