// Evidence and catalogue caveats: docs/editorial/product-batch-37-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

type Draft = {
  name: string; category: string; overview: string; craft: string;
  nose: string; palate: string; finish: string; glass: string; temp: string; serve: string;
  pairings: [string, string, string, string, ...string[]]; why: string;
  faqs: [{ question: string; answer: string }, { question: string; answer: string }]; description: string;
};
const detail = (d: Draft): ProductPublicDetail => ({
  productName: d.name, category: d.category, shortOverview: d.overview, craftStory: d.craft,
  tastingNotes: { nose: d.nose, palate: d.palate, finish: d.finish },
  servingGuide: { glassware: d.glass, idealTemperature: d.temp, recommendation: d.serve },
  foodPairings: d.pairings, whyBuyThis: d.why, faqs: d.faqs,
  metaTitle: `${d.name} Price, Taste & Review | BevOry`.length <= 60
    ? `${d.name} Price, Taste & Review | BevOry`
    : `${d.name} Price | BevOry`.length <= 60 ? `${d.name} Price | BevOry` : d.name,
  metaDescription: d.description,
});

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "teachers-highland-cream-fc446fc": detail({
    name: "Teacher's Highland Cream", category: "Blended Scotch Whisky", overview: "Highland Cream is a malt-forward blended Scotch with a genuine peated edge rather than added smoke flavour. Honey and orchard fruit round out its Ardmore-led profile.", craft: "William Teacher introduced Highland Cream in Glasgow in 1863. Ardmore single malt, twice distilled in copper pot stills near Kennethmont and peated before maturation, is its signature component alongside other Scotch malts and grains.", nose: "Honey, apple, pear and a gentle Highland peat tang.", palate: "Rounded and warming, with robust malt, sweet orchard fruit and measured smoke.", finish: "Medium-long, clean and softly smoky.", glass: "Glencairn or highball glass", temp: "Room temperature (18–20°C)", serve: "Taste 30 ml neat first; a splash of water or soda opens a lighter serve.", pairings: ["mutton seekh", "tandoori chicken", "roasted cashews", "70% dark chocolate"], why: "Ardmore's peated malt gives a familiar blend a recognisable smoky backbone.", faqs: [{ question: "Is Teacher's Highland Cream peated?", answer: "Yes. Teacher's identifies fully peated Ardmore malt as its signature whisky." }, { question: "Is it a single malt?", answer: "No. It blends malt and grain Scotch whiskies." }], description: "Teacher's Highland Cream has honey, orchard fruit and light peat. Pair with mutton seekh; check city prices on BevOry."
  }),
  "teachers-50-b25c0c0": detail({
    name: "Teacher's 50", category: "Blended Scotch Whisky", overview: "Teacher's 50 is a richer blended Scotch made for the Indian market. Sherry-tinged fruit, malt and a trace of peat give it more after-dinner weight than a basic highball whisky.", craft: "Teacher's created this expression in 1997 to mark fifty years of India's independence. The producer describes a 50:50 split of Scotch malt and grain whiskies, following the Glasgow house's long tradition of peated malt blending.", nose: "Pear, orange peel, malt and a hint of sherry and peat.", palate: "Full and silky, with malt sweetness, dried fruit and gentle smoke.", finish: "Long, spicy and faintly smoky.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Pour 30 ml neat; add a few drops of water before considering ice.", pairings: ["galouti kebab", "lamb rogan josh", "roasted almonds", "70% dark chocolate"], why: "Its unusually explicit malt-to-grain balance sets it apart within accessible blends.", faqs: [{ question: "Does 50 mean fifty years old?", answer: "No. It commemorates fifty years of Indian independence." }, { question: "What is the blend ratio?", answer: "Teacher's states 50% malt whisky and 50% grain whisky." }], description: "Teacher's 50 has pear, sherry-like fruit and light smoke. Pair with galouti kebab; check city prices on BevOry."
  }),
  "teachers-origin-e3b07f6": detail({
    name: "Teacher's Origin", category: "Malt-Rich Blended Scotch Whisky", overview: "Origin is the malt-heaviest whisky in Teacher's published range, with sweetness and dry peat in tension. It merits a slower neat tasting than a soda-heavy serve.", craft: "Made in tribute to founder William Teacher, Origin contains 65% single malts according to the producer. Ardmore's peated Highland malt contributes liquorice-root smoke, while Speyside and Highland components bring fruit and flowers.", nose: "Malt, pear, apple, orange and a drier peat undertone.", palate: "Mouth-filling, shifting from fruit sweetness to oak dryness and liquorice smoke.", finish: "Long, with persistent malt and peat spice.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Sip 30 ml neat; a few drops of water can lift the fruit and floral notes.", pairings: ["mutton seekh", "lamb rogan josh", "smoked paneer tikka", "70% dark chocolate"], why: "A declared 65% malt content gives this blend unusually clear character.", faqs: [{ question: "Is Origin a single malt?", answer: "No. It is a malt-rich blended Scotch." }, { question: "Where does its smoke come from?", answer: "Teacher's credits peated Ardmore malt in the blend." }], description: "Teacher's Origin has pear, orange, oak and peat. Pair with mutton seekh; check city prices on BevOry."
  }),
  "grants-triple-wood-97ea255": detail({
    name: "Grant's Triple Wood", category: "Blended Scotch Whisky", overview: "Triple Wood is a round, sweet-edged Grant's blend built around three oak influences. Vanilla and baking spice make it a practical whisky for a highball.", craft: "The Grant family has made whisky in Scotland since 1887. Grant's says Triple Wood is matured in three wood types to build balance across malt and grain Scotch components, without claiming a fixed age on this bottle.", nose: "Pear, vanilla and gentle baking spice.", palate: "Medium-bodied, with orchard fruit, caramel and soft oak.", finish: "Medium, mellow and lightly spicy.", glass: "Highball or rocks glass", temp: "Room temperature or over ice", serve: "Combine 45 ml with chilled soda and a twist of lemon, or pour over one large cube.", pairings: ["tandoori chicken", "paneer tikka", "masala peanuts", "roasted cashews"], why: "Three-wood maturation gives an easy-drinking blend a little more oak texture.", faqs: [{ question: "Does Triple Wood mean three years old?", answer: "No. The name refers to three wood influences, not an age statement." }, { question: "Is it Scotch?", answer: "Yes. It is a blended Scotch whisky." }], description: "Grant's Triple Wood has pear, vanilla and soft oak. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "grants-distinction-b926ffa": detail({
    name: "Grant's Distinction", category: "Blended Scotch Whisky", overview: "Distinction is a Grant's blended Scotch positioned for the Indian market. Its malt-and-grain balance suits a tall soda serve beside savoury snacks.", craft: "William Grant & Sons makes Grant's within its family-owned Scotch portfolio, founded in 1887. Distinction is a separate Indian-market expression; its label, not the Triple Wood recipe, governs the bottle's exact composition.", nose: "Malt biscuit, honey and light dried fruit.", palate: "Medium-bodied and rounded, with cereal sweetness and restrained oak spice.", finish: "Medium, warm and gently dry.", glass: "Highball glass", temp: "Room temperature or over ice", serve: "Pour 45 ml over ice and top with chilled soda; keep the mixer unsweetened to see the malt.", pairings: ["mutton seekh", "paneer tikka", "roasted peanuts", "tandoori chicken"], why: "It provides a malt-led Scotch option designed around familiar Indian drinking occasions.", faqs: [{ question: "Is Distinction the same as Triple Wood?", answer: "No. They are separately named Grant's expressions." }, { question: "Can it be served neat?", answer: "Yes; a small neat pour is a useful first taste before adding soda." }], description: "Grant's Distinction has malt biscuit and gentle oak. Pair with paneer tikka; check city prices on BevOry."
  }),
  "grants-grant-blended-scotch-whisky-the-family-res-ae5b2d9": detail({
    name: "Grant's Family Reserve", category: "Blended Scotch Whisky", overview: "Family Reserve is a smooth Grant's blend with sweet malt, fruit and light wood. It offers a straightforward Scotch profile for a whisky-and-ginger-ale or neat pour.", craft: "The Grant family established its Scottish whisky business in 1887. Family Reserve combines malt and grain Scotch whiskies under the house blender; it is a distinct historical label and should not be assigned the Triple Wood cask recipe by default.", nose: "Honey, pear and toasted cereal.", palate: "Soft and medium-light, with vanilla, apple and mild oak spice.", finish: "Medium, clean and a little sweet.", glass: "Rocks or highball glass", temp: "Room temperature or over ice", serve: "Start with 30 ml neat, then try ginger ale and ice for a longer drink.", pairings: ["tandoori chicken", "masala peanuts", "paneer tikka", "roasted almonds"], why: "An uncomplicated Grant's blend with a useful balance of fruit and grain.", faqs: [{ question: "Is Family Reserve an age-stated Scotch?", answer: "No age statement is part of this listing's name." }, { question: "What goes into blended Scotch?", answer: "It combines Scotch malt and grain whiskies." }], description: "Grant's Family Reserve has honey, pear and soft vanilla. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "jim-beam-orange-bbe1a52": detail({
    name: "Jim Beam Orange", category: "Orange Bourbon Liqueur", overview: "Jim Beam Orange layers juicy citrus over Kentucky bourbon's vanilla and light char. It is a flavoured liqueur-style bottle, not the same liquid as straight Jim Beam bourbon.", craft: "Jim Beam makes bourbon in Clermont, Kentucky. The producer blends orange liqueur with Kentucky straight bourbon for this expression, retaining an oak undertone beneath the orange flavour.", nose: "Sweet orange peel, vanilla and a little barrel char.", palate: "Juicy and sweet, with orange zest followed by bourbon oak.", finish: "Medium, citrus-led with light woody warmth.", glass: "Highball glass", temp: "Chilled over ice", serve: "Mix 45 ml with soda and ice; add an orange slice rather than more syrup.", pairings: ["tandoori chicken", "masala peanuts", "orange-dark-chocolate bark", "paneer tikka"], why: "The orange is clear and bright without erasing the bourbon base.", faqs: [{ question: "Is this straight bourbon?", answer: "No. Jim Beam describes it as orange liqueur blended with bourbon." }, { question: "What is an easy mixer?", answer: "Soda and ice keep the citrus from becoming overly sweet." }], description: "Jim Beam Orange brings juicy citrus and bourbon oak. Pair with tandoori chicken; check city prices on BevOry."
  }),
  "jim-beam-devils-cut-e288218": detail({
    name: "Jim Beam Devil's Cut", category: "Kentucky Bourbon Whiskey", overview: "Devil's Cut is an oak-forward bourbon with deeper barrel character than standard Jim Beam. Char, vanilla and spice make it worth tasting neat before mixing.", craft: "At Clermont, Kentucky, Jim Beam extracts whiskey held within emptied barrel wood and blends it with extra-aged Kentucky straight bourbon. The producer bottles this expression at 90 US proof, giving it a fuller, darker profile.", nose: "Deep char, vanilla and a smoky wood backdrop.", palate: "Full-bodied, with intense oak, vanilla and warm spice.", finish: "Long and dry, with charred wood and pepper.", glass: "Rocks glass", temp: "Room temperature (18–20°C)", serve: "Taste 30 ml neat, then add one large cube if the oak feels firm.", pairings: ["mutton seekh", "lamb rogan josh", "70% dark chocolate", "roasted almonds"], why: "Its barrel-extraction method delivers a distinctly assertive oak profile.", faqs: [{ question: "What is the devil's cut?", answer: "Jim Beam uses whiskey extracted from barrel wood after emptying." }, { question: "Is it smoky like peated Scotch?", answer: "Its smoky impression comes from charred oak, not peated malt." }], description: "Jim Beam Devil's Cut has char, vanilla and firm oak. Pair with mutton seekh; check city prices on BevOry."
  }),
  "magic-moments-magic-moment-orange-132a45e": detail({
    name: "Magic Moments Orange", category: "Indian Orange-Flavoured Vodka", overview: "Magic Moments Orange adds a sweet orange note to the brand's grain-vodka base. Its direct citrus profile works best in a simple, cold long drink.", craft: "Radico Khaitan launched Magic Moments in India in 2006. Its Remix range includes Orange; the producer describes the core grain vodka as triple-distilled before flavour-led variants are made.", nose: "Fresh orange zest, candied peel and clean grain.", palate: "Light and sweet, with orange cordial fruit and a smooth vodka base.", finish: "Short, citrusy and lightly warming.", glass: "Highball glass", temp: "Chilled over ice", serve: "Mix 45 ml with chilled soda and lime; avoid sweet juice if you want the orange to stay crisp.", pairings: ["tandoori prawns", "malai paneer tikka", "masala peanuts", "fruit chaat"], why: "An easy orange-led mixer without needing a complicated recipe.", faqs: [{ question: "Is this plain vodka?", answer: "No. Orange is a flavoured Magic Moments expression." }, { question: "What can I mix it with?", answer: "Soda, ice and lime make a straightforward citrus highball." }], description: "Magic Moments Orange has bright citrus over smooth grain vodka. Pair with prawns; check city prices on BevOry."
  }),
  "magic-moments-magic-moments-verve-lemon-lush-17c32ec": detail({
    name: "Magic Moments Verve Lemon Lush", category: "Indian Lemon-Flavoured Vodka", overview: "Verve Lemon Lush gives a sharper citrus edge to Magic Moments' premium vodka line. It is a better match for soda and fresh herbs than a sugary mixer.", craft: "Radico Khaitan introduced Verve as its super-premium vodka line in 2012. The producer describes a five-stage slow filtration process using silver and platinum filters, with Lemon Lush one of its named flavoured expressions.", nose: "Lemon zest, soft cereal and a floral citrus hint.", palate: "Light, clean and lemon-forward, with a slight sweetness beneath the acidity.", finish: "Short, bright and zesty.", glass: "Highball glass", temp: "Chilled over ice", serve: "Pour 45 ml over ice with soda and a little fresh mint (pudina).", pairings: ["rava-fried fish", "tandoori prawns", "cucumber chaat", "malai paneer tikka"], why: "A clean lemon profile makes a quick, refreshing highball.", faqs: [{ question: "Is Verve Lemon Lush unflavoured?", answer: "No. It is a lemon-flavoured Verve vodka." }, { question: "Does Verve use a filtration process?", answer: "Radico describes five-stage slow filtration with silver and platinum filters." }], description: "Verve Lemon Lush has lemon zest and a crisp finish. Pair with rava-fried fish; check city prices on BevOry."
  }),
  "magic-moments-remix-radiant-pink-vodka-5f87256": detail({
    name: "Magic Moments Remix Radiant Pink", category: "Indian Berry-Flavoured Vodka", overview: "Radiant Pink is a berry-and-floral Magic Moments vodka, not a rosé wine. Black mulberry, elderflower and raspberry create a brighter spritz profile than plain vodka.", craft: "Radico Khaitan announced Remix Pink in 2023 as a coloured, flavoured vodka. The producer identifies natural black mulberry, elderflower and raspberry flavours, built within its Indian Magic Moments portfolio.", nose: "Raspberry, black mulberry and light elderflower.", palate: "Soft and fruit-forward, with sweet berry notes and a floral lift.", finish: "Short, pink-berry and gently perfumed.", glass: "Highball or spritz glass", temp: "Chilled over ice", serve: "Lengthen 45 ml with soda and ice; garnish with lime rather than syrup.", pairings: ["malai paneer tikka", "fruit chaat", "tandoori prawns", "roasted makhana"], why: "It combines distinct berry and floral notes in an uncomplicated spritz base.", faqs: [{ question: "Is Remix Pink a wine?", answer: "No. It is a flavoured vodka." }, { question: "Which flavours are named by the producer?", answer: "Black mulberry, elderflower and raspberry." }], description: "Magic Moments Remix Pink has berry and elderflower notes. Pair with fruit chaat; check city prices on BevOry."
  }),
  "magic-moments-magic-moments-remix-grapefruit-and-watermelon-flavoured-superior-vodka-6b63411": detail({
    name: "Magic Moments Remix Grapefruit & Watermelon", category: "Indian Fruit-Flavoured Vodka", overview: "Grapefruit & Watermelon combines tart citrus with soft melon fruit. It is an easy cold mixer when a plain vodka-and-soda feels too neutral.", craft: "Radico Khaitan makes Remix as a flavoured extension of its triple-distilled Magic Moments vodka. Grapefruit & Watermelon is one of the producer's established named flavours within the Indian range.", nose: "Pink grapefruit peel and fresh watermelon.", palate: "Light and fruit-sweet, with grapefruit bite after the melon.", finish: "Short, juicy and citrus-tinged.", glass: "Highball glass", temp: "Chilled over ice", serve: "Mix 45 ml with soda, plenty of ice and a grapefruit wedge.", pairings: ["tandoori prawns", "cucumber chaat", "malai paneer tikka", "masala peanuts"], why: "The tart grapefruit edge balances the watermelon sweetness.", faqs: [{ question: "Is it a ready-to-drink can?", answer: "No. This is a flavoured vodka bottle to pour or mix." }, { question: "What is a simple serve?", answer: "Soda and ice keep the two fruit notes clear." }], description: "Magic Moments Remix has grapefruit bite and watermelon fruit. Pair with prawns; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-dazzle-special-edition-vanilla-flavoured-vodka-8d7dc1b": detail({
    name: "Magic Moments Dazzle Vanilla", category: "Indian Vanilla-Flavoured Vodka", overview: "Dazzle Vanilla is the dessert-leaning member of Magic Moments' vodka family. Creamy vanilla and grain spirit make it useful in a short coffee cocktail rather than a citrus highball.", craft: "Radico Khaitan describes Dazzle Vanilla as made from grain spirit with Madagascar vanilla flavour. The producer introduced it as a separate premium expression, distinct from the fruit-led Remix bottles.", nose: "Vanilla pod, soft cream and sweet grain.", palate: "Smooth and sweet, with creamy vanilla moving into warm cereal.", finish: "Medium, vanilla-led and gently warming.", glass: "Rocks glass", temp: "Cool over ice", serve: "Shake 45 ml with chilled espresso and ice for a vanilla coffee cocktail.", pairings: ["70% dark chocolate", "roasted almonds", "gajar halwa", "coffee kulfi"], why: "Madagascar-style vanilla gives the bottle a clear dessert-cocktail role.", faqs: [{ question: "Is Dazzle Vanilla plain vodka?", answer: "No. It is a vanilla-flavoured vodka." }, { question: "Which dessert suits it?", answer: "Coffee kulfi or dark chocolate picks up its creamy vanilla." }], description: "Magic Moments Dazzle Vanilla has creamy vanilla and grain. Pair with coffee kulfi; check city prices on BevOry."
  }),
  "magic-moments-m2-magic-moments-verve-super-premium-vodka-15e2ab9": detail({
    name: "Magic Moments Verve", category: "Indian Premium Grain Vodka", overview: "Verve is Magic Moments' unflavoured premium grain vodka, made for a clean, chilled serve. Its smooth texture makes it a flexible Martini or soda base without the fruit sweetness of Remix.", craft: "Radico Khaitan introduced Verve in 2012. The producer describes grain spirit passing through a five-stage slow filtration process using silver and platinum filters, distinguishing it from the flavoured Remix line.", nose: "Clean cereal, faint citrus peel and a light mineral note.", palate: "Soft and neutral, with mild grain sweetness and a smooth texture.", finish: "Medium, dry and clean.", glass: "Small vodka glass or Martini glass", temp: "Chilled (4–8°C)", serve: "Chill and taste 30 ml neat, or stir with dry vermouth for a Martini.", pairings: ["tandoori prawns", "rava-fried fish", "cucumber chaat", "malai paneer tikka"], why: "A filtered grain vodka for drinkers who want a neutral base rather than added flavour.", faqs: [{ question: "Is Verve flavoured?", answer: "This is the unflavoured Verve expression; the range also has flavoured variants." }, { question: "How is it filtered?", answer: "Radico describes five-stage slow filtration with silver and platinum filters." }], description: "Magic Moments Verve is clean and grain-soft. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "smirnoff-orange-flavour-17267fd": detail({
    name: "Smirnoff Orange", category: "Orange-Flavoured Vodka", overview: "Smirnoff Orange is a brightly flavoured vodka with mandarin and navel-orange character. Its zesty sweetness is most useful in a simple soda drink.", craft: "Smirnoff makes this flavour from its triple-distilled vodka base. The brand describes six varieties of mandarin and navel orange flavours; bottle strength and origin can vary by market.", nose: "Mandarin peel, sweet orange and clean grain.", palate: "Light and juicy, with sweet citrus followed by zest.", finish: "Short, bright and orange-led.", glass: "Highball glass", temp: "Chilled over ice", serve: "Pour 45 ml with soda and ice, then squeeze in a fresh orange wedge.", pairings: ["tandoori prawns", "paneer tikka", "masala peanuts", "fruit chaat"], why: "Its mandarin-and-navel profile is more specific than a generic citrus vodka.", faqs: [{ question: "Is Smirnoff Orange unflavoured?", answer: "No. It is Smirnoff's orange-flavoured vodka." }, { question: "Is the ABV always the same?", answer: "Check the local bottle, as strength differs between markets." }], description: "Smirnoff Orange has mandarin and navel-orange zest. Pair with paneer tikka; check city prices on BevOry."
  }),
  "royal-stag-royal-stag-4f75669": detail({
    name: "Royal Stag", category: "Indian Blended Whisky", overview: "Royal Stag is a widely recognised Indian whisky with malt, grain and gentle wood notes. It is geared toward a straightforward rocks or soda serve rather than extended neat tasting.", craft: "Pernod Ricard India makes Royal Stag within its Seagram's whisky family. The brand's recent Mark of Purity programme highlights triple-barrel maturation and a long-standing no-artificial-flavour positioning, while pack details should guide the precise expression.", nose: "Malt biscuit, soft vanilla and light oak.", palate: "Medium-bodied and grain-led, with mild sweetness and wood spice.", finish: "Medium, warm and lightly dry.", glass: "Rocks or highball glass", temp: "Room temperature or over ice", serve: "Start with 45 ml over one large cube; add chilled soda if desired.", pairings: ["mutton seekh", "tandoori chicken", "masala peanuts", "paneer tikka"], why: "An accessible Indian whisky with a clean malt-and-grain profile.", faqs: [{ question: "Is Royal Stag Scotch?", answer: "No. It is an Indian blended whisky." }, { question: "Can it be mixed with soda?", answer: "Yes. Soda and ice are a simple way to serve it." }], description: "Royal Stag has malt, vanilla and gentle oak. Pair with mutton seekh; check city prices on BevOry."
  }),
  "royal-stag-barrel-select-674552c": detail({
    name: "Royal Stag Barrel Select", category: "Indian Blended Whisky", overview: "Barrel Select is Royal Stag's more polished step above its main label. It brings a rounder wood note while retaining the familiar Indian blended-whisky profile.", craft: "Pernod Ricard India introduced Barrel Select as a premium extension of Royal Stag. It is a separate Seagram's expression; specific barrel types and age should not be inferred from the word Select alone.", nose: "Vanilla, toasted grain and faint dried fruit.", palate: "Rounded and medium-bodied, with grain sweetness and a warmer oak accent.", finish: "Medium, smooth and lightly spiced.", glass: "Rocks glass", temp: "Room temperature or over ice", serve: "Pour 30 ml neat to compare it with regular Royal Stag, then add ice if preferred.", pairings: ["mutton seekh", "paneer tikka", "roasted cashews", "tandoori chicken"], why: "A fuller Royal Stag profile without moving to a very smoky style.", faqs: [{ question: "Is Barrel Select the same as Royal Stag?", answer: "No. It is a separate expression in the Royal Stag family." }, { question: "Does Select state an age?", answer: "No age is stated by this name." }], description: "Royal Stag Barrel Select has vanilla and a rounded oak edge. Pair with kebabs; check city prices on BevOry."
  }),
  "ciroc-snap-frost-7172fa6": detail({
    name: "Cîroc Snap Frost Vodka", category: "French Grape Vodka", overview: "Cîroc Snap Frost is grape-based rather than grain-based vodka, with a light fruit lift beneath its clean profile. It suits a cold Martini or a short citrus-and-soda serve.", craft: "Cîroc is produced in France from fine French grapes and marketed as five-times distilled. Snap Frost names the original expression and its cold-production identity; it is not a flavoured vodka.", nose: "Light grape skin, citrus peel and a clean mineral note.", palate: "Soft and lightly fruity, with grape sweetness kept in check by a dry spirit edge.", finish: "Medium, crisp and gently citrusy.", glass: "Martini or small vodka glass", temp: "Chilled (4–8°C)", serve: "Chill thoroughly; stir 45 ml with dry vermouth and strain into a cold glass.", pairings: ["tandoori prawns", "rava-fried fish", "cucumber chaat", "malai paneer tikka"], why: "Its grape base makes a noticeably different option from grain vodkas.", faqs: [{ question: "Is Snap Frost grape vodka?", answer: "Yes. Cîroc identifies fine French grapes as its base." }, { question: "Is it flavoured?", answer: "No. This is the original unflavoured expression." }], description: "Cîroc Snap Frost has subtle grape and citrus notes. Pair with prawns; check city prices on BevOry."
  }),
  "molinari-sambuca-c8e56dc": detail({
    name: "Molinari Sambuca Extra", category: "Italian Star-Anise Liqueur", overview: "Molinari Sambuca Extra is a sweet, star-anise-led Italian liqueur, not a dry gin or vodka. A small chilled pour beside coffee shows its herbal perfume without hiding the anise.", craft: "Angelo Molinari created Sambuca Extra in Civitavecchia in 1945. The family describes star anise as its defining base and keeps the full recipe private; the traditional Rome serve adds a roasted coffee bean.", nose: "Star anise, sweet liquorice and a light herbal accent.", palate: "Full and syrupy, with anise sweetness and a small coffee-friendly spice edge.", finish: "Long, sweet and distinctly anise-scented.", glass: "Small liqueur glass", temp: "Chilled (6–10°C)", serve: "Pour 25–30 ml chilled and add one roasted coffee bean, or serve over one large cube.", pairings: ["coffee kulfi", "70% dark chocolate", "roasted almonds", "anise biscotti"], why: "Its clear star-anise identity makes a memorable after-dinner alternative to whisky.", faqs: [{ question: "What gives Molinari its anise aroma?", answer: "The producer identifies star anise as the defining ingredient." }, { question: "Why serve it with coffee?", answer: "A roasted coffee bean contrasts its sweetness in a traditional Italian serve." }], description: "Molinari Sambuca Extra has star anise and a sweet herbal finish. Pair with coffee kulfi; check city prices on BevOry."
  }),
  "famous-grouse-the-famous-grouse-59dcd00": detail({
    name: "The Famous Grouse", category: "Blended Scotch Whisky", overview: "The Famous Grouse is a balanced blended Scotch with bright fruit and warm grain notes. Its gentle profile makes it equally suitable for a small neat pour or ginger-ale highball.", craft: "The Famous Grouse traces its Scottish house identity to 1896. Its blend joins malt and grain whiskies; the producer says casks are aroma-checked before blending and the whisky is rested for a smooth result.", nose: "Candied fruit, buttery shortbread and citrus peel.", palate: "Medium-bodied and soft, with fruit, cereal and warm oak.", finish: "Medium, smooth and balanced.", glass: "Rocks or highball glass", temp: "Room temperature or over ice", serve: "Taste 30 ml neat, then try ginger ale, ice and a lime wedge.", pairings: ["tandoori chicken", "paneer tikka", "roasted cashews", "mutton seekh"], why: "Fruit and shortbread notes offer a gentle entry to blended Scotch.", faqs: [{ question: "Is The Famous Grouse a single malt?", answer: "No. It blends malt and grain Scotch whiskies." }, { question: "What mixer is suggested?", answer: "The brand recommends ginger ale with lime." }], description: "The Famous Grouse has candied fruit and shortbread notes. Pair with chicken tikka; check city prices on BevOry."
  }),
  "1664-blanc-e625eab": detail({
    name: "1664 Blanc", category: "French Wheat Beer", overview: "1664 Blanc is a hazy wheat beer with citrus, peach and coriander spice. Its soft body and low bitterness sit well beside seafood and creamy paneer.", craft: "The French 1664 Blanc recipe combines wheat and barley malt with orange peel, coriander and hop extract. Those additions produce its fruit-and-spice character without implying barrel maturation.", nose: "Orange peel, peach, apricot and gentle coriander.", palate: "Creamy and light, with citrus freshness, soft wheat and mild spice bitterness.", finish: "Short, refreshing and citrus-led.", glass: "Wheat-beer glass", temp: "Cool (5–7°C)", serve: "Pour chilled into a tall glass, leaving room for a soft white head.", pairings: ["tandoori prawns", "rava-fried fish", "malai paneer tikka", "cucumber chaat"], why: "Real orange peel and coriander give a distinct alternative to plain lager.", faqs: [{ question: "Why is 1664 Blanc hazy?", answer: "Haze is characteristic of its wheat-beer style." }, { question: "Is it strongly bitter?", answer: "No. The producer describes subtle bitterness balanced by citrus." }], description: "1664 Blanc has citrus, peach and coriander. Pair with tandoori prawns; check city prices on BevOry."
  }),
  "hoegaarden-can-91bbc9e": detail({
    name: "Hoegaarden White Can", category: "Belgian Wheat Beer", overview: "Hoegaarden White brings citrus and earthy coriander to a soft, cloudy wheat beer. The can changes the pack, not the underlying style.", craft: "Hoegaarden's brewing story begins in the Belgian village of the same name, where wheat beer was shaped by botanical additions. The current White expression uses orange-peel and coriander character to balance its wheat base.", nose: "Orange peel, wheat bread and coriander seed.", palate: "Soft and lightly creamy, with sweet citrus and very mild bitterness.", finish: "Short, fresh and faintly spicy.", glass: "Hoegaarden or wheat-beer glass", temp: "Cool (5–7°C)", serve: "Chill, pour two-thirds, swirl the can gently, then top the glass to carry the haze.", pairings: ["rava-fried fish", "tandoori prawns", "malai paneer tikka", "cucumber chaat"], why: "Its orange-and-coriander profile is more aromatic than a typical lager.", faqs: [{ question: "Is Hoegaarden White a lager?", answer: "No. It is a Belgian wheat beer." }, { question: "Why swirl the last pour?", answer: "The producer recommends swirling to bring the remaining wheat haze into the glass." }], description: "Hoegaarden White has orange peel, wheat and coriander. Pair with fried fish; check city prices on BevOry."
  }),
  "diplomatico-mantuano-02a5004": detail({
    name: "Diplomático Mantuano", category: "Venezuelan Blended Rum", overview: "Mantuano is a dark-gold Venezuelan rum with dried fruit, oak and a slightly dry finish. It can carry a rum Mule without losing its own character.", craft: "Diplomático blends Venezuelan rums for Mantuano, named after nineteenth-century Venezuelan mantuanos. The producer presents it as a versatile blend rather than a single-cask or fixed-age bottling.", nose: "Dried fruit, oak and soft vanilla.", palate: "Rich and balanced, with raisin, vanilla and delicate spice.", finish: "Medium-long, warm and slightly dry.", glass: "Rocks or highball glass", temp: "Room temperature or over ice", serve: "Try 45 ml with ginger beer, ice and lime for a rum Mule.", pairings: ["mutton seekh", "lamb rogan josh", "roasted almonds", "70% dark chocolate"], why: "Its dry edge reins in the usual sweetness of a rich rum highball.", faqs: [{ question: "Where is Mantuano from?", answer: "Diplomático makes it as a Venezuelan rum blend." }, { question: "Is it only for sipping?", answer: "No. The producer recommends it in long drinks and classic-cocktail twists." }], description: "Diplomático Mantuano has dried fruit, vanilla and oak. Pair with mutton seekh; check city prices on BevOry."
  }),
  "sazerac-rye-df84ffe": detail({
    name: "Sazerac Rye", category: "American Rye Whiskey", overview: "Sazerac Rye is a spice-led American whiskey closely tied to New Orleans cocktail history. Clove, anise and citrus make it a natural choice for its namesake cocktail.", craft: "The Sazerac Company links this rye to the nineteenth-century Sazerac Coffee House in New Orleans, where rye met Peychaud's Bitters and absinthe. Its rye character brings spice distinct from a sweet corn-led bourbon.", nose: "Clove, vanilla, anise and black pepper.", palate: "Medium-bodied, with candied sweetness, spice and crisp citrus.", finish: "Medium-long, smooth and liquorice-tinged.", glass: "Rocks glass", temp: "Room temperature or over ice", serve: "Stir 60 ml with Peychaud's Bitters and sugar, then strain into an absinthe-rinsed glass.", pairings: ["mutton seekh", "tandoori chicken", "aged cheddar", "70% dark chocolate"], why: "It brings authentic rye spice to a classic New Orleans Sazerac.", faqs: [{ question: "Is Sazerac Rye bourbon?", answer: "No. It is an American rye whiskey." }, { question: "Which cocktail shares its name?", answer: "The New Orleans Sazerac cocktail." }], description: "Sazerac Rye has clove, anise and citrus spice. Pair with mutton seekh; check city prices on BevOry."
  }),
  "ballantines-ballantine-aged-12-yrs-blended-scotch-whisky-a535f7e": detail({
    name: "Ballantine's 12 Year Old", category: "12-Year-Old Blended Scotch Whisky", overview: "Ballantine's 12 is a creamy, honeyed Scotch blend with floral and oak detail. It has enough maturity for a neat pour but remains gentle beside lightly spiced food.", craft: "Ballantine's introduced its 12 Year Old in the 1960s. The age statement means every malt and grain Scotch component spent at least twelve years in oak casks before the master blender married them.", nose: "Honey, vanilla, red apple and soft flowers.", palate: "Creamy and medium-bodied, with honeyed fruit, gentle oak and mild spice.", finish: "Long, sweet and fresh with a light woody echo.", glass: "Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Pour 30 ml neat; a few drops of water can soften the oak without hiding the fruit.", pairings: ["tandoori chicken", "malai paneer tikka", "roasted cashews", "aged cheddar"], why: "Twelve years of minimum oak age give a soft blend added depth.", faqs: [{ question: "Does 12 apply to every whisky in the blend?", answer: "Yes. The youngest component is at least twelve years old." }, { question: "Is it a single malt?", answer: "No. It is a blend of Scotch malt and grain whiskies." }], description: "Ballantine's 12 has honey, apple and creamy oak. Pair with chicken tikka; check city prices on BevOry."
  }),
  "antiquity-blue-antiquity-blue-4320d58": detail({
    name: "Antiquity Blue", category: "Indian Blended Whisky", overview: "Antiquity Blue is an Indian whisky with pronounced malt, wood and a trace of peat. It stands apart from softer blends through its fuller flavour and lightly smoky edge.", craft: "Introduced in 1992, Antiquity Blue is a Diageo India blend of select Indian malts and Scotch components linked to Cameronbridge. The producer identifies copper-pot distillation in its craft story and describes peat and heather accents.", nose: "Malt, heather, toasted wood and a faint peat note.", palate: "Fuller-bodied, with grain sweetness, firm oak and restrained smoke.", finish: "Medium-long, woody and lightly peaty.", glass: "Rocks or Glencairn glass", temp: "Room temperature (18–20°C)", serve: "Try 30 ml neat, then add a little water to distinguish malt from peat.", pairings: ["mutton seekh", "lamb rogan josh", "smoked paneer tikka", "70% dark chocolate"], why: "Its malt-and-wood weight makes it more characterful than a neutral mixer whisky.", faqs: [{ question: "Is Antiquity Blue made entirely in Scotland?", answer: "No. It is an Indian blend with Scotch components." }, { question: "Does it have peat character?", answer: "Diageo describes a hint of peat and heather in the whisky." }], description: "Antiquity Blue has malt, wood and a light peat note. Pair with mutton seekh; check city prices on BevOry."
  }),
  "johnnie-walker-white-walker-2478e8b": detail({
    name: "Johnnie Walker White Walker", category: "Limited-Edition Blended Scotch Whisky", overview: "White Walker is a Game of Thrones-themed Johnnie Walker blend made for a notably cold serve. It leans into lighter fruit and vanilla rather than Black Label's heavier smoke.", craft: "Diageo released White Walker as a limited collaboration inspired by the television series. Its Johnnie Walker identity remains a blend of Scotch whiskies, while the themed packaging and freezer-friendly serving cue distinguish this edition.", nose: "Soft vanilla, orchard fruit and a little malt.", palate: "Light-medium, with sweet grain, fresh fruit and a mild pepper note.", finish: "Medium, clean and gently warming.", glass: "Small whisky glass", temp: "Chilled (8–12°C)", serve: "Chill the bottle and pour 30 ml neat; allow the glass to warm gradually.", pairings: ["tandoori chicken", "paneer tikka", "roasted almonds", "aged cheddar"], why: "A recognisable limited-edition blend for those who prefer a cooler, lighter Scotch serve.", faqs: [{ question: "Is White Walker a single malt?", answer: "No. It is a limited-edition blended Scotch." }, { question: "Must it be frozen?", answer: "No. A chilled serve suits it, but freezing is not necessary." }], description: "Johnnie Walker White Walker has vanilla and fresh fruit. Pair with paneer tikka; check city prices on BevOry."
  }),
  "johnnie-walker-song-of-ice-a99d4c4": detail({
    name: "Johnnie Walker A Song of Ice", category: "Limited-Edition Blended Scotch Whisky", overview: "A Song of Ice is a crisp Game of Thrones-themed Scotch blend with a lighter grassy and fruit-led direction. It differs from the smoke-led A Song of Fire companion bottle.", craft: "Diageo created A Song of Ice as a limited Johnnie Walker collaboration associated with House Stark. The blend was presented as a clean, refreshing contrast to A Song of Fire, without an age statement on its name.", nose: "Green grass, vanilla and a little tropical fruit.", palate: "Light-medium and smooth, with fresh fruit, soft malt and gentle sweetness.", finish: "Medium, cool-feeling and lightly grassy.", glass: "Small whisky or highball glass", temp: "Slightly chilled (12–16°C)", serve: "Try 30 ml slightly chilled; add soda only if you prefer a longer drink.", pairings: ["malai paneer tikka", "tandoori chicken", "roasted cashews", "aged cheddar"], why: "Its crisp style makes it distinct from heavier, smoky limited editions.", faqs: [{ question: "Is A Song of Ice the same as White Walker?", answer: "No. They are separate Game of Thrones-themed Johnnie Walker releases." }, { question: "Is it peated?", answer: "The published concept emphasises clean, grassy fruit rather than peat smoke." }], description: "Johnnie Walker A Song of Ice has grass, vanilla and fruit. Pair with paneer tikka; check city prices on BevOry."
  }),
  "johnnie-walker-red-rye-finish-052a7ca": detail({
    name: "Johnnie Walker Red Rye Finish", category: "Rye-Cask-Finished Blended Scotch", overview: "Red Rye Finish is a Johnnie Walker Blender's Batch with a sweeter, spice-led profile. It brings Scotch malt and grain character closer to the feel of an American-whiskey cocktail.", craft: "Diageo released Red Rye Finish as the first Johnnie Walker Blender's Batch experiment. Scotch whiskies were finished in casks that previously held rye whiskey, bringing vanilla and spice without turning the liquid into American rye.", nose: "Vanilla, caramel and sweet oak.", palate: "Smooth and medium-bodied, with toffee, grain sweetness and rye-cask spice.", finish: "Medium, dry and lightly peppery.", glass: "Rocks or highball glass", temp: "Room temperature or over ice", serve: "Try 45 ml with soda and ice, or substitute it for bourbon in an Old Fashioned.", pairings: ["mutton seekh", "tandoori chicken", "roasted peanuts", "70% dark chocolate"], why: "The rye-cask finish gives familiar Scotch a useful cocktail-friendly spice.", faqs: [{ question: "Is Red Rye Finish American rye?", answer: "No. It is a blended Scotch finished in rye-whiskey casks." }, { question: "What is Blender's Batch?", answer: "It is Johnnie Walker's series of experimental blends." }], description: "Johnnie Walker Red Rye Finish has vanilla, caramel and rye spice. Pair with kebabs; check city prices on BevOry."
  }),
  "100-pipers-8-years-2930cb5": detail({
    name: "100 Pipers 8 Years", category: "8-Year-Old Blended Scotch Whisky", overview: "100 Pipers 8 Years is an age-stated step within the gently smoky Scotch range. Malt sweetness and soft peat make it well suited to savoury, spice-rich food.", craft: "Pernod Ricard's 100 Pipers family blends a selection of Scotch malt whiskies into a smooth, lightly smoky style. This named eight-year expression indicates a minimum of eight years in oak for its whisky components, rather than a separate cask finish.", nose: "Honeyed malt, dried apple and a light smoke thread.", palate: "Medium-bodied, with cereal sweetness, oak and gentle peat spice.", finish: "Medium, warm and delicately smoky.", glass: "Glencairn or rocks glass", temp: "Room temperature (18–20°C)", serve: "Sip 30 ml neat first; a few drops of water make its malt and smoke easier to separate.", pairings: ["mutton seekh", "tandoori chicken", "roasted almonds", "70% dark chocolate"], why: "An accessible age-stated Scotch with mild smoke rather than overwhelming peat.", faqs: [{ question: "Does eight years apply to the youngest whisky?", answer: "Yes. A Scotch age statement gives the minimum cask age of the blend." }, { question: "Is 100 Pipers a single malt?", answer: "No. It is a blended Scotch whisky." }], description: "100 Pipers 8 Years has malt, oak and gentle smoke. Pair with mutton seekh; check city prices on BevOry."
  }),
};
