// Producer-checked editorial. Source ledger: docs/editorial/product-batch-07-sources.md.
import type { ProductPublicDetail } from "./productContentBatch01.js";

export const PRODUCT_BATCH_CONTENT: Record<string, ProductPublicDetail> = {
  "sula-late-harvest-chenin-blanc-c6a66b5": {
    productName: "Sula Late Harvest Chenin", category: "Indian Chenin Blanc Dessert Wine",
    shortOverview: "Sula Late Harvest Chenin is deliberately sweet, with apricot, ripe mango and raisin rather than sparkling-wine bubbles. Its acidity keeps a small pour lively beside Indian sweets.",
    craftStory: "Sula makes this late-harvest wine from Chenin Blanc in Maharashtra's Nashik Valley. Leaving grapes longer on the vine concentrates sweetness before fermentation; Sula calls it India's first still dessert wine.",
    tastingNotes: { nose: "Apricot, ripe mango, raisin and a honeyed edge.", palate: "Full and sweet, with dried-fruit weight lifted by Chenin acidity.", finish: "Long and lush, with apricot and raisin lingering after the sweetness." },
    servingGuide: { glassware: "Small white-wine or dessert-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Pour a modest chilled serving after dinner; avoid serving it warm with an equally sweet dish." },
    foodPairings: ["qubani ka meetha", "gulab jamun", "baked cheesecake", "blue cheese with walnuts"],
    whyBuyThis: "A Nashik dessert wine whose sweetness has enough acidity to sit beside syrupy Indian desserts.",
    faqs: [{ question: "Is Sula Late Harvest Chenin sparkling?", answer: "No. Sula describes it as a still, sweet dessert wine." }, { question: "Which grape is used?", answer: "The producer lists 100% Chenin Blanc." }],
    metaTitle: "Sula Late Harvest Chenin Price, Taste & Review | BevOry", metaDescription: "Sula Late Harvest Chenin offers apricot, mango and raisin sweetness. Try it with qubani ka meetha; check indicative city prices on BevOry."
  },
  "sula-dia-white-sparkler-12d120b": {
    productName: "Sula Dia White Sparkler", category: "Indian Semi-Sparkling Chenin Blanc Wine",
    shortOverview: "Dia White Sparkler is a light, gently fizzy, slightly sweet white. White flowers and honeysuckle make it a softer introduction to bubbles than a bone-dry brut.",
    craftStory: "Sula makes Dia White from Chenin Blanc in its Maharashtra wine programme. The wine follows a sweet, semi-sparkling style; its canned format helped introduce Indian drinkers to individual wine servings.",
    tastingNotes: { nose: "Honeysuckle, white flowers and fresh pear.", palate: "Lightly fizzy and softly sweet, with Chenin fruit and a refreshing lift.", finish: "Short to medium, with floral fruit and a clean sweet edge." },
    servingGuide: { glassware: "Small tulip sparkling-wine glass", idealTemperature: "Well chilled (6–8°C)", recommendation: "Chill the can or bottle before opening and pour gently to keep the light fizz." },
    foodPairings: ["onion pakora", "vegetable spring rolls", "sweet-and-sour chicken", "paneer tikka with green chutney"],
    whyBuyThis: "Its floral Chenin fruit and gentle sparkle are easy to pair with spicy snacks.",
    faqs: [{ question: "Is Dia White Sparkler dry?", answer: "No. Sula describes the wine as light, sweet and semi-sparkling." }, { question: "What grape is in Dia White?", answer: "Sula lists 100% Chenin Blanc." }],
    metaTitle: "Sula Dia White Sparkler Price, Taste & Review | BevOry", metaDescription: "Sula Dia White Sparkler brings floral, gently sweet Chenin bubbles. Pair with pakoras; check indicative city prices on BevOry."
  },
  "sula-dia-red-sparkler-6d85daa": {
    productName: "Sula Dia Red Sparkler", category: "Indian Semi-Sparkling Red Wine",
    shortOverview: "Dia Red Sparkler is a lightly fizzy red-fruit wine with a sweet edge. It suits samosas and dabeli better than the heavier roast-food pairings of a tannic red.",
    craftStory: "Sula blends Chenin Blanc with a small share of Shiraz for this Nashik Valley sparkler. The Shiraz brings its red-fruit character and colour, while the light semi-sparkling style stays refreshing.",
    tastingNotes: { nose: "Fresh red berries and a soft cherry note.", palate: "Light-bodied, lightly sweet and gently fizzy, with juicy red fruit.", finish: "Short to medium, leaving berry fruit and a little sweetness." },
    servingGuide: { glassware: "Small tulip sparkling-wine glass", idealTemperature: "Well chilled (6–8°C)", recommendation: "Serve cold with hot snacks; pour from a chilled can or bottle without adding ice." },
    foodPairings: ["vegetable samosa", "dabeli", "Chicken Manchurian", "chilli paneer"],
    whyBuyThis: "A snack-friendly red sparkler with very little of the tannic grip of still red wine.",
    faqs: [{ question: "Is Dia Red a still red wine?", answer: "No. It is semi-sparkling, with a light fizz." }, { question: "Which grapes are used?", answer: "Sula lists Chenin Blanc and Shiraz; the published blend is predominantly Chenin." }],
    metaTitle: "Sula Dia Red Sparkler Price, Taste & Review | BevOry", metaDescription: "Sula Dia Red Sparkler offers lightly sweet berry bubbles. Pair with samosas or dabeli; check indicative city prices on BevOry."
  },
  "sula-dindori-shiraz-reserve-06d89bd": {
    productName: "Sula Dindori Reserve Shiraz", category: "Oak-Aged Indian Shiraz Red Wine",
    shortOverview: "Dindori Reserve Shiraz is smoky and spicy, with cherry fruit under vanilla from oak. It has the structure to accompany laal maas or charcoal-grilled kebabs.",
    craftStory: "Sula grows the fruit around Dindori in the Nashik region and blends Shiraz with a small Cabernet Sauvignon component. The producer specifies 10–12 months in American oak barrels, giving the wine its pronounced vanilla and toast.",
    tastingNotes: { nose: "Cherry, red berries, smoke, vanilla and baking spice.", palate: "Full-bodied and dry, with dark cherry, oak spice and firm but rounded tannin.", finish: "Long, leaving smoke, vanilla and red-fruit spice." },
    servingGuide: { glassware: "Large red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Pour beside a rich main course; give a young bottle about 20 minutes in the glass." },
    foodPairings: ["laal maas", "mutton seekh kebab", "tandoori chicken", "lamb chops"],
    whyBuyThis: "Dindori fruit and American-oak ageing give this Shiraz a distinct smoky-spice profile.",
    faqs: [{ question: "Is this wine aged in oak?", answer: "Yes. Sula specifies 10–12 months in American oak barrels." }, { question: "Is it pure Shiraz?", answer: "The producer allows a small Cabernet Sauvignon component; proportions can vary by release." }],
    metaTitle: "Sula Dindori Reserve Shiraz Price, Taste & Review | BevOry", metaDescription: "Sula Dindori Reserve Shiraz brings cherry, smoke and American-oak vanilla. Pair with laal maas; check city prices on BevOry."
  },
  "sula-cabernet-shiraz-f470d2e": {
    productName: "Sula Shiraz Cabernet", category: "Indian Shiraz-Cabernet Red Wine",
    shortOverview: "Sula Shiraz Cabernet combines ripe black fruit with olive, pepper and mocha notes. Its supple texture makes it a flexible red for medium-spiced Indian food.",
    craftStory: "Sula blends Shiraz and Cabernet Sauvignon for this Nashik Valley staple. The Shiraz-led construction brings ripe dark fruit, while Cabernet adds a little structure around its smooth texture.",
    tastingNotes: { nose: "Blackberry, black plum, ripe cherry, olive and pepper.", palate: "Smooth and medium-bodied, with ripe dark fruit, mocha and gentle spice.", finish: "Medium, carrying pepper and dark cherry." },
    servingGuide: { glassware: "Medium-bowl red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Serve slightly cool rather than warm, with a moderately spiced main." },
    foodPairings: ["chicken tikka masala", "rajma masala", "mutton rogan josh", "barbecued paneer"],
    whyBuyThis: "Its soft Shiraz-led fruit and savoury edge work across vegetarian and meat curries.",
    faqs: [{ question: "What grapes are in Sula Shiraz Cabernet?", answer: "Shiraz and Cabernet Sauvignon; check the bottle for the release-specific blend." }, { question: "Is it very tannic?", answer: "Sula presents a smooth, food-friendly style rather than a heavily grippy one." }],
    metaTitle: "Sula Shiraz Cabernet Price, Taste & Review | BevOry", metaDescription: "Sula Shiraz Cabernet offers black plum, cherry, pepper and mocha. Pair with rajma or rogan josh; check city prices on BevOry."
  },
  "sula-zinfandel-rose-wine-21b779f": {
    productName: "Sula Zinfandel Rosé", category: "Indian Zinfandel Rosé Wine",
    shortOverview: "Sula Zinfandel Rosé offers citrus and cranberry brightness in a light pink wine. It belongs with a chilled starter plate rather than a heavy red-wine dinner.",
    craftStory: "Sula uses Zinfandel grapes for this Nashik Valley rosé. Brief colour extraction from the red grape produces a pink wine whose fresh fruit and acidity take priority over barrel character.",
    tastingNotes: { nose: "Cranberry, ripe red fruit and citrus peel.", palate: "Light, juicy and refreshing, with red-berry fruit and lively acidity.", finish: "Medium and clean, leaving cranberry and a citrus flicker." },
    servingGuide: { glassware: "Rosé or white-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool with mildly spiced fish or a vegetable starter." },
    foodPairings: ["tandoori prawns", "rava-fried fish", "malai paneer tikka", "cucumber chaat"],
    whyBuyThis: "A bright Indian rosé that keeps Zinfandel fruit light enough for seafood and summer snacks.",
    faqs: [{ question: "Is Zinfandel Rosé the same as Sula Zinfandel red?", answer: "No. Both use Zinfandel, but this is a lighter pink wine made for chilled service." }, { question: "Should it be served cold?", answer: "Yes. Around 8–10°C keeps the fruit and acidity in balance." }],
    metaTitle: "Sula Zinfandel Rosé Price, Taste & Review | BevOry", metaDescription: "Sula Zinfandel Rosé brings cranberry and citrus freshness. Pair with tandoori prawns; check indicative city prices on BevOry."
  },
  "sula-dindori-viogner-7d4c84d": {
    productName: "Sula Dindori Viognier", category: "Indian Viognier White Wine",
    shortOverview: "Dindori Reserve Viognier is a textured white led by apricot, peach and lychee. Its gentle acidity makes it particularly comfortable beside a creamy curry.",
    craftStory: "Sula grows Viognier at its Dindori estate near Nashik and uses it alone for this Reserve white. The producer stresses aromatic fruit and smooth texture rather than claiming an oak-barrel regime for this wine.",
    tastingNotes: { nose: "Apricot, ripe peach, lychee and soft flowers.", palate: "Medium-bodied and rounded, with stone fruit, floral lift and mild acidity.", finish: "Medium and smooth, leaving peach and lychee." },
    servingGuide: { glassware: "Medium-bowl white-wine glass", idealTemperature: "Chilled (9–11°C)", recommendation: "Serve cool, not icy, so the apricot and floral notes remain clear." },
    foodPairings: ["Goan chicken xacuti", "butter-garlic prawns", "malai paneer tikka", "roasted root vegetables"],
    whyBuyThis: "Dindori-grown Viognier brings stone-fruit aroma and enough texture for creamy Indian food.",
    faqs: [{ question: "Which grape makes Dindori Viognier?", answer: "Sula lists 100% Viognier." }, { question: "Is this an acidic white?", answer: "It is less sharp than many Sauvignon Blancs, with a rounder texture." }],
    metaTitle: "Sula Dindori Viognier Price, Taste & Review | BevOry", metaDescription: "Sula Dindori Viognier offers apricot, peach and lychee. Pair with Goan xacuti or prawns; check city prices on BevOry."
  },
  "sula-sula-rasa-syrah-73a6f0c": {
    productName: "Sula RĀSĀ Syrah", category: "French-Oak-Aged Indian Syrah Red Wine",
    shortOverview: "RĀSĀ Syrah is Sula's richer red, with dark berries, pepper, mocha and a firmer frame than its everyday Shiraz Cabernet. It calls for a savoury meal and a little time in the glass.",
    craftStory: "Sula combines Syrah with a small amount of Viognier from its Nashik vineyard programme. Selected fruit matures for 12–14 months in French oak, building vanilla and mocha around the wine's dark fruit.",
    tastingNotes: { nose: "Blackberry, red berries, pepper, vanilla and mocha.", palate: "Full-bodied and dry, with concentrated fruit, supple tannin and oak spice.", finish: "Long, leaving dark berries, pepper and cocoa-like oak." },
    servingGuide: { glassware: "Large red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Give it 20–30 minutes of air before serving with a slow-cooked main." },
    foodPairings: ["nalli nihari", "chicken tandoori tikka", "paneer tandoori tikka", "lamb rogan josh"],
    whyBuyThis: "Syrah-Viognier blending and extended French-oak ageing make it a serious Nashik red.",
    faqs: [{ question: "Does RĀSĀ Syrah include Viognier?", answer: "Yes. Sula lists a small Viognier component alongside Syrah." }, { question: "Which oak is used?", answer: "The producer specifies French oak for 12–14 months." }],
    metaTitle: "Sula RĀSĀ Syrah Price, Taste & Review | BevOry", metaDescription: "Sula RĀSĀ Syrah brings berries, pepper and French-oak mocha. Pair with nalli nihari; check indicative city prices on BevOry."
  },
  "sula-seco-rose-634faf7": {
    productName: "Sula Seco Rosé", category: "Indian Sparkling Rosé Wine",
    shortOverview: "Seco Rosé is a light, fruity sparkling pink wine with nectarine and watermelon. Its gentle sweetness and fizz suit salty, fried snacks.",
    craftStory: "Sula's published portfolio describes a Chenin Blanc-led blend with a small Shiraz share. It is a fruit-first Maharashtra sparkler, distinct from the producer's darker Sparkling Shiraz.",
    tastingNotes: { nose: "Nectarine, watermelon and pale orchard fruit.", palate: "Light-bodied and gently sweet, with soft bubbles and fresh fruit.", finish: "Medium, leaving watermelon and a clean fruity lift." },
    servingGuide: { glassware: "Tulip sparkling-wine glass", idealTemperature: "Well chilled (6–8°C)", recommendation: "Serve straight from a chilled bottle with crisp fried food; pour slowly to preserve bubbles." },
    foodPairings: ["onion pakora", "fish fingers", "honey-chilli potato", "crispy fried chicken"],
    whyBuyThis: "A lighter, more snack-friendly rosé sparkler than a full-bodied sparkling red.",
    faqs: [{ question: "Is Seco Rosé the same as Sula Seco?", answer: "No. Rosé includes red-grape fruit and has a pink colour; Seco is a white Chenin sparkler." }, { question: "Is it very dry?", answer: "Sula's profile places it toward a softly sweet, fruit-led style." }],
    metaTitle: "Sula Seco Rosé Price, Taste & Review | BevOry", metaDescription: "Sula Seco Rosé has nectarine, watermelon and soft bubbles. Pair with pakoras; check indicative city prices on BevOry."
  },
  "sula-chenin-reserve-3e904e4": {
    productName: "Sula Chenin Reserve", category: "Part-Oaked Indian Chenin Blanc White Wine",
    shortOverview: "Chenin Reserve keeps the grape's tropical fruit while adding a little French-oak roundness. It is more textured than Sula's simple, off-dry Chenin Blanc.",
    craftStory: "Sula makes this Chenin Blanc in its Nashik wine programme. Producer material describes a small portion of the blend spending time in French oak, adding honeyed texture without turning the wine into an overtly woody white.",
    tastingNotes: { nose: "Melon, pear, pineapple and light honey.", palate: "Medium-bodied, with concentrated tropical fruit, gentle oak roundness and fresh acidity.", finish: "Medium and lively, leaving honeyed fruit and citrus." },
    servingGuide: { glassware: "Medium-bowl white-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool with herby chicken or fish curry; excessive chilling hides its texture." },
    foodPairings: ["Goan fish curry", "chicken hariyali tikka", "paneer tikka", "spinach-ricotta ravioli"],
    whyBuyThis: "A measured oak contribution gives Chenin more body without sacrificing freshness.",
    faqs: [{ question: "Is Chenin Reserve fully barrel-aged?", answer: "No. Sula describes French-oak ageing for only a small portion of the blend." }, { question: "How does it differ from regular Sula Chenin Blanc?", answer: "Reserve is more concentrated and lightly oak-textured; the regular wine is simpler and fruitier." }],
    metaTitle: "Sula Chenin Reserve Price, Taste & Review | BevOry", metaDescription: "Sula Chenin Reserve mixes pineapple, honey and gentle French oak. Pair with fish curry; check indicative city prices on BevOry."
  },
  "yellow-tail-chardonnay-1c92bd4": {
    productName: "Yellow Tail Chardonnay", category: "Australian Chardonnay White Wine",
    shortOverview: "Yellow Tail Chardonnay is a smooth, peach-and-melon white with a creamy close. It suits roast chicken and mild Indian gravies better than a fiercely acidic white.",
    craftStory: "Casella Family Brands makes Yellow Tail in Australia, drawing on the country's broad Chardonnay plantings. The producer notes vanilla and light spice in this label but does not promise a fixed barrel schedule across releases.",
    tastingNotes: { nose: "White peach, melon, light spice and vanilla.", palate: "Silky and medium-bodied, moving from fresh peach to melon and soft vanilla.", finish: "Medium and creamy, with peach and a gentle vanilla note." },
    servingGuide: { glassware: "Medium-bowl white-wine glass", idealTemperature: "Chilled (9–11°C)", recommendation: "Serve cool with roast poultry or a mild cream-based dish." },
    foodPairings: ["chicken malai tikka", "butter-garlic prawns", "roast chicken", "paneer in white gravy"],
    whyBuyThis: "Peach-led fruit and a creamy finish make this Australian Chardonnay easy to place at dinner.",
    faqs: [{ question: "Is Yellow Tail Chardonnay a sweet dessert wine?", answer: "No. Its fruit is ripe and soft, but the producer presents it as a table white." }, { question: "What are its main flavours?", answer: "Yellow Tail lists peach, melon and a hint of vanilla." }],
    metaTitle: "Yellow Tail Chardonnay Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Chardonnay offers peach, melon and a creamy finish. Pair with malai tikka; check indicative city prices on BevOry."
  },
  "yellow-tail-red-moscato-5d749cb": {
    productName: "Yellow Tail Red Moscato", category: "Australian Sweet Semi-Sparkling Red Wine",
    shortOverview: "Red Moscato is sweet, lightly fizzy and packed with raspberry and cherry. It is a chilled alternative for people who find dry red wine too tannic.",
    craftStory: "Yellow Tail makes this Moscato-style red in Australia as part of its fruit-led range. The gentle bubbles and retained sweetness define the style rather than oak ageing or a dry Cabernet-like structure.",
    tastingNotes: { nose: "Fresh raspberry, cranberry and a cherry accent.", palate: "Light and softly fizzy, with sweet strawberry, raspberry and cherry.", finish: "Short to medium, refreshing with red-berry sweetness." },
    servingGuide: { glassware: "Small tulip or white-wine glass", idealTemperature: "Well chilled (6–8°C)", recommendation: "Serve cold with a spicy snack or fruit dessert; do not warm it like a full-bodied red." },
    foodPairings: ["chilli paneer", "spicy chicken wings", "strawberry tart", "dabeli"],
    whyBuyThis: "Its low-tannin berry sweetness offers an easy entry to chilled red wine.",
    faqs: [{ question: "Is Red Moscato dry?", answer: "No. Yellow Tail describes it as a little sweet and a little fizzy." }, { question: "Should it be chilled?", answer: "Yes. Cold service highlights its refreshing fizz and berry fruit." }],
    metaTitle: "Yellow Tail Red Moscato Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Red Moscato has sweet raspberry, cranberry and light fizz. Pair with chilli paneer; check city prices on BevOry."
  },
  "yellow-tail-white-moscato-8ccb6b6": {
    productName: "Yellow Tail Moscato", category: "Australian Sweet Semi-Sparkling White Wine",
    shortOverview: "Yellow Tail Moscato is a lightly fizzy, sweet white with passion fruit and melon. It is brighter and less berry-led than the producer's Red Moscato.",
    craftStory: "Casella Family Brands makes this Australian Moscato in a fresh, fruit-first style. Yellow Tail describes white peach, orange blossom and a soft palate, without claiming a barrel-matured character.",
    tastingNotes: { nose: "White peach, passion fruit and orange blossom.", palate: "Light and gently fizzy, with sweet kiwi, melon and passion fruit.", finish: "Short to medium, zesty and fruit-sweet." },
    servingGuide: { glassware: "Small white-wine glass", idealTemperature: "Well chilled (6–8°C)", recommendation: "Serve cold beside spicy food; the sweetness softens chilli heat." },
    foodPairings: ["chilli chicken", "vegetable spring rolls", "spicy corn chaat", "mango shrikhand"],
    whyBuyThis: "Floral fruit and gentle fizz make it an uncomplicated partner for spicy snacks.",
    faqs: [{ question: "Is Yellow Tail Moscato sweet?", answer: "Yes. It is a sweet, lightly fizzy white." }, { question: "Is it the same as Red Moscato?", answer: "No. This white style focuses on peach, passion fruit and melon rather than red berries." }],
    metaTitle: "Yellow Tail Moscato Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Moscato brings peach, passion fruit and gentle fizz. Pair with chilli chicken; check indicative city prices on BevOry."
  },
  "yellow-tail-whisky-barrel-aged-cab-sauv-0bd924d": {
    productName: "Yellow Tail Whisky Cask Cab", category: "Whisky-Barrel-Finished Australian Cabernet Wine",
    shortOverview: "This Cabernet adds cigar-box, malt and vanillin-oak accents to blackcurrant fruit. A whisky-seasoned barrel finish changes the wine's texture without making it a whisky cocktail.",
    craftStory: "Yellow Tail prepares Australian oak barrels with Australian single malt whisky, empties them, then holds Cabernet Sauvignon wine in the seasoned wood for at least 30 days. The final wine remains a Cabernet Sauvignon, with a smooth oak-led finish.",
    tastingNotes: { nose: "Blackcurrant, black cherry, plum, cigar box and subtle malt.", palate: "Full-bodied and supple, with dark fruit, spicy vanilla and softened tannin.", finish: "Long and velvety, trailing vanilla, oak and black fruit." },
    servingGuide: { glassware: "Bordeaux glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Pour with grilled lamb or tomato-rich food; let the wine breathe briefly." },
    foodPairings: ["mutton seekh kebab", "lamb chops", "tandoori mushrooms", "tomato-based pasta"],
    whyBuyThis: "The seasoned Australian oak gives Cabernet an unusual malt-and-vanilla edge.",
    faqs: [{ question: "Does the wine contain whisky?", answer: "No whisky is blended into the wine; the barrel is seasoned with whisky before the wine enters it." }, { question: "How long does it spend in whisky barrels?", answer: "Yellow Tail states at least 30 days for its whiskey-barrel range." }],
    metaTitle: "Yellow Tail Whisky Cask Cab Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Whisky Cask Cab layers blackcurrant, vanilla and oak. Pair with seekh kebabs; check indicative city prices on BevOry."
  },
  "yellow-tail-cabernet-sauvignon-8337631": {
    productName: "Yellow Tail Cabernet", category: "Australian Cabernet Sauvignon Red Wine",
    shortOverview: "Yellow Tail Cabernet Sauvignon has blackcurrant, blackberry and a sweet-mocha accent. Its velvety texture makes it less stern than many young Cabernets.",
    craftStory: "Casella Family Brands produces this Australian Cabernet as a drink-now red. Its producer profile focuses on ripe fruit and spice rather than a single named vineyard or a fixed barrel specification.",
    tastingNotes: { nose: "Blackcurrant, blackberry, red fruit and sweet mocha.", palate: "Velvety and medium-full, with juicy blackcurrant, cocoa and spice.", finish: "Medium, with fruit, mocha and a light peppery close." },
    servingGuide: { glassware: "Bordeaux glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Pour beside a hearty meal; a brief rest in the glass softens the fruit-tannin edge." },
    foodPairings: ["tandoori lamb chops", "mutton keema", "mushroom kebab", "roast beef"],
    whyBuyThis: "Ripe Cabernet fruit with an easy texture suits a weeknight roast or kebab spread.",
    faqs: [{ question: "Is this the Reserve Cabernet?", answer: "No. Reserve is a separate Yellow Tail range with longer oak contact." }, { question: "What leads the flavour?", answer: "The producer names blackcurrant, mocha and spice." }],
    metaTitle: "Yellow Tail Cabernet Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Cabernet offers blackcurrant, mocha and velvety tannins. Pair with lamb kebabs; check city prices on BevOry."
  },
  "yellow-tail-reserve-shiraz-35424f5": {
    productName: "Yellow Tail Reserve Shiraz", category: "Oak-Matured Australian Shiraz Red Wine",
    shortOverview: "Reserve Shiraz is a richer Yellow Tail red, with dark cherry, black pepper and chocolate. Oak adds cedar and vanilla to its generous fruit.",
    craftStory: "Yellow Tail selects premium Australian fruit for its Reserve range and matures the wines in contact with oak for six to nine months. Its Shiraz is built for a darker, more persistent profile than the standard bottling.",
    tastingNotes: { nose: "Ripe berry, dark cherry, black pepper, vanilla and cedar.", palate: "Rich dark fruit and spice, with a dark-chocolate note and rounded tannin.", finish: "Long and velvety, leaving cherry, cocoa and oak spice." },
    servingGuide: { glassware: "Large red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Serve with braised or grilled food; give it a short rest after pouring." },
    foodPairings: ["mutton ghee roast", "tandoori lamb chops", "chicken tikka", "70% dark chocolate"],
    whyBuyThis: "Extra oak time and concentrated fruit distinguish it from standard Yellow Tail Shiraz.",
    faqs: [{ question: "What makes Reserve different?", answer: "Yellow Tail describes selected fruit and six to nine months of oak contact for the Reserve range." }, { question: "Is this an Australian Shiraz?", answer: "Yes. Yellow Tail produces the wine in Australia." }],
    metaTitle: "Yellow Tail Reserve Shiraz Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Reserve Shiraz layers dark cherry, pepper, cedar and chocolate. Pair with mutton roast; check city prices on BevOry."
  },
  "yellow-tail-reserve-cabernet-sauvignon-39c5896": {
    productName: "Yellow Tail Reserve Cab", category: "Oak-Matured Australian Cabernet Sauvignon",
    shortOverview: "Reserve Cabernet is full-bodied, with blackcurrant, blueberry and cinnamon around supple tannin. It offers more oak influence than Yellow Tail's standard Cabernet.",
    craftStory: "Yellow Tail makes its Reserve wines from selected Australian fruit and gives the range six to nine months of oak contact. The Cabernet's wood influence supports rather than replaces its dark-fruit core.",
    tastingNotes: { nose: "Blackcurrant, dark cherry, fruitcake and light cinnamon.", palate: "Full and generous, with blueberry, cherry and soft tannins.", finish: "Long, soft and spicy, leaving dark fruit and oak." },
    servingGuide: { glassware: "Bordeaux glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Pour with slow-braised meat or smoky vegetables; avoid serving it hot." },
    foodPairings: ["mutton rogan josh", "lamb chops", "tandoori mushrooms", "braised beef"],
    whyBuyThis: "Selected fruit and measured oak give a fuller, softer Cabernet than the basic range.",
    faqs: [{ question: "Is Reserve Cabernet the same as the whisky-barrel wine?", answer: "No. The whisky-barrel bottling uses specially seasoned barrels; Reserve is a separate oak-matured range." }, { question: "How long is the Reserve range in oak?", answer: "Yellow Tail describes six to nine months of oak contact for the range." }],
    metaTitle: "Yellow Tail Reserve Cab Price, Taste & Review | BevOry", metaDescription: "Yellow Tail Reserve Cab offers blackcurrant, blueberry and soft oak spice. Pair with rogan josh; check city prices on BevOry."
  },
  "grover-la-reserva-white-0f09002": {
    productName: "Grover La Réserve Blanc", category: "Barrel-Fermented Indian Viognier White Wine",
    shortOverview: "La Réserve Blanc is a rich Viognier with apricot, honeysuckle and a quiet oak note. It has more body and lees texture than Grover's everyday whites.",
    craftStory: "Grover Zampa hand-picks Viognier from a selected Indian vineyard parcel, bunch-presses it, and ferments the wine in French oak barrels. Ageing on lees adds breadth beneath the tropical fruit.",
    tastingNotes: { nose: "Honeysuckle, apricot and pineapple.", palate: "Rich and powerful, with tropical fruit, citrus and soft oak texture.", finish: "Long, with pineapple, citrus and gentle wood." },
    servingGuide: { glassware: "Medium-bowl white-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool with tandoori seafood or a creamy but not overly hot curry." },
    foodPairings: ["malai chicken tikka", "tandoori crab", "vegetable biryani", "grilled fish with lemon butter"],
    whyBuyThis: "Barrel fermentation and lees ageing give Indian Viognier serious texture without losing its flowers and fruit.",
    faqs: [{ question: "Is La Réserve Blanc made from Chardonnay?", answer: "No. Grover identifies Viognier as the grape." }, { question: "Does it see oak?", answer: "Yes. The producer describes barrel fermentation and ageing in French oak." }],
    metaTitle: "Grover La Réserve Blanc Price, Taste & Review | BevOry", metaDescription: "Grover La Réserve Blanc brings apricot, honeysuckle and soft French oak. Pair with malai tikka; check city prices on BevOry."
  },
  "grover-la-reserves-syrah-grencha-red-e9e238e": {
    productName: "Grover Syrah Grenache", category: "French-Oak-Aged Indian Red Wine Blend",
    shortOverview: "This La Réserve blend is dark and structured, with black cherry, pepper and floral lift. Grenache adds a different shape to Grover's Cabernet-Shiraz red.",
    craftStory: "Grover Zampa blends Syrah and Grenache for this Indian La Réserve wine. The producer specifies fermentation and six months of ageing in French oak barrels, bringing vanilla and sweet spice to the dark fruit.",
    tastingNotes: { nose: "Black cherry, black pepper, flowers and vanilla.", palate: "Full-bodied and rich, with black fruit, sweet oak spice and firm tannins.", finish: "Long and dry, leaving cherry, pepper and oak." },
    servingGuide: { glassware: "Large red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Give a young bottle some air and serve with grilled meat or a slow-cooked curry." },
    foodPairings: ["lamb seekh kebab", "mutton biryani", "pepper mushroom stew", "lamb rogan josh"],
    whyBuyThis: "Syrah-Grenache fruit and six months in French oak make it a powerful Indian dinner red.",
    faqs: [{ question: "Is this the standard La Réserve red?", answer: "No. This entry is Syrah Grenache; the original La Réserve red is Cabernet Sauvignon-Shiraz." }, { question: "How long is it aged in oak?", answer: "Grover specifies six months in French oak barrels." }],
    metaTitle: "Grover Syrah Grenache Price, Taste & Review | BevOry", metaDescription: "Grover Syrah Grenache offers black cherry, pepper and French-oak vanilla. Pair with mutton biryani; check city prices on BevOry."
  },
  "grover-chene-grand-reserv-chardonnay-7825485": {
    productName: "Grover Chêne Chardonnay", category: "French-Oak-Aged Indian Chardonnay",
    shortOverview: "Chêne Chardonnay is a creamy, full white with apple, pear and green plum. French oak adds hazelnut, vanilla and toasted richness.",
    craftStory: "Grover Zampa ferments and ages Chardonnay in French oak for this Indian Chêne release. The producer describes a roughly nine-month making period, producing a more structured wine than a simple stainless-steel Chardonnay.",
    tastingNotes: { nose: "Nectarine, hazelnut, vanilla and crème brûlée.", palate: "Full and creamy, with apple, pear, green plum, bright acidity and toast.", finish: "Long, leaving orchard fruit, vanilla and gentle oak." },
    servingGuide: { glassware: "Medium-bowl Chardonnay glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool rather than icy to let its oak and orchard-fruit detail emerge." },
    foodPairings: ["butter-garlic prawns", "malai paneer tikka", "grilled fish", "mushroom risotto"],
    whyBuyThis: "French-oak fermentation gives this Indian Chardonnay a concentrated, creamy profile.",
    faqs: [{ question: "Is Chêne Chardonnay oaked?", answer: "Yes. Grover says it is fermented and aged in French oak barrels." }, { question: "How cold should it be?", answer: "The producer recommends 8–10°C." }],
    metaTitle: "Grover Chêne Chardonnay Price, Taste & Review | BevOry", metaDescription: "Grover Chêne Chardonnay layers apple, pear, hazelnut and French oak. Pair with butter-garlic prawns; check city prices on BevOry."
  },
  "grover-chenne-9ae4525": {
    productName: "Grover Chêne Red", category: "French-Oak-Aged Indian Tempranillo-Shiraz Red",
    shortOverview: "Chêne Grand Reserve is a deep-ruby red with black fruit, cinnamon and coffee-bean oak. It has the weight for slow braises and grilled kebabs.",
    craftStory: "Grover Zampa blends Tempranillo and Shiraz for Chêne Grand Reserve. The producer specifies at least 15 months in French oak barrels, building vanilla, liquorice and roasted-coffee detail around the fruit.",
    tastingNotes: { nose: "Blackberry, currant, ripe plum, cinnamon and vanilla.", palate: "Full and structured, with dark fruit, balanced tannin, liquorice and chocolate.", finish: "Long, with coffee bean, oak spice and ripe plum." },
    servingGuide: { glassware: "Large red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Decant a young bottle briefly and serve alongside a substantial savoury main." },
    foodPairings: ["mutton ghee roast", "baingan bharta", "tandoori lamb chops", "mushroom biryani"],
    whyBuyThis: "Extended French-oak ageing gives the Tempranillo-Shiraz blend a notably layered finish.",
    faqs: [{ question: "Which grapes make Chêne Grand Reserve?", answer: "Grover lists Tempranillo and Shiraz." }, { question: "How long is it in oak?", answer: "The producer says a minimum of 15 months in French oak barrels." }],
    metaTitle: "Grover Chêne Red Price, Taste & Review | BevOry", metaDescription: "Grover Chêne Red offers plum, cinnamon, chocolate and French-oak coffee. Pair with lamb chops; check city prices on BevOry."
  },
  "grover-la-reserve-bourgogne-pinot-noir-e509b13": {
    productName: "Grover La Réserve Pinot", category: "French Bourgogne Pinot Noir Red Wine",
    shortOverview: "This La Réserve Pinot Noir is a French Bourgogne wine, not an Indian-grown Grover red. Strawberry, raspberry and floral notes meet grippy but measured tannin.",
    craftStory: "Grover's La Réserve Pinot Noir comes through a partnership with Château d'Etroyes in Bourgogne's Côte Chalonnaise. The producer cites fruit from Mercurey and Rully vineyards and a year in French oak barrels.",
    tastingNotes: { nose: "Floral red berries and soft oak.", palate: "Medium-bodied, with strawberry, raspberry and finely grippy tannin.", finish: "Medium-long, trailing red fruit and light wood spice." },
    servingGuide: { glassware: "Burgundy or wide-bowl red-wine glass", idealTemperature: "Cool room temperature (15–17°C)", recommendation: "Serve slightly cool with mild poultry or a gently spiced minced-meat dish." },
    foodPairings: ["mutton keema", "paneer tikka", "mild chicken curry", "roast duck"],
    whyBuyThis: "A Côte Chalonnaise Pinot Noir under Grover's La Réserve banner offers a clear contrast to its Indian reds.",
    faqs: [{ question: "Is this Pinot Noir made in India?", answer: "No. Grover identifies it as a Bourgogne Côte Chalonnaise wine from France." }, { question: "Does it spend time in oak?", answer: "Yes. The producer describes one year in French oak barrels." }],
    metaTitle: "Grover La Réserve Pinot Price, Taste & Review | BevOry", metaDescription: "Grover La Réserve Pinot offers French red berries, flowers and soft oak. Pair with mutton keema; check city prices on BevOry."
  },
  "grover-grovers-la-reserve-chardonnay-2a5d9e6": {
    productName: "Grover La Réserve Chardonnay", category: "French Bourgogne Chardonnay White Wine",
    shortOverview: "This La Réserve Chardonnay comes from Bourgogne's Côte Chalonnaise rather than Grover's Indian vineyards. Peach and melon sit over full texture and crisp acidity.",
    craftStory: "Grover's French partnership with Château d'Etroyes sources Chardonnay from Mercurey and Rully. The producer describes a year in French oak barrels, giving the wine structure and a soft oak note.",
    tastingNotes: { nose: "Fresh peach, melon, tropical fruit and lemon zest.", palate: "Rich and full, with stone fruit, soft oak and balancing acidity.", finish: "Long, leaving citrus, ripe fruit and gentle wood." },
    servingGuide: { glassware: "Medium-bowl Chardonnay glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool with creamy fish or chicken; avoid over-chilling the oak character." },
    foodPairings: ["chicken malai tikka", "tandoori lobster", "vegetable biryani", "fish in lemon-butter sauce"],
    whyBuyThis: "French Chardonnay origin and a year in oak distinguish it from Grover's Indian Chêne Chardonnay.",
    faqs: [{ question: "Is La Réserve Chardonnay Indian wine?", answer: "No. Grover identifies Côte Chalonnaise fruit from France for this label." }, { question: "How is it different from Chêne Chardonnay?", answer: "La Réserve is sourced from Bourgogne; Chêne Chardonnay is an Indian wine in Grover's own range." }],
    metaTitle: "Grover La Réserve Chardonnay Price, Taste & Review | BevOry", metaDescription: "Grover La Réserve Chardonnay offers French peach, melon and soft oak. Pair with malai tikka; check city prices on BevOry."
  },
  "grover-la-reserve-brut-a9bdf83": {
    productName: "Grover La Réserve Brut", category: "Indian Reserve Chenin Blanc Sparkling Wine",
    shortOverview: "La Réserve Royale Brut is a pale-gold sparkling Chenin with lemon zest, brioche and hazelnut. Its lees-derived savouriness sets it apart from a simple sweet sparkler.",
    craftStory: "Grover Zampa introduced Royale Brut for its 30th anniversary. Premium Chenin Blanc is partly fermented in French oak and spends more than 30 months on lees, building fine bubbles and bakery notes.",
    tastingNotes: { nose: "Lemon zest, white flowers, hazelnut and brioche.", palate: "Delicate, persistent bubbles with citrus, mineral freshness and creamy depth.", finish: "Long and mineral, with lemon and a faint pastry trace." },
    servingGuide: { glassware: "Tulip sparkling-wine glass", idealTemperature: "Well chilled (6°C)", recommendation: "Open cold and pour carefully with savoury starters; do not add ice." },
    foodPairings: ["rava-fried fish", "tandoori prawns", "crispy fried chicken", "goat-cheese salad"],
    whyBuyThis: "Extended lees time gives Indian Chenin sparkling wine a complex, savoury edge.",
    faqs: [{ question: "Is La Réserve Royale Brut Champagne?", answer: "No. It is an Indian sparkling wine, not wine from the Champagne region of France." }, { question: "What grape is used?", answer: "Grover lists Chenin Blanc." }],
    metaTitle: "Grover La Réserve Brut Price, Taste & Review | BevOry", metaDescription: "Grover La Réserve Brut offers lemon, brioche and fine bubbles. Pair with fried fish; check indicative city prices on BevOry."
  },
  "fratelli-classic-merlot-825d3bc": {
    productName: "Fratelli Classic Merlot", category: "Indian Merlot Red Wine",
    shortOverview: "Classic Merlot is a soft, dark-plum red with a little chocolate and earth. It is an approachable Fratelli option when Cabernet tannin would overpower dinner.",
    craftStory: "Fratelli grows Merlot at its Akluj estate in Maharashtra for this Classic label. The producer describes varietal fruit and silky tannin, without specifying a fixed oak-ageing period for the release.",
    tastingNotes: { nose: "Ripe plum, dark chocolate and a mild earthy note.", palate: "Medium-bodied and rounded, with dark-plum fruit, silky tannin and pleasant acidity.", finish: "Medium, leaving plum and a faint cocoa note." },
    servingGuide: { glassware: "Medium-bowl red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Serve slightly cool with a mildly spiced meat or mushroom dish." },
    foodPairings: ["tandoori chicken", "mushroom kebab", "paneer tikka masala", "roast duck"],
    whyBuyThis: "Soft tannin and earthy plum make it a useful first step into Indian Merlot.",
    faqs: [{ question: "Is Fratelli Classic Merlot very tannic?", answer: "No. Fratelli describes silky tannins and an approachable medium body." }, { question: "What fruit dominates?", answer: "The producer highlights ripe dark plums." }],
    metaTitle: "Fratelli Classic Merlot Price, Taste & Review | BevOry", metaDescription: "Fratelli Classic Merlot gives dark plum, chocolate and silky tannin. Pair with mushroom kebabs; check city prices on BevOry."
  },
  "grover-one-tree-hill-red-498de93": {
    productName: "Grover One Tree Hill Red", category: "Indian Cabernet-Shiraz-Zinfandel Red Wine",
    shortOverview: "One Tree Hill Red is a smooth, dark-fruited blend with plum, blackcurrant and green pepper. It comes from Grover Zampa's Sahyadri Valley programme rather than the winery's Nandi Hills range.",
    craftStory: "Grover Zampa blends Cabernet Sauvignon, Shiraz and Zinfandel for this wine from Sanjegaon in Maharashtra. The solitary mango tree overlooking its vineyard inspired the One Tree Hill name; the producer does not specify a universal barrel-ageing period.",
    tastingNotes: { nose: "Plum, blackcurrant and spicy green pepper.", palate: "Rounded and balanced, with ripe dark fruit and smooth tannins.", finish: "Long, leaving cocoa and dark berry fruit." },
    servingGuide: { glassware: "Medium-bowl red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Serve with kebabs or a medium-spiced curry; keep the bottle out of direct heat." },
    foodPairings: ["mutton seekh kebab", "paneer tikka masala", "tandoori mushrooms", "tomato pasta"],
    whyBuyThis: "Three red grapes create an approachable Sahyadri blend with a savoury pepper edge.",
    faqs: [{ question: "Which grapes make One Tree Hill Red?", answer: "Grover lists Cabernet Sauvignon, Shiraz and Zinfandel." }, { question: "Where is it made?", answer: "The producer connects One Tree Hill to its Sanjegaon vineyards in Maharashtra's Sahyadri Valley." }],
    metaTitle: "Grover One Tree Hill Red Price, Taste & Review | BevOry", metaDescription: "Grover One Tree Hill Red offers plum, blackcurrant, pepper and cocoa. Pair with seekh kebabs; check city prices on BevOry."
  },
  "fratelli-classic-shiraz-58109ec": {
    productName: "Fratelli Classic Shiraz", category: "Indian Shiraz-Cabernet Franc Red Wine",
    shortOverview: "Classic Shiraz mixes black pepper, flowers and earthy leather with smooth tannin. It is fresher and less heavy than a long-oaked reserve red.",
    craftStory: "Fratelli's Akluj vineyards supply this Shiraz and Cabernet Franc blend. The producer presents it as an aromatic, balanced Classic wine and does not attach an unsupported barrel duration to the label.",
    tastingNotes: { nose: "Black pepper, floral notes, earth and a light leather edge.", palate: "Medium-bodied and smooth, with red-dark fruit, pepper and balanced tannin.", finish: "Medium and savoury, leaving pepper and gentle earth." },
    servingGuide: { glassware: "Medium-bowl red-wine glass", idealTemperature: "Cool room temperature (16–18°C)", recommendation: "Serve with kebabs or a spiced vegetable main; a brief chill can sharpen the fruit." },
    foodPairings: ["mutton seekh kebab", "tandoori mushrooms", "chicken tikka", "baingan bharta"],
    whyBuyThis: "Cabernet Franc brings a savoury edge to Fratelli's easy-drinking Shiraz.",
    faqs: [{ question: "Is Fratelli Classic Shiraz pure Shiraz?", answer: "No. The producer lists Shiraz and Cabernet Franc." }, { question: "Is it very oaky?", answer: "The published description focuses on fruit, pepper and earth rather than a heavy oak profile." }],
    metaTitle: "Fratelli Classic Shiraz Price, Taste & Review | BevOry", metaDescription: "Fratelli Classic Shiraz offers pepper, flowers and smooth tannin. Pair with seekh kebabs; check city prices on BevOry."
  },
  "fratelli-pinot-noir-wine-a43255c": {
    productName: "Fratelli Pinot Noir", category: "Indian Pinot Noir Red Wine",
    shortOverview: "Fratelli Pinot Noir favours cherry, rose and gentle spice over power. Its silky medium body suits poultry and lightly spiced food.",
    craftStory: "Fratelli grows Pinot Noir in its higher-altitude Indian vineyards and uses careful stainless-steel fermentation to protect freshness. The producer highlights red berries and floral nuance without asserting a long oak maturation.",
    tastingNotes: { nose: "Cherry, rose petals and a hint of forest floor.", palate: "Silky and medium-bodied, with ripe red berries, clove and cinnamon.", finish: "Medium-long and warm, trailing cherry and soft spice." },
    servingGuide: { glassware: "Burgundy or wide-bowl red-wine glass", idealTemperature: "Slightly cool (14–16°C)", recommendation: "Serve a touch cooler than a heavy Shiraz, with roast poultry or mild curry." },
    foodPairings: ["tandoori chicken", "mushroom kebab", "mild mutton keema", "roast duck"],
    whyBuyThis: "Its floral, red-fruit profile offers a lighter Indian red without losing dinner-table substance.",
    faqs: [{ question: "Is Fratelli Pinot Noir a heavy red?", answer: "No. The producer calls it silky and medium-bodied." }, { question: "What fermentation method is described?", answer: "Fratelli cites careful stainless-steel fermentation for this wine." }],
    metaTitle: "Fratelli Pinot Noir Price, Taste & Review | BevOry", metaDescription: "Fratelli Pinot Noir brings cherry, rose, clove and silky texture. Pair with tandoori chicken; check city prices on BevOry."
  },
  "fratelli-sangiovese-bianco-3369d37": {
    productName: "Fratelli Sangiovese Bianco", category: "Indian White Wine From Sangiovese Grapes",
    shortOverview: "Sangiovese Bianco is a white wine made from a red grape, with spring blossom and yellow apple rather than red-wine tannin. A creamy finish makes it unusually versatile with Indian starters.",
    craftStory: "Fratelli uses Sangiovese grown in its Maharashtra vineyard programme to make this rare white expression. Gentle pressing limits colour extraction from the red skins; the producer presents it as India's first white Sangiovese.",
    tastingNotes: { nose: "Spring blossom, coconut, bougainvillea and a hint of vanilla.", palate: "Light but creamy, with yellow apple, lemon drop and minerality.", finish: "Medium and buttery, leaving lemon and soft vanilla." },
    servingGuide: { glassware: "Medium-bowl white-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Serve cool with a mildly creamy starter so its floral nose stays visible." },
    foodPairings: ["malai paneer tikka", "tandoori prawns", "rava-fried fish", "chicken malai tikka"],
    whyBuyThis: "A white Sangiovese gives an uncommon grape-and-style story with genuine food appeal.",
    faqs: [{ question: "How can Sangiovese make white wine?", answer: "The juice is pale; limiting contact with the red skins keeps the finished wine white." }, { question: "Is it the same as Sangiovese rosé?", answer: "No. This is a white expression, not Fratelli's pink Master Selection rosé." }],
    metaTitle: "Fratelli Sangiovese Bianco Price, Taste & Review | BevOry", metaDescription: "Fratelli Sangiovese Bianco offers blossom, apple and creamy lemon. Pair with malai paneer; check city prices on BevOry."
  },
  "fratelli-master-select-late-harvest-white-wine-8feeda7": {
    productName: "Fratelli MS Late Harvest", category: "Indian Late-Harvest Chenin Blanc Dessert Wine",
    shortOverview: "Master Selection Late Harvest is a sweet Chenin Blanc with dried fruit, honey and caramel. It is a small-glass dessert wine, not a dry white for spicy mains.",
    craftStory: "Fratelli hand-picks late-ripened Chenin Blanc at its Akluj vineyards for this Master Selection release. Extra time on the vine builds concentrated sugar and a velvety, lingering dessert-wine profile.",
    tastingNotes: { nose: "Dried apricot, honey and caramel.", palate: "Velvety and sweet, with dried fruit, honey and a balancing fresh edge.", finish: "Long, leaving caramel and honeyed fruit." },
    servingGuide: { glassware: "Small dessert-wine glass", idealTemperature: "Chilled (8–10°C)", recommendation: "Pour in small servings after dinner beside a dessert that is not much sweeter than the wine." },
    foodPairings: ["qubani ka meetha", "baked cheesecake", "panna cotta", "blue cheese with walnuts"],
    whyBuyThis: "Late-picked Akluj Chenin gives the Master Selection range a genuinely rich dessert wine.",
    faqs: [{ question: "Is Master Selection Late Harvest dry?", answer: "No. Fratelli describes a rich, sweet dessert wine." }, { question: "Which grape is used?", answer: "The producer identifies Chenin Blanc." }],
    metaTitle: "Fratelli MS Late Harvest Price, Taste & Review | BevOry", metaDescription: "Fratelli MS Late Harvest has dried fruit, honey and caramel. Pair with qubani ka meetha; check city prices on BevOry."
  },
};
